### ISSUE TITLE
[QUESTION] What modifier key for links in the editor?

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#100]
Dear community,

I've got a question. Since the linux distributions that are reserving `Alt+Click` for some window dragging functionality are not as rare as I expected, and additionally, as many people are used to `Cmd/Ctrl+Click`ing on special links (as in Word or LibreOffice), I'm currently split between two options of mitigating the `Alt+Click`-problem for those linux distros:

1. Add a "compatibility" switch to the settings, allowing the affected users to switch from `Alt` as the necessary modifier key to `Ctrl`
2. Generally switch to `Cmd/Ctrl` as the modifier key for following internal and external links, and initiating tag searches

Opinions?

**Comment by samarulmeu** [comment]
Maybe you can consider using `Super+Click` with the `Super` key as explained [here](https://en.m.wikipedia.org/wiki/Super_key_(keyboard_button)).

**Comment by nathanlesage** [comment]
That wouldn't work on Windows machines, because on Windows, pressing the super key opens up Cortana or the Start menu :/

Maybe an option 3:

- Use `Cmd` on macOS
- Use `Super` on Linux distributions
- Use `Ctrl` on Windows distributions

…? But then again we would need some numbers so that we can estimate which key would provide the least friction on each system.

**Comment by samarulmeu** [comment]
I think that your proposal could be a viable option. But I think you need more input from Windows users.
I also use macOS and `Cmd` is ok.

**Comment by nathanlesage** [comment]
Yeah, let's hope some people come around so that this gets started. But I think that after all, I will enable such a switch for the time being so that people like you can actually work with it until we get to a final solution.

**Comment by Shandi97** [comment]
I use both Windows and Linux (ubuntu budgie). Haven't had any problems with alt. The super key could work. But I would prefer consistency across platforms, so maybe ctrl?

**Comment by nathanlesage** [comment]
Yes, consistency would be great. Can you tell me if `ctrl` yields any problems on Windows or Linux? I'll test on macOS and if everything works fine, I'll start implementing it!

**Comment by nathanlesage** [comment]
I had a better idea: I've kept the `Alt`-key, and added the `Ctrl`-key as a second option, so you can use whatever you like! Please share your experiences during the beta phase! :)

**Comment by samarulmeu** [comment]
After testing the new beta release (v1.2.0-beta.1) I think that you've made the right choice. It's perfect and you may close this issue. 
Thank you for your great job!

**Comment by nathanlesage** [comment]
Thank you! I'll leave this issue open for a while just to be sure, but I'll keep the Alt/Ctrl-double-solution :)
