### ISSUE TITLE
It freezes if I type two [ in header

### ISSUE THREAD

**Issue by edusantana** [Zettlr/Zettlr#1000]
## Reproducing

We I try to type two `[` inside header.

![freezes-two-](https://user-images.githubusercontent.com/3603111/86521719-dafae100-be2a-11ea-95b5-bc249be20a3f.gif)

## Platform
 - OS and version: `Fedora release 32` - x64
 - Zettlr Version: 1.7.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
See issue #967, already fixed, patch to be released in a few hours
