### ISSUE TITLE
[BUG] File rename after global search breaks global search

### ISSUE THREAD

**Issue by wheelercj** [Zettlr/Zettlr#1001]
## Description
Renaming a file through Zettlr while search results are being displayed in Zettlr's file window completely breaks Zettlr's global search feature until the application is restarted.

## Reproducing
1. Open Zettlr.
2. Perform a global search with any keyword, tag, file ID, etc.
3. Rename a file using any of Zettlr's five ways to rename a file.
4. Try to perform another global search using any keywords, tags, file IDs, etc.
5. See that either the search will not be performed, or only one file is found even if there should be more results.

## Expected behaviour
Global searches should be possible and should display more than one result.

## Platform
 - OS and version: Windows 10 version 1909
 - Zettlr Version: 1.7.0
 - Screen Resolution: 1368 × 912

## Additional information
Other things that sometimes happen at the same time as this bug:
* Sometimes another tab that is open will suddenly close.
* Sometimes Zettlr's loading symbol will appear and get permanently stuck partway through.

The only way to recover from this bug seems to be restarting the application.

**Comment by emef** [comment]
+1

I have noticed search breaking as well but hadn't realized it had anything to do with renaming (which I do a lot). Repro steps work for me on a fresh restart though as well.

**Comment by wheelercj** [comment]
With Zettlr version 1.7.2, I can no longer reproduce this bug on Windows 10! I don't know if this still happens on Macs.

**Comment by nathanlesage** [comment]
Uh, totally forgot about this issue — sooooo … did I accidentally solve it without knowing? 👀

**Comment by wheelercj** [comment]
Yes, it looks like this has been solved also because a duplicate issue (#1074) has now been closed. Thanks for your hard work making Zettlr amazing!

**Comment by nathanlesage** [comment]
Perfect! :)
