### ISSUE TITLE
Website has obscene CPU usage

### ISSUE THREAD

**Issue by fnorf** [Zettlr/Zettlr#1004]
## Description
Having https://www.zettlr.com/ opened in a browser makes my system's fans spin up and drains the battery. It uses a full CPU core even if I do not interact with it at all.

## Reproducing
Open https://www.zettlr.com/ in a web browser

## Expected behaviour
The site should have neglible or even zero CPU usage once loaded.

## Platform
 - OS and version: Linux
 - Browsers: Chromium, Opera, Firefox

**Comment by nathanlesage** [comment]
Reduced particle amount, instead increased the link distance so it doesn' look too sparse, disabled rendering when tab is invisible, reduced GPU load to ~5 %

**Comment by fnorf** [comment]
Thanks!

It is not deployed yet, correct? Because it still does it.

**Comment by nathanlesage** [comment]
I was moving the server yesterday night, at that point there might've still been wrong DNS-records showing up. Please give the root servers some time to update all records as necessary!

**Comment by fnorf** [comment]
Cheers!
