### ISSUE TITLE
Adding pt-BR dictionary crashes zettlr

### ISSUE THREAD

**Issue by Vitorvlv** [Zettlr/Zettlr#1010]
**Below, please describe what the Bug does in one or two short sentences**
Hello, I followed the steps outlined in here: https://docs.zettlr.com/en/reference/spell-checking/#add-new-dictionaries

When I try to enable the pt dictionary on zettlr settings, it crashes.

**Below describe the steps necessary to reproduce the malicious behaviour** 
Follow the steps in Zettlr docs to add the portuguese dictionary, then enable it on Zettlr.

**Below, please describe what Zettlr should do instead**
If possible it would be nice if it worked, I've seen this warning at the end of the page: 

`The hunspell algorithms implemented in JavaScript are still not as powerful as the main algorithm used by LibreOffice, so it may very well be that some dictionaries simply prove to be too large to be loaded. If Zettlr hangs after loading a dictionary, simply force-quit the app and make sure the dictionary is deselected.`

So maybe the dictionary is too big and it's not possible?

**If helpful, add Screenshots to further narrow down the issue**
Here's a little video of the issue: https://gfycat.com/youngblaringachillestang

## Platform
 - OS and version: latest Manjaro stable
 - Zettlr Version: 1.7.1
 - Screen Resolution: 2560x1080

**Comment by nathanlesage** [comment]
> So maybe the dictionary is too big and it's not possible?

Exactly that is the case; the same unfortunately applies to the Italian dictionaries and others. Please see #1022 for further developments in this regard.

**Comment by Vitorvlv** [comment]
I see, I'll follow that issue then, thank you!
