### ISSUE TITLE
Use H1 titles (#) in the sidebar, similar to YAML title. 

### ISSUE THREAD

**Issue by grst** [Zettlr/Zettlr#1011]
## Description
When using `title` in a YAML header, in the sidebar, the filename is replaced by the title. 
I suggest expanding this behaviour to the first H1 (`#`) header in the document. 

## Proposed Changes
Parse the document for the first H1 header. Or, alternatively, just check if the very first line is a H1 header. 
YAML should take precedence over H1, IMO. 

## Caveats
Can't see any. 

## Additional Information
I believe this is a good idea in order to maximize compatibility with standard markdown. Instead of relying on Zettlr's non-standardized ID parsing, I'd rather name documents by their ID. Instead of relying on non-standardized YAML headers, I'd rather rely on a standardized markdown H1 header.

**Comment by berzhot** [comment]
I would like to have an option to "use first h1 as title" in the preferences menu. This would affect the way it is displayed this information in the sidebar but also in the suggestions list when creating an internal link and if we check the option to add the filename when linking files.

**Comment by nathanlesage** [comment]
Ah, implemented that yesterday, coming in the next release the way @berzhot describes
