### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by makinskn** [Zettlr/Zettlr#1012]
## Description

I can't re-install after 1.7.0 => 1.7.1 update. 

After install, there was message "Can't found Uninstall.exe" once. (But it was already deleted.)
I got error to install and there's only the message "Program Install Cancelled." 
that's all

I tried install several times, but it goes automatically cancelled.

Prior 1.7.0 Program was deleted all so I can't run & install application now

## Reproducing
I don't know how to reproduce. 
Don't know even what's wrong.
Maybe if u delete prior program while install update. 

## Expected behaviour

**Screenshots**
![capt](https://user-images.githubusercontent.com/67904521/86589445-af156200-bfc8-11ea-8b1f-8a07286e7937.PNG)

It says "Program installation is cancelled."

## Platform
 - OS and version:  Windows 10 Pro 1903
 - Zettlr Version: 1.7.0 , 1.7.1 
 - Screen Resolution: 1920 x 1080

## Additional information

English is not my first language , so there's can be some error with my description. 
Also not developer, i can't recognize the cause.
I deleted program and local data too.
But I coudn't find cause yet. 

If there's Zip File with Zettlr.exe (Program file, not for install / develop), Could you upload that too?
Then maybe I can use program for temporary.

I'm Sorry for my issue, and Very Thanks For your Application.

**Comment by nathanlesage** [comment]
I did change the uninstaller's filename, if I'm correct (from "Zettlr.exe" to "Uninstall Zettlr.exe" if I remember it correctly), maybe that has something to do with it?

**Comment by makinskn** [comment]
> I did change the uninstaller's filename, if I'm correct (from "Zettlr.exe" to "Uninstall Zettlr.exe" if I remember it correctly), maybe that has something to do with it?

I never changed any file's name.

**Comment by makinskn** [comment]
I installed at other pc and move files from that one now. So I can use program now. Thanks.
