### ISSUE TITLE
File list's tag tooltip doesn't display properly

### ISSUE THREAD

**Issue by Shandi97** [Zettlr/Zettlr#1013]
## Description
In the file list when hovered over, tags that are not there are shown, sometimes they are clipping over each other, sometimes they are duplicated other times they fail to display at all.

## Reproducing
On initial opening of the app the tags appear to be working correctly, however after some time passes they will get messed up.
It also appears to occur if one switches directories. If I switch to another directory and then go back and check the tags they start displaying this behaviour.

## Expected behaviour
The tooltip should display only the tags that are actually there. It shouldn't seemingly try display multiple tags in the same place thus resulting in clipping or fail to display at all.

**Screenshots**
![tag tooltip issue](https://i.imgur.com/60x9wbt.gif)

## Platform
 - OS and version: Windows 10 1903, Pop_Os 20.04
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Did you happen to remove some tags prior to the screencast? There may be an issue with Zettlr not removing tags from a file afterwards. Possibly.

**Comment by Shandi97** [comment]
> Did you happen to remove some tags prior to the screencast? There may be an issue with Zettlr not removing tags from a file afterwards. Possibly.

I didn't, certainly not in that session. And I am pretty sure I've never had those tags (aside from "reading") in that file. I did do some tag removal recently but that issue was already occurring at the time.

**Comment by nathanlesage** [comment]
Is this still an issue in the 1.8 alpha?

**Comment by marcinsmialek** [comment]
Unfortunately, it's still in 1.8.0.-alpha.2

When I browse the bundled tutorial, it's fine. But when I then switch to my other opened folder, where there's a note with a "classic" hashtag, it shows ones from the tutorial
![image](https://user-images.githubusercontent.com/16687607/95480839-a5ffac80-098c-11eb-87c0-c8cab9ccbadf.png)

After restart, it shows only the correct hash tag. But when I start clicking the tutorial notes, and then go back to my note, it shows more again.
When I added yaml-style tags to my note, saved, and removed them, it looked like this:
![image](https://user-images.githubusercontent.com/16687607/95481248-14dd0580-098d-11eb-81fd-051c407f4ebe.png)

2 tooltips at once?

**Comment by bit-hug** [comment]
Just confirming this on macOS 10.13.6 and Zettlr 1.7.5. The erroneous tooltips seem to be from other files.

**Comment by nathanlesage** [comment]
I think I found the issue; if it occurs in the next release (so I think alpha.3 or the first beta)
