### ISSUE TITLE
[ENHANCEMENT] Sort by note title in file list

### ISSUE THREAD

**Issue by tygorda** [Zettlr/Zettlr#1014]
## Description

Now that Zettlr can display the note titles (YAML `title` field) in the file list, it would be incredibly convenient to be able to *sort* by them as well. 

## Proposed changes

Allow users to sort notes by YAML `title` field, already displayed in the file list.

## Caveats

I cannot think of any.

## Additional Information

My workflow is to keep the filenames as the IDs (so the links will still work in other apps), and sorting by filenames or date created means that my titles are completely mixed up.

Sorting by title would also allow one to effectively "pin notes" ([#226](https://github.com/Zettlr/Zettlr/issues/226)) using special characters at the start of the `title`, without needing to use them in the file name.

**Comment by nathanlesage** [comment]
Already implemented, will come with 1.8; totally forgot about this issue!
