### ISSUE TITLE
Can't create new files or folders

### ISSUE THREAD

**Issue by randomluck17** [Zettlr/Zettlr#1016]
Unfortunately I'm not able to create new files or folders in Zettlr. The buttons on the upper left do nothing at all.

## Platform
 - OS and version: Windows 10 64 bit
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920x1200

**Comment by nathanlesage** [comment]
Do you have (a) any directory open in the app, and (b) selected at least one directory in the tree view?

**Comment by randomluck17** [comment]
I understand the issue now. When you don't have a folder connected for some reason the application doesn't allow you to create a new folder in a specific directory on your computer but you have to open an existing directory and there you can create other folders and files.

So in any case someone encounters the same issue: connect to an existing folder, create other folders and files.

**Comment by nathanlesage** [comment]
> the application doesn't allow you to create a new folder in a specific directory on your computer 

This can indeed happen sometimes. Windows and macOS both give you the ability to create new folders within the file-selection dialog, but as far as I know there are linux distributions that do not allow that. Zettlr piggybacks on the operating system for this functionality, so this might be the case.

I will add a warning to the corresponding documentation page.
