### ISSUE TITLE
[ENHANCEMENT] Right to left (RTL) in Exported files

### ISSUE THREAD

**Issue by gotoayman** [Zettlr/Zettlr#1017]
It was great that Rtl has been enabled in the latest release of the program. However it still need some improvements:
1. Enabling the rtl in the exported files. currently all files exported ltr even if written Rtl in the program.
2. Enabling positioning the sidebar to the right side of the screen with the text shown rtl too.

Thanks

**Comment by nathanlesage** [comment]
> Enabling the rtl in the exported files. currently all files exported ltr even if written Rtl in the program.

This would be dependent on the way Pandoc handles RTL-stuff; would you mind searching for something regarding this? This would be increadibly helpful!

> Enabling positioning the sidebar to the right side of the screen with the text shown rtl too.

You mean completely taking the sidebar to the right side, e.g. completely exchanging the GUI? If so, I see your point, but it will take a lot of time to do correctly …

**Comment by gotoayman** [comment]
yes i meant completely moving the sidebar to the right or having the option to position it from right to left.
thank you for your response

**Comment by nathanlesage** [comment]
Can be an option, yes.
