### ISSUE TITLE
Upon clicking link, make new note visible in adjacent, new column?

### ISSUE THREAD

**Issue by rameshuconn** [Zettlr/Zettlr#1019]
## Description
Andy Matuschak's blog (https://notes.andymatuschak.org/About_these_notes) has an interesting and (in my view) very useful feature: In note 1, when you click on a link to note 2, note 2 opens in an adjacent column on the same page, so now you see note 1 and note 2 side by side. Next, in note 2 when you click on the link to note 3, note 3 opens in an adjacent column, so now you see note 1, note 2, and note 3 side by side. This goes on for note 4, note 5, etc. - without limit. A horizontal scrollbar on the bottom lets you move from the left-most to right-most notes, when there are lots of notes. 

This helps because when I am reading a note, I want to see the context - the notes preceding and succeeding this note. 

When you have note 1 -> note 2 -> note 3 -> note 4, and now you click on the link to note 21 in note 2, then now your visible note sequence is note 1 -> note 2 -> note 21 (note 3 and note 4 vanish). 

## Additional Information
This feature might satisfy some of the visual feel for the relationships among notes, that is afforded by Roam's graph overview feature.

**Comment by nathanlesage** [comment]
I know that concept, and it does certainly have a cool appeal to it, but it won't come to Zettlr. Zettlr is primarly a tool to write, not to only take notes with. What will come is split-pane (e.g. two or more editors side by side), but there is no ETA right now.

**Comment by cloudhan** [comment]
Just to mention, Andy Matuschak's note website is a pure joy to browse.
