### ISSUE TITLE
frac displays incorrectly

### ISSUE THREAD

**Issue by Wieke** [Zettlr/Zettlr#102]
## Description

For some reason the \frac{}{} command in latex doesn't render properly, the horizontal line separating the numerator and denominator is missing.

## Reproducing

Just use the frac in a math environment like this for example:

```
$$
a = \frac{b}{c}
$$
```

## Expected behaviour

I was expecting a horizontal line to appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/6737186/52738702-82c20580-2fcf-11e9-9656-d2df3ec5316b.png)

## Platform
 - OS: Archlinux 
 - OS Version N/A rolling distro (kernel version 4.20.6-arch1-1-ARCH)
 - Zettlr Version 1.1.0
 - Screen Resolution 1920x1080

## Additional information

Found another math thing that renders incorrectly:

![image](https://user-images.githubusercontent.com/6737186/52741459-abe59480-2fd5-11e9-9015-0bd411826a21.png)

**Comment by nathanlesage** [comment]
Thanks for the hint! I have to be honest — I didn't pay very much attention to the formula rendering process, because I'm not using it myself, but I'll see into it!

**Comment by Wieke** [comment]
Heh, I suspected as much. There are multiple bugs, inconveniences and a missing feature or two related to doing math/rendering equations. Which is a shame because I quite like the editor otherwise but I tend to do a lot of math. How open are you to contributions? Cause I have half a mind to try fix these issues myself.

**Comment by nathanlesage** [comment]
PRs are always welcome! You can find all code pertaining to the KaTeX-rendering in [this file](https://github.com/Zettlr/Zettlr/blob/master/source/renderer/assets/codemirror/zettlr-plugin-render-math.js). As you can see there's not much usage of the KaTeX-library at the moment:

https://github.com/Zettlr/Zettlr/blob/1cd9b6a4ba137eaae9c50449f095307395799d42/source/renderer/assets/codemirror/zettlr-plugin-render-math.js#L110-L112

**Comment by nathanlesage** [comment]
So the frac is showing up perfectly now, but strangely, the unequal-bug persists:

![image](https://user-images.githubusercontent.com/17251683/52855680-6da9bb80-3122-11e9-8f78-85b505ae231b.png)

**Comment by Wieke** [comment]
I'm pretty sure that's [this known katex bug](https://github.com/KaTeX/KaTeX/issues/1842) since electron is based on chromium.

**Comment by nathanlesage** [comment]
Ah, so at least help is underway! As soon as the new KaTeX is released I'll see to implementing the fixed fonts!
