### ISSUE TITLE
(Mac) Scrolling, then pressing "cmd" causes text to zoom

### ISSUE THREAD

**Issue by adrn** [Zettlr/Zettlr#1021]
## Description

Here is how I noticed this:
* I had just reset the zoom in my Zettlr window
* I scrolled down to the bottom of a note
* *After* scrolling, I pressed Cmd (I was about to switch windows with Cmd-tab)
* The text changed size, as if I had been holding down Cmd and scrolling

## Reproducing

Scroll down in a document, then press the Cmd key.

## Expected behaviour

No text zooming if I'm not holding Cmd.

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/583379/86826909-55ac4200-c05f-11ea-9afc-104af2f37f73.gif)

## Platform
 - OS and version: Mac OS 10.15.5
 - Zettlr Version: 1.7.1
 - Screen Resolution: retina display?

**Comment by nathanlesage** [comment]
If you scrolled with the trackpad, there is this slight delay in scrolling where you lift up your fingers from the trackpad but macOS will still emit scroll events. If you in that case happen to press `Cmd`, Zettlr will regard this as a scrolling-event.

A good "habit" in this regard is to always "force-stop" your scroll-events by tapping with both "scroll-fingers" before perfoming an additional action to immediately stop the scrolling!
