### ISSUE TITLE
[DEVELOP] New Dictionary/Spellchecking Mechanism

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1022]
Hello everyone,

as the app's userbase keeps growing, naturally more people want to install dictionaries that as of now prove to be too large for the dictionary provider we currently use, so we need to switch in due time. If someone wants to research what is best concerning spell checking (important: Needs to integrate with CodeMirror, otherwise it won't work), this would be great!

***

EDIT: Some more information for those who may be unfamiliar with these problems:

- Most dictionaries don't work good (e.g. the German spellchecker fails at almost any word)
- Some even crash the app (e.g. the Portuguese and Italian ones)
- The current library adds considerable lag to the application (freezes for 1–2 seconds) on boot
- Neither their maintainers nor we have any time on our hands to actually fix the algorithm (see [this issue](https://github.com/wooorm/nspell/issues/11))

Henceforth: We need something – anything better. Since Zettlr runs on a CI since a few months, we should even be able to use C++-bindings from native node-modules. Just as an indication …

**Comment by ArcticSnow** [comment]
Would it be possible to choose the dictionnary/language per page? For instance when writing in multiple languages over Zettlr, it'd be really nice to choose per file which dictionnary Zettlr should refer too, rather than being done at the App level.
Thanks for the great software!

**Comment by jzeneto** [comment]
Adding in @ArcticSnow's suggestion, file's language could be defined via YAML metadata. [Pandoc uses `lang` to that](https://pandoc.org/MANUAL.html#language-variables), as it's passed to some formats. It's a [BCP 47](https://tools.ietf.org/html/bcp47) code, like `en`, `en-GB`, `pt-BR` etc. I suggest Zettlr should follow Pandoc's way, via `lang` metadata.

**Comment by nathanlesage** [comment]
Also some good ideas!

**Comment by nathanlesage** [comment]
Superseded by some of the newer issues, so closing this one

**Comment by Enrico68** [comment]
will be any chance that Italian dictionary would ever be working in the near future? I am just waiting that this functionality will be added in order to use this great app
