### ISSUE TITLE
RSS feed missing links to articles

### ISSUE THREAD

**Issue by carregal** [Zettlr/Zettlr#1025]
## Description
The RSS feed (https://www.zettlr.com/feed) apparently does not include the links to each article in the feed

## Reproducing
Open the RSS feed in any RSS Client and try to open any article in the feed.

## Expected behaviour
The link tag should include the URL of the article

**Screenshots**

## Platform
 - OS and version: any
 - Zettlr Version: N/A
 - Screen Resolution: N/A

## Additional information
It may also be interesting to change the RSS feed title from simply "Feed" to something like "Zettlr Blog" or "Zettlr Feed"

**Comment by nathanlesage** [comment]
Whoops, @ploum already reminded me of that; I just fixed it! Should work now, if not please comment!
