### ISSUE TITLE
When readability mode is on and I click a sentence it enlarges yaml frontmatter variable

### ISSUE THREAD

**Issue by lsolesen** [Zettlr/Zettlr#1026]
## Reproducing

1. Have a file with YAML-frontmatter.
2. Toggle Readability-mode
3. Click on a sentence
4. Watch the last key in the YAML-frontmatter enlarge (get bigger)

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.1
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Can't reproduce this locally, do you have a YAML frontmatter at hand that I might test out?

**Comment by lsolesen** [comment]
Thanks for looking into this. I happens e.g. if editing this, but basically it happens on all files I tried with similar frontmatter from that repository.

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/_posts/2020-07-07-mavefedt.md

**Comment by nathanlesage** [comment]
That was refreshingly easy to solve; thanks for sharing the frontmatter!
