### ISSUE TITLE
Link doesn't always open in new tab

### ISSUE THREAD

**Issue by marktermaat** [Zettlr/Zettlr#1028]
## Description
When clicking on a link with CMD+click, sometimes it opens in a new tab, and sometimes it doesn't.

## Reproducing
Unknown, I haven't been able to figure out when it happens, and when it doesn't. Of course, this might mean it's intended behaviour in different contexts, and I just haven't figured out what this is exactly.

## Expected behaviour
I expect it to either always open a link in a new tab, or always open in the same tab. Perhaps two different ways to click? When it opens in the same tab, I would also love to have a shortcut to go to the previous note.

## Platform
 - OS and version: MacOS 10.14.5
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920:1200

**Comment by nathanlesage** [comment]
It's called tab transiency: https://docs.zettlr.com/en/core/tabs/

What I will be adding soon is a way to `Cmd/Ctrl` or Middle-mouse-click files in order to make sure they always open in a new tab instead.

**Comment by marktermaat** [comment]
Ah, that explains a lot. Awesome, thanks for the heads-up. :)
