### ISSUE TITLE
[ENHANCEMENT] built-in option to export to PowerPoint 

### ISSUE THREAD

**Issue by drmdshahid** [Zettlr/Zettlr#1030]
## Description
Zettlr readily exports to a handful of formats including revealjs presentation.
As it uses Pandoc, It would be nice to have an option to export to MS powerpoint format.
I presently do the conversion of zettlr produced markdown to ppt using command line pandoc options.

## Proposed Changes
Such pandoc option like --reference-doc can be provided in preference>Advanced options.

## Caveats
None, as i can see.

## Additional Information
...

**Comment by nathanlesage** [comment]
Added here: #1005
