### ISSUE TITLE
[FEATURE] Add Check/Uncheck Task List Item (Toggle Checkbox) Keyboard Shortcut

### ISSUE THREAD

**Issue by AnthonyShipman** [Zettlr/Zettlr#1031]
Add a check/uncheck task list item keyboard shortcut similar to functionality in VsCode Markdown All In One package: https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts-1 

ALT + C keyboard shortcut is recommended (or make it configurable?)

## Example Workflow
When the cursor is on a single line or text from a single line is selected, the checkbox at the beginning of the line should be toggled. 

Checkboxes should be toggled for all selected lines if multiple lines of text are selected.

**Comment by nathanlesage** [comment]
I don't see any great benefits over just checking the checkbox in comparision with the significant costs of implementing a search-and-replace algorithm for this specific usecase.

**Comment by AnthonyShipman** [comment]
Not a huge benefit, but a small quality-of-life improvement similar to other "toggle" shortcuts that are already built-in like "Insert Task List":
- Keyboard shortcut allows you to keep your fingers on the keyboard (faster, more efficient)
- Keyboard shortcut would allow for easily checking multiple boxes at once

Ironically, the VsCode Markdown All In One package doesn't have the "Insert Task List feature", but does support the "toggle checkbox" feature. Zettlr, of course, is the reverse. 

Having both in this one app would be helpful for those who use tasks lists heavily.

**Comment by nathanlesage** [comment]
Well, if someone wants to implement such a codemirror plugin, it's up for grabs!

**Comment by maxanthem** [comment]
# Smarter keyboard shortcut for checkboxes

Hello,  
I would like to re-open this issue, as I often miss this feature in daily use.

I don’t have the capacity to implement it myself, but I’d like to propose a concrete and incremental behavior for `Ctrl+T` that stays backward-compatible while being more context-aware.

## Current behavior

When `Ctrl + T` (or OS equivalent) is pressed, Zettlr blindly inserts `- [ ] ` at the beginning of the current line or each selected line.

## Suggested behavior (context-aware)

When `Ctrl + T` is pressed, apply different behaviors depending on context.

### 1. Multi-line selection
For now, keep the **current behavior**:
- Insert `- [ ] ` at the beginning of each selected line.

(Optionally, this could later evolve so each line is treated independently using the rules below.)

### 2. Single line or no selection (cursor only)

#### a. Line is an unordered list item (but not a checkbox)
If the line starts with:
- any indentation (spaces or tabs),
- followed by a bullet marker `-`, `+`, or `*`,
- followed by exactly one space,
- and **not** followed by `[ ] ` or `[x] `,

then:
- convert it into an **unchecked checkbox**
- preserve indentation and bullet marker.

Example:
```markdown
    - item
```

→

```markdown
    - [ ] item
```

#### b. Line is an unchecked checkbox
Preserve indentation and toggle it to **checked**.

```markdown
    - [ ] item
```

→

```markdown
    - [x] item
```

#### c. Line is a checked checkbox
Preserve indentation and toggle it back to **unchecked**.

```markdown
    - [x] item
```

→

```markdown
    - [ ] item
```

#### d. Line is part of a Markdown table
Do nothing (could be extended later).

#### e. Any other line
Insert a checkbox while preserving indentation.

```markdown
    some text
```

→

```markdown
    - [ ] some text
```

## Rationale

- Matches user expectations from editors like VS Code, Obsidian, Typora.
- Avoids destructive or surprising behavior.
- Preserves indentation and list structure.
- Keeps multi-line handling simple for now.
- Provides a clear path for future refinement.

**Comment by nathanlesage** [comment]
This issue is super old and I won't reopen it. Please open a new issue, copying your comment in there. Thank you.
