### ISSUE TITLE
A line with a single `=` inside of a math enviroment (`$$`) is incorrectly parsed as a heading

### ISSUE THREAD

**Issue by fvollmer** [Zettlr/Zettlr#1032]
## Description
A line with a single `=` inside a math enviroment (`$$`) is incorrectly parsed as a heading.

## Reproducing
1. Open Zettlr
2. Paste the following code:
    ```
    $$
    f(x)
    =
    1+2
    $$
    ```

## Expected behaviour
Do not interpret the `=` inside of an equation as a heading. The code view and the rendered equation have wrong font sizes.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16699443/87031217-13137280-c1e3-11ea-8a9c-a11a0565ee9b.png)
![grafik](https://user-images.githubusercontent.com/16699443/87031260-26bed900-c1e3-11ea-998e-8a1ad648c20d.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Fixed it. Furthermore, we now have math syntax highlighting, as this was easier to implement for this fix!
