### ISSUE TITLE
[FEATURE] Back-button in transient tabs

### ISSUE THREAD

**Issue by marktermaat** [Zettlr/Zettlr#1034]
## Description
Issue #367 suggested a back-button, which was closed in favour of the new tabs. However, I would love to have a back-button available while clicking through notes with transient tabs.

## Example Workflow
When clicking on links while in a transient tab, the new note will open in the same tab. Pressing the back button or the back hotkey would bring you back to the previous note. This is especially useful while browsing through notes.

## Caveats
None that I can think of.

## Additional Information
We'd have to think about how this would behave in a note that has just been opened in a new tab. Would it just not work, because the tab doesn't have a previous note?

**Comment by nathanlesage** [comment]
Oh god …

I can't think of anything to make this non-shitty with regards of user interface stuff. A tab represents a document, and not a history of documents.

BUT what is still in the making are keyboard shortcuts to prevent transient tabs, which might be what you are looking for.

I'm going to close this issue therefore, but @tobiasdiez if you somehow see how this might work out, feel free to comment

**Comment by marktermaat** [comment]
Heh, I never said it was easy, just that it would be a nice enhancement :P
But I understand that it isn't worth it if it goes so hard against concepts (like a tab is one document).
