### ISSUE TITLE
Zettler (version 1.7.1) consumes a bit much CPU

### ISSUE THREAD

**Issue by Wiesensohle** [Zettlr/Zettlr#1035]
When I load a file, Zettlr on my laptop uses about 10% CPU without me doing anything. This shortens the runtime of my laptop and after a few minutes the fan starts up.

I would not like to use it mobile under these circumstances.

Lg, Horst (translated with Deepl)

**Comment by nathanlesage** [comment]
"A bit much" is unfortunately nothing actionable, but we are aware of the performance bottlenecks and keep that in mind.
