### ISSUE TITLE
Zoom setting only changes text font size, not images in content

### ISSUE THREAD

**Issue by 13rac1** [Zettlr/Zettlr#1036]
## Description

The Zoom In/Out feature only changes the size of the text in the content area, but not the size of anything else.

FWIW I find the text size at the default zoom far too large and reduce the zoom by three levels before there is a comfortable/useful amount of text on screen.

## Reproducing

1. Insert an image
2. Zoom Out

## Expected behaviour

Images should scale at the same time as the text

or

The entire application should scale and default font size should be a menu option. (Perhaps a better option)

**Screenshots**

### Default Zoom
![image](https://user-images.githubusercontent.com/195061/87077208-a5157e00-c1d7-11ea-943b-f4e8f971240b.png)

### Three levels out
![image](https://user-images.githubusercontent.com/195061/87077271-bc546b80-c1d7-11ea-9e36-bd1d2a9e332d.png)

## Platform
 - OS and version: Linux - Mint
 - Zettlr Version: 1.7.1
 - Screen Resolution: 2560 x 1440

**Comment by 13rac1** [comment]
The menu item `File->Custom CSS` helps as a workaround to make everything sized a bit better:
```css
body {
  zoom: 90%;
}

body #editor {
  font-size: 0.9em;
}

img {
  zoom: 50%;
}
```

**Comment by nathanlesage** [comment]
Well, the `zoom`-function only affects the font size as of now. But as we're trying to improve the UI either way, it's a good thing to include.

**Comment by 13rac1** [comment]
@stale This is still an active issue.

**Comment by 13rac1** [comment]
@Stale This is still an active issue.
