### ISSUE TITLE
Can't Even Get Started: Won't Open New Files

### ISSUE THREAD

**Issue by Asterix05** [Zettlr/Zettlr#1037]
Downloaded Zettlr & went through the tutorial, then clicked "close directory". Tried to create a new directory or file (both through Ctrl+Shift+N and via menu bar), and nothing happens.

See above

A new directory or file should open, presumably?

![zettlr](https://user-images.githubusercontent.com/68080945/87083236-33afec80-c224-11ea-8a19-76fc5f3d6726.jpg)

## Platform
 - OS and version: Win 10
 - Zettlr Version: 1.7.1
 - Screen Resolution:

Is this a bug, or am I just missing something really obvious? Even if I reopen the tutorial, I can't create a new directory or folder from there. Can't even get started with this thing!

**Comment by Asterix05** [comment]
Ah, well it looks like you have to create a new, empty folder in Windows File Explorer, then open *that* in Zettlr in order to start a new project.
This is a bit weird to my mind. Not sure why File>New in Zettlr can't do what it says on the tin?

**Comment by nathanlesage** [comment]
`File -> New` means new file, not new directory :D 

Further, you can create new directories from Windows explorer. If you click the "No directory opened" pane you will get to the `File -> Open`-dialog, which opens it. Feel free to instead amend the tutorial to mention this fact in a way that's transparent to the user: https://github.com/Zettlr/Zettlr/tree/develop/source/main/assets/tutorial; I'll gladly merge this PR.
