### ISSUE TITLE
[ENHANCEMENT] Remember editor zoom level

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1038]
## Description
Currently, custom zoom levels in the editor are not preserved when launching Zettlr next time. An option to save the current zoom level could save us some time so that we don't have to readjust the zoom whenever launching Zettlr.

## Proposed Changes
Add a toggle called "Remember editor zoom level" (or similar) to the "Editor" tab of the preferences.
When enabled, the zoom level is saved when Zettlr is closed. The next time Zettlr is launched, the saved zoom level is applied to the editor zoom.

## Caveats
Probably none.

**Comment by nathanlesage** [comment]
Closing in favor of #1039
