### ISSUE TITLE
[FEATURE] File encryption

### ISSUE THREAD

**Issue by joshsweaney** [Zettlr/Zettlr#1040]
## Description
Some Markdown editors (e.g. Joplin) support encryption. I think this is an important feature for all software to support in some capacity where appropriate, and would preference using software that supports it.

This feature suggestion is for adding some kind of file encryption directly into Zettlr.

## Example Workflow
You specify a password in Zettlr, which is then used to derive AES keys for encrypting files. Individual files can be encrypted separately, or you can opt for all files to be encrypted with the same key.

## Caveats
There are no caveats, but it would be important to have the ability to encrypt existing files. So, if you specify a key, Zettlr will ask if you want to encrypt all your current files.

**Comment by grst** [comment]
Why not just use [EncFS](https://wiki.archlinux.org/index.php/EncFS)? 
There's even a [windows port](https://encfsmp.sourceforge.io/). 

If encryption will be part of zettlr, it will always be somewhat specific to zettlr, which is against its philosophy of being compatible with whatever other markdown editors.

**Comment by nathanlesage** [comment]
What @grst says; there are several reasons against this:

1. Zettlr only uses plain text files, and there are methods to create containers for encryption/unencryption, where you could simply load in the unencrypted one into Zettlr.
2. You'd completely dependent on the cryptographic implementation of Zettlr (add one small deviation and your files are vendor-locked in, this time for real, and this is not a risk I am willing to take)
3. **Rule number 1: Never do crypto stuff yourself, if there are other specialized projects to do so. You are likely going to add insecurities.** (omg, googling this unearthed a bunch of weird "How to become a blockchain coder with crypto"-articles, I think humanity is lost)
