### ISSUE TITLE
YAML-frontmatter delimiters conflict with default list of AutoCorrect rules

### ISSUE THREAD

**Issue by srikumarks** [Zettlr/Zettlr#1041]
## Description

Starting off a new document by manually typing in the YAML frontmatter results in the frontmatter not being closed correctly. Copy-pasting the delimiters works correctly though.

## Reproducing

Zettlr v1.7.1

1. Create a new blank document.
2. Type the following at the top

```
---
title: YAML frontmatter bug
---
```

3. Make sure you put the closing delimiter by hand rather than by copy-pasting the opening delimiter.

Notice that the closing delimiter gets autocorrected to a long dash and subsequent parts of the document don't get treated as Markdown.

## Expected behaviour

Options

1.  Remove default AutoCorrect rule that corrects "---" (triple hyphen) to a long dash.
2. Ignore AutoCorrect rule for delimiters when in YAML frontmatter

## Platform
 - OS and version: MacOSX 10.14.6
 - Zettlr Version: 1.7.1

**Comment by UpsettingBoy** [comment]
As v1.7.5, when AutoCorrect is in Word style, this issue still exists, replacing both the opening and closing YAML delimiter.

**Comment by nathanlesage** [comment]
@UpsettingBoy Please make sure to test the 1.8.0-betas once they're released, and comment again here if the issue persists!
