### ISSUE TITLE
The spellcheck in Germany is suck, cannot recognize nearly every verb. 

### ISSUE THREAD

**Issue by TangdizhiH** [Zettlr/Zettlr#1042]
## Description
Hello, dear developer of Zettlr
I want the spellcheck functionality of Germany (maybe other languages have the same issue as well) to be finetuned. For me I'm a foreigner who have learnt Germany and is heavily depended on the spellcheck when I'm using Zettlr to do my dictation. However, the spellcheck seems to be a mess, even the most üblich verb like "macht" "verdeutlichen""wissen""sprechen" are not to be found in the dictionary, the red wave line appears every time I typed a verb in, at the beginning I tried to add that verb into the dictionary manually, however, it seems to be an endless hole, my OCD is 😆

Is that  just the badness of the dictionary, I don't know whether spellcheck would be frequently used for native speaker, can we finetune is issue? That is all my request, thank you my dear developer! I appreciate your work to make such a remarkable editor for all of us.

**Comment by nathanlesage** [comment]
It's not the problem of the dictionary (as the hunspell-dictionaries are actually quite good), but rather of the algorithm. We've had a conversation with their maintainer but neither they nor we have any time to actually fix these problems.

See it this way: At least the German dictionary loads, unlike the Italian, which crashes the app …

Please go here for more information on progress --> https://github.com/Zettlr/Zettlr/issues/1022
