### ISSUE TITLE
Chinese heading display as square

### ISSUE THREAD

**Issue by Jasonwi** [Zettlr/Zettlr#1043]
## Expected behaviour
test.md
```
# 这是一个测试

blah blah blah

# This is a test

formula like this 公式如下

$$
e=mc^2
$$

```
export PDF as below
![Snipaste_2020-07-10_22-51-26](https://user-images.githubusercontent.com/59698185/87168406-05eca580-c301-11ea-85d4-acf4536850f6.png)
Text display normal, title display garbled code

## Platform
 - OS and version: Windows10 1909
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920x1080 125% scale
- pandoc version: 2.2.3.2

## Additional information
As #225 set PDF font `Source Han Serif SC`

Have another configure at advanced use external template.latex file?
I try to set 
```
pandoc "$infile$" -f markdown $outflag$ $toc$ $tocdepth$ $citeproc$ $standalone$ --pdf-engine=xelatex --template=D:\export.latex --mathjax -o "$outfile$"
```
export.latex
https://gist.github.com/Jasonwi/ff624e6d479ef6e0f3b17504e6aecd3a
failed and need more changes
![image](https://user-images.githubusercontent.com/59698185/87170146-8c09eb80-c303-11ea-949f-11e1ccd34efb.png)

**Comment by nathanlesage** [comment]
Hey, the selected font likely does not include Chinese glyphs. You need to select a font [in your PDF-preferences](https://docs.zettlr.com/en/reference/settings/#pdf-preferences) which is a) installed on your computer and b) includes chinese glyphs (there should be some standard Windows-fonts for this!)

**Comment by Jasonwi** [comment]
It's weird, as the screenshot shows

![Snipaste_2020-07-11_07-40-47](https://user-images.githubusercontent.com/59698185/87210937-f2b1f800-c349-11ea-8eb6-97e2dc67caf6.png)

red area shows normal but blue area shows abnormal
I also change the font like STSong also have same situation

![image](https://user-images.githubusercontent.com/59698185/87211108-85529700-c34a-11ea-8f53-b5c9d34ed409.png)

**Comment by Jasonwi** [comment]
@nathanlesage I find two solution 
- customize your tex template and use it through FILE--PDF Preference--metadata--Custom TeX template
- set main font and secondary font as `Source Han Serif SC`  `Noto Sans SC`
![image](https://user-images.githubusercontent.com/59698185/87211912-7a016a80-c34e-11ea-804c-7c67609fc19b.png)

**Comment by nathanlesage** [comment]
> It's weird, as the screenshot shows

No, because there are two fonts, and every font needs to contain said glyphs.

> set main font and secondary font as `Source Han Serif SC` `Noto Sans SC`

This was exactly what I tried to tell you 😄

**Comment by Jasonwi** [comment]
@nathanlesage got u! very nice 👍
