### ISSUE TITLE
[ENHANCEMENT] Folding Headings

### ISSUE THREAD

**Issue by ecvgit** [Zettlr/Zettlr#1044]
## Description
It would be great if there is a way to fold the headlines. Similar to https://orgmode.org/manual/Global-and-local-cycling.html#Global-and-local-cycling

**Comment by nathanlesage** [comment]
Folding headings is already included and supported. You can either fold headings by clicking on the small arrows left to the headings, or by using the shortcuts (which don't work on all keyboard layouts) `Ctrl+Shift+[` and `Ctrl+Shift+]`.

**Comment by ecvgit** [comment]
Neither Cmd+Shift+[ or Ctrl+Shift+J seems to work in Mac. Clicking the twisty works though.

Also, what I was requesting is slightly different. I wanted a way to fold all the headings with one shortcut key.

**Comment by nathanlesage** [comment]
> Neither Cmd+Shift+[ or Ctrl+Shift+J seems to work in Mac

Doesn't work with all keyboard layouts, I have German QWERTZ and it also doesn't work here. Therefore please wait until we have custom shortcut support (it's already in the making)

> I wanted a way to fold all the headings with one shortcut key.

Concerning fold all: This sounds like something I'd like to implement AFTER the custom keymaps, as I think it's more specific. After custom shortcuts are there, please open another issue (and please make the title more precise, e.g. "Fold all headings at once"
