### ISSUE TITLE
Drag and drop a sidebar note into the active one creates an internal link

### ISSUE THREAD

**Issue by berzhot** [Zettlr/Zettlr#1047]
## Description
When you're on the active note screen, dragging and dropping a note from the sidebar to the active note screen creates an internal link to that sidebar note

## Proposed Changes
Excuse my total ignorance about programming. The concepts I'm going to use are probably misused: Dragging is associated with getting the ID of the note and keep it in buffer. Dropping action releases the buffer information and inserts the ID as an internal link.

## Caveats
Maybe the same behaviour with the new top tabs

**Comment by nathanlesage** [comment]
… umm, that's already implemented, if I'm not mistaken?

**Comment by canpolat** [comment]
Yes, I just tested. It works (on Windows).

**Comment by berzhot** [comment]
I have just tried on Zettlr 1.7.1 on Windows 10 and doesn't work 
![Drag and drop](https://user-images.githubusercontent.com/8502544/87229892-47865a80-c3ac-11ea-8c65-0bda89010eb6.gif)

**Comment by canpolat** [comment]
I'm also on 1.7.1 (and Windows 10). Nevermind the position of the cursor, the screen capture tool records it at the wrong location. I actually drag the note.

![2020-07-11_19-41-53](https://user-images.githubusercontent.com/459891/87230203-9c2ad500-c3ae-11ea-9a8c-f2aad2586e27.gif)

But anyway... You obviously can reproduce the problem. I was wondering if you would get a different behavior if you clicked on the directory name (`Zettlr`) and dragged the note from that view (instead of the current directory view)? (I actually don't see any of my files under the Direcory view)

**Comment by berzhot** [comment]
Sorry. I don't understand. I just have one directory named "Zettlr", wich I create in my documents folder. I can't create or view a file if I don't have selected this directory in the sidebar. There is no other way to see the notes. Also I can't create a new file or a new directory from the menu. Maybe that's the problem? 
![Zettlr 2020-07-11 20-57-04](https://user-images.githubusercontent.com/8502544/87231672-65a68780-c3b9-11ea-9cbe-2b96aa690a22.gif)

**Comment by berzhot** [comment]
It works different when dragging than when creating the link. First one duplicates ID and adds the title and the second one just adds the title as expected.
![Zettlr Link creation Different Behaviour](https://user-images.githubusercontent.com/8502544/87232297-0bf48c00-c3be-11ea-8b33-926e3b7f25aa.gif)

**Comment by canpolat** [comment]
Can confirm. In Combined sidebar mode it does not work for me either. I find the combined mode a bit confusing, myself... So, perhaps the developers could say if this is intended behavior or not. But, until then, if you don't have a flat folder structure, I can recommend the thin mode.

**Comment by berzhot** [comment]
Yes, thin mode works great for me too.

**Comment by shanvrolijk** [comment]
i use the latest zettlr and windows 10. everything works perfectly just fine

**Comment by canpolat** [comment]
> i use the latest zettlr and windows 10. everything works perfectly just fine

If it works for you in the Combined mode, then this is probably not a choice by the developers and most likely a bug...

**Comment by berzhot** [comment]
> > i use the latest zettlr and windows 10. everything works perfectly just fine
> 
> If it works for you in the Combined mode, then this is probably not a choice by the developers and most likely a bug...

I don't know if it is intentional or not but it would be strange to keep the same behaviour in just 2 of 3 sidebar options. It wouldn't be consistent

**Comment by nathanlesage** [comment]
> In Combined sidebar mode it does not work for me either.

This is most likely the reason. The thin and expanded sidebar modes are both implemented using one component, but the component for the combined mode is different, and it is very likely that I just forgot that use case … I'll have a look!
