### ISSUE TITLE
Unreliable rendering of multiple in-line equations in a paragraph.

### ISSUE THREAD

**Issue by Wieke** [Zettlr/Zettlr#105]
## Description

When you have a paragraph with multiple in-line equations the moment you finish the paragraph (hit enter) only the first inline equation get's rendered. Sometimes when hitting enter an additional time, or moving past the paragraph with the text cursor, the next equation will be rendered.

## Reproducing

Write a paragraph with multiple inline equations and hit enter. Or copy this into the editor and hit enter:

> Lorem ipsum dolor sit amet, $$a^2 + b^2 = c^2$$ consectetur adipiscing elit. Nam eros velit, fringilla et magna nec, posuere mattis orci. Sed suscipit non mauris et rutrum. In tristique risus volutpat nisl laoreet fringilla. $$a^2 + b^2 = c^2$$ Sed consequat placerat ligula, ut consequat lacus gravida in. $$a^2 + b^2 = c^2$$ Curabitur nulla urna, maximus in eros vitae, $$a^2 + b^2 = c^2$$ gravida suscipit odio. Sed facilisis tincidunt placerat. Pellentesque dignissim feugiat $$a^2 + b^2 = c^2$$ facilisis. Maecenas ligula sapien, vehicula nec tristique molestie, $$a^2 + b^2 = c^2$$ molestie ut nulla. Ut ut rhoncus nibh.

## Expected behaviour

All equations in the paragraph being rendered.

**Screenshots**

![image](https://user-images.githubusercontent.com/6737186/52859103-1ad50180-312c-11e9-9b7f-37c52529c955.png)

## Platform
 - OS: Archlinux
 - OS Version N/A
 - Zettlr Version 1.1.0 (master and develop branches)
 - Screen Resolution 1920x1080

## Additional information

I'll probably try and fix this this weekend.

**Comment by nathanlesage** [comment]
It's copied to the testing file, will see to it!

**Comment by nathanlesage** [comment]
Here you go!

![image](https://user-images.githubusercontent.com/17251683/52861485-e31d8800-3132-11e9-92b9-a2c54299e104.png)
