### ISSUE TITLE
Hide title in sidebar

### ISSUE THREAD

**Issue by berzhot** [Zettlr/Zettlr#1051]
## Description
Have the option to hide the title of the file in the sidebar, just showing the ID. Title (taken for example from first h1) still appears in the suggestion list when creating link and after link is inserted into the note (if this option is selected in preferences/Zettelkasten)

## Proposed Changes
Add the option in the General-Preferences Menu in a similar way as "show file information"
![hide](https://user-images.githubusercontent.com/8502544/87233324-8e814980-c3c6-11ea-8d51-9fb57f42f4da.png)

## Caveats
Just the sidebar information

## Additional Information
Luhmann couldn't see the card's title without "accesing" the card. In his slip-box, titles are hidden in the body of each card so when you see the box (wich I compare with the sidebar view) you can't see the titles, just a bunch of cards together. Only when you read the card you can see the title.
![_home_httpd_vhosts_swissmercenariesgame com_luhmann ixistenz ch_documents_objectcomponent35419](https://user-images.githubusercontent.com/8502544/87233250-0dc24d80-c3c6-11ea-8911-b99ff411ee1f.jpeg)

**Comment by Zverik** [comment]
Why do you even need a sidebar then?

**Comment by berzhot** [comment]
> Why do you even need a sidebar then?

To be able to access to all the cards.
