### ISSUE TITLE
Quick look function among different markdown files.

### ISSUE THREAD

**Issue by librix** [Zettlr/Zettlr#1052]
## Description
When I am typing what I think, jumping from the keyboard to the mouse is a silly act.
Sometimes it is necessary to get an overview of all the files in the file list, or the markdown files in the search results file list. I read all the help documents, and there is no mention of which keyboard shortcuts can achieve this function.
In my opinion, each document is a card, and different cards can be expressed on different pages. So is it possible to add a key short or shortcut for turning pages?

## Example Workflow
Each page-changing operation will preview the files in turn.

**Comment by nathanlesage** [comment]
I do not quite understand what functionality you exactly wish for — would you mind describing the expected result a little bit more?
