### ISSUE TITLE
Preserving formats during copy/paste doesn't work

### ISSUE THREAD

**Issue by canpolat** [Zettlr/Zettlr#1053]
## Description
According to [documentation](https://docs.zettlr.com/en/core/editor/#preserving-formats-during-copy-paste) Zettlr preserves formatting when copying from formatted text. But this does not work for me.

## Reproducing
1. Copy text from a web page
2. Paste it into Zettlr
3. Observe that the formatting is lost

## Expected behaviour
Formatting should be retained when the text is pasted into Zettlr.

**Screenshots**
Here is a video showing copy/paste from Google Docs into Zettlr and LibreOffice. As you can see, LibreOffice recognizes the formatting while Zettlr does not.

![2020-07-12_09-46-16](https://user-images.githubusercontent.com/459891/87241626-58bf7d80-c425-11ea-8ad8-78c89a4e7727.gif)

And this one show the same process for another web page

![2020-07-12_09-56-22](https://user-images.githubusercontent.com/459891/87241702-0cc10880-c426-11ea-9ff1-07911609be94.gif)

## Platform
 - OS and version: Windows 10 version 1903
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920 x 1080

**Comment by nathanlesage** [comment]
> Here is a video showing copy/paste from Google Docs into Zettlr and LibreOffice. As you can see, LibreOffice recognizes the formatting while Zettlr does not.

Hah, this is an easy fix. On the one hand, Google Drive sometimes does not produce good HTML output (e.g. italics and bold are not done using the correct structural elements).

On the other hand, and I assume this is the case for the document in question: **Bold text is not equal to a heading**. To achieve a heading, you must use the correct structural element (see screenshot). This is the benefit of Markdown: It teaches you to pay attention to the structure.

![image](https://user-images.githubusercontent.com/17251683/87289917-94c61180-c4fd-11ea-91d7-b638b404c130.png)

**Comment by canpolat** [comment]
Thank you for the quick fix :) The element in my screenshot was a heading (not just bold text).

**Comment by canpolat** [comment]
Is this in 1.7.2? I still observe this behavior in 1.7.2.

**Comment by nathanlesage** [comment]
There is nothing merged, as I was explaining some things to be expected – I myself can successfully copy and paste headings both from Firefox and Google Chrome …

**Comment by canpolat** [comment]
Oh, my mistake. I thought this was somehow fixed. Let me elaborate a bit more... This is not related to (only) headings. Below, you can see a screencast of it not working for Heading 1, bold and italic text (from Libre Office). Basically all formatting is lost. I understand that you cannot reproduce this on your setup. 

![2020-07-29_18-17-05](https://user-images.githubusercontent.com/459891/88825363-c3174280-d1c7-11ea-80f3-859b5d30ebf8.gif)

Bonus: At the end of the GIF you see the whole text disappearing due to the file system polling issue.

**Comment by canpolat** [comment]
This is the contents of my clipboard for a similar test. Behind the clipboard inspector, you can see the pasted text. For some reason Zettlr chooses text over HTML.

![image](https://user-images.githubusercontent.com/459891/88841423-43e13900-d1de-11ea-9e95-e7f600d0f036.png)

**Comment by nathanlesage** [comment]
> For some reason Zettlr chooses text over HTML.

This shouldn't happen. I have to test this

**Comment by canpolat** [comment]
Closing this in favor of #608
