### ISSUE TITLE
[Translation] Missing i18n strings in 4 locations in Zettlr and a string that needs to have its content changed

### ISSUE THREAD

**Issue by DozyDolphin** [Zettlr/Zettlr#1054]
I have translated all strings for a language through translate.zettlr.com and I still find these places where the text isn't localized, when I have changed the language of the app from english:

EDIT: I have downloaded and imported the translation file

## Missing i18n 1
When no note is open
![Translated but still english](https://user-images.githubusercontent.com/5829129/87246217-32f99f00-c44c-11ea-808e-d7e75fd85b0b.png)

## Missing i18n 2
In top of the left sidebar - inventory of directories and files
![Translated but still english 2](https://user-images.githubusercontent.com/5829129/87246240-5e7c8980-c44c-11ea-8fc1-3e460a748da4.png)

## Missing i18n 3
The 'More...' button in statistics.
![Translated but still english 3](https://user-images.githubusercontent.com/5829129/87246258-84099300-c44c-11ea-93c9-92e19bb42532.png)

## Missing i18n 4
In the detailed statistics - days logged since...
![Translated but still english 4](https://user-images.githubusercontent.com/5829129/87246282-c206b700-c44c-11ea-9b64-ed0af56a947b.png)

## Change of content
I think the description string regarding the tag cloud needs to be revised. 
You do _not_ need to hover over the tags to see how many times you have used them.
![Text is not correct](https://user-images.githubusercontent.com/5829129/87246135-8c150300-c44b-11ea-81cf-4be7017c31e3.png)
Suggestion for change:
_Here you find all tags that you've used somewhere in your files, and how many times you have used them. You can copy the whole list to the clipboard._ 

Thank you

**Comment by canpolat** [comment]
Which language and which strings are these?

**Comment by DozyDolphin** [comment]
> Which language and which strings are these?

Yeah, sorry - hit the enter button too early :-/ Should be updated now with all info

**Comment by nathanlesage** [comment]
First one is already confirmed:

![image](https://user-images.githubusercontent.com/17251683/87290775-b5db3200-c4fe-11ea-8eb1-2ead6446ae40.png)

BUT there is an issue asking for the tab bar to hide if there's no document open, so I wanted to wait with translating this (adding this to Zettlr Translate is a little bit tedious)

Second one has been overlooked, you're right! (File path: `resources/vue/file-item.vue`, line 171 ff)

Third as well (File path: `resources/templates/popup/stats.handlebars`, line 42)

Fourth as well (File path: `resources/templates/dialog/statistics.handlebars`, line 22)

**Comment by nathanlesage** [comment]
So, I translated the missing strings, except the first and fourth.

The first has not been deleted, as we're currently discussing to just simply drop the tab-bar if just one file is opened, and the fourth because it's not feasible translating it due to limitations in the templating engine. However, we're planning to migrate completely to Vue either way, and it's more like debug information, so I think it's acceptable …!
