### ISSUE TITLE
Citation key search not filtering

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#1067]
## Description

When you start typing the citation key the list of references should automatically filter. This no longer works. No filtering takes place.

## Expected behaviour

Filter the list as the citation key is written 

## Platform
 - OS and version: WIndows 10
 - Zettlr Version: 1.71
 - Screen Resolution: 1920 x 1200

**Comment by marcusyoung** [comment]
@nathanlesage 
OK, this is odd. I had created a project and Zettlr allowed me to merrily write my document on the root of the project, which isn't a document at all. That's where the citation filtering wasn't working. I lost what I'd been working on, though it wasn't that long and not that good! It is still working on normal documents.

**Comment by nathanlesage** [comment]
Huh? This sounds like a serious bug! Would you mind describing more verbosely what exactly happened?

**Comment by marcusyoung** [comment]
I'm not entirely sure how I ended up where I did! I will try to replicate tomorrow.

**Comment by nathanlesage** [comment]
Thank you! Take your time; the better we can reproduce this the quicker we can find a fix :)

**Comment by nathanlesage** [comment]
Any news on this one?

**Comment by nathanlesage** [comment]
Closing due to missing activity.
