### ISSUE TITLE
ctrl+click without ctrl 

### ISSUE THREAD

**Issue by ascii78** [Zettlr/Zettlr#1069]
Hi,

Great work on zettlr, maybe strange question but why is it needed to always use ctrl when clicking a link. Is this for security ? Is this fixed into electron ? Can it be click only ?

**Comment by nathanlesage** [comment]
The reasoning behind having to click links is a usability thing. Zettlr is a text editor, and it is bad UX to have text render as if it was already rendered. There still is a difference between the Markdown source, and the final rendered HTML or PDF. There you would naturally expect links to be clickable. But within the context of a text editor, the "main" action, if you so will, is to edit text, and following a link will break the flow, as you will have to wait until the link has opened and then switch back to the app.

Therefore, simply clicking into a text is considered as the wish to set the cursor there to write, not open the link.

Directly opening the link is something that Microsoft Word can do phantastically, and I for once almost always lose my mind, as links are sometimes hidden. I want to control if I follow a link or actually edit this link, and editing a link is almost impossible if the default action is to simply open it.

Therefore, the `Cmd/Ctrl`-click is required, to prevent these accidents.
