### ISSUE TITLE
[FEATURE] Transparent symmetrical encryption of the markdown files.

### ISSUE THREAD

**Issue by xwindkgb** [Zettlr/Zettlr#1070]
I wonder how practical would be to add the following feature. 

What I thinking of is basically a paranoid feature for people who do the synchronization of the zettlr database in the cloud between the computers: an option to encrypt files with standard symmetrical cypher (e.g. AES) with a pre-shared password/encryption key. A hardware acceleration of an AES can be also considered.

This encryption should be completely transparent. Files are decrypted and pre-loaded in the memory on zettlr start. Then, files are encrypted prior to writing them back on the disk when created, or changed.

**Comment by nathanlesage** [comment]
Not considering, as there are other external tools that do a much better job than we could aim to achieve, especially with regard to safety and reliability. [Please refer to this issue for a longer and more verbose explanation for why we are not considering this feature](https://github.com/Zettlr/Zettlr/issues/1040).
