### ISSUE TITLE
References not appearing in attachments

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#1072]
## Description
This is self explanatory really. In previous versions you could see a list of references in the attachments. Not sure if it's intentional that this is gone or not?

## Expected behaviour
Not sure!

## Platform
 - OS and version: WIndows 10
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920 x 1200

**Comment by nathanlesage** [comment]
Just to make sure, you mean this:

![image](https://user-images.githubusercontent.com/17251683/87483071-179cb880-c633-11ea-85cd-f8891863618e.png)

Right? This is a screenshot from a running app current develop branch

**Comment by marcusyoung** [comment]
Yeah, that's what I mean. There's nothing listed under references even though my document has at least one (which is expanded by the editor) in it.

**Comment by boutil** [comment]
I have just experienced something like this today. It was due to a "syntax error" in my citation in the text.
I was using at some place `[@cite1 Theorem 2]` instead of `[@cite1, Theorem 2]` (note the additional comma.

As a consequence, all the citations disappeared in the attachment section, and I had hard time to find what was the cause of it.
But as soon as I fixed the syntax at that place, all the citations reappeared correctly. @marcusyoung , maybe you have something like this too?

**Comment by marcusyoung** [comment]
@boutil I don't think so, as I was just using an in-text citation `@cite1` without the square brackets which correctly appeared in the PDF export. This is probably the issue, as the references do appear in the list when in square brackets, but that will give the bracketed citation, which isn't always wanted.

**Comment by nathanlesage** [comment]
> I have just experienced something like this today. It was due to a "syntax error" in my citation in the text.
I was using at some place [\@cite1 Theorem 2] instead of [\@cite1, Theorem 2] (note the additional comma.

Yes, without commas it is currently not working, see the relevant issue on the Citr repository: https://github.com/Zettlr/Citr/issues/4

Exporting, though, will still work flawlessly

**Comment by nathanlesage** [comment]
> I don't think so, as I was just using an in-text citation @cite1 without the square brackets which correctly appeared in the PDF export.

Ah, this one! I just fixed that two days ago – I realised that I forgot to check for the corresponding citations …! Should come in 1.7.2, and if not, please comment here! :)
