### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#1075]
## Description
Zettlr response is slowing down during use and becoming difficult to work with - several seconds to recognise the cursor in a new position for instance. Document is less than 3000 words. It has been like this for several days. Closing Zettlr and starting again appears to fix the issue, but it soon returns.

## Platform
 - OS and version: Windows 10
 - Zettlr Version:  1.7.1

**Comment by nathanlesage** [comment]
We are aware that there are many performance bottlenecks currently in the application, but we are actively working on them. Do not worry, they'll ship gradually over time!

Do you have specific information on this certain case? (e.g. performance logs, logs in general? Reproducability steps?) Without these it's a little hard fixing this issue …

**Comment by marcusyoung** [comment]
No specific information unfortunately.
