### ISSUE TITLE
Right-click on Display File information on Windows 10 does nothing

### ISSUE THREAD

**Issue by meathrel** [Zettlr/Zettlr#1078]
## unsure
![2020-07-16 11_59_38-Zettlr](https://user-images.githubusercontent.com/2781934/87663530-e075f680-c75b-11ea-836b-3e83d13bab06.jpg)

**Screenshots**

## Platform
 - OS and version: Windows 10.0.19041 Build 19041
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1366x768

**Comment by nathanlesage** [comment]
It's a translation mistake: Previously you could switch between word counts and cursor position using the right click, I'll have to find a way to this, probably a new translation key!

**Comment by nathanlesage** [comment]
Already fixed!
