### ISSUE TITLE
Frequent typ removal

### ISSUE THREAD

**Issue by Blistax** [Zettlr/Zettlr#1080]
## Description
When typing in Zettlr words are removed. This happens once or twice a minute.

## Reproducing
I cannot document the issue that is happening, it just happens! However, when I typed a word and it is deleted by Zettlr I can get the word back with history (by pressing ctlr-Z)

## Expected behaviour
Do not remove typed words!

**Screenshots**

## Platform
 - OS and version:
Windows 10 Education, Version 1909, OS build 18363.900
 - Zettlr Version:
1.7.1
 - Screen Resolution:
2560x1440

## Additional information
I know this is a very vague description of the problem, but that is because I cannot retrace to the origin of the problem, so I hope you guys can help me out!

**Comment by canpolat** [comment]
I have a feeling that this may be related to #746 

@Blistax are your notes in a directory that is synced to cloud (OneDrive, Dropbox, etc.)?

**Comment by Blistax** [comment]
Hi @canpolat ,

Yes my notes are stored in an online cloud application (Onedrive)

**Comment by canpolat** [comment]
In that case, I think you case is related to the bug I linked to. As far as I can see, Zettlr may get confused in such scenarios (the dev team still is looking into the issue). When the sync happens, Zettlr thinks the file has been modified outside Zettlr (even though it is actually not modified) and tries to load that older version of the file (which results in loss of the most recent change).

While the dev team looks into it, I suppose there are some workarounds:

1. If you move the files outside OneDrive, I think the problem wil disappear (but I can understand if you don't want to do this, it feels safe to have continuous backup)
2. You keep your files in the OneDrive directory. In Preferences > General tab, you can disable "Always load remote changes to the current file". When you do this, you may start getting pop up dialogs saying the the file has been modified outside Zettlr (even though it is not) and asks you if you want to reload it or not. If you get too many of these, it may get very annoying very quickly. In that case, you may want to go to Preferences > Advanced, enable "Activate Watchdog polling" and set the time to wait to a value like 10000 (ten thousand). See if this helps.

**Comment by Blistax** [comment]
Hi @canpolat ,

Thank you for your time and help regarding this issue. Option 2 you are mentioning is worth the try. Another workaround which works for me as well, is pausing the sync of Onedrive itself (for approx. 2 hours). I've tested it and it seems the bug is resolved when pausing Onedrive. So your feeling might be right the bug finds it origin in syncing.

**Comment by canpolat** [comment]
Temporary pause is a good idea. You get the best of both worlds.

If you agree, I would suggest closing this issue (since it is technically a duplicate) and following up the process in #746

**Comment by Blistax** [comment]
Yes, this issue can be closed!

**Comment by nathanlesage** [comment]
> I've tested it and it seems the bug is resolved when pausing Onedrive. So your feeling might be right the bug finds it origin in syncing.

I do have the feeling I need to get back to the chokidar issue tracker to see if there is something going on! Further discussion as already mentioned in #746 please! Thanks y'all! <3

**Comment by canpolat** [comment]
@Blistax This issue (\#746) is solved in version 1.7.3. You may want to get the latest version (1.7.4) and see if that works for you.

**Comment by Blistax** [comment]
Installed the new update. No bugs while onedrive sync was on today. I think the update fixed it! Thank you all!
