### ISSUE TITLE
Some of my notes were deleted

### ISSUE THREAD

**Issue by hojjatabdollahi** [Zettlr/Zettlr#1081]
## Description
This might not be the most useful bug report, but I thought I might as well file it. I had a project in my notes with a huge amount of notes in it. From the Release notes, I saw that when I upgrade I will use the project file (and not the notes, just the file containing information about my project), so I ignored it and just updated. I have been using 1.7 and 1.7.1 for a while now. But recently I tried to search for some of my notes and realized that all of the notes that were part of that project are gone. The files were stored in my Google Drive. They are all physically gone. I had a mini heart attack. But fortunately, I had a back up of all my note (this was old, but better than nothing) so I copied the deleted files back. So, here is my question, why were my notes deleted? Has this happened to anybody else? 

## Reproducing
I'm not sure how to reproduce it. 

## Expected behaviour
Delete only the .project files, and not the notes.

**Screenshots**

## Platform
 - OS and version: Ubuntu 18.04
 - Zettlr Version: 1.7 (currently)
 - Screen Resolution: Multiple monitors with different resolutions.

**Comment by 13rac1** [comment]
I haven't experienced anything like this. I'd be surprised if Zettlr were responsible. Here's every call to `fs.unlink()` in the codebase as a starting point for reproducing this issue. Issue should probably be closed until it can be reproduced.
```
$ grep unlink\( * -Rn | grep -v node_modules
scripts/update-csl.js:75:    await fs.unlink(localesZip)
source/main/providers/log-provider.js:129:      await fs.unlink(toRemove)
source/main/modules/fsal/fsal-file.js:297:    // await fs.unlink(fileObject.path)
source/main/modules/fsal/fsal-directory.js:155:      await fs.unlink(configPath)
source/main/modules/fsal/fsal-directory.js:160:    await fs.unlink(configPath)
source/main/modules/fsal/fsal-directory.js:211:      await fs.unlink(path.join(dir.path, child))
source/main/modules/fsal/fsal-cache.js:147:        fs.unlink(realPath, (err) => {
source/main/modules/export/make-reveal-bundle.js:34:  await fs.unlink(options.targetFile)
source/main/modules/export/showdown-export.js:57:    await fs.unlink(options.sourceFile)
source/main/modules/export/run-pandoc.js:87:        await fs.unlink(options.sourceFile)
source/main/modules/export/run-pandoc.js:88:        if (options.discardTemplate) await fs.unlink(options.template)
```

**Comment by nathanlesage** [comment]
Well, what Zettlr **did** delete after the update were `.ztr-project`-files  in case you had some (because these were merged into the `.ztr-directory`-files; this way there's only one and not two files present in any project directory).

"Project" for Zettlr just means the presence of some settings in such a file, and it doesn't touch any of these.

**Comment by hojjatabdollahi** [comment]
I tried to reproduce the problem in a virtual box. But I couldn't. Since I was playing with different versions (beta versions and appimage mixed with deb files, testing a beta and going back to previous stable version) I have no idea what I did that caused this. I will assume that I did something stupid. Thanks for the help guys.
