### ISSUE TITLE
Pressing tab when cursor not in document causes "No Directory Selected" navigation sidebar

### ISSUE THREAD

**Issue by soaxelbrooke** [Zettlr/Zettlr#1082]
## Description

When the cursor is not in the document pane, pressing tab causes the navigation sidebar to show "No Directory Selected", even though a directory is still selected.  For instance, you can still create new documents, etc. Expanding the window shows the previous directory hierarchy to the left of the new navigation pane.

Why I was doing this: in every document I create an `id` field in the YAML metadata that is copied from the created file name (minus `.md`), which defocuses the right pane. Thinking I could tab back to the editor pane caused this problem.

## Reproducing

1. Press F2 to open "rename" input
2. Press escape to close it
3. Press tab
4. See "No Directory Selected"

## Expected behaviour

Pressing tab should not cause this to happen, and should eventually move the focus back to the editor pane and reinstating the cursor there.

**Screenshots**

<img width="1304" alt="Screen Shot 2020-07-16 at 12 54 31 PM" src="https://user-images.githubusercontent.com/2815794/87716676-0901ee80-c764-11ea-8c03-7f884cf36a1c.png">

<img width="1304" alt="Screen Shot 2020-07-16 at 12 54 43 PM" src="https://user-images.githubusercontent.com/2815794/87716688-0dc6a280-c764-11ea-908c-617e8ffad139.png">

<img width="1304" alt="Screen Shot 2020-07-16 at 12 54 59 PM" src="https://user-images.githubusercontent.com/2815794/87716696-10c19300-c764-11ea-8b4d-da5a01c729d2.png">

<img width="1698" alt="Screen Shot 2020-07-16 at 12 55 19 PM" src="https://user-images.githubusercontent.com/2815794/87716708-1323ed00-c764-11ea-83d0-c24c192aecf7.png">

## Platform
 - OS and version: MacOS 10.15.5
 - Zettlr Version: 1.7.0
 - Screen Resolution: 2560x1600 (macbook air 2019)

## Additional information

Thanks for this awesome project, I'm excited to expand my usage of it!

**Comment by nathanlesage** [comment]
Sorry for the late answer: Interesting behaviour! I'll have a look.

**Comment by nathanlesage** [comment]
Still happening?

**Comment by soaxelbrooke** [comment]
Nope, it’s fixed, thank you!!
