### ISSUE TITLE
[ENHANCEMENT] Drag and Drop attachments from Zettlr out to OS

### ISSUE THREAD

**Issue by 13rac1** [Zettlr/Zettlr#1083]
## Description

Dragging an image into Zettlr inserts it using Markdown. Hovering over an image displays the filename and image dimensions. It would be convenient to be able to drag _out_ of Zettlr into other applications.

The current workaround is displaying to the attachments sidebar, finding the image, clicking to open in the image viewer, then dragging from that.

## Proposed Changes

https://www.electronjs.org/docs/tutorial/native-file-drag-drop

> In your renderer process, handle the ondragstart event and forward the information to your main process.
```html
<a href="#" id="drag">item</a>
<script type="text/javascript" charset="utf-8">
  document.getElementById('drag').ondragstart = (event) => {
    event.preventDefault()
    ipcRenderer.send('ondragstart', '/path/to/item')
  }
</script>
```
> Then, in the main process, augment the event with a path to the file that is being dragged and an icon.
```javascript
const { ipcMain } = require('electron')

ipcMain.on('ondragstart', (event, filePath) => {
  event.sender.startDrag({
    file: filePath,
    icon: '/path/to/icon.png'
  })
})
```

## Caveats

There is no current click and drag functionality. There is "click" functionality which displays the underlying markdown and shouldn't be changed.

**Comment by nathanlesage** [comment]
> There is no current click and drag functionality.

What? You can of course drag the thing into the editor to create links to attachments. Which is why this might be problematic, as I have yet to find a way to successfully enable both the drag to OS and drag around in the app (currently not working good with regard to the sidebar)

**Comment by 13rac1** [comment]
> What? You can of course drag the thing into the editor to create links to attachments. 

Haha, clarification: There is no current click and drag functionality _from the editor to the OS_. I mean the UX doesn't conflict with existing functionality.

**Comment by nathanlesage** [comment]
"from the editor to the OS" == from the text editor, or in general?

**Comment by 13rac1** [comment]
From the text editor. The file path is shown in the tooltip, so it shouldn't be a large change since the data is there.

Problem statement: I'm working on a document containg photos and screenshots. I need to send one of these images to a co-worker. Currently:
1. Click the image in the editor.
2. Look at the filename.
3. Open the directory in my file manager.
4. Scroll or search to find the file.
5. Drag and drop it to Slack.

I want to drag and drop from the text editor directly to Slack. Now that I think about it, a "Copy Image" in the context menu would also reduce this hassle  https://www.electronjs.org/docs/api/clipboard#clipboardwriteimageimage-type :thinking:

**Comment by nathanlesage** [comment]
Aaaaaaaaaaah now I see what you mean!

**Comment by 13rac1** [comment]
bump

**Comment by jpggithub** [comment]
It is a nice idea!
