### ISSUE TITLE
Feature Request - for side by side view

### ISSUE THREAD

**Issue by rohan-paul** [Zettlr/Zettlr#1086]
**I have searched the documentation to make sure I did not overlook it.**

It would be absolutely awesome to get a side-by-side view with source-code on left and rendered markdown on right. That is the right side markdown would be rendered with its final display form, e.g. without the asterix for a bold text.

**Comment by nathanlesage** [comment]
Hey, thanks for the request! Unfortunately, this is not in alignment with the goals of Zettlr (which is to provide the source code only, with some renderings). We've had this discussion a fair amount of times, and while I do see that people might want this, Zettlr will not implement this. I understand that this is a somewhat arbitrary design-decision, but I believe it to be best for the application.
