### ISSUE TITLE
Undo breaks YAML formatted sections

### ISSUE THREAD

**Issue by davidparks21** [Zettlr/Zettlr#1087]
When adding a line above the YAML front section the YAML will change to a table, but undo [CTL-Z] will not bring you back to your original starting point.

Create a new file containing the following:
```
---
title: "test"
---
```
- Now place your cursor at the first character of the first line of text (in front of `---`)
- Press [ENTER] + [UP-ARROW-KEY]
- The YAML has now changed to a table.
- Press [CTRL-Z] to undo, you cannot get back to the previous format.

It's expected that [CTRL-Z] can undo and get you back to your previous state.

## Platform
 - OS and version: Linux Mint 19.3 (a.k.a. Unbutu/Debian)
 - Zettlr Version: 1.7.1
 - Screen Resolution: 3840x2160

**Comment by nathanlesage** [comment]
This should work by clicking inside the generated table and outside again. This is because once you add a line before the YAML frontmatter it is not recognized as a frontmatter anymore, hence due to your delimiters (lines of `---`) the TableEditor will take over and render it. Unfortunately, it does not know that the underlying _meaning_ of your frontmatter has changed. But as soon as you click into the table (= enter edit mode) and immediately click somewhere else in the editor again, the table will need to be regenerated, but the plugin will then realize that it's actually a YAML frontmatter and not display the TableEditor again.

**Comment by davidparks21** [comment]
The fact that the table formatter took over is less an issue than the fact that undo didn't get me back out of the situation. I figured I did something wonky by adding a line above the yaml, but undo should always get a user out of what they did. If that's not the case then they get stuck not knowing what to do and the whole experience feels buggy.

**Comment by nathanlesage** [comment]
Alright, we might want to have an additional look into this!

**Comment by the-solipsist** [comment]
> This should work by clicking inside the generated table and outside again. This is because once you add a line before the YAML frontmatter it is not recognized as a frontmatter anymore, hence due to your delimiters (lines of `---`) the TableEditor will take over and render it. 

Is there a reason to prevent YAML metadata blocks from being recognized in the middle of documents?

Apparently what pandoc does is to use [the following order of precedence](https://groups.google.com/g/pandoc-discuss/c/_oO9SFTjFTU/m/I_uvnr59BAAJ) for understanding `---`:

YAML block separator > setext header > table row separator > horizontal rule

So whatever can be understood as a YAML metadata block will be understood as such, if not, check if it can be understood to be an setext header, if not, check if it could be a table, and if not, render it as a horizontal rule.

Also, pandoc does not understand this (space as the first line after the separator) as a YAML metadata block:

```
---

key: value
---
```

But it does recognize this (space above the separator) as a YAML metadata block:
```

---
key: value
---
```

Perhaps that is something to consider?

**Comment by nathanlesage** [comment]
@the-solipsist Yeah, this definitely helps. It might work, but I'll need to switch the renderers' position. The current sorting order is as follows:

```javascript
function renderElements (cm) {
  const render = cm.getOption('zettlr').render
  // this._cm.execCommand('markdownRenderMermaid') // Render mermaid codeblocks TODO
  if (render.tables) cm.execCommand('markdownRenderTables')
  if (render.links) cm.execCommand('markdownRenderLinks')
  if (render.images) cm.execCommand('markdownRenderImages')
  if (render.math) cm.execCommand('markdownRenderMath')
  if (render.citations) cm.execCommand('markdownRenderCitations')
  if (render.tasks) cm.execCommand('markdownRenderTasks')
  if (render.headingTags) cm.execCommand('markdownRenderHTags')
  if (render.iframes) cm.execCommand('markdownRenderIframes')
  if (render.wysiwyg) cm.execCommand('markdownWYSIWYG')
}
```

Maybe we could think about the assumptions generally …? Anything that cannot be solved by rendering in a certain order we need to solve within the commands themselves.

Oh, and I just saw that I have to re-enable the Mermaid rendering …

**Comment by nathanlesage** [comment]
Is this still happening …?

**Comment by the-solipsist** [comment]
The original issue about YAML->tables and undo not working is no longer present. 

But the additional comments I'd made still stand:
1) Differences between Zettlr and pandoc in treatment of blank lines within and before the YAML metadata block; and 
2) Inability to render YAML metadata blocks as metadata blocks when they occur anywhere but the first line of the document.

**Comment by nathanlesage** [comment]
@the-solipsist To both of your points:

This cannot really be alleviated, I think, because highlighter modes cannot peek between lines which is a requirement for that to work. We have to wait for CodeMirror next for a possible fix.

**Comment by the-solipsist** [comment]
If that's the case, then I feel this issue could be closed, and, if needed, reopened as and when CodeMirror supports this.

**Comment by nathanlesage** [comment]
Agreed!
