### ISSUE TITLE
Zoom only affects editor

### ISSUE THREAD

**Issue by shockme** [Zettlr/Zettlr#1088]
## Description
Zooming in only affects the editor, without affecting the sidebar.

## Reproducing
Use the menu item or the keyboard shortcut to zoom in. Notice how the text in the editor becomes bigger but the text in the sidebar stays the same size.

## Expected behaviour
The text in the whole UI should be affected by zoom, not just the editor. This is consistent with how other applications behave.

## Platform
 - OS and version: Ubuntu 16.04
 - Zettlr Version: 1.7.1
 - Screen Resolution: 2560x1440

## Additional information
Without all the UI elements being affected by zoom usability quickly becomes worse because some elements of the UI become much harder to see.

**Comment by nathanlesage** [comment]
> This is consistent with how other applications behave.

What "other applications" do you mean? I can only think of browsers right now!

**Comment by shockme** [comment]
Obsidian, Skype, Element/Riot

**Comment by nathanlesage** [comment]
Alright, added it to the backlog!
