### ISSUE TITLE
[ENHANCEMENT] Show custom folder in paste image dialog + allow skipping dialog

### ISSUE THREAD

**Issue by ianhi** [Zettlr/Zettlr#1091]
## Description
**custom folder**
Currently if I set a custom image folder in the preferences:
![image](https://user-images.githubusercontent.com/10111092/87864382-9183b900-c935-11ea-8754-06332d7eefb5.png)

And then paste an image into Zettlr then the image dialog does not reflect that the image will not be saved in the current folder which initially made me go back and check my preferences again:
![image](https://user-images.githubusercontent.com/10111092/87864375-86c92400-c935-11ea-85ad-f3496e39b2fd.png)

**skipping dialog**
There does not seem to be a setting to automatically skip the image dialog.

## Proposed Changes
For the former: When a custom image path is set change: `Save to current directory` to `Save to {{ custom directory }}`
For skipping dialog. 2 options (not mutually exclusive):
1. Add an option in the settings
2. `ctrl-shift-V` pastes without the dialog. 
   - I do not think that this shortcut currently has another meaning in Zettlr
   - If there was a setting to toggle the dialog then `crtl-shift-V` could always do the opposite of the setting

## Caveats
None I can think of

**Comment by nathanlesage** [comment]
Yeah, we can certainly improve on the User Interface with regard to that!

As for now, albeit it's intransparent it works like this: If you paste an image, you can simply hit Enter to accept the default settings (which is "Save to current directory" with a possible sub-directory set in the preferences)
