### ISSUE TITLE
[ENHANCEMENT] Support for a date/time based macro for auto adding it to the file.

### ISSUE THREAD

**Issue by nipunarora** [Zettlr/Zettlr#1093]
## Description

I plan to use Zettlr as my daily journal/note taking app. For this, I'd like something along the following lines - 
If I add something like `/date` -> zettlr auto-generates and adds the current date.

Something similar for `/time`, and `/datetime` would be useful

## Proposed Changes

Hopefully this can be something which can be derived from the machine and added as raw text.

**Comment by canpolat** [comment]
If you are not making use of the Zettelkasten IDs, you could use that to generate `datetime` (any one of the three, actually).

Usually, people use a datetime based string to generate the IDs. You could use a pattern like: `%Y-%M-%D %h:%m:%s` to generate `datetime` whenever you need it (or you can omit `%h:%m:%s` to only have `date`, and vice versa). Then you can use the `Ctrl+L` keyboard shortcut to insert this 'ID' to anywhere in your document. See the screenshots below. If you need all three of these, I suppose the dev team (I'm not one of them) needs to chime in.

## Screenshot datetime
![image](https://user-images.githubusercontent.com/459891/87884058-e98cef00-ca0b-11ea-9f92-85b56cdb678a.png)

## Screenshot date
![image](https://user-images.githubusercontent.com/459891/87884083-075a5400-ca0c-11ea-8574-ccf8ba82fd46.png)

## Screenshot time
![image](https://user-images.githubusercontent.com/459891/87884122-5902de80-ca0c-11ea-9df7-bbaad422e7ca.png)

**Comment by ianhi** [comment]
Were this to be considered it would awesome if the formatting supported more than just the date formatting. I.e. if it were possible to add hashmarks to make it a title. Maybe this would be best accomplished by way of the custom keymaps being worked on in https://github.com/Zettlr/Zettlr/pull/927 with some default maps like `/date`, `/time` and `datetime`? 


> Hopefully this can be something which can be derived from the machine and added as raw text.

If you are looking for a workaround in the meantime and are on linux I found that a keyboard short that invokes this command: `bash -c 'sleep 0.3 && xdotool type "# $(date +%Y-%m-%d\ %H:%M)"'` works well.

**Comment by nathanlesage** [comment]
Basically, I see three possible implementations for adding custom variables:

1. Using snippets (adding the time-variables there is a no-brainer)
2. Custom commands as @ianhi has suggested, albeit I am a little bit anxious to invite feature-bloat with this :S 
3. Using the ID generator for this

I personally would opt for 1 (as you could also misuse the snippets-feature to only insert the variables themselves)

**Comment by nathanlesage** [comment]
Let's close this issue in favour of the snippets, which will be coming, and also support variables.
