### ISSUE TITLE
Editor inserts tabs instead of spaces

### ISSUE THREAD

**Issue by canpolat** [Zettlr/Zettlr#1097]
## Description
In Preferences > Editor, there is a setting for number of spaces for indentation. But, when the tab/tabulator key is pressed within the editor, it inserts a `TAB` character instead of spaces.

## Reproducing
- Open the editor
- Press the `TAB` key on the keyboard

Observe that a `TAB` character is inserted in the document.

## Expected behaviour
A number of spaces (determined by the setting under Preferences > Editor) should be inserted.

**Screenshots**

## Platform
 - OS and version: Windows 10, 1903
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1980 x 1080

**Comment by nathanlesage** [comment]
And fixed in the last commit!
