### ISSUE TITLE
Errors during manual install to GalliumOS (offline)

### ISSUE THREAD

**Issue by st-fresh** [Zettlr/Zettlr#1099]
## Description
Downloaded `Zettlr-develop.zip`
.
`unzip Zettlr-develop.zip` to `/home/username/` >success> `/home/username/Zettlr-develop`
.
Errors after running `npm install` within folder `Zettlr-develop` >node-npm installed at> `/usr/local/bin`
.
See errors below
.
**Question>> Should I proceed with an `npm install` within `/home/username/Zettlr-develop/source`? >Or> These errors won't allow for Zettlr to operate?**

## Reproducing
```
username@pcname:~/Zettlr-develop$ npm install
npm ERR! Linux 4.16.18-galliumos
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/Zettlr-develop/npm-debug.log

```

## Platform
 - OS and version: GalliumOS Intel Celeron x86_64
 - `npm version`
```
{ npm: '2.14.7',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '46',
  node: '4.2.1',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by st-fresh** [comment]
EAI are DNS issues right? ~ Using Zettlr offline on this machine so can ignore those I believe? Or Zettlr requires DNS to operate?

**Comment by st-fresh** [comment]
Looks like I can use `npm config delete proxy` to bypass the `npm ERR! syscall getaddrinfo` ~ That ok for Zettlr to operate?

**Comment by nathanlesage** [comment]
> Using Zettlr offline on this machine so can ignore those I believe?

Nope, because if I read the errors right, NPM was unable to fetch the repository list, hence it was unable to install the dependencies, hence there's a lot of code missing that's necessary for Zettlr to operate.

> Looks like I can use npm config delete proxy to bypass the npm ERR! syscall getaddrinfo ~ That ok for Zettlr to operate?

If that works, I'd suggest you try it, but after all you need `yarn`, as we completely ditched NPM support a few weeks ago …

**Comment by st-fresh** [comment]
Installing yarn
Trying again to install Zettlr using yarn
