### ISSUE TITLE
Error message when trying to export to pdf

### ISSUE THREAD

**Issue by saggers147** [Zettlr/Zettlr#1102]
I tried to export to pdf but I got the message:
Error producing PDF.
! Missing number, treated as zero.
<to be read again> 
                   \protect 
l.182 ...nter}\rule{0.5\linewidth}{\linethickness}

## Expected behaviour

![image](https://user-images.githubusercontent.com/68693092/88284260-0748a580-cce5-11ea-870c-2337fe5745bb.png)

**Screenshots**

## Platform
 - OS and version: MacOS 15.5
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Do you have a vanilla LaTeX-installation on your system? And do you use the standard template?

**Comment by saggers147** [comment]
I downloaded mactex and installed it.

I have had no problem with other exports (so far)

**Comment by nathanlesage** [comment]
other exports to PDF or to other file formats? It might be that some things in your file make Pandoc choke …?

**Comment by saggers147** [comment]
No problem so far with other formats.

I reinstalled mactex and it was fine but started making errors again on the third time

[cid:image001.png@01D66275.84148000]

**Comment by nathanlesage** [comment]
Okay thank you! I'll have a look!

**Comment by nathanlesage** [comment]
Just had a look at the issue again, and I don't know why I didn't write that before, but it strongly looks like an error somewhere in either your file or your template, which makes Pandoc choke. Mitigation: Search for the LaTeX commands in your files to determine the error!

**Comment by saggers147** [comment]
Thank you I will try that

On 26 Oct 2020, at 00:41, Hendrik Erz <notifications@github.com> wrote:


Just had a look at the issue again, and I don't know why I didn't write that before, but it strongly looks like an error somewhere in either your file or your template, which makes Pandoc choke. Mitigation: Search for the LaTeX commands in your files to determine the error!
