### ISSUE TITLE
Cannt download Zettlr

### ISSUE THREAD

**Issue by sergpy** [Zettlr/Zettlr#1103]
https://www.zettlr.com/download  does not work, pls help

**Comment by canpolat** [comment]
Which version are you trying to download? Have you tried clicking on the link to manually start the download?

![image](https://user-images.githubusercontent.com/459891/88318912-bc965000-cd1b-11ea-94ac-42312697717c.png)

**Comment by nathanlesage** [comment]
Thanks for reporting! Fixed it!

> Which version are you trying to download?

The whole page didn't load because there was \~again\~ some PHP bug …
