### ISSUE TITLE
Text being deleted every 5 seconds

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#1104]
This bug has been first described on the forum : https://forum.zettlr.com/discussion/215/autosave-bug#latest

When typing, the last seconds of texts are erased every 5 or 10 seconds.  Sometimes, the dialog "this file has been modified, would you save it ?" popup.

At first glance, it looks like the autosave function is modifying the file and that Zettlr is detecting the change and reloading the file as it was during the last autosave, losing a couple of seconds in the meantime.

It is possible that the bug only happens when autosave and automatic load are enabled.

This bug was never present under 1.6 and suddenly started to appear here. I don't know if it was always present in 1.7 or if it started today.

**Comment by ploum** [comment]
This bug is quite critical as it breaks completely Zettlr. Might be linked to #1105

**Comment by nathanlesage** [comment]
It's even related to #746

**Comment by nathanlesage** [comment]
Current mitigation is to increase the watchdog polling interval in the "Advanced" settings + activate watchdog polling. Then try restarting and it should work – some users explain they could silence this behaviour with 10 seconds delay. Please report if this helps in the meantime!

**Comment by ploum** [comment]
Thanks, it seems to fix the issue !

You are learning the hard way a strong lesson that every software developer needs to learn :  "that old spaghetti code that you rewrote to make it more clean had, in fact, years of tuning and was doing the job properly. When your new code will have all the bug polished and ironed out, it will also looks like some spaghetti crap".

We all had to learn this lesson. Several times. And we still fall for the trick every time ;-)

**Comment by nathanlesage** [comment]
Well, at least as long as the new spaghetti code has better sauce, it's worth it!

I still stand by rewriting that monstrosity, because I think it's equally a fallacy to "never change a running system" — my old Windows 95 computer also worked pretty well ;)

But alas, glad it worked out!

**Comment by canpolat** [comment]
@ploum This issue (\#746) is solved in version 1.7.3. You may want to get the latest version (1.7.4) and see if that works for you.
