### ISSUE TITLE
CTRL-click a link to a file opens a (badly formated) url in the browser

### ISSUE THREAD

**Issue by yhancik** [Zettlr/Zettlr#1107]
CTRL-click on a link to a non-markdown file (for example a PDF) actually tries to open an `https://` address in the default browser, instead of the default application associated with the file type.

## Reproducing
- _(Facultative step, but that's how you usually create these links)_ Drag an attachment from the attachment sidebar, into the editor
- An absolute link is created (on Windows, using the Win32 format , starting with the drive letter, and using backslashes)
- CTRL-click on the link in the editor
- It opens `https://<my link>` in my default browser. The url isn't correct so it doesn't work.

That happens, regardless of the link format.
`[test.pdf](F:\zettlrtest\test.pdf)` → `https://f/zettlrtest/test.pdf`
`[test.pdf](F:/zettlrtest/test.pdf)` → `https://f/zettlrtest/test.pdf`
`[test.pdf](/zettlrtest/test.pdf)` → `https://zettlrtest/test.pdf`
`[test.pdf](test.pdf)` → `https://test.pdf`
... you get the idea.

Some extensions work : .md and .txt are opened in the associated application. It's not the case with all text (vs binary) files.

## Expected behaviour
- The links open in the default application (which is the behaviour when clicking a link in the Attachment bar)

## Platform
 - OS and version: Windows 10, latest
 - Zettlr Version: 1.7.1 & current dev branch
 - Screen Resolution: 1920x1080

## Additional information
I wanted to test this in connection to https://github.com/Zettlr/Zettlr/pull/1096 - and it'll be of course interesting to see if it's a good idea to use relative POSIX paths for links to files ;)

**Comment by nathanlesage** [comment]
Sounds like a great addition to [this test](https://github.com/Zettlr/Zettlr/blob/develop/test/make-valid-uri.js) (including mitigation)

**Comment by Vipoli** [comment]
I'm having the same experience as @yhancik. My temporary solution is to manually modify the link format in this way:
- instead of `[test.pdf](test.pdf)`
- I write `[test.pdf](file://test.pdf)`
And it works!
I don't know if this solution has an impact in exporting issues, just because I've never tried, so far.

**Comment by nathanlesage** [comment]
Short question to @Vipoli and @yhancik: Does this still happen in 1.8 beta? I've just stumbled upon this issue but I'm pretty sure I fixed that in one of the last releases.

**Comment by Vipoli** [comment]
Dear Hendrik,
sorry but I haven’t tried the beta version yet. I’m still using 1.7.5.

**Comment by yhancik** [comment]
@nathanlesage it still does indeed!

**Comment by RedDocMD** [comment]
@nathanlesage it does so also on  Linux.

**Comment by RedDocMD** [comment]
I would like to file a PR for this. @nathanlesage can you please assign it to me?

**Comment by Vipoli** [comment]
1.8 just installed. The problem persists: the relative path [file.pdf] acts as an URL, opening a (empty) page in the default browser.

**Comment by nathanlesage** [comment]
Fixed, coming in the next release!
