### ISSUE TITLE
Ctrl+K automatic paste doesn't work with some urls

### ISSUE THREAD

**Issue by ShanSanear** [Zettlr/Zettlr#1109]
## Description

Ctrl+K doesn't automatically paste urls when used with some non-standard urls.

## Reproducing
1. Copy this link - https://data-flair.training/blogs/python-project-ideas/ to clipboard
1. Use Ctrl+K shortcut in Zettlr

## Expected behaviour
Markdown text, such as `[](https://data-flair.training/blogs/python-project-ideas/)`

**Screenshots**
![image](https://user-images.githubusercontent.com/8857417/88365789-65c66000-cd87-11ea-9791-904de33032e1.png)

## Platform
 - OS and version: Windows 10 Pro, Build 19041
 - Zettlr Version: 1.7.1
 - Screen Resolution: 2560x1440 on two screens, Zettlr on secondary one

## Additional information
From what I managed to get my head around, when last part of main url has more than 4 characters, it's not considered URL.

**Comment by nathanlesage** [comment]
Does it work, if you have some text selected? Or doesn't it also work with text selected?

**Comment by ShanSanear** [comment]
It doesn't, behavior is similar to the first example:
![image](https://user-images.githubusercontent.com/8857417/88370161-c65a9a80-cd91-11ea-99c8-aa39ff038c6e.png)

**Comment by nathanlesage** [comment]
Alright, would you mind to quickly have a look at the clipboard's contents so that I have all information for tackling this bug?

(Activate Debug mode in advanced settings, then menu -> Develop -> Inspect Clipboard)

It will help to know what the clipboard looks like as Zettlr looks at that when deciding what to do!

**Comment by ShanSanear** [comment]
![image](https://user-images.githubusercontent.com/8857417/88371463-5e598380-cd94-11ea-859b-96b41073faf4.png)

**Comment by nathanlesage** [comment]
Thank you! I'll get into it!

**Comment by nathanlesage** [comment]
I'm an idiot. Somehow I limited the Sub- and global domain name to max. 256 characters, and the top level domain to 2-4 characters. Don't ask me why I thought that'd be a good idea 🤷

**Comment by ShanSanear** [comment]
No worries, did such stuff myself many times :D Thanks for the quick fix :)

**Comment by nathanlesage** [comment]
Yeah, it's just that in the past three months due to increased activity I am forced to view and correct all the stupid decisions from 3 years ago increasingly often, hahahaha
