### ISSUE TITLE
Open default file of a folder

### ISSUE THREAD

**Issue by enteropositivo** [Zettlr/Zettlr#111]
Would be nice to load a default file for every directory click,  so when navigating using directory tree,  and clicking in a directory, Zettlr could load automatically a file inside that folder.

Possible solutions.

- if a folder contains a file called  ( index.md or index.txt, ... )  or perhaps if a folder contains a file named like that folder  "sample_directory/sample_dirtectory.txt"

- Othe solution could be to  allow this option only in Project folders,  and under Project Settings allow this option.

How do you see it ?

**Comment by nathanlesage** [comment]
mh … I'm curious as to your motivation behind this! I clearly understand what you want, but how does it help/what situations do you anticipate? Do you have an example?

**Comment by enteropositivo** [comment]
I use the Zettlr for many purposes.  

- Work, Manage projects
- Annotate Software development progress, to-dos, ideas, pseudo code, source attachments ...
- Notes for personal use


Some examples:

Having different project folders,  each project folder with a lot of related file ,  i allways use one index file  for  To-Do and Bug tracking  about that project.  So clicking in every project folder i would see easilly that project Summary


Having different folders for app documentation. There is allways an index for that documentation in progress  so clicking the folder i need to see that index, so no need to search for that index file and click again.


Having a folder for Invoices,  would be nice see when clikcing it a default file to see/write  unpaid invoices,  invoices to create,  or something else.  Without looking for this default file between a lot of invoice files.


Some years ago we used **The Guide**  outliner App  (http://theguide.sourceforge.net/),  i could create nested notes,  so a note is a note and a folder at the same time,  but the problem where that the notes are stored in a db file,  not plain text like Zettlr.



( if you can not understand something due to my english,  please tell me and i will try to explain it better )

**Comment by nathanlesage** [comment]
No, no, the English is good :) And I see your point. But I'd have to think about a way to implement it, but I think I have a good idea already. Can't promise anything as to when this will come, though.

**Comment by enteropositivo** [comment]
Has this issue closed because you have implemented it or because you decided not to do it ?

**Comment by nathanlesage** [comment]
I don‘t currently see the feature in Zettlr, and I don‘t have the resources for it. If you‘d like to implement it I‘m happy to accept a PR.

**Comment by enteropositivo** [comment]
Ok, no problem.  I'll try to implement it myself
