### ISSUE TITLE
Very long freeze at startup

### ISSUE THREAD

**Issue by mouarfff** [Zettlr/Zettlr#1110]
Windows 10 last updates.last update too, same issue under linux mint (folder synchronized on disks by an app)

I have a folder with 20 md files and since 1 week, the start is very very long (about 1 to 3 minutes), at first i have "white" freeze, after, zetllr show me un file, and switch to another file, and re-switch to a another file again, and once it display the last file i used, i need to wait more to use it.

It's very strange, because the differents files displayed during the freeze, are files I switched in same order just before the bug appear.

**Comment by nathanlesage** [comment]
This is unfortunately not very helpful. Did something happen one week ago?

**Comment by mouarfff** [comment]
I just added an image ?
I use Seafile to sync my files between linux and windows, and use markdown in linux and windows too,.

But i'm sorry i can't be sure when the issue happend really, if it was juste after, or some days after ...

**Comment by mouarfff** [comment]
I just see something, i have freeze when i try to switch tabs

**Comment by nathanlesage** [comment]
Thanks for the additional information! I've also noticed that switching tabs sometimes leads to some lag, but I haven't had the time to double-check this as of now!

**Comment by nathanlesage** [comment]
File performance was improved in the most recent releases.
