### ISSUE TITLE
Autocompletion only shows filenames

### ISSUE THREAD

**Issue by inquisitiv3** [Zettlr/Zettlr#1112]
## Description

The auto suggestion window only shows filenames if you have activated the option _If present, use the first heading level 1 instead of the filename_ that was introduced in Zettlr version 1.7.2. This is a problem for me because I only use UIDs for filenames. E.g., `55416496-b9be-430c-b7d6-bc5dc3c0d6f9.md`. 

## Reproducing

1. Activate the option Preferences --> Dipslay --> If present, use the first heading level 1 instead of the filename.
2. Try to create a link to a note by typing `[[` (or whatever symbols you use to create an internal link), and watch the auto completion window show filenames.

## Expected behaviour

The auto suggestion window should contain the level one heading. I.e., the same behavior as the side bar.

**Screenshots**

![Autocompletion doens't have the title](https://user-images.githubusercontent.com/38804798/88414332-f8451e80-cddc-11ea-9ac7-92ca61eed09e.png)

In the screenshot I try to create a self-reference to the zettel, to be used to find backlinks.

## Platform
 - OS and version: Fedora 32
 - Zettlr Version: 1.7.2
 - Screen Resolution: 1366x768

## Additional information

It would be nice if the displayed titles could exclude the links inside them. E.g., my note with the header `# Dependency Inversion Principle [[d8705878-00c3-4d95-9cfb-d0bb3fb80ea1]]` should be displayed as `Dependency Inversion Principle`. As i mentioned earlier I create self-references to find backlinks.

**Comment by nathanlesage** [comment]
Hey, sorry, I forgot about your issue, but I am happy to tell that it's been fixed, and now it should work (in the 1.8 alpha). If it doesn't, simply comment here again!
