### ISSUE TITLE
Exporting a project to PDF fails -- Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by masonrhayes** [Zettlr/Zettlr#1113]
## Description
When exporting a project to PDF, I receive the following error message:
> Cannot read property 'replace' of undefined

Exporting individual pages of the project still works fine. Also, exporting the exact same project to PDF with Zettlr 1.7.1 still works; it only stopped working after the new release.

## Reproducing
The project I am trying to export consists primarily of plain text notes interspersed with LaTeX math, about 10 different Markdown files in the project. Using the latest version of Zettlr, 1.7.2, create a project like this and attempt to export; changing no other settings, downgrading to Zettlr 1.7.1 fixes this issue.

## Expected behaviour
Proper PDF export of a project

## Platform
 - OS and version: Windows 10 Pro 1909, OS Build 18363.720
 - Zettlr Version: 1.7.2
 - Screen Resolution: 1080p

**Comment by sjhaque14** [comment]
I am having this exact same issue.

**Comment by Kangie** [comment]
Can replicate, export fails with 'Cannot read property 'replace' of undefined' in 1.7.2, however project builds successfully when downgraded to 1.7.1.

**Comment by obehrto** [comment]
Can replicate the exact same issue after upgrade to 1.7.2.

**Comment by nathanlesage** [comment]
Whoopsie, looking into it!

**Comment by webbj74** [comment]
```
8a1f5274c8b79bf13d65be84b8bf79bc09951816 is the first bad commit
commit 8a1f5274c8b79bf13d65be84b8bf79bc09951816
Author: nathanlesage <nathan.lesage@mailbox.org>
Date:   Fri Jul 10 12:22:40 2020 +0200

    Frontmatter support on PDF export

 CHANGELOG.md                                     |  1 +
 source/main/assets/export.tex                    |  4 +-
 source/main/commands/export.js                   | 50 ++++++++++++++++++++++--
 source/main/modules/export/prepare-pdf-export.js |  1 +
 4 files changed, 51 insertions(+), 5 deletions(-)
```

**Comment by webbj74** [comment]
The reported error is thrown by `sanitiseTexValue()` because in `prepare-pdf-export.js` the property `options.date` is undefined.
```
    'PDF_DATE': (options.date === '\\today') ? options.date : sanitiseTexValue(options.date),
```

My suspicion is that the `options` object in `prepare-pdf-export.js` is referring to the preference pane options and **NOT** to the options being defined in `source/main/commands/export.js`.

**Comment by nathanlesage** [comment]
Thanks y'all for looking into it and for @webbj74 for quickly fixing it! I'll see to releasing a fix this weekend so that it works again.
