### ISSUE TITLE
H1 as title in addition to ID

### ISSUE THREAD

**Issue by berzhot** [Zettlr/Zettlr#1115]
## Description
Use H1 as title in the sidebar in addition to the ID, not in subsitution

## Example Workflow
I love the new option to use H1 as title but I would like to do it in addition to the ID, not in substitution. I would like to use both. This way I can create a new note quickly (just with the ID) and inmediately start working in the content. When I add the H1, the note will take it as a Title and will show it in the sidebar next to the ID

## Additional Information
I can create a new note quickly (just with the ID) and inmediately start working in the content

![1](https://user-images.githubusercontent.com/8502544/88454499-71418600-ce70-11ea-91d0-f3d3f6974d4b.png)

Eventually I can write H1

![2](https://user-images.githubusercontent.com/8502544/88454502-743c7680-ce70-11ea-9607-86b5d1dac4be.png)

The note take H1 as a Title and show it in the sidebar next to the ID

![3](https://user-images.githubusercontent.com/8502544/88454504-769ed080-ce70-11ea-8158-4a103e0672fc.png)

**Comment by nathanlesage** [comment]
Mh, this might result in making everything even more and more crumbled in the settings; I don't really see the benefit in the "greater scheme of things", to use a totally stupid idiom … because there are already numerous different options to change the way information is displayed in the file list :/

**Comment by berzhot** [comment]
> Mh, this might result in making everything even more and more crumbled in the settings; I don't really see the benefit in the "greater scheme of things", to use a totally stupid idiom … because there are already numerous different options to change the way information is displayed in the file list :/

I think is not about adding a new function but perhaps about changing the way it works the way the new one does. In my opinion ID and Title are two different elements related to the filename so my suggestion is to keep their both behaviour independent. 
My assumption is that H1 and Title, from an informative viewpoint, can be equals. So H1 can replace Title but doesn't have to affect ID visibility.

At this point, it can be used as filename:
ID 
ID + Title 
Title 

With the new option, use H1 as filename, I get:
H1

If ID and Title are independent elements and we think H1's informative value equals to the Title. Is just about changing the behaviour of the new option and use Markdown's sintax to do the job:

ID 
ID + H1 (=Title)  
H1 (=Title)

**Comment by santidingo** [comment]
Is there a way to disable automatically changing the file name? I didn't know this was happening and now...well I can't tag anything because I use H1 a lot.
