### ISSUE TITLE
Citation issues with update

### ISSUE THREAD

**Issue by Zettelkaestner** [Zettlr/Zettlr#1116]
## Description
There is a problem with autofilling citations. I don't get any suggestions after using the shortcut anymore and need to write it manually. After that it also won't format it by itself. Converting to PDF shows, that Zettlr recognizes the citation correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/68324765/88463668-aa034e80-ceb4-11ea-92ca-1436ed7276d7.png)
![image](https://user-images.githubusercontent.com/68324765/88463685-d28b4880-ceb4-11ea-8d83-5253a7c9c599.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: Newest version

**Comment by nathanlesage** [comment]
Sooo, finally able to get to you! This does indeed indicate that there might be an error with your citation database. Does Zettlr spit out a warning when it starts or you switch to said library?

**Comment by Zettelkaestner** [comment]
There ist no warning.

**Comment by nathanlesage** [comment]
Hmm, is something visible in the logs?

**Comment by nathanlesage** [comment]
Oh, sorry! You can open the logs by going into the Advances tab of the settings, activate debug mode and then clicking the menu-item "Develop" and then "Open Logs"!
