### ISSUE TITLE
Zettlr does not start by default in i386 using AppImage edition

### ISSUE THREAD

**Issue by EchedeyLR** [Zettlr/Zettlr#1121]
Zettlr does not start

## Reproducing
1. Download i386 dedicated AppImage.
2. Mark it as excecutable.
3. Try to execute it.

## Expected behaviour
Start.

**Screenshots**
![proof](https://user-images.githubusercontent.com/56733813/88493464-3858fc80-cfa9-11ea-94cb-122a68b4f8e4.png)

## Platform
 - OS and version: Devuan 3 Beowulf i686
 - Zettlr Version: 1.7.2 i386
 - Screen Resolution: 1920x1080

## Additional information
I tried to execute it by terminal and saw info related to default permissions in some of the files inside the AppImage.

**Comment by webopold** [comment]
add --no-sandbox
is 32bit intended  - don't you have a 64bit system (Devuan 3 Beowulf i686)?

**Comment by EchedeyLR** [comment]
No, sorry. The processor is capable of it but has no much memory for running certain apps if I run a 64 bits distro which I already compared. However, some electron apps ran very well when I tested years ago in 32 bits.

**Comment by EchedeyLR** [comment]
About the suggestion, thank you, it worked but, what is the point of providing an AppImage and having to use the terminal to execute it in this way when can be used as a simple portable executable which can be executed in double click? Even if I can tweak to use a custom .desktop file, there is no excuse for it, there are other apps which also use AppImage and ask you to create a .desktop automatically in local or even Ungoogled Chromium has its own .desktop inside the AppImage for a custom starting line, like this.

**Comment by EchedeyLR** [comment]
I updated the name to address the real issue you showed me.

**Comment by webopold** [comment]
I am also not happy with using the switch, i made an alias for it and made a starter from my ~/bin/, using i3wm.
This sandbox on/off is a chromium "feature" i guess.
For my whishes to be fullfilled there might be an i386 *.deb, as i use zettlr mostly on my "Schreibmaschine" - an Atom-Subnotebook where 64Bit is not possible. So I have to run the appimage, which is starting very slow, and consumes a lot of memory.

**Comment by EchedeyLR** [comment]
I recognize that. I would also prefer that. But an executable portable is also useful by now. My issue is just that behaviour and yes, sandboxin is Chromium feature.

**Comment by nathanlesage** [comment]
Soooooooooo what you're getting is that AppImage somehow doesn't work out of the box, right?

**Comment by EchedeyLR** [comment]
Yes. In a first time I thought that just didn't work but the other user addressed me to the real issue.

**Comment by nathanlesage** [comment]
Alright, so we'd need to have a look at what Electron builder does and whether we have a misconfiguration in the build setup

**Comment by nathanlesage** [comment]
Does this still happen in the last releases?

**Comment by EchedeyLR** [comment]
I almost forgot about this. I am going to test rn. 

Thank you for notifying.

**Comment by EchedeyLR** [comment]
I am using a x86_64 OS rn and seems that even having installed some things of x86_32 I am having issues to test this.

I can test in a VM but will have to wait a bit more.

**Comment by EchedeyLR** [comment]
![2020-10-26_11-37](https://user-images.githubusercontent.com/56733813/97168053-ba5eea00-177f-11eb-951f-fe406d46c204.png)

Should I try beta versions too?

The issues about sandboxing and recurrent faulty libffmpeg (which should be packages inside the AppImage) are still present.

**Comment by EchedeyLR** [comment]
![2020-10-26_11-49](https://user-images.githubusercontent.com/56733813/97169066-589f7f80-1781-11eb-8b12-21f01bce9477.png)

In last beta.

**Comment by nathanlesage** [comment]
Thanks for checking. Unfortunately, I have no idea why this is happening :/

**Comment by nathanlesage** [comment]
Still happening in 1.8.3?
