### ISSUE TITLE
[Feature request] Formatting Marks

### ISSUE THREAD

**Issue by dagdrommer** [Zettlr/Zettlr#1123]
While writing a text it happens from time to time that several spaces creep in. This is not tragic after compiling with pandoc, though I would suggest to implement optional formatting marks, as they are common in most Office-Suits (e.g. showing a light grey dot where a space is used). I am sure that this feature will lead to more tidy (and satisfying) markdown documents.

**Comment by nathanlesage** [comment]
Oh, this shouldn't be too hard, I figure!

**Comment by boutil** [comment]
Codemirror has a [trailing space](https://codemirror.net/addon/edit/trailingspace.js) addon.
Maybe this, plus the custom CSS trick to show line ends mentionned in the documentation, can be activated/deactivated by an additional button on the toolbar?

**Comment by canpolat** [comment]
Isn't this about showing *all* whitespaces in a document? Here is a screenshot from Noteapad++:

![image](https://user-images.githubusercontent.com/459891/88666576-8d4b5e80-d0e0-11ea-8b6d-eff20f34210a.png)

**Comment by dagdrommer** [comment]
> Isn't this about showing _all_ whitespaces in a document? Here is a screenshot from Noteapad++:
> 
> ![image](https://user-images.githubusercontent.com/459891/88666576-8d4b5e80-d0e0-11ea-8b6d-eff20f34210a.png)

Yes, this is exactly what I imagined. Maybe including our friend the pilcrow  ![pilcrow](https://www.zeichen.tv/images/icons/182-Absatz.png)

Especially in a language like Markdown this can be helpful to keep an overview: E.g. 4 whitespaces and a simple paragraph are interpreted as a paragraph.

**Comment by canpolat** [comment]
> Maybe also including our friend the pilcrow

The pilcrow can be added via custom CSS (see [documentation](https://docs.zettlr.com/en/core/custom-css/#visualising-line-endings))

I don't know much about CSS that's why I'm asking: would it be possible to add *all* whitespaces using CSS? If that's possible, I suppose I can send a PR to update the documentation.

**Comment by dagdrommer** [comment]
> The pilcrow can be added via custom CSS (see [documentation](https://docs.zettlr.com/en/core/custom-css/#visualising-line-endings))

Thank you very much!

> **Edit:** Aaaand, I think it would be nice to keep pilcrow separate from spaces and tabs. This is obviously about personal preference, but I like seeing all spaces and tabs in my editors but I never want to see pilcrows.

I advocate that too.

**Comment by dagdrommer** [comment]
> I don't know much about CSS that's why I'm asking: would it be possible to add _all_ whitespaces using CSS? If that's possible, I suppose I can send a PR to update the documentation.

I googled that for a while and it seems, that it is (yet) not possible to achieve that with CSS. It can be easily replaced using Java, or you can set a custom font which has a symbol for whitespaces. [Source](https://stackoverflow.com/questions/7900655/visualize-whitespaces-using-css)

Furthermore Visual Studio Code recently added this feature into their CSS-Settings. [Source](https://stackoverflow.com/questions/30140595/show-whitespace-characters-in-visual-studio-code)

**Comment by canpolat** [comment]
My googling did not turn anything much either. I suppose this needs to be implemented in code (if possible).

**Comment by boutil** [comment]
Indeed the trailing space addon fulfills only a little part of what is needed.
I found this addon [cm-show-invisibles](https://github.com/coderaiser/cm-show-invisibles), which seems to do exactly what @dagdrommer  wants.

**Comment by nathanlesage** [comment]
The plugin looks a little bit overly complicated. But I think an overlay mode will do just fine for this

**Comment by Himra** [comment]
Hello all,

thanks for the great program

The function would be helpful for me as well. 

I have long used Typora until I discovered two weeks ago Zettlr enthusiastically. 
There is a function "Show source code" I find this very helpful especially with inserted foreign text. 
It would make many presettings unnecessary and make a character exact formatting possible. 

Many thanks and greetings Himra

**Comment by dagdrommer** [comment]
Hello @Himra,
this thread is more about the formatting marks (see the post from @canpolat). The source code can be easily shown, just as in Typora, if you go to Preferences --> Display: There you can deactivate all rendering options (which is also my personal preference).

Cheers

**Comment by Himra** [comment]
Hello @dagdrommer,

I turned it off in the settings as you described, but nothing changed in the display afterwards. Even a restart did not change anything in the display of the document.
![grafik](https://user-images.githubusercontent.com/15324567/102609101-37c52c00-412b-11eb-87c8-30139f8d3bb7.png)

**Comment by dagdrommer** [comment]
Hey @Himra,
for me (on Arch Linux) these settings work perfectly, Consider reporting a reproducible bug here on github.

Beste Grüße ;)

**Comment by nathanlesage** [comment]
@Himra Are you on the latest patch 1.8.3?

**Comment by Himra** [comment]
Hello together,
I tested it again (Version 1.8.4). It was my mistake, I had expected something else. 
I expected all the characters to be visible, including the spaces and the different types of wrapping.
Maybe this is planned for the future.
The real reason on my part is when you insert texts from other sources and then want to clean them up.

Many greetings Himra

**Comment by maunzCache** [comment]
I know the issue is rather old but i'd support it. Would be nice if the application would ship with the CSS snippet which can then be activated in the settings by default. It was initially a let down for me not to have whitespaces and tabs shown in a text editor. Luckily there is a way, but i don't like that i have to do it by customizing CSS.

So thumbs up for "native" support :)

**Comment by nathanlesage** [comment]
Another 4 years til completion issue 🥳
