### ISSUE TITLE
[ENHANCEMENT] Allow save as JPG in addition to PNG in Image Paste from Clipboard dialog

### ISSUE THREAD

**Issue by 13rac1** [Zettlr/Zettlr#1127]
## Description

`save-image-from-clipboard` currently only saves PNG format images: https://github.com/Zettlr/Zettlr/blob/34d302cf66b336af7703272f90b3d4eec22c73f5/source/main/commands/save-image-from-clipboard.js#L44-L46
https://github.com/Zettlr/Zettlr/blob/34d302cf66b336af7703272f90b3d4eec22c73f5/source/main/commands/save-image-from-clipboard.js#L105

It is useful to optionally save images to JPG. I tend to use both to avoid the disk space waste of PNG when it is unnecessary. I'm currently changing the format manually after pasting.

## Proposed Changes

UI/UX options:
1. Two buttons: `Save as PNG` and `Save as JPG` on the _Insert Image from Clipboard_ dialog.
2. Radio button _Format_ on the _Insert Image from Clipboard_ dialog.
3. (simplest) Allowing `.jpg` extensions in the filename field.

Electron's `NativeImage` class supports `toJPG()`: https://www.electronjs.org/docs/api/native-image#imagetojpegquality So there is no significant work required in that regard.

![image](https://user-images.githubusercontent.com/195061/88705331-3899ea80-d0c4-11ea-87b5-9c2d1f6ee98a.png)

## Caveats

Options 1 and 2 increase the UI complexity. Option 3 creates a hidden feature, but might be the best option if the help text makes it clear and `.png` is always shown by default. All options would probably require a "JPEG Quality" option in the settings, but a 85% default is sufficient.

**Comment by 13rac1** [comment]
No bot. I will get back to this.

**Comment by 13rac1** [comment]
No bot. I will get back to this.

**Comment by nathanlesage** [comment]
I find it cute to a certain extent how everyone is hushing the bot away like some dog :D

**Comment by nathanlesage** [comment]
Done! Now, if you provide either extension, the app will save it as either PNG or JPEG, depending on the extension.
