### ISSUE TITLE
[ENHANCEMENT] Middle clicking a file should open a new tab

### ISSUE THREAD

**Issue by seagann** [Zettlr/Zettlr#1129]
### Description

The current tab behaviour, as far as I understand it, requires a file to be altered in order to keep it open in the current tab and enable the opening of new tabs.  This doesn't allow a user to open up multiple files in separate tabs quickly.

### Proposed Changes
Instead Zettlr could allow the opening new tabs with a middle click on a link or on a file in the sidebar, this would mirror the behaviour of web browsers like Firefox and Chrome that most people are already familiar with.

Alternatively/additionally, there could be an option in the right click menu that would allow the user to open the file in a new tab.

### Caveats
I don't really see any, since this doesn't add any complexity to the UI or replace an existing hotkey/behaviour

**Comment by nathanlesage** [comment]
Good thinking; as middle mouse buttons can now close tabs, so should they open them when clicking in the file list!

**Comment by seagann** [comment]
Adding the option to "open note in a new tab" to the right click menu would also be helpful for people using input devices without the ability to middle click (e.g. trackpads)

**Comment by nathanlesage** [comment]
> Adding the option to "open note in a new tab" to the right click menu would also be helpful for people using input devices without the ability to middle click (e.g. trackpads)

Good catch!
