### ISSUE TITLE
[Enhancement] Silently update the file if changes can be merged

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#1134]
Regarding #746:

Notifications for remote updates are very frustrating, especially when you haven't changed anything. Worse, if the file has actually been changed remotely, applying remote changes would delete local changes.

I suggest attempting to merge changes.

When chokidar detects a change, try doing a three-way merge (I'm pretty sure there must be a library for that). If it can be done seamlessly (e.g. there has been no change, or the remote change occured far from the place a user is editing), do it and do not disturb a user.

Otherwise show the prompt and so on.

The idea is that the user's input is infinitely important, and they should not make decisions on whether they want to lose their current or their past work.

**Comment by canpolat** [comment]
I believe when \#746 is properly fixed, there won't be a need for this complex solution (at least Zettlr will be on par with all other editors when it comes to handling remote changes). But, more importantly, I don't think silently updating the file is a good thing if there really are changes. That would mean Zettlr potentially sneaking in changes in a file without the knowledge of the user. I would classify that as a bug if I encountered in a text editor.

**Comment by nathanlesage** [comment]
What @canpolat says. Plus, I have way too high expectations for myself to try to get away with such a monkey-patch …

As I commented in #746, chokidar appears to actually choke; I have just tested out a later version, which didn't work, and will now go back to the last working version to see if it's actually the library.

**Comment by Zverik** [comment]
This is not proposed as a monkey-patch. This is a possible solution to the problem of losing data, that is outlined in the last section. I added a section to a note at home, then I started editing it at work — and got the notification on the remote change. What do I do now, to not lose neither the home work, nor the work-work?

**Comment by canpolat** [comment]
@Zverik I think most of the users (including myself) would expect Zettlr to behave as any other text editor. If the files have a conflict, text editors expect the user to take action (discard one of the versions).

> I added a section to a note at home, then I started editing it at work — and got the notification on the remote change. What do I do now, to not lose neither the home work, nor the work-work?

Isn't this an age old problem and people generally expect the "syncing software" (be it OneDrive or Git) to solve it, not the editor. When I encounter this, I generally do the following:

1. `Ctrl + A`
2. `Ctrl + C`
3. Open Notepad (or something similar)
4. `Ctrl + V`
5. `Ctrl + S`
6. In Zettlr, discard local changes and load from remote
7. Diff the text in Notepad with the text in Zettlr (and cherry-pick the changes I want)

I'm not saying this is the most elegant of workflows, but the problem occurs so rare that I can live with it. If you (or any other user, for that matter) have a workflow that presents you this problem often, then I would suggest looking into the syncing process (and not the editor). For developers, using Git is a perfect solution for these kind of scenarios. I hope my arguments (for not including merge logic in the editor) make sense to you.
