### ISSUE TITLE
Unintentional scrolling and unfolding of collapsed text sections

### ISSUE THREAD

**Issue by DavidBjelland** [Zettlr/Zettlr#1135]
## Description
I'm relatively new to Zettlr and am sometimes experiencing unintientional / automatical scolling of the text. Additionally, intentionally collapsed sections tend to "unfold" automatically after some time of working on other sections. Both issues might be related.

## Reproducing
Collapse one section (errow next to heading) and work on another one (write, collapse and unfold etc.). After some time (partly < 2 min.) the collapsed, not worked on section might unfold.

## Expected behaviour
Keep collapsed sections collapsed, it helps in terms of clariry when working on longer files.

**Screenshots**
![image](https://user-images.githubusercontent.com/63207312/88917534-3375a080-d268-11ea-8150-364d337c35b4.png)
To work on one section (in this case "Notizen"/"Einleitung"), it can be helpful to have other sections collapsed for a better overview.

## Platform
 - OS and version:
Win 10 Home, Version 1903
 - Zettlr Version:
1.7.2
 - Screen Resolution:
Total: 1920 x 1080
Used for Zettlr: 1920 x 1080 or (1920/2) x 1080

**Comment by nathanlesage** [comment]
Concerning the scrolling issue: Already confirmed, but I haven't had the time to deduct _why_ this is happening. It's either a misconfiguration on my side of CodeMirror, or it's simply that there are too many line-widgets for it to properly handle the sizing … concerning the auto-expanding, I'd have to test this, as I normally don't make use of the folding feature!

**Comment by DavidBjelland** [comment]
> Concerning the scrolling issue: Already confirmed, but I haven't had the time to deduct _why_ this is happening. It's either a misconfiguration on my side of CodeMirror, or it's simply that there are too many line-widgets for it to properly handle the sizing … concerning the auto-expanding, I'd have to test this, as I normally don't make use of the folding feature!

Thank you for your dedication.

**Comment by nathanlesage** [comment]
Hey, does it still happen in 1.7.5?

**Comment by DavidBjelland** [comment]
Nope, I've used 1.7.5 intensively for some days now and haven't encountered the same behavior again.

**Comment by xplosionmind** [comment]
Actually, I don't know if this is related to #1199, but I continue to experience this issue and I think the issue should be re-opened.

**Comment by nathanlesage** [comment]
@xplosionmind Please refer to my comment on #1199 for this.
