### ISSUE TITLE
[BUG] Zettlr not converting all images to absolute paths

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1139]
## Description
Zettlr (1.7.1) is not successfully correcting *all* relative image links to absolute links before exporting the project, resulting in Pandoc Warnings and incomplete exports.

## Reproducing
I am able to reproduce this at will on a project, but can't seem to narrow down *why* it happens, or find any rhyme or reason to the file paths that do not successfully convert, aside from the fact that they're consistent.

## Expected behaviour
All image paths should be converted to absolute links during the export process.

## Platform
 - OS and version: Windows 10 (20.04)
 - Zettlr Version: 1.7.1 (1.7.2 can't export projects, waiting on bugfix)
 - Screen Resolution: 1920x1080

## Additional information

In a sample document that's impacted there are three image links:
```
![](../../../../../zzzTrash/ImagesSept2014/Widget.png)
![](../../../../../zzzTrash/ImagesSept2014/PreEnhance.png) 
![](../../../../../zzzTrash/ImagesSept2014/PostEnhance.png)
```

Zettlr is able to display the images in the WYSIWYM editor, so it's not a file path / perms issue.

The first image always exports successfully. Breaking Pandoc processing at the end of the document reveals the following warnings, suggesting that Zettlr is not correctly setting the absolute path of these image links. 

```
[WARNING] Could not fetch resource '../../../../../zzzTrash/ImagesSept2014/PreEnhance.png': replacing image with description
[WARNING] Could not fetch resource '../../../../../zzzTrash/ImagesSept2014/PostEnhance.png': replacing image with description
```

Note that this occurs across the whole project, with some image paths being converted to absolute links and others not (i.e, not restricted to particular images or documents). While this example is 5 levels down in the folder structure, this occurs on documents in the project that are only one level down.

**Comment by Kangie** [comment]
Is there any way to get an insight into how / why Zettlr isn't converting these images? I'm a bit stuck for where to begin tracking this one down.

**Comment by nathanlesage** [comment]
Can confirm that this will be working in 1.7.3, so it was indeed also a spillover from me forgetting that `date`-variable
