### ISSUE TITLE
No Zettelkasten IDs

### ISSUE THREAD

**Issue by anthrolisp** [Zettlr/Zettlr#114]
There are no Zettelkasten IDs showing anywhere, not in the tree or document, even after attempt at manual ID regeneration. Snippets are turned on in the preferences, and ID generation there works fine. Many thanks in advance! I'm on Ubuntu 18.04

**Comment by nathanlesage** [comment]
You'd have to manually create a Zettelkasten ID for each file you would like to assign one using either the menu command or the shortcut `Ctrl+L`. Then the files will detect them and display them fine.

**Comment by anthrolisp** [comment]
It works. Thank you!
Question: If I had an outline similar to the phone pictured here (https://zettlr.com/storage/app/media/docs/zettlr_zettelkasten.png), is it possible to export such that linked files are included in the exported file?
Many thanks in advance!

**Comment by nathanlesage** [comment]
That's good to hear!

Concerning the expansion of linked notes: I have that on my mind, but won't make any promises as to when it will actually come, as I'm currently rather overworked.
