### ISSUE TITLE
Apt-get repository

### ISSUE THREAD

**Issue by ad-m** [Zettlr/Zettlr#1142]
Hello,

Have you considered creating an apt-get repository with packages for Debian-like distro?

It will also reduce the importance of the repository and reduce the expectation of PPA repository (see #361 ).

I have prepared Telegram repository on top of GitHub. It's dead simple repository https://github.com/ad-m/telegram-repository . Most of stuff is contained within Makefile:

https://github.com/ad-m/telegram-repository/blob/ee0b36b025d1494e27d9b2b8ead477b27b758162/Makefile#L15-L22

If someone would like to create a repository for Zettlr, they can copy my code and use it to publish already-existing package for Debian as apt-get repository.

As this is an open-source project, we can also ask apt-hosting like https://packagecloud.io/pricing and just upload deb package. I have no experience in this area.

Kind regards,

**Comment by nathanlesage** [comment]
Hey, thanks a lot for the info, and I'm sure we can make use of the Makefile in your repository to set up an APT-repository. However, in order to keep the issue list clean, let's move this conversation over to #361! :)
