### ISSUE TITLE
Parts of the document not correctly exported to PDF nor Word

### ISSUE THREAD

**Issue by glazcano** [Zettlr/Zettlr#1143]
## Description
When exporting my files, parts of the document get interpreted erroneously or not at all. For example, this:
![image](https://user-images.githubusercontent.com/25857401/89133790-fff77800-d4ec-11ea-8f61-08954453d32e.png)

(sorry, it's in spanish)

Looks like this when exported to PDF:
![image](https://user-images.githubusercontent.com/25857401/89133808-29b09f00-d4ed-11ea-82b7-8f2d7ddf3257.png)

I reviewed the code in Notepad++, with no obvious issues there, and also with other Markdown editors, which exported it correctly 

## Reproducing
Exporting a .md document to PDF.

## Expected behaviour
Correctly render the text
![image](https://user-images.githubusercontent.com/25857401/89133841-7bf1c000-d4ed-11ea-8a5a-bcbad6dfd1dc.png)

**Screenshots**
Screenshots already added in their respective sections

## Platform
 - OS and version: Windows 10 64 bits, v2004
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080

## Additional information
Both Pandoc and Miktex seem to be correctly installed and uptodate, as other editors dependent on them work without problems. Zettlr itself doesn't give any error messages.

**Comment by nathanlesage** [comment]
Zettlr uses Pandoc for exports, would you mind attempting to export this document using plain Pandoc in order to rule out that it's a Pandoc issue?

**Comment by glazcano** [comment]
> Zettlr uses Pandoc for exports, would you mind attempting to export this document using plain Pandoc in order to rule out that it's a Pandoc issue?

Seems to be a Pandoc issue:
- Using Pandoc from the command line gives the same result, using the most rudimentary command
`pandoc filename.md -o filename.pdf`

- Now, using the -f option to force interpretation as Github markdown, processes correctly

This behaviour was the same in my Desktop, and a fresh install of Zettlr+Pandoc+MikTex that I made in my laptop.

Anyway, if something is happening, is on Pandoc's side

**Comment by glazcano** [comment]
Zettlr and PDF export side by side

![image](https://user-images.githubusercontent.com/25857401/89233932-c1c78a80-d5b8-11ea-8f3c-0d9c8dd01106.png)

**Comment by nathanlesage** [comment]
Mh, might be related to issue #1097

**Comment by glazcano** [comment]
> Mh, might be related to issue #1097

I can replicate the error either with manual spaces in Zettlr, or writing a small .md file in Notepad and Notepad++. Same behaviour: Pandoc Markdown fails, but forcing Github Flavored Markdown works.

**Comment by nathanlesage** [comment]
Oh, yes, and it's funny because I just looked up how it's supposed to be in CommonMark, and even there I spotted one thing that lists were allowed immediately after paragraphs with no new line 😂

**Comment by nathanlesage** [comment]
I reported the issue to the Pandoc team. Let's see what they can tell us!

**Comment by glazcano** [comment]
> I reported the issue to the Pandoc team. Let's see what they can tell us!

Thanks for doing so! I'm not very well versed in Github so I didn't know how to do a post it in Pandoc's issue list while linking back to here

**Comment by nathanlesage** [comment]
Quoting the answer by @tarleb:

> The markdown reader has an extension lists_without_preceding_blankline which can be enabled to give the CommonMark behavior: `pandoc --from=markdown+lists_without_preceding_blankline -o test.pdf test.md` should give the expected result.
> 
> Nota bene: there is now (pandoc 2.10.1) a new `commonmark_x` reader which uses CommonMark rules, but also allows to enable extensions not available in commonmark; the current Markdown reader is planned to be phased out in favor of the new reader.
