### ISSUE TITLE
[FEATURE] Request for customizable WYSIWYM formatting (concerning the philosophy behind current formatting)

### ISSUE THREAD

**Issue by MushroomHunting** [Zettlr/Zettlr#1144]
## Description
I propose to allow a user level customization for the display of variance markdown elements. I know similar issues have been brought up before where people have asked for a pure WYSIWYG (remove all markdown formatting) however what I am proposing is an enchancement that stays within the existing and implemented philosophy of Zettlr's design.

**My understanding of Zettlr's meaning of WYSIWYM**: Strike a balance between pure WYSIWYG and pure WYSIWYM. I will use WYG and WYM for short.

**My argument**: This balance is an intrinsic factor of the _user_ not the _program_. Already by not showing all code for _all markdown_ options (e.g. links) the current implementation has violated, in a certain sense, the ideology behind WYM. Which is fine because Zettlr aims to strike a balance. I argue this balance should be customizable by the user.

**Justification 1**. I was drawn to zettlr initially for its excellent zettelkasten like abilities and editing interface. I use it to store and consume (read) my personal notes which include flows of thought, ideas, etc. However, I find certain markdown elements quite distracting (underscores and stars for italics and bold) and certain markdown elements not distracting (heading formats, block quotes). This is my personal preference and I find my core text to revolve around written discourse. Clearly others will have different visual priorities and hence a different personal understanding of WYM. Zettlr has enforced this by certain design criteria (links are more WYG and WYM for example). But why are just links like this? Why not have links as WYM? 

**Justification 2**. Zettlr already changes the colour of the text after formatting (hence exemplifying to the reader that this is a formatting change). So rendering the markdown formatting, e.g. "_" and "*" for italics and bold _in addition to the color change_ is two levels of formatting. I would prefer only one change of formatting (the color).

**Justification 3**. Zettlr integrates such things as latex and links as WYG and simply by clicking on the rendered item the user is exposed to the code (latex or markdown in this case). Justification 2. where Zettlrs's _color change_ is a sufficient bridge between the code level and the rendering level.

## Possible implementation
Simply have an option in the Preferences whereby a user is able to toggle the level of WYG/WYM for the major markdown options. For example, I would be able to toggle on and off between removing markdown formatting for Italics and Bold. My editor would then stop displaying _ and * for any Italics and Bold code but continue to change the color (to Zettlr's theme color) and also continue to display properly italicised and bolded text.

## Caveat
The main caveat is that this proposal seems at odds with the current WYM philosophy presented. However, I have given an explanation why it is in fact _not_ at odds with WYM but actually even more aligned with Zettlr's WYM philosphy.

## Additional Information
I have played with the experimental debug console wysiwyg toggle = true. However this is not what I have in mind: I am not asking for pure WYG.
I have also read https://github.com/Zettlr/Zettlr/issues/457#issuecomment-570902928
Please correct me if I have misunderstood the underlying design justifications behind Zettlr

**Comment by nathanlesage** [comment]
I do see the value of your proposal, and in fact to a certain degree this is already possible. You can, in fact, convert to fully WYSIWYM by disabling all renderers in the Preferences --> Settings. And adding a few more might not hurt necessarily. The problem that I see is simply that it would increase the rendering complexity, and while certainly possible, we would first need to get back to CodeMirror and improve the overall performance of the editor! But until then y'all feel free to build upon this initial thought.
