### ISSUE TITLE
[BUG] Relative Paths for Inline Images

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1145]
## Description
Zettlr does not process relative image paths for inline images

## Reproducing
1. Create a test markdown document with a line of text.
2. Drag an image to the end of the line to import it.
3. Copy the line (including image) to a new line separated by some whitespace.
4. Amend the image path so that it is relative. 
5. Copy the relative image to a new line.
6. Export the document

- Zettlr will correctly display the inline image with the absolute path. 
- Zettlr will correctly process the relative image link on its own line. 
- Zettlr will **not** process the relative path for the inline image and it will not be displayed correctly. 

## Expected behaviour
Zettlr should process relative paths for inline images.

## Platform
 - OS and version: Win 10 (20.04)
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
> Zettlr will not process the relative path for the inline image and it will not be displayed correctly.

This is the solution, thanks for pointing it out.

Offending function: https://github.com/Zettlr/Zettlr/blob/develop/source/common/util/make-img-paths-absolute.js

The regular expression currently expects images to reside on their own line, and doesn't yet support what the renderer does, that is, having images render as inline elements as stated in the CommonMark specs.

**Comment by Kangie** [comment]
Thanks for the quick and informative response @nathanlesage

**Comment by Kangie** [comment]
@nathanlesage 

I'm seeing issues where the regex function isn't replacing the path for block element images (not inline) sometimes. 

When it occurs it's consistent (Happens every time I export), until I remove the image entirely and replace it (complete with relative path). I can't find any reason for this to be happening (It's replacing all the other paths in the same markdown document / across the whole project). 

Would you like me to submit another bug? Do you have any suggestions for trying to trigger this to make it reproducible?

**Comment by nathanlesage** [comment]
> isn't replacing the path for block element images (not inline) sometimes.

Mh, I'd like to wait until I've unified the regular expressions. If it happens afterwards still, yes, please a new issue!
