### ISSUE TITLE
[ENHANCEMENT] link autocomplete with h1 title instead of YAML

### ISSUE THREAD

**Issue by pmelchior** [Zettlr/Zettlr#1146]
## Description

I like to write notes with as little overhead as possible, i.e. without YAML frontmatter. But the link autocomplete dropdown doesn't show anything other than the note id in this case

## Proposed Changes

The option "If present, use first heading level 1 instead of filename" should allow the h1 titles to be shown in the link autocomplete dropdown, just like it does in the sidebar.

## Caveats

I don't see any because this setting would simply augment YAML information in the same way as for the sidebar.

## Additional Information

I'm writing a zettelkasten and really like zettlr for its support of math and code. But the reliance on yaml goes against my working style. I much rather set title and tags only once, namely in the document. This all works fine with zettlr until I'm trying to link to other notes, for which I only see a long and useless list of IDs.

**Comment by AlejoOdgers** [comment]
I would love this too!

**Comment by nathanlesage** [comment]
And here we go!
