### ISSUE TITLE
Multiple citations plus other text in bracket 

### ISSUE THREAD

**Issue by EconomistMike** [Zettlr/Zettlr#1147]
Hi, I'm having trouble including multiple references in an in-text citation. 

I'm trying to write the in-text citation as:

> ...and in the early surveys that were issued from the 1980s onwards once it was clear that EOB had emerged as a bona fide sub-discipline of economics **(such as Jackson 1982 and Olson 1991)**.

I wrote this markdown: [such as @Jackson1982PoliticalEconomyBureaucracy and @Olson1991Bureaucracy], 

but the second reference didn't convert properly: (such as Jackson 1982, and **@Olson1991Bureaucracy**)

Apologies if I missed something basic, but could you please let me know how I can fix this? 

Thanks.

**Comment by nathanlesage** [comment]
Two questions:

Does it export properly? If so, this means that `pandoc-citeproc` does it and hence Citr should also do it.

If it doesn't: Citr (which Zettlr uses for internal display purposes) expects each portion of a citation to have a semicolon in the middle, that is:

```
[such as @Jackson1982PoliticalEconomyBureaucracy and @Olson1991Bureaucracy]
```

can be rewritten as (for example)

```
[such as @Jackson1982PoliticalEconomyBureaucracy; also @Olson1991Bureaucracy]
```

**Comment by nathanlesage** [comment]
Ah I just saw your mistake: citation keys **must** be delimited with `;`. Both Citr and Pandoc citeproc expect only one citekey per part.
