### ISSUE TITLE
[ENHANCEMENT] Default Image Description

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1148]
## Description
Images dragged from file manager into Zettlr should have the description set as file name, rather than entire file path.

## Proposed Changes
Images that are dragged from the file manager into Zettlr currently have their description text set to the entire path to the image. e.g, for an image located at `C:\ZettlrProjects\Project\Images\Image_01.jpg`, we get the output: 

`![C:\ZettlrProjects\Project\Images\Image_01.jpg](C:\ZettlrProjects\Project\Images\Image_01.jpg)`

This breaks Pandoc processing to PDF (due to unescaped `\` characters) and doesn't add any value (as the absolute path is the next value anyway). 

Ideally Zettlr should instead output: 

`![Image_01](C:\ZettlrProjects\Project\Images\Image_01.jpg)`

Stripping both the path and file extension, while providing a descriptive name for the image (assuming that the user has named their images descriptively!)

**Comment by nathanlesage** [comment]
Coming in https://github.com/Zettlr/Zettlr/pull/1096
