### ISSUE TITLE
Text to speech using Speech Synthesis API

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#115]
I noticed the latest Beta removes text-to-speech for Windows and Linux because it was non-working. I was wondering what the problem is, since text-to-speech is built into the standard JavaScript Speech Synthesis API, which "just works" on any recent browser engine on any platform (see https://caniuse.com/#feat=speech-synthesis).

Sample code (from a working version in a pure JS app I am involved with), which works on Windows, Mac, Linux:
```
var documentText = document.getElementById('myText').textContent;
var utterance = new SpeechSynthesisUtterance(documentText);
utterance.voice = getSelectedTextToSpeechVoice();
window.speechSynthesis.speak(utterance);

// Returns the selected text to speech voice object.
function getSelectedTextToSpeechVoice() {
    var selectedTextToSpeechVoiceOption = $("#textToSpeech_voices")[0].selectedOptions[0];
    var selectedVoiceName = selectedTextToSpeechVoiceOption.getAttribute("data-name");
    return window.speechSynthesis.getVoices().filter(function(voice) { 
        return voice.name == selectedVoiceName;
    })[0];
}
```
Obviously there are a few details like choosing the language for the speech synthesis, and perhaps allowing the user to choose the voice as in the function above.

**Comment by nathanlesage** [comment]
I just removed the speech submenu because it was a dedicated macOS submenu using the pre-assigned role, so on Windows or Linux these commands wouldn't do anything.

I didn't know that JavaScript itself offers a built-in Text-to-Speech engine o.O But that helps explain why the V8 is so ridiculously big.

Phew … well, I'm not sure … do you think people actually use this on Win/Linux, or whether or not there are dedicated Text-to-Speech-libraries that can do a better job?

**Comment by Jaifroid** [comment]
It's a nice capability to have, but it's not essential. Main use of Zettlr is for writing rather than reading out stuff, and I guess it's not like it's optimized for people with vision difficulties. But if your Mac-only text-to-speech engine is taking up a lot of space, then a pure JS solution is only a few lines and is cross-platform (famous last words -- of course it's always a bit more difficult than that, due to need to select and store a reading language and voice  and to provide a toolbar or interface to pause/stop/start reading). Not high priority! Other things are more important.

**Comment by nathanlesage** [comment]
> But if your Mac-only text-to-speech engine is taking up a lot of space

Well, it's baked into macOS, so I'm not shipping anything text-to-speech-related with the app, because, as you say, other things are more important =D

So, I'll close this now, but if anybody needs/wants this, please feel free to comment so I can reopen!
