### ISSUE TITLE
Mermaid filter not recognised by pandoc

### ISSUE THREAD

**Issue by hubertau** [Zettlr/Zettlr#1150]
# Description
Hi all,

Not opening this as a bug because I'm not sure if it's just something I need to alter on my system, and not to contribute to the horror of piling bugs. I'm trying to export mermaid code with a filter as described in #854, but am having some trouble.

# Reproducing
I installed mermaid-filter from https://github.com/raghur/mermaid-filter, and tested it exporting a same simple mermaid block directly from the terminal with the mermaid-filter included in the pandoc command which worked fine. Exporting the same file from Zettlr, however, with the following command, set in the 'Advanced' menu:

`pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ --filter mermaid-filter --filter pandoc-crossref $citeproc$ $standalone$ --pdf-engine=xelatex --mathjax -o "$outfile$"`

produces an error that Zettlr isn't able to find the mermaid-filter command.

Is there a way to make mermaid-filter visible to Zettlr somehow? Thank you so much in advance!

# Expected Behaviour
Correct export of mermaid code to image.

#  Platform
- OS and version: MacOS Catalina (10.15.6)
- Zettlr Version: 1.7.4
- Screen Resolution: 2560x1440

**Comment by nathanlesage** [comment]
Mh, might be that the mermaid-filter is not in the PATH, as the working directory for Pandoc is set to the directory of the file, and depending on how Electron handles thread-spawning this might create an issue. But I'm not completely sure...

**Comment by hubertau** [comment]
hm! I've checked the PATH and the mermaid-filter in the /anaconda3/bin/ directory which is exported correctly, so this remains a bit of a mystery :/

**Comment by nathanlesage** [comment]
Closing; but I just remembered that it might help to use the absolute file path to make sure Pandoc finds the filter (within the Pandoc command itself)

**Comment by xalario** [comment]
Hello,

I reopen this thread because I am experiencing the very same problem on a MacOs 12.6.3 with Zetllr 2.3.0.

A command line with the filter renders the mermaid graph correclty

`pandoc -t html -F mermaid-filter -o chapterX.html chapterX.md`

However, exports from Zettlr (using cmd-E) do not render the graph.

This is despite adding 
`filters:`
`  - mermaid-filter`

to the YAML frontmatter.

Any suggestions would be much appreciated.  

Thanks

Xavier
