### ISSUE TITLE
[BUG] Images break list levels when placed between them.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1151]
## Description
Indented lists below images are displayed as monospaced text (code)

## Reproducing
- Create a list with several list levels
- Insert an image between one list level and the next (indented) level, e.g.:
```
1. This is a list
2. This is a second list item
![Example Image](ExampleImageLocation.jpg)
    * This is another list level
```
- The list level(s?) below the image will be displayed (and output when exported) as monospaced text.

## Expected behaviour
List should continue below the image, not be marked as code / monospaced text.

## Platform
 - OS and version: Win 10 (20.04)
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080

## Additional information
This is a bit of an edge case - usually an indented line being marked as a codeblock is desired behaviour, however it's breaking lists when an image is put in the 'wrong' location, even when it would be more useful to put an image between the text and the next list level as far as the way documentation is structured.

Not sure if there's a good fix for the issue, other than working around it.

**Comment by nathanlesage** [comment]
> The list level(s?) below the image will be displayed (and output when exported) as monospaced text.

This is correct Markdown behaviour, please refer to the CommonMark specification on how list-block elements work: https://spec.commonmark.org/0.29/#lists

(TL;DR: Apparently, you need to indent the image itself, if I read the specs correctly)
