### ISSUE TITLE
[ENHANCEMENT] Paste screenshot image as a base64

### ISSUE THREAD

**Issue by teopost** [Zettlr/Zettlr#1154]
It would be interesting to be able to paste an image created with a screenshot, such as source base64.
In this way the image would be merged with the file and I would have many advantages.
For example, if I move the file to another folder I wouldn't have to worry about moving the images too.

**Comment by nathanlesage** [comment]
… but you know that this is both considered bad practice and will immensely increase the file sizes? Plus, I'm not sure if CodeMirror will be able to handle files with more than a few images added this way.
