### ISSUE TITLE
[BUG]: Markdown Rendering (_italics_)

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1157]
## Description
When Underscores are used to indicate Italics `_italic_`, and is suffixed with a character (e.g. ™) the end of the italics is ignored and Zettlr renders italics until the end of the line. Output (to HTML, PDF, etc) is not impacted.

## Reproducing
Paste the text `configuring _Google Earth_™ for use with your system.` into a new Zettlr document.

## Expected behaviour
Zettlr should behave as it does when italics are indicated using `*italic*` where this issue does not occur. 
## Platform
 - OS and version: Win 10 (20.04)
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
This is intended. From the [CommonMark specs](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis):

> Many implementations have also restricted intraword emphasis to the * forms, to avoid unwanted emphasis in words containing internal underscores. (It is best practice to put these in code spans, but users often do not.)
> 
> ```
> internal emphasis: foo*bar*baz
> no emphasis: foo_bar_baz
> ```
> 
> The rules given below capture all of these patterns, while allowing for efficient parsing strategies that do not backtrack.

**Comment by noecochetel** [comment]
### Description
I agree that internal underscores prevent any unwanted emphasis. However, I observed that emphasis occurs when such internal underscores are within a link.

### To reproduce
no emphasis: foo_bar_baz
unwanted emphasis: [foo_bar_baz.sh](path_to_foo_bar_baz.sh)

![Screen Shot 2020-12-09 at 2 13 21 PM](https://user-images.githubusercontent.com/57455039/101694969-c4376680-3a28-11eb-8dc8-3b7452701277.png)

### Suggestion
It would be great if the automatic emphasis was prevented in any filename within a link.

### Platform
- macOS Catalina Version 10.15.7
- Zettlr 1.8.1

**Comment by nathanlesage** [comment]
Fixed.

**Comment by noecochetel** [comment]
I am really impressed by your speed, thank you, your tool is amazing.
