### ISSUE TITLE
[Feature] Autosave editor state

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#1158]
## Description

My mac went to reboot, and when I opened Zettlr again, it opened files from an older editing session, not the ones I've been working on for the last three hours. I would like to continue from where I started, not having to search for these files.

## Example Workflow

1. Open some notes in tabs, work on those.
2. Force quit Zettlr (or hard restart the computer).
3. Reopen Zettlr. All the tabs should be restored.

## Caveats

I don't see any.

## Additional Information

Currently I san save contents of a note with Cmd+S, but cannot save tab state. Thus I was very puzzled to see old notes when I restarted the mac. I propose to auto-save the state every minute, and also when you press Cmd+S.

**Comment by nathanlesage** [comment]
This is deliberate, because I wanna be on the safe side: When Zettlr crashes, it doesn't save the config, and is therefore able to restore a working state. Rather, I'd like you to propose saving the open _tabs_ to this issue: #1039

**Comment by Zverik** [comment]
When _does_ it save tabs? It didn't in three hours I was using it.

**Comment by canpolat** [comment]
I think it saves the tabs when you close it (not force close).

**Comment by nathanlesage** [comment]
> When does it save tabs? It didn't in three hours I was using it.

It saves the tabs as an option in the configuration which, as I said, is only being saved on a successful shutdown. This, as well as the window dimensions and other not-that-important-things should either way not be saved in the main configuration file, but I know I'm not going to remember it if nobody adds this to aforementioned issue :D

**Comment by Zverik** [comment]
Does that mean that if I never shutdown Zettlr properly (it's started on boot, and works for months until the mac reboots from some error), the tabs will never be saved?

**Comment by nathanlesage** [comment]
Exactly. But on another note, you should never ever have your MacBook (or, for that matter, any other computer) running for months.
