### ISSUE TITLE
Broken code indents in an exported HTML file

### ISSUE THREAD

**Issue by TicTak21** [Zettlr/Zettlr#1159]
## Description
Broken code indents in an exported HTML file

## Reproducing
1) Write code block with three back-ticks '`'
2) Export file into HTML
3) Look at the indents. Starting from the second line of code every line has a indent + tab-like size indent

## Expected behaviour
All lines of code has a normal indentation. Without hidden tabs or spaces.

**Screenshots**
In editor:
<img width="395" alt="Screenshot 2020-08-04 at 17 31 55" src="https://user-images.githubusercontent.com/44474697/89306344-68bf2b80-d678-11ea-9820-e88f8b42121b.png">

In browser:
<img width="395" alt="Screenshot 2020-08-04 at 17 32 35" src="https://user-images.githubusercontent.com/44474697/89306568-b8055c00-d678-11ea-9206-cdc232114896.png">

## Platform
 - OS and version: MacOS Catalina 10.15.6
 - Zettlr Version: 1.7.4
 - Screen Resolution: 2560x1600
- Chrome Version: Version 84.0.4147.105 (Official Build) (64-bit)
- Pandoc Version: 2.9.2.1
- TeX Version: 3.14159265 (TeX Live 2020) 
- kpathsea Version 6.3.2

## Additional info
1) After exporting in pdf format, everything works as expected.
2) I've tested it in other browsers as well. Firefox, Safari. There's still an error.
3) The problem occurs also when using other languages: JS, SH, Python

**Comment by Kangie** [comment]
Can reproduce. 

The whole codeblock is contained within a `<pre>`, so each new line after the `<pre>` is declared (the first, where the codeblock opens) has the whitespace for indentation included in the line of code.

```
<body>
    <article>
    <div class="sourceCode" id="cb1"><pre class="sourceCode cpp"><code class="sourceCode cpp"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true"></a><span class="kw">enum</span> List {</span>
    <span id="cb1-2"><a href="#cb1-2" aria-hidden="true"></a>    Nil,</span>
    <span id="cb1-3"><a href="#cb1-3" aria-hidden="true"></a>    Cons(i32, List),</span>
    <span id="cb1-4"><a href="#cb1-4" aria-hidden="true"></a>}</span></code></pre></div>
    </article>
</body>
```

I'll try and have a look at the way it's generating and see what can be done. Given that it all generates within ('inline' with) the article tags, it should be indented at this level. It might be as simple as wrapping each line in a `<pre>` instead of the whole codeblock. Messy, but it'll completely avoid unintentionally pulling in whitespace!

**Comment by nathanlesage** [comment]
Looks like something up with Pandoc because as far as I know Zettlr doesn't touch those code blocks. Please report if this is not reproducible by using Pandoc directly!

**Comment by Kangie** [comment]
OK, using pandoc to directly convert a markdown document containing only: 

```
``` rust
enum List {
    Nil,
    Cons(i32, List),
}
``` `
(Sorry for excess backtick - it's not there in the source)

Results in HTML output as expected - Pandoc doesn't indent the codeblock.

I suspect this issue has to do with the way content is injected into the Zettlr html template:

```
<body>
...
  <article>
    $body$
  </article>
</body>
```

The generated content correctly replaces $body$, however as it's between the article tags in the template (and indented), we run into this issue where the `<pre>` tags catch the whitespace from indentation in addition to that specified in the codeblock.

**Comment by Kangie** [comment]
OK, Can confirm that removing indentation from the `$body$` substitution makes this behave as expected. Note that this means while the `<article>` tags are indented appropriately, the content between them is not, so there's no whitespace for the `<pre>` to pickup.

Not sure if there's a good solution - Removing indentation will do the job, but result in less readable output (at least, as far as source goes).

If there's no 'good' solution, I'm happy to throw a quick PR together to remove the indentation there, but I'd prefer to find a decent fix. @nathanlesage, any thoughts?

**Comment by nathanlesage** [comment]
So … just remove the indentation of the contents? After all, the display is more important than the source, so I'm fine with that :D

**Comment by Kangie** [comment]
Pretty much. I'll take this one on and submit a PR within the next few days; bit busy tonight. :)

**Comment by nathanlesage** [comment]
Lucky you I had VSCode open right now, hehe — please report back if something's still amiss!
