### ISSUE TITLE
Problem in 'Export project'

### ISSUE THREAD

**Issue by alvarocesar94** [Zettlr/Zettlr#116]
## Description

When I use the drop-down right-click option "Export project", the program freezes and appears the error message below.

I'm really confused since my Zettlr is up-to-date and the program never had this problem.

## Screenshot

![image](https://user-images.githubusercontent.com/48396635/54079184-a1f24100-42b6-11e9-8ca5-056f31b8c439.png)

## Platform

 - OS: Windows
 - OS Version: 10
 - Zettlr Version: 1.2.0
 - Screen Resolution: 1280x768

Your program is the best!

**Comment by nathanlesage** [comment]
uh-oh, this almost looks like the chokidar-demon is preparing his return … From what I see here, the project features don't even come close to the filesystem watchdog.

Does this error occur *immediately* after clicking export or is there a short (even if it's minimal) delay? If there's a delay then the error occurs during the export itself.

**Comment by alvarocesar94** [comment]
Nathan,

There is a 2, 3 minutes delay; the program freezes, the problem pop-up appears (and doesn't go away) and I have to kill the app (killing the app is mandatory to close the pop-up under those conditions). The PDF is created shortly AFTER I kill the application. Before the 1.1.0 version these problems did not occur.

**Comment by nathanlesage** [comment]
This is indeed weird. So just to be sure:

1. You click on PDF export
2. Nothing happens for a rather long time
3. After 2-3 minutes, above-mentioned error pops up
4. You have to kill the app
5. Afterwards, XeLaTeX will suddenly run and produce the PDF?

**Comment by alvarocesar94** [comment]
Nathan,

Yep, just like that.

**Comment by nathanlesage** [comment]
Alright, I'll have a look asap (but not this week, as I'm full with other work)! If you notice something that might be helpful, please tell me :)

(P.S.: Would you mind looking whether or not the pandoc/xelatex-processes are being started before Zettlr hangs, or only after you kill the app? Maybe one of those is the issue …?)

**Comment by nathanlesage** [comment]
Any news on this @alvarocesar94 ?

**Comment by alvarocesar94** [comment]
Hello, Nathan!

After the most recent update, the program is running flawlessly. The "Export Project" function works like a charm.

Thanks for the reply, btw.

**Comment by nathanlesage** [comment]
Perfect, thanks for the feedback! :)
