### ISSUE TITLE
[BUG]: Zettlr 'File has been modified remotely" dialog variable substitution.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1160]
## Description
"File has been modified remotely" dialog does not correctly substitute the filename for the variable in the title.

## Reproducing
Open a file in Zettlr. Modify in another Application and Save to trigger dialog.

## Expected behaviour
%s should be replaced with filename.

**Screenshots**
![Variable Substitution Issue](https://user-images.githubusercontent.com/9733178/89366110-8c867e00-d719-11ea-8f02-4530d6e0b184.png)

## Platform
 - OS and version: Win10 (20.04)
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Fixed — I accidentally switched message and title in the British translation! Thanks for spotting!
