### ISSUE TITLE
opening .rmd with zettlr triggers error.

### ISSUE THREAD

**Issue by conig** [Zettlr/Zettlr#1161]
## Description

Attempting to open .rmd with zettlr triggers error

## Reproducing

1. Set windows to open .rmd with zettlr
2. enable rmarkdown support, add '.rmd' to file extensions in sidebar
3. create .rmd file with no content
4. close and reopen zettlr
5. attempt to open the new .rmd file in the attachment sidebar

Attempting to open the .rmd file in zettlr from the attachment sidebar causes the following error:

![image](https://user-images.githubusercontent.com/12742211/89379072-7a680800-d738-11ea-95a2-76ba423e2da3.png)

renaming the file to .md allows the file to open without issue

## Platform
 - OS and version: Windows 10 v2004
 - Zettlr Version: 1.7.4

**Comment by nathanlesage** [comment]
This is because the file is being checked before the configuration provider is loaded, which is responsible for providing the corresponding setting. Will look into it!
