### ISSUE TITLE
[BUG] Removing all h1 headings with h1 file name substitution enabled does not revert display name back to filename

### ISSUE THREAD

**Issue by crbald** [Zettlr/Zettlr#1163]
## Description

Removing all headings level 1 from a file with the setting Display>"If present, use the first heading lvl 1 instead of the filename" enabled does not revert the displayed name in the sidebar and the tab bar back to the original filename.

The tab bar name also does not update until saving a file or clicking on a file in the sidebar.

## Reproducing
1) Have the setting Display>"If present, use the first heading lvl 1 instead of the filename"  enabled
2) Create a new file
3) Enter an h1 heading (displayed name should change to new heading)
4) Remove all h1 headings from file
5) The displayed name in the sidebar and tab bar remains the h1 heading
6) Disabling the setting immediately updates the sidebar name back to the file name, but not the tab bar name until clicking on a file in the sidebar or tab bar or saving a file (not necessarily the file in question)
7) Reenabling the setting does a similar thing like 6) and also restores the h1 name as displayed name which was already removed in 4)

Closing and restarting Zettlr after 4) does solve the heading problem, as the no-longer-existent h1 heading is no longer used as displayed name after restarting even with the setting being turned on (or toggled off and on again).

## Expected behaviour

Removing all h1 headings even with Display>"If present, use the first heading lvl 1 instead of the filename"  enabled should revert the displayed name back to the filename.

Also the task bar name should perhaps update at the same time (setting change) as the side bar name.

**Screenshots**

for 6): after reenabling the setting, the deleted h1 "Heading Name" is substituted for the file name "Filename" in the side bar, but not in the task bar until saving the file or clicking on a file in the sidebar or tab bar.
![grafik](https://user-images.githubusercontent.com/68776321/89421223-088dbf80-d734-11ea-9011-586d3ccb69fe.png)

## Platform
 - OS and version: Windows 10 1909
 - Zettlr Version: 1.7.4
 - Screen Resolution: 3440x1440

**Comment by nathanlesage** [comment]
Oh, interesting catch. I'll have a look!
