### ISSUE TITLE
Windows 10 - Distraction free mode is not marked in the menu

### ISSUE THREAD

**Issue by meathrel** [Zettlr/Zettlr#1164]
When enabling "distraction free mode", the menu item is not marked with a tick, unlike "night mode" or "additional information".  This is present in Windows 10.
![2020-08-05 20_09_31-](https://user-images.githubusercontent.com/2781934/89453793-a8a91000-d757-11ea-93e8-f12e5ec009c7.jpg)

**Comment by nathanlesage** [comment]
Sorry for super-late answer, tracking in #999 !
