### ISSUE TITLE
[ENHANCEMENT] Open links to markdown files within zettlr

### ISSUE THREAD

**Issue by grst** [Zettlr/Zettlr#1165]
## Description
I suggest that links to markdown files, e.g. `[rocket science](202007291826.md)` are opened within zettlr upon ctrl-clicking them. 
Currently, clicking on such a file opens a PDF of the markdown. 

I want to use this as an alternative to internal wiki links (`[[ ]]`) as I believe it has the following benefits: 
 * markdown links are standard markdown, while wiki links are not. 
 * titled links are possible
 * as a bonus, markdown links will work with GitHub pages out-of-the-box. 

## Example Workflow
To ease the workflow, it would be great if when starting to type a relative link (e.g. `./202...`) the autocomplete would 
work the same way as for wiki links. 

## Caveats
* What happens with links to markdown files that point to a files outside the current zettlr directory? Should it also be opened internally? 
* When the target file is moved, the link will be dead. To me this is totally acceptable, as all files are named by ID and within the same folder. Plus I could set-up some linting that checks for dead links if I really want to. As long as this is properly documented, I don't see any issues. 

## Additional Information
In the past there were several discussions about naming internal links (e.g. https://github.com/Zettlr/Zettlr/issues/1122, https://github.com/Zettlr/Zettlr/pull/688, https://github.com/Zettlr/Zettlr/issues/992), all of them proposing an extension to the wiki link syntax (`[[ ]]`). While I agree that it may make sense to name links in some cases, for me any solution that is not fully markdown-compliant is unacceptable. This proposal addresses the issue in a markdown-compliant way.

**Comment by enricllagostera** [comment]
I agree that this would be a very helpful way to navigate when reading, as it would not result in an ID search as the Ctrl+click flow is right now. 

I'd suggest a slightly different workflow though:

1. You create a markdown link [title](<url>), as usual.
1. If you start typing `[[` inside the <url> part of the link, the autocomplete for wiki links shows up, and you pick the file you want. 
1. After your target file, it changes the whole <url> section of the markdown link to the relative path of the picked file.

The advantage of this to me would be that you can keep the same action (typing `[[`) when you want to search for MD files with IDs. Otherwise, typing a link to any file (via `./`) would trigger an autocomplete, which might be confusing. 

The downside is that the result of the `[[` wiki link autocomplete is different depending on context, but I'd argue it fulfills the same goal of connecting the current file to that target.

**Comment by nathanlesage** [comment]
> Currently, clicking on such a file opens a PDF of the markdown.

WHAT? 😄  That shouldn't happen!

> markdown links are standard markdown, while wiki links are not.
> titled links are possible
> as a bonus, markdown links will work with GitHub pages out-of-the-box.

This is exactly as it's supposed to be!

> To ease the workflow, it would be great if when starting to type a relative link (e.g. ./202...) the autocomplete would
work the same way as for wiki links.

Does make sense to me!

> While I agree that it may make sense to name links in some cases, for me any solution that is not fully markdown-compliant is unacceptable.

Thank you for supporting my position on this! :)

***

> The downside is that the result of the [[ wiki link autocomplete is different depending on context, but I'd argue it fulfills the same goal of connecting the current file to that target.

While there's certainly a charm to that, I could imagine it would be hard to implement in an easy way … hm. I think the relative-link thingy might be better (in a way like VSCode), but please add more suggestions!

**Comment by grst** [comment]
> WHAT? smile That shouldn't happen!

I swear it does :P
(Ctrl+Click on relative markdown-link under zettlr v1.7.4 / linux 5.7.10-arch1-1)

**Comment by enricllagostera** [comment]
Plus one to the need for title-based search on autocomplete. Without that it becomes really difficult to use markdown links with ID-based filenames, which is an important workflow with Zettelkasten.

**Comment by pcarbonn** [comment]
I fully support this request.  Compatibility with github/gitlab is important to me.

**Comment by TS-CUBED** [comment]
> > WHAT? smile That shouldn't happen!
> 
> I swear it does :P
> (Ctrl+Click on relative markdown-link under zettlr v1.7.4 / linux 5.7.10-arch1-1)

Same here. I had assumed the [Text](./filename.md) link would open the file in Zettlr.

Zettlr V1.7.5 on Ubuntu Linux 20.04LTS

**Comment by TS-CUBED** [comment]
> Plus one to the need for title-based search on autocomplete. Without that it becomes really difficult to use markdown links with ID-based filenames, which is an important workflow with Zettelkasten.

Plus two. This is the one big thing I'm missing.

**Comment by vypxl** [comment]
I just tried to hack a solution for this together, I used the following idea:

- Normal markdown links still work with ctrl-k
- Upon typing `[[` (or whatever link start you specified), the autocomplete activates
- After selecting a file, zettlr replaces the wiki link with a relative markdown link

Any suggestions?

**Comment by nathanlesage** [comment]
It works beginning from 1.8! The betas already include this; I monkey-patched the support a few weeks ago!

Just found this issue again -- if there are any problems with the functionality, don't hesitate to comment here!

**Comment by vypxl** [comment]
Maybe this belongs into a new issue, but you still can't create markdown links via autocomplete. The original issue with opening the relative markdown link is fixed.
