### ISSUE TITLE
One-line math block breaks formatting

### ISSUE THREAD

**Issue by ShaddyDC** [Zettlr/Zettlr#1167]
## Description
When you open and close a math block on the same line, Zettlr doesn't seem to recognise that it's closed, and following markdown isn't properly formatted anymore.

## Reproducing
```md
# a

$$x^2$$

# b
```
In this example, `# a` is properly enlarged, but `# b` remains in the normal text size.  
![](https://i.imgur.com/ezyopqc.png)

## Expected behaviour
It works properly if you spread the block over multiple lines 
```md
# a

$$
x^2
$$

# b
```
![](https://i.imgur.com/nKuL8Pp.png)

Maybe it's just not checking for multiple `$$` in the same line for formatting but it does for maths rendering.  
```md
# a

$$x^2$$
$$
# b
```
![](https://i.imgur.com/68my232.png)

## Platform
 - OS and version: 5.7.9-1-MANJARO 
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
> Maybe it's just not checking for multiple $$ in the same line for formatting but it does for maths rendering.

Exactly, it assumes that if a line starts with $$ it's a multiline-equation, not a single-line.

**Comment by nathanlesage** [comment]
Found the reason: The multiplex mode expects $$ to be on its own line. It's as easy as removing three characters. HOWEVER, would that break anything? Are double-dollars used for anything else?

Opening the discussion.

**Comment by nathanlesage** [comment]
Cannot fix due to missing feedback. Closing unresolved for now.
