### ISSUE TITLE
[FEATURE] Custom text template

### ISSUE THREAD

**Issue by retaw106** [Zettlr/Zettlr#1169]
## Description
Insert a custom paragraph by typing an abbreviation.

Though there is a "Custom Templates" chapter in Zettlr Docs, it seems too complicated and designed for typography. What I need is a convenient way to insert some regular expressions.
The Zettelkasten ID generator can be used as a template. But it can only generate one phrase.

## Example Workflow
1. In settings, user can define a set of custom text templates.
2. One template contains two parts: abbreviations and texts. The abbreviation can be just a word (e.g. author), or a word after a symbol (e.g. &author). The text can be a paragraph, similar to the signatures in email settings.
3. (Optional) If possible, some special variables can be used in the texts, such as %Y%M%D.
4. When the user types the exact abbreviation and presses "Tab", then the abbreviation would be replaced by the pre-defined text template.
5. For example, I might like to insert the following texts by simply typing "frontmatter":
```
title: ""
keywords:
  - 
  - 
author:
  - Retaw Jin
```

## Caveats
Seldom.

**Comment by canpolat** [comment]
This seems to be a duplicate of #1009

**Comment by retaw106** [comment]
> This seems to be a duplicate of #1009

Oh. Sorry I didn't see that.
