### ISSUE TITLE
[Syntax-Highlighting] Add Org-Mode & Scribble Markup

### ISSUE THREAD

**Issue by anthrolisp** [Zettlr/Zettlr#117]
support org-mode and scribble markup [feature request]
thank you in advance!

**Comment by nathanlesage** [comment]
You mean for import/export? Org was actually supported until I needed to make space for Textbundle and Textpack — if we manage to get to 4 new modes, I could add a new row to the export options!

**Comment by anthrolisp** [comment]
Apologies, I meant for syntax highlighting inside the editor.
I've already added org as export option, unfortunately, pandoc does not support scribble.
Thanks again!

**Comment by nathanlesage** [comment]
Aaaaaah even easier. I'll get to it in the next few days!

**Comment by anthrolisp** [comment]
Awesome, thanks!

**Comment by nathanlesage** [comment]
Alright, short realisation: CodeMirror doesn't support Org-Mode built-in, and the support is … let's say marginal. I'll see to finding a way, but be prepared that this might take longer than anticipated :S

**Comment by nathanlesage** [comment]
[Clipboard-Post]

- Possible Org-Mode Plugin: https://github.com/mickael-kerjean/codemirror-orgmode

**Comment by nathanlesage** [comment]
The org-mode isn't viable, unfortunately … so I think both will be unavailable (for now). If you'd like both modes be available, please consider writing a simple mode and opening a PR to the dev-branch. I'd happily integrate it! Until then, I'll close this issue to reduce clutter!

**Comment by AtomicNess123** [comment]
Still not viable a few years later?

**Comment by nathanlesage** [comment]
That's now already possible, and even more so in 3.0. Right now you can "misuse" an existing exporter by changing the "writer" property of an existing defaults file. Then it will still be called "Docx" for example (if you use that one), and you have to change the file extension manually afterwards, but then you can do it.

The current nightly already has a much more flexible system for exports that will allow you to create a template for exporting to orgmode.

Oh, and this also means that I can close this issue for good now :D

**Comment by nathanlesage** [comment]
There is still no syntax highlighter for orgmode, but with the new Lezer package that Marijn created it may be easier to create one. As soon as there's a package available I'll pull it in!

**Comment by iburunat** [comment]
Any updates on this? Thanks!

**Comment by nathanlesage** [comment]
This issue is very old. Please consider opening a new issue. However, when it comes to supporting further syntax highlighting, I appreciate you doing some research if there even is a plugin that allows that. I don't have any bandwidth of implementing such things myself.
