### ISSUE TITLE
Pomodoro sound can be easily missed 

### ISSUE THREAD

**Issue by pvjeetze** [Zettlr/Zettlr#1174]
## Description
Thanks for this great app! 
When I use the pomodoro timer and work outside Zettlr, I frequently miss the sound notification, because it is a rather inconspicuous single 'beep' that is easily drowned in background noise (e.g. in an office) or, say, when focused during programming.   

## Proposed Changes
Maybe repeat the sound two or better three times or you could generally chose a more noticeable sound theme.

**Comment by nathanlesage** [comment]
Mh, the basic idea of the sound was precisely not to completely rip you out of any work you're doing, this is why I chose a rather soft sound. More opinions on this?

**Comment by NekoApocalypse** [comment]
I would suggest letting the user choose a local sound file. Different people have different preferences.

I use pomodoro to remind myself to get up and relax my neck & shoulders, so I want the sound to be as striking as possible and not blending into my work music. So the sound I am actually using with another pomodoro app is this one....

https://www.myinstants.com/instant/this-is-sparta/
