### ISSUE TITLE
Resizing the left sidebar makes visual cursor position change and messes with text selection

### ISSUE THREAD

**Issue by KarlClinckspoor** [Zettlr/Zettlr#1175]
## Description

Suppose there is a sentence. I then resize the left sidebar, and go back to the editor. The cursor position will be in a different place. Typing will work normally, in the correct position. Selecting text will behave very strangely. This worked both on Normal and Vim editing modes.

## Reproducing
Write a sentence. I think it has to be long enough so that when you resize the sidebar, it leads to breaking/unbreaking the line. Then click back to the editor. Try to type, and try to select text. Typing a little bit, or clicking directly normally makes it go back to behaving normally.

## Expected behaviour
Cursor position shouldn't be altered.

**Screenshots**

I recorded a short video showing me reproducing the first step of the bug. https://youtu.be/sa_CB_V4_yA

## Platform
 - OS and version: Win 8.1
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080, happens more often if the Zettlr window is smaller.

**Comment by nathanlesage** [comment]
The cursor position is not altered, but sometimes CodeMirror doesn't properly refresh, and I still don't really know why. But it's known behaviour.
