### ISSUE TITLE
Folder names getting mashed

### ISSUE THREAD

**Issue by petegubbins** [Zettlr/Zettlr#1177]
Can I please raise one issue I have noticed recently?

In the folder list on the left hand side, when a folder name is larger than the column width, the display of the folder name gets mashed. See screenshots below.

![image](https://user-images.githubusercontent.com/60329508/89706875-84b91a80-d961-11ea-9eae-edc35f23a793.png)

![image](https://user-images.githubusercontent.com/60329508/89706870-7a971c00-d961-11ea-8f15-ac30b9141f3c.png)

Apologies if this is already known.

Best wishes,
Pete

**Comment by nathanlesage** [comment]
It's not mashed, there are the directory sorting indicators overlaying in a not-so-nice fashion, someone forgot some rules for this!
