### ISSUE TITLE
HTML custom tags disables the markdown rendering

### ISSUE THREAD

**Issue by tupio** [Zettlr/Zettlr#1179]
## Description

If there are any custom tags in the HTML code the remaining markdown rendering is disabled.

## Reproducing

1. Create a markdown file
2. Add an HTML component at the start having tags, not in vanilla code. eg; <Link>  in GatsbyJS

## Expected behaviour

There are two options:( As I think )
1. Option to disable/ignore syntax check for the HTML .
2. syntax errors in HTML should not interfere with the remaining markdown.

## Platform
 - OS and version: Fedora 32
 - Zettlr Version: 1.7.2
 - Screen Resolution: 1080p

## Additional information

I'm not sure whether this a Bug or new enhancement. Kindly migrate to appropriate.

**Comment by nathanlesage** [comment]
Hey,

Would you mind adding a screenshot to illustrate what is happening? Thanks!

**Comment by tupio** [comment]
![Screenshot from 2020-08-10 16-59-32](https://user-images.githubusercontent.com/34391915/89778405-14f68b80-db2b-11ea-8870-fd7220630c6b.png)

`#` tag is not rendering here.

![Screenshot from 2020-08-10 17-00-06](https://user-images.githubusercontent.com/34391915/89778413-188a1280-db2b-11ea-8760-c4a82ecc277f.png)

Just changed `Image` to `img` (Only the first occurrence)

**Comment by nathanlesage** [comment]
Ah, this might have to do with the HTML mixed mode … so it could be that this is simply not supported (unless someone takes the time to modify that mode itself)

**Comment by nathanlesage** [comment]
So, I had a look, and indeed: The HTML mixed mode has hardcoded "self-closing" tags. If the tag is not in there (e.g. `Image`) it won't self-close. If there's a valid use-case for this, you need to make a PR to the XML-mode on the CodeMirror repository!
