### ISSUE TITLE
Window header doesn't show maximize icon

### ISSUE THREAD

**Issue by meathrel** [Zettlr/Zettlr#1180]
The maximize button on the window header doesn't shows on Windows 10.

Ensure that the Zettlr App is in non-maximised mode, the middle icon will show the "Restore down" option rather than the "maximize" option.

It should show the maximise icon when in non-maximised mode

![2020-08-10 08_35_25-Window](https://user-images.githubusercontent.com/2781934/89760512-78a99600-dae4-11ea-8913-93f7bd6c82b9.png)

## Platform
 - OS and version: Windows 10 - all latest updates
 - Zettlr Version: 1.74
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Known issue, but extremely low priority, as the functionality is given and this is just a minor quirk, which will require some changes to the strucutre.

**Comment by nathanlesage** [comment]
I think this was fixed almost a year ago or something!
