### ISSUE TITLE
[ENHANCEMENT] Clarify Setting of autocorrect style

### ISSUE THREAD

**Issue by ianhi** [Zettlr/Zettlr#1181]
## Description
In settings > Autocorrect there is a toggle between word style and libreoffice style. 
![image](https://user-images.githubusercontent.com/10111092/89812602-5dec1700-db0e-11ea-8562-8353af652a80.png)
When confronted with this I realized that I do not actually know what the differences between these options are.

## Proposed Changes
Similar to the changes propsoed in https://github.com/Zettlr/Zettlr/issues/1176 I suggest changing the primary text on each option to describe the behavior. The word/libreoffice description could be kept in a parenthetical after the description:
Sort of like this
- [ ] Autocorrect will ___ (word style)
- [x] Autocorrect wil ___ (libreoffice style)

**Comment by ianhi** [comment]
Oooh and one more thing. I also propose explanatory text for what I would be selecting with `Quick Select` am I choosing the dictionary to be used? If yes how does that interact with my choices from the spellchecking tab?

**Comment by nathanlesage** [comment]
Closed sometime in between the road to 2.0.
