### ISSUE TITLE
Symantec Security Risk Found and Blocked the application from install.

### ISSUE THREAD

**Issue by dangsonbk** [Zettlr/Zettlr#1183]
## Description
Security risk detected: WS.Reputation.1

## Reproducing
Download Zettlr-1.7.4.exe from homepage

## Expected behaviour
Can install application

**Screenshots**
![image](https://user-images.githubusercontent.com/6972607/89854143-559ee500-dbbd-11ea-84ba-dbb6321ba581.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.4

## Additional information
Symantec Endpoint Protection: Version 14 (14 RU1 MP2) build 3929

**Comment by Kangie** [comment]
Not a bug with Zettlr. 

Symantec/NortonLifeLock `WS.Reputation.1` basically indicates that the file is unknown to Endpoint Protection (hasn't been downloaded / used by enough customers). 

There is no longer a mechanism for submitting your program to be whitelisted, and no easy solution to this issue from a developer standpoint.

Talk to your IT department and see what they can do to assist you.

**Comment by nathanlesage** [comment]
What @Kangie says – currently a lot of AntiVir software companies are rather harsh on software, and to be whitelisted by them purely depends upon these companys's goodwill … we do have code signing in place though, but it may very well be that your IT department itself goes for extra-security. I know that other Zettr users had their IT department add Zettlr as a default application company-wide, so talking to them as Kangie suggests might do the trick!
