### ISSUE TITLE
[BUG]: Repeated Image attributes hidden by image preview

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1184]
## Description
If image attributes (e.g. size [height/width]) for an image are repeated, the repeated block is hidden by image preview.

## Reproducing
Create a test document, insert an image, and set something like the following: 
```
(..\images\Button.png){ height=16 width=16 }{ height=16 width=16 }
```
When you click away from the image, both image attribute blocks are hidden, however the second (non-visible) block will be processed by Pandoc as text and displayed in your output (tested HTML, PDF).

## Expected behaviour
Only one attribute block should be hidden when the image is switched to preview.

## Platform
 - OS and version: Win10 20.04
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
… probably works with the new image regular expression, so I'd like to ask you to wait for the next patch in order to verify this.

However — why would you want to add two of the same class blocks in the first place …?

**Comment by Kangie** [comment]
> why would you want to add two of the same class blocks in the first place …?

I didn't want to, I manually appended the class block to one image for testing, and then regex find and replaced the rest, resulting in a duplicate. I got a bit confused when it turned up in my output, but was not visible in the editor, so decided to file a bug around the undesired behaviour. 

When the new regex is in I'll test and update here. :)

**Comment by nathanlesage** [comment]
> then regex find and replaced the rest

That is good to know, I'll have another check at the regex just to be sure!

**Comment by Kangie** [comment]
> > then regex find and replaced the rest
> 
> That is good to know, I'll have another check at the regex just to be sure!

To clarify, I used an external editor to do the find and replace across the whole project, resulting in the duplicate. Totally my fault!
