### ISSUE TITLE
[DEVELOP] Migrate to TypeScript

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#1186]
With #1060 support for typescript is added. The long-term goal is to fully migrate the code base to typescript.

As part of this:
- [ ] Convert require statements to imports
- [ ] Fix ESlint warnings: tracked at https://github.com/Zettlr/Zettlr/issues/1185 in more detail
- [ ] Check if all global objects are needed indeed, and add proper typing: https://github.com/Zettlr/Zettlr/pull/1060#discussion_r467470696

**Comment by nathanlesage** [comment]
Sometimes it helps to scroll through old issues: Already done! The TypeScript-migration of the Vue-parts is covered by a separate issue.
