### ISSUE TITLE
Emails are not rendered

### ISSUE THREAD

**Issue by Shandi97** [Zettlr/Zettlr#119]
Hello. I have one file which contains emails, recently when opening said file I've noticed that they are not rendering correctly or more precisely they are not appearing at all.

![zettlr mail issue](https://user-images.githubusercontent.com/43752302/54625703-1162f000-4a70-11e9-9192-d54d9fef3cc8.gif)

**Comment by nathanlesage** [comment]
Yes, I noticed that problem this morning, and I already have an idea why it happens — there's a problem in the regular expression detecting these, so my fantastic solution to simply steal the RegEx from the underlying mode wasn't so fantastic after all.

I've got extremely limited time currently, but I try to get to it asap.

Until then, the **workaround**: Simply go to the Settings -> Display -> Uncheck "Render links"

**Comment by nathanlesage** [comment]
Found the bug, it was literally just a wrong number!
