### ISSUE TITLE
Zettlr stops formating headings after a heading containing less-than AND greater-than signs

### ISSUE THREAD

**Issue by par4dise** [Zettlr/Zettlr#1192]
##  Description
Zettlr stops formatting headings after first encountered heading containing at least a less-than ("<") AND a greater-than (">") sign. After that, headings are not formatted anymore. Neither they appear in the ToC available on the toolbar.
See screenshots to see exactly where and how it occurs.

## Reproducing
Insert both "<" and ">" signs in the same title, whether it be h1, h2, h3...

## Expected behaviour
Display titles properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/3480636/89910359-69177380-dbf0-11ea-8191-68e37716c7d3.png)
*Case 1: both less-than AND a greater-than signs are present, then titles are not formatted anymore*

![image](https://user-images.githubusercontent.com/3480636/89911157-65382100-dbf1-11ea-9e07-a4033e0b7171.png)
*Case 2: only greater-than sign, formatting works*

![image](https://user-images.githubusercontent.com/3480636/89911262-813bc280-dbf1-11ea-8b13-5499e945c9dc.png)
*Case 3: only less-than sign, formatting works*

## Platform
 - OS and version: Win10 Pro 19041.388
 - Zettlr Version: 1.7.4
 - Screen Resolution: 2560x1440

**Comment by nathanlesage** [comment]
This is because you also have the ability to add HTML tags to the file, which in general need to be closed, so you need to escape those with backslashes (or wrap them in back ticks)
