### ISSUE TITLE
Zettlr breaks when deleting a previously existing file with unsaved changes

### ISSUE THREAD

**Issue by sesi200** [Zettlr/Zettlr#1194]
## Description
I found a strange way to stop any file-system related operations (read, write, new) from working. Probably quite low-prio due to the complicated steps to reproduce.

## Reproducing
* Create file with dummy content. Example: test.md, content; "arst"
* Close and reopen Zettlr with test.md open. If test.md is not open the bug does not happen.
* Edit test.md in some form (type random characters)
* Delete test.md without saving changes. When saving the canges first, reproduction is unreliable.

## Observed behaviour
* test.md stays open in the editor, is deleted in the file system view
* cannot close test.md in the editor, stays as a ghost file until Zettlr is restarted
* cannot open or save any other file either
* Closing Zettlr works only via Alt+F4, the red X does not work anymore

## Expected behaviour
* (unsaved) test.md gets deleted and closed in the editor
* Zettlr keeps working

## Platform
 - OS and version: Win 10
 - Zettlr Version: latest, 1.7.5
 - Screen Resolution: 1080p

**Comment by nathanlesage** [comment]
Just to clarify: the file is being deleted on the file system and the internal state of Zettlr is wrong, as the file is a ghost file, as you say?

**Comment by sesi200** [comment]
Yes, the file is deleted on the file system and disappears from the file overview in Zettlr, but the tab with the file content stays open.

**Comment by nathanlesage** [comment]
Does this still happen with the 1.8 beta?
