### ISSUE TITLE
[BUG]: UTF Byte Order Mark displayed as content in MarkDown files.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1198]
## Description
Files with a UTF-8 / 16 / 32 [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) (BOM) (hex `0xEF 0xBB 0xBF` for UTF-8, `0xFE 0xFF` [big endian] or `0xFF 0xFE` [little endian] for UTF-16/32) at the beginning of the file have this displayed in Zettlr as one or more characters.

## Reproducing
Generate a file with a UTF-8/16 BOM at the beginning of the file and open it in Zettlr.

## Expected behaviour
The BOM should be retained in the text document (if present) to signal that the following text is UTF-# encoded, but it should not (under any circumstances) be displayed as a character in the editor, and should not be edited unless the encoding of the MarkDown file is modified.

**Screenshots**
UTF-8:
![UTF-8](https://user-images.githubusercontent.com/9733178/90362750-af634b80-e0a4-11ea-8e44-e1504736fec0.png)

UTF-16:
![UTF-16](https://user-images.githubusercontent.com/9733178/90363116-6c55a800-e0a5-11ea-88c8-102e81c85f60.png)

## Platform
 - OS and version: Win10 20.04
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920x1080

## Additional information
[UTF-8 Test](https://github.com/Zettlr/Zettlr/files/5082440/test.zip) is a zip file containing an example MarkDown file with UTF-8 BOM. 

[UTF-16 Test](https://github.com/Zettlr/Zettlr/files/5082446/test2.zip) is a zip file containing an example MarkDown file with UTF-16 BOM - This is also standard for UTF-32, but rarely used.

Note that UTF-16 BOM example that I created on a lark (my content is all UTF-8) is *really* bad. I don't know where all of the extra characters came from, and they aren't in the source document. If I had to take a guess, I'd say that Zettlr is ignoring the UTF-16 encoding, and attempting to decode as UTF-8, putting a whitespace character `00` between each legitimate character, because UTF-16 encodes (e.g. 'T') as `00 54`, resulting in a 'doubling' of characters through odd characters when the file is read by Zettlr.

Of note is that the UTF BOM is not visible in UTF-8 or 16 flavours within either Notepad, Wordpad, or VS Code - I had to dig out a hex editor to work out why these funny characters were showing up in Zettlr and what they are!

If I'm on the right track, let me know and I'll split this into two bugs: One for (the lack of) UTF-16 support, and the other for UTF-8 BOM issues.

**Comment by nathanlesage** [comment]
This is not a bug, this is expected behaviour from CodeMirror. A [quote from the docs](https://codemirror.net/doc/manual.html#option_specialCharPlaceholder):

> A regular expression used to determine which characters should be replaced by a special placeholder. Mostly useful for non-printing special characters. The default is `/[\u0000-\u001f\u007f-\u009f\u00ad\u061c\u200b-\u200f\u2028\u2029\ufeff\ufff9-\ufffc]/`

This default also includes the BOM characters and in general I do like the idea of having non-printable characters displayed so you see when something seems to be amiss in your document.

How relevant is this issue? I personally see not necessarily a reason for building into the application the ability to distinguish UTF-16 byte order marks from UTF-8 which is the default. Is there a usecase where retaining UTF-16 is paramount that does affect quite a group of people?

Nota bene: Implementation should be fairly easy to implement these BOM functionality, stored in the file's metadata, and written back into the file on save, but internally, Zettlr will always use UTF-8, as it makes most sense. The question would only be how to convert UTF-16 into UTF-8 using node, but maybe it's simply a configuration setting.

**Comment by Kangie** [comment]
Happy to amend this issue to be an enhancement.

The BOM should be displayed as a non-printable character if it appears within the document, so that behaviour is fine. Maybe it should just not appear if it's the first bytes in the file?

As for relevance, The UTF-8 BOM displaying at the beginning of the file is undesirable. I'm not so concerned about UTF-16, I just tested it for completeness sake. It looks like node can handle reading and encoding UTF-16 files natively via `{ encoding: }` params in `fs.readFileSync` and `fs.writeFileSync`, I haven't done any more digging though.

I don't think that there's a use case where keeping the file as UTF-16 would cause any issues, as I understand it the biggest benefit for using UTF-16 is for non-European languages where it takes more space to encode characters in UTF-8 - I'm not an expert on text encoding though!

**Comment by Kangie** [comment]
Thinking on it some more, I'd suggest a bug and an enhnacement:

Bug: Byte Order Mark incorrectly displayed if it occurs at beginning of file.

I'd consider displaying the BOM (outside of its occurrance in body content) an issue, particularly as (and especially if working on existing content) the BOM should not be modified without explicit user authorisation. Displaying it as a non-printable character at the beginning of the document instead breaks heading rendering (because your first heading will likely start immediately after the BOM in a project file), among other things. I also wouldn't expect the 'average' user to have any idea what the BOM is, or why it's appearing at the beginning of every one of their files!

Enhancement: Handle opening of UTF-16 files (low priority).

What are your thoughts? I'm happy to raise a separate enhancement for UTF-16 to keep this issue focused.

**Comment by Kangie** [comment]
An additional impact: If you create a newline from one that begins with a BOM, the newline will begin indented by one space.

It's hard to notice that everything after your top-level-heading in a file is indented!

**Comment by Kangie** [comment]
Another note: While Pandoc handles UTF8 BOM's just fine... if they're at the start of the file, when Zettlr concatenates a project it includes the BOM as a text character, breaking heading formatting. 

In the short term I'm just going to manually remove the BOM from all files in my project to prevent this, but as the BOM is part of the UTF-8 standard, even if it's not commonly encountered, we should handle it.

**Comment by nathanlesage** [comment]
Sooo, after a long time, I've just had the motivation to implement this.

How this is working:

1. On each read of any file, the contents are tested for the existence of a BOM. Took all available BOMs from Wikipedia in the hope of the list being complete
2. If the contents are loaded for ingestion into the editor, the BOM-length is being removed from the string
3. If the file is being written, the BOM is re-added again

This way, the feature works like the linefeed detection: If it's there, it's retained, but nothing else.
