### ISSUE TITLE
Enhancement: Make URLs clickable

### ISSUE THREAD

**Issue by sahil48** [Zettlr/Zettlr#12]
Please enable URLs in the document to be clickable so it is easy to open up the linked website.

**Comment by nathanlesage** [comment]
This is already possible, by holding the shift key while clicking on the link (currently, the clicking on the caption itself will not do anything).

As for the future: I have successfully implemented inline image previewing, and I will also render links directly in the same manner, which will then work way better than Shift-clicking them. So be prepared!
