### ISSUE TITLE
Mermaid flowchart nodes are cropping the text

### ISSUE THREAD

**Issue by carregal** [Zettlr/Zettlr#1204]
## Description
Mermaid.js seems to be cropping the text from some nodes in flowchart mode ("graph")

## Reproducing
1) Create a new document
2) Add a mermaid graph like this

```mermaid
graph LR
Factories-->Distributor
Distributor-->Retail
Retail-->Consumer
```

3) Check if all node labels are displaying the full word

## Expected behaviour

The expected behavior would be to always see the full node label texts (see example below)

**Screenshots**

Zettlr version of the above graph:
![image](https://user-images.githubusercontent.com/55634/90678855-a8b80e00-e235-11ea-8902-6ef9c4ddae1d.png)

Mermaid online version of the above graph
![image](https://user-images.githubusercontent.com/55634/90679153-25e38300-e236-11ea-8912-400a642a0801.png)

## Platform
 - OS and version: Mac OS Catalina
 - Zettlr Version: 1.7.5
 - Screen Resolution: N/A

## Additional information

Mermaid Live URL
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbkZhY3Rvcmllcy0tPkRpc3RyaWJ1dG9yXG5EaXN0cmlidXRvci0tPlJldGFpbFxuUmV0YWlsLS0-Q29uc3VtZXJcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0IiwidGhlbWVWYXJpYWJsZXMiOnsiYmFja2dyb3VuZCI6IndoaXRlIiwicHJpbWFyeUNvbG9yIjoiI0VDRUNGRiIsInNlY29uZGFyeUNvbG9yIjoiI2ZmZmZkZSIsInRlcnRpYXJ5Q29sb3IiOiJoc2woODAsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsInByaW1hcnlCb3JkZXJDb2xvciI6ImhzbCgyNDAsIDYwJSwgODYuMjc0NTA5ODAzOSUpIiwic2Vjb25kYXJ5Qm9yZGVyQ29sb3IiOiJoc2woNjAsIDYwJSwgODMuNTI5NDExNzY0NyUpIiwidGVydGlhcnlCb3JkZXJDb2xvciI6ImhzbCg4MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJwcmltYXJ5VGV4dENvbG9yIjoiIzEzMTMwMCIsInNlY29uZGFyeVRleHRDb2xvciI6IiMwMDAwMjEiLCJ0ZXJ0aWFyeVRleHRDb2xvciI6InJnYig5LjUwMDAwMDAwMDEsIDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxKSIsImxpbmVDb2xvciI6IiMzMzMzMzMiLCJ0ZXh0Q29sb3IiOiIjMzMzIiwibWFpbkJrZyI6IiNFQ0VDRkYiLCJzZWNvbmRCa2ciOiIjZmZmZmRlIiwiYm9yZGVyMSI6IiM5MzcwREIiLCJib3JkZXIyIjoiI2FhYWEzMyIsImFycm93aGVhZENvbG9yIjoiIzMzMzMzMyIsImZvbnRGYW1pbHkiOiJcInRyZWJ1Y2hldCBtc1wiLCB2ZXJkYW5hLCBhcmlhbCIsImZvbnRTaXplIjoiMTZweCIsImxhYmVsQmFja2dyb3VuZCI6IiNlOGU4ZTgiLCJub2RlQmtnIjoiI0VDRUNGRiIsIm5vZGVCb3JkZXIiOiIjOTM3MERCIiwiY2x1c3RlckJrZyI6IiNmZmZmZGUiLCJjbHVzdGVyQm9yZGVyIjoiI2FhYWEzMyIsImRlZmF1bHRMaW5rQ29sb3IiOiIjMzMzMzMzIiwidGl0bGVDb2xvciI6IiMzMzMiLCJlZGdlTGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsImFjdG9yQm9yZGVyIjoiaHNsKDI1OS42MjYxNjgyMjQzLCA1OS43NzY1MzYzMTI4JSwgODcuOTAxOTYwNzg0MyUpIiwiYWN0b3JCa2ciOiIjRUNFQ0ZGIiwiYWN0b3JUZXh0Q29sb3IiOiJibGFjayIsImFjdG9yTGluZUNvbG9yIjoiZ3JleSIsInNpZ25hbENvbG9yIjoiIzMzMyIsInNpZ25hbFRleHRDb2xvciI6IiMzMzMiLCJsYWJlbEJveEJrZ0NvbG9yIjoiI0VDRUNGRiIsImxhYmVsQm94Qm9yZGVyQ29sb3IiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJsYWJlbFRleHRDb2xvciI6ImJsYWNrIiwibG9vcFRleHRDb2xvciI6ImJsYWNrIiwibm90ZUJvcmRlckNvbG9yIjoiI2FhYWEzMyIsIm5vdGVCa2dDb2xvciI6IiNmZmY1YWQiLCJub3RlVGV4dENvbG9yIjoiYmxhY2siLCJhY3RpdmF0aW9uQm9yZGVyQ29sb3IiOiIjNjY2IiwiYWN0aXZhdGlvbkJrZ0NvbG9yIjoiI2Y0ZjRmNCIsInNlcXVlbmNlTnVtYmVyQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvciI6InJnYmEoMTAyLCAxMDIsIDI1NSwgMC40OSkiLCJhbHRTZWN0aW9uQmtnQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvcjIiOiIjZmZmNDAwIiwidGFza0JvcmRlckNvbG9yIjoiIzUzNGZiYyIsInRhc2tCa2dDb2xvciI6IiM4YTkwZGQiLCJ0YXNrVGV4dExpZ2h0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0RGFya0NvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dE91dHNpZGVDb2xvciI6ImJsYWNrIiwidGFza1RleHRDbGlja2FibGVDb2xvciI6IiMwMDMxNjMiLCJhY3RpdmVUYXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwiYWN0aXZlVGFza0JrZ0NvbG9yIjoiI2JmYzdmZiIsImdyaWRDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQmtnQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JvcmRlckNvbG9yIjoiZ3JleSIsImNyaXRCb3JkZXJDb2xvciI6IiNmZjg4ODgiLCJjcml0QmtnQ29sb3IiOiJyZWQiLCJ0b2RheUxpbmVDb2xvciI6InJlZCIsImxhYmVsQ29sb3IiOiJibGFjayIsImVycm9yQmtnQ29sb3IiOiIjNTUyMjIyIiwiZXJyb3JUZXh0Q29sb3IiOiIjNTUyMjIyIiwiY2xhc3NUZXh0IjoiIzEzMTMwMCIsImZpbGxUeXBlMCI6IiNFQ0VDRkYiLCJmaWxsVHlwZTEiOiIjZmZmZmRlIiwiZmlsbFR5cGUyIjoiaHNsKDMwNCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGUzIjoiaHNsKDEyNCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIiwiZmlsbFR5cGU0IjoiaHNsKDE3NiwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU1IjoiaHNsKC00LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTYiOiJoc2woOCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwiZmlsbFR5cGU3IjoiaHNsKDE4OCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

**Comment by carregal** [comment]
Anyone else can reproduce this bug?

**Comment by threecgreen** [comment]
I get a similar issue where each node's box does not expand to fit the label text. ![label overflow image](https://user-images.githubusercontent.com/17754110/112681553-e8cf1700-8e3c-11eb-924f-4c90dceda43f.png) 

## Code
```mermaid
graph LR
List --> A[Node] --> B[Node] --> C(Node) --> D(Node)
List --> D(Node)
```

## Platform
* OS: Linux and Windows
* Zettlr version: 1.8.7

**Comment by trwa** [comment]
> 
> 
> I get a similar issue where each node's box does not expand to fit the label text. ![label overflow image](https://user-images.githubusercontent.com/17754110/112681553-e8cf1700-8e3c-11eb-924f-4c90dceda43f.png)
> ## Code
> 
> ```
> graph LR
> List --> A[Node] --> B[Node] --> C(Node) --> D(Node)
> List --> D(Node)
> ```
> 
> ## Platform
> 
>     * OS: Linux and Windows
> 
>     * Zettlr version: 1.8.7

Same issue here.

## Platform
* Zettlr Version: 1.8.7
* System: win32 10.0.19042 (architecture: x64)

**Comment by trwa** [comment]
By looking through [mermaidjs documentation](https://mermaid-js.github.io/mermaid/#/Setup) a quick workaround would be to prepend the following directive to each block:

`%%{init:{'flowchart':{'htmlLabels':false}}}%%`

Indeed it works:

```
%%{init:{'flowchart':{'htmlLabels':false}}}%%
graph LR
List --> A[Node] --> B[Node] --> C(Long text Node) --> D(Node)
List --> D(Node)
```
![immagine](https://user-images.githubusercontent.com/74215708/114170528-572ed180-9933-11eb-8d58-285ae01d38bb.png)

I'm afraid I am not experienced enough to propose a more general solution though...

# Platform
* Zettlr Version: 1.8.7
* System: win32 10.0.19042 (architecture: x64)

**Comment by trwa** [comment]
Version 1.8.8 (4d72f9c) seems to have fixed.

It was probably related to the out-of-date Electron version... Shall we close this?

**Comment by threecgreen** [comment]
Yeah it's fixed for me on 1.8.8 too

**Comment by nathanlesage** [comment]
Uhm … okay? Nice, I'd say, although I have changed literally nothing :D But glad it's off the bucket list now!

**Comment by galicjok** [comment]
The problem occurs when a text is scaled e.g 150% in System->Display setting. With 100% it works correctly
