### ISSUE TITLE
Deleting files has no effect

### ISSUE THREAD

**Issue by vonloxley** [Zettlr/Zettlr#1205]
## Description
Deleting files doesn’t work.

## Reproducing
1. Right click on a file in the sidebar.
2. Chose delete.
3. Confirm.
4. The entry stays in the sidebar.
5. The file remains in the filesystem.

## Expected behaviour
The file should be deleted.

**Screenshots**
[Screencast.zip](https://github.com/Zettlr/Zettlr/files/5101814/Screencast.zip)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.5 (happens since 1.7)
 - Screen Resolution: 

## Additional information
The file resides on a mounted network share.

**Comment by Kangie** [comment]
Unable to replicate. Works fine for me. 

Zettlr 1.7.5, Win10 20.04.

**Comment by Kangie** [comment]
Upon further testing: 

Behaves as expected in Project mode - files are removed from the project folder structure in Zettlr & on Disk. 

Also works as expected in directories that are not projects.

For 'Files' that are opened individually, They are not removed from the UI (bug), but are successfully removed from the Disk.

**Comment by vonloxley** [comment]
If you need any more info, just tell me. Meanwhile:
[Screencast.zip](https://github.com/Zettlr/Zettlr/files/5101814/Screencast.zip)

**Comment by nathanlesage** [comment]
Does this still happen in the 1.8.x-series?

**Comment by vonloxley** [comment]
Yes, it happens with alpha-2.

**Comment by nathanlesage** [comment]
> For 'Files' that are opened individually, They are not removed from the UI (bug), but are successfully removed from the Disk.

I just removed it shortly thereafter. I now only know what that meant, but yes, I fixed precisely that by accident a few days ago!
