### ISSUE TITLE
Pressing TAB indents line no matter where cursor is located within line

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1206]
## Description
Since **1.7.5**, pressing TAB just indents the whole line, no matter where the cursor is positioned.

## Reproducing
1. Place the cursor somewhere within a line
2. Press TAB
--> The whole line will be indented

## Expected behaviour
Only indent a particular line if the cursor was before the first character of that line. For any other cursor position _within_ the line, simply insert TAB.

## Platform
 - OS and version: Linux Ubuntu 20.04
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920x1080

## Additional information
This was not an issue in **1.7.4**.

**Comment by nathanlesage** [comment]
But at least the editor does not insert TAB characters anymore … but yeah, I see where this is coming from.

**Comment by Kangie** [comment]
I'm going to be honest, I like the new behaviour; it's quite useful when working within lists as far as adjusting the list levels / indentation goes, and I very (very) rarely need to insert a literal tab character. 

Could this be toggle-able? If not, could this behaviour exist when within a list?

**Comment by nathanlesage** [comment]
I just found another issue that wanted the tab key to indent regardless of the position within the line :D And, giving it further thought: This is perfect behaviour, so I am going to close this. There is, after all, no reason for using TAB characters within your texts either way, so this is preferred behaviour.
