### ISSUE TITLE
Footnotes do not work as expected in 1.7.5

### ISSUE THREAD

**Issue by pipik1199** [Zettlr/Zettlr#1209]
## Description
Entering a footnote in Zettlr produces an output in OST that is just a number for the footnote and no footnote body

## Reproducing
Create a footnote in Zettlr
Export it to OST
Check the resulting output for accuracy

## Expected behaviour
Produce a superscripted number where the footnotes occurs in the text and have the body of the footnote at the bottom of the page

**Screenshots**

## Platform
 - OS and version:
 - Zettlr Version:
 - Screen Resolution:

**Comment by nathanlesage** [comment]
There is no output format OST, did you mean ODT? ODT exports footnotes just fine.

**Comment by pipik1199** [comment]
I did mean ODT, and the export works on Windows.  Not on the Mac, where it
has the behavior I described.

Thanks, Dan Gordon

**Comment by nathanlesage** [comment]
Alright, I tested it on macOS, but couldn't reproduce – anyone else having this issue?

In the meantime: Would you mind testing it out with some form of "dummy" document? Maybe it's an issue with the document itself, some small typo that's hard to spot?

**Comment by pipik1199** [comment]
Thanks for checking!  I'll look at it again on my system.  I will check it
out with a dummy document as well.

Dan Gordon
