### ISSUE TITLE
Memorize Sort Order

### ISSUE THREAD

**Issue by davidbosman** [Zettlr/Zettlr#121]
## Description
Have the app memorize the sort order after relaunching the application. And if possible memorize it for each folder independantly.

Depending the project I'm working on, I can have different expectations as ordering the content of a folder is concerned.

## Reproducing
Set an order, quit the app: order is back to default.

## Expected behaviour
Once a sort order has been selected, the app should keep that in memory, for each folder. 

## Platform
 - OS: macOS Mojave, Windows 10
 - Zettlr Version 1.2.0

**Comment by nathanlesage** [comment]
See #120, but here a short summary: I see the benefits and would like to do, but for my psychological well-being, I need some more convincing that this is really okay. I'm still traumatised by the amount of useless files I discovered from using Ulysses for some months 🙈

**Comment by davidbosman** [comment]
I can't see useless files at all when using Ulysses, but I only use it with iCloud (no external folder). Ditto when I export: everything is fine, or at least it looks like.

As far as needing more convincing, I'll try: 

* It's somethign I really use all day long working on certain texts (mostly longish fiction).  And that option would be great coupled with the "project" fucntion: having 1 file perchapter, sorted in whatever order you fancy... Thinking of that, shouldn't it be possible to allow 'Manual sorting' in Projects only, and so store the sorting data in the already existing .project file? *No new mess* at all plus a happy user as a bonus ;)

**Comment by nathanlesage** [comment]
Alright, to not confuse other observers, let's keep this discussion here =D

My reservations are mainly me pathologically sticking to "cleanness". And every app-specific folder is somewhat "dirty". But I see that I'm probably the only one whining about small Dot-files in the directories, so maybe it's all much ado about nothing.

What I think would be great is to keep it in one file. This would mean, that Zettlr from whenever I manage to include this, would always create one `.ztr-dir` (or whatever) file inside each directory that you open with Zettlr. And in that there would be all virtual directories, the project settings and the sorting stuff.

**Comment by davidbosman** [comment]
That sounds great 👍

**Comment by ploum** [comment]
Don't know if you consider the case where it's nice to have "manual" ordering of files. Especially useful when working on fictions so you can reorder chapters.

**Comment by nathanlesage** [comment]
Yes, manual sorting is also on the agenda, don't worry!
