### ISSUE TITLE
Hide left sidebar 

### ISSUE THREAD

**Issue by stevenfang1997** [Zettlr/Zettlr#1211]
## Description
I sometimes use split screen to take note on Zettlr while read PDF files. It would be convenient to have the ability to hide left sidebar. I know you can use focus mode to achieve this, but personally I find focus mode made the "unfocused" text hard to read and it's not very practical in my case.  

## Proposed Changes
The ability to hide left sidebar, or add an extra option to make all text "normal" under focus mode.

**Comment by canpolat** [comment]
You can modify the focus mode behavior in your settings.

![image](https://user-images.githubusercontent.com/459891/91209302-cc82c480-e70b-11ea-8781-bcb34a31b833.png)

**Comment by stevenfang1997** [comment]
Thanks a lot! Issued solved ;)
