### ISSUE TITLE
render SVG

### ISSUE THREAD

**Issue by SchrodingerZhu** [Zettlr/Zettlr#1212]
## Description
render HTML block with SVG instead of showing the 

## Additional Information
Typora can be an example of doing this, but it hides the code automatically when it is not being edit.

**Comment by Kangie** [comment]
@SchrodingerZhu It's a little unclear what you're asking for here. SVG images show up properly for me when dragged and dropped, so it's not SVG image rendering in general. 

Are you asking for inline svg images in HTML to be rendered?

Can you provide us with a screenshot demonstrating the current behaviour vs desired (e.g. Typora)?

**Comment by nathanlesage** [comment]
SVG images can be rendered by using the standard image syntax (`![Caption](/path/to/file.svg)`). Direct rendering of SVG tags within Zettlr is not supported.
