### ISSUE TITLE
Enable optional split screen for parallel notes

### ISSUE THREAD

**Issue by DavidBjelland** [Zettlr/Zettlr#1213]
## Description
For my workflow it would be a great enhancement to have a split screen option to view and edit two notes simultaneously.

## Proposed Changes
My proposition would be to include the split screen option when right clicking a .md file in the directory (next to "Rename file", "Delete file" etc.). The option itself could e.g. be called "Open file in split screen". 

## Possible looks
Quick visualization in Gimp
![image](https://user-images.githubusercontent.com/63207312/91432358-e7ffe380-e861-11ea-8eb6-9bd94d023c5a.png)

**Comment by nathanlesage** [comment]
Will be implemented after a VueJS refactor, which will come. Therefore closing because it will be coming definitely.

**Comment by Triple1090** [comment]
Hi,
are there any updates on this topic?
Thanks!

**Comment by nathanlesage** [comment]
It's already in the nightlies, will come with 3.0
