### ISSUE TITLE
HTML syntax highlighting weirdness

### ISSUE THREAD

**Issue by AlvaroDeMenard** [Zettlr/Zettlr#1214]
## Description
Hashtags break the detection of a closing string, messing up syntax highlighting. See screenshot below.

## Reproducing
This should do the trick:

    <td style="background: #f7f8f8;"></td>

## Expected behaviour
Detect string closing properly.

**Screenshots**

![pic](https://i.imgur.com/H3ZrQpa.png)

## Platform
 - OS and version: windows
 - Zettlr Version: 1.7.3
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Fixed; sorry for the long delay
