### ISSUE TITLE
Export to Reveal.sj

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#1215]
Hi.
Zettlr 1.7.5 is not exporting to Reveal.sj. I try it on Ubuntu and nothing happened. i did it for HTML5 and it works. Asked for it in a community of users and others told me is the same for them.
Thanks for any help!

**Comment by nathanlesage** [comment]
Will check this.

**Comment by Kangie** [comment]
Can replicate, when attempting to export anything to reveal.js console shows the following: 
```
[15:17:00]	Trying to run command through Application: export
[15:17:00]	Unknown command received: export
```

Platform: Win10 (20.04)
Zettlr: 1.7.5

**Comment by nathanlesage** [comment]
Fixed in latest commit!
