### ISSUE TITLE
[FEATURE] An option to use markdown link for default, not wiki link

### ISSUE THREAD

**Issue by yoonbae81** [Zettlr/Zettlr#1217]
## Description

It would be beneficial to provide an option to generate a markdown link, not wiki link when I dropped another file into editor (like pressing CTRL+K key), so that markdown files will be used in publishing services such as Gitbook and Hugo.

## Example Workflow

1. Add the checkbox option that labeled `Use Markdown link` in Preferences > Editor.
2. When you check the option, you can have markdown links instead of wiki links.

## Caveats

Nothing, because Markdown links are more generic.

**Comment by canpolat** [comment]
@yoonbae81 As far as I can tell, `Ctrl + K` creates a markdown link already. Am I misunderstanding something?

**Comment by yoonbae81** [comment]
I was confused with `CTRL + K`. I need to edit the description. Thanks.

**Comment by nathanlesage** [comment]
Would be a preferences option!

**Comment by vypxl** [comment]
Possible duplicate of #1165 ?

**Comment by nathanlesage** [comment]
@vypxl No, this one wants a different type of functionality.
