### ISSUE TITLE
Moving cursor ahead of the first letter in a line with a mouse is too hard - collapses headings

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#1218]
## Description
When trying to move the cursor to before the first letter in the line with a mouse you need to be very precise to avoid triggering a collapse of the heading instead. 

## Reproducing
Click a bit left of a paragraph that is located inside a heading.

## Expected behaviour
Have a bit more room to click that moves the cursor rather than triggering the heading.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920x1080

**Comment by canpolat** [comment]
This seems to be a duplicate of #1199

**Comment by BellLongworth** [comment]
You are right. Apologies.

**Comment by canpolat** [comment]
No problem :)
