### ISSUE TITLE
Set a max width for the editor?

### ISSUE THREAD

**Issue by davidbosman** [Zettlr/Zettlr#122]
In the editor, the text will occupy as much width as possible. Would it be possible to have a setting to set a maximum width (in number of chars, or pixels, or whatever) and have the line soft wrap at that length?

Outside of code, I prefer shorter lines when reading.

**Comment by nathanlesage** [comment]
I just tested out the app on my new 27 inch monitor and realised I need some more breakpoints, as in Distraction-free mode the code should actually **not** be that spread out … I got to the CSS either way today, so I'll keep that in mind additionally!

Besides that: I recommend the [Custom CSS](https://www.zettlr.com/docs/custom-css) option!

**Comment by davidbosman** [comment]
Wow, did not noticed that option. That's great. Thx :)

**Comment by samarulmeu** [comment]
I manage to modify the width of text adding to my **Custom CSS** this 
```
.CodeMirror-lines {
  max-width: 250px;
}
```
The problem is that the text wrapper is not centered and I could not figure out how to do it.

**Comment by nathanlesage** [comment]
As a short explanation: I don't set a max-width on the text itself, but handle this using margins and paddings:

![image](https://user-images.githubusercontent.com/17251683/55146497-fe71af00-5144-11e9-9baf-cb8d00c76001.png)

**Comment by samarulmeu** [comment]
I manage to get what I wanted by having `margin: auto` on `.CodeMirror-sizer`

**Comment by HendySutarto** [comment]
Adding to @nathanlesage above, here's my implementation on **Custom CSS**:
```
.CodeMirror-lines {
  margin-left: 500px; 
  padding-right: 500px;
}
```

**Comment by siddacool** [comment]
This will solve the issue but breaks the heading accordion (Minimize) feature

`
.CodeMirror-lines > div {
  max-width: 800px;
  margin-left: auto;
  margin-right: auto;
}
`

**Comment by janospower** [comment]
For a width that's consistently within the ideal range of roughly 50 ~ 70 characters per line regardless of window size, I've adapted what @siddacool shared like so:
`#editor {
  --side-margin: calc( 50vw - 30em ); 
}
#editor .CodeMirror {
  margin-left: var(--side-margin);
}

#editor .CodeMirror-scroll {
  padding-right: var(--side-margin);
}`

Depending on the font you use and your personal preference, you'll have to play with the `em` value a bit.

**Comment by nathanlesage** [comment]
This solution looks cool, and I might even end up putting this in the distraction free mode (albeit with 55em on monospace fonts because … well, they're monospace) — after all this is what I wanted to achieve with the margins earlier!

**Comment by siddacool** [comment]
@janospower, It's quite an improvement on the quick and rigid snippet I have posted. 👍

**Comment by YuriGeinishO** [comment]
Would be really nice to have this as a GUI option.

**Comment by evdcush** [comment]
Can someone help me define a `custom.css` that will get rid of this huge margin padding?

I've tried the css in this thread; but it did not change the view 😕

![2023-09-09_19-58](https://github.com/Zettlr/Zettlr/assets/28853935/74e6c8db-3cd7-40cf-972f-f3ce3d6a6d76)

**Comment by nathanlesage** [comment]
If you use the instructions defined in the custom CSS docs you should be able to find the corresponding selectors, I think it is a padding set on the `.cm-scroller` element

**Comment by evdcush** [comment]
> If you use the instructions defined in the custom CSS docs you should be able to find the corresponding selectors, I think it is a padding set on the `.cm-scroller` element

Thank you for your help! 🙇🏻‍♂️
I took a look at https://docs.zettlr.com/en/advanced/custom-css/

I tried some various snippets out for my `custom.css`, but I was not able to reduce the padding.

I hope this is directly configurable from the settings some day (like in Joplin and MarkText). 🤞🏻

**Comment by evdcush** [comment]
Can anyone share their custom CSS snippet to remove the left padding in the editor?

**Comment by jvgarrison** [comment]
FWIW, in version 3.2.0, this is working for me:

`
.main-editor-wrapper .cm-editor .cm-scroller {
  --text-width: 45em; /* set your desired width here */
  --gutter: 60px; /* approx width of .cm-gutters element*/
  --padding: calc( 50% - calc(var(--text-width) / 2)); 
  padding-left: calc(var(--padding) - var(--gutter));
  padding-right: calc(var(--padding) + var(--gutter));
}
`

The snippet supplied in the documentation still works for distraction-free mode.
