### ISSUE TITLE
[BUG] Not Working Ctrl+Shift+E, Gives focus to editing window

### ISSUE THREAD

**Issue by yoonbae81** [Zettlr/Zettlr#1221]
## Description
Ctrl + Shift + E shortcut, which is for focusing to the editing window is not working.

## Reproducing
After I finished renaming document or finding text in document, press the shortcut Ctrl + Shift + E.

 
## Expected behaviour
Zettlr should move focus to the editing window.

**Screenshots**

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.75
 - Screen Resolution: 1600x1200

**Comment by nathanlesage** [comment]
Found the error! Shipping with the next release
