### ISSUE TITLE
[ENHANCEMENT] Behavior of overwriting dialog when adding new file

### ISSUE THREAD

**Issue by yoonbae81** [Zettlr/Zettlr#1222]
## Description

When I try to add a new file that already exists, Zettlr asks me whether to overwrite the file on the dialog with default value of 'Ok', not 'Cancel'. I believe that this behavior is too dangerous because people may lost the existing file if they accidentally press enter key. 

## Proposed Changes

Zettlr may just open the existing file instead of asking overwrite it (or Zettlr may just let us know after it opens the file that it didn't create the file because the file exists). People might tend to just adding a new file because it is much more economic than checking the file exists.

**Comment by nathanlesage** [comment]
I see what you mean; please to all others give feedback on this!

**Comment by canpolat** [comment]
I always create files using `Ctrl+N` and therefore do not experience this scenario, but if I was manually creating a file and the file already existed, I would expect the editor to either give an error (and not create the file) or to open the existing file (this could be a bit confusing). I would not expect/want the editor to overwrite the file in any circumstances (and therefore the dialog is not necessary).

**Comment by Kangie** [comment]
I think that the default behaviour should be to open a file if it has the same name. Overwriting existing content is always undesirable, and opening the file in question should be a good indication to the user that it already exists! Perhaps a notification 'opened existing file with «filename»' or similar could help resolve @canpolat's comment about confusing the end user. 

It's not like we're dropping any content if they're trying to open a new file, and only adds a second 'new file' action as a worst-case for the end user.

**Comment by nathanlesage** [comment]
Ah, so you're basically in favour of going towards apps such as nvALT or so where the file creation is much less like the file system?

Mh, the point I'd argue against concerning this would be that Zettlr attempts to mimick a minimal file browser and not hide too much of the underlying file system from the user, so it should feel more like an explorer than a database list (which is also important given that the GUI pretty much defines how people interact with stuff, and Zettlr has always been something that wants to nudge people towards actually caring about what they do …)

**Comment by yoonbae81** [comment]
I agree your thought that Zettlr should be more like an explorer than a database system because that's why I am a big fan of Zettlr. It provide me independence from specific solution. 

There are people like me don't use ID system. I'm satisfied with specific topic for filename and I believe I can manage it from undesirable renaming in the future. I also like Zettlr doesn't force me to use ID system. It would be another example of independence that Zettlr offers. However, using a topic as filename leads us to overwriting issue. As @Kangie mentioned, nobody would want to overwrite the existing file in Zettenkasten. They might just forget what they have.

The point that I wanted to raise on this issue was that **a software should be safe and protect its users from human errors**. It should not overwrite the existing file with blank one by a mistake. Also, it could be one step further by opening the existing file with the same name.

**Comment by yoonbae81** [comment]
I'd like to add my observation that I've discovered from [Gollum](https://github.com/gollum/gollum) today. I'm using it as the web frontend of my wiki. Zettlr is the offline editor to support it. 

When I request /gollum/create/Home, which is the existing page, the gollum redirect to the view page of the page. Meaning, Gollum also handles user's request to create the existing page as opening it. This is what I mentioned behavior in the original post.
