### ISSUE TITLE
Using button to resize image drops image size to 1

### ISSUE THREAD

**Issue by ianhi** [Zettlr/Zettlr#1224]
## Description
If you use the arrows in the `resize image to` dialog on the first step the image will be first become a 1x1 pixel image and then the arrows keys will work as expected

![broken-image-resize](https://user-images.githubusercontent.com/10111092/91926443-47685400-eca5-11ea-9b66-4f5fdc50a0ed.png)

## Reproducing
- Take a screen shot
- copy screenshot to clipboard
- paste into zettlr
- try to resize image using the arrows

## Expected behaviour

Pixel size would increment by 1 on pressing the button.

## Platform
 - OS and version: PopOS 20.04 (basically ubuntu)
 - Zettlr Version: 1.7.4
 - Screen Resolution: 1080p on monitor in question

**Comment by ianhi** [comment]
I think that if these lines:
https://github.com/Zettlr/Zettlr/blob/6f01e9fa8d1aa237bf4b25021724f8b2118dffa0/resources/templates/dialog/paste-image.handlebars#L17-L18

had the `placeholder` value replaced by `value` it would resolve this

**Comment by nathanlesage** [comment]
> had the placeholder value replaced by value it would resolve this

Not replacing, but adding it as the default value is indeed the solution — and now implemented 🎉
