### ISSUE TITLE
[ENHANCEMENT]: Close all tabs option in tab context menu.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1226]
## Description
Add additional options to the context menu for opened file tabs.

## Proposed Changes
Add additional context menu options to the tab for open files:
- Close all files
- Close all other files

Potentially: Close all files to the Left/Right, depending on feedback. 
This one isn't super useful for me - I'd prefer to be able to close the 100 file I've worked on all at once, but I've seen the feature elsewhere, so if other users will find it useful it might be worthwhile.

Couldn't find an existing enhancement for this after a quick search, apologies if this one already exists!

**Comment by nathanlesage** [comment]
Sounds interesting, yes!
