### ISSUE TITLE
More control on sidebar width/resizing?

### ISSUE THREAD

**Issue by davidbosman** [Zettlr/Zettlr#123]
Would it be possible to have more control when resizing the extended side panels, resizing each one of them indendently of the other?

![zettlr Resize Side panels](https://user-images.githubusercontent.com/104005/54865064-d4447980-4d5f-11e9-9e7a-055899d52e00.png)

The space marked in red is not used by the left panel, but I can't shrink it to make more room for the right panel that'd use this space to show more of the file names ;)

**Comment by nathanlesage** [comment]
Yes, I know about this issue. It’s only that jQueryUI can be a pain in the ass why I didn’t address it until now :D

As I only have limited time, I tend to postpone everything that works, even though not great and focus on bug fixes and features first. But now it’s up on my agenda :)

**Comment by davidbosman** [comment]
Great to know, and don't rush anything: those are merely suggestions ;)

**Comment by nathanlesage** [comment]
As announced on Twitter, it's implemented and will ship with the next release 🙏🏼
