### ISSUE TITLE
[ENHANCEMENT]: 'Omit unsaved changes?' behaviour.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1230]
## Description
If you edit the contents of a file and try to close the editor tab before Zettlr has had a chance to autosave the changes, you are presented with the following dialog, which defaults to dropping your changes.
![image](https://user-images.githubusercontent.com/9733178/92063457-7d5d2380-edde-11ea-8de8-20bde46c9e27.png)

## Proposed Changes
Given that Zettlr's default behaviour is to autosave the content pretty quickly after you modify a file, this dialog should *not* exist, particularly as the possibility of losing any changes exists as the default option.

Remove the dialog, instead force a save if there is unsaved content *and* the close file in editor action occurs.

**Comment by nathanlesage** [comment]
> Given that Zettlr's default behaviour is to autosave the content pretty quickly after you modify a file, this dialog should not exist, particularly as the possibility of losing any changes exists as the default option.

This dialog is meant as a failsafe (better be safe than sorry), so:

> instead force a save if there is unsaved content and the close file in editor action occurs

Might work using this here:

https://github.com/Zettlr/Zettlr/blob/e97ca2aa985e3901f146e2ab6d421f9589fbdb0c/source/renderer/zettlr-rendereripc.js#L23-L35

**Comment by nathanlesage** [comment]
The dialog is now gone for good, so regarding this issue as closed. Instead: If you see that some changes have not been auto-saved, feel free to suggest new issues.
