### ISSUE TITLE
Support Image relative path to certain folder

### ISSUE THREAD

**Issue by h4tr3d** [Zettlr/Zettlr#1231]
## Description

Add option to YAML frontmatter like `zettlr-root-url` that will be used as a prefix for each link path without schema, mainly used for Images. Feature is similar to Typora feature `typora-root-url`: https://support.typora.io/Images/.

## Example Workflow

Mainly feature will be useful for Static sites. Many static generators use separate folder to store static content like images. I use Hugo, article will be located at the `<root>/content/blog/2020-09-01/article.md`, images should be putted into `<root>/static/img/blog/2020-09-01/article/image1.png`. And reference in `article.md` will be:
```
![image1.png](/img/blog/2020-09-01/article/image1.png) <!-- Source location without root/static/ prefix -->
```
Obviously, that Zettlr can't display such image. But, if frontmatter parameter `zettlr-root-url` is pointed, like here:
```yaml
---
zettlr-root-url: ../../../static
---
```

Zettlt can use this knowledge to construct resulting link relative to current document:
```
zettlr-root-url + img-url = "../../../static" + "/img/blog/2020-09-01/article/image1.png" = "../../../static/img/blog/2020-09-01/article/image1.png"
```

Now we have complete relative link and image can be displayed by Zettlr.

`zettlr-root-url` must allow pointing absolute and relative paths.  Absolute paths with schemas (like "http:", "https:") also welcomed.

## Additional Information

No (?)

Typora also uses frontmatter parameter named `typora-copy-images-to` that uses as a prefix for storing inserted images. It is good to have similar parameter for Zettlr too. For sample above it can be:
```yaml
---
typora-copy-images-to: ../../../static/img/blog/2020-09-01/article/
---
```

**Comment by Kangie** [comment]
I can see a use for this feature, but worry that as proposed it's impossible to tell between a posix absolute path `/home/user/image.jpg` and a path that should use the prefix:  e.g. if the prefix is /home `/user/image.jpg` looks like an absolute path instead of something that should be processed as `/home` + `/user/image.jpg`

If we need to start adding things to a path to denote that it should use the prefix, we'd be adding complexity for a use case that (as described) could easily be wholly replaced by taking the relative path up another couple of levels, so 2-3x `../`.

**Comment by h4tr3d** [comment]
@Kangie It is not a problem. Main scenario: locate ALL resources related to this document in single base path. If user manually point `root-url` option and mix absolute and relative paths in document... Its wrong. Another solution, add prefix only to relative locations, that didn't start with `/`. But I prefer to add base url to any locations without schema.

**Comment by Kangie** [comment]
> If user manually point `root-url` option and mix absolute and relative paths in document... Its wrong. 

It may be _wrong_, but a lot of the documentation that I'm currently working on gets converted from legacy content to MarkDown and has absolute paths baked in before I change them (over 100+ files in a project) to relative paths. Any option that would break absolute paths while enabled would break my ability to preview images until I've done that, which is bad. 

Changing the default behaviour around paths seems like a bad idea to me; more complexity for functionality that already exists.

I can certainly see it being useful, particularly where there are convoluted paths in a project **and** the images are stored in a location that's not easily accessible without 5+ layers of `../` first. I'd just like to see a way of doing it that doesn't interfere with posix absolute paths!

**Comment by h4tr3d** [comment]
> more complexity for functionality that already exists.

I describe scenario when functionality is not exists: use Zettlr as editor for statically generated sites. Resulting path, uses by generator and editor may be different. Note, Typora introduces this feature mainly for static sites and it works well for a while (see link: https://support.typora.io/Images/).

As I describe above, static data located at the:
```
site_root/static/some/path/file.png
```
After generation this data located at:
```
https://domain.tld/some/path/file.png
```
Reference in md source is:
```markdown
![file.png](/some/path/file.png)
```
that will be simple translated into:
```html
<img src="/some/path/file.png"></img>
```
Markdown file located at the:
```
site_roo/content/another/path/article.md
```

If I just point image as:
```
![file.png](../../static/some/path/file.png)
```

It will be displayed in Zettlr, but... after site generation this address will be translated into:
```html
<img src="../../static/some/path/file.png">
```
That wrong. For Jekkyl replace "content" with "_post" and "static" with "_media". 

Also, I suggest introducing this feature only as a Frontmatter parameter for a **single document**. Only if user specify it, behavior will be changed and only for links displayed by Zettlr for this document. If user have mixed relative/absolute paths across a single document and specify this parameter, it is expected that something will be wrong, just like point incorrect path. Behavior for other documents will be kept unchanged.

Also, I it is possible to enable this options only for relative paths by default and add option to force absolute paths changing too. In any case, I predict, that second option will be turned on always when first one will be specified.

**Comment by Kangie** [comment]
> > more complexity for functionality that already exists.
> 
> I describe scenario when functionality is not exists: use Zettlr as editor for statically generated sites. 

Sorry, I should have been more clear: It adds complexity around image path handling when there is already a function (using a relative link) that will accomplish the same thing for only a little additional effort on the part of the user.

Thanks very much for expanding on your use case - I can definitely see why you want this, and where it would be useful to my own work. I'm interested others feedback, and can certainly see myself using the feature if it's implemented. :)

**Comment by h4tr3d** [comment]
> Sorry

No problem. I am not a native speaker, so, maybe I just misunderstood you.

> Thanks very much for expanding on your use case

You are welcome!

**Comment by nathanlesage** [comment]
Hey,

thank you for opening this issue. However, this will not be implemented. There are two main reasons to this.

First, static site generators do not need Zettlr to export anything. Static site generators use the Markdown you write and turn that into HTML. There is no need to use Zettlr to export anything, it is even discouraged. If such a static site generator needs some base URLs, you can use the corresponding properties within your YAML frontmatters. The documentation for Zettlr, for instance, is also written with Zettlr, but it is never exported _using Zettlr_. Instead only the files are being edited, and _then_ the static site generator (in our case MkDocs) is being directed to export the files.

Secondly, it would only work for Zettlr, using such a property. Typora doesn't really adhere to any standards, so they may be able to get away with it, but Zettlr strictly adheres to as many standards as possible, and we will not deviate from keeping Zettlr aligned with best practices and standards so that users in many different scenarios can use the application without friction.

**Comment by h4tr3d** [comment]
I didn't mean to use Zettlr for exporting. Just for static site articles editing with images preview without breaking site source tree structure introduced by site generator. To keep same location in MD links across Hugo/Jekkyl and Zettlr. So, this option just a helper for Zettlr to find right image location.

Next, according standard. Do you mean, that all YAML frontmatter fields strongly standardized? I'm not sure. Some applications use property `keywords` to keep tags (Zettlr, pandoc), another use's property `tags` for same purpose (Hugo, Jekkyl). Only field `title` has more-less same meaning in different kind of applications. What standard do you mean? Why is it impossible to introduce some property that can be used by Zettlr itself and it increases area of editor using? And this property just may be ignored by any other application that can't interpret it meaning.

**Comment by nathanlesage** [comment]
> Do you mean, that all YAML frontmatter fields strongly standardized?

Yeah, there _should be_. And in fact there's a working group currently attempting to do so. If you want a special property, please at least try to find some property name that seems to be working somewhere, but not Typora, please!

**Comment by h4tr3d** [comment]
> And in fact there's a working group currently attempting to do so.

Any proofs? I found one related question SO: [Is there a YAML front matter standard / validator?](https://stackoverflow.com/questions/27838730/is-there-a-yaml-front-matter-standard-validator) and can't found any proofs for any work group that tries to standatize Frontmatter fields. But, there is a couple of tools that uses Frontmatter with different fields:

* [Hugo](https://gohugo.io/content-management/front-matter/)
* [Jekyll](https://jekyllrb.com/docs/front-matter/)
* [Middleman](https://middlemanapp.com/basics/frontmatter/)
* [docpad.js](https://docpad.bevry.me/core/meta-data)
* [CSVY](https://csvy.org/) - only one yaml frontmatter spec, but for CSV files
* [pandoc](https://stackoverflow.com/questions/26395374/what-can-i-control-with-yaml-header-options-in-pandoc), man pandoc

Look into template fields for above applications. Seems only pandoc and Zettlr uses `keywords` field. All other uses `tags` for same purpose.  Yes, there are common fields, but most of them natural: it is difficult to find name replacement for `title` propertly :-) But there is a lot of fields that different and specific only for concrete application. At least in Hugo, new fields can be introduced by user and uses by theme or template code on content generation stage.

Frontmatter just a meta information, that can helps some applications to do it work better if user provides them. If I open Hugo article for editing in Zettlr, Zettlr will just ignore unknown fields and this is good, because most of the fields will help Hugo do it work better and should not affect Zettlr. In similar way Typora introduces it own properties that optional and just helps end user to work with application more comfortable in some cases. Integrates separate applications more tightly: Markdown editor and Static site generator in such case. I don't understand, why Zettlr can't do something similar. It is does not break any applications and any existing standards and can make user life a little bit better.

Name for such property can be more generic, like `content-base-url`, `content-root-url` or something like.

**Comment by nathanlesage** [comment]
> Any proofs?

https://github.com/jam-schema/jams
