### ISSUE TITLE
Increase size lines before a line with `-` symbol

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1235]
## Description

Increase size of lines when start a next line with `-` symbol

## Reproducing

Enter header, next line with text and next line with `symbol`

## Expected behaviour

Don't increase size of lines

**Screenshots**

Normal size:
![image](https://user-images.githubusercontent.com/1186777/92162303-9f848f00-ee3a-11ea-8d8a-94e7bfb625e8.png)

After enter `-` symbol at next line:
![image](https://user-images.githubusercontent.com/1186777/92162352-b4f9b900-ee3a-11ea-84bb-7e3fd837c7ff.png)

## Platform
 - OS and version: Windows 10 with last updates
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920x1080

**Comment by Kangie** [comment]
Hi @dukebarman 

The reason that this behaviour occurs is that the `-` is considered to be a [Setext](https://en.wikipedia.org/wiki/Setext) style subheading (level 2 heading).

I have noticed that Setext style headings seem to 'overflow' until there's a blank line above them to interrupt that. This may be a bug - Without a blank line above the heading pandoc will not process the `-` as indicating a heading, however a single `-` will suffice if there's space above, e.g.:
```MarkDown
This is a valid Setext style heading
-

This
is not a valid setext style heading
-
```

 Some examples of the rendering behaviour:
![image](https://user-images.githubusercontent.com/9733178/92204436-d86a4580-eec6-11ea-9a10-b1f8c95dad48.png)
![image](https://user-images.githubusercontent.com/9733178/92204451-e0c28080-eec6-11ea-987b-6d76fa0f88d8.png)
![image](https://user-images.githubusercontent.com/9733178/92204551-10718880-eec7-11ea-9030-56abc2773679.png)

**Comment by nathanlesage** [comment]
Zettlr strictly follows [CommonMark](https://spec.commonmark.org/0.29/#setext-headings) here, as also Pandoc wants to switch more and more to CommonMark itself (so Zettlr is to some extent farther than Pandoc). So it is expected behaviour.

**Comment by dukebarman** [comment]
How can I disable it?

**Comment by nathanlesage** [comment]
Afaik you can't

**Comment by dukebarman** [comment]
It's bad =\

**Comment by nathanlesage** [comment]
It's the Markdown standard; and Zettlr follows it closely. ¯\\\_(ツ)\_/¯

**Comment by dukebarman** [comment]
So ia writer, vscode and another editors with markdown renders this wrong?

**Comment by nathanlesage** [comment]
Yes, at least not CommonMark conforming. As Pandoc will be switching to CommonMark, and CommonMark is the de-facto standard for Markdown, we'll stick to that to reduce interoperability issues.

**Comment by dukebarman** [comment]
Make more tests - when write text after `-` symbol, it returns to habitual behavior. So should not to pay attention in same rare cases :) 

P.S. Imho, this settext behavior will be more comfortable with `---` symbols

**Comment by Kangie** [comment]
> P.S. Imho, this settext behavior will be more comfortable with `---` symbols

Unfortunately, the [CommonMark spec](https://spec.commonmark.org/0.29/#setext-headings) says: 

> A setext heading underline is a sequence of = characters or a sequence of - characters, with no more than 3 spaces indentation and any number of trailing spaces.

A strict reading of the spec says that a single `-` character is acceptable, and that's the behaviour that Zettlr follows.
It's not ideal, but Zettlr should be able to parse any valid MarkDown document  that it's presented with according to the specification, and that's what it does. Deviating from strict standards compliance is undesirable here.
