### ISSUE TITLE
[BUG] CodeMirror pads selections on lines

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1236]
## Description
Don't select a few left pixels on each selected lines

## Reproducing

Select a few strings

## Expected behaviour

More lookful selection

**Screenshots**

![image](https://user-images.githubusercontent.com/1186777/92165048-19b71280-ee3f-11ea-8f4d-bc2b8cb43e49.png)

## Platform
 - OS and version: Windows 10 with last updates
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920х1080

**Comment by nathanlesage** [comment]
I already found this weird behaviour; it's always exactly 4px and I do not know why CodeMirror applies this … I currently assume it has something to do with the line rendering process, but I haven't had the time to go into it

**Comment by dukebarman** [comment]
The size of the cursor (width) in Vim's command mode isn't wide enough. Is it related to this issue?

**Comment by nathanlesage** [comment]
@dukebarman Nope, that's a different issue (which we simply cannot solve with the current CodeMirror implementation; you'd have to use a monospaced font-theme for this purpose)

**Comment by nathanlesage** [comment]
Fixed during the editor refactoring!

**Comment by dukebarman** [comment]
What version of Zettlr I can to check it?

**Comment by nathanlesage** [comment]
The one I'll be releasing this evening

**Comment by dukebarman** [comment]
Thanks, now it looks better.
