### ISSUE TITLE
[BUG]: Toggle developer tools keybinding broken

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1238]
## Description
The toggle developer tools keybinding `ctrl+shift+I` does something completely different, instead inserting an image?
```MarkDown
![]()
```

## Reproducing
Press Ctrl + Shift + I, observe that `![]()` is placed in your document.

## Expected behaviour
Either enable developer options, or do not show this keyboard shortcut against the menu option under Develop --> Toggle developer tools.
## Platform
 - OS and version: Win10 (20.04)
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
On Windows, we'd need a different keybinding for either the image tag insertion or the developer tools. Feel free to suggest one. Open for discussion by all of you!

**Comment by TicTak21** [comment]
@nathanlesage 
My suggestion:
`Ctr+Shift+I` - for devtools.
`Ctrl+Shift+P` - for images, pictures.

**Comment by nathanlesage** [comment]
Fix in favor of the image shortcut. Most users will want to stick to `Ctrl+Shift+I` to insert images. However, developers will be less likely to be sad by me changing that shortcut, so now you can open the devtools using `Ctrl+Alt+I` instead of `Ctrl+Shift+I`.
