### ISSUE TITLE
Could not add a tag of Chinese character

### ISSUE THREAD

**Issue by sahmoli** [Zettlr/Zettlr#124]
## Description
zettlr could not recognize a tag with Chinese character.

## Reproducing
zettlr could recognize ##note as a tag, but could not recognize ##笔记 as a tag.

## Expected behaviour

**Screenshots**

## Platform
 - OS: Windows
 - OS Version 10
 - Zettlr Version 1.2.1
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
It's coming in the next version!
