### ISSUE TITLE
[ENHANCEMENT] Right to left (rtl) languages support in exported files

### ISSUE THREAD

**Issue by gotoayman** [Zettlr/Zettlr#1240]
While zettlr supports RtL in its display, the exported file is still shown from left to right. I wish extending the support of RtL to be maintained even in the exported files.
thank you

**Comment by nathanlesage** [comment]
We need to add the corresponding switches within the TeX and the HTML template — for all those lurkers out there, it should be fairly easy to add; here are the files:

- https://github.com/Zettlr/Zettlr/blob/develop/source/main/assets/export.tex
- https://github.com/Zettlr/Zettlr/blob/develop/source/main/assets/export.tpl.htm

Please refer to the [Pandoc manual](https://pandoc.org/MANUAL.html) for more information on possible Pandoc switches (but querying the config options should also work for the HTML template; feel free to see how it works)

**Comment by nathanlesage** [comment]
This should now work thanks to usage of the provided templates by Pandoc; further support can be added in the defaults files!
