### ISSUE TITLE
Zettlr does not start (Zettlr-1.7.5-x86_64.AppImage)

### ISSUE THREAD

**Issue by aueb** [Zettlr/Zettlr#1242]
## Description
after long time trying to load the files, zettlr breaks to start

## Expected behaviour

**Screenshots**

<--- Last few GCs --->

[4668:0x3c2500000000]   935691 ms: Scavenge 2986.9 (2997.2) -> 2982.6 (2999.0) MB, 10.5 / 0.0 ms  (average mu = 0.862, current mu = 0.786) allocation failure 
[4668:0x3c2500000000]   935721 ms: Scavenge 2988.6 (2999.0) -> 2984.2 (3000.7) MB, 10.3 / 0.0 ms  (average mu = 0.862, current mu = 0.786) allocation failure 
[4668:0x3c2500000000]   935749 ms: Scavenge 2990.3 (3000.7) -> 2985.9 (3002.5) MB, 9.3 / 0.0 ms  (average mu = 0.862, current mu = 0.786) allocation failure 

<--- JS stacktrace --->

Speicherzugriffsfehler (Speicherabzug geschrieben)

## Platform
 - OS and version: Linux Mint 19.3
 - Zettlr Version: Zettlr-1.7.5-x86_64.AppImage
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Puh, let's await the first alpha for 1.8, because we've switched the full CI over to electron forge, so we have to re-test this again either way.

CC @tobiasdiez

**Comment by aueb** [comment]
what does this message mean? what could be the reason for this? any ideas? may be i can help to make it work.
 Andreas

**Comment by Kangie** [comment]
Hi Andreas, 

A short term workaround might be to compile and Zettlr from source, if that's an option in your situation. 

```bash
git clone --depth 1 --branch v1.7.5 https://github.com/Zettlr/Zettlr.git
cd Zettlr
yarn install
cd source 
yarn install
cd ..
yarn start
```

If Zettlr launches for you after the `yarn start`, you can use `yarn build:quick` (or a similar command - see [package.json](https://github.com/Zettlr/Zettlr/blob/v1.7.5/package.json)) to build an executable that you can run normally.

Note that before you attempt to compile Zettlr you'll need to get `yarn` and `nodejs` from your distro's package manager.

I hope that this helps you get going; I'm sure that the appimage will work again after the 1.8 release.

**Comment by nathanlesage** [comment]
> what does this message mean? what could be the reason for this? any ideas? may be i can help to make it work.
> 
>  Andreas

I am pretty sure it has to do with the app image binary, and not with Zettlr. But I don't have any experience with those binaries …

**Comment by nathanlesage** [comment]
Still happening with 1.8 alpha?
