### ISSUE TITLE
[ENHANCEMENT] easy way to create Pandoc-style heading links.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1246]
## Description
Within a project that gets compiled into a single PDF, Word Document, HTML page (etc), it can be useful to link to other sections of the document via the pandoc-generated [heading auto-identifier](https://pandoc.org/MANUAL.html#extension-auto_identifiers).

Currently the only way to do this is to manually open a file within a project and work out what the heading auto-identifier will be.

## Proposed Changes
Provide a mechanism that allows easily searching of and inserting links to headings across a project.

```MarkDown
[This is a test link](#auto-generated-heading-identifier)
```

**Comment by nathanlesage** [comment]
Interesting idea! No bandwidth right now, but a PR would be implemented!
