### ISSUE TITLE
[BUG]: Find and Replace for Image paths

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1248]
## Description
When moving a file around in a project it is necessary to adjust the relative file path if it ends up at a different 'depth'. Attempting to use find and replace to replace e.g. `..\..\` with `..\..\..\` is unpredictable when using the 'Replace All' function, resulting in: 

For the source:

```MarkDown
![UI Component](..\..\Images\UI\Example_UI_Component.png)
```

This:

```MarkDown
![UI Component](..\..\Images\UI\Example_UI_Component.png)..\..\..\
```

Instead of this:

```MarkDown
![UI Component](..\..\..\Images\UI\Example_UI_Component.png)
```
## Reproducing
Attempt a find and replace on relative image paths within a file using the 'replace all' function.

This perfectly if you click 'next' then 'replace', doing images one-at-a-time.
## Expected behaviour
Find and replace replaces the image path that it finds, not append the replacement to the end of the line.

Ideally Zettlr should transparently update relative image paths within a file when it is moved within a project / folder, eliminating the need for find and replace, but that's a feature request, not a bug.
## Platform
 - OS and version: Windows 10 (20.04) 
 - Zettlr Version: 1.7.5 and electron-forge branch.
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
1. Are you using regular expression search or default search?
2. Can you please provide a reproducable Markdown source (please no file uploads, just into a code block) with corresponding search for us to reproduce?

**Comment by Kangie** [comment]
I'm using the regular 'Find' function to look for the string (in the example I'm about to provide) `..\..\`.

Example Markdown. (Document located in `D:\Temp\ZettlrTest`, images in `D:\Temp`). Apparently I use images of Potatoes when debugging Zettlr image functionality!

```MarkDown

![Potato1.jpg](..\..\Temp\Potato1.jpg)
![Potato2.jpg](..\..\Temp\Potato2.jpg)
![Potato3.jpg](..\..\Temp\Potato3.jpg)

```

Search String: `..\..\Temp\`
Replace String: `..\`

Results: 

```MarkDown

![Potato1.jpg](..\..\Temp\Potato1.jpg)..\
![Potato2.jpg](..\..\Temp\Potato2.jpg)..\
![Potato3.jpg](..\..\Temp\Potato3.jpg)..\

```

Expected Results:

```MarkDown
![Potato1.jpg](..\Potato1.jpg)
![Potato2.jpg](..\Potato2.jpg)
![Potato3.jpg](..\Potato3.jpg)
```

Note that you get the expected results if you find and replace one item at a time. I assume that's because you're "inside" the image "tag" (the line isn't being rendered as an image at the time).

The replace string is consistently appended to the end of the line when using `Replace All`. I expect that this issue occurs across *all* image paths, not just relative ones, don't have the time to do any additional investigation right now.

**Comment by nathanlesage** [comment]
Ah the info "replace all" was important _ looks as if we're simply missing a global flag on the regexp
