### ISSUE TITLE
[BUG]: Renaming a file does not trigger a save action, resulting in the loss of content with no warning.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1249]
## Description
If a file is renamed within Zettlr (I use the **F2** shortcut) while there are unsaved changes, the file is renamed but changes are not retained. There is no warning that changes will be dropped. 

## Reproducing
1. Create a new file in Zettlr. 
2. Save the file. 
3. Modify some content (adding an ATX-style heading is a quick way to do this)
4. Quickly rename the file before Zettlr has a chance to autosave. 

The file will be successfully renamed, but the changes that you made will be discarded.

## Expected behaviour
Zettlr should save the file before renaming.

## Platform
 - OS and version: Win10 (20.04)
 - Zettlr Version: Electron-forge branch.
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Confirmed, missing "closing" command in the IPC, getting to it …

**Comment by nathanlesage** [comment]
And done
