### ISSUE TITLE
[BUG] Impossible to write the word "Constructor"

### ISSUE THREAD

**Issue by fego** [Zettlr/Zettlr#1253]
## Description
Impossible to write or paste the word "Constructor"

## Reproducing
Open a new file. 
Write "Constructor" respecting the case (not "constructor")

## Expected behaviour
No error, but an error occurs when I enter the last letter. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1447977/92649407-4493e180-f2eb-11ea-8640-9536c98046bb.png)

## Platform
 - OS and version:Windows 10
 - Zettlr Version:1.7.5
 - Screen Resolution:1920x1080

**Comment by nathanlesage** [comment]
Amazing o.O

**Comment by the-solipsist** [comment]
I cannot reproduce this on an Ubuntu 20.04 system with Zettlr 1.7.5.  This might be OS-specific.

**Comment by cdaven** [comment]
I cannot reproduce this on Windows 10 with Zettlr 1.7.5 either.

**Comment by canpolat** [comment]
I could reproduce it on Windows 10, Zettlr 1.7.5.

**Comment by Kangie** [comment]
I've been unable to reproduce on Win10 or Linux. 

1.7.5 & develop (Win), develop (linix)

**Comment by nathanlesage** [comment]
It apparently has to do with the loaded dictionaries (it throws an error in the dictionary provider) - I had German and en-GB loaded.

**Comment by fego** [comment]
I have loaded only the french dictionnary. Do you need more informations ?

**Comment by nathanlesage** [comment]
Sorry for the late response, but it's not happening in 2.0 anymore, so it seems nspell has fixed the error! Just checked and it's working perfectly fine!
