### ISSUE TITLE
[ENHANCEMENT]: Readability mode stays on between files.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1254]
## Description
If readability mode has been toggled while reviewing a project and you switch editor tabs or open a new file it is disabled.

This is frustrating when reviewing files across a whole project for readability and adds >100 additional clicks to accomplish the task!

## Proposed Changes
As the tooltip suggests that readability mode is toggled, it should not be disabled until the user chooses to do so.

**Comment by nathanlesage** [comment]
So instead always resetting the mode, enable a toggle? Sounds fair enough!
