### ISSUE TITLE
Citation database stops updating

### ISSUE THREAD

**Issue by ewquon** [Zettlr/Zettlr#1259]
## Description
I am using BetterBibtex with a collection exported with the "keep updated" option. Typing `[[@... ` presents an autocompletion list with bibtex keys, as expected. When I update my bib file, Zettlr usually refreshes the citation database successfully the first time and I am able to access the new bibtex entry--but most of the time, subsequent changes to the bib file are _not_ refreshed, and the only fix is to restart Zettlr. 

## Reproducing
1. Add new article to citation database
2. Create citation for new article in zettlr
3. Add another new article to citation database
4. Try to create citation for second new article (fails)

## Expected behaviour

**Screenshots**
n/a

## Platform
 - OS and version: Mac OSX Catalina (10.15.6)
 - Zettlr Version: 1.7.4
 - Screen Resolution: n/a

## Additional information
n/a

**Comment by nathanlesage** [comment]
> most of the time

_most_ of the time is insufficient to pin down an issue. I cannot reproduce this via my installation, so please to other readers here, feel free to try to reproduce this issue!

**Comment by the-solipsist** [comment]
I've had a similar experience: https://github.com/Zettlr/Zettlr/issues/1251#issuecomment-690107903  

For me, it's all of the time, that is: Zettlr's auto-suggestions upon pressing `@` never changes, even if the .bib file has changed, and this continues till I close and reopen Zettlr (at which point the changes in the .bib file get reflected).  How should I seek to pinpoint the problem?

I'm using Zotero 5.0.89 + BetterBibTex 5.2.66, with auto-update of .bib file switched on + Zettlr 1.7.5.

**Comment by nathanlesage** [comment]
@the-solipsist Does your Zettlr Print out the "changes to the library detected" notification? If so, Zettlr detects the changes, then the next step would be to see if there are any errors logged.

**Comment by ewquon** [comment]
@nathanlesage I can confirm that the first time my library changes (a bibtex entry is added or removed), I see not one but _four_ messages in succession: "Changes to the library file detected. Reloading ..." Subsequent changes do not update the citation autocomplete list and I do not see any popups.

If you tell me what to look for I can check the developer logs.

**Comment by ewquon** [comment]
FWIW, getting this issue sorted out is of paramount importance to me. I've been applying the Zettelkasten method for my research and I **love** that Zettlr integrates with my bibtex citations. However, I am constantly adding references and citations to my notes as I read papers and follow up on references, so it's a dealbreaker for me if I have to restart Zettlr every time I update my citation database. I hope this gets sorted out soon and I'm happy to help troubleshoot.

**Comment by nathanlesage** [comment]
Just to ask again … you are using `.bib`, and not `.json`, right? If so, would you mind to test using CSL-json instead of bibtex? If that works, this indicates that there's a bug in the `bib`-loading code and would help me pin it down!

**Comment by the-solipsist** [comment]
Hi. I tried "Better CSL JSON" export in Zotero, and I couldn't reproduce this.  But the weird thing is that I then shifted back to the `.bib`, and I still couldn't reproduce it.  And it showed the "changes to the library detected" notification each time I made a change in Zotero (which I don't recall it doing earlier)!

I've faced this issue on at least two different occasions, but I am not facing it today.  I'll continue with the `.bib` for now to see if it recurs.  Sorry if this has been a wild goose chase.  From my side: I'd be happy to see this issue closed (with `.json` being the recommended format for now), and reopened if it can be consistently reproduced.

**Comment by ewquon** [comment]
I can confirm that using "Better CSL JSON (keep updated)" export allows me to update my references in Zotero and have those changes appear in Zettlr.

**Comment by nathanlesage** [comment]
Perfect, then I'll see this issue as closed, but in case you notice an error in the bibtex loading mechanism (I'm pretty sure I made an accident somewhere in the code), please comment here so that we can tackle it!

**Comment by MaPeras** [comment]
Unfortunately I am having the exact same problem, when I add a new reference to my Zotero library, autocomplete with @ does not work and only a restart helps. Got this from the logs:

[07:05:25]	[Citeproc Provider] Database /home/max/Nextcloud/library.csl.json has been changed remotely. Reloading ...
[07:05:25]	[Citeproc Provider] Parsing file /home/max/Nextcloud/library.csl.json as CSL JSON ...
[07:05:25]	[Citeproc Provider] Could not reload affected database /home/max/Nextcloud/library.csl.json: Unexpected end of JSON input

Ubuntu 20.04.3 LTS
Zettlr 2.1.1

**Comment by nathanlesage** [comment]
> Could not reload affected database /home/max/Nextcloud/library.csl.json: Unexpected end of JSON input

This indicates that maybe Zettlr attempts to read in the database before Zotero has finished writing it.

**Comment by MaPeras** [comment]
Okay, thanks, I slowed down the Better Bibtex Export (see Screenshot) and it worked, but when I restarted Zotero I got a new error:

[18:18:00]	[Citeproc Provider] Parsing file /home/max/Nextcloud/Meine Bibliothek.json as CSL JSON ...
[18:18:00]	[Citeproc Provider] Could not reload affected database /home/max/Nextcloud/Meine Bibliothek.json: Unexpected end of JSON input

![Bildschirmfoto vom 2022-01-13 18-22-11](https://user-images.githubusercontent.com/49619613/149378435-7eb5c150-08a3-4a7f-b510-023645012ae4.png)

**Comment by nathanlesage** [comment]
That's the same error. What kind of computer do you have? Is it relatively fast or more somewhat slower? I'm asking because this might indicate that I need to increase the thresholds for the watchdog so that it functions properly also on slower machines …

**Comment by MaPeras** [comment]
First I like to thank you again for this amazing tool - it really changed my way of working and doing research! 

---

I am working on two machines, syncing Zettlr (through Nextcloud) and Zotero (through an Zotero-Account).
Intel® Core™ i5-4570 CPU @ 3.20GHz × 4  + 15,6 GB with Ubuntu
and
my old friend: Macbook Air 2014 with Xubuntu 1,4 GHz Dual-Core Intel Core i5 + 4 GB

However, the error appears on both machines equally.

My library has 1793 items. I could split this up, but it would inhibit the Zettelkasten Workflow as I like to add other thoughts + sources, that are not connected with my current project.

**Comment by nathanlesage** [comment]
> I could split this up, but it would inhibit the Zettelkasten Workflow as I like to add other thoughts + sources, that are not connected with my current project.

Of course, this wouldn't be the long term solution. But if the errors disappear if you use a smaller library, that would give me an indication as to what might be going wrong!

**Comment by MaPeras** [comment]
> Of course, this wouldn't be the long term solution. But if the errors disappear if you use a smaller library, that would give me an indication as to what might be going wrong!
You were right. It worked with 382 items Export

> EDIT: Also, let's focus on the Intel machine, not the Hackintosh – not because I dislike that, but I want to make sure we exclude potential issues between a MacBook and a Linux kernel …
Okay sure :)

**Comment by nathanlesage** [comment]
> You were right. It worked with 382 items Export

Ah, perfect. Thanks for the quick update! Possibly it would make sense simply to increase the watchdogs sensitivity for that particular file (as it could be, unlike other files, rather big).

**Comment by MaPeras** [comment]
Okay, great, should I do it on a global level through the advanced options tab? And if so, to what extent? 3000? 10000?

**Comment by nathanlesage** [comment]
> should I do it on a global level through the advanced options tab?

The problem is that this is not tied to the citation provider, that only affects the file system … plus I think due to the size differential (a few kb for almost all files, sometimes several mb for the library files) it might make sense to distinguish between these two settings, because otherwise you'll have to wait for said amount of ms before Zettlr recognizes changes to small Markdown files.

**Comment by MaPeras** [comment]
Yess! Seems to work! Thank you so much!
