### ISSUE TITLE
[Feature Request] AutoCorrect Options

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#126]
Automatically closing for special character pairs is a nice feature, but I think that it will be nice to have the posibility of choosing what pair to use. 
For example the quote pair in Romanian is ` „ ” `, but Zettler suggests ` „ “ `.

P. S. 1.2.1 is a very nice and seems to be a very stable release. Nice job!

**Comment by nathanlesage** [comment]
Yes, it's something I've been thinking about for a year now, but I haven't had any good idea of how to achieve that in CodeMirror. So I'll keep this issue open and once I find something, I'll implement it!

**Comment by nathanlesage** [comment]
I just thought why not go full throttle and implement auto correct options, such as replacing certain codes with the respective glyphs, such as:

- "" => Smart quotes, e.g.: “” (en-GB), »« (fr-FR), „“ (de-DE)
- -> => →
- <- => ←
- `--` => –
- `---` => —
- Also, custom AutoCorrect options, of course.

**Comment by samarulmeu** [comment]
This will be nice.

**Comment by samarulmeu** [comment]
Or will it be possible to just have an option to choose starting and ending character from a drop-down menu (one menu for start and one for end)? This way the language will not matter.

Pitty will not make it in 1.3.0, but patience and stability are more important.

**Comment by nathanlesage** [comment]
Alright, after almost a year, I can finally report some progress: I just sat down and wrote a 300-lines plugin that actually performs preeeeeeetty good so far! So AutoCorrect is a reality now :)

**Comment by samarulmeu** [comment]
Nice to hear. I hope I will finally escape the struggle of using quote marks in Romanian.

**Comment by nathanlesage** [comment]
It should, magic quotes are in there by default :)

**Comment by nathanlesage** [comment]
As AutoCorrect is fiiiiiinally here, I'm going to close this issue to keep the list clean :)
