### ISSUE TITLE
[FEATURE] Open an existing file

### ISSUE THREAD

**Issue by yoonbae81** [Zettlr/Zettlr#1261]
## Description

Currently, When I need to open another file during edit, I have to find the file using `CTRL+SHIFT+F` and select the file using my MOUSE. Zettlr doesn't seem to let me choose the file using my keyboard. 

Although [Zettlr has been designed for directories](https://github.com/Zettlr/Zettlr/issues/236), I believe it would be much convenient if Zettlr provides a feature to open a file with a shortcut key such as `CTRL+SHIFT+O`, `CTRL+G` (stands for go) or something. 

(For your reference, I use only one folder for my zettelkasten because I don't need to care about the naming conflict. So, I wish I could use `CTRL+O` for opening a file, not a directory. However, I understand that there might be people having multiple directories for some purposes.)

## Example Workflow

1. When a user press the keyboard shortcut, `CTRL+SHIFT+O' or something, Zettlr accepts the name of file and show similar files. 

2. Zettlr opens the selected file in a new tab when the user selects a file using arrow keys and the enter key finally.

## Caveats

Zettlr could create a new file when the file that the user wanted to open does not exists. Of course, Zettlr should notify this to user in form of a small notification window that disappear automatically.

## Additional Information

For someone who prefers to use only one directory, Zettlr might provide an option for users how the shortcut, `CTRL+O`, works. It could open a directory or a file.  

Thanks.

**Comment by Kangie** [comment]
Interesting. Possibly related to #1222.

When you say 'open a file', do you mean:
- [ ] A file that's within a directory that Zettlr already knows about,
- [ ] A file located in any path on your filesystem,

**Comment by yoonbae81** [comment]
I meant to open a file in a directory that Zettlr has already opened. 

Of course, I could select the file in the left pane with my mouse. However, it would not be easy to select the file if you have hundreds of files in a directory. I believe a program should provide interfaces for both mouse and keyboard. 

As you pointed out, this is slightly related to the [#1222](https://github.com/Zettlr/Zettlr/issues/1222) because Zettler needs to create the file when it fails to file. It is opposite behavior to the previous issue, #1222. 

Thanks.

**Comment by nathanlesage** [comment]
This is a task for the global search, which behaves a little bit like nvALT's search bar: if the text in there matches a file name, the file will be opened. It also features autocomplete!

**Comment by nasteffe** [comment]
Is there currently a way, using only the keyboard, to go from a global search to selecting a file from the file manager?

**Comment by nathanlesage** [comment]
You can select the file manager by pressing I think `Cmd/Ctrl+Alt+F` (or shift …?)

**Comment by nasteffe** [comment]
Sorry, I'm not getting any response to those key combinations on OSX (ie Ctrl+Opt+F, Cmd+Opt+F, Shift+Ctrl+Opt+F, Shift+Cmd+Opt+F, etc.). Any recommendations?

**Comment by nathanlesage** [comment]
It's `Cmd/Ctrl+Shift+F`, begin typing the name, the global search will autocomplete the name, press Enter, it will open the file. Nevertheless, it currently has to be in the same root directory. But there's an issue open that global search works across root directories. Please follow there if something else comes up!
