### ISSUE TITLE
Zooming with trackpad

### ISSUE THREAD

**Issue by pythonian23** [Zettlr/Zettlr#1263]
## Description
Zooming with the trackpad seems to be reversed.

## Reproducing
If you pull your fingers together, it zooms in. If you push them outwards, it zooms out.

## Expected behavior
If you pull your fingers together, it should zoom out. If you push them outwards, it should zoom in.

## Platform
 - OS and version: Microsoft Windows 10 Pro 10.0.19041 Build 19041
 - Zettlr Version: v1.7.5
 - Screen Resolution: 2256x1504

**Comment by kyaso** [comment]
`CTRL` + scrolling also is reversed.

`CTRL` + scroll up zooms out; most programs I am familiar with (e.g., Firefox) zoom in when scrolling up.

**Comment by nathanlesage** [comment]
I didn't even know that pinching on Windows is reversed …? Feel free to have a look at the code, I can't test it on Windows:

```js
// Enable zooming by Cmd/Ctrl-scrolling
    this._cm.getWrapperElement().addEventListener('wheel', (e) => {
      if (
        (process.platform !== 'darwin' && e.ctrlKey) ||
        (process.platform === 'darwin' && e.metaKey)
      ) {
        // NOTE: Did you know that pinching events get reported as "wheel" events as well?
        // Me neither.
        e.preventDefault()
        // Divide by itself as absolute to either get -1 or +1
        let direction = e.deltaY / Math.abs(e.deltaY)
        this.zoom(isNaN(direction) ? 0 : direction)
      }
    })
```

**Comment by khemako** [comment]
As mentioned by #kyaso above, 
> `CTRL` + scrolling also is reversed.
> 
> `CTRL` + scroll up zooms out; most programs I am familiar with (e.g., Firefox) zoom in when scrolling up.

I'm seeing the same behaviour on Linux using a 3-button wheel mouse. Trying to zoom in/out using the mouse middle-wheel-button works exactly reverse of what I expect.  Cntl-wheel-up should zoom in (more magnification), just like on web browser such as Chrome, Firefox or office suites such as LibreOffice.

Unfortunately there appears to be no user configuration setting to modify this.

**Comment by s-celles** [comment]
Hi,

I'm coming to this issue because control + mouse wheel is not working here (v4.6.0)
Ctrl + - (doesn't work on french AZERTY keyboards too - I was expecting zoom out) - CTRL + + (need shift here) zoom in 

Best regards
