### ISSUE TITLE
[DEVELOP] CSS-Loader and Less-Loader cannot be upgraded

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1264]
Pinging @tobiasdiez @Aigeruth 

---

I just bumped all dependencies; everything works out, but I couldn't upgrade the `less-loader` (would result in the LESS code being unable to be compiled as the corresponding module cannot be found by forge) nor the `css-loader` (would not properly include the CSS files we need for the virtual scroller to work properly). Would be cool if we could check why that is, but unfortunately I didn't have time to investigate.

**Comment by tobiasdiez** [comment]
Probably one of the breaking changes in https://github.com/webpack-contrib/css-loader/releases/tag/v4.0.0. I'll try to investigate this, but not before next wee.

**Comment by nathanlesage** [comment]
Thanks so much! If I can help, just ping me :)
