### ISSUE TITLE
[BUG/DEVELOP]: Project export does not respect custom LaTeX templates.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1267]
## Description
When projects are exported using the Develop branch they export successfully, however the custom LaTeX template is never placed in the project folder, instead placing the default template in the folder.

## Reproducing
1. Create a project and assign a custom LaTeX template. (easily done if you add some comments to the top)
2. Export the project while watching your project folder.
3. Open the template.latex that's placed in your project directory.
4. Observe that it is always the default Zettlr template, not the one specified in project settings.

## Expected behaviour
Export template should be respected.
## Platform
 - OS and version: Win10 20.04
 - Zettlr Version: Develop (current HEAD)
## Additional information
No errors in zettlr log; it goes straight to the pandoc export command as it would in 1.7.5. 
Same command is run for both 1.7.5 & Develop, however Develop *always* goes for the built-in template, not for the one specified in project settings.

**Comment by nathanlesage** [comment]
Thank you for testing and reporting! :)

**Comment by Kangie** [comment]
OK, A little bit more investigation: 

- Issue also occurs on Linux.
  - Suspect that `if (pdf.hasOwnProperty('textpl') && isFile(pdf.textpl))` in `source/main/modules/export/prepare-pdf-export.js` never evaluates to true. 
- `textpl` is never saved from project settings in project `.ztr-directory` file.
  - Manually populating this in the file doesn't fix anything.
  - Where is this value stored? Project settings seems to be able to retrieve it consistently...

That's all that I can really dig out for now.

**Comment by webopold** [comment]
Related to

https://github.com/Zettlr/Zettlr/issues/1126

**Comment by Kangie** [comment]
@nathanlesage, any thoughts on this? If you can point me in the right direction I'm happy to keep looking into it.

**Comment by nathanlesage** [comment]
I have no idea, but I'm currently digging like a worm through all the left-over issues here, and I'm sure I'll find a fix soon. I just realized that, for instance, the tab behavior was completely irrational until I fixed it this morning :D

**Comment by Kangie** [comment]
No worries. Sorry that I couldn't work out why this is misbehaving and get it off your plate!

**Comment by nathanlesage** [comment]
Found the issue, but it bugs me, because the condition @Kangie mentioned indeed evaluated to true, BUT the corresponding path variable was never set to something different. Now that I directly access the base variables, it works but this leaves the main question unanswered: Why was the variable never overwritten …?

Nevertheless: Fixed!
