### ISSUE TITLE
[BUG] Sorting by Name Not Working

### ISSUE THREAD

**Issue by Mavpt** [Zettlr/Zettlr#1271]
## Description
Alphabetical sorting is not working in the file list.

## Reproducing
1. Create a new empty directory and open the file list in it
2. Create files 3 files under that directory with the title property in the YAML header being "A Note", "C Note" and "B Note" in that particular order
3. Attempt to sort said files by title by clicking the Aa button when hovering over the directory, without any result

## Expected behaviour
Have files in the file list sorted by their name.

**Screenshots**
![image](https://user-images.githubusercontent.com/58571526/93144733-94efb280-f6e2-11ea-9d63-a3ca377c19c6.png)
![image](https://user-images.githubusercontent.com/58571526/93144709-873a2d00-f6e2-11ea-80b4-78a3003bd8c8.png)

## Platform
 - OS and version: Linux (Arch Linux)
 - Zettlr Version: [zettlr-bin](https://aur.archlinux.org/packages/zettlr-bin/) as well as the AppImage from [here](https://zettlr.com/download)
 - Screen Resolution: 1080x1920

## Additional information
The section about sorting the file list in the [documentation](https://docs.zettlr.com/en/core/file-list/#sorting) seems me outdated, as the interface represented in the image is not the current one and the description given doesn't match with what I imagine is the intended experience (the left button selecting what's being sorted by and the right button selecting the sorting order), but I might be wrong on that one.

Edit: Added the Additional information section.

**Comment by nathanlesage** [comment]
Has already been reported and is fixed in the Codename; it will ship with 1.8.0!
