### ISSUE TITLE
[ENHANCEMENT] Render grouped citations with just one set of parentheses

### ISSUE THREAD

**Issue by zentralwerkstatt** [Zettlr/Zettlr#1272]
## Description

Multiple sources, separated by a semicolon, should be rendered as a single "grouped" citation with just one set of parentheses.

## Proposed Changes

At the moment Zettlr renders grouped citations with individual sets of parentheses. Example: `@miller:2000; @smith:2001` is currently rendered as "(Miller 2000); (Smith 2001)" but should be rendered as "(Miller 2000; Smith 2001)".

Thank you for considering this enhancement, and for the amazing work on Zettlr!

**Comment by canpolat** [comment]
This is actually supported, but you need to use square brackets around the sources. Try `[@miller:2000; @smith:2001]`

**Comment by zentralwerkstatt** [comment]
Perfect, thank you so much for the super fast response (and sorry for opening an issue for this).

**Comment by nathanlesage** [comment]
It's pretty much hidden in the Pandoc documentation … and even I can't find it right now o.O

Ah, here: https://pandoc.org/demo/example19/Extension-citations.html

Linked from the documentation: https://docs.zettlr.com/en/academic/citations/#citing-in-zettlr
