### ISSUE TITLE
In the tag cloud, clicking on tags containing spaces doesn't show any results

### ISSUE THREAD

**Issue by sxn** [Zettlr/Zettlr#1275]
## Description

When using [YAML frontmatter](https://docs.zettlr.com/en/core/yaml-frontmatter/#variable-keywords) to add keywords to notes, it's possible to add keywords containing spaces. These keywords appear in the tag cloud, but clicking them yields no results.

## Reproducing

1. Create a new note, add the following front matter (or anything with a space in it):

```yaml
---
keywords:
  - Foo Bar
---
```

2. Go to the tag cloud, click on the `Foo Bar` tag
3. The search bar should now contain `#Foo Bar`, but you should see no results.

## Expected behaviour

I would expect to see a list of results containing the tag that I clicked.

**Screenshots**

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1155589/93529861-edba8780-f93c-11ea-999a-45bab0ca3b7c.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1155589/93529945-13479100-f93d-11ea-9233-d5699e6a6da3.png">

## Platform
 - OS and version: macOS Catalina, Version 10.15.6
 - Zettlr Version: 1.7.5
 - Screen Resolution: 2880 x 1800

## Additional information

I cloned the repository and managed to get it to work by modifying one of the following two files:

- https://github.com/Zettlr/Zettlr/blob/develop/source/renderer/zettlr-renderer.js#L490-L491 to quote the search term, i.e.:
```
this._toolbar.setSearch(`"${term}"`);
this.beginSearch(`"${term}"`);
```

- https://github.com/Zettlr/Zettlr/blob/develop/source/renderer/dialog/tag-cloud.js#L35 in the same way:
```
window.renderer.autoSearch(`"${elem.attr('data-tag')}"`)
```

However I'm completely new to the codebase, so I'm not sure if this is a good way to go around it, or if either of these solutions risk modifying some other behaviour I'm unaware of.

Finally, thank you for creating Zettlr! I've come across it a few months ago and have been using it daily ever since! 😸

**Comment by canpolat** [comment]
I don't know much about the code base either, but solving this would be a good ımprovement.

How does you branch behave with links like these:

```
[[#Game Development]]
```

In Zettlr, internal links are also triggering the search function. So, it may make sense to cover those as well (if it is not already covered).

**Comment by sxn** [comment]
Oh, that's a good point! You can find the branch here: https://github.com/sxn/Zettlr/tree/fix-tag-handling

Clicking on `[[#Game Development]]` works correctly as far as the search is concerned:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/1155589/93636150-b78c0f00-f9f3-11ea-88cd-0d9ce58cb71e.png">

However, because I activated the "Automatically create non-existing files when following internal links", and because I have no file named `#Game Development.md`, on top of the search being triggered, the file is also created. 😅 This happens with any tag, though, and is not related to my change, though it might make sense to check if that is actually the expected behaviour. 🤔

**Comment by canpolat** [comment]
Hmm... I cannot remember if file creation via search was a setting somewhere. When I try searching for `"#game development"` (or Ctrl+clicking `[[#game development]]`), the file is not created (which is what I would prefer, anyway).

The only question in my mind is: Since both `"#game development"` and `#"game development"` return the same results, is there a correct way to search?

**Comment by nathanlesage** [comment]
You are right with encapsulating searches with quotes, and I added that behaviour now! As for the links … there you can simply encapsulate this with quotes yourself, and it'll work just fine:

![image](https://user-images.githubusercontent.com/17251683/93765830-cfdb7400-fc15-11ea-8538-012678afc4a9.png)
