### ISSUE TITLE
Minimizing header too easily triggered

### ISSUE THREAD

**Issue by YueGan** [Zettlr/Zettlr#1276]
## Description

When clicking onto left side of empty space below a `#` or `##` or `###` header, it would minimize all the content below it. 

## Proposed Changes
The guideline is not clear, perhaps a change of color would be beneficial.

**Comment by Kangie** [comment]
Hi @YueGan, this is a duplicate of #1199 

It will be addressed in a future release. :)

**Comment by YueGan** [comment]
Koodos!

**Comment by brimwats** [comment]
yes! This is SO annoying! I made a gif showing just how goddamn frustrating this is when trying to change the first word of a paragraph


![kvPbKqwP9B](https://user-images.githubusercontent.com/49103046/93661262-46585600-fa0b-11ea-986e-295785c894a4.gif)

**Comment by nathanlesage** [comment]
For some context: This issue has been introduced with a recently merged PR, I didn't notice this beforehand, and I think it's already working out pretty well. It comes with the first 1.8-beta!
