### ISSUE TITLE
could tag cloud show the tag number directly?

### ISSUE THREAD

**Issue by sahmoli** [Zettlr/Zettlr#128]
now the tag cloud could only show number of tags when mouse hover on the tag

## Reproducing

It will be convenient if the tag cloud could directly show the numbers of each tag.

**Screenshots**

## Platform
 - OS: windows
 - OS Version 10
 - Zettlr Version 1.2.1
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Yep, there will be more additions to the tag cloud, including this, in the future.

**Comment by nathanlesage** [comment]
Done!
