### ISSUE TITLE
On MacOS: export fails because Pandoc tries to use xelatex

### ISSUE THREAD

**Issue by OlivierPS** [Zettlr/Zettlr#1280]
## Description

On _MacOS_: export fails because *Pandoc* tries to use *xelatex*. Isn’t “xelatex” a *Linux* package?

## Reproducing

Any export invoquing *Pandoc*, I suppose. See screenshot below.

## Expected behaviour

Exporting!

**Screenshots**
![CleanShot 2020-09-19 at 08 01 55](https://user-images.githubusercontent.com/68178338/93660664-7a566a00-fa51-11ea-98fe-c643337fbe43.png)

## Platform
 - OS and version: MacOS 10.15.6
 - Zettlr Version: 1.7.5
 - Screen Resolution:

**Comment by OlivierPS** [comment]
I think I have “corrected” what needed to be corrected: after checking the *Pandoc* installation sequence, I discovered I should run

    brew link --overwrite pandoc

I did it and now, everything seems to run fine. Most sorry for the disturbance… if any!

Thank you very much for your kind attention.

Olivier :-{)

PS: I’m not a programmer, just an occasional geek and this is a really nerdy, geeky issue… Lots of geeky stuff involved in getting all this running smoothly… 😉

**Comment by Kangie** [comment]
@OlivierPS Were you instructed to do that by brew when you installed pandoc?

If not, we may need to update the Zettlr docs. 

Glad you got export sorted!

**Comment by nathanlesage** [comment]
@Kangie The docs explicitly mention the homebrew method to install Pandoc (b/c it's much easier to update Pandoc this way).

However, the mistake was that no LaTeX package has been installed.

> Isn’t “xelatex” a Linux package?

Nope, it's a binary that ships for every platform, it's a replacement for the not-so-good pdflatex binary. It's just the LaTeX compiler that is being installed when installing a LaTeX package (however, preferrably the one mentioned in the docs, I'm personally not sure which packages for macOS do include xelatex apart from the one mentioned in the docs).

> I think I have “corrected” what needed to be corrected: after checking the Pandoc installation sequence, I discovered I should run

Yeah, this sometimes happens, if homebrew has a hiccup, I experienced this myself. Glad it worked out!
