### ISSUE TITLE
[FEATURE] If codemirror supported vim-mode plugins, could zettlr use them?

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#1284]
## Description

vim mode is great, but comes with a cost to power vim users.  In vim, I use several plugins that significantly improve moving and editing within files.  ([vim-sneak](https://github.com/justinmk/vim-sneak) and [vim-surround](https://github.com/tpope/vim-surround) are two of the most indispensible.)

Turning on vim mode in zettlr activates my "vim muscle memory", and makes me feel productive... until I try taking an action based on one of these plugins.  Then it really wrecks my flow.

I know zettlr/codemirror will never support vimscript, so we'll never be able to install these plugins.  That's fine.  I do wonder, though... would it be possible to write a _codemirror-native_ plugin for vim mode that essentially re-implements the "API" of these plugins?

Obviously, in any case, this is not a zettlr issue _per se_.  But zettlr is the only codemirror client I care about.  Thus, before I consider actually investigating this kind of plugin, I need to know whether it would actually make any difference to my zettlr experience even if I succeed.

So, what I want to know is: if somebody wrote "vim mode plugins" for codemirror, would zettlr be able to take advantage of them?

- [ ] Yes, it would be trivial.
- [ ] Possibly, but it would require additional work on zettlr's part.
- [ ] No.

What do you think?

## Example Workflow

- Somebody writes a codemirror vim-mode version of, say, vim-sneak.
- I install this plugin to zettler, by (insert methodology here).
- When I activate vim mode, I am able to move around the document more easily by searching character pairs (as provided by vim-sneak).

## Caveats

N/A

## Additional Information

N/A

**Comment by nathanlesage** [comment]
> would it be possible to write a codemirror-native plugin for vim mode that essentially re-implements the "API" of these plugins?

Yes

> So, what I want to know is: if somebody wrote "vim mode plugins" for codemirror, would zettlr be able to take advantage of them?

Yes

***

Chiming in on this; what you need is the following:

1. Define a CodeMirror plugin
2. Map a certain key to it.

More specifically, have a look at the plugins written for Zettlr:

https://github.com/Zettlr/Zettlr/blob/7d6d049c8ec1259d81402b944d5627e5be579e72/source/renderer/assets/codemirror/zettlr-plugin-markdown-shortcuts.js#L212-L218

This simply defines a command for CodeMirror that can be called in a variety of ways (both programmatically, and via shortcut)

Then, you can add this command to a keybinding:

https://github.com/Zettlr/Zettlr/blob/7d6d049c8ec1259d81402b944d5627e5be579e72/source/renderer/assets/codemirror/generate-keymap.js#L42

With regard to vim-only commands, you'd need to modify the VIM keymap. Please refer to the CodeMirror documentation on ways to do this.

***

### How can these plugins be incorporated?

I'm against committing these plugins directly into the codebase (b/c of reusability for other clients of CodeMirror), hence here's what I'd suggest:

1. Create a standalone repository with the code of the plugin
2. When it works, publish to npmjs.com
3. Then, `yarn add` the plugin to the Zettlr codebase
4. `require` it in [this file](https://github.com/Zettlr/Zettlr/blob/develop/source/renderer/assets/codemirror/plugins.js)
5. TEST IT (!), especially that the keybinding only works in vim mode
6. Open a PR, and see it being merged ;)
