### ISSUE TITLE
[ENHANCEMENT] Rename File applied when you click away from the field.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1285]
## Description
I often find myself clicking away from the 'rename file' dialog, rather than pressing enter and my changes are discarded rather than saved.

## Proposed Changes
Save changes when you click away from the _Rename_  dialog. Add an explicit 'cancel' action by pressing **Esc**.

## Caveats
If there are users use the current behaviour as part of their workflow there maybe some unintentional file renaming.

## Additional Information
Discuss!

**Comment by nathanlesage** [comment]
You can already press Escape to close the popup (I think…? If not we can add this)

However, in this specific case, I have to ask you to change your habits to press Return. As I stated in many other issues and what is my experience with regard to UX, it is best practice to have such changes apply only explicitly by pressing Return.

Why? There are basically two methods for saving changes: (a) To make content editable (click on a file, and the name itself turns into a text field) and (b) to use popups. With regard to popups, it is common (and henceforth expected by most users) that if you click away, changes are not being persisted, whereas clicking Return is associated with "apply my changes". If we were to apply changes either way, it's way too hard for most users to "learn" having to press Escape explicitly. Plus, even apart from other applications which handle this case the same, it would mean a breaking change for Zettlr, as this would reverse the current behaviour. So I'll not implement this specific request, sorry! :)
