### ISSUE TITLE
Add project-specific CSL-files

### ISSUE THREAD

**Issue by Krande** [Zettlr/Zettlr#1286]
Hello,

continuing the discussion from issue #952 regarding the possibility to have a project specific CSL-file. Having CSL-file path to be set relative to the project root would significant improve the way we currently share projects in-house or when I change work stations (where in all the cases the project root is located in different places, making the absolute path to the CSL file different each time).

Let me know if I can help in advancing a solution to this issue,

Best Regards
Kristoffer

**Comment by nathanlesage** [comment]
Thanks for opening this up!

**Comment by the-solipsist** [comment]
A suggestion to consider: Just as Zettlr recognizes `title:` in the YAML metadata and changes the title, it would be great if it also recognized `csl:` or `bibliography:` path fields, and applied the paths provided there to the file being used.

**Comment by SigmaX** [comment]
Oh good, I was just about to open a feature request for exactly this. Ya'll beat me to it.  I like to put each Zettlr project into a separate git repo, and it would be more natural if I could commit a separate bibtex file for each project to manage references locally.

I'd add one requirement: it'd also be good to be able to open two projects at the same time, and have them each use a different references file.

**Comment by nathanlesage** [comment]
> A suggestion to consider: Just as Zettlr recognizes `title:` in the YAML metadata and changes the title, it would be great if it also recognized `csl:` or `bibliography:` path fields, and applied the paths provided there to the file being used.

Absolutely! This shouldn't be all too hard to incorporate either way. But, alas, it would be a different feature request! But shouldn't take too long to incorporate. Maybe we could open a thread to collect possible YAML frontmatter options which could override global ones?

**Comment by the-solipsist** [comment]
Just wanted to add a note that issue https://github.com/Zettlr/Zettlr/issues/459 already request the use-YAML-set-CSL/Bibliography request.

>  Maybe we could open a thread to collect possible YAML frontmatter options which could override global ones?

I'm my adding YAML-related comments to that issue, rather than here.

**Comment by nathanlesage** [comment]
Please move this discussion over to the new issue #1640
