### ISSUE TITLE
[DEVELOP] Fonts, and other assets are not packaged into the final app

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1287]
## Description

While during development everything works fine, the final app (more specifically, the created `app.asar`) does not contain any resources such as the fonts or the feather icon.

## Reproducing

Build the current develop branch using `yarn package` and open the resulting App/Exe/Binary. The developer tools will then tell you:

![image](https://user-images.githubusercontent.com/17251683/93768343-8f7df500-fc19-11ea-911d-5e5dd5153f24.png)

## Expected behaviour

Package the assets (or, if the assets are packaged, fix the paths)

## Platform
 - OS and version: macOS 10.15.6
 - Zettlr Version: 1.8.0-develop

## Additional information

Pinging @tobiasdiez: Do you know what the issue could be?

**Comment by tobiasdiez** [comment]
Looks like the following: https://github.com/electron-userland/electron-forge/issues/1196

**Comment by nathanlesage** [comment]
Thanks, I will have a look! :) If you manage to implement this quickly, please go forward!

**Comment by tobiasdiez** [comment]
I'm currently traveling, so sadly no access to a dev-setup.

**Comment by nathanlesage** [comment]
Easy, I'll try to spin up an early alpha on Friday so that we can begin gradually testing everything out … no hurry here.

**Comment by nathanlesage** [comment]
And fixed — the issue was precisely what went wrong! Thanks for the research.

**Comment by tobiasdiez** [comment]
Glad it worked!
