### ISSUE TITLE
[ENHANCEMENT] Add "Ask" Option for "Create non-existing files when following internal links"

### ISSUE THREAD

**Issue by hced** [Zettlr/Zettlr#1288]
## Description
Add "Ask" option for creating files when following internal links.

## Proposed Changes
In `Preferences > Zettelkasten` there's the option, `Automatically create non-existing files when following internal links`. I've never used this option because of the current "either on or off" choice, where I'm afraid I might litter my Notes folder with a lot of redundant/empty files and therefore would've prefered to be asked for confirmation before creating non-existing files.

My suggestion is to rename the text to `Create non-existing files when following internal links` and add the following choices (dimmed when main option turned off):
- `Always`
- `Ask`

## Caveats
None, AFAIK.

![create_non-existing_files_pref](https://user-images.githubusercontent.com/93350/93815128-ca9e1980-fc55-11ea-8590-4836f881ab73.png)

**Comment by nathanlesage** [comment]
Better idea, a radio option like the one above:

```
Create non-existing files when following internal links:
(*) Never
( ) Ask
( ) Always
```

**Comment by hced** [comment]
@nathanlesage Ha ha.. That's what I first did (your idea), but changed the picture to the one I posted. Sure, that'll work even better!
