### ISSUE TITLE
Possible colour inconsistencies on website

### ISSUE THREAD

**Issue by co16353sidak** [Zettlr/Zettlr#129]
On going through the website I find according to me some colour inconsistencies, what I mean by that is the colours used on the website (which are mostly bootstrap defaults) are conflicting from a UI point of view.
the yellow and the blue don't seem to merge well together but here it is attempted to do the same.

<img width="517" alt="Screenshot 2019-03-27 at 10 47 46 AM" src="https://user-images.githubusercontent.com/35738138/55052121-c489a580-507d-11e9-8c1d-26a72663d9b0.png">
`btn-groups` are usually best implemented by using the same primary colour.

here as well, the two alerts used here seem to have inconsistencies which disrupt the UI.

<img width="603" alt="Screenshot 2019-03-27 at 10 52 02 AM" src="https://user-images.githubusercontent.com/35738138/55052282-5db8bc00-507e-11e9-96fe-b6b657ac6eb0.png">

1. view the homepage.
2. click the download button
3. then view the page.

The colour scheme could be immensely changed, the `zettlr` green colour used on the website could be used to generate a set of ui colour which can be used on the website instead of the bootstrap defaults

Added all screenshots in description itself

## Platform
 - OS: macOS 
 - OS Version 10.14.3
 - Zettlr Version: not necessary, problem related to website
 - Screen Resolution: not necessary, problem related to website

## Additional Information
I would really love it if I could get involved in this project and if you deem this as a legal issue, I would love to work on it and submit a PR 🥇

**Comment by nathanlesage** [comment]
Hey, thanks a lot for paying attention! The website is a mess, honestly. It starts from the colours, but it gets worse afterwards (you haven't seen the backend yet :D)

During the past years, I've gradually adapted the website, but it wasn't the focus (the app was) which has ended in the current website. As I'm also involved in creating the translating service and the API, it's difficult keeping the website in good shape as well, but it's definitely going to be one of the next steps.

In case you would like to help, I'd greatly appreciate it! But this issue tracker is not the right place for this; so maybe you'd like to stay in contact via Email?
