### ISSUE TITLE
Footnotes cannot be created and do not render popup inside tables

### ISSUE THREAD

**Issue by mberasategi** [Zettlr/Zettlr#1292]
## Description

Footnotes do not display as a popup when hovering/Ctrl+clicking an anchor when inside a table.

## Reproducing

When adding a footnote reference (like `^[1]`) inside a table, it does not display the popup as when it is outside the table. Also the command to add a footnote (`Ctrl+Alt+F`  in Windows) does nothing when the cursor is inside a table.

## Expected behaviour

I would expect footnotes (command for new one and popup on hover/Ctrl+click) to work just the same inside the table as outside.

## Platform
 - OS and version: Windows 10 Pro
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920&times;1080

## Additional information

N/A

**Comment by nathanlesage** [comment]
Unfortunately, the table editor doesn't work the same way as the editor itself. This means, there's a lot of work necessary. We are collecting the discussion here: #632.
