### ISSUE TITLE
[FEATURE] Syntax high-lighting for Dart code blocks

### ISSUE THREAD

**Issue by boukeversteegh** [Zettlr/Zettlr#1293]
Just trying out Zettlr! It looks great and I'm eager to switch to it, but I have a lot of documentation written with Dart code examples, which are now not highlighted.

##  Description
Supporting syntax highlighting for the Dart language https://dart.dev

I think only `dart` needs to be supported as an identifier.

## Additional Information
https://codemirror.net/mode/dart/index.html

Let me know if I can help!

**Comment by Kangie** [comment]
Looks pretty simple. I'll have a go at it!

**Comment by Kangie** [comment]
@boukeversteegh, I've submitted a PR to enable syntax highlighting and everything seems to be working using some demo dart code that I scrounged up.

If you'd like to test before the PR is merged you can build the dart-highlighting branch in my fork, else it should be available in 1.8.0.

**Comment by boukeversteegh** [comment]
cool! thanks a lot 😁

**Comment by nathanlesage** [comment]
It's not a feature, it's an enhancement :-P

Coming in 1.8.x!
