### ISSUE TITLE
[ENHANCEMENT] Internal ID Links should resolve to file links on export

### ISSUE THREAD

**Issue by KieranFoley** [Zettlr/Zettlr#1294]
## Description
As it stands, internal wiki style links are either ignored or are inserted as dead links on export, meaning that while a Zettelkasten can be browsed within Zettlr, it cannot be browsed as a static site on export. I think ID links should be resolved to a filename and an appropriate link format on a group export of files.  

## Proposed Changes
Zettlr already has the functionality to search through a file and find an ID that's referenced in a link format of the form [[Unique_ID]], and does so by finding a colon and the unique ID of the file. It states in the documentation that it chooses the first ID it finds in a file and uses that as the ID. 

To implement this enhancement, I believe that the same system can be used to cycle through each internal link in a file, grab its ID, search the file directory for a file containing that ID (As it already does) and then grab the filename of the file containing that ID. This would then be converted into a markdown link of the form \[Unique_ID\]\(File_containing_ID\), which could then be ran through pandoc to generate a series of HTML pages. 

This way, a Zettelkasten can be written and browsed within Zettlr and filenames can be kept independent from links through IDs and internal links, but an export can then allow for a snapshot of the Zettelkasten which can be browsed and uploaded elsewhere. 

## Caveats
None that I can see.

**Comment by nathanlesage** [comment]
I know where you're going to with this, but I see a lot of issues with this request:

1. How should the resultant file links be generated? Zettlr could easily replace `[[12345]]` with `[Filename](/path/to/your/file)`, but that wouldn't work on uploading or on moving it elsewhere.
2. If you plan to take a snapshot of a Zettelkasten, this would imply that you'd like to export the whole thing, not just one file – and projects don't work like that, so we'd need a new feature for this.

This seems as if there's much more included in this request than a simple enhancement, don't you?

**Comment by KieranFoley** [comment]
@nathanlesage Yeah that's fair enough :) 

I'm kind of script literate rather than software engineering literate to be honest, so I'm not totally sure about how detailed this would be. I went with enhancement just because export to HTML and IDs were already an implemented feature, and it seemed to be an extension of that (kind of? But yeah I can see how it would be a new feature). 

But yeah, to answer those questions:

1) There could be a few options for that, but I think at the very least it should replace [[12345]] with [12345](/path/to/your/file] where path to your file is the file containing the ID. That way it works in the same way ID links work already and would appear the same in the generated output.

For the moving it elsewhere thing, I kind of seen it working as a mass export that would do the following (and this is probably crude, and proper programmers could probably conceive of it better):

- Specify an export directory
- Begin in the Zettlr file directory and open each note
- Store in a list the filename and ID for every note in the directory [(ID, file_name)(ID, file_name)...]
- Cycle through each file in the directory and replace each [[12345]] link with /[12345/]/(file_name/) - Have file_name either appended with md or html depending on markdown export or html export
- If the intention was to export to standard markdown, the new directory should now be filled with markdown files with markdown file links which respect each other 
- HTML: Convert all files in the new directory individually using pandoc to HTML, their markdown links should have filenames listed with ".html", so their links should work on conversion. 

- Finally, copy all attachments with into the same location as the original directory structure so that markdown links to these files still operate. 

2) And yeah I was implying importing the whole thing as a pack of individual HTML files (One for each note) to create a static site, or to create a standard markdown export to do the same, by collapsing the internal link system from Zettlr so that it could be used by other programs or for backups or if Zettlr ever goes out of development (Not saying that will happen necessarily, but assurance of data access is something important to me).

Should I edit the original post to [FEATURE]? Typing it all out feels more like a feature anyway so sorry about that haha

Also thanks for the app by the way! It's fantastic :)

**Comment by nathanlesage** [comment]
> Should I edit the original post to [FEATURE]?

At least, but whereas what you describe sounds reasonable, this would require a massive overhaul of the codebase, which I personally don't want to push into the repository :/ 

However, I'm still tinkering with the idea of including some form of script support for Zettlr (e.g. automating certain tasks). This would then enable such things. But I don't see this as a core feature of the application itself, both due to scope and because it's a more or less specific thing that can also be handled using Python (or any other scripting language).

Feel free to share any script you may come up with on the forum, but I'm afraid this is too big and too diverting from the goals of Zettlr to be implemented :/

In case of other opinions, make sure to comment here, or open a bigger thread, ideally on the forum or reddit!
