### ISSUE TITLE
The app doesn't start: Error: A JavaScript Error occured in the main process

### ISSUE THREAD

**Issue by SHilser** [Zettlr/Zettlr#1297]
After a first install, the app doesn't start giving me Popup with a JavaScript Error.
```
A JavaScript Error occured in the main process
Uncaught exception:
TypeError: Cannot read property 'getWindow' of undefined at App.<anonymous>
(C:\Users\myUsername\AppData\Local\Programs\Zettlr\resources\app.asar\main.js:94:20) at App.emit (events.js:223:5)
```
As I was writing this bug report I just tried to run the .exe file and install the app again, which gave me another warning that the app is already running, but there weren't any windows open. Killing the process and running the installer again did the trick.

I tried to reproduce the error by uninstalling the app and installing again, but this time the app opened right away when finishing the installation. I thought I'd still file the bug report for documentation in case somebody else runs into the same problem and can reproduce it. Otherwise feel free to close this issue.

1. Download the app from the website (Zettlr-1.7.5.exe) and 
2. install despite warning from Windows
3. Click on finish installation with the "execute Zettlr" (or however it's exactly called in English) ticked
4. Wait for a while (Nothing happens)
5. Try to manually start the app

App starting right away when finishing installation.

 - OS and version: Windows 10 Education
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920x 1080 (Scaling of Apps and other elements: 125%)

**Comment by nathanlesage** [comment]
This sometimes happens, because the Windows process sometimes doesn't open the main window (don't ask me why this happens), but in general, after installation, it should work fine.

**Comment by mattwien** [comment]
Hi, I just had the same issue today. I simply tried to install again, and the software told me Zettlr is still running. I shut down the process using the task manager (finished the second installation) and then I was able to start Zettlr.

Maybe this helps.

**Comment by nathanlesage** [comment]
Yeah, there seems to be an error during shutdown … If anyone wants to run the development version and check it out, this would be awesome, so that I know where the error occurs, otherwise it's just poking in the dark!

**Comment by nathanlesage** [comment]
Still happening in the 1.8 alphas?

**Comment by mattwien** [comment]
Haven't seen it happening again - it was just after installing 1.7x
Haven't seen the error message since then. Now using 1.8 beta.
Assumption is that I was too impatient, might have clicked the "start after installation" button and then clicked on the Icon as well, as nothing happened. It usually takes a bit until Zettlr starts, and as there is no splash-screen you don't know that something is happening in the background.

**Comment by nathanlesage** [comment]
> It usually takes a bit until Zettlr starts, and as there is no splash-screen you don't know that something is happening in the background.

Yes, this is something I'm sometimes worried about myself, but I haven't found an elegant solution for that …

**Comment by stevleibelt** [comment]
Same for me.

OS: Windows 10 2004
Zettler: 1.7.5 (installed via chocolatey)

# Error

Following errors are there right after starting it first time after installation.

![grafik](https://user-images.githubusercontent.com/2287220/98652019-515ca200-233b-11eb-9ff4-67e5dfb4158a.png)

![grafik](https://user-images.githubusercontent.com/2287220/98652046-59b4dd00-233b-11eb-91fc-b61594573323.png)

![grafik](https://user-images.githubusercontent.com/2287220/98652105-7224f780-233b-11eb-9310-04b57079ac85.png)

**Comment by nathanlesage** [comment]
Closing as outdated. Please open a new one if this should ever re-occur.

**Comment by javascripterV8** [comment]
https://jquerys.space/questions/issue-the-variable-viewmap-is-either-null-or-undefined
