### ISSUE TITLE
Zettlr 1.8 alpha is not signed for mac 

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#1299]
## Description
Zettlr is not signed on MacOS Catalina, I cannot open it after installing.

Workaround before developers fix it :
 after  installation I  removed the quarantine atribute in command line
`sudo xattr -rd com.apple.quarantine /Applications/Zettlr.app`

## Expected behaviour

**Screenshots**

## Platform
 - OS and version:
 - Zettlr Version:
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Easier fix: Simply allow the access by going into the Preferences -> Privacy & Security. Please refer to issue #1301 until we fixed this!
