### ISSUE TITLE
Zettlr does not seem to follow file hierarchy anymore?

### ISSUE THREAD

**Issue by brimwats** [Zettlr/Zettlr#1302]
## Description

I just wanted to move some files from one folder to another in my zettlr and dragging them didn't seem to work. So I opened the file manager and moved them but then that wasn't copied in Zettlr and never showed up? I

## Reproducing

Move MD files from one folder to another 

## Expected behaviour

The change should be reflected... but instead it means tha tI have to delete the entire fole, then re-add a file in zettlr? I cant add a local file through the file manager anymore and then have it show up in zettlr? Or maybe there's a delay? I'm very confused 

**Screenshots**

![image](https://user-images.githubusercontent.com/49103046/94083068-351a9b00-fdb7-11ea-9c4c-e4f959f246ac.png)

wat

## Platform
 - OS and version: windows 10 latest
 - Zettlr Version: latest

## Additional information

I know I used to be able to do it and it's why I preferred zettlr

**Comment by Kangie** [comment]
Dragging files between folders in Zettlr does work, but it can be kind of picky, and the UI doesn't clearly indicate when you can drop things sometimes. Other times it looks like you should be able to, but you can't.

I've encountered the other issue before too, restarting Zettlr should make the files appear when it rescans the directory, however watching for new files should pick that up, too. 

Can you reproduce this issue and watch the Zettlr logs to see if it's identifying the new files? You'll need to enable developer tools in settings and then develop -> show logs. 

Apologies for the vague instructions, I'm not in front of a computed right now!

**Comment by brimwats** [comment]
I had similar things as you. It looks like part of my problem however is that I thought the primary directory was by Box folder and not my Nextcloud folder

```
[00:45:29]	[WATCHDOG] Ignore event: unlink:C:\Users\Brian\Nextcloud2\Notes\Zettlr\Academic Paragraphs\2020.09.21_ProblemStatement.md
[00:46:21]	[WATCHDOG] Emitting event: add:C:\Users\Brian\Nextcloud2\Notes\Zettlr\Academic Paragraphs\2020.09.17_ProblemStatement.md
[00:46:21]	<<< IPC OUT: tags-database
[00:46:21]	<<< IPC OUT: sync-files
[00:46:21]	<<< IPC OUT: config-update
[00:46:21]	<<< IPC OUT: dir-replace
[00:46:21]	[WATCHDOG] Emitting event: unlink:C:\Users\Brian\Nextcloud2\Notes\Zettlr\UBC\2020.09.17_ProblemStatement.md
[00:46:21]	Could not process event unlink for C:\Users\Brian\Nextcloud2\Notes\Zettlr\UBC\2020.09.17_ProblemStatement.md: The corresponding node does not exist anymore.
```

**Comment by nathanlesage** [comment]
After rewriting the whole FSAL to TypeScript, I've run extensive tests, and right now it should work perfectly. Especially the registration of remote changes to the directory structure are now handled like a charm!
