### ISSUE TITLE
AppImage of 1.8.0 build doesn't start

### ISSUE THREAD

**Issue by AlienTux** [Zettlr/Zettlr#1303]
## Description

AppImage doesn't start up

## Reproducing

Download, set AppImage to executable, try to run

## Expected behaviour

Execute

Here's the code reported on the terminal:

```
kurt@kurt-lin ~/bin/AppImages $ ./Zettlr-1.8.0-alpha-x86_64.AppImage 
/tmp/.mount_ZettlrXnXW5e/AppRun: line 43: /tmp/.mount_ZettlrXnXW5e/zettlr: No such file or directory
kurt@kurt-lin ~/bin/AppImages $ 
```

## Platform
 - OS and version: Solus 4.1 Gnome
 - Zettlr Version: 1.8.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Thank you for reporting! We will have a look!

**Comment by nathanlesage** [comment]
Duplicate of #1304
