### ISSUE TITLE
Deb package for 1.8.0-alpha does: /opt/Zettlr/zettlr not found

### ISSUE THREAD

**Issue by boutil** [Zettlr/Zettlr#1304]
Hi,

After installing `Zettlr-1.8.0-alpha-amd64.deb`, I am unable to launch Zettlr via the menu system.
The .desktop file is refering to `/opt/Zettlr/zettlr/` which is not present in the package, instead of `/opt/Zettlr/Zettlr`.

Changing manually `/usr/share/applications/zettlr.desktop` to capitalize zettlr in the `Exec=` line fixes the issue.

**Comment by boutil** [comment]
The file posinst script of the Debian package also fails to create a working symbolic link to `/usr/bin/zettlr` as it expect `/opt/Zettlr/zettr` as the source.

Instead of capitalizing in the .desktop file, the solution seems to rename /opt/Zettlr/Zettlr to /opt/Zettlr/zettlr (as it was before?)

**Comment by nathanlesage** [comment]
AppImages have the same problem, as reported:

```
/tmp/.mount_ZettlrXnXW5e/AppRun: line 43: /tmp/.mount_ZettlrXnXW5e/zettlr: No such file or directory
```

Same as the opt-path (only this time within the AppImage container).

**Comment by nathanlesage** [comment]
Update: Newly generated `-deb`-files still have an uppercase `Zettlr` binary, whereas the `.desktop`-file still points to the lowercase one. No idea why.

**Comment by nathanlesage** [comment]
And fixed!

**Comment by webopold** [comment]
Would be nice if lowercase would be used all the time, as it is common habit.
Is packaging for i386 also affected?

**Comment by nathanlesage** [comment]
> Would be nice if lowercase would be used all the time, as it is common habit. Is packaging for i386 also affected?

Yes, this would be, but unfortunately, electron-forge does not seem to support that. As on Linux and Windows, binaries are not really visible, but on macOS they are, we needed to switch to uppercase binaries. All packaging have been affected, but, as I mentioned, the newly released alpha already fixes this (albeit, as I said, with uppercase binary name, which may break a habit, but not the program)
