### ISSUE TITLE
missing dependencies for the debian package

### ISSUE THREAD

**Issue by boutil** [Zettlr/Zettlr#1305]
Currently, the last line of the postinst script is failing, because the command `update-desktop-database` is not found.
This command belongs to the package `desktop-file-utils` in Debian and its derivative, which has priority optional, meaning that it may be not installed on a machine a priori (like mine).
Similarly, the line before uses `update-mime-database`, contained in `shared-mime-info`, with the same priority.

Could you please add these two packages `update-mime-database` and `shared-mime-info` to the list of dependencies, so that the postinst script can run fully? (or add a check to see if the commands are present before trying to run them, as in the end, they don't play a crucial role)

**Comment by boutil** [comment]
This has more to do with electron-forge than Zettlr itself.
Since the commands are `or`ed with true, the combination always succeeds even if the command is not found.
It is better to close this report, as not relevant with Zettlr.

**Comment by nathanlesage** [comment]
Huh? I mean I would really like to do it; do you gave any hints as to how we can amend the configuration?

**Comment by boutil** [comment]
According to the documentation of electron-forge, it is possible to declare extra dependencies in the "deb": section of the `package.json` file. Since these two packages are not mandatory, a 'recommends' level seems enough (instead of depends).

Adding
```
"recommends": ["update-mime-database", "shared-mime-info"]
```
in the `"deb"` section of package.json should do. By default, these packages would be installed as dependencies unless the users explicitly mention that they do not want recommended packages.

**Comment by nathanlesage** [comment]
Thank you, I'll see to adding these!

**Comment by nathanlesage** [comment]
Short follow-up question: Where exactly did you find this information? I couldn't find any documentation for the `recommends`-property!

**Comment by boutil** [comment]
It comes from here:
https://js.electronforge.io/maker/deb/interfaces/makerdebconfigoptions#recommends
but it doesn't seem to be what you are using :( Sorry to have put you on a wrong trail.
I should have tried myself first. No "recommends" property indeed as it is now (strange there is no...).
Still "depends" could be used, but that is maybe too strong a relation with these extra packages.

**Comment by nathanlesage** [comment]
Hm, feel free to test it out -- but I will release another alpha in the next days to hopefully have this sorted out
