### ISSUE TITLE
[ENHANCEMENT] Make opening files more intuitive.

### ISSUE THREAD

**Issue by andypea** [Zettlr/Zettlr#1306]
##  Description

It took me about 10 minutes of googling and experimenting before I could figure out how to open an existing markdown file in Zettlr. Zettlr has many nice features, but I don't feel comfortable recommending it to my colleagues when the process of opening files is so different from the standard approach used in most other pieces of software.

## Proposed Changes

Add a new path for opening existing markdown files that closely matches the typical workflow in other pieces of software, such as Microsoft Word.

## Caveats

A comment on issue #236 mentions that "Zettlr is made for working mainly with directories". As a novice user, I don't completely understand this point, but it seems important.

**Comment by Kangie** [comment]
Dupe of #1307, #236

**Comment by nathanlesage** [comment]
Hey, sorry for the really slow answer, but: You can in fact open files in the standard way, but there were some bugs which are fixed in the upcoming 1.8 release. Furthermore, you can from 1.8 onwards open regular files using the known shortcut `Ctrl/Cmd+O`.
