### ISSUE TITLE
Editor: Render/Preview inline LaTeX math formulae in Markdown table

### ISSUE THREAD

**Issue by marbetschar** [Zettlr/Zettlr#1308]
Would be great if the Zettlr Editor becomes capable of rendering inline LaTeX formulae inserted into a Markdown table:

|   LaTeX    | in Table                                 |
|----------|-------------------------------|
| $a = b$ |  $\sum_{n = 1}^{\infty} x_{n}$ | 

Seems like pandoc is capable to do so - at least, if this is exported to PDF the formulae are rendered correctly.

For copy & paste convenience:

```
|   LaTeX    | in Table                    |
|----------|-------------------------------|
| $a = b$ |  $\sum_{n = 1}^{\infty} x_{n}$ | 
```

**Comment by nathanlesage** [comment]
Closing in favour of issue #632, please comment there!
