### ISSUE TITLE
Writing Statistics and Preferences/Zettelkasten menus overflow the screen

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#1310]
## Description

For both menus the screen seems to be shifted down compared to other menus. This is most obviously seen when switching between the Zettelkasten page in Preferences and other mpages.

## Reproducing

Enter any of the two menus.

## Expected behaviour

Have the menus well centered.

**Screenshots**

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha
 - Screen Resolution: 1920*1080

**Comment by nathanlesage** [comment]
Would you mind adding some screenshots outlining precisely your problem? This would help! Thanks!

**Comment by BellLongworth** [comment]
Note: The Windows taskbar begins at the bottom just when the screenshots end.

Normal preferences menu:
![image](https://user-images.githubusercontent.com/63842998/94344517-97c69d80-0028-11eb-9f09-e3b9de2b5e07.png)

Zettelkasten menu:
![image](https://user-images.githubusercontent.com/63842998/94344557-e7a56480-0028-11eb-9406-cff1549dd903.png)

More statistics menu:
![image](https://user-images.githubusercontent.com/63842998/94344535-c17fc480-0028-11eb-8d7c-259c0af2e4ad.png)

**Comment by nathanlesage** [comment]
Ah, this. I now reduced the added margin for overflowing windows, so it should look better. But in general: Some preferences windows are too large for smaller screens and this is the best option we've found to fit them on screen, by scrolling them.

**Comment by BellLongworth** [comment]
Wonderful, thanks!

Though I should note that 1920*1080 is not exactly "smaller screens". It is about typical, no? So maybe some windows should be designed to be more compact. Very low priority obviously, but one day when you have time for this kind of optimization. :)

**Comment by nathanlesage** [comment]
> So maybe some windows should be designed to be more compact.

Sure thing; if you feel like playing around a little bit, do so! PRs always welcome :)
