### ISSUE TITLE
Allow a custom location for the user dictionary file

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#1311]
## Description

Allow keeping the user dictionary file in a user specified location. This will enable the user to place the file in a cloud synced folder, avoiding losing the entire dictionary when doing a clean OS install or moving between computers.
Based on a true story.

## Proposed Changes

Have a path selector in the Preferences->Spellchecking screen.

## Caveats

Placing the file in a different place may increase the probability of accidental editing and screwing something up?

**Comment by nathanlesage** [comment]
You can't really destroy it, as it's simply one word per line, but locating it someplace else might work.

**Comment by BellLongworth** [comment]
Ah yes, I know I could've saved it and copied it back to the new install. But frankly the Zettlr dictionary file is just not something you think about when formatting the OS drive.

**Comment by BellLongworth** [comment]
To be clear: In no way do I think this is actually important to implement anytime soon. In my line of work I like to have a long backlog of even unimportant items, as the future where they are relevant always comes. Some prefer having only the important stuff in front of their eyes, in which case this suggestion is a great candidate for deletion.
