### ISSUE TITLE
[ENHANCEMENT] Files opened from the OS should automatically open in Zettlr – not just open the app

### ISSUE THREAD

**Issue by hced** [Zettlr/Zettlr#1312]
##  Description
When opening a document from the OS, by double-clicking on it or by any other means (such as a file launcher like [ueli](https://ueli.app/)), the only result is that Zettlr opens. The requested document does not open automatically ... so I have to navigate to it once again inside Zettlr.

## Proposed Changes
Documents opened from the OS should also automatically show up inside Zettlr, instead of simply just opening the app.

## Caveats
None that I could think of, really :)

## Additional Information
I'm on Windows 10 Pro version 2004 (OS build 19041.508) using Zettlr 1.7.5.

**Comment by Kangie** [comment]
Hm. Odd. My experience is that with proper file associations set, Zettlr opens the file directly.

If Zettlr is open and you double click on a file, what happens?

**Comment by hced** [comment]
> If Zettlr is open and you double click on a file, what happens?

I’m on my phone and can’t check, but, nope. That doesn’t open the file in Zettlr for sure. If I recall correctly, that would only activate the app.

**Comment by nathanlesage** [comment]
Files can currently be somewhat unstable due to a missing check on application boot, will take care of that!

**Comment by klieret** [comment]
When I open zettlr from the command line on Ubuntu 19.10, zettlr 1.7.5,  `zettlr myfile.md` also just opens zettlr and not the file itself (irregardless of whether zettlr is already running or not). Would be really happy if that could be improved :)

**Comment by nathanlesage** [comment]
Now it should work as expected.
