### ISSUE TITLE
Vim Mode: checking checkbox in normal mode doesn't check the checkbox in the actual markdown

### ISSUE THREAD

**Issue by rafedramzi** [Zettlr/Zettlr#1313]
## Description

The markdown checkbox doesn't check if you check in normal mode

## Reproducing

Start with this markdown
```markdown
- [ ] check me!
```
This should be rendered as checkbox, great!
Now, make sure your vim keybinding is enabled and you're in normal mode and put your cursor on the checkbox, and revealing the original markdown of the checkbox, the value is:
```markdown
- [ ] check me!
```

not 
```markdown
- [x] check me!
```

However, if repeat the step above but in insert mode instead of normal mode, things  works fine.

## Expected behaviour

The value should be 
```markdown
- [x] check me!
```

## Platform
 - OS and version: Linux hostname 5.8.10-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 17 Sep 2020 18:01:58 +0000 x86_64 GNU/Linux
 - Zettlr Version: 1.7.5

## Additional information

頑張ってください.

**Comment by nathanlesage** [comment]
In the current 1.8.x development branch, this bug does not occur, so I assume this has been fixed in the meantime. Please feel free to test out the most recent release to verify this. If the bug should re-occur, please comment here again so that we can have another look!
