### ISSUE TITLE
[ENHANCEMENT] Double-click to fix transient tab

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1318]
## Description

It would be very convenient to be able to double-click a transient tab to make it fixed (like in VSCode).

## Proposed Changes

We already have middle-mouse click to close a tab (like VSCode), so the suggested enhancement should be similar to implement.

## Caveats

None that I'm aware of!

## Additional Information
None.

**Comment by nathanlesage** [comment]
Comes with the huge refactor that I'm about to commit! Will ship with the next release.
