### ISSUE TITLE
Can't create new directories in Zettlr-1.8.0-alpha.1-x86_64.AppImage

### ISSUE THREAD

**Issue by ritvje** [Zettlr/Zettlr#1319]
## Description

I can't create new directories in Zettlr, either by right-clicking and selecting `New directory`, or `File->New directory`, or the shortcut `Ctrl+Shift+N`. 

If I create the directory elsewhere, Zettlr shows it immediately.  

## Reproducing

Take the mouse to the left sidebar, right click and select `New directory`. Or in top bar, select `File->New directory`. Or press `Ctrl+Shift+N
`
## Expected behaviour

The dialog for writing name of new directory opens in the left sidebar.

## Platform
 - OS and version: Ubuntu 18.04, linux 5.4.0-48-generic (architecture: x64)
 - Zettlr Version: Zettlr-1.8.0-alpha.1-x86_64.AppImage

**Comment by nathanlesage** [comment]
Is a directory selected in the sidebar while you perform one of the three mentioned actions?

**Comment by ritvje** [comment]
Yes. Nothing happens if I select a directory and then do any of the three ways to create a new directory. In the previous version 1.7.5 it works.

**Comment by nathanlesage** [comment]
Perfect, thank you for the quick feedback!

**Comment by Kangie** [comment]
Can replicate, Win10 20.04. Related to #1324? Is FSAL a little broken?

**Comment by nathanlesage** [comment]
I'll have a look today!

**Comment by nathanlesage** [comment]
Found the error, was caused by the migration from jQuery to vanilla JS!
