### ISSUE TITLE
Double click in search bar toggles maximized window state

### ISSUE THREAD

**Issue by klaus7** [Zettlr/Zettlr#132]
## Description
If you want to select a word in the global search bar with a double mouse click, the window's maximized state toggles.

## Reproducing
Double left mouse click in global search bar.

## Expected behaviour
No window maximize state toggle.

**Screenshots**

## Platform
 - OS: Ubuntu 18.04
 - Zettlr Version 1.2.1

**Comment by nathanlesage** [comment]
Fixed in tomorrow's release.
