### ISSUE TITLE
[BUG] Pomodoro timer stuck on short break in 1.8.0-alpha.1

### ISSUE THREAD

**Issue by montd** [Zettlr/Zettlr#1320]
## Description

Pomodoro after counting down from work time signals end, however the timer does not move forward when in "short break"

## Reproducing

Set pomodoro timer to 1 minute

## Expected behaviour

Should count down from set time and start next "work" timer.

https://i.imgur.com/hRHLuRL.png

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.1

**Comment by nathanlesage** [comment]
Thanks for reporting!
