### ISSUE TITLE
Launching off screen, can't see or move window. 

### ISSUE THREAD

**Issue by Shazib** [Zettlr/Zettlr#1322]
## Description
Zettlr launches but the window is not visible on screen anywhere. I can see it in the taskbar and with Win+Tab I believe this is because i had an ultrawide monitor with it pinned to one side, and now that i'm on a regular monitor, it remembers its position and is drawing itself off the screen.

I can't select it via Alt+Tab and then win Win+Left/Right to move it. so its there, its open, but just permanantly off screen.

The 'new update' popup is visible if i hover over the taskbar. Maybe this is why Win+Left/Right doesn't work

## Reproducing
No longer have the ultrawide and can't reproduce.

## Expected behaviour
Open somewhere i can see it, or acept Win+Left/Rioght

## Platform
 - OS and version: Win10 v1903
 - Zettlr Version: 1.7.1

**Comment by nathanlesage** [comment]
In this case, please remove the `config.json` and start Zettlr. It will open normally. A better handling will come and is tracked in issue #1039
