### ISSUE TITLE
[BUG]: Adjusting heading levels by adding or removing a `#` causes Zettlr to scroll the heading offscreen.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1323]
## Description

When adjusting heading levels on a file within a project, the the heading is scrolled offscreen sometime after you adjust the heading level.
## Reproducing

Within a MarkDown file that has multiple headings, click within a heading and add (or remove) a # to change the heading level. 
Zettlr will adjust the viewed section of the document so that the heading is offscreen ('above' the visible area of the file).
## Expected behaviour

Zettlr should focus on the line being modified.

## Platform
 - OS and version: Win10 20.04
 - Zettlr Version: 1.8.0-alpha.1

## Additional information

This is somewhat inconsistent; the majority of the time adjusting a heading level triggers this bug but not all the time. I do have several large images towards the beginning of this file, above the headings that I'm adjusting.

**Comment by nathanlesage** [comment]
I have also noticed this, but I have no idea why this happens. I suspect some of the Zettlr configurations doesn't play well with CodeMirror's internal assumptions, but I haven't been able to pinpoint something there :S

**Comment by nathanlesage** [comment]
This should've been fixed with one of the most recent pushs, I currently suspect calling `codeMirror.refresh()` is not the most useful option 👀
