### ISSUE TITLE
[BUG]: Buttons at top of screen stop working.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1329]
## Description

The buttons at the top of the screen (export, rename file, etc. [with the exception of Text Formats]) stop working occasionally, requiring that the editor tab be switched to a new file before they will work again.
## Reproducing

I am unable to reproduce this behaviour at will, but do have a consistent workaround. 
There is nothing logged by Zettlr when these buttons are pressed while they are not working.
## Expected behaviour

These buttons should always expand / trigger the apprporiate action. 

![image](https://user-images.githubusercontent.com/9733178/95408688-c79c6c00-096b-11eb-965e-7eed80a59763.png)

## Platform
 - OS and version: Win10 20.04
 - Zettlr Version: 1.8.0-alpha.2

**Comment by Kangie** [comment]
Hm. I note that the file I was editing when I encountered this bug was not saved when I restarted Zettlr. Possibly related?

**Comment by nathanlesage** [comment]
> Hm. I note that the file I was editing when I encountered this bug was not saved when I restarted Zettlr. Possibly related?

After a restart the state is reset, so no, but I was too lazy to yeaterday fix an interesting quirk that Zettlr would sometimes not close files whose tabs is closed, so I have this on my list already, I'll have a look at the buttons too.

**Comment by nathanlesage** [comment]
Oh and btw, I will need some way to reproduce this bug, because obviously "works for me" right now 🙄

**Comment by Kangie** [comment]
Of course. If I can't repro I'll close this off until I find a way to get it to occur.

**Comment by nathanlesage** [comment]
How's it going with the current alpha?

**Comment by Kangie** [comment]
Honestly, I got stuck working on latex templates and shell scripts for a week or so there. I haven't seen it since, nor has it occurred in the new alpha so I'll close this until I can reproduce it in some form or another. 

Loving the new features!
