### ISSUE TITLE
No new directoy created via File > New directory…

### ISSUE THREAD

**Issue by foss-** [Zettlr/Zettlr#133]
## Description

Can't create new directories in Zettlr 1.2.2.

## Reproducing

File > New directory…

## Expected behaviour

New directory name should be asked and new directory created.

![Neues Verzeichnis erstellen](https://user-images.githubusercontent.com/5708172/55276328-f6f00880-52f2-11e9-9334-72d73393ac85.gif)

## Platform
 - OS: macOS 10.14.4
 - Zettlr: 1.2.2

**Comment by nathanlesage** [comment]
Found the error, will fix it tomorrow!
