### ISSUE TITLE
[BUG]: Readability mode cannot be enabled. 

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1330]
## Description

The Readability Mode button does not work.
## Reproducing

1. Open a file with some content.
2. Click the 'Readability Mode' button.
3. Observe no change to your content. 
## Expected behaviour

Readability mode should be enabled.

## Platform
 - OS and version: Win10 20.04
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
Yeah I know, was too lazy yesterday to fix that too :D (As with precisely all bugs you just reported, hehehe)
