### ISSUE TITLE
Tags erroneously detected inside fenced code blocks

### ISSUE THREAD

**Issue by bit-hug** [Zettlr/Zettlr#1334]
## Description
Fenced code blocks may contain the hash symbol but should not contain tags for detection by Zettlr. However, in the example below `#0` is detected as a tag.
![tag #0 in codeblock](https://user-images.githubusercontent.com/8385847/95476783-82823500-097f-11eb-8f36-c56a58366a36.png)

## Reproducing
In any fenced code block, include a single backtick, then later within the same fenced code block include a hash character followed immediately by at least one non-whitespace character.

## Expected behaviour
Since a single backtick within a fenced code block needn't be escaped in markdown, Zettlr should consistently ignore the hash within the code block when parsing the file for tags regardless of the preceding backtick.

## Platform
 - OS and version: macOS version 10.13.6
 - Zettlr Version: 1.7.5

## Thanks
As I haven't posted here before, I just wanted to say thank you for your efforts developing Zettlr. I very much appreciate the design philosophy evident in all aspects of its implementation.

**Comment by nathanlesage** [comment]
Cannot reproduce in the 1.8.x-develop branch, so I'm assuming it has been fixed meanwhile. If it occurs in the 1.8.0 stable, please comment here so we can have another look.

**Comment by bit-hug** [comment]
This bug persists in 1.8.0 stable.

**Comment by nathanlesage** [comment]
Found the error, I originally did not pay too much attention to the fact that there was an uneven number of backticks in your code block (which made the code extraction fail for the complete block) – I've now adapted the regular expression to remove code from the file so it should work out now.
