### ISSUE TITLE
[FEATURE] Chocolatey prerelease packages

### ISSUE THREAD

**Issue by marcinsmialek** [Zettlr/Zettlr#1335]
## Description
Zettlr can notify about new pre-release versions when ticking Advanced -> Notify my about beta releases.
Can you prepare Chocolatey packages when uploading such release too? It would make chocolatey auto-update much easier, especially as there are 1.8.0 alphas out now.

## Example Workflow
```
choco search --pre zettlr
zettlr 1.8.0-alpha.2 [Approved]
```

Alternatively, having 1.7.5 installed, `choco upgrade --pre zettlr` would bump it to 1.8.0-alpha.2

## Caveats
Minor issue related to how choco works: Chocolatey doesn't offer any means to stay on pre-releases until the next stable release. Effectively if one initially installs Zettlr via chocolatey with `--pre` argument, and forgets about it, while having chocolatey `useRememberedArgumentsForUpgrades` feature enabled, then they may get updated to unstable release later on.

## Additional Information
The current stable packages look fine. I guess that if you created ones in similar way, only with "pre" flag added, it would be just fine.
Alternatively, you might consider using something like [Squirrel](https://github.com/Squirrel/Squirrel.Windows) for auto-update.

**Comment by nathanlesage** [comment]
The Chocolatey packages are managed by a third party, please get in touch with their maintainer to make this happen!
