### ISSUE TITLE
Zettlr does not respect system date and time format settings

### ISSUE THREAD

**Issue by marcinsmialek** [Zettlr/Zettlr#1336]
## Description
Zettlr does not respect the operating system date and time formats, and there is no place in settings to override it.

## Reproducing
1. Set Windows regional format to not-like-in-US
2. Start Zettlr (it doesn't matter what language you pick in Zettlr - tried US/UK English, and German)
3. The note date and times are displayed in US way: "October 8, 2020 5:37 PM"

## Expected behaviour
Zettlr follows system date formatting, in this case "08.10.2020 17:37"
Eventually, there might be a setting to provide date/time template.

## Platform
 - OS and version: Windows 10 x64 20H2 19042.546, US English; regional formats set to Polish
 - Zettlr Version: 1.8.0-alpha.2

## Additional information
I think that the best option would be to have a setting for template, and in case it's not filled, then fallback to operating system format.

**Comment by nathanlesage** [comment]
Known bug, we need to switch from moment.js to an alternative. Currently, the locales are not being loaded. I just used the Intl object directly, so it should work again.
