### ISSUE TITLE
Citation autocomplete not working in 1.8.0-alpha.2

### ISSUE THREAD

**Issue by ritvje** [Zettlr/Zettlr#1338]
## Description

When typing `@`, no citation autocomplete list is opened. If the citation keys are typed manually, they are rendered and exported as well shown in the sidebar correctly. The autocomplete works as I expect in 1.7.5.

## Reproducing

Make sure that citations are enabled as described in [documentation](https://docs.zettlr.com/en/academic/citations/). Type `@` in any file.

## Expected behaviour

When typing `@`, a list of available citations opens.

## Platform
 - OS and version: Ubuntu 18.04, linux 5.4.0-48-generic (architecture: x64)
 - Zettlr Version: Zettlr-1.8.0-alpha.2-x86_64.AppImage

**Comment by nathanlesage** [comment]
Already fixed in current develop branch, coming with the next release!
