### ISSUE TITLE
Linux Install Issues

### ISSUE THREAD

**Issue by j-proc** [Zettlr/Zettlr#134]
## Description
Install issue. Seems to be related to electron?
Nothing happens when trying to open normally.
From the terminal reveals this:
`The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.`

If you sudo chown and then sudo chmod to fix this, it seems to work then.

## Expected behaviour
Install and work simply as previous versions did.

## Platform
 - OS: Arch (Previous versions worked fine and should be the same here)
 - OS Version Kernel 4.19.30
 - Zettlr Version 1.2.1

**Comment by jcuenod** [comment]
Yup, I'm getting the same thing and I just pulled 1.2.2

**Comment by j-proc** [comment]
Try the sudo fix? Can anyone on a Debian based distro verify. This really shouldn't be distro dependent as it's a very basic functionality.

**Comment by samarulmeu** [comment]
On Ubuntu I had no problem. I am currently running 1.2.2

**Comment by nathanlesage** [comment]
Maybe this is related to Zettlr currently using Electron 5 `beta` …?

**Comment by j-proc** [comment]
@samarulmeu Thx for the info.

If it's only an issue on Arch based systems, a workaround is acceptable. Just as a note to any devs that come across this, you can feel free to close the issue if you prefer not to support arch based distros.

I can confirm that
`
sudo chown root /opt/Zettlr/chrome-sandbox
 & sudo chmod 4755 /opt/Zettlr/chrome-sandbox
`
fixes this issue on arch based distros and allows it to run.

**Comment by nathanlesage** [comment]
@j-proc Thanks for the confirm!

I prefer to also support Arch based distributions … but if it's an issue with either `electron-builder` or `Electron` … is there already an issue open?

**Comment by j-proc** [comment]
I'll try to look into that. Just from some Googling that was a guess. But I
suppose I could look into the build scripts to see where it comes from. You
can mark it appropriately in the meantime and I'll try to get back to you.

**Comment by jcuenod** [comment]
I can confirm the `sudo` fix does work (I'm running a clone of the repo so it's the `chrome-sandbox` in `./node_modules/electron/dist/chrome-sandbox`).

**Comment by TriciaHampton** [comment]
Same issue on debian buster.
Fix works here as well.

**Comment by TriciaHampton** [comment]
Perhaps chown/chmod in postinstall script of deb package to work around.

**Comment by nathanlesage** [comment]
Alright, the electron builder docs on this are virtually nonexistent, but I'll give it a try. So please stay tuned for a beta including this fix. I can't test it locally, so I appreciate any testing help with this!

**Comment by j-proc** [comment]
@nathanlesage  https://github.com/electron/electron/pull/17269 seems to be part of addressing it.

I don't do much with electron, so I haven't actually followed on how electron-build is seperate. https://github.com/electron/electron/issues/16631#issuecomment-476082063 is essentially the same as @TriciaHampton suggested, their suggestion is [this](https://github.com/vladimiry/ElectronMail/blob/d2a931771eaf2964829c07ed5587460f878f73eb/scripts/electron-builder/after-pack.ts).

And I guess this isn't arch specific. I'm not sure why ubuntu would avoid it. But until the external issue is fixed, it seems a patch as they suggested is a good option.

**Comment by nathanlesage** [comment]
Electron Builder is successfully running `chmod 4755` on the chrome sandbox, so it seems to work. New release due this afternoon, including the fix! Please comment whether or not it works, so that we can close the issue, eventually!

**Comment by jcuenod** [comment]
Hmm, that didn't seem to do the trick for me...

**Comment by nathanlesage** [comment]
mh … I wonder if I could chown root and whether this would make sense. Or probably we'll just hope for electron 5 to solve this problem …

**Comment by jcuenod** [comment]
My vote would be to wait for electron 5 before doing something like that...

**Comment by nathanlesage** [comment]
Alright, it should be right around the corner if nothing goes wrong with the Electron-Team. Let's hope sooner than later!

**Comment by vladimiry** [comment]
It was already possible to package compatible with suid sandbox deb/pacman builds using electron v5 beta releases and it's possible now with v5.0.0. See more info [here](https://github.com/electron/electron/issues/17972).

**Comment by nathanlesage** [comment]
I suppose that this issue can now be closed, as there were no additional complaints after release of the 1.3 beta!

**Comment by jcuenod** [comment]
Didn't even notice that it was working again, lol :)
