### ISSUE TITLE
Inserting tables from top button dont working anymore (1.8.0 alpha.2)

### ISSUE THREAD

**Issue by swl181** [Zettlr/Zettlr#1342]
## Description
Inserting tables from top button dont working anymore

## Reproducing
1. Click on top button
2. Select Insert table
3. Select cols and rows
And Zettlr do not insert table in my note

## Platform
 - OS and version: windows 10
 - Zettlr Version: 1.8.0 - aplha.2

**Comment by nathanlesage** [comment]
Fixed in upstream, coming with next release!
