### ISSUE TITLE
[ENHANCEMENT]: For PDF quick export, if within a project with textpl value set, use the specified template.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1344]
## Description

If within a Project directory, and the `textpl` value is set, PDF quick export should respect this and use the specified template.
## Proposed Changes

If MarkDown file for quick-export is: 

1. Within a Project directory; and
2. Has a `textpl` value.

Use the specified template for PDF export, rather than the built-in one.

## Caveats

None that I can think of!

**Comment by nathanlesage** [comment]
Has already been fixed, it was a weird bug but will come with the next release!

**Comment by Kangie** [comment]
> Has already been fixed, it was a weird bug but will come with the next release!

I'm working off develop at the moment just to get that fix. :)

> won't implement BECAUSE I will implement custom templates on a per-file basis, which is easier and better to understand (otherwise how so you realize whether or not it will use the project template or not? It's a little bit intransparent)

So, to clarify your planned implementation: in my use case where I have large project directories (100+ MarkDown files) I'd be expected to set the export template for each file *individually* within the project directory if I wanted to use the 'quick export' function to quickly preview changes without exporting the whole project (a 3-5 minute process).

It seems simpler (at least in the case of projects) to respect the template that the user has added for the project. 

As an end user I use the 'quick export' function to validate that things are exporting 'correctly' (how I expect the output to look) on a per-file basis before compiling and exporting the whole project. The further my latex templates diverge from the default Zettlr template, the less accurate the "quick export to preview changes" workflow becomes. 

The added burden of changing the export template for 100+ files is unattractive when there's a more elegant solution using functionality that exists already.

In saying that, for those that don't work within project folders I do see the utility of being able to set this on a per-file basis - I'd certainly adjust my workflow for a lot of the smaller (single file) documents that I write to take advantage of the functionality.

What are your thoughts? In the end Zettlr is your project, and I'll respect your decision on the matter.

**Comment by nathanlesage** [comment]
Hm, that's a valid concern I didn't think of! I'll leave this open as a discussion, because I clearly see why that is.

But the question would be: Wouldn't it be better to simply switch the global export template to quickly preview everything in the project instead? I could offer to add the option for a quick-switcher of those templates (e.g. you have an easy time setting the global export template).

The reason why I don't want this is because the single file export is fixed to the _file_ and it is intransparent to users whether the file is part of a project or not.

What would be transparent would be to offer a quick-switch-dropdown immediately in the exporting popup with a persistent setting to quickly switch (+ you immediately see which template will be used)

**Comment by Kangie** [comment]
If I can quickly and easily pick the template used in the quick export it eliminates most of my concerns, especially as that fits better with the Zettlr philosophy! It might be nice to extend that to the HTML5 and possibly odt/docx reference docs, too (though I note that there's currently nothing in the UI to expose custom templates for anything other than LaTeX).

I'm interested in what others have to say on the topic.

**Comment by nathanlesage** [comment]
> It might be nice to extend that to the HTML5 and possibly odt/docx reference docs, too (though I note that there's currently nothing in the UI to expose custom templates for anything other than LaTeX).

Have a look here --> #1193

**Comment by nathanlesage** [comment]
Quick update to this, refer to this issue for further info: #1552
