### ISSUE TITLE
Citeproc filter was changed to flag on pandoc >= 2.11

### ISSUE THREAD

**Issue by das-s** [Zettlr/Zettlr#1351]
## Description

Export with citeproc does not work on Pandoc >=2.11.

## Reproducing

Download Pandoc 2.11, convert a file with citations and receive error message about citeproc filter being removed.

## Expected behaviour

File is converted with citations.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: Zettler 1.7.5
 - Pandoc: 2.11

## Additional information

Pandoc removed the `pandoc-citeproc` filter in [2.11](https://github.com/jgm/pandoc/releases/tag/2.11) as mentioned in the changelog.

Digging into the code [this line](https://github.com/Zettlr/Zettlr/blob/161cf475fbfa52d307e7453e647d17084849cd8d/source/main/modules/export/run-pandoc.js#L53) probably needs an additional check for the current pandoc version to set the corresponding flags correctly.

**Comment by nathanlesage** [comment]
Thank you for reporting that they finally bundled it! Workaround until Zettlr supports Pandoc >= 2.11: Use Pandoc >= 2.0 and <= 2.10.

**Comment by nathanlesage** [comment]
Will be fixed in next release
