### ISSUE TITLE
Typo words got highlited but are not replaced from the context menu

### ISSUE THREAD

**Issue by tasiorq** [Zettlr/Zettlr#1354]
## Description
You are not able to replace the word with typo form the context menu
## Reproducing
1. Misspell a word 
2. R-click and select the correct word.
3. Original word is not being replaced. 

## Expected behaviour
Word is corrected.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
Already fixes, coming in next release
