### ISSUE TITLE
[FEATURE] Shortcut for column selection via keyboard

### ISSUE THREAD

**Issue by jzeneto** [Zettlr/Zettlr#1355]
## Description
In Sublime, Notepad++ and [Atom via a package](https://atom.io/packages/Sublime-Style-Column-Selection), it's possible to do [column selection](https://www.sublimetext.com/docs/3/column_selection.html): with some key + Up or Down, you place a cursor in above or below line in same column position as current cursor. As far as I searched for, Zettlr currently doesn't have this function --- although it's possible to do it using mouse, which is a slower, error prone process.

In Sublime, it's `Ctrl`-`Shift`-`Up/Down` (Mac) or `Ctrl`-`Alt`-`Up/Down` (Win/Linux) --- and Atom's package follows Mac keybindings as default (even on Win/Linux). I think in Notepad++ shortcut is `Alt`-`Shift`-`Up/Down`, but I don't use Windows anymore and so can't test that.

## Example Workflow
My use case is with poems. After typing entire poem (or pasting it from another file), I should put `| ` in the beginning of every line, to make effective line breaks. In editors cited above, this is a simple process: put cursor in the beginning of first (or last) line, hit shortcut repeatedly to select the first column of every poem's lines, and type `| `.

## Caveats
Using non-monospaced fonts in editor (as I do) would make columns not visually match when cursor is anything but in first column.

## Additional Information
In #443, Hendrik [wrote in a comment](https://github.com/Zettlr/Zettlr/issues/443#issuecomment-569295550) about sublime.js keymap for CodeMirror. Searching in that file, I found two functions, `addCursorToPrevLine` and `addCursorToNextLine`, which seem to implement that functionality. So, it would be simple to make it in Zettlr, I guess...

**Comment by nathanlesage** [comment]
Thank you for the initial research: the function names gave me the final clue what you want to do! While it would be easy to do so, I have actually lost sight over what shortcuts are already given, and which ones not -- we need to somehow collect these and get an overview again 😅

Implementation is easy then!
