### ISSUE TITLE
Pasting picture to the document doesn't work

### ISSUE THREAD

**Issue by tasiorq** [Zettlr/Zettlr#1356]
## Description
When you paste pictures from the clipboard into the document it's not being part of the document

## Reproducing
1. Copy picture to the clipboard
2. Go to Zettlr and paste it
3. Pasting pop up shows up but it's not being part of the document

## Expected behaviour
As in the previous version. The pasted picture is part of the document and it's shown. 

## Platform
 - OS and version: Windows 10 win32 10.0.18362 (architecture: x64)
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
Tested and works in the 2.0-dev branch, ships with the 2.0 release
