### ISSUE TITLE
Searching in current document

### ISSUE THREAD

**Issue by tasiorq** [Zettlr/Zettlr#1357]
## Description
Searching in the current document via Ctrl+F or magnifying glass doesn't work.

## Reproducing
1. While being in the document press Ctrl+F or click the magnifying glass
2. there is not pop up with the search options

## Expected behaviour
Search option is available

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
Works in the current develop branch — please comment on this issue, if `alpha.3` won't fix this issue!
