### ISSUE TITLE
Use top # heading as document title in case of no YAML front matter title

### ISSUE THREAD

**Issue by ungerik** [Zettlr/Zettlr#1358]
Writing front matter YAML just to give a document a title is tedious and that title is often repeated as the top # heading.

I suggest using the top # header (#, ##, ###) as logical document title if there is no other document text before it and if there is no YAML front matter title.

Maybe it would also be useful to offer a configuration option to define what is considered a logical document title.

**Comment by nathanlesage** [comment]
You are missing the version you are currently using, but it has been implemented in 1.7.5 and will come with more fixes in 1.8.0.

**Comment by ungerik** [comment]
1.7.5. Was too stupid to find the option because I was looking for something with "title" in the text and not thinking about "filenames".

Anyways thanks, you work is highly appreciated!

**Comment by nathanlesage** [comment]
Perfect, glad you found it! In case you think we should [update the documentation on the preferences](https://github.com/Zettlr/zettlr-docs/edit/master/docs/en/reference/settings.md), please feel free to simply propose a suggestion! I will gladly merge this.
