### ISSUE TITLE
HTML5 Math Export - Replace MathJax with KaTeX

### ISSUE THREAD

**Issue by stefnotch** [Zettlr/Zettlr#1359]
## Description
Currently, for the HTML5 export, MathJax is being used. However, MathJax and KaTeX have some slight, but irritating differences.

## Reproducing
```md
$$
3 \in \N
$$
```
ends up rendering as 
![image](https://user-images.githubusercontent.com/10220080/96444747-17522180-120f-11eb-9a81-fcde69ba0b78.png)

## Expected behaviour
![image](https://user-images.githubusercontent.com/10220080/96444736-115c4080-120f-11eb-98c0-415802f552c2.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
Do you have any suggestions on how to mitigate this?

**Comment by stefnotch** [comment]
The two approaches I can think of are
- Saving the KaTeX-rendered SVG in the HTML5 output
- Adding KaTeX (directly or as CDN) to the HTML5 output and using that to render the mathematics

**Comment by stefnotch** [comment]
After checking out Pandoc, it seems like the following command *should* work for KaTeX
```
pandoc -s --katex test.md -o test.html
```

However, math in `$$ $$` blocks simply gets dropped. It's possible that this is a pandoc bug.
