### ISSUE TITLE
Easier access to recent documents

### ISSUE THREAD

**Issue by klaus7** [Zettlr/Zettlr#136]
A (for me) highly useful feature in other editors, is the "recent documents" feature. Or a feature to switch between "open" documents. I understand that Zettlr has a different philosophy here with now "open documents". However you provide a "recent documents" feature, but it is only accessible through a lot of mouse clicking/movement :) 

Long story short: I'd love to have a shortcut for it. :)

**Comment by nathanlesage** [comment]
I was thinking of assigning Ctrl-1 to 10 or something like that. Plus, I'm currently thinking of integrating tabs for multiple open documents (concerning the implicit question on how to access open files better)

**Comment by nathanlesage** [comment]
Shortcuts `Cmd/Ctrl+0-9` will ship with the next version!
