### ISSUE TITLE
HTML5 Export - Random $$ signs

### ISSUE THREAD

**Issue by stefnotch** [Zettlr/Zettlr#1361]
## Description
In some rare cases, a mathematical equation is surrounded by $$ signs.

## Reproducing
```md
**Induction step**
$$
\begin{aligned}
P(n+1) &= 7^{n+1}-1 \\
&=7^1 \cdot 7^n-1 \\
&=7(7^n-1) + 6 \\

&=7(6x) + 6 \\
&=7 \cdot 6x + 6 \\
&=6 (7x+1) \\
& \Box \\
& 
\end{aligned}
$$
Also $3 \in \N$
```
(same screenshot and equation as in #1360)
![image](https://user-images.githubusercontent.com/10220080/96444988-7dd73f80-120f-11eb-86a7-b667a35d0e55.png)

## Expected behaviour
![image](https://user-images.githubusercontent.com/10220080/96444975-7879f500-120f-11eb-99d4-e77ac4fc7c00.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
I believe this may be because Pandoc detects the Math environment without the dollar signs, but I'm not sure. Please try to reproduce this behaviour, and find a reproducible way to do so, using Pandoc directly, without Zettlr in the middle, so that I know what I might need to change.

**Comment by stefnotch** [comment]
Simply copying the text into a .md file and then using a command like the following reproduces this bug
```
pandoc -s --mathjax test.md
```

It's quite possible that this is a pandoc bug! See my comment in https://github.com/Zettlr/Zettlr/issues/1359#issuecomment-712238294

**Comment by nathanlesage** [comment]
Thank you for investigating! I'll be asking the Pandoc team, whether they know something. Would you mind skimming the Pandoc manual in the meantime if you find some clues for this behaviour?

**Comment by stefnotch** [comment]
I tried searching around a bit, but couldn't really find anything about it. Maybe I just haven't searched hard enough.
