### ISSUE TITLE
HTML5 Export - Missing line break

### ISSUE THREAD

**Issue by stefnotch** [Zettlr/Zettlr#1362]
## Description
Sometimes, when doing an HTML5 export, a few line breaks go missing

## Reproducing
```md
**Induction step**
$P(n) = 6 | 7^n-1$
where $6|$ means ...
```
![image](https://user-images.githubusercontent.com/10220080/96445523-56cd3d80-1210-11eb-8154-c7f0fd8c7077.png)

## Expected behaviour
![image](https://user-images.githubusercontent.com/10220080/96445552-5e8ce200-1210-11eb-9c2d-eb6684edc717.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
Expected behaviour: Single line breaks are removed, double line breaks render a new paragraph. To retain single line breaks, end the lines using two spaces or a backslash (`\`). It is recommended to use double newlines, though.
