### ISSUE TITLE
HTML5 Export - Missing new lines

### ISSUE THREAD

**Issue by stefnotch** [Zettlr/Zettlr#1364]
## Description
When exporting to HTML5, extraneous new lines get collapsed. 

## Reproducing
```md
aaaa








bbbb
```

## Expected behaviour
I would expect Zettlr to keep the new lines.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2

## Additional information
For me, Zettlr has been a super useful tool for writing down mathematical equations, solving problems and explaining them to others! And, since Zettlr uses KaTeX instead of MathJax, the equations actually look great (as compared to how they look in Typora). 

This also means that I'm extensively using the math part of Zettlr and thus, find various bugs 😉

**Comment by nathanlesage** [comment]
> For me, Zettlr has been a super useful tool for writing down mathematical equations, solving problems and explaining them to others! And, since Zettlr uses KaTeX instead of MathJax, the equations actually look great (as compared to how they look in Typora).

Thank you for the compliment, greatly appreciated!

> This also means that I'm extensively using the math part of Zettlr and thus, find various bugs 😉

Don't worry; it's not a focus of Zettlr per se, but if there are things we can improve, all the better.

As for the empty lines: You can forcefully retain them by placing a single backslash (`\`) on each line (also expected behaviour by Pandoc)
