### ISSUE TITLE
[FEATURE] Fetch Youtube Video Title on Paste

### ISSUE THREAD

**Issue by whateverforever** [Zettlr/Zettlr#1365]
## Description

Videos disappear, and as such our links to them become invalid. To fix this, a proposal would be to fetch the author and title on pasting a youtube link. This will allow you to google for the video at a later point in time, or at least, still be able to tell from the title what it might've contained.

## Example Workflow

1. User pastes a youtube link
2. The link, together with title and author is pasted, analogous to how links between documents get expanded.

**Comment by nathanlesage** [comment]
I am not sure this is in scope of the application. It's not difficult to simply note down this information separately, as you need to have open the video either way, right?
