### ISSUE TITLE
[ENHANCEMENT] Opening a file using relative path

### ISSUE THREAD

**Issue by megomark** [Zettlr/Zettlr#1366]
Thanks for the awesome app! 

I would like a small improvement for opening file with a relative path
### Description
Now I can set a link to a file using following : 
````
[Video name or some text](//D:\zettlr_notes\path_to_note\video\2020-10-09_Video1.mp4)
````

But would be nice to have a possibility to open a file using relative path. For example:
````
[Video name or some text](//2020-10-09_Video1.mp4)
````
**or** 
if  \*.md file (which refers to video or another file) is in " D:\\zettlr_notes\\path_to_note\\ "
then

````
[Video name or some text](//video\2020-10-09_Video1.mp4)
````

Thanks again for the hard work in creating such a cool application. I've been looking for it for several years.

**Comment by nathanlesage** [comment]
`//` refers to a shared Windows resource, and I'm sure you don't mean that, right…?

**Comment by megomark** [comment]
Yes I have tested on Windows 10.  And if I put // before the file full path then I can open a file or video then I click to link. Only this method works to open a file with a default application that is installed on Windows. 

If this is not a cross-platform way, then it would be nice to find some way to open files from a relative link. And to open them with a default app of operating system.
