### ISSUE TITLE
[ENHANCEMENT] HTML5 Export - Looks different from the preview

### ISSUE THREAD

**Issue by stefnotch** [Zettlr/Zettlr#1367]
## Description
As I've noticed in the following issues, the HTML5 export and printing *intentionally* looks different from the preview. This also affects printing the document with `Ctrl`+`P`

https://github.com/Zettlr/Zettlr/issues/1362
https://github.com/Zettlr/Zettlr/issues/1360
https://github.com/Zettlr/Zettlr/issues/1363
https://github.com/Zettlr/Zettlr/issues/1364

The current behaviour does make sense, considering that the preview should be different from the final document. However, a number of things are, in my opinion, quite unexpected.

## Proposed Changes

I would propose adding a HTML5 mode that tries to keep the document as close to the preview as possible. This is also what Typora does and is significantly less unexpected. Especially things like line breaks easily go unnoticed until the last moment.

## Caveats

Regarding line breaks, it might also make sense for Zettlr to automatically save them in a way that actually reflects what the preview shows.

**Comment by nathanlesage** [comment]
Sorry for coming back at you so lately. The preview _intentionally_ looks different from the HTML output, and a full WYSIWYG-mode possibly won't ever come. Furthermore, double line-breaks are Markdown-compliant, and Typora is non-standard-conforming here.

**Comment by CaeeXar** [comment]
Yes, please fix.
Especially the line-break issues are irritating.
