### ISSUE TITLE
[FEATURE] Pomodoro export 

### ISSUE THREAD

**Issue by vitlib** [Zettlr/Zettlr#1368]
## Description

- Pomodoro stats
- Pomodoro data export

## Example Workflow

- I'd like to view how many pomodoro I completed
- I'd like to export number of pomodoros and time of beginning-ending of each cycle.

## Caveats

- I don't know the best position to put an "export pomodoro data" button, probably in settings.

## Additional Information

- My use case would be to track Pomodoro completed with Beeminder.

**Comment by nathanlesage** [comment]
The pomodoros are already tracked, but yes, there is no GUI element to display them. For exporting, you can look into your application data directory; the `stats.json` contains serialized JSON data, which can easily be dragged out of the file and used by external scripts. Does this fit your usecase?

**Comment by vitlib** [comment]
Thanks for the reply!
I checked the file and it has two issues for what I'm trying to do: it updates only when Zettlr gets closed (I think, I didn't check if it has a scheduled time to update) and it doesn't show the time of pomodoro cycles, only the total.
It could be used with a script that when launching Zettlr pulls the data from the json file though.
