### ISSUE TITLE
Hide folders with no markdown files

### ISSUE THREAD

**Issue by klaus7** [Zettlr/Zettlr#137]
In both the tree view and the "condensed" view, I'd love to hide the folders with no markdown files in them. This again, has to do with the big documents folder I'm working in. 

I really hope I don't annoy you with my many requests. Just keep in mind, it's just something I'd like to have and I think it would serve Zettlr as a whole - but I'm far from "demanding" anything. :)
Also I don't know how you handle contributions, but if you'd like I can also try to add it myself and make a pull request.

**Comment by nathanlesage** [comment]
This is a good idea! And it shouldn't prove difficult to implement. If you'd like to contribute, please feel free!

The best thing is to announce what you're doing, work on the develop-branch and open PR-requests targeting that. There's a PR template for some additional information! :)

**Comment by klaus7** [comment]
I've added this functionality. For now it simply hides all directories in the preview with no files in it. Some improvements I can think of: 

1. preview: don't hide directories, that have children with files?
2. tree view: also implement this feature there?

What do you think of the code? The posted improvements may prove a little bit more difficult to add though.

**Comment by nathanlesage** [comment]
Hey, thanks for developing the feature! It looks good so far, and much compliments for the quality! There's one excess semicolon, though (Zettlr follows JSStandard w/o semicolons, basically the default linter settings in Atom). But overall very good.

Yet, I've found some major mistakes in our reasoning so far, which we forgot:

1. It must be visible to the user that empty folders are currently hidden, and we need a small GUI indicator (maybe even clickable) so nobody misses folders
2. We have to deal with newly created folders, which would be hidden by default. This is maybe the biggest problem in implementation, it's going to be completely unusable if it's hiding folders by default.

Concerning the proposed improvements: We would need both, or maybe, depending on my point 2, a middle ground.

**Comment by nathanlesage** [comment]
I'll close the issue for now to keep the list clean, but once anyone comes up with any good idea, I'll be pleased to reopen it. I'd suggest using the Forum and/or Reddit to discuss it prior!
