### ISSUE TITLE
[Bug] Issues with images in new alpha

### ISSUE THREAD

**Issue by klieret** [Zettlr/Zettlr#1370]
## Description

* Bug 1: Pre-existing images do not show up right away, but only as gray placeholders (1). Only if you click at them, see the markdown source (2) and click somewhere else, they appear (3)
* Bug 2: Pasting images shows the usual image dialogue, but upon confirming, nothing happens

### Bug 1: Screenshots

1:

 ![image](https://user-images.githubusercontent.com/13602468/96560586-cb5eb580-12be-11eb-8383-512780fc5e41.png)

2: 

![image](https://user-images.githubusercontent.com/13602468/96560620-d1549680-12be-11eb-8248-cde88d35e5d9.png)

3: 

![image](https://user-images.githubusercontent.com/13602468/96560646-d7e30e00-12be-11eb-81a2-a076414a2318.png)

## Reproducing

See description

## Expected behaviour

See description

## Platform
 - OS and version: Ubuntu eoan 19.10
 - Zettlr Version: 1.8.0.alpha2 461c8a8e-0c78-435e-9f25-1315b0531cdc

**Comment by nathanlesage** [comment]
Please test this out with the next alpha which is building at the moment, and then report back if it still doesn't work!

**Comment by klieret** [comment]
Hi Nathan. 

## Issue 1

Seems to have been solved

## Issue 2

Remaining

## Issue 3

New: If I click on "Choose directory" in the image dialogue, the dialogue just disappears without anything happening (no directory chooser popup)

**Comment by klieret** [comment]
See also https://github.com/Zettlr/Zettlr/issues/1393 for OSX

**Comment by klieret** [comment]
The issue still persists with the beta.

**Comment by nathanlesage** [comment]
Fixed both issues 1 and 2, this was a regression from migrating the FSAL to TypeScript.
