### ISSUE TITLE
[ENHANCEMENT] Open files directly from folders

### ISSUE THREAD

**Issue by Zettelkaestner** [Zettlr/Zettlr#1371]
It would be great if markdown documents could be opened directly without Zettlr having to be open beforehand. In addition, even in this case, the problem arises that the file can no longer be closed without exiting the entire programm.

**Comment by nathanlesage** [comment]
This might work as expected in the current beta. Please [check it out](https://GitHub.com/Zettlr/Zettlr/releases), test it, and, if it works, close this issue, and, if it doesn't, leave a short comment that we can have a look.

**Comment by Zettelkaestner** [comment]
I tried it with 1.8.0-alpha.3 - unfortunately that didn't work.
