### ISSUE TITLE
[Bug] "File was modified remotely" dialog may come up many times in a row for the same file

### ISSUE THREAD

**Issue by uhbif19** [Zettlr/Zettlr#1375]
## Description

If opened file is modified by another app, then this dialog is showed. If the same happens to the file again, while dialog is not closed, it will be duplicated.

So you need to close dialog as many times, as the file was changed. This makes no sense, because you may apply only current version of file.

## Reproducing

0. Setting "Allways load remote changes ..." must be off
1. Open some file in Zettlr.
2. Change it >1 time by another app
3. You will see >1 modal dialog

## Expected behaviour

You must see only one modal dialog.

## Platform

Arch Linux x86, Zettlr 1.7.5

**Comment by uhbif19** [comment]
Sorry, I misclicked and posted blank issue. Will fill in a couple of minutes.

**Comment by uhbif19** [comment]
I can work on it, just waiting for confirmation, that UX bug is correct.

**Comment by bionicles** [comment]
this is still happening and drives me nuts! @uhbif19  how could we fix it?

**Comment by nathanlesage** [comment]
Sorry for the delay.
