### ISSUE TITLE
PDF export failing on linux

### ISSUE THREAD

**Issue by anthrolisp** [Zettlr/Zettlr#138]
I'm having several variants of the following error regardless of the font specified, whether it's the family name, font name file name, etc of an installed font. 

! Package fontspec Error: The font "Liberation Serif Regular" cannot be found.

I have pandoc and xetex packages installed. I'm running Archlinux. Is there a particular command that I can run to determine what exactly I should put in the font field inside PDF preferences?

Many thanks in advance!

**Comment by nathanlesage** [comment]
Yeah, LaTeX can be a real pain in the ass concerning fonts. I haven't been able to verify any pattern in the font selection process so far, but I'm wondering that Liberation Serif Regular isn't found, as it's one of those main fonts available on nearly every computer. I just tried it using quotes, but it still won't work.

Basically, you can input anything in the text field which could be placed inside `\setmainfont{font-name}` and `\setsansfont{font-name}`, Zettlr just replaces these variables. I tried to find something here, but to no avail: http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/fontspec/fontspec.pdf
