### ISSUE TITLE
[BUG] YAML Front Matter Blocks Corrupted

### ISSUE THREAD

**Issue by lutzenburg** [Zettlr/Zettlr#1380]
## Description

YAML Front matter blocks at the top of a file are poorly converted into tables and persisted to the file
system as tables.

![image](https://user-images.githubusercontent.com/11610578/97241626-61558b80-183d-11eb-88c1-1bc36bd6e697.png)

## Reproducing

1. Open an existing file with a YAML front matter block at the top
2. Click into the file

![zettlr-cooked](https://user-images.githubusercontent.com/11610578/97241510-15a2e200-183d-11eb-915e-1ddeb9e99848.gif)

## Expected behaviour

As with the previous version (1.7.5), Zettlr previously did not transform the front matter block. 

The expected behaviour is as follows: (recorded on 1.7.5). 

![expected-behaviour](https://user-images.githubusercontent.com/11610578/97242434-9c58be80-183f-11eb-84c0-fef3fd175bcb.gif)

## Platform

 - Ubuntu 20.04
 - Zettlr Version: 1.8.0-beta

**Comment by webopold** [comment]
Same here on Debian Testing 64-Bit

**Comment by nathanlesage** [comment]
Already fixed upstream, comes with the next beta.
