### ISSUE TITLE
YAML Frontmatter No long Used in Sidebar or in PDF Export

### ISSUE THREAD

**Issue by lightsquared** [Zettlr/Zettlr#1386]
## Description
The YAML front matter is no longer being used in the sidebar (file manager).  Also on export to PDF the YAML data is not used in the title page.

## Reproducing
On opening, the file manager displays the Zettlr ID rather than the YAML front matter title.  If you export an open file the YAML front matter is ignored.

## Expected behaviour
Expect it to continue to show the YAML front matter in the file manager and on export.

<img width="1988" alt="Screen Shot 2020-10-29 at 8 51 26 AM" src="https://user-images.githubusercontent.com/9501140/97590794-9dffbf00-19c4-11eb-8385-523b1f20d1e3.png">

[20201029082522.pdf](https://github.com/Zettlr/Zettlr/files/5459272/20201029082522.pdf)

## Platform
 - OS and version:  Version 11.0 beta
 - Zettlr Version: 1.8 beta

**Comment by lightsquared** [comment]
I've been able to remove the zettlr id if I edit the YAML front matter.  Just changing a single letter causes the file name in the file manager to change and the pdf output to properly show the metadata.

**Comment by lightsquared** [comment]
If I restart zettlr all of the zettlr id's come back in the file manager and I lose the YAML title again.  Changing anything in the frontmatter will cause the file manager to show the YAML title again.  I also noticed that files that I have manually inserted the zettlr ID do not have this issue.

**Comment by nathanlesage** [comment]
Thanks for reporting, I will have a look.

**Comment by nathanlesage** [comment]
Accidentally broke the caching mechanism with some `undefined` in the last iteration of the FSAL, sorry!
