### ISSUE TITLE
[ENHANCEMENT] Dock TOC in left (or right!) sidebar

### ISSUE THREAD

**Issue by dadatuputi** [Zettlr/Zettlr#1387]
## Description
I am just getting into Zettlr for a penetration testing workflow (OSCP) and it is great so far. 
I have built a template with an extensive TOC. I've been collapsing them and that's helped organize, but having the TOC dockable on the left or right would be immensely helpful for navigating within a document.

## Proposed Changes
Include a setting where the TOC can be docked in a sidebar. 

## Caveats
If placed on the right, it wouldn't interfere with the directory sidebar and could be coupled with attachments and references. If placed on the left it could be paged with the file tree and file list, or shown independently.

![image](https://user-images.githubusercontent.com/1217269/97619637-d4eec880-19f6-11eb-80a9-14d3710722a6.png)

**Comment by nathanlesage** [comment]
Guess what I implemented in the latest beta, which will for sure come with 1.8? A dockable TOC in the sidebar! 😎

During the weekend I will launch another, more stable beta, so if you can wait until then, you can switch to beta, if you like!
