### ISSUE TITLE
[Regression]: Footnote text can no longer be edited & saved using Ctrl+Enter

### ISSUE THREAD

**Issue by the-solipsist** [Zettlr/Zettlr#1388]
## Description

In the stable version, one can edit footnote text by pressing `Cmd` / `Ctrl` + `Return` / `Enter`, and then save the edit using `Shift` + `Return` / `Enter`.

In the latest beta, this is no longer possible.

## Reproducing

1. Press `Ctrl` + `Enter`, edit the footnote in the text box that pops up.
2. Press `Shift` + `Enter`.

You will find that the a carriage return happens (i.e., the same as a regular `Enter`, and thus the text isn't saved).  In fact,there is no way to save the text since `Esc` or clicking outside the text box don't result in the text getting saved.

## Expected behaviour

The text gets saved.

## Platform
 - OS and version:
 - Zettlr Version: 1.8.0 beta.

**Comment by the-solipsist** [comment]
Another issue: Footnote references are only clickable if they are numbers (e.g., `[^1]`).  If they are text (e.g., `[^footnote-1]`), then they are not clickable.  Should I file that as a separate bug?

**Comment by nathanlesage** [comment]
The latter thing: it has never been implemented; the first one: will check it!
