### ISSUE TITLE
JS error message and high CPU load 

### ISSUE THREAD

**Issue by wiesener** [Zettlr/Zettlr#1389]
## Description
The CPU load goes up to 184 % under mac osx and after the start the an error message occurs:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/12429559/97748789-5412f800-1aee-11eb-9319-477c2c645833.png">

## Reproducing
Version is 1.7.5 under mac OSX nothing special. I've updated node-js with brew and disabled therefore the old nodejs.

## Expected behaviour
- low CPU load and no error messages.

## Platform
 - OS and version:
macOS newest 10.15.7 (19H2)
 - Zettlr Version:
1.7.5

## Additional information
I've installed node js to check if I can fix the issue of the table editor. Therefore I've downloaded the source code and were running yarn.

**Comment by wiesener** [comment]
Okay deleting the setting under /Users/constantin/Library/Application Support/zettlr reset everything and brings back the old performance. I guess something in the settings skrewed up when I tried to run the development version.

**Comment by nathanlesage** [comment]
Yeah, there were a few problems somehow with regard to the switch from 1.7.5 -> 1.8.0, which is possibly caused by a lot of changes under the hood. I'm already considering to make this 2.0.x …
