### ISSUE TITLE
 Generate ID issue

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#139]
## Description
When trying to genereate an ID for a file using the menu nothing happens. Only using the shortcut `Ctr+L` is working. 

## Reproducing
'Menu > Edit > Generate new ID' no ID generated

## Platform
 - OS: Linux Ubuntu
 - Zettlr Version 1.2.3

**Comment by nathanlesage** [comment]
Alright, on my Mac it works. Would you mind opening the development console (Debug mode on, then restart the app, then click Develop -> Toggle Developer Tools) and see whether or not an error is produced in the console?

**Comment by nathanlesage** [comment]
Aaaaand fixed
