### ISSUE TITLE
thunderlink protocol not recognized: https prepended

### ISSUE THREAD

**Issue by bit-hug** [Zettlr/Zettlr#1391]
## Description

Thunderlink is a protocol for linking from anywhere directly to emails in the Thunderbird email client. It is very useful to be able to link from notes to emails, especially in zettelkasten. Zettlr cannot do this because it does not recognize that a link contains the thunderlink protocol, instead attempting to convert it into a url.

## Reproducing

* Create a new note.
* Enter a thunderlink such as the following.
```
[example of a thunderlink](thunderlink://messageid=Zettlr/Zettlr/issues/1334/706175616@github.com)
```
* Click to follow the link.
* Zettlr sends you to your default browser, which tries to open an address such as the following.
```
https://thunderlink//messageid=Zettlr/Zettlr/issues/1334/706175616@github.com
```

## Expected behaviour

Zettlr should recognize that the link already contains a protocol, and doesn't need a new one (`https`) prepending. Zettlr should then route the link to the operating system, which can decide how to interpret the protocol.

## Platform
 - OS and version: macOS 10.13.6

 - Zettlr Version: 1.7.5

**Comment by Kangie** [comment]
I note that `mailto:` links attempt to open the domain of the email address, rather than being passed to your installed mail client. Related?

**Comment by nathanlesage** [comment]
With regard to the `thunderlink` custom protocol: The reason was simple: The protocol was longer than 10 characters, and until now Zettlr only checked for custom protocols that were between one and ten characters. The limit is now 100 characters, which should suffice for everything.

@Kangie Can confirm, and have fixed it.
