### ISSUE TITLE
[BUG] Context menu can be spawned multiple times by right-clicking on the editor.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1395]
## Description

The context menu can be spawned multiple times within the editor.
## Reproducing

Open an editor and begin right-clicking. 
## Expected behaviour

Menu should be dismissed if another right-click action is received before a new menu is spawned.

![image](https://user-images.githubusercontent.com/9733178/97953992-5202af00-1df6-11eb-8666-c83d14dcd006.png)

## Platform
 - OS and version: Win10 20.04
 - Zettlr Version: 1.8.0-beta.

## Additional information

This occurs throughout the UI - The editor and navigation panel both display this behaviour.

**Comment by nathanlesage** [comment]
I don't know what you have – All Contexts Are Beautiful!

**Comment by nathanlesage** [comment]
Btw, I can't reproduce this – are you using the latest beta, or the first?

**Comment by Kangie** [comment]
It might be the first. I'll report back tomorrow.

If that's the case, the auto-updater hasn't notified me...

**Comment by nathanlesage** [comment]
I published the new beta release a few hours ago, so that might be the cause!

**Comment by Kangie** [comment]
So, I was on the first beta, not "beta.1". Can't reproduce in Beta.1, so I'll close this off. 

Of note though is that the new autoupdater notified me in a more subtle way, which addresses the other issue raised (that I can't be bothered to dig out). Is it supposed to fetch the release for you or perform any action other than notification?

**Comment by nathanlesage** [comment]
> Of note though is that the new autoupdater notified me in a more subtle way, which addresses the other issue raised (that I can't be bothered to dig out). Is it supposed to fetch the release for you or perform any action other than notification?

When you click download it actually fetches the file for you (it's stored in Downloads). After the download is complete, you can run the installer and restart the app, which makes it much easier to update. The only thing I haven't done so far is that the "Restart and install" button is also displayed when the popup was open. Currently you have to close the popup and reopen it ...

**Comment by Kangie** [comment]
I'll keep an eye out for the download button next update. :)
