### ISSUE TITLE
Support URL Scheme to add notes quickly?

### ISSUE THREAD

**Issue by sullevy** [Zettlr/Zettlr#140]
Thanks for this work, amazing.

I am using FSnotes and nvALT for quick get my fleeting ideas, they all support url scheme. 

If Zettlr could suport, maybe zettlr://make/new or other similar feature, I could integrate it into many workflow.

Thanks.

**Comment by nathanlesage** [comment]
This sounds like a cool thing, although it'll require some thinking at first. But I'll get to it at some point!

**Comment by nathanlesage** [comment]
Duplicate of #736
