### ISSUE TITLE
[ENHANCEMENT] Add support for opening YAML files

### ISSUE THREAD

**Issue by the-solipsist** [Zettlr/Zettlr#1400]
## Description

Currently Zettlr supports opening the following file extensions: `.txt`, `.md`, `.markdown`, `.rmd`, and `.tex`, as well as showing files with those extensions in the file manager bar on the left.  The proposal is to add `.yaml`.

While Zettlr ships with YAML syntax support, it cannot open `.yaml` files, nor does it show them in the file manager.  Given that Pandoc uses YAML for both metadata as well as for defaults files, it might be useful to be able to edit them in Zettlr.  Currently, I end up using gedit for those files, and Zettlr for the `.md` files.

## Proposed Changes

I believe it involves adding `".yaml"` to `"filetypes"` in `data.json`:
https://github.com/Zettlr/Zettlr/blob/93265b9662212220d0879ad244030ad2cab32a78/source/common/data.json#L2-L8

But it may involve other changes as well, I'm not familiar with the Zettlr codebase.

## Caveats

I don't think there are any.

**Comment by nathanlesage** [comment]
Hmhm, basically Zettlr could open any text file and display it using the appropriate syntax highlighter already. However, being a Markdown editor, right not Markdown- and LaTeX-files are the only ones being displayed. That being said, I fully understand the uses of adding YAML files.

However, as I have extremely limited time right now, do you mind having a look at possible workflows that involve pure YAML-files? This would make it easier for me to spot eventual caveats with certain types of implementations.

So the questions I have are:

- How can YAML-files be used within Markdown-based workflows? One per project? One for general (so, in a sense, like TeX-files?)
- Where will they likely occur?
- How should they be interleaved with the rest of the app (I'm trying to think ahead here because careful planning reduces the amount of refactoring I'll have to spend in a few years time when it becomes visible the original implementation was rubbish)
- Anything else that I should keep in mind?

**Comment by Kangie** [comment]
I'd welcome the ability to edit / view YAML within Zettlr. 

Using pandoc, I can see at least a few places where it might be useful:

1. Where you want to store the YAML metadata block as a separate file.
2. Where you have a CSL YAML database.

These may be the same file (as they can be consolidated into the metadata block at the beginning of a markdown file), however I'd expect that in practice you'd see them separately more often than not (as you'd be exporting the CSL YAML database from your reference manager as you add to it).

I can't see much use for it outside of that, but maybe others are using YAML as part of their workflow in ways that I'm not expecting (focusing on tools & integration).

**Comment by the-solipsist** [comment]
>   * How can YAML-files be used within Markdown-based workflows? One per project? One for general (so, in a sense, like TeX-files?)

There are many uses for YAML files. As Kangie notes:
1. Metadata files.
2. CSL YAML files.  (Currently Zettlr only supports `.bib` and `.json` files.)

I'd also add:
3. Defaults files.  These are central to my workflows, and I suspect this is increasingly so for many.

(I don't think it matters for Zettlr, but it should be noted that YAML metadata files can be be provided either as `markdown` format input to pandoc or separately referenced via `--metadata-file` or `metadata-files:` in a defaults file.)

>   * Where will they likely occur?

It's not easy to say.  Sometimes YAML files will be in the same directory / sub-directory.  But sometimes, they may be in other directories.  

I personally have all my bibliographies exported (with auto-updates) to `~/documents/references/` and then I link the appropriate `.json` file (using a hard link) to `~/documents/work/{projectname}/bilbiography/`.  I also have all the defaults files in `{projectname}/` and all the metadata files in `{projectname}/metadata/`.  My final pandoc invocation nowadays is almost always: `pandoc -d {projectname}/{output-name}.defaults.yaml`.  A single project can have multiple distinct outputs.  This scheme allows for a git repo to have all the files necessary to build all my output documents.  But that's just my (current) organizational scheme.

>   * How should they be interleaved with the rest of the app (I'm trying to think ahead here because careful planning reduces the amount of refactoring I'll have to spend in a few years time when it becomes visible the original implementation was rubbish)

Apart from being able to see (in the file manager) and open YAML files, it would also be great for Zettlr to be able to understand references to YAML files and then read the fields (such as "author" or "bibliography") specified in those files.

Currently, Zettlr supports a few (`title:` and `keywords:` come to mind).  I've a separate comment on [what YAML fields Zettlr should support](https://github.com/Zettlr/Zettlr/issues/459#issuecomment-721197761).

>   * Anything else that I should keep in mind?

I don't have much knowledge of uses for purposes other than pandoc, so you might want to consider other use cases.  But I feel the two biggest use categories for Zettlr are (1) note-keeping; (2) scholarly writing.  So I don't know about how bloggers using Zettlr would use Mustache YAML files, for instance.  Personally, I'd be happy enough with Zettlr being a great editor for the first two use cases.

One additional point, which is slightly besides the "being able to open YAML files" issue: One can reference metadata files in defaults files.  So, it is possible that there are two levels of looking for metadata fields, and not just one, i.e., in-file YAML -> defaults file -> metadata file.

**Comment by nathanlesage** [comment]
Works in 2.0
