### ISSUE TITLE
[ENHANCEMENT] Middle click to close a tab.

### ISSUE THREAD

**Issue by Bestulo** [Zettlr/Zettlr#1403]
Whenever I come to a file manager with tabs, I click the middle button to close the tab. That's like a rule that all editors have for some reason, and not having it on Zettlr is weird, and having to click the little X is something that I have to readjust to, and I don't think it's ideal.

Right now, middle click triggers a quick scrolly thing to move through tabs. That is also achievable by rolling the middle wheel, which on click would close the tab.

For file management, this is ideal because I don't want to have 100 tabs open. Maybe 3, maybe 4. If I open too many because I'm writing too intensely, or reading too intensely, I know what folder everything is in, and how to find it, and I don't need to have my whole library open. Therefore, I will often have a 10-second cleaning session where I will just middle click everything that I don't need right now and be done with it. This works for firefox, where I often have 5 windows with 3-8 tabs each, and I go on closing sprees, which are very much easier by middle clicking than searching the tiny little X at the right of the tab.

Middle click triggering a scrolly pointer on the tab section is not at all standard and is a feature that I would definitely never use, in contrast with middle clicking to close, which is something that I use multiple times per writing and browsing session.

**Comment by nathanlesage** [comment]
> Middle click triggering a scrolly pointer on the tab section is not at all standard

The problem is that until now I haven't found a way to disable this behaviour on windows. Fuethermore, there is already an issue by @Kangie open that addresses this.
