### ISSUE TITLE
On first open after close, the first Ctrl+Scroll reduces the size by 2 before applying the +1 or -1 zoom.

### ISSUE THREAD

**Issue by Bestulo** [Zettlr/Zettlr#1404]
My build:
- Windows 10
- Zettlr 1.8.0-beta.1

# Introduction

What I call First Open: When you close Zettlr process, then run it again.

On First Open, it goes to default size. Let's say that size is 14, and that each scroll forward (zoom out) and backward (zoom in) is +1 and -1.

# Description of the bug

On First Open, if you scroll forward (zoom out), it reduces the size by 3. Then, to go back to the size it had before, you need to scroll backward 3 times.

![gZVsEMMfPp](https://user-images.githubusercontent.com/23301025/98070024-b0e81880-1e36-11eb-870a-9a7e1773feec.gif)

On First Open, if you scroll backward (zoom in), it reduces the size by 1.

# The actual bug

What this means is that the first scroll on First Open triggers a -2 size, and then applies the +1 or -1 zoom (resulting in -3 on first zoom out, and -1 on first "zoom in" [which is actually zooming out by 1 due to the bug]).

# On normal behavior

I would also like to mention that this zoom out and zoom in direction, scroll back and forward, is the complete inverse as any normal app, such as Firefox, where zooming forward zooms IN (not out like on Zettlr), and zooming backwards zooms OUT.

I think it would be more normal to increase text size on scroll forward and reduce text size on scroll backward.

**Comment by nathanlesage** [comment]
Hey, sorry for responding so late, but good news: It's been fixed and comes with Zettlr 1.8.5!
