### ISSUE TITLE
It's not possible to close top bar menu dropdown by (a) clicking again; and (b) clicking top bar outside

### ISSUE THREAD

**Issue by Bestulo** [Zettlr/Zettlr#1405]
My build:

    Windows 10
    Zettlr 1.8.0-beta.1

When I click a top bar button such as Edit or File, I often want to close it without picking any option. Clicking the button again should do the job. If not, clicking outside of the button, on the top bar, where nothing ever happens and clicking is safe, should also do it. But it doesn't do it, and that's pretty strange.

![Screen recording of the bug](https://user-images.githubusercontent.com/23301025/98071798-e858c400-1e3a-11eb-9bd8-944750f87cd0.gif)

**Comment by Kangie** [comment]
Can replicate. Beta.1, Win10 20.04.

**Comment by nathanlesage** [comment]
The toggling works now, but I cannot reproduce the click-outside, so it may have something to do with how `-webkit-app-region: drag` is being handled on the different platforms. Would anyone of you please support me by verifying this suspicion, or seeing to how this is being handled? The corresponding `mousedown`-event listener is registered, either way.

**Comment by nathanlesage** [comment]
Already fixed
