### ISSUE TITLE
[ENHANCEMENT]: Support pandoc citeproc YAML as a citation database. 

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1407]
## Description

As pandoc now has citeproc built-in, we should support its default CSL database format: CSL YAML. This enables users to share the CSL YAML database between Pandoc and Zettlr (i.e. I won't need to export the database into JSON and YAML).
## Proposed Changes

Allow a CSL Yaml formatted CSL database to be used, in addition to the current CSL JSON and BibTex.
## Caveats

Nil.
## Additional Information

Hopefully this isn't too hard to implement, but it would be really nice to be able to use the same CSL database in both pandoc and Zettlr.

**Comment by the-solipsist** [comment]
Hi. While it might be useful to support CSL YAML, it is currently *much* slower than CSL JSON if the files are large, as the Haskell YAML (hsyaml) library that Pandoc uses [is much slower](https://github.com/jgm/pandoc/issues/6084) than its JSON processor.

So, unless you need to have easily readable bibliography files, or you need to additional formatting options that CSL YAML provides, it may be better to use CSL JSON.  (CSL JSON only allows the following formatting options: Italics, bold, super/subscript, smallcaps, and it doesn't allow math in the title.)  Both CSL JSON and CSL YAML can be used with the `references:` metadata block (which can be relegated to "backmatter" despite Zettlr currently only supporting "frontmatter") to create self-contained markdown files which don't need an external bibliography file.  So for instance, this is valid in a metadata block:
```
references: [ {"id":"academieroyaledessciencesCodeEthique2009","accessed":{"date-parts":[[2020,8,17]]},"issued":{"date-parts":[[2009]]},"language":"fr","publisher":"SPP Politique Scientifique","title":"Code d’éthique de la recherche scientifique en Belgique","type":"article","URL":"https://www.belspo.be/belspo/organisation/publ/pub_ostc/Eth_code/ethcode_fr.pdf"} ]
```

On the mailing list, jgm summarised it as:
> Bottom line: if you have math in your titles, go for BibLaTeX
> or pandoc YAML/Markdown. If you have a very large bibliography
> so that speed becomes an issue, CSL JSON will be by far the
> fastest to parse. Otherwise, personal preference.

**Comment by nathanlesage** [comment]
Well, Zettlr already ships with a YAML parser and a short conversion in the citeproc provider wouldn't hurt. As for the pandoc part, I don't know, but that's not my business either way

**Comment by Kangie** [comment]
I'm definitely not advocating for the removal of the CSL JSON parser. 

My document build pipeline uses YAML, and since it's all done using scripts it doesn't bother me if it takes a little bit longer to parse. It's just more convenient to only generate the bibliography once, and has the added benefit of being more human-readable. :)

**Comment by nathanlesage** [comment]
Aaand implemented. You go you! ;)
