### ISSUE TITLE
Ctrl shortcuts trigger autocomplete in search field

### ISSUE THREAD

**Issue by cdaven** [Zettlr/Zettlr#1408]
## Reproducing

1. Write something in the search field that triggers autocomplete.
2. Press Delete to clear the autocomplete suggestion.
3. Then press either one of these shortcuts:
    - Ctrl/Cmd+A (select all)
    - Ctrl/Cmd+C (copy)
    - Ctrl/Cmd+W (close window)
    - Super+A (open some sidebar in Windows 10)

You get the idea. Any standard key that triggers the keyup event, but has an OS-wide action connected to it, will trigger autocomplete inadvertently.

## Expected behaviour

When I use OS-wide actions such as "select all" and "copy", I don't expect the autocomplete to be triggered.

## Suggested fix

Abort the event handler if Ctrl/Cmd, Alt or Super/"Windows key" are pressed.

I'm not sure if this is compatible with pasting in the search field (Ctrl/Cmd+V).

## Platform
 - OS and version: Windows 10
 - Zettlr Version: develop

**Comment by nathanlesage** [comment]
Thanks for reporting!

**Comment by RedDocMD** [comment]
Hi, @cdaven, can you please give an example for what triggers auto-complete. I myself couldn't trigger auto-complete at all.

**Comment by cdaven** [comment]
> Hi, @cdaven, can you please give an example for what triggers auto-complete. I myself couldn't trigger auto-complete at all.

In my setup, typing the first digit(s) of a note's Zettelkasten ID triggers auto-complete.

**Comment by nathanlesage** [comment]
Fixed in one of the recent versions, forgot to mark this issue
