### ISSUE TITLE
[Enhancement] Add option to use markdown links as internal links instead of wiki links

### ISSUE THREAD

**Issue by vypxl** [Zettlr/Zettlr#1409]
## Description
As someone who uses Github as their backup, I like to use relative markdown links to reference other files because they work with such services out of the box, the existing internal wiki links do not.
I propose an option that allows for the automatic insertion of relative markdown links via the existing link autocomplete system.

## Example Workflow

- Upon typing [[ (or whatever link start you specified), the autocomplete activates
- After selecting a file, zettlr replaces the wiki link with a relative markdown link, e.g.:

```plain
[[foo -> [foo](foo.md)
with zkn-ids
[[bar ->[bar](20201104151319-bar.md) // of course regarding the "add filename when linking" option
```

## Caveats
I do not see any real caveats to this, as it does not modify any existing workflow but rather adds an alternative for users to choose.

**Comment by nathanlesage** [comment]
Relative links already work out of the box. What I could propose would be an autocomplete for loaded files when adding a normal markdown link, would that suffice?

**Comment by vypxl** [comment]
I think that this could be cumbersome if you wanted to just link a website or something, but zettlr proposes some files to you.
