### ISSUE TITLE
Feature request: paragraph spacing

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#141]
Could it be possible that paragraphs get an empty line between on pressing `Enter`?
Maybe having `Ctrl+Enter` for the next line? 

Taking into account Markdown format, if there is no empty line between them or two or more spaces at the end they are considered the same paragraph. 

You can try to export this into docx:

```
Paragraph1
Paragraph2

Paragraph3   
Paragraph4
```

**Comment by nathanlesage** [comment]
Do you mean to add two newlines on `Enter` and only one on `Ctrl+Enter`?

**Comment by samarulmeu** [comment]
Exactly.

**Comment by nathanlesage** [comment]
Phew … this might prove interesting to implement, as `Enter` already has a pesky command attached to it. But I'll see what I can do!

**Comment by samarulmeu** [comment]
Thank you again for the great support!

**Comment by nathanlesage** [comment]
You're welcome! Btw there are some new translations on translate.zettlr.com, you might want to check them out for translation :)

**Comment by samarulmeu** [comment]
I noticed some last evening, but it seems i have to check it more often... ;)

P. S. The last translation string means there are some goodies in the next release... I was waiting for it...

**Comment by nathanlesage** [comment]
Yes indeed! I'll implement an automatic mailing feature in a few days so that you can subscribe to email updates which I'll then send out once the translations have changed! This way you don't have to be on alert all the time ;)

**Comment by nathanlesage** [comment]
After due consideration, I decided not to implement this. Both because it tends to render invisible the mechanics of Markdown, and because it's not all too hard to hit `return` twice. Hope you don't mind! :)

**Comment by samarulmeu** [comment]
If it is too much trouble, you can forget about it and keep closed this issue, but the markdown specifications are different. 

Quoting from [markdown specifications](https://daringfireball.net/projects/markdown/syntax#p):

> **A paragraph** is simply one or more consecutive lines of text, **separated by one or more blank lines**. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with spaces or tabs.
>
> The implication of the “one or more consecutive lines of text” rule is that Markdown supports “hard-wrapped” text paragraphs. *This differs significantly from most other text-to-HTML formatters (including Movable Type’s “Convert Line Breaks” option) which translate every line break character in a paragraph into a `<br />` tag*.
>
> When you do want to insert a `<br />` break tag using Markdown, you **end a line with two or more spaces**, then type return. 

And as I mentioned in my previous message it is a problem when you export markdown.

**Comment by nathanlesage** [comment]
… how does this differ from what I've elaborated before?

It's simple: To begin a new paragraph, you need to hit Return twice, just as I stated. It's exactly as the Markdown specifications go!
