### ISSUE TITLE
[FEATURE] Manage files (not directories) as a nested list in the File Explorer

### ISSUE THREAD

**Issue by berzhot** [Zettlr/Zettlr#1418]
## Description

If you want to follow the Folgezettel ID system, you may find helpful the ability to manage files in the File Explorer as a nested list. This would allow you to expand or collapse sections in order to improve the way to view and work with the different branches

## Example Workflow

Expanded File list  example
![Nested list expanded](https://user-images.githubusercontent.com/8502544/98465682-e5f3c280-21ca-11eb-96d7-3c4ce038a5c7.png)

Collapsed File list example
![Nested list collapsed](https://user-images.githubusercontent.com/8502544/98465681-e55b2c00-21ca-11eb-8088-52a079b1015f.png)

## Additional Information

It is the same way we can actually manage directories but applied to files management

**Comment by nathanlesage** [comment]
I get what you want, but chances are almost infinitely small that I'll have the capacity to implement or maintain it.

**Comment by berzhot** [comment]
> I get what you want, but chances are almost infinitely small that I'll have the capacity to implement or maintain it.

I get it. Thanks for your quick response
