### ISSUE TITLE
Feature request: Export to HTML without metadata

### ISSUE THREAD

**Issue by TomasBouska** [Zettlr/Zettlr#142]
As a markdown + yaml user, I want to export to HTML without the metadata section the same way as the other exports (for example to docx) are doing.

Input:
```
---
title: test
date: 2019-04-10 19:35:38
tags: #test #zettlr

---
# Header
Some text
```
Actual output:

```
...
<article>
  <hr />
  <p>title: test<br />
  date: 2019-04-10 19:35:38<br />
  tags: #test #zettlr</p>
  <hr />
  <h1 id="header">Header</h1>
  <p>Some text</p>
</article>
...
```
Expected output:

```
...
<article>
  <h1 id="header">Header</h1>
  <p>Some text</p>
</article>
...
```

Thank you!

**Comment by nathanlesage** [comment]
Ahh, that's because HTML outputs are generated not by Pandoc but by Showdown.js (for users not able or not wanting to install Pandoc).

I'll see to use Pandoc if available and only use Showdown.js as a fallback!

**Comment by nathanlesage** [comment]
This should do it!
