### ISSUE TITLE
[1.8.0.beta2] pandoc-citeproc deprecated, replaced by new citeproc library

### ISSUE THREAD

**Issue by phense** [Zettlr/Zettlr#1420]
## Description
pandoc-citeproc was deprecated in favour of the new citeproc library. Zettlr's Advanced Option filter $citeproc$ does not know this yet, which will lead to an Export Error (if a Citation Database is linked) and/or show a deprecation-warning from pandoc.

## Reproducing
Link a Citation Database and just try to export to pdf, will result in error message.

## Quick-fix
As the deprecation-message shows, --filter $citeproc$ will not work properly and is deprecated. To make it work, in Zettlr, go to Settings --> Advanced --> and under "pandoc command"

**replace $citeproc$ with --citeproc (without the $)**

## Fix
* the variable $citeproc$ should be changed to the new value of '--citeproc'
* the Zettlr documentation contains the following quote under pandoc, which can now be removed: 
> You may need to set up pandoc-citeproc manually by installing it using the preferred method on your operating system.

**Comment by nathanlesage** [comment]
> the variable $citeproc$ should be changed to the new value of '--citeproc'
> the Zettlr documentation contains the following quote under pandoc, which can now be removed:

Not yet, as there are still many repositories featuring Pandoc 2.10 or less. So, no easy fix right now.

**Comment by phense** [comment]
True. 
I'd like to recommend to make a note in the official documentation: 
Under "Installing Pandoc", move this note: 

> You may need to set up pandoc-citeproc manually by installing it using the preferred method on your operating system.

up, from #Linux to #Installing-Pandoc, and add something like: 

> You may need to set up pandoc-citeproc manually by installing it using the preferred method on your operating system.
> Due to a change in pandoc's newest version (>=2.11.1.1), the extra installation of pandoc-citeproc is no longer necessary, but the pandoc command under Zettlr's Advanced Settings needs to be manually changed to: 
> **pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ --citeproc $standalone$ --pdf-engine=xelatex --mathjax -o "$outfile$"**
> in order to reflect this current change.

**Comment by nathanlesage** [comment]
@phense Please open a PR, including this change. Then I can simply merge it and we are done as long as Zettlr doesn't bundle Pandoc :)
