### ISSUE TITLE
Drag and Drop arbitrary files from any directory to create a link

### ISSUE THREAD

**Issue by oashour** [Zettlr/Zettlr#1422]
I am quite new to Zettlr so pardon me if I'm posting this in the wrong spot or if this feature already exists, but I haven't been able to find it.

I would like to drag and drop files with arbitrary extensions (e.g. *.in, *.cif, *.xsf, or whatever else) from any folder into Zettlr. On MacOS, if I drag such a file from finder to the editor, I get the error "could not open file". If I move the file to the same folder as the .md note and drag it from the attachment pane then it actually works.

Unfortunately, I can't move the files manually to the folder with my .md link since they have really convoluted file trees and I don't want to get my notes into this mess. I could write the links by hand but that seems like quite a pain. Am I missing something?

Cheers and thanks for the app.

**Comment by nathanlesage** [comment]
You're in luck: I just fixed that in one of the latest betas (at least it's fixed in the codebase, and I'm pretty sure the latest beta release already does this as expected! If it doesn't please comment that I have another look!)
