### ISSUE TITLE
Folding Behaviour

### ISSUE THREAD

**Issue by ludos1978** [Zettlr/Zettlr#1425]
## Description
When pressing left of any text with the mouse, the whole section is collapsed. When trying to move the cursor to the beginning of the text or selecting multiple lines with the mouse, most of the time the text is collapsed. I believe some other bug reports might be issues caused by this behaviour.

## Reproducing
Write text with header and content, try to select text.

## Expected behaviour
Quotes are used to clarify the described areas.
My suggestion would be to have the text only folded if you press "left to the header", not "left to the whole paragraph". This would also be consistent with most other tools that fold text (at least that i know of) such as visual studio code. If it's intentional behaviour that it folds "left of the whole paragraph", then i would recommend to have at least some more space "left to the text" which would not fold the paragraph.

<img width="296" alt="Bildschirmfoto 2020-11-16 um 01 54 23" src="https://user-images.githubusercontent.com/4594166/99202334-074a4500-27af-11eb-8560-63211001b14b.png">

## Platform
 - OS and version: OSX 10.15.6
 - Zettlr Version: 1.7.5

**Comment by nathanlesage** [comment]
Fixed in upstream, and afaik it's already shipped with the current 1.8 beta.
