### ISSUE TITLE
Citation rendering fails when followed by a period

### ISSUE THREAD

**Issue by eladzlot** [Zettlr/Zettlr#1427]
## Description
When a citation is followed by a punctuation mark (i.e. @abramowitzExposureTherapyAnxiety2019.), it is rendered as plain text instead of transformed into the actual citation: (Abramowitz et al. 2004).

## Reproducing
Write a citation followed immediately by a period.
For example: @abramowitzExposureTherapyAnxiety2019.

If instead of writing them consequently, I first write them with a separating space and then delete it, rendering is correct.
In any case, pandoc exports the citations correctly.

## Expected behaviour
parse the citation and ignore the period

![image](https://user-images.githubusercontent.com/1874199/99240089-ac433d00-2804-11eb-8bf0-1f02bf8f665e.png)

## Platform
 - Windows 10:
 - Zettlr Version: 1.7

**Comment by nathanlesage** [comment]
Perfectly to be expected, as periods are a valid part of a citation. Please consider wrapping all of your citekeys within square brackets, as these are definite markers of beginning and ending of a citation (e.g.: `[@citekey].`)

**Comment by eladzlot** [comment]
Thanks for the solution (and for Zettlr too. it's fantastic).
