### ISSUE TITLE
[ENHANCEMENT] Allow user to disable mouse zoom

### ISSUE THREAD

**Issue by cianoc** [Zettlr/Zettlr#1430]
## Description
Add an option in preferences that allows the user to disable mouse zoom (CMD/CTRL - mouse scroll).

## Justification
When using the Apple magic mouse in Zettlr it is almost impossible to click on a link without also zooming in/out - as the slightest lateral movement on the mouse will trigger 'scrolling'. Allowing the user to optionally disable this would remove a source of considerable frustration.

**Comment by baubaid** [comment]
Adding my "vote" for this enhancement. I've already done this accidentally more times than I care to count.

**Comment by tap349** [comment]
Even when using trackpad I get accidental zooming in and out when scrolling. It's very distracting.

**Comment by nathanlesage** [comment]
Took a long time but finally here we go!
