### ISSUE TITLE
[ENHANCEMENT] Checkboxes to enable/disable specific autocorrect substitutions

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#1431]
## Description
Control of autocorrect substitution settings is very coarse-grained at the moment. There is a single enable/disable switch and the option to add or delete individual substitutions. While this is just about workable, it has a major flaw in that once a substitution is removed it is almost impossible to add it back again. Most users (me included) would have no idea where to find or how to type the particular symbols or ligatures on the right-hand side of the substitutions. That's why we have easy-to-type replacement patterns after all! I tried deleting some when I first installed Zettlr, but now I am too afraid to do so again, in case I can not get them back.

## Proposed Changes
Please support an individual enable/disable checkbox for each substitution, and only replace the character sequence in the text if the checkbox is enabled. For extra credit, consider greying out any disabled substitutions in the settings panel.

## Caveats
- This potentially makes text processing slightly more complicated
- If a substitution is re-enabled and then an old note is edited, the new substitution rules will apply, which may surprise. Of course, this would also happen if a new substitution was added manually.

## Additional Information
There seems to be room in the settings dialogue for this, so it should not need any UI layout changes.

**Comment by nathanlesage** [comment]
Is there any precedent of any other software doing this? It seems very odd to me, especially given the fact that you can immediately un-do any substitution.

[From the docs](https://docs.zettlr.com/en/core/autocorrect/):

> AutoCorrect comes in two flavors: You can either choose the "Word" mode, or the "LibreOffice" mode – depending on whether you are more accustomed to Microsoft Word or LibreOffice. The two modes differ in how they are triggered. The Word mode is generally more aggressive and will immediately attempt to replace every sequence of characters it encounters. The LibreOffice mode requires you to press either Space or Enter before it attempts to replace something. You can always undo a replacement by pressing the Backspace key.
