### ISSUE TITLE
[1.8.0.beta3] When creating a Zettelkasten Link the ID is shown two times

### ISSUE THREAD

**Issue by mattwien** [Zettlr/Zettlr#1432]
## Description
When I create a [[ link with the Zettelkasten feature enabled, the ID is shown in the wiki link as well as behind the link.

## Reproducing
Type [[, select one entry, enter

## Expected behaviour
As before. Just the ID within brackets and the rest of the filename behind the brackets

## Platform
Windows 10
1.8.0.beta3

## Additional information
![image](https://user-images.githubusercontent.com/70956195/99442100-206f0500-2919-11eb-803e-f05c80afc587.png)

**Comment by nathanlesage** [comment]
Funny behaviour. I'll see to it; if you spot any error messages in the logs/console, paste them here!

**Comment by nathanlesage** [comment]
Oh boy, there was a lot else wrong with that functionality …

**Comment by mattwien** [comment]
@nathanlesage : just wonder, you closed the issue, but the behavior is still the same in 1.8.0 beta4. Did you change it after the update?

**Comment by nathanlesage** [comment]
If I see it correctly, it's in the beta. But I've tested precisely your use-case and couldn't reproduce it after the fix, hence I closed this issue.
