### ISSUE TITLE
[1.8.0.beta3] Autocomplete list for tags does not work properly

### ISSUE THREAD

**Issue by tobenschmidt** [Zettlr/Zettlr#1433]
## Description

After entering the hashtag character the autocomplete list opens with all available tags. The autocomplete list stays the same when typing more characters. Selecting a hastag with a mouse click does not work.

## Reproducing

Selecting a tag with mouse click:

1. Enter hashtag character
2. Select any tag from autocomplete list with a mouse click
3. Nothing happens

Update of autocomplete list:

1. Enter hashtag character
2. Autocomplete list opens
3. Type more characters
4. Autocomplete list stays in initial state

## Expected behaviour

Selecting a tag from autocomplete with a mouse click should work just as selecting a tag with the keyboard.
Autocomplete list should update with every typed character and only show tags matching typed characters.

## Platform
 - OS and version: Linux Mint 20 5.4.0-54-generic x86_64
 - Zettlr Version: 1.8.0-beta.3

## Additional information

Error message when selecting tag from autocomplete list with mouse:
<pre>
 codemirror.js:4627 Uncaught TypeError: Cannot read property 'length' of undefined
    at Ai (codemirror.js:4627)
    at Si (codemirror.js:4634)
    at Li (codemirror.js:4645)
    at uo (codemirror.js:5278)
    at co (codemirror.js:5272)
    at mo (codemirror.js:5486)
    at Eo.replaceRange (codemirror.js:6125)
    at Sa.replaceRange (codemirror.js:9752)
    at show-hint.js:93
    at Jr (codemirror.js:3918)
﻿</pre>
​
Error message when typing after hashtag character:

<pre>
Uncaught TypeError: t.text.toLowerCase is not a function
    at autocomplete.js:231
    at Array.filter (<anonymous>)
    at s (autocomplete.js:222)
    at c (autocomplete.js:265)
    at c (show-hint.js:409)
    at r.update (show-hint.js:127)
    at show-hint.js:119
</pre>

**Comment by nathanlesage** [comment]
Thank you for the error codes, will fix this asap!

**Comment by nathanlesage** [comment]
There seems to be something else off, I just attempted to reproduce but it works just fine here (also beta3, macOS Big Sur).

Are there any other errors logged? This might be a problem with the tags itself …?

**Comment by tobenschmidt** [comment]
The problem most certainly only occurs if there's a tag that consists of numbers only in the YAML Frontmatter of at least one file. A tag name like _1997_ breaks the autocomplete feature. Something like _y1997_ oder _1997y_ is fine. Regular tags with the hashtag character cause no problems.

(I already noticed this behaviour in version 1.8.0-beta.2 and mentioned it in https://github.com/Zettlr/Zettlr/issues/1419#issuecomment-724328800)

**Comment by nathanlesage** [comment]
@tobenschmidt Thanks for pinpointing the issue, I'll have a look

**Comment by nathanlesage** [comment]
Found the issue: If you only use numbers as the keywords, the YAML parser cast them to type number, where neither `toLowerCase` nor `length` works. Thanks for reporting!

**Comment by tobenschmidt** [comment]
Thanks for fixing!
