### ISSUE TITLE
[1.8beta3]  Longer attachments names  in the sidebar not fully adjusted/readable

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#1434]
## Description

In the sidebar, in the example  file shipped with Zettlr, longer text is unreadable, it cut part of the filename.
There is too much space at the beginning of every line with  filename.
The vertical space between "Attachements" and "Pandoc and ... " is much bigger than in the space in the tab "References"

<img width="227" alt="image" src="https://user-images.githubusercontent.com/7980381/99530481-a3d43900-29a1-11eb-9e95-12a88e91a56e.png">

Also the attachments tab seems be the same for all files, I don't have many other notes with attachements  to check  it.
## Platform
 - OS and version: Big Sur 11.0.1
 - Zettlr Version: 1.8.3 Beta

**Comment by nathanlesage** [comment]
Feel free to play around with the CSS and provide a PR for this – it's pretty easy and this way we could share some work :)

**Comment by danieltomasz** [comment]
I could try to do that, but probably not this week and not  before you plan to release 1.8

**Comment by nathanlesage** [comment]
Then so be it. 1.8 won't be the last release, and we can push more changes at any time :)
