### ISSUE TITLE
Nested List

### ISSUE THREAD

**Issue by TicTak21** [Zettlr/Zettlr#1438]
## Description

I would like to be able to use nested lists. The problem is that now lists cannot be formatted like that.

## Example Workflow

For example:
```
1. List item
  1.1 List item
  ...
2. List item
```

Now I use this syntax:
```
1. List item
<- Two spaces or one tab here ->  1.1 List item
  ...
2. List item
```

I think it would be great if I can mark levels of list:
```
_1. List item
__1.1 List item
_2. List item
```

First screenshot: in Zettlr
<img width="220" alt="Screenshot 2020-11-20 at 21 01 21" src="https://user-images.githubusercontent.com/44474697/99839541-8bb41380-2b73-11eb-8049-c6013c09c4a3.png">

Second screenshot: converted to HTML or PDF
<img width="309" alt="Screenshot 2020-11-20 at 21 01 45" src="https://user-images.githubusercontent.com/44474697/99839587-a4bcc480-2b73-11eb-8972-598d9ebe8f8e.png">

**Comment by nathanlesage** [comment]
This is intended Markdown design, see the specs: https://spec.commonmark.org/0.29/#lists
