### ISSUE TITLE
[Feature]: Customise Pandoc command

### ISSUE THREAD

**Issue by anthrolisp** [Zettlr/Zettlr#144]
Is there any way to have toc automatically generated on export through the GUI?

Many thanks in advance!

**Comment by nathanlesage** [comment]
If you mean …

- an auto-generated TOC on single-file PDF export: Ideally use a custom template (you can simply copy the default template and replace the TOC-variable with the LaTeX-TOC command)
- an auto-generated TOC on project PDF export: check the corresponding option

Do you need it in other instances? If so, rest assured: I'll implement an override option for the pandoc command to be executed shortly so you can pass the `--toc`-flag to pandoc automatically on every export!

**Comment by anthrolisp** [comment]
The latter would be awesome for easy of use! Thanks for getting back!

**Comment by nathanlesage** [comment]
Alright, noted! :)
