### ISSUE TITLE
[ENHANCEMENT] Add comand "Close other" to popup menu belonging to tabs area

### ISSUE THREAD

**Issue by swl181** [Zettlr/Zettlr#1440]
## Description

Add comand "Close other" to popup menu belonging to tabs area

## Proposed Changes

Add comand "Close other" to popup menu belonging to tabs area
When executing this command system must close all tab except one current open tab

**Comment by Kangie** [comment]
Should be pretty easy to implement now that we have a tab list... there was a bug in the `Close all tabs` behaviour that pretty much replicated this request at some point. I do believe that this is a dupe, though I can't find the issue that was open for it!

**Comment by nathanlesage** [comment]
> I do believe that this is a dupe, though I can't find the issue that was open for it!

Heh, I also remember there was something like this. If you find it, feel free to flag it, the thing itself is already on my ToDo list and will come soon.

**Comment by nathanlesage** [comment]
Implemented that a few days ago.
