### ISSUE TITLE
Lines beginning with "[0-9]." are always treated as lists and are automatically continued on Enter

### ISSUE THREAD

**Issue by Pascalio** [Zettlr/Zettlr#1441]
## Description

Zettlr sometimes senses a numbered list where there is none. On newline, it then copies and increments the number whereas it is not desired.
## Reproducing

- Write a number followed by a point _and_ something else, at the beginning of a line, as in a date like "21.11.20", or a unit and chapter like "7.3"
- Press enter
- "22." or "8." respectively is auto-added.

## Expected behaviour

It should be recognized that 21.11.20 and 7.3 are no numbered list items.

## Platform
 - OS and version: Linux Ubuntu 20.04
 - Zettlr Version: 1.7.5

**Comment by nathanlesage** [comment]
It's the attempt of [this file](https://github.com/Zettlr/Zettlr/blob/develop/source/renderer/modules/markdown-editor/plugins/continuelist.js) to mimick the official Microsoft Excel™ experience.

**Comment by Pascalio** [comment]
Oh... I'm not aware of the above cited experience, I'm sorry. 
However, it probably doesn't make sense to treat 21.11.20 as a list, right? Maybe the fix would be as simple as saying that a whitespace must follow the "." in order to treat the 21. as a list ?

**Comment by nathanlesage** [comment]
> Oh... I'm not aware of the above cited experience, I'm sorry.

That was sarcasm ;) It's a bug (just as Excel is)

**Comment by nathanlesage** [comment]
Wohow, took me just a year to add a single character 👀
