### ISSUE TITLE
[1.8.0beta4] Zettlr can't find pandoc or xelatex even with custom paths

### ISSUE THREAD

**Issue by AlienTux** [Zettlr/Zettlr#1442]
## Description

Zettlr doesn't find pandoc or xelatex despite both of them are in my path (I can test it on the terminal from any folder). Doesn't work even with custom paths to executables. Works as intenden in version 1.7.5.

Just as a note: HTML export works as intended.

## Reproducing

Fresh AppImage download (x64 version). Remove .config folder and test. Error is the same. 

## Platform
 - OS and version: Solus 4.1 Gnome
 - Zettlr Version: 1.8.0 beta 4

## Additional information

Version 1.7.5 also doesn't find pandoc and xelatex even tho they're on my path, but at least the custom commands work. Pandoc and xelatex have been installed in custom folders. The structure is as follows:

```
/home/kurt/bin/pandoc-current/bin/pandoc

/home/kurt/bin/texlive-current/bin/x86_64-linux/xelatex
```

**Comment by nathanlesage** [comment]
Works as intended again in 1.8.6!
