### ISSUE TITLE
Renaming a file does not appear to update the ID

### ISSUE THREAD

**Issue by vijoc** [Zettlr/Zettlr#1444]
## Description

After moving the ID of a file from the contents to the file name, following a link to that ID does not find the existing file. Instead, a new file is created, if the setting to do so is on.

## Reproducing

Create a file with no ID in the title, but one in the contents (e.g. in the header). Following links to that ID will work fine. Now remove the ID from the contents of that file, *save the file*, and add it to the file name (renaming the file). Following links to that ID will not find the existing file until Zettlr is restarted, *or* the file is saved again, triggering an update.

## Expected behaviour

Renaming the file should potentially affect the (cached?) ID of a file.

## Platform
Zettlr Version: 1.8.0-beta.4
System: win32 10.0.18363 (architecture: x64)

## Additional information

I tried tracing the source of the problem, but had some trouble wrapping my head around the FSAL. As far as I can tell, the problem occurs due to the `findObject` traversing a `filetree` with cached IDs not reflecting the latest version after file rename. As for where/how the ID update generally happens, I couldn't tell from my brief exploration.

https://github.com/Zettlr/Zettlr/blob/b4ee57e764fe88e54d6900448a2cb74b2bd3ac44/source/main/modules/fsal/index.ts#L724

Further, if the file is edited and saved after the renaming, it is found via the ID in search again. This suggests that the file change does some updates that file renaming does not do.

**Comment by nathanlesage** [comment]
> Renaming the file should potentially affect the (cached?) ID of a file.

Yes, indeed renaming does not yet alter the cache, thank you for reporting.
