### ISSUE TITLE
Markdown doesn't render well in read mode

### ISSUE THREAD

**Issue by sadakmed** [Zettlr/Zettlr#1445]
I just start using zettlr! When I write something it doesn't render into it's right markdown format, it just color the text, and keep all the syntax as it is.

Edit: Linux ubuntu 18.04, I used the .deb file to install it

**Comment by sadakmed** [comment]
cant deal with it it just how they coded it, too much colors; and so much ugly.

**Comment by nathanlesage** [comment]
> When I write something it doesn't render into it's right markdown format, it just color the text, and keep all the syntax as it is.

Unfortunately, I don't quite know what you mean by any of this. What do you mean by "render into it's right markdown format" and "it just color the text"?

> cant deal with it, it just how they coded it, too much colors; and so much ugly.

Would you mind sharing a screenshot to visualise what you are referring to here?

**Comment by sadakmed** [comment]
@nathanlesage  after playing with it for a while i think i understood how it works, at first I considered that toggle readability mode as preview(like obsidian), and it highlight all text to green and yellow, and still show the astrix **, #, >  so i was confused (should it disappear in a preview mode). 
![this one](https://user-images.githubusercontent.com/18331629/100156632-89222880-2ea9-11eb-8cc2-d3e04f7d4dfe.png)

**Comment by Kangie** [comment]
Yeah, this function is **not** for displaying a preview of your output. You should use the quick export functions for that!

What this function actually does is have your content graded for readability by your choice (from the selection in options) of algorithm, and colouring lines as a result of the output.

**Comment by nathanlesage** [comment]
What Kangie said! Considering this closed :)
