### ISSUE TITLE
Front-matter variables are ignored

### ISSUE THREAD

**Issue by GrazingScientist** [Zettlr/Zettlr#1446]
## Description
Some of the given front-matter variables are ignored both in project and on single file export. Explicitely the ones I found are `figureTitle` (changing the default "Figure" in the image caption to the given value) and `notes-after-punctuation`.

## Reproducing

```
---
figureTitle: Abbildung
notes-after-punctuation: true
---

# Introduction
Here I give a citation [@Wang:2013df]. And here one with pages [-@Sir:2013hu, p. 123].
```

results in:

```
INTRODUCTION
Here I give a citation (Wang et al., 2013). And here one with pages (2013, p. 123).
```

## Expected behaviour
At least for `notes-after-punctuation`, I would expect it to behave as [documented](https://docs.zettlr.com/en/core/yaml-frontmatter/#variable-notes-after-punctuation).

For `figureTitle`, it would be nice, if it was implemented, if not done so yet. :)

## Platform
Zettler 1.7.5 on MacOS 10.15.7.

**Comment by the-solipsist** [comment]
Hi @GrazingScientist. 

1. `figureTitle` is not a variable recognized by Pandoc, nor is it mentioned in the Zettlr documents.  If you're trying to convert to LaTeX and are using Zettlr for the export, then Zettlr' LaTeX template needs to provide for `figuretitle`, and then it will work.

2. `notes-after-punctuation`, as mentioned in the documentation, affects _footnote_ reference placement.  It does not affect in-line citations.  If you use a CSL style that implements footnotes (as the `chicago-note-bibliography` style does), then the footnote will be placed appropriately.

**Comment by GrazingScientist** [comment]
> figureTitle is not a variable recognized by Pandoc, nor is it mentioned in the Zettlr documents. If you're trying to convert to PDF (via LaTeX) and are using Zettlr for the export, then Zettlr's LaTeX template needs to provide for figuretitle, and then it will work. You can manually modify the template to achieve what you want.

You are right! I was so stuck that this should work (because I found it somewhere) that I blamed Zettlr. Sorry!

> notes-after-punctuation, as mentioned in the documentation, affects footnote reference placement. It does not affect in-line citations. If you use a CSL style that implements footnotes (as the chicago-note-bibliography style does), then the footnote will be placed appropriately.

Ah! That's the magic! ^^

**Comment by nathanlesage** [comment]
In general, there will be improvements to the PDF exporting and importing some time in 2021, so then we can tackle a lot of those interrelating issues against which I currently can't do much because it depends on so many variables I cannot control!
