### ISSUE TITLE
[DEVELOP] Static Font Assets not Loaded Correctly

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1447]
Note that this won't make it into the initial 1.8. **Mitigation** until it's fixed: Make sure to install the fonts Lato, Inconsolata, Crimson, and Liberation Mono on your system _or_ use the Custom CSS to override the font declarations globally.

***

Yo, I've been on to this issue for quite some time, but webpack and I are not getting to common ground with this issue.

The issue is that the fonts are shipped with the app, but not addressed correctly by the compiled LESS files. Here's the issue:

- The fonts are correctly located in the corresponding source LESS file (`../fonts/` in the file `fonts.less`).
- The fonts are correctly copied to the resulting folder (`.webpack/renderer` and there into a `common` directory as obviously all renderers share the font files)
- The correct file path would be: `..` (move out of the dedicated renderer folder) and then `common/fonts`.
- The file path that's resolved in the index.js, however, is: `./source/common/fonts`

So we somehow need to get webpack to replace `./source` with `..`. The (apparently?) correct option `publicPath` is already set in the file `./webpack.rules.js`, but somehow the file paths are messed up. With other assets it works, even though they have the same ruleset. I don't get it.

Here's a screenshot to illustrate:

![image](https://user-images.githubusercontent.com/17251683/100324006-e233ae80-2fc6-11eb-8b21-e021f2861887.png)

## Impact of this Behaviour:

Every computer that does not have the correct fonts installed will show the system defaults. This is currently extremely problematic in the Windows builds, as the default monospace fonts (used by the Berlin and Bordeaux themes) are so ugly I cannot put it into words.

***

Pinging @tobiasdiez @Kangie @canpolat

**Comment by tobiasdiez** [comment]
Mhh, on first glance it appears to me that `renderer/common/fonts` is actually the correct path, isn't it?
Are the images found? According to your screenshot `image-preview.png` at the bottom is placed in `source/common/img`, and everything is working there?

**Comment by Kangie** [comment]
Not much experience with webpack, but it looks like you're telling it to go to `source`:

https://github.com/Zettlr/Zettlr/blob/6d3e817b7a01186bf5d2e03d7ac1d65b179a3fc3/webpack.rules.js#L61

**Comment by nathanlesage** [comment]
> According to your screenshot image-preview.png at the bottom is placed in source/common/img, and everything is working there?

Yes, and this is what I don't quite get – the configs for both images and fonts are exactly the same, however, images are being found, while the fonts are at a completely different location, and I still don't quite get what is causing this …

**Comment by nathanlesage** [comment]
Oh, and btw, if someone finds a solution, here's my wish-for reality:

All assets that are not code or text are not even loaded into the app.asar, but can be placed in the resources-directory. This is because I plan to bundle Pandoc with the app in a few months, and hence I'd ideally put anything not strictly runtime code in the resources path. If that doesn't work (b/c, e.g., the paths differ on multiple platforms that's completely fine! In that case it'd still be great if we could place all resources in a sibling directory to main and renderer, as sometimes both main and renderer(s) require them (such as the icons) – this would result in even less wasted space :) 

Thanks y'all for helping out here in the meantime ❤️

**Comment by Kangie** [comment]
Going to be honest, going for the preferred solution seems easier than working out why it's not behaving after having put a few solid hours into it. I've made a start, will see where I get / if I get too busy to continue. It doesn't look too complex though.

**Comment by nathanlesage** [comment]
> Going to be honest, aiming for the preferred solution seems easier than working out why it's not behaving after having put a few solid hours into it. I've made a start, will see where I get / if I get too busy to continue. It doesn't look too complex though.

Thank you for your dedication! I'll stay tuned to more info on that — if the preferred solution is easier, that's even better.

**Comment by nathanlesage** [comment]
Short update: I just tested with 1.8 on Windows 10, and somehow the fonts are being loaded correctly now. I'm gonna leave that issue open for the time being, but apparently it was only occurring during the beta…? I have no idea what Electron forge does here.

**Comment by nathanlesage** [comment]
Closing since the issue seems to be resolved now.
