### ISSUE TITLE
[Feature Request] show all files using certain tag when in "tags" view aka tag cloud

### ISSUE THREAD

**Issue by foss-** [Zettlr/Zettlr#145]
The tag feature is great. It could be even more useful, if it was possible to a) show the number a tag was used by default https://github.com/Zettlr/Zettlr/issues/128 and b) a click on a tag would show a list of files using that specific tag and allowed opening a file from that list.

This should be very useful for research work and allowing to easier connect files for the same tag although they are stored in various directories.

**Comment by nathanlesage** [comment]
Concerning b): You can already only show certain files with a tag using the global search. If you precede the tag explicitly with a hashtag, Zettlr will only show you files tagged with what you searched for, e.g. `#my-tag` will not yield files in which `my-tag` is present without the hash sign.

**Comment by foss-** [comment]
Sweet, wasn't aware.. Is there a keyboard shortcut to get to the global search? cmd+F goes to the search for the current file. So this feature request would concern specifically the "Tags" view.

**Comment by nathanlesage** [comment]
Global search: `Cmd or Ctrl+Shift+F`

**Comment by nathanlesage** [comment]
And concerning clicks on the tag: Sure, I'll get to it!

**Comment by ElectronicTeaCup** [comment]
I saw a friend using Bear the other day and saw how tags were marked:

![image](https://user-images.githubusercontent.com/31346583/56061890-09def000-5d6b-11e9-836b-96fa8e5ef0e1.png)

It looked pretty neat.

**Comment by nathanlesage** [comment]
It's a little bit … massive I think 🤔

**Comment by samarulmeu** [comment]
I think this can be easily done by the Custom CSS feature. 

I can't stress enough how important and **huge** improvement and feature of Zettlr was the `Custom CSS`. Ok, you have to know a little bit of CSS, but then you can have **your** app.

**Comment by samarulmeu** [comment]
In the new 1.3.0-alpha version you have the number of tags shown by the side of tags and also when you hover the tag name. Isn't it redundant?

Was searching by clicking on the tag implemented or it will be a future feature?

**Comment by nathanlesage** [comment]
Yep, it's redundant, i didn't remove that hovering effect until now. And the file search function will be implemented in the future, there's been an issue concerning that, iirc!
