### ISSUE TITLE
[1.8.0] Win10, Sticky menu bar overlapping opened preferences dialog

### ISSUE THREAD

**Issue by derwok** [Zettlr/Zettlr#1450]
## Description
When I choose from main menu `File / Preferences / Manage Tags` (or any other choice from the Preferernces sub menu), the application menu stays open and overlapps the opened dialog

## Reproducing
Click File / Preferences / Manage Tags on Win10 menu

## Expected behaviour
Menu shoud close before dialog opens

![image](https://user-images.githubusercontent.com/4393698/100432788-6145e700-309a-11eb-95a9-36c670d6646e.png)

## Platform
 - OS and version: Win10
 - Zettlr Version: 1.8.0 (final)

**Comment by robxylyxuk** [comment]
I can confirm this is happening for me too. Seems to have occurred since the last beta, as it worked in beta 4.

**Comment by jsstanley** [comment]
I can reproduce this bug too on Zettlr 1.8.0 and Windows 10.
