### ISSUE TITLE
[ENHANCEMENT] [1.8.0] Support ZKN links in hovering tooltip

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1454]
## Description

First of all, Zettlr 1.8.0 is great so far! The tooltip for links is really helpful, thanks for implementing. What I would like to suggest with this issue is, to also enable the tooltip for **ZKN links** ([[id]]). This would speed up navigating through your Zettelkasten by a lot.

## Proposed Changes

- Show tooltip also for ZKN links, i.e. [[...]]
- It would be good if this worked irrespectively of the content between the [[ ]]
    - So for both [[20201127123559]] or [[my-file]] the tooltip would show up
- Clicking on the link of the tooltip would simply do the same as Ctrl/Cmd clicking
    - i.e. open the file (if it exists) + search globally for the id/text.

## Caveats

Not sure.

**Comment by nathanlesage** [comment]
Fixed by #1988
