### ISSUE TITLE
[BUG] Distraction-free mode doesn't hide certain UI elements in Zettlr 1.8.0

### ISSUE THREAD

**Issue by jsstanley** [Zettlr/Zettlr#1457]
## Description

After upgrading to Zettlr 1.8.0, toggling distraction-free mode no longer removes the window header/toolbar. I can't find anything in the Preferences to modify this behaviour. In Zettlr 1.7.x, the window header/toolbar would also hide for a truly distraction-free experience.

## Reproducing

*Zettlr 1.8.0*

Distraction-free mode off:
![image](https://user-images.githubusercontent.com/50111317/100449090-39ab4a80-30ab-11eb-86d6-77dfdfb98ec9.png)

Distraction-free mode on:
![image](https://user-images.githubusercontent.com/50111317/100449157-5778af80-30ab-11eb-84ef-25536be361ca.png)

## Expected behaviour

On toggling distraction-free mode on, Zettlr should hide everything in the UI except the markdown file you are working on.

## Platform
 - OS and version: Windows 10 Version 20H2
 - Zettlr Version: 1.8.0

**Comment by nathanlesage** [comment]
This is expected: the toolbar will never be hidden, you have to do this using custom CSS!

**Comment by jsstanley** [comment]
I see, thanks. I'll have a play with some custom CSS.

**Comment by nathanlesage** [comment]
Do so; if I remember correctly, someone already shared the necessary code on the forum (albeit I think it might need to be rewritten with the new rules …)

This video might help you: https://www.youtube.com/watch?v=QcJGI_3adhc

**Comment by jsstanley** [comment]
Yes, I've come across this helpful snippet in the docs which I seemed to have added in Zettlr's custom css previously but forgotten about: https://docs.zettlr.com/en/core/custom-css/#hide-the-toolbar-in-distraction-free

It seems that 1.8.0 introduces some changes which means the following no longer works:
```
#editor.fullscreen, .CodeMirror-fullscreen { top: 0px; }
```

However, I will have a go at modifying this and will have a look at the video you kindly linked.

**Comment by nathanlesage** [comment]
> It seems that 1.8.0 introduces some changes which means the following no longer works:

Yes, there's now a conditional rule that tends to that somewhere in the Geometry files, see here: https://github.com/Zettlr/Zettlr/blob/develop/source/common/less/geometry/editor.less#L132

If you find a workaround, please feel free to suggest the correct CSS rules to our [documentation repository](https://github.com/Zettlr/zettlr-docs), where I will gladly merge it!

**Comment by jsstanley** [comment]
I've managed to find the correct css rules to achieve what I wanted. Please find the PR for the docs [here](https://github.com/Zettlr/zettlr-docs/pull/84).
