### ISSUE TITLE
Version display incomplete on https://www.zettlr.com/download

### ISSUE THREAD

**Issue by derwok** [Zettlr/Zettlr#1459]
See https://www.zettlr.com/download

![image](https://user-images.githubusercontent.com/4393698/100451036-02db3180-30b7-11eb-9876-684918df58f0.png)

**Comment by nathanlesage** [comment]
Noticed this myself, but I have absolutely no idea what weird hiccup the API has in that case …

**Comment by nathanlesage** [comment]
Oh, know where this is coming from: I completely forgot to add the "v" in front of the 1.8 version, I'll make sure to re-add this later, then the display will be fixed.
