### ISSUE TITLE
[Resolved] Can't generate pdf

### ISSUE THREAD

**Issue by jlnbdt** [Zettlr/Zettlr#146]
Hi,
First of all, thank you a lot for this very nice app!

## Description
Can't export to pdf. I get the following:

    pandoc: unrecognized option `--pdf-engine=xelatex'
    Try pandoc --help for more information.

## Reproducing
Just click the pdf icon.

## Expected behaviour
Produce a valid pdf file :-)

## Platform
 - OS: Ubuntu
 - OS Version: 18.04.2 LTS
 - Zettlr Version: 1.2.3

## Additional information

    $ pandoc --version
    pandoc 1.19.2.4
    Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1

    $ xelatex --version
    XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Debian)
    kpathsea version 6.2.3

**Comment by samarulmeu** [comment]
From pandoc 2.0 `--latex-engine` changed to `--pdf-engine`.
I had the same problem so I had to install the latest pandoc from site as my Ubuntu distribution supports only 1.9.

**Comment by jlnbdt** [comment]
Thank you. I've upgraded Ubuntu to 18.10. It works perfectly now :+1:
