### ISSUE TITLE
[BUG] [1.8.0] Global search highlighting broken

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1460]
## Description

When a **global search** is performed (manually or via ZKN link click), the **highlighting** of the search results does not work reliably anymore.

More precisely, the results in the currently open file do get highlighted at first, however, when you switch to another file through the search results on the left, nothing is highlighted there (and when switching back to the first file, highlighting doesn't work there anymore either).

If you pay close attention after switching a file, you can briefly see the words actually getting highlighted, but it disappears within a split second.

The location marking in the scrollbar is not affected though. 

## Reproducing

1. Do a global search
2. Click on a file in the results list
3. Matches in text are not highlighted

## Expected behaviour

Highlight matches.

## Platform
 - OS and version: Ubuntu 20
 - Zettlr Version: 1.8.0

## Additional information

Worked fine in 1.7.5

**Comment by nathanlesage** [comment]
> If you pay close attention after switching a file, you can briefly see the words actually getting highlighted, but it disappears within a split second.

Thank you, this quick information might help me take a shortcut to solving this!

**Comment by kyaso** [comment]
I just tested 1.8.1 (AppImage64), and the issue is not present there anymore. Double checked with 1.8.0 again, and there the issue was still present.

**Comment by nathanlesage** [comment]
Perfect, thank you for getting back. Feel free to close those resolved issues yourself! :)
