### ISSUE TITLE
Cannot see note text in linux

### ISSUE THREAD

**Issue by lukeallister** [Zettlr/Zettlr#1462]
## Description

Cannot see note contents on 1.8.0

The TOC is correct in the sidebar (very cool looking, BTW), but there is no text.

## Reproducing

Update to 1.8.0 from 1.7.5 using the .deb release

## Expected behaviour

Notes work

## Platform

- Linux Mint 19.1, MATE 64-bit (installed .deb release)
- 1.7.5 worked
- 1.8.0 doesn't

## Additional information

It looks like the folder/file navigation is all working but when I open a md file it doesn't show text at all.

I downgraded back to 1.7.5 and everything works there.

**Comment by nathanlesage** [comment]
Do you happen to use VIM edit mode? I'm asking because it's broken and causes text to disappear.

**Comment by lukeallister** [comment]
Yep, that's me! I see that's already tracked in #1415 so I'll close this one.
