### ISSUE TITLE
DMG Mac Release on 1.8.0 page is actually the 1.6.0 build

### ISSUE THREAD

**Issue by rabble** [Zettlr/Zettlr#1463]
## Description
The release page https://github.com/Zettlr/Zettlr/releases/tag/1.8.0 has a DMG for Zettlr which at least for the mac DMG is actually the 1.6.0 release. Because of this you download, install the upgrade, but it's still the old version, then you get an alert telling you to upgrade. It's an endless loop. 

## Reproducing
Download and install the dmg linked from: https://github.com/Zettlr/Zettlr/releases/tag/1.8.0

## Expected behaviour
There should be a DMG with the build for 1.8.0. 

## Platform
 - OS and version: Mac
 - Zettlr Version: Github release links for Zettlr 1.8.0

## Additional information
Seems like it was just a mistake in the build scripts as this 1.8.0 is from yesterday.

**Comment by nathanlesage** [comment]
Please provide a screenshot of your About dialog. I currently think a lot might have been gone wrong with me accidentally forgetting to add the "v" in front of the versioning tag.

**Comment by nathanlesage** [comment]
Should work again now
