### ISSUE TITLE
[FEATURE] Filelist sort order with frontmatter tag

### ISSUE THREAD

**Issue by rottmann** [Zettlr/Zettlr#1464]
## Description

Add abbility to sort the fileliste by frontmatter tag `order`.

## Example Workflow

```
---
title: Some title
order: 1
---

My document
```

Without an order tag the filename/title is used.

Sorting by time still sorts by time. Sorting by name (`Aa`) sorts by frontmatter tag order and filename.

Iam not sure if an extra "sort by frontmatter" is necessary in the filemenu, i think sort by name `Aa` is ok.

**Comment by nathanlesage** [comment]
Is there any way Pandoc would use something like that to sort files? If not, I'd rather say let's do this via the directory settings files (CC @Kangie )

**Comment by Kangie** [comment]
I don't believe so. Pandoc doesn't really do ordering - It will concatenate multiple input files, but it does them in the order you give on the command line. 

[This](https://pandoc.org/MANUAL.html#default-files) example from the documentation should show all *current* options, for reference. 

If you want to implement this by parsing the YAML block I can't see any issues - pandoc will happily parse the variables set in YAML and won't error if they don't appear in the template, etc.
