### ISSUE TITLE
[FEATURE] Option to hide Frontmatter in the main window and show them in the sidebar

### ISSUE THREAD

**Issue by rottmann** [Zettlr/Zettlr#1465]
## Description

Option to hide Frontmatter in the main window and show them in the sidebar.
Less distraction in the main content area.

**Comment by nathanlesage** [comment]
Hey, thanks for the request! However, this would mean to hide a large and important portion of the document, and this is not in line with the general philosophy of Zettlr to only hide text if it's transparent and clear where it ended up, so unfortunately, I cannot implement this!
