### ISSUE TITLE
not remembering open file, whenever re-opening the same file is opened

### ISSUE THREAD

**Issue by foss-** [Zettlr/Zettlr#1467]
## Description
Minor bug: whenever I open Zettlr, it always opens a certain file from one subdirectory.

## Reproducing
Open Zettlr

## Expected behaviour
Would be great if Zettlr remembered the file that was last opened and continue with the last view it was closed with. This is not the case currently. No matter what file is open, after closing and reopening Zettlr I am back on the one file it always opens with.

## Platform
 - macOS 10.15.7
 - Zettlr 1.8.0

**Comment by nathanlesage** [comment]
Pretty sure this has to do with #1474

**Comment by foss-** [comment]
If there is debug data that could help, let me know. This is reproducible here on every opening of the app.

**Comment by nathanlesage** [comment]
If there are warnings or errors in the logs, sure!


Here's how you find the logs:

After you quit the app, Zettlr will save the collected logs to disk. You can find them …

* … on Windows: `C:\Users\<your username>\AppData\Roaming\zettlr\logs`
* … on macOS: `/Users/<your username>/Library/Application Support/zettlr/logs`
* … on Linux: `/home/<your username>/.config/zettlr/logs`

They are named after the day where they were created in the format `yyyy-mm-dd.log`

**Comment by foss-** [comment]
No errors only a warning on open
`[23:12:36] [Warning] [FSAL Watchdog] The chokidar process falls back to polling. This may lead to a high CPU usage.`

Note: you can use ~/Library/Application Support/zettlr/logs if you want to get to the user library on macOS, so you can replsace `/Users/<your username>`with `~`.

**Comment by nathanlesage** [comment]
The warning is to be expected. Hm. I'll have a look. Maybe it's fixed with 1.8.1!

**Comment by foss-** [comment]
1.8.1 indeed fixed the problem for me. Thanks so much.
