### ISSUE TITLE
404 error with brew installation

### ISSUE THREAD

**Issue by The33Coder** [Zettlr/Zettlr#1469]
Hello,
In https://zettlr.com/download, you are brew link to install. However, when I execute the command I get a 404 error.
if I try to open the url https://github.com/Zettlr/Zettlr/releases/download/1.8.0/Zettlr-1.8.0.dmg I have same error and if I see the link from releases. Is https://github.com/Zettlr/Zettlr/releases/download/v1.8.0/Zettlr-1.8.0.dmg
```
❯ brew cask install zettlr
==> Downloading https://github.com/Zettlr/Zettlr/releases/download/1.8.0/Zettlr-1.8.0
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'zettlr' with message: Download failed: https://github.com/Zettlr/Zettlr/releases/download/1.8.0/Zettlr-1.8.0.dmg
```

**Comment by nathanlesage** [comment]
Yup, I had to monkeypatch the "v" in front of the versioning number. Apologies for messing it up, but hopefully the brew release will automatically pull in the updates. Otherwise, I would suggest pinging the maintainer so that it's manually fixed! :)
