### ISSUE TITLE
When linking files, ID is duplicated

### ISSUE THREAD

**Issue by berzhot** [Zettlr/Zettlr#1470]
## Description

My files are created like this: "ID Name.md". For example:"20201121220427 Menos es mas.md" . 
In Preferences/Zettelkasten "When linking files, add the filename...", "always" option is selected.

Usually, when creating an internal link, suggestion list shows files as "20201121220427 Menos es mas" 
![expected](https://user-images.githubusercontent.com/8502544/100525831-d95bfc00-31c3-11eb-9613-5cda0138b09b.png)
and created link shows the same
![Expected 2](https://user-images.githubusercontent.com/8502544/100525839-e1b43700-31c3-11eb-9b33-62f2a08d3ec9.jpg)

Now I'm getting this behaviour
![strange1](https://user-images.githubusercontent.com/8502544/100525855-01e3f600-31c4-11eb-95e6-3bb4feb572f5.jpg)
and created link shows repeated the ID
![strange 2](https://user-images.githubusercontent.com/8502544/100525909-4c657280-31c4-11eb-9080-7cc29bc13030.jpg)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0

**Comment by yhoiseth** [comment]
Reproduced on 1.8.1 with macOS.

**Comment by santidingo** [comment]
Same on 1.8.1 with Windows 10.

![image](https://user-images.githubusercontent.com/6327497/101370022-d1542a00-385d-11eb-8583-ab7c4557e669.png)
![image](https://user-images.githubusercontent.com/6327497/101370224-16785c00-385e-11eb-8098-55ecb84d29fe.png)

**Comment by nathanlesage** [comment]
Was a regression after a refactor; should work again now.
