### ISSUE TITLE
"Preferences" option in File Menu, doesn't work

### ISSUE THREAD

**Issue by berzhot** [Zettlr/Zettlr#1471]
## Description

Clicking "preferences" in the "File" menu doesn't work

## Reproducing
If I navigate through the File menu, and try to click "Preferences" option, nothing happens

## Expected behaviour

![Captura de pantalla 2020-11-28 214206](https://user-images.githubusercontent.com/8502544/100526094-25a83b80-31c6-11eb-9caf-8d15baef5b38.jpg)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0

**Comment by nathanlesage** [comment]
Already fixed, coming in 1.8.1!
