### ISSUE TITLE
Text or Links in a footnote are not displayed correctly 

### ISSUE THREAD

**Issue by berzhot** [Zettlr/Zettlr#1472]
## Description

Any text or link I write in a footnote is not displayed correctly. First word is shown in a different color
## Reproducing

![actual](https://user-images.githubusercontent.com/8502544/100526479-8ab16080-31c9-11eb-9f8a-9ae5cab84b99.png)

## Expected behaviour

![expected](https://user-images.githubusercontent.com/8502544/100526483-900eab00-31c9-11eb-9bfa-ebae90d75639.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0

**Comment by nathanlesage** [comment]
This is due to the underlying gfm mode. It's purely æsthetic, so it won't impart any functionality.
