### ISSUE TITLE
[v.1.8.0] Editor frozen after switching to vim mode

### ISSUE THREAD

**Issue by whytong** [Zettlr/Zettlr#1473]
## Description
The Editor is frozen after changing to vim mode.

## Reproducing
Fresh installation, generate one .md file, type in a few lines, change the Editor to vim mode in settings, then the Editor is frozen and no input is possible. Other menu items still possible.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0

## Additional information
Tried to delete the files under %USER%\AppData\Roaming\zettlr folder and restart. Same problem.

**Comment by nathanlesage** [comment]
Gonna get the discussion of #1415 over here. Here's the short story:

- I'll be deactivating the VIM mode in the dropdown from 1.8.1 because there's no priority for me in having it.
- However, I see that a lot of people actually want VIM mode.
- So here's the deal: If someone wants to tackle the VIM mode, I'll accept a PR that reinstates it's functionality as long as it doesn't degrade the performance and functionality of other components.

In general: I'm more than willing to add features to Zettlr that are made for technical users, **but** only if they are no-ops for me (e.g. don't require maintenance on my part, that is: are being maintained by someone else).

**Comment by the-solipsist** [comment]
I think this is a fair and sensible outcome.  The target of Zettlr is the non-technical(-but-technical-enough-to-be-using-markdown) user, and Vim keybindings are for more-technical users.  And so, this will have to be lower in priority and will have to be maintained by another dev.

I would like to point out, however, that Vim mode isn't only about keybindings and about modal editing, but they also about additional features.  For instance, Zettlr don't have a "join lines" feature, which the Vim mode (with [Shift+j]), in effect, adds.  (This is very useful for fixing incorrectly split sentences after copy-pasting from a PDF, for example.)

In the meanwhile, if Emacs mode is better maintained at the Codemirror level, then perhaps it will be worthwhile for the more technical users to check out Emacs keybindings.

**Comment by serpro69** [comment]
Will subscribe to this issue just in case it ever gets resolved.
Took a brief look at Zettlr and it looks great. But not having vim mode is a dealbreaker for me, so I'll stick to other apps for now, hoping that vim support will once again be present in Zettlr one day.

**Comment by siriak** [comment]
I'll stick to using 1.7.5 for now too

**Comment by marvinbernhardt** [comment]
Me too

**Comment by Fryie** [comment]
I completely understand that the owner of this repo doesn't want to maintain the vim mode they themselves don't use, and if I had more time, I would try contributing to a fix, but it would still be nice if this issue could be kept open in case anyone else can get this to work again. Zettlr seems like a really nice app, but I won't update as long as vim mode is missing, as I really can't go back to working without it (muscle memory and all).

**Comment by ttxtea** [comment]
I also think vim-mode is useful for some users for fast text manipulation.

**Comment by the-solipsist** [comment]
Currently, I paste into nvim or Atom to do some light text editing (such as using `ctrl+j` for joining lines I've pasted from a PDF), and then copy-paste that edited text into Zettlr.

**Comment by account-sxf** [comment]
A quick solution (in the name of fewer keystrokes/speed) to appease us Vim users might be a quick shortcut to launch the current file in vim (or even a keyboard shortcut for "show file" and we can open it in Vim ourselves via the OS). Vim is huge, and it really doesn't make sense to emulate it unless you have an interest in it or a lot of money/developers (e.g. the team at Jetbrains, who develop the IdeaVim plugin, I guess?).  There is also the possibility of using Neovim as a backend, though that would have it's share of challenges too.

Just perused the docs to make sure I'm not assuming the absence of an "open with" sort of option from within the interface, but there is only the right-click "Show file".

It's given me an itch to have a go at it.

**Comment by ttxtea** [comment]
There is also a (subset of) vim implementation in `python`
https://github.com/prompt-toolkit/pyvim

There is also `minivim`, `vimlib` usw and I would guess that vim users are very happy with a reduced functionality.
It seem that the `atom editor` `vim-mode-plus` is rather layered and complex. And I don't know which library that is based on.
