### ISSUE TITLE
All files are blank after update

### ISSUE THREAD

**Issue by zigius** [Zettlr/Zettlr#1475]
## Description

All files are blank. Cant view content of files in workspace in the editor after upgrade to 1.8.0

## Reproducing

Upgrade zettlr to 1.8.0

## Expected behaviour

View content of my files

![image](https://user-images.githubusercontent.com/13416165/100546697-6312d480-326b-11eb-965f-5b3e3d2645c2.png)

## Platform
 - OS and version: macos
 - Zettlr Version: 1.8.0

**Comment by nathanlesage** [comment]
Are you using vim mode?

**Comment by zigius** [comment]
yeah i used it before the update. 

Tried disabling it after the update but I cant

**Comment by zigius** [comment]
After restart, I changed vim mode to normal, closed and opened the editor and now its working again. 

Did the same thing before the restart and it went back to vim mode after reopening the app

**Comment by zigius** [comment]
Thanks, I can close the issue if you would like
