### ISSUE TITLE
[BUG] Cannot load bibliography in Zettlr. TypeError.

### ISSUE THREAD

**Issue by pavlohrab** [Zettlr/Zettlr#1476]
## Description
Exported the file in Better CSL Json format (or Better BibTex). Then tried to import it in Zettlr, but failed with the following error:
`TypeError: Cannot read property 'strings' of undefined` 

## Reproducing

Load Better CSL json or Better BibTex format files into zettlr
## Expected behaviour

Added citation library <br>

Actual behaviour: <br>

![image](https://user-images.githubusercontent.com/38843017/100548678-be968f80-3276-11eb-8a86-431f41284f21.png)

## Platform
 - OS and version: Manjaro Linux 64-bit
 - Zettlr Version: 1.8.0

**Comment by beardhatcode** [comment]
i have the same issue on NixOS with 1.8.0 (it worked in 1.7.5). 

My bib file no longer works: [bib.txt](https://github.com/Zettlr/Zettlr/files/5614642/bib.txt) (as txt because GitHub does not allow bib files)

**Comment by nathanlesage** [comment]
There were some errors in the citeproc provider. I just got to it and fixed a lot of them. I'll be improving the provider further in the future, but for now it should work again! If not, feel free to comment here again (the next release will come some time next week I suppose)
