### ISSUE TITLE
[Bug] Task lists

### ISSUE THREAD

**Issue by myn-user** [Zettlr/Zettlr#148]
Hi,

I have a little problem with the task list.

## Description

I had created a nested task list.
When I checked a task on level two, the checkbox of the task "jumped" to the begin to the line.
Sometimes the colour of the text of this "jumped" tasks went blue.
Sometimes the text of the task "jumped" somewhere inside the document and "overwrote" text of a headline for example.

## Reproducing

1. Create a nested task listed:

- [ ] A
- [ ] A
  - [ ] B
  - [ ] B
    - [ ] C
  - [ ] B

2. Now check some of the tasks.
3. See what happens. ;-)

## Platform
 - OS: Windows 8, 64-Bit
 - Zettlr Version 1.2.3

**Comment by nathanlesage** [comment]
Okay, Problem was related to a miscalculation (as in: not even happening) of the position of the task list items at the moment when you clicked them, leading them to replace the whole line with a wrong amount of spaces. Attached patch fixes this!

**Comment by henrique9i** [comment]
Another similar bug, when you deselect a task level> 2, it doesn't actually deselect, it creates another unchecked checkbox and hides the one checked.
Also jump to the beginning.
![Zettlr_05Z9ivTsJ5](https://user-images.githubusercontent.com/62220974/80656893-ab111500-8a58-11ea-81f1-7a8f9e95d320.png)

**Comment by nathanlesage** [comment]
> when you deselect a task level> 2, it doesn't actually deselect

Whoops, will have a look

**Comment by nathanlesage** [comment]
I think this bug has already been resolved for 1.7 — if not please comment.
