### ISSUE TITLE
Paste Without Style Shortcut Not Working As Intended

### ISSUE THREAD

**Issue by the-blunderbuss** [Zettlr/Zettlr#1480]
## Description
When the shortcut is used for Paste Without Style is used (Control + Shift + V in Windows), the software will paste the clipboard contents twice, once with and once without styles.

## Reproducing
Copy any text and paste it by using the Control + Shift + V shortcut. You will see the text pasted twice and, had you copied text with specific styles (e.g. a heading) you will see it pasted first _with_ the style and then _without_ the style. Please note that this only occurs when using the shortcut and not when selecting the option from the context menu or from the Edit menu.

## Expected behaviour
Zettlr should paste the relevant text _once_ and do so without retaining any styles.

## Platform
 - OS and version: Windows 10 Version 10.0.18363 Build 18363
 - Zettlr Version: 1.8.0

## Additional information
I've tested in two different PCs and with two different keyboards to (within my means) rule out any OS or hardware weirdness. So far, the incorrect behavior is consistent.

**Comment by coevolving** [comment]
I am having the same problem that Paste without Style is not working in Zettlr 1.8.0 .

This was not an issue in the releases that we've had over the past 6 months.  (It's annoying now, I paste and then have to delete!  Sometimes a paste and then ctrl+z removes a double paste to leave a single).

**Comment by coevolving** [comment]
Updated to Zettlr 1.8.1 this morning.

When I have copied plain text onto the clipboard.

* ctrl+shift+V pastes the text twice
* Edit ... Paste without style ... pastes correctly!  

When I copy a link (with http)

* ctrl+shift+V pasts the link, and then a plain text of the link
* Edit ... Paste without style ... pastes correctly!

:laughing: Is Zettlr trying to discourage the use of shortcut keys?

**Comment by nathanlesage** [comment]
Unfortunately, I cannot reproduce this locally, and I cannot find anything in the codebase that would explain this behaviour. Is this only happening on Windows?

**Comment by boutil** [comment]
I am experiencing this on Linux with the Debian package as well.
- Ctrl+Shift+V duplicates the material to be pasted (with/without escape codes)
- Paste without style menu works as expected

**Comment by coevolving** [comment]
Today, I updated to Zettlr 1.8.3 , on Windows 10 Pro, OS build 19041.572 .

The paste-without-style keyboard problem persists. 

This problem only started with Zettlr 1.8 , and wasn't a problem with Zettlr 1.7.

**Comment by nathanlesage** [comment]
> This problem only started with Zettlr 1.8 , and wasn't a problem with Zettlr 1.7.

Yeah, thanks for reiterating, but this does not help. There is some logical error within CodeMirror after my refactoring, but we have to pinpoint it somewhere to a specific piece of code.

**Comment by the-blunderbuss** [comment]
This issue is currently marked as **Waiting For Feedback**. I assume given that it wasn't clear at the time whether this was an error limited to Windows OS. Considering this is (as far as I'm aware) no longer the case:

1. What is the current status of this issue?
2. If the status is correctly listed as "Waiting For Feedback", what feedback would prove useful to further decipher what might be going wrong?

**Comment by nathanlesage** [comment]
> If we still are waiting for feedback, what feedback would prove useful to further decipher what might be going wrong?

Actually, someone who can perform some debugging of the code base to see what's happening. I'm still at a loss and only on macOS, it's a classical case of "works on my machine".

**Comment by areographe** [comment]
Hey, I'm getting this same issue on Manjaro Linux at the moment. Is there any way I can help with the debugging for this problem? My current experience with Zettlr is otherwise very very smooth with essentially no other issues and finding it very useful, but I'd love to help fix this one problem :)

**Comment by nathanlesage** [comment]
@areographe The easiest way (for me at least) would be if you could actually locate the malfunctioning code by putting in some console.logs or something in the code base 👀

**Comment by ludwigHoon** [comment]
Additionally, the ctrl + shift + v seems to also prompt saving as image in certain situation (even the the image is not saved even if I click save in current directory). In such situation, though the content is not duplicated.

**Comment by nathanlesage** [comment]
> saving as image in certain situation

This will happen mostly with Microsoft Office products, since these not just copy the text you selected, but also an image of that text, and Zettlr will first look for an image in the clipboard and offer to save this. And, only if there's no image, Zettlr will attempt to paste text.
