### ISSUE TITLE
[DEVELOP] Deprecate 32bit, Bundle Pandoc

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1481]
I'm opening this issue because due to Pandoc being caught between 2.10 and 2.11, depending on the package manager, we need a solution for this. I've been speaking to Albert of the Pandoc project, and he suggested that we bundle Pandoc directly with Zettlr to mitigate said problems, and also make it easier for non-technical users to use the app directly.

However, Pandoc is only provided for in 64bit versions, and I do not intend to perform any additional stuff in order to compile the binary for 32bit manually, because that would make my work once again more difficult, not easier.

This issue is meant as a reminder that it has priority to do so. The current problems with incompatibilities between Zettlr and Pandoc are a little bit overwhelming, especially for novice users. By bundling Pandoc directly with Zettlr, we mitigate those problems, and achieve even better possibilities with regard to customization and the controlling of the binary.

I will announce what will be happening on the blog quickly. Please comment below in case you have questions.

**Comment by Kangie** [comment]
So I have a branch that I was working on to resolve the Windows issues during the beta that used a script to put files outside the webpack during the build (etc). I hope to have some time to pick that back up soon (had to work on some other projects & actually code for work) - I assume that it'll be useful here!

I'm 100% in favour of doing so; It will eliminate issues such as those from the recent citeproc change among other things!

**Comment by nathanlesage** [comment]
> I assume that it'll be useful here!

You mean a script to perform the Pandoc-bundling step? :D

If so, I just committed code that will bundle Pandoc on supported platforms (64 bit and ARM64-macOS). Feel free to have a look:

https://github.com/Zettlr/Zettlr/blob/develop/forge.config.js (the extraResource part)

https://github.com/Zettlr/Zettlr/blob/develop/scripts/get-pandoc.sh

**Comment by Kangie** [comment]
Hah. You're a bit ahead of me! Looks good!

Yes, it would have accomplished a similar thing, but was aimed at resolving the issues you were having with webpack and fonts on Windows during the 1.8.x beta. Since it resolved itself for the release I put it on the backburner!

**Comment by nathanlesage** [comment]
> Yes, it would have accomplished a similar thing, but was aimed at resolving the issues you were having with webpack and fonts on Windows during the 1.8.x beta. Since it resolved itself for the release I put it on the backburner!

Ah, yeah, webpack. I'm not quite sure but I think Electron-forge (and, with that, electron-packager) lags behind a little bit either way. There are some packages we can't update yet because Electron-forge only supports webpack 4, and somehow it still doesn't support Apple's M1 config, which is a bummer :(

**Comment by nathanlesage** [comment]
Closing in favour of #1690
