### ISSUE TITLE
Ctr+Click does nothing + black horizontal rectangle under mouse when hover link

### ISSUE THREAD

**Issue by JosephLucas** [Zettlr/Zettlr#1482]
Hi, thanks for Zettlr, I just tried it and I really like it. 
(I wonder how you manage to work on all your projects at once.)

## Description
I Have some issues when I click on links.
When I click on  a URL that goes to the web nothing happens. Even with Ctr+Click.

## Reproducing
On NixOS, add the [unstable channel](https://nixos.wiki/wiki/Nix_channels)
```
nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
```
Update the channel
```
nix-channel --update nixos-unstable
```
Install Zettlr 
```
nix-env -iA nixos-unstable.zettlr
```
Then 
- Open Zettlr (currently v1.75 is packaged) 
- try to Ctr+click on a link: e.g. [google](google.com).

When I hover the link, a black horizontal rectangle is displayed under the cursor.

## Platform
 - NixOS, [unstable channel](https://github.com/NixOS/nixpkgs-channels)
 - Zettlr Version:[1.75, packaged in nixpkgs](https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/pkgs/applications/misc/zettlr/default.nix)

## Additional info

For reproducibility, it should be enough to install Zettlr with the [Nix package manager](https://nixos.org/download.html#nix-quick-install), within any linux distribution.
Otherwise you can run [a VM with NixOS](https://nixos.org/download.html#nixos-virtualbox)

**Comment by JosephLucas** [comment]
Trying to convert a markdown document into html i get the error
```
pandoc: symbol lookup error: /usr/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```
I confirm that on NixOS there is no ` /usr/lib/libc.so.6`, only `/usr/bin/env`. Otherwise binaries and executables are all within the store `/nix`.

Maybe the path to `/usr/lib/libc.so.6` is hardcoded in the AppImage of Zettlr.
Usually Nix packagers alter ELF binaries with PatchELF to change the paths hardcoded to runtime dependencies. 
It seems that is not done in the Zettlr package of this distribution.

**Comment by nathanlesage** [comment]
I am afraid I do not quite understand both the issue and how I could do anything to alleviate this?
