### ISSUE TITLE
Preferences menu doesn't work from File -> Preferences

### ISSUE THREAD

**Issue by ShanSanear** [Zettlr/Zettlr#1483]
## Description
Clicking through File -> Preferences -> Preferences doesn't work. Preferences menu doesn't appear at all. Other submenus (PDF Preferences, Manage Tags, Custom CSS) work correctly.

## Reproducing
1. Click FIle
2. Hover Preferences
3. Click on Preferences submenu

## Expected behavior
Preference menu appears.

![image](https://user-images.githubusercontent.com/8857417/100872942-dfdbc380-34a2-11eb-9130-85135117b673.png)

## Platform
 - OS and version: Windows 10 Pro 20H2
 - Zettlr Version: 1.8.0

## Additional information
There is a workaround to this issue - the shortcut for these options works correctly (Ctrl + , )

**Comment by jsstanley** [comment]
This is a duplicate of #1451. A [fix](https://github.com/Zettlr/Zettlr/commit/062c6b1499868052e667b8af36d8dba0da85fe26) has been made and will be released in Zettlr 1.8.1.

**Comment by ShanSanear** [comment]
Oh, didn't see that one in the browser for some reason. Closing it then.
