### ISSUE TITLE
Should update default pandoc command

### ISSUE THREAD

**Issue by lucifer1004** [Zettlr/Zettlr#1484]
## Description

According to [Pandoc's change log](https://pandoc.org/releases.html#pandoc-2.11-2020-10-11), since `v2.11`, we should use the `--citeproc` option instead of `--filter pandoc-citeproc`.

**Comment by jsstanley** [comment]
This has already been reported in #1420. You'll see from [that issue](https://github.com/Zettlr/Zettlr/issues/1420#issuecomment-725387725) that you can modify the pandoc command in Zettlr's preferences dialog.

Eventually, as per #1481, the intention is to bundle Zettlr with Pandoc, which will probably help avoid similar problems.

**Comment by nathanlesage** [comment]
Fixed, Pandoc 2.11 support now given, backwards-compatibility included.
