### ISSUE TITLE
[ENHANCEMENT] separate autocorrect from macro expansion

### ISSUE THREAD

**Issue by eichin** [Zettlr/Zettlr#1485]
## Description

Autocorrect (which appears to have two modes, both of which always change what I typed)  and macro expansion (which has a deterministic list of changes that I can control) are combined into one switch.  Please provide some way for me to enable macro expansion while never ever making random changes to what I typed.

## Proposed Changes

I can think of at least three ways to do this, and don't have a good style judgement between them:
* just add an independent toggle to the settings page (or move template expansion to a separate page entirely; conflating the two features seems a very developer-centric choice.)
* while you're fixing the "word mode vs libreoffice mode" toggles to include some indication of what that could possibly mean (I haven't used word in 2 decades, and I only use libreoffice for viewing) also add a "don't change my stuff" selection.  (Frankly, I was surprised that there were modes other than browser-style - red squiggles, right-click to change things - since this is an electron app, after all.)

## Caveats

Beginning user, don't know.

## Additional Information

I appreciate having been able to turn off autocorrect - but the macro expansion feature for things like `-->` is neat and it would be nice to be able to get that back.  Thanks!

**Comment by eichin** [comment]
(also: this is based on using the `Version: 1.8.0` zettlr package, under ubuntu 20.10 "groovy".)

**Comment by nathanlesage** [comment]
I am not sure what exactly sure what feature you want to exactly toggle independently. Yes, the AutoCorrect preferences can definitely make use of a much better description (but imagine implementing it, then the settings, and then also having to think of very good labels all in the same stage when you're alone), but all components can be toggled separately.

![image](https://user-images.githubusercontent.com/17251683/100981394-0bb08500-3547-11eb-8161-e59de645d5f7.png)

This works so far exactly as many word processors work. Hence, in re-evaluating this functionality in light what I hopefully was able to explain, please remember that Zettlr's options attempt to first and foremost help users of Word Processors more easily to get around Markdown!

**Comment by eichin** [comment]
That's great - "quick select None" seems to be exactly what I was asking for - is there some documentation where I should have found that screenshot, or some other way I would have guessed what None meant (or even what Quick Select meant?) Or is there some specific documentation for some proprietary word processor that would be a good reference here?

I'm not sure your typical word user knows about settings like this to start with, or has even necessarily internalized what word actually does other than occasionally having to fight with it.  (I've certainly seen "computer is doing a thing and I just have to cope with it" as a frustrated user behavior, though.)

Thanks for your time, I'm fine with closing this and letting the Issue stand as documentation.

**Comment by nathanlesage** [comment]
> That's great - "quick select None" seems to be exactly what I was asking for - is there some documentation where I should have found that screenshot, or some other way I would have guessed what None meant (or even what Quick Select meant?) Or is there some specific documentation for some proprietary word processor that would be a good reference here?

I actually don't know if the docs are sufficient in this regard, but please feel free to document this, if you don't find it! The docs are free for all, and PRs are easy, and well appreciated because I simply don't have the time right now to tend to it with the time necessary. [Just open PRs on our repository](https://github.com/Zettlr/zettlr-docs)!
