### ISSUE TITLE
Localisation of project-exports (PDF)

### ISSUE THREAD

**Issue by svseidel** [Zettlr/Zettlr#1486]
## Description
Wrong language in PDF-Exports.

## Reproducing
* create a project
* write a text
* export project to PDF (German Language)

## Expected behaviour
The date-format is English (month, day, year). Instead it should use (in my case) the German notation (day month year) or the common yyyy-mm-dd.

The heading of the TOC is "Contents" and should be "Inhaltsverzeichnis".

## Platform
 - OS and version: Ubuntu Ubuntu 20.10
 - Zettlr Version: 1.8.0

**Comment by nathanlesage** [comment]
I am very positive that you can control this using the `lang`-attribute in the YAML frontmatter. Would you mind to try this?
