### ISSUE TITLE
Relative links to local files don't work

### ISSUE THREAD

**Issue by myn-user** [Zettlr/Zettlr#149]
Hi,

I have a folder with documents which I have created with Typora. 
Inside one document I have links to "attachements" I stored in this folder too.
The links are all relativ, for example `[Test](Test.pdf)`.

In Zettlr I opened this folder. But when I press the link to the file nothing happened.
I had to change the link in an absolute link in order to open the linked file.

Did I something wrong?

OS: Windows 8, 64-Bit
Zettlr 1.2.3.

**Comment by nathanlesage** [comment]
I'm on it.

**Comment by nathanlesage** [comment]
Consider it done.
