### ISSUE TITLE
Alternative Tex template is not used by PDF export in when added in Project Settings v1.8.0

### ISSUE THREAD

**Issue by webopold** [Zettlr/Zettlr#1491]
## Description
Zettlr doesn't use the given template in the Project Settings - is just  taking the default template, or the template given in the global PDF Settings
Problem persits since 1.7 here - Something wrong with the template below?

## Reproducing
Purgin deb-Package, deleting ~config; fresh Download and install

Make a new directory ~/letters
Make a new directory ~/template
place mytemplate.tex to ~/template
start zettlr and make ~/letters a project; set the template to mytemplate.tex
(i have a letter template with address etc.) 
PDF-Export 

## Expected behaviour
The above works well on the commandline with pandoc ...  --template="mytemplate.tex"  . So should zettlr do.
Furthermore there might be some additional settings for using templates without the full project behaviour

## Platform
Debian testing
 - Zettlr 1.8.0

mytemplate.tex

```
\documentclass[
    foldmarks=true,      % print foldmarks
    foldmarks=BTm,       % show foldmarks top, middle, bottom
    fromalign=right,     % letter head on the right
    fromphone,           % show phone number
    fromemail,           % show email
    fromlogo,            % show logo in letter head
    version=last         % latest version of KOMA letter
 ]{scrlttr2}

\usepackage[ngerman]{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\usepackage{parskip}

\usepackage{graphics}

\usepackage{booktabs}
\usepackage{longtable}

\usepackage[right]{eurosym}

\makeatletter
    \setlength{\@tempskipa}{-1.2cm}%
    \@addtoplength{toaddrheight}{\@tempskipa}
\makeatother

\setlength{\oddsidemargin}{\useplength{toaddrhpos}}
\addtolength{\oddsidemargin}{-1in}
\setlength{\textwidth}{\useplength{firstheadwidth}}

\begin{document}
    \setkomavar{fromname}{$author$}
    \renewcommand*{\raggedsignature}{\raggedright}
    \setkomavar{fromaddress}{
        $for(return-address)$
            $return-address$$sep$\\
        $endfor$
    }
    \setkomavar{fromphone}{$phone$}
    \setkomavar{fromemail}{$email$}
    \setkomavar{signature}{$author$}

    \setkomavar{date}{$date$}
    \setkomavar{place}{$place$}

    \setkomavar{subject}{$subject$}

    \begin{letter}{%
        $for(address)$
            $address$$sep$\\
        $endfor$
    }

        \opening{$opening$}

        $body$

        \closing{$closing$}

        \ps $postskriptum$

        $if(encludes)$
            \setkomavar*{enclseparator}{Anlage}
            \encl{$encludes$}
        $endif$
    \end{letter}
\end{document}
```

**Comment by nathanlesage** [comment]
Please use code blocks to paste files in here, otherwise they're pretty long! :) 

But yes, I think I may have just found something: Do you want to write `$if(encludes)$`? Please also make sure to check your logs, possibly there's something in there! If nothing works, I am still having a look at the settings, there'll possibly be coming some enhancements in the future either way!

**Comment by webopold** [comment]
I don't know what the question is with ```$if(encludes)``` .
I started the developer mode - the logs gave no error.
Using the template on the file with pandoc on the commandline works without errors.
The template is for a ISO-A4 Business/Private Letter with folding marks.

Same as
https://github.com/Zettlr/Zettlr/issues/1126

**Comment by maciemesser** [comment]
I failed because I did not realize at the beginning that there are two places to use a custom template, once in the PDF export settings, once in the Project settings. Maybe this is an issue in your case too?

**Comment by webopold** [comment]
I tried all combinations -- same behavior
Also described in #1126 

https://github.com/Zettlr/Zettlr/issues/1126#issuecomment-667900471

**Comment by nathanlesage** [comment]
Labelling this as "wont fix" to concentrate on mitigating this issue and quite a few other ones in the upcoming 1.9.0. For more information, please refer to this issue: #1552
