### ISSUE TITLE
Clicking between multiple tables makes table editor disappear

### ISSUE THREAD

**Issue by selflein** [Zettlr/Zettlr#1492]
## Description
The table editor disappears when clicking between different tables and shows only the markdown representation of the table which is unfocused. The table editor appears again after clicking on non table space. 

## Reproducing
Enable table editor. Create two tables and click between them. The table editor disappears for the unfocused table.

## Expected behaviour

Table editor is always shown and does not disappear on unfocusing the table like it works with clicking on normal text after having a table cell selected.

## Platform
 - OS and version: Fedora 33
 - Zettlr Version: 1.8.1

**Comment by nathanlesage** [comment]
Yes, unfortunately this is not behaviour I can influence – the table editor in itself is a little bit hacky when it comes to integration into CodeMirror, so what we need to be doing is basically: Remove the table editor, update the underlying Markdown table, and then re-apply the table after the next cursor movement. If anyone has a better idea, I gladly accept PRs!
