### ISSUE TITLE
[ENHANCEMENT] Add option to configure amount of whitespace in editor

### ISSUE THREAD

**Issue by BeatLink** [Zettlr/Zettlr#1496]
## Description

Add option to configure the amount of whitespace between the borders of the editor

## Proposed Changes

This would add an option in settings to configure the amount of whitespace between the text and the borders of the editor on the top, bottom, left and right sides. Power users (like me) who wish to maximize the screen space can reduce the amount of whitespace while those preferring a more minimalist look can increase the whitespace to make things less cluttered

## Caveats

None that I can think of.

## Additional Information

Just wanted to say that I found out about Zettlr 5 minutes ago and I already love it!

**Comment by nathanlesage** [comment]
Hey, this is already possible: Just use [Custom CSS](https://docs.zettlr.com/en/core/custom-css/#set-a-maximum-width-for-the-text) for this!

**Comment by BeatLink** [comment]
I seem to be having some trouble getting this to work

**Comment by BeatLink** [comment]
I got it to work by editing the styles in my home folder, But now I want to reduce the whitespace at the top and bottom
