### ISSUE TITLE
Clicking on items in Table of Contents does not navigate to relevant section

### ISSUE THREAD

**Issue by hueyy** [Zettlr/Zettlr#1497]
## Description
Clicking on the table of contents icon on the top bar produces a dropdown. However, none of the links in the dropdown work. 

## Reproducing

1. Open a markdown file in Zettlr which has multiple headers
2. Click the TOC icon in the top bar
3. Click any of the sections in the TOC (nothing happens)

## Expected behaviour

It should (and it did) navigate to the relevant section.

## Platform
 - OS and version: Windows 10 (OS Build 19041)
 - Zettlr Version: 1.8.1

**Comment by derwok** [comment]
Yeah. Just stumbled upon this few days back. First thought my files are somehow corrupt?
But yes: this was working fine with 1.7.5.
Two observations

1. when file has multiple headlines, sometimes the first few work as expected. But the later ones don't
2. No matter if I use the toolbar button for content navigation or the sidebar one... - both header navigations are currently broken

I use the headlines often to jump to relevant sections.
Would be cool if you coud fix this with higher prio?

Thanks for all the hard work and continuous pace!

**Comment by derwok** [comment]
Thanks! Works in 1.8.2 again
Greatly appreciated  :-)
