### ISSUE TITLE
Deb Package for 0.15.2 corrupted

### ISSUE THREAD

**Issue by CreateWebNZ** [Zettlr/Zettlr#15]
When I try to install/update current deb package via "dpkg --install Zettlr-linux-x64-0.15.2.deb", I get the following error message:

decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive Zettlr-linux-x64-0.15.2.deb (--install):
 cannot copy extracted data for './opt/Zettlr/zettlr' to '/opt/Zettlr/zettlr.dpkg-new': unexpected end of file or stream

I downloaded it serveral times with different browsers, tried to install it with gdebi, nothing works. So i assume the deb package ist corrupted.

**Comment by nathanlesage** [comment]
Already confirmed the bug, a friend called me yesterday. I'm currently assuming an error with electron-builder, but I couldn't find the exact cause yet. I'm on it!

**Comment by nathanlesage** [comment]
Okay, I've tried some things. It is not a problem with `dpkg` and not a problem with `electron-builder` and _also_ not a problem with `Zettlr` itself. It seems to be related to the Software package of Ubuntu/Gnome/Xfce.

So until we know more what this is, please use the workaround (it works definitely):

# Workaround

Simply head over into the terminal and call

`dpkg -i Zettlr-linux-x64-0.15.2.deb`

This works.

----

_I'll keep open the issue until a friend of mine has tried it with Fedora. If this fails as well we can be sure that it's not a problem of Zettlr._

**Comment by nathanlesage** [comment]
Okay forget what I wrote. I've searched the error but indeed you were right. The package simply was corrupted. It seems there has been an error on upload.

**I've replaced the defective deb package in the release page now.**

So it should work. Sorry for the inconveniences!

**Comment by nathanlesage** [comment]
Thanks a lot! :)

Stay tuned, I think tomorrow or the day after there will be a new release coming that fixes a lot concerning the search and implements a lot of useful features (among them a "heat map" indicating the relevancy of search results, as well as an "auto-highlighting" of all results in the opened file). 😄
