### ISSUE TITLE
Undo/redo

### ISSUE THREAD

**Issue by myn-user** [Zettlr/Zettlr#150]
Hi,

in my Zettlr version nothings happens when I choose **undo** or **redo** in the **edit menu**.

I use Zettlr 1.2.3 under Windows 7 (and 8), 64-Bit.

By the way: would it be possible to set shortcuts for these two functions or buttons?

**Comment by nathanlesage** [comment]
It should be fixed in this commit (https://github.com/Zettlr/Zettlr/commit/94989b8cd075886074f00c343a3897f23e8a70d6) together with #139!

Concerning shortcuts: `Cmd/Ctrl+Z` for Undo and `Cmd/Ctrl+Shift+Z` for Redo!
