### ISSUE TITLE
Problem :  Displaying heading

### ISSUE THREAD

**Issue by EchosinEchos** [Zettlr/Zettlr#1502]
I don't know why but some of my document don't format heading. It's just a display bug, but still a bug I thing.
A screen shot of the problem : 
![image](https://user-images.githubusercontent.com/29641304/101493865-e49eec80-3966-11eb-9dbd-27b0afa2da80.png)

The code witch generated the content (in full version) is this :

```markdown
---
title: "TP Modulation 9 et 10"
author: [Thibault PENNING, Sarah BENSRHIR]
institute: "ENS Rennes"
lang: fr-FR
document_class: article

output:
  pdf_document:
    number_sections: true
    toc: true
    pandoc_args: ["--filter pandoc-plot", "--filter pandoc-crossref"]
    template: "eisvogel"
...



# TP9
## Modulation a bande latéral unique (BLU)
### Préparation - étude du fonctionnement du montage :

D'après l'image du montage on a que :
$$S(t) = A\cdot \cos(2\pi f_{BF}.t ) \cdot B\cdot \cos(2\pi f_{OL}.t ) \pm A\cdot \cos(2\pi f_{BF}.t + \frac{\pi}{2}) \cdot B\cdot \cos(2\pi f_{OL}.t + \frac{\pi}{2})$$
$$=A\cdot B (\cos(2\pi f_{BF}.t ) \cos(2\pi f_{OL}.t ) \pm \sin(2\pi f_{BF}.t ) \sin(2\pi f_{OL}.t))$$
$$=A\cdot B (\cos(2 \pi t (f_{BF} \mp f_{OL})))$$


### Modulation d’amplitude classique - Test des multiplieurs :
Une fois le tout brancher on obtient le résultat suivant (@fig:TP9-1multi):

![Résultat signaux un seul multiplieur](assets/TP9-1multi.png){#fig:TP9-1multi}


### Modulation BLU (voir schéma ci-dessus) :
#### Remarque : mise en œuvre du montage

On test d'abord le déphasage des signaux. on obtient pour les deux porteuse par exemple (@fig:tp9-deph) : 

![Signaux des deux porteuse déphasé de 90°](assets\TP9-Dephasage.png){#fig:tp9-deph}

Lorsque l'on câble l’ensemble et que l'on regarde la FFT du signal reçus on obtiens : 

![FFT de la BLU (en DB)](assets\TP9-FTT-BLU.png){#fig:tp9-ftt-blu}
On a un pique a 90 kHz avec un autre pique autour 110kHz. Ce dernier est plus petit que le précédent (résultat attendu)

En modifiant la phase légérement on obteint (85° afin de corriger les soucis)(@fig:tp9-ftt-blu-85) :

![FFT du signal avec un phase de 85° ](assets\tp9-FTT-BLU.png){#fig:tp9-ftt-blu-85}

En continuant dans la foulé on obtient le tableau (phase en 75 et 85) : 

| Phase (deg) |$\Delta$dB   |
|-------------|------|
| 75          | 20   |
| 77          | 22.9 |
| 79          | 25   |
| 81          | 28.5 |
| 83          | 33   |
| 85          | 40   |
| 87          | 33   |
| 89          | 28.5 |
| 91          | 25   |
| 93          | 22.9 |
| 95          | 20   |


```{.matplotlib caption="Tacé phase par papport au $\Delta$dB"}
from matplotlib import pyplot as plt
from numpy import linspace

Y = [20,22.9,25,28.5,33,40,33,28.5,25,22.9,20]
X = range(75,97, 2)

plt.plot(X, Y)
```

##### Remarque

D'après le  précédent, on a que : $V_+ = V_-$ et $i_+ = i_-$

Or par PDT on a :
$$V_+ = V_E \frac{\frac{1}{jC\omega}}{\frac{1}{jC\omega} + R}=V_E\frac{1}{1+jRC\omega}$${#eq:1}
Mais on a aussi que : 
$$V_- - V_E= (V_S-V_E) \frac{R'}{R'+R'} \Leftrightarrow V_- = \frac{V_S+V_E}{2}$${#eq:2}
On a donc au final en mêlant @eq:1 et @eq:2 :

$$V_E\frac{1}{1+jRC\omega} = \frac{V_S+V_E}{2}$$
$$\Leftrightarrow V_E \left( \frac{1}{1+jRC\omega} - \frac{1}{2} \right) = \frac{V_S}{2}$$
$$\Leftrightarrow \frac{2}{1+jRC\omega}  -1= \frac{V_S}{V_E}$$
$$\Leftrightarrow \frac{1 - jRC\omega}{1+jRC\omega}= \frac{V_S}{V_E}$$

$$\arg(V_S)-\arg(V_E) = \arg \left(\frac{V_S}{V_E}\right) = \arg \left(\frac{1 -jRC\omega}{1+jRC\omega}\right) = 2\arg(1+jRC\omega)$$

On obtient : 
```{.matplotlib caption="Déphasage en fonction de la pulsation"}
from math import atan2, pi
from matplotlib import pyplot as plt
from numpy import linspace

#omega = list(linspace(200,1000, 1000)) + list(linspace(0, 200, 2000))
#omega.sort()
omega = linspace(0,50,2000)
Y = [ 180*(atan2(1, -o)-atan2(1, o))/pi for o in omega]
plt.plot(omega, Y)
plt.plot([0,50],[90,90])

```
Le maximum de la focntion est ici vers $\omega = 1  \text{ rad.s}^{-1}$ avec $RC = 1$
En vérité on obtient que : $\frac{\pi}{2} = 2\arg(1+jRC\omega) \Leftrightarrow \frac{\pi}{4} = \arg(1+jRC\omega) \Leftrightarrow RC\omega = 1$
$$\Leftrightarrow \omega = \frac{1}{RC}$$

#### Variante avec déphaseur HF
$$S(t) = A\cdot \cos(2\pi f_{BF}.t + \frac{\pi}{2}) \cdot B\cdot \cos(2\pi f_{OL}.t + \frac{\pi}{2}) \pm A\cdot \cos(2\pi f_{BF}.t ) \cdot B\cdot \cos(2\pi f_{OL}.t + \frac{\pi}{2})$$
$$=A\cdot \sin(2\pi f_{BF}.t) \cdot B\cdot \sin(2\pi f_{OL}.t) \pm A\cdot \cos(2\pi f_{BF}.t ) \cdot B\cdot \sin(2\pi f_{OL}.t)$$
$$=A\cdot B\cdot \sin(2\pi f_{OL}.t)(\sin(2\pi f_{BF}.t) \pm \cos(2\pi f_{BF}.t ))$$

## Modulation Amplitude en quadrature

![Sortie en triangle](assets\TP9-ultime.png)

![Sortie en carré](assets\TP9-ultime-carre.png)

# TP10

## Etude émetteur seul

On monte le circuit et on observe que la sortie du signal est sinusoïdale, et que le potentiomètre fait varier l'amplitude du signal.

![Signal de sortie du montage noté BF](assets\TP10-1.png)

On observe maintenant le signal a la sortie du circuit, on obtient : 

 ![Signal a la sortie du CI LM 566](assets\TP10-signal-carre.png)
 On remarque que le potentiomètre bleu fait varier la fréquence (et dans une moindre mesure l’intensité) du signal carré
 
 On observe maintenant la forme du signal en sortie de l'étage et on obtient : 
 
 ![Signal de sortie de l'étage HF](assets\TP10-Signal-Sortie-HF.png)
 
 Il prend la fondamentale du signal carré, pour construire le signale sinusoïdale.
 
 ![signal de sortie de l'étage AM à la branche X](assets\tp10-etage x.png)
 pour la branche sigma, nous obtenons 
 
![signal de sortie de l'étage AM au niveau de la branche sigma](assets\tp10-etage sigma.png)

![sortie du r&écepteur très faible signal](assets\TP10-pas signal.png)

![sortie avec son en entrée](assets\tp10-son.png)

on passe en signal carré!

![signal entrée carré](assets\TP10-signal carré.png)
signal triangle nous donne

![Signal triangle entrée](assets\tp10-signal triangulaire.png)
Nous allons tester un son quelconque et nous donne : 

![essai sur un son quelconque](assets\tp10-son qqconque.png)
Le signal grisille un peu mais le son est restituer correctement. 

Pour qualifie la qualité, on peut dire que si les antennes sont côte à côte la modulation donne un son gresillant de fond mais audible, qui n'est pas désagréable

```

The problem also apear in some shorter document. I think that it's related with math. It's maybe a miss use of my own. A way to fix it's to add dollars in the frontier of the bug.

Your program rock beside.
Sorry for my bad english :P 
Good luck !

**Comment by nathanlesage** [comment]
As you can see the remainder after your equations is being displayed in kind of a code-thingy font. This indicates that your syntax blocks are not complete and you're missing some ending-tags. Please check your document in this case! :)
