### ISSUE TITLE
`WM_WINDOW_ROLE` probably shouldn't be `browser`

### ISSUE THREAD

**Issue by eichin** [Zettlr/Zettlr#1503]
## Description

    $ xprop -id 0x4c00005 WM_WINDOW_ROLE
    WM_WINDOW_ROLE(STRING) = "browser-window"

Which means that using `[window_role="browser"] focus` in the `i3` window manager to jump to your browser window ends up jumping to Zettlr instead.

## Reproducing

With the above i3 command, jump to browser and not zettlr.  If you're not an i3 user, just having the `xprop` command say something other than `browser` is fine.

## Expected behaviour

Set the property to something that isn't browser.  (I don't know if Electron makes this difficult or if their are best practices for it, but it's not a browser - maybe set it to `editor`? emacs doesn't set it at all which would also be fine.)

## Platform
 - OS and version: Ubuntu 20.10 "groovy"
 - Zettlr Version: `Version: 1.8.0`

## Additional information

Hmm, a quick search turned up http://man.hubwiz.com/docset/electron.docset/Contents/Resources/Documents/releases.html#0.16.0 which suggests that this was added to electron in 0.16 (6 years ago) and might not be configurable.  I haven't dug further than that, though.

**Comment by nathanlesage** [comment]
All windows created by an Electron application are browser windows, and this is the best possible description there is. I cannot alter this behaviour.

Hence, please open this issue on the Electron GitHub repository, not here.
