### ISSUE TITLE
problem on math render error

### ISSUE THREAD

**Issue by librix** [Zettlr/Zettlr#1504]
## Description

A rendering error is found when entering mathematical formulas. A cursory look at the code doesn't show any significant problems.

It is assumed that the rendering error for formulas with color is due to the fact that textcolor is not supported. However, the 
```latex
\displaystyle \sum ^{+\infty }_{n=1}( -1)^{n}\dfrac{1}{n\ln n}
```
rendering in [katex](https://katex.org/#demo) is normal, while rendering inside the zetlr software is not. So it is possible that the mathematical formula renderer called internally is incomplete.
## Reproducing

```latex
$\displaystyle \sum ^{+\infty }_{n=1}\textcolor[rgb]{0.74,0.06,0.88}{u}\textcolor[rgb]{0.74,0.06,0.88}{_{n}}$ 
具有两个性质，收敛或者发散。用以判断
$\displaystyle \lim _{n\rightarrow \infty } S_{n} \ $ 是否存在（ $\displaystyle \in \Re $），
$\displaystyle \lim _{n\rightarrow \infty } u_{n}$ 是否存在。
```

![image](https://user-images.githubusercontent.com/10742127/101591175-dadcbe00-3a26-11eb-968f-afd7e53f0f34.png)

## Expected behaviour

![image](https://user-images.githubusercontent.com/10742127/101591259-11b2d400-3a27-11eb-9385-65d304411e0c.png)

## Platform
 - OS and version: windows 10 2004
 - Zettlr Version: 1.8.1

**Comment by nathanlesage** [comment]
Entering the formula you provided works as expected:

![image](https://user-images.githubusercontent.com/17251683/102015479-27dccf00-3d5c-11eb-89c3-cb6b765a8b9c.png)

However, some styles are still unsupported by KaTeX, and the red font colour is the necessary indicator that there seems to be something off. Improving or customising KaTeX is out of scope for Zettlr, but feel free to provide a simple, maintenance-less PR that fixes this issue, if this is possible.
