### ISSUE TITLE
Editor loses focus after creation of a new file / change of tab

### ISSUE THREAD

**Issue by puldzian** [Zettlr/Zettlr#1506]
## Description
After creation of a new file, editor loses focus (or just cursor does not appear?).
Somehow ctrl+l still works, so the ID can be added, just no other input is possible until I click LMB inside the editor.

## Reproducing
Create a new file by ctrl+n or a toolbar icon, then try to write something. 

## Expected behaviour
In past, I clicked ctrl+n, changed the title, then ctrl+l to create ID and it worked great. 
Now this flow is broken by the necessity to 're-focus' the editor.

This might be somehow related: I don't remember how it worked before, nevertheless, now I have to click the editor for cursor to appear after changing tabs.

## Platform
 - OS and version: Ubuntu 20.04.1
 - Zettlr Version: 1.8.1

## Additional information
Thank you for Zettlr! :+1:

**Comment by Himra** [comment]
I have the same Problem on WIN10 and Version 1.8.2

Thank you for Zettlr

**Comment by nathanlesage** [comment]
Will be fixed in next release
