### ISSUE TITLE
Font zoom is forgotten on restart

### ISSUE THREAD

**Issue by deobald** [Zettlr/Zettlr#1507]
## Description

After closing and re-opening Zettlr, the zoom setting is completely reset.

For those of us with eye damage who require a large font size, this essentially means reconfiguring the app on every start.

## Reproducing

1. Open Zettlr
2. Zoom in as required for near legal blindess (`CMD-+` 6+ times)
3. Close and reopen Zettlr
4. Zoom level has returned to the app default

## Expected behaviour

After closing and reopening Zettlr, I would expect the app to remember the zoom level the user has chosen.

## Platform

 - OS and version: MacOS Big Sur 11.0.1
 - Zettlr Version: 1.8.1

**Comment by hueyy** [comment]
Not a perfect fix, but I think you can set a persistent font size via some custom CSS:

```css
body #editor .CodeMirror {
	font-size: 4em;
}
```

**Comment by nathanlesage** [comment]
In 2.0 you will be able to mitigate this by setting an explicit font size for the editor in the settings.
