### ISSUE TITLE
--- YAML Issue Resurfaces

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#1510]
## Description

Closed Issue #1378, where the --- YAML changes into table, reappear in Zettlr 1.8.1. However, this is not a consistent issue. While other files are alright, the others changed into table.

## Reproducing

Use --- as YAML front matter

## Expected behaviour

To work normally, if possible, to change back the table into YAML front matter

## Platform
 - OS and version: Windows 10 64x
 - Zettlr Version: 1.8.1

## Additional information

Thank you :)
I love Zettlr

**Comment by the-solipsist** [comment]
Hi, @shanvrolijk. As a workaround, you could use `...` as the closing delimiter instead of `---`.

**Comment by dialmove** [comment]
I've managed to reproduce the bug consistently in version 1.8.9 (and found a workaround to avoid it). There's a weird interaction between the Frontmatter and the Readability mode, which forces the YAML front matter to be recognized as a table.

Steps to reproduce:

1. Fill in a front matter on an empty file.
![image](https://user-images.githubusercontent.com/3824360/121874449-a87a8900-cd07-11eb-8aa0-cc1bcbe61b11.png)

2. Toggle readability mode. The last row and the '---' are highlighted in bold.
![image](https://user-images.githubusercontent.com/3824360/121874669-dd86db80-cd07-11eb-9fd3-1ffc365c5de8.png)

3.  Click inside the Front matter, and then outside of it. The front matter is turned into a table, with just the first three letters on each row.
![image](https://user-images.githubusercontent.com/3824360/121874898-19ba3c00-cd08-11eb-82cc-7b872842847d.png)

I've also found a workaround to avoid the bug. If you leave an empty row after the last attribute and before the final '---', the rows are not highlighted and the block is not converted to a table.

![image](https://user-images.githubusercontent.com/3824360/121875026-48381700-cd08-11eb-9c30-3a0c3217e0fe.png)

I know Nathan is busy with his PhD, I reopen this mainly to notify about the workaround for people who are suffering the problem.

**Comment by nathanlesage** [comment]
> There's a weird interaction between the Frontmatter and the Readability mode, which forces the YAML front matter to be recognized as a table.

Luckily, not anymore. In 2.0-dev I switched the underlying mode from a basic Markdown mode (incapable of detecting frontmatters) to the custom one we're using for the default rendering. So it won't happen in 2.0 anymore.
