### ISSUE TITLE
PDF export broken with 1.8.2 because of error in template

### ISSUE THREAD

**Issue by maciemesser** [Zettlr/Zettlr#1511]
With 1.8.2 the PDF export is no longer working for me. Error message is:

```
Error producing PDF.
! LaTeX Error: Environment CSLReferences undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.161 \begin{CSLReferences}
```

It seems the internal template uses "cslreferences" instead of the requested "CSLReferences". At least with a custom template based on https://github.com/Zettlr/Zettlr/blob/master/source/main/assets/export.tex and "cslreferences" replaced by "CSLReferences" it works without error message.

**Comment by nathanlesage** [comment]
Merged @Kangie's PR earlier this day, fix is building rn
