### ISSUE TITLE
Unable to conveniently download earlier version of zettler

### ISSUE THREAD

**Issue by piprrr** [Zettlr/Zettlr#1512]
Giving the problems some are encountering with zettlr such that it is impossible to open directories (see: #1461 ), I would like to install the earlier 1.7.x version in the hopes of restoring minimal functionality.  However, there does not seem to be a convenient way to do this.  Other software generally has a way of installing earlier version, and this would be useful for zettlr for just this kind of scenario.

**Comment by dalito** [comment]
Old releases are here: https://github.com/Zettlr/Zettlr/releases
You can also navigate to a specific release via https://github.com/Zettlr/Zettlr/tags

**Comment by nathanlesage** [comment]
See @dalito ! Thanks for the info.
