### ISSUE TITLE
Clicking on any hyperlink irreversibly opens the webpage in the Zettlr webview

### ISSUE THREAD

**Issue by hueyy** [Zettlr/Zettlr#1513]
## Description

Links open in the Zettlr webview rather than in an external web browser.

## Reproducing

1. Type any hyperlink, e.g. `[example](https://example.org)`
2. Left click it when it has been rendered by Zettlr
3. It opens in the Zettlr webview, and there is no way to return to the editor, access the menu, settings, etc.

## Expected behaviour

Open the hyperlink in the default external web browser.

## Platform
 - OS and version: Windows 10	
 - Zettlr Version: 1.8.2

**Comment by nathanlesage** [comment]
Hey, this was a regression by a stupid "up"grade of the link rendering. I partially reversed that now and it'll come with the next patch. Sorry for the inconveniences!
