### ISSUE TITLE
Changing options should rerender

### ISSUE THREAD

**Issue by tafli** [Zettlr/Zettlr#1515]
When saving options in zettlr after disabling display option 'render link' should trigger a rerender of the text. Currently the option does not take effect until I set the cursor on the rendered link and remove it from it again.

After enabling the 'render link' option and saving, a rerender of the links is done.

**Comment by nathanlesage** [comment]
For now it's too expensive to re-render those elements, which is why it has been disabled. You need to close and re-open a document after disabling rendering. I did not have any time yet to implement a good algorithm for this.

**Comment by tafli** [comment]
Fair enough. Though to report as is came to me while testing the broken link rendering issue.
