### ISSUE TITLE
[BUG] [1.8.2] Lines containing links rendered with line break

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1517]
## Description

When you have a line containing a markdown-formatted link (i.e. `[]()`), there is a weird line break when being rendered. See screenshots below.

## Reproducing

The screenshots below show some test cases to reproduce the behaviour:

**(1) Text before link**
Source:
![zettlr_link_1](https://user-images.githubusercontent.com/18646029/102068712-14ce0b80-3dfd-11eb-8d1b-eff7a5486d57.png)

Rendered:
![zettlr_link_1 1](https://user-images.githubusercontent.com/18646029/102068732-1bf51980-3dfd-11eb-8382-9ee6174e58da.png)

**(2) Text after link**
Source:
![zettlr_link_2](https://user-images.githubusercontent.com/18646029/102068802-37602480-3dfd-11eb-910c-47471e931057.png)

Rendered:
![zettlr_link_2 1](https://user-images.githubusercontent.com/18646029/102068825-3b8c4200-3dfd-11eb-9140-3100cf5cddc8.png)

**(3) Link inside text**
Source:
![zettlr_link_3](https://user-images.githubusercontent.com/18646029/102068921-5fe81e80-3dfd-11eb-8e10-ccafdbcd3391.png)

Rendered:
![zettlr_link_3 1](https://user-images.githubusercontent.com/18646029/102068942-66769600-3dfd-11eb-9ae7-88499fd1dd39.png)

**(4) Plain link**
Source:
![zettlr_link_4](https://user-images.githubusercontent.com/18646029/102069051-87d78200-3dfd-11eb-85d4-670e2b3ce613.png)

Rendered:
![zettlr_link_4 1](https://user-images.githubusercontent.com/18646029/102069061-8b6b0900-3dfd-11eb-807f-8d999516772d.png)

## Expected behaviour
No line break.

## Platform
 - OS and version: Ubuntu 20.04
 - Zettlr Version: 1.8.2

**Comment by michal-organek** [comment]
Same here.

- OS and version: Linux Mint 20
- Zettlr Version: 1.8.2

**Comment by kyaso** [comment]
Ok, there was already an issue for this: #1514

And it has been fixed!
