### ISSUE TITLE
Export error: "pandoc OpenBinaryFile: invalid argument (invalid argument)" when link to Citation Database is empty

### ISSUE THREAD

**Issue by Krande** [Zettlr/Zettlr#1518]
Hi,

after updating to v1.8.2 and to pandoc 2.11 (from 2.9) I encountered a "OpenBinaryFile: invalid argument (invalid argument)" error on export (I tried this for docx\pdf). The issue seems to go away when I add a citation database.

![image](https://user-images.githubusercontent.com/9642232/102086049-c712cc80-3e17-11eb-88cd-3ffc0b57d467.png)

I tried looking for any other recent issues that might cover this already (but I seem to have failed finding one!).

## Reproducing
Exporting either a single file or project seem to be impacted by this on the two machines I've tested on (both running windows 10).

Fails when citation databse is empty. When I add a csl json database it works.
![image](https://user-images.githubusercontent.com/9642232/102086347-3e486080-3e18-11eb-9911-0b979db57450.png)

## Platform
 - Windows==10
 - Zettlr==1.8.2
 - pandoc==2.11.0.2
 - pandoc-crossref==0.3.8.3

Let me know if there is anything else I can do to advance this issue!

Best Regards
Kristoffer

**Comment by nathanlesage** [comment]
Mitigation for now: Remove `--bibliography` from the command in the advanced preferences if you don't use it.

Mitigation for this and a few other issues, please see #1552. I want to focus my energy on that one instead, because it'll not just solve this issue but many others as well!
