### ISSUE TITLE
[FEATURE] AsciiDoc support (as well as other Lightweight Markup formats)

### ISSUE THREAD

**Issue by Mishco** [Zettlr/Zettlr#1520]
## Description

Hello, Zettlr seems great project and I'm going to give it a try.

Would you consider adding support for asciidoc?
https://asciidoctor.org/docs/user-manual/#what-is-asciidoctor

I am well aware that Markdown is currently the most used. Nevertheless it shows its limits really soon, even if most people are not immediately aware of it. Similar question was discussed on typora https://github.com/typora/typora-issues/issues/1771 

## Example Workflow

* Because you used pandoc I think there should be some way to use asciidoc as well.
* Maybe it can be some plugin for that purpose. 

## Caveats

I know it is `A Markdown Editor`... on the other hand, notepad++ also have multiple plugins for different languages. 

## Additional Information

Comparison:
* https://asciidoctor.org/docs/user-manual/#compared-to-markdown

Lightweight Markup: Markdown, reStructuredText, MediaWiki, AsciiDoc, Org-mode 
* https://hyperpolyglot.org/lightweight-markup

Thanks

**Comment by nathanlesage** [comment]
We had this issue already, so the short answer is: No.

The slightly longer version:

- Zettlr doesn't have a plugin system and I am not planning on implementing one soon.
- AsciiDoc has more stuff than Markdown, but if you know that you are exporting to PDF, for example, you can enhance Markdown with LaTeX, which gives you all the freedoms you need.
- Zettlr is targeted at non-technical Word users. Markdown is easier than AsciiDoc. Hence, Zettlr uses Markdown.

I concur with AbnerLee here that this is out of scope. If you need AsciiDoc specifically, there are specialised editors. Zettlr's use case is something different.
