### ISSUE TITLE
[ENHANCEMENT] Option to fully disable update popup.

### ISSUE THREAD

**Issue by cessen** [Zettlr/Zettlr#1521]
## Description

In issue  #1289 it was requested to only have the version popup get displayed when there's an actual update available.  I'd like to go a step further and have an advanced option to disable the popup entirely, for those who wish to.

## Caveats

People who opt-in to disabling the popup won't update as often.  But... that's probably what they want.

## Additional Information

The main reason I want this is because of the high frequency of releases.  If releases were only every 3 months or so, this wouldn't annoy me.  But within the last three weeks there have been as many releases, and getting a popup every time feels excessive to me.  If releases are going to be that frequent, I'd rather manually check the site every few months and skip the updates in-between.

I realize a small popup is not a *practical* impediment to users like me (it's just a small pop-up that doesn't get in the way), but it is a *psychological* impediment.  Pinging me to upgrade is like Facebook pinging me to check new postings: it's something I'm psychologically drawn to do, and so it creates a distraction that takes willpower to resist, when my intention in opening Zettlr was to get work done.

To clarify: I think Zettlr is a great piece of software, and I'm extremely grateful for the time you put into developing it.  And I'm not fundamentally against upgrade pop-ups.  But if they're gong to be frequent (which to me means more than once every couple of months), I would like to be able to opt out of them.

**Comment by nathanlesage** [comment]
Okay, first long story short: There were many, many issues demanding this in the past, and I always refused it for now; the only concession I was willing to make was what you describe – make it less obstrusive.

Furthermore, I am of the conviction that frequent updates are something good; plus an update is not Facebook, but rather something actually useful.

After I had the opportunity to think about that many times due to the frequency of these issues, I think the underlying main reason why I refuse to do this is because I'm afraid of too many issues opening up here from people who don't use the most recent version, so that it incurs more mental load on me if I have to tell those people to update first and then try it again.

To further clarify my problem: I even had an issue recently where someone apparently was unable to find the "releases" section here on the GitHub repository and opened an issue for this. This kind of small workloads is actually amounting to something that it feels insurmountable. Hence, my unwillingness to give up one part of reducing my workload.

In the end, what is missing are people I can rely upon to regularly screen the issues here and help me out with this kind of stuff – @Kangie for instance does this often, but as this is still voluntary, I feel that I shouldn't expect this to be a regular commitment.

So I'll leave this issue open for now for some discussion, now that I hopefully was able to express why I'm very unwilling to do this. But I am extremely open for any kind of support — especially when it comes to managing the issues here!

**Comment by cessen** [comment]
> I think the underlying main reason why I refuse to do this is because I'm afraid of too many issues opening up here from people who don't use the most recent version, so that it incurs more mental load on me if I have to tell those people to update first and then try it again.

I am *very* sympathetic to that, and I think that's a perfectly good reason to keep the update notification.  I'm happy to accept that until that situation changes, it's reasonable for you to refuse this.

I do want to make a final case, however, on the slim chance that I can change your mind.

> I am of the conviction that frequent updates are something good

For security-sensitive or otherwise critical updates, I 100% agree.  And I also think it's very reasonable to expect users to upgrade if/when they want support.  But otherwise isn't it up to the user whether it's good/useful for them or not?

I'm as much of a fan of new-and-shiny as the next guy, but ultimately probably 90% (or more!) of the software upgrades I do aren't actually practically useful to me, because they don't affect my use cases.  I just feel compelled to upgrade anyway, because of that voice in the back of my head that says, "Oooh, shiny!", ha ha.

> plus an update is not Facebook, but rather something actually useful.

I realized too late that this was perhaps a loaded comparison, which wasn't my intention.  I was just looking for something common and relatable.  I actually don't even use Facebook...

Maybe a better comparison would be real-time work-email notifications.  Or, in your case, getting a ping every time someone files a github issue. ;-)  Emails and github issues are also very useful, but in the typical case they're not *urgent*.  And when you're trying to get something else done they're psychologically distracting.

Having the ability to disconnect and focus is really important, IMO.

Another way to look at it is the college-professor-assigning-homework problem, which many students experience.  If each professor assigns homework as if their class is the only class the students are taking (which often seems to be the case), the students quickly get overwhelmed with too much homework.  Software is kind of the same way: Zettlr isn't the only piece of software I use.  If every piece of software gave me an update notification every week, I'd be getting multiple update notifications every day, which would be truly obnoxious.

> I think the underlying main reason why I refuse to do this is because I'm afraid of too many issues opening up here from people who don't use the most recent version

So, coming back to this.  Do you think it would really increase this problem too much to have an *option* to disable the notification, in the advanced tab?  Possibly with a prominent warning that only the latest version is supported?

My (admittedly not-supported-by-any-evidence) suspicion is that the people blindly filing issues without upgrading/searching are also likely the people that wouldn't think to look for that option.

Another way to address my concern would be to simply release less frequently.  Wait a couple of months, and roll all the changes into a bigger release.

Anyway, I'm very sympathetic to the issues you face as a maintainer, and won't push any further.  If you need to keep things as-is to keep your life sane, I'm 100% in support of that.  I'm *extremely* grateful for the time and effort you put into this wonderful project.

**Comment by cessen** [comment]
I have a workaround for Linux users.  However, anyone coming across this **please** read the thread above, so you understand @nathanlesage's situation, and your responsibilities around filing issues if you're not on the newest version of Zettlr.

To prevent the upgrade popup, you can create a launcher that starts Zettlr through [firejail](https://wiki.archlinux.org/index.php/Firejail) like so:

```
firejail --noprofile --net=none path_to_zettlr_executable
```

This denies network access to Zettlr, so it can't check to see if there's a newer version, which in turn prevents the popup.

Presumably there are similar workarounds on Mac OS and Windows, but I don't personally use those platforms so I haven't checked.

(As an aside: now that I'm aware of it, this also just seems like good security practice, denying network access to software that you only use locally.  Even software you trust can have bugs.  So I'm strongly considering making this the norm for me more broadly.)

**Comment by Kangie** [comment]
Just keep in mind you can use Zettlr to fetch remote content (i.e. images) by design, and thus workaround will break that capability.

**Comment by cessen** [comment]
Ah, that's a good point.  So, yeah, not a full solution at all, even aside from being Linux-only.

In my case, I only use Zettlr locally, and that's how I want it anyway.  I think the only extent to which I reference networked content is links, which open in a separate browser anyway.  But yeah, for people who use it differently, a proper option will likely still be desired.
