### ISSUE TITLE
[Feature Request] Choosing italic or bold formating characters

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#153]
As markdown supports both * and _ I find myself using only the * for **bold** and *italic* formating, because * is a character I hardly use in my writing as opposed to _. 
But when I use shortcuts (`Ctrl+I`) Zettlr uses _. It will be nice to have an option  in Preferences where you can choose the character to use _ or *. And also for unordered lists (+ or *). 

Thank you!

**Comment by nathanlesage** [comment]
This has been on my agenda already =D So rest assured

**Comment by samarulmeu** [comment]
Surprise after surprise. I can't wait for the new beta to emerge.

**Comment by nathanlesage** [comment]
It's gonna be tremendous, I think!
