### ISSUE TITLE
Rename directory doesn't work

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1533]
## Description
Renaming directory from context menu doesn't work

## Reproducing
- Right-click at directory's name in sidebar
- Choose a "Rename directory"
- Enter new name
- Enter

## Expected behaviour
Renaming directory

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.3

**Comment by nathanlesage** [comment]
Cannot reproduce locally, and this should not be dependant on the platform, iirc.

**Comment by dukebarman** [comment]
Additional information for reproduce. I found that renaming doesn't work when you have a sub-directory

![zettlr_renamedir](https://user-images.githubusercontent.com/1186777/102469438-d1290b00-4063-11eb-8934-467a6b654bc6.gif)

**Comment by crbald** [comment]
I can reproduce that with the additional info (Win10, Zettlr 1.8.3) (in all three file manager modes and when trying to rename the directory in the file tree and file list of these modes).

As long as the directory to be renamed has subdirectories renaming fails.
When it doesn't have subdirectories (or no longer does after deleting all subdirectories) renaming works (again).

**Comment by dukebarman** [comment]
Maybe "waiting for feedback" label remove too? Or you need more additional info?

**Comment by nathanlesage** [comment]
I just tested it out; it has been fixed during the TypeScript migration!
