### ISSUE TITLE
Wrong cursor placing in headers

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1534]
## Description
Cursor is higher than header's symbol

## Reproducing
Type `#`

## Expected behaviour

Cursor at same line with header's symbol

![image](https://user-images.githubusercontent.com/1186777/102375873-130a7080-3fd4-11eb-88ee-db75816feea4.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.3

**Comment by boutil** [comment]
I confirm this problem on Linux, with the Debian package. It appears on 1.8.1, 1.8.2, 1.8.3, but 1.8.0 does not exhibit this behaviour.

**Comment by Kangie** [comment]
Can replicate - Windows 10 (1.8.0; 1.8.3)

**Comment by nathanlesage** [comment]
Yeah, the problem is that headers have a different font size, and CodeMirror somehow refuses to refresh itself. But this behaviour is not only in 1.8, it basically has been from the beginning.

**Comment by nathanlesage** [comment]
Gnarf, I just googled, and there was an undocumented option buried within the CodeMirror codebase …

**Comment by dukebarman** [comment]
Nice, thx!

**Comment by dukebarman** [comment]
Was it fixed in 1.8.4? Because I have this bug again

**Comment by nathanlesage** [comment]
Yeah, we cannot completely make the cursor the right size everytime, and just have to live with this. Maybe only until we ship CodeMirror.Next, maybe forever. When it's fixed, it's fixed.

**Comment by dukebarman** [comment]
So have to reopen issue?

**Comment by nathanlesage** [comment]
No. There is nothing I can do and I will not keep un-fixable issues open here.

**Comment by dukebarman** [comment]
If it is bug in CodeMirror, maybe recreate an issue there?

**Comment by nathanlesage** [comment]
Please go forward. I don't have the time to test out theories and create an issue there. I have a lot of other stuff to do here.
