### ISSUE TITLE
Enter and Shift + Enter

### ISSUE THREAD

**Issue by Himra** [Zettlr/Zettlr#1535]
Hello all,

thanks for the great program

I noticed that there is no difference visually and formatting between Enter and Shift + Enter. I always use Shift + Enter when I need a line break within a paragraph or a line break when enumerating and I want to keep the indentation.
Enter I always use when I want to start a new paragraph (larger line spacing) or generate a new bullet point.

Maybe this can be integrated in a future version because this makes it much easier to read and format bullets.

Win10, version 1.8.3

greetings Himra

**Comment by Kangie** [comment]
That doesn't make much sense in a MarkDown editor. 

In MarkDown, a single line break is meaningless and basically for making long lines / paras more easily readable by humans, but are ignored when MarkDown is parsed. Two line breaks starts a new para, and Zettlr keeps track of indentation within lists etc.

**Comment by Himra** [comment]
How is the following problem solved then?
![grafik](https://user-images.githubusercontent.com/15324567/102607473-a654ba80-4128-11eb-91b5-586036fc46ae.png)

**Comment by nathanlesage** [comment]
Shift-Enter directs Zettlr to not perform any action, just add the line break. This is consistent with a lot of apps, even messenger services, where the default Enter-action would not be to insert a newline but rather send the message.

The specific use-case you're describing would require to hit Shift-Enter and then indent the line. Additionally, you will need to use a monospaced font, e.g. with the Bordeaux or Bielefeld theme. So this is to be expected.

**Comment by Himra** [comment]
Hello nathanlesage,

Thanks for your reply and the great program.
Like most, I have tested many Markdown editors, and got stuck here because it supports the "Zettelkasten" function brilliantly simple. 
In all the programs I tested, indenting with Shift-Enter was preserved and numbering was not incremented until an Enter.
Please try it yourself with any editor, it is very helpful.
At the moment I use Nextcloud and Typora in parallel, where it also works. Also this function is implemented in every text processing program like MS Word or Libre Writer and therefore almost a standard when working with enumerations.
Maybe you can consider this in a later version. From my point of view it would simplify things and make them clearer.

Thanks for your patience and great work.

Many greetings Himra

**Comment by Himra** [comment]
Attached is a small GIF file to illustrate my problem.

![test](https://user-images.githubusercontent.com/15324567/109143306-2a967000-7760-11eb-84ab-903743562b11.gif)

The first part shows the behavior of Typora, Nextcloud, etc. the second part shows the behavior of Zettlr

Thanks for the great project
HimRa

**Comment by nathanlesage** [comment]
Well, yes, the "benefit" of Typora is that it immediately renders everything, so they have another perspective on Markdown that allows them to perform different actions on your documents as Zettlr. Zettlr treats your files more like source code and less like a WYSIWYG-document. See on this [the corresponding documentation](https://docs.zettlr.com/en/concepts/wysiwym/).

**Comment by Himra** [comment]
Hello @nathanlesage 

I agree with you, but from my point of view it contributes considerably to the clarity of the entered text, if the indentation is preserved.
Since one also reads the notes, it is certainly not wrong to improve something about it.
Basically I would like to replace Typora by Zettlr, just because of the great Zettelkasten function and I think this goal has not only me, when I read here under the issues so.

Just consider it as a suggestion, maybe this suggestion will be considered in a later version. 

Thank you for your work so far and the great project.
@Himra
