### ISSUE TITLE
pandoc: $: openBinaryFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by Yo9458675483** [Zettlr/Zettlr#1537]
Hi everyone!

I just updated Zettlr to the newest version (1.8.3)

Then everything became super slow, I can't even write. Then when trying to export I got the same error:

pandoc: $: openBinaryFile: does not exist (No such file or directory)

I went to the FAQ and it says to run which pandoc to fin the directory and to paste it in my advanced preferences.

Terminal gives me this: /usr/local/bin/pandoc

I tried copying the link but still not working.

I also updated pandoc via brew and it says it's up to date.

I work on MacOS version 11.1

Could you help me please? (I know the issue exist already but I don't understand so sorry, don't know coding at all :S)

## Platform
 - OS and version: 11.1
 - Zettlr Version: 1.8.3

**Comment by FlashBlaze** [comment]
Can you provide screenshot of the Advanced tab as well as the pandoc command?

**Comment by lwb52** [comment]
I have identical issue(s) in OSX10.14.6 after recent install of Zettler, etc.—no <export.tmp> file is created in attempting PDF (or other) export:
![Screen- 2020-12-19 at 12 20 55 AM](https://user-images.githubusercontent.com/22728371/102684772-56114300-4190-11eb-97dc-3552630dcb6c.jpg)
Pandoc & (xe)latex both installed at bog-standard locations: </usr/local/bin/pandoc> and </Library/TeX/texbin/xelatex>

**Comment by hssofina** [comment]
Hello,
I have the same problem the last days and had only found hints from 2018 for export problems.
I have exactly the same problem on 11.x and 10.x on three machines after the upgrade to 1.8.2 / 3. I did a fresh install on the third device via homebrew and 'manually'.  Always the same problem.
When I look into the folder there is no export.tmp file there. So when there are helping hands... Thanks in advance, Immo

**Comment by netwaif** [comment]
Hi,
same here on Win10 x64 with Zettlr 1.8.3.

![image](https://user-images.githubusercontent.com/17922998/102687093-e2515380-41ec-11eb-9668-511fff727cf5.png)
![image](https://user-images.githubusercontent.com/17922998/102687100-ee3d1580-41ec-11eb-8c82-0d8cf0aa61ed.png)

Thanks in advance!

**Comment by nathanlesage** [comment]
The `$citeproc$` variable has been deprecated in 1.8.3, and you have to reset the Pandoc command.

Go to Preferences -> Advanced -> and click the button next to the Pandoc command.

Also, make sure that Pandoc is at least version 2.11, otherwise exporting won't work as well.

**Comment by netwaif** [comment]
> The `$citeproc$` variable has been deprecated in 1.8.3, and you have to reset the Pandoc command.
> 
> Go to Preferences -> Advanced -> and click the button next to the Pandoc command.
> 
> Also, make sure that Pandoc is at least version 2.11, otherwise exporting won't work as well.

there is no "button" in the Windows version

**Comment by hssofina** [comment]
Hello,
I have pandoc 2.11.3. I just tried to reset also the command in preferences with no change.
Regards
Immo

**Comment by Yo9458675483** [comment]
Thanks you all for your responses. Finally, I fixed the problem by uninstalling pandoc and then reinstalling it again (via brew, because that’s the way I installed it initially)

In MacOS, you open terminal
Enter: brew uninstall pandoc
Let it process..
Then: brew install pandoc

Hope it helps!

**Comment by hssofina** [comment]
Hello,

thanks for the hint. I tried it but again:

File  not found in resource path

Regards
Immo

**Comment by nathanlesage** [comment]
If reinstalling fixed this, you might want to open an issue on the pandoc issue tracker, as this doesn't seem to pertain only to Zettlr alone.

**Comment by Chuhtra** [comment]
> The `$citeproc$` variable has been deprecated in 1.8.3, and you have to reset the Pandoc command.
> 
> Go to Preferences -> Advanced -> and click the button next to the Pandoc command.

The button didn't work, removing `--citeproc` manually did work. Emoji's weren't exported correctly though, but I am new to Zettlr so I don't know if it's irrelevant.

**Comment by nathanlesage** [comment]
> The button didn't work, removing --citeproc manually did work.

That's good to know — did the button do anything at all? If not, were there errors in the developer tools (activate debug with Preferences -> Advanced and then from the newly appearing develop menu)

**Comment by nathanlesage** [comment]
Further, if "The button didn't work, removing --citeproc manually did work.", then you have Pandoc <2.10 installed and should upgrade asap.

**Comment by Chuhtra** [comment]
>did the button do anything at all? If not, were there errors in the developer tools 

The button only brings back the `--citeproc` flag once I remove it, and does nothing if it already exists. I don't see anything in the Log or the Developer tools (only an error about fonts but that's probably irrelevant).


> Further, if "The button didn't work, removing --citeproc manually did work.", then you have Pandoc <2.10 installed and should upgrade asap.

Yeah, sorry for omitting the version details. I am on Zettlr 1.8.2 with Pandoc 2.11.1. I know Zettlr .3 is out, it's just seems that my repos haven't yet updated it.

**Comment by hssofina** [comment]
Hello,

first - thanks @ all for giving the hints.

I removed --citeproc also manually (Pandoc 2.11.3 on MacOS 11.1 and Zettlr 1.8.3) and got

Error producing PDF.
! Undefined control sequence.
<argument> @{} >{\raggedright \arraybackslash 
                                              }p{(\columnwidth - 4\tabcolsep...
l.346 ...mnwidth - 4\tabcolsep) * \real{0.19}}@{}}

yet.

Looking into the export folder there is still not the export.tmp.

Any hints?

Thanks
Immo

**Comment by nathanlesage** [comment]
> The button only brings back the --citeproc flag once I remove it, and does nothing if it already exists. I don't see anything in the Log or the Developer tools (only an error about fonts but that's probably irrelevant).

So the button does what it's told to. So it appears you still have Pandoc 2.10 or earlier installed.

**Comment by Chuhtra** [comment]
> So the button does what it's told to. So it appears you still have Pandoc 2.10 or earlier installed.

I wouldn't like to sound rude by any chance, but in the same comment I mentioned that I am using newer Pandoc than 2.10.

**Comment by nathanlesage** [comment]
This doesn't sound right — what does your full Pandoc command look like right now, knowing you're on Pandoc 2.11?

**Comment by Chuhtra** [comment]
I reinstalled the same version of Pandoc last night, and it appears to not show this behavior anymore. So I guess it might be a configuration error? I will keep an eye on it and come back to you.

**Comment by guybrush115** [comment]
Just upgraded to 1.8.3. This is what I encountered:

On reset default "advanced" pandoc command, got error:

`Unknown option --citeproc.`

When I removed --citeproc option, got error:

`Could not find bibliography file:
Error running filter pandoc-citeproc
Filter returned error status 1`

Everything worked fine on version 1.8.1.

My system:

- Linux Mint 20 Cinnamon
- pandoc 2.5
- Zettlr 1.8.3

**Comment by nathanlesage** [comment]
@guybrush115 You need to have Pandoc 2.11 installed for Zettlr 1.8.3

**Comment by briholt100** [comment]
> Hello,
> 
> I removed --citeproc also manually (Pandoc 2.11.3 on MacOS 11.1 and Zettlr 1.8.3).
> 
> It works yet!
> 
> Thanks
> Immo

Yes, when I removed --citeproc, I was able to export **however** my document would not properally format citations.  

Once I upgraded pandoc to 2.11 everything worked.

**Comment by the-solipsist** [comment]
I thought I'd add the below if it helps with debugging:

```
pandoc --version
pandoc 2.11.3
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.2,
citeproc 0.3, ipynb 0.1.0.1
```
I encounter this error despite:
* using pandoc 2.11.3
* resetting the pandoc command in the "Advanced" tab.
* uninstalling and reinstalling pandoc

This error goes away if I remove `-- citeproc` from the pandoc command in the "Advanced" tab.

**Comment by briholt100** [comment]
That is interesting.

 What was your process for uninstalling and installing pandoc?

And what kind of operating system are you using?

**Comment by the-solipsist** [comment]
>  What was your process for uninstalling and installing pandoc? 

~~~
sudo apt remove pandoc
wget -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.11.3/pandoc-2.11.3-1-amd64.deb
sudo dpkg -i /tmp/pandoc.deb`
~~~

> And what kind of operating system are you using?

Ubuntu 20.10.

**Comment by LacikaG** [comment]
I had the same issue:
pandoc: $: openBinaryFile: does not exist (No such file or directory)
I have resolved it by refreshing the Pandoc- comand in Settings/advanced. The trick was that I had to delete the text and the refresh button re-wrote the data.

**Comment by deerainw** [comment]
To my great disappointment, many people above have already clearly stated that their pandoc version is 2.11+, but the developer still repeatedly suggested that they should install the latest pandoc and closed this issue, which is not a problem-solving attitude at all.

I encountered the same problem, as shown below, my pandoc version is 2.11.3.2:

![image](https://user-images.githubusercontent.com/32661922/103530560-9d9f0b00-4ec2-11eb-8d43-767c9c38972b.png)

![image](https://user-images.githubusercontent.com/32661922/103530817-14d49f00-4ec3-11eb-8600-0eeca008a4f1.png)

**Comment by nathanlesage** [comment]
> To my great disappointment, many people above have already clearly stated that their pandoc version is 2.11+, but the developer still repeatedly suggested that they should install the latest pandoc and closed this issue, which is not a problem-solving attitude at all.
> 
> 
> 
> I encountered the same problem, as shown below, my pandoc version is 2.11.3.2:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/32661922/103530560-9d9f0b00-4ec2-11eb-8d43-767c9c38972b.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/32661922/103530817-14d49f00-4ec3-11eb-8600-0eeca008a4f1.png)
> 
> 
> 
> 

The problem is the empty bibliography path. Has been fixed and will ship in 185. Please do some research among other issues and the forum before complaining.

**Comment by deerainw** [comment]
I'm not complaining about neither the export problem itself nor the project. When someone said that he already had the latest pandoc installed, you didn't believe him, that's the point.

**Comment by nathanlesage** [comment]
> When someone said that he already had the latest pandoc installed, you didn't believe him, that's the point.

Yeah, maybe because end of the year is always stressful and given that I have 200+ issues to tend to, I sometimes just don't have the mental energy to fully read all the comments of each issue.

**Comment by briholt100** [comment]
With as much gentleness that can be communicated through a chat in github, I hope you can all try to breathe and reflect that people are trying to do the best they can under the circumstances.  To try avoid characterizations, Accusations, and recriminations.  

There are lots of opportunities to get upset in talking about product, almost as many opportunities as the product could break.  

thank you all for your help in working on this issue.

**Comment by feekApp** [comment]
Same here, when running the following:

```
$ pandoc -v

> pandoc 2.11.4
> Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
> citeproc 0.3.0.5, ipynb 0.1.0.1
> User data directory: /Users/Feek/.local/share/pandoc or /Users/Feek/.pandoc
> Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
> This is free software; see the source for copying conditions. There is no
> warranty, not even for merchantability or fitness for a particular purpose.


$ pandoc -s -L pagebreak test.md -o test.docx

> Error running filter pagebreak:
> pagebreak: openBinaryFile: does not exist (No such file or directory)


$ pandoc -s -L /Users/Feek/.local/share/pandoc/filters/pagebreak.lua test.md -o test.docx

> "Pandoc is running OK, output as expected"
```

The lua filters are stored in User data directory `/Users/Feek/.local/share/pandoc/filters`

When pointing a full path to the filter, the filter is found and output is as expected. So it seems like the "User Data Directory" path is not well set.

**Comment by AtomicNess123** [comment]
I am having this issue. Can't export to PDF, I get the error: .
`pandoc: /Users/USER/path.to.file: openBinaryFile: does not exist (No such file or directory)`
I tried uninstalling Pandoc and installing it again via `Brew` in vane.
 Is there a way to fix this? Thanks.

**Comment by nathanlesage** [comment]
It should work by going into Preferences -> Advanced, and click the button next to the text field containing the "Pandoc command".

**Comment by AtomicNess123** [comment]
Yes, but what next? When I click nothing happens. What shall I change?
![image](https://user-images.githubusercontent.com/47029233/122120556-3ef79900-ce33-11eb-9608-776f14fb6b16.png)

**Comment by nathanlesage** [comment]
Mh, resetting the Pandoc command will make sure that that's not the cause of an error. Would you mind sharing the full Pandoc command here as well? There might be some issue with some character (I recently had someone using a folder with a question mark and that upset Pandoc)

**Comment by AtomicNess123** [comment]
Thanks for your kindness. 
This is the full pandoc command:
`pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $bibliography$ $cslstyle$ $standalone$ --pdf-engine=xelatex --mathjax -o "$outfile$"`

**Comment by nathanlesage** [comment]
Hey, sorry, I forgot to mention that I mean the "full" command that is being shown alongside with the error message (where those things like "$infile$" have been replaced with some actual values)!

**Comment by AtomicNess123** [comment]
This is it:

![image](https://user-images.githubusercontent.com/47029233/122471262-b827f500-cfc7-11eb-8982-73f1e0a6abb1.png)

**Comment by nathanlesage** [comment]
Mh, the command is correct, so maybe some file path isn't correct within the file? Would you mind trying to export some file with ONLY text and no images, and see if that works? If so, then the error might probably be in your file.

**Comment by AtomicNess123** [comment]
> Mh, the command is correct, so maybe some file path isn't correct within the file? Would you mind trying to export some file with ONLY text and no images, and see if that works? If so, then the error might probably be in your file.

Thanks, it was all because of images! I guess Zetterl does not work well with copypasted images from the clipboard.

**Comment by nathanlesage** [comment]
Well, judging from your comments, I infer that the images were displayed correctly in the document, right? After all, the main problem especially with characters like `?` and `#` is that they work for local files, but for URLs they have a special meaning, and so it can always be that something doesn't quite work if local files contain these characters. But that's true for anything where you can supply either a web-address or a local file.

**Comment by AtomicNess123** [comment]
Yes, they were correctly displyed in the document. Thanks for your help!
