### ISSUE TITLE
Window position/size is not updated in window_state.json and window_state.json is ignored on startup

### ISSUE THREAD

**Issue by tordeu** [Zettlr/Zettlr#1538]
## Description

Starting with a fresh Zettlr config (I used AppImage x64 and removed ~/.config/zettlr), Zettlr will write the correct main window position and size to window_state.json, it will also store if the window was maximized. However, Zettlr starts maximized every time and ignores the data in window_state.json. Additionally, the file is never updated after the initial created. The modification time does change, so it is probably written every time Zettlr closes, but the content does not change.   

## Reproducing

- Delete ~/.config/zettlr/window_state.json (path depends on OS), start Zettlr, change window size, close Zettlr.
- See content of window_state.json
- Start Zettlr again. It now starts maximized, desprite the contents of window_state.json.
- Move it to a different posiiton and resize it to a different size than first time and close it again.
- See that the modification time of window_state.json changed, but the content did not desprite closing it at a different position and with a different size than the first time.

## Expected behaviour

- Zettlr should write the current position/size to window_state.json when it's closed
- Zettlr should load the file at start up and initialize the main window with the position and size of that file  

## Platform
 - OS and version: OpenSUSE Tumbleweed
 - Zettlr Version: 1.8.3 and current master (commit e1dac6d, 2020-12-15 20:38:17)

**Comment by nathanlesage** [comment]
Cannot reproduce this locally. I checked the code and there isn't a logical error either, so I don't know why this happens.
