### ISSUE TITLE
Zettlr freezes when trying to activate pt-BR dictionary

### ISSUE THREAD

**Issue by kemelzaidan** [Zettlr/Zettlr#1539]
## Description
Every time I try to activate the Brazilian Portuguese dictionary, Zettler freezes. CPU usage sparks to 100% or more.

## Reproducing
I tried installing the pt-BR dictionary from https://github.com/wooorm/dictionaries/tree/main/dictionaries/pt (this github repository is on the Zettler documentation). I just downloaded the dictionaries created the pt-BR folder inside the right directory and renamed the dictionaries to `pt-BR.dic` and `pt-BR.aff` but when trying to activate them on the Zettlr preferences makes the whole software to freeze and one of the CPUs to spark to a 100% usage.

## Expected behaviour
I expect the spell check to work for this language

## Platform

``` sh
$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"
```

 - Zettlr Version: I'm using Zettlr 1.8.3 from AppImage package

**Comment by nathanlesage** [comment]
Hey, this is a bug in the nspell library, it's known and it's being worked on, but there's nothing I could do at the moment. Workaround until this is fixed: Don't use pt-BR. I know, not a good workaround, but that's unfortunately how it is right now.

**Comment by kemelzaidan** [comment]
Can you please send the link to this bug?

**Comment by GCBrito** [comment]
Any progress on the bug? Portuguese dictionary still won't work.

**Comment by nathanlesage** [comment]
@GCBrito Please see this repository for that: https://github.com/wooorm/nspell

**Comment by davisonajr** [comment]
I'm having the same problem... I get excited with Zettlr but how cannot i use it to write text in my language? It seems useless at all for me now!

**Comment by davisonajr** [comment]
Guys.... I a kind of solved it by using the IME of USP (Instituto de Matemática Aplicada da USP) .dic and .aff files. I don't know how good this dictionary is but at least it doesn't craches Zettlr.

here the link to download the files:
https://www.ime.usp.br/~ueda/br.ispell/pt_BR.zip

**Comment by davisonajr** [comment]
So, I realized that the .aff of nspell that crashes the system. I mixed the .dic file of nspell with the .aff of IME and it seems to work perfect now!
The .dic file of .IME is very old, so maybe mixing the files is the best solution so far.

**Comment by davisonajr** [comment]
The files I'm using are in this repo:

[(https://github.com/davisonajr/zettlr_pr-BR_files)]

if we get the blocks one by one of nspell .aff file, we can find which line is crashing Zettlr.

**Comment by davisonajr** [comment]
So, I removed ênclises and mesóclises from .aff file and it worked for me...
It seems latin languages are too refined for these app.

My current version os dictionary is available on:
[](https://github.com/davisonajr/zettlr_pr-BR_files)

In the future, I want to return some ênclises to see how far it can go...

**Comment by vict0rg** [comment]
For me the files at https://www.ime.usp.br/~ueda/br.ispell/pt_BR.zip partially worked. Accented words like "is" are marked as an error.
The dictionaries in
https://github.com/davisonajr/zettlr_pr-BR_files does not crash but does not work and everything is shown as an error

What worked for me in Zettlr 2.1.1 was the dictionaries at https://addons.mozilla.org/en-US/firefox/language-tools/ and clicking the link to "https://addons.mozilla.org/ en-US/firefox/addon/corretor/", or directly downloading and extracting the pt-BR Firefox dictionaries from the link https://addons.mozilla.org/firefox/downloads/file/1176165/brazilian_portuguese_dictionary_new_spelling-65.2018.12.8. xpi
