### ISSUE TITLE
HTML export problems with mathjax and citations

### ISSUE THREAD

**Issue by annargrs** [Zettlr/Zettlr#154]
## Description

HTML export of Tex equations and Zotero links doesn't work.

## Reproducing

1) Sample tex formulas: 

  ```
  Inline formula: $E = mc^2$, and a stand-alone formula:
  
  $$E = mc^2$$
  ```

2) Add a ref to a CSL Json file

## Expected behaviour

Mathjax math output for formulas, formatted citation and bib entry in the end of the file for citations.

**Screenshots**

This is how formulas and CSL Json file links are rendered in Zettlr:

![image](https://user-images.githubusercontent.com/1450322/56147776-d375c080-5f76-11e9-9ac7-a812f5bede1d.png)

And this is how they get exported to HTML:

![image](https://user-images.githubusercontent.com/1450322/56147818-f607d980-5f76-11e9-8d16-830de5f87e24.png)

## Platform
 - OS: Ubuntu
 - OS Version 18.04
 - Zettlr Version 1.2.3

**Comment by nathanlesage** [comment]
Same problem as #142 , so it'll be addressed at the same time. It's basically a switch in the exporter!

**Comment by nathanlesage** [comment]
There you go!
