### ISSUE TITLE
[FEATURE] ARM64/AARCH64 build for Linux / Raspberry Pi 4 & 400

### ISSUE THREAD

**Issue by woworiven** [Zettlr/Zettlr#1543]
## Description
Ubuntu Destop has released a 64-bit distro for Raspberry Pi 4/400. It would be great to run this on the ARM64/AARCH64 architecture. I have seen it compiled elsewhere for ARMHF, but that hasn't been a public release, and it wasn't compiled for ARM64. AppImage or deb?.

**Comment by woworiven** [comment]
Incidentally, I tried compiling after modifying package.json, but the build failed for Linux / arm64:

> An unhandled rejection has occurred inside Forge:
> [Error: ENOENT: no such file or directory, stat ''] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'stat',
>   path: ''
> }
> 
> Electron Forge was terminated. Location:
> {}
> error Command failed with exit code 1.

**Comment by nathanlesage** [comment]
You have to manually run the `./scripts/get-pandoc.sh linux`-command so that packaging works. The installer right now expects this. But remember that only x64-binaries will be provided. Arm64 is not supported by Pandoc officially right now, and the installer expects the official Pandoc release for this. If you want to have ARM pandoc, please write your own script for this.

**Comment by woworiven** [comment]
OK. I'm new to Zettlr, though; just trying to get it working on my comp and able to keep updates current. 

Yes, I was able to build working AppImage by copying pandoc file from my install into ./resources. Appears working, but I am v new to Zettlr. 
Sounds like pre-built will not be possible until Pandoc officially has arm64 support.

Seems like it could be packaged in a deb w/o pandoc,  but indicating that as a dependency and allow apt to download what's needed (pandoc is in deb/ubuntu repos for arm64).

**Comment by nathanlesage** [comment]
Feel free to ship those builds until arm is fully supported by Pandoc, just shoot me a mail if you provide them so that I can list those on the official page, in case you some day want to help out!
