### ISSUE TITLE
Bug or feature ? Case-sensitive global search

### ISSUE THREAD

**Issue by jlnbdt** [Zettlr/Zettlr#155]
Hi,

According to the documentation, global search is case-insensitive.
Yet, if I use an upper case in the search field, global search is case-sensitive.

So, if I search for the word "Test", only notes which contains that exact string are found (ie: notes containing "test" aren't found). If I search for "test", notes containing "Test" _and_, of course, notes containing "test" are found.

I wonder if this behavior is a bug or a feature, because it's remind me the [smartcase](https://vim.fandom.com/wiki/Searching) vim's functionality. 

Thanks!

**Comment by nathanlesage** [comment]
*looks up the code*

*scratches head*

Aaaaalright. So here we immediately transform the whole content to lower case:

https://github.com/Zettlr/Zettlr/blob/master/source/main/zettlr-file.js#L491

And here a case-insensitive search is performed:

https://github.com/Zettlr/Zettlr/blob/master/source/main/zettlr-file.js#L517

Here for the OR-operators:

https://github.com/Zettlr/Zettlr/blob/master/source/main/zettlr-file.js#L555

So actually I have no idea why it wouldn't find files containing "test" if you search for "Test" o.o

But anyway, I wanted to work through the global search at some point (to make it even faster, more precise, give it more options, and, most importantly: finally do some syntax highlighting and autocompletion to the search field. So maybe it'll work then in the process? The search functionality is really old and originates in the first days of Zettlr, so it wouldn't surprise me that there are still some misbehaviours.

So to keep the issue list clean (I have a huge neurosis concerning emptying up lists) I'll close this issue for now, but of course this will be dealt with during the search rewrite :) It's one of my next projects either way!

**Comment by nathanlesage** [comment]
Oh wait, I just realised why it does that -- the search term is not transformed to lower case, I'll fix this quick so until the rewrite at least this works as expected =D

**Comment by jlnbdt** [comment]
Thanks for these explanations!
