### ISSUE TITLE
Internal linking .md [link](file) doesn't work like [link](file.md)

### ISSUE THREAD

**Issue by pcuci** [Zettlr/Zettlr#1553]
## Description
Re: https://docs.zettlr.com/en/academic/zkn-method/#internal-linking

`[other file](other-file)` - DOESN'T work

`[other file](other-file.md)` - works for both Ctrl+Click as well as just simple through clicking

## Reproducing
Import a `.md` project with 2 files (managed outside Zettlr)

e.g.:

`a.md`

```markdown
Hi
[other](b)
```

`b.md`

```
dummy content
```

## Expected behaviour

![image](https://user-images.githubusercontent.com/2169849/102962226-397c5000-449b-11eb-93fa-43484a817eb3.png)

## Platform
 - OS and version: Win 10 Version 1909
 - Zettlr Version: 1.8.3

## Additional information

Should also work for folder hierarchies, e.g.: `[other](subdirectory/b)` should link to and open `subdirectory/b.md` file (unlike `[[ ]]` which seems to link based on file name only)

**Comment by nathanlesage** [comment]
There is no bug in your descriptions. Regular Markdown link don't support magic, so you can't omit the file extension. Internal links focus on the file name (or the ID), that is right.

So I'm unsure whether I understand what your aim is.

**Comment by pcuci** [comment]
The default behavior in https://content.nuxtjs.org/ (Jekyll, and most other JAMstacks?) is to internally link without file extensions.

My aim is to manage a [wiki-like](https://github.com/deposition-cloud/wiki) repository of `.md` documents without a full-blown developer-focused setup, so that I can more easily engage with non-developer writers.

[Joplin](https://joplinapp.org/)'s UX is ok, however, the import/export flow is not idempotent, so it fails at allowing team-focused collaboration, which Zettlr mostly gets right except the ambiguous internal linking. My baseline for comparison is 
VS Code markdown editing tooling: https://marketplace.visualstudio.com/items?itemName=foam.foam-vscode (this particular one aggregates a bunch of 3rd party markdown extensions for a more integrated editing experience)

My hope is that I'll stumble across a knowledge-base system/tool that non-devs can handle and still be able to version the underlying data in git repositories. 😄

I expect contributors to update their tools as they become more involved with the projects we're collaborating on:

1. In the beginning, simply edit markdown files like most docs-focused websites out there, directly in GitLab/GitHub
2. To create new knowledge (go beyond simple edits), and engage in small/medium refactorings of the knowledge base, use a tool like Zettlr/Joplin or similar writer-focused editors: https://alternativeto.net/software/zettlr/ (I evaluated most of them, and Zettler seems to be a good match for this workflow because it works against the raw .md files directly, which is git friendly)
3. For heavy-duty cross-KB refactoring, use something like https://github.com/foambubble/foam and Code's global search and replace facilities etc. - a simple vscode setup could work for non-developers, though it's still a pretty steep learning curve...
4. Dump, analyse, refactor, query, sync (import/extract, in real-time?) and manage the entire knowledge set in a graph database like https://neo4j.com/ or https://www.elastic.co/fr/what-is/elasticsearch-graph (Joplin seems to bet on this idea but it's not mature yet, i.e.: wonky API on top of their SQLite design), my project's need is for knowledge to be versioned and DVCS'd so this would be a single person/team session-based workflow.

Hope this helps paint the need, I should be able to expand if you need more details.

Thx!

**Comment by nathanlesage** [comment]
Hey. Sorry for the late response. I won't implement this. Why? Because it's very confusing. Zettlr in and of itself is pretty much becoming a "work horse", and since you can, e.g., also link within a document or link websites, it's hard to differentiate a web-URL (which could also be as simple as `google.com`) from a Markdown link without the file name extension. For example, what should you do with `dev.local`? Is this a local domain by someone who doesn't want to type in `localhost:8000` all the time, or is it actually a file `dev.local.md`? In this regard, and given that Jekyll and other static site generators also support the more verbose syntax, it's easier this way.

But, if you STILL wanna do this, feel free to do a PR! It's certainly not impossible, I just think it's low-value right now. Hope that's okay! :)
