### ISSUE TITLE
OSX - how to "reset" the zettlr installation ?

### ISSUE THREAD

**Issue by 0gust1** [Zettlr/Zettlr#1554]
## Description
When installing Zettlr the first time, I did a bad manipulation and gave it the root directory of all my projects (numerous git-backed dev projects). It tried desesperatly to parses this enormous file-tree, and I had to kill it.

Now, each time I launch it, It has performance issues (even if I changed the root directory for notes) and CPU usage goes through the roof.
I tried to uninstall/reinstall but no luck. 

I think there is some database/internal working directory somewhere that I should kill to have a clean start.

## Reproducing

See above? Basically give Zettlr a too big workspace root.

## Expected behaviour

see above. 

## Platform
 - OS and version: OSX Mojave 
 - Zettlr Version: 1.8.3

**Comment by nathanlesage** [comment]
Yes, there is:

Here's how you safely clean out the app data:

1. First ensure that the application is closed (in some error cases, there is a "zombie" process, which you can close from within your Task Manager or Activity Monitor)
2. Make sure to optionally backup these files:
    - `stats.json` (your writing statistics)
    - `config.json` (the app settings — **this one you should delete because it contains the enormous root directory**)
    - `custom.css` (your custom CSS, if any)
    - `tags.json` (your colour-coded tags)
    - `targets.json` (your writing targets)
    - `user.dic` (your own custom dictionary)
4. Select everything in this directory and delete it.
5. Restart the application. Some of these files will be re-created.

The application data path is …

* … on Windows: `C:\Users\<your username>\AppData\Roaming\zettlr`
* … on macOS: `/Users/<your username>/Library/Application Support/zettlr` (open a Finder window, hold down "Alt" while opening the "Go"-menu, and click on the appearing "Library" entry)
* … on Linux: `/home/<your username>/.config/zettlr`

**Comment by 0gust1** [comment]
Awesome,

Many thanks to you for your time and your work ! 🙏 👏 🙇 

Maybe it could be a small paragraph somewhere in the docs (as your response is almost a doc and cover all the OSes) ? Give a sign if you need a hand.

**Comment by nathanlesage** [comment]
Yes, feel free to add this to the docs in an appropriate place -- the repository is at https://github.com/Zettlr/zettlr-docs, just edit files and submit a PR!
