### ISSUE TITLE
[ENHANCEMENT] Remove Color "Blue" for syntax-highlighting of code-snippets in Night-mode

### ISSUE THREAD

**Issue by YoungMahesh** [Zettlr/Zettlr#1559]
## Description
Cannot read the syntax of code-snippets on zettlr in the Night-mode if color of the syntax in blue

Here is the screenshot of code-snippet in python language
![color-syntax-problem-zettlr](https://user-images.githubusercontent.com/46471981/103062024-0210bf00-45d3-11eb-98f9-0dad58160010.png)
- In the first line it is hard to see number - **3000** from `num = 3000`
- In the second line, it is hard to see - **int()** from `num = int('3000')`

This problem is started occuring from Zettlr version - 1.8.0

## Proposed Changes
Remove/Replace color "blue" for syntax-hightlighting in Night-mode

## Platform
- OS and version: Ubuntu 18.04 (LTS)
- Zettlr version: 1.8.4

**Comment by nathanlesage** [comment]
There's some info missing -- I need the theme, Zettlr version, and whether you are certain that it indeed started to happen, and then from which version onward!

**Comment by YoungMahesh** [comment]
> There's some info missing -- I need the theme, and whether you are certain that it indeed started to happen, and then from which version onward!

This problem occurs in three themes - Berlin(default), Frankfurt and BieleFeld. when Night mode is ON
And as I stated earlier, it is started occuring from `Zettlr version - 1.8.0`, as this was not the problem with version 1.7.5

**Comment by nathanlesage** [comment]
Thank you, I'll have a look!
