### ISSUE TITLE
Can't delete file from virtual directory

### ISSUE THREAD

**Issue by jlnbdt** [Zettlr/Zettlr#156]
Hi,

## Description

Click on "Delete from virtual directory" does nothing.

## Reproducing

Just right click on a file which is in a virtual dir and select "Delete from virtual directory". Nothing happens.

## Expected behaviour

The file should be removed from the virtual directory.

## Platform
 - OS: Ubuntu 18.10 and Windows 10
 - Zettlr Version 1.2.3

Here is the content of a virtual dir I use for testing: `[{"name":"virtualdir","files":["/coucou.md"]}]`

**Comment by nathanlesage** [comment]
Thanks for reporting!

**Comment by nathanlesage** [comment]
There you go; one logical error and one stupidity were error removed =D

**Comment by jlnbdt** [comment]
Well done! Thanks again!
