### ISSUE TITLE
The highlight line with collapsed header doesn't work correct

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1561]
## Description

When you try to highlight a collapsed header, it auto unfolds and highlight header and part of header's paragraph

## Reproducing

1. Collapse a header's paragraph
2. Put cursor at the start of a line and press `shift+end`

## Expected behaviour

I was expecting a highlighted only header or at least a whole collapsed paragraph. 

![zettlr_select_header](https://user-images.githubusercontent.com/1186777/103079763-9126d280-45e5-11eb-8e60-6bb517008a1a.gif)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.4

**Comment by nathanlesage** [comment]
I'm not sure I understand what you try to achieve? Select only the header without uncollapsing it? If so, that's not possible.

**Comment by dukebarman** [comment]
It was a plan. But selected part of collapsed header's paragraph isn't good too
