### ISSUE TITLE
"Delete File" confirmation box not accepting mouse clicks

### ISSUE THREAD

**Issue by derwok** [Zettlr/Zettlr#1562]
## Description
On "Delete File" via file list context menu, the upcoming confirmation dialog does not accept mouse clicks on "OK" or "Cancel" buttons

## Reproducing
- In file list (left) open right mouse button context menu on a file
- Select "Delete File"
- wait for confirmation dialog try to click OK or Cancel

![image](https://user-images.githubusercontent.com/4393698/103088820-51171e00-45ec-11eb-963b-b87a48153735.png)

## Expected behaviour
Confirmation dialog should close and file should be deleted after click on OK (or not deleted on Cancel)

## Platform
 - OS and version: Ubuntu 20.04
 - Zettlr Version: 1.8.4

## Additional information
* Workaround possible via keyboard: Press ENTER key to confirm, ESC key to cancel
* If the same confirmation box is triggered via toolbar button (trash can) it works as expected
* The problem is reported under Linux. I double checked with Zettlr 1.8.4 under Win10 - no problem! Works as expected

**Comment by nathanlesage** [comment]
Sounds like a bug in the underlying electron framework. Please consider reporting that bug there.

**Comment by derwok** [comment]
Hhmm. while I understand your reasoning... (as it works on Windows, it cannot be Zettlrs fault)... 
But: Under windows the confirmation dialog looks like a Windows native dialog (not HTML/CSS themed!) while under Linux I see a HTML/CSS styled dialog. So it could be under your control.

More thinkings:
* Why is it working correctly via the trashcan toolbar icon? So Zettlr has one way that is working, one way that is not working... So it again seems under your control, I think?
* If I file a bug at Electron: "In Zettlr opening a dialog via Electron functionality is not working..." this will be closed quickly pointing me back to the Zettlr project, I fear
* If I file it without a reference to Zettlr, I fear I cannot provide enough context so they can reproduce it or that they understand what is not working

I have one more "suspicion"... The main difference between trashcan icon vs. context menu is... of course the context menu.
So, is it possible that there is some Z-order issue here? It maybe that the "disable background layer" somehow is on top if the confirmation dialog?

Last Question:
I opend the developer / debug "Inspect Element" before triggering the dialog.
Unfortunately when the confirmation dialog opens, the dark-grey disable background layer spans also across the "Developer Tools". So I cannot inspect the dark-gray area or the Z-order of the elements. Any idea how I could inspect the confirmation dialog?

**Comment by nathanlesage** [comment]
No, the confirmation dialog IS indeed native, I have no control over that. However, a few days ago I discovered an accidental error in the file deletion logic, but it's fixed in 1.8.4 for sure.

**Comment by nathanlesage** [comment]
P.S.: if the developer tools are covered by it, this is a sure indicator that the dialog is indeed native and not controlled by the Web UI, wouldn't you think? 😉

**Comment by puldzian** [comment]
The bug is still active in 1.8.4 (Ubuntu).
