### ISSUE TITLE
[Enhancement] The Gutter should not be the Text Selection Cursor

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1568]
## Description

The cursor changes a shape to select but a user cannot select lines

## Expected behaviour

This shape-changing without select ability misleads the user

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.4

## Additional information

![zettlr_select_zone](https://user-images.githubusercontent.com/1186777/103152103-b1958f00-4795-11eb-9184-167b4197d4f5.gif)

For example in another editor:

![vscode_select_zone](https://user-images.githubusercontent.com/1186777/103152100-acd0db00-4795-11eb-9169-e67a6b8db17a.gif)

**Comment by nathanlesage** [comment]
Possibly the simples bug fix ever. Don't ask me what took me so long…
