### ISSUE TITLE
Table editing in unusable

### ISSUE THREAD

**Issue by AndreiPashkin** [Zettlr/Zettlr#1569]
## Description
1. It's unclear how to invoke table editing controls (add row/column, remove row/column). I've found that they appear after pressing "readability view" which doesn't make a lot of sense.
2. Content of the table is fully or partially erased when I use table-editing controls.

## Reproducing

https://user-images.githubusercontent.com/4378647/103152098-a7739080-4795-11eb-9c67-284fddec99db.mp4

## Expected behaviour
1. There should be a clear way of making editing controls visible. In Dropbox Paper they appear when you are placing the caret within the table - I think that would be pretty intuitive.
2. Content of the table shouldn't be magically erased in any scenario.

## Platform
 - OS and version: Kubuntu 18.04
 - Zettlr Version: 1.8.3

**Comment by nathanlesage** [comment]
I'm not sure I fully understand what you mean …?

**Comment by AndreiPashkin** [comment]
@nathanlesage, could you be more specific?

**Comment by nathanlesage** [comment]
I don't quite understand what you mean by stating that invoking the editing controls is unclear – you have to move your mouse over the table, and then they'll appear, right?

**Comment by AndreiPashkin** [comment]
@nathanlesage, no! Watch the video - they only appear after I pressed "readability view".

**Comment by nathanlesage** [comment]
Ah, sorry, I have no excuse for why I missed that! That is indeed a bug – does this still occur with Zettlr 1.8.7?
