### ISSUE TITLE
[Feature request] Persistent files ordering

### ISSUE THREAD

**Issue by jlnbdt** [Zettlr/Zettlr#157]
Hi,

My notes' title always starts with the date (YYYY-MM-DD) and I like to display the most recent file at the top of the files list. But each time I launch Zettlr, I've to click on the little "AZ" icon to order my files in the desired way (and I've to do it for each subfolder).

I think Zettlr should remember this setting for a given folder and/or should propose to set a default mode in Preferences.

Thanks again :-)

**Comment by nathanlesage** [comment]
Duplicate of #121, it will be addressed soon! If you have any cool additional input, please provide it there! :)
