### ISSUE TITLE
Pressing Esc on the Overwrite? question when creating a new file overwrites an old file anyway.

### ISSUE THREAD

**Issue by ibbles** [Zettlr/Zettlr#1573]
## Description

Pressing the Escape key on the `The file <FILENAME> already exists in this directory. Overwrite?` dialog causes the file to be overwritten anyway, and all contents lost.

## Reproducing

- Hit Ctrl+N to create a new file. It can have any name, but remember it since we'll use it later.
- Write some text to the file, for example `Very important text.`.
- Close the file.
- Hit Ctrl+N again and type the same filename again.
- A dialog with the `already exists, overwrite?` question appears. Hit Esc on the keyboard.
- The file has now been emptied and is listed twice in the files list in the left side panel.

## Expected behavior

When asked to overwrite Esc should mean `don't` and the file should keep its contents.

## Platform

 - OS and version: Ubuntu 20.04.1
 - Zettlr Version: 1.8.4

## Additional information

Clicking Cancel on the `Overwrite?` dialog behaves the same way.

**Comment by nathanlesage** [comment]
Thanks for reporting! Confirmed and fixed.
