### ISSUE TITLE
File Import Crash

### ISSUE THREAD

**Issue by ajlewis2** [Zettlr/Zettlr#1575]
## Description

Click on "Import files" under File in the menu. The window comes up to select the file, but the program seems to have crashed and I am unable to choose a file, move through to navigate in the window, or close the program. 

## Reproducing

Click on "Import files" under File in the menu

## Expected behaviour

Import the file, view in editor.

## Platform
Linux Mint 20
Zettlr Version: 1.8.4
System: linux 5.4.0-58-generic (architecture: x64)

**Comment by cyannuremagik** [comment]
Confirming this, I have the same issue. 
Wanted to import a .txt file and the import kept on crashing. The file opened fine in any text file reader.
Same issue with a .md file which opened fine in other md file readers.

my work around was to copy paste content from the original documents into new zettlr files

Platform:
- Linux manjaro xfce 20.2
-  Zettlr: version 1.8.4 (from official AUR repo)
-  linux 5.4.0-58-generic (architecture: x64)

**Comment by ajlewis2** [comment]
Import still does not work. I click on Import File. Navigation window opens. Can't click on anything in the window. I have to tap ESC in order to close the navigation window. Only way to import is to copy and paste into a new document.

**Comment by nathanlesage** [comment]
Does this happen in 1.8.9 as well?

**Comment by ajlewis2** [comment]
Yes, it happens with 1.8.9. I just now notice that it also happens with Delete file.

**Comment by ajlewis2** [comment]
That makes me wonder if this has something to do with the file browser I use which is nemo -- in Linux Mint. I could try installing another file browser to see what happens.

**Comment by nathanlesage** [comment]
I don't think it has anything to do with the file browser, but could it be that this issue is related to #1645 ?

**Comment by ajlewis2** [comment]
Right, I just tried another file browser and no change there. And Yes it is related to #1645! I see that it is being worked on. I'll watch that thread. Thanks.

**Comment by nathanlesage** [comment]
Perfect, thank you for confirming! :)
