### ISSUE TITLE
Export via pandoc fails on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by AIBN60** [Zettlr/Zettlr#1579]
## Description

Exporting to any format fails; error can be reproduced. Couldn't find any similar issue in list :-/

## Reproducing

Error occurs with any format any time

## Expected behaviour

export PDF, DOC, TXT aso.

Error message:
![103237283-6e7b1d80-4947-11eb-9316-d745b959b245](https://user-images.githubusercontent.com/62201504/103288348-f6633500-49e4-11eb-909c-416f87514ea4.png)

## Platform
 - OS and version: UBUNTU 20.4 LTS
 - Zettlr Version: 1.8.4
 

**Debug Info (part)**
General Information
Zettlr Version: 1.8.4
.....
System: linux 5.4.0-58-generic (architecture: x64)
...
Node.js v12.18.3
Electron v11.1.1
Chrome v87.0.4280.88
v8 engine v8.7.220.29-electron.0
Zlib v1.2.11
OpenSSL v1.1.1
Current System Load
CPU Load: 0.75 %
Resident Set Size: 265.34 MB
C++ memory for JS Objects: 45.78 MB
Heap: 31.25 from 37.02 MB (Limit: 4194.05 MB)
Renderer flags
/opt/Zettlr/Zettlr
--type=renderer
--field-trial-handle=4473874597339068839,230464262735397459,131072
--enable-features=WebComponentsV0Enabled
--disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess
--lang=de
--app-path=/opt/Zettlr/resources/app.asar
--node-integration
--no-sandbox
--no-zygote
--background-color=#fff
--enable-spellcheck
--enable-websql
--disable-electron-site-instance-overrides
--num-raster-threads=4
--enable-main-frame-before-activation
--renderer-client-id=4
--no-v8-untrusted-code-mitigations
--shared-files=v8_context_snapshot_data:100
.......
PANDOC_PATH: /opt/Zettlr/resources/pandoc

## Additional information

**Installed** is **pandoc** 2.11.3.1

xxx@xxxx-desktop:/$ sudo find -iname pandoc
./opt/Zettlr/resources/pandoc
./usr/share/doc/pandoc
./usr/share/pandoc
./usr/bin/pandoc

**Installed** is **texlive** with all options and packages. **Xelatex** is installed as well as **xetex**

xxx@xxxx-desktop:/$ sudo find -iname xelatex
./usr/share/doc/texlive-doc/generic/e-french/test/XeLaTeX
./usr/share/doc/texlive-doc/xelatex
./usr/share/texlive/texmf-dist/tex/xelatex
./usr/bin/xelatex

=====

xxxx@xxxx-desktop:/$ sudo find -iname xetex
./usr/lib/python3/dist-packages/docutils/writers/xetex
./usr/share/doc/texlive-doc/xetex
./usr/share/texmf/fonts/misc/xetex
./usr/share/texlive/texmf-dist/fonts/misc/xetex
./usr/share/texlive/texmf-dist/tex/xetex
./usr/bin/xetex
./var/lib/texmf/web2c/xetex

**Pandoc Command** is unaltered:
pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ --citeproc --bibliography "$bibliography$" $cslstyle$ $standalone$ --pdf-engine=xelatex --mathjax -o "$outfile$"

**path** to pandoc or Xelatex is not altered (left to standard)

**Comment by Sherl0ck007** [comment]
can confirm on Windows 10, same error occurs when trying to export to pdf.

**Comment by nathanlesage** [comment]
The problem is the malformed `--bibliography ''`-part, see PR #1565 for that.

**Comment by AIBN60** [comment]
Ok, if you think this is the same issue. FYI: But I don't have this error in Ubuntu 18.4 LTS, although having the same pandoc, Zettlr, Texlive Installations and the same parameters. 

Anyway: I hope all will have a happy and better new year 2021 :-)

**Comment by nathanlesage** [comment]
> But I don't have this error in Ubuntu 18.4 LTS, although having the same pandoc, Zettlr, Texlive Installations and the same parameters.

But you probably have a CSL Library loaded …? The problem, if I see it correctly, is the `--bibliography`-part being empty (`''`)

But yeah, same to you! See you on the other side!
