### ISSUE TITLE
Other donation option

### ISSUE THREAD

**Issue by SolarDesalination** [Zettlr/Zettlr#1581]
Not a high priority issue, but wondering if the developer could create an account on Liberapay or Mollie or some other venue besides Patreon/Paypal.

Great software BTW!

**Comment by nathanlesage** [comment]
What would you recommend? I can't promise anything, but I might consider other alternatives.

**Comment by SolarDesalination** [comment]
https://en.goteo.org/ - based in Catalonia
Liberapay.org - based in France, uses Stripe or Paypal
https://www.mollie.com/en - based in NL, service fee model is per-transaction based

Also could post an Ethereum or bitcoin wallet for donations.

When you have time. I actually don't mind paying on Paypal as long as I don't have to sign up for their account. Many sites I can donate via paypal without setting up for an account, but for some reason on Zettlr's donate page it will not let me donate unless I create a Paypal account, which I refuse to do for data privacy reasons.

**Comment by nathanlesage** [comment]
> but for some reason on Zettlr's donate page it will not let me donate unless I create a Paypal account, which I refuse to do for data privacy reasons.

I didn't know that – but I am fully sympathetic to why you would not want this. But rest assured: Other people donate enough so I can uphold the server costs; until I've settled with a possibly other option, feel free to donate to other Open Source projects which might need funding much more than Zettlr needs. After all, we all benefit from that :)
