### ISSUE TITLE
The function to Redo and Undo doesn't work on Zettlr 1.8.4 

### ISSUE THREAD

**Issue by panaousisn** [Zettlr/Zettlr#1582]
I was editing a note, and when I attempted to **undo** by pressing ctrl+z, nothing happened. Clicking it from the Edit menu also did not do anything. This is a major bug.

**Comment by chiphogg** [comment]
FWIW, I'm on 1.8.4 as well, and Undo and Redo seem to work just fine.

**Comment by panaousisn** [comment]
I forgot to mention I am running it on Windows, and I discovered more keyboard shortcuts that do not work. Reverting back to 1.8.3 fixed it, so it is concentrated to the newest update.

**Comment by nathanlesage** [comment]
> 1.8.3 fixed it, so it is concentrated to the newest update.

This is an important information.

However: Duplicate of #1560
