### ISSUE TITLE
[ENHANCEMENT] Reduce contrast for checked items

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#1583]
## Description

Checklists are hard to read at a glance, because checked items appear identical to unchecked items (apart from the checkbox, of course).  If we somehow de-emphasized checked items, seeing what's "left to do" on a list would become much faster and more pleasant.

## Proposed Changes

This should affect only the display of checked-off items in checklists.  Granted, there are a wide variety of stylesheets!  But as long as it's easy to identify "content in a checked-off item" (an assumption I'm making), then I think we could handle this fairly naturally.

The simple implementation idea I'd suggest is to linearly interpolate between any colour and the background.  Suppose 0.0 means "identical to the background colour" and 1.0 means "unaltered foreground colour".  We know 1.0 is perfectly readable for all stylesheets.  I assume that no colour between 0.0 and 1.0 will clash with the colour scheme (this seems reasonable).  What I think we want is something that is _still clearly legible_, but also _clearly distinct_.  Off the top of my head: maybe 0.7 would be good?  It should be pretty easy to find a value that strikes a good balance.

> Actually, in thinking about this more: maybe you could just set the _opacity_ of the checked-off content to 0.7?

## Caveats

I cannot think of any caveats off the top of my head.  I don't think this would interact with other features.

## Additional Information

I use Zettlr not just for notes, but also for a daily journal and task planning at work.  Making checklists more at-a-glance-able would _supercharge_ my productivity!  :smile:

**Comment by chiphogg** [comment]
What do folks think of this idea?  It seems to me that it would be very useful, while not interfering with the fundamental philosophy of Zettlr to be as compatible as possible with "plain" markdown (since it only affects the way these items are rendered within one particular app, i.e., Zettlr).

**Comment by chiphogg** [comment]
I would still really love to see this feature.  I've had several additional months of heavy Zettlr usage, and I still think this would be a great improvement.

**Comment by nathanlesage** [comment]
Sorry for jumping in so late. I think we can do this by adding an additional class that strikes those through. Would require another display module …

**Comment by chiphogg** [comment]
Cool... I expect the strikethrough effect would work about as well as the fading suggestion.  Thanks for responding!

**Comment by nathanlesage** [comment]
So, finally in the codebase, coming with 2.0.

For those who don't like that, use the following CustomCSS:

```css
.task-item-done {
    text-decoration: none !important;
}
```

**Comment by chiphogg** [comment]
I have been using this in 2.0, and it is wonderful!  I'll post my `custom.css` for posterity:

```css
.task-item-done {
    opacity: 0.5 !important;
    text-decoration: none !important;
}
```

This adapts really nicely to both "normal mode" and "night mode".

![fade-light](https://user-images.githubusercontent.com/1819744/139869923-dca69f78-7914-4a0e-a42a-82b20f082391.png)


![fade-dark](https://user-images.githubusercontent.com/1819744/139869925-aaba912c-d9af-4dea-b6b6-9e75b70e00b1.png)

Thanks for fixing this!  It was well worth the wait.
