### ISSUE TITLE
Display Mode Formula

### ISSUE THREAD

**Issue by hadjiforce** [Zettlr/Zettlr#1588]
## Description
Not sure whether there is a limitation that display mode formula should appear as an inline formula until it has been rendered to PDF.

## Reproducing
Just use two dollars instead of one, and notice that the formula appears no different from the one, until having been rendered to PDF.

## Expected behaviour
That it would appear in display mode, without having to render the file to PDF.

## Platform
Ubuntu 20.04

## Additional information
I also noticed that after the upgrade that I had to delete my .config/zettlr directory in order for export to work correctly with the new pandoc-js settings.

**Comment by nathanlesage** [comment]
> That it would appear in display mode, without having to render the file to PDF.

That is, unfortunately, impossible with the current implementation of CodeMirror. However, Marijn is currently working on CodeMirror.Next, so once that hits stable, it should become possible. I don't really want to put too much more effort into the current editor instance and rather use that motivation to implement the next iteration. As this is a somewhat minor bug, I hope you understand that it's easier this way!

> I also noticed that after the upgrade that I had to delete my .config/zettlr directory in order for export to work correctly with the new pandoc-js settings.

Resetting the Pandoc command in the advanced preferences would've sufficed …
