### ISSUE TITLE
[Improvement] Remove duplicated found files

### ISSUE THREAD

**Issue by jlnbdt** [Zettlr/Zettlr#159]
Hi,

Let's say I put a note into 2 virtual folders. If I start a global search which found this note, it appears three times 
![Zettlr_2019-04-17_10-23-24](https://user-images.githubusercontent.com/6383095/56272180-79056d00-60fa-11e9-8671-86a8413b6e2d.png)
![Zettlr_2019-04-17_10-23-40](https://user-images.githubusercontent.com/6383095/56272190-7b67c700-60fa-11e9-950f-6af65b47f2a8.png)

The note should be found once, _or_ the virtual folders should be displayed in the search result.

Thanks again ;-)

**Comment by nathanlesage** [comment]
Sooo here you go! Piece of cake :)
