### ISSUE TITLE
Writing in Zettlr painfully slow

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#1591]
Got myself a new laptop and immediately installed Regolith Linux (basically Ubuntu). Installed the latest Zettlr.

Realized that writing is almost impossible with longer files (more than 2000 words, so not really huge). After some times, characters takes several seconds to appear.
I’ve try to set the watchdog option but it’s even worse. I’ve disabled the "update when file remotely modified" without success.

Quitting and restarting Zettlr fixes the issue for some tenths of minutes.

I have no idea how to investigate this.

(the laptop is brand new, with brand new OS and everything is uber smooth so it’s not performance problem)

**Comment by ploum** [comment]
correction: it doesn’t work after a restart. It’s just that I was briefly editing shorter files. So Zettlr is unable to edit no-tiny files in all circumstances.

It’s very strange.

**Comment by panaousisn** [comment]
I have been experiencing the same problem. Closing the app and re-starting it seems to fix it for a few seconds and then back to lag territory. I have no problems with very short files, but when a paragraph or file cross the 500 word mark, I experience major delays.

**Comment by ploum** [comment]
Yep, that’s exactly my symptoms. What is your system?

**Comment by ploum** [comment]
Ok, I’ve been using Zettlr with a top running next to it. When waiting between the key press and the display, Zettlr is using all the CPU it can.

**Comment by Agias77** [comment]
I have the same problem. I have a MacBook Retina (Early-16 / MacBook 9,1).

The slowness appeared with the last 2/3 versions.

Strangely enough, slowness also appears on short texts.

**Comment by tegularius-fr** [comment]
I have been experiencing the same behaviour recently. Kubuntu 20.10. Long lines (more than 500 chars) become pain at some point. And after the moment the line is more than 1000 chars (+\- 150-200 words) it is almost impossible to write something. CPU loads up to 102.3% at the moment.

**Comment by nathanlesage** [comment]
The reason is the multiplexer which performs A LOT of regex matches for the Syntax Highlighter. Remedification only works with a full rewrite of the whole rendering mode, which takes considerable amount of time, and I don't know when I'll have that …

**Comment by ploum** [comment]
Can we simply disable syntax highlighting as a workaround?

Le lun. 4 janv. 2021 à 00:05, Hendrik Erz <notifications@github.com> a
écrit :

**Comment by nathanlesage** [comment]
> Can we simply disable syntax highlighting as a workaround?

Yes, I thought about that, maybe I'm even able to integrate this in 1.9!

**Comment by Anamon** [comment]
As a temporary workaround, try enabling readability mode. The lag seems to disappear for me when it's turned on.

**Comment by nathanlesage** [comment]
Oh, btw, a fix has already been implemented for that matter! Closing this issue, the fix will be coming in the next days/week or something! Next release, in any case!
