### ISSUE TITLE
tag cloud offeres tags that retrieve no results

### ISSUE THREAD

**Issue by briholt100** [Zettlr/Zettlr#1599]
## Description

Possibly similar to #1275, my tag cloud offers tags that once clicked, there are 'no results'
## Reproducing

Open tag cloud
click on tag (eg., "#want")

## Expected behaviour

Either the tag shouldn't exist in the cloud, or it should retrieve some file. 

![zettle_tags_offering](https://user-images.githubusercontent.com/3466992/103715553-c59b7680-4f75-11eb-9bf1-e1498641486a.png)

![zettle_tag_output](https://user-images.githubusercontent.com/3466992/103715563-cb915780-4f75-11eb-84a2-2ad5776ae717.png)

## Platform
 - OS and version:  Linuxmint 18.3
 - Zettlr Version: 1.83

## Additional information

n/a

**Comment by saschalalala** [comment]
I also noticed this. I think it has to do with tags that have been created at some time but the related files have been deleted (For me it is the tutorial). This tag cloud surely isn't recreated on the fly but cached somewhere so it would be nice to have a cleanup functionality in the settings?

**Comment by nathanlesage** [comment]
It's different: The tag cloud lists *all tags* from everywhere. If the tag is listed, it is being used in there. However, the search for a tag is being done on a per-directory basis, so if no file within your current directory uses that tag, the search will obviously not return any files.

> This tag cloud surely isn't recreated on the fly but cached somewhere so it would be nice to have a cleanup functionality in the settings?

It is recreated on the fly, the files will register and deregister their files decentralised, and this works perfectly.

**Comment by saschalalala** [comment]
Hmm, then I'll have to look into this once more. I deleted the tutorial and I see tags like these that I don't use anywhere in my text base:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/3439311/104324923-54fdd800-54e8-11eb-9f50-6e249c61f1a5.png">

But perhaps I did something wrong when I "deleted" the tutorial files.

**Comment by teacher-brian** [comment]
Thank you for the attention.  I have a clarifying question about this 

>The tag cloud lists all tags from everywhere. 

What does 'everywhere' mean in this context?

**Comment by nathanlesage** [comment]
> What does 'everywhere' mean in this context?

Every single file that is being loaded into the app, so all files across all the loaded workspaces, plus standalone files, if you have some open.

**Comment by briholt100** [comment]
Hmm.  When you say "workspaces" I think Linux and it's concept of a
workspace, which leads me to interpret this as any file on my machine.

But I **think** you mean the workspaces created by the Zettlr app.  Is this
correct?


Brian Holt
16614 Stone Ave. North
Shoreline, WA 98133
206.915.4805

**Comment by briholt100** [comment]
So, This issue was solved when I went and deleted the Zettlr tutorial folder.  Once I did that, the extraneous tags disappeared.

**Comment by saschalalala** [comment]
> Hmm, then I'll have to look into this once more. I deleted the tutorial and I see tags like these that I don't use anywhere in my text base:
> 
> <img alt="image" width="854" src="https://user-images.githubusercontent.com/3439311/104324923-54fdd800-54e8-11eb-9f50-6e249c61f1a5.png">
> 
> But perhaps I did something wrong when I "deleted" the tutorial files.

Just a quick headsup: I also had 2 Zettlr versions installed, one still contained the tutorial data. After uninstalling the older Zettlr version, the tags disappeared.

**Comment by nathanlesage** [comment]
All tags should be gone if you close ALL workspaces and all open files. If your file manager tells you that nothing is loaded, this would prove that tags indeed are removed from the tag cloud when the corresponding files are unloaded from the app.
