### ISSUE TITLE
Import images

### ISSUE THREAD

**Issue by Jkbains** [Zettlr/Zettlr#16]
The documentation isn't very clear on how to import images into a file in Zettlr. I'm using a Windows PC for reference.

**Comment by nathanlesage** [comment]
Hey,

you import images the usual way you would do with any markdown document, meaning you have the following three options:

- Insert an image using a web-url (such as `http://www.domain.tld/your-image.jpg`)
- Insert an image using an absolute path (such as `C:\Users\user-name\Pictures\your-image.png`)
- Insert an image using a relative path (relative to the file, such as `../img/your-image.gif`)

In the end it would look like this in your file:

- `![Image Caption](http://www.domain.tld/your-image.jpg)`
- `![Image Caption](C:\Users\user-name\Pictures\your-image.png)`
- `![Image Caption](../img/your-image.gif)`

But thanks for the notice, I'll see to implementing a dialog that is easier to use.

**Comment by nathanlesage** [comment]
Docs update is underway and will come with version 0.17!
