### ISSUE TITLE
Math preview not working for single letter string

### ISSUE THREAD

**Issue by ijpulidos** [Zettlr/Zettlr#160]
## Description
The math preview/rendering is not working when the string it has to render contains only a single letter. It works with longer expressions.

## Reproducing
Just try with something like `$a$` and you don't get a rendering/preview of it.

## Expected behaviour
Zettlr should render it as any other LaTeX/math equation, 

**Screenshots**
You can see there how the z (`$z$`) is not rendered as a LaTeX expression but the gamma symbol (`$\dot{\gamma}$`) does.
![image](https://user-images.githubusercontent.com/2949729/56325472-ec799f80-6137-11e9-8357-f88ec0ba57aa.png)

## Platform
 - OS: Linux (ArchLinux with latest updates)
 - Zettlr Version 1.2.3

**Comment by nathanlesage** [comment]
And fixed, please make sure to check out the beta version to test this for bug-freeness!

**Comment by j-proc** [comment]
Just as a quick fix for anyone not looking to do beta right now, you can add a space after the single letter and it will work because a space isn't rendered anyways. 

I'll try the beta version at some point next week and report back. Thx for the fast fix!

**Comment by j-proc** [comment]
Works for me too.

**Comment by jakeoung** [comment]
How can I download the beta version? Although I tick receiving beta version on the preference, Zettlr says that I'm on the latest version.

**Comment by nathanlesage** [comment]
@jakeoung You‘re right, currently there‘s no beta version. I‘m still refining some features for the 1.3.

BUT I‘ll upload an Alpha version of it before I‘m off to the conference next week; please monitor Zettlr‘s twitter to see when!

**Comment by j-proc** [comment]
Using the build instructions on the dev branch worked for me. I suppose not
a beta, but that's what I tested.

**Comment by nathanlesage** [comment]
Yep, that‘s what will become the beta in a few weeks, when some of the last remaining bugs have been cleared ;)
