### ISSUE TITLE
[ENHANCEMENT] A way to open text files of any filetype and of any location, not just workspaces (incl. via double clicking the file)

### ISSUE THREAD

**Issue by mYnDstrEAm** [Zettlr/Zettlr#1600]
## Description
It would be very useful if one could (display and) open text files of any filetype (e.g. .xml, .log, .html, .desktop, no filetype, etc.) and of any location, not just workspaces.

Zettlr is really amazing and could be or become the best networked note-taking tool ahead of ([enhanced](https://giffmex.org/stroll/stroll.html)) TiddlyDesktop and (enhanced) Dendron and I'd like to replace my current text editor (mostly KDE's Kate) with it. With Kate one can quickly open such files via double click or by "Open With->Kate" or by "Open with kate" in KDE.
However, that would require it to be able to a) just as easily open b) any text file c) located anywhere on my computer.

## Proposed Changes
An option or default functionality to make Zettlr able to view and edit all files that contain text. Depending on the filetype on could use a different syntax than Zettlr's default Markdown.

The change could be as simple as commenting out [this](https://github.com/Zettlr/Zettlr/blob/f8b7662b9f400713775826608f21cdc2dadc3542/source/common/util/extract-files-from-argv.js#L34) line or wrapping it in a condition configurable in the settings.

For some files the original syntax of that filetype could be enhanced with Zettlr / markdown syntax / features such for links between documents. This would require using a larger library of syntax files. Here is one such library which is used by Kate: https://kate-editor.org/syntax/

It would also be good if it detected the filetype not just by file-extension but by e.g. "#!/usr/local/bin/python3.6" at the top of the file (this seems to work in the file-explorer of KDE, Dolphin). Btw I couldn't find a way to add "no file-extension" in the Advanced settings of Zettlr and opening a .json file after adding .json there didn't work.

## Caveats
See the parts about filetype syntaxes above. I currently get system.error.open_root_error when dragging files of other filetypes than those specified under Advanced into the left sidepanel and nothing happens if I select "Open with Zettlr" in the context menu of such files.

## Additional Information
I'm new to Zettlr. I already went through the [IDE guide](https://docs.zettlr.com/en/guides/guide-ide/). System is Debian10/KDE.

**Comment by nathanlesage** [comment]
Hey, thanks for the request, but I don't think this would be wise.

We will enable to open JSON and YAML files soon, but I think we must leave it with that (YAML and JSON are important for academic work). The main reason is that the main CodeMirror instance (= the text editor) is heavily modified to work with Markdown files and hence it would require some intervention to enable more file extensions.

But the bigger reason is that, to edit any text file, you should not use Zettlr, but rather, e.g., VSCode. If we would allow all file extensions, this would open the gates to a flood of issues that would tilt Zettlr much more into the direction of a code editor. Plus, it's some work that we cannot uphold and maintain here. Basically, it's extremely "out of scope", even though purely technical it would require the adaption of some dozens lines of code.
