### ISSUE TITLE
Allow escaping parenthesis for URLs/links

### ISSUE THREAD

**Issue by ijpulidos** [Zettlr/Zettlr#161]
## Description
As far as I can see, Zettlr doesn't have a way to escape parenthesis in URLs

## Reproducing
For example for the following link `https://en.wikipedia.org/wiki/Protein_Data_Bank_(file_format)` using the following markdown string `[pdb-formatted](https://en.wikipedia.org/wiki/Protein_Data_Bank_\(file_format\)` I don't get the correct link, the escaping backslashes are read as part of the string. If I lose the escaping backslashes ("\") I still don't get the last parenthesis.

**Note:** Encoding parenthesis with `%29` works, for example as in `[pdb-formatted](https://en.wikipedia.org/wiki/Protein_Data_Bank_(file_format%29)`, but I think it should work escaping with backslashes as well.

## Expected behaviour
I'd expect the escaping backslashes to work to help putting parenthesis in URLs in Markdown, as suggested in https://stackoverflow.com/questions/13824669/how-do-you-write-a-link-containing-a-closing-bracket-in-markdown-syntax

## Platform
 - OS: Linux (Archlinux with latest updates)
 - Zettlr Version 1.2.3

**Comment by nathanlesage** [comment]
I've got a better idea, which is included in attached fix: Simply drop in any link containing any character _except whitespace_. This way the regular expression will eat anything up to a closing bracket, as long as there's no whitespace in the URL (which it isn't supposed either way)!

**Comment by ph1-xyz** [comment]
I have this same problem, but I can't manage using the %29 workaround.

The image below is when I try to write
`[_Glider Gun_](https://en.wikipedia.org/wiki/Gun_(cellular_automaton))`

![immagine](https://user-images.githubusercontent.com/6156113/83970841-38594c00-a8d8-11ea-8d1e-8a486a720d57.png)

**Comment by nathanlesage** [comment]
The parentheses stuff will come in 1.7

**Comment by andreypz** [comment]
I am on v 2.3.0 (Linux Appimage)  but I think this still does not work. Was this really implemented?
