### ISSUE TITLE
I don't find export whole projects function 🤔

### ISSUE THREAD

**Issue by ShadowMax** [Zettlr/Zettlr#1611]
## Description
[Here](https://docs.zettlr.com/en/core/export/) you wrote:
> The second method to export files is to export whole projects. You can export a project by right-clicking the project directory, and choosing the export option.

I don't see this option:
![image](https://user-images.githubusercontent.com/10102994/103997485-90c93280-51b4-11eb-816a-523637fd2ddf.png)

I try to push this button, but programm not respond.
![image](https://user-images.githubusercontent.com/10102994/103997565-b22a1e80-51b4-11eb-865f-4f5703ac014a.png)

**I need Pandoc for it?**

**Comment by nathanlesage** [comment]
Look here:

![image](https://user-images.githubusercontent.com/17251683/104007025-953b1e80-51a7-11eb-9b27-0161bd4f5925.png)

And no, Pandoc ships with the released 1.8.5 version which I just released a few minutes ago.

**Comment by ShadowMax** [comment]
> Look here:
> 
> ![image](https://user-images.githubusercontent.com/17251683/104007025-953b1e80-51a7-11eb-9b27-0161bd4f5925.png)
> 
> And no, Pandoc ships with the released 1.8.5 version which I just released a few minutes ago.

Oh, I see. I think it was project already)

![image](https://user-images.githubusercontent.com/10102994/104016148-2376cb00-51cf-11eb-994f-f8505afe3010.png)
