### ISSUE TITLE
AppImage shows generic X11 icon instead of Zettler icon in KDE Plasma taskbar

### ISSUE THREAD

**Issue by thomond** [Zettlr/Zettlr#1612]
## Description
AppImage shows generic X11 icon instead of Zettler icon

![image](https://user-images.githubusercontent.com/2264685/104031260-6bdcbb80-51c4-11eb-9940-a24a08461dfa.png)

## Reproducing
Download the x86-64 appimage of Zettler and launch

## Expected behaviour
The taskbar to show the Zettler icon

## Platform
 - OS and version:
Operating System: Fedora 33
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.2
Kernel Version: 5.9.16-200.fc33.x86_64
OS Type: 64-bit

 - Zettlr Version: 1.8.5/1.8.4

## Additional information
I have so far not tested with RPM or on other platforms
No issue with Zettlr-1.7.5-x86_64

**Comment by nathanlesage** [comment]
Could be due to our Electron forge migration, if some of the contributors with a Linux installation could verify that, I'd be more than happy, because this might only involve some changes to the `forge.config.js`.

**Comment by mYnDstrEAm** [comment]
Maybe it only requires somehow [setting](https://github.com/nukeop/nuclear/pull/743/commits/aa1b334b91ffe3969f2c746bc60f15b31201cdcd) "icon": "./build/", (see https://github.com/electron-userland/electron-builder/issues/2577)

**Comment by thomond** [comment]
Closed this. It appears to be a limitation in AppImage more then anything else:

https://discourse.appimage.org/t/icon-on-a-shortcut/1639/2
