### ISSUE TITLE
Use Github Discussion to discuss about features 

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#1615]
In December 2020 Github introduced for general public their "Discussions" feature https://docs.github.com/en/free-pro-team@latest/discussions/quickstart

Adding this to the repository would be beneficial to the community, also it would lead for less issues to track for developers (and less burden for them).
 People could discuss Zettlr related issues and development that doesnt involve direct action.

**Comment by nathanlesage** [comment]
That's what the [forum](https://forum.zettlr.com/) is for. Most of the user target group are not on GitHub, so GitHub Discussion would be fairly exclusive, I think.

**Comment by danieltomasz** [comment]
You are right. Anyway I was also thinkining that some old issues  could be moved to Discussions (like UI discussions) but I dont see enthusiasm from anyone else than me so I admit that law of parsimony should be used here

**Comment by nathanlesage** [comment]
Alright!
