### ISSUE TITLE
File gets deleted after changing file name's capitalization

### ISSUE THREAD

**Issue by chrstnbwnkl** [Zettlr/Zettlr#1622]
## Description

When trying to rename a md file to the same name, but with a different capitalization of letters (e.g. from test.md to Test.md), the file gets deleted.

## Reproducing

Create a .md file with a name like "test.md", then change its name to the same file name but with different capitalization (e.g. "Test.md". Click ok for the warning that the file already exists and will get overwritten. Instead of overwriting the file, it gets deleted.

## Expected behaviour

Rename the file to the new desired name, internally overwrite the file instead of deleting it.

## Platform
 - OS and version: MacOS Catalina 10.15.7
 - Zettlr Version: 1.8.5

**Comment by crbald** [comment]
I can reproduce this (from uppercase to lowercase and the other way). The "Overwrite?" prompt appears and then the file is deleted.
Windows 10 1909, Zettlr 1.8.5

**Comment by nathanlesage** [comment]
Ouh, I know where this is coming from – thanks for reporting.
