### ISSUE TITLE
Version 1.8.5 files cannot be easily click and dragged into folders anymore

### ISSUE THREAD

**Issue by SolarDesalination** [Zettlr/Zettlr#1623]
## Description
In version 1.8.5 when I click and drag a .md file to a new folder using the combined tree mode the file does not move into the new folder.

## Reproducing
Using the "combined" view for files/folders; Create 2 folders, and one text file in one of the folders, drag the .md file into the other folder.

## Expected behaviour
Clicking and dragging a .md file into a different folder should place the file in that folder.

## Platform
 - OS and version: Linux Mint 20.1
 - Zettlr Version: 1.8.5

## Additional information
This used to work fine in the previously released version. Also to note the text size on Zettlr has shrunk considerably. It's actually not as nice IMO.

**Comment by nathanlesage** [comment]
Will have a look

**Comment by kalivas** [comment]
I am experiencing exactly the same issue on macos (intel). The expanded view drag and drop is not working, combined view works. In the previous version it was working just fine. I saw on the changelong that there were some improvements on the drug and drop system on the latest version, so I suspect it's a small bug that occurred during this change.

The Log is not showing something, the console shows an error but only when i switch from combined to expanded. Hope this helps.

**Comment by nathanlesage** [comment]
> so I suspect it's a small bug that occurred during this change.

You are right, and I just had a look at the code, I think I fixed both the non-working drag'n'drop behaviour on the file list as well as the somewhat laggy drag'n'drop in the combined mode, so it should work now!
