### ISSUE TITLE
[BUG]: Copy pasting from HTML has spaces eaten around links and formatting.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1624]
## Description

If text is copied from a HTML source and pasted into Zettlr, formatting and links are correctly handled, but any whitespace characters around them (i.e. between words) are gobbled.
## Reproducing

Copy text from the web (my example is from the CommonMark spec) and paste into Zettlr: 

Actual Text: 

A [list](https://spec.commonmark.org/0.29/#list) is a sequence of one or more list items [of the same type](https://spec.commonmark.org/0.29/#of-the-same-type). The list items may be separated by any number of blank lines.

Result:
A[list](https://spec.commonmark.org/0.29/#list)is a sequence of one or more list items[of the same type](https://spec.commonmark.org/0.29/#of-the-same-type). The list items may be separated by any number of blank lines.

The same issue occurs with emphasis `_` and strong `**` formatting - it is properly recognised, but the formatting replaces the spaces. I suspect that description is probably what is happening, but don't have time to dig into it now!

## Expected behaviour

Spaces should not be gobbled. :)

## Platform
 - OS and version: Win10 20.H2
 - Zettlr Version: 1.8.5/Develop

## Additional information

The regex fix seems to have greatly improved performance!

**Comment by nathanlesage** [comment]
Known bug, comes from the joplin-turndown plugin. The author is also aware of it, but I won't push them. Mitigation is: Don't use any Blink-based browsers (such as Safari or Chrome). Firefox works like a charm.
