### ISSUE TITLE
[FEATURE] Find files *not* containing internal links

### ISSUE THREAD

**Issue by marbetschar** [Zettlr/Zettlr#1630]
## Description

It would be great if there's a way to search for files, which do **not** contain any internal links. The reasoning: In the Zettelkasten method we are supposed to connect notes. If we do not connect notes, those thoughts are lost over time. But in practice, I sometimes don't have the time to explore my Zettelkasten for relations and just jot in some piece of information.

Therefore it would be great to easy re-find those notes to re-examine relationships to other notes. This would also be great to improve the overall quality of the Zettelkasten from time to time by making sure nothing falls through the cracks.

### Using Tags

I considered tagging those notes manually as a workaround. This way I could easily use the tag search feature to re-find the notes in question. Unfortunately I wasn't aware of this issue from the get go. Therefore there is no way to re-find the currently existing, non-linked notes. And to be honest, I guess I would forget to set the tag occasionally anyway.

But maybe the tag search option can be used for this kind of search by providing some sort of automatically assigned, always available "magic tag" (e.g. `w/o internal link`)

### Allow complex search terms

Another potential solution is to allow complex search terms. Things Google also allows when searching the web like:

- `-[[`
    - must not contain the string "[["
- `+[[`
    - must contain the string "[["
- ...

This might be overkill and is not very intuitive for beginners - but would enable a lot more use cases.

**Comment by kyaso** [comment]
If you happen to use Linux/Mac, for now, you can also use `grep` to search for files w/o internal links:

`grep -ELnr --include='*.md' '\[\[regex\]\]'`

- Replace `regex` with your ID regex, e.g., `[0-9]{14}` for the default 14-digit time string.

**Comment by cdaven** [comment]
I have been working on a tool for such things, and you are welcome to try it. You are probably referring to what I (and graph theory) calls "sinks", which is notes with no outgoing links, but at least one incoming link: https://github.com/cdaven/noteexplorer#list-sinks

**Comment by marbetschar** [comment]
@cdaven `noteexplorer list-isolated` works like a charm - thank you very much!!!
