### ISSUE TITLE
Update with .deb package possible only from command line, not working with Ubuntu Software

### ISSUE THREAD

**Issue by raphraph** [Zettlr/Zettlr#1631]
## Description
On Ubuntu (20.10) when trying to install Zettlr update with .deb package and default program (Ubuntu Software), the program does not run the update but instead act as if the update had already been done (it shows the update version number as the "installed version" and does not provide any **Install update ** action button).

Running manually `sudo apt install Zettlr-1.8.5-amd64.deb` performs the update without any problem.

## Reproducing

1. From Zettlr interface, follow instructions to download and install the update.
2. Ubuntu Software is launched and the update is not performed

## Expected behaviour
1. Ubuntu Software should propose to install the update

## Platform
 - OS and version: Ubuntu 20.10
 - Zettlr Version: 1.8.4

## Additional information
The problem exists since first version of Zettlr that I started using which was 1.8.1 and when I was on Ubuntu 20.04.

I have seen issues which seemed sort of similar (#1316, #1325 ) but were closed in reference to the fix of issue #1304. But the problem (minor I agree) does not seem solved.

**Comment by nathanlesage** [comment]
Puh, the main problem I think is that there is no Debian repository. I think this refers to the general fact that updates from Zettlr are pretty much handcoded, which is not the best method either way, but I am afraid of implementing the server side structure for driving updates :(
