### ISSUE TITLE
cannot export any file to word or pdf

### ISSUE THREAD

**Issue by legend053** [Zettlr/Zettlr#1632]
I re-install Zettlr 1.85 several times and the latest version of Pandoc, but always failed to export. Do I need to do some special settings?

![zettlr error](https://user-images.githubusercontent.com/7464388/104541307-fec38e80-55e6-11eb-92ff-87b0edeb4718.JPG)

**Comment by nathanlesage** [comment]
Two options:

1. Wait for 1.8.6, then the internal Pandoc should work perfectly
2. Until then (release is tomorrow), you can deactivate the internal Pandoc in Settings -> Export
