### ISSUE TITLE
citations cannot be generated in the exported pdf and word files

### ISSUE THREAD

**Issue by legend053** [Zettlr/Zettlr#1633]
I encountered this issue last year. But I still have this issue for zettlr 1.8.5. I can cite the paper and zettlr shows the references well inside the software. But I cannot export them. What should I do to solve this issue? Please advise. Thank you.

**- test document**

![zettlr citation issue_1](https://user-images.githubusercontent.com/7464388/104655929-113fd580-5684-11eb-9d41-80f7949fa8f8.JPG)
![zettlr citation issue_2](https://user-images.githubusercontent.com/7464388/104655932-11d86c00-5684-11eb-852a-45128f4c73dd.JPG)

**- export pdf file**

![zettlr citation issue_3](https://user-images.githubusercontent.com/7464388/104655934-11d86c00-5684-11eb-9d10-6a0da38cfc71.JPG)

**Comment by nathanlesage** [comment]
What does your Pandoc command say? (Settings -> Advanced -> Pandoc Command)

And, what's your system? (Platform, etc. – those templates aren't there for fun)

**Comment by legend053** [comment]
Thank you.

My system is Windows 10 Pro.

Pandoc Command shows: pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$
$tocdepth$ $bibliography$ $cslstyle$ $standalone$ --pdf-engine=xelatex
--mathjax -o "$outfile$"

Sean

**Comment by nathanlesage** [comment]
Thank you for pointing me to the thing — I had a look at the source code again and found a nasty bug that would render ANY citation rendering impossible! Fixed now!
