### ISSUE TITLE
Missing icons in 1.8.6 deb

### ISSUE THREAD

**Issue by nistude** [Zettlr/Zettlr#1637]
## Description

The 1.8.6 deb does not install proper application icons. There is only /usr/share/icons/hicolor/0x0/apps/Zettlr.png instead of one file per resolution.

## Reproducing

Install the 1.8.6 deb on linux.

## Expected behaviour

The deb should install one properly scaled icon to all the different subfolders of /usr/share/icons/hicolor as 1.8.5 did and other previous versions did.

## Platform
 - OS and version: Debian testing
 - Zettlr Version: 1.8.6

**Comment by nathanlesage** [comment]
This might relate to this change here: https://github.com/Zettlr/Zettlr/blob/develop/electron-builder.yml#L65

Previously, it was like this: https://github.com/Zettlr/Zettlr/blob/v1.8.5/package.json#L99

Could someone please verify, so that I can publish a hotfix on the 1.8.x branch to fix this before I finally let 1.8 be and focus on 1.9? That would be great.

**Comment by kb173** [comment]
Changing it to `icon: "./resources/icons/png"` indeed made the icon appear correctly again!

I opened a PR in case it helps: https://github.com/Zettlr/Zettlr/pull/1643 (it's my first PR here, so please let me know if I did something wrong!)

**Comment by nistude** [comment]
Thanks @kb173, I can confirm that your change creates a deb including the missing icons.

**Comment by nathanlesage** [comment]
Perfect, gonna take a look at it right now!

**Comment by nathanlesage** [comment]
Alright, looks perfect, we just need it in the master branch in this particular case (because I committed non-working changes to develop because I just started a very huge project on develop – yes, I didn't plan correctly, it's my fault :D)

**Comment by kb173** [comment]
Haha, no problem! I re-opened the pull request to the master branch: https://github.com/Zettlr/Zettlr/pull/1649

**Comment by nathanlesage** [comment]
Perfect! I've merged it, hotfix is coming in the next few days :) 

Thank you all for the very quick response and support!

**Comment by kb173** [comment]
Nice, thank you too!

**Comment by nistude** [comment]
Thanks a lot, guys!

**Comment by kroq-gar78** [comment]
Can confirm that the 1.8.7 deb does have working icons, thanks!
