### ISSUE TITLE
Keyboard navigation extension [feature request]

### ISSUE THREAD

**Issue by annargrs** [Zettlr/Zettlr#165]
I've over-strained my hand and need to stay away from the mouse for the moment. It looks like currently the only keyboard navigation option in Zettlr is the up/down arrow for moving between files in the list.

Would it be possible to add at least the following actions to which shortcuts could be assigned? This would really help.

* Focus on the file list
* Focus on the text editor
* Focus on the search field

Desirable but non-crucial shortcuts:

* move 10 files up/down with shift+up/down arrow, in addition to move 1 file up/down with up/down arrows;
* view and close the tag list;
* view the stats;
* open the main menu.

Apologies if the settings for this are already available somewhere and I couldn't find them.

**Comment by nathanlesage** [comment]
Hey, I see where you are getting at. Generally, focusing specific parts of the GUI and some other global shortcuts will require to finally implement the command shortcuts, that have been present in the app's source code for some time now, but have remained inactive, because it's not too high on the todo list.

Concerning the focusing: I can think of something like a custom shortcut section where you have the ability to customise shortcuts for all commands, but also things like this focusing stuff. Among these one might then also be able to add shortcuts to open certain dialogs.

The closing of the dialogs is something accessibility-related which still is somewhat coarse, because currently dialogs only close if one of the buttons is focused while pressing `ESC`, so I'll think of that as well!

Concerning the search field focusing btw: It's `Cmd/Ctrl+F` for the file-internal search and `Cmd/Ctrl+Shift+F` for the global search! All shortcuts (if I didn't mess up something) are located here: https://zettlr.com/docs/shortcuts

**Comment by annargrs** [comment]
Thanks a lot! My wrist is sending its best regards. 

Another relatively easy enhancement with a lot of payback for users who need to stick to the keyboard is an extra shortcut for moving up/down 10 files, in addition to 1. For example, it could be shift+top/bottom arrow, while top/bottom arrow alone would move one file forward/backward, as now. I'll add this to the wishlist above.

**Comment by goncalomcorreia** [comment]
Hi! First of all this app is incredible!

I want to second this issue. These keyboard shortcuts would really help. Especially having one to focus on text editing.

I would like to add two more to the list:

- Clear search and have the file list go back to show all files in the folder (you have to click the x in the search bar at the moment)
- Being able to go back to the previously selected note (ex.: after clicking on a note ID link)

**Comment by nathanlesage** [comment]
Hey, thanks @goncalomcorreia !

Concerning your strokes: For the first there's already a shortcut: First hit `Cmd/Ctrl+Shift+F` to focus the global search, and then hit `ESC`. Voilà!

Concerning the second, there's already this nasty issue which I still haven't managed to fully implement: ... oh, why did I close it? Anyhow, something's on the horizon, concerning that.

**Comment by goncalomcorreia** [comment]
Yes, if the search box is selected, then you can hit `ESC`. But you can't clear the search if the search bar is not selected. But now that you mention it, I guess you can just `Cmd/Ctrl+Shift+F` again and press `ESC`. Will there be any nasty issues if `ESC` clears the search, regardless if the search bar is selected or not?

Playing with the search function right now I also noticed that if you do a global search you need to click the note you want with the mouse after hitting `Enter`. It would be nice to be able to use the arrows immediately in the file list after doing a search. 

I think this kind of details really make a difference to keyboard-heavy users and it would be awesome if you could consider them :)

**Comment by nathanlesage** [comment]
> Will there be any nasty issues if ESC clears the search, regardless if the search bar is selected or not?

I guess ... not? :D I could implement it for testing purposes and if it breaks we'll notice during beta.

>  It would be nice to be able to use the arrows immediately in the file list after doing a search.

Yes, sounds very good!

> I think this kind of details really make a difference

Yes, they do, but as there are still a lot of features requested and I'm bad in postponing them, I don't come to implement details that often :( But I'll try to do better!

**Comment by goncalomcorreia** [comment]
Don't feel bad about it! You have finite hours in your week and that's understandable -- there will always be stuff left to do.

After a lot of search and trying out several apps for note taking, I can't overstate how happy I was for finding Zettlr. It had all the features I was looking for and that I found other apps were missing :D Really great work! I'm so excited about it that I wanted to give feedback and help make it even better :)

**Comment by nathanlesage** [comment]
You're so nice, thank you! :)

**Comment by nathanlesage** [comment]
Just implemented a way to move up/down by 10 files while holding shift!

**Comment by luskwater** [comment]
I, too, would love to have a *Go to editor pane* shortcut. I try not to use the mouse, but that's 40 years of using Emacs having its effect. Even having `<TAB>` *eventually* get to the editor pane would be an advantage (as long as one stopped in time).

**Comment by nathanlesage** [comment]
I think Tab should actually work (but don't ask me how many times it would take; the Editor is rather far down in the DOM, only before the window controls) =D

**Comment by nathanlesage** [comment]
Alright, after having spent two full work days simply to build an application to finally map out the shortcuts already present, to determine which ones I use, I finally ended up with a conclusion:

* `Cmd/Ctrl+Alt+E`: Focus the **E**ditor
* `Cmd/Ctrl+Alt+T`: Focus the **T**ree view / file list (the full sidebar, to be precise)

**Comment by goncalomcorreia** [comment]
Awesome!! Looking really forward to downloading a new version of zettlr :))

**Comment by nathanlesage** [comment]
And here we go! After almost exactly seven Months, the final shortcuts are implemented! Hooray, I guess …?

**Comment by goncalomcorreia** [comment]
Hi! After updating to 1.6, these shortcuts no longer work for me and the up/down arrows don't work in the file list.

**Comment by nathanlesage** [comment]
Which shortcuts do you mean exactly?

The file list shortcuts only only work if it's focused!

**Comment by goncalomcorreia** [comment]
These ones:

>     * `Cmd/Ctrl+Alt+E`: Focus the **E**ditor
> 
>     * `Cmd/Ctrl+Alt+T`: Focus the **T**ree view / file list (the full sidebar, to be precise)

**Comment by nathanlesage** [comment]
Oh, you're right! I have no idea how that happened, will investigate!

**Comment by goncalomcorreia** [comment]
Thanks!

**Comment by nathanlesage** [comment]
Accidentally stumbled upon the error, should work now!
