### ISSUE TITLE
[FEATURE REQUEST]: Line numbers in gutter

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1654]
## Description

Enable optional line numbers in editor gutter.

## Example Workflow

Line numbers should appear in the non-editable section of the gutter at the beginning of each newline. 

Note: Lines that are wrapped must **not** display a line number

## Additional Information

I've just started linting my docs using my document generator, it'd be really nice to be able to reference lines without needing to open vscode!

**Comment by exislow** [comment]
@nathanlesage: I would also love to have line numbers visible in the editor. Maybe this is a feature for Zettlr v3?

**Comment by nathanlesage** [comment]
Maybe. I've been tinkering a little bit and the CM6 API is in fact much better for many things as compared to the older API, so there is a possibility. Won't promise anything, though.
