### ISSUE TITLE
Removing an open file make the file unclosable

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#1657]
Zettlr 1.8.6, under Ubuntu.

Open a file in working directory in Zettlr.
In the sidebar, right-clic on the file to delete it.
Confirm.

The file is removed from the sidebar but not from the editor.  Worst : you can’t close it. The tab is now iresponsive.

Workaround : close and restart Zettlr, the file will disappear.

**Comment by nathanlesage** [comment]
I can't reproduce this behaviour locally, unfortunately. Do the logs tell you something?

**Comment by ploum** [comment]
Can’t reproduce it after a reboot. So probably some kind of heisenbug. Sorry for the noise.
