### ISSUE TITLE
Table editor losing edits and behaving erratically

### ISSUE THREAD

**Issue by cybervegan** [Zettlr/Zettlr#1658]
## Description

Previous edits "disappear"  when working on a table, seemingly reverting to a previous "version" of the table. Saving the file regularly does not seem to help. Edits do not seem to be present in undo or redo buffer.

## Reproducing

1. Create a table using the "insert table" function or by typing in the markdown.
2. Edit it interactively, adding rows, columns and text, pasting text from the clipboard, etc. in a non-linear fashion. 
3. Change focus to a separate window or another part of the text; the table *sometimes* reverts to Markdown mode or back to "rendered display" mode, often losing random edits.
4. Clicking into a cell in "table editor mode" often clears the contents of that cell rather than allowing editing of it.

## Expected behaviour

Edits should not be randomly lost. It should be possible to edit tables without randomly losing text.

## Platform
 - OS and version: Debian Buster (10) with MATE desktop
 - Zettlr Version: 1.8.1

## Additional information

Video of the behaviour:
https://user-images.githubusercontent.com/7657923/105044639-de6c5780-5a5e-11eb-9a8e-b6965d8a72cc.mp4

Things dissappear randomly - I never deleted anything apart from when correcting typos as I typed.

**Comment by nathanlesage** [comment]
The table editor has been refactored to be much more stabler in a later version of Zettlr. Please make sure to try out the newest version (at the time of writing 1.8.5) before opening an issue to help keep our work focused :)
