### ISSUE TITLE
FEATURE: Use CSL and bibliography paths set in YAML frontmatter

### ISSUE THREAD

**Issue by petrbouchal** [Zettlr/Zettlr#1659]
## Description

Currently, CSL and bibliography are set globally. It is standard practice to use project-level CSL and bibliography files, pointing to them in the `csl` and `bibliography` fields (`bibliography` can be an array of paths.) Pandoc understands these, however currently Zettlr passes its global paths to CSL and bibliography files, resulting in unprocessed references and an error if the global CSL preference is unset.

For projects, it is possible to set a CSL, but this should also be possible for individual files. I cannot see a bibliography option in the Project settings menu.

## Example Workflow

See above.

## Caveats

Rmarkdown-based projects like website and bookdown projects (and perhaps also blogdown), can set the bibliography and CSL fields in a project-level YAML config file, such as _site.yml for Rmarkdown websites. A sensible solution might be to warn when attempting to export, as people should really be building their larger projects in R and Zettlr should not be expected to duplicate this functionality.

**Comment by Kangie** [comment]
This is an interesting issue. The new defaults-file writer should handle this use case, so stay tuned. :)

**Comment by tillgrallert** [comment]
I politely second this feature request. I just discovered Zettlr and I am used to various Pandoc-based workflows, where one would almost always set a a file-specific URL for the bibliography. This has two advantages:

1. The underlying markdown files are self-sustained in the sense that  the link to the bibliography isn't lost outside Zettlr.
2. File-specific bibliographies will almost always be significantly smaller than global bibliographies. The latter contains some 30k references in my case.

**Comment by nathanlesage** [comment]
Yup, this sounds like an issue that's covered in our defaults-file refactoring for Zettlr 2.0!

**Comment by nathanlesage** [comment]
Implemented a few days ago!
