### ISSUE TITLE
French translation issues

### ISSUE THREAD

**Issue by ngirard** [Zettlr/Zettlr#166]
Hi,

thanks very much for your dedication in writing a free software that both allows to implement the Zettelkasten system, and is available on Linux platforms !

as you might notice, I've started improving the french translation on your dedicated website. I'm afraid my additions are not comprehensive yet, because of the efforts involved first ; but also because I'm having a hard time dealing with some items, so I wish I'd ask you to clarify them and I'm under the impression that other translators could benefit from these discussions.

Where is the best place to do this ? 

- Is there a way of discussing translation issues in your [dedicated website](https://translate.zettlr.com/) ?
- Should I use this very issue as a placeholder for my questions?
- Should I open a new issue for each question, to which you could add a specific tag related to translation issues ?

Cheers !

**Comment by nathanlesage** [comment]
Hey,

yes I've seen you've registered! Thanks for helping!

Concerning your issues: The big problem is that I still struggle a little bit of how to effectively create a great community where it's possible to discuss everything as needed. As of now, I've offloaded the efforts of maintaining to third-party services such as Reddit and GitHub, which also helps the problem that I don't want to force people to create so many accounts on dedicated services etc. But I've thought that maybe a Slack channel would be an appropriate way of having something where to discuss developer stuff.

But until this happens, I would suggest the following procedure (please comment if you think something is not useful or could be done better!)

1. If the issue pertains the usability of the Translate-website (which will concern the most issues as it's a completely self-written backend and therefore still has some terribly bad usability issues), maybe the best place to ask those things is still here on the GitHub repository. It's not the best solution but this way everybody can be kept in the loop.
2. If it concerns how translations are used by Zettlr, of course this repository is the correct place (for instance if you have input on the structure of the translations as such)
3. If you simply have a usability question of how something works, dropping me a mail at info@zettlr.com should prove to be best, as I can then answer it and update the short documentation on how to use Zettlr Translate.

What do you think?

**Comment by ngirard** [comment]
> I would suggest the following procedure
> ...
> What do you think ?

I'm good with it, thanks !
