### ISSUE TITLE
[ENHANCEMENT] Improve Typewriter mode when selecting text with mouse cursor

### ISSUE THREAD

**Issue by raphraph** [Zettlr/Zettlr#1660]
## Description

Ease text selection on one or multiple lines when using the mouse **in Typewriter mode**.

When in this mode, the scrolling speed of the selection is so high that it is very hard to precisely make the selection you want.
For example if you click on the highlighted line and slowly move your mouse cursor to the above line, it automatically scrolls a few lines before stopping.

Even when you try to select text on the same line, if you are not careful enough the cursor hovers slightly the previous or following line and selects multiple lines right away...

## Proposed Changes

When you are in Typewriter mode you can still scroll the view up and down (moving the highlighted line, and the cursor, up and down), and once you start typing the highlighted line is centered again immediately (this is very nice).

I propose that when you start mouse selecting text when in Typewriter mode, the cursor is also allowed (as when you scroll) to move up and down ant not automatically centered on the page.

## Caveats
Not sure

## Additional Information

I discovered this mode and adopted it immediately. Before I used to always add blank lines to keep my cursor in the middle of the page... But really this difficulty to select text is quite annoying. I would love this enhancement 🤩

**Comment by nathanlesage** [comment]
Good idea!

**Comment by nathanlesage** [comment]
Implemented that a few days ago, Typewriter is now much nicer to your selectivity!
