### ISSUE TITLE
Global search with exact filename does not open file anymore

### ISSUE THREAD

**Issue by klieret** [Zettlr/Zettlr#1661]
## Description

Global search with an exact filename will no longer open the file, but only show it as search result.

## Reproducing

1. Suppose we have two files in the zettelkasten directory, one called `a_20210120182954`, the other `b_20210120182955`
2. Enter `a` in the global search bar
3. The rest of the filename will autocomplete to `a_20210120182954`
4. Hit enter

## Expected behaviour

Zettlr should open the file  `a_20210120182954` (this has been the behavior in the past). Currently it is only shown as search result (with high weight).

## Platform

Zettlr Version: 1.8.6

System: linux 5.3.0-64-generic (architecture: x64)

Build Dependencies
This build was compiled using

Node.js v12.18.3
Electron v11.1.1
Chrome v87.0.4280.88

**Comment by nathanlesage** [comment]
That behaviour was always a tad unstable. However, due to major changes to how the global search works, this is no longer a relevant issue – the global search is no longer a mixture of advanced search and omnibar (such as in nvAlt) but only a global search.
