### ISSUE TITLE
Find icon on toolbar doesn't respond to mouse click

### ISSUE THREAD

**Issue by jchalifour** [Zettlr/Zettlr#1663]
## Description
The magnifying glass icon for the "Find in file" functionality (within the toolbar of buttons across the top of Zettlr) doesn't respond to a mouse click. Using [CTRL]-F does display the "Find in file" dialogue from that icon. 

## Reproducing
Use the mouse to click the magnifying glass

## Expected behaviour
The "Find in file" dialogue drops down to allow a person to type words to find/replace in the current file.

## Platform
 - Manjaro Linux (stable branch) up-to-date (Gnome 3.38.3)
 - Zettlr Version: 1.8.6

**Comment by nathanlesage** [comment]
There were some issues in the past, but since we've in the meantime moved completely to Vue, and also improved on the general handling of keyboard strokes and mouse clicks, this should work perfectly fine now.
