### ISSUE TITLE
Clicking on Find in File doesn't show the Cmd-F dialog

### ISSUE THREAD

**Issue by memeplex** [Zettlr/Zettlr#1667]
## Description

When I click on the magnifying glass icon in the toolbar nothing happens. OTOH, Cmd-F displays a search dialog below that icon.

## Reproducing

I think it's already clear from the description.

## Expected behaviour

Clicking on the icon should do the same than pressing Cmd-F.

## Platform
 - OS and version: MacOS Big Sur 11.1
 - Zettlr Version: 1.8.6

**Comment by nathanlesage** [comment]
Duplicate of #1663
