### ISSUE TITLE
[ENHANCEMENT] don't select '.md" in 

### ISSUE THREAD

**Issue by bionicles** [Zettlr/Zettlr#1671]
## Description
When we create new files, it opens a box with the generated filename. The whole filename is selected, including the ".md" extension. The enhancement would simply be to not select ".md" so when you create a new file you can instantly type a filename without an extension

## Proposed Changes
Simply change the selection of the text in the filename modal to not include the ".md" 
(perhaps via string slicing) -- or don't include the extension in the modal

## Caveats

might need to include .txt

## Additional Information
tiny improvements yield compounded exponential growth

**Comment by nathanlesage** [comment]
Why did you open two issues for this request?
