### ISSUE TITLE
[FIXED] Deleting a note disables mouse input for all apps including Zettlr

### ISSUE THREAD

**Issue by EcherArt** [Zettlr/Zettlr#1677]
## Description
I have 2 notes and I want to delete 1 of them. Doing so (right click - delete file) causes the following: I can move a cursor but unable to click anything; switching workspaces (Ctrl+F1 and then Ctrl + F8) causes my screen to fully disable itself. Only thing that works is a drop-down terminal with a forced focus, sound is also unaffected. I can call in other windows via terminal, but I am unable to send clicks to them. I've checked and my system (CPU, RAM, etc) is not loaded at all, so it's not a system resources problem.

## Reproducing
On a fresh install of Zettlr (see system specifics) create 2 notes. Create 1 Zettelkasten ID (might not be the cause of the problem, deleting it didn't fixed it). Delete 1 of the notes without the ID.  A dialog window pops up, but clicking anything doesn't work now. 

## Expected behaviour
Just deleting a note and not disabling my input

## Platform
 - OS and version: Manjaro Linux, **XFCE**, Linux 5.9.16-1
 - Zettlr Version: 1.8.6 from AUR (yes it might be AUR problem but I don't have other distros to check out)

## Additional information
What was tested:
-Custom CSS is not the problem (deleting it does not fix it)
-deleting Zettelcasten ID does not solve the problem. It also may be not the source of the problem.
-localization is not the cause of the problem

My note files are located at:
/hone/username/Documents/Zettlr
GPU: Nvidia 2070 Super driver version 460.32.03
I have yarn installed, v. 1.22.10
I've set Zettlr window to use native system appearance because default one stands out too much.

**Comment by nathanlesage** [comment]
Sounds like this is related to #1618, can that be?

**Comment by EcherArt** [comment]
Hi, both the button "Open workspace" and the menu dialog "File" -> "Open Workspace" work for me without hanging anything. So for the only thing that disables Zettlr is removing the workspace: right click - Delete file. It calls up the system dialog window which immediately comes unresponsive to mouse input, along with any other apps and panels.

**Comment by nathanlesage** [comment]
This more and more looks like an issue with Electron on Linux platforms which somehow instantiates those native dialogs in some wrong way and has a bug. Maybe it'll go away with a newer Electron version, but we have to watch this …

**Comment by zargex** [comment]
Hi @nathanlesage , i just noticed that this one could be the same than #1645

**Comment by pltcldvlpr** [comment]
I experience the same issue. As a workaround I delete files & folders via file manager and not via Zettlr. Sometimes, the freeze can be stopped by resizing the window and the confirmation dialogue disappears

**Comment by nathanlesage** [comment]
> Sometimes, the freeze can be stopped by resizing the window and the confirmation dialogue disappears

Yeah, this utterly sounds like an issue with Electron – has someone already spotted something on their repository?

**Comment by EcherArt** [comment]
> Sometimes, the freeze can be stopped by resizing the window and the confirmation dialogue disappears
I've tried and this is not possible on my system, at all. (not window resizing in general, but window resizing during the bug). So, a rather crytical bug, it disables my mouse completely.
