### ISSUE TITLE
Hard Limit on Word Count

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#1678]
## Description

Alert the user when they have exceeded there chosen word limit/target.

## Proposed Changes

When setting the writing target, have an option to set a 'hard limit' which informs the user if they exceed the limit (maybe the green status wheel on the document goes red if they exceed it by over 10% of there target, amber if they exceed it at all).

This would be especially useful for University/College students who write assignments with a hard word limit.

## Caveats

The current writing target system would need to adapt to fit the feature.

## Additional Information

I have only just discovered the writing target was a thing and find it really useful for dissertation work. Stay awesome!

**Comment by nathanlesage** [comment]
I think that simply setting this hard limit as your writing target should suffice, shouldn't it?

**Comment by break6700** [comment]
The issue is that if I go over my word count I don't get alerted and all I can see (at a glance) is that I have reached my writing target. I recenltly wsa working on a project with a limit of 4000 words, set my writing target to 4000. When I finished the project, checked what the limit was for my word count, I could see that I had written an extra 1000 words.

The idea is just a nicety and could potentially save people some time in the long run.

Alternatively, you could have the writing target apear here as well. Which would be useful for people using Zettlr in compact mode.

![zettlrword](https://user-images.githubusercontent.com/44082853/107230281-c614aa80-6a16-11eb-8771-a9dc16cdb482.png)
![zettlrword](https://user-images.githubusercontent.com/44082853/107230619-34f20380-6a17-11eb-8a52-981040564bde.png)

![zettlrword2 png](https://user-images.githubusercontent.com/44082853/107231651-7505b600-6a18-11eb-9677-c48b0e4e8172.png)

Sorry I'm not a designer.
