### ISSUE TITLE
.md file is deleted if replaced with same name

### ISSUE THREAD

**Issue by welovelain** [Zettlr/Zettlr#1679]
## Description

.md file is deleted if replaced with same name

## Reproducing

1. Press "rename file"
2. Leave the same name
3. In warning notification press "replace file"
4. file is deleted

## Expected behaviour

File should remain the same.

## Platform
 - OS and version: archlinux
 - Zettlr Version: 1.8.6

**Comment by BellLongworth** [comment]
Also happens if you rename it by only changing the case of letters.

**Comment by nathanlesage** [comment]
According to `git blame` fixed on May 12th by 4b447aac9
