### ISSUE TITLE
[ENHANCEMENT] Add CSS selector to tags with tag name

### ISSUE THREAD

**Issue by ritvje** [Zettlr/Zettlr#1680]
## Description

I would like to dynamically override tag style based on the text in it, for example have `#red` show up as red. As far as I understand, for this the tag selector should be different for each tag.

This is possible for example in Obsidian:
![image](https://user-images.githubusercontent.com/11709270/105615185-55934a00-5dd7-11eb-85fa-dd0c53951083.png)

## Proposed Changes

To me it seems this could be done by changing `/source/renderer/modules/markdown-editor/modes/markdown-zkn.js` from line 183 to something like

```javascript
if (stream.sol()) {
  stream.match(zknTagRE)
  // return 'zkn-tag'  // original
  return `zkn-tag zkn-tag-${stream.current().substring(1).toLowerCase()}`
} else {
  stream.backUp(1)
  if (stream.next() === ' ') {
    stream.match(zknTagRE)
    // return 'zkn-tag'   // original
    return `zkn-tag zkn-tag-${stream.current().substring(1).toLowerCase()}`
  } else {
    return mdMode.token(stream, state.mdState)
  }
}

```

which would result in selectors `#red` -> `cm-zkn-tag-red`.

## Caveats

I can't think of any problems, as one can always ignore the extra selectors. There would be quite a lot of selectors, but I am not an expert enough to say if that's a problem.

**Comment by nathanlesage** [comment]
Better though: There is a tag manager that allows you to color your files with regard to certain tags. I'd rather suggest you use this, and then the changes would only include adding that colour in the editor as well, which is better with regard to runtime efficiency.
