### ISSUE TITLE
Properties "author-only" and "suppress-author" in cite items

### ISSUE THREAD

**Issue by fbennett** [Zettlr/Zettlr#1682]
In reference to ... https://github.com/Zettlr/Zettlr/blob/01dde68c3f7808863c0656c9728e4674aa2ade94/source/citeproc.d.ts#L73-L90 ... the "Dirty Tricks" section of the `citeproc-js` documentation needs an update. Those flags on individual cite items do work, but the "new way," available only on `processCitationCluster()`, is to set a single `mode` property on the outer object (`EngineCitation`) with a value of `author-only`, `suppress-author` or `composite`, with an optional value of `infix` when the last is used. The documentation on it is [here](https://citeproc-js.readthedocs.io/en/latest/running.html#special-citation-forms).

The change was introduced to support the "composite" form, so that you can (say) set an author-date citation in the form "Smith (2000)" in one go without typing "Smith" into the text, and have it adapt smoothly when converted to footnote or numeric styles. (The "composite" form pretty-much works for current CSL styles, but will work best in some styles with an extension to CSL syntax, covered in the doc, that is not currently valid CSL.)

**Comment by nathanlesage** [comment]
Sorry for my late response, I wasn't able to check until now! I'll put that on the roadmap to 2.0, since that seems to be a development issue, thank you for notifying!

**Comment by nathanlesage** [comment]
Just double checked and we're not even using the processCitationCluster function, mainly because it's pretty expensive running this often … but thanks again for the heads-up! If I'm ever able to use citeproc "as it's meant to be" I'll make sure to implement it this way!
