### ISSUE TITLE
[FEATURE] Disable auto save

### ISSUE THREAD

**Issue by meaz** [Zettlr/Zettlr#1683]
Hi,

I have seen that https://github.com/Zettlr/Zettlr/issues/712 is closed.

However, that would be a great feature. Or does it already exist and, in this case, where can I find it?

I don't like the auto-save feature, because I like being able to do changes to a file without saving them, so that I can save them only when I'm sure my changes are rights. For example, I just discovered Zettlr so I wanted to play with it a bit: I messed up my file because I didn't know that the changes were auto-saved!

Thanks a lot

**Comment by nathanlesage** [comment]
For Zettlr 2.0, there's no more autosave, since Zettlr now corresponds to all other note-taking and text and word editors on all platforms, none of which feature autosave by default, so I think this issue is resolved!

**Comment by indeyets** [comment]
@nathanlesage Will it maintain current "unsaved" state between app restarts? that's default in modern macOS apps and it makes workflow so much more safe. The idea is to keep data in presistent buffer belonging to Zettlr, but save to user-owned files only on explicit demand

**Comment by nathanlesage** [comment]
Phew … that involves quite the code base change, so to be safe don't expect it to do that. I have very limited time on my hands and it's much easier to just have an unsaved file representing exactly that: Unsaved, which'll mean it's lost if it's not saved.

However, Zettlr will always ask you to save changes prior to actually quitting the app, so it will be very hard to lose any data even without that feature. You have to mingle with the system settings in order to forcefully shut down Zettlr thereby losing your data so while – yes – that would be convenient, it has a very low priority.

**Comment by SamirSaidani** [comment]
In my own experience, my OS forced a restart for an update (guess which OS...), while I was not in front of the screen, and I've lost all my changes on zettlr. 
Actually autosave was a great feature, one of the feature that it's possible on emacs or vim. I understand that a lot of editors doesn't have this feature, but I don't understand the logic of giving up on autosave. That's precisely what makes zettlr above the crowd: a feature that only a few editors have. Unfortunate decision in my opinion. I hope that you'll give a second thought on autosave feature (on/off).

**Comment by usedbytes** [comment]
> For Zettlr 2.0, there's no more autosave, since Zettlr now corresponds to all other note-taking and text and word editors on all platforms, none of which feature autosave by default, so I think this issue is resolved!

I don't think that's true at all. MS Office apps now autosave by default. In particular, OneNote - which probably has the most similar use-case to Zettlr - doesn't even have a save button.

I think autosave is a really important feature for this kind of note-taking app, at least as an option.

**Comment by dave-kennedy** [comment]
@SamirSaidani @usedbytes for the record, this option has been restored in 2.0:

![image](https://user-images.githubusercontent.com/13735532/136084812-18941d23-6df6-485d-88fd-fa880eb31afa.png)
