### ISSUE TITLE
Ctrl+Shift+F doesn't open global search without open files

### ISSUE THREAD

**Issue by klieret** [Zettlr/Zettlr#1684]
## Description

Ctrl+Shift+F doesn't open global search without open files

## Reproducing

1. Close all open files
2. You should see "No open files." in the tab bar
3. Press Ctrl+Shift+F
4. Nothing happens

## Expected behaviour

Jumping to global search.

## Platform
 
General Information
Zettlr Version: 1.8.7

System: linux 5.3.0-64-generic (architecture: x64)

Build Dependencies
This build was compiled using

Node.js v12.18.3
Electron v11.1.1
Chrome v87.0.4280.88
v8 engine v8.7.220.29-electron.0
Zlib v1.2.11
OpenSSL v1.1.1

**Comment by nathanlesage** [comment]
Now it should work perfectly.
