### ISSUE TITLE
[ENHANCEMENT] List Files in Shuffled/Random Order

### ISSUE THREAD

**Issue by whateverforever** [Zettlr/Zettlr#1689]
## Description

This enhancement would add a new button to the file list on the left hand side, which allows to shuffle the files. So in addition to chronological and alphabetical order you'd have no order at all. Clicking on the button again reshuffles the list.

The purpose of this is to have a way to refresh your memory of what you have already, and to find new interconnections. The current file orderings can't do this because, for a given file, you mostly see the same files, or files you were aware of anyways (because you just edited them).

## Proposed Changes

This would add a new button next to the current ordering buttons.

## Caveats

Might be confusing to new users, but with a tooltip that could be remedied.

**Comment by nathanlesage** [comment]
Before that could be implemented, there are a few other features that would be needed. Furthermore, this change might drive Zettlr too far into the Spaced-Repetition corner which is already filled to a good extent by tools such as Anki or Mochi. I don't really see a use for this right now, but maybe others disagree.
