### ISSUE TITLE
I want to use the TAB button to space out text in one line, but the editor always indents the whole line instead

### ISSUE THREAD

**Issue by northern-arizona** [Zettlr/Zettlr#1694]
I'm just starting to use Zettlr, but I am running into a problem.

When I am typing a line of text in the editor and I hit the TAB button, I want the editor to add the correct number of spaces within the line to jump my cursor to the next tabstop. However, the editor indents the entire line and does not add the tabstop spaces within the line.

For example, I type this:
A <TAB> B <TAB> C
What I want and expect is this:
A         B        C
But instead, I get this:
             A B C
           
Is there any way to get the traditional editor functionality that the TAB button inserts spaces until the next tabstop?

**Comment by kyaso** [comment]
Currently, this is the default behaviour of pressing TAB. See #1206.

**Comment by nathanlesage** [comment]
I can have a look into the function hook, but can't promise anything.
