### ISSUE TITLE
Notes list jumps when a note is clicked

### ISSUE THREAD

**Issue by aleksey-uvarov** [Zettlr/Zettlr#1696]
## Description

After I click on a note in the note list, the list scrolls itself so that the note opened is the lowest note in the visible part of the list.

## Reproducing

1. Open some folder with the notes. There should be more notes that can fit in one screen.
2. Open some file and edit it, so that there is more than one tab open.
3. Scroll down a screen or so.
4. Click on any note.

This doesn't happen every time, so one should click on a few different notes to catch this.

## Expected behaviour

The note list does not move when a note is clicked on.

## Platform
 - OS and version: Windows 10, version 20H2
 - Zettlr Version: 1.8.7

## Additional information

This doesn't seem to happen when there is only one tab open. Occasionally, the list flashes up to briefly highlight the note open in the first tab.

**Comment by nathanlesage** [comment]
Since we have now a much better state management, this bug should be resolved already. If not, feel free to comment after the 2.0 release.
