### ISSUE TITLE
Export-Template formatting

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#1697]
Hey guys,

for my academic work, I need to produce this kind of layout, with a bibliography at the end. 
Is there a way to make these settings in Zettlr? 

The problem is, that if I export it to Word, I loose the Zotero connection. 

<img width="587" alt="Bildschirmfoto 2021-01-30 um 13 40 25" src="https://user-images.githubusercontent.com/68868949/106357088-3a0ece80-6304-11eb-8229-82c273dcdbec.png">

**Comment by audijenz** [comment]
Hi JJger148, you have to use a custom csl file. 
Looks like you can work with the following style:
https://github.com/citation-style-language/styles/blob/master/hochschule-pforzheim-fakultat-fur-wirtschaft-und-recht.csl

**Comment by JJger148** [comment]
thanks audijenz, 

that worked well!
