### ISSUE TITLE
[ENHANCEMENT] Better handling of inline latex using double $ as delimiters

### ISSUE THREAD

**Issue by tejasvi** [Zettlr/Zettlr#1698]
## Description
```
$$x$$ some text
# title
```
works but
```
$$x$$
# title
``` 
doesn't and breaks the parsing.

# Better handling of inline latex using double $ as delimiters

## Proposed Changes
Currently Zettlr parses '$$' delimiter for inline Latex as expected in almost all cases other than the one mentioned above. Either this behavior can be corrected or a config for custom delimiters regex can be offered which is beyond this proposal's scope.

## Caveats
None that I know of.

## Additional Information
Some standards use different latex delimiters (e.g. Gitlab's kramdown uses `$$` for both inline and block mode, Katex by default uses `\(..\)` for inline). [This](https://tex.stackexchange.com/q/410863) Stack Exchange question offers another view.

**Comment by Kangie** [comment]
We use pandoc markdown; You need to use $...$ for inline maths, and $$...$$ for block maths. Block maths should be in their own block and should have whitespace before and after them.
