### ISSUE TITLE
Custom Tex-Template not used

### ISSUE THREAD

**Issue by audijenz** [Zettlr/Zettlr#1699]
## Description
With a custom Tex-Template set in General Export Setting or Project Settings the standard template is sill copied to the export directory. 

## Reproducing
Set the Export Setting or Project Setting to a custom Tex-Template

## Expected behaviour
Zettlr should copy the custom template to the temporary directory.

## Platform
 - OS and version: Win10
 - Zettlr Version: 1.8.6

**Comment by audijenz** [comment]
Apprently in windows the specified template from the project settings is not used to generate the temp file stored in $tpl$. Workaround is to copy that file, add customizations and then replace $tpl$ with
--template="D:\Path\to\template\Template.tex" under Einstellungen>Erweitert

**Comment by Kangie** [comment]
Interesting. Possibly errata from recent pandoc bundling changes? I'll try and reproduce this, but it may be Monday before I get a chance.
