### ISSUE TITLE
Table of Contents is not properly punctuated.

### ISSUE THREAD

**Issue by httpsterio** [Zettlr/Zettlr#17]
If I have say, three headings like:
`# Heading 1`
`## Heading 2`
`# Heading 3`

It should show under the TOC as this:

1. Heading 1
1.1. Heading 2
2. Heading 3

Currently the full stops after the ordinals are missing.

**Comment by nathanlesage** [comment]
Granted, it definitely looks better than without the full stops. Will be coming with the next release!
