### ISSUE TITLE
Linking notes by ids is impractical because only IDs can be easily copied

### ISSUE THREAD

**Issue by ngirard** [Zettlr/Zettlr#170]
Using Zettlr 1.2.3 on Ubuntu 18.10.

After playing with Zettler for less than a day, this has been my biggest usability issue so far.

Following Zettelkasten methodology implies to link, say, zettel `za` to zettel `zb`, by adding a link to za's ID to zb's contents.

But most of the time adding just the ID is not sufficient because we need to characterize the link by adding a description in it, or next to it. And reusing the filename or the title (if any) for such a description is what I want (what we want, dare I say, after following other people's workflows) most of the time.

But currently, Zettler only facilitates copying the IDs of notes, and not their titles nor their filenames.

I'd suggest that Zettlr *at least* allows to insert both (a) whatever the user prefers between filename/description ; **and** (b) the link to the ID, at the same time.

That is, instead of simply inserting
```
[[@xxx]]
```

Zettlr would allow to insert
```
<description> [[@xxx]]
```
where `<description>` is either the filename or the text of the first heading of the note, depending on what the user decides.

**Comment by annargrs** [comment]
Second that.

I've started with ZK methodology with [sublimeless_zk](https://github.com/renerocksai/sublimeless_zk/), which does have the option of adding note title to the file name. The file names then look like `xxxxxxxxxxx a note about something.md`.

In fact, that happens with one handy shortcut:

* you type something inside note A;
* you decide it should be a separate note, highlight it and with one shortcut sublimeless_zk (a) generates an id, (b) creates a note with the said id and selected text as the title, (c) pastes both title and id inside the new note as the title, according to a pre-defined template, and (4) formats the reference in the original file. 
* From now on, when you reference the new note from any other notes, the title text is also added automatically as `[[xxxxxxxxxxx]] a note about something`. Note that only the id is actually in the reference, as it does need to stay stable - but the helper title text can be edited without breaking the link.

This was a really handy feature. I must admit that sometimes I did NOT want those titles in exactly the same shape, and edited the auto-inserted reference text, but still - having the titles to edit was very helpful.

**Comment by dambaras** [comment]
Would really like to see some movement on this issue. Thanks.

**Comment by nathanlesage** [comment]
There are still a lot of issues older than this that also require some attention, so please be patient!

**Comment by dambaras** [comment]
No worries, and sorry to sound pushy. I'm impressed by how responsive you are and how quickly the app has developed! (I'm pretty much hoping that I can use Zettlr and Zotero as my two standard tools. If anyone knows of a good browser or pdf reader that starts with Z, I'm all in.)

**Comment by amw290** [comment]
Ditto what @annargrs said. I, too, miss this functionality from sublimeless_zk

**Comment by nathanlesage** [comment]
Accidentally found the most easy way to implement that. If you now enter an ID and pick an option from the dropdown menu, Zettlr will automatically add the displayed filename from the dropdown as the description behind the ID, like this:

![image](https://user-images.githubusercontent.com/17251683/62776902-276b5e80-baac-11e9-889e-5166a3ddcf70.png)

**Comment by dambaras** [comment]
Perfect! Thanks!

**Comment by amw290** [comment]
Sweet! Glad it was easy!

**Comment by siddacool** [comment]
> Accidentally found the most easy way to implement that. If you now enter an ID and pick an option from the dropdown menu, Zettlr will automatically add the displayed filename from the dropdown as the description behind the ID, like this:
> 
> ![image](https://user-images.githubusercontent.com/17251683/62776902-276b5e80-baac-11e9-889e-5166a3ddcf70.png)

Smooth.. thanks

**Comment by nathanlesage** [comment]
Just to clarify, in one of the next versions there'll be an option of how these ID links will be generated, please refer to this issue to follow development: https://github.com/Zettlr/Zettlr/issues/391
