### ISSUE TITLE
℉ doesn't render in PDF

### ISSUE THREAD

**Issue by eichin** [Zettlr/Zettlr#1706]
## Description

A .md file that contains `        * cook at 400℉ for 45 minutes` (literal codepoint #x2109) fails to render the ℉ in PDF generation.

(Rendering tested in `evince`, emacs docview, printing (via cups), and upload to google docs.)

## Reproducing

Click on the PDF icon, look at the output.  I do end up with `  \item
    cook at 400℉ for 45 minutes
` if I ask for TeX output instead.

Font settings according to the ctl-alt-comma panel are Liberation Serif, Liberation Sans, 12, 150.  `fonts-liberation` and `fonts-liberation2` packages are both installed, and the render step doesn't give any errors (as the FAQ suggests would happen if it can't find anything.)

## Expected behaviour

Main request is "unicode should just work by default, it's 2021" :-)  More practically, if I'm missing some package, having it at least be in the Recommended or Suggested packages in the deb would help even if it's not in debs; maybe even a different default font?

## Platform
 - OS and version: Ubuntu 20.10 "groovy"
 - Zettlr Version: 1.8.0 from deb

I'm running Ubuntu 20.10 "groovy", zettlr 1.8.0 deb, texlive packages; in particular,
```
ii  texlive-fonts-extra                2020.20200804-3                all          TeX Live: Additional fonts
ii  texlive-fonts-extra-doc            2020.20200804-3                all          TeX Live: Documentation files for texlive-fonts-extra
ii  texlive-fonts-extra-links          2020.20200804-3                all          TeX Live: Setup of fonts for TeX Live and search via kpathsea
ii  texlive-fonts-recommended          2020.20200804-2                all          TeX Live: Recommended fonts
```
Font settings according to the ctl-alt-comma panel are Liberation Serif, Liberation Sans, 12, 150.  `fonts-liberation` and `fonts-liberation2` packages are both installed

## Additional information

Screenshot as-rendered in evince.  Note that the spacing is plausible.
![unicode-degrees](https://user-images.githubusercontent.com/208492/106643066-2c04bc00-6557-11eb-8fb1-c33d16c3ac38.png)

**Comment by Kangie** [comment]
This isn't an issue with Zettlr; Unfortunately you don't have a glyph for the ℉ symbol in Liberation Sans and XeLaTeX is doing its best to provide output even though it hasn't been given a glyph for that character.

Good news, I've been working on this as part of a template update; This *should* eventually work, though it will still be a game of whack-a-mole to define unicode transitions and fonts as users need them. You can just wait for the new template & defaults writer (I'm imagining they'll be part of 2.0), else you can take a look at [my template here](https://github.com/lackadaisical-documentation/lackadaisical-generator/blob/master/templates/template.tex). and review the  \setTransitionsFor lines to do something similar for your glyph to try and get this working for yourself for now.

Step 1 will be identifying the unicode block; In this case it's '[Letterlike Symbols](https://en.wikipedia.org/wiki/Letterlike_Symbols)' identified from the code point 2109 for ℉.

Step 2 is identifying a font that contains the glyph you need. Noto has good coverage, as it's designed to (eventually) cover every code point.

Step 3 is instructing fontspec to use that font, and defining a new transition to and from it.

Note that step 3 is optional if you can find a font that contains the glyph and is suitable for your body text. :)

Happy to help if you encounter any issues with that.

**Comment by eichin** [comment]
Since for now I'm going for correctness rather than beauty, setting `Noto Sans` and `Noto Serif` worked.  I do appreciate the more sophisticated approach, and look forward to seeing it in the future!
