### ISSUE TITLE
File name is inconsistently used as id

### ISSUE THREAD

**Issue by ThaddaeusWiedemer** [Zettlr/Zettlr#1709]
## Description

Zettlr is using filenames of the `%id.md` as IDs, even if an ID is specified.  This is especially weird since its not documented (afaik).

## Reproducing

A file named with `%id.md` (let's call this ID1) and another ID2 somewhere in the file (e.g. in the YAML header) will be linked with `<[[ID1]] YAML title>` when using Zettlrs drop-down menu for internal links.

This is especially inconsistent since it seems Zettlr is not just checking the filename with the ID regex. Using `%id_.md` as a filename will use the first ID in the file as a default ID.

## Expected behaviour
In my opinion, the behaviour could either be explained fully in the docs or---preferably---the default could be
1. never use file names as ID
2. include the filename in the text that the ID regex is searching, i.e. an ID in the filename counts as the first ID in the file.

## Platform
 - OS and version:
 - Zettlr Version:

**Comment by nathanlesage** [comment]
> This is especially inconsistent since it seems Zettlr is not just checking the filename with the ID regex. Using %id_.md as a filename will use the first ID in the file as a default ID.

This sounds like a bug. (Wanted) behaviour is documented here: https://docs.zettlr.com/en/academic/zkn-method/#file-identification
