### ISSUE TITLE
Supporting `pp` would greatly enhance Zettlr's versatility and its users' expressivity

### ISSUE THREAD

**Issue by ngirard** [Zettlr/Zettlr#171]
Looking into the devel branch, I can see you recently strenghened the integration with Pandoc, which I'm glad about.

While the iron is hot, I wish to suggest adding support for the [pp preprocessor](https://github.com/CDSoft/pp).

Written in Haskell, it comes as a single executable, just like `pandoc` or `pandoc-citeproc`. The cost of adding such support would be fairly low with respect to the huge benefits it would bring.

Since it apparently hasn't been mentioned in here yet, I might just want to have a look at it first to give you and idea ; but I can also elaborate if you wish.

**Comment by nathanlesage** [comment]
Hmm … what I could offer you would be a way to have a custom command that you can execute instead of pandoc, where you could _also_ run pp?

**Comment by ngirard** [comment]
That would be great, provided the custom command goes through a parameter substitution stage before executing it. For instance, `{p}` would be substituted with the value of `b`.

The following parameters to be available for substitution should be enough:

- the root directory ;
- the default path for images, that you added recently ;
- the path to the `.md` file to be ingested ;
- the name if the `.md` file without its path
- the complete name of the output file

The remaining step for complete integration with pp, admittedly not indispensable but very useful, would be to allow the editor to parse `pp` directives according to their syntax, and allow them to be colored / styled via css...

**Comment by nathanlesage** [comment]
Alright, I'll look into it. But let me be honest: I will not feature a full-fledged **dedicated** support for pp, because it's not that central to a writing workflow (as opposed to pandoc), plus: If I were to integrate pp, then there would be no reason not to integrate other apps as well, etc., making the effort necessary unbearable, especially when looking at the already long list of issues.

Therefore, what I'll do is: Enable a custom command (something Abricotine supports as well) that you can make use of containing some variables, and launch any application using a specific command.

**Comment by nathanlesage** [comment]
I just realised that this is already quite possible: As 1.3 brings you the ability to customize the pandoc command by yourself, you can simply replace `pandoc` at the beginning of the command with `pp`. The only thing that you may need, and which I can provide, are some variables to use! Concerning the ones you already mentioned:

- The root directory can be easily implemented, I would call it `$indir$` (for: input file directory)
- The default path for images may not be needed, as all image paths are already converted to absolute paths prior to exporting to prevent any issues with any software.
- It's already available, called `$infile$`
- The basename could be provided, I would name it `$infile_basename$` (or something shorter)
- How about `$outfile_basename$`?

**Comment by ngirard** [comment]
Yes, please keep going, i'm fine with your suggestions !
