### ISSUE TITLE
Editor cursor loses focus after F2 shortcut is used to rename

### ISSUE THREAD

**Issue by joetainment** [Zettlr/Zettlr#1710]
## Description
Editor loses focus or loses cursor position, after F2 shortcut is used to rename

## Reproducing
Start typing some text in the main editor
Press F2 to rename the file
Press escape to cancel the file rename (or alternatively change the name and press enter)
continue typing
if escape was pressed in previous step
  new typed text will not appear at all
if name was changed and enter was pressed
  typed text will go to wrong position, since cursor is moved to the wrong position after rename
  (editor loses the cursor's old position prior to rename, and moves cursor to start of doc)
  

## Expected behaviour
Text typed after rename operation should appear in editor, and go to the same place cursor was before the rename operation.

## Platform
 - OS and version:   Windows 10  build 19042.685
 - Zettlr Version:  1.8.5

## Additional information
The current behavior is just weird and breaks the "flow" of usage because typing doesn't continue where it left off.

This bug tends to make it harder to operate Zettlr by hotkeys (without reaching for the mouse) or to automate it.
For example, it is often useful to do things like copying and pasting the current file name via hotkeys, to paste the current file name into the current file

e.g.  press F2 to rename, press ctrl-c to copy existing name, press escape to cancel rename, press ctrl-v to paste current file's name which was just copied, pasting it into the current file.

In general, the Zettlr user interface should probably maintain/restore cursor position whenever possible, and restore focus to the editor after temporary, pop-up or modal-like operations, such as F2 file renaming.

Workaround:
Currently, the focus loss can be worked around by pressing tab twice after pressing escape to cancel the rename.
I discovered this just by trial an error, combined with the knowledge that tab generally switches UI element focus.

**Comment by nathanlesage** [comment]
Thanks for reporting, will hopefully be gone during the full refactor

**Comment by nathanlesage** [comment]
Not happening anymore in the 2.0 dev branch, closing as fixed.
