### ISSUE TITLE
Screen is jumping around when typing at the bottom of the page

### ISSUE THREAD

**Issue by LePeti** [Zettlr/Zettlr#1711]
Hi there!

## Description

The screen is jumping around when there are only a few paragraphs on the screen and I start typing at the bottom of the page. This seems to stem from the feature that moves the screen to where the cursor is located once one starts typing.

## Expected behaviour

No jumping around :)

## screen recording

[Video on Google Drive](https://drive.google.com/file/d/1DhI20YJ7WbBJT4CkAC86CVdBcjXSymgI/view?usp=sharing)

## Platform

 - MacOS BigSur
 - Zettlr Version: 1.8.1

## Additional information

It seems that this doesn't happen if
- the cursor is not at the very bottom (this can be seen in the screen recording)
- or when there is much more text in the document

## Reproducing

Paste the below into a document to reproduce the problem:

```
# Donec mollis maximus justo, pharetra cursus ante dictum non

## Donec mollis maximus justo

### Nullam imperdiet nec est et aliquam.

malesuada orci. Proin non convallis est. Nam et ipsum elit. Proin nunc tellus, iaculis convallis vestibulum ut, blandit non nisi. Morbi sit amet tellus sit amet tellus malesuada sagittis. Sed mauris dui, bibendum sit amet elementum non, scelerisque et odio. Nullam imperdiet nec est et aliquam. Quisque consequat aliquam facilisis. Morbi feumalesuada orci. Proin non convallis est. Nam et ipsum elit. Proin nunc tellus, iaculis convallis vestibulum ut, blandit non nisi. Morbi sit amet tellus sit amet tellus malesuada sagitti

### Donec mollis maximus justo, pharetra cursusDonec mollis maximus justo, pharetra cursus

malesuada orci. Proin non convallis est. Nam et ipsum elit. Proin nunc tellus, iaculis convallis vestibulum ut, blandit non nisi. Morbi sit amet tellus sit amet tellus malesuada sagittis. Sed mauris dui, bibendum sit amet elementum non, scelerisque et odio. Nullam imperdiet nec est et aliquam. Quisque consequat aliquam facilisis. Morbi feumalesuada orci. Proin non convallis est. Nam et ipsum elit. Proin nunc tellus, iaculis convallis vestibulum ut, blandit non nisi. Morbi sit amet tellus sit amet tellus malesuada sagitti
```

Thanks!

**Comment by boutil** [comment]
Hi,
There is a mention in the changelog of v1.8.7 that such a problem was fixed in that version. Please upgrade to 1.8.7 and check if you can reproduce the issue.

**Comment by LePeti** [comment]
Cool, thanks! I used `brew` to install Zettlr and I think 1.8.1 is the latest version there. How and when do updates roll out to brew too?

**Comment by LePeti** [comment]
Turns out it's now available on `brew` too, so I'm closing this issue. Thanks @boutil for your help!
