### ISSUE TITLE
markdown layer on PDF for linking PDF text

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#1712]
It would be amazing Zettlr could put a markdown layer on top of a normal PDF.

Highlights could be turned into [[links]] or used as quotes. 
If I would click in the link it could jump directly to the location in the PDF. 

I hope people see value in this feature and can add some ideas.

**Comment by JJger148** [comment]
I just found out about this app that is still about to be released  https://keypoints.app
I hope this will work together with Zettlr, or maybe Zettlr can it's own version of this program.

**Comment by LoganWalls** [comment]
Hi there!

I just wanted to chime in and say that this is already possible with Zettlr if you use Zotero as a reference manager (using ZotFile and MdNotes plugins)! Here is an example of my workflow:

1. Add PDF to Zotero
2. Open the PDF in a viewer that supports highlighting (e.g. Preview on MacOS for me), and highlight / take notes.
3. In Zotero `right-click on the PDF > Manage Attachments > Extract Annotations` (this will create a new note will all of the quotes you highlighted and the notes you wrote).
4. Then `right-click on the note > MdNotes > Export as Markdown` (you can set your default export directory to one of the folders watched by Zettlr.
5. The markdown file will look something like this:
<img width="676" alt="screenshot" src="https://user-images.githubusercontent.com/2934282/109397158-5867ea00-7903-11eb-9930-83b79fce819b.png">

As you can see from the link URL, it will instruct Zotero to open the PDF and jump to the page where the quote is from.

This workflow is similar to the one a lot of people use for Obsidian (Search Google or YouTube for Obsidian + Zotero and it should probably come up).
