### ISSUE TITLE
Proposal: Git integration && Text Addons

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1715]
# Description

There are some common requests and quality of life improvements that would go together nicely and make Zettlr more useful.

This Issue is to serve as a central point to discuss and track these issues.

I will admit that some of this is just because I want to make my own life easier...

## Requests

1. Sync to Cloud

## Useful Tools

1. Integrate configurable Markdown structure validation.
2. Integrate configurable Markdown content validation.

## Other Stuff

1. Sensitivity Linting
 
# Proposed Solutions

## Cloud Storage

Cloud storage is something that a number of issues have been raised for (and keep being raised for).

- Git integration should be offered a la vscode
- Display tracked, untracked files. Commit/Push/Pull, etc. from within the app.
- Ideally, GitHub and GitLab integration to enable the creation of new repos through their API from a workspace.

### Benefits

This enables several nice things:

1. Cloud storage and collaboration
2. Revision history tracking through Git tags
3. Git Blame & Commit tracking!

### Caveats

- We will need to track every file in a workspace, and .gitignore files.

### Cool Stuff

- Automated production of documents on push/tag/release through CI (Hey, I've been working on something like this...)
- Git LFS handles images and other large files quite well.

## Markdown structure validation

Successful conversion from Markdown using Pandoc requires some rules that inexperienced users may not be aware of.

- Integrate [Markdownlint](https://github.com/DavidAnson/markdownlint) to provide warnings, errors and right-click to fix + fix auto-fixable errors.
- Provide 'this will break pandoc's processing of markdown' pre-configured settings
- Provide 'This will produce easy-to-read Markdown' pre-configured settings
- Offer the ability to configure Markdownlint rules via JSON/YAML upload.

### Benefits

- Easily see if output will break pandoc (e.g. line breaks around headings and lists)
- There's already a vscode addon for this. It's probably not too much effort to port.
- It's a node module!

### Caveats

- List detection rules are for Commonmark not Pandoc - It would be really nice to add Pandoc rules that allow list numbers to continue...

**Note**: We should probably start saying that Zettlr uses Pandoc Markdown rather than CommonMark.

## Markdown Content Validation

Markdown content validation allows us to catch things other than just spelling errors.

- Implement [Textlint](https://github.com/textlint/textlint) as a natural language linter.
- Provide sane defaults and an interface to upload YAML/JSON rules.

### Benefits

- Textlint bundles a number of language linting tools into a single interface and set of rules. 
- It's easy to configure
- It's got tons of rules
- They're all node modules.

### Caveats

-  I've observed that some Textlint rules output Errors where they should be warnings (e.g. Alex). Some validation needed.

## Sensitivity Linting

In spite of our best efforts it's easy to use prejudicial or insensitive language by mistake. E.g. Manned/Unmanned vs Crewed/Uncrewed.

- Introduce [Alex](https://alexjs.com/) as a sensitivity linting option.

### Benefits

- Makes it easier to prevent issues with documents that are to be published.
- Running it separately provides better output than running as part of Textlint.

# Roadmap

- [ ] 2.0 Release Stuff
- [ ] Implement Git integration for workspaces (Commit, Push, Pull, Force Push, Tag, Branch, Merge Conflicts)
- [ ] Implement Markdownlint + Textlint + Alex

As always, I'm open to comments / additions / etc.

**Comment by yhancik** [comment]
Several of my Zettlr workspaces are already Git repos! So having some Git integration would be perfect!

**Comment by break6700** [comment]
This appears to be the solution used by logseq: https://isomorphic-git.org/en/

**Comment by Yajo** [comment]
Isn't this a duplicate of #1050?
