### ISSUE TITLE
Feature : New file from template

### ISSUE THREAD

**Issue by josephgarnier** [Zettlr/Zettlr#1717]
## Description

I know this is not the [first time](https://www.reddit.com/r/Zettlr/comments/gn96wr/templates_for_new_notes_zettel/) this request of template has been submitted, but I think the answer of using AutoHotKey is not very practical to reach a neophyte audience.

## Example Workflow

This feature could take the form of 2 buttons : `New file from template` and `Insert a template` (like in [Joplin](https://discourse.joplinapp.org/t/templates-how-to-use/3517/2)).
The templates could be defined as markdown files that the user would put in a `template` folder next to custom css, etc... The buttons would just copy and paste these markdown files.

## Caveats

none

## Additional Information

none

**Comment by lduktus** [comment]
I just wanted to support the request. While I am aware that there are things like AutoHotKey, xdotool (Linux with X), ydotool (Linux with Wayland), etc. it feels kind of hacky and while I like scripting stuff and hack around imo this should be a core functionality. I also think that different workflows (writing and drafting publications and/or taking and organizing notes) could profit from this.

**Comment by nathanlesage** [comment]
Here we go: I just implemented a full-features templating system which will allow you to do basically everything as, e.g., in VS Code or TextMate (in fact, it's based on TextMate's syntax).

I did not implement a "from template" function, BUT it's as easy as it can get:

1. Create a new file
2. It will be immediately focused
3. Type a colon (`:`) and choose the correct template
4. You're set to go!

**Comment by va1entin** [comment]
> Here we go: I just implemented a full-features templating system which will allow you to do basically everything as, e.g., in VS Code or TextMate (in fact, it's based on TextMate's syntax).
> 
> I did not implement a "from template" function, BUT it's as easy as it can get:
> 
>     1. Create a new file
> 
>     2. It will be immediately focused
> 
>     3. Type a colon (`:`) and choose the correct template
> 
>     4. You're set to go!

For anyone stumbling upon this: The new feature mentioned in the comment above seems to be called "snippets", not "templates", and is part of Zettlr since 2.0.0 according to the [changelog](https://github.com/Zettlr/Zettlr/releases/tag/v2.0.0).
Docs: https://docs.zettlr.com/en/core/snippets/
