### ISSUE TITLE
Keyboard shortcuts: (Un)Comment selection

### ISSUE THREAD

**Issue by offray** [Zettlr/Zettlr#172]
I'm using Zettlr for translations of Markdown documents and pairing the commented original text with the translated paragraph afterwards. I have seen the [shortcuts](https://zettlr.com/docs/shortcuts), but I was unable to find any that works for (un)commenting text selections. Is there any support for it? If not, it would be a handy shortcut to have.

**Comment by nathanlesage** [comment]
Currently, no support for this, but now that you mention it, it sounds like a super nice thing to have! I only have to find a shortcut for it, but I think `Ctrl/Cmd+Shift+C` sounds reasonable!

**Comment by nathanlesage** [comment]
Piece of cake 😎
