### ISSUE TITLE
Adding citation language locale to the Pandoc line

### ISSUE THREAD

**Issue by tomislavmedak** [Zettlr/Zettlr#1720]
First kudos for developing Zettlr, a great tool to use -- particularly for people not familiar with text editors and interested in sustainable writing and publishing.

As someone who writes articles in two languages (English & Croatian), I think it would be useful to introduce an entry box where users can define the metadata filter for the language locale that will be used by pandoc-citeproc in rendering references. Namely, the rules for capital letters in titles or phrases such as "edited by" change from language to language. A metadata filter sorts this, provided the CSL file you use supports the language that you need.

For instance, the metadata filter for Croatian locale is -M lang:hr.

**Comment by nathanlesage** [comment]
Yes, this is one shortcoming I identified myself some time ago. But this will automatically work once we have implemented the defaults writer functionality. Keeping this open and will close this as soon as the new mechanism is in place. So it should work in Zettlr 2.0 by setting `lang` in the YAML frontmatter (if I don't mix some things up here!)

**Comment by tomislavmedak** [comment]
Wonderful. And keep the good work! I've been proselatysing Zettlr to everyone I've been trying to get hooked onto writing in Markdown. I didn't use it myself, b/c everytime I would load long documents I was writing for my PhD my system - Ubuntu Linux - it would just start to hog my computer. I've gave it recently a spin and that's a huge improvement, so might eventually migrate from Atom to Zettlr. In any case I'm looking forward to using it a bit more and writing it up in my [Digital scholarship workflows](http://tom.medak.click/en/workflows/).

**Comment by nathanlesage** [comment]
Closing since in the meantime we've implemented the new system and it works as advertised!
