### ISSUE TITLE
iframes are not rendered

### ISSUE THREAD

**Issue by pvjeetze** [Zettlr/Zettlr#1721]
## Description
In version 1.8.7 iframes are not rendered anymore.

## Reproducing
Update to Zettlr 1.8.7 on a Windows 64 bit machine.

## Expected behaviour
iframes should be rendered properly

![image](https://user-images.githubusercontent.com/50408549/107264616-7698a380-6a43-11eb-8eb8-df65b4f684b5.png)

## Platform
 - Windows and version: Windows 10
 - Zettlr Version: 1.8.7

## Additional
Rendering iframes in "Preferences" is activated.

**Comment by nathanlesage** [comment]
The reason is the rendered link in the `src` here. Has to do with rendering order. I'll fix this in 2.0, until then mitigate by turning off Link rendering in the preferences.

**Comment by pvjeetze** [comment]
Thanks for the quick fix Hendrik! 👍  Looking forward to 2.0!

**Comment by nathanlesage** [comment]
Fixed the order of rendering, so that now iFrames are rendered before links, which means: They are rendered.
