### ISSUE TITLE
Gravizo support by allowing multiline image link

### ISSUE THREAD

**Issue by jakeoung** [Zettlr/Zettlr#173]
For example, I can embed gravizo image as follows:

```
![](https://g.gravizo.com/svg?digraph G {a->b a[label="df"]})
```

But I want to embed with multiple lines such as

```
![](https://g.gravizo.com/svg?digraph G {
a->b a[label="df"]
})
```

Typora currently supports this by using:
```dot
...
```

Maybe, could you consider any way to support image with multiline URL?

## Expected behaviour

**Screenshots**

## Platform
 - OS Version [e.g. 11]
 - Zettlr Version [e.g. 0.15]
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
I see your point. However, [according to the Markdown specification, images are inline elements](https://spec.commonmark.org/0.29/#images) and therefore cannot contain newline characters. Therefore I cannot implement your desired behaviour.
