### ISSUE TITLE
How to debug the main process in the new version zettlr?

### ISSUE THREAD

**Issue by Zheng392** [Zettlr/Zettlr#1731]
The new version of zettlr has used  the typescript and vue.js, how can I debug the main process now with visual studio code?

**Comment by nathanlesage** [comment]
According to the documentation it should work out of the box, but for me VSCode always tells me it can't find the correct binary. I didn't have the motivation to look for the cause by now. If someone wants to fix this, PRs gladly welcome.

**Comment by tobiasdiez** [comment]
Do you mean the following error ?
ERROR in unable to locate 'D:/Programming/Zettlr/source/main/modules/export/assets/template.revealjs.htm' glob

I'm currently also not able to show the developer console (Ctrl + Shift/Alt + I). Is there a workaround for this?

**Comment by nathanlesage** [comment]
> Do you mean the following error ?

Nope, this one:

```
/Users/hendrik/Documents/dev/Zettlr/node_modules/.bin/electron-forge-vscode-nix . --remote-debugging-port=9223
Process exited with code 1
Uncaught Error: Cannot find module '/Users/hendrik/Documents/dev/@electron-forge/cli/dist/electron-forge-start'
```

As to missing dev tools … ehm … I've basically bricked a lot of the core functionality because there's so much bad stuff in there (so you can prepare for a hefty commit in the next week or so)

**Comment by nathanlesage** [comment]
Small update: Decided I can give the code as is to you now. Many things in the new window still don't work, but this way you have an easier job following my ripping-apart-the-highway flow.
