### ISSUE TITLE
RPM dependencies missing

### ISSUE THREAD

**Issue by maweki** [Zettlr/Zettlr#1732]
## Description
First of all, I am sorry about not providing a PR. I have no idea about packaging.

On one of my machines I am using Fedora Silverblue and the workflow basically prohibits installing bare rpm packages (waiting for #1084). What I do is, that I install rpm packages in a podman toolbox (podman container with own root but shared home) that basically has no packages, even ones necessary for the desktop environment, etc.

As I was trying to install `Zettlr`, the following packages had to be installed as libraries were missing and startup failed: `libX11-xcb libdrm mesa-libgbm alsa-lib`

These need to be included in the Fedora rpm's dependencies.

## Reproducing
Install zettlr rpm in a podman container, follow the error messages.

## Expected behaviour
all dependencies are provided.

## Platform
 - OS and version: Fedora 33 Silverblue
 - Zettlr Version: 1.8.7

**Comment by nathanlesage** [comment]
Do you mean something like [this key here](https://www.electron.build/configuration/linux#debian-package-options)? (also applies to RPM files)

**Comment by maweki** [comment]
> Do you mean something like [this key here](https://www.electron.build/configuration/linux#debian-package-options)? (also applies to RPM files)

Without looking into it, I somehow thought we did the packaging ourselves. I believe the missing dependencies are missing upstream in what Electron packages and not with our own dependencies. I will look into opening that ticket against Electron.

**Comment by nathanlesage** [comment]
Alright, thank you! Report back with what they say! We in fact do the packaging ourselves, only the compilation is done by Electron.

So we basically download the correct binary, but the packaging into the RPM-package is done by ourselves. And I think we have to specify these dependencies. However, there's is also a default in `electron-builder`, which we use for this. So maybe there is a better place to start …?
