### ISSUE TITLE
Open-file dialog somehow unfocused when opening via menu

### ISSUE THREAD

**Issue by maweki** [Zettlr/Zettlr#1733]
## Description

I am running Zettlr on Fedora 33 Silverblue in a podman container. When selecting the "Open File" or "Open Workspace" options via the menu, the open-dialog does not accept any input. You can't select a file or close the dialog. The dialog can be closed via `F4`. If you change the size of the Electron window, it is now possible to select an option in the Dialog. Selecting another window and reselecting the dialog does not work. The Electron window needs to be resized (or moved, other interactions with the main window also seem fine) and then the dialog works.

If the dialog is opened via the quicklaunch icon below the menu bar, the dialog works.

Maybe there's some wating-for-signal-code in the menu that needs to release some window handler or something. 

## Reproducing

https://user-images.githubusercontent.com/613272/107671199-df765a80-6c93-11eb-824b-5543bd9bbb35.mp4

## Platform
 - OS and version: Fedora 33 Silverblue
 - Zettlr Version: 1.8.7

## Additional information

Edit: this issue also presents on regular Fedora 33

**Comment by nathanlesage** [comment]
Might this also relate to the different bug with regard to the modals in #1645 ? I will have a look either way!

**Comment by maweki** [comment]
Seems to be the same bug. I continue over there. Close this issue at your discretion.
