### ISSUE TITLE
[ENHANCEMENT] Allow images to be copied via mouse right click

### ISSUE THREAD

**Issue by hipitihop** [Zettlr/Zettlr#1737]
## Description

I take notes and embed images with them in Zettlr, but frequently I use those notes elsewhere, for example github issues and I would like to be able to copy paste those images via the clipboard.

## Proposed Changes

Add an item to the Zettlr right mouse menu which allows you to `"Copy image"` to the clipboard.
This should probably go within the same group as the existing "Copy" & "Copy as HTML"

Existing popup menu
![image](https://user-images.githubusercontent.com/4626024/108019807-b88aa080-7066-11eb-980a-1ed8461598f9.png)

**Comment by nathanlesage** [comment]
Good idea. I wanted to improve the context menu of the editor either way to account, e.g., also for citations, etc.
