### ISSUE TITLE
[FEATURE] generating footnotes like in obsidian with ^[text] 

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#1738]
## Description
I would like to generate footnotes like in Obsidian so that I can use both programs. 
In Obsidian you can simply do this ^[text] and it generates the numbers and puts the text in the footer (in preview mode)

**Comment by boutil** [comment]
Hi,

Zettler already implements footnotes, with marks of the form [^1], [^2]. If you type Ctrl+Alt+F (on windows and Linux at least), this will insert a footnote mark (with the next integer available) and create the reference tag at the end of the document where you can insert the text of the footnote itself. You can Ctrl+click on the tag to edit the footnote text in a text zone popup.

See <https://docs.zettlr.com/en/core/editor/#working-with-footnotes> for more details. Do you mean something more than that?

**Comment by JJger148** [comment]
the thing is, if I add footnotes not in order, I get confused when I look at the numbers in the bottom of the page. 
If the numbers in the text body would automatically be updated, or just appear like this ^[] it would be less confusing.

**Comment by nathanlesage** [comment]
Unfortunately, Obsidian is using a non-standard syntax for footnotes. There are two types of footnotes we can make use of, which are described here: https://pandoc.org/MANUAL.html#footnotes

With regard to the numbering, that's a different story, but that has no priority right now, as the numbers are correctly put on export. I'll try to see to improving that other algorithm for 2.0.
