### ISSUE TITLE
[Feature Request] Extension of in-view markdown rendering

### ISSUE THREAD

**Issue by CxRes** [Zettlr/Zettlr#174]
I really like the way Zettlr has been coming along. It is so rare to see code that actually has a basic level of comments!

However, I find Zettlr is a little light on markdown in-view rendering when compared to some other products. I recently came across another open-source project called [HyperMD](https://github.com/laobubu/HyperMD), also based on Codemirror that can render a far greater range of markdown syntax and with many other extensions such as flowcharts and mermaid diagrams. Some ideas such as displaying math formula in a dialog as you are typing it is really nice as well. 

With this issue, I am hoping to persuade to include some of its goodies or better still join forces with @laobubu in making Zettlr even more awesome!

**Comment by nathanlesage** [comment]
Phew … looks interesting! Here are some thoughts:

- HyperMD looks really nice, but CodeMirror is already extremely deeply integrated within Zettlr, so that switching the underlying editor may very well take a lot of time.
- I'm still convinced that Markdown actually shouldn't be to display **everything** just like a WYSIWYG-editor, because this was one of the major and main reasons why I switched from Word processors to Markdown
- Most of the really important stuff is already present within Zettlr, and this way I know that things will work. I've had it several times that even when I updated CodeMirror I had to fork some of the plugins because they broke some functionality I needed. I don't really expect this to become less with an editor that incorporates a lot of the higher-order functionality (because it is more difficult to remove features one does not want than adding the ones one wants)
- CodeMirror will in the foreseeable future be released in version 6, and I really look forward to it to integrate it into Zettlr to make it more free for disabled people. It would take some more time and there's no guarantee that HyperMD will switch to CodeMirror 6 as well. In this case, accessibility counts more than cool but, quite literally, mainly visual, features.
- Besides, concerning the Mermaid and flowcharts request … there's already some issue I think open that demands it. And it shouldn't prove difficult, because let's be blunt: Most previewing stuff is so simple to embed it just takes duplicating a file and adding different contents … which reminds me I need my own class for that stuff!

What do you think?

**Comment by CxRes** [comment]
Since you asked (and I am sorry for being so verbose in advance)...

Let me start by explain where I am coming at this from. I have a background in engineering and physics, and despite it all being clubbed under STEM these days, they have widely differing cultures. I am sure that differences, say, in two field of humanities is similarly different than the higher level cultural differences drawn out between soft and hard sciences (at least as far the culture of communication goes).

In physics, Latex is a de-facto standard. However, from the very first time I encountered I found it disturbing to see so much mark-up mixed in the content that you could not reasonable follow an idea when seeing the document in raw form. The happy compromise I found was Lyx, which advertises as WYSIWYM (since WYSIWYG has been taken to mean how something would look on paper), but it is WYSIWYG in terms of Latex markup for all practical purposes (despite claims to being a general front-end see eg its ERT facility). Lyx's military focus on WYSIWYM however really discourages simple things, like putting line breaks in text, not for rendering but just as a reminder to self that something else is meant to go there eventually. 

On the other end of the spectrum, that one encounters in engineering, is the word processor (read MS Word though open-source community has made some unnecessarily valiant effort). Whereas you can see what you wrote without encumbrance, you end up in a situation where the tail (document) wags the dog (author). You have to finger paint the document and have no control as to what it really ends up doing, except you hope against hope that it wont look too bad. 

And lets not even get into DTP.

What I am leading to is the common ground that we share. We want something that allows us create content easily and with full control while at the same time to visualize and analyze the content that we create. We can agree that Markdown (and other minimal markup formats/languages?) fits somewhere in this sweet spot.

But as you can see there is tension between the two requirements and the format itself is insufficient to solve the issue. The fact that you format the preview rather than present it as plain text is an acknowledgement of this tension and plain-text markup itself inadequate. And here I would humbly differ from you in some of the choices made in Zettlr. The difference I think are small technically and presentation-wise but the cumulative effect imho is significant.

While I agree everything should not be completely WYSIWYG, I tend to lean toward it a bit more than you do. Perhaps I am in the Edwards Tufte's camp that believe in it being paramount to be able to see your content and your semantic intention as clearly as possible. Controls and markup take away from that and should be tucked away when possible. Take, for example, emphasized text can instead be presented as italicized until the user clicks on it, when the control of asterisks/underscore re-appears. You will have to admit that even that asterisks/underscore in the body of the text is the slightest of distraction from the text and maybe its appearance can be minimized until the need to edit (while still retaining control which word processors take away). Intent is still visible without the markup being shown all the time and editing can be done using markup. I think this is one place where closed source editors like Texts or Typora are easier on the eye (perhaps both versions can be implemented here within the same code with the choice under a flag).

Yet, in other places Zettlr leans towards being too WYSIWYG. Take, for example, latex equations. I think this is one place where Lyx shines over anything else I have seen. Equations are rendered as you type and having math toolbars is a blessing for those who do not know the Greek alphabet and every mathematical operator by heart. In Zettlr one has to go out of editing mode to see what the equation looks like and then back in to make changes, which I cannot stress enough is a pain (In general while preview is simple, preview with live editing is a hard problem). HyperMD is a bit better as you can see a live preview in a mini window; perhaps that latter kind of functionality at least would be easier to accommodate into Zettlr. Also I do not think Zettlr should run away from representing formats where editing is text based (especially if they are popular, like math). 

I think Zettlr still has some way to go, whether in terms of mark-up highlighting (closer to your preference) or inline preview with markup shown on focus (my preference). There are many markup syntax features, say within pandoc (since that is the preferred engine for eventual output), that are not yet interpreted/prettified by Zettlr. Then there would be a number of things that are just nice to have. eg live bibliography (where clicking @reference follows the URI to the document) or sidenotes (which is how I make notes on paper).

Even though I am being critical of choices made in Zettlr, I am able to do so because your work is open source. Unemployed researchers like yours truly (ie who are working on their own dime) are eternally grateful for the effort that people in the open-source community like you put in (again on own your own dime). All we want is that the open project comes out to be the best possible thing even though we may have a few differences (I think we generally agree on the principles) as to what that best thing is!

**Comment by cben** [comment]
CodeMirror is great for in-line replacements!  Math inside Codemirror has been done several times, HyperMD is Codemirror-based too.
A possibly notable comparison for researchers is Overleaf — their ["rich text" mode](https://fr.overleaf.com/blog/new-overleaf-v2-features-rich-text-and-adding-linked-files) also did it with CodeMirror in v1, not sure about v2 after merge of ShareLaTeX which was based on Ace.
https://tex.stackexchange.com/questions/308256/editors-with-rich-text-viewing-similar-to-overleaf has some more links.
(I also have an implementation https://github.com/cben/CodeMirror-MathJax/ powering https://mathdown.net but at this point it's not the most bug free)

>  Equations are rendered as you type and having math toolbars is a blessing for those who do not know the Greek alphabet and every mathematical operator by heart. 

This goes beyond "rendering".  https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors has a list of editors, from those I tried http://mathquill.com/ was by far the smoothes.

**Comment by cben** [comment]
Umm sorry, I jumped to commenting before actually using Zettlr, and missed that it already does math preview.  I'll come in again after I've done my homework :smile:
