### ISSUE TITLE
Turn off readability in frontmatter

### ISSUE THREAD

**Issue by lsolesen** [Zettlr/Zettlr#1740]
## Description

When turning on the readability mode, all the yml in the frontmatter is also highlighted, and how the frontmatter is shown is changed.

## Proposed Changes

Leave the frontmatter alone.

## Caveats

There might be excerpts or other things in the frontmatter, which might have longer pieces of text, that might need accounting for getting a readability analyis.

**Comment by nathanlesage** [comment]
Yeah, there's a lot of room for improvement for the readability mode, I agree!
