### ISSUE TITLE
[ENHANCEMENT]  Hide left sidebar with button (MacOS style)

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#1742]
## Description

Since the app is getting a general overhaul, I would like to ask for adding a button for hiding/unhiding left sidebar.
This kind of UI is really popular in MacOS and its part of this system guideline, but it also really handy and would work for other systems too. This is the one feature that I miss in the current Zettlr. Ability to fast show/hide files would help me focus on writing. 
Currently present "Distraction-free mode" is doing too much, apart from dimming the screen is not easily accessible in one click from the main screen.

## Proposed Changes

Add button in the left part of the bar with icons.
This Button would allow toggle/untoggle left sidebar showing files.
## Caveats

No other feature will be affected,   the only risk is an additional clutter with more icons on the main bar.

**Comment by nathanlesage** [comment]
Just for clarity: Left sidebar is the file manager. The "actual" sidebar is the one on the right!

Feel free to look through the [Clarity Icon set](https://clarity.design/foundation/icons/) to find a good looking icon (we had some troubles finding the sidebar icon ourselves, but maybe with a fresh mind & a user perspective you have a better time)

**Comment by danieltomasz** [comment]
> Just for clarity: Left sidebar is the file manager. The "actual" sidebar is the one on the right!
> 
> Feel free to look through the [Clarity Icon set](https://clarity.design/foundation/icons/) to find a good looking icon (we had some troubles finding the sidebar icon ourselves, but maybe with a fresh mind & a user perspective you have a better time)

I remembered that this was the convention here, but macOS's convention of naming things is too intrusive ;)

About the icon, I could have several propositions 
* library - since the file manager actually fits the metaphor of a  library and how people  use files  there
* I was thinking of "home" - but it has too many other connotations
*  folder is too  similar to folder-open unfortunately
* tree-view or tree-list visually also suits the metaphor of file tree

So my vote would be for the library icon, but tree view could be also interesting to use

**Comment by nathanlesage** [comment]
Hmm … I could imagine we might need the library icon for something citeproc-related, might that be? In this case the tree-list icon would be more fitting. Actually it has also been already used on the file manager, so this might fit better. What do you think?

**Comment by danieltomasz** [comment]
> Hmm … I could imagine we might need the library icon for something citeproc-related, might that be? In this case the tree-list icon would be more fitting. Actually, it has also been already used on the file manager, so this might fit better. What do you think?

Tree view might work.  If you still are looking for other alternatives, maybe layers?

**Comment by danieltomasz** [comment]
@nathanlesage  do you use file-group somewhere? file-group this is also semantically close to meaning what "file manager and not sidebar" is

**Comment by nathanlesage** [comment]
As I mentioned on Twitter: It's in!
