### ISSUE TITLE
Rendering bug: flickering 

### ISSUE THREAD

**Issue by fstamour** [Zettlr/Zettlr#1743]
## Description

When entering a multi-line bullet point, followed by an _empty_,
indented bullet point (see example in `Reproducing`). Then the extra
lines in the parent bullet change formatting (I think it's bold and
bigger font size). And then it flicker between that formatting and the
correct formatting after every action (like typing or selecting a
character).

## Reproducing

Enter something like this:

```markdown
- afsfasdfa
  asdfae
  -
```

And this is what I get:

https://user-images.githubusercontent.com/2881922/108366627-95770280-71c6-11eb-8fa4-716130d374e1.mp4

## Expected behaviour

The formatting shouldn't change at all (for the case I provided)

### Child bullet must be empty to trigger the bug

It doesn't seem to happen when the child bullet is not empty, like this:

```markdown
- afsfasdfa
  asdfae
  - I'm not empty
```

### The caret is also affected

https://user-images.githubusercontent.com/2881922/108368362-5944a180-71c8-11eb-9f13-a6b24d9095c1.mp4

## Platform
 - OS and version: Windows 10 Version	10.0.19042 Build 19042
 - Zettlr Version: 1.8.7 (I just installed it a few minutes ago)

**Comment by kyaso** [comment]
Can confirm this for Linux as well (Ubuntu, Manjaro).

**Comment by geoffadams** [comment]
Issue is also present on Mac OS 10.15.7 with Zettlr 1.8.7.

**Comment by boutil** [comment]
If the bullet is empty, there is an ambiguity in its interpretation: bullet for a list, or underline of the line above, as a mark for Setext-style headers. It seems to switch between the two interpretations at each new character. A workaround is to not leave a bullet with an empty item

**Comment by nathanlesage** [comment]
Simple explanation: The renderer thinks it's a Setext heading level 2. I don't know how far I can add this exception, but I'll add it to the 2.0 list. (Until then, use asterisks or plus signs for this case, these will work easily)

**Comment by nathanlesage** [comment]
That bug has been solved recently by some work on the heading detection. Multi-line stuff like SeText headings are a curse in CodeMirror's purely line-based highlighters …

**Comment by fstamour** [comment]
Great! ❤️
