### ISSUE TITLE
Slow to open a *.md with a large workspace

### ISSUE THREAD

**Issue by erickod** [Zettlr/Zettlr#1744]
## Description

Slow to open a *.md

## Reproducing

It happens when you have a workspace with 800+ *.md files.

## Expected behaviour

More responsiveness when to open a *.md file

## Platform
 - OS and version: Manjaro
 - Zettlr Version: 1.8.7

**Comment by nathanlesage** [comment]
I am very sure this will work well on the 2.0 branch due to numerous refactors, however, I'll be keeping this open for the meantime to double-check it once we're in beta

**Comment by nathanlesage** [comment]
The 2.0 branch is right now capable of handling even bigger workspaces than 800 files with ease, so the issue is resolved & the fix will ship with 2.0
