### ISSUE TITLE
Update Zettlr manifest in winget

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#1745]
Winget is something like apt get, just for Windows. Zettlr is listed, but only an old version (1.6). It would be good if this could be continuously updated to the latest version.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/Zettlr/Zettlr/1.6.0.yaml

@Wav3

**Comment by Wav3** [comment]
I've manually updated the Winget manifest to version 1.8.7 (See [winget-pkgs#7873](https://github.com/microsoft/winget-pkgs/pull/7873)).  
I'm trying to update the manifest as soon as possible if a new version is released.
