### ISSUE TITLE
[BUG] Unclear how to "refresh" IDs (or whether it's even possible)

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#1746]
## Description
When I change the ID format in the Preferences dialog, it doesn't seem to affect the IDs that show up in the left-hand (file listing) pane.  I have tried everything up to closing and reopening the software, and closing and reopening the folder; no luck.

## Reproducing

1. Start with the default ID pattern `(\d{14})`.
2. `Ctrl-N` to create a new file, but append some text to the filename, e.g., `20210221125319_file_a.md`.
3. Observe that the ID in the left hand pane is `20210221125319`.
4. Change the ID pattern to `(\d{14}[\w-]*)`, so as to include any appended text in the filename as part of the ID.
5. Repeat and modify step 2, but name the file `20210221125429_file_b.md`
6. Observe that the ID in the left hand pane has the new format, `20210221125429_file_b`, but the ID for the old file is still in the old format, `20210221125319`.

## Expected behaviour

Zettlr should either update IDs immediately on an ID format change, or else provide the user a means to do so manually.

Yes, ideally, the ID should never change.  :slightly_smiling_face:  However, I'm new to Zettelkasten, and I'm still figuring out what works best for me.  It's better if I can avoid getting into a state with a mishmash of confused ideas---or at least, if I _do_ get into such a state, if there's a way for me to get out of it.

## Platform
 - Ubuntu Linux 20.04
 - Zettlr Version: 1.8.7

## Additional information

I found some items in `~/.config/Zettlr` which appear to be caches, but I decided not to blow them away.

**Comment by chiphogg** [comment]
By the way: my current "alternative" for doing this is:

1. Uninstall Zettlr.  (Now there is no installed application for the cache/config folder to refer to.)
    - (For me, this was `sudo dpkg -r zettlr`.)
2. Blow away the cache/config folder.
    - (For me, this was `rm -Rf ~/.config/Zettlr/`.)
3. Re-install Zettlr.
4. Edit Zettlr preferences to be the ones I want, _particularly_ including ID pattern.
5. Close the "default" workspace; re-open my workspace.

**Comment by nathanlesage** [comment]
Ah, the cache isn't being updated. What might help is to just edit the file in question, then the ID should become updated.

**Comment by chiphogg** [comment]
I can confirm: if you change the ID format, then edit the file, zettlr updates its ID as soon as you save your changes.  Thanks for this!

What do you think about bulk ID updates, for when you change the ID schema?  In that case, is the uninstall/reinstall dance above the best way to go?

(Note that I think a fine answer would be "IDs should almost never change, so we don't want to support this officially".  In fact, I think that's probably the answer I'd expect!  The only reason I changed my ID schema in the first place is because I was just starting out with Zettelkasten, and didn't have a good idea of the tradeoffs for different choices.  Now I've got a schema I expect to be happy with for a long time.)

**Comment by nathanlesage** [comment]
> What do you think about bulk ID updates, for when you change the ID schema? In that case, is the uninstall/reinstall dance above the best way to go?

Mh, well, in that case clearing the cache should work. The Zettlr binary accepts a command-line argument, `--clear-cache`, that instructs it to do just that. This will also be performed whenever there's an update, but you can of course do it manually in between!

**Comment by chiphogg** [comment]
I haven't tried that out (as I no longer need to update IDs), but that would perfectly serve my use case.  Thanks for your help!
