### ISSUE TITLE
Maybe I'm just missing it, but how do I see the readability? 

### ISSUE THREAD

**Issue by mgifford** [Zettlr/Zettlr#1752]
## Description
I'm looking for an open source alternative to the HemingwayApp.  This looks like a good one.  I've got it installed but can't seem to get the readability to work properly. 

A screenshot of what I should look for or where I should go to enable would be good. I've clicked all the buttons I could see. 

![Screen Shot 2021-02-23 at 1 55 29 PM](https://user-images.githubusercontent.com/116832/108893266-e16ae280-75de-11eb-9271-eaa73b7f408a.png)

## Reproducing

$ brew reinstall zettlr

Seemed to work, I then clicked on /Applications/Zettlr.app to launch it 

## Expected behaviour

I should see text which is similar to what the HemingwayApp does with their sentences. 
http://www.hemingwayapp.com/

## Platform
 - OS and version: Mac 
 - Zettlr Version: Version 1.8.7

**Comment by boutil** [comment]
Hi,

If you click on the eye icon in the toolbar, your text should be colored. The color code goes from green (good) to orange (not readable) corresponding to the score scheme you choose in the Editor tab, in the parameters.

In contrast with the Hemingway app you were referring to, there is no indication in Zettlr about how to improve your style.

**Comment by mgifford** [comment]
Ok..  No idea why that wasn't showing up before.  That's working for me now. 

Might be some ideas to pull in the other recommendations from https://www.freecodecamp.org/news/https-medium-com-samwcoding-deconstructing-the-hemingway-app-8098e22d878d/

I'm fine closing this for now though, but I am sure I clicked on it.
