### ISSUE TITLE
[ENHANCEMENT] Keep vertical cursor position where it was when typewriter mode was activated

### ISSUE THREAD

**Issue by jweickm** [Zettlr/Zettlr#1754]
## Description
I really enjoy the typewriter mode, but I would like to be able to decide on the vertical cursor position (I prefer it actually higher than the current middle-of-the-page position). 

## Proposed Changes
This could be achieved by keeping it fixed at the vertical position that the cursor was at, when typewriter mode was activated.

## Caveats
This should not interfere with existing workflows.

## Additional Information
If you want to see in action what I mean, "Writemonkey" uses that kind of typewriter mode.

**Comment by nathanlesage** [comment]
Interesting proposal, but I'm curious as to how many people would actually like this – how is this done in other editors with this feature?
