### ISSUE TITLE
[ENHANCEMENT] Open previous file/tab when `Cntr + Tab` is pressed

### ISSUE THREAD

**Issue by YoungMahesh** [Zettlr/Zettlr#1755]
## Description
- Most of the times we want to switch tab, to go to the previous file; but in Zettlr when we click `Cntr + Tab` the file which is next in the tabs-row is opened.

## Proposed Changes
- Change `Cntr + Tab` button feature to open previously opened file as in VSCode; instead of opening file which is next in tab-row.

## Additional Information
- For clear understanding, just open multiple tabs in VSCode and Zettlr. 
- Then use `Cntr + Tab` in both applications.
- You will see VSCode switches to the lastly opened tab, while zettlr switches to the next-tab in row which is most of the times not desirable

**Comment by nathanlesage** [comment]
You can use `Ctrl+Shift+Tab` to select the previous tab. The problem for me in embracing this enhancement request is the "which is most of the times not desirable"-part. For me, for instance, it's undesirable to use Ctrl+Tab and suddenly switch to the _previous_ tab. I expect a keyboard shortcut not to suddenly change its behaviour. Plus, Zettlr is not aimed primarily at technical folk, so the VSCode-anecdote doesn't have that much weight here.

It would be best to discuss this on the forum beforehand.

**Comment by YoungMahesh** [comment]
`Cntr + Shift + Tab` does not go to the lastly opened Tab, it go to the previous Tab according to the row_of_Tabs. 

For example, if I opened 4 Tabs in Tabs-section, if I go from 2nd Tab to 4th Tab with mouse-clicking, and then I clicked `Cntr + Shift + Tab`, then it goes to the 3rd Tab instead of going to the 2nd Tab.

Yes, I understand the aim of Zettlr. 

But with popularity of Zettlr, many techinal-users who loves simplicity of Zettlr started to use this app. For these users, it would be better if you create a section in settings named - **Hotkeys**, where a user can determine his/her keyboard-shortcut keys for various activites such as -  
- Search in all Files 
- Search in current-file 
- Search file-names 
- Tab-switching 
- Edit-filename 
- Fold-unfold all heading of the file, etc.

**Comment by nathanlesage** [comment]
I agree, shortcut options have been some feature many have wanted for quite some time now! Unfortunately, I haven't yet come up with a way to manage those cleanly, as there are still multiple places where these get defined … but it's surely on my list

**Comment by YoungMahesh** [comment]
OK, thanks then, I have put my message, and it was nice to talk with you. I end this conversation now. 

👏🏻 Best wishes for you and Zettlr. Bye 👋🏻
