### ISSUE TITLE
Monospaced font is not rendered as such in link text

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#1758]
## Description
If link text contains backtick-surrounded text, that text will not be rendered as monospaced.

## Reproducing
Add a link like the following:

```
[Documentation for `std::move`](https://en.cppreference.com/w/cpp/utility/move)
```

Observe that the text is all rendered in the "normal" font, whereas the `std::move` portion of the link should be rendered in monospace (as it would be if it weren't part of a link).

Note that other instances of nested formatting _do_ work.  For example, I tested the following:

```
[`std::move` is a **bold** idea](https://en.cppreference.com/w/cpp/utility/move)
```

Here, the `**bold**` will be correctly rendered in boldface.

## Expected behaviour
Backtick-surrounded text within link text should be rendered in monospace, as it would be outside the link text environment.

## Platform
 - OS and version:  Chrome OS, Version 87.0.4280.152 (Official Build) (64-bit)
 - Zettlr Version: 1.8.7

## Additional information
N/A; I think this is pretty straightforward.

**Comment by waterfallpit** [comment]
I checked this in the current development version. It seems that link text formatting is done separately in source/renderer/modules/markdown-editor/plugins/render-links.js, lines 165 and on. Hackish solution would be to insert
```regularLinkCaption = regularLinkCaption.replace(/`([^`]+?)`/g, '<span class="cm-comment">$1</span>')```
at that place, which solves the issue.

**Comment by nathanlesage** [comment]
@waterfallpit is right in this regard: We're basically pre-rendering some elements within the link, but that pre-rendered element has no access to any formatting to the left and right. But that use-case you have should be easy
