### ISSUE TITLE
[FEATURE] Please add Clojure as a Code Fenced Block Syntax

### ISSUE THREAD

**Issue by dharrigan** [Zettlr/Zettlr#1759]
## Description

Hi,

Please can you consider adding Clojure as a fenced code block recongised syntax.

https://codemirror.net/mode/clojure/index.html

Thank you.

-=david=-

**Comment by nathanlesage** [comment]
Hi, thanks! This mode is already in there:

![image](https://user-images.githubusercontent.com/17251683/109434457-c43a7780-7a15-11eb-934e-78eba6202a60.png)

Keyword, as you can see, is: clojure.

**Comment by dharrigan** [comment]
Oh,

Thank you :-) I was just reading the docs and it's not listed

https://docs.zettlr.com/en/reference/markdown-basics/#fenced-code-blocks

Great to know it's there! Thank you!

**Comment by nathanlesage** [comment]
If it's not yet in the docs, please add it, I'll merge the change asap :)

**Comment by dharrigan** [comment]
Done.

https://github.com/Zettlr/zettlr-docs/pull/100

There is one other thing, in the docs, it says, quote:

```
three backticks, directly followed by the word "javascript" on an empty line.
```

That doesn't appear to be the case, I think it's more like this:

```
>  ```javascript
let x = 10
>  ```
```

i.e.,

```
three backticks, directly followed by the word "javascript".
```

Putting the syntax word, i.e., `javascript` on a new line doesn't seem to render the content correctly. 

(at least that's what happened when I tried it)

-=david=-
