### ISSUE TITLE
Copy paste doesn't work with the shortcuts : Ctrl C/V

### ISSUE THREAD

**Issue by h0ffnr** [Zettlr/Zettlr#1764]
## Description

The title is quite explicit to my problem, for no logic reasons during a writing session the ctrl c/ ctrl V stopped working. Since then, (the incident was about two weeks ago), the issue has remained the same. 

## Reproducing

Ctrl C/ Ctrl V anything using the shortcuts instead of the right click option. It seems something else is happening as sometimes the cursor scroll down, as a page down scroll, instead of copy/pasting. Others classicals shortcuts seem to work (CtrL Z/S/A...)

## Expected behaviour

Normally Copy paste text or Image 

## Platform
 - OS and version: Windows 10 updated 
 - Zettlr Version: Zetllr 1.8.7 64 bits 

## Additional information

I've reinstalled a couple times the software without sucess, also the shortcut works perfectly on any other software including other markdown soft. It's quite annoying since this shortcut is always in need. Does have this issue ever happen before ? I checked others issues and I seem to be alone with this issue. 

I hope I haven't made a dummy mistake, thank for your time, hoping this will resolves easily. 

Nice day to you.

**Comment by waterfallpit** [comment]
I can't replicate this behaviour, but perhaps you can determine what is going on by using developer tools.
Go to Zettlr preferences and enable debug mode in the Advanced tab.
Then: Develop -> Toggle developer tools
Once there, got to Performance tab.
Hit record.
Go to Zettlr and try pasting some text with ctrl-V.
Go to developer tools and stop recording.
Look at the FPS vs. time and the CPU vs. time graphs and isolate the interval of pasting.
Click on individual boxes that represent portions of code and look at the Call tree and Event log if you can spot what is wrong with the shortcuts.

Example when using ctrl-V:
![image](https://user-images.githubusercontent.com/31076407/109876627-4b842700-7c72-11eb-82fb-e589ed49a103.png)

**Comment by nathanlesage** [comment]
If the shortcuts have stopped working at some point with no apparent reason, and even reinstallation hasn't helped, this might indicate two things: Either you've stumbled upon a very weird bug, or maybe another software on your computer has registered Ctrl+C/Ctrl+V as global shortcuts for Zettlr (there is software that just does this).

An easy mitigation would be:

1. Close all roots
2. Restart the app
3. Load an innocent, new folder
4. Try to type and see if Ctrl+C/Ctrl+V work there
5. If they does, begin re-opening all your roots and see when the behaviour starts to occur
6. As soon as it does, see exactly what's different at the folder/file you've tested this behaviour with, and report back so we can figure this out!
