### ISSUE TITLE
Window navigation icons not like system setting

### ISSUE THREAD

**Issue by mokkin** [Zettlr/Zettlr#1768]
## Description

The minimize, maximize and close icons are unfortunately not following the system settings. In my case they are on the left side.
## Reproducing

Change window icons to the left side and compare with Zettlr.

## Expected behaviour

Zettlr should follow system config.

## Platform
Zettlr Version: 1.8.7

System: linux 5.4.0-66-generic (architecture: x64)

## Additional information

![grafik](https://user-images.githubusercontent.com/2938748/110206134-4f839500-7e7c-11eb-945c-d28c9f3d9707.png)

![grafik](https://user-images.githubusercontent.com/2938748/110206145-5ca08400-7e7c-11eb-9bb4-5b52852073db.png)

**Comment by nathanlesage** [comment]
Soooo, short update on this one: Native window icons for Linux are now done. However, in order to make the app REALLY follow the native styles, you must use the "native" application style, it's a setting in the preferences.
