### ISSUE TITLE
Readability mode begins to fail when switching between files with readability ON.

### ISSUE THREAD

**Issue by pmullhaupt** [Zettlr/Zettlr#1777]
## Description

If Readability is ON when changing files, the Readability button no longer works.

## Reproducing

1. Open a file.
2. Click Readability, (It works).
3. Change to another file.
4. Click Readability, (Readability does nothing).

Note 1:  If the user clicks readability OFF before switching files it seems to work correctly.
Note 2: Sometimes the app starts up in the state where the Readability button is not working.  Restarting the app usually fixes this.

## Expected behaviour

My suggestion is that Readability should automatically turn OFF if the user switches files while in Readability mode.

## Platform
 - OS and version:  Windows 10
 - Zettlr Version: 1.8.7

## Additional information

I love the app!  It's the best markdown editor for a chromebook, (running on the Linux beta).

**Comment by nathanlesage** [comment]
Yup, there are some problems with that involved, but they're on my radar and I'll fix these with 2.0!

**Comment by nathanlesage** [comment]
Fixed that a few days ago
