### ISSUE TITLE
Project export removes word links

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#1780]
## Description

When exporting a project, [[links]] are deleted including the respective words. Leaving weird gaps or breaking the sentences in the final PDF.

## Reproducing

Export project containing file with [[links]] in it.

## Expected behaviour

You should have the option to specify what happens to links (like in the export tab) and ideally unlink the [[links]] but keep the words there.

![image](https://user-images.githubusercontent.com/44082853/110789523-e202aa80-8267-11eb-9198-09c8d4316cc2.png)

![image](https://user-images.githubusercontent.com/44082853/110789594-f47ce400-8267-11eb-91e2-4f73d6582401.png)

![image](https://user-images.githubusercontent.com/44082853/110789718-1aa28400-8268-11eb-904d-e7f13e43901b.png)

## Platform
 - OS and version: Windows 10 x64
 - Zettlr Version: 1.8.7

## Additional information

Can't wait for the next update, looks awesome!

**Comment by nathanlesage** [comment]
Huh, I must've simply forgotten to include that setting in the project options! Will keep this open for 2.0

**Comment by nathanlesage** [comment]
Should be fixed in the current exporter for 2.0.0.
