### ISSUE TITLE
Triple-click selection of entire line extends beyond it

### ISSUE THREAD

**Issue by montd** [Zettlr/Zettlr#1781]
## Description

When selecting entire line of text via mouse triple click, although invisible, the selection extends to the next lower line, so if one would apply text formatting using a shortcut (for example bold) part of the lower line would receiver formatting as well.

## Reproducing

![Zettlr-11-03-2021 21_14_28](https://user-images.githubusercontent.com/33810914/110851334-2f573a00-82b1-11eb-8046-0a2a6096bf09.png)
1. Quickly triple click with LMB thus selecting one line of text  
![Zettlr-11-03-2021 21_14_35](https://user-images.githubusercontent.com/33810914/110851367-38e0a200-82b1-11eb-9976-90d583fc94b1.png)
2. Apply bold formatting (Ctrl + B)
![Zettlr-11-03-2021 21_14_43](https://user-images.githubusercontent.com/33810914/110851372-3c742900-82b1-11eb-8c1e-30c7cf6f216f.png)

## Expected behaviour

Only the selected line should receive formatting.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.7

**Comment by nathanlesage** [comment]
This sounds as if CodeMirror includes the final newline in the selection; should be fairly simple to mitigate for 2.0
