### ISSUE TITLE
Document how to remove top and left padding for easier note taking

### ISSUE THREAD

**Issue by drcursor** [Zettlr/Zettlr#1797]
I'm trying to remove both the left and top padding so that the app can be easily used for note taking.
As per this tweet : https://twitter.com/zettlr/status/1048237021561593856 , when the window is resized it supposedly  removes those padding distances.
I was able to remove the left padding by adding the following to Custom CSS:
` #editor .CodeMirror {
    margin-left: 5px;
  }`

I've tried to figure out, using the dev console what is causing the top padding without success. I don't understand why that top space is there, nor what its function is, and I would really love to be able to suppress it.

<img width="511" alt="Screenshot 2021-03-15 at 18 03 59" src="https://user-images.githubusercontent.com/1838337/111271120-0d531400-8631-11eb-8c61-b34f1246a0a7.png">

Sorry for the noise, thank you in advance to any help you can give.

**Comment by nathanlesage** [comment]
A look in the devtools helps to pin down the rule in question – see the bottom right of this screenshot:

![image](https://user-images.githubusercontent.com/17251683/111279777-5740f780-863b-11eb-8147-6f7b13750153.png)


P.S.: This is not an issue that belongs onto the main issue tracker. For these things, please in the future consult [reddit](https://www.reddit.com/r/Zettlr) or the [forum](https://forum.zettlr.com). Additionally, here's the documentation you are searching for: https://docs.zettlr.com/en/core/custom-css/
