### ISSUE TITLE
[ENHANCEMENT] Add Pascal to the code blocks

### ISSUE THREAD

**Issue by trayres** [Zettlr/Zettlr#1799]
## Description
Add Pascal to the code block regions. Hey, it's a valid language in 2021. FreePascal is awesome. Or in my case you're reading "Thinking Recursively" from 1986 and you're taking notes... But Pascal is still alive! I promise!

How will this aid in non-technical text workers: Well, if they're writing about the history of computer science, they'd dearly miss Pascal highlighting! You can write a history book and not be technical. Pascal is still a valid language to start new projects in with how awesome FreePascal is... why is nobody staying for my Ted Talk?

## Proposed Changes
It looks like the file: 
Zettlr/source/common/modules/markdown-editor/modes/multiplex.js needs to add a Pascal item
and the CodeMirror mode must be added here:
Zettlr/source/common/modules/markdown-editor/load-plugins.js
and the autocompletion must be added here for the drop down:
Zettlr/source/common/modules/markdown-editor/hooks/autocomplete.js

I can open a PR to do this if nobody else cares (about Pascal?! Why not, it's a great language!)

## Caveats
I don't think this change would significantly change anything negatively. That said, I don't really know enough about Electron to be a source of truth so uh, big dash of salt there.

## Additional Information
Zettlr is awesome, and I need you to know that.

**Comment by nathanlesage** [comment]
If there's CodeMirror mode for Pascal, go for it - the only place you missed where this mode needs to be added is in the autocomplete plugin of the editor. Feel free to open a PR.
