### ISSUE TITLE
[FEATURE] In-document links

### ISSUE THREAD

**Issue by esarbe** [Zettlr/Zettlr#1800]
## Description
Allow links to not only refer documents but allow to target a section of a document with a link. Sections and subsections are specially annotated to provide a consistent id for the link that survives changing of the section title.

## Example Workflow
After a suggestion for link has been accepted by the user, provide a list of sections and subsections that have been provided with an appropriate annotation

## Caveats
Easy to lose links when changing structure of  a document.

**Comment by esarbe** [comment]
I'm sorry if such a feature has been proposed before, I didn't find a related feature while skimming the existing issues. Zettlr is really neat, thanks for the hard work.

**Comment by nathanlesage** [comment]
Should be able to integrate by leveraging existing ToC-functionality

**Comment by esarbe** [comment]
That would be neat.
