### ISSUE TITLE
Footnotes issues

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#181]
I do not know that this are **true** issues or just the way the app is supposed to have but I mention them anyway.

The first one is that, when I hover over a footnote, a `Ctrl+Enter` gives me a window where I can edit the text. But after I leave the window the changes are not kept (the text doesn't change in the `[^footnote]: definition...` section). I even tried `Ctrl+S` before exiting the window. The possibility to edit this way will be extremely helpful. 

The second one is the format of the footnote's definition section. Suppose I have something like this:

```
[^1]: John Doe, *The most amazing book ever written*
```

I don't understand why `John` has to belong to the classes `cm-string cm-url`? It messes up the CSS styles... It is the way it is supposed to be? 

Both issues are present on a Ubuntu based Linux distribution on the 1.3.0-alpha release (but it was the same on the previous releases).

**Comment by nathanlesage** [comment]
You can open up the footnote editing window by pressing `Ctrl+Enter`? Interesting, I never intended this to work =D

Concerning saving of footnotes: You must save them by pressing `Shift+Enter` after you're done. Simply clicking outside the window **does not save the footnote**. This is as expected, as this way you have a fast way to "cancel" footnote editing.

And concerning the styles: Well, it's an issue with the underlying Markdown mode, but I didn't find it _that_ unsettling until now ...

Please also check the docs concerning this, and if you find that it's not good described there please open up an issue that the docs need fixing! As always, I don't need the docs, and therefore I can't say anything concerning the quality of them!

**Comment by samarulmeu** [comment]
> You can open up the footnote editing window by pressing `Ctrl+Enter`? Interesting, I never intended this to work =D

My mistake, it is `Ctrl+Left Click` that it is showing the editing window and, indeed, `Shit+Enter` saves the footnote. Nice feature indeed...

I do not know what you meant by *checking* the docs. The problem is when the app is rendering the markdown file. I don't understand why the first word of a footnote definition gets a different style. I attached a screenshot of what I mean...
![footnote](https://user-images.githubusercontent.com/39216570/57367734-3e8b6f00-7192-11e9-91ac-04137c516b00.png)

**Comment by nathanlesage** [comment]
Yes, it's because in standard markdown (which is what the root-mode renders) the [^text]: Something was originally meant as a reference style for links, and not for footnotes.

Footnotes aren't actually a part of standard Markdown as of today, and therefore we can't expect the modes to do this right now. We might have to wait until CommonMark supports them :/

You can check what the markdown mode will render by having a look here: https://codemirror.net/mode/gfm/index.html

Zettlr just extends this mode to accomplish spell checking, tag rendering and Zettelkasten functionality! Have a look here for the "correct" reference style link documentation: https://daringfireball.net/projects/markdown/syntax#link

**Comment by samarulmeu** [comment]
After reading the links I understood what you meant. My mistake. You are right. 

In the end it is not the end of the world. I thought it is something in rendering the markdown. I can live with it...

**Comment by hueyy** [comment]
It might be possible (and fairly straightforward) to properly render footnotes now, without the different format style for the first word of the footnote.

From what I understand, Zettlr uses showdown for markdown to HTML rendering, so  https://github.com/tivie/showdown-ghost-footnotes and a bit of CSS styling should make footnotes render properly.

**Comment by nathanlesage** [comment]
Thank you for the hint, but this won't help the CSS of the footnotes. The underlying mode (GFM) formats the first word after the footnote description as `cm-string cm-url`, which is defined in the CSS to be rendered in the primary colour and monospace font. I could change that, but then the links from Markdown-URLs (e.g. `[Text](Link)`) won't render as well. This is what I meant that we cannot simply override that behaviour.

What would be necessary would be a complete re-writing of the mode itself, which I would like to tackle, but not now! :)
