### ISSUE TITLE
Reduce/standardise width of note when disabling sidebar

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#1813]
## Description

When the file manager is toggled off, the screen stretches so wide it is **uncomfortable** to look at.
![image](https://user-images.githubusercontent.com/44082853/111833565-423dc000-88ea-11eb-85d1-b5fe9f11334a.png)

## Proposed Changes

Either shrink to standard size (e.g. PDF viewed in browser), or allow width adjustment with slider.
![image](https://user-images.githubusercontent.com/44082853/111833025-7664b100-88e9-11eb-8280-44a5385301c9.png)

## Caveats

Slider may clutter workspace.

## Additional Information

**Screenshot from Zettlr 2.0 dev**

**Comment by nathanlesage** [comment]
Yes, I will do that before launching 2.0, but right now I'm just happy that so much just works, I wanna enjoy this feeling a few days longer before getting back to work 😅

**Comment by nathanlesage** [comment]
Oh that issue is already fixed! (although you'd need to activate the distraction free mode. This will automatically hide the two sidebars. Zettlr will leave distraction free mode once you show one of the sidebars again)
