### ISSUE TITLE
[FEATURE] Possibilty to change title of table of contents

### ISSUE THREAD

**Issue by techboy-coder** [Zettlr/Zettlr#1814]
## Description
When you export your project to a PDF, a Table of Contents section is created with the title "Contents". It would be great if you could change this default to something else. This is especially useful for people who write in different languages and would need the table of contents title in a different language.
![image](https://user-images.githubusercontent.com/71926891/111916343-b6a76900-8a7a-11eb-98a5-db61986ac59a.png)

## Example Workflow
I think one way to implement this is to add a field in the project settings window to customize the title for the table of contents section.

![image](https://user-images.githubusercontent.com/71926891/111916468-5664f700-8a7b-11eb-957b-049a0cc163a4.png)

## Caveats

It is possible that the latex template would be affected.
## Additional Information

At the end you could have something like this:
![image](https://user-images.githubusercontent.com/71926891/111916663-41d52e80-8a7c-11eb-9b46-d9170dfe593c.png)
Suggestions? Do you think this feature is important?

**Comment by nathanlesage** [comment]
You can, in your YAML frontmatter, set `toc-title: "Some title"`. See example screenshot:

![image](https://user-images.githubusercontent.com/17251683/111919248-3f2d0600-8a89-11eb-8c50-2bbb639b7876.png)
