### ISSUE TITLE
[ENHANCEMENT] Collapsible bulletpoints

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#1817]
## Description

Collapsible bullet points (at all levels).
## Proposed Changes

Following a similar system to Roam Research/Athens.

![image](https://user-images.githubusercontent.com/44082853/111979559-20685700-8afd-11eb-8011-12b9eb20b1d9.png)

Example of my (fleeting) notes in Zettlr.
![image](https://user-images.githubusercontent.com/44082853/111979907-8c4abf80-8afd-11eb-9a84-59f40bebf92f.png)

## Caveats

Although great for notes, may encorage the use of excessive bullet points that break when exported as documents.

## Additional Information

This would make those switching from a system like Roam Research/Athens feel more comfortable and enable Zettlr to be a more **general** note taking tool (rather than specifically academic).

**Comment by break6700** [comment]
I still feel this would be beneficial

**Comment by nathanlesage** [comment]
Hey, just stumbled upon this issue -- will come with the next patch! :)
