### ISSUE TITLE
Daily Note on Startup

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#1819]
## Description

Zettlr by default opens a note with the days date (instead of nothing).

## Example Workflow

When loading Zettlr with no notes open (and the user try's to enter text), create a note with the title of the days date. This could have the tag #journal, #daily-note or something similar to make it easily searchable later (and with the addition of templates could easily be changed). This replaces having to create a new note when first lauching Zettlr and I believe would leave to a more streamlined program (not to mention those that use Zettlr for a journal/daily notes).

![image](https://user-images.githubusercontent.com/44082853/112004558-d17cea80-8b19-11eb-95bd-0024da253e62.png)

## Caveats

Requires the implementation of templates to avoid the feature being anoying or potentialy the option to configure it so it just opens a blank note.

**Comment by webbj74** [comment]
Such a feature should also have configurable directory and filename (e.g. to be compatible with the macOS NotePlan app, I'd want my daily file to be named YYYYMMDD.md and exist in the Calendar directory of my NotePlan workspace).
