### ISSUE TITLE
[Enhancement] Close the sidebar with ESC

### ISSUE THREAD

**Issue by b3z** [Zettlr/Zettlr#1832]
## Description
Make the sidebar closable with ESC when open.

I just started using Zettlr two hours ago and I like it already. Still when I reached the part with the sidebar in the tutorial I spammed Escape to close it out of intuition. That's why I suggest making it closable with ESC. 

Still please maybe some more people give feedback about this since I don't know any workflows in this app so that the possibility that this change of mapping could break another folks workflow exists.

**Comment by b3z** [comment]
whut

**Comment by nathanlesage** [comment]
sry, just saw this issue in my notifications. Fortunately, no longer necessary, since in 2.0-dev the sidebar is not anymore something visually confusing as in 1.x, so don't worry! Change is coming.
