### ISSUE TITLE
system.error.open_root_error

### ISSUE THREAD

**Issue by webbj74** [Zettlr/Zettlr#1833]
## Description

Zettlr stopped loading a workspace. Instead it throws system.error.open_root_error and says the workspace is opened, however the workspace never appears in the list. No errors in the "console" (not sure where else I should look).

## Reproducing

So this happened after I was attempting to auto populate a directory & file structure from a template (i.e. I created about a hundred md files from a single source file, across maybe 10 directories). I closed Zettlr before executing this from the command-line. When I reopened Zettlr, the root directory for the workspace containing the auto-generated files vanished.

Even after moving the auto-generated files & folders, my workspace will not come back. Attempts to re-add the folder get the following:

![Screen Shot 2021-03-26 at 2 04 55 PM](https://user-images.githubusercontent.com/50980/112675737-e4efc480-8e3d-11eb-9bea-df4f30b791e3.png)

## Expected behaviour

Load my directory or give me a more specific error message explaining how to fix.

## Platform
 - OS and version: macOS 11.2.3 (20D91)
 - Zettlr Version: 1.8.7 (1.8.7)

**Comment by nathanlesage** [comment]
Would you mind attempting to open the root file and then look into the logs? (Develop -> Open Logs) There a more verbose message should appear

**Comment by Klemet** [comment]
Hey, @nathanlesage ! I'm having the same issue, and it's becoming quite difficult to open any file as all of my folders are getting "corrupted" in this way.

I can't find the "develop" option; could you give me a pointer as to where to find it ?

**Comment by Klemet** [comment]
I have an interesting development to report on this issue !

So basically, little by little, all of my working folders became stuck with this "corruption"; meaning that they were not opened in Zettlr anymore, and trying to open then resulted in the `system.error.open_root_error` error. Even worse, Zettlr was starting to have trouble opening files (I had to manually ask him to open one multiple times for it to work); and it became impossible to see different files at once (no tabs were visible).

I saw that I still didn't update to v.1.8.9, and decided to do so (I had v.1.8.8). But when I tried to update Zettlr, the installer worked like a charm (I'm on Windows 10); but Zettlr wasn't updated. Checking my Zettlr installation folder, I saw that none of the files were edited/updated by the installer.

I decided to manually delete all of the files, and try running the installer again. The installer became capable of installing the files, and when I opened Zettlr (now on v.1.8.9)...all of my folders were back, and Zettlr had once again no troubles opening any files that I wanted, and tabs were working like a charm.

I wonder if @webbj74 would have the same experience if they tried to re-install Zettlr, without deleting the personal configuration files ? I also wonder were this "corruption" might come from, if it is one. Might be Windows restricting Zettlr to do stuff, like the installer someone wasn't able to replace the existing files of my previous Zettlr installation.

**Comment by nathanlesage** [comment]
> I also wonder were this "corruption" might come from, if it is one.

+1, that sounds super weird and I have no idea where this might come from. The installers are completely automatically generated by Electron builder, but that is being used widely, and I haven't stumbled upon this issue myself :S

**Comment by Klemet** [comment]
> +1, that sounds super weird and I have no idea where this might come from

I have the same feeling. But the `system.error.open_root_error` error is still very frequent for me. Almost 1 time out of 4, when I'm trying to open a file, I get it and the file doesn't get opened. I have to restart Zettlr to make it work again, which makes things a bit cumbersome :c .

If I find anything, I'll be sure to add it here.

**Comment by kamilchm** [comment]
There's nothing more shown in the Log Viewer:
```
[15:23:50]	Trying to run command through Application: get-paths
[15:23:50]	Trying to run command through Application: citeproc-get-ids
[15:23:50]	Trying to run command through Application: set-active-file
[15:23:52]	Trying to run command through Application: workspace-open
[15:23:55]	Could not open new root file /home/kamil/notes!
```

**Comment by kamilchm** [comment]
After digging into the code, I realized I was trying to open a symbolic link to a directory, which leads to `false` here https://github.com/Zettlr/Zettlr/blob/08bcf1c4e8a88c6f274fa2e41cc95662356e448a/source/app/service-providers/config-provider.ts#L310
Everything works fine when I point Zettlr to a real directory.

**Comment by Klemet** [comment]
That's interesting ! Thank you for digging, @kamilchm .

I'm still unsure as if this is the cause of the issue. I've never tried to open symbolic links with Zettlr, yet the problem keeps happening for different folders on my computer.

**Comment by nathanlesage** [comment]
Yeah, symlinks are not yet implemented, but these shouldn't throw errors o.O

I'll have to check that.

**Comment by tsbertalan** [comment]
Still seeing this today when trying to open a really large directory. Windows 10, Zettlr 2.3.0
