### ISSUE TITLE
Outlining tool in second column, like Word commenting tool [FEATURE]

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#1834]
## Description
Having an outlining tool (like [logseq](https://github.com/logseq/logseq)) as a column left to main text. 

## Example Workflow
Like a commenting column in Word, this could serve as an outlining and commenting column next to the main text. 
Folding and unfolding of the outline column would keep the main text clean, as I can put my messy thoughts and links into the outline. 

## Caveats
If the headings of the Outline are linked to the headings of the main text, and kept at the same level, you would always have the right information next to the section you are focusing on. 
It would be similar to the commenting feature in Word, but combined with outlining. 
In focus mode this column could disappear.

**Comment by nathanlesage** [comment]
This is a very extensive feature, so I cannot promise anything with regard to this. It is unlikely something like this will be tackled 2021 and maybe not even 2022.

**Comment by JJger148** [comment]
Thats sad but I understand. I'm sure it would be a lot of work, but this would be super useful for me.
Would it not be possible to use the logseq code, since they already have a nice md-outliner and optimise it?  

When I used RemNote for doing my research I made "literature notes" but at the same time I linked quotes to my outline for my essay. This was really helpful. 

I'm sure this idea can be improved.

**Comment by nathanlesage** [comment]
> I'm sure it would be a lot of work, but this would be super useful for me.

Not to sound picky, but that is something I oftentimes hear on this issue tracker: "Would be lots of work, but good for me" – and who's going to do the work? 👀

Besides, Logseq is written in Clojure, so not even a language the Zettlr codebase would understand.

**Comment by JJger148** [comment]
I just saw your tweet about my comment on logseq. 
I apologise 🙈 I did not know how bad this comment sounded to you as a developer.

**Comment by nathanlesage** [comment]
Don't worry, I was a little bit too triggered about that myself 🙈 It's just hard to maintain such a project and then even great feature requests don't sound like great feature requests anymore for me, but increasingly like "Look what a huge pile of work that is!"
