### ISSUE TITLE
Highlight similar words to the word of active cursor position [FEATURE]

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#1835]
## Description
When the cursor is placed at a word, another words that are the same or similar should be highlighted.
As soon as the cursor is placed at another word, the highlighted word's would change. 

## Example Workflow
If the same or similar words are highlighted, I could quickly spot repetitions. 

## Caveats
very common word's could be filtered, so that they would not be highlighted when clicking on them. 
And aliases could be defined, so that acronyms or synonyms would be highlighted together. 
If the highlight would slowly appear and fade with a delay, it would even not be too distracting when writing. 

## Additional Information
This would be a simple tool that would help the writing.

**Comment by nathanlesage** [comment]
Puh, I am of the opinion that this is very distracting, since VSCode does it as well and I hate it extremely much. So I won't implement this. If enough people want this, and someone creates a PR and vows to maintain that feature, I would merge that possibly.
