### ISSUE TITLE
[SUPPORT] Chapter/Section End Notes

### ISSUE THREAD

**Issue by webbj74** [Zettlr/Zettlr#1843]
## Description

I am wondering if it is possible for all of the reference within a particular md file (representing a chapter or a subsection of the document) to go into a particular place (under a particular sub-heading in the same file) when exporting a project. Is there some trivial latex/pandoc/citeproc recipe to do this either inline in the md file or via a custom template? 

## Example example.md file:
```
---
title: Section Heading
---
### Section Heading

#### Notes

Some info ipsum [@citation1, pp. 380]. Etc etc [@citation2, pp. 5].

#### References

<!-- references for just the two citations in this file should go here on export -->

#### See also

* Note
* Link
* Etc
```

**Comment by nathanlesage** [comment]
Do you mean something like this? https://github.com/jgm/pandoc/issues/4041
