### ISSUE TITLE
[ENHANCEMENT] Better Night Mode colour palette for "Berlin" and "Frankfurt" themes

### ISSUE THREAD

**Issue by UnoYakshi** [Zettlr/Zettlr#1845]
Warnings:
  - I'm not a designer
  - I'm colour blind
  - my opinion is subjective
  - screenshots are only "Berlin" theme

So I'm all for critique.

## Description
Colour palette for "Berlin" theme isn't readable enough on Win10.

1. quoted code blocks aren't readable at all
![image](https://user-images.githubusercontent.com/5715383/113126545-6ec5d600-9220-11eb-9118-2ace706c56c1.png)
2. headlines are too whitish bright
![image](https://user-images.githubusercontent.com/5715383/113126596-7a190180-9220-11eb-85fc-fc8742ad60f6.png)
3. citing and Bold symbols are barely visible (in a bad way)
![image](https://user-images.githubusercontent.com/5715383/113126632-8309d300-9220-11eb-85cf-38c33b007a1a.png)
4. spellchecking (dotted underline) creates way more noise in the Night Mode than in normal
![image](https://user-images.githubusercontent.com/5715383/113127075-01667500-9221-11eb-86bf-cd0a13651982.png)
5. I don't really see any difference between colours in Readability Mode
![image](https://user-images.githubusercontent.com/5715383/113126885-cf551300-9220-11eb-9e04-8210d3ea3d34.png)

## Proposed Changes

1. Change the colours to somewhat complementary ones. A simple solution would be tweaking either background darker or the text brighter.
2. Use more pastel tones. Beige (`#F2DCD3`) or white smoke (`#F9F7F7`) might work. I personally prefer `#E2E2E2` for text.
3. Well, just make them brighter.
4. The easiest way is to change the underline format to a more sparse one.
5. Finding better colours for color-blind folks. Even grayscalish tones should work.

## Caveats
Not sure how the colours thing is implemented but it might need some refactoring or adding extra calculation layers to check the colours matching.

## Additional Information
P.S. I wonder if later it'd possible to have an in-app theme editor.
Example: FF plug-in that rewrites CSS
![image](https://user-images.githubusercontent.com/5715383/113144619-1c8faf80-9236-11eb-9bde-b53b8a116b1f.png)

**Comment by nathanlesage** [comment]
> P.S. I wonder if later it'd possible to have an in-app theme editor.

You can always customise Zettlr by way of custom CSS. There are some great examples over on the forum which contain CSS code to achieve other designs.

In general, you are right that many colours were simply the result of me having to think of some, but I did not – since I'm not a designer — really think it through. However, it's on my bucket list for 2.0.

**Comment by zhangfanfansz** [comment]
Hi, I am Fan Zhang from the University of Adelaide, my team and I are very interested in this issue and happy to contribute to this issue. For now, we have found the specific css code for changing the color of 
![image](https://user-images.githubusercontent.com/58411513/117753677-0d9a1500-b258-11eb-9350-53f6ffcd5ef8.png)  and 
![image](https://user-images.githubusercontent.com/58411513/117753718-1db1f480-b258-11eb-91c2-bdb0c4fc7fe4.png)

But we are encountering one issue that we can't trigger the spellchecking (dotted underline), I don't know how to show a dotted underline even I made some spelling mistakes. And I will be very appreciative if you can tell me which file controls the appearance of the dotted underline. We will do some researches to make sure the color contrast be better than the current one.

**Comment by zhangfanfansz** [comment]
![image](https://user-images.githubusercontent.com/58411513/117847769-d2ccc700-b2c1-11eb-9925-2cd618107e00.png)
For the first problem, we decided to use --beige-5 as the background color for dark mode
the following are the example of the quoted code
![image](https://user-images.githubusercontent.com/58411513/117847895-ed9f3b80-b2c1-11eb-846d-59dc9f724702.png)
![image](https://user-images.githubusercontent.com/58411513/117847911-f1cb5900-b2c1-11eb-9740-bb2abc420bf6.png)

**Comment by zhangfanfansz** [comment]
![image](https://user-images.githubusercontent.com/58411513/117850244-45d73d00-b2c4-11eb-9e06-0ee2387a6701.png)
For the third problem：
![image](https://user-images.githubusercontent.com/58411513/117850325-5687b300-b2c4-11eb-945a-516c154a15fc.png)
We increased the opacity of the escape-char to make sure they cay be seen in the night mode and not affect the normal reading in the light mode. The following are the samples:
![image](https://user-images.githubusercontent.com/58411513/117850580-99e22180-b2c4-11eb-9c7f-c87a33b2ee37.png)
![image](https://user-images.githubusercontent.com/58411513/117850600-9e0e3f00-b2c4-11eb-9b57-277115f8d145.png)

**Comment by zhangfanfansz** [comment]
And I found a bug during implementing this code, I found if I switch the language to Chinese and the preferences will not work anymore until I delete the Chinese language file within the lang directory.
![579bfdf0c93a574cde8818835bd425d](https://user-images.githubusercontent.com/58411513/117924372-cb92d100-b334-11eb-9100-ab3a83157d25.png)
![15910f9ec14dfe22c416e6683738d6b](https://user-images.githubusercontent.com/58411513/117924374-ccc3fe00-b334-11eb-96cd-8c60adc1c24a.png)

**Comment by nathanlesage** [comment]
Hey @zhangfanfansz 

First, thanks for tackling this issue. Second, please consider updating your single comment instead of adding more and more; this will make referencing the issues easer!

Then:

> But we are encountering one issue that we can't trigger the spellchecking (dotted underline), I don't know how to show a dotted underline even I made some spelling mistakes.

You have to activate spellchecking in the preferences. If no spellchecking dictionary is selected, Zettlr will not perform spellchecks.

> And I found a bug during implementing this code, I found if I switch the language to Chinese and the preferences will not work anymore until I delete the Chinese language file within the lang directory.

That sounds bad. Would you mind opening an issue for this?

Regarding the colour changes: Please feel free to open a PR and link this issue, then we can work on this. Thanks!

**Comment by zhangfanfansz** [comment]
Thanks, I have figured out how to use the spellchecking function. And the following link is connected to the color changes issue: https://github.com/zhangfanfansz/Zettlr/tree/fanzhang-new-issue
We have fixed the previous 3 problems and working on the 4th ATM.
