### ISSUE TITLE
Question mark in Spanish

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#1846]
## Description

In Spanish, every opening question mark (¿) is tagged as a grammatical error

## Reproducing

Anytime you open a question mark and write any word, is marked as error. For example:

`¿Word `

## Expected behaviour

An open question mark is not a mistake in Spanish, should not be underlined in red.

![2021-03-31_15-32-Zettl-bug](https://user-images.githubusercontent.com/10172036/113152413-66789580-9236-11eb-9f60-5ea7ecd553e7.png)

## Platform
 - OS and version: Ubuntu 20.10
 - Zettlr Version: 1.8.7.

## Additional information

Many thanks!

**Comment by nathanlesage** [comment]
There are a lot of characters which are not necessarily words which currently fall prey to the spellchecker, but I have no solution at hand right now how to mitigate this … so if anyone has, e.g., some great regular expressions to share with this regard, feel free to!

**Comment by nathanlesage** [comment]
I did have a solution at hand to mitigate that. Don't ask me what took me so long.

The ¿-questionmark is now considered a delimiter, just like brackets or quotes, and that should do the trick …
