### ISSUE TITLE
Templates for common documents

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#1847]
## Description

There are files in markdown with the same structure, tags, etc. I want to mark them as _templates_ to re use them and change certain parts of its content, saving some time in repeated parts of the structure.

## Example Workflow

I have a file in markdown to copy and paste when I create a new file, avoiding to repeat the same titles, subtitles, tags, bullet points, etc. I prefer to mark certain types of files as _templates_. When I create a new file, I want to choose one of the templates saved before to create the new file with pre loaded content and save some time writing the same over and over again.

I prefer if I can choose multiples templates, modify them or even delete templates for my new files.

## Caveats

Not for the moment.

## Additional Information

Many thanks!

**Comment by nathanlesage** [comment]
There have been several such requests in the past, and yes, it's on the bucket list!
