### ISSUE TITLE
Archives notes

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#185]
When a project is finished, you usually don't want to see it anymore but it's not a reason to delete everything.

A note or a folder should be "archived" in that case. 

Archive should be really easy to do (quick button or shortcut)

Archives is a special folder which have the following property: 
- it's folded by default (out of sight)
- it doesn't return search results by default (exception if the search is started in the archives. Optionally, it could be investigated if it's a good idea to return results from the archives if the search doesn't have any result in the other folders)

**Comment by nathanlesage** [comment]
This is already possible: Simply create an "Archive" folder somewhere on your computer, open it in Zettlr (it must be its own root folder, not inside any other folder), and when you're done with a project, simply move the full project directory into that folder using Drag&Drop.

This way search results won't show up in your regular folders, you still have them, and obviously the archive folder will stay collapsed until you explicitly select it!

**Comment by ploum** [comment]
Thanks, that's indeed a nice trick. I will consider that the feature is there.

I would argue that it might be nice to mark a folder as "archive" with a nice icon and a button to send to archive. It's not technical but it would be a way to help people with their workflow to make it more apparent.

After all, when GMail introduced the archives folder in mails, they didn't do anything else.

But, as this is not purely factual/technical decision, I understand that this is not a quick decision.

**Comment by nathanlesage** [comment]
Yes, maybe I could add a small option to tell Zettlr which one is the archive folder for some quicker actions, so I'll keep that in mind!
