### ISSUE TITLE
Cannot compile latest dev build on Win x64: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by cskeogh** [Zettlr/Zettlr#1850]
## Description

Cannot compile latest dev build on Win x64

## Reproducing

`yarn start`
```
yarn run v1.22.5
$ electron-forge start
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies

An unhandled rejection has occurred inside Forge:
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:627:9)
    at spawnWithSignal (node:child_process:775:17)
    at C:\Users\craig\Zettlr\forge.config.js:26:26
    at new Promise (<anonymous>)
    at downloadPandoc (C:\Users\craig\Zettlr\forge.config.js:25:9)
    at Proxy.generateAssets (C:\Users\craig\Zettlr\forge.config.js:77:17)
    at runHook (C:\Users\craig\Zettlr\node_modules\@electron-forge\core\src\util\hook.ts:12:7)
    at _default (C:\Users\craig\Zettlr\node_modules\@electron-forge\core\src\api\start.ts:52:3)
    at C:\Users\craig\Zettlr\node_modules\@electron-forge\cli\src\electron-forge-start.ts:58:19 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Electron Forge was terminated. Location:
{}
```

## Expected behaviour

Zettlr application starts.

## Platform
 - Windows 10
 - Zettlr Version: develop 13e533b7106205c70b1f3c3243cd16978d44ce54

## Additional information

Also reported in issue 1812 [comment  803976707](https://github.com/Zettlr/Zettlr/issues/1812#issuecomment-803976707)

**Comment by cskeogh** [comment]
This bug occurs because of the 'Spawning .bat and .cmd files on Windows' problem as discussed in the [Node.js documentation](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows) and is caused by [L26](https://github.com/Zettlr/Zettlr/blob/e19232fc47dd735f5edc57651b2bfca2a435d813/forge.config.js#L26) in [forge.config.js](https://github.com/Zettlr/Zettlr/blob/e19232fc47dd735f5edc57651b2bfca2a435d813/forge.config.js#L26):

``` typescript
const shellProcess = spawn('./scripts/get-pandoc.sh', [ platform, arch ])
```

To solve on Windows, see below. But this wouldn't work on other operating systems because of the `.exe`
``` typescript
const shellProcess = spawn('bash.exe', ['./scripts/get-pandoc.sh', platform, arch ])
```

**Comment by nathanlesage** [comment]
I've now added an easy way to run either `bash.exe` or simply the shell script depending on platform:

```js
const argWin = [ 'bash.exe', [ './scripts/get-pandoc.sh', platform, arch ] ]
const argUnix = [ './scripts/get-pandoc.sh', [ platform, arch ] ]
// Use the spread operator to spawn the process using the correct arguments.
const shellProcess = (process.platform === 'win32') ? spawn(...argWin) : spawn(...argUnix)
```

Feel free to check that we can indeed simply run "bash.exe" in every case or whether we might need additional checks for windows platforms.

If everything works, please close the issue to mark it as done!

**Comment by cskeogh** [comment]
Thank you, works great on Windows & MacOS.

**Comment by nathanlesage** [comment]
Thanks for confirming & closing!
