### ISSUE TITLE
[ENHANCEMENT] Transclusion in Zettlr

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#1858]
## Description

Include [transclusion](https://maggieappleton.com/transcopyright-dreams) in Zettlr.

## Proposed Changes

When you write in Zettlr, sometimes you want to use an idea in many notes. If the idea changes, al notes can change where that note was transcluded, because a manual change can take a lot of time, according to the number of transclusions you have. Maybe we can use the same system to render Zotero's bibliography to render markdown files.

## Caveats

The export and the graphic user interface can be affected.

## Additional Information

I [read about transclusion in this link](https://maggieappleton.com/transcopyright-dreams) and I use it in [Tiddlywiki](https://tiddlywiki.com/static/Transclusion%2520in%2520WikiText.html). I imagine [Mediawiki uses templates](https://www.mediawiki.org/wiki/Help:Templates) (but not in the same meaning than I mentioned in #1847 , those are other templates) to recreate transclusion.

Many thanks!

**Comment by nathanlesage** [comment]
Puh, transclusion is an insanely difficult thing to achieve when you want to preserve editability. I'm thinking about this since the issue was first brought up a few years ago, but I haven't yet found a sustainable way of doing so. I'll continue thinking about this, and maybe I come up with something.

**Comment by dabelmedvedovity** [comment]
Hi, 
Transclusion is already available in Obsidian. (It is called: Embed a note in another note)
https://help.obsidian.md/Linking+notes+and+files/Embedding+files

It would be great if Zettlr have a same feature (ideally with same syntax) 
Thanks!
