### ISSUE TITLE
Zettlr 1.3 beta keeps crashing on MacOS

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#186]
The beta is crashing basically all the time on MacOS (as soon as you leave the app for another one in my case).

Don't know how I could investigate this further to help you find the problem.

**Comment by nathanlesage** [comment]
Do you happen to use Zotero? If so, there's currently a bug that is being discussed on the issue trackers of the repositories in question as `fsevents` on macOS tends to crash Electron apps after multiple `watch()` calls on the same file.

Workaround: Either close Zettlr during work with Zotero, or unload the library during work. Zettlr has constantly crashed yesterday as I was doing chores in my library. Zettlr does not crash if the library file remains unaltered. Do you also use macOS 10.14.4 or an older version?

If you don't use Zotero, could you give a detailed report of what you did prior to Zettlr crashing, maybe even remember the concrete action you took at the point Zettlr did crash?

Further reference:

- https://github.com/fsevents/fsevents/issues/273

**Comment by ploum** [comment]
I don't use Zotero but my Zettlr folder is saved by Tresorit. (which is an encrypted equivalent to Dropbox).

Stopping the Tresorit app seems to solve the problem (no crash so far) .

Some facts :
- using MacOS 10.14.4
- Zettlr 1.2 doesn't have the problem at all.

As I understand, this is an electron bug and this was triggered by the upgrade of Electron from 1.2 to 1.3.

It seems to be a quite critical problem of Electron and I guess they will have so solve it quite quickly (I hope in time for the release of 1.4)

**Comment by ploum** [comment]
Still had a crash. They are less frequent but one of my other folder is synchronised with Dropbox.  So I guess that nothing can touch your Zettlr folders.

**Comment by ploum** [comment]
Still have crashes without Zotero, Tresorit or Dropbox.

Writing it only for the record.

**Comment by nathanlesage** [comment]
Oh dear … are you sure there are no external applications touching the files?

We're still unsure whether Electron 5.0.1 introduced the bug, or fsevents, or chokidar …

**Comment by ploum** [comment]
There's probably one, will investigate.

Anyway, I'm tired of MacOS. Getting back to Linux as soon as I can find a laptop as light and small than the Macbook retina ;-)

**Comment by ploum** [comment]
It looks like it crashes a few seconds after modifying a note. So probably related to the "save" mechanism" or the fact that the file has been modified. Still trying to find which app could cause that.

**Comment by nathanlesage** [comment]
Would be great, because even syncing with Nextcloud on my macOS does not trigger the segfault, no matter how often I modify the files, so there's definitely something going on

**Comment by ploum** [comment]
Ok, I think I've identified the problem : https://osxfuse.github.io

If, for whatever reason, the folder is also accessed by Fuse (which was the case for my Tresorit folders, even when tresorit is not running), Zettlr will keep crashing. Uninstalling fuse allowed me to keep Zettlr running for more than 3 minutes.

**Comment by nathanlesage** [comment]
Yes this is basically what is also cristallizing in the discussions over at fsevents --- somehow the file watching concurrently with other handlers accessing files makes it literally choke and therefore Zettlr crashes. There's a lot of activity going on, so I hope the issue will be fixed soon!

**Comment by dambaras** [comment]
1.3 Beta v2 on Mac OS X 10.13.6 still crashing when I make changes to Zotero...

**Comment by nathanlesage** [comment]
Maybe short update on the fsevents issue: They think they're on to something, so there's definitively movement in that … I'll publish a patch once fsevents is updated!

**Comment by dambaras** [comment]
Thanks!
-- 
David R. Ambaras
Associate Professor and Director of the History Honors Program
Department of History, Campus Box 8108
North Carolina State University
Raleigh, NC 27695-8108
Phone: 919-513-2228 | Fax: 919-515-3886
Email: dambaras@ncsu.edu | Skype: dambaras
http://history.ncsu.edu/people/faculty_staff/dambaras

*Now available:* *Japan's Imperial Underworlds: Intimate Encounters at the
Borders of Empire*
<http://www.cambridge.org/gb/academic/subjects/history/east-asian-history/japans-imperial-underworlds-intimate-encounters-borders-empire?format=HB#S0xuPmfieDhRxgtJ.97>
(Cambridge University Press, 2018)
*New spatial history site:* Bodies and Structures: Deep-mapping Modern East
Asian History <http://scalar.chass.ncsu.edu/bodies-and-structures>
