### ISSUE TITLE
"Note is unsaved" dialog appears when closing Zettlr on MacOS

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#187]
- Open Zettlr on MacOS
- Open a note
- modify the note
- immediately after, close the app using the close button (the small red circle, upper left of the window)

A popup will appear telling you that the note is unsaved and asking you to save it.

**Comment by nathanlesage** [comment]
Aaaaaaaaah yes I see where it comes from. I normally don't close the main window so this little bit eluded me. Wait, let me check …

**Comment by nathanlesage** [comment]
Piece of cake. Comes in the next beta!
