### ISSUE TITLE
[ENHANCEMENT] Table of Contents sidebar

### ISSUE THREAD

**Issue by BrandonKMLee** [Zettlr/Zettlr#1870]
## Description
Currently, there is only a file sidebar and a table of contents dropdown, but never a Contents sidebar for easy access, like what MarkText has.

## Caveats
MarkText's sidebar does not seem to handle Title/Heading updates.

**Comment by nathanlesage** [comment]
There is a table of contents in the sidebar, even in 1.8.7. To open it, click the right-most toolbar icon to show the sidebar, and then click the correct tab (I think it's the second or third).

**Note**: The "file sidebar" to the left of the app is called the file manager, the right-sidebar is what is named just "Sidebar".

**Comment by BrandonKMLee** [comment]
@nathanlesage in this case, I should clarify that having the file manager bar to have a "switch to table of content side bar" as the content bar is commonly accessed when arranging documents.

**Comment by nathanlesage** [comment]
I'm not quite sure I understand …?

**Comment by BrandonKMLee** [comment]
Currently, the "sliding" table of contents side bar is on the right, and it is not as accessible as the file bar on the left, where it stays with you on the left.

**Comment by nathanlesage** [comment]
Ah, alright, I see. In the current 2.0 development build it's a sidebar just like the file manager. Apologies, I'm slowly forgetting how 1.8.7 works!

**Comment by BrandonKMLee** [comment]
@nathanlesage <3 thx
