### ISSUE TITLE
[FEATURE] Automatic copying of pictures to a file specific subdirectory

### ISSUE THREAD

**Issue by adamprada** [Zettlr/Zettlr#1873]
## Description

When I drop an image into a document, I want it to be copied into a subdirectory specific to the file. E.g. if the file is myfile.md, it could be myfile.assets subdirectory. The relative path to this would then appear in the code. The same could be done with links to files.

## Example Workflow

Have this as option in the settings.

## Caveats

If users wanted this behaviour only for certain files, it could be activated or deactivated in the YAML header.

## Additional Information

Why is this useful? If you want to send your note to someone or move it to a different location, you can just copy and paste the .md file + its folder of pictures. The pictures will not be mixed with pictures belonging to other .md files and one does not have to move all the pictures manually to the folder.  Even on a single machine, it makes the notes more self-contained, persistent w.r.t  changes of files in other folders. It would also be nice to implement this for other types of files.

**Comment by nathanlesage** [comment]
> Why is this useful? If you want to send your note to someone or move it to a different location, you can just copy and paste the .md file + its folder of pictures.

That's what the `Textpack` and `Textbundle` export options are for. [The format](http://textbundle.org/) has been specifically designed for exactly that purpose.

I am quite sure automatic duplication of data on your file system is an anti-pattern.
