### ISSUE TITLE
Hightlight shift from selected text in distraction free mode

### ISSUE THREAD

**Issue by harry-xiaomi** [Zettlr/Zettlr#1876]
## Description

Zettlr dims the selected text in distraction free mode.

## Reproducing

1. Enable distraction free mode.
2. Select a line with triple-clicking.

<img width="275" alt="2nd" src="https://user-images.githubusercontent.com/47099356/114367759-5c985000-9baf-11eb-88d7-be543dc866c2.png">

## Expected behaviour

Highlight the selected text.

## Platform
 - OS and version: macOS 11.0
 - Zettlr Version: 1.8.7

**Comment by nathanlesage** [comment]
I'm not sure this is relevant anymore since the distraction free mode as we know it is gone in 2.0. The bigger question here would be whether or not we would need dimmed paragraphs at all.

Comments, anyone else?

**Comment by harry-xiaomi** [comment]
I think this is definitely useful, and could be split into a standalone feature, capable of dimming text at the sentence or paragraph level.

**Comment by harry-xiaomi** [comment]
Still relevent.

**Comment by harry-xiaomi** [comment]
I'll let it stale next time if no one else comments on this.

**Comment by nathanlesage** [comment]
Note: Triple-clicking will still unmute the line following the selected line since the selection extends past the linebreak of said line.
