### ISSUE TITLE
[ENCHANTMENT] MDX support

### ISSUE THREAD

**Issue by krry** [Zettlr/Zettlr#1880]
## Description

As a zettlr, when I open a folder containing `.mdx` files in the file manager, I would like to see them treated as files, and see their contents displayed as those of a `.md` would be.

## Proposed Changes

This may entail letting the Zettlr app know that `mdx` files are markdown files. I do not care if the `x` aspects of mdx are handled richly, just plaintext for the beyond-markdown pieces would suffice.

## Caveats

[MDX](https://mdxjs.com/) may contain all manner of javascript.

**Comment by nathanlesage** [comment]
Should be possible, yes, since we also support Rmd. However, it shall be noted that there won't be dedicated syntax highlighting for the JSX parts of MDX.
