### ISSUE TITLE
Pasting with the middle mouse button does not work

### ISSUE THREAD

**Issue by sphh** [Zettlr/Zettlr#1882]
## Description

On Linux pasting with the middle mouse button does not work.

## Reproducing

1. Open Zettlr.
2. Open a simple text editor.
3. Select some text in the text editor.
4. Click the middle mouse button in Zettlr.
5. Nothing is inserted into Zettlr.

## Expected behaviour

The selected text should be inserted into Zettlr (either at the position of the click or at the actual cursor position).

## Platform
 - OS and version: Linux Mint 20.1
 - Zettlr Version: 1.8.7

## Additional information

Selecting text in Zettlr and pasting it with the help of the middle mouse button into the editor does work.

**Comment by nathanlesage** [comment]
Is this a global/common shortcut on your specific distribution? That is because I have never heard of pasting using the middle mouse being a thing at all.

**Comment by sphh** [comment]
No, it's not specific to my distribution at all:

> Using the left mouse button to select and copy text in terminals and the middle mouse button to paste has been a feature of X-Windows, and the various window managers built on top of X-Windows, since the early 1990s.

> In the X Window system used on Linux and other UNIX variants, making a selection sets the primary selection, and in some applications such as terminals, clicking the middle mouse button pastes the primary selection.

See also: https://en.wikipedia.org/wiki/X_Window_selection

This is a very, very useful feature making copy'n'pasting quick and painless. And you can have two clipboards (primary and secondary). It's so useful, that people missing it on Windows systems wrote programs to get a similar experience there (e.g. https://www.highrez.co.uk/downloads/XMouseButtonControl.htm)

**Comment by nathanlesage** [comment]
Ah, yes I figured as much: It's a feature I know from terminal applications myself.

However, Zettlr is a GUI application, so the question was related to that: Does Word/LibreOffice/other word processors and/or text editors support middle-mouse pasting? I am not talking about the terminal here.

**Comment by sphh** [comment]
Yes, all GUI text editors I know of, support middle-mouse pasting.

**Comment by nathanlesage** [comment]
Alright, thank you for confirming. This should be fairly simple to implement; albeit I have to confess I'm very sparse on time and I'm not sure when I can do this. So, PRs welcome.

**Comment by sphh** [comment]
Thanks for putting this on the To do list! Unfortunately I cannot help here, since Electron/JavaScript is not really the language I excel in …

**Comment by nathanlesage** [comment]
Just implemented that. It *should* work now (in the 2.0-dev branch). If it doesn't once you test it out, notify me.

Currently just supports plain text and HTML, so I hope it doesn't break any workflows if you have to paste images the lame way :P

**Comment by sphh** [comment]
Thanks, @nathanlesage! Is there a nightly build or something similar available, so that I can test it?

**Comment by nathanlesage** [comment]
Not yet, but you can build it yourself. Shouldn't be too hard, especially on Linux. You basically just need to install Node and Yarn, clone the repository, install the dependencies and then run the builder. There's a good intro in the README file that should include all information necessary!

**Comment by sphh** [comment]
Yes, you have quite a good description, how to build it. I just want to avoid installing more and more packages from an ecosystem I am not familiar with. So I was hoping for a pre-compiled version. Maybe I should just wait for the 2.x.y branch …

**Comment by nathanlesage** [comment]
Of course, if that's more comfortable for you! I can totally understand you. I hope to be shipping builds by the end of the month … if all goes right.
