### ISSUE TITLE
Mac OS doesn't let me open (by default) .md files with zettlr

### ISSUE THREAD

**Issue by jearistiz** [Zettlr/Zettlr#1885]
## Description
If I want to select the default app to open .md files, MacOS blocks zettlr from the app list displayed when using right-click (on .md file) > Open With > Other...

## Reproducing
Already described above

## Expected behaviour
.md files to be opened by default with zettlr

## Platform
 - OS and version: MacOS BigSur v11.2.3
 - Zettlr Version: 1.8.7

**Comment by jearistiz** [comment]
Sorry guys, I just needed to select ``Enable: All Applications`` when the app list is opened. However, I think Zettlr should not be blocked from the list when ``Enable: Recommended Applications`` is selected.

**Comment by nathanlesage** [comment]
Curious. I know that macOS's default application handling is in fact a little bit weird, but for me it works out of the box as expected (I'm on Big Sur 11.2.3 as well).

However, I noticed that sometimes the finder greys out even working applications (similar with Open-File-dialogs and correct files having the right extension), so it might be a bug with Big Sur itself …?

**Comment by nathanlesage** [comment]
I did not anticipate what a piece of work `plist`-files would be, but I managed to associate Zettlr with the correct file extensions!
