### ISSUE TITLE
Limits on root directory size/depth?

### ISSUE THREAD

**Issue by EcoFin** [Zettlr/Zettlr#1887]
## Description

Trying to open large and deep folder as root directory causes Zettlr to crash. 

## Reproducing

Trying to open root folder Zettlr crashes (not always at the same place according to the log) after loading 2 sub-folders, the first  containing 6 sub-folders itself, the second 20.

## Expected behaviour

Per the documentation, Zettlr would open the folder as a root directory.  I can open other fairly complex root folders just fine.

## Platform
 - Win 10 x64 
 - Zettlr Version: 1.8.7

## Additional information

Maybe there are de facto limits on folder depth? number of files? memory used to hold directory structure? types of files (other that md)?  I could restructure folders on disk to take any limitations into account if they were added to the documentation, but I can't be sure what they are.  Only filed this as a bug because it does reliably cause Zettlr to crash after what seems to me a relatively modest amount of  content loaded (the log suggests that Zettlr doesn't like load times that  exceed 1000ms.

I know this is specific to my system, but don't know what I should be looking for.

Just trying to be helpful by flagging the problem.

**Comment by nathanlesage** [comment]
I'm pretty sure it's not because of the folder depth. We've had the problem in the past that sometimes, rogue `.ztr-directory`-files were causing problems. Since you already mentioned the logs: These would be helpful in this case.

**Comment by EcoFin** [comment]
Hendrick,

 

Here’s  aa minimal example of a crash log from yesterday.

 

In this particular example, it reads the first 2 of (at the time) 6 sub-folders and then … boom, gone.

But sometimes, it would read 3 sub-folders before disaster.  Don’t know why.  None of the first 4 were the real problem as far as I can  tell.

 

What I did as an ad hoc fix was to restructure the top-level folder a bit to (a) be able to work and (b) try to isolate the problem sub-folder.

 

1.	Made new sub-folder inside the one I at first tried to make the root
2.	Added folders progressively to the new sub-folder
3.	Successfully opened that (new) sub-folder as root.
4.	That leaves one large folder aside.   It is the problem folder.   I don’t know why or what I should look for.   It doesn’t matter much in a practical way because it is relatively old reference material.   But there is something going on.  I will continue to play with it and track it into a corner.  But if you have any ideas, I will try them first.  

 

Zettlr is getting a lot better all the time and the “virtual file system” is a problem I have tried to solve repeatedly with only limited success.

 

Sincerely

Arthur younger

**Comment by nathanlesage** [comment]
Seems as if that Finance - Reading & Research folder is causing problems. Would you mind checking in there if you can spot some `.ztr-directory` file? The easiest way would be to just get rid of these at first (you'd lose custom icons and sorting, but I guess that's a minor hassle) – although I don't know how to do that on Windows. On Unixoid systems I'd attempt `rm **/.ztr-directory` ...

**Comment by nathanlesage** [comment]
Alright, yes, I see that. There must be something with that folder that makes Zettlr crash, but it can be really hard to pin down these issues … I had my fair share of trying to get the directory loader to do some thing in the past … looking forward to your results!

**Comment by EcoFin** [comment]
Hendrik

 

You are quite right.  I just wondered whether you had any tips.

I will pursue the good old-fashioned trial and error debugging process and let you know what I can find.

 

Unless zettlr is ‘reading ahead into folders it plans to load, I don’t know why the bad folder wouldn’t be the last thing in the crash log.

But then I have no clue how electron works.

 

Sincerely

ay

**Comment by nathanlesage** [comment]
> Unless zettlr is ‘reading ahead into folders it plans to load, I don’t know why the bad folder wouldn’t be the last thing in the crash log.

Well, Zettlr only logs *after* it has successfully read the folder ...

**Comment by EcoFin** [comment]
That is what I would think … curious

 

ay
