### ISSUE TITLE
[Feature request] Smart virtual folder/filters

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#189]
Virtual folders are nice.

You know what is nicer?

Smart virtual folders!

What does a smart virtual folder do?

It simply display all notes within the same folder (or subfolder) with a given tag. That way, you could add a note to a virtual folder just by writing the tag in it. Would also be very useful to work on some projects when you need to quickly go to references.

**Comment by nathanlesage** [comment]
Replace Smart Virtual Folder with Filter and have a look at this class. https://github.com/Zettlr/Zettlr/blob/master/source/main/zettlr-filter.js =D

It's been there for exactly one year now, I haven't gotten to implementing them. I already thought maybe to deprecate virtual folders and replace them with these filters, in addition to the Symlink issue somewhere in the issue list this could be more handy and modern :)

**Comment by ploum** [comment]
That would be perfect!

And I agree with the fact that virtual folder and filters are competing. Having both features is a bit confusing. 

I would personally go with the filters instead of virtual folders ;-)

**Comment by nathanlesage** [comment]
Just stumbled upon this issue, because there are several more specific issues open by now (this makes it easier to implement these things!)
