### ISSUE TITLE
Does it work on Windows 10?

### ISSUE THREAD

**Issue by thistlillo** [Zettlr/Zettlr#1892]
I have just installed the latest version (as of today April 21, 2021, Windows reports version 1.8.7) of Zettlr on my Windows 10 Pro laptop. I downloaded the file from: https://www.zettlr.com/download by clicking on the Windows-related download.

The file I got has md5: 3ad966ab8b8566a018b7e1142d8cd4d1

When I run the app after installation (for current user only - not system wide) I see the window below:

![zettlr-error](https://user-images.githubusercontent.com/6717655/115496372-c4aefc00-a269-11eb-912a-3b337e286f4d.PNG)

What did I (or you) do wrong?

**Comment by nathanlesage** [comment]
To your title: Yes, it runs on Windows 10, and most beautifully so. That being said, checking the error message you get gives the following, first result:

![image](https://user-images.githubusercontent.com/17251683/115514635-98ed3f80-a284-11eb-807f-cf0351148d26.png)

So, my first question would be: Is your Windows 10 a 32bit version? I've heard some reports that Zettlr doesn't run on 32bit Windows although the installer should be able to. That might be the reason you're seeing this message. Would you mind checking that real quick?

(N.B.: In case you're indeed running 32bit Windows, the chances are almost 100 % that your computer can also run 64bit, in which case I'd recommend an upgrade irrespective of Zettlr)

**Comment by thistlillo** [comment]
64 bit here.

Device name	dell-xps
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	-
Product ID	-
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	20H2
Installed on	‎08-‎Feb-‎21
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by nathanlesage** [comment]
Huh, that is more than weird. I have no idea what've might gone wrong with that set up, because I know for sure the 1.8.7 installer worked on my 64bit Win10 system freshly set up just a week ago. Maybe google a little bit around …? I'm sorry that I can't be of any more help right now :/
