### ISSUE TITLE
Cannot step out of `code block` if at end of document using "```", arrows keys, or mouse.

### ISSUE THREAD

**Issue by indirection** [Zettlr/Zettlr#1895]
## Description
Cannot step out of `code block` if at end of document using "```", arrows keys, or mouse.

## Reproducing
Create a document and append a `code block` using the "\```" and hit return. I am unable to step out of the `code block` using 
1. "```", 
2. arrows keys, or 
3. mouse by selecting blow the document.

## Expected behaviour

<img width="1363" alt="Screen Shot 2021-04-24 at 2 19 26 PM" src="https://user-images.githubusercontent.com/398047/115968917-1aa0cf80-a508-11eb-8718-f4f2f6c874d2.png">

## Platform

 - OS and version: macOS 10.15.7
 - Zettlr Version: Version 1.8.7 (1.8.7)

**Comment by nathanlesage** [comment]
Ah, I think I know that bug, and I can confirm that this doesn't happen in the 2.0 branch, so it seems fixed! There were a few oddities, and some more remain, but I'll attempt at getting rid of all of these in Zettlr 2.0 :)
