### ISSUE TITLE
[FEATURE] Support .mkd files

### ISSUE THREAD

**Issue by johannhuang** [Zettlr/Zettlr#1897]
- [x] Zettlr does not possess something similar (in which case it
        would be an enhancement, NOT a feature!)
  - [x] I have searched the documentation to make sure I did not overlook it.
  - [x] Zettlr's current features cannot be used to approximate this behaviour.
  - [x] I have searched all issues (open and closed) to see if someone else
        wants something similar to which I could propose modifications.
  - [x] I will prepend "[FEATURE]" to my issue title.

## Description
Treat .mkd files the same as .md files

## Example Workflow
Following windows convention about file extensions, some tools generate markdown files with 3-letter extension, i.e., .mkd instead of .md. Zettlr current only scan .md files in the given directory.

**Comment by nathanlesage** [comment]
I have never heard of mkd-files. Could you name "some tools"?

**Comment by johannhuang** [comment]
@nathanlesage thanks for your quick response. To be honest, we have some internal tools which create markdown files ending with .mkd by default. As for the possibility of having .mkd as extension of markdown files. Maybe the link https://superuser.com/questions/249436/file-extension-for-markdown-files can give you some ideas.

And maybe, it is also much better to generalize extensions in use by allowing the user to config with comma separated list.

**Comment by nathanlesage** [comment]
Mh, I think the idea of letting the user specify those file extensions that should be treated as Markdown would solve a lot of those issues, that's a good idea.
