### ISSUE TITLE
[Feature request] integrate PDF files

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#190]
It would be nice to add PDF into a document and have it displayed either as an icon or, even better, as a preview of the document (that could then be opened with an external application).

Currently, on MacOS, drag-n-droping a PDF results in an error "could not open xxxx.pdf".

(my request may be linked with the attachment panel but I don't understand how it works)

**Comment by nathanlesage** [comment]
This is basically the issue that I need to enable drag&drop of attachment files into the editor to link them, so it's not only with PDF-files, but with everything (except something on images).
