### ISSUE TITLE
No dropdown list when creating new link

### ISSUE THREAD

**Issue by AndrewRRM** [Zettlr/Zettlr#1905]
## Description
Zettlr no longer supplies a dropdown menu of my files when I open a double square bracket to create a new link

## Expected behaviour

Zettlr had been working mostly as expected although this behaviour has occurred previously. Generally, a restart seemed to have fixed it but not this time. Links work as expected once created.

## Platform
 - M1 Macbook Air Big Sur, 11.2.2
 - Zettlr Version: 1.8.7

## Additional information
Sorry to post here if this inappropriate. This is probably not a bug but a setting I have screwed up.

**Comment by AndrewRRM** [comment]
I have no idea what I'm doing but if I turn on debug, and look into the logs, as type open square brackets "[["  I see this:

[R] [Main Window] Uncaught TypeError: t.displayText.toLowerCase is not a function (index.js:585)

**Comment by nathanlesage** [comment]
Mh, it seems there is indeed an error in the entries for the autocomplete, since at least one of those seems to not have any `displayText` (the text that is shown to you, not what is actually added). But I don't really know where this stems from :/

I can only confirm that internal links work as expected in the current 2.0 dev branch. I get the feeling that I cannot wait too long to start the public beta, given that 1.8.7 exhibits more and more minor bugs recently …

**Comment by AndrewRRM** [comment]
Thanks for the quick reply. I've been playing around with workspaces and have internal links working in the old Zettlr tutorial folder and a newly created workspace but not on the one I need :). Even tried dumping the Zettlr folder in Application Support. No luck.

**Comment by nathanlesage** [comment]
What is the link you want to get? Do you have some, e.g., screenshots or just some more info here?

Oftentimes, those kinds of errors are due to miniscule problems that are only visible if you know every inch of the source …

**Comment by AndrewRRM** [comment]
Sorry, I'm not sure what you mean. When I try to create a new internal link with [[, there is no dropdown /  autocomplete list. My feeling the problem lies with one specific workspace.

**Comment by AndrewRRM** [comment]
OK, I think I figured it out. I've been back and forth with Obsidian and a couple of files either got corrupted or were named in a way that Zettlr didn't like. It was screwing up everything for some reason. I've removed them and it all works again.

**Comment by nathanlesage** [comment]
That's good to hear! Do you have any idea what might've caused Zettlr to misbehave?

**Comment by AndrewRRM** [comment]
Not really. I just opened various combinations of workspaces and narrowed down the offending folder, and within that a couple of files that when included would stop Zettlr from autocompleting links. They looked innocuous (basically placeholders for me) with not much in them so I trashed them. I have an inkling that they were badly named so will experiment today and get back to you.

**Comment by nathanlesage** [comment]
Thank you, looking forward to the info!

**Comment by marbetschar** [comment]
@nathanlesage I ran into the same issue today: Entering `[[` does not show any dropdown. FWIW: I reorganized my folder and moved a lot of files around. Before it worked - now it does not work any longer. Any ideas how to fix this and/or which information you need in order to pin this down?

**Comment by nathanlesage** [comment]
mh … strictly speaking no ID is necessary, so this might indicate a bug. Although I'm not sure whether it's fixed in 2.0 dev …
