### ISSUE TITLE
[FEATURE] Support links of the form `[[Path/To/Link]]`.

### ISSUE THREAD

**Issue by hameerabbasi** [Zettlr/Zettlr#1925]
## Description
Allow links from the root of the Zettelkasten.

## Proposed Changes
If I click on a link similar to `[[Path/To/File]]`, it should try to find it as a relative path in `.`, `./..`, `./../..` iteratively until we can't find anything in the root of the Zettelkasten in this way.

## Caveats
Links no longer valid before may become valid. But that's kind of the point, no? 😉

## Additional Information
[Obsidian](https://obsidian.md/) provides this feature, and I'm trying to switch. I have a lot of files, and wouldn't like to change all the links. Additionally, I find it better to order things hierarchically in my head, so this is helpful.

I'm perfectly willing to implement this, I found, e.g. [`render-links.js`](https://github.com/Zettlr/Zettlr/blob/0637bafaaba94660446ff770e68abd05f226730f/source/common/modules/markdown-editor/plugins/render-links.js) and [`make-valid-uri.js`](https://github.com/Zettlr/Zettlr/blob/0637bafaaba94660446ff770e68abd05f226730f/source/common/util/make-valid-uri.js) as two possible places. I'm willing to make a PR and would appreciate some guidance on what parts of the code to touch.

**Comment by nathanlesage** [comment]
I'm sympathetic to this, given that it's _not just_ implemented by Obsidian. I want to keep features out of Zettlr that only very few different apps understand, but everything that is en route to becoming "common" should be, so if that's one thing, feel free to go for it!
