### ISSUE TITLE
Embedded Clock and Pomodoro

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#193]
Hello, I am new to Zettlr, and find it good and has a lot of potential. I work on a minimalistic desktop, where I hide the windows toolbar, causing me to have to install clock extension on mozilla, for example. I wonder if Zettlr could do this to. 

And as for pomodoro, could you please add reset button and stats in order to track how long we work on a text or on the the whole documents? Another problem with pomodoro is that it sometimes crashes when I click on it. Sometimes I have to open attachment panel first in order to give the pomodoro scroll-down panel a 'background' so that it would work, but it doesn't always work. 

Thanks a lot!!!

**Comment by nathanlesage** [comment]
> Another problem with pomodoro is that it sometimes crashes when I click on it. Sometimes I have to open attachment panel first in order to give the pomodoro scroll-down panel a 'background' so that it would work, but it doesn't always work.

Could you provide a little bit more info, such as: Which Zettlr version are you using? Which Operating System? Which Version?

**Comment by shanvrolijk** [comment]
I run zettlr 1.3 beta on windows 10

**Comment by nathanlesage** [comment]
Ah just found the bug, the popup is closing immediately. Something wrong with the event handlers, I'll get into it!

**Comment by nathanlesage** [comment]
Fixed the Pomodoro timer bug in https://github.com/Zettlr/Zettlr/commit/73a0a1a7bc5eaf9cc8eaa74a6558fe26512c0280. Concerning the clock, I'm unsure, sounds more like a plugin to me that would need to wait until a Plugin API may emerge …
