### ISSUE TITLE
Zettlr will not install correctly on Debian Bullseye or higher

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#1936]
## Description

Installing Zettlr fails to install on Debian Bullseye (testing). It shows the package libappindicator3-1 is not installed and breaks updating and installing packages until Zettlr is uninstalled.
## Reproducing

Download latest version of Zettlr (1.8.8) from https://www.zettlr.com/download/deb
- In terminal run: sudo dpkg -i Zettlr-1.8.8-amd64.deb
```
Selecting previously unselected package zettlr.
(Reading database ... 362275 files and directories currently installed.)
Preparing to unpack Zettlr-1.8.8-amd64.deb ...
Unpacking zettlr (1.8.8) ...
dpkg: dependency problems prevent configuration of zettlr:
 zettlr depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.
dpkg: error processing package zettlr (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (2.0-1) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Errors were encountered while processing:
 zettlr
```

Then attempting to install another package:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 zettlr : Depends: libappindicator3-1 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

## Expected behaviour

Installation goes smoothly using dpkg.

## Platform
 - OS and version: Debian GNU/Linux bullseye x86_64
 - Zettlr Version: 1.8.8 (and 1.8.7)

## Additional information

This appears to be a common problem when installing electron apps on Debian testing/sid and is due to `libappindicator3-1`being made depreciated. It does not to affect Debian Buster (stable). It has been replaced by `libayatana-appindicator`.

Bug Report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

**Comment by nathanlesage** [comment]
I'm afraid this lies in the realm of the Electron builder/electron forge team, so maybe have a look at their issue tracker to see if someone has already raised this issue?

**Comment by Moltkex** [comment]
@break6700 Installing downloaded .debs with dpkg doesn't resolve dependencies, you have to install the pkg with apt, like this
```bash
sudo apt install ./Zettlr-1.8.8-amd64.deb
```
apt will download and install the necessary dependencies, as long as they're in the repos of course.

**Comment by nathanlesage** [comment]
Does this mean the issue can be seen as resolved?

**Comment by Moltkex** [comment]
> Does this mean the issue can be seen as resolved?

Actually, I just tried to install **Zettlr-1.8.9-amd64.deb**, and got the same error as the OP. Turns out the pkg **libappindicator3-1** is not in Bullseye's repos. It's in Stretch's, Buster's and Sid's though https://pkgs.org/search/?q=libappindicator3-1. So I guess no, it can't be seen as resolved just yet.

**Comment by nathanlesage** [comment]
Mh, but it still seems like an upstream bug that needs to be addressed by … I think electron-builder. Or, maybe it'll be ported to the Bullseye repos in some time; especially given that it's kind of a standard on debian-systems

**Comment by break6700** [comment]
I think it is unlikely to get ported to Bullseye soon. I have found that I **can** install the necessary packages separately and it works. This does mean I will receive **not** updates but for now, will do.

https://packages.debian.org/sid/libappindicator3-1 

This is by no means a good solution and directly [breaks the 'rules' to not break Debian](https://wiki.debian.org/DontBreakDebian).

**Comment by Moltkex** [comment]
> Mh, but it still seems like an upstream bug that needs to be addressed by … I think electron-builder. Or, maybe it'll be ported to the Bullseye repos in some time; especially given that it's kind of a standard on debian-systems

It looks to me like a Debian upstream thing. 




> I think it is unlikely to get ported to Bullseye soon. I have found that I **can** install the necessary packages separately and it works. This does mean I will receive **not** updates but for now, will do.
> 
> https://packages.debian.org/sid/libappindicator3-1
> 
> This is by no means a good solution and directly [breaks the 'rules' to not break Debian](https://wiki.debian.org/DontBreakDebian).

Yeah, it's not an ideal solution, but sometimes you have to get your hands dirty. I didn't try installing those since I use the appimage, I was only trying to help with the **.deb** issue :grin:

**Comment by zchap26** [comment]
Issue persists with Zettlr-2.0.0-beta.5-amd64.deb:
```
user@computer:~$ sudo dpkg -i Zettlr-2.0.0-beta.5-amd64.deb 
Selecting previously unselected package zettlr.
(Reading database ... 166731 files and directories currently installed.)
Preparing to unpack Zettlr-2.0.0-beta.5-amd64.deb ...
Unpacking zettlr (2.0.0-beta.5) ...
dpkg: dependency problems prevent configuration of zettlr:
 zettlr depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package zettlr (--install):
 dependency problems - lDownloadseaving unconfigured
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for shared-mime-info (2.0-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 zettlr
```
_.deb_ does not install correctly on _Debian_. I am going to stop trying.

Is this not exactly the kind of problem that snaps and flatpaks were meant to solve once and for all?

AppImages on Linux do work. But I would argue that the average Macintosh user would want to avoid having to use an application that somehow didn't integrate well with their desktop.

Given how much work clearly must have gone into Zettlr the application as well as Zettlr the manual, I cannot help but think that the lack of either a snap or a flatpak for Linux is an oversight that really should be addressed.

Regards (and thanks for such an outstanding application)

**Comment by nathanlesage** [comment]
> Given how much work clearly must have gone into Zettlr the application as well as Zettlr the manual, I cannot help but think that the lack of either a snap or a flatpak for Linux is an oversight that really should be addressed.

The main problem is that I simply don't have the time to really plan such a release right now. I am completely overworked and while AppImages are simply a build & upload, for snap I need to somehow register with the service, fulfill quite an amount of preconditions, have to do testing (which I can't because I don't have Linux) and finally figure out how to get that thing into the automation. I take any help available, so feel free to draft something that makes it easier for me; feel free to discuss this on Discord.

**Comment by zchap26** [comment]
Ok, I totally understand.
All I keep hearing about is that universal packages are meant to make things easier for _developers_. But I do appreciate that that does not translate into effortless.

Regards

**Comment by nathanlesage** [comment]
Definitely. Once set up I imagine that those releases should go pretty much effortless, but there is kind of an effort, although I suspect that releasing snap-packages should be a one-time effort.
