### ISSUE TITLE
[BUG] Surrounding space will be removed when pasting HTML with <code> tags

### ISSUE THREAD

**Issue by ousheobin** [Zettlr/Zettlr#1937]
## Description

When copying the HTML content contains `<code>` from the browser, spaces around the `<code>` tag will be removed.

For example if the HTML content is:

```HTML
<p>Hello Zettlr, <code>Code</code> !</p>
```

When we copy and paste it into the Zettlr, the content will become:

```Markdown
Hello Zettlr,`Code`!
```

It's easy to find out that spaces around `<code>` tag are removed.

## Reproducing

Using Chrome and Safari, copy some text with `<code>` tag and paste it into Zettlr.

## Expected behaviour

The markdown string displayed in Zettlr will be similar to below screenshot :

![image](https://user-images.githubusercontent.com/3753809/117583109-4b365b00-b0fd-11eb-84d8-11e1da5da44a.png)

## Platform
 - OS and version: MacOS 10.15 
 - Zettlr Version: 1.8.8

## Additional information

After my initial investigation, I found when we copy such text, Chrome and Safari will replace the space around the tag `<code>` with a `<span> </span>` , below are some samples I collect from Chrome, Safari and Firefox:

Chrome:

```HTML
<meta charset='utf-8'><span style="...">Hello Zettlr,<span> </span></span><code style="...">Code</code><span style="..."><span> </span>!</span>
```

Safari:

```HTML
<span style="...">Hello Zettlr,<span class="Apple-converted-space"> </span></span><code style="...">Code</code><span style="..."><span class="Apple-converted-space"> </span>!</span>
```

Firefox:

```HTML
<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body><p>Hello Zettlr, <code>Code</code> !</p></body></html>
```

With *joplin-turndown*'s default `blankReplacement` rule, this tag with empty content will be trimmed. Therefore, all spaces around the `<code>` tag will be removed.

A simple proposal for fixing this issue on Zettlr is to modify the `/source/common/util/html-to-md.js` and extend the default `blankReplacement` rule of *joplin-turndown*:

```Diff
 const converter = new Turndown({
   headingStyle: 'atx',
-  hr: '---'
+  hr: '---',
+  blankReplacement: function (content, node) {
+    // Fix the <span> </span> issue
+    if (node.nodeName === "SPAN"){
+      return ' ';
+    }
+    return node.isBlock ? '\n\n' : ''
+  },
 })
```

One of the drawbacks of this solution is that the `blankReplacement` is an extended version and it may need to be changed when *joplin-turndown* update the default  `blankReplacement` rule.

Best regards.

**Comment by ousheobin** [comment]
Thanks @nathanlesage for you quick response. I have created a PR (#1939) for this issue. It has been tested on Chrome, Safari and Firefox. Would you please review it and let me know if you have any concern on it. Thank you.

**Comment by nathanlesage** [comment]
Have done so; if you can confirm this works (even if it doesn't capture every white-space issue) then we can merge!

**Comment by nathanlesage** [comment]
> The reason of why I use "it can help" in the PR is for some special case (e.g. `<a>xxx </a>`) this solution may not be able to eliminate this whitespace problem due to the design of Joplin-Turndown.

That is definitely good enough. It's no problem to fix a few errors here and there as long as most stuff works as it is supposed to.
