### ISSUE TITLE
Beta 1.3: Theme selector not working?

### ISSUE THREAD

**Issue by davidbosman** [Zettlr/Zettlr#194]
Just installed the latest beta on a Mac, not much testing yet but it seems like I can't select any theme, it will stick with the default one (light, or dark when Night Mode is switched on). _Edit_: It looks there is a problem under Windows too: when using the default light appearence, only the Bielefeld theme seems to be registering and update the background color.

Running on Mojave 10.14.5, and on Windows 10 Pro 1809.

**Comment by nathanlesage** [comment]
Can't reproduce here (Mojave 10.14.4 works + Windows 10 also) :S 

It sounds really strange that on Windows, for instance, just one theme works o.O If you could investigate a little bit what happens, this would be great. One way to start would be to look in the `<head>` tag and see if the theme correctly switches:

![grafik](https://user-images.githubusercontent.com/17251683/58002846-c309b600-7adf-11e9-8160-a44cd7735ad5.png)

It should always be named `theme-bielefeld.css`, `theme-frankfurt.css` or `theme-berlin.css`.

**Comment by nathanlesage** [comment]
Anything new on this one?
