### ISSUE TITLE
[ENHANCEMENT] close dialogs with Escape-key

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#1940]
## Description

Allow all dialogs in the app (e.g. settings, tags etc) to be closed using the Esc key.

## Proposed Changes

Pressing Escape is like clicking Cancel or Close.

**Comment by nathanlesage** [comment]
Let me add to this that some dialogs should be confirmable with the Return key (e.g. the image insertion), which bugs me as well

**Comment by nathanlesage** [comment]
Since there are no more in-main-window-dialogs, this issue is superseded!
