### ISSUE TITLE
[BUG] Code block detection for background and color coding not in sync

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#1941]
## Description

Accidentally add a space before the triple back-tick, and the color coder accepts the space, while the background for code blocks ignores the triple back-tick.

![image](https://user-images.githubusercontent.com/1702193/117740384-a00eca00-b200-11eb-9db6-67fa64058ec5.png)

## Reproducing

Paste this markdown:

    # Code problem

    Here is some python.
    Accidentally added space
    before first back-tick.

     ```python
    if test < 4:
        test++
    ```
     
    The color coding is applied 
    to the correct code block.
     
    ```js
    let a = 2
    let b = 4
    ```

    The grey background however 
    ignores the first line of back-ticks.

## Expected behaviour

Code block is either matched one way or the other way. Not one way for code coloring and the other way for background color.

## Platform
 - Linux Mint 20.1
 - Zettlr Version 1.8.8

**Comment by nathanlesage** [comment]
Here we go, also decided to add those to indented code blocks

![image](https://user-images.githubusercontent.com/17251683/117942039-f0724e80-b30a-11eb-8604-8b2c99a25b90.png)

**Comment by Redsandro** [comment]
Thank you :+1:
