### ISSUE TITLE
[BUG] Renaming a note without changing the name causes note to disappear

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#1942]
## Description

Pressing F2 to rename a note and pressing Enter without changes and then answer "Yes" to overwrite the note causes the note to disappear

## Reproducing

Create any note make sure it is saved.

Then press the following

1. F2
2. Enter
3. Enter

Observe how the note just removed itself.

## Expected behaviour

When the filename is not changed after confirming the "new" name, nothing should happen.

## Platform
 - Linux Mint 20.1
 - Zettlr Version 1.8.8

**Comment by nathanlesage** [comment]
It should at worst just remove itself from the app, and be loaded again upon restart, can you confirm this? (That is, it does not actually get removed, it just disappears from the app)

**Comment by Redsandro** [comment]
On my system, the note is ~~removed from the filesystem~~ moved to the trash bin.

I tried both the AppImage and the .deb installer.

Linux Mint 20.1 AKA Ubuntu 20.04 with Linux 5.4.0.

**Comment by nathanlesage** [comment]
Wait … ah I think I know where this comes from.

**Comment by Redsandro** [comment]
Thank you. I feel safer already. :+1:
