### ISSUE TITLE
[ENHANCEMENT] Convert apostrophe internally when spell checking

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#1948]
## Description

Only the standard ASCII apostrophe `'` is in English dictionaries. A lot of pasted or converted documents contain a typographically pleasing apostrophe `’`. The spell check marks these words as incorrect.

![image](https://user-images.githubusercontent.com/1702193/117823652-00882080-b26e-11eb-9834-1f55958ac3ff.png)

## Proposed Changes

If we could spell check those words against the default ASCII apostrophe, they wouldn't be marked as invalid.

## Additional Information

I'm seeing a lot of `’`, but there might be others. 🤷‍♂️

**Comment by nathanlesage** [comment]
Sounds like a good idea – the file to look at would be this one: https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/modes/spellchecker.js (specifically the "check" function)

PRs welcome!

**Comment by Redsandro** [comment]
Thanks for pointing me in the right direction. Give me some time to get acquainted with Zettlr and see if I can figure this out.

**Comment by nathanlesage** [comment]
Hey, sorry for snatching that one away from you; I felt motivated … but I hope it's working as expected!

**Comment by Redsandro** [comment]
Heyyy! :angry: 

Naah, any time. I will find some other fish to fry. Thank you. :+1:
