### ISSUE TITLE
[ENHANCEMENT] Add keyboard shortcut to focus filter field

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#1949]
## Description

Right after searching, I often filter. There is no shortcut for that. It requires a mouse click.

According to the documentation, `Ctrl`+`Shift`+`F` gives focus to the **Find...** field. Also according to the documentation: _"We take the semantic meaning of the `Alt` key seriously. Therefore, take a high-priority shortcut, add an `Alt` to it and you normally tend to trigger an alternative action"_

Can we add an alternative action to focus **Filter...**?

## Proposed Changes

`Ctrl`+`Shift`+`Alt`+`F` gives focus to the **Filter...** field.

**Comment by nathanlesage** [comment]
There is a shortcut for it: `Cmd/Ctrl+Shift-T`, but it might very well be that it's missing from the docs – feel free to open a PR over there: https://github.com/Zettlr/zettlr-docs !

**Comment by Redsandro** [comment]
@nathanlesage thanks for pointing this out. Turns out, it _is_ actually in the docs:

> `Ctrl`+`Shift`+`T`: Gives focus to the tree window.

I have read all those hotkeys, and even copied a note as a cheatsheet. (I am just starting to use Zettlr.) I had previously read it, and rejected it. The problem is this:

![image](https://user-images.githubusercontent.com/1702193/117953770-a5f6cf00-b316-11eb-825f-16668b660733.png)

Even with that line in front of me, I assumed it would focus the **T**ree so I could navigate the folders with the keyboard or something, which was not what I wanted to do.

While selfishly speaking, the problem is now solved for me, I would still like to ask you to reconsider closing this feature.

1. It makes intuitive sense try any key combination involving the `F` key first. It's what I did, and so I discovered the Search shortcut.
2. When reading Zettlr motto in the docs: _"take a high-priority shortcut, add an `Alt` to it and you normally tend to trigger an alternative action"_ and considering Filter is basically search in search results, I'd retry `Ctrl`+`Shift`+`Alt`+`F` to make sure I tried it correctly before.
3. In many Electron apps and Chromium-based browsers, `Ctrl`+`Shift`+`T` is already associated with re-opening a previously closed tab.

I would still vouch for adding `Ctrl`+`Shift`+`Alt`+`F` as a keyboard shortcut, in conjunction with the existing shortcut as not to confuse new users, although you could give it a deprecation status because of reason 3 above.

**Comment by nathanlesage** [comment]
> Even with that line in front of me, I assumed it would focus the Tree so I could navigate the folders with the keyboard or something, which was not what I wanted to do. So I didn't even try.

Hah, you know what? The shortcut DOES in fact highlight the full file tree – the input is just focused ALONGSIDE with it :D But I see the potential for confusion.

> When reading Zettlr motto in the docs: "take a high-priority shortcut, add an Alt to it and you normally tend to trigger an alternative action" and considering Filter is basically search in search results, I'd retry the Search shortcut with Alt added to make sure I tried it correctly before

You are right, but to be honest, almost none of the shortcuts follow this motto, since if you try to keep the shortcuts consistent with _other_ apps, you begin to fathom the amount of inconsistency with that :/ 

> In many Electron apps and Chromium-based browsers, Ctrl+Shift+T is already associated with re-opening a previously closed tab. (E.g. you want to close 2 tabs, accidentally press Ctrl+W 3 times, followed by a Ctrl+Shift+T)

Interesting, I didn't know that.

> I would still vouch for adding Ctrl+Shift+Alt+F as a keyboard shortcut

I see your point, but pressing four keys …? :/ I'm not really sure …

**Comment by Redsandro** [comment]
Fair enough, I'll drop it. But there will be a time when people start demanding to have Ctrl+Shift+T for reopening accidentally closed notes! :smile:
