### ISSUE TITLE
Open/close directory is not saved when Zettlr crashes

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#196]
Use case :

1.Have folders A and B opened in Zettlr.  (for the record, consider that folder B is monitored by Fuse, as in #186 )

2. Close folder B (to avoid crashes related to Fuse)

3. Open folder C (which is not monitored by Fuse)

4. After some time, Zettlr will still crash but, on reopen, Zettlr will still have folders A and B (and not A and C as expected).

Zettlr 1.3 beta on latest MacOS.

**Comment by nathanlesage** [comment]
This is by design, as I only save the config on a regular exit. By this, potential problems with faulty configurations are tackled. This way you know that the configuration you've made will definitely work.
