### ISSUE TITLE
1.3 beta: pandoc issue

### ISSUE THREAD

**Issue by Monolecte** [Zettlr/Zettlr#197]
## Description
When I try to export document to PDF, I have this message : 

> pandoc: unrecognized option `--pdf-engine=xelatex' Try pandoc --help for more information.

Xelatex is installed (texlive-xetex) → /usr/bin/xelatex

## Platform
 - OS: Ubuntu LTS
 - OS Version 18.04
 - Zettlr Version 1.3 beta

**Comment by nathanlesage** [comment]
Please make sure to install Pandoc Version 2 or greater, as you seem to have a version 1.x which does not recognise the newer option `pdf-engine`.

See the Changelog of Pandoc for more details: https://github.com/jgm/pandoc/blob/master/changelog#L4349

**Comment by nathanlesage** [comment]
I just added the solution for this error to the FAQ, in case someone else stumbles across it!

https://github.com/Zettlr/zettlr-docs/commit/08be2e37f2860507e4b4ba4cdced1482522be753
