### ISSUE TITLE
Missing back or forward slash in the absolute paths to images if a folder contains a dot (.) at the beginning of its name.

### ISSUE THREAD

**Issue by Klemet** [Zettlr/Zettlr#1991]
## Description

When the path to images contains a folder whose name starts with a dot (e.g. ".config"), the absolute link to the image created by the parser (which is then sent to pandoc) lacks a backslash or forward slash in front of this folder. This leads to the path not being recognized.

## Reproducing

1. Create a folder named `test`
2. Inside this folder, create a folder named `.ressource`
3. Create a new `.md` file in the `test` folder
4. Put an image in the `.ressource` folder
5. Link the image in the `.ressource` folder with a relative or an absolute path in the new md file created
6. Try to export the .md file as `.pdf` or `.html`. Export to `.pdf` will result in a pandoc error as the image file is not found, and the `.html` file will not show the image.

## Expected behaviour

It is expected that a folder with a `.` at the beginning of its name should be properly integrated in the path to ressources.

Here is a screenshot of a test I made. The `.md` file is located in the `Zettler_test` folder. The image (`samoyed.jpg`) is in the `.test` folder, which is inside `Zettler_test`. The relative path given is hence `./.test`. As can be seen from the pandoc error, a backslash or forward slach is missing from the path. The same goes if the file is exported in .html format.

![image](https://user-images.githubusercontent.com/41070328/119057636-d08dfb00-b99a-11eb-80de-8fce42b65c66.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.8

**Comment by nathanlesage** [comment]
That's odd. I just had a look but couldn't identify any piece of the code that might cause this problem. Would you mind trying to export your file using pandoc _directly_ instead of using Zettlr? If that works we can confirm it's a problem in Zettlr and I can take a look.

**Comment by Klemet** [comment]
I just tried with the following pandoc command : 

`pandoc "D:\Clement\Desktop\Zettlr Test\test_Image_Path.md" -f markdown -t latex --pdf-engine=xelatex --mathjax -o "D:\Clement\Desktop\output.pdf"`

With the link of the image in the test file being : 

`![](D:/Clement/Desktop/Zettlr Test/.test/samoyed.jpg)`

And it worked like a charm. The image is embedded in the resulting `.pdf`, as should be the case.

I believe the issue might be in the step where Zettlr reads the paths to images that are in the file, and converts them to absolute paths. I'm pretty sure that a dot at the beginning of a folder name might trigger a process (or avoid triggering it) that leads to a missing slash.

**Comment by nathanlesage** [comment]
Okay, perfect, so the issue must be in here somewhere: https://github.com/Zettlr/Zettlr/blob/develop/source/common/util/make-img-paths-absolute.js

Could be an issue with the regular expression. Oh, or even more trivial: Since it's a dot (indicating the current directory) but WITHOUT the slash right next to it (so `.` instead of `./`) that might be the cause!

I'm not sure when I can get to it, but if someone wants this, it's up for grabs and should in fact be simple to implement. PRs welcome!

**Comment by nathanlesage** [comment]
I think I found the bug: Zettlr would always attempt to resolve a path, even if it was already absolute. This might've caused the dot to cause problems. If the problem persists in 2.0, just drop me a line!

**Comment by Klemet** [comment]
Thanks, @nathanlesage ! I'll try to remember it : ). Great job finding the bug !
