### ISSUE TITLE
Please add a button to change the root folder on Windows

### ISSUE THREAD

**Issue by sahil48** [Zettlr/Zettlr#2]
It would be nice to have a menu or button for changing the root folder instead of using ctrl+o as a shortcut.

**Comment by sahil48** [comment]
Yes. I think it should have the icon currently reserved for the create new folder button. A separate button (folder with a + sign or something different) should be used for creating a new folder.

**Comment by nathanlesage** [comment]
Yep, I was thinking of this, but fontawesome (which I'm using for the buttons) stupidly doesn't feature such icons, so I'll first have to find a new icon font …

**Comment by nathanlesage** [comment]
The new font definitely does its job. So button will be added in the next version.

![screen shot 2018-02-25 at 20 05 47](https://user-images.githubusercontent.com/17251683/36645335-552e3446-1a67-11e8-90bc-5f40ecbf3dc7.png)
