### ISSUE TITLE
[Develop] Breakages due to Webpack 5 migration

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#2016]
Electron forge has finally released the webpack 5 update, so I have taken the liberty of merging all the dangling PRs from dependabot for the plugins that were progressively switching to webpack 5 in the past half year.

I knew that this would cause breakages, but we definitely should use Webpack 5, both to silence dependabot and because more and more plugins wouldn't get any more updates for webpack 4.

What is going wrong?

So, first, somehow this process broke `archiver`. I don't quite know why but there is a module that archiver can't resolve right now (or, to put it correct: Somehow TS fails at resolving the module). Please note that VS Code's resolver _does_ correctly find the module, so I'm guessing that this might be a configuration we have to change in tsconfig.

Then, a second thing is that all the Node module resolutions broke during the update, because webpack 5 doesn't include silent fallbacks for these anymore. We have to specifically ignore these imports (rather, most of these are, if I have seen it correctly, caused by `require`s, not `import`s).

So we probably get away with some config tweaks. I'm opening this issue because right now I have to get back to work, but I'm pretty happy that we could finally update all those outdated dependencies, which additionally made a security advisory go away on the repo 💁🏻

CC @tobiasdiez

**Comment by tobiasdiez** [comment]
For the second issue, maybe it's worth directly converting all requires to imports (if the latter are indeed working). There are only 200 or so require statements left, so that seems to be doable.

**Comment by nathanlesage** [comment]
The second thing was actually pretty easy: I just had to tell webpack to leave `require`s for node modules alone. I got everything to compile successfully, however now I'm stuck with two further errors that we have to pin down.

First, running Zettlr in dev mode somehow has included some `eval` which is (obviously) blocked. Enabling unsafe-eval makes that error go away, but somehow the following code managed to sneak into the builds:

```js
85428: (e,t,n)=>{
            const r = n(48102)
              , i = n(10629)
              , o = n.ab + "path.txt";
            e.exports = function() {
                if (r.existsSync(n.ab + "path.txt")) {
                    const e = r.readFileSync(o, "utf-8");
                    return process.env.ELECTRON_OVERRIDE_DIST_PATH ? i.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, e) : i.join(__dirname, "dist", e)
                }
                throw new Error("Electron failed to install correctly, please delete node_modules/electron and try installing again")
            }()
        }
```

So there seems to be something else going on (note, with "sneak into the builds" I literally mean I got that error in a packaged app.

However, at least we just got rid of 20MB in size due to the non-existing polyfills, which is at least something, I'd argue 💁🏻

I'm just committing the changes to the config I have made. Please have a look https://github.com/Zettlr/Zettlr/commit/5061aca4041ca7ab2496401cd41553885bd2f8a3 (and also note that I've removed the node_modules resolution path in TSConfig, since we don't need it, and I figured this way we can exclude that interfering)

**Comment by nathanlesage** [comment]
Final update: Found solutions/quick fixes to the problems. Forge is now working properly again.

For further updates, I reported what I found out to the Forge team, so please refer to https://github.com/electron-userland/electron-forge/issues/2289 for further discussion.
