### ISSUE TITLE
[ENHANCEMENT] Non *txt but text files

### ISSUE THREAD

**Issue by yashpalgoyal1304** [Zettlr/Zettlr#2024]
## Description

Ability to open and save files whose format is not for common text related stuff, but their content is still just text. like windows notepad and notepad++ does.

## Proposed Changes

Like i was editing json files. And i can very well use the multi cursor editing of zettlr for those. But zettlr failed to open those files.

## Caveats

i dont think much, the only thing i can imagine is that *other* people may request further extensions of this feature - like syntax highlighting and stuff. But typora also opened the json file well and it doesnt have any non *md syntax highlighting either.

**Comment by yashpalgoyal1304** [comment]
i was thinking that maybe this request can be put away by saying smth like "zettlr is not intended for those uses" but yeah, other ppl are using it for that purpose too :) just mentioning here beforehand to save myself 😅  

https://github.com/Zettlr/Zettlr/issues/1715

**Comment by nathanlesage** [comment]
In principle, it would cost me like 10 lines of code to transform Zettlr into some VS Code like thing that can edit any plain text code file, but I haven't done this because I fear that this completely kicks Zettlr off course. So I'm still pondering the thought, and am still undecided of how and what to do.

Very likely: Enable editing of files related to Markdown workflows (e.g. YAML, JSON, maybe bash script)

Very unlikely: Enable editing of files unrelated (such as C++ source, Rust, Python, etc.)

**Comment by yashpalgoyal1304** [comment]
how about just adding the support like silently - like not gaining attention way. That is, the file associations stay as current (zettlr not associated with those), and those other files are not included in default files filter while opening either. 
![image](https://user-images.githubusercontent.com/19423063/119535646-dc682b80-bda5-11eb-93e0-fef80b91b67f.png) 

So, the overall ui change would be just that there's a new filter for "all files" in the file open dialog. Rest there will be no indication in any way that zettlr opens those too. No syntax highlighting, no any fancy stuff for those. no nothing.

**Comment by SecT0uch** [comment]
I would live to be able to edit config files or scripts.
My documentation heavily relies on (separate) file examples and being able to edit them along the documentation would be awesome.

I'm thinking conf, ini, yaml, sh, py, etc.

Can this be re-opened?
