### ISSUE TITLE
[ENHANCEMENT] Exporting should display just as preview

### ISSUE THREAD

**Issue by Porrumentzio** [Zettlr/Zettlr#2046]
## Description
I was first opening an issue as bug when I realized that exporting MD to any other format does not respect linebreaks as they are displayed, when I noticed that actually it was exporting as it should, considering the input file as pure markdown.
The problem is that the preview is not pure markdown and that simple linebreaks (without two whitespaces for line end) are displayed as common linebreaks, while on the core of the file format they aren't.

## Proposed Changes
So my proposal is to somehow export simple linebreaks as they are displayed, whether by using another Markdown style/type which will make simple linebreaks into full ones (for example GitHub's Markdown style/flavour) or by adding some parameter into exportation order that will make simple linebreaks into full ones.

## Caveats
I don't think so, as long as pure markdown linebreaks (two whitespaces for line end) are respected to.

## Additional Information
This happened to me with this MD:
```
#landare #sendabelar #janari
# Baratxuria edo berakatza
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Allium_sativum_Woodwill_1793.jpg/220px-Allium_sativum_Woodwill_1793.jpg)
```
Which was being rendered/exported as:
![irudia](https://user-images.githubusercontent.com/61913683/120177829-1bb0d500-c209-11eb-9d74-5674f12b4aab.png)

While the preview was:
![irudia](https://user-images.githubusercontent.com/61913683/120177874-27040080-c209-11eb-91ec-c91344ba36a0.png)

**Comment by Porrumentzio** [comment]
Also happens that headers must have an empty line before to be exported as headers, at least to HTML:
```
#landare #sendabelar #janari
HERE MUST BE EMPTY LINE
# Baratxuria edo berakatza
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Allium_sativum_Woodwill_1793.jpg/220px-Allium_sativum_Woodwill_1793.jpg)
```
But same as proposed, headers displayed that way should be exported well.

**Comment by nathanlesage** [comment]
Difficult. With regard to header highlighting, this clearly seems as if I have to go back to that again for 2.0. But with regard to linebreaks, I think that it is precisely the case that linebreaks must behave differently.

Idea behind this: Many people write better if they only write one sentence per line, and then separate paragraphs using two linebreaks. This is also pretty explicit in the specs. The rendered elements are only those in which it makes sense for better readability, many elements are not actually rendered (and that for a reason).

**Comment by nathanlesage** [comment]
Unfortunately, you can't export from preview; as I said: It's neither an export nor something you could transform into anything else. Have you seen [this part of the docs](https://docs.zettlr.com/en/concepts/wysiwym/)?
