### ISSUE TITLE
[ENHANCEMENT] Sort all files in one list when directories are hidden

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2049]
## Description

When you choose to hide directories in a global search:

![image](https://user-images.githubusercontent.com/1702193/120198274-38a5d200-c222-11eb-8e83-18e836ba77cc.png)

Every search result is still invisibly grouped by their containing directory, resulting in a confusing and seemingly random order of notes in search results. It makes sense to sort them as one list.

## Proposed Changes

When directories are hidden, sort all notes as if they are one list. (It makes sense because visually they are.)

## Additional Information

Although unrelated, on one particular machine I cannot seem to turn showing those directories back on. The toggle doesn't change anything. Even after upgrading to the latest 1.8.9. Can you spare some advise? :sweat_smile:

**Comment by nathanlesage** [comment]
That's no problem in 2.0 anymore, since that features a completely rewritten global search! If you are eager to try it out, [there are nightlies available](https://nightly.zettlr.com/), otherwise the beta isn't far away!

That being said: Thanks for pointing out that I need to remove that setting =D

**Comment by Redsandro** [comment]
I didn't know about this secret Zettlr 2.0. Haven't read about it in your blog. Is this a scoop?
The 1.8.9 nightlies contain the 2.0 global search?

**Comment by nathanlesage** [comment]
> The 1.8.9 nightlies contain the 2.0 global search?

Yes, they are still called 1.8.9, but only because electron-builder right now is incapable of including the "+"-part of the version number. In fact, they are "1.8.9+nightly-YYYYMMDD" (which you can then see when opening the About panel)
