### ISSUE TITLE
Citation file cannot be loaded with empty entry (minor issue)

### ISSUE THREAD

**Issue by mattwien** [Zettlr/Zettlr#2050]
## Description
When an empty entry is in my citation file (.bib), the file cannot be loaded. 

## Reproducing
I want to create a new book based on ISBN in Zotero, click the manual creation button accidentally, delete it, but it's still in the export file, but without any content. I have to go manually to the recycle bin in Zotero to delete it. This situation isn't catched by Zettlr. I don't know if it's rather a but in Zotero, still the first time I encountered the problem, it took me a few days to find the issue.
![image](https://user-images.githubusercontent.com/70956195/120229711-f7c3b280-c24d-11eb-89e6-2a79bf264446.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.9

## Additional information
Error message when opening Zettlr
![image](https://user-images.githubusercontent.com/70956195/120229527-a1567400-c24d-11eb-90b3-a692ec4aa385.png)

**Comment by nathanlesage** [comment]
If that still constitutes a valid BibTex file, I would recommend you open this issue against the [astrocite library](https://github.com/dsifford/astrocite/), which is the creator of the error message you see there!

(I'd argue you at least need that comma behind the citation key, but then I'm no expert on BibTex.)
