### ISSUE TITLE
Find next CTL+G hotkey support

### ISSUE THREAD

**Issue by rccordell** [Zettlr/Zettlr#2052]
## Description
I propose that Zettlr add "find next" keyboard functionality, which is usually `CTL + G` in other applications.

## Proposed Changes
Currently `CTL + F` pulls up the find function, but unless I'm missing something I don't see a way to easily cycle through all the instances of a search term. Usually when I'm writing I make frequent use of `CTL + G` to quickly find what I'm looking for. I know that Zettlr will allow me to click on the "Find" button repeatedly but it would be fantastic if this were a keyboard shortcut like in many other writing applications.

## Caveats
I don't think this would affect anything else. Currently `CTL+G` doesn't seem to do anything, so I don't think this would interfere with any other functionality.

**Comment by nathanlesage** [comment]
Never implemented that (you can find the next occurrence by pressing Return, though). Could prove somewhat difficult since the search plugin is custom and not an actual CodeMirror plugin … would need some refactoring – so I can't give any ETA yet.

**Comment by rccordell** [comment]
I had not realized that `enter` would do the trick, so I can adapt to that for now. `CTL+G` is hardwired in my fingers from other apps, though, so if it's possible without too much effort I think it would be worthwhile.

**Comment by nathanlesage** [comment]
Yeah, I just double-checked the CodeMirror docs, and they have a command reserved for this. So basically all I need to do is figure out a way to call `findNext` when the corresponding command is being called!

**Comment by nathanlesage** [comment]
Coming in 3.0 because we're now using the default search panel
