### ISSUE TITLE
[ENHANCEMENT] Exporting to HTML should embed images

### ISSUE THREAD

**Issue by Porrumentzio** [Zettlr/Zettlr#2054]
## Description
Exporting MDs into HTML files should embed the images.

## Proposed Changes
Currently it does reference the image path, so if the path is local it won't be displayed in other devices.

## Caveats
I don't know if it's possible to embed images on a HTML file itself, without external path.

**Comment by nathanlesage** [comment]
No, it should not — at least not by default. Embedding images via plain text means transforming them to base64, thereby increasing the image's size by 1.3x and additionally making the HTML slower to load.

However, don't worry, from version 2.0 onwards, you can modify the defaults file easily and set the corresponding option that does that: `self-contained: true`. This way you can by default embed all images in HTML exports easily. And if you need a file without its images embedded, you can easily revert that option.

**Comment by Porrumentzio** [comment]
Thanks for the answer, I'm waiting excitedly for 2.0! :)
