### ISSUE TITLE
[Feature request] Autoformat tables

### ISSUE THREAD

**Issue by yannforget** [Zettlr/Zettlr#206]
It would be nice to integrate a way to autoformat markdown/pandoc tables.

See for example the [table-formatter](https://marketplace.visualstudio.com/items?itemName=shuworks.vscode-table-formatter) VSCode plugin.

Many thanks!

**Comment by nathanlesage** [comment]
Already on the roadmap.

Here's the current frontrunner for doing so: https://github.com/brrd/celldown.js
