### ISSUE TITLE
[ENHANCEMENT] Support RMarkdown files

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#207]
## Description

RMarkdown files are regular Markdown files that have some benefits such as embedded runnable code that are used in RStudio. As it is therefore also possible to edit them easily with Zettlr (minus running code directly), Zettlr can easily support opening `.rmd`-files as well.

## Scope

As the file extension `.rmd` is also used by other softwares that write binary data to them across the board, according to FileInfo, RMarkdown support will be off by default. This is meant as a safeguard for people that, for instance, use Adobe Premiere (which apparently writes `.rmd`-files) and Zettlr for video scripts, but don't know RMarkdown. So they can't accidentally open ugly files (if you want to see it for yourself, take a file with binary data in it, rename it to `.md` and open it with Zettlr).

Therefore, a preferences toggle will be implemented that has to be switched on for Zettlr to open `.rmd`-files.

**Comment by haphap** [comment]
Thank you for considering the Rmarkdown!
