### ISSUE TITLE
[FEATURE] Define folder to sync notes between machines

### ISSUE THREAD

**Issue by mosesontheweb** [Zettlr/Zettlr#2071]
## Description

I'm currently using Joplin as my favorite note taking app. It's nice and useful and has one feature, which makes it special to me. You can define a folder where the app should store all notes, where other instances of Joplin can take them. This is called "sync". Works great for me on my Windows host and Ubuntu guest in VirtualBox on a shared folder between them. Would be great if Zettlr may get a similar feature.

## Example Workflow

- Define a folder where the notes database or notes folder should be stored to
- open your guest OS, define the location as shared folder, define that shared folder in the app in the guest OS as sync folder
- Press sync
- Voilá!

## Caveats

None from my point of view

## Additional Information

I hope I explained it as detailed as possible.

Regards, Thomas

**Comment by waterfallpit** [comment]
Perhaps I'm missing something obvious here, but this should already be possible with Zettlr and other editors that save notes in text files. For example: in the host OS in Zettlr go to Open workspace and pick a folder that is shared with the guest OS. Then in the guest OS pick the same folder in Zettlr. If you have opened a note (a file) in Zettlr, while you change the same file in another application (or another instance of Zettlr running in, say, guest OS), Zettlr will notice you update the file contents.
Last time I tried Joplin, it was using database to store notes, not "flat" text files as Zettlr (and other) markdown editors do.

**Comment by nathanlesage** [comment]
If nobody overlooks something obvious here, what @waterfallpit says.

**Comment by ThaddaeusWiedemer** [comment]
I agree with @waterfallpit. this seems to already work. You can even use third-party tools like OneDrive or Github to sync the entire Zettelkasten folder across pretty much any device.

**Comment by nathanlesage** [comment]
Yup. Actually, _any_ cloud provider should do (although OneDrive is sometimes a little bit picky). Closing as fixed.
