### ISSUE TITLE
Mouse clicks not working in Linux Mint and Debian

### ISSUE THREAD

**Issue by yaxu** [Zettlr/Zettlr#2088]
## Description
In dialogues (like opening a file, or importing iles) mouse clicks do not work. I can use the escape key to close the dialogue, then if I switch to another app (like a web browser) and click, it switches to the zettlr window. From then it goes back to normal until I try to open a file again. The 'about zettlr' dialogue works fine. I can't think what might be causing this on my side, I tried a fresh reboot..

## Reproducing
Click file, then open, then try to click something else.

## Platform
 - OS and version: Linux mint 20 MATE
 - Zettlr Version: 1.8.9

**Comment by yaxu** [comment]
I noticed this in the console, I wonder if it's related:
```
(node:5199) ExtensionLoadWarning: Warnings loading extension at /home/alex/.config/Zettlr/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `Zettlr --trace-warnings ...` to show where the warning was created)
```

**Comment by yaxu** [comment]
I've reproduced this issue in Debian 10 (buster).

**Comment by nathanlesage** [comment]
Could it be that this is a duplicate of #1645?

**Comment by yaxu** [comment]
Yes sorry, I missed that somehow.
