### ISSUE TITLE
Unable to paste code in Zettlr

### ISSUE THREAD

**Issue by rahulbansal16** [Zettlr/Zettlr#2089]
## Description

I am trying to code from a website and I was unable to paste it inside the Zettlr. 

## Reproducing

Copy the html code 
```
<html>
<head>
  <title>Beautiful page</title>
</head>
<body>
    
  <p>
    Once upon a time there was 
    a looong paragraph...
  </p>
  
  <div style="display: none">
    Secret message
  </div>
  
  <div><img src="..." /></div>
  ...
 
</body>
</html>
```
and try pasting it inside the Zettlr

## Expected behaviour

 The code should be pasted with no issue.

![image](https://user-images.githubusercontent.com/8466045/121879529-99590280-cd2a-11eb-83ac-dd2ef3662c51.png)

## Platform
 - OS and version: Windows
 - Zettlr Version: 1.8.9

**Comment by nathanlesage** [comment]
This should work by "pasting without formatting" (Ctrl+Shift+V). Pasting normally (Ctrl+V) will attempt to render it to Markdown instead of pasting exactly what you want pasted.

If this also doesn't work, please comment here again!

**Comment by rahulbansal16** [comment]
Thanks @nathanlesage
