### ISSUE TITLE
[ENHANCEMENT] Export using pandoc-scholar

### ISSUE THREAD

**Issue by manueldeljesus** [Zettlr/Zettlr#2093]
## Description
For scientific paper writing, it would be really convenient to be able to export documents using [pandoc-scholar](https://github.com/pandoc-scholar/pandoc-scholar).

## Proposed Changes
Additional export options would appear to export the current document using pandoc-scholar. Zettlr could even allow the user to create customized export buttons running specific scripts; the user being responsible to configure the desired export option (this would be a more general solution).

## Caveats
Specifically supporting pandoc-scholar or other similar solution may introduce dependencies that have to be tracked. If additional export options could be created by users, **they** would be responsible to update **their** workflow when external utilies changes their expected behavior.

**Comment by nathanlesage** [comment]
Would you be happy with what Axel has described in this issue? #1842 

Since that's what I wanted to implement for 2.0 either way, and it seems to cover what you want, right?

**Comment by manueldeljesus** [comment]
I'd say so, yes. I was mostly interested in pandoc-scholar, but as I was writing the issue I thought about the external command. Should have checked if some other issue suggested this possibility.

Thanks!

**Comment by nathanlesage** [comment]
Alright, then I'll be closing this one, since 1842 is already in the project :)
