### ISSUE TITLE
Incomplete table of contents 

### ISSUE THREAD

**Issue by fourteenminusone** [Zettlr/Zettlr#2095]
Hi,
I recently switched to Zettlr (until recently I was using Typora) and I find it very simple, intuitive and responsive. The only problem is that the table of contents that can be viewed by clicking on the sidebar at the top right is incomplete. In detail, only a part of the table is displayed up to a certain header after which it is as if it no longer recognizes new headers. The file I am editing is a `.md` one. The strange thing is that in another file (`.md`), the table of contents is displayed complete (when I add a header a new entry is generated in the table of contents)

Could you check please?

**Comment by nathanlesage** [comment]
Do the headings after said point somehow look different than before? Or is there anything following the last recognised heading in the text (i.e. somehow wrong looking syntax highlighting) that might be indicative?

It would be great to add some more info, maybe paste parts of that file in here, or make some screenshots, so I can have a better look at the problem.

**Comment by fourteenminusone** [comment]
Hi Hendrik,

thank you for your feedback. I cannot perceive any difference between the
last *1.10.1 Single User* header that is correctly reported in the table of
contents and the first header *Global System* that is not reported (please
see attached a screenshot of the file I' editing.

Thank you.
Riccardo

Il giorno mar 15 giu 2021 alle ore 17:45 Hendrik Erz <
***@***.***> ha scritto:

**Comment by nathanlesage** [comment]
Dear @fourteenminusone,

unfortunately, the attached screenshot was not added to your comment. Would you mind using the website directly to provide the screenshot?

Thank you very much!

**Comment by fourteenminusone** [comment]
Here is the screenshot.

![screen_zettlr](https://user-images.githubusercontent.com/22525437/122093784-b6b1cd80-ce0b-11eb-856f-c8dde024055b.png)

**Comment by nathanlesage** [comment]
Thank you! This is indeed odd behaviour. I cannot spot anything right away that might cause this from the screenshot. I think I have to take a look at this here on my computer.

Would you mind sending me this file so I can check locally, and ideally already fix the problem? If that file contains sensitive data, you can also send it via mail: info@zettlr.com.

**Comment by waterfallpit** [comment]
It's the dash in front of the code segment. See the example below. With the dash I can't see h3.2 in TOC, but without the dash h3.2 is there. Try pasting this into Zettlr and then add a dash and a space ("- ") in front of both triple backticks. Even github doesn't render it correctly, that's why I omitted dashes here.

# h1
## h2
### h3.1
```bash
ls -la
```
### h3.2
```bash
ls -la
```

**Comment by nathanlesage** [comment]
@waterfallpit Ouh, I overlooked that one, since in 2.0-dev this is already fixed (at least I think? I'll try this later today just to be sure). Thanks for pointing that out!

**Comment by fourteenminusone** [comment]
Thank you guys.

Riccardo

Il giorno mer 16 giu 2021 alle ore 09:06 Hendrik Erz <
***@***.***> ha scritto:

**Comment by nathanlesage** [comment]
@fourteenminusone Does this mean this issue has been solved?

**Comment by fourteenminusone** [comment]
Yes, it was the dash that created the issue I described

Il mer 16 giu 2021, 17:10 Hendrik Erz ***@***.***> ha scritto:
