### ISSUE TITLE
In RTL macOS, toolbar and window buttons overlap

### ISSUE THREAD

**Issue by tom-programming** [Zettlr/Zettlr#2097]
## Description
In RTL macOS (Hebrew/Arabic), the close/maximize/minimize buttons are on the right side of the window. They overlap with the toggle sidebar and pomodoro buttons of the toolbar

## Reproducing
Use Arabic or Hebrew as the system language in macOS settings or open the app with a tool like "App Language Chooser" and select Arabic, Hebrew or Farsi (I guess)

## Expected behaviour
It should detect if the window has its buttons on the right (or if the language is RTL) and leave the space in the toolbar for the window buttons in the right instead of in the left

See at the right top corner

![screenshot](https://user-images.githubusercontent.com/29755050/122306069-86a02280-cf10-11eb-867e-1fcb7c3c5394.png)

## Platform
 - OS and version: macOS Catalina 10.15.7
 - Zettlr Version: 1.8.9

**Comment by nathanlesage** [comment]
Ah THANK YOU. That was one of my biggest worries on the 2.0 roadmap! I'll have a look!
