### ISSUE TITLE
"Export project" always removes internal links

### ISSUE THREAD

**Issue by marshrossney** [Zettlr/Zettlr#2099]
## Description
Handling of [[internal links]] during project export appears to be broken. When I export a single file, the options for handling internal links found under "Preferences/Export" work as expected. When exporting the same file using "Export project" internal links are always removed, regardless of which option is selected.

## Reproducing
I created a project directory with a single file containing some internal links, and compared the result of exporting that file with the output of "Export project".

## Expected behaviour
I would expect the "Preferences/Export" settings to apply globally. 

## Screenshot
Left is MD, top right is single file export, bottom right is project export. With the option "Unlink internal links" selected. 
![Screenshot from 2021-06-17 19-06-06](https://user-images.githubusercontent.com/17361029/122450760-4b006980-cf9f-11eb-8864-88f147e20fd8.png)

## Platform
 - OS and version: Ubuntu 20.04
 - Zettlr Version: 1.8.9-x86_64 (AppImage)

## Additional information
Zettlr is cool.

**Comment by nathanlesage** [comment]
Fixed in the exporter for 2.0.0.
