### ISSUE TITLE
Combined preview and directory pane as option

### ISSUE THREAD

**Issue by seeseekey** [Zettlr/Zettlr#21]
I have tried the current development version. In my opinion, the new "Combined preview and directory pane"-feature is impractical for the workflow. Can you please make it optional via settings?

**Comment by nathanlesage** [comment]
I should've known that this was a highly individual choice by me … alright, I don't know how fast I can implement the switching, but I'll put this further upwards on my agenda.

**Comment by nathanlesage** [comment]
Was easier than I thought. Here you go!
