### ISSUE TITLE
[Feature request] Quicklook and Custom CSS 

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#210]
I've noticed that when you change the Zettlr's themes the Quicklook option displays the files in the new theme. Could it be possible that Quicklook also loads the Custom CSS? As it is a different window I did not found a way to enable my changes using my modified CSS. 

And also, as a suggestion, wouldn't it be natural to have WYSIWYG enabled by default in Quicklook? Is not like you can modify anything in there...

**Comment by nathanlesage** [comment]
Concerning the custom CSS: Yup, got a point!

Concerning WYSIWYG: I've deliberately deactivated _everything_ there, as this way you see precisely what you'll be copying. If everything's prerendered it hides code, yet one of the fundamental principles of Zettlr is to not hide anything from the user (otherwise we could just rebrand it as "Word for Markdown")!

**Comment by samarulmeu** [comment]
Thank you for considering the Custom CSS.

As of the other "issue", I'm not a fan of WYSIWYG. It was just a suggestion, I did not take into account the copy feature. I use the Quicklook (when I need it) on half of the screen for reading other notes and on the other half I have the editor.

**Comment by nathanlesage** [comment]
Mh... maybe I could consider a "toggle preview" switch on Quicklook windows triggering a full WYSIWYG ...

**Comment by samarulmeu** [comment]
This could be an option, but if it is too much work, please focus on the more important stuff. The Custom CSS I think will be just enough for the moment, if you have the time. Thank you again!

**Comment by samarulmeu** [comment]
Please do not forget to implement also the root variable for main color use in Custom CSS as described [here](https://github.com/Zettlr/Zettlr/issues/85#issuecomment-477510577)

**Comment by samarulmeu** [comment]
Thank you! 🎉
