### ISSUE TITLE
Table of Comments in PDF/DOCX Export

### ISSUE THREAD

**Issue by BrandonKMLee** [Zettlr/Zettlr#2103]
## Description
Currently, Microsoft Office and Google Docs have a TOC function, if there is a way of doing this in Zettlr would be perfect.

## Proposed Changes
Something similar to https://pandoc.org/MANUAL.html#option--toc but for Zettlr

## Caveats
TexLive is installed on the computer but the PDF function is not working.
https://community.chocolatey.org/packages/texlive
https://github.com/naveen521kk/chocolatey-texlive/issues/3

## Additional Information

https://support.microsoft.com/en-us/office/insert-a-table-of-contents-882e8564-0edb-435e-84b5-1d8552ccf0c0
https://support.google.com/docs/answer/116338?co=GENIE.Platform%3DDesktop&hl=en

**Comment by nathanlesage** [comment]
You can achieve this by adding `toc: true` to the YAML frontmatter of your file. Beginning with 2.0 you will be able to make that the default behaviour for all files.

**Comment by BrandonKMLee** [comment]
@nathanlesage how do I do that in the one-click method of making DOCX/PDF?

**Comment by nathanlesage** [comment]
Inside your file where you want to have a table of contents generated, you need to add a YAML frontmatter section, if not already:

```markdown
---
# Any values go in here. The three dashes must be the very first thing on the first line of the file.
---

# A heading

Some text here ...
```

Inside that three-dash-section, you need to put `toc: true`, that is:

```markdown
---
toc: true
---

# A heading

Some text here ...
```
