### ISSUE TITLE
Connection to clients2.google.com

### ISSUE THREAD

**Issue by dturaev** [Zettlr/Zettlr#2104]
Thanks for this very nice editor. Upon installation, the app connects to clients2.google.com. Just out of curiosity, what is the purpose of this?

**Comment by nathanlesage** [comment]
> Upon installation, the app connects to clients2.google.com

Are you really sure about this? There is no connection to any google services inside my app. The only hard-coded connection is to our api to check for updates, but not to google.

It might be that there is some image or some iFrame that requires such a connection, but it should not happen in the app itself. If you close all files and open a Markdown file that only contains text, is that happening still?

**Comment by dturaev** [comment]
Thanks. At least that's what my firewall said yesterday, but I can't currently reproduce. (At least, I tried `grep -r "clients2.google.com" /Applications/Zettlr.app/`, and some files matched. May be somehow related to the Electron framework.) Will close the issue and re-open if I can reproduce.
