### ISSUE TITLE
Export Changes British Punctuation of Quotations to US Punctuation

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2105]
## Description
In British English punctuation immediately after quotation marks remains outside the quotation marks, in US English it does not.  I write my British English text in Zettlr but when I export it changes the punctuation to US punctuation.

## Reproducing
Write something in a file like: This sentence ends with a quotation "this is my quote".

Note that the full stop is OUTSIDE the quotation marks, which is correct for British English.

Export (I've tried HTML and PDF) and you'll see your sentence is now in the form: This sentence ends with a quotation "this is my quote."

Note that the full stop has now moved to INSIDE the quotation marks, which is correct for US English and not what I wrote.

## Expected behaviour
I'd expect it not to change what I've written!

## Platform
 - OS and version: Ubuntu 20.04
 - Zettlr Version: 1.8.9

**Comment by nathanlesage** [comment]
Try setting your `lang` in your frontmatter to `en-GB`: https://docs.zettlr.com/en/core/yaml-frontmatter/#variable-lang

Something like this:

```markdown
---
# other frontmatter vars ...
lang: en-GB
# other frontmatter vars ...
---

# My heading

Some text
```

**Comment by mousetrappling** [comment]
Thank you! That works.

So it wasn't so much a bug as my failure to know how to set things up properly.  Would it be possible to add a note in the docs for the lang setting that it's also useful for punctuation handling? Even if I'd thought to look at that page I probably wouldn't've realised that variable would affect how it was going to handle punctuation from the description.

**Comment by nathanlesage** [comment]
Please! The docs are public access precisely that this is possible! Please open a PR!

**Comment by mousetrappling** [comment]
I think I have successfully edited the docs and submitted a PR, but I have never done that before for a project on github so if I've failed in some fashion to do it properly can you let me know so I figure out what went wrong?

**Comment by nathanlesage** [comment]
Yes, sure! Let me have a look!
