### ISSUE TITLE
Bug: Setting writing target on the last file

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#211]
I think that this affects all versions of Zettlr: I can't set a writing target on the last file that it is displayed on the left panel as the word's "window" is covered being always displayed under the file name. Maybe this window can go above the filename?
As a solution, I have to rearrange the file in order to set a target.
I'm using a Debian based Linux distribution, but I think it is present all systems.

**Comment by nathanlesage** [comment]
Mah, I thought I told the popup windows to always position themselves where they'll be visible >:O

I'll see to it!

**Comment by nathanlesage** [comment]
Fixed in https://github.com/Zettlr/Zettlr/commit/1b49c225b365e6b96cffd272106638c429145fca
