### ISSUE TITLE
Confusing labels when shrinking Zettlr

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#2119]
## Description

With Zettlr shrunk below 25% screen space it shows only 'Import' for both options but adjusting the window by a faction shows the correct labels i.e. 'Import translation...' and 'Import dictionary'.
## Reproducing

Open Zettlr and shrink to below 25% screen space and open 'File' tab.
![Animation1](https://user-images.githubusercontent.com/44082853/123089660-c1c1ba80-d416-11eb-8941-296df8d677f6.gif)
## Expected behaviour

'Import translation...' and 'Import dictionary' should show always.

## Platform
 - OS and version: win32 10.0.19042 (architecture: x64)
 - Zettlr Version: 1.8.9+nightly-20210619 (and latest 2.0 DEV)

## Additional information

This is follow up to a comment I made on the Zettlr 2.0 BETA testing issue.

**Comment by nathanlesage** [comment]
Thanks for reporting! However, I can't currently debug that. Would you mind opening up the dev tools, then pulling up that menu again, and using the "inspect element" feature of dev tools to see if both are the same element, or if there is any indication why this is happening (and, only to the imports…?)?

That would be great!

**Comment by nathanlesage** [comment]
Looking at the GIF again I realized what could be happening: Apparently, the accelerator section (shortcuts) collapsed on top of the labels at some point (hence it LOOKS as if there is two times the "import" item, although it's just cropped text).
