### ISSUE TITLE
[FEATURE] Multiple split tabs a.k.a Multiplexer

### ISSUE THREAD

**Issue by dybjto** [Zettlr/Zettlr#2123]
## Description

Current Zettlr is limited to one single pane. While multiple tabs can be open, only one shows on screen.
Split pane would help when working with literature (e.g. definitions), drafts, or coding while following a statistical analysis plan
Split pane could be done horizontally, vertically, and it could be nested

This would be a great feature for Zettlr 2.0 

## Example Workflow
Here is an exemple using obsidian.md, another notetaking app. 

![image](https://user-images.githubusercontent.com/40626358/123285752-9bcb1180-d50d-11eb-94e0-ff58c4666061.png)

This picture contains 4 different panes which can all be split again independently of each others. 
Each pane can be edited, closed, or pinned, or exported. That means each pane is fully independent.
Additionally, each pane can have a different fonts size (ctrl + ±) 
Finally, pane can be moved and re-arranged using drag&drop, they will automatically adapt to the location (further vertical split or side by side)

Pane layout can be saved so the structure remains when quitting and re-opening the app (currently needs a plugin)
## Caveats

Unsure how synchronization would work with two panes open on the same file.
Should there be a limit to the number of splits?

## Additional Information
Implementation is well done in [obsidian.md](https://obsidian.md/features#_)  https://help.obsidian.md/Panes/Pane+layout 
The picture taken is from my own files and may be a bit extreme, two independent panes would be great already

Maybe their github provides some insight on how to do this: [obsidian github](https://github.com/obsidianmd)

**Comment by nathanlesage** [comment]
Already on my radar, but this won't come in 2.0, since it's already extremely full with an insane amount of features. But some time afterwards, it'll come!

**Comment by dybjto** [comment]
Fair enough!

**Comment by apple-ouyang** [comment]
Hope the  split screen can be available soon!

**Comment by micapam** [comment]
I am super keen for this. Do you have any notes on the approach you'd like to use, @nathanlesage? I could have a stab at the implementation...

**Comment by nathanlesage** [comment]
Everything is basically prepared now. I put the exporter refactor in between just because it annoyed me (see https://github.com/Zettlr/Zettlr/pull/3550), but the next two steps are (1) punned tabs and then (2) splits in the window!

But I appreciate if you'd like to help out! Especially if you use Windows and/or Linux, there are quite a few bugs open that are super hard for me to reproduce and fix because I'm 99% of my time on macOS, so feel free to have a look at those! Every PR is welcome :)

**Comment by micapam** [comment]
Sorry for my delay in response. Pinned tabs would be a great one to have! I am forever opening another tab over my main one and losing track of where I am - so that would also be very welcome! 

I'm on Mac too, sadly (or, happily, but sadly in this case).

**Comment by nathanlesage** [comment]
@micapam The Pinned-Tabs PR is now open: https://github.com/Zettlr/Zettlr/pull/3568

If you'd like to leave a review, feel free to! Just waiting for one or two reviews before merging, then the next step will be split windows.
