### ISSUE TITLE
Impossible to open a workspace that contains a  .tex file

### ISSUE THREAD

**Issue by monkey-sapphy** [Zettlr/Zettlr#2128]
Under Windows, when opening a workspace and the folder contains a file  with the   **.tex** extension, Zettlr reports an error and doesn't open the workspace, yet it reports the root directory has been loaded but the workspace doesn't appear in Zettlr.

![texError](https://user-images.githubusercontent.com/86493462/123472188-23d91600-d5f7-11eb-893e-fc090c2be48f.PNG)

**Comment by nathanlesage** [comment]
Does that still happen on the Zettlr 2.0 beta?

**Comment by monkey-sapphy** [comment]
Hello,
 
 
I’ve created a directory with a text file with extension .tex in it:     testtex.tex is in the directory (workspace) test.
In version 1.8.9  the file testtex.tex is detected as a directory when clicking on it but cannot be opened.
In version 2.0 the file is recognized as a text file and can be opened as such.
 
Please see the attachements as illustration.
 
Note that in version 2.0 with the same theme “Berlin” selected as in version 1.8.9,  the selected directory and file do not appear in green, they are greyed and it’s a pain from an ergonomical point of view. This appears clearly in the attachments. Is this a bug or is it compliant with the 2.0 specs ? 
 
 
Have a nice day.
 
Sapphy.

**Comment by nathanlesage** [comment]
Please feel free to open issues for design problems. And remember that GitHub does not support Email attachments, so your screenshots were not included by email.

Closing this as fixed in 2.0.
