### ISSUE TITLE
Automatic reload of modified files

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#213]
In my system, files are often modified by another tool (be it another device with sync or from another editor such as a spelling corrector). Each time, Zettlr asks me if I want to reload the file. I would like it to be done automatically without any interaction (which is what Ulysses is doing)

In fact, it can be argued that the current dialog can only lead to confusion and loss of data because the "don't reload the current modification" is actually saying "I don't know what are the data currently in the file and not yet displayed in Zettlr but I don't want to see it, I will modify the file which will put me in a virtual state with two conflicting versions of the same file and without any power on how this will be resolved. Does it means that I will loss those unknown data next time Zettlr saves, which is automatic?"

In fact, I can't find any good example where the external modifications should *not* be reloaded.

**Comment by nathanlesage** [comment]
Of course you're right. But I designed the dialog with the generic academic workflow in mind: You don't use external tools to modify your files, but only Zettlr, then sync it via any cloud, and when you open Zettlr prior to Nextcloud/Dropbox/GDrive syncing the file to the other computer, it would overwrite the new file with the old version.

But I can see your point and will implement a preferences setting to deactivate the dialog, something like: "Automatically load remote changes to the file"

**Comment by ploum** [comment]
Thanks for the clear answer :-)

**Comment by ploum** [comment]
Something to investigate later could be to be smarter about it and looks at the modification date. But that's something I could have a look myself. In fact, this issue might be simple enough for me to start contributing.

**Comment by nathanlesage** [comment]
tüdelü …

**Comment by RyanGreenup** [comment]
On Ubuntu 18.04 (well Mint) the `.deb` will watch for changes and works as expected but the `.AppImage` will not.

If anybody else has this issue bear in mind that it may relate to the `.AppImage` specifically.
