### ISSUE TITLE
Feature Request: Support Front Matter

### ISSUE THREAD

**Issue by flyisland** [Zettlr/Zettlr#214]
Markdown files could contain a YAML front matter block includes title, categories, and tags, etc. It'd be perfect zettlr could support these properties.

For example, showing the "title" in the front matter of a markdown file in the preview pane.

**Comment by asielen** [comment]
I second this. Could also contain things like created date, last updated etc.

**Comment by nathanlesage** [comment]
I just stumbled upon this issue, sorry for not answering earlier. What do you mean by "support these properties"? After all, they'll be recognized by pandoc and applied correctly, right …?

**Comment by flyisland** [comment]
@nathanlesage, for example, I have a markdown file with filename "innodb-diagrams.md", and the tilte property " InnoDB internals diagrams".  I hope that the name at the left pane of this file would be " InnoDB internals diagrams" too.

![image](https://user-images.githubusercontent.com/547085/62004899-d0859100-b15d-11e9-8487-18ac54eb2f74.png)

**Comment by nathanlesage** [comment]
Aaaaaaah, I see. Good point!

**Comment by flyisland** [comment]
and it'd better if zetllr could support the categories and tags too, like browsing or searching by  categories and/or tags

**Comment by nathanlesage** [comment]
Yeah, I'll see what I can do -- parsing the YAML header is not a problem at all, it would be more problematic to see how to integrate all of this! But in case I could do it gradually. Nevertheless, it'll require some refactoring again, so I can't promise when it'll come!

**Comment by nathanlesage** [comment]
And here we go!
