### ISSUE TITLE
[ENHANCEMENT] Apply AutoCorrect replacement only if there is an exact character match with the expression

### ISSUE THREAD

**Issue by raphraph** [Zettlr/Zettlr#2142]
## Description
When using AutoCorrect the expression is replaced as soon as you hit spacebar and that the last characters of the word you are typing correspond to one of the expressions in the list.

**The enhancement consists in replacing the expression only if there is an exact character match.** This is very useful in the case of using Zettlr for note taking and using abbreviations to write faster (especially for words that have a high frequency occurrence).

Imagine the following autocorrect expression in order to illustrate: "ecs" >> "écosystème"

If I type : "**ecs**" + spacebar, it is replaced by "**écosystème**" :+1:
If I type : "**secs**" (which is another non-abbreviated french word) + spacebar, it is replaced by "**sécosystème**" :-1: 

## Proposed Changes
This can either be the default behavior, or it can be a option that can be toggled on/off (maybe not useful for some languages ?).
I personally don't see the interest of not having an exact match but if someone has an answer I'm curious.

## Caveats
I don't see any but might be missing something.

## Additional Information
None, but I can provide more information if needed.

**Comment by nathanlesage** [comment]
Mh, if I don't overlook something here your proposal basically assumes we can cleanly separate by whitespaces, does it? I'm just asking because I'm worried what to break with regard to edge cases … :D

**Comment by raphraph** [comment]
Yes I suppose checking up to the latest whitespace would work. It's what I had in mind.

**Comment by nathanlesage** [comment]
That was the _problem_ that I saw with your suggestion, since a lot of the autocorrect values are also expected to be transformed if they are _not_ preceeded by whitespace.

`3m2 --> 3m²` is just one of the examples. So checking for whitespace is not a solution.

**Comment by raphraph** [comment]
Ah ok sorry for my misunderstanding.

I just found an "ugly" workaround : if in the autocorrect table I put a white space both in front of the expression to be replaced and in front of the replacing expression, then the autocorrect occurs only if the expression looks like an "exact match".

But it is important to also put a white space in front of the replacing expression otherwise you "loose" a white space...

Maybe this workaround is actually sufficient if it is documented clearly as a "tip" or something :)
You tell me if you see any caveat in doing this.

**Comment by nathanlesage** [comment]
Yeah, I think this workaround is sufficient because of the whitespace issues I mentioned. Also, one could try to find unique replacements rather than trying to make AutoCorrect more smart. In the end, a smart autocorrect is what makes Word so horrible to work with since it's never clear what it tries to replace :D 

So I'm going to close this issue for now. If you feel the need to further discuss this issue and potential workarounds, feel free to do so on Reddit or the Forum. If the crowd comes up with a cool idea, we can certainly talk about implementing that one – if that's even necessary! :)
