### ISSUE TITLE
[Bug] floating text on footnotes not working after link

### ISSUE THREAD

**Issue by ddrm86** [Zettlr/Zettlr#2143]
### Description

I am working on this text: https://pastebin.com/Bir0dkCt and for some reason, after the first link [[20210623135258]] (that is working fine, by the way) the next footnote is shown in a slightly different font and does not show the text:

![zettlr_bug](https://user-images.githubusercontent.com/15799167/123926868-9a299f80-d98c-11eb-9418-23ef3d9a7be2.PNG)

If I remove the link (by removing the brackets, for instance) the problem goes away. Changing the position of the footnote after the link does not solve the issue.

```
General Information
Zettlr Version: 1.8.9

System: win32 10.0.19041 (architecture: x64)

Build Dependencies
This build was compiled using

Node.js v14.16.0
Electron v12.0.6
Chrome v89.0.4389.128
v8 engine v8.9.255.25-electron.0
Zlib v1.2.11
OpenSSL v1.1.1
Current System Load
CPU Load: 0.52 %
Resident Set Size: 145.58 MB
C++ memory for JS Objects: 46.03 MB
Heap: 31.95 from 39.3 MB (Limit: 4194.05 MB)
Renderer flags
C:\Users\Administrador\AppData\Local\Programs\Zettlr\Zettlr.exe
--type=renderer
--field-trial-handle=1552,3072574299708026126,5652253489425755828,131072
--enable-features=WebComponentsV0Enabled
--disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess
--lang=es
--app-user-model-id=electron.app.Zettlr
--app-path=C:\Users\Administrador\AppData\Local\Programs\Zettlr\resources\app.asar
--no-sandbox
--no-zygote
--device-scale-factor=1
--num-raster-threads=4
--enable-main-frame-before-activation
--renderer-client-id=4
--no-v8-untrusted-code-mitigations
--mojo-platform-channel-handle=2568
/prefetch:1
```

### Reproducing

Not sure, I guess just make a new document in Zettlr with this Markdown code https://pastebin.com/Bir0dkCt and maybe make the link or links work since it might be related.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by ddrm86** [comment]
After other tests, it looks like is alternating: the first reference to a footnote after the link does not work, then the second does work, then the third does, the fourth doesn't...

**Comment by nathanlesage** [comment]
That is most certainly odd. But I also noticed that sometimes note retrieval doesn't work and sometimes showing/editing the footnote references doesn't work as well. There's clearly something afoul here.

**Comment by waterfallpit** [comment]
Testing this in yesterday's develop version on Windows 10: If there's zero or one character between double bracket link and preceeding single bracket block (either link or reference), then the even references after the double bracket work, but the odd ones don't. If there are two or more charcter in between, then it's vice versa.

Samples:
```
ab [link][[test4.md]] ef [^2] [^3] [^4] [^5]

[^1]: ref. 1
[^2]: ref. 2
[^3]: ref. 3
[^4]: ref. 4
[^5]: ref. 5
```

```
ab [link]cd[[test4.md]] ef [^2] [^3] [^4] [^5]

[^1]: ref. 1
[^2]: ref. 2
[^3]: ref. 3
[^4]: ref. 4
[^5]: ref. 5
```

**Comment by nathanlesage** [comment]
So, I've found an underlying cause for this. We're basically making use of the underlying GFM-mode to detect links. But that mode doesn't allow multiple links following each other. So you can improve this behaviour by typing _anything_ in between the references. Then it will work.

I'm not sure how to really fix this issue cleanly. We could basically take over the functionality from the gfm-mode but then we could also just write our completely own Markdown mode which I wanted to prevent. Mh...

**Comment by nathanlesage** [comment]
Closing as wontfix for now, as soon as we switch to CM6 and the problem persists, we can have a look again.
