### ISSUE TITLE
A JavaScript Error... makes it impossible to use zettlr

### ISSUE THREAD

**Issue by myn-user** [Zettlr/Zettlr#215]
Hi,

I installed Zettlr on a new PC with Windows 10 64-Bit.

After choosing a directory Zettlr becomes "blank" and I got the message:

![Message](https://user-images.githubusercontent.com/48586796/58483456-a2390480-8160-11e9-94b1-bf629831d79c.png)

It is impossible (for me) to "stop" this message.

I de-installed Zettlr and installed it again, but the message is still there.

What can I do?

**Comment by nathanlesage** [comment]
This looks incredibly related to the fsevents issue that a lot of Electron apps are currently experiencing. Nobody really knows what is happening, but some mishap in the fsevents watching algorithm keeps crashing apps throughout the board ...

Here are the related issues:

- https://github.com/Zettlr/Zettlr/issues/186
- https://github.com/fsevents/fsevents/issues/273
