### ISSUE TITLE
[DEVELOP] Enable overwriting of `userData` path

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#2151]
Following up on @waterfallpit, it's a good idea to somehow enable users to set the whole configuration directory to another one using a command-line flag.

This would kill two birds with one stone:

1. We can safely detach a production configuration with all of its data from testing the GUI
2. We can finally solve the (quiet, but still existing) demands for a portable app.

Should be fairly simple to implement; requires basically a new line of code in `main.ts` as well as some changes to the `test-gui`-script.

If anyone has a few free minutes, feel free to already do a PR. All the code's literally there and simply requires copy, pasting, and adapting. (+ a look into the electron docs how to change the `userData`-path globally)

**Comment by waterfallpit** [comment]
@nathanlesage I implemented this via --config-dir (to keep --config switch available). So far only (and minor) issue is that `Dictionaries` dir is created in the default location. Relevant reported issue: https://github.com/electron/electron/issues/26039
I'll make a PR later this weekend. I'd like to test it some more.

**Comment by nathanlesage** [comment]
@waterfallpit Thanks for taking a look! So I think we can definitely keep waiting until the corresponding fix is in an Electron release.

But generally, I'd say we can actually remove the `--config`-switch perspectively and replace it with `--data-dir` (or something similar) since it basically supersedes the `--config`-switch. I can take care of moving the code for the `test-gui`-command to use that new CLI switch, because I don't see much use in keeping the additional switch (which introduces considerable boilerplate anyways).

**Comment by nathanlesage** [comment]
Sometimes it helps to scroll through old issues: This has already been implemented.
