### ISSUE TITLE
[Bug] 2.0 dark mode broken on Linux

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2157]
### Description

@nathanlesage [commented](https://github.com/Zettlr/Zettlr/issues/1690#issuecomment-855398025):

> the biggest thing that's currently stopping me from starting the public beta is that I still have no one who has had a **thorough** look at the Linux appearance of the app

## Dark mode

Dark mode causes many elements to be either aesthetically broken and/or unreadable. A workaround is to use light mode. This only works for people who tolerate light mode.

### Using the search or staring at the sun? :sunglasses: 

![image](https://user-images.githubusercontent.com/1702193/124467587-5376e380-dd98-11eb-983d-fcf76ab1c4d2.png)

### Search results not readable (until onmouseover)

![image](https://user-images.githubusercontent.com/1702193/124467993-ddbf4780-dd98-11eb-8f33-ea2b2a08101d.png)

### Some minor things like dates in note overview

I'm not sure if I should mention minor things like this.

![image](https://user-images.githubusercontent.com/1702193/124468061-f16aae00-dd98-11eb-9db2-1087091b572b.png)

### About screen

Both tabs and contents are hard to read.

![image](https://user-images.githubusercontent.com/1702193/124468290-3858a380-dd99-11eb-9959-0663e90c64da.png)

### Preferences

Similar

![image](https://user-images.githubusercontent.com/1702193/124469571-d13bee80-dd9a-11eb-9e44-1b589505de17.png)

---

> I want at least one person confirming that the app looks decent so far and we can give it to users.
  
I would recommend fixing major discrepancies in theme before beta version.
  
### Other minor issues

- Scrollbars are white on dark theme 
- Search dialog doesn't disappear when pressing ESC or Crtl+Shift+F
- Not sure if already planned or not: From a usability point of view, the simplest user experience would be to use the existing elements as much as possible. It would be helpful if the search results would appear in the existing file list (center column in the screenshot below) similar to 1.x, not in a new and slightly different dialog where you can't filter your search results.

![image](https://user-images.githubusercontent.com/1702193/124469224-5f63a500-dd9a-11eb-8eb0-51a352b9fa5a.png)

### Reproducing

Install nightly over an existing batch of notes and play around.

### Zettlr Version

Nightly

### Specify version

1.8.9-nightly-20210703

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.1 AKA Ubuntu 20.04

**Comment by nathanlesage** [comment]
I _think_ I captured all of these after a comment on the development feedback since I figured I forgot to tell the Linux styles to also adopt the background colour in night mode. But I might have overlooked something. Please wait for the next nightly on Friday. If that still features this bug, give me a quick shoutout. If it's gone then, feel free to close this issue!

**Comment by nathanlesage** [comment]
Closing as fixed; if not please comment on the development feedback thread (pinned to the top)
