### ISSUE TITLE
[Feature Request] Provide a Flatpak

### ISSUE THREAD

**Issue by ChristopherBurg** [Zettlr/Zettlr#216]
Debian and Red Hat packages don't play well on Linux distributions with immutable root file systems such as Fedora Silverblue and EndlessOS. Moreover, those packages won't install on distros that utilize a different package manager, such as Solus. 

Providing a Flatpak of Zettlr would allow users of such systems to install and use it.

**Comment by nathanlesage** [comment]
Hey, thanks for the recommendation. I'm getting a lot of requests of providing binaries for other operating systems lately, but I'm extremely limited resource-wise, so I can't support more than what electron-builder supports right out of the box (I'm currently considering trying to build pacman and freebsd builds, but only if that works out flawlessly).

If you would like to contribute flatpack builds in a way that [this guy here currently provides Arch Linux builds](https://aur.archlinux.org/packages/zettlr-bin/), I'll gladly link to the option on the [Download page](https://www.zettlr.com/download)!

And if the building of flatpacks works stable in a macOS environment, you can contribute the algorithm for building it to the repo and then I could "officially" support it by running the script alongside the main `make.sh`.

Also, please keep watching this issue: https://github.com/electron-userland/electron-builder/issues/512

If it gets resolved, let me know, maybe we can make this work with electron-builder, then.

**Comment by HannanAkbar** [comment]
Have you tried [electron-forge](https://github.com/electron-userland/electron-forge)? It's built on top of existing Electron build tools and can be used to build [flatpak](https://www.electronforge.io/config/makers/flatpak) while the native support is on the way.

**Comment by nathanlesage** [comment]
Thanks for the notice! Due to some other refactoring, I can't currently switch the builder, as everything's set up with `electron-build`. Nevertheless, feel free to do a PR that doesn't break build support for darwin, win32, deb and rpm while adding the flatpack option!
