### ISSUE TITLE
Support web clipper functionality

### ISSUE THREAD

**Issue by avarakin** [Zettlr/Zettlr#217]
It would be nice to support web clipper functionality, where the text and images can be cut and paste from web pages

**Comment by nathanlesage** [comment]
?! It's already implemented, if I understand you correctly?

**Comment by StoltHD** [comment]
A web clipper offer more than just copy paste, it will also keep the format (mostly) on the web page, and it shuldt also provide a reference link to the webpage where the page/section/paragraph was clipped from...

It should also offer a page dump (Print screen)  of the complete page, not only the part inn view (look at Firefox' "Take a Sceenshot" as an example...

Joplin, Zotero, "Bib it Now" are some Open Source examples of software that have a web clipper add-on for browsers...
Other software with web clippers: Onenote, Evernote, TagSpaces

**Comment by nathanlesage** [comment]
Ah. Now I see what you mean. But I don't think this is part of the functionality Zettlr should offer, as there's no use in saving all of that information. If you want to copy some website content while retain formatting, a standard copy&paste operation will do the job.

**Comment by StoltHD** [comment]
In a research environment, it is actually really important to have all the
information...
All Researchers use citation or store articles and thing they find with
their Research, so yeh, it is kind of important if you want Zettlr to be a
tool for academics and researchers... Copy paste will never give you the
information and formatting needed...
... but, at the same time, we can use Zotero and citeproc, so thats an
alternative :-) only thing with that is that you need your Research
material in one software and your notes and writing in another...

Great software by the way, just found it and still testing, but with a
couple of additional features I can really see it been used in genealogy
research and historian research...

Wish for support for Markvis or 3d.js so that I could write both
hierarchies and timelines, both showing with the possibility to show
paragraphs, notes and notebooks and projects as "nodes" with relations...

Jaran


tor. 13. jun. 2019 kl. 14:56 skrev Hendrik Erz <notifications@github.com>:

**Comment by nathanlesage** [comment]
> ... but, at the same time, we can use Zotero and citeproc, so thats an
alternative

This is exactly the point for why Zettlr integrates with Zotero so well and Zettlr won't support web clipping the way you propose. Zettlr solves the problem of writing effectively. But collecting your research results and other information must be done by another program.

**Comment by StoltHD** [comment]
I didn't propose anything regarding the web clipper, I just added
information... nothing more...

I see other functions much more important than a web clipper... i.e.
possibilities to use timelines and hierarchies to make visuals of the
research/writing... i.e. showing the linked between documents/notes/parts
of notes as nodes in a diagram... murmaid do not have that many
possibilities, and do not have timelines at all...

Thanks for answering...

Looking forward to next release, bet you have something more great up the
sleeves... :-)

tor. 13. jun. 2019 kl. 16:55 skrev Hendrik Erz <notifications@github.com>:

**Comment by graphixillusion** [comment]
Guys i'm trying the copy and paste from a web page but it doesn't keep the formatting, it justs copy and paste text. I've tried with the same selection with typora and it works good. I need some special config to make it works in here too?

**Comment by nathanlesage** [comment]
Do you use the 1.6? If you copy text from a webpage, Zettlr should from now on do a decent job at parsing the HTML to valid Markdown, as we've included the Joplin-parser!

**Comment by graphixillusion** [comment]
@nathanlesage yep i'm using the last version.

**Comment by nathanlesage** [comment]
This is what I get when I copy the README text from this repository and paste it onto the app:

![image](https://user-images.githubusercontent.com/17251683/76142394-91ada700-606d-11ea-9f12-537455722a58.png)

**Comment by graphixillusion** [comment]
@nathanlesage 
doesn't work like this on my system. what could be possible wrong?

**Comment by nathanlesage** [comment]
I have absolutely no idea, because this is some behaviour that should definitely not be platform-dependant o_O I did notice slight differences with the way Chrome and Firefox copy text to the clipboard.

Nevertheless, copying some text from a website and pasting them with Ctrl+V should do the job, at least on Chrome and Firefox. Didn't test any other browsers right now.

**Comment by graphixillusion** [comment]
In this scenario, the two funny things are:
1. I used Chrome too, even in Private browsing mode
2. The copy and paste on the same systems with typora works good.
I've just tried the operation with Firefox, here's the result:
```
With Zettlr, writing professional texts is easy and motivating: Whether you are a college student, a researcher, a journalist, or an author — Zettlr has the right tools for you. Watch the video or continue reading to see what they are!

Visit the Website.
Features

    Available in over a dozen languages
    Tight and ever-growing integration with your favourite reference manager (Zotero, JabRef)
    Cite with Zettlr using citeproc and your existing literature database
    Four themes and dark mode support
    File-agnostic writing: Enjoy full control over your own files
    Keep all your notes and texts in one place — searchable and accessible
    Code highlighting for many languages
    Simple and beautiful exports with Pandoc, LaTeX, and Textbundle
    Support for state of the art knowledge management techniques (Zettelkasten)
    A revolutionary search algorithm with integrated heatmap

… and the best is: Zettlr is Open Source (FOSS)!
```

**Comment by nathanlesage** [comment]
The paste looks exactly like the plain text from firefox — so I'm wondering why Turndown hasn't translated the HTML 🧐 Could it be access rights to the clipboard …?

**Comment by graphixillusion** [comment]
Yep, Firefox copy and paste is a little bit different from Chrome. If it could help, i'm running Windows 10 1909.

**Comment by nathanlesage** [comment]
Mhhh … I'll have to have a look at this at work. It's still only Windows 7, but maybe some errors appear, or so!

**Comment by IpeTek** [comment]
Hi, And thanks for the software that got me hooked - its omitted features notwithstanding! Maybe worth an issue of its own, but my two cents for the proposed functionalities that in my eyes would make Zettlr even better for writing effectively: timelines, hierarchies and the one I personally would benefit the most of, links/tags visualizer/navigator. If this was already implementable with markvis would be some really good news. And take Zettlr a bit closer to expensive proprietary software like e.g. Atlas.ti. 

 i.e. possibilities to use timelines and hierarchies to make visuals of the research/writing... i.e. showing the linked between documents/notes/parts of notes as nodes in a diagram... murmaid do not have that many possibilities, and do not have timelines at all... 
> 
> ... but, at the same time, we can use Zotero and citeproc, so thats an alternative This is exactly the point for why Zettlr integrates with Zotero so well and Zettlr won't support web clipping the way you propose. Zettlr solves the problem of writing effectively. But collecting your research results and other information must be done by another program.
