### ISSUE TITLE
[Bug] Dark mode on Win10:  Settings window white on white

### ISSUE THREAD

**Issue by georgd** [Zettlr/Zettlr#2174]
### Description

After installing the latest nightly, the settings window is presumably white on white.

![image](https://user-images.githubusercontent.com/214002/124821732-5b3cb080-df6f-11eb-9458-ac5e0b502e6f.png)

### Reproducing

I’m not sure about my settings in 1.8.9. It surely was set to dark mode but I don’t know if anything else plays a role there (I think, I also chose one of the colour themes). My system is in dark mode as well.

Anyways, I assume to reproduce on needs to set system and Zettlr 1.8.9 to dark mode. Then, install the nightly and open the settings.

### Zettlr Version

Nightly

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Just double-checked – should work beginning with tomorrow's nightly. If not, please feel free to comment that over on our dev-issues thread (pinned to the repo)!

**Comment by georgd** [comment]
> Just double-checked – should work beginning with tomorrow's nightly. If not, please feel free to comment that over on our dev-issues thread (pinned to the repo)!

Will do. Sorry for not having done that in the first place.
