### ISSUE TITLE
[Bug] [DEVELOP] File saving when closing the file

### ISSUE THREAD

**Issue by waterfallpit** [Zettlr/Zettlr#2178]
### Description

1. File content is not saved when clicking `Save` in dialog box upon closing file.
2. Filename has asterix next to it even though it is not modified.
3. In some cases, a dialog box for modified file is not displayed.

### Reproducing

1.
Create new file in the file manager.
Put in some content. I used the following text:
```
# test 3
file saving: 1
```
Save content (`ctrl/cmd + s`)
Insert some characters.
Press `ctrl/cmd + w`, a dialog box appears.
Choose `Save`.
File content is not saved and the file is not closed.

2. (continue from 1)
Press `ctrl + w` (`cmd + w`), a dialog box appears.
Choose `Proceed without saving`.
The file is closed.
Open the same file from the file manager.
Filename has asterix next to it, even though its content is the same as on the drive.

3. (continue from 2 with the same file still open)
Insert some characters.
Press `ctrl + w` (`cmd + w`).
Dialog box doesn't appear at all.

Closing the file via keyboard shortcut or by clicking the `X` produces the same effect.

edit:
Log after pressing `ctrl/cmd + s`:
```
[12:52:46] Saving file test3.md...
[12:52:46] [WATCHDOG] Emitting event: change:/home/waterfallpit/testing/notes/Zettlr/test3.md
[12:52:46] Updated modtime for fileDescriptor test3.md to 1625914366739
[12:52:46] File test3.md saved.
[12:52:46] Updated modtime for fileDescriptor test3.md to 1625914366739
```

Log after closing the file and selecting `Save` in the dialog box:
```
[12:53:04] [Command] Not closing file, as the user did not want that.
```

### Zettlr Version

Right off the develop branch

### Specify version

lastest commit (08bcf1c)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Xubuntu 20.04

**Comment by waterfallpit** [comment]
Problem identified:
`await this._app.askSaveChanges()` in `file-close.ts` doesn't return expected values.

**Comment by sds100** [comment]
yeah! I just noticed this as well. 2 more bugs...
- [ ] saving by pressing Ctrl+S or pressing the menu button doesn't save the file. It shows a file picker. Here is the log
```
[13:16:38] Saving file 20210710131628.md...
[13:16:39] [App] No path for the file to save provided. Aborting save.
[13:16:39] [R] [Main Window] Retrieved a falsy result from main, indicating an error with saving the file. (index.js:185414)
```
- [ ] When you press the close button on the dialog that tells you where whether to proceed without saving or save deletes the file. I'm not sure if this is an issue or not.

https://user-images.githubusercontent.com/16245954/125162836-fdcc7d80-e181-11eb-8704-eda3e8556290.mp4

**Comment by sds100** [comment]
The pre-2.0 version automatically saved notes and when you created a new note it created the file on disk straight away instead of waiting for it to be saved by the user.

**Comment by nathanlesage** [comment]
Yes, I know this and I know I have to fix it before going Beta. Basically, it's super hard to auto-save everything, and it requires quite some code changes. But I have that on my radar. Right now, clicking "Save" will just abort quitting the app and allow you to manually save the files. But yes, it should be able to do that automatically.

**Comment by sds100** [comment]
Cool. I was going to try working on this as well. Since it seems like a complicated change I'll let you do it 😀

**Comment by nathanlesage** [comment]
P.S.: This is something that involves many moving parts, so please refrain from attempting this yourselves. I have to overwork the internal state management which is rather bodged right now. Doing this wrong could be … let's say detrimental 👀

**Comment by waterfallpit** [comment]
@nathanlesage Thanks for the clarification. And `await this._app.askSaveChanges()` returns as expected. Don't know why it didn't before.
