### ISSUE TITLE
Shortcut issue on Linux/German Keyboard Layout

### ISSUE THREAD

**Issue by thob** [Zettlr/Zettlr#218]
Zoomin doesn't work tried it w/ `ctrl+shift+=`, why can't we get `ctrl + +` . `ctrl + -`does work for zooming out.

**Comment by nathanlesage** [comment]
Yup, it's a known Electron issue, as discussed for years on their repository: https://github.com/electron/electron/issues/6731

I can't do much but keep `CmdOrCtrl+Plus` in the shortcut section and hope they'll fix it some day …
