### ISSUE TITLE
[Discussion] Ideas for Better Internal Links

### ISSUE THREAD

**Issue by ThaddaeusWiedemer** [Zettlr/Zettlr#2180]
I'd like to discuss possible improvements to the handling and rendering of internal links, especially when linking to files using an ID. As internal links are essential to Zettlr, especially to a Zettelkasten workflow, I feel like the community could benefit greatly from improvements here. I have some ideas but no definitive answers and am also aware that some things depend on different Markdown styles (which I'm not really well versed in), so please feel free to share opinions.

I've also tried to compile related enhancements and feature requests here. Many things have been proposed and discussed in the path, but I feel like many topics are linked (no pun intended) and we could benefit from having a clearer vision what Zettlr's workflow with internal links could look like.

## labeled links
Normal links can be annotated using `[label](link)`. Internal links don't support anything like that at the moment, which makes linking with IDs cumbersome. I'm not sure what could work well with other programs that use Markdown, but here are some ideas how this could be implemented:

- In Dendron, internal links can be labeled with `[[label|link]]` (see [Dendron wiki here](https://wiki.dendron.so/notes/3472226a-ff3c-432d-bf5d-10926f39f6c2.html)). This is convenient, but I suspect it might not work well with most Markdown styles. Also discussed in [this Reddit thread](https://www.reddit.com/r/Zettlr/comments/gpozku/why_doesnt_zettlr_support_linktext_format_for/)
- `[[link]](label)` or `(label)[[link]]` would be similar to the implementation in normal links and the extra `(label)` could easily be ignored by other Markdown styles that don't support this

## better link rendering
Especially when linking with IDs, links take a lot of space without providing useful information. Here are some related ideas, although most of these would probably not be necessary anymore if labeled links were a thing:

- ID links could be collapsed to some icon or symbol unless clicked/hovered, similar to what was shown in [this Reddit post](https://www.reddit.com/r/Zettlr/comments/ohhxv0/how_to_use_zettlr_as_a_zettelkasten/) using CSS
- more options to style internal links, including the brackets `[[ ]]` could be given to the user. Maybe this is already a thing, but I didn't find a way to e.g. render the brackets smaller using custom CSS
- when adding the filename to an ID link, it could be auto-formatted, e.g. bold or in italics, to make it stand out. This is basically a cheap workaround of labeled links

## linking to note sections
Currently, it is only possible to link to a note as a whole. Even when a second ID is used in a file, or the idea is placed in the middle of a file, we can basically only link to the head of the file. See also #1800 and [this Reddit thread](https://www.reddit.com/r/Zettlr/comments/fpbjnc/is_there_a_way_to_link_to_a_specific_header_in_a/)

- [Dendron](https://www.reddit.com/r/Zettlr/comments/ohhxv0/how_to_use_zettlr_as_a_zettelkasten/) allows linking to sections with the `[[link#header]]` syntax. As above, I think this might clash with many Markdown styles, but the behavior is amazing otherwise.
- a modification of that syntax could be `[[link]]#header` or `[[link]](#header)`
- instead of allowing linking only to headers, we could have a special tag, like `#anchor<number>` to allow linking to user-defined places in any note

## transclusion
When writing notes and linking other ideas, we often need to repeat some of the content from other notes. Rendering some part of the linked note as a preview, or even a specific section would eliminate the need to repeat oneself. See also #1162 and #354

- [This Reddit thread](https://www.reddit.com/r/Zettlr/comments/nc9sbk/call_for_ideas_zettlrs_project_feature/h4p42vx?utm_source=share&utm_medium=web2x&context=3) proposes rendering internal links using the `![[link]]` syntax similar to how normal links are forced to render in-place.
- if there was a way to link to note sections, as proposed above, rendering an internal link could just include that section from the linked note
- [Roam has implemented this](https://roamstack.com/kb/starter/6-block-references/), maybe this could be used as inspiration?

## related issues and discussions
- #2048 proposes how to deal with internal links to non-existent files. While Zettlr auto-creates files when linking by title, I don't see how this can work when linking by ID
- #1925 proposes support of relative internal links like `[[path/to/file]]`, which is also discussed in [this Reddit thread](https://www.reddit.com/r/Zettlr/comments/mkmld9/use_nested_link_instead_of_finding_the_file/)
- #1798 proposes automatically appending a backlink to linked notes
- #1283 proposes a keyboard shortcut to navigate through links

**Comment by nathanlesage** [comment]
Converting this to a discussion, since I just stumbled upon it and there are many good ideas in there worth discussing!
