### ISSUE TITLE
Navigate quickly between existing notes

### ISSUE THREAD

**Issue by Yaco** [Zettlr/Zettlr#2182]
Hi folks!
I can't find the way to navigate and view the notes quickly. I can open them one by one in different tabs and then cycle them, but this is not very comfortable if you have more than 5 notes. This is very necessary to review and seek for related notes in the zettelkasten.

According to the documentation there seems to be some "preview mode" with some associated shortcuts ([see here](https://docs.zettlr.com/en/reference/keyboard-shortcuts/#preview-related-shortcuts)) that would enable to "open next and previous files"... but cannot find a way to enable that mode and not reference to it in the documentation (only to the print/preview view, but seems that's a different functionality).

Any clue or idea if this is already possible or would require a new functionality? Thanks!

**Comment by nathanlesage** [comment]
Ah, "preview" should read "File list", that's on me. But in general, please do not open issues if you have a question. This issue tracker is for reporting bugs and asking for concrete, actionable enhancements and feature requests. Please ask on [Reddit](https://www.reddit.com/r/Zettlr) or on the [forum](https://forum.zettlr.com). Thanks!
