### ISSUE TITLE
create no-exist notes when clicking `[[links]]`

### ISSUE THREAD

**Issue by jackusay** [Zettlr/Zettlr#2188]
## Description
create no-exist notes when clicking `[[links]]` just like wiki

maybe auto delete no-exist notes when you don't want it anymore?

## Example Workflow
1. writing content > type [[whatever-no-exist-notes]] > ctrl + click this link > **auto** create whatever-no-exist-notes.md file and open it and focus this tab.

2. 
In step1., you find out that is a typo or you don't need this file(whatever-no-exist-notes.md) anymore > you close this tab > **auto** delete whatever-no-exist-notes.md if it have no content

## Caveats
NO?

**Comment by nathanlesage** [comment]
There is a setting in the Zettelkasten-preferences offering you exactly what you want.

**Comment by jackusay** [comment]
preferences > zettelkasten tab > check automatically create non-existing files when following internal links
