### ISSUE TITLE
[Bug] [Develop] ID not recognized in YAML Frontmatter

### ISSUE THREAD

**Issue by tokritikos** [Zettlr/Zettlr#2190]
### Description

Placing an ID in the YAML Frontmatter does not lead to it being recognized by Zettlr. The ID also does not appear in the file information (in the file tree), when "Show file information" is selected in Preferences. The ID is not recognized both in files already existing, and when creating new files.

When linking to a file with an ID in the YAML Frontmatter, Zettlr will use the filename in the double brackets (that is: [[]]).

The problem does not happen if the ID is outside of the YAML Frontmatter (e.g., after the first heading).

I used the exact same YAML Frontmatter that I was using in the stable 1.8.9, and in that version there was no problem (the ID was recognized in the file information, and linking used the ID).

### Reproducing

1. Open Zettlr.

2. Create new file.

3. Create YAML Frontmatter and specify an ID.

Example:

```
---
ID: 20210714232323
---

# Title 1
```

4. Save file.

5. Try to link to file in another file (or look at the file information).

6. The ID does not appear in the file information, nor it does appear when linking.

### Zettlr Version

Nightly

### Specify version

Zettlr-1.8.9-x64.exe - nightly - Mon Jul 12th, 2021 14:36:20

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

I apologize for any improper formatting.

**Comment by nathanlesage** [comment]
Ah, I've recently kicked out the YAML frontmatter from the text parser, no wonder! Thanks for noticing!
