### ISSUE TITLE
[Bug] Scrolling can cause involuntary zoom

### ISSUE THREAD

**Issue by marktermaat** [Zettlr/Zettlr#2192]
### Description

On a Mac, I often encounter an involuntary zooming in or out in Zettlr, caused by scrolling, letting to, and then pressing the Command button. This probably happens because scrolling and letting go has a continuation effect, the page will keep scrolling for a second, and when you press the cmd button in this period it will register this as zooming in or out.

### Reproducing

Get a Mac (I have no idea if this happens on Windows too), take a long Zettlr page, scroll down strongly, let go of the scroll button, and while the page is still scrolling (without any active input) press the Command button.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.4

**Comment by nathanlesage** [comment]
This bug fortunately has been resolved – in the upcoming 2.0 there is an option to prevent zooming with the mouse! You can also get the nightlies right now to benefit from that setting: nightly.zettlr.com!

**Comment by marktermaat** [comment]
That's awesome, great service ;) Thanks!
