### ISSUE TITLE
[Bug] Editing tables does not work properly

### ISSUE THREAD

**Issue by sewag5** [Zettlr/Zettlr#2193]
### Description

When editing tables, in almost all cases WYSIWYM does not work. When clicking into table, source code is displayed. After leaving table sourcecode, table is rendered again.

![image](https://user-images.githubusercontent.com/54976115/125763920-37a04e8f-a99c-40dd-90bb-e3bc29b5bd05.png)
![image](https://user-images.githubusercontent.com/54976115/125763988-02fc5514-be66-47fe-8414-c6779605e121.png)
![image](https://user-images.githubusercontent.com/54976115/125764038-9f506e12-a8e9-4b3d-8052-925e1c98a305.png)

### Reproducing

Klick into table cell.

### Zettlr Version

Nightly

### Specify version

1.8.9+nightly-20210712

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 21H1 Build 19043.1083

**Comment by nathanlesage** [comment]
I am very positive that this is related to another bug I fixed this morning. Please try the new nightly version which I will manually build tomorrow during the day, and if the bug is fixed in there, please close this issue. Otherwise please comment so that I can have a look.

**Comment by sewag5** [comment]
Thanks for fixing. Is working as expected.
