### ISSUE TITLE
Unable to link internal files

### ISSUE THREAD

**Issue by Nermeta** [Zettlr/Zettlr#2198]
Every time I link to another file within Zettlr it will give me the following error Could not open file. 
When looking in the developer tools it shows the following error 
[R] [Main Window] The current opened file was not found in the list of open files during sync! (index.js:593). 
All of the files are open in Zettlr and I can navigate and edit them. Reinstalling Zettlr has no effect nor does changing where it is installed.

**Comment by nathanlesage** [comment]
Please use the correct issue template in order to create a bug report. I need that information in order to be able to help you.
