### ISSUE TITLE
[Feature request] new files default to .txt

### ISSUE THREAD

**Issue by volt4ire** [Zettlr/Zettlr#221]
## Description
Zettlr currently creates files with a .md extension

## Expected behaviour
I would like a setting to change the extension for new files to .txt. Thanks!

## Platform
 - OS: Kubuntu
 - OS Version 19.04
 - Zettlr Version 1.2.3

**Comment by Monolecte** [comment]
Hell no! Zettlr is a **MarkDown** editor, so, it is working with **markdown** files!

**Comment by nathanlesage** [comment]
@Monolecte is right: It's a Markdown editor, so the default extension should be `.md`. Nevertheless: Zettlr also allows you to create the following other file types:

* `.markdown`
* `.txt`
* `.tex` (which additionally switch the syntax highlighting of the editor from Markdown to LaTeX)

Simply provide the respective extensions, Zettlr will accept them and create the correct files for you and not add a `.md`-extension.

**Comment by volt4ire** [comment]
@Monolecte I know! I keep all my notes formatted in Markdown format, but prefer to use a .txt extension with these markdown-formatted notes so that they can be synced with and read by other applications which only support files without .txt extension.
That's why I was hoping for a solution to automatically save new with .txt extensions, but it's good to know I can specify the extension type when creating a new note!

**Comment by nathanlesage** [comment]
Always glad to help, and I know that this feature is somewhat invisible, I need to make it more obvious to people ...

**Comment by andrewchenshx** [comment]
it would be great if Zettlr could recognize/treat files with custom file extensions as markdown file, for the sake of interoperability with other apps.
thanks
