### ISSUE TITLE
[Bug] Blurry rendering on Wayland with Fractional Scaling

### ISSUE THREAD

**Issue by curbia** [Zettlr/Zettlr#2215]
### Description

Running Zettlr on Wayland with fractional scaling enabled results in very blurry text. I assume this is because Zettlr is still running on Electron 11, and support for fractional scaling was added in Electron 12? Would love to know the approximate timeline for this to be fixed.

Attached screenshot compares sharp text (Firefox with Wayland support enabled,) on the left, to Zettlr on the right: https://imgur.com/a/CGdVlCy

Thanks for all your work on this wonderful app!

### Reproducing

Run Zettlr on a system with Wayland's fractional scaling applied.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubunto 20.04.02 LTS

**Comment by nathanlesage** [comment]
We're very close to the 2.0.0 beta. I can also recommend you get the current nightlies right now. For 2.0.0, the nightlies, which you can get at https://nightly.zettlr.com, are extremely stable, plus you'll get beta/new stable releases as well. The warning there is just because afterwards the nightlies might also include fairly unstable things, but everything available there before the launch of 2.0 is very stable.

If you still do not prefer to get nightlies, or betas, the ETA for 2.0 will be I guess sometime around September; I'm planning on a fairly long beta. But I cannot give you any specific ETA.

**Comment by Oakwas** [comment]
Using version 2.2.6 and facing the issue mention here.
![Blurry interface](https://user-images.githubusercontent.com/103877079/173342340-7e5fc57c-627f-4160-8f33-003a44c1570a.png)

In gnome software, it reports that the Zettlr uses a legacy windowing system. Maybe this might be causing the problem.
![Legacy windowing system](https://user-images.githubusercontent.com/103877079/173341171-07da9247-eae9-4122-a557-3c135f5c18e6.png)

**Comment by nathanlesage** [comment]
Do other Electron-based apps (Slack, Discord, VSCode) also exhibit this behavior? If not it may be something we can influence, otherwise it is best to direct this to the Electron repository.

**Comment by Oakwas** [comment]
Yes, seems to be an electron issue. I'm not familiar with electron, but they seem to be having support for Wayland.
https://github.com/electron/electron/pull/26022#issuecomment-793105706

**Comment by nathanlesage** [comment]
Then feel free to report this to them! I will update Electron for Zettlr in regular intervals, so that any bug fixes will make it into some version of Zettlr! :)

**Comment by curbia** [comment]
It's not an Electron issue — Zettlr needs to change its flags to enable the Wayland support. I have done this manually once in the past but it is not user-friendly for less advanced users.

https://wiki.archlinux.org/title/Wayland#Electron

**Comment by ksinica** [comment]
Just wanted to say, that running Zettlr (2.3.0) with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags fixes the blur issue on my Fedora 36 installation with fractional scaling enabled in Wayland.

Exactly the same issue is occurring for other Electron-based apps, for ex. `vscode`:
https://github.com/microsoft/vscode/issues/109176

**Comment by nathanlesage** [comment]
@curbia 

![image](https://user-images.githubusercontent.com/17251683/173776999-c33d05e6-f1e9-40f4-a902-dfee43c87c31.png)

According to this excerpt, it's the users' responsibility. I double checked the electron logs and there's no way of programmatically appending these flags for the renderer instances to pick them up effectively. If there is a way, please feel free to open a PR, I can't test on Linux.
