### ISSUE TITLE
[FEATURE] Support folding/collapsing of lists

### ISSUE THREAD

**Issue by koenlek** [Zettlr/Zettlr#2222]
## Description & Example Workflow

I use Zettlr for managing my day to day todos, which I structure in lists. I often use sublists to further break down details of todos, which is nice for that specific todo, but it can obscure the bigger picture structure of the todo list (sublist complexities and size can quickly get out of hand ;) ). Because of that, it would be nice if you can fold/collapse sublists. This way, I'd only unfold the sublists that I'm actively working on...

This feature would work exactly the same as current folding support for markdown headers. An edge case is when you search for text that's in a collapsed chunk. That can simply be solved by causing the list to unfold, just like how that is currently implemented for markdown headers. Just like heading collapse, this is just an editor state that doesn't need to be stored in the file itself.

The html `details` ([example](https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2)) approach could be an alternative solution, but the overhead of that is too big imho (adding the html is not lightweight enough for on the fly editing of todo lists that evolve in structure all the time) and it doesn't seem like Zettlr currently even supports rendering it.

## Caveats

None that I'm aware of

## Additional Information

I checked various other markdown editors and found this being supported in some of them. For example, Obsidian supports it (though for some reason you first need to enable it in Obsidia settings). See screenshot:

![image](https://user-images.githubusercontent.com/6514289/126908389-f67901ae-5393-40ac-8564-0edf3093c17e.png)

**Comment by nathanlesage** [comment]
In theory a very nice idea, in practice I'm still afraid of looking into foldcode helper code. But I'll keep it open for now.

**Comment by koenlek** [comment]
@nathanlesage, Thanks so much for implementing this!! Really looking forward to try it out in 2.1.2!!
