### ISSUE TITLE
[ENHANCEMENT]: dark mode tabs more readable

### ISSUE THREAD

**Issue by cedardocster** [Zettlr/Zettlr#2229]
## Description
file tabs in night mode / dark mode are hard to read

## Proposed Changes
either make the tab background darker, or the letters lighter for non-open tabs

## Caveats
... as long as day mode unaffected :)

## Additional Information
see attached for what I'm seeing
![zettlr4](https://user-images.githubusercontent.com/10538705/127037122-9590ac06-271d-4d09-8f59-c77b1c7e9bed.gif)

**Comment by nathanlesage** [comment]
Please remind me to add an issue template for enhancement requests as well 🙈 I do suspect correctly that you're using the nightly on Linux, right? I'll have a look =D
