### ISSUE TITLE
css in editing area

### ISSUE THREAD

**Issue by DoctorSubtilis** [Zettlr/Zettlr#223]
I find quite useless apply custom css to application interface, I 'd rather apply custom css to md file in editing area. What doesn't mean get a wysing editor. Thanks

**Comment by nathanlesage** [comment]
? So you mean to write CSS inside the editor itself in `<style>`-tags that is applied …? I don't quite see the sense of Zettlr applying this CSS itself, as it would be extremely tedious to implement with not-so-much of a benefit.

**Comment by DoctorSubtilis** [comment]
I think I didn't explain myself; I mean I would like to see for example the title h2 (##) with a gradient background, like this:  
    background: # B35A31 linear-gradient (to left, # B35A31 80%, # F4E492 105%); text-shadow: gray -1px -1px; border-radius: 8px; box-shadow: 5px 4px 4px gray;  
Thanks

**Comment by samarulmeu** [comment]
And why can't you do something like:
```
body .cm-header-2 {
   background: # B35A31 linear-gradient...
}
```
in Custom CSS?

**Comment by DoctorSubtilis** [comment]
Thank you: so **it works**, though not yet perfectly (because I get some "sausages", as in attached image)
![zettlt-still-imperfect](https://user-images.githubusercontent.com/20089138/58783098-61b60c80-85e0-11e9-959d-128a71b9fc04.png)

**Comment by nathanlesage** [comment]
Yep, it's because of different spans that are applied by CodeMirror (the formatting, the space, the actual heading and then apparently there are two spaces or so at the back). But it's good to hear that it works!
