### ISSUE TITLE
[ENHANCEMENT] Specific text color for markdown braces (custom identifiers)

### ISSUE THREAD

**Issue by daltroaugusto** [Zettlr/Zettlr#2233]
## Description
Well, I had such a kinda bad time trying to make internal links within the single document. For better picturing, i.e. I created a manual summary for a file (using markdown anchor links like `#this-heading`), but then I have this situation that I need some support for duplicated header names, e.g. two headers called "potato". I tried the common syntax that would be something like "1-potato", "2-potato" and unfortunately it didn't work. Then, I tried to use brace marks (`{custom-id}`) and those worked well. Howerver, I noticed that this marks aren't recognized as simple, pure identifier elements, and I think this prejudice readability. 

![image](https://user-images.githubusercontent.com/58415152/127104041-977ccad1-2234-49d0-b849-8dcdf5f68336.png)

## Proposed Changes
I think this {julho-2} identifier should be less opaque, in this case it'd be kinda gray, less visible than the actual text/header. I could change the color by myself if there was a specific element for the identifier, but that's not the case.

**Comment by nathanlesage** [comment]
Do I understand you correctly that all you're asking for is a different styling for those Pandoc identifiers in general?

**Comment by daltroaugusto** [comment]
> Do I understand you correctly that all you're asking for is a different styling for those Pandoc identifiers in general?

Ya. Sorry if it was a too small request, maybe I'm just being too picky. Actually I'm not even demanding it by now, as I decided to just separate the diary in a folder/files structure and internal links (seems a more decent way to do what I want).

So, if you want to close, or wait to see if someone else think this'd be useful.

**Comment by ThaddaeusWiedemer** [comment]
I also think this could be nice, Pandoc identifiers are also useful to remove the numbering for headings---would be nice if they didn't stand out as much.
