### ISSUE TITLE
[Feature] please add an issue template for enhancement requests

### ISSUE THREAD

**Issue by cedardocster** [Zettlr/Zettlr#2236]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

(this is your reminder to do this :)

### Example Workflow

...

### Caveats

...

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

...

**Comment by nathanlesage** [comment]
Alright, I'd say the issue template form works!

And you just used a feature request template to propose an enhancement 😝
