### ISSUE TITLE
[Enhancement] "End" key should travel to the end of the wrapped text

### ISSUE THREAD

**Issue by hmf** [Zettlr/Zettlr#2238]
### Description

When editing, I would like to go to the end of the line as I see it in the text editor. The editor wraps the text, so it is somewhat surprising that the cursor is placed at the end of the text line (next line break) when it shows up as several text lines in the editor. 

### Proposed Changes

I think it is more intuitive and is more in line with current convention for the "End" and "Home" keys to place the cursor at the end and start of the wrapped text  as is viewed by the user. 

### Caveats

I don't think most users will want to move to the new line position when they press "End", so it should not pose problems to current users.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 20.04

**Comment by nathanlesage** [comment]
Could it be that this issue is covered by this setting in the editor tab? Try turning it on or off to see if that solves the issue:

![image](https://user-images.githubusercontent.com/17251683/127335795-4a251805-52e9-4147-95dc-cfcd13a746a0.png)

**Comment by hmf** [comment]
You are correct. My apologies. By turning it off, I get the expected behavior.
