### ISSUE TITLE
[Enhancement] Add control to delay link content popup

### ISSUE THREAD

**Issue by cedardocster** [Zettlr/Zettlr#2239]
### Description

If you have a list of links all in a row or a column, sometimes the popup for the link content comes up too fast to obscure the links above it (see gif).  It would be nice to be able to delay that by 500 milliseconds (or whatever) so you can sweep the mouse across the list and then stop over the one you want to see.

### Proposed Changes

maybe under the display tab, under the maximum height of images you could have a numbers input box with the current default milliseconds popup time that you could type over, and a reset button back to default.

### Caveats

no caveats I can think of

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

ubuntu mate 20.04.2

### Additional Information

![zettlr5](https://user-images.githubusercontent.com/10538705/127358198-cf6900bb-da23-4999-a9e4-0c3c21a4de38.gif)

**Comment by nathanlesage** [comment]
Sounds like a good idea – I think I'll implement one general delay for any tooltips that may occur in the editor (the link tooltips, those things, etc.) because I think a small delay for all of these is certainly not a bad idea.
