### ISSUE TITLE
Can't open directory from Zettlr in ChromeOS

### ISSUE THREAD

**Issue by ztwhaley** [Zettlr/Zettlr#2240]
When attempting to open a new directory from Zettlr, it tries to open the file from the browser instead of the file directory system. This makes it impossible to open sub-directories of a workspace unless you create them from within Zettlr. 

![Screenshot 2021-07-28 5 42 56 PM](https://user-images.githubusercontent.com/32799575/127400401-0e4316ec-f975-4b1d-8597-eac94c90896b.png)

## Zettlr Version
Debian

## Specify version
1.8.9 july 28

## Your Platform
Linux on ChromeOS

## Architecture
Intel 64-bit

## Operating System Version
ChromeOS 91.0.4472.167

**Comment by nathanlesage** [comment]
I didn't even know Zettlr could run on ChromeOS. However, right off the top of my head, I have no idea how one might change that. If someone else has an idea, please step forward.

But as a note of caution: Because of many reasons, ChromeOS is not officially supported, so please do not be disappointed if we will be unable to fix this issue.

**Comment by ztwhaley** [comment]
ChromeOS now allows you to enable Linux in order to run Linux applications. So while running Zettlr I am technically doing so using an instance of Linux. One of the big advantages of Zettlr was that since it runs on Linux it is available to ChromeOS users. As such, Zetllr is a great solution for ChromeOS users who are interested in a robust notetaking app!

**Comment by ztwhaley** [comment]
Something that might be helpful: when adding a Workspace, Zettlr works as it should and goes to the Linux file manager to choose a folder. It is only when adding a new directory within the Workspace (a sub-directory) that the problem occurs.

**Comment by nathanlesage** [comment]
So what you're telling me is you're doing this:

1. Open some directory in Zettlr as a workspace
2. Work with Zettlr within that and everything is fine
3. Then you create some directory in the workspace, but not from within Zettlr but from the file manager
4. Zettlr doesn't read in this folder

Does this describe your situation?

**Comment by ztwhaley** [comment]
Hi, this describes the situation:
1. Open some directory in Zettlr as a workspace by clicking the Open Workspace icon
2. Opens file manager to select folder and everything is fine
3. Right click in the Workspace and select Open Directory
4. Does not open file manager, but redirects to another location.

I have provided a screenshare of the situation to show you. Note that I am working within Linux. Also note that if the Right Click --> Open Directory would trigger the file manager in the same way that Open Workspace does, the problem would be resolved.

https://user-images.githubusercontent.com/32799575/127485572-76580318-17ef-49ee-96f4-ed053601dc57.mp4

**Comment by nathanlesage** [comment]
Ah alright. Thanks for clarifying. We're using the built-in shell module to open the path, i.e. we make a call to `shell.showItemInFolder`. It can very well be that the specific way that ChromeOS requires this syscall is not implemented in Electron, so I'm afraid it might be an issue with Electron itself. Given that ChromeOS couldn't execute any application until recently it's very likely that Electron just hasn't adapted. That might be the case.

**Comment by ztwhaley** [comment]
So if I'm understanding correctly, when you select Open Workspace, you are using a different call than shell.showItemInFolder? Because the call for Open Workspace works fine.

**Comment by nathanlesage** [comment]
Yes. For reading in a directory we're literally querying the directory contents with `fs.readdir`.

**Comment by nathanlesage** [comment]
Perfect, that sounds good! Closing then!
