### ISSUE TITLE
[Bug] [2.0.0 beta] Recent documents not working anymore

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#2245]
### Description

When clicking on "File" -> "Recent documents", nothing is shown.

In 1.8.9 and older, any file that you opened either (I believe) through internal links, search results, or manually would show in the list.

Now, in the beta, it stays empty.

### Reproducing

1. Open a few files through, e.g., internal links
2. Open the "Recent documents" menu -> should show "Empty"

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

### Additional Information

Might be a bit unrelated to this issue, but still worth mentioning: in version 1.8.9, files you opened through clicking on their tab were not included (try by opening some tabs, then restarting Zettlr -> now when cycling through the tabs, the "Recent documents" menu will remain empty).

**Comment by nathanlesage** [comment]
What I changed in between is that now Zettlr completely relies upon the recent document management of the operating system, i.e. it remains empty if the operating system does not support recent documents.

I just saw that this API apparently is only implemented for macOS and Windows. I can see to re-adding this for Linux operating systems.

**Comment by nathanlesage** [comment]
Re-implemented the recent documents functionality. However, please make sure to test this since I introduced a few improvements in this regard and made it a little bit sleeker, but I cannot test it (since on macOS+Windows we're using the built-in OS support for recent documents and I don't have a Linux machine available).

**Comment by nathanlesage** [comment]
@sith-on-mars Btw when you click any of the files – is something showing up in the logs, like a potential error or so? Would you mind sharing those?

**Comment by sith-on-mars** [comment]
Of course not! Here you go:
```
[18:10:43]	[Application] Opening file [file path].md
[18:10:48]	[Config Provider] Writing configuration file to /home/mydesktop/.config/Zettlr/config.json...
[18:10:49]	[Application] Received a request to run command file-open, but it's not registered.
```

**Comment by nathanlesage** [comment]
> Received a request to run command file-open, but it's not registered.

Whoops. Wrong command name 🙈

**Comment by kyaso** [comment]
Somehow I completely forgot about this. I haven't used the recent documents feature in a long time, but when I tried it recently, clicking an item still doesn't do anything for me.

**Comment by kyaso** [comment]
Whenever I click an item, the following message shows up in the log:
```
Clicking menu item with ID undefined
```

I added a `console.log` below line 57 in the code snippet below:

https://github.com/Zettlr/Zettlr/blob/5b07aa206d2da802aadf087060ab311828daeb34/source/app/service-providers/assets/menu.win32.ts#L40-L63

But that message never appears in the logs when I click a recent document.

**Comment by nathanlesage** [comment]
> Whenever I click an item, the following message shows up in the log:

Whoops, there needs to be an ID, similar to how the spellchecking suggestions are dynamically generated
