### ISSUE TITLE
[Bug] [2.0.0 beta] Search results not highlighted

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#2247]
### Description

Search results of global search are not highlighted (neither in the file itself, nor their location in the scroll bar).

Local search only highlights one result at a time.

### Reproducing

1. Search globally for something
2. Click on a file in the search results -> the matching term(s) are not highlighted in the text, and also the location indicators in the scroll bar are missing.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
That functionality is a little bit wonky either way, and I found it hard to make it work consistently and logically. I cannot promise anything for 2.0, but see your point.

**Comment by noah-arroyo** [comment]
I'm experiencing this as well in 2.0.0-beta.3

I wonder if this bug is related to another I've found, in Quicklook function: https://github.com/Zettlr/Zettlr/issues/2366
