### ISSUE TITLE
[Enhancement] Increase contrast of filenames in file manager

### ISSUE THREAD

**Issue by vtcarlino** [Zettlr/Zettlr#2248]
### Description

The contrast of filenames isn't high enough when using the yellow system accent color

### Proposed Changes

Darken the color of selected filenames in the file manager

### Caveats

This should impact the global appearance of file browser

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

macOS Catalina 10.15.7

### Additional Information

![Capture d’écran 2021-07-30 à 13 50 36](https://user-images.githubusercontent.com/24810357/127649465-cefcdfb7-9e75-4628-a307-f27001d316b2.png)

**Comment by nathanlesage** [comment]
In today's beta, the contrast should be better! If not, please ping me again!

**Comment by nathanlesage** [comment]
In today's beta, the contrast should be better! If not, please ping me again!
