### ISSUE TITLE
Failed to export PDF in Chinese characters

### ISSUE THREAD

**Issue by LIFanAr** [Zettlr/Zettlr#225]
It is very good to type Chinese in Zettlr, but when the files are exported as PDF all Chinese characters will disappeared.

## Expected behaviour

Screenshots
1. typing in Zettlr window
<img width="576" alt="image" src="https://user-images.githubusercontent.com/44634495/58929479-c3fe4100-8789-11e9-8598-740e8a7541e7.png">
2. after exported as PDF
<img width="472" alt="image" src="https://user-images.githubusercontent.com/44634495/58929488-cd87a900-8789-11e9-8e2e-f6ac5def8cd2.png">

Platform
 - OS: macOS Mojave
 - OS Version 10.14.5
 - Zettlr Version 1.3.0-beta.2
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## I installed BasicTeX.pkg.

**Comment by LIFanAr** [comment]
I tried a full afternoon and found an accessible way to make it, not the best but good for use. Just change the main font setting from Times New Roman to Kai.

Finally, it can be exported PDF in Chinese. However, setting the main font as Songti is also impossible.

Hope the information will be useful for people who are stuck in the same problem as me.

; D

**Comment by LIFanAr** [comment]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/44634495/58941957-6a107200-87af-11e9-826e-b827c66e9e91.png">
Setting Font as STSong is also an ideal way to export PDF including Chinese.

**Comment by nathanlesage** [comment]
Yes, it's due to the default LaTeX fonts not including chinese (and for that matter: other languages such as Ethiopian as well) characters, therefore the font must be matched. A good resource on how to achieve typing, e.g., in Chinese, is this: https://de.overleaf.com/learn/latex/Chinese
