### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by matthijsbro** [Zettlr/Zettlr#2250]
### Description

When I search by tag it does not show the yaml title in the list with results, but the file name. 

### Reproducing

Name a file. 
Create a yaml title. 
Give a #tag
Search for the file by tag
See sidebar

### Zettlr Version

Beta (if applicable)

### Specify version

v2.0.0-beta

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.4

**Comment by nathanlesage** [comment]
I see what you mean. That's not a bug; rather it is a conscious design decision. Do you feel it comes off as unexpected?

**Comment by matthijsbro** [comment]
I do. My titles are my id, and not very human readable. Perhaps it's just
my workflow, because my files are hard to identify by file name this way.

But since I gave the file a title, I would like to see that title rather
consistently. Otherwise it seems to me that I see the same file coming by
under different names. Which confuses me.



Op zo 8 aug. 2021 21:27 schreef Hendrik Erz ***@***.***>:
