### ISSUE TITLE
[Feature] [2.0.0 beta] Custom TeX-templates within projects

### ISSUE THREAD

**Issue by Tettsch** [Zettlr/Zettlr#2253]
### Description

Hi,
in the stable version of Zettlr I use the custom TeX-template feature quite a lot with projects but this feature seems to be missing int the 2.0.0 beta of Zettlr and is also missing from the current Zettlr 2 documentation. Is there another way to add a template when I export a project? Or any chance that this feature comes back later on?

### Proposed Changes

Add add custom Tex-template selection to the project settings window

### Caveats

No caveats.

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Beta (if applicable)

### Your Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Coming, just like the custom CSL style option and the title. Since I didn't use the project feature that often in the past 6 months, it slipped my memory a little bit. I only began re-adding project functionality recently.

**Comment by pstadler1990** [comment]
It would also be great if the templates could be specified individually per file / workspace. Otherwise you'll always have to change the template first, when opening a different file.

**Comment by nathanlesage** [comment]
@pstadler1990 With regard to "per fil" I have to think about that. Was my first idea as well, but it turns out Pandoc doesn't allow this natively, and I'm very averse in just adding random YAML properties into the ecosystem without consulting with the other app developers first.

**Comment by pstadler1990** [comment]
Understandable. I have not digged into the file structure myself yet, but could it be possible to store such "per-file" attributes with the file / workspace itself? I get that this could turn into a larger break with existing workflows, but maybe it can be reused for other settings. My current Zettlr workflow requires different .tex templates for different documents (for instance one paper that requires a certain conference template, and another file that requires corporate templates). I imagine that there may be others with this requirement.

**Comment by nathanlesage** [comment]
As I said, it's a matter of ten lines of code for me to implement a custom YAML frontmatter property to deal with this situation, but as soon as this feature is implemented, people will begin to rely on it, and if the whole ecosystem then moves to a different frontmatter property, that will break workflows in the future :/

I think I have to double-check with the Pandoc team before I do something on my own here.
