### ISSUE TITLE
[Bug]  Beta 2.0 .deb Installation failed on Ubuntu 21.04 

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#2254]
### Description

I try to install deb beta on Ubuntu. What I get 
```
The following packages have unmet dependencies:
  zettlr: Depends: libgtk-3-0 but it is not installable
          Depends: libnotify4 but it is not installable
          Depends: libnss3 but it is not installable
          Depends: libxss1 but it is not installable
          Depends: libxtst6 but it is not installable
          Depends: libatspi2.0-0 but it is not installable
          Depends: libuuid1 but it is not installable
          Depends: libappindicator3-1 but it is not installable
          Depends: libsecret-1-0 but it is not installable
````

### Reproducing

Download and try to install deb file

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Pop 21.04

**Comment by danieltomasz** [comment]
Installed wrong architecture, sorry !

**Comment by alfa-th** [comment]
LMAO i installed using the wrong architecture package aswell!
![image](https://user-images.githubusercontent.com/35270908/153623703-ece4ae41-4ab4-4f78-84fc-1ad621a98dc6.png)
It's hard to tell if these are two distinct buttons or not

**Comment by nathanlesage** [comment]
@alfa-th Agreed, I can make the architectures more specific!
