### ISSUE TITLE
[Enhancement] Support attribute lists in fenced code block headers

### ISSUE THREAD

**Issue by vijoc** [Zettlr/Zettlr#2259]
### Description

Attribute lists in fenced code block headers are supported by [some markdown parsers](https://python-markdown.github.io/extensions/fenced_code_blocks/#attributes), and are required to use some features of e.g. pandoc [mermaid-filter](https://github.com/raghur/mermaid-filter#options). Currently, this does not appear to be supported in Zettlr, and using attributes or the curly brace syntax breaks syntax highlighting and mermaid rendering.

I'm happy to look into this in more detail and give a shot at implementing it if it's deemed useful.

### Proposed Changes

Enable syntax highlighting / mermaid rendering for code blocks where the mode is expressed in an attribute list. The attributes themselves can be ignored, but the language declaration should be supported with either the form ` ```{ #identifier .mermaid caption="Caption Text Here" }` or ` ```mermaid`. 

It would seem that there are at least two locations that would need to be updated: [the openRegex in `modes/multiplex.js`](https://github.com/Zettlr/Zettlr/blob/b74bcfd0c5287f2f00bc954a7448b4b20aca49a5/source/common/modules/markdown-editor/modes/multiplex.js#L391) and the [special case of mermaid rendering in `plugins/render-mermaid.js`](https://github.com/Zettlr/Zettlr/blob/24ea70311b92bbec6d5bb083862ad54e8093a403/source/common/modules/markdown-editor/plugins/render-mermaid.js#L50).

### Caveats

Parsing the language declaration from within the attribute list will complicate the parsing logic to some extent. 

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Beta (if applicable)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This has been partially required by the R highlighting already, and I have that on my radar! It requires a few changes in the multiplexer but that should do it.

**Comment by vijoc** [comment]
Glad to hear that this was on your radar already!

I imagine that in addition to the multiplexer the [Mermaid rendering plugin](https://github.com/Zettlr/Zettlr/blob/24ea70311b92bbec6d5bb083862ad54e8093a403/source/common/modules/markdown-editor/plugins/render-mermaid.js#L50) would also need to be updated, as in my understanding it currently only triggers on ` ```mermaid`.

Would a PR be welcome, or would you like to make the changes yourself?

**Comment by nathanlesage** [comment]
This works in the current nightly branch! We can improve the behavior if necessary, thanks to the better implementation in CodeMirror v6.
