### ISSUE TITLE
[2.0.0-Beta] "Duplicate File" does not work

### ISSUE THREAD

**Issue by quittenkaes** [Zettlr/Zettlr#2260]
Only in 2.0.0.-Beta.

Steps to reproduce:

- Right-click on a file in the sidebar
- Click "Duplicate File"

=> nothing happens

**Comment by nathanlesage** [comment]
Please use the provided bug template so I don't have to manually add/ask for all of this stuff.

1. Would you mind keeping the DevTools console open (Activate debug mode, then toggle developer tools in the develop menu, then switch to the tab console) and look for any errors when you attempt to duplicate?
2. Do the logs (also in develop menu -> open logs) say something after you attempted to duplicate a file?

**Comment by quittenkaes** [comment]
Sorry for the inconvenience, I didn't see the bug template!

I don't see any error in the DevTools console or the logs. But I found out that it only happens in file manager mode "combined". In "thin" and "expanded" it works fine.

**Comment by nathanlesage** [comment]
> I don't see any error in the DevTools console or the logs. But I found out that it only happens in file manager mode "combined". In "thin" and "expanded" it works fine.

Thanks, that already helps me find out where it's happening! I'll have a look!
