### ISSUE TITLE
[Enhancement] [2.0 Beta] Alternative treatment for opening or working with notes/tabs

### ISSUE THREAD

**Issue by jchalifour** [Zettlr/Zettlr#2261]
### Description

I've been working with the Zettlr 2.0 beta for a little while now and really appreciate it. One thing that I'm really struggling with though is the way it manages the open notes. 

My process...  
I have a file open and write something, then I save it. Then I click on another file and it opens in my exisiting note area (tab). That makes sense but then suppose I need to go back to the previous one to review something or add something. I have to find it again within my hierarchy or else search for it. Both those activities tend to make me sort of lose my flow. It's really difficult sometimes to remember where that one note was and find it again, especially if I have several tabs open (which I typically do), I forget what is where and don't realize which note I lost to the newly opened one. 

This becomes more difficult when looking at related notes, for example, in the sidebar. Where maybe I'm browsing things and don't necessarily want my current work to close. The file manager portion allows me to right click a file and open it in a new tab but the related notes don't have that option.

### Proposed Changes

I don't know that I have a great suggestion for resolving this but here are a few ideas for consideration. 

1) Being able to CTRL-click on a note to open it in a new tab would be helpful. I believe this action is common across web browsers and some other tools so the expectation here would be reasonable. It is quick, easy, and if it worked consistently in the file browser, search results, related files, etc. it would be helpful.

2) An option to go back to the previous file/tab? Some other similar tools to Zettlr provide back and forward arrows.

3) When a file is open it would be really helpful if it displayed the file manager hierarchy to highlight and show where that file existed within the hierarchy. Right now, it's true Zettlr highlights the file, which is open in the file manager but only if you happen to have the file manager already displaying that portion of the hierarchy. If you have multiple tabs open and have browsed different sections of the hierarchy, it doesn't show you where you are for a particular file open in a tab.

Or if not that, maybe there could be some action like what Zotero does where if you press the ALT button while hovering the mouse cursor over a note, it reveals where it is in the hierarchy and highlights that folder (but in Zettlr's case I guess it'd be for the file open in the tab).

### Caveats

I don't think this would impede anything else.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro, Gnome with latest updates

**Comment by nathanlesage** [comment]
> Being able to CTRL-click on a note to open it in a new tab would be helpful.

You can middle-click anything that would open a new note and it will open in a new tab regardless of your settings. In the file manager you can also in the context menu explicitly require to open a note in a new tab.

Imagine working with a browser (that's where I took a lot of the ideas from)

But yeah, the docs do not yet reflect that …

> An option to go back to the previous file/tab?

That's already requested in some issue here … but with tabs it's really difficult :D I will have to think of a way to basically record changes in time, but I do not have any clever idea right now, sorry!

> When a file is open it would be really helpful if it displayed the file manager hierarchy to highlight and show where that file existed within the hierarchy.

Mh, I can see the benefits of that. Maybe in a status bar …?

**Comment by jchalifour** [comment]
Thanks for considering. Yeah, that's true, a status bar path might help. Also, I hadn't realized the middle click option, that's good to know.

**Comment by nathanlesage** [comment]
Alright, I'll pin this issue and see when I get some time (or someone else, PRs welcome as always)

**Comment by jchalifour** [comment]
Another option that could help (not sure if this has been considered already) would be to permit users to easily pin the tab(s). It's common in web browsers and some other applications, to pin a frequently used tab so that it remains open in the top left of the tabbed windows. Then any new tabs open after it (on the right). If this were possible, then working with something in one tab would not risk being accidentally replaced/lost by clicking on another note because that other note would have to open in a new tab. 

I noticed there is an [older request (226)](https://github.com/Zettlr/Zettlr/issues/226) for pinning notes but it looks like that request is referring to more of a favourite/bookmarking type of feature so I don't think it's the same.

**Comment by nathanlesage** [comment]
> I noticed there is an older request (226) for pinning notes but it looks like that request is referring to more of a favourite/bookmarking type of feature so I don't think it's the same.

I always thought issue #226 was more or less about that. But yeah, another point to consider, yes.

**Comment by nathanlesage** [comment]
All of that coming in the next version
