### ISSUE TITLE
[Enhancement] Export internal links using note title

### ISSUE THREAD

**Issue by BabakFarshchian** [Zettlr/Zettlr#2267]
### Description

The handling of internal links when exporting in Preferences-->Export.

### Proposed Changes

I want to see the title of an external link when I export the note. Currently there are three options in Zettlr to handle internal links when exporting: 1) remove internal link completely, 2) unlink, 3) don't touch. None of these are useful when I use Zettlr-assigned IDs and link to these (e.g. [[20210802151842]]). It would be useful to have the human readable note title replace the ID (e.g. "Some title I gave to this note"). So a fourth option to 4) replace with YAML title, would be very welcome!

### Caveats

I cannot see any, except maybe that Zettlr has several ways of giving title, e.g. first heading, YAML title, title given automatically. Such an option might have to choose one of them? Not sure.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

### Additional Information

I am not a programmer. But I appreciate a lot the work you do!

**Comment by nathanlesage** [comment]
I'm not sure we can do that at all. We're using a custom Lua filter — and replacing an ID with an actual link requires (a) searching for that file (non-deterministic behaviour) (b) parsing the YAML frontmatter of that external file and (c) then creating said link. @tarleb any thoughts?

**Comment by BabakFarshchian** [comment]
Hm. Maybe it is enough to have only the note title (the string) without linking it to the actual note. Actually since this is about exporting (e.g. to PDF), it does not help me much to have a link to the note. But it is nice to have the title of the note that I link to in the PDF file, instead of the ID of the note. 

I see in the file list each note is presented with its title and ID, so I suppose it is possible to get hold of the title string belonging to a note ID by querying the array that creates the file list? Cheers.

**Comment by BabakFarshchian** [comment]
I noticed that a hack exists for doing this in Zettlr. It is documented under internal linking here: https://docs.zettlr.com/en/academic/zkn-method/#internal-linking. So someone has been thinking the idea before me:-) The hack solves the problem of readability of the text, but it is not optimal because it creates an invalid link in the exported document.

**Comment by nathanlesage** [comment]
> I see in the file list each note is presented with its title and ID, so I suppose it is possible to get hold of the title string belonging to a note ID by querying the array that creates the file list?

The thing is that the filelist is completely separate from the exporting process. For the exporter, it's much harder to get that list. We're using a Lua-filter for handling links, and for that filter it's extremely hard to find those. Lua is a pretty restricted language.

**Comment by BabakFarshchian** [comment]
I see. I wonder if this enhancement can reformulated so we are not fixed on the title of the note but on any user-given string. I see Obsidian has a vertical pipe function that allows one to have an alias string for an internal note. The format is:

> [[2021080211453|Here is the readable text]].

This gives you a clickable "Here is the readable text" in the editor, which could be unlinked/showed with a color during export.

The hack I linked to above really tries to do this, but in a way that is not very usable.

**Comment by tarleb** [comment]
The CommonMark parser used in pandoc should support this, but I believe pandoc doesn't expose this yet https://github.com/jgm/commonmark-hs/issues/69

**Comment by tarleb** [comment]
Commenting to keep the issue open. There's no recent progress, but it is still in my list.

**Comment by nathanlesage** [comment]
@tarleb Good that I saw your comment – pinned the issue!
