### ISSUE TITLE
[MINOR BUG] Search popup not disappearing

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#227]
It seems that if you press the search icon do/or not do a search and you press some other icon (TOC, rename, export...) the search popup does not disappear as it should and as the other popups do. 
I attached some screenshots and I mention that I noticed this behavior on the latest beta in an Ubuntu based Linux distribution. I don't remember this to happen in older versions, but I my might be wrong. 
![search1](https://user-images.githubusercontent.com/39216570/58948386-ada8b300-8792-11e9-9928-0225f3b5b327.png)
![search2](https://user-images.githubusercontent.com/39216570/58948396-b5685780-8792-11e9-9f1f-535c8cc944d4.png)

**Comment by nathanlesage** [comment]
Thanks for reporting, did it! :)
