### ISSUE TITLE
[Bug] RTL display does not work after application restarts

### ISSUE THREAD

**Issue by kavir1698** [Zettlr/Zettlr#2275]
### Description

I have a note in RTL mode. It works fine. I close the editor and open it again. The same note displays text from left to right. I go to editor settings. I see it is set to "Use right-to-left (RTL) writing direction". I set it to "Use left-to-right (LTR) writing direction" and click OK. The text does not change. I change the setting again back to RTL. This time the text is in the correct direction.

This is a procedure I have to do every time I reopen the Zettlr.

### Reproducing

Write a note. Set the editor to RTL mode. Restart the editor.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Would you mind trying this out with the 2.0 beta? If the bug occurs there as well I'll have a look!

**Comment by kavir1698** [comment]
I'll try it now.

**Comment by kavir1698** [comment]
Do I need to uninstall the previous version first?

**Comment by nathanlesage** [comment]
No it should just simply install the newer version on top of the older one!

**Comment by kavir1698** [comment]
As soon as I open version 2.0 beta, I received a window with this error: "Cannot read property 'parse' of undefined". Also, there is no save button in the settings windows. I change the setting and press X. The setting seems to be saved after I check again. With this version, RTL does not work at all.

**Comment by nathanlesage** [comment]
> With this version, RTL does not work at all.

Ouhh, that is not good o.O

I'll see to fixing this!

**Comment by nathanlesage** [comment]
Found the bug: I never set that property in the first place, apologies! Should work now.
