### ISSUE TITLE
[Bug] Files with identical names in different folders clash in link popup

### ISSUE THREAD

**Issue by Johennes** [Zettlr/Zettlr#2277]
### Description

When two files with the same name and distinct IDs are placed into different folders, only one of them will show up in the popup that opens after typing `[[`.

### Reproducing

Create the following files:

```
./folder1
  file1.md
./folder2
  file2.md
```

Give both files unique IDs. The files will show up when you type `[[`.

Now rename `file2.md` to `file1.md`. Type `[[` again and notice that only one of the files (in my case the second one) shows up.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSuse Tumbleweed

**Comment by nathanlesage** [comment]
Does this also happen on the current 2.0 beta?

**Comment by Johennes** [comment]
@nathanlesage yes, it does. I just tested 2.0.0 beta3 and the behavior seems identical to the latest stable version.

In the screenshot below you see how I was able to insert links to `file1` and `file2` but as soon as I rename `file2` (which is in the other folder) to `file1` only one of them shows up in the completion popup.

![Screenshot_20210822_195345](https://user-images.githubusercontent.com/1137962/130365103-476e0ae9-130b-45f4-9859-1ce78bdf9644.png)

Maybe the filename is used as a key somewhere so that when two files in two different folders have the same name, one of them overrides the other during completion?

**Comment by nathanlesage** [comment]
> Maybe the filename is used as a key somewhere so that when two files in two different folders have the same name, one of them overrides the other during completion?

Might well be; I haven't looked at that code in quite some time!

**Comment by Johennes** [comment]
I've only browsed the code online so far but I think this here might be the culprit:

https://github.com/Zettlr/Zettlr/blob/8b7e758dee3feeba7df8ccb84fb1a65f8145677c/source/win-main/Editor.vue#L293

The array of files is flattened into an object using only the filename as the key.

**Comment by Johennes** [comment]
Yupp, that seems to be it. When I change to e.g. `fileDatabase[file.dir + '/' + fname] = {` I'm getting both files in the completion popup.

![Screenshot_20210825_103931](https://user-images.githubusercontent.com/1137962/130758127-0c217e28-0e2e-48ae-8f8a-53d55b53c8ed.png)

This is already better but it still doesn't allow to differentiate the two files. It'd be nice if the path from the respective root folder would be visible in the popup but changing the `displayText` property would also change the text to be inserted. :thinking:

**Comment by nathanlesage** [comment]
Uh, thank you for looking for the culprit! Nice!

But yeah, there's certainly room for improvement; for example we might even want to enable searching for the full file path or smth … I have to have a look on it (or anyone else, if anyone wants to open a PR!)

**Comment by Johennes** [comment]
Maybe using `file.hash` as the key could be an acceptable intermediary fix. At least that way you get both files in the completion popup and depending on the ID you might even be able to tell them apart.
