### ISSUE TITLE
[Bug] [Develop] Zettlr icon not shown in menubar

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#2282]
### Description

I just realized that the application icon is not shown in the menubar although set. This affects Windows, and very very likely also Linux builds (without native appearance).

### Reproducing

Just run the current betas.

### Zettlr Version

Beta (if applicable)

### Specify version

beta.1

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Windows 10 + all Linux

### Additional Information

Webpack doesn't complain about the image, and the image is clearly there. However, once I adapt the path, it will complain that it doesn't find the file; so apparently the file is being found. I have no idea why it's not displayed.

If anyone has an idea, feel free to open a PR!

**Comment by c-4-m** [comment]
This does not seem to be an issue running PopOS 21.04 (Ubuntu-based) with beta 2.0.0 - see screenshot bottom left corner. Sorry if I misunderstood and you were referring to another version of the beta.

![zettlr_beta_icon](https://user-images.githubusercontent.com/68698176/128641524-0178df50-7f8c-4579-907d-d5344a7f4880.png)

**Comment by nathanlesage** [comment]
No I actually meant the menu bar itself, that is in front of the menu items; I feared that my description was not all too precise. Here's a screenshot:

![image](https://user-images.githubusercontent.com/17251683/128643434-5c97cd62-1bdc-4ca1-8df0-d074d1e02532.png)

I mean the icon that should appear left to "Datei" in the top-left corner (which is similar in other applications on Windows 10)

**Comment by c-4-m** [comment]
Ah, I see. Then I can confirm that this bug exists with the settings mentioned above. Sorry I couldn't be of more help.

**Comment by nathanlesage** [comment]
Update: Weirdly enough, *no* image referenced in the CSS is being fetched.

**Comment by nathanlesage** [comment]
Webpack is a cruel thing.
