### ISSUE TITLE
Homebrew not yet pointing to 1.3 stable?

### ISSUE THREAD

**Issue by filipgoc** [Zettlr/Zettlr#229]
## Description

I did not get v 1.3 with homebrew cask on MacOS High Sierra

## Reproducing

```
brew cask uninstall zettlr
brew tap caskroom/cask
brew cask install Zettlr

==> Satisfying dependencies
==> Downloading https://github.com/Zettlr/Zettlr/releases/download/v1.2.3/Zettlr-macos-x64-1.2.3.dmg
Already downloaded: /Users/filipgoc/Library/Caches/Homebrew/downloads/839ab6df5cd20ee6752865f0264a08a646fba6fb89106f92f909a8fe0b784d76--Zettlr-macos-x64-1.2.3.dmg
==> Verifying SHA-256 checksum for Cask 'zettlr'.
==> Installing Cask zettlr
==> Moving App 'Zettlr.app' to '/Applications/Zettlr.app'.
🍺  zettlr was successfully installed!
```
As you can see, the version is wrong, verified:

```
╭─  ~  
╰─ brew cask info zettlr
zettlr: 1.2.3
https://www.zettlr.com/
/usr/local/Caskroom/zettlr/1.2.3 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/zettlr.rb
==> Name
Zettlr
==> Artifacts
Zettlr.app (App)
```

## Expected behaviour

Get me the newest version

**Screenshots**

## Platform
 - OS: mac
 - OS Version high sierra
 - Zettlr Version ??

**Comment by nathanlesage** [comment]
Homebrew is out of our realm. The build script when I saw it the last time looked correct, but I may be wrong. Please get in toucch with Homebrew for these issues! Thank you! :)

**Comment by filipgoc** [comment]
( It seems it's been updated since, https://formulae.brew.sh/cask/zettlr shows 1.3)

**Comment by nathanlesage** [comment]
Maybe there's a cronjob running somewhere that queries the repositories from time to time, and which only runs every other day. Would explain the delay!
