### ISSUE TITLE
Images scales to window app full width

### ISSUE THREAD

**Issue by enteropositivo** [Zettlr/Zettlr#23]
First of all congrats for this awesome app!

I encountered a problem when previewing images because they get scalled to all window app full width.

This is a problem when makeing a document with small images.

Could you make that the images maintain their oriiginal height and width,   and don't resize them to a bigger size than original ?

Of course, images may be down resized  if they are bigger than the window width but please don't scale them to a bigger size.

**Comment by nathanlesage** [comment]
Got it, is on my bucket list! And thanks a lot!
