### ISSUE TITLE
Moving folder when I didn't ask for it

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#230]
The folder view is quite "buggy", with folders being sometimes "glued" to the mouse pointer without apparent reason and being moved without intention.

This was pure heisenbug until today! I found a way to reproduce the problem! Yeah!

So, on a folder:

1. Right click (ctrl-click on a mac) then choose "rename"
2. The rename popup appear
3. The folder is also "glued" to the pointer and will be moved.

**Comment by nathanlesage** [comment]
Ugh … somehow I'm getting the impression that either my local version of Zettlr wants to mock me and somehow denies me the luxury to actually reproduce issues, or your Zettlr version tries to annoy you big time by doing such nasty things :/ I'll keep my eyes open, the tree view & file list are the next ones on my list to get a refactoring, after I finalise the synchronous file operations! Maybe while doing this these bugs will solve themselves!

**Comment by ploum** [comment]
I could reproduce the same bug by right-click -> deleting folder. 

I think that all those "folders moving" bug can be summarised by "after some action, the folder is glued to the pointer just like an initiated drag".

**Comment by nathanlesage** [comment]
Precisely. I'll try increasing the sensitivity of the drag detection!

**Comment by nathanlesage** [comment]
Oh great, just saw [jQueryUI has deprecated the sensitivity functions](https://stackoverflow.com/questions/48235544/jquery-ui-replacement-for-distance-and-delay-options) because apparently they think to drag stuff around one should use handles 🤷‍♂️

**Comment by ploum** [comment]
not sure it will fix the issue as it looks that the drag is initiated by the action itself (renaming, deleting) and cannot be stopped (as you cannot release the mouse button). I may investigate what initiate the drag.

**Comment by ploum** [comment]
Ok, I can confirm that the bug is created by the context right click menu. If I disable this menu, the bug is clearly gone. But only right clicking on a folder initiate a drag.

**Comment by nathanlesage** [comment]
This sounds to me as if there's a bug in jQueryUI o_O

**Comment by nathanlesage** [comment]
Alright, as the new sidebar with native Drag&Drop is now initiated, the bug should be gone. If it persists, please comment so I can reopen the issue! :)
