### ISSUE TITLE
[Enhancement] [Beta 2.0]

### ISSUE THREAD

**Issue by pharaoh23** [Zettlr/Zettlr#2305]
### Description

I have been trying to use a bibtex file as citation file. But when I click in export and I want to select it, the it is not possible to select  a .bib file, but only a .json file. The issue as far as I know was going on in the nightly releases as well. 

I attach here a screenshot of what I see in my computer. 
![Screenshot 2021-08-12 at 06 42 39](https://user-images.githubusercontent.com/10102677/129117563-99a47366-0d9e-4d3f-9b66-04fc150af67d.png)

### Proposed Changes

Restore .bib selection

### Caveats

No caveats

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

Big Sur 11.5.1

**Comment by nathanlesage** [comment]
Totally my fault. I just looked it up and for "BibTex" I just allowed ".tex" files instead of ".bib" files 🙄

(Which wouldn't have worked because the citeproc provider expects a ".bib"-file …)

Apologies!

**Comment by pharaoh23** [comment]
Dear Hendrik,
I have now downloaded Version 2.0.0-beta.1 (2.0.0-beta.1), but bib files
remain not selectable.

Please check again on your side, and let me know about it.

Roberto

**Comment by nathanlesage** [comment]
Are you really sure? I just tried that with the beta.1 but I can select bib files just fine.

**Comment by pharaoh23** [comment]
I I tried with both computers, but I can only work with JSON, not Bib. The
bibtex files remain not selectable.

**Comment by nathanlesage** [comment]
Have you tried just selecting your bib-file *despite* it being grayed out? I have realized that sometimes the finder window that pops up is not the fastest in displaying which files you can and cannot select.

Plus, there are two "options" to selecting: The first one (default) is JSON, the second one (has to be selected) is "BibTex", see screenshot:

![image](https://user-images.githubusercontent.com/17251683/129476549-867674a6-013b-4b1a-93d8-2a002623fc85.png)

**Comment by pharaoh23** [comment]
Thanks,
It is working, I did not know that in options there was the possibility for
the choice.

Rob
