### ISSUE TITLE
[Feature] Make YAML Frontmatter Block toggeable

### ISSUE THREAD

**Issue by taubmann** [Zettlr/Zettlr#2307]
Sometimes YAML Frontmatter is filling up half of the screen when opening a file. It would be less distracting and a lot more elegant if it would be possible to toggle the visibility of the whole YAML Block (eg. by klicking on the YAML Frontmatter Button or with another Button in the Menu or a Shortcut). In Addition it would be great do define wether the Block should be visible by default or not.

### Example Workflow

Open a file containing a YAML Frontmatter block, only the Label/Button "YAML Frontmatter" is visible, indicating that there is a Frontmatter Block available. Clicking on the Label should toggle the visibility of the Block. If you define that the Block should be visible by default, the Block is expandad by default.

**Comment by nathanlesage** [comment]
This is a good one. I just don't know how to implement foldcode helpers but somehow it's possible!

(As always, if someone already has an idea, feel free to open a PR)

**Comment by cjpoor** [comment]
YAML Frontmatter can be folded as shown [here](https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/)
```
> — Folded text block

    Start with a greater than, and indent the next lines.

    The text will be collapsed into a single line when parsed.

    desc: >
      Tyrannosaurus is a genus of coelurosaurian theropod dinosaur.
      The species Tyrannosaurus rex is one of the most well-represented of the large theropods.
```

**Comment by taubmann** [comment]
This method is creating other issues. In this case (shown below) the title, tags and other elements are not recognized anymore. Also it would be necessary to remember the folding state (witch would be nice to have anyway)
<img width="386" alt="yaml-example2" src="https://user-images.githubusercontent.com/1518022/147256554-c478c8be-2777-4012-90a1-fccc928eec45.png">

**Comment by dranjor** [comment]
> This method is creating other issues. In this case (shown below) the title, tags and other elements are not recognized anymore. Also it would be necessary to remember the folding state (witch would be nice to have anyway) <img alt="yaml-example2" width="386" src="https://user-images.githubusercontent.com/1518022/147256554-c478c8be-2777-4012-90a1-fccc928eec45.png">

I think this is due to the indentation at the beginning of line, since 

![screen18](https://user-images.githubusercontent.com/18162321/180569844-9b099f04-60f4-4046-a99d-7b8e0f09db59.png)
works fine (Version 2.3.0).

Is it possibly to hide the yaml frontmatter analogous to links? Means: If the cursor is inside the yaml frontmatter, it is shown completely, otherwise "toggled".

![screen19](https://user-images.githubusercontent.com/18162321/180571762-9d24e6b8-ea70-498c-b1e2-0e33eeb5d76c.png)

**Comment by etienne-tr** [comment]
Yes it would help reading that yaml frontmatter to be hidden by default. It's sometimes a bit long and not so interesting when reading the literal content.

Using the yaml folded style is not so easy and it seems to me not so good to use code to manage style when you want to read or right contents.

For instance, the following example is it correct ?
```
---
> title:"My title"
  type:"index"
---
```

My preference would be using the toggle style (which style existing) to let appears by default only the first yaml line below the `---`. 

At least, if using yaml folded style with >, could it be toggled to hidden state by default ?

**Comment by exanrauzer** [comment]
No, don't include. In my opinion clickable YAML label to toggle visibility would be neat. And the visibility mode should be saved for given file, fe: inside a yaml as a variable (if it's possible).

**Comment by exanrauzer** [comment]
I think that in 3.0.0 Beta it is possible to fold Yaml section, but it goes along with the possibility to fold every broken line (not only Headings - as it was in 2.3.0).

From the other hand:

I dont't know if 3.0.0 additional element (reversed caret) will be immanent in GUI fir every broken line. I would prefere not to - I find it distracting in workflow over some types of documents (that I am used to). So I would preffer seperate way of folding Yaml section (and possibility to turn off folding UI revers caret in options for broken lines).

**Comment by nathanlesage** [comment]
The new Markdown mode features a more comprehensive folding strategy, which definitely clutters up the fold gutter. This is why I made those buttons invisible by default, so that you can only see them when you're on there with your mouse. I have no idea if we can actually turn that off. It could be that not.

Furthermore, we cannot separately introduce YAML front matter folding and the other folding, it's all in one, unfortunately.

**Comment by nathanlesage** [comment]
Closing as YAML frontmatter folding is supported in 3.0
