### ISSUE TITLE
Pdf export need new line to recognize next section

### ISSUE THREAD

**Issue by airaylee** [Zettlr/Zettlr#231]
## Description
Exported pdf couldn't recognize h2 header if previous body doesn't end with empty lines.

## Reproducing
On version 1.3.0 for h2 header with newest mactex and pandoc install using brew.

## Expected behaviour
Should be like  screenshot 2 instead of 1

**Screenshots**
Screen Shot 1 - Couldn't recognize second h2 header
![Screen Shot 1 - Couldn't recognize second h2 header](https://user-images.githubusercontent.com/5315165/59138787-d8863900-8943-11e9-866e-a6c47af58172.png)
Screen Shot 2 - Should work like this but new line in body still not recognized
![Screen Shot 2 - Should work like this but new line in body still not recognized](https://user-images.githubusercontent.com/5315165/59138814-2dc24a80-8944-11e9-8e51-f9cf02f79af2.png)

## Platform
 - OS: [e.g. iOS] MacOS
 - OS Version [e.g. 11] 10.14.5
 - Zettlr Version [e.g. 0.15]  1.3.0 
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
This is intended and correct Markdown specification behaviour. From our FAQ:

> **I want to use single line breaks and not create new paragraphs. When I simply hit Enter once, it removes the single line break!**

To force Pandoc to render single line breaks as such, end your line with a backslash (`\`) or two spaces. The backslash as well as the two spaces will not be rendered in the resulting file.

Further reading:

- https://gist.github.com/shaunlebron/746476e6e7a4d698b373
- https://docs.zettlr.com/faq/
