### ISSUE TITLE
[Bug] Ctrl-n does not create a new file in a directory

### ISSUE THREAD

**Issue by bachmeil** [Zettlr/Zettlr#2310]
### Description

If I right click the folder name and create a new file, the new file is created in the current directory. If I use the keyboard shortcut Ctrl-n, a new note is opened, but it's not created in any directory. I have to save the note and go through the file dialog to choose where to save it. 

I believe this is a bug, but if not, there should be a keyboard shortcut to create a new file in the current directory.

### Reproducing

Hit Ctrl-n while typing. Hit Ctrl-s to save.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by BellLongworth** [comment]
Happens to me in Windows 10 as well on beta-1.

**Comment by nathanlesage** [comment]
It is not a bug, in fact. My reasoning behind implementing it as such was the following:

* If you right click a directory, it's pretty clear where you want the file to end up, so we can simply drop it in there.
* If you just choose the shortcut, however, it is expected that the main concern is to start writing and deciding later where to put it.

For me, personally, I found this an extremely helpful way of preventing too much clutter in the directories while being able to just open a new unsaved file where I can quickly drop some text before deciding what to do with it.

I can see, however, that this might be confusing for some. But I'm not quite sure how I could mitigate this cleanly for everyone involved – any ideas?

**Comment by BellLongworth** [comment]
I work with only two directories and use the filter to find files. Also, I'm paranoid about losing data so ctrl-s is the first thing I do after naming the file, and I repeat it frequently. So for me the directory confusion is not a threat and so the old method made more sense.

 I understand how that changes if your flow has lots of directories and you don't mind keeping the file unsaved for a while.

**Comment by mousetrappling** [comment]
That's ... really distracting.  There I am, typing away and I save what I'm doing so far (I'll miss autosave a lot :( ) and suddenly I'm presented with a dialog box completely derailing my train of thought.  It didn't even default to one of the two open directories when I first tried it but tried to save the file in my Zotero directory.  And you can't trigger a save without starting work.

Not a deal breaker, I can come up with a workflow to work round it (stick in my boilerplate frontmatter, then save, then work) but it feels like a retrograde step to go back to manual saving and not even have a default place to save it.  Can it be a configurable option for default directory in the same way that you can choose whether or not to be prompted for the filename?

**Comment by BellLongworth** [comment]
I must say I agree. I really liked the old flow, including autosave (scroll jumping bug excepted). It was very close to the Google Docs and MS Office online flows where pretty much everything you type is getting saved and you don't need to worry about it. 
Saving every character is an overkill of course, but every few seconds or tens of seconds is ideal I think.

**Comment by bachmeil** [comment]
For me, the source of confusion was this combination:

- No button on the toolbar to create a new file.
- The only menu option to create a new file creates it without a location.
- Right clicking on the directory name for menu options is not intuitive.

My preferred solution would be:

- A button in the toolbar to create a new file that goes to an "inbox" of some kind.
- A menu option plus keyboard shortcut to create a new file in the current directory.

**Comment by nathanlesage** [comment]
> A button in the toolbar to create a new file that goes to an "inbox" of some kind.

That won't be possible; Zettlr has no concept of an "inbox". Remember: Zettlr's aim must be to provide professional writing but NOT the easy-peasy logseq-like experience of creating files on the go. It should be closer to offering you a very conscious decision whether you want to create new notes or not.

But I see across the board that autosaving was a big thing and that many want that back, so I'll be doing that as well.

**Comment by mousetrappling** [comment]
Just to clarify: I think that one of the reasons the behaviour was so unexpected (and distracting) for me was that I have Zettlr set to not prompt me for filenames, so having previously had seamless generation of a new file called exactly what I wanted and put exactly where I wanted, I now have filenames generated as I wish but it stops and asks questions about where it goes.  So that's why I was asking for an option to set a default directory (to go along with my generated filename), rather than a "inbox".

**Comment by noah-arroyo** [comment]
Just gonna pile on here. I prefer the old method of saving.

But I hear you, @nathanlesage. Maybe you could create a toggle in preferences, so the user could choose between auto-saving in the current directory v. the latest beta approach?

**Comment by nathanlesage** [comment]
> but then a second save dialogue (triggered by auto-save) opens on top of the first.

Grr, I thought I had prevented that … alright, ehm … yeah I have to think about all of that! I certainly see the issue but I'm pretty much out of time right now :(

**Comment by nathanlesage** [comment]
Commit 38db46c introduces a few notable changes that should fix that behavior:

1. When you select the option not to prompt for file names in the Advanced settings, a file will **always be created**, no matter what. Whether you right-click a directory or use the keyboard shortcut. A file will always be created.
2. When that option is **not** selected (the default), you will **always be asked for a filename**, no matter what. Additionally, if you create a new file using the keyboard shortcut, that file is in memory and not saved until you manually save it (the current behavior).

This should accomodate both types of people: Those who really want to have control over the files being created as well as those who simply want to have the file being created with no further ado. Just make sure to select the corresponding setting in the advanced preferences! Please provide feedback if that is a satisfactory solution after you're able to test it out (tomorrow with the new nightly or with the beta next week).

**Comment by mousetrappling** [comment]
Feedback as requested – that works well for me, with the don't prompt for filenames option ticked it's back to the previous pre-2.0.0 Zettlr behaviour and my workflow is happy again :)

P.S. I find it kind of amusing that (elsewhere, Twitter I think) you referred to this as catering for people who prefer Obsidian- or Logseq-like behaviour, when I've never used those applications and it's Zettlr that introduced me to this way of working!  I'd been thinking of it as preferring old-school Zettlr behaviour ;)

**Comment by noah-arroyo** [comment]
@nathanlesage I have good news AND bad news, per your fix:

### Good news

Agreeing with @mousetrappling: If the "Do not prompt" box is **checked**, then my workflow for creating and working within a new file in the current directory is as seamless as it used to be. Thank you!

And if the "Do not prompt" box **unchecked**, then this bug is now gone: Previously, if delayed auto-save was activated, then if I (a) opened a new file and (b) immediately hit `save`, (c) an initial save window would appear, but (d) the delayed auto-save function would then cause a _second_ save window to appear on top of the first.

### Bad news

If the "Do not prompt" box **unchecked** _and_ auto-save function is activated (either delayed or immediate), then after creating a new file (pressing `Ctrl+n`) Zettlr will not prompt me with a window asking where to save / what to name the file.

**Comment by mousetrappling** [comment]
Isn't the bad news exactly what @nathanlesage says it should do? That if you use option 2 in his comment then that means that pressing Ctrl-n is essentially not creating a file till you save it – it won't autosave coz it doesn't exist on disk till you manually save it, before that it's just floating about in memory.

**Comment by noah-arroyo** [comment]
Ah, yes you're right @mousetrappling. I missed that part of his comment. Thank you for the correction.

**Comment by nathanlesage** [comment]
Looks like we're all happy again :)
