### ISSUE TITLE
[Bug] 2nd (and Nth) right click in file list keeps old menus

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#2313]
### Description

![image](https://user-images.githubusercontent.com/63842998/129485423-dca0598a-59ff-4545-8470-145cea870802.png)

### Reproducing

Right click somewhere in the file list.
Right click again.

### Zettlr Version

Beta (if applicable)

### Specify version

beta-1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
That looks funny!

(But also unwanted.) Thanks for reporting!
