### ISSUE TITLE
[Enhancement] 'Omit Saved Changes' Dialog could be simpler

### ISSUE THREAD

**Issue by charris101** [Zettlr/Zettlr#2319]
### Description

In the 'omit saved changes' dialog the current options are 'proceed without saving' and 'save' but I find that strangely hard to process when I've just finished a late night writing session.

### Proposed Changes

I think a simpler dialog would read something like: 
'Save the file "new1.md"?' with options 'yes' 'no' or 'cancel'. 

### Caveats

Maybe user are used to the existing dialog but otherwise it shouldn't impede any other feature. 

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

### Additional Information

![zettlr ux](https://user-images.githubusercontent.com/70552035/129562861-c508023b-22a0-474a-be5f-d126f3ed9c18.jpg)

**Comment by nathanlesage** [comment]
Good point.
