### ISSUE TITLE
[feature request]: Way of Sorting Tags

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#232]
Hello, I'd like to request way of sorting tags. Perhaps this could be a reference, another markdown which ceased running. Thank you!
(link: http://www.sklobovskaya.com/work/Marginalia) sklobovskaya.com/work/Marginalia 
https://github.com/peterkeen/marginalia

**Comment by nathanlesage** [comment]
I just noticed your profile image and I am so happy to see Virno and Toni Negri!

So the tag sorting should not be of any problem in the tag cloud. The tags will receive a refactoring in the next months anyway, so I'll add this to my bucket list!

**Comment by nathanlesage** [comment]
Just saw it, fixed by the filtering in 1.4!
