### ISSUE TITLE
[Bug] Middle Click Paste on Ubuntu Linux Inserts Two Copies of the Copied Text

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2321]
### Description

In linux you can use two copy/paste methods – highlight text, ctrl-c to copy, ctrl-v to paste; or highlight text then use middle mouse button to paste.  Ctrl-C/Ctrl-V works as expected. Middle click paste inserts two copies of the copied text.  In Zettlr 1.8.9 (and all versions from May 2020 up to then) both copy/paste methods worked as expected, I didn't try the first 2.0.0 beta so I have first seen it in 2.0.0-beta.1.

### Reproducing

Highlight some text, use middle click to paste it.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

I think this may be related to this bug: https://github.com/Zettlr/Zettlr/issues/1882  If I had seen that bug before you closed it I would've commented that middle click paste works for me and always has, and I can't reproduce that bug in Zettlr 1.8.9 running on Ubuntu 20.04.  So I wonder if your fix for that is generating one of the pasted bits of text and the standard OS implementation of middle click paste is generating the other.

**Comment by mousetrappling** [comment]
Ctrl-Middle-Click on a file link opens the file and pastes the ID into both files.  I'm guessing that's related to this as well.

**Comment by nathanlesage** [comment]
Hm, someone was complaining that the selection clipboard didn't paste for them, so I added an explicit check for that here: https://github.com/Zettlr/Zettlr/commit/811fd3e10fc8319efdcbfc84753e4082a0bcc5b6

Since I can't test on Linux I have to rely on others reporting those bugs. It seems that these two issues are orthogonal to themselves, can that be? That for you it worked without the manual intervention, and for them it didn't work without that manual intervention of mine?

**Comment by mousetrappling** [comment]
Yeah, I installed this beta rather than wait for a stable release coz I know you've said before that you can't test Linux stuff so the more of us that do the better :)

I think the middle-click paste thing is handled by Gnome (or other desktop like KDE or whatever).  I've just done a bit of googling, and I think that middle click paste may NOT be on by default on a brand new Ubuntu Gnome install but it's something you set to on or off in the Gnome Tweak Tool rather than handled by applications (I did set this machine up only a few months ago, but I really can't remember what I needed to alter to make it all "the way I'm used to").  I'm really not a dev or even a particularly "power user" of linux though, so take all this with a large pinch of salt!

So if the original reporter was on a new install but hadn't noticed till using Zettlr about a missing middle click paste, maybe that was the problem?  My instinct is something was up with their set up rather than something you needed to fix, but hopefully they will come and chime in at some point too with more info!

**Comment by nathanlesage** [comment]
> My instinct is something was up with their set up rather than something you needed to fix, but hopefully they will come and chime in at some point too with more info!

Hey @sphh – in #1882 you mentioned that middle mouse pasting didn't work for you; would you mind checking what @mousetrappling just wrote, if that could be the case? If so, I'll revert the commit 811fd3e so that we're back to a regular setup!

**Comment by sphh** [comment]
Yes, the middle mouse pasting did not work for me – and is still not work working for me.

Zettlr 1.8.9
Linux Mint 20.2 Cinnamon

Middle mouse button pasting is working in all other applications, such as:
- Terminal
- XApps (editor and such like)
- LibreOffice
- Thunderbird
- Firefox
- Spyder
- any other program I use

I never heard about a global setting to dis/enable the middle mouse button pasting, because this is a fundamental feature of Linux since the 1990ies (and I use Linux since that time). So I guess, it is really not ‘up to my set up’!

Said that, there might be the idea in Gnome 3, that pasting with the middle mouse button is so unWindows-like, that they switched it off? I would not know …

**Comment by nathanlesage** [comment]
> Said that, there might be the idea in Gnome 3, that pasting with the middle mouse button is so unWindows-like, that they switched it off? I would not know …

That could well be. However, I have too few experience with Linux Window managers to state something clear. From my perspective, the main problem seems to be that one of you cannot middle-click-paste at all, while the other does it double, and we need to figure out why this is.

**Comment by mousetrappling** [comment]
I've also been using linux since the 1990s, middle click paste works in everything, and for me that INCLUDES Zettlr 1.6.x through 1.8.9 and now in the 2.0.0-beta 1 it double pastes.

I've got to take back the off by default thought, it was a red herring anyway – my husband just set up a new Ubuntu install last night (21.04 iirc) and it was on by default there.  And if it works in other applications for you then it's unlikely to be switched off.  Have you tried the beta?

**Comment by sphh** [comment]
Middle mouse pasting is definitely not turned off – I would not be able to live without it!!

One idea: You use `electron` for Zettlr? I wonder if we use different versions of `electron`: @mousetrappling one with middle mouse button pasting natively supported and for me, one which does not support it? Or there are (global) `electron` settings different for @mousetrappling and me?

I just downloaded the AppImage of the beta version:
```
$ ./Zettlr-2.0.0-beta.1-x86_64.AppImage 
(node:493766) ExtensionLoadWarning: Warnings loading extension at /home/sph/.config/Zettlr/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `Zettlr --trace-warnings ...` to show where the warning was created)
(node:493824) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 shortcut listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `exe --trace-warnings ...` to show where the warning was created)
```
and copying and pasting with the middle mouse button works both ways.

**Comment by mousetrappling** [comment]
So that suggests that the fix @nathanlesage put into works as intended for you whilst breaking middle-click paste (as it inserts two copies of the paste buffer) for me.  And we're no further forward, alas!

I've certainly never knowingly touched `electron` settings or installed it (other than as  Zettlr), so I've no idea where I would find such things so we can compare settings.

I install Zettlr from the .deb.  Is it possible that that brings with it a different collection of dependencies to the .AppImage?  I've no idea about Linux Mint as I've never used it, but can you install from the .deb on that and if so, what does that do?

**Comment by mousetrappling** [comment]
Actually, I've just spotted we're using builds for different architectures (I think that's how to phrase it).  I installed Zettlr-2.0.0-beta.1-amd64.deb for the beta, and all my previous Zettlr installs were -amd64.deb too.  Can that be making a difference?

**Comment by sphh** [comment]
The existing version – that one, which I use all the day and where I noticed, that pasting with the middle mouse button does not work – was installed from zettlr-1.8.9-amd64.deb.

The installed dependencies for it are:
- libappindicator3-1
     12.10.1+20.04.20200408.1-0ubuntu1
- libatspi2.0-0
     2.36.0-2
- libgtk-3-0
     3.24.20-0ubuntu1
- libnotify4
     0.7.9-1ubuntu2
- libnss3
     2:3.49.1-1ubuntu1.5
- libsecret-1-0
     0.20.4-0ubuntu1
- libuuid1
     2.34-0.1ubuntu9.1
- libxss1
     1:1.2.3-1
- libxtst6
     2:1.2.3-1
- xdg-utils
     1.1.3-2ubuntu1.20.04.2

I could not find an AppImage for amd64.

I have never knowingly fiddled with any electron settings (@nathanlesage: are there any?), but I once had Atom installed (but removed it some time ago)

I am not too happy to install the beta version via the .deb file (but if it is the only way to sort this out, I might bite the bullet).

**Comment by mousetrappling** [comment]
I suspect it's a red herring, because we were using the same version of 1.8.9 :/

**Comment by nathanlesage** [comment]
Hm. So let me attempt at clarifying what might and what might not be the cause:

* Electron is the underlying framework, but it's basically just the binary that executes the code for Zettlr. That being said, even on different architectures (x64 vs. arm64) there shouldn't be a difference.
* Specifically: The code for middle-pasting is 100% my own code, so this code runs completely independently of any platform or architecture
* There are no global Electron settings since each electron app ships with its own binary and config

That being said: I cannot think of anything that might cause this problem, except one global setting which we've already ruled out by now.

> I could not find an AppImage for amd64.

`amd64` === `x86_64`, so that's why. This is just a peculiarity of Electron-builder, both are standard 64bit architectures.

> I am not too happy to install the beta version via the .deb file (but if it is the only way to sort this out, I might bite the bullet).

You might not need to. Did I correctly understand that you regularly use the AppImage version where it doesn't work, while @mousetrappling has just tested out the AppImage as well and noticed that it does work for them?

**Comment by mousetrappling** [comment]
No, sorry that's not the case.

In summary: I have used the 1.8.9 deb and the 2.0.0-beta 1 deb.  @sphh has used the 1.8.9 deb and the 2.0.0-beta 1 AppImage.

With 1.8.9 middle click paste works for me, and does nothing at all for @sphh.

With 2.0.0-beta 1 middle click paste pastes twice for me, and once for @sphh.

I think the underlying behaviour hasn't changed for either of us: middle click paste works natively for me and does not work natively for @sphh.  Your code change works for both of us, that's why I see duplicate pasting and @sphh only one in the beta.

**Comment by nathanlesage** [comment]
That was what I wanted to express (albeit unnecessarily complicated, I'll admit)!

**Comment by sphh** [comment]
Thanks for explaining and summarizing. I can only add:

I used the AppImage for x86_64 (and not for arm).

I just installed 2.0.0-beta.1 from the amd64 deb file and here I also get a perfect single paste (and also a perfect copy when selecting some text).

Two questions:
1. I guess `electron` uses an external toolkit. On my installation it has a dependency on `libgtk-3-0` and I have version `3.24.20-0ubuntu1` installed. It would be interesting, which version @mousetrappling has installed?
2. The other reason for this puzzling behaviour might be the graphical environment: X-server or Wayland. Linux Mint is still using X11, but Ubuntu might have switched to Wayland …

Re. 2: Please execute
```sh
echo $XDG_SESSION_TYPE
```
and tell us your output. I get `x11`.

(If the above command does not work, excute
```sh
loginctl
```
note the `SESSION` id (for me it is `c1`) and call
```sh
loginctl show-session c1 -p Type
```
with your session id.

I get `Type=x11`.

**Comment by mousetrappling** [comment]
I have version `3.24.20-0ubuntu1` of `libgtk-3-0`, and I'm using X11 as well.

**Comment by sphh** [comment]
Last thing to try:
```sh
gsettings get org.gnome.desktop.interface gtk-enable-primary-paste
```
I get `true`.

If there is no difference, @mousetrappling you might want to ask the Ubuntu developers, why Ubuntu is behaving differently :grin: …

**Comment by mousetrappling** [comment]
I also get `true`.

Let's be honest I'm not going to go waste the time of the Ubuntu developers by asking "My system was working perfectly till a dev added code to duplicate the middle-click paste behaviour, now it is displaying duplicated behaviour in that dev's application.  Why's that?".  Because they, like me, will see this as Ubuntu working perfectly and suggest I ask the dev to take their code out.

I'm also not going to ask @nathanlesage to do that, because it clearly would break things for you (and possibly every other Linux Mint user out there).

Instead might I suggest that @nathanlesage turns this into a togglable setting where those of us with working middle-click paste can leave his version off, and those of us with non-working middle-click paste can turn his version on.  He could set whichever default he thinks will get him fewer bug reports :)

**Comment by nathanlesage** [comment]
> Instead might I suggest that @nathanlesage turns this into a togglable setting where those of us with working middle-click paste can leave his version off, and those of us with non-working middle-click paste can turn his version on. He could set whichever default he thinks will get him fewer bug reports :)

The preferences dialog is really getting crowded 😂

**Comment by sphh** [comment]
@nathanlesage, I might have found something!

On Zettlr-2.0.0-beta1:

- If I paste with the middle **mouse** button, I get a **double** paste.
- If I paste with using the **touchpad**, which emulates the middle mouse button with a tri-finger tap, I get a **single** paste.

On Zettlr-1.8.9:

- If I paste with the middle **mouse** button, I get a **single** paste.
- If I paste with using the **touchpad**, which emulates the middle mouse button with a tri-finger tap, I get **no** paste.

In my defence, I can only say, that I don't use the mouse very often and always thought, touchpad equals mouse, hence I did not mention this is my bug report #1882 …

**Comment by mousetrappling** [comment]
Ok, as it happens I am also actually using a laptop (only got it a couple of months ago) but I plug it into keyboard and mouse when I'm at home and am significantly more likely to use the real mouse than the touchpad.

I have now also tested that and I get the same behaviour as @sphh.  So clearly touchpad three-finger-click emulates middle mouse button in one sense (@nathanlesage's code recognises it as a middle mouse button) but not in another sense (Gnome treats it differently).  It never would've crossed my mind that that is a situation that might exist :open_mouth:

But it's a Gnome problem, not a Zettlr problem I think.

**Comment by sphh** [comment]
I cannot comment, if it is a Gnome or `electron` problem (pasting with middle mouse button was added in 2014 https://github.com/electron/electron/issues/377), I can only observe, that pasting with middle mouse button and three-finger tap on the touchpad works for **all** other programs …

@nathanlesage?

**Comment by sphh** [comment]
I captured both events with `xev`.

Mouse middle click:
```
ButtonPress event, serial 35, synthetic NO, window 0x6200001,
    root 0x7b2, subw 0x0, time 158462015, (53,100), root:(1770,1230),
    state 0x10, button 2, same_screen YES

ButtonRelease event, serial 35, synthetic NO, window 0x6200001,
    root 0x7b2, subw 0x0, time 158462188, (53,100), root:(1770,1230),
    state 0x210, button 2, same_screen YES
```

Triple-finger tap on touchpad:
```
ButtonPress event, serial 35, synthetic NO, window 0x6200001,
    root 0x7b2, subw 0x0, time 158468816, (53,100), root:(1770,1230),
    state 0x10, button 2, same_screen YES

ButtonRelease event, serial 35, synthetic NO, window 0x6200001,
    root 0x7b2, subw 0x0, time 158468816, (53,100), root:(1770,1230),
    state 0x210, button 2, same_screen YES
```

Both are the same, but the time difference between `ButtonPress` and `ButtonRelease` for the touchpad is always =0. I could not get a larger difference there, whereas for the mouse button I could not get it down to 0. I wonder, if `electron` catches this and only accepts taps for native pasting with time difference larger than 0?

I seem to remember, that I could not paste with the touchpad in the Atom editor and that was one of the reasons, I ditched it again (but please don't quote me on this, this is lost in the mist of history).

**Comment by nathanlesage** [comment]
> Anyway, I can observe that when I click very slowly, one paste happens at button press, and the second one at button release.

My custom middle-click paste reacts to mousedown events (i.e. when you press the button down). So the native paste event seems to listen to mouseup events. Maybe that helps?

**Comment by frederik-elwert** [comment]
Another observation: Other applications show different behaviour: Native GNOME applications like gedit or Terminal also past on button down. Others, like Firefox, paste on button up. So it looks like it somehow depends on the application and/or framework behaviour.

In Zettler, I found that button down pastes _with_ formatting, while button up pastes _without_ it (i.e., plain text).

Still, I’m quite puzzled as to what users can do about it. It looks like you implemented a custom handling because it didn’t work for some users. Now it’s duplicated for others. Where does the second paste come from? Is it CodeMirror that also handles the event?

**Comment by nathanlesage** [comment]
> Where does the second paste come from? Is it CodeMirror that also handles the event?

The second event is likely the native Chrome behavior of pasting text, so I think that code might be hidden somewhere in Chromium's code base …

> (The interesting behaviour with regards to formatting reminds me of #1480, though of course I don’t know if they are related.)

Good question, I saw that you linked that issue, but I'm not sure how much related these are. Copying and Pasting is really an art …

**Comment by nathanlesage** [comment]
Yes, I haven't yet removed the additional code, since I'm still unsure what is causing this :S

**Comment by sphh** [comment]
I now installed v2.0.2 and found the following experience on Linux:
- Touchpad triple finger click (=emulates mouse middle click): The selected text is pasted once.
- Mouse middle click: The selected text is pasted twice at button up.

Could this be a bug in the underlying Electron framework?

**Comment by Libralop** [comment]
I have also installed version 2.0.2. 
OS: xfce / xubuntu. 
I can observe the following behaviour:

- Middle click with the mouse: double paste
- Three finger tap on the touchpad (=emulates mouse middle click): double paste

**Comment by nathanlesage** [comment]
> Could this be a bug in the underlying Electron framework?

… maybe? I honestly don't know. But I'm pretty sure this also varies among distributions, given that different window managers apparently have different ways of handling this.

I think I'm just gonna remove the custom code which'll reset the behavior to useful on most distributions, and for the other distros we'll just have to file bug reports with Electron. There's not much Zettlr itself can do here.

**Comment by sphh** [comment]
I can perfectly understand removing this custom code!!!

**Comment by nathanlesage** [comment]
The code is now gone. If anyone experiences these issues, it's probably best to try to open a bug report directly against Electron's repository since in some instances it works well, so it might be a bug in the framework.

**Comment by sphh** [comment]
I certainly could open a bug report against [Electron's repository](https://github.com/electron/electron/issues). My problem is, that I am not of much help to track this down, because I have very, very limited knowledge of JavaScript and absolutely none with regard to Electron. I can only describe my experience (no paste with triple-finger tap on touchpad, paste with mouse middle click in Linux Mint 20.2). I would not be able to answer any question at all.

@nathanlesage: You are be the expert and it would be most efficient if you could open the bug. Is that possible?

**Comment by nathanlesage** [comment]
I think it might actually also be a problem for CodeMirror. One last attempt: Would you mind trying out middle clicking here in that text area: https://codemirror.net/mode/gfm/index.html

If you can reproduce the same behavior as in Zettlr, it might be that it's CodeMirror all along, and Electron was a false flag. But if you cannot reproduce the behavior, then it's definitely CodeMirror, and I can set up a fiddle to reproduce this.

**Comment by sphh** [comment]
Thanks for still looking into this!

I tried pasting with the middle mouse button or the touchpad three-finger tap in the text area at https://codemirror.net/mode/gfm/index.html: Nothing is pasted. Not with the middle mouse button. Not with the three-finger tap on the touchpad.

I also tried it here in github's text input field: Both pasting method works.

Browser: Firefox 94.0 (64-bit)
Linux Mint 20.2

**Comment by sphh** [comment]
I just did a simple search through CodeMirror's source code for mouse events and found these lines: https://github.com/codemirror/CodeMirror/blob/475069f8f7fbe6bb21f54eed51e52ff6741335ce/src/edit/mouse_events.js#L87-90
```javascript
  } else if (button == 2) {
    if (pos) extendSelection(cm.doc, pos)
    setTimeout(() => display.input.focus(), 20)
  } else if (button == 3) {
```

I wonder, if the line
```javascript
    setTimeout(() => display.input.focus(), 20)
```
is the culprit (but then, as I often said, I have no idea about JavaScript and what the function `setTimeOut` really does, so this is a very wild guess).
Maybe these lines should read
```javascript
  } else if (button == 2) {
    if (pos) {
      extendSelection(cm.doc, pos)
      setTimeout(() => display.input.focus(), 20)
    }
  } else if (button == 3) {
```
instead???

**Comment by nathanlesage** [comment]
> I also tried it here in github's text input field: Both pasting method works.

Ah, alright. This is a good indicator that the culprit might really be CodeMirror, since it's not a regular textarea (where middle-clicks work as expected); it has to emulate that behavior.

With regard to the code changes you found: Maybe? It does look logical to me but I'm not as firm in the codebase as I wished I was. But since you could reproduce it on the demos of CodeMirror, you might be able to file a bug report with CodeMirror!

**Comment by sphh** [comment]
I now searched for middle click / primary clipboard in CodeMirror's issue, I found this [issue 931](https://github.com/codemirror/CodeMirror/issues/931). It basically says, that pasting does not work for Firefox but it works for Chrome and this is an issue with Firefox. Hence I do not know, if my tests at https://codemirror.net/mode/gfm/index.html are meaningful at all.

With regard to the code: We tracked the problem down to the fact that when using the touchpad the `ButtonRelease` event is fired immediately after the `ButtonPress`. If the lines mentioned implement a cool down period of 20 ms(?), the `ButtonRelease` event falls into this period and is discarded. I wonder, if that is the functionality of `setTimeout(() => display.input.focus(), 20)`?

**Comment by Libralop** [comment]
> I think it might actually also be a problem for CodeMirror. One last attempt: Would you mind trying out middle clicking here in that text area: https://codemirror.net/mode/gfm/index.html
> 
> If you can reproduce the same behavior as in Zettlr, it might be that it's CodeMirror all along, and Electron was a false flag. But if you cannot reproduce the behavior, then it's definitely CodeMirror, and I can set up a fiddle to reproduce this.

I also tried to insert something into the linked text field using the middle mouse button and the three-finger tap. 

For me, everything worked as expected: simple pasting of a previously copied text. 

- Ubuntu 20.04.2.0 (Focal Fossa) with XfCE as window manager. 
- Firefox 93.0
- Chrome 95.0.4638.69

**Comment by nathanlesage** [comment]
@Libralop Yeah, so if the CodeMirror demo is any authoritative example, it might also be an issue with the MINT Window manager. Basically: I don't know which part is causing it and so I'm basically wildly guessing.

Please excuse if I sound very un-knowledgable in this regard, it is because I am, and I don't have a Linux machine to try that out :(

**Comment by Libralop** [comment]
> Please excuse if I sound very un-knowledgable in this regard, it is because I am, and I don't have a Linux machine to try that out :(

You don't have to apologise for anything! I can see that the project is a one-man-show, a good bit away from being perfect, but on the other hand a maintainer who is fully committed. And that makes me believe in ZETTLR. That makes it exciting ;-)

**Comment by sphh** [comment]
@Libralop: Thanks for trying. Can you please start `xev` from a terminal window, move the cursor over the small window which pops up and press/release the middle mouse button and do a three-finger tap. Than please post the four `ButtonPress`/`ButtonRelease` events. (BTW the program can either be closed with the window close button or `Ctrl-C` on the _terminal_ window.) Thanks.

@Libralop: Do you use X11 or Wayland?

Do you know, if the events are generated by the window manager or the graphical display server (X11/Wayland)?

If it is really a Mint issue, I am happy to open an issue there…

**Comment by sphh** [comment]
@Libralop: Thanks. Are those `xev` events for the mouse middle button or the three-finger touchpad tap? (And can you please post the missing one.)

I was always of the impression, that the display server generates the mouse events (that might be different for Windows?) A quick search gave me (https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html):
> The X server reports KeyPress or KeyRelease events to clients wanting information about keys

so I believe, the events on Linux are independent from the window manager used (but experts might prove me wrong). Anyway I use the default window manager for Linux Mint: `muffin 5.0.2`

My X version:
```sh
$ xdpyinfo
version number:    11.0
vendor string:    The X.Org Foundation
vendor release number:    12011000
X.Org version: 1.20.11
[...]
```

**Comment by Libralop** [comment]
> @Libralop: Thanks. Are those `xev` events for the mouse middle button or the three-finger touchpad tap? (And can you please post the missing one.)

XEV for the Three-Finger-Tap:

```
ButtonPress event, serial 37, synthetic NO, window 0x5400001,
    root 0x705, subw 0x0, time 6684398, (62,146), root:(894,533),
    state 0x0, button 2, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x5400001,
    root 0x705, subw 0x0, time 6684498, (62,146), root:(894,533),
    state 0x200, button 2, same_screen YES```
```

XEV for the Middle-Mouse-Button:

```
ButtonPress event, serial 37, synthetic NO, window 0x5400001,
    root 0x705, subw 0x0, time 6690182, (62,146), root:(894,533),
    state 0x0, button 2, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x5400001,
    root 0x705, subw 0x0, time 6690332, (62,146), root:(894,533),
    state 0x200, button 2, same_screen YES
```

> I was always of the impression, that the display server generates the mouse events (that might be different for Windows?) A quick search gave me (https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html):
> 
> > The X server reports KeyPress or KeyRelease events to clients wanting information about keys
> 
> so I believe, the events on Linux are independent from the window manager used (but experts might prove me wrong). 

Yes, that is also my basic assumption.

> Anyway I use the default window manager for Linux Mint: `muffin 5.0.2`

> My X version:
> 
> ```shell
> $ xdpyinfo
> version number:    11.0
> vendor string:    The X.Org Foundation
> vendor release number:    12011000
> X.Org version: 1.20.11
> [...]
> ```

Same X-Version here.

**Comment by sphh** [comment]
Thanks!

Comparing the `xev` events between https://github.com/Zettlr/Zettlr/issues/2321#issuecomment-901419536 and https://github.com/Zettlr/Zettlr/issues/2321#issuecomment-963071679, the following behaviour can be seen:
1. Mouse press and release events are always some time apart: 150 ms for @Libralop and 173 ms for me (for the examples given).
2. Three-finger tap press and release events for @Libralop are 100 ms apart.
3. Three-finger tap press and release events for me are 0 ms apart.

This explains, why it is working for @Libralop, but not for me, as established previously.

I see the following behaviour:
1. If the `ButtonPress` and `ButtonRelease` events are spaced some time apart, Zettlr received the second event and can paste.
2. If the `ButtonPress` and `ButtonRelease` event occurs virtually at the same time, Zettlr does not receive the paste event.
3. Any other X program acts on the `ButtonRelease` event by pasting the primary clipboard.

For me the consequential question is: Which of the frameworks used by Zettlr (Electron, CodeMirror, …) suppresses the `ButtonRelease` event if it is too closely to the `ButtonPress` event?

@nathanlesage: Do you know, what the line
```javascript
    setTimeout(() => display.input.focus(), 20)
```
really does?

A workaround would be to change the input driver (or the kernel driver?) to put some time between the `ButtonPress` and `ButtonRelease` events. (I use `libinput 1.15.5`)

**Comment by nathanlesage** [comment]
First, I do not think the distance in time delay has any meaningful to say, since 150ms vs. 170ms seems to pretty much indicate the amount of time it took you to lift your fingers off the trackpad again. The 0ms event delay might be a potential candidate, since (as far as my reasoning goes, without knowing it) press-release event cycles might generally be "expected" by most to be some time apart, and if that assumption is violated (as in your case) this might cause problems.

As to which framework is the culprit: I don't know, actually. It might be this unwritten assumption that there should be some time difference between a press and a release event, but I could be wrong.

With regard to the timeout: That focuses the input of the CodeMirror editor (which receives those paste events) after a 20ms timeout, but I don't know at which step during a cycle it is being fired. So it could be the culprit, or just a false flag.

**Comment by sphh** [comment]
@frederik-elwert has proven in https://github.com/Zettlr/Zettlr/issues/2321#issuecomment-907185756, that only the time delay between the `ButtonPress` and `ButtonRelease` events is important: If he was very fast when clicking, he got a paste, otherwise two pastes (that was with the custom paste code in place). Without that custom code in place, this would mean:
1. Regular click with the middle mouse button: Paste the primary clipboard.
2. Very, very fast click with the middle mouse button (or three-finger tap with some touchpads/drivers): No paste of the primary clipboard.

Regarding the timeout: If that line focuses the input of the CodeMirror editor 20 ms after `ButtonPress` event, the `ButtonRelease` event would not reach the editor in this time frame, because the editor does not have the focus! (At least that is my understanding.)

**Comment by nathanlesage** [comment]
> Regarding the timeout: If that line focuses the input of the CodeMirror editor 20 ms after ButtonPress event, the ButtonRelease event would not reach the editor in this time frame, because the editor does not have the focus! (At least that is my understanding.)

That was my thought as well, yes.

**Comment by Libralop** [comment]
Version 2.0.3:

-     Middle click with the mouse: single paste
-     Three finger tap on the touchpad (=emulates mouse middle click): single paste

Everything works like expected. Thanks!

**Comment by sphh** [comment]
@Libralop: Great that it works for you! It does not work as expected for me. :disappointed:
