### ISSUE TITLE
[Bug] Quicklook Doesn't Do Anything

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2322]
### Description

If I right click on a file in the file browser on the left and choose Quicklook, nothing happens.

I'd expect it to open the file in a second read only window as it used to.

### Reproducing

Right click on a file, choose Quicklook.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

I hope this isn't a duplicate.  I could swear I saw a mention that this wasn't working somewhere (that's why I have specifically tested this evening when I installed the beta) but a search of the issues here doesn't pull anything out.

**Comment by nathanlesage** [comment]
Couldn't work since the context menu didn't do anything :D
