### ISSUE TITLE
[Bug] Linux Icons can't be scaled?

### ISSUE THREAD

**Issue by tegularius-fr** [Zettlr/Zettlr#2327]
### Description

Don't know if it's mine problem or not. I am running Zettlr on my Manjaro Linux laptop (AppImage). When the app is running in full-sized window it seems ok, but if I want to resize the window, icons overlap or just can't be scaled.

### Reproducing

Run zettlr and resize the window (for example [super] + right | left arrow)

That's how it looks for me in half-sized window (file manager and global search icons overlap):
![image](https://user-images.githubusercontent.com/76920949/129818940-d613d06a-35d3-42f1-af87-933eb17cdf7f.png)

Or quarter-sized window (icons can't fit the window size):
![image](https://user-images.githubusercontent.com/76920949/129819058-431eac57-c98f-4a90-b06c-e87b04d9865f.png)

In comparison 1.8.9. version seems to scale icons fine or at least better (half-sized window):
![image](https://user-images.githubusercontent.com/76920949/129820012-a9d0dbd5-bc62-462e-a348-32150c5e0c7c.png)

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.1+nightly-20210816

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro Linux

### Additional Information

Display resolution is 1920x1080 (16:9).
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.11-1-MANJARO (64-bit)

**Comment by nathanlesage** [comment]
Looks as if I accidentally made the Linux icons way too large while looking at the gnome HIG
