### ISSUE TITLE
[Bug] menus don't work on beta2

### ISSUE THREAD

**Issue by gusmmm** [Zettlr/Zettlr#2329]
### Description

In the new beta2 in ubuntu - both the deb and the appimage - these menus don't work anymore - when I click on them, nothing happens.
![unknown](https://user-images.githubusercontent.com/6109604/129959552-b0f09d01-0b73-4fda-9b46-88d0eaaf1a06.png)

### Reproducing

Click on the menus

### Zettlr Version

Beta (if applicable)

### Specify version

Beta 2

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by mousetrappling** [comment]
Those menus work for me, also Ubuntu 20.04 running 2.0.0-beta 2.

However I can no longer right click to get context menus.  Not sure if that should go in a different issue or if both of these are part of a more general "there are problems with menus" bug.

**Comment by charris101** [comment]
Just confirming that menus are not working here in Windows 10 either

**Comment by sewag5** [comment]
Here the same: menu not working, also contextmenu is not. Windows 10 21H1 Build 19043.1110)
Latest Zettlr from updater (imho beta2)

**Comment by nathanlesage** [comment]
Confirmed: Menus don't work on Windows and Linux, only on macOS. I screwed them up accidentally. To fix, you'd have to downgrade to beta.1

Apologies!

This is the offending commit: https://github.com/Zettlr/Zettlr/commit/f090a596d72d5acda986ede7d9a5404d556ce67b

If someone has the time to test out what exactly in these changes has destroyed the menu ability on Linux+Windows, feel free to already open a PR fixing that – I don't have time this week to fix it, but I will merge a fix PR.

Please also see the linked issue that has prompted me to implement this: #2313.

**Comment by nathanlesage** [comment]
Found the issue: I forgot to change two (!) single (!) characters (!!). The menus were never gone, they were always there, and everything worked perfectly -- EXCEPT the styles. These were missing. This happens when you "just qucikly wanna push code to production" very shortly before a release ... 🙄
