### ISSUE TITLE
Feature Request: Mindmap + Zettel

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#233]
Hello, I really appreciate the newet version of zettlr launched. It looks really good. I started using zettlr as zettelkasten and frequently frequented zettelkasten.de blogs to see how to use zettels. And one idea that captivates me is using zettel + mindmap to connect ideas more freely. Some use tinderbox on macs (I use windows). I tried searching mindmaps that could cater to my needs, i.e. to be able to edit the nodes in markdown. I stumbled upon a website markdown+mindmap editor called [contexted.io](http://contexted.io) and [tiddlywiki.com](https://tiddlywiki.com/). I know this is a big project and don't expect it would come out as a new feature soon, but I think it would only make Zettlr more robust as a markdown editor. Thank you, for bringing this app for us. :)

**Comment by nathanlesage** [comment]
Hey, thank you so much for the compliments! :) I really appreciate this! Concerning your idea: Yes, it's planned, but, as you mentioned, indeed a huge task. So, for the time being I'll close this task not to pollute the issue tracker. However, you may want to discuss this on the [forum](https://forum.zettlr.com/) and see here and there about possible concrete ideas to help shape this feature for when it's due in the future!

Just some buzzwords to indicate at what I'm planning: Something along the lines of a multiple correspondence analysis (cf. Pierre Bordieu, "La Distinction"); network analysis/complex systems theory (something concerning Luhmann and cybernetic research), natural language recognition and Graph DB. I'm still not sure as to what I'll be doing, but something along these lines! :)
