### ISSUE TITLE
[Bug] Dropdown List for Link Selection Doesn't Update Titles Until a New File is Created (or Zettlr is Restarted)

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2330]
### Description

If I edit the title of a note (in the YAML front matter) it updates immediately on save in the file browser on the left and the tab header.  However it doesn't update in the dropdown list you get when you add a link (by typing [[ ) until either a new file is created and saved or Zettlr is restarted.  I'd expect it to update at the same time the other places do.

### Reproducing

Create a file, and create YAML front matter including a title attribute.  Save this file.

Look in the file browser, tab header and type [[ to check the dropdown list; all will show the title of the file.

Edit the title.  Save the file.

See it update in the file browser and tab header.

Type [[ and look at the dropdown list, where you will see the original title.

Create a new file and save it.

Now type [[ and look at the dropdown list and you'll see the edited title for that first file.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.2

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by nathanlesage** [comment]
> until either a new file is created and saved or Zettlr is restarted

That is a pretty helpful info for me so I know where to start looking, thanks!
