### ISSUE TITLE
Spellchecker not working 

### ISSUE THREAD

**Issue by diocrates** [Zettlr/Zettlr#2334]
### Description

Right+clicking  a misspelled word does not activate spellchecker.

### Reproducing

Right+click a misspelled word to bring up spellchecker

### Zettlr Version

Beta (if applicable)

### Specify version

2.0 beta 2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This has nothing to do with the spellchecker. Rather, I accidentally broke the menus in beta.2; fix will be incoming asap; until then please use the beta.1. Sorry for the inconvenience!
