### ISSUE TITLE
GUI doesn't show up [Bug]

### ISSUE THREAD

**Issue by sebi5361** [Zettlr/Zettlr#2335]
### Description

Zettlr GUI doesn't show up despite Zettlr process being executed:
![](https://i.ibb.co/cv95v0N/2021-08-19-21-28-29.png)

### Reproducing

Killing Zettlr process using the process explorer and restarting the app by clicking on its shortcut.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Microsoft Windows 10 Pro Version	10.0.19043 Build 19043

### Additional Information

Zettlr used to work on my computer.
At one time I uninstalled the app and when I reinstalled it after a while the issue started.
To solve this issue I tried reinstalling the app for all users but it didn't help.
I tried to run the program as an administrator but neither did it help.

**Comment by nathanlesage** [comment]
Do I understand you correctly that you have killed the process and then clicked on the icon to re-start the app, but the GUI doesn't show up?

If so, it could very well be that you just killed one of the processes (Zettlr uses several binaries for various helper processes) which could've resulted in zombie-processes.

Would you mind trying out the beta.1 (NOT the beta.2 since I unfortunately did a big mistake for that one) and see if the problem persists?

**Comment by sebi5361** [comment]
> Do I understand you correctly that you have killed the process and then clicked on the icon to re-start the app, but the GUI doesn't show up?

I killed the process because the GUI didn't show up after I reinstalled Zettlr.
As I might have clicked on the icon a second time as I was expecting for the GUI to appear (if I remember right the mouse cursor was changing its shape for a short moment), I decided to look for the presence of a process in the task explorer.
I noticed there was some processes called Zettlr running so I killed the root one to try again launching a fresh Zetlr.

The import thing is that **Zettlr GUI never showed up after I re-installed the software on my computer**.

> If so, it could very well be that you just killed one of the processes (Zettlr uses several binaries for various helper processes) which could've resulted in zombie-processes.

I made sure to kill ALL of the Zettlr processes by clicking on the root process in the task explorer, and checking I couldn't find any more process named Zettlr after this.

> Would you mind trying out the beta.1 (NOT the beta.2 since I unfortunately did a big mistake for that one) and see if the problem persists?

I will do so and let you know.
Thank you for trying to help me!
I find Zettlr to be a great piece of software and would love to use it more.

**Comment by sebi5361** [comment]
> Would you mind trying out the beta.1 (NOT the beta.2 since I unfortunately did a big mistake for that one) and see if the problem persists?

I have just tried **Zettlr-2.0.0-beta.1-x64** and the problem is still exactly the same ):

**Comment by sebi5361** [comment]
> Would you mind trying out the beta.1 (NOT the beta.2 since I unfortunately did a big mistake for that one) and see if the problem persists?

I have just tried **Zettlr-2.0.0-beta.1-x64** and the problem is exactly still the same :(

**Comment by nathanlesage** [comment]
That is weird. It might be that you've encountered this weird "Electron doesn't want to do what it should"-bugs. Would you mind following the instructions here and see if that fixes it?

--> https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app

**Comment by sebi5361** [comment]
It worked!! Thank you so much!!

**Comment by sebi5361** [comment]
I am closing this issue. Thanks again.

**Comment by nathanlesage** [comment]
Glad to hear that! :)
