### ISSUE TITLE
[Bug] Missing images when exporting project to Office on Windows if project folder is not C:\

### ISSUE THREAD

**Issue by dialmove** [Zettlr/Zettlr#2338]
### Description

Exporting images on Windows to Office documents is hit or miss. In versions 1.8 and 1.9, there is a bug when exporting as document a project stored in a folder on a drive unit other than `C:\` (for example in `E:\`). This happens when exporting either to .docx or .odt. 

It was bothering me for some time, as it worked in one computer and not another, and I couldn't identify the drive unit as the cause until today.

I've tried it on 2.0.0-beta1, and it has gotten worse. In the latest version the images don't show even when generating a single current file, in any format (not even .html), in either unit `C:\` or `E:\` . Also, Export project doesn't do anything for me on beta 1, it fails silently (I couldn't try on beta2 because of the bug of menus not showing); .

I'm using images relative to the path of each file that use them, maybe version 2.0 is expecting only absolute paths? That would make my project unupgradeable to 2.0, as all image paths are relative to the local folder of the file). If this was needed, I could change them to be relative to the project base path, but not absolute to the file system.

### Reproducing

Steps to reproduce in 1.X: 
- Store a project with subfolders in drive `E:\temp\myProject\`
- Create subfolders `\myChapter1\chapter1.md`, `\myChapter2\chapter2.md`
- Set `./media` as the relative path when inserting an image in a file of the project (I also have `media/` as default image path in settings)
- Store images in `\myChapter1\media`, `\myChapter2\media` (linked either as `media/image.png` or `./media/image.png` from the .md files)
- Export the project. It doesn't find images, and instead inserts the file name. 
 
The same export works fine when generating a single file, or if the same project is copied to `C:\`:

-Copy the project to `C:\temp\myProject`
-Export the project. It shows all images correctly.

It also works if changing the export file type to html on `E:\`. In this case, it creates the correct route to the `\media` subfolder with the correct image for each file, changing the image path to absolute.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9 Application ID: c2d6a968-90ea-4221-a0e0-060fb14a73ae

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

This is the output of two chapters with images in them, when export fails:

#### Screen layout
F1301-SSM-Calendar.en.png
Figure 1: SSM Calendar

#### Day view
F-Daily-view-details.en.png
Figure 2: Daily view details
F-Day-view-stretches.en.png
Figure 3: Day view stretches
F-Day-view-trips.en.png
Figure 4: Day view trips

The images preview works correctly on the editor, although copy/pasting from clipboard messes up the path character:

    ![Day view stretches](media\F-Day-view-stretches.en.png)

instead of 

     ![Day view stretches](media/F-Day-view-stretches.en.png)

It recognizes both versions, though.

**P.S.** 

I've tried updating the image path to absolute with URL local path format and it works in beta1 when generating html, but not for .docx.

    file:///E:/temp/myProject/myChapter/media/F1301-SSM-Calendar.en.png

or 

    E:/temp/myProject/myChapter/media/F1301-SSM-Calendar.en.png

(Export to .docx also didn't work when adding the absolute path as a Windows route either as `E:/temp/myProject/myChapter/media/F1301-SSM-Calendar.en.png` or `E:\temp\myProject\myChapter\media\F1301-SSM-Calendar.en.png`).

Also, I've noticed the new "Open image externally" replicates the unit drive bug: it works for images stored in `C:\` but not in `E:\`.

**P.P.S.**

I love the new image preview that lets you change the image footer visually. The GUI is quickly approaching an interface that I could recommend to non-technical users accustomed to WYSIWYG editors! In fact I introduced it to two semi-technical co-workers and they barely complained at all ;-)

**Comment by nathanlesage** [comment]
This sounds weird; the 2.0 line actually relies much more heavily on Pandoc and as far as I know that should pose no problem to find images relative to a Markdown file. I definitely have to investigate that one!

If someone already has an idea where this problem might stem from, please step forward!

**Comment by dialmove** [comment]
Is there a way to see the generated Pandoc command line? I could check what's going wrong with the paths and try to find the way to fix it

**Comment by nathanlesage** [comment]
@dialmove Thank you very much for your extensive testing!

The good thing is, one can specify `resource-path` in the defaults files: https://pandoc.org/MANUAL.html#default-files

This means that any one can fix this problem by opening File -> Preferences -> Assets Manager -> Export -> Docx -> and add a field `resource-path` (make sure the YAML syntax is right).

However, I'm keeping this open because I know that splitting hard drives is absolutely common on Windows so I think we should document that somewhere … do the FAQ make sense…?

**Comment by dialmove** [comment]
I've been trying some tests, and adding the `resource-path` parameter is not enough. I cannot make images work when launching pandoc from Zettlr. 

This parameter helps when the .md contain relative routes, as in my first tests that link directly to `\myChapter1\chapter1.md` or `E:\_Temp\Mobile\Field op\View-manager.en.md`. Internally, these files have relative paths to the \media folder and its images, and `resource-path` is enough to point pandoc to the correct route.

However, the temporary `export.md` that you generated in earlier versions contains absolute routes, not relative. I've managed to capture its contents, and I can create the correct Word file with images with this command from the command line:

    C:\Users\Usuario>pandoc "E:\_Temp\Manuales-EN\export.tmp" -f markdown -t docx   --toc-depth=2   -s --pdf-engine=xelatex --mathjax -o "E:\_Temp\Manuales-EN\Manuals.docx"

It finds the right path to images because it is encoded in the .tmp file:

    ![Resources operations](E:\_Temp\Manuales-EN\02-Master-data\2.01-Resources\media\Resources_Operations.png)

However, the same exact command creates a broken Word file when launched from within Zettlr, as documented by the log:

    [19:48:35] [Info] Running Pandoc with command: pandoc "E:\_Temp\Manuales-EN\export.tmp" -f markdown -t docx   --toc-depth=2   -s --pdf-engine=xelatex --mathjax -o "E:\_Temp\Manuales-EN\Manuals.docx"
    [19:48:36] [Info] [WATCHDOG] Emitting event: change:E:\_Temp\Manuales-EN\Manuals.docx
    [19:48:36] [Info] [WATCHDOG] Emitting event: change:E:\_Temp\Manuales-EN\Manuals.docx
    [19:48:36] [Warning] Pandoc ran successfully. However, there were warnings and/or additional output. | Details: {"stdout":"","
          stderr":"[WARNING] Could not fetch resource 'E:_Temp\\Manuales-EN\\02-Master-data\\2.01-Resources\\media\\Resources_Operations.png': PandocResourceNotFound \"E:_Temp\\\\Manuales-EN\\\\02-Master-data\\\\2.01-Resources\\\\media\\\\Resources_Operations.png\"\r\n[WARNING] Could not fetch resource 'E:_Temp\\Manuales-EN\\02-Master-data\\2.01-Resources\\media\\manager_resources_view.png': PandocResourceNotFound 

So, there's something odd with the environment where pandoc is run, and it's not just the `resource-path` command. The difference seems to be that the unit drive isn't being transferred to the path (pandoc needs to have double backslash `\\` in Windows path files internally).

As before, I couldn't generate a Word file with images in version 2.0.0beta3; and I can't see what pandoc command line is being used because it no longer shows in the log file.

**Comment by nathanlesage** [comment]
> I can't see what pandoc command line is being used because it no longer shows in the log file.

There's always this command being executed: `pandoc --defaults-file=/link/to/the/defaults.yaml` Everything is specified in the defaults file, we're not doing anything on the command line anymore. Plus, you can fully configure Pandoc within default files, so that's not a problem, and the solution lies somewhere in the defaults file options, I think.

**Comment by dialmove** [comment]
Ok, several things.

Short story: `resource-path` somewhat helps, but it's not the root cause of the problem. To fix the bug I suggest:

a) generate the temporary `export.tmp` file (the file combining the contents from all .md files in the project) with a path prefix for images, relative from the root project folder, including long subpaths prefixes for images stored in subfolders of arbitrary nested depth. 

(Also please add an option to make that `export.tmp` visible and persistent, so that we can debug the pandoc command required to make generation work. I will be tied to version 1.8.9 until this bug is fixed, or at least until I can get this `export.tmp` file with version 2.0.0).

b) call pandoc with an explicit --resource-path line parameter (in addition to the --defaults), with a path value configurable per-project, defaulting to the project root. Adding this parameter to the `defaults.yaml` file means that we have to edit its value for each different project we want to generate, every time we switch projects.


Long story:

1) I'm using pandoc 2.14.2 and the parameter for the default file is named `--defaults`. If you're using `--defaults-file`, probably the runtime isn't locating the `defaults\export.docx.yaml` file.

2) Is it possible to read a log with the pandoc output?  The warnings and errors are most informative about what's going on in the export process.

3) Is it possible to generate a persistent `export.tmp` file with the combined contents of all .md files in the project? I'd like to check what routes the images are pointing to. I strongly suspect those contents, and not the `resource-path`, are the reason why I can't create Word files with images from within Zettlr but I can create them with pandoc from the command line.

#### Generating a single file

I've managed to generate a correct file with pandoc using only the defauls.yaml file with the following command, where the `\media` folder is directly under the 04-Planning folder:

    C:\Users\Usuario>pandoc --defaults="C:\Users\Usuario\AppData\Roaming\Zettlr\defaults\export.docx.yaml" 
        -o "c:\Temp\Manuales-EN\04-Planning\planning.docx" "c:\temp\Manuales-EN\04-Planning\planning.md"

including in `export.docx.yaml` the following parameter :   `resource-path: ['C:\temp\Manuales-EN\04-Planning']`

But, the file generated within Zettlr from a project in `C:\temp\Manuales-EN\04-Planning` is created without images, with the same parameter in export.docx.yaml.

#### Generating a whole project

To create a Word for the whole project, I use this command:

     C:\Users\Usuario>pandoc --resource-path=C:\temp\Manuales-EN  -o "c:\Temp\Manuales-EN\Manual.docx" "c:\temp\Manuales-EN\export.tmp"

where `export.tmp` is the project file generated with Zettlr 1.8.9, manually editing its contents so that image is prefixed with the relative path to its subfolder, starting from `c:\Temp\Manuales-EN`. For example images for chapter 04-Planning have this format:

     ![Day edit actions](04-Planning\media\F1301-Edit-float.en.png)

This generates the Word with all images, even if resource-path is not included in the `defaults.yaml` file.

The key reason why my files are missing images is because pandoc can only find images relative to its working directory, not relative to where the .md containing the route is placed. So, flat hierarchies with no subfolders are not a problem as long as you can point pandoc to the correct directory. But nested folders need to have their relative paths correctly inserted in the compiled `export.tmp` file before passing them to pandoc. 

I assume you were adding image routes as absolute paths from the root folder, but that's what caused it to fail when switching drive units. Adding them as relative paths from the project root would be more robust and easier to make pandoc work.

Last but not least, I think parameter `shift-heading-level-by: 0` would be a better default for the Word default. Now the Word title is being generated from the last file with a #1 heading (usually the last chapter in the book), but with this parameter set to 0 it uses the project title.

That's all, thanks for your time! Keep going with this wonderful software, it already has revolutionized the documentation workflow at my workplace.

**Comment by nathanlesage** [comment]
Thank you for the detailed response. I'm beginning to suspect the reason is more how I construct projects. There's still something different than for exporting regular files, so I might've actually created a bug there. @Kangie I know you also have some insight into the exporter, do you have an idea?

If we didn't put a bug into the exporter, then there might be a bug with Pandoc in that it SOMEHOW differentiates between a resource-path given on the command line as opposed to a defaults file. Otherwise, I simply cannot explain this.

**Comment by Kangie** [comment]
I'll try and take a look tomorrow. Nothing immediately comes to mine!

**Comment by dialmove** [comment]
Can you point me to what source file(s) participate in the process to export a project? I could take a look at the code and see what logic is being used, to find out what assumptions it makes that my project structure does not meet.

**Comment by nathanlesage** [comment]
> so definitely there are some Windows character encoding settings shenanigans messing up the correct path before it reaches the external program.

That's what you get when you use escape characters as path delimiters 😐 But well, at least we're slowly circling around the problem …

**Comment by nathanlesage** [comment]
Pandoc can now be completely customized from within Zettlr, so there's nothing more I could do.
