### ISSUE TITLE
Close non-saved file dialog cannot Save file [Bug] 

### ISSUE THREAD

**Issue by derwok** [Zettlr/Zettlr#2340]
### Description

With a unsaved edits, when you press Ctrl (Cmd)+W to close an unsaved file, this dialog appears:
<img width="524" alt="grafik" src="https://user-images.githubusercontent.com/4393698/130226337-74dd5115-ca46-4493-9ec5-89b0439abaa2.png">

The button **"Save"** here seems to be broken in two aspects: When I click it, the file is not saved and the file stays open. In the log I can find this: `[Command] Not closing file, as the user did not want that.`

### Reproducing

Make an edit and hit Ctlr/Cmd+W prior to auto-save kicking in

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.2 (2.0.0-beta.2)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS Mojave 10.14.6 (18G9028)

### Additional Information

Autosave works again! Hooray! :-)

**Comment by nathanlesage** [comment]
Ah, I fixed that for closing everything, not for individual files. Missed that one.
