### ISSUE TITLE
[FEATURE REQUEST] More option in notes management

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#235]
Sorry for the title if it is misleading, but I thought it will cover the two issues. 

As 1.3 is behind, I was thinking if it will be possible to have more possibilities in notes management: 
1. **To *duplicate* a note** (using a copy/paste mechanism or another combination) -- sometimes I like to use some notes as drafts for other notes (I know it can be done using select all text > new note > paste, but it is a little bit tedious)
2. **To select and move / copy multiple notes**. The move feature is just amazing and it is easy to create new projects from old ones, but sometimes it is too slow if you want to move notes from the same folder.

Thank you for the great job and I can't wait for the new *goodies* in the 1.4 betas...

**Comment by nathanlesage** [comment]
The duplication issue is something that bugs me as well, but there were too many bugs in the previous version that needed to be addressed first. It'll definitely come. As to the moving and copying of multiple notes: There's been an issue on the forum asking whether it's possible to export multiple notes in one batch by selecting them. Including such a selection will require some intensive work at the core of Zettlr, so it'll take some time!

**Comment by samarulmeu** [comment]
Thank you for taking into account my proposals (I missed the forum entry about multiple files selection). I imagined they were not so easy to implement that's why I waited for the release of the stable 1.3 version before mentioning them.

**Comment by nathanlesage** [comment]
File duplication: ✅
