### ISSUE TITLE
Citations broken in text [Bug] 

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#2351]
### Description

When starting Zettlr, alerted:

![image](https://user-images.githubusercontent.com/44082853/130597115-55c8cd6f-796b-4537-b1a1-98aa533c2e74.png)

When performing a search for a citation, nothing shows. Writing a correct Citekey does not show as a citation:

![image](https://user-images.githubusercontent.com/44082853/130598016-88813d4e-1e41-47de-8fa3-d7abc44ea443.png)

However, exporting creates the correct citation (as correct in the bibliography):

![image](https://user-images.githubusercontent.com/44082853/130598194-5c4c0b5b-0fb1-40e9-9790-8703c7fc6cd8.png)

![image](https://user-images.githubusercontent.com/44082853/130596801-a1fc0932-3bb4-4155-b70b-f986e9dd4f07.png)

### Reproducing

Start Zettlr, open new file and type '@' to search for reference.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian Bullseye

**Comment by break6700** [comment]
I have noticed this issue does not occur when using a CSL JSON file but does with a BIB file.

**Comment by nathanlesage** [comment]
I just found the bug and fixed that in this commit: https://github.com/Zettlr/Zettlr/commit/81f687f6f0ca3de96893992fbb1f52e28bb2b6d2

It was a signature change that slipped my eyes because I don't use BibTex myself, just CSL JSON. It should work beginning at the next nightly (Monday) and beta (sometime after that)!
