### ISSUE TITLE
Add option to have non-overlapping sidebar

### ISSUE THREAD

**Issue by schlichtanders** [Zettlr/Zettlr#2353]
### Description

The current sidebar just overlaps the editor pane, so that one cannot easily work and sametime look at information in the sidebar.

### Proposed Changes

Add an option in the settings to make the sidebar non-overlapping.
Decide for a default value (I would think non-overlapping is more intuitive for most users)

### Caveats

no caveat found yet

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Nixos 21.05

### Additional Information

![image](https://user-images.githubusercontent.com/4255480/130624843-88eb77d4-7d8c-400e-aa09-c41e6e1e9244.png)

**Comment by nathanlesage** [comment]
Didn't like that myself, and it's already changed for 2.0! You can safely switch to the current betas!
