### ISSUE TITLE
[Bug] Character count with and without spaces equal

### ISSUE THREAD

**Issue by Wietor-bb** [Zettlr/Zettlr#2355]
### Description

Character count present equal values for without and with spaces (in prefs. option Count characters instead of words set to none).  Without spaces value is correct.

### Reproducing

![obraz](https://user-images.githubusercontent.com/70803464/130667310-20f02365-7b6d-4e5b-ba7c-0872d7a5f270.png)

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Does this also happen on the most recent beta 2.0?

**Comment by Wietor-bb** [comment]
Unfortunately, in 2.00 beta.3 – no changes.
In example on screenshot the real value (with spaces) should be 5696 (according MS Word counter):

![counter-beta](https://user-images.githubusercontent.com/70803464/131962017-3f49b234-71a7-4843-b19a-b3e6cb08114d.jpg)

In Prefs option <kbd>Count characters instead of words</kbd> is unchecked.

This bug make the <kbd> Set writing target</kbd> function unusable. In my country, setting the target of writing in the number of characters with spaces (instead of words) is the editorial standard.

**Comment by nathanlesage** [comment]
Thanks for confirming, will have a look!

**Comment by Wietor-bb** [comment]
In beta 2.00 beta 4 still the same error

**Comment by nathanlesage** [comment]
@Wietor-bb Yes, and the error will remain until this issue is closed. A closed issue indicates I have been able to write a fix!

**Comment by nathanlesage** [comment]
Please don't ask me what I did with that function, but it was an utter mess. Should work better now!

**Comment by LegonEtp** [comment]
I hope so. I wrote too long texts because of this. 👍
