### ISSUE TITLE
[Feature] Multiple Instances and "Projects"

### ISSUE THREAD

**Issue by schlichtanders** [Zettlr/Zettlr#2358]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Hi at [the forum](https://forum.zettlr.com/discussion/99/how-to-start-2-instances-of-the-app) it is mentioned that Zettlr is currently envisioned to be a single instance app. I want to encourage rethinking this idea because of the following reasons:

- when using zettlr as a zettelkasten it can appear that you want multiple sessions open, one for business, one for private for example.
- another usecase is to use zettlr as an ad-hoc markdown editor. Here you may want to leave your current setup in place, but just open a separate zettlr for quick editing which you can then close again afterwards.

Currently I have to use typora or marktext or vscode instead of zettlkasten to do so.

### Why reusing a central zettlr session is not an option
- you may want to use the different instances on different virtual desktops, screens, activities
- you may want to have different window sizes and positions for the different instances
- you may want to have both instances on the same desktop next to each other

### Essentially needed additions for zettlr.
- In order to be able to reopen a specific session like business, a meta-workspace concept, lets called it "project" would be needed
- the workspaces, tag management and all other config could be shared among projects, only the folder selection and open files would differ
- alternatively each project could also have individual workspaces, however I wouldn't prefer this right now, as I like the feeling of one global zettlr which the sharing of workspaces would enable.

### Example Workflow

launching Zettlr a second time will open a new blank Zettlr

it would be nice to have the option to load an existing Zettlr "Project" by clicking on some button in a summary-user-interface

### Caveats

you may loose the convenience that when starting zettlr your last setup is restored,
however this should be the case if you have multiple projects, and it is ambiguous which project to load

if there is only one project, the current zettlr behaviour could be retained
if there are multiple it may be best to start with an empty zettlr and a list of loadable "projects"

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
I'm playing with this idea since the state management of Zettlr is more and more getting to where this is a real possibility. Right now, it's impossible to create multiple windows since the internal state cannot cope with that. But it's getting there. However, since there are still many, many changes necessary, I cannot give you any ETA. (Of course, the more help I get in fixing bugs and implementing enhancement and feature requests, the faster it goes.)
