### ISSUE TITLE
[Question] How to open a single file?

### ISSUE THREAD

**Issue by dengue8830** [Zettlr/Zettlr#236]
I can't just open a single file, i'm only able to open folders.

This is a problem because i have my `.md` file in my root project file and in the same level there is `node_modules/` so if i open the root project folder the file watcher goes crazy with `node_modules/`

Env: Mac, installed via homebrew

**Comment by nathanlesage** [comment]
Single files can easily be opened by double clicking (or right-click -> Open With...) in your file browser or dragging them onto the app. Zettlr is made for working mainly with directories, so there‘s no dedicated menu option!
