### ISSUE TITLE
[Bug] White Scrollbar when Night Mode is on

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#2361]
### Description

White Scrollbar when Night Mode is on

See on this screen shot: [https://imgur.com/a/Qc2rAbu](https://imgur.com/a/Qc2rAbu)

### Reproducing

1. open folder with enough files that the scroll bar is visible
2. select night node

### Zettlr Version

Beta (if applicable)

### Specify version

Beta 3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro Linux, i3, packages up to date.

**Comment by nathanlesage** [comment]
This is the native scrollbar, right? And your operating system is not in dark mode? If so, we might be able to mitigate this using CSS.

**Comment by tscheims1** [comment]
Thank you for your response. Yes, this is my default scroll bar and my system dont have dark mode. (on zettlr 1.8 the scroll bar is black and does not distract)

**Comment by Atulin** [comment]
Just gonna chime in and say it's an issue on Windows 10 as well

**Comment by djsime1** [comment]
On Windows at least, it is not possible to customize the scrollbars with CSS. Attempting to change the width using
```css
::-webkit-scrollbar {
    width: 3px;
}
```
causes all scrollbars to disappear completely. I remember reading somewhere that this application now uses native components, so I guess that includes the scroll bar.

**Comment by nathanlesage** [comment]
> I remember reading somewhere that this application now uses native components, so I guess that includes the scroll bar.

No, the idea with a webkit-scrollbar property is in fact right. But you need to add more properties (there are actually quite a few that let you customize the scrollbars).

Zettlr doesn't really use "native components" as the term might imply. Rather, it uses CSS to mimick the native look and feel as close as possible.

**Comment by nathanlesage** [comment]
Fixed. Please take a moment to check if the scrollbars look correct now. Since macOS doesn't provide scrollbar buttons (the up and down ones), it might be that that style is still somewhat weird. Please feel free to check that.
