### ISSUE TITLE
Assets Manager menu is weird [Bug] 

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#2364]
### Description

5th item from the top is messed up. 4th is overflowing.
![image](https://user-images.githubusercontent.com/63842998/131214802-58b7b6ea-8836-4098-8bf9-87ce2e40f5a1.png)

### Reproducing

Open assets manager.

### Zettlr Version

Beta (if applicable)

### Specify version

beta-3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Ahh, one's gotta love CSS. Thanks for reporting!
