### ISSUE TITLE
[Enhancement] Add Setext-header detection for file-representation

### ISSUE THREAD

**Issue by petesimonic** [Zettlr/Zettlr#2372]
### Description

it's an awesome feature to show first heading-1 instead of the filename
but when you use `==` heading as title for the file, then it gets dropped
Zettlr "doesn't see it"

Feels like it sometimes "read" it as H1, but mostly not. Will try to test more thorough, if it would be helpful. 

### Reproducing

start the file with 
```md
heading
========
Lorem impsum...
```

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

`Linux pop-os 5.11.0-7620-generic #21~1626191760~21.04~55de9c3-Ubuntu SMP Tue Jul 20 22:18:55 UTC  x86_64 x86_64 x86_64 GNU/Linux`

**Comment by nathanlesage** [comment]
This is due to the fact that Zettlr in most places only detects ATX-headers (the ones with the hashtag-signs), and not Setext-headers (the underlined ones), as the latter are much more difficult to detect.
