### ISSUE TITLE
[Enhancement] Pretty print code block with emphasis on language

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2376]
### Description

Right now, the markup annotations for markdown are semi-hidden in a dim color. For code-blocks, this includes the backticks and the language name. For the user, the language name might not be a mere annotation, but can be relevant information. It makes sense to communicate this more clearly.

### Proposed Changes

If we could css-select the code block language string separately from the backticks, we can style the language to be more clear in themes and in custom css.

### Example 

Mockup:
![image](https://user-images.githubusercontent.com/1702193/131270410-cdc38744-cbe9-494e-b60d-b04bf83e066a.png)

### Additional Information

To close this issue satisfactory, the language needs to be css-selectable and the themes must be updated to make use of this by using a brighter color for the language.

---

Backlinks: #2369

**Comment by nathanlesage** [comment]
(Note: Not adding this to the 2.0 project, since the amount of necessary code-changes is out of scope for the stable 2.0. Will be added after 2.0 release)

**Comment by nathanlesage** [comment]
Works in the current nightly!
