### ISSUE TITLE
[Enhancement] [2.0] (Option to) hide markup annotations for italics and bold

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2377]
### Description

Implement **an option to** hide the markup annotations for markdown italics and bold. It is a popular recurring request.

> :information_source: Zettlr already behaves in a similar way for urls/links and - to a more complex degree - tables.

This would make behavior for italics and bold similar to that of links, where you only see the markup annotations while the cursor is in the relevant position.

__Update:__

- `__bold__`
- `*italics*`
- `inline code`
- `~~strikethrough~~`

### Additional Information

@nathanlesage [commented](https://github.com/Zettlr/Zettlr/issues/2243#issuecomment-908289469):
> The functionality is already in Zettlr, funny enough. I just need to expose a setting to actually enable it. If you didn't know: I did write an experimental WYSIWYG-mode two or three years ago, but never opened it to the public :D

---

Backlinks: #2243

**Comment by Redsandro** [comment]
Inline  `backticks`! 

Should we include the markup annotations for `inline code` to the optional hide?

**Comment by nathanlesage** [comment]
Mh, since both are semantically the same (delimit code) this could be done in one option, yes

**Comment by Julianoe** [comment]
Hi! I'm a daily user of Zettlr as I use .md notes for pretty much anything. But like @Redsandro describes in issue https://github.com/Zettlr/Zettlr/issues/2243 I tend to cheat on Zettlr for more "slick" softwares when I need to have a "bloat-less" view of my content. For writing long form among other use cases. Typora is the one these days.

Wouldn't it be possible to dynamically add classes to the CSS of an element when cursor is on the relevant position to show the markup like "active". This way it would allow anybody to define what it looks like in the CSS easily? I guess that's how other tools do it.

Anyways, I'm all for the addition of that option! :D 

ps: don't forget ~~the slashed texte too ;)~~

**Comment by nathanlesage** [comment]
Ouh, I just implemented that! Just not strikethrough … but I can add that real quick

**Comment by Redsandro** [comment]
@nathanlesage sweet, I've been looking forward to this one!

It is not in today's 2.2.0 release yet, correct? Or am I looking in the wrong place to enable this option?

**Comment by nathanlesage** [comment]
Nope, it's coming with 2.2.1! But that should take at most a few days!
