### ISSUE TITLE
[Enhancement] [2.0] Pressing Ctrl+Alt+, a second time should hide the asset manager.

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2379]
### Description

I notice that it's a bit tedious to navigate the menu to go to the Custom CSS page. Especially when making refinements and you go to that menu dozens of times. 

### Proposed Changes

Create a keyboard shortcut for opening the CSS editor (and mention that shortcut on the themes page). That would really make it easy for people to take a look.

---

Backlinks: #2243

**Comment by nathanlesage** [comment]
I still don't quite see why we need to add a keyboard shortcut: You can simply keep that window open – as soon as you save the changes they will be applied immediately, so you can keep the window open until you're satisfied?

**Comment by Redsandro** [comment]
> You can simply keep that window open – as soon as you save the changes they will be applied immediately, so you can keep the window open until you're satisfied?

Not on Linux. Or has this changed recently? For me, the screen is stuck/immovable in the middle of the screen (so you can't move it to the side) and once you click 'save' it closes.

Either way, _even if_ it was a separate window, once you're nitpicking to get the perfect theme, you'll still end up opening that screen multiple times per day for the rest of the week. What is the harm in adding a keyboard shortcut? I'd recommend <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>,</kbd>

In my subjective perfect world, every conceivable action has a keyboard shortcut, and we never have to search for the action in a menu.

**Comment by nathanlesage** [comment]
> For me, the screen is stuck/immovable in the middle of the screen (so you can't move it to the side) and once you click 'save' it closes.

What 😳 This should **not** be the case. The assets manager should, in fact, be a completely separate window which you can move to the side. This very much sounds like a bug!

> you'll still end up opening that screen multiple times per day for the rest of the week.

And after the week you won't do this, so this is still kind of a weak argument for doing that, isn't it?

> In my subjective perfect world, every conceivable action has a keyboard shortcut, and we never have to search for the action in a menu.

That, however, sounds more like one. As far as I remember this is also somewhere in the HIGs. Hmm.

**Comment by Redsandro** [comment]
### :warning: Deprecated by https://github.com/Zettlr/Zettlr/commit/2e584f8a384930a1ac32115e2b12038a97f6918b 
### although pressing `Ctrl+Alt+,` a second time should hide the window.

**Comment by nathanlesage** [comment]
> although pressing Ctrl+Alt+, a second time should hide the window.

This is not the default behavior on at least macOS, and I'm pretty sure on Windows as well. I want Zettlr to closely follow the behavior of other native apps on the respective platforms.

**Comment by Redsandro** [comment]
Gotcha
