### ISSUE TITLE
[Enhancement] [2.0] Add helpful text to themes page

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2380]
### Description

Below the theme icons, on the preferences page, I recommend putting a short text that describes the theme. It prevents people from making the wrong assumption thinking only the font differs and the color changes in hue. 

Also, make it as easy as possible to open the CSS editor from there, to tempt people to tinker.

### Proposed Changes

Add a characteristic feature that you were going for when creating the template. For example, under "Bordeaux" a text could say something like _"Minimalist and monospaced."_

Put a reminder that further refinements can be made with Custom CSS. Mention the keyboard shortcut to open the CSS editor (#2379), and add a link to the css documentation.

---

Backlinks: #2243

**Comment by nathanlesage** [comment]
Feel free to already elaborate some suggested wordings which we can then discuss and finally merge into the translations!

**Comment by Redsandro** [comment]
**Berlin:** Clean and green, designed for a screen. Sans.
**Frankfurt:** Oldschool with serifs. Looks on in High DPI screens.
**Bielefeld:** Orange monospaced and extra thicc for readability.
**Karl-Marx-Stadt:** Berlin with a more socialist color.
**Bordeaux:** Bielefeld with less colors, for readability.

(PS - Yaml frontmatter remains green in every theme.)

**Comment by nathanlesage** [comment]
> (PS - Yaml frontmatter remains green in every theme.)

This should be by design, since it's a syntax highlighting theme. Have to double check. Other than that, I laughed a little bit with the pun in the Berlin description ;D

**Comment by Redsandro** [comment]
The latest dev seems to have a simple dropdown for themes in stead of the 1.x theme icons page.

Not sure if by design or due to Electron on Linux.

**Comment by nathanlesage** [comment]
> Not sure if by design or due to Electron on Linux.

By design. I figured that might be nicer. But I'm also thinking that reinstating the old theme previews might be cool.

**Comment by nathanlesage** [comment]
@Redsandro What do you think of this?

![image](https://user-images.githubusercontent.com/17251683/135285561-ed65aadd-671b-4f7a-95c2-02305afc98f0.png)

**Comment by Redsandro** [comment]
@nathanlesage looks very nice. I prefer this over the dropdown.

**Comment by nathanlesage** [comment]
Perfect, then I consider this issue closed, because I already added this to source! :)
