### ISSUE TITLE
[Enhancement] [2.0] Add commented-out examples to Custom CSS page

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2381]
### Description

Tempt people to tinker with custom CSS.

### Proposed Changes

Apart from adding a keyboard shortcut (#2379) and mentioning it on the themes page (#2380), by default, upon opening the CSS editor for the first time, there could be some basic examples (commented out of course) so the user is tempted to uncomment them and alter them.

---

Backlinks: #2243

**Comment by nathanlesage** [comment]
Interesting idea, but I think that should be a discussion, since the actual change then would just incorporate copying and pasting the successful examples over to the Custom CSS page!

Moving …
