### ISSUE TITLE
[Enhancement] Filter and Open Files in Quicklook from the Search Results 

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2382]
### Description

My workflow for outlining and writing articles in 1.8.9 heavily relied on searching using an ID, then filtering that list and opening notes in Quicklook view.  In 2.0 the search results are separate from the file browser so I can no longer do this.

To expand that a bit, what I do when I'm writing an article is take a whole bunch of individual notes in separate files, in each note I link to an outline file.  In the outline file I have a list of links back to the notes.  As I go I move around the links in the list into clusters – an outline.  Then when I come to write I want to open up all the notes from a cluster that'll become a paragraph in Quicklook, and work my way down the stack of "cards" typing my paragraph of the article based on what it says in those notes.  My mental model of this is based on when I was using a paper index card based system – each note was on a card, I laid the cards out on the table and moved them into an order, then put the stack in order next to my computer and started typing and working my way through the stack.

In 1.8.9 the easiest way to do this was to search for the ID of the outline note which would do a first stage filtering of the file browser for relevant notes, then optionally use the filter to narrow it further if I couldn't just spot the right note, and then right click to open in Quicklook.  I used Quicklook because it's the only way to display two notes side by side, one that I can type in and one that I'm looking at to see what I want to type.

In all the 2.0 betas I can't do this, because the search results aren't the same as the file browser.  I'd like to be able to open a file in Quicklook directly from the search results, and preferably also filter those search results.

### Proposed Changes

Have a right click menu in the search results that lets me open a note in Quicklook.

Preferably also be able to filter the search results to only display a subset of them (as you can in the filebrowser).

### Caveats

It might interfere with whatever right click already does in the search results? It seems that right clicking just opens a note like left clicking does but maybe there is some nuance I haven't spotted!

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 20.04

**Comment by nathanlesage** [comment]
Would it suffice to add a context menu to the search results that don't just allow you to open these in the main window but also in Quicklook windows? Because I wanted to add a context menu either way, and this would just be adding a single more item to that. Then this should work again!

**Comment by nathanlesage** [comment]
Puhh … I don't think so, Zettlr will always search EVERYTHING. But certainly discuss-able, so feel free to open one.

**Comment by nathanlesage** [comment]
Quicklook is in ✅

**Comment by mousetrappling** [comment]
Awesome :) Thank you!
