### ISSUE TITLE
[Bug] Cursor navigation & text highlighting faulty under certain conditions

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#2388]
### Description

The cursor does not navigate or highlight text properly in response to hotkey commands, in paragraphs that contain certain types of characters.

### Reproducing

**NOTE:** I've experienced this but while the following box was unchecked, in preferences: _Use the CodeMirror default actions for `Home` and `End`_

**In a paragraph that begins with a bolded word or phrase**

If the cursor is at the end of a multi-line paragraph that begins with a bolded phrase, then pressing `Shift + Home` will not highlight the current line and bring the cursor to rest at the beginning of line. Instead, the cursor will merely come to rest between the first and second * of that paragraph.

**In a paragraph that occurs within a bullet point or ordered-list item**

If the cursor is at the end of a multi-line paragraph within a bullet point, pressing `Shift + Home` will not highlight the current line and bring the cursor to rest at the beginning of line. Instead, the cursor will merely come to rest at the beginning of the paragraph, just following the bullet point or ordered-list item number.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I think I fixed that bug with my revamp of the function – feel free to complain if that didn't fix it!

**Comment by noah-arroyo** [comment]
@nathanlesage I've installed beta.5, and _the bug lives!_ Though it has morphed a bit.

### The good

Hitting `Shift + Home` will successfully highlight text. Yay!

### The bad

The cursor still jumps to the beginning(ish) of the first line of a multi-line paragraph, even if the cursor began on a different line. Specifically: 
- **In a paragraph within a bullet point,** the cursor and highlighting come to rest after the bullet and the space separating bullet from text.
- **In a paragraph wherein the first word is bolded,** the cursor and highlighting come to rest after the first `*` of the double-asterisk markdown.

**Comment by nathanlesage** [comment]
Grrrrr 😡

Okay, just had a second look at how CodeMirror does its smart line go-commands, and I found out they're cheating: They have access to some very deeply hidden helper functions that help them to discern the _visual_ lines. So I guess what we need to do is just execute those commands and check where the cursor ends up. If it's in front of a bullet point, back the cursor up to after the bullet point, otherwise continue. (And, also make sure that the cursor was farther back before executing the command so that the user will end up at the actual beginning of the line after repeating the command)

**Comment by noah-arroyo** [comment]
@nathanlesage Thank you for fixing this!

(I've just downloaded latest ver., 2.2.1, and confirm that this bug is toast.)
