### ISSUE TITLE
Couldn't add correct russian number delimeter

### ISSUE THREAD

**Issue by maxtar** [Zettlr/Zettlr#239]
In Russia as number delimiter using space. But I couldn't add it to translate because it just removed after save.

**Comment by gritty-gitty** [comment]
> In Russia as number delimiter using space. But I couldn't add it to translate because it just removed after save.

Use [Unicode Character 'NO-BREAK SPACE' (U+00A0)](https://www.fileformat.info/info/unicode/char/00a0/index.htm) instead.
That one will be saved as 

> "thousand_delimiter": "\u00a0"

**Comment by maxtar** [comment]
@gritty-gitty Hm, will try. Thank you.

**Comment by nathanlesage** [comment]
Yes, the input is sanitised in the system, therefore you'll need the non-breaking space. It's the same issue as with the French translation, where we're using this character as well!
