### ISSUE TITLE
Preview task list as checkboxes

### ISSUE THREAD

**Issue by enteropositivo** [Zettlr/Zettlr#24]
This is for a new Feature.  

When writing taks list 

```
- [ ] Buy milk
- [x] Buy bread
- [ ] Buy eggs
```

Would be great to preview it as checkboxes that we could check/uncheck only by clicking each task

- [ ] Buy milk
- [x] Buy bread
- [ ] Buy eggs

**Comment by nathanlesage** [comment]
Alright; I haven't done this yet because I wasn't using these. I'll see to implementing it in the near future!
