### ISSUE TITLE
[FR] back and forward actions (keyboard)

### ISSUE THREAD

**Issue by filipgoc** [Zettlr/Zettlr#240]
## Description

As I am using Zettlr more and more, the features I'm really missing are starting to become apparent.

One of them is clearly the inability to go to the previous page and then back forward. Like in a web browser. The lack of this feature makes me fearful to exit the page I'm editing. This is not a big deal if Zettlr is used for long-form writing, but it is a big deal for Zettelkasten. I need to be able to be jumping around my notes fearlessly. 

In fact, the way I work now is I have Zettlr _and_ VScode open at the same time.  I use Zettlr for longer-form writing, and VScode for opening other files I need... 

I know I'm not the first one requesting this. 
(https://github.com/Zettlr/Zettlr/issues/50, https://github.com/Zettlr/Zettlr/issues/165
https://github.com/Zettlr/Zettlr/issues/58... )

I am just adding my voice to the crowd to illustrate the importance and possibly bump up the priority.

**Comment by nathanlesage** [comment]
I don‘t see the problem — Zettlr always saves everything on note-switching so there‘s no loss and there‘s Cmd/Ctrl-Number for switching quickly back between the notes!

**Comment by filipgoc** [comment]
Oh that's very interesting.
I did not think of using Recent Documents as a sort of back and forth. 
It's mentally different, but it shouldn't take long for the brain to adjust. 

Basically ctrl+2 will keep switching between two docs. Perfect!
Thanks.

**Comment by nathanlesage** [comment]
You're welcome!

**Comment by clozach** [comment]
This seems worth reopening to me. Thanks to the ubiquity of web browsers, a linear browsing history accessed through `back` and `forward` commands is universally understood. As a new user exploring Zettlr, I've already spent 20 minutes scouring the UI, documentation, and finally Google just trying to figure out how to see recently-visited documents.

The Recents List is good to know about, but several things make it frustrating to use as a mental model, not the least of which is that it's completely idiosyncratic. For one thing, the browsing order gets shuffled as one uses the ⌘1-9 & ⌘0 shortcuts. (Actually, minor point: ⌘1 seems pretty useless as the most recently-viewed doc is already in view…but perhaps there's some subtle scenario that I'm missing where it helps.) For another, this inherently limits the browsing history to 10 files.

If you want to increase the chances that new users stick with the program long enough to fall in love with it, it's probably best to throw them (us) a bone by implementing this feature. Not everyone has the patience to go Googling once something that seems so fundamental appears to be broken. 😉

**Comment by nathanlesage** [comment]
Back and forward buttons won't come because this is simply _not_ universally understood in the contexts of text documents (do you have forward/back buttons in Word? I assume no). Basically the whole back/foward-discussion was a substitute for something else that was off. Nobody needed the forward/back button thingy, rather the whole idea of Zettlr missed the ability to have several documents open at the same time.

And all of that has already been fixed; we're basically just waiting for two bugs to be solved until 1.7 can be released, containing a much more straight forward interface which'll make a whole lot more sense to all users. And all of that without back/forward buttons ;)

**Comment by clozach** [comment]
Hmm, at the risk of sounding argumentative, the comparison to Word seems pretty artificial, and it sells Zettlr short. The _key_ feature distinguishing the two isn't editor-related at all…it's link-based navigation! Given that every single one of your potential customers has been trained in the use of ←/→ buttons (with the corresponding ⌘[ and ⌘] shortcuts) thanks to the ubiquity and consistency of web browsers, you may want to think twice before dismissing this feature out of hand.

Fwiw, Notion provides a more modern and apt comparison to Zettlr. It, too, is primarily an editor, and it supports browser-style navigation on all platforms. ¯\_(ツ)_/¯

All that said, I'm looking forward to seeing the changes in 1.7. Cheers!

**Comment by nathanlesage** [comment]
Mh, yes, I don't think either that this argument is off the table, but at some point I just had to make a decision, as there were three camps forming and I can't possibly satisfy all of them at once :D We can talk about this later on again when all that's in 1.7 is settled and the app looks a little bit less cluttered in its codebase! Feel free to bring it up in autumn, after I had some well-deserved vacation =D

**Comment by khakhalin** [comment]
> Basically ctrl+2 will keep switching between two docs. Perfect!

Wait, is this still true? I've just updated to 1.8.4 (wait real long, hoping that the navigation shortcuts would settle haha), and it doesn't seem to be working, at least not "out of the box". Should I enable it somehow? Or has the key combo changed?
