### ISSUE TITLE
Render image with a link (fr or bug report)

### ISSUE THREAD

**Issue by filipgoc** [Zettlr/Zettlr#241]
## Description

Most markdown editors I know including Github support various syntax to show an image that has a hyperlink in it. 

Zettlr doesn't, or mine doesn't. 

## Reproducing

```
[![Watch the video](assets/img.png)](https://URL.com)
[<img src="assets/img.png">](https://URL.com)
```
both of these work on github, but not in zettlr

## Expected behaviour

render the pictures :-) 

**Screenshots**

![image](https://user-images.githubusercontent.com/16858474/59538622-bc156e00-8efa-11e9-854e-36bfca76796d.png)

![image](https://user-images.githubusercontent.com/16858474/59538631-c33c7c00-8efa-11e9-98c7-91db71b9dc74.png)

## Platform
 - OS: Mac High Sierra
 - Zettlr Version 1.3.0

**Comment by nathanlesage** [comment]
Should!‘t be too difficult.
