### ISSUE TITLE
[Feature] [2.0] Custom pandoc invocation

### ISSUE THREAD

**Issue by camilstaps** [Zettlr/Zettlr#2411]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

In the current 1.8.9 version, in Preferences > Advanced there is an option to change the pandoc command. I use this to add a `--metadata-file` and a `--lua-filter`. I have not been able to find this option in Zettlr 2.0.0-beta.3, so I just wanted to open this issue to check that I am not looking in the wrong place / if there is no other way to do this at the moment / that it won't be overlooked if it shouldn't be.

### Example Workflow

For example, I use the following command to add a metadata file and Lua filter:

```
pandoc "$infile$" -f markdown $outflag$ --metadata-file=/path/to/metadata.yml --lua-filter=/path/to/pandoc-ling.lua $tpl$ $toc$ $tocdepth$ $bibliography$ $cslstyle$ $standalone$ --pdf-engine=xelatex --mathjax -o "$outfile$"
```

### Caveats

N/A

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

I have tested this on Linux, but assume that it also applies on other platforms.

**Comment by nathanlesage** [comment]
In 2.0 we switched from the command line to defaults files. Default files allow you to do exactly the same as with the command line, but more cleanly and more easily. The defaults files are located in the assets manager, and there's also a link to the corresponding Pandoc documentation on defaults files!

**Comment by camilstaps** [comment]
I spent some time converting my setup to use default files, and this is a much nicer way in the end indeed!

**Comment by mcaruel** [comment]
I don’t understand how to use the default files. For instance I would like to add a —filter pandoc-eqnos’ to the pandoc command but I don’t know how to do it with the asset manager. Could someone explain it to me ?
