### ISSUE TITLE
[Feature] Using native icon packs

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#2416]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Add a setting for allowing Zettlr to use the system icon instead of the provided one to improve the consistency across the applications, especially on the Linux system.

### Example Workflow

See above.

### Caveats

See above.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
I don't know of any way of accessing the native icon sets. In general, if we can manage that, why not, but I fear that this is either not possible or, if it is, only with an extreme amount of work.
