### ISSUE TITLE
[Bug] Open- and closed-quotes fail to auto-wrap text

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#2418]
### Description

Upon keystroke for open-quotes (either single- or double-quotation marks), instances of both open- and closed-quotes _should_ automatically appear on either side of cursor / selected text. _But they only_ appear on one side.

### Reproducing

Two methods to reproduce this bug:

#### FIRST METHOD

Type the open-quotation mark = The open-quote appears. But a closed-quote mark, which should automatically appear on the other side of the cursor and lead as you type, is absent. 

**Note:** If you type the open-quote _and then do not type any characters,_ `backspace` will seemingly have no effect on first press but then delete the quotation mark on second press. This makes me wonder if the first press is actually deleting an invisible quotation mark(???)

#### SECOND METHOD

Highlight any volume of typed text and then hit the keystroke for a quotation mark = Only one quotation mark appears, either at the beginning or end of the highlighted text. 

**Note:** If you highlighted the text via keystrokes, rather than mouse-click, then wherever the cursor landed at the end of highlighting process is where the lone quotation mark appears.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Good catch, I noticed that already but was too lazy to fix it yet 👀

Only caveat:

> But a closed-quote mark, which should automatically appear on the other side of the cursor and lead as you type, is absent.

Quotes (especially magic quotes) are not the same as brackets and other auto-closing characters. I would think that most people would be weired out if … well, nevermind, having them auto-close might make sense, since the regular quotes in code also autoclose.

Will fix this at some point!

**Comment by noah-arroyo** [comment]
@nathanlesage Right, auto-close quotes is good for coding. But honestly I found this a huge time saver when writing, as I'm a journalist and every article includes numerous quotes from people.
