### ISSUE TITLE
[Bug] 2.0 Beta 3 Search & Replace ignoring Space

### ISSUE THREAD

**Issue by ludos1978** [Zettlr/Zettlr#2423]
### Description

Search and Replace does not respect a space in the search. (non regex search)

### Reproducing

have a text with line breaks copied over resulting in break- ed words.

example text:
Lorem ipsum dolor sit amet, con- setetur sadipscing elitr, sed diam no- numy eirmod tempor invidunt -ut lab- ore et dolore magna aliqu- yam erat, sed -diam voluptua. 

try to replace "- " with ""

It will also replace single dashes, and dashes without a following space.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0 Beta 3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.5.2

**Comment by nathanlesage** [comment]
I will have a look!
