### ISSUE TITLE
Better Visual Hierarchy, Contrast avoiding Visual Overload

### ISSUE THREAD

**Issue by m5x5** [Zettlr/Zettlr#2426]
### Description

I would like to suggest enhancing the contrast in the dark mode of the app, or even in general.
The reasons for enhancing contrast would be a better productivity during the note-taking process and this would also make it more accessible to users who already have problems with their eyes.

![Screenshot from 2021-09-06 17-35-21](https://user-images.githubusercontent.com/30301026/132239914-53be28e7-bd7a-4d92-ad79-8ed862f307ae.png)
![Screenshot from 2021-09-06 17-35-10](https://user-images.githubusercontent.com/30301026/132239923-152bcf34-3092-4a16-86e1-39413f882000.png)

### Proposed Changes

**Sidebar Enhancements**
- [ ] Improve contrast of folder name in sidebar
- [ ] Establish better visual hierarchy
- [ ] Remove margin at filter input box
- [ ] Better contrast for file date
- [ ] Add an option to hide properties like the file date on file left-click
- [ ] Better contrast for badges (below folder name)
- [ ] Better contrast for category name (Where it says "Workspaces" in the root folder)
- [ ] Remove margin between files and use padding instead (, or attempt to make it consistent at least)
- [ ] Make the top 5 tools glow with the theme color on hover

**Menu Bar Enhancements**
- [ ] Hide menu bar in distraction-free mode
- [ ] Lower contrast for menu bar  items

**File Edit View Enhancements**
- [ ] Only show "x" icon when tab is being hovered
- [ ] Make active tab color, and hover color softer

**General**
- [ ] Let users hide hints that appear on hover

### Caveats

Having the "x" icon only appear on the file name when we actually hover it could potentially leave people confused and prevent them from closing the tabs. Even though, I'd say that it's somewhat a standard behavior to hover over the tab name to get more details on it. Additionally, we could also think about making the "x" darker, so it doesn't conflict with other icons like the ones we have in the toolbar.

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

pop!_OS

**Comment by nathanlesage** [comment]
Am I right in that you also checked out the most recent beta based on the way your PR looks like?

**Comment by Michael55555** [comment]
I believe to have used the default branch. At the time, it was the latest state of it. 🙂

**Comment by nathanlesage** [comment]
Hmm … the screenshots look like 1.8.9. Hm, but you're on Linux. In general the Linux styles are indeed pretty bad still, because I have no Linux machine to properly adapt them and I have almost no time to deal with this unfortunately. So … if you feel up to it, please feel free to propose these changes (or anyone else reading this), because I'm not sure if I can get to that :(
