### ISSUE TITLE
[Bug] Displayed latex equations are copied as unicode

### ISSUE THREAD

**Issue by davidoskky** [Zettlr/Zettlr#2431]
### Description

Latex math equations can be highlighted and copied, however you obtain the unicode of that displayed equation and not the underlying latex expression if you start dragging from the equation.
Copying the latex expression is much more useful.

### Reproducing

- Write something containing a Latex equation
`$\theta < 0.5$: good example`
- Make sure that the equation is displayed as symbols and not as latex expression
- Click on the theta and drag the mouse until the whole line is selected and copy pressing CTRL+C
- Start a new line and paste pressing CRTL+V
- Compare the two theta, one is rendered by latex while the other one is the unicode character

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
That's interesting, I had never thought about users copying the pre-rendered stuff. Good catch!
