### ISSUE TITLE
Random scrolling [Bug] 

### ISSUE THREAD

**Issue by dctreu** [Zettlr/Zettlr#2438]
### Description

When typing in a document, as soon as typing stops, Zettlr scrolls up a few lines and hides the place I was typing.

### Reproducing

Typing.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 Home 21H1

**Comment by nathanlesage** [comment]
This is a known bug in 1.8.9, but luckily has already been fixed for 2.0. While still in beta, the betas are very stable, so you can safely use these instead of 1.8.9. Otherwise, you can wait for the stable 2.0
