### ISSUE TITLE
Some "Edit" options of the menu no longer work

### ISSUE THREAD

**Issue by monkey-sapphy** [Zettlr/Zettlr#2442]
### Description

Clicking on the menu Edit - Copy  or  Edit - Generate new ID   does not trigger any action while using the corresponding shortcut  (i.e.: Ctrl-C   or Ctrl-L ) produces the expected result.

### Reproducing

Position the cursor in a open file and then select  Edit - Generate new ID   nothing will happen.
Click   Ctrl-L   and a new ID will be generated.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 7

**Comment by nathanlesage** [comment]
This could be because of a focus problem in the menu generation, can't test this right now here (b/c there are only native menus on macOS), but it should be easy to find.
