### ISSUE TITLE
[Bug]  Don't interpret author name that contain `tag` in citation with actual `tag`

### ISSUE THREAD

**Issue by mafsi** [Zettlr/Zettlr#2446]
### Description

Trying to cite `freytag:drama`

Zettlr is interpreting any group of `tag` in citation key with normal `tag: book`

### Reproducing

Add this to your `.bib` file and try to cite the key and you will get this:

![image](https://user-images.githubusercontent.com/61430691/132940722-fd192923-d914-48fd-879c-fef602dd0c62.png)

```bib
@book{freytag:drama,
  editor    = {MacEwan, Elias J.},
  author    = {Freytag, Gustav},
  title     = {Freytag's Technique of the drama},
  subtitle  = {An exposition of dramatic composition and art},
  year      = {1969},
  edition   = {2},
  publisher = {{Scholarly Press}},
  pagetotal = {ix, 395},
  location  = {St. Clair Shores Mich.}
}
```

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Ah, yes. The reason is that citekeys are still limited to a few characters and the colon is not part of that, so Zettlr will break. If you remove the colon from the ID, it should work.
