### ISSUE TITLE
Underscore in project title causes PDF export to fail

### ISSUE THREAD

**Issue by ChristianNext** [Zettlr/Zettlr#245]
## Description
Adding an underscore '_' to the project title causes the PDF export to fail with

'Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.162 \pagebreak'

## Reproducing
* Add an underbar `_ ` to the title of a project.
* `Export Project`

## Expected behaviour
Render the project title as is.

**Screenshots**

## Platform
 - OS: Ubuntu 
 - OS 19.04
 - Zettlr Version 1.3.0
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
There you go.
