### ISSUE TITLE
[Bug] 2.0 Beta versions fail to launch on MacOS

### ISSUE THREAD

**Issue by woaidangyang** [Zettlr/Zettlr#2450]
### Description

While trying to launch the Zettlr app, it shows "Zettlr quits unexpectedly" 

All 2.0 beta version.

MacOS version: 10.13.6 (17G66)

I also tested the windows version on a PC. They are fine.

Thanks!

### Reproducing

Fail to launch

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

10.13.6

**Comment by nathanlesage** [comment]
Did you download the correct installer? For macOS there are two, one for the traditional Intel-chips, and one for the new Apple Silicon chips. The installers are labelled with the actual architecture, that is: The Intel-installers have the architecture `x64` in their filename, whereas the Apple Silicon-chips have the architecture `arm`. A good indicator to check is if the application has a white "Denied"-circle on their icon, indicating that it's the wrong architecture.

**Comment by nathanlesage** [comment]
Closing as fixed.
