### ISSUE TITLE
[Bug] Error Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#2451]
### Description

Hi! After updating to the v2.0.0-beta.3 I receive the error 

> "Cannot read property 'parse' of undefined" 

Citations are marked as missing.

My .bib file is 280kb and exported from Citavi. 

### Reproducing

Just starting the app or reloading citation database. I can also send my .bib file if necessary :)

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Yup, it was a stupid mistake I introduced into the code between beta.2 and beta.3 — I will be releasing a new beta next week, and that will contain the fix!

**Comment by halloichbingunnar** [comment]
works. thanks a lot!
