### ISSUE TITLE
[Feature] Add a second option to generate a page for the current day (yyyy-mm-dd) 

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#2458]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

It's good to have the Zettelkasten ID's, but it would be helpful to also have a second option to generate a document with the current date (yyyy-mm-dd) for writing journals.   

### Example Workflow

A simple click on the daily note will generate a document in a dedicated folder. 
 

### Caveats

a template for daily notes would help a lot

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
If you want to create a file with the format `YYYY-MM-DD.md`, the filename pattern in the advanced preferences got you covered. If not, it would be great to get some more info on what you're planning to do, since I don't really know where the problem is …?

**Comment by JJger148** [comment]
I want to generate my zettelkasten files with yyyymmddhhmm and at the same time my journal entries with yyyy-mm-dd

**Comment by nathanlesage** [comment]
Aaaaah. I'm not sure this is that easy …
