### ISSUE TITLE
[Enhancement] Allow the content of typewriter-active-line to be styled

### ISSUE THREAD

**Issue by gbraad** [Zettlr/Zettlr#2460]
### Description

At the moment it is not possible to style the content of the typewriter's active line differently:

```html
<div class="" style="position: relative;">
  <div class="typewriter-active-line CodeMirror-linebackground"></div>
  <pre class=" CodeMirror-line " role="presentation" style="text-indent: 0px; padding-left: 4px;">
     <span role="presentation" style="padding-right: 0.1px;"><span class="cm-null cm-spell-error">My text</span></span> 
  </pre>
</div>
```

### Proposed Changes

Allow the active line to be styled by adding an appropriate style class:

```html
<div class="" style="position: relative;">
  <div class="typewriter-active-line CodeMirror-linebackground"></div>
  <pre class="typewriter-active-line CodeMirror-line" role="presentation" style="text-indent: 0px; padding-left: 4px;">
     <span role="presentation" style="padding-right: 0.1px;"><span class="cm-null cm-spell-error">My text</span></span> 
  </pre>
</div>
```

this way the font color and size can be adjusted accordingly.

### Caveats

Not sure

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by gbraad** [comment]
@nathanlesage is there anything I can do for this... Where to look?

**Comment by nathanlesage** [comment]
Don't worry, see 7e55c92 for how it's done ;)
