### ISSUE TITLE
[Bug] YAML Frontmatter gets converted to table using readability mode

### ISSUE THREAD

**Issue by gbraad** [Zettlr/Zettlr#2462]
### Description

When using the YAML frontmatter and toggling to the readability mode, this gets converted to a table and the content is truncated.

### Reproducing

When using the following format for YAML frontmatter

```yaml
---
Title: Chess Not Checkers
Author: Mark Miller
ISBN: 978-1-62656-396-4
---

```

... and switching to Readability mode, this gets converted to:

```diff
----
-Title: Chess Not Checkers
-Author: Mark Miller
-ISBN: 978-1-62656-396-4
----
+Tit
+-----
+Aut
+ISB
```

This does not seem to be consistent, as after I `git checkout` the file, this does not happen again... but happens again on restart of Zettlr.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10, Mojave, Fedora 35

**Comment by gbraad** [comment]
Most likely related to https://github.com/Zettlr/Zettlr/issues/2461

**Comment by gbraad** [comment]
This is likely caused by the `----` preceding the frontmatter. However it marks it in codemirror correctly:

![image](https://user-images.githubusercontent.com/1894/133105361-0f017359-7d7d-46d9-b417-56e7906a0ce7.png)

due note it renders `--- YAML Frontmatter`

After the toggle this what remains:

![image](https://user-images.githubusercontent.com/1894/133105153-f3871275-be27-4c55-b074-99508bf857b1.png)

with this in the file:

```diff
----
-Title: Chess Not Checkers
-Author: Mark Miller
-ISBN: 978-1-62656-396-4
----
+Tit
+-----
+Aut
+ISB
```

**Comment by nathanlesage** [comment]
Mhh you indicated you use 1.8.9 – does this also occur in the betas?

**Comment by gbraad** [comment]
Will check

**Comment by gbraad** [comment]
Seems to be resolved in the latest beta (3)
