### ISSUE TITLE
Image is not displayed after export in HTML

### ISSUE THREAD

**Issue by yoyoweb** [Zettlr/Zettlr#247]
Hello,

## Description
When I export a file in HTML, I don't have the image in the HTML 

## Reproducing
Create a file
Add some text
Copy (Ctrl C) an image (resize windows appears)
The image is available in Zettlr
Then export in HTML, the page is created, but no image

## Expected behaviour
The image should be displayed.

When I link an image from the internet, then it's displayed

## Platform
 - OS: Windows 10
 - Zettlr Version 1.3.0

## Additional information
In the source code of html, i can find the img tag, and the image path. But it is written Windows like
`<img src="Y:\Documents\lionel\notes\jardinage\b859d76392154a1fd6d5ba9cdda66006.png" alt="" /><figcaption>b859d76392154a1fd6d5ba9cdda66006.png</figcaption>`

In markdown it's written like this:
`![b859d76392154a1fd6d5ba9cdda66006.png](b859d76392154a1fd6d5ba9cdda66006.png)`

Is this behaviour normal ? Can you help me ? Thanks in advance.

**Comment by nathanlesage** [comment]
Hey,

I've totally overlooked that, but you're right: The absolute path to system files must be prepended with the protocol: `file://`, which Zettlr doesn't do. I'll fix it asap!

**Comment by nathanlesage** [comment]
Gotcha :)

**Comment by yoyoweb** [comment]
Thanks for the quick fix :)
I have another question related to this one.
If I want to export my zettlr as a website, will the pictures be exported too ? 

If I export a single file, with an image local and linked relatively such as ![Un exemple de branche d'églantier](./img/eglantines.jpg), your fix will work if I open the html page on my PC.
But if I send the page on the internet via ftp, it will not work because file:// will not be found.
Is there an option (or a planed one) to export in html keeping the relative path ?
Is there an option (or a planed one) to export in html including the images ?

**Comment by nathanlesage** [comment]
Umm… the HTML export is mainly used for preview purposes. To publish real websites better use a different tool. (For instance, the Zettlr docs are written in Markdown, but for final export we use a special tool, called MkDocs, which takes care of a lot of other stuff concerning this).

**Comment by yoyoweb** [comment]
Thanks Hendrik for the explanation and the tip. Go on with this project, you really do an amazing job. Thanks for that 🥇

**Comment by nathanlesage** [comment]
You're welcome 🤗

**Comment by lucmos** [comment]
Mmmh I think I'm hitting this issue, I can only see the file name in the html:

![image](https://user-images.githubusercontent.com/11019190/81619108-1c51b000-93e9-11ea-83f0-d6ff1c805ece.png)

I'm using a relative path:

```markdown
![102847c157ed2d4c5283070572136ba8.png](../pics/102847c157ed2d4c5283070572136ba8.png)
```

The preview in Zettlr works without issues!

**Comment by nathanlesage** [comment]
Yeah, there is something going on with resolving relative paths on export atm, but I've not gotten to pinpoint that issue …

**Comment by skatego** [comment]
It works when you specify that the export should go into the current working directory. (Preferences -> Export).

If you don't do that, the html file is generated into the /tmp directory and the files are not copied there I think.

**Comment by nathanlesage** [comment]
> and the files are not copied there I think.

Accurate, because why would you want to copy the images there? That's why then there will be absolute links (I think … have to read the changelog again)
