### ISSUE TITLE
[Bug] Typewriter's active line does not follow cursor

### ISSUE THREAD

**Issue by gbraad** [Zettlr/Zettlr#2470]
### Description

When switched to Typewriter mode in the current beta 3 for 2.0, the active line does not follow cursor movement. It becomes active and visible on the line when you start typing.

### Reproducing

  * switch to typewriter mode
  * move cursor (not following, active line remains in place)
  * start typing (active line shown at cursor)
 

### Zettlr Version

Beta (if applicable)

### Specify version

2.0 beta 3

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10, Mojave, Fedora 35

### Additional Information

![image](https://user-images.githubusercontent.com/1894/133417237-83465d3f-4c28-45aa-a4c0-f07944d13f23.png)

**Comment by nathanlesage** [comment]
That change was introduced because when the Typewriter line would ALWAYS follow the cursor movement, selecting text would become almost impossible. But i see the point that at least the highlighting itself should follow the cursor – and that only the centering should be restricted to actual typing.

**Comment by nathanlesage** [comment]
Fixed that in one of the recent commits
