### ISSUE TITLE
[Bug] Notifications are identified by the application name but rather the app-user-model-id

### ISSUE THREAD

**Issue by gbraad** [Zettlr/Zettlr#2471]
### Description

The application starts with `--app-user-model-id=electron.app.Zettlr` which makes notifications on Windows show the following:

![image](https://user-images.githubusercontent.com/1894/133560479-b63023ad-c547-4240-a76b-0c635384a318.png)

### Reproducing

Use the latest stable version and on startup the translations notifications follows.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10, Mojave, Fedora 35

### Additional Information

Perhaps set the model ID in code with:

```js
app.setAppUserModelId("Zettlr");
```

**Comment by gbraad** [comment]
According to https://docs.microsoft.com/en-us/windows/win32/shell/appids#how-to-form-an-application-defined-appusermodelid the app-model-id is well-formed, but have seen the same issue a lot. Not sure what the deal is ...

**Comment by nathanlesage** [comment]
Yeah I noticed that as well, but I have no idea what I can do about it. I was wondering if it's maybe a missing manifest file entry …? If someone has a solution, it certainly looks better if the actual application name instead of the ID is displayed.

**Comment by gbraad** [comment]
We had the same issue with .NET and now also with Electron. Overriding the modelid as mentioned works,  but is a workaround. Will look into this for sure
________________________________

**Comment by nathanlesage** [comment]
> Will look into this for sure

Thank you! Feel free to open a PR any time!
