### ISSUE TITLE
[Bug] File Dialog Save and Cancel Buttons not translated

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#2474]
### Description

When I save a File the "save" and "cancel" button of the File Dialog  are not translated. (the buttons are named "gtk-save" and "gtk-cancel")

### Reproducing

1.) Create new File
2.) Save the file
3:) File Dialog opened

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr 2 Beta 4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro Linux, i3, packages up to date.

### Additional Information

It's a minor /low priority issue.

**Comment by nathanlesage** [comment]
This almost sounds like a bug in the Electron framework. What Zettlr does is simply call the file-saving dialog which is offered by Electron, and we do not override any button labels in there. Plus the `gtk-`-prefix indicates that it looks like the placeholder by the GTK window manager. Maybe it's just a bug in the 14.0.0 release of Electron, I've seen there is a newer one. Let me quickly check … Okay the 14.0.1 apparently does not fix anything related to that.

Just to check, would you please mind checking the _first_ beta version of Zettlr 2.0 to see if the buttons are translated there? This way we might be able to pinpoint it down to Electron 14.

**Comment by tscheims1** [comment]
@nathanlesage Downloaded first Beta: Jup you re right the buttons are correct translated.

**Comment by nathanlesage** [comment]
Then it pretty much sounds like a bug in the electron framework! Would you mind opening up a bug with them (but only if it hasn't yet been reported!)? Their repo is here: https://github.com/electron/electron

You can tell them that the last working electron version was `13.1.9` and that we see the bug with electron `14.0.0`.

That would be awesome!

**Comment by tscheims1** [comment]
@nathanlesage It's already reported: https://github.com/electron/electron/issues/30247
and will be fixed soon (pull request is waiting for merge)
https://github.com/electron/electron/pull/30888

**Comment by nathanlesage** [comment]
Ah peeeeerfect! :) Then I'll be closing this issue here, because I always update any dependencies as soon as there's a new version available, so as soon as Electron fixes this bug, Zettlr will follow suit! Thank you for looking it up!
