### ISSUE TITLE
[Enhancement] Show Total Words in each listed Folder

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#2475]
### Description

On each File the Number of written Words is listed, but if I want to know how many total words are in a folder, I have to sum the total words of every file.

### Proposed Changes

On each folder are the total words of each file in the folder listed

### Caveats

It could be a performance issue (To recalculate the total words of a folder with many files). Maybe only count the total words of a folder  when the properties context menu of a folder is opened

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro Linux, i3, packages up to date.

**Comment by nathanlesage** [comment]
> It could be a performance issue (To recalculate the total words of a folder with many files).

Actually (fortunately) not, it's as simple as a one-liner:

```js
const wordCount = directory.children
    .filter(file => file.type === 'file')
    .map(file => file.wordCount)
    .reduce((cur, prev) => cur + prev, 0)
```

I think I can squeeze this into 2.0

**Comment by tscheims1** [comment]
That would be awesome.

**Comment by nathanlesage** [comment]
It's incredible how fast something can be if all the data you need is already there!
