### ISSUE TITLE
[Bug] Delete key does not show deleting

### ISSUE THREAD

**Issue by dctreu** [Zettlr/Zettlr#2479]
### Description

In a large file, when typing, if the delete key is used to delete text to the right of the cursor, the deletion is not shown character by character while the delete key is held down: the first character is deleted, and while the delete key is held down, nothing appears to change. The characters deleted only disappear after the delete key is released. 

### Reproducing

This bug does not appear if I create a new test file with only a few lines of text. It however appears in a very large file I am working on (57,956 characters with many headings and references).

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 Home 21H1

**Comment by nathanlesage** [comment]
Huh? That sounds weird. I'll have a look.

**Comment by nathanlesage** [comment]
Tried it out, seems to be a performance issue with CodeMirror. It hangs sometimes. Not sure what I could do about it.

**Comment by nathanlesage** [comment]
Closing as wontfix, we'll implement CodeMirror 6 first, and then see if the performance issue persists. If it does, we can again take a shot at it.
