### ISSUE TITLE
[Feature] Export as markdown

### ISSUE THREAD

**Issue by dianlujitao** [Zettlr/Zettlr#2482]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Export Zettlr flavored markdown as "general" markdown, with Zettlr-specific additions stripped.

### Example Workflow

Zettlr extends the "general" markdown with external features, such as customization via yaml header and citations. It would be nice to provide an option to export as "general" markdown, with yaml header stripped and citations expanded, etc., so that the output file can be properly read by other markdown editors.

### Caveats

Not applicable.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
Very good idea, I have a markdown powered blog which doesn't have any citation support so I'm actually needing this myself.
