### ISSUE TITLE
[Bug] Multiple citation problem on export to pdf

### ISSUE THREAD

**Issue by dm5n** [Zettlr/Zettlr#2483]
### Description

Using the Vancouver-superscript.csl style from [the Zotero repo](https://www.zotero.org/styles?q=id%3Avancouver-superscript) – there is a formatting error on export to pdf.

The in-text citation should be all in superscript but when the citation includes 2 references, the comma separator is rendered in lowercase as shown in the attachment.
<img width="373" alt="Screen Shot 2021-09-19 at 21 42 43" src="https://user-images.githubusercontent.com/5894141/133926215-936f4e8d-5499-4718-9dcd-79f6bc48b5a6.png">
  I'm using Better Bibtex on Zotero 5.0.96.3

### Reproducing

The issue appears to be fixed in the latest Beta. 

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS 10.14.6 Mojave

**Comment by nathanlesage** [comment]
> The issue appears to be fixed in the latest Beta.

That is good to hear – then I'm closing this issue since there won't be any fixes for 1.8.9 – rather, I aim to release 2.0 as soon as possible.
