### ISSUE TITLE
Changing margins of notes

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#2484]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Could we perhaps to have the setting to change margin of notes? I often put Zettlr in a smaller window so that I can take notes while reading PDF documents on the same workspace. The default margin is pretty large which limits the amounts of text that can display in a small window. Therefore, I think it might be a nice functional improvement if we could change margins of notes.

### Example Workflow

See above

### Caveats

See above

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
This is definitely something we could improve, since I have the same problem myself. I don't think a setting is necessary, but just a readjustment for the different margins we have for various screen sizes.

I'm taking suggestions for cool margins! (pls with screen sizes so I can adapt the correct rules!)

**Comment by sith-on-mars** [comment]
Thanks for this. I think I'm fine without the setting, but I'm bit less sure about adjusting margins based on screen sizes. I think the adjustment based on the window width might be more practical? Because one can use Zeetlr at the full size window or as well as the small size window.

**Comment by nathanlesage** [comment]
> adjustment based on the window width might be more practical?

That's what I meant!

Here's what we have right now: https://github.com/Zettlr/Zettlr/blob/develop/source/win-main/Editor.vue#L851

Basically we have three sizes based on which we apply both a margin-left and padding-right (further below the linked line), for widths of 0-900px, 901-1024px, and 1025px and above.

The distraction free mode is basically a "fullscreen" mode which has a few different sizes: https://github.com/Zettlr/Zettlr/blob/develop/source/win-main/Editor.vue#L987

**Comment by sith-on-mars** [comment]
> Here's what we have right now: https://github.com/Zettlr/Zettlr/blob/develop/source/win-main/Editor.vue#L851

I didn't realise we already have this before. It's a nice option, but the margin is still sometimes bit too large for widths of 0-900px. Would you consider to have an xsm and xxsm sizes for widths lower than 900px? Like 0-600 uses the xxsm size and 601-899 uses the xsm size?

**Comment by nathanlesage** [comment]
Sure, that's what I meant when I wrote "I'm taking suggestions for cool margins! (pls with screen sizes so I can adapt the correct rules!)"

Feel free to experiment a little bit and suggest new sizes which can then be added.

**Comment by vkovalcik** [comment]
This is the first issue I am searching for right after installing Zettlr and going through the settings a few times. I too consider margins rather huge and same as the OP, I use notes in a smaller window on a big screen to see the notes and other content (my notes window is around 960px wide with file manager displayed). It would be great if the margins could be adjusted by the user.

**Comment by nathanlesage** [comment]
They can with custom CSS: https://docs.zettlr.com/en/core/custom-css/#set-a-maximum-width-for-the-text

**Comment by vkovalcik** [comment]
@nathanlesage : Cool, works great, thank you very much! BTW for anyone else interested, this is what I ended up doing. A bit different from the docs, I adjusted one more element:

#editor .CodeMirror {
  margin-left: 10px;
}

#editor .CodeMirror-scroll {
  padding-right: 10px;
}

#editor .CodeMirror-sizer {
  margin-left: 0 !important;
}

**Comment by sith-on-mars** [comment]
A lot of underlying DOM structure and class names have changed in the migration of CodeMirror 5 to 6 in the Beta version, so the old custom CSS on margin just stopped working now. Do you perhaps have any idea how to change margin in the beta version? @vkovalcik

**Comment by vkovalcik** [comment]
@sith-on-mars : Sorry, currently I don't use Zettlr very often, so I have no idea.

**Comment by mahmoudjalloh** [comment]
> A lot of underlying DOM structure and class names have changed in the migration of CodeMirror 5 to 6 in the Beta version, so the old custom CSS on margin just stopped working now. Do you perhaps have any idea how to change margin in the beta version? @vkovalcik

Did anyone ever figure out how to change the margins in more recent versions?

**Comment by evdcush** [comment]
Related:

- [Set a max width for the editor? #122](https://github.com/Zettlr/Zettlr/issues/122)
- [What exactly is the CSS required to reduce the editor left-margin padding #5241](https://github.com/Zettlr/Zettlr/issues/5241)
