### ISSUE TITLE
[Solved] Presence of YAML Front matter inhibits Zettlr 2.0 from showing markdown file contents

### ISSUE THREAD

**Issue by hildebrand-institute** [Zettlr/Zettlr#2485]
### Description

If I have a markdown file with a YAML Front matter, Zettlr 2.0 does not show the file contents, even if the file appears among the opened tabs. Contents are normally shown only when Zettlr is newly opened after having been closed when the md file with YAML front matter was the last one to be clicked on the sidebar or among the tabs. But after another file has been clicked, then again the contents of the file with YAML front matter are not shown anymore.

### Reproducing

Just insert a YAML front matter within a markdown file.

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr-2.0.0-beta.4-x86_64.rpm

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 34

### Additional Information

If the YAML front matter appears at the beginning of the markdown file, on the side bar under the file name a "0 word" info appears.

**Comment by nathanlesage** [comment]
I am very positive that there might be interference with the file itself. Can you reproduce this with different files or is it just one file? If the latter, what does the YAML frontmatter look like?

**Comment by hildebrand-institute** [comment]
SORRY! That was definitely my fault. A very stupid syntax error within a couple of YAML file of which I have copied the content from one to the other...
