### ISSUE TITLE
Projects - Export

### ISSUE THREAD

**Issue by monkey-sapphy** [Zettlr/Zettlr#2486]
### Description

Exporting a project with the **PDF AND HTML** formats selected does only export the project in pdf format, not in html format. Exporting with any other format (e.g.: .rtf) and html selected works, the project is exported as an rtf file and an html file.

### Reproducing

Activate the project mode for a directory containing some .md files. 
Under properties for export, select .html and .pdf.
Right-click on the directory and export the project. 
After a succesful creation message has been displyed, click on it to check the contents of the current directory: a .pdf file will have been created but NO .html file.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.4

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 7

**Comment by nathanlesage** [comment]
I think I fixed this a few days ago, so it should be out with the next nightly.
