### ISSUE TITLE
Can't create new folder from Zettlr

### ISSUE THREAD

**Issue by semiopat** [Zettlr/Zettlr#249]
#11  Description
When Zettlr has projects and folders in its vertical bar, it's impossible to create new folder (nor from the Files menu neither with the keyboard shortcut).

## Reproducing
Clic on the menu item Files>Create new folder (sorry if not exactly the name, I translate from french mac version) do nothing, using the `cmd`+`maj`+`N`key neither.

## Expected behaviour
Zetllr should be able to create new folders, which could be saved automatically in its own saved directory (the one created when opening Zettlr for the first time), or saved anywhere after asking for it in a pop up window.

## Platform
 - OS: macOS 
 - OS Version Mojave (10.14.5)

**Comment by nathanlesage** [comment]
Hey,

to verify the bug, I would like you to describe more of the context when this bug occurs, such as:

- What was the currently selected directory? Or was no directory selected?
- Was the selected directory a default directory, a project directory, or a virtual directory?

Zettlr's shortcuts derive additional necessary information from context. Using right-clicks provides the context by means of the clicked element (such as a directory, or a file). If you don't use right-click, the context needs to come from somewhere else, namely the currently selected directory or file. If no file is selected, or no directory is selected, the shortcuts will do nothing, as the context they require for performing the requested action, is missing.

**Comment by semiopat** [comment]
Hi Hendrik,

Thank you for your answer, that clears one point to me: if it’s not in an existing directory, I can’t create a directory in Zettlr; but, if I create a new folder in the Finder, I can drag and drop it as a new directory in Zettlr. For example, if I want to open a brand new project, I need to open a new folder in the Finder, and drag and drop it to Zettlr. That’s why I thought it was a bug. I don’t understant the logic of this behavior, but at least I have a solution to my problem.

What would be better to me, as a useful feature,  is to be able to add new directory in the default saved directory of Zettlr, with the usual cmd+maj+N that works all around the system. In the actual way, I have to clic on the finder and create the folder first, drag and drop it to Zettlr window, and store it in the directory I want it to stay (otherwise the folder would stay in the Finder, which is not, for me, a good solution of storage).

I hope it helps, your software is very good and I’d like to help if I could to enhance it.

Best regards,
Patrick

**Comment by nathanlesage** [comment]
Ah wait, so you mean you can't create new root folders by pressing Cmd+Shift+N? This is intended. Zettlr is programmed to have one or more so-called "root-directories" open, and **in these** you should put all directories that you need. You can't simply create new Root directories, but new subdirectories!

![image](https://user-images.githubusercontent.com/17251683/60248221-75dce900-98c2-11e9-8c36-d84e42e8d48b.png)

Zettlr is intended that you have one "overarching" directory (e.g., called "Zettlr" or "My Projects") and in this you can then put all your projects, directories, etc!

**Comment by jaydorsey** [comment]
I also found this to be confusing; you can only create subfolders for existing imported folders

In order to accomplish this I was able to:

- Create the new directory on my local filesystem
- In Zettlr; File > Open that folder as a new "root" directory

I was able to have two root directories this way:

![image](https://user-images.githubusercontent.com/191564/86963397-51445f80-c119-11ea-8448-5f1223bf09ec.png)

Although I wasn't able to intuitively figure this out (I found this issue via a Google search for a solution), the explanation above (you can't create root directories via CMD+SHIFT+N) makes it clear it's working as designed. (I didn't read the whole tutorial so it may be covered there, just posting this follow up in case anyone else makes it this far)
