### ISSUE TITLE
[Bug] PDF export with image fails

### ISSUE THREAD

**Issue by kenokenobingo** [Zettlr/Zettlr#2495]
### Description

My .md document contains an image with the correct path. When I try to export the .md file to a PDF file, an error message is shown:

<img width="995" alt="Bildschirmfoto 2021-09-20 um 11 25 56" src="https://user-images.githubusercontent.com/9639767/133981073-2c3a6db1-3785-43ee-9be1-98210ac45e43.png">

### Reproducing

- include an image file in the .md document
- try to export it as a PDF document with Zettlr

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Big Sur 11.5.2

**Comment by nathanlesage** [comment]
Do you experience this bug as well with the most recent beta?

**Comment by kenokenobingo** [comment]
No, in the most recent beta, it works fine! Thanks!

**Comment by nathanlesage** [comment]
Perfect, then closing this issue! Please feel free to continue using the beta, since these are extremely stable and should work well better than 189!

**Comment by kenokenobingo** [comment]
I see! Cool, thanks!
