### ISSUE TITLE
Can't find Close file or directory

### ISSUE THREAD

**Issue by evelynmitchell** [Zettlr/Zettlr#250]
## Description
Close (tidy up, non-destructive) and Delete (permanent, destructive) mean very different things

Only offering the destructive option, leads me to be hesitant to use it, if I am wrong on it's meaning, because instead of tidying, I'd be destroying.

## Reproducing
There is a menu item File: Delete File and one File: Delete Directory
but there isn't one File: Close File or File: Close Directory

## Expected behaviour
Offer a Close option, and perhaps an Archive option. I'd be unlikely to use this application to delete notes. Archive would put the archived item in the Archive place.

**Screenshots**

## Platform
 - OS Version [e.g. 11]
 - Zettlr Version [e.g. 0.15]
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information
The application is lovely! Thank you!

**Comment by nathanlesage** [comment]
I've had this discussion with some other people already, so here's the reasoning why I'll keep it:

1. Zettlr will **never ever ever remove anything permanently**. Anything you delete is moved to the system's trash bin from where you can restore everything.
2. "Closing" files and directories is only possible for root level files and directories, which is only present on right-click, as you probably won't be closing roots very often.
3. Single files are always closed whenever you choose another file. Zettlr is designed to always have at least one file open. Only in rare cases does it happen that Zettlr's editor does not show a file.

Concerning the archiving option: For now it's possible by creating an Archive directory, opening it as a root directory and simply move all old files and directories into it. But it may soon be a built-in feature, just stay tuned!

**Comment by evelynmitchell** [comment]
You know your program is safe, but a new user may be confused. I was
confused.

There are customs which people rely on, in order to leverage their prior
learning in novel situations.
Not including a 'Close' button is a fairly large change in custom.

Evelyn

**Comment by nathanlesage** [comment]
I see your point, and it certainly proves to be absolutely valid. Yet, as "closing" files is not intended, and as there are many other Markdown editors out there who also don't intend closing files, I think that it would be even more confusing to have a close command only to display a notification telling the user that closing is not intended :/

**Comment by evelynmitchell** [comment]
I'm not clear on the sense you intend for "Destroy" to indicate to me that
it allow me to remove an item from my workspace in a safe way, when what it
does, is destructive removal (put in the trash).

That other Markdown editors (implementation detail) don't tell the user
what they are doing, does not make it ok to follow their lead.

Right click on my system shows the menu:
   Rename File
   Delete File
   ------
   Quicklook
   ------
   Writing target

None of those are similar to "I no longer want to work with this file in
zettlr" which is the sense of close I was looking for. The choice you are
giving me is "I no longer want to work with this file at all" which is a
broader scope than I need.

Thank you,
Evelyn

**Comment by nathanlesage** [comment]
Yeah, as I said: Zettlr is designed as such that you open up dedicated root directories, in which you put all your files you want to be working with. If there are some files you only want to edit with Zettlr once, choose "Open with … Zettlr" from the file browser context menu, it'll be opened in Zettlr as a standalone root file, and if you THEN right-click on it, you can "close" the file as in: really close.

You can't close files within root directories, as this is the design choice of Zettlr to always have a directory which will be kept open in Zettlr.

**Comment by evelynmitchell** [comment]
The dedicated root directory part, could be included in the the onboarding
docs/beginner tutorial. I'll write something up.
Thank you,
Evelyn
