### ISSUE TITLE
[Enhancement/Bug] Improve/Debug markdown link click behavior in editor

### ISSUE THREAD

**Issue by raphraph** [Zettlr/Zettlr#2503]
### Description

_I'm on Zettlr 2.0.0-beta4_

When inserting a file from the "Other files" section of the sidebar, Zettlr automatically creates a link.

When the file is an image, it becomes a block element. But when the file is not an image, for example a pdf file, it inserts a link with the filepath as the url.

When clicking on this link (pdf file) in Zettlr, the file is opened in a web browser as if the link was a hypertext link (therefore formatted such as `https://home/user/path/to/pdf/file.pdf`) which does not work.

Manually adding `file://` (on Linux...) in front of the filepath makes Zettlr behave normally and correctly open the pdf file in the default pdf viewer.

### Proposed Changes

In the `handleDragStart` function in [Sidebar.vue](https://github.com/Zettlr/Zettlr/blob/c9fbe1dac8de857b6a67e14420994cd93a9b2ac3/source/win-main/Sidebar.vue) there is the following line :
```
const data = FILETYPES_IMG.includes(ext) ? `![${basename}](${uri})` : `[${basename}](${uri})`
```
I think that a string can be added here (for non-image filetypes) in front of the uri in order to produce a correct link, but this is surely system dependent...

### Caveats

I don't know for sure

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 21.04

### Additional Information

I selected yes at "Do you Wish to Attempt Implementing this Yourself?" but even if it's a small fix I will need help. So if someone is willing to guide me, please feel free :)

**Comment by nathanlesage** [comment]
> I selected yes at "Do you Wish to Attempt Implementing this Yourself?" but even if it's a small fix I will need help. So if someone is willing to guide me, please feel free :)

Thank you very much!!

You're on the right track, but I think you should look here: https://github.com/Zettlr/Zettlr/blob/develop/source/common/util/make-valid-uri.js

This function is being executed whenever the user attempts to open a Markdown link, so we might just add it there. I just saw [here](https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/plugins/render-links.js#L148) that the editor itself uses the older function. Let me have a look.

Hmm … yeah, it seems really convoluted, but the correct solution is already somewhere in there. Feel free to tinker around and if you encounter problems, feel free to ask (preferably on our Discord)

**Comment by raphraph** [comment]
This is a followup describing the problem. If someone is willing to help or take over this issue please say so. For now my little knowledge is not enough to solve it...

The [utility function (make-valid-uri.js)](https://github.com/Zettlr/Zettlr/blob/develop/source/common/util/make-valid-uri.js) managing the uri formatting in order to correctly open links depending on their protocol (file, https, etc) is not working properly.

When run the `fileExists()` function (from [is-file.js](https://github.com/Zettlr/Zettlr/blob/develop/source/common/util/is-file.js)) which checks the existence of a file at a given uri always return `false`, even when the file exists.
Inspecting code shows that when calling `let s = fs.lstatSync(p)` the following error occurs and `fileExists()` therefore always return false:
```
TypeError: fs.lstatSync is not a function
```

Trying to bypass this check (removing it) brings in errors when evaluating uris (this can easily be checked when running `yarn test` after having renamed `make-valid-uri.js.ignore` in `make-valid-uri.js` in the **test folder**).

_Note: in `make-valid-uri.js` script the `const path = window.path` line (replacing old line `const path = require('path')`) throws an error in mocha... This will probably require an independent fix._

**The solution seems to be either to fix the problematic call to `fileExists()`, or to find another way to check the file existence of a given uri.**

**Comment by nathanlesage** [comment]
Yeah, I think we can't check anything. I'm right now inclined to either remove that file existence check completely (the window.path thing is another issue) or even just have the main process deal with the link.

**Comment by nathanlesage** [comment]
Fixed by one of the more recent commits, shouldn't be a problem anymore!
