### ISSUE TITLE
[Bug] CiteProc references with special characters don’t work

### ISSUE THREAD

**Issue by kenokenobingo** [Zettlr/Zettlr#2504]
### Description

In my library, there is the CiteProc key `klima*kollektive.v.Klimascheinlosungen2021`. Zettlr isn’t able to parse it as a reference.

<img width="961" alt="Bildschirmfoto 2021-09-21 um 17 20 04" src="https://user-images.githubusercontent.com/9639767/134199039-5e842f8d-b277-4ff5-8111-6937a90ad0a4.png">

### Reproducing

Save a publication with a special character in Zotero and try to quote from it in Zettlr.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.4

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Big Sur 11.6

**Comment by nathanlesage** [comment]
Reason is with https://github.com/Zettlr/Citr. Have to port that into the main codebase, but it's some work, so please try to prevent special chars until then! Sorry for any inconvenience.

**Comment by kenokenobingo** [comment]
Thank you, @nathanlesage! If it’s alright with you, I’ll close the issue as soon as the fix is deployed to the beta version.

**Comment by nathanlesage** [comment]
I'm not sure it'll make it into 2.0, that's the thing. It's really a moloch of work. I have nobody but me to blame for this, but unfortunately that makes it no easier to actually do it.
