### ISSUE TITLE
Zettlr randomly Scrolls Up [Bug] 

### ISSUE THREAD

**Issue by 1-Falcon** [Zettlr/Zettlr#2509]
### Description

Sometimes when using Zettlr (whether simply reading a file or adding to it), Zettlr randomly scrolls up. It is very annoying.

### Reproducing

This happen while I am using the app normally , so I don't know how to reproduce it.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 21H1

**Comment by nathanlesage** [comment]
Is this possibly a duplicate of #1621?

**Comment by 1-Falcon** [comment]
Yeah, sorry. I looked before posting if someone else reported this bug , but it seems I missed #1621 .

**Comment by 1-Falcon** [comment]
Sorry
