### ISSUE TITLE
Export pdf on Linux, alternative to xelatex

### ISSUE THREAD

**Issue by evelynmitchell** [Zettlr/Zettlr#251]
## Description
Attempt to export to pdf, get error

## Reproducing
Create text file. 
File: export
(I can't copy and paste most of the error.)
Export Failed
Command failed: pandoc '/tmp/export.tmp" -f markdown --template="/tmp/template.latex" --pdf-engine=xelatex -o "/tmp/filename.pdf"
(copy and paste below)
pandoc: unrecognized option `--pdf-engine=xelatex'
Try pandoc --help for more information.

## Expected behaviour
I have pandoc installed, and can export to pdf using this command:
pandoc --from=org --to=pdf notes.org -t latex -o notes.pdf

My first attempt from outside zettlr to create the pdf with pandoc had a helpful error message
 pandoc --from=org --to=pdf notes.org 
pandoc: Unknown writer: pdf
To create a pdf with pandoc, use the latex or beamer writer and specify
an output file with .pdf extension (pandoc -t latex -o filename.pdf).

**Screenshots**

## Platform
Ubuntu 18.0
zettlr 1.3.0
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1

 - OS Version [e.g. 11]
 - Zettlr Version [e.g. 0.15]
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Thank you for providing the Pandoc version, now I can help you. Please consider the following excerpt from our [Frequently Asked Questions](https://docs.zettlr.com/faq/):

> **On Export, Zettlr says the PDF-Engine wasn't recognised!**
>
> This is a common Pandoc error, indicating that your Pandoc version is pre-2.x. When Zettlr presents you the following error message, it means you need to update to Pandoc 2.x:
> 
> `pandoc: unrecognized option '--pdf-engine=xelatex' Try pandoc --help for more information.`
>
> The reason is that with Pandoc 2.0, the older option `--latex-engine` was renamed to `--pdf-engine`. [See more in Pandoc's changelog](https://github.com/jgm/pandoc/blob/master/changelog#L4349).

**Comment by gritty-gitty** [comment]
> Command failed: pandoc '/tmp/export.tmp" -f markdown --template="/tmp/template.latex" --pdf-engine=xelatex -o "/tmp/filename.pdf"
> (copy and paste below)
> pandoc: unrecognized option `--pdf-engine=xelatex'
> Try pandoc --help for more information.
> …
> Ubuntu 18.0
> zettlr 1.3.0
> pandoc 1.19.2.4
> Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
> 
Even on Ubuntu 18.04, I had to install *pandoc* from its [official install page](https://pandoc.org/installing.html#linux) in order to get the newest version, eg:
> pandoc 2.7.2
> Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7

**Comment by WilliamYangShuai** [comment]
my pandoc version is pandoc 2.2.3.2, Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2, but I still have this problem

**Comment by nathanlesage** [comment]
Does this problem even occur with the current Pandoc 2.7-line?

**Comment by ossphil** [comment]
> Does this problem even occur with the current Pandoc 2.7-line?

Yes, I installed pandoc-2.7.3 from anaconda distribution, but this problem still occurs.

**Comment by nathanlesage** [comment]
Does the error still include `pandoc: unrecognized option --pdf-engine=xelatex`?

**Comment by tomtroughton** [comment]
Ubuntu 18.04. I had to install pandoc from the deb file available at https://github.com/jgm/pandoc/releases/tag/2.7.3 which enabled ODT but not pdf export. Pdf export was fixed when I installed texlive-xetex. On my way to trying that I also installed texlive-base, texlive-latex-base, texlive-latex-recommended and texlive-latex-extra.
