### ISSUE TITLE
[FEATURE REQUEST] Notes switching and a small bug

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#252]
It's great that we have the `Cmd/Ctrl+[0-9]` to "open recent document at position 0 to 9 in the recent documents list (File->Recent Documents)" (quote from Zettlr Docs), but wouldn't it be nice to have also a shortcut for switching between recent documents without using the numbers? Something like `Cmd/Ctr+Tab`? (I don't see it reserved for something)

P. S. I don't know if it is a bug or a feature but in Linux (maybe on other OS) if you create a note (let's say `test.md`) it does not appear in the `Recent documents` list until you restart Zettlr and so you can not navigate using keys to it.

**Comment by nathanlesage** [comment]
Concerning the note-switching: I may have a better idea for the `Cmd/Ctrl+Tab`-shortcut, which involves literally tabs … but more on that once I get to it! If there is only one open file, it would be visually confusing to be able to switch through recent documents (imagine in your webbrowser, if you would be able to open history pages that are currently not open by hitting `Cmd/Ctrl+Tab`).

Concerning the fact that newly created files are not added to the recent documents is weird, as I thought I'd add files after they've been opened o.O I'll see into it!

**Comment by samarulmeu** [comment]
Tabs will also be interesting. Hope Zettlr will not lose the **clean** look I'm used to. 
And the issue with the newly created files was bothering me for quite some time, but now as I need to navigate more and more through notes is getting annoying. 

Thank you for the great work. Any roadmap for the new beta/version release?

**Comment by nathanlesage** [comment]
Ehm … I was thinking when I'll be starting the next beta, because there's already so much new stuff in it that a new version is justified … I think I'll get to this bug and hopefully some other minor things, and then I'll begin the next beta round, so maybe End of July! :)

**Comment by samarulmeu** [comment]
Great! Hardly waiting for the first beta ;).

**Comment by nathanlesage** [comment]
I think we've solved this one, right? If not, pls let me know.
