### ISSUE TITLE
Very high cpu usage

### ISSUE THREAD

**Issue by mouarfff** [Zettlr/Zettlr#253]
Since some days, using zettlr become difficult, i have a very high cpu usage and i can't editing anything for 1 minutes each time i try ti type something.

I start to type my texte and after 3à secondes or 1 minute, my text appears. I can't navigate into it with my mouse cursor, it take so much time.

cpu incrase to more than 20% of usage.

If i have only text, basic things as tittle or short quote, it's OK, if i have a lot of links or long citation, cpu usage increase a lot and it's become inusable.

If i show all the code in the text, i don't have issue.

I'm in windows 10 familly (last update) an dlast version of zettlr

**Comment by nathanlesage** [comment]
Ouh, that's not good. But there have been some performance issues with the plugins prior. The question is: Which one of the plugins causes the problem? Could you activate all display plugins and then deactivate one at a time to see where the speed increases again? Then we have a place to start

**Comment by mouarfff** [comment]
i said i disabled all wizywig view, so now i see all the markdown code and i don't see the final rendering.
so i turned of all, and i retry with a new file and turn on view, and it works ...

i have only this issue with one file contains a lot of hyperlinks ?
strange

**Comment by samarulmeu** [comment]
It is something to do with what was discussed at the end of this [topic](https://forum.zettlr.com/discussion/9/1-3-0-beta-release) in the forum. 

I experience on a regular bases this very, very slow performance from Zettlr on files with a lot of links on them. Sometimes I save web pages for further reference and convert them to Markdown. Using Zettlr to eliminate the unwanted text (links, menus, comments) takes for ever.

**Comment by nathanlesage** [comment]
Ah, ah, ah! I think I know where it comes from. If it's the Link-rendering plugin, then it may be caused by these pesky lines of code: 

https://github.com/Zettlr/Zettlr/blob/929c4d22ca3f3e89856d1b38767561c3b6131a75/source/renderer/assets/codemirror/zettlr-plugin-render-links.js#L76-L77

They check the surroundings of a found link to make sure the link is not inside a comment to not render it. They do indeed have some costs on performance, albeit I am surprised at how much actually.

**Comment by samarulmeu** [comment]
Maybe the plugin (if that's the cause for slow performance) works for one or two links, but, when you have a lot of them, that adds up. As I mentioned above, in my usual scenario converting and then editing a saved web page is getting extremely tedious.

**Comment by mouarfff** [comment]
same issue as described by samarulme about files with a lot of hyperlinks

i just turn off the plugin for this moment

it's better with it but i like use zettlr and i don't want to change :)

**Comment by nathanlesage** [comment]
I realised that the main problem for the plugin seems to be too many hyperlinks on the same line ... can anyone confirm that? Because having hundreds of hyperlinks, but all of them on different lines, seems to be not at all so performance hungry. Or is it just my impression?

**Comment by samarulmeu** [comment]
No. I think it is just an impression. It's slow with links spread on different lines also, not only on the same line.

**Comment by nathanlesage** [comment]
Alright. Maybe I'll just get rid of the token check and just render the thing whether or not it's in a comment or not. I mean, after all, the only problem with these links is that it's hard to get the corrent font-family, so once I solve that it shouldn't be a problem!

**Comment by samarulmeu** [comment]
I also removed the links rendering and the handling of files was so much smoother and Zettlr was usable again. So maybe you can eliminate the *search for comment* behavior.

**Comment by nathanlesage** [comment]
Alright! I'll try to think of something to at least match the fonts (otherwise, for instance with sans-serif and serif-themes, the links will be rendered using sans or sans-serif fonts, instead of monospace within comment sections). But I think the performance is in this case more important than a small design issue!

**Comment by nathanlesage** [comment]
I think … the issue is resolved now? If not pls let me know.

**Comment by mouarfff** [comment]
Yesss i think it's solved thx a lot :)
