### ISSUE TITLE
Issue with duplicate dictionaries

### ISSUE THREAD

**Issue by thob** [Zettlr/Zettlr#254]
So, I added two dictionaries (de-DE, en-US). They're in `/.config/zettlr/dict/`now in the settings these two and the shipped two are checked. There's no way I can get rid of the duplicate check boxes
![image](https://user-images.githubusercontent.com/755337/60397392-49340600-9b3c-11e9-942b-09a6c8573000.png)
Is this just a GUI glitch or does it affect performance. Or do I even miss something here.
Thanks

**Comment by nathanlesage** [comment]
Hey, the German dictionary was actually already included with the app, so there's no need to install it again. Nevertheless, Zettlr should give precedence to the user-provided dictionary, if available, and not include multiple entries.

**Comment by nathanlesage** [comment]
There you go, should be fine now!

**Comment by thob** [comment]
@nathanlesage is the German and US dictionary really the same I downloaded from GH. I received different results with the new ones. But seems to be fixed with the next update. Thanks :+1:

**Comment by nathanlesage** [comment]
Different results? Where did you download them? I have to admit I haven't updated them in some time, so it's very likely they're outdated :S
