### ISSUE TITLE
[Enhancement] Sort by filename in project

### ISSUE THREAD

**Issue by pabaillon** [Zettlr/Zettlr#2543]
### Description

Actually you can chose to sort by name or date before export a project. But if you chose to use "display the first heanding level title " in preferences, you must change titles to have the right order. 

### Proposed Changes

Add sort by filname in the project properties.

### Caveats

no

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by nathanlesage** [comment]
Sounds like a good new option for projects. Something like a YAML frontmatter var.
