### ISSUE TITLE
[Bug] The ui changed in the latest 2.0beta5 version

### ISSUE THREAD

**Issue by lianghongzhuo** [Zettlr/Zettlr#2546]
### Description

The UI changed in the latest 2.0beta5 version in ubuntu 18.04 and ubuntu20.04
expected UI look:
![ui1](https://user-images.githubusercontent.com/16577120/135680567-16bd5017-1e27-4216-b25f-55eadf411e21.png)

beta version UI  look:
![ui2](https://user-images.githubusercontent.com/16577120/135680627-efd665ca-3b97-40b0-b582-94f51759709a.png)

### Reproducing

Download the  latest 2.0beta5 version (deb or appimage) and the UI is different than v1.8.9

### Zettlr Version

Beta (if applicable)

### Specify version

v2.0.0-beta.5

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 18.04 or Ubuntu20.04

**Comment by nathanlesage** [comment]
> Download the latest 2.0beta5 version (deb or appimage) and the UI is different than v1.8.9

Umm... yes. That's intended. Just have a look around, a lot of other things have changed, many to the better! I will be writing a longer and more elaborate statement summarising the changes when 2.0.0 is out in two weeks or so! Until then, if you have further questions, feel free to ask on Discord or Twitter :)

**Comment by lianghongzhuo** [comment]
Sorry if I did not explain it clearly, but I believe the outlook change is a bug. Have you tried to check the software on a ubuntu computer?
![ui1](https://user-images.githubusercontent.com/16577120/135719589-b46c34c8-8fe1-49f0-bfdf-535b6417ba5b.png)
![ui2](https://user-images.githubusercontent.com/16577120/135719590-141e700c-057c-4d6b-a78f-3b2b2791dd37.png)
I hope these two compare figs show better the difference.

**Comment by nathanlesage** [comment]
Why should the style change be a bug? I implemented the GNOME Human Interface Guidelines as close as possible so that Zettlr looks native now. So no, it's not a bug, it's fully intentional.
