### ISSUE TITLE
Feature not working: [CTRL + R] Rename file doesn't work anymore when not in directory

### ISSUE THREAD

**Issue by alpcantal** [Zettlr/Zettlr#2559]
Previous versions were able to rename the files right from the editor, but now it doesn't seem to be working unless I'm in the file directory. 

P.S. Why aren't full-text search and the directory filter merged together? The filter is extremely fast and works the same as Notational Velocity/The Archive! Darn amazing.

**Comment by nathanlesage** [comment]
> Why aren't full-text search and the directory filter merged together?

Because the filter only takes into account metadata ready at hand whereas the full-text search does precisely that: Read in every file and actually search every piece of content there is.

With file renaming, I actually have no good idea of how to solve it, so it remains up for discussion ...

**Comment by alpcantal** [comment]
I see! Thanks for clarifying. For now a personal workaround may suffice for this feature :D
