### ISSUE TITLE
[Enhancement] Filter when following links option

### ISSUE THREAD

**Issue by alpcantal** [Zettlr/Zettlr#2560]
### Description

Workflow wise, when a "**filter** (not search) when following links" is implemented, then three things happen:

- filtering when following links helps implement [this feature](https://github.com/Zettlr/Zettlr/issues/2443) without strictly limiting the feature to YAML headers
- following links in the Zettelkasten can now be translated into searching/filtering filenames and then simply showing the note with matching ID (I don't know about the code)
- when clicking on a note ID, the filtered results will already show the backlinks, i.e. the notes that mention the ID. (this result lacks context, anyway, aside from being "backlinks" so **there's NO need to automate putting backlinks into the content area**). I mentioned this because of [this discussion](https://github.com/Zettlr/Zettlr/discussions/2410).

Another benefit is that many users of Notational Velocity or The Archive cannot find any alternative to those apps in Windows. But this might be a "small probability" benefit.

In my experience I believe Zettlr is pretty much the closest thing to The Archive in Windows, with more features. (I personally love how it integrated pandoc) But instead of searching, filtering must be used to achieve the same (or better) performance. Searching just gets in the way of the workflow because of the time required.

I don't know but if it's easy to just merge search and filtering that would make Zettlr extremely fast. Then again, I do not fully know the rationale behind it, so I cannot judge quickly. 

**Disclaimer**: I am a Zettelkasten user for ~~3 years~~ (EDIT: more than 1 year — 3 years was my writing experience) now, but not a programmer

### Proposed Changes

an option for "filter when following internal links" instead of full-text search

### Caveats

Now the "follow Zettelkasten link" function becomes redundant :D

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Hm interesting proposal. It would be nice to see some workflows of how that would then work, so that we can spot problems early on. But I think for this a discussion might be also a good place ...?

**Comment by alpcantal** [comment]
Theoretically, I would think that the only problem would be searching for content deep into a long note that cannot be covered by the filter feature. But, that's what full-text search is for! (As you mentioned in the other issue) Thus, I don't think it's worth a longer discussion. :)

For the actual workflow of how it works, I personally don't look further than The Archive and its main proponents — so here's a [sample](https://youtu.be/2_MJYtWr1vE?t=2267):

![image](https://user-images.githubusercontent.com/64248029/136027463-c6e8a621-30f5-46fd-9bdc-0bdb26da00a5.png)
