### ISSUE TITLE
Menu items not clickable on Linux

### ISSUE THREAD

**Issue by cjpoor** [Zettlr/Zettlr#2562]
Zettlr 2.0.0-beta.5
Linux Mint 20.2 Cinnamon

Expected behaviour:
When clicking on menu item such as Select All or Undo
all text in the current note should be selected or the last action should be undone.

Actual behaviour:
Clicking on menu item has no effect, but using keyboard shortcuts Ctrl-A or Ctrl-Z give expected results.

**Comment by nathanlesage** [comment]
Please use the provided issue templates! :)

**Comment by cjpoor** [comment]
Sorry. Thanks for the beautiful app!

**Comment by nathanlesage** [comment]
Really? On Macs it shouldn't be a problem actually

**Comment by cjpoor** [comment]
Ah. Sorry. Clicking Undo works, but Select All only works with keyboard.

**Comment by nathanlesage** [comment]
It might not work completely with CodeMirror, but that's a problem that is not necessarily with the mneu but rather with the way CodeMirror works. The selectAll should work on regular text fields.

**Comment by cjpoor** [comment]
I find the menu item results quite quirky.

On the Mac: 
Select All does not work on the text that I have typed into a note.
Menu undo does work on text that I type into the note but not on actions such as cut and paste.
That is, I can undo a typed word letter by letter, with the menu undo. Cmd-Z removes the whole word.
After cutting (or pasting) a word undo does not restore (or remove) it. However Cmd-Z does.
Other Edit menu items work as expected.

On Linux: 
Edit menu items do not work except Generate new ID.
Keyboard edit actions work as expected.
