### ISSUE TITLE
[Bug] File List  is not updated when sorting by modification time

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#2577]
### Description

Sort order in file list is not updated when the folder is sorted by modification time and files are modified.
(when the sort order is switched in the folder settings, (eg from ascending to desceinding) the sort order is updated.

the timestamp in the file list (eg. 1 min ago ) is updated properly.

### Reproducing

1.) open a folder that contains some files
2.) set option: "when sorting by time sort by modification time"
3.) set sort of folder to sort by time ascending
4.) modify some files. 
5.) the timestamp of the file (e.g. 1 min ago) of the file in the file browser list is updated properly. the order of the files remains.
![file-sorting-by-modification-time-not-refresh-properly](https://user-images.githubusercontent.com/5829119/136290664-0830d877-4e02-4c7f-b113-0a8f11828b1f.png)

### Zettlr Version

Beta (if applicable)

### Specify version

5

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro Linux, i3, packages up to date.

**Comment by nathanlesage** [comment]
Closed in 6da4b24

**Comment by newhinton** [comment]
Is this truly fixed? I build from develop (and made sure the change in 6da4b24 was present) and the sorting still does not reorder the list automatically after a change occured. (Tested in all three view-modes)

Is it supposed to update on change?
