### ISSUE TITLE
feature: a wysiwyg review mode

### ISSUE THREAD

**Issue by semiopat** [Zettlr/Zettlr#258]
A preview mode already exist in Zettlr : right clic on a note in the tab bar activate a contextual window where you can clic on a *preview* item; but this preview activate a new window where you can see your text… in markdown, like in the editor mode (may be its only a problem on my french mojave (macOS 10.14.5) version ?).
Is it possible that the preview mode show us a wysiwyg preview ? More, could you assign a keyboard shortcut to this wysiwyg preview function ?

**Comment by nathanlesage** [comment]
I left the preview plugins fully deactivated due to the fact that one should be able to copy the text out of the QuickLooks, which is easier if you see the full source code (remember Zettlr has a strict and strong focus on transparency, of you knowing what you actually write, not as Word does it, for instance). I mean I could offer a WYSIWYG-shortcut on the QuickLook windows, if that's what many of you want.

**Comment by semiopat** [comment]
I don’t think that giving a wysiwyg QuickLook window is changing the philosophy of transparency of Zettlr. It’s not like a mixed view of markdown and wysiwyg as it could be in Typora or MarkText, that changes fundamentaly the philosophy of markdown and light markup languages. 
But having a way to preview the result of the markdown code helps in the process of writing (as it helps to preview webpage on a code editor, and many editor implement their own preview mode), to verify if my code is good, or fully rendered by the app. For example, it could be better to see how a table/footnote/etc. is displayed while you’re writing it, as many markdown apps don’t render the table/footnote/etc. the same way. As my files are often created in a app, fully written in another and finalised sometimes in a third, it could be very useful to verify how they’re displayed.

**Comment by Miljanikus** [comment]
I have a large number of notes and documents in markdown files, and I mainly use Zettlr both for writing and for organizing and reviewing records, and to a lesser extent for publishing in other formats. It seems to me very meaningful besides the source code of the editor's mod to have a preview of the formatted text without markdown syntax. The rendering of formatted text while writing, as in the Mark Text Editor, looks like a good extra option. In this way, everyone could choose the editor mode and adjust the program to their workflow.

**Comment by nathanlesage** [comment]
@Miljanikus As i mentioned in your other issue, there's currently a WYSIWYG-module in the making, which I'll be activating once I've completed some more serious refactoring work! :)

**Comment by Miljanikus** [comment]
Tnx!

**Comment by jonas-sk** [comment]
Just wanted to add that it seems like many Markdown editors are based on the idea of "write it once, publish it elsewhere", whereby you write your text in an editor with a monospace font and all Markdown syntax visible without any (or very little) WYSIWYM/WYSIWYG features. This might work for blog posts but it's terrible for any workflows where you revisit what you wrote (regularly) in the editor. This occurs most commonly when taking notes and that is also the reason why I like Typora so much.

So, it's great that you are taking care of that. Do you have any ETA?

**Comment by nathanlesage** [comment]
I seldomly do ETAs, because a plentitude of factors determine the development speed, among them my interest in certain features, the simplicity/complexity of them, and most of all, my time. So I can't tell you when it'll come.

**Comment by enjoysmath** [comment]
@semiopat There is no "note in the tab" bar which you can click.  I have no idea how to enable preview.  I had downloaded and installed and thought this was a WYSIWYG editor like StackEdit.io but local.  ...?

**Comment by nathanlesage** [comment]
Zettlr has never been purely WYSIWYG, but you can enable various renderers to make it more so. I would like to invite you to read the documentation: https://docs.zettlr.com/en/reference/settings/#display
