### ISSUE TITLE
[Bug] ID's don't show up in double brackets after making a new file from link

### ISSUE THREAD

**Issue by alpcantal** [Zettlr/Zettlr#2582]
### Description

When I created a new file and started following a link that leads to a nonexistent file, the double bracket autosuggest stops working.

### Reproducing

I don't know if this only applies to a new directory, but here's what I did:

- Create a new file
- Create a link with ID + full filename within brackets
- Click on the link
- Try using double brackets — nothing pops up

### Zettlr Version

Beta (if applicable)

### Specify version

Release v2.0.0-beta.5

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

I actually don't know about this, sorry

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Just checked the exact workflow and it works. I guess it now works thanks to some improvements in the autocompletion plugin!
