### ISSUE TITLE
[Bug] Indented code block not working

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2583]
### Description

Indented code blocks are not rendering properly.

### Reproducing

Use four spaces

### Zettlr Version

Right off the develop branch

### Your Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.1 AKA Ubuntu 20.04

### Additional Information

Followup to #2374 #2527

**Comment by Redsandro** [comment]
@nathanlesage I tried a couple of times, but I keep getting render errors when forking from latest dev. E.g.:

```bash
ERROR in source/common/util/extract-citations.ts:211:32
TS2550: Property 'matchAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.
    209 |   const retValue = []
    210 |
  > 211 |   for (const match of markdown.matchAll(citationRE)) {
        |                                ^^^^^^^^
    212 |     let from = match.index as number // Here we know index will be set
    213 |     let to = from + match[0].length
    214 |     const citations = []
```

Is this a known issue? Is this a problem on my end? Do you know how I can work around this?

**Comment by Redsandro** [comment]
> run `yarn install --frozen-lockfile`

That was it :blush: 
Sometimes I'm smart. I promise.

**Comment by nathanlesage** [comment]
Even I forget to run this command *even though I'm the one merging the dependabot PRs*, so no worries :D
