### ISSUE TITLE
Unable to add @ symbol using Turkish F keyboard layout

### ISSUE THREAD

**Issue by gokserg** [Zettlr/Zettlr#259]
## Description
When using Turkish F keyboard layout, if user enters Opt/Alt+F (which is assigned to @ symbol) to enter references, the cursor moves to next word instead of entering @ symbol.

## Reproducing
The issue could reproduced by changing keyboard layout to Turkish F (not the legacy version), and entering Opt/Alt+F.

## Expected behaviour
The keyboard shortcut Opt/Alt+F could be reassigned or overridden.

**Screenshots**

## Platform
macOS 10.14.5
Zettlr 1.3.0

**Comment by nathanlesage** [comment]
Thanks for opening up the issue!

I just took a deeper look. On Windows, the shortcut is not preset and on macOS you can achieve the same by using `Cmd+ArrowRight`. Additionally, I'll kick out `Alt+B`, as it's the opposite, and again only set on macOS, where you can use `Cmd+ArrowLeft` instead.

Will come in the next beta!

**Comment by nathanlesage** [comment]
Aaaaaand here we go!

**Comment by gokserg** [comment]
Many thanks!
