### ISSUE TITLE
Opening home directory/rejecting contacts.app permissions causes the app to be unusable, even after reinstallation

### ISSUE THREAD

**Issue by zackbatist** [Zettlr/Zettlr#260]
## Description
I'm experiencing some very strange issues relating to opening and reading the contents of directories, which somehow also relates to requests to read from my address book. The app is completely unusable now, even with a fresh install, since I think Zettlr is trying to read some system files, specifically pertaining to address book / contacts.app permissions, in ways that cause it to crash.

## Reproducing
This started when I tried opening the home directory using the 'open existing directory' button in the top left. I already had the Desktop opened in the sidebar, which is within the home directory. I remember being prompted to give permission for Zettlr to read data from the Contacts.app, which I rejected. As I recall, the dialog to select directories/files then popped up as expected, but a few things were different. First I could not select files, only directories (I forget if this is actually expected behaviour), and secondly the icon for the home directory (the little house icon) was missing. This missing icon persists, see screenshot 4. I got some errors whose contents I can't really remember, probably relating to JavaScript, and then I quit the app and restarted it. Then when reopening the app each time now, even after removing and reinstalling it, I get the same error message, as documented in the first screenshot below. Moreover, I get another error message, in screenshot 2, when I navigate to another window and then go back to the Zettlr app by selecting its icon in the dock, but this behaviour is more sporadic and less predictable. Additionally, as documented in screenshot 3, when trying to save a new file I'm prompted to save it as though the app is quitting, and when I click the save button it just reappears and does not actually save anything.

## Expected behaviour
Open directory, save file, initiate the app as a stable program

**Screenshots**
<img width="1680" alt="Screen Shot 2019-07-03 at 12 29 56 PM" src="https://user-images.githubusercontent.com/6233250/60608944-94455780-9d8e-11e9-984e-37ed57cd55d0.png">
<img width="1680" alt="Screen Shot 2019-07-03 at 12 20 01 PM" src="https://user-images.githubusercontent.com/6233250/60608964-9d362900-9d8e-11e9-83a3-361ec481fb53.png">
<img width="1680" alt="Screen Shot 2019-07-03 at 12 24 23 PM" src="https://user-images.githubusercontent.com/6233250/60608989-a58e6400-9d8e-11e9-98e8-46e37986d8e4.png">
<img width="1680" alt="Screen Shot 2019-07-03 at 12 30 04 PM" src="https://user-images.githubusercontent.com/6233250/60608996-aaebae80-9d8e-11e9-8a65-29dd0a500882.png">

## Platform
 - OS: MacOS Mojave
 - OS 10.14.5 (18F132)
 - Zettlr Version 1.3.0 (1.3.0)
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information
I apologize for this somewhat rambly bug report. I really love this app and it's a shame that I can't use it anymore. If you have suggestions for a workaround, such as ways to correct the system files which Zettlr seems to be trying to read, I'd love to hear about them so I can continue to use the app while a more permanent fix is being worked on.

**Comment by nathanlesage** [comment]
Sounds as if in there's the AddressBook-directory in the open paths of the configuration. Zettlr does not try to read these files at all, so it must've gotten there accidentally. Please try the following solution:

1. Open a finder window
2. Click on the "Go" menu item
3. Hold down "Option" and click on "Library"
4. Navigate to "Application Support" -> "zettlr"
5. Remove the "config.json"
6. Try to start Zettlr again

**Comment by nathanlesage** [comment]
Additionally, as I just saw that:

> This started when I tried opening the home directory using the 'open existing directory' button in the top left. 

Please don't do that. Zettlr recursively reads in ALL files and folders within such root directories. Zettlr is not meant to open the home directory directly.

**Comment by nathanlesage** [comment]
Attached patch prevents opening of the full home directory in the future.

**Comment by zackbatist** [comment]
Thank you, I appreciate your help.
