### ISSUE TITLE
[Bug] Ctrl+Shift+F shows global search box, but does not give it focus

### ISSUE THREAD

**Issue by usedbytes** [Zettlr/Zettlr#2605]
### Description

When I press "Ctrl+Shift+F", the global search shows in the sidebar, but it does not receive focus, so I have to manually click on the search box.

The [docs indicate](https://docs.zettlr.com/en/core/search/#searching-globally) that receiving focus is the intention, and would be much more useful/usable (and I think it worked this way for me on v1.x):

> The search input in the toolbar will receive focus

### Reproducing

* Press Ctrl+Shift+F
* Global search shows on the left
* The "Find ..." box is not focussed

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.5

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

This was also the case on an earlier v2 nightly, though I didn't write down my version I'm afraid.
I haven't used a v2 which doesn't have this issue (only tried Windows 10 on arm64)

**Comment by nathanlesage** [comment]
The docs are currently outdated because I couldn't adapt them to 2.0 yet. But the global search receiving focus would indeed be great, yes.
