### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JetV** [Zettlr/Zettlr#2613]
### Description

Footnotes not hooked in MD. I wrote [^1] in a text block, then wrote [^1]: footnote 1 text, but I do not see footnotes text when mouse over footnote reference. Moreover in another text footnotes mechanism working.

### Reproducing

This behavior occurs when paragraphs are not exactly tabulated (very difficult to track).

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 7

**Comment by nathanlesage** [comment]
> This behavior occurs when paragraphs are not exactly tabulated (very difficult to track).

Could you be a little bit more specific as to what this refers to? Maybe a piece of text which is malfunctioning?

**Comment by JetV** [comment]
Thanks for the answer!
This behavior occurs when a block of text is offset 1-2-3 spaces from the starting tab position (for example, in a long document with several paragraphs).
You can put a footnote [^x], but you cannot attach text to it using the corresponding label [^x]: below.

**Comment by nathanlesage** [comment]
Closing as it's both an unsupported version and there is too few info available to fix this.
