### ISSUE TITLE
[Bug] Zettlr on Fedora freezes on start when a Windows drive with Zettlr is mounted.

### ISSUE THREAD

**Issue by aljohnston112** [Zettlr/Zettlr#2617]
### Description

When the Windows drive is mounted, Zettlr starts and is listed in the process list, but the GUI never pops up. Not only that; if you open a markdown file, it will open the GUI and work for a little, then start to lag, and then throw a JavaScript exception and freeze. I will try to replicate to get the error message. It said something about a cyclical reference and listed a Windows folder. 
After these event, I unmounted the Windows drive despite Zettlr's hold on it, and Zettlr became responsive.

### Reproducing

This needs two hard drives on a motherboard. One with Windows 10 and the other with Fedora 34.
Install Zettler on Windows 10.
Install Zettlr on Fedora 34.
It may or may not be necessary to create notes on each drive.
Start Fedora and mount the Windows drive.
Start Zettlr.
This is where Zettlr doesn't proceed to the GUI.
Open a markdown file. This will open the GUI which will work for a little, become unresponsive, and then throw an exception.
Unmount the Windows drive. This will make Zettlr responsive. 

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 34 and Windows 10

**Comment by nathanlesage** [comment]
Aaaaaah. Okay, if I get your setup right, you have some folder or file loaded, which contains somewhere a symlink into the ProgramData directory of the windows machine. And there is an erroneous symbolic link that points from this appdata dir to its parent.

I recommend you attempt to delete the settings file (only the `config.json`, see https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app) and then open Zettlr anew. It should load without any folders opened. Then it should stay responsive whether or not the Windows drive is mounted. Then begin to re-add folders until Zettlr becomes unresponsive again. Then you have the faulty folder where there is this faulty symlink.

**Comment by aljohnston112** [comment]
I am not very familiar with symlinks, but there are several on the Windows hard drive for some reason. I must have accidentally opened ProgramData once. It does indeed perform the behavior described above if I open ProgramData.

**Comment by nathanlesage** [comment]
Closing this issue due to its age. Should this problem still occur on the most recent betas, please comment.
