### ISSUE TITLE
REQUEST: right-click offers to "Show in Finder"

### ISSUE THREAD

**Issue by jrennstich** [Zettlr/Zettlr#262]
## Description
This is a feature request. Similar to options in iA Writer or Typora, it would be extremely helpful to be able to be able to gain access to documents in the Mac Finder directly through Zettlr. Typically this is done through: Right-click on file > select "Open in Finder" > switch to Finder, selected file in Folder(s).

This would be very helpful, because I am using Zettlr in a mixed app environment. In order to edit documents using iOS I am storing them in iCloud, editing them in iA Writer and using files for further editing in RStudio.

In mixed App use environments it is simply helpful to gain access to files this way. Thanks for considering!

**Comment by nathanlesage** [comment]
Shouldn't prove too difficult, so yeah, no problem!

**Comment by jrennstich** [comment]
Klasse! Thanks!

**Comment by samarulmeu** [comment]
This will be nice until a duplicate option for files will be available.

**Comment by nathanlesage** [comment]
The duplicate option is also something that I'll be implementing. I don't even know why I didn't do that before =D

**Comment by SebastianGrans** [comment]
I also want to suggest "Open in new window". Because I often want to work with multiple documents at once, and it would be convenient to simply switch between windows. 

(Maybe this is already a feature that I can't find?)

**Comment by nathanlesage** [comment]
@SebastianGrans Nah, it's not implemented, but have a look at this issue: #243

**Comment by nathanlesage** [comment]
Done.

**Comment by samarulmeu** [comment]
In my linux version *Show in Finder* appears as `menu.show_file`.

**Comment by nathanlesage** [comment]
Yep, because it's a new string, it needs to be translated first …

**Comment by samarulmeu** [comment]
Using English it's the same.

**Comment by nathanlesage** [comment]
Strange, for me it's working — and I've updated the English translations. Did the translations on your computer update recently? After an update of the languages the app needs a restart in any case …

**Comment by samarulmeu** [comment]
You were right. I had some trouble with translation updates. Thanks!

**Comment by nathanlesage** [comment]
Alright, good to hear it worked out :)
