### ISSUE TITLE
[Bug] Bibliography in YAML frontmatter not working

### ISSUE THREAD

**Issue by dometto** [Zettlr/Zettlr#2622]
### Description

When using `bibliography: database.bib`, in the YAML frontmatter, citations are not rendered upon export to any format (in PDF, they are rendered as e.g. `(ripsteinForceFreedom2010?)`, as if BibTex can't find the citation).

Additionally, when you don't have a central Citation Database selected, attempting to export will generate an error. The precise error depends on the export format. When exporting to PDF, the error is:

```
ERR_FILE_NOT_FOUND (-6) loading 'file:///Users/user/foo/main.html'
```

When exporting to PDF XeLaTeX, it is:

```
An error occurred on export: File database.bib not found in resource path


File database.bib not found in resource path
```

### Reproducing

1. use `bibliography: database.bib` in YAML frontmatter
2. export to any format

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta5

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Mojave

**Comment by nathanlesage** [comment]
> Note that citation suggestions in the editor are appearing when setting the bibligraphy: key.

This indicates that this might rather be an error on the side of Pandoc. Zettlr does very little processing to database files so it's less susceptible to errors in there. The error you describe almost sounds as if there is some remote file (this `file:///Users` thing) which cannot be found. But I might be wrong.

Does the database work if you instead specify it in the global database settings and remove the bibliography key?

**Comment by dometto** [comment]
When unchecking the `Use internal pandoc` setting, the problem is unfortuntely still present. Is there anything I can do to provide more debug output?

**Comment by nathanlesage** [comment]
> And yes, when I select database.bib as the global citation database, everything renders fine.

Hm, I have to observe this.

**Comment by dometto** [comment]
The problem disappeared after upgrading to `v2.0` (possibly my previous installation was corrupted).
