### ISSUE TITLE
[Feature] Markdown Support Superscript/Subscript

### ISSUE THREAD

**Issue by BsNoSi** [Zettlr/Zettlr#2628]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [ ] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

see [pandoc feature](https://pandoc.org/MANUAL.html#superscripts-and-subscripts)

`^Super^script` → <sup>Super</sup>script
`~Sub~script` → <sub>Sub</sub>script

### Example Workflow

For example, if I need to write the formula for H<sub>2</sub>0, the markup "H\~2\~0"<sup>a</sup> is less distracting in the text and quicker to type than "H\<sub>2\</sub>", right?

<sup>a</sup> Currently, this collides with markdown of GitHub, where "\~…\~" is used for strikeout. Pandoc (and Zettlr) requires `\~\~strikeout\~\~` to achieve this. And this is a sample, why "\~a\~" is nicer instead of "\<sup>a\</sup>"

### Caveats

This is another softening of the "true markdown". Assuming that Zettlr will be bound to Pandoc in the future for export, it seems to be reasonable to support its formatting rules. This is less disruptive as using LaTeX commands (which is already supported) or HTML code.
This can solved by `markdown → markdown` export replacing it with HTML code. Which is, in my opinion, a worse solution in compare to this.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [ ] macOS
- [ ] Linux

### Additional Information

I read through the “developer requirements”. So I should focus on testing, bug finding/reporting and documentation. I can contribute that, as a developer I would be a “glitch”.

**Comment by BsNoSi** [comment]
(Wrong search by myself…): In addition to #309 this should/can be displayed in zettlr itself?

**Comment by nathanlesage** [comment]
Surely, but it requires a few smaller addendums, it makes most sense as a rendering plugin I think

**Comment by abclements** [comment]
Superscript and subscript should be supported by Zettlr as it is part of the markdown specification. I have tested it on MacOS and Linux and it doesn't work as expected, though other editors work as expected.
