### ISSUE TITLE
[Bug] Zoom

### ISSUE THREAD

**Issue by BsNoSi** [Zettlr/Zettlr#2634]
### Description

1. Keyboard Shortcut `STRG` `Plus` does not work (German keyboard)
2. Zoom in destructs GUI
![15-10-_2021_13-25-06](https://user-images.githubusercontent.com/2784683/137479795-80cdafd8-ad78-4ed5-91fe-69218842d56d.jpg)

### Reproducing

1. Use German KEyboard and try `STRG` `Plus`
2. Zoom in

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10pro x64

### Additional Information

Higher zoom level destructs file manager an menu, too.
![15-10-_2021_13-29-06](https://user-images.githubusercontent.com/2784683/137480221-be96edc4-9da8-446c-a692-e3090f4887fa.jpg)
![15-10-_2021_13-28-52](https://user-images.githubusercontent.com/2784683/137480264-25c5e897-abfb-4750-b2f5-f34563fc07ad.jpg)
(Possibly one reason, why other programs only zoom text instead of GUI).

**Comment by xplmr** [comment]
I couldn't replicate the second bug, but the first one is also an issue for me: At least zoom in doesn't work via hot keys. It also doesnt work with the mouse wheel. (And scrolling with the mouse wheel is suddenly also very slow for me. Touchpad and arrow keys work fine though). Apart from that, I really love the new version! Thank you so much.

**Comment by BsNoSi** [comment]
https://user-images.githubusercontent.com/2784683/137505244-a5fa2c2f-7d73-40eb-94a6-6d3c4ded7b70.mp4

**Comment by nathanlesage** [comment]
@BsNoSi Yeah. I'd argue this is not a bug, but with such a small screen size I'd rather expect to zoom out to have a little bit more screen estate...

**Comment by BsNoSi** [comment]
The challenge is a little bit more complicated. I am (typically) using a UHD 4K (3840x2160) workstation screen and a 2K-DCI (1980 x 1080) laptop screen.
And in both cases, I have (at least) two applications in use. Especially on UHD there are even more, which means, that I divide the available space into areas. This leads regularly to a window size as shown above. And there, it is a requirement to easily change font size *of content*. Which all applications *beside* Zettlr do with `Ctrl` mouse wheel (try browser, you are reading this).

- Zettlr ignores mouse wheel for sizing.
- I have to switch into `preferences`, click on `editor`, scroll down to `Editor font size`, type in an expected size that fit my need in the current situation, close dialog – and recognize, that my estimation of font size was wrong.

Possibly, these are two different things:
- Zoom *GUI* is something, that is useful but (in my opinion) nothing that I do every few minutes. 
- Zoom *editor font size* is currently cumbersome to reach for those (like me) used to constantly adjust *reading needs*.

As a result of this, it is not a bug, but an *improvable* feature:

- Commands for scaling *editor text font* on the fly (→ `Ctrl` mouse wheel,  `Ctrl` `+`, `Ctrl` `+` ) are missing (`Font +`, `Font -`).
- `Zoom in` `Zoom out` may be better described with `GUI +` , `GUI -`  (`Shift` `Ctrl` `+`|`-`)

Then it would align to the usual behaviour (on Windows, don't know behaviour of Linux/Mac) *and* offeres a (truly) nice feature, to resize program gui elements.

**Comment by BsNoSi** [comment]
I have been involved in software development for a very long time now. Typically, concepts prevail because they are popular. Therefore, it is hard to believe for me, that so many programs (browser, editors, text processors, graphic programs, pdf viewer, …) use `Shift` Mouse wheel for *content sizing*, ignoring »so many people complaining« about it. 

Honestly, this is one reason,  I'm thinking of uninstalling Zettlr and getting back to my productive work. In a productivity process it is heavily disturbing, having the same keyboard shortcuts or actions with different behaviour in a single program or requiring different ones for same behaviour.

Other reasons speaking (currently) against Zettlr (for me, if I can not solve them today) will be part of another comment to come – to keep focus in this thread.

**Comment by BsNoSi** [comment]
Everything is fine. If I were not a patient one, you would not receive comments from me. Sorrily, I can only support with investigation and not with development – I am too far away from Electron.

But nevertheless, I have to bring a process up and running, I was taking Zettlr into account, as possible part of it. But 
after roundabout one week of testing, I am close to the point, that Zettlr may be unsuitable for this. The main reason is not Zettlr itself: I am struggling with high instability of post-processing of Pandoc/Tex and requirement of using latex inside texts – which contradicts the concept of Markdown

**Comment by nathanlesage** [comment]
I guess the summary of the problems you describe with Zettlr can be subsumed under "Pandoc can be hard sometimes", I guess that's part of its technical debt, and even Zettlr, as well as its Pandoc integration is already, is far from making working with Pandoc easy. But I'm confident we'll get there someday.

**Comment by BsNoSi** [comment]
… and – as a refinement – an option to increase/decrease *content* only.

**Comment by guerrajose** [comment]
To go back also to the original issue, I am also struggling with keyboard shortcuts, including for zoom:

* I run Debian 10 KDE and Zettlr 2.0.1.
* I am using a French Keyboard layout (Azerty)
* **I can zoom in** with `Ctrl + Plus` ; **but can't zoom out** with `Ctrl + -`
* Using the **menu `View/Zoom in` and `View/Zoom out` is functional.**

But... **I can't use the menu in the "quicklook" windows, thus I can never zoom out in these "quicklook" windows...**

_In previous versions, using the mouse wheel with `Ctrl` was functional to zoom in and out._

This is only **one of the shortcuts which don't work on my computer** among others (I don't tested anything): `Ctrl + !` doesn't work; `Ctrl + ?` doesn't work

Yet, I still use Zettlr almost every day, because this is a great piece of software, thank you.

**Comment by nathanlesage** [comment]
> I can't use the menu in the "quicklook" windows, thus I can never zoom out in these "quicklook" windows...

This whole thing is another story, because we might want to at some point add custom menus **per window** as opposed to one menu for the whole app (as it is now) …

**Comment by guerrajose** [comment]
> This whole thing is another story

Well my point was that currently the zoom functionality of the quicklook windows is broken for me due to these shortcut problems. Menu per window will be nice though.

**Comment by sam9032** [comment]
@nathanlesage The new function to select whether to zoom everything or only the text is amazing, thank you! 
No more broken interface on my small laptop screen :tada: 

Bringing back the ctrl+scroll would be amazing, just a littlebit faster than ctrl+shift+plus for me and since the keyboard shortcut seems to be different in different keyboard languages, it would enable a more consistent option to zoom.

**Comment by nathanlesage** [comment]
> Is there a way to zoom the interface if I switched to "zoom the editor font size"?
> The shortcut and the entry in the view menu both changes the font size..

No, the toggle in the settings switches both (the shortcuts basically "click" the menu items).

With regard to scroll zoom, that is likely also coming back

> seems to be different in different keyboard languages

That's an unfortunate shortcoming of Electron, for which I have not yet found a good way to resolve
