### ISSUE TITLE
[Bug] Hotkey for File Rename not working (W10, QWERTZ German keyboard)

### ISSUE THREAD

**Issue by ItsFullOfCode** [Zettlr/Zettlr#2639]
### Description

Renaming a file using the hotkey Ctrl+R works only if no Rename action has happened before during the session. Once a file has been renamed (either by context menu or Ctrl+R hotkey), it is not possible to subsequently rename the same or other files using the Ctrl+R hotkey. Pressing the hotkey doesn't activate the filename for renaming. Renaming any file using the context menu is still possible.
Exception: the very first file under the root work directory can still be renamed using Ctrl+R.
After restarting Zettlr Ctrl+R works as anticipated until the first file rename has been executed.

### Reproducing

- Start Zettlr
- [Set File Manager Mode to combined]
- Select any file in the File Manager
- Press Ctrl+R
- Rename the file: works as anticipated
- Press Ctrl+R again on the same file: rename does not work
- Press Ctrl+R on any other file except the first one under the root node: rename does not work
- Press Ctrl+R on the first file under the root node: works as anticipated

### Zettlr Version

Stable (most recent version)

### Specify version

 2.0.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
> Unfortunately I don't have the error logs of the previous session where the problem occurred. Unless they are still available somewhere on my file system?

These logs are always written to (in your case) `%AppData%/Zettlr/logs`, if I'm not mistaken. But I mean if this was only an intermittend error, I think it might be safe to close this issue, given that you don't find any relevant error messages!

**Comment by marktermaat** [comment]
I actually have the same issue. I'm on a Mac, using 2.0.1, and even File -> Rename file doesn't work. Only when I go to the File manager (in Zettlr) and right-click on a file to rename it works.
