### ISSUE TITLE
[REQUEST] Selecting texts in the attachment pane

### ISSUE THREAD

**Issue by jakeoung** [Zettlr/Zettlr#264]
When I import some references from Zotero, I can see the list in the attachment pane. But I couldn't select the texts so that I couldn't copy. Is it possible to allow copy the texts in the attachment pane?
(P.S. Thanks for this amazing app!)

**Comment by nathanlesage** [comment]
Why would you want to select the references list from the sidebar ...? The references will be generated in your output either way!

However, if you need to, simply use this one-liner of custom CSS to achieve what you wish for:

```css
#attachments #bibliography { -webkit-user-select: text; }
```
Cheers! 🎉

**Comment by jakeoung** [comment]
Oh, thanks. I use some notes for literature review. When I search in semantic scholar, I need to put the subject and authors. I don't want to export to check the references.

**Comment by nathanlesage** [comment]
Oh, I never heard of that. But it indeed makes sense then. Thanks for the clarification!
