### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CairnsAlasdair** [Zettlr/Zettlr#2646]
### Description

I can't scroll text using pagedown pageup and arrow down/up key.
I can scroll text using bar on the right with pointing mouse and so on.

Version 1.8.9 checked, works fine.

### Reproducing

Open file which is longer than screen.
Using key Page Down, Page Up, arrow up, arrow down  try to move cursor below screen.
Cursor move below, counter of lines increments, but text does not go up.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.0.

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by Redsandro** [comment]
Keyboard scroll issue was part of #2643 and is fixed in #2641 waiting to be merged.
