### ISSUE TITLE
[REQUEST] 1.4.0-Beta: Cursor position aware line/row adding in table editor

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#265]
## Description
First let me thank you for the table editor - it's a great improvement and so far it seems to work well.
But there is an inconsistency concerning the function of the line/row add buttons at the table edges. In opposite to the line/row delete buttons they only add new lines on top/bottom or  left/right hand side of the entire table (as described in the changelog).

## Expected behaviour
The add buttons should work like the line/row delete buttons relative to the current selected table cell: The left/right add buttons should add a row in front of/behind the current cell - and analog for the top/bottom add buttons.

## Platform
 - OS: Windows
 - OS Version: 7, 10
 - Zettlr Version: 1.4.0-beta

**Comment by nathanlesage** [comment]
Ah, never thought of that approach! Good idea.

**Comment by nathanlesage** [comment]
Just implemented the desired behaviour, the add-buttons will now appear at the active cell and only add rows/cols with respect to the cell, so to add rows/cols to the table itself, it suffices to select one of the outermost cells!
