### ISSUE TITLE
[Bug] Quicklook not working on Windows

### ISSUE THREAD

**Issue by generic-user** [Zettlr/Zettlr#2668]
### Description

On a new install the quick-look window is just a blank window opening.

### Reproducing

Create a new vault, create a new note, click quick-look context menu item.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

10

**Comment by nathanlesage** [comment]
Duplicate of #2666.

Right now working on a fix.
