### ISSUE TITLE
[Bug] Wrong folder selected upon saving new file

### ISSUE THREAD

**Issue by BsNoSi** [Zettlr/Zettlr#2669]
### Description

New file opens on save wrong folder:

https://user-images.githubusercontent.com/2784683/137867775-68ce7843-6b58-4d00-9a8c-f59e524780cc.mp4

### Reproducing

see video.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10pro x64

**Comment by nathanlesage** [comment]
That has now been fixed.
