### ISSUE TITLE
Feature request: Shortcut to export and separate compile for beamer

### ISSUE THREAD

**Issue by jakeoung** [Zettlr/Zettlr#267]
I use Zettlr for making a beamer presentation from pandoc. I feel inconvenient to click the menu whenever I compile it. So it would be nice to set shortcut for the export to pdf or something.

Secondly, I need the option -t beamer and remove the option `$tpl$` to compile beamer presentation. (I don't know what tpl is) Anyway, is it possible to add one more export option for beamer? (I can change the pandoc option, but it would be good to have another option..)

Thanks,

**Comment by nathanlesage** [comment]
Just found this thing again — by modifying the command directly, you can enable beamer exports!
