### ISSUE TITLE
[Bug] In-line images are not exported

### ISSUE THREAD

**Issue by torus13** [Zettlr/Zettlr#2674]
### Description

The in-line images in md files are not exported in any format (pdf, html, etc.) anymore in 2.0.0 (both, on macOS and Linux). It worked without any issue in 1.8.9 and I haven't changed the configuration (images are saved in the Resources subfolder of the main Zettelkasten folder).

Is it necessary to do some reconfiguration in 2.0.0?

Thank you.

### Reproducing

The md file with an in-line image:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67106279/137986899-711dbd53-717b-413e-8804-70f6801b413e.png">

The image path: 

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/67106279/137987654-66622457-f350-432c-935e-0b278c22a431.png">

The configuration:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67106279/137986662-be16dc99-7fdb-402e-a876-2b65b88719cd.png">

The exported pdf file:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67106279/137987530-51b40613-860b-4a52-af57-f62d4a4e5734.png">

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Catalina (10.15.7), Debian 11

**Comment by nathanlesage** [comment]
Hm, does the print preview look normal? And: Does a docx-export look good?

**Comment by torus13** [comment]
If it might help:

When the in-line image is specified with the full path:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/67106279/138051000-89baee83-451c-453c-ba1e-bb6bff48ab37.png">


the PDF export is correct:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67106279/138051216-51aa2b89-34ed-4e34-96cb-b453f4dc35fe.png">

**Comment by nathanlesage** [comment]
> When the in-line image is specified with the full path:

I thought as much, this reminds me of the recent discussions we've had … I'll check that locally and see what is going on!
