### ISSUE TITLE
Export to pdf freezes Zettlr for a couple of minutes and other lock ups

### ISSUE THREAD

**Issue by panthia** [Zettlr/Zettlr#2677]
### Discussed in https://github.com/Zettlr/Zettlr/discussions/2676

<div type='discussions-op-text'>

<sup>Originally posted by **panthia** October 19, 2021</sup>
I just upgraded to 2.0.0 with a deb package on Ubuntu 20.04. The first thing I tried was to export to html and the program locked up for a few minutes. Same happens with export to pdf and evidently just trying to take a look at the About window also locks it up. I don't think it is my cpu AMD Ryzen 9 3900X 12-Core Processor × 24. Any suggestions? It is actually not usable at this point. 

I tried uninstall and reinstall and it took a solid 2 minutes before any of the menu items worked when I started the program.

Next tried downloading the AppImage but it behaves the same. Can't find prior version download to at least get it working again.

Upgraded my Windows 10 Zettlr and it works great there but I mostly use Linux. 

</div>

**Comment by nathanlesage** [comment]
That update loop is certainly not correct. The update check is a one-shot method (i.e. it only attempts to check once and then be done), which means that something is triggering that update check in a loop, but I cannot think of any way this is happening.

Nope, just checked, there is not a single loop. That being said, there must be something which is continuously triggering the menu item for updates ...

**Comment by panthia** [comment]
Just updated to 2.0.1. Still having same issues. Every startup has a 2 minute hang. 
[12:36:26]	[Update Provider] No new update available. Current version is v2.0.1.
[12:38:15]	[Config Provider] Writing configuration file to /home/user/.config/Zettlr/config.json...

Export still hangs up takes two minutes for the browser to show the html. Pdf also hangs up and takes two minutes to show document.  

[12:54:43]	[Export] Pandoc run successful.
[12:54:43]	Successfully exported file to /tmp/document.html
[12:56:33]	[Config Provider] Writing configuration file to /home/user/.config/Zettlr/config.json...

[13:00:36]	[Exporter] Running pdfExporter exporter ...
[13:00:36]	Successfully exported file to /tmp/document.pdf
[13:02:26]	[Config Provider] Writing configuration file to /home/user/.config/Zettlr/config.json...

**Comment by panthia** [comment]
So I was using the MATE Desktop on my system and yesterday I went back to the Ubuntu desktop and Zettlr is working as expected. It seems the issue is with the MATE Desktop.

**Comment by nathanlesage** [comment]
I think I'm going to close this issue. There hasn't been any activity and as far as I know there are more people using it on MATE who did not recently complain.

If that is a mistake and the error indeed still happens, please comment here on this issue so that I can reopen it.
