### ISSUE TITLE
[Bug] No prompting for filename 

### ISSUE THREAD

**Issue by AIBN60** [Zettlr/Zettlr#2684]
### Description

Although the checkbox "Not prompting for filename when creating new files" is NOT checked, Zettlr does not prompt for filename. The file is opened, but not saved in the directory and cannot be seen in the file manager.

When checked, there is no prompt, but the file is created in the directory (and can be seen in the file manager).

### Reproducing

Either Ctrl N or click in menu New File Markdown
when Checkbox checked: instant creation in Zettlr, listed in file manager, saved on disk
when not checked: instant creation in Zettlr, not in file manager, not saved on disk

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux 5.4.0-89-generic #100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by santidingo** [comment]
Hello!

Firstly, thank you for working on this project! I love Zettlr and use it all the time.

I'm using Windows 10 by the way. 

Perhaps I'm not following the thread well, but I will try to be helpful by explaining my experience and the order of operations.
Knowing myself, I will eventually adapt to the new method, but if it's possible to allow me to tweak my workflow, it would help a lot.

### **What I was used to:**
Before 2.0, this happened:
1. Hit CTRL + N
2. New file is created, with filename as note ID highlighted for me to change, or append
3. Hit Enter
4. File saved to disk, and saved as I go.

### **The issue**:
Now the default is:
1.  Hit CTRL + N
2. New file is created with note ID as the name; name not highlighted, not prompted to change
3. New file is held in memory
4. I must save to adjust file name
5. Must save manually

When I check the box to say "do NOT prompt for filename":
1. Hit CTRL + N
2. New file is created, with filename as note ID; name not highlighted
3. New file is saved to disk immediately
4. I must hit CTRL + R to rename (doesn't always work...?)
5. Must save manually

### **My humble suggestion:**
This might sound stupid or difficult or both, but bear with me. I do not yet understand what would honor native UX and what wouldn't.

**2 options/checkboxes**

The first checkbox says "prompt for new filename on save". This could be checked by default (if possible).

The second checkbox might say "prompt for filename before text entry". (This would not even be available if the first is not checked.) 

This could make things clearer/more intuitive. 

One normally expects a save to disk when prompted for a file name, whether before or after inputting text.

Additionally, when users explicitly choose to avoid being prompted for a name, it seems to be a reasonable expectation that the file is immediately saved to disk.

### Selfishly, this would allow my preferred workflow:
1. Hit CTRL + N
2. New file is created, with filename as note ID, and highlighted for me to change, or append
3. Hit Enter
4. File saved to disk.
5. Saved manually as I go.

**Comment by nathanlesage** [comment]
Thanks for the input! I'll implement a better solution at some point; until then please add more comments if you think something might work even better or so; I'll then implement whatever is happening in this thread to make that experience better for everyone!

**Comment by nathanlesage** [comment]
This should be fixed due to the extensive changes in preparation for 3.0.
