### ISSUE TITLE
[Bug] Cannot update automatically from version 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by nicos68** [Zettlr/Zettlr#2691]
### Description

* Run version 2.0.0 of Zettlr => A popup shows up notifying that version 2.0.1 is available
* Click on the notification popup => The "Updater" window opens
* Click on the Zettlr-2.0.1-x86_64.AppImage button => Version 2.0.1 is downloaded and the Update popup now only shows the "Click to start update" button
* Click on the "Click to start update" button
  * Expected behavior : the update continues
  * Actual behavior : An error popup appears with the message "For security reasons, launching executables is not allowed in this context."
*  Click on the "OK" button in the error popup => The Zettlr process terminates and nothing else happens.

### Reproducing

See above

### Zettlr Version

Stable (but an older version)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

linux 5.13.19-2-MANJARO with KDE plasma

**Comment by nathanlesage** [comment]
AppImages are now just opened in the folder instead of Zettlr trying to execute it.
