### ISSUE TITLE
[Bug] Can't easily add attachments into notes

### ISSUE THREAD

**Issue by praxiq** [Zettlr/Zettlr#2699]
### Description

When I drag a file from the "Other Files" sidebar into the note, it creates a link to that file using the file's _absolute_ path, even if it's in the same directory or a subdirectory, which doesn't seem like the intended behavior. 

When I drag a file from Finder into a note, then it creates a link to that file using the file's _relative_ path, which seems correct.

Neither link actually works. When either is clicked, it tries to open them in my browser with "https://" prepended.

I can manually edit the absolute url by adding "file:///" to make it work as intended - in the case of a PDF, for example, this opens the PDF in my default PDF editor. The relative url doesn't seem to work no matter what I do.

I can't find any way to create a usable link to a file other than with a "file:///" url and an absolute path, which isn't very portable.

### Reproducing

Drag a file from the "Other Files" sidebar or the Finder / Explorer into a note. Activate the link by cmd/ctrl clicking.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

11.2.3

**Comment by Glunk** [comment]
For the relative path to work, you should add `file://` and not `file:///` before the file name.  
But indeed, it would be better not to have to add it manually. As you said, with the file name without the `file://`, it is interpreted as a http url and opened by the browser.

**Comment by nathanlesage** [comment]
> When I drag a file from Finder into a note, then it creates a link to that file using the file's relative path, which seems correct.

This is an important observation, as this tells us that that handler works as expected

> I can manually edit the absolute url by adding "file:///" to make it work as intended

That should be a piece of cake.

As always, if someone wants to open a PR for this, feel free to!

**Comment by praxiq** [comment]
> That should be a piece of cake.

> As always, if someone wants to open a PR for this, feel free to!

What is the intended behavior? I'm guessing that it should be possible to create a link to a file using a relative path instead of a url, and that clicking the link would open the file? Links to markdown files already work this way, as do embedded images. So I guess the fix would have two parts:

1. Dragging a file from the "Other Files" sidebar should insert a link or image with a relative path, not an absolute path, just like dragging a file from the MacOS Finder already does.
2. Clicking a link without any URL scheme should attempt to interpret the link as a (possibly relative) path, instead of assuming it's a URL and sending it to a browser.
