### ISSUE TITLE
[Feature] Snippet variable for Zettelkasten ID based on file id

### ISSUE THREAD

**Issue by tafli** [Zettlr/Zettlr#2702]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Really like the new snippet functionality. One thing I miss is next to the snippet variable `$ZKN_ID` a variable that (instead of creating a new ID) takes the ZKN ID from the given file name (when available).

### Example Workflow

When creating a new Zettelkasten note, the file is automatically named with a generated ZKN_ID like `<ID>.md`. Using a snippet with variable like `$ZKN_FILE_ID` will take the ID from the filename and inserts it at the given position. If no ID from the filename can be taken, a new ID can be generated.

### Caveats

None

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by devhell** [comment]
I've just noticed something that is probably relevant to this. After I create a new file (default naming scheme by Zettlr, i.e., date and time), I tend to add a YAML snippet (using the excellent snippet functionality) which also adds the `id: $ZKN_ID` field in my YAML frontmatter. 

The `$ZKN_ID`, however, is _not_ the same as the ID given to the file. This is hugely confusing (at least to me). Is this on purpose or is it a bug? Thank you!

**Comment by tafli** [comment]
> I've just noticed something that is probably relevant to this. After I create a new file (default naming scheme by Zettlr, i.e., date and time), I tend to add a YAML snippet (using the excellent snippet functionality) which also adds the `id: $ZKN_ID` field in my YAML frontmatter.
> 
> The `$ZKN_ID`, however, is _not_ the same as the ID given to the file. This is hugely confusing (at least to me). Is this on purpose or is it a bug? Thank you!
> 

I do the same and this is the behaviour I also noticed. It is clearly not a bug as the [documentation](https://docs.zettlr.com/en/core/snippets/) says it "generates a Zettelkasten ID (according to your pattern)". For my understanding, this means it creates a new ID exactly as of now.
So this request is to take the file ID into account instead of creating a new one.

**Comment by nathanlesage** [comment]
@devhell: As @tafli writes, currently it's just generating a new one instead of using the filename. This is kind of a limitation within the implementation because I first have to somehow give the snippets manager access to the file descriptor. Have to think about that because it's a bigger change, and is less high in priority than the rewriting of the full autocomplete feature (the snippets was what prompted me to plan the refactoring in the first place because in the autocomplete plugin there's a lot of code which doesn't belong there)

**Comment by lcsolano** [comment]
> > I've just noticed something that is probably relevant to this. After I create a new file (default naming scheme by Zettlr, i.e., date and time), I tend to add a YAML snippet (using the excellent snippet functionality) which also adds the `id: $ZKN_ID` field in my YAML frontmatter.
> > The `$ZKN_ID`, however, is _not_ the same as the ID given to the file. This is hugely confusing (at least to me). Is this on purpose or is it a bug? Thank you!
> > EDIT: I should clarify that the snippet is entered a few seconds after the file has been created, hence the ID discrepancy.
> 
> The problem still exists in Version 2.3.0.
> 
> ![Bildschirmfoto_2023-06-09_10-14-17](https://user-images.githubusercontent.com/133958042/244635144-99568d5b-3aad-4a74-9e6b-89e0452317e5.png)

Think about file names being a completely different thing than IDs.  You are using the same YearMonthDay... for both filenames and IDs, so the look the same **but**, they don't have to.

I decided to forget at all about file names and to use only IDs to links, so I use uuid4 format for filenames. This filenames and the IDs looks different.

Using uuid4 for filenames forced me not to pay attention to filenames anymore as they dont have any meaning.

There are some blogs that talks about this. Some people prefer to use filenames to links in case they migrate to another tool and is a valid argument too.

**Comment by natalieavene** [comment]
Yeah, struggled with YAML as well. What variable represents the original ID.... in documents its the 
⌘/Ctrl+⇧+L | Copy current Zettelkasten ID?

**Comment by lcsolano** [comment]
> Yeah, struggled with YAML as well. What variable represents the original ID.... in documents its the ⌘/Ctrl+⇧+L | Copy current Zettelkasten ID?

Notes do not haven an original ID. The ID is anything you want, you can even set  it up manually.

In general, IDs are created with the `YearMonthDayHourMinuteSeconds` (4+2+2+2+2+2=14 digits) format and Zettlr is configured to detect a 14 consecutive digits as the ID.

If you don't create the ID with a snipped, you can created it using `CTRL+L` at anytime and it will be generated using that YearMonth... format, as it's defined in the Zettelkasten configuration.

But you can do it manually. 

So if for example you have this in thre YAML Frontmatter:

```
---
title: "This is the title"
id: 12345677654321
```

That will be the ID for the note.

If you press `CTRL+SHIFT+L` it will place `12345677654321` in the clipboard to paste it. And if you run a snipped after that ID is created, the snipped will use that ID in the `$CURRENT_ID` variable.

You can link that note from another note with that ID.

The same for filenames, for IDs: the format doesn't matter.

If from another note you want to link a a nothe with the YAML above, you just type `[[This is...` and it will auto complete the ID.

**Comment by lcsolano** [comment]
By the way, in current versions you can now achieve what the original post wanted: to create the ID identical to the file name:

1. Create a file
2. Save it
3. Run a snipped to write in the YAML frontmatter: `id: $FILENAME`

Note that the `$ZKN_ID` is to **create** a new ID. If you already created it (with the snipped for example) the variable you must use is `CURRENT_ID`
