### ISSUE TITLE
[Bug] References do not always show in sidebar

### ISSUE THREAD

**Issue by cobblepot1** [Zettlr/Zettlr#2705]
### Description

When opening a document and trying to show references in the sidebar, they do not always appear. Instead it says "There are no citations in this document"

### Reproducing

1. Open the sidebar and choose to show the "Table of Contents" tab
2. Close the right sidebar
3. Select a document with citations in the left sidebar that has not been opened during this Zettlr session
4. Open the right sidebar, ToC tab should be selected
5. Click the "References" tab - no citations show up
6. Leaving the sidebar open, select a different document in the left sidebar, see the references
7. Re-select the first document, the references now appear

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 10

**Comment by BabakFarshchian** [comment]
This is fixed for startup scenario, but still happens for newly created notes. This is what happens:

* Create a new note.
* Add keywords.
* Click on sidebar, choose related files.
* It is empty.
* Switch to another note.
* Back to the new note, all related files are there!
