### ISSUE TITLE
[Request] 1.4.0-beta: Avoid unnecessary '.ztr-directory'-files

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#272]
## Description
I recently realized that Zettlr ALWAYS creates a '.ztr-directory'-file in every opened directory and all related subdirectories - only to store the directory specific file sort order. This I think is a bit too much since this way a clean dokument filing sturcture is needlessly flooded with program specific files.
Yes, I truly see the idea behind this approach - mainly when it comes to special things like virtual directories and so on, but for the more 'trivial' things I really would prefer a solution without extra files.

## Expected behaviour
So why not make a new 'directories'-tab in the preferences to adjust all the global directory settings (e.g. file sort order, etc.) and store them in the program specific directory/file (e.g. config.json). And only create a '.ztr-directory'-file to override appropriate settings of some directories with special requirements if needed.

## Platform
 - OS: Windows
 - OS Version: 7, 10
 - Zettlr Version: 1.4.0-beta

## Additional information
BTW - the behavior NOT to write all these program specific '.'-files and -directories everywhere in the document structure is one of the reasons for me switching over to Zettlr from TagSpaces.

**Comment by nathanlesage** [comment]
> So why not make a new 'directories'-tab in the preferences to adjust all the global directory settings (e.g. file sort order, etc.) and store them in the program specific directory/file (e.g. config.json). And only create a '.ztr-directory'-file to override appropriate settings of some directories with special requirements if needed.

This is precisely the idea behind them. What's still missing is an additional check of whether or not the directory settings equal the default settings, and, if they do, don't save a file. If they divert from the built-in defaults, then save a file.

**Comment by nathanlesage** [comment]
Consider it done!
