### ISSUE TITLE
[Bug] Captions written in the image caption box are not saved if the image is clicked on

### ISSUE THREAD

**Issue by irmoodie** [Zettlr/Zettlr#2736]
### Description

When including an image such as:

`![](https://upload.wikimedia.org/wikipedia/commons/3/33/Zettelkasten_%28514941699%29.jpg)`

And then adding a caption via the black box that appears on the rendered image in Zettlr. If the image is clicked upon, as to go from the rendered image back to the link text, the caption is not saved. I would expect the caption to be saved as:

`![my caption should be saved here](https://upload.wikimedia.org/wikipedia/commons/3/33/Zettelkasten_%28514941699%29.jpg)`

If the caption is entered while the image is not rendered, by writing it between the `[ ]`, then it is retained if the image is clicked on to return to the code.

### Reproducing

- Paste `![](https://upload.wikimedia.org/wikipedia/commons/3/33/Zettelkasten_%28514941699%29.jpg)`
- Press enter to go to new line, the image is then rendered.
- Edit the caption in the black box that appears on the image.
- Click on the image as to return to the link text.
- Caption was not saved.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Currently the caption is only applied when you press Enter. Should be straight forward to also trigger on focus-out events.
