### ISSUE TITLE
[Enhancement] Tags in the tag cloud do not need to show the leading '#' 

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#2737]
### Description

Showing a leading '#' on every tag in the tag cloud is pointless. It increases visual clutter, makes it harder to scan for tags by "shape", and wastes vital space. It's also unnecessary, as the leading '#' is assumed for tags and they are visually distinguished from regular text anyway.
![image](https://user-images.githubusercontent.com/51254/139530906-33dec5f8-1af9-4f52-8604-a54bead31b05.png)

### Proposed Changes

remove the leading '#' when displaying tags in the tag cloud, just like the code already does when listing suggested tags.

### Caveats

Can't think of any right now

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I see your point, seems like a good fix, yes
