### ISSUE TITLE
[Enhancement] The Assets Manager edit pane should resize with the enclosing window

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#2738]
### Description

Although the Assets Manager is just about usable, it is annoying that the edit panel is a fixed size and always requires scrolling and "keyhole surgery", even on a large screen. The enclosing window can be resized but the end result is just a large area of pointless blank space rather than adjusting the size of the edit panel.

### Proposed Changes

Resize the Assets Manager edit panel when the Assets Manager window is resized

### Caveats

There is a bit of complexity, as the "Save" and "Restore Defaults" buttons will also need to move, but arguably these should be positioned relative to the bottom of the window rather than the top anyway.

### Do you Wish to Attempt Implementing this Yourself?

No

### Your Platform

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by nathanlesage** [comment]
The problem is that it's super hard to make it resize vertically — this behavior annoys me as well, but CSS can be hard sometimes :D As soon as I find a way to do so I'll implement it (if anybody else has a good idea, feel free to open a PR). Rest assured this annoys me as well!

**Comment by nathanlesage** [comment]
Uhh, I fixed that in some of the more recent versions!
