### ISSUE TITLE
[Bug] Zettlr treats a 3-character tag that uses hex digit representations (0-9,a-f) as text, not a tag. 

### ISSUE THREAD

**Issue by rpace314159** [Zettlr/Zettlr#2742]
### Description

Zettlr treats a 3-character tag using hex digit representations (0-9, a-f, A-F) as text and not a tag. . 
For  example, \#12a or \#dbb or \#abc are not honored as tags. but \#12g, or \#dbh or \#abz are treated as tags. 
I discovered this when I was creating a document about an IBM product call **Dependency Based Build** and a common acronym for this product is **DBB**.  So I tried setting a tag \#DBB and Zettlr  did not honor it as a tag - it treats it as text. 

### Reproducing

Try setting a 3-character tag using any of these characters -- 0-9, a-f, A-F.
- \#DBB is treated as **text**.
- \#DBBB is treated as a tag.
- \#DB is treated as a tag.
- \#abc is treated as **text**. 
- \#abcd is treated as a tag. 
- \#abg is treated as a tag. 
- \#ab is treated as a tag.
- \#aaa is treated as **text**
- \#aaaa is treated as a tag. 
- \#aa is treated as a tag.
- \#a is treated as a tag. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE Linux Tumbleweed 20211025
Windows 10

**Comment by derwok** [comment]
Yea. I spotted this in the early betas.
There was a (silent) behavioral change introduced, which threw my own tagging system off...
There is a discussion and explanation of possible solutions over here:
https://github.com/Zettlr/Zettlr/discussions/2341

Feel free to add your 2cts there. And maybe we can ask dev team to bring us back the old tagging - soon?

**Comment by nathanlesage** [comment]
The idea was that I was using a lot of hex colors, but it turns out that broke a lot of workflows. You know what? I'm just going to re-enable the tag processing in that regard and be done with it (but not for the next patch, don't wanna risk anything breaking before it :D)
