### ISSUE TITLE
[Enhancement] Sorting tags in the tag cloud would make it easier to find the one you are looking for

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#2746]
### Description

When you have accumulated a lot of tags it can be surprisingly difficult to find the one you are looking for in the tag cloud, as they appear in a seemingly random order:
![image](https://user-images.githubusercontent.com/51254/139590766-d41efc18-0065-46cd-9278-e888d26667f8.png)
- Even something as simple as soring the tags alphanumerically would make it much easier to find the one you want
- This could also help a little in finding near-duplicates or typos in tags

### Proposed Changes

Sort the tags in the tag cloud before display

### Caveats

I don't know if there is currently any logic to the order in which tags are displayed, but if there is, the sorting would lose that information.

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by rpace314159** [comment]
:+1: I vote for this.  It appears to me the tag cloud presents the tags in order of creation.

**Comment by nathanlesage** [comment]
Not order of creation, but order in which they have been found in the files on start. Sorting them sounds like a valid idea.
