### ISSUE TITLE
[Bug] Checkbox strikeouts only appear when you click into a document

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#2748]
### Description

Checked checkboxes in checklists apply a strikeout style to the text of the item in the list. However, that strikeout is not shown when you first open a document containing checked entries. Instead, the strikeout only appears when you click into the edit panel for the document containing the list.

### Reproducing

1. Create a new file in Zettlr
2. Add a checklist using several lines of  `* []`  with text next to each one
3. Check some of the boxes and observe that the text for those entries now has a strikeout style
4. Save and close the file
5. Open the file again and observe that although the checkboxes are checked, the text does not have the strikeout style
6. Click in the edit area for the file and observe that the strikeouts suddenly appear.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This is a current limitation in the implementation; @Redsandro that here could be a potentially much more satisfying fix, since we basically just have to run the corresponding hook upon instantiation. Should be safe to implement unlike the codeblock classes :D

**Comment by leo-hstone** [comment]
@nathanlesage duplicate with #3029 and to be closed I guess?

**Comment by nathanlesage** [comment]
Ouhh, yes! Thanks for pointing it out!
