### ISSUE TITLE
[FEATURE] Default paste behaviour as a preference

### ISSUE THREAD

**Issue by SebastianGrans** [Zettlr/Zettlr#275]
I rarely want to paste with style, and thus always have to press ⌘-⇧-V. 
It would be nice if this behaviour could be switched in the preferences.

Thanks again for an awesome app! :)

**Comment by dambaras** [comment]
Ditto on this. I often press Cmd-V and then have to undo and repeat with Cmd-Shift-V. Would be nice to be able to customize this.

**Comment by samarulmeu** [comment]
I always struggle with the default behavior. A switch will be nice.

**Comment by nathanlesage** [comment]
Okay, okay =D
