### ISSUE TITLE
[Bug] Text in backticks does not show up in the title

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#2755]
### Description

In the options, under "Display", I have checked "If present, use the first heading level 1 instead of the filename".

I find that any text in backticks is now omitted from the title.

### Reproducing

In the options, under "Display", ensure that the option "If present, use the first heading level 1 instead of the filename" is checked.

Create a new file:

```
# My `title` with `backticks`
````

Observe that the title shows up as "My with".

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr 2.0.1 (85323a54-9adc-4f6f-8c4f-d80bb025ab1f)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux 5.4.0-67-generic, Ubuntu 18.04

### Additional Information

Zettlr Version: 2.0.1 (UUID: 1c006165-098e-4091-8a05-52f3ae0d105c)

System: linux 5.4.0-67-generic (architecture: x64)

**Comment by chiphogg** [comment]
Well... that was fast :sunglasses: 

Thank you very much!

**Comment by nathanlesage** [comment]
Was luckily one of the easier things to spot, so thank the issue more than me :D
