### ISSUE TITLE
[Bug] Incorrect treatment of Cyrillic characters when Export PDF (LaTeX)

### ISSUE THREAD

**Issue by alexei271828** [Zettlr/Zettlr#2756]
### Description

After upgrade from 1.8 to 2.0.1, the Cyrillic characters are missing in the exported PDF file if export as PDF (LaTeX). If export as simple PDF, everything is correct.

### Reproducing

Take any .md file with Cyrillic characters and export as PDF (LaTeX).

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Mac OS Catalina

### Additional Information

If export as a LaTeX source, something is also wrong, I cannot compile the resulting .tex file successfully.

**Comment by nathanlesage** [comment]
Do you have any errors, screenshots and other information to share with us? Generally, faulty export of non-lating characters almost always indicate a problem with the default TeX font, which can be mitigated by choosing a different one (via setting the YAML property `mainfont: 'Some font name'`

**Comment by alexei271828** [comment]
![PDF-LaTeX](https://user-images.githubusercontent.com/93550248/139743925-fbc12ca2-cb5c-4345-9714-3fa089d7cbe5.png)
![PDF](https://user-images.githubusercontent.com/93550248/139743943-c73db960-1968-4850-bb8f-d690d82584e7.png)
Here are screenshots of PDF of the same text generated via LaTeX and directly.
I do not see where the YAML settings are hidden

**Comment by nathanlesage** [comment]
> I do not see where the YAML settings are hidden

Please try this (scroll up to see where to set these settings), and try adapting the *mainfont* to something that definitely works, for example Times New Roman (I think you already know fonts that work): https://docs.zettlr.com/en/core/assets-manager/#how-to-adapt-the-pdf-preferences

Please report back!

**Comment by alexei271828** [comment]
If I change in Assets Manager the LaTeX section like this:

reader: markdown
writer: latex
pdf-engine: pdflatex
self-contained: false
variables: {fontenc: T2A}

then the produced .tex file could be compiled and produces the desired result.

However, I failed to produce changes to PDF section in Assets Manager. Moreover, I do not understand whether the PDF section govern PDF export or PDF (LaTeX) section.

**Comment by alexei271828** [comment]
I corrected in PDF section of  Assets Manager

pdf-engine: pdflatex

and added

variables:
  fontenc: T2A

and now everything works.
