### ISSUE TITLE
[Bug] Incorrect markdown processing after math formulae with $$ $$

### ISSUE THREAD

**Issue by alexei271828** [Zettlr/Zettlr#2757]
### Description

I observe that after math formulae with `$ $` markdown processing is correct but after `$$ $$` is not. A screenshot is attached:
![formulae](https://user-images.githubusercontent.com/93550248/139751788-0baf97d9-9a31-4f86-9585-5d02b2130647.png)
 

### Reproducing

just type: First equation $x=y$

## Section 1

Second equation $$x=y$$

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Mac OS Catalina

**Comment by mb2g17** [comment]
Reproduced on Windows 10 Pro with Zettlr 2.0.1

**Comment by nathanlesage** [comment]
CC @tobiasdiez

**Comment by alexei271828** [comment]
New version 2.0.3: the same bug.

**Comment by nathanlesage** [comment]
@alexei271828 Yes, because this issue is still open. Please wait until we are able to look into this. Only check for the existence of this bug after this issue has been closed.

**Comment by nathanlesage** [comment]
This works in the current development version. It will come with 3.0; the nightlies already support this.
