### ISSUE TITLE
[Bug] Can't link to note document if period is in its filename

### ISSUE THREAD

**Issue by mb2g17** [Zettlr/Zettlr#2759]
### Description

Hi all,

I've created a markdown notes document with a period / full stop in its name: `PCRs on TPM 2.0.md`.

Upon creating a link to it, namely `[[PCRs on TPM 2.0]]`, nothing happens when ctrl + clicking on it.

When I enable `Automatically create non-existing files when following external links`, and then ctrl + clicking on the link, it suggests to overwrite the existing `PCRs on TPM 2.0.md` file.

![image](https://user-images.githubusercontent.com/30006386/139929599-976e7f02-f1ba-4d8c-bb75-fe3e93ac48a4.png)

This leads me to believe Zettlr incorrectly parses notes documents with periods in its name.

Thank you for your time!

### Reproducing

1. Create a target note with a period in its name (like in my description above)
2. Create a source note (source note doesn't have to have period in its name)
2. Link from the source note to the target note
3. Try to ctrl + click the link

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 Pro

**Comment by nathanlesage** [comment]
Interesting! I'll have a look.

**Comment by nathanlesage** [comment]
Cause: I just checked if there was something that looks like an extension and `.0` could be considered an extension. Now it'll check if it looks like an actual Markdown file extension (so the issue you discovered still will happen if you name a file `some name.md.md` and link it as `some name.md` -- so please don't do that)

**Comment by mb2g17** [comment]
thank you for fixing this issue! 😁
