### ISSUE TITLE
Screen twitching when a document creating [Bug] 

### ISSUE THREAD

**Issue by JetV** [Zettlr/Zettlr#2764]
### Description

When I create a document (**with a stationary mouse**), While typing, the document canvas starts to spontaneously twitch and slide across the screen. It is terribly annoying, and sometimes it is almost impossible to work.

### Reproducing

I recorded a video in which this effect is shown at the moments 0:3, 0:27-0:32, 0:57-0:58 and 1:20

https://user-images.githubusercontent.com/6479885/140219773-bce0f865-28c2-469c-b4d8-ee4049d832c6.mp4

 

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 7

**Comment by nathanlesage** [comment]
This bug has been fixed in the most recent stable version, 2.0.2. Please update your setup to 2.0.2.

**Comment by JetV** [comment]
Thank you very much, great job!
The program update also did not work for me - because I checked it before writing here.

**Comment by nathanlesage** [comment]
> The program update also did not work for me - because I checked it before writing here.

Zettlr needs to have internet access for this to work. Otherwise that might be a bug. You can always download the most recent version here from GitHub. That is basically the same as using the internal update dialog, just with a few extra steps.

**Comment by JetV** [comment]
Thanks for the answer!
Now this is no longer relevant, but my Zetllr is constantly connected to the network, because I'm online around the clock.
