### ISSUE TITLE
[Bug] Laggy window transition on MacOS

### ISSUE THREAD

**Issue by maschio** [Zettlr/Zettlr#2767]
## Description

When I perform the trackpad gestures for Mission Control, the window transition is pretty laggy. The lag only occurs in this scenario, dragging and resizing the window works fine. Resetting and reinstalling Zettlr does not fix the issue.

## Zettlr version
2.0.2

## Platform 
macOS 12.0.1

## Architecture 
Intel 64 bit

**Comment by nathanlesage** [comment]
Cannot reproduce on macOS 12.0.1

**Comment by lumitry** [comment]
I am able to reproduce this issue on an Intel MacBook Pro, however it is completely averted by switching to "automatic graphics switching" off in System Preferences, thus forcing the laptop to use its dedicated graphics.
Additionally, if Zettlr is not in the foreground (another application is in front of it) and mission control is activated, there is no performance issue.

**Comment by maschio** [comment]
> I am able to reproduce this issue on an Intel MacBook Pro, however it is completely averted by switching to "automatic graphics switching" off in System Preferences, thus forcing the laptop to use its dedicated graphics.
> Additionally, if Zettlr is not in the foreground (another application is in front of it) and mission control is activated, there is no performance issue.

My MacBook Pro only has integrated graphics, so I wasn't able to avert it with your fix. In my case, disabling Transparency in  `System Preferences - Accessibility - Display - Reduce transparency` completely eliminated it. I will continue to look into it and see what else can be done.

**Comment by nathanlesage** [comment]
> In my case, disabling Transparency in System Preferences - Accessibility - Display - Reduce transparency completely eliminated it. I will continue to look into it and see what else can be done.

Ah, Zettlr makes use of a semi-transparent window background on macOS (in line with native macOS apps), it might be that the fullscreen blur in this regard taxes heavily on your systems.

Would you mind trying that out to see if this reduce transparency indeed only removes the background blur in the sidebar of the main window, and report back if you experience the same? Then I could simply add a setting to disable window vibrancy for older systems.

**Comment by maschio** [comment]
> > In my case, disabling Transparency in System Preferences - Accessibility - Display - Reduce transparency completely eliminated it. I will continue to look into it and see what else can be done.
> 
> Ah, Zettlr makes use of a semi-transparent window background on macOS (in line with native macOS apps), it might be that the fullscreen blur in this regard taxes heavily on your systems.
> 
> Would you mind trying that out to see if this reduce transparency indeed only removes the background blur in the sidebar of the main window, and report back if you experience the same? Then I could simply add a setting to disable window vibrancy for older systems.

I saw a similar issue with Alacritty (see [https://github.com/alacritty/alacritty/issues/4474](url) & [https://github.com/alacritty/alacritty/issues/3641](url)) that seems to suggest that it is a MacOS OpenGL issue.I just tried your suggestion and it removes just the sidebar blur as you said. I think this could be a viable fix for this issue.

**Comment by nathanlesage** [comment]
> I just tried your suggestion and it removes only the sidebar blur as you mentioned. I think this could be a viable fix for this issue.

Perfect, I can add a corresponding settings option that simply disables the window vibrancy.

**Comment by 7596ff** [comment]
I'm also experiencing this issue on a 2021 Macbook Pro.

**Comment by rinkjames** [comment]
Experiencing this on a MacBookPro16,2 (13-inch, 2020, Four Thunderbolt 3 ports) running macOS Ventura 13.4.1. Only have integrated intel gpu on this machine. Reducing transparency globally in system accessibility settings fixes the issue, but I don't see an app-specific toggle for transparency or vibrancy as mentioned in earlier posts. What is the latest on adding this setting to Zettlr?

**Comment by nathanlesage** [comment]
Theoretically easy, just didn't get to implementing it yet. But now that the issue is bumped, there's a higher chance to make it happen.
