### ISSUE TITLE
[Bug] TOC export in PDF

### ISSUE THREAD

**Issue by Viguro79** [Zettlr/Zettlr#2768]
### Description

Using the `Export > PDF Document` document, I'm waiting for a PDF export with a Table of content, beeing named with the right title defined in the YAML frontmatter of my document... But it does not works.

### Reproducing

Using the `Export > PDF Document` document, I'm waiting for a PDF export with a Table of content, beeing named with the right title defined in the YAML frontmatter of my document :
```
toc: true
toc-depth: 4
toc-title: "Table des matières"
```

The `pdf export assets` is defined with :
```
toc: true
toc-depth: 3
```
But it does not works.

Strangly, the TOC only appears when I set `toc: true` in the `html export assets` 🤔 But in this case, the toc-title option does not apply.

I wonder if pandoc is correctly reading the yaml frontmatter. And if the pdf export is based on the right asset.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Aw yeah, the HTML template deserves a facelift. ("PDF Document" exports as HTML and then renders that as PDF. toc will work perfectly if you export using LaTeX --> "PDF (LaTeX)")

**Comment by Doud-gbx** [comment]
I also have an issue using the export PDF Document. It seems that the any changes in the assets manager even in deleting the all content have no impact on the export PDF ... with V2.0.2 on windows.

**Comment by Viguro79** [comment]
Ok, I now understand how it works. That was not a bug. Thanks @nathanlesage for the clarification.

**Comment by Viguro79** [comment]
Ok, I now understand how it works. That was not a bug. Thanks @nathanlesage for the clarification.
