### ISSUE TITLE
.md files that are in folder on computer do not show up in folder in Zettlr

### ISSUE THREAD

**Issue by wilkohardenberg** [Zettlr/Zettlr#2773]
As in the title, a couple of files that are present on the computer are not shown in Zettlr (see the two list compared in the screenshot). They used to do before I took a brief hiatus from working on this specific project and today I noticed that they disappeared. My first suspect was that Nextcloud had messed up (again), but since the files actually are still on my computer, in the correct folder, I do not understand what might have happened here. 

Extremely grateful for any help or suggestion on how to get back everything into Zettlr.

![Screenshot 2021-11-05 at 14 34 15](https://user-images.githubusercontent.com/1612993/140518795-82d13ba6-ac07-434f-8f54-9012068ec330.png)
.

**Comment by nathanlesage** [comment]
When the files are present on your computer they should show up. Do restarts solve the problem? If so, temporarily? Or are these files just generally missing? If the latter, what do the logs say?

**Comment by wilkohardenberg** [comment]
I should've thought that turning on and off would solve the issue. I hope permanently. Thanks and sorry for bothering.
