### ISSUE TITLE
[Bug] Code snippet weird overlapping background in PDF export

### ISSUE THREAD

**Issue by benjaminmordaunt** [Zettlr/Zettlr#2778]
### Description

Code blocks seem to have a background which overlaps strangely when using PDF export.
![image](https://user-images.githubusercontent.com/17656637/140628063-9628fa22-daba-4578-a01c-be161528c9b0.png)
(Notice the dark rectangle which cuts through ~half of the above header).

### Reproducing

Write a code block and export using PDF.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Monterey

**Comment by nathanlesage** [comment]
That should be fixed in the next patch: Yesterday I removed the custom HTML template which was still a remnant from way earlier. Now, Zettlr will use Pandoc's default HTML, which should work much better out of the box!
