### ISSUE TITLE
[Bug] Incorrect use of role=search on search input

### ISSUE THREAD

**Issue by scottaohara** [Zettlr/Zettlr#2779]
### Description

[The search input, in toolbar-controls > Search.vue](https://github.com/Zettlr/Zettlr/blob/b7443bc117895c96cf5d73280b2ae08e0c32313a/source/common/vue/window/toolbar-controls/Search.vue#L11) incorrectly uses the `role=search`.

This [role is meant to be used to identify a section of a page that contains search-related form controls](https://www.w3.org/TR/wai-aria-1.2/#search).  It is not for use on form controls themselves, as doing so will suppress the fact that this is an editable control to assistive technologies, such as screen readers.

From reviewing the markup for this component, `role=search` should instead be set to the parent `<div class="toolbar-search-container" ...>`

### Reproducing

To reproduce the bug, while using a screen reader, try interacting with the search field in the toolbar, as mentioned in the description.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [X] ARM 64bit

### Operating System Version

macOS, Windows

### Additional Information

this bug will impact all versions of the app.  Removing the `role` from the input is the way to fix this.

**Comment by nathanlesage** [comment]
Good catch, thank you for reporting!
