### ISSUE TITLE
Shift-tab behaviour is inconsistent

### ISSUE THREAD

**Issue by SebastianGrans** [Zettlr/Zettlr#278]
## Description
It is usually possible to unindent text using shift-tab. In Zettlr, this doesn't work when there are multiple lines. 

## Reproducing
Write several lines and use tab to indent it.
Then try to unindent it using shift-tab. That doesn't work. 

## Expected behaviour
Shift-tab should remove indentation. 

**Video illustrating the issue**
https://www.youtube.com/watch?v=beAq8JsJIpk

## Platform
 - OS: MacOS Mojave
 - OS Version: 10.14.6
 - Zettlr Version: 1.3.0

**Comment by nathanlesage** [comment]
Thanks for the video, makes it easy to trace! I strongly assume that this is a bug inside the CodeMirror core itself, as what I'm doing is simply binding the `autoUnindentMarkdownList`-command to `Shift-Tab`, which in turn calls the default `indentAuto` command by the underlying CodeMirror instance. The default `Tab`-command simply inserts spaces as expected, but the `indentAuto`-command doesn't do that.

One possible solution would be to replace the default handler with the `indentLess`-command (see [section "Commands"](https://codemirror.net/doc/manual.html#commands) in the CodeMirror manual)

References:

https://github.com/Zettlr/Zettlr/blob/bbe434c0bc75bc9a5c430885789b76ffb7fbda51/source/renderer/assets/codemirror/generate-keymap.js#L17

https://github.com/Zettlr/Zettlr/blob/bbe434c0bc75bc9a5c430885789b76ffb7fbda51/source/renderer/assets/codemirror/indentlist.js#L71

I'll be looking after it!

**Comment by nathanlesage** [comment]
Done!
