### ISSUE TITLE
can't export PDF file  on LINUX

### ISSUE THREAD

**Issue by WilliamYangShuai** [Zettlr/Zettlr#279]
## Description
just can't export pdf with error **pandoc: unrecognized option `--pdf-engine=xelatex'
Try pandoc --help for more information.**

## Reproducing
I have already installed pandoc and xelatex and use"which"to find their paths, but it still doesn't work.

## Expected behaviour

**Screenshots**

## Platform
 - OS: [Debian]
 - OS Version [6.3.0]
 - Zettlr Version [1.3.0]
 - Pandoc Version [2.2.3.2]
 - Screen Resolution [2K]
![image](https://user-images.githubusercontent.com/39552610/61957742-8764fe00-aff2-11e9-9c4e-09feeacb7a97.png)
![image](https://user-images.githubusercontent.com/39552610/61957835-baa78d00-aff2-11e9-9de4-8c38e7738f7b.png)
![image](https://user-images.githubusercontent.com/39552610/61957892-d57a0180-aff2-11e9-95fe-ef361f123158.png)
![image](https://user-images.githubusercontent.com/39552610/61957923-e75ba480-aff2-11e9-8bc5-176f83d0dcaf.png)

**Comment by nathanlesage** [comment]
This doesn't make sense on the first view, as the change was supposed to happen in Pandoc 2, so I have no idea why your pandoc doesn't want to accept the option. Could you try `pandoc --help` and see if there's any clue? Did you install pandoc from the official repositories?

**Comment by WilliamYangShuai** [comment]
> This doesn't make sense on the first view, as the change was supposed to happen in Pandoc 2, so I have no idea why your pandoc doesn't want to accept the option. Could you try `pandoc --help` and see if there's any clue? Did you install pandoc from the official repositories?

Yes，I installed it from the link in zettlr. By the way, if I use the zettlr on windows10, it goes wrong either.  It keeps telling me "LaTeX Error: Command \ttfamily invalid in math mode". And after I delete all the "|" in my formula, the problem disappears(but I don't why).Then I export PDF, it works. However the pdf can't display correctly. You can see the details in the pics below.
![1](https://user-images.githubusercontent.com/39552610/62018729-813b7100-b1ee-11e9-9cda-00bbd2070615.png)
![2](https://user-images.githubusercontent.com/39552610/62018730-81d40780-b1ee-11e9-97c6-8022ac9f29f9.png)
![TIM截图20190729104229](https://user-images.githubusercontent.com/39552610/62018731-826c9e00-b1ee-11e9-8c8e-55c5f32284cd.png)

**Comment by nathanlesage** [comment]
This now seems like an erroneous font — unfortunately, LaTeX has a history of being pesky concerning its font support. :/ But I fear this is out of my realm, however: If you find a solution, please share it with me so I can add it to the FAQ-Section in the docs for other people experiencing the same problem!

**Comment by ed1d1a8d** [comment]
Would like to say that I am also running into this issue, and it was also due writing some bra-kets with `|`.

**Comment by ed1d1a8d** [comment]
Spent some time troubleshooting the issue, and here are my findings:

The issue is due to the usage of the `|` character, and can be fixed by replacing using `\vert` instead in math expressions. The reason `|` is problematic is due to the following line in the default latex template:
https://github.com/Zettlr/Zettlr/blob/2f7dc39dbd514488410619bfc752a7a2d4f706a7/source/main/assets/export.tex#L125
Essentially the command redefines the catcode of `|`, which makes weird things happen.
Commenting out this line also fixes the issue, but may break other features that I did not test.

This issue with `\DefineShortVerb` has occurred in many different contexts for many different projects in the past, and it is unclear what exactly the best fix is. The ipython people seemed to have fixed the issue by just removing the line: https://github.com/ipython/ipython/pull/5380/.

**Comment by nathanlesage** [comment]
Ahh, alright. I took most of the command-redefines from the default Pandoc-template (basically the default Zettlr template is just a barebone of the Pandoc one), so maybe they've already solved this. Feel free to search within the Pandoc template what they've changed so we can adapt this as well!

https://github.com/jgm/pandoc/blob/master/data/templates/default.latex

**Comment by fvollmer** [comment]
I can also reproduce the `|` issue (on windows with miktex). Should we maybe create a new issue or just reopen this issue?

**Comment by Fryie** [comment]
I ran into the same issue. If it's possible it would be nice to fix the default template. Otherwise it makes it a bit hard to use zettlr for maths out of the box, since `|` is quite a commonly used character.
