### ISSUE TITLE
[Bug] multiple cursor placement

### ISSUE THREAD

**Issue by JetV** [Zettlr/Zettlr#2793]
### Description

Possible multiple placements of cursors when holding down the second key while maintaining cursor functionality.

### Reproducing

1. open Zettlr 
2. open .md doc
3. start typing text
4. press Ctrl + Left Mouse Button in several places on the typed line
5. several blinking cursors will appear (see picture -- I placed 8 cursors)
6. if unpress Ctrl key and Left Mouse Button, and start typing, then the text will appear in all places with cursors (see picture)
![err2](https://user-images.githubusercontent.com/6479885/140960066-11a23743-003b-48dc-84ac-aa5ee23d9e39.JPG)
![err21](https://user-images.githubusercontent.com/6479885/140960134-078a4a16-0fdd-44fb-8c01-214f7e931584.JPG)

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 7

**Comment by jgsw** [comment]
This is a feature, rather than a bug! See https://docs.zettlr.com/en/core/editor/#special-features-of-codemirror.

**Comment by nathanlesage** [comment]
What @jgsw wrote: Using this behavior you can type text once in case you need to repeat it several times. It comes in quite handy sometimes (but agreed, this is a feature one doesn't necessarily know from standard word processors!)
