### ISSUE TITLE
[Bug] Tags in YAML headers are not recognized by tag cloud and autocomplete

### ISSUE THREAD

**Issue by nabusch** [Zettlr/Zettlr#2798]
### Description

Tags that are only included inside YAML headers and never appear inside that main body of at least a single note do not appear in the tag cloud and do not trigger the autocomplete function. I think this used to work different before the 2.x update.

### Reproducing

Create a new note with this content:`

```
---
keywords: #missingtag 
---

Another #secondtag in the main body.
```

Then start typing "#missingtag" - it will not trigger autocomplete. Then start typing "#second..." and it will trigger autocomplete.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by rpace314159** [comment]
I have same problem -- 2.0.2 nightly.  Win 10 and Linux SuSE Tumbleweed.

**Comment by canpolat** [comment]
Have you tried formatting it like this:

```yaml
keywords:
    - missingtag
```

**Comment by nabusch** [comment]
Hah, yes using ...

```
keywords:
    - missingtag
```

... works: now the #missingtag is recognized in other notes, too. What is still strange to me is that ...

```
keywords: #missingtag
```

... definitely used to work in previous Zettlr versions. I hope I won't have to reformat the YAML header in all my old notes!

**Comment by rpace314159** [comment]
> I have same problem -- 2.0.2 nightly. Win 10 and Linux SuSE Tumbleweed.

My  problem was my own doing.  I was using the brace format:
`Keywords: [kwd1, kwd2, kwd2,...,kwdn]`
and the problem was the capital "K", in "Keywords:"....I changed it to "keywords:"  and it works now.  All keywords in the brace list are recognized now.

**Comment by canpolat** [comment]
> `keywords: #missingtag`
>  definitely used to work in previous Zettlr versions

I cannot confirm or deny that (I don't remember), but since this is YAML I would not expect it to work: `#` denotes comments in YAML.

**Comment by nathanlesage** [comment]
@canpolat You are correct. And this should also be indicated by the text beginning with the `#` changing color.

Closing as fixed.
