### ISSUE TITLE
Add syntax highlighting in Markdown

### ISSUE THREAD

**Issue by avetturi** [Zettlr/Zettlr#28]
Hi,
I would suggest to add syntax highlighting feature in markdown code blocks.

**Comment by Kremor** [comment]
Hello.

I would love  if this app had support for mathematical equations using LaTeX's syntax, where two dollar signs are user for inline equations: `$ your formula $`. And four are used for paragraph equations. 

```
$$
your formula
$$
```

An example of this can found in typora.

![typora](https://typora.io/img/new/math.png)

**Comment by nathanlesage** [comment]
Hey,

I'll keep that in mind; there was a way to implement this in CodeMirror. But the current focus is the PDF exporting options, because I've neglected them for some time now.

Cheers
