### ISSUE TITLE
Settings for document view and sharing custom themes

### ISSUE THREAD

**Issue by Miljanikus** [Zettlr/Zettlr#280]
First I apologize because I did not know where to put custom css I wrote for my own purposes. I think it would be nice if there is a page on which users can post their custom themes so others can benefit from it.
Here's my custom css code for dark Frankfurt theme. My goal was to reduce the contrast a bit and make it easier for me to work longer. I also hope that with tiny changes I have created a slightly more modern look. Of course this is a matter of opinion.
![Custom dark theme](https://user-images.githubusercontent.com/13729147/61994475-f71ecb80-b07a-11e9-9ed7-b13fee9fe21c.png)

In addition, since I find it much more pleasant for me to read my records when I see them as already formatted text (without markdown syntax, for bold text in particular), I set it to not display in the editor (display: none). If it's a problem for someone, it can easily find and erase that part of the code.
I think this option should exist in settings, as it is done for headings and some other syntax. 
Thank you very much for the opportunity to use this great application.

**Comment by Miljanikus** [comment]
`/* custom CSS for dark Frankfut theme */
body.dark #editor {
    background-color: #21212b;
}

body.dark .cm-quote, body.dark .cm-link, body.dark .cm-strong, body.dark .cm-em {
    color: #94c7ea;
}
body.dark #preview {
    background-color: #21212b;
    color: white;
  	box-shadow: inset -14px 2px 54px -23px rgba(0,0,0,0.5);
  	margin-top: 1px;
  	font-size: 1em;
}
body.dark #preview ul .selected {
    background-color: #2b3240;
    border-left: 5px solid #df5d33;
    font-weight: bold;
    color: #df5d33;
}
body #preview ul li {
    border-bottom: 1px solid var(--grey-2);
    border-top: 1px solid var(--grey-2);
    background-color: inherit;
  	box-shadow: inset -14px 2px 54px -23px rgba(0,0,0,0.5);
}
body.dark #preview ul li {
    border-top-color: #444;
    border-bottom-color: #444;
}
body.dark #preview ul li.directory, body.dark #preview ul li.virtual-directory {
    background-color: #030304;
    color: white;
  	font-weight: bold;
}
body #preview ul li p.file-meta .date,body #preview ul li p.file-meta .id, body #preview ul li p.file-meta .tags
{
    color: #ffffff !important;
    background-color: #000 !important;
    border: ipx solid #777;
}
.CodeMirror .cm-escape-char, .CodeMirror .cm-formatting-code, .CodeMirror .cm-formatting-code-block, .CodeMirror .cm-formatting-em, .CodeMirror .cm-formatting-quote, .CodeMirror .cm-formatting-strong {
    opacity: .3;
    display: none;
}
body.dark #preview ul li p.file-meta .directories
{
  background-color: #b75a3d;
}
.CodeMirror .CodeMirror-sizer {
  	margin-left: 30px;
    border-right-width: 30px;
    padding-right: 30px;
}`

**Comment by nathanlesage** [comment]
Hey, concerning your theme, I would suggest the best option would be to put it in this forum category: https://forum.zettlr.com/categories/customisation

There I already added one theme customisation I did a while ago: https://forum.zettlr.com/discussion/7/paperstyle-css#latest

Concerning your issues with Markdown syntax only being partially rendered, there's the WYSIWYG-module that is currently only activated on the developer console, where you can add it by executing `renderer._editor._wysiwyg = true` (make sure to have Debug mode turned on in the Advanced settings tab and then use the Develop-menu).

**Comment by Miljanikus** [comment]
Thank you, for your answer.
