### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dm5n** [Zettlr/Zettlr#2801]
### Description

Within-app updating failed Zettlr 2.0.2 to 2.0.3 with error code 3804. 

Downloaded file size was 255 and 383 MBs on desktop and laptop. When downloaded from GitHub, the dmg filesize was 128MB and installation completed.

### Reproducing

Within-app update process.

### Zettlr Version

Stable (but an older version)

### Specify version

2.0.2

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS 10.14.6 Mojave and 12.0.1 Monterey

**Comment by nathanlesage** [comment]
I've tampered with the updater in order to make it more responsive, so some issues are to be expected. But luckily I've also included a lot of debug logs, so it would be great if you could provide me with the relevant logs (beginning from the update check until the failed attempt to install!)

**Comment by dm5n** [comment]
[Zettlr console log.zip](https://github.com/Zettlr/Zettlr/files/7520275/Zettlr.console.log.zip)

**Comment by nathanlesage** [comment]
I meant the logs that the app produces :) (They are in `Application Support/Zettlr/logs` or in the log viewer)

**Comment by nathanlesage** [comment]
Any news on this? Otherwise I'm gonna book that as an accidental hiccup that has been fixed in the meantime.

**Comment by dm5n** [comment]
Yep. Sorry, dropped the ball on that one. Will monitor next update. Thanks

**Comment by nathanlesage** [comment]
@dm5n Any updates?

**Comment by dm5n** [comment]
Hey @nathanlesage ,  in-app updates have gone fine. Will close the issue, thanks.
