### ISSUE TITLE
[Bug] Weird : multi-words tags only partly recognized?

### ISSUE THREAD

**Issue by Julianoe** [Zettlr/Zettlr#2804]
### Description

The tag cloud seems to detect multi words, both with and without quotes, they are listed in the tag cloud. But when clicking on one or the other, they return 0 posts as result.

Maybe I'm not familiar with YAML and how it should be used and multi words keywords should avoided. If so then it's weird for the tag cloud to find and list them, and they should not be listed if they shall not return any result.

At the contrary if it is Ok for keywords to be multiple words, then they should be listed as they are but then there is a bug that makes them not find the posts they are from.

### Reproducing

Using a yaml frontmatter with multi-words keywords like follows:

```
---
keywords:
   - "history of art"
   - history of architecture
---
```

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro 21.1.6 Pahvo

### Additional Information

I understand that Zettlr works with two types of keywords/tags: those fed from the YAML frontmatter, and those with # symbol, and that those can't use multiwords. But there is clearly some odd behaviour with the former.

**Comment by nathanlesage** [comment]
This could probably be fixed with a rewrite of the search function (which is still not as good as it should be), because the search function is still somewhat old and doesn't really work for multiword tags.

**Comment by nathanlesage** [comment]
I'm going to close this issue, not because it's solved, but rather since we'll need a global search improvement. Tag detection including multiword tags is flawless in its own right.
