### ISSUE TITLE
[Bug] Application name is "Uninstall Zettlr" instead of "Zettlr"

### ISSUE THREAD

**Issue by ItzLevvie** [Zettlr/Zettlr#2811]
### Description

In Control Panel, application is referred to as "Uninstall Zettlr" instead of "Zettlr".

Usually, most applications don't have "Uninstall" shown in the name.

Screenshot taken from 13th of November 2021:
![image](https://user-images.githubusercontent.com/11600822/141651585-22e53178-b402-4a90-b1d0-26131beef490.png)

Screenshot taken from 10th of November 2021:
![image](https://user-images.githubusercontent.com/11600822/141651641-76e73458-fce9-4314-9c1f-e4377bbcd2fa.png)

This might be a culprit from https://github.com/Zettlr/Zettlr/blob/develop/electron-builder.yml#L92 and affects package managers where wildcard is used for ARP entries.

### Reproducing

1) Boot VM with VHDX/ISO, or use Windows Sandbox.
2) Install latest release from https://github.com/Zettlr/Zettlr/releases/latest
3) Observe that the application name is "Uninstall Zettlr" instead of "Zettlr" in Control Panel.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 (daily builds)

**Comment by nathanlesage** [comment]
I'm still a bit confused by how this works, but I guess I'll merge #2812 soon, so this should be resolved then. Just out of curiosity: Where are your screenshots from, which repository?
