### ISSUE TITLE
[Feature] Ability to take the screenshot of tutorial video and store it inside the notes.

### ISSUE THREAD

**Issue by rahulbansal16** [Zettlr/Zettlr#2816]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Allow a user to take a screenshot by using a shortcut and autosave it to the notes.
I have many time felt the need while watching a tutorial to take a screenshot and dump its content to the zettlr for future reference and the current process is very manual.

### Example Workflow

A small icon appears on the top of the screen or bottom and user can click that icon to take a screenshot.
Instead of icon, some shortcut keys can be used to take a screenshot.

Once the screenshot is taken it will be automatically inserted to the active note tab.

### Caveats

I am unable to think of any.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

I don't have.

**Comment by nathanlesage** [comment]
On all operating systems, taking screenshots is already built-in and thus there is no need for Zettlr to somehow duplicate that functionality. The workflow is actually very simple.

On Windows, you can use `Win+Shift+S`, select an area or the full screen, and have the screenshot copied to your clipboard. Then you can, within any note, press `Ctrl+V` and just press Return to save the screenshot.

On macOS and Linux, the process is exactly the same, only with different shortcuts (`Cmd+Shift+3` and `Ctrl+Shift+Print` respectively).

The coding overhead to integrate Zettlr that deep into the system (note that this might not even work on Linux!) is much higher than any gained benefits from saving you the second keystroke, so I'm going to close this issue.
