### ISSUE TITLE
[Bug] One-liner snippets without trailing newline are inserted also with their formula content

### ISSUE THREAD

**Issue by derwok** [Zettlr/Zettlr#2817]
### Description

When a snippet consists just of only one line (without trailing Newline), parts of the formula are inserted, when the snippet is inserted not on "column one", but on higher columns. The higher the column number, the more formula gets inserted.

### Reproducing

Enter this formula as snippet called `date`  - `$CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE`. Make sure it consists of just one line like so:
![image](https://user-images.githubusercontent.com/4393698/141825246-7d5a7ac2-5015-4b26-9855-0432e6917062.png)

Then insert the snippet at higher column numbers. Then parts of the snippet's formula show up in the MD editor:
![image](https://user-images.githubusercontent.com/4393698/141825607-cd587861-269c-4566-887a-b2d62d538f0d.png)

![image](https://user-images.githubusercontent.com/4393698/141825732-47f8d7fc-fd2a-4f67-a0d5-e1c3b7dad519.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

Workaround: add new line after formula
![image](https://user-images.githubusercontent.com/4393698/141825454-a48eeda4-501c-4669-8199-ea0c5d76e84d.png)

**Comment by nathanlesage** [comment]
That is an interesting observation! I'll look into it and fix it (except someone wants to do it before me :D)
