### ISSUE TITLE
[Bug] Selection highlighting ignores text height until the window is resized

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#2821]
### Description

When a fresh Zettlr file is opened it seems to default to a selection area the same height as regular text, so if the first thing selected is, for example, a # header, then the selection highlighting is strange and confusing. The effect seems to reset to the correct behaviour when the window is resized

### Reproducing

1. open a previously created file which includes a header and various other text sizes
2. attempt to select some text from the header
3. observe that the highlighted area does not cover the full height of the selected text
![image](https://user-images.githubusercontent.com/51254/141966550-0fcf22e4-5f67-4997-8b35-cea2542e1c61.png)
4. resize the window (e.g. click the "full screen" icon)
5. attempt to select the same text
6. observe that the highlighted area now matches the text
![image](https://user-images.githubusercontent.com/51254/141966641-81550ed2-82a8-4e97-be80-edbf0322bf1f.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This is currently a limitation in the implementation: When headings are detected, their font size changes, but this is something the editor itself is not aware of, so it will still assume the same size. I haven't yet found a way to correctly do that.

**Comment by nathanlesage** [comment]
I cannot reproduce this bug on the most recent branch, can someone else reproduce this? Selection height for me is always correct.

**Comment by efficacy** [comment]
Still does it for me in 2.0.3.
![image](https://user-images.githubusercontent.com/51254/144748282-6d34b684-664e-4ace-abbe-bec883428415.png)

What platform are you using @nathanlesage ? I'm Windows 10

**Comment by nathanlesage** [comment]
Since this bug only happens rarely, and apparently window resizing fixes it, I'm now just calling that function manually after a document swap. Should work fine now.
