### ISSUE TITLE
Sporadic Error Message when Exporting

### ISSUE THREAD

**Issue by jurastudio** [Zettlr/Zettlr#2824]
![image](https://user-images.githubusercontent.com/70759955/142043204-2a5ef829-8ece-4ed2-979d-a66c7f66c98b.png)

When trying to export, I get the above error. Googling it didn't help.

**Comment by nathanlesage** [comment]
This was an error I made in a previous version, a fix is already in the codebase. It's either already contained in the most recent version or will come with the next patch.

This error only occurs if there are internal links `[[123456789]]` somewhere in the file AND if you set to do something to these links (remove them or unlink them), so this is a way to mitigate them.

**Comment by jurastudio** [comment]
Thank you Nathan! Love your software!
