### ISSUE TITLE
[Bug] Tray icon duplicates

### ISSUE THREAD

**Issue by newhinton** [Zettlr/Zettlr#2832]
### Description

Only one Tray icon should be shown

### Reproducing

When the app is minimized in the tray, it can be reopened 2 ways:
1. Click on the Trayicon and select "Show Zettlr"
2. Use Applicationstarter to 'start' Zettlr
In the latter case, a NEW Trayicon is created. The old one is also kept.

### Zettlr Version

Right off the develop branch

### Specify version

2.0.3 (from develop/git)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

KDE 20.04

**Comment by newhinton** [comment]
It seems to be the same bug as the  _removeTray () function inhibtits, since Tray.destroy() does not work properly. 

I have found a partial workaround. If there is already a tray, do not recreate it. This works for static tray's as zettlr's is. It does not work for quickly toggling the Tray-setting, there the old one is never destroyed. Also we may run into issues when someone adds dynamic content to the tray, but i haven't looked into that. 

Should i open a pr for it?

**Comment by nathanlesage** [comment]
If it works reliably and doesn't impede functionality on other platforms sure!

**Comment by cskeogh** [comment]
Tray.destroy() worked ok on Linux Fedora 33 KDE Desktop (KDE Plasma 5.20).

Are you running Ubuntu 20.04 (KDE plasma 5.18) ?

**Comment by nathanlesage** [comment]
Closing as fixed due to closing of #2842
