### ISSUE TITLE
[Feature] smooth reloading

### ISSUE THREAD

**Issue by JorySchossau** [Zettlr/Zettlr#2844]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Reloading a file after external change would update the editor content without jumping the viewed location unexpectedly.

### Example Workflow

1. Create a full document including images and place cursor & view somewhere in the middle
2. Slightly alter document (spelling of a word) from an external process (and allow Zettlr to automatically reload file)
3. Editor location and view in Zettlr has ideally remained predictable in the same location.

### Caveats

I've been assessing a variety of other WYSIWYG MD editors and some handle this quite well. For instance, Typora. I wonder if it is doing a dom diff? It seems as though Zettlr currently allows media like images to render asynchronously:
* first the markdown source is rendered ex: `![my image](/some/url)`
* the markdown source line gets visually replaced with an image of a large height

This contracting and expanding of the height of various lines in Zettlr makes retaining document location and view very difficult. 

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

I'm happy to help, but unsure how best to tackle this. My first guess is this needs a large change of adding dom diffing and render state tracking (on file reload don't dump old content naively, then is image already rendered... then don't render as md source)

**Comment by nathanlesage** [comment]
> Editor location and view in Zettlr has ideally remained predictable in the same location.

I'm afraid that won't be completely possible. We can certainly do better, but the CodeMirror implementation is not as powerful as one might wish. I'm curious whether CodeMirror 6 would do the job, but for that we would have to await the migration of that one. I'm sure with enough of effort it should be possible to do that, but I guess it's a super difficult job to do.
