### ISSUE TITLE
Checkboxes aren't at baseline (and don't scale with zoom)

### ISSUE THREAD

**Issue by SebastianGrans** [Zettlr/Zettlr#285]
## Description
Checkboxes aren't aligned with the text as shown in the screenshot. 
When zooming in the editor, the checkboxes aren't scaled accordingly. 

## Expected behaviour
The checkbox should be aligned with the baseline and should zoom as the other elements. 

**Checkbox at default zoom level**
![DefaultZoom](https://user-images.githubusercontent.com/10030015/62208250-8cc99c00-b396-11e9-805f-da7d81ebdf0a.png)

**After zooming (⌘-+) 10 times**
<img width="417" alt="Zoom10x" src="https://user-images.githubusercontent.com/10030015/62208257-9521d700-b396-11e9-9186-ab300f67dd17.png">

## Platform
 - OS: MacOS Mojave
 - Zettlr Version: 1.3.0

**Comment by nathanlesage** [comment]
Yup, I can't guarantee to fix all of that, but the design will receive some anti-ageing in a while, so I'll keep this in mind! (Just found out a bug in checking the checkboxes, which needs adressing too)

**Comment by nathanlesage** [comment]
Sooo, finally got around to fixing the alignment — the scale can't be done, as this would involve a lot of legacy code on top (plus as far as I remember scaled-up checkboxes look ugly on Windows)
