### ISSUE TITLE
[Bug] Citations in footnotes are not exported correctly

### ISSUE THREAD

**Issue by wilkohardenberg** [Zettlr/Zettlr#2850]
### Description

If I put a reference in a footnote and it is not preceded by some text the quotation is given as empty (in both word and pdf). I know I could make the footnotes be produced automatically by pandoc, but as a historian I need more in the footnote itself than just the references.

### Reproducing

- create a footnote
- insert a bibliographic reference into the footnote
- export as word or pdf (and possibly others as well)

In the attached images you can see what happens, both with and without more text after the reference that doesn't get processed.

![Screenshot 2021-11-23 at 10 35 58](https://user-images.githubusercontent.com/1612993/143000858-fce8a64a-51fd-4cf4-9263-4fa5531fd21b.png)
![Screenshot 2021-11-23 at 10 35 43](https://user-images.githubusercontent.com/1612993/143000864-7fd46534-0550-4a1a-bff7-9d77827e598a.png)
![Screenshot 2021-11-23 at 10 35 13](https://user-images.githubusercontent.com/1612993/143000912-436efe94-1706-4e7e-a023-b695f04a997e.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3.

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Mojave 10.14.6

**Comment by nathanlesage** [comment]
Two things here: First, I don't really see where the bug happens, and I don't know whether that isn't rather a bug with Pandoc itself.

With regard to that:

> but as a historian I need more in the footnote itself than just the references.

What you can do is use a citation style that uses footnotes instead of in-text citations. This way you can do something like this:

```markdown
This is a sentence with a Reference [This text is basically part of the normal footnote, and then you can just add a citekey like so, @Autor2015, p. 23-34].
```

This should already then render as such:

```
This is a sentence with a Reference[1].

[1] This text is basically part of the normal footnote, and then you can just add a citekey like so, Autor 2015, A title, p. 23ff.
```

**Comment by wilkohardenberg** [comment]
Thanks, I’ll give it a try, at least for the ones that do not render correctly. 

Cheers,
Wilko

**Comment by wilkohardenberg** [comment]
It works for notes that include just a standalone references, but doesn't render more complex stuff like this:

`For once, it adopts mean sea level as its datum and is unaware of local tidal ranges, the effects of coastal erosion, or the role of existing coastal defences.[See @tingle. On this tool's limitations, see also @tingle2006. Another example of a sea level mapping tool with similar limitations is @zotero-30378. On the impact of the melting of all of Antarctica's ice cover on sea level, see @davies.]`

This renders as in the attached image...

![Screenshot 2021-12-04 at 21 17 20](https://user-images.githubusercontent.com/1612993/144723426-0a9a1c22-336b-4be7-9293-a9741033e5c6.png)

I will stick to the method I devised for stuff like this and use the other one for simpler note, even if I cringe  about the need to use two different standards... Or is there something I'm doing wrong?

**Comment by nathanlesage** [comment]
Mh, the citekeys do still need to be separated by semicolons, which you missed. Does the following work?

`For once, it adopts mean sea level as its datum and is unaware of local tidal ranges, the effects of coastal erosion, or the role of existing coastal defences.[See @tingle; On this tool's limitations, see also @tingle2006; Another example of a sea level mapping tool with similar limitations is @zotero-30378; On the impact of the melting of all of Antarctica's ice cover on sea level, see @davies.]`

**Comment by wilkohardenberg** [comment]
It renders the references, but does not allow to create sentences that end in a full stop. Which ends up weird looking syntax in narrative footonotes. I’ll stick to the option of either using two standards for different kinds of notes or write some easily identifiable gibberish in front of standalone citekeys in footnotes (and then delete it with search and replace).
Thanks for the clarification.

**Comment by nathanlesage** [comment]
@wilkohardenberg This almost seems like an issue we might want to put to Pandoc. It does seem to me as well that what you've written in your earlier screenshot (the "miami" footnote) should definitely work (and in Zettlr it does, in fact, work).

**Comment by wilkohardenberg** [comment]
Sorry for getting back to this: I still wonder how it comes that the rendering for this footnote is so different if I use the internal conversion and if I do it from the command line

`[^tingle]: See @tingle. On this tool's limitations, see also @tingle2006. Another example of a sea level mapping tool with similar limitations is @zotero-30378. On the impact of the melting of all of Antarctica's ice cover on sea level, see @davies.`

This is the code I used on the command line:

`pandoc -s -o 7_Afterword_Tide.docx 7_Afterword_Tide.md --bibliography /Users/whardenberg/Dropbox/TempLibrary.bib --csl /Users/whardenberg/Zotero/styles/chicago-fullnote-bibliography.csl`

Command line:
![Screenshot 2021-12-17 at 15 37 24](https://user-images.githubusercontent.com/1612993/146561587-337a6949-1b12-4150-bfec-c48ffa6773d9.png)

Zettlr:
![Screenshot 2021-12-17 at 15 45 47](https://user-images.githubusercontent.com/1612993/146561818-5324e51b-4afa-4cb2-bc89-23ab20123689.png)

What befuddles me is the comma after "limitations is" in the Zettlr one: why does it do that? I set the same style for both conversions, but still it handles references without an author differently.

**Comment by nathanlesage** [comment]
> why does it do that? I set the same style for both conversions, but still it handles references without an author differently.

I guess it has to do with the options in the defaults files. Would you mind checking if the corresponding defaults file has `standalone: true`? Because that's one of the parameters you're passing, and sometimes seemingly unrelated settings may have an impact. But I'm positive that it's an issue with the defaults file.

**Comment by wilkohardenberg** [comment]
sorry for being particularly thick:

is this the file in the defaults folder I’m supposed to check: export.docx.yaml?
If yes, since there is no line for “standalone”, should just add one? If that is the case it doesn’t make a difference.

Cheers,
Wilko

**Comment by nathanlesage** [comment]
> sorry for being particularly thick:

Don't worry! If you're exporting to docx, then it's the default you've found, which you can also edit from within the app. If it's not the standalone flag (which you can add if it's not in there, yes), then it must be some other setting in that file. I'd recommend the following:

First, comment out EVERYTHING except the reader and writer options from the Zettlr default file (by prepending each line with a `#` character) and export. The export should look correct (because your library and the CSL style will be added by Zettlr during export, even if the setting is commented out).

Then, gradually un-comment each line and again export, and see when the export begins to look wrong. As soon as that happens, we finally know which setting has caused the wrong export, and we can think about why that happens and possibly adapt the defaults for the default file.

**Comment by wilkohardenberg** [comment]
yeah, not really I am afraid. If I comment everything out no citekey gets processed, and as soon as I uncomment filters: type: - citeproc the problem is back...

**Comment by nathanlesage** [comment]
What version of pandoc do you get when you run `pandoc --version`? Maybe your system version differs from the one shipped with Zettlr?

**Comment by wilkohardenberg** [comment]
2.7.3

**Comment by nathanlesage** [comment]
Ah, Zettlr currently ships with 2.16 — maybe there has been a change in how Citeproc works in between.

CC @tarleb

**Comment by tarleb** [comment]
I only skimmed the issue, but there are two changes which are likely to be relevant:

- pandoc replaced the way citations are resolved: instead of using the external `pandoc-citeproc` program, the processing now happens with an internal citeproc implementation.
- Specifying `--bibliography` no longer implies `--citeproc`; the flag has to be passed explicitly.

HTH.

**Comment by wilkohardenberg** [comment]
I see. but in 2.7.3 --bibliography implied citeproc, right? And Zettlr, running pandoc 2.16, explicitly states citeproc as the filter. Shouldn’t the results be comparable, if not identical?
I could obviously update my pandoc installation to test what happens then from command line, but, frankly, I’m afraid to break the one way I have to get word files with fully compliant footnotes.

**Comment by wilkohardenberg** [comment]
ok, I found the courage and updated pandoc and indeed with this command

`pandoc -s -o testoutput.docx 7_Afterword_Tide.md --bibliography /Users/whardenberg/Dropbox/TempLibrary.bib --citeproc --csl /Users/whardenberg/Zotero/styles/chicago-fullnote-bibliography.csl`

now also from command line I get the same errors. I'll reinstall 2.7.3 for the time being and move over to issues on pandoc to go on discussing this.

**Comment by nathanlesage** [comment]
Okay, perfect, closing as pertaining to Pandoc! Thank you so much for trying to figure out what is happening!
