### ISSUE TITLE
Latex tikz and pgf support + latex table support

### ISSUE THREAD

**Issue by Nathan-Furnal** [Zettlr/Zettlr#286]
Hi !

Thanks for the great app,

is there a way to easily incorporate latex tables and pgf graphs into my markdown document ?

This would make Zettlr way above anything existing as of now,

Thanks!

**Comment by nathanlesage** [comment]
Easily … depends? I mean, you can always incorporate normal LaTeX-commands in your Markdown files when you will be exporting to PDF. Otherwise, normal Markdown-tables will also work. In 1.4, there'll be a Table Editor that'll work as a great helper in composing such tables. Is that what you mean?

**Comment by Nathan-Furnal** [comment]
@nathanlesage Alright, I was looking for something that'd also be able to compile Latex like Latex studio and show what I'm doing. Crossing Latex and Md in the same doc would be invaluable

**Comment by nathanlesage** [comment]
Yeah, you can in fact mix up Markdown and LaTeX; it will be rendered when you export to PDF. (Unfortunately, in other export formats, LaTeX is not converted and will remain as it is). What you could also do if you need a real-time check on your LaTeX tables is making use of projects, adding a pure TeX-file into your project directory which you can then edit in LaTeX Studio and which will also be incorporated into your final Zettlr export! The approach is mentioned at the end of the table documentation!

**Comment by Nathan-Furnal** [comment]
Awesome thanks for your help!

**Comment by nathanlesage** [comment]
You're welcome! :)
