### ISSUE TITLE
[Bug] Selecting file in unselected folder opens wrong folder

### ISSUE THREAD

**Issue by newhinton** [Zettlr/Zettlr#2864]
### Description

Selecting file in unselected folder opens wrong folder in the foldertree.

### Reproducing

Open Folder with notes and multiple subfolders that contain more notes.

Expand Subfolder C.
Open Subfolder A, and File B in A.
B opens. 
Close B, Collapse A.
Open file D, contained in C. 
A expands. This is due to the folderselection not beeing updated, and therefore the wrong parent gets opened.

### Zettlr Version

Right off the develop branch

### Specify version

77b6597

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 20.04

**Comment by nathanlesage** [comment]
I noticed the same weird behavior, although I thought I did something wrong until now. Will have a look, but first please await my Vue 3 migration commit, then I'll have a look at what is happening there, because I guess that the Vue 3 migration will have a few more issues.

**Comment by nathanlesage** [comment]
@newhinton Do you think this issue is now close-able…? You mentioned that the PR might solve it?

**Comment by nathanlesage** [comment]
This bug is not appearing in the current beta!
