### ISSUE TITLE
[Bug] When Open Preference A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by DawnMagnet** [Zettlr/Zettlr#2868]
### Description

On My MacOS(arm64, MacOS12) I tried both the arm64 and x64 arch, but preferences crashed everywhere.
Here is the Preview.
![image](https://user-images.githubusercontent.com/61567130/143734434-1d3d1ce0-62c7-46b7-a50d-08b959cead30.png)

### Reproducing

Open Application, Click Menu->Zettlr->Preferences, And Crashed

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

MacOS12.1

**Comment by nathanlesage** [comment]
This is a bug that occurs because some internal API calls require integers, and will fail on floating point numbers. I think I have fixed all of these instances. Opening the preferences itself shouldn't crash consistently.

**Comment by DawnMagnet** [comment]
> 

Thanks! Hope Zettlr to be better

**Comment by nathanlesage** [comment]
I just checked and the code that fixes this issue (not related to the preferences) has been in the codebase since Oct 8th. One thing that might help is to manually remove the file `~/Library/Application Support/Zettlr/window_state.json`.

Please report back if that solves your issue and close this issue if so.

**Comment by DawnMagnet** [comment]
> I just checked and the code that fixes this issue (not related to the preferences) has been in the codebase since Oct 8th. One thing that might help is to manually remove the file `~/Library/Application Support/Zettlr/window_state.json`.
> 
> Please report back if that solves your issue and close this issue if so.

Thank you. It doesn't crash any more.
