### ISSUE TITLE
[Bug] File tab gets closed on remote change

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#2871]
### Description

Whenever I do a remote change on a file (e.g. using vim), that file (more precisely: its _tab_) gets closed.

This also happens even if the file is not the active tab.

I have the option "Always load remote changes to the current file" enabled.

I have not tested at which 2.0.x this bug first appeared, but I do know for sure that it used to worked as expected in 1.8.9.

### Reproducing

1. Open a file in a tab
2. Open the same file in some external text editor
3. Do some changes in that external editor, and save the changes
4. The tab of the file in Zettlr should've been closed now

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro, Ubuntu 20.04.2

**Comment by nathanlesage** [comment]
I'm on the most recent dev branch and cannot reproduce this. Please feel free to try that out and see if this fixes the bug. Otherwise, tomorrow there will be a new nightly, if you do not want to compile the app yourself.

Please report back if the bug has been solved.

**Comment by kyaso** [comment]
Looks like this is an issue with my work machinue (Ubuntu). On my private laptop (Manjaro), both 2.0.3 and the latest nightly don't suffer from this issue.

Not sure if other Ubuntu users experience the same problem.

**Comment by nathanlesage** [comment]
Yeah the setting adds just that confirmation dialog, but the underlying logic is obviously the same. But I still can't reproduce this here, so I can't help currently :/ 

However, I did just simplify the file opening/closing logic by a large margin, maybe I accidentally fixed whatever bug was causing this and potentially the next nightly next Monday might solve it?

**Comment by kyaso** [comment]
No worries :) Editing files externally is luckily not something I do regularly, so for now it's not a too big deal.

Let's hope for the best then on next Monday!

**Comment by kyaso** [comment]
Small update: I noticed that this only seems to happen when doing the remote change using Vim. If I edit a file using VSCode or gedit, Zettlr imports the change without crashing (as one would expect).

Also, when just opening the file in Vim, and immediately save (`:w`) w/o any change, the tab in Zettlr gets closed as well.

I suspect it has something to do how Vim saves it _buffers_ to the disk, which in turn confuses Zettlr?

**Comment by nathanlesage** [comment]
> I suspect it has something to do with how Vim saves its buffers to the disk, which in turn confuses Zettlr?

Either that, or what might be happening could be that vim locks the file so that Zettlr is not allowed to read the file while it is opened in vim. This would then cause the watchdog to emit a "removed" event, so that the file is not at all visible to Zettlr.

This stackoverflow issue seems to point in that direction: https://vi.stackexchange.com/questions/27498/closing-the-file-handle-while-keeping-buffer-open

**Comment by nathanlesage** [comment]
Does this still happen?

**Comment by kyaso** [comment]
> Does this still happen?

It still happens with Vim, but not with other editors (e.g. VSCode).

Shall we still close this issue, as it seems to be something Vim-specific which might be out of our control?

**Comment by nathanlesage** [comment]
Probably! Every closed issue is one less to deal with :D

**Comment by kyaso** [comment]
Ok! :D
