### ISSUE TITLE
[Bug]  CTRL-CLICK for editing footnotes only works intermittently

### ISSUE THREAD

**Issue by dajare** [Zettlr/Zettlr#2873]
### Description

According to [the documentation][1], 

> Zettlr tries to ease your life \[managing footnotes\]. Move your mouse over a footnote reference to see the footnote text. Click it while holding down `Cmd` or `Ctrl` to edit the footnote. Press `Shift+Return` to save your changes.

Only about one click in 10 produces this workflow. Typically what happens is that I get a second (or third) cursor, which seems to be a (very welcome) [CodeMirror feature][2]. Only rarely do I actually get the transform of the footnote content into an editable area. **IF** (IFF?) that happens, it works brilliantly. :) But it's a big "IF".

[1]: https://docs.zettlr.com/en/reference/markdown-basics/#footnotes
[2]: https://docs.zettlr.com/en/core/editor/#special-features-of-codemirror

### Reproducing

To reproduce, open/produce a document with footnotes, like this:

```
Here's a footnote.[^1]

[^1]: My footnote content.
```

Hover over `[^1]` in the main text. The content of the footnote ("My footnote content.") should appear as a "pop-up" floating above it. While hovering over the footnote reference, click it while holding down `Cmd` or `Ctrl`. This *should* alter the form of the floating footnote to make it an editable window. In my case, it seldom does. Only, *sometimes* (rarely) it does.

### Zettlr Version

Stable (most recent version)

### Specify version

v. 2.0.3

### Your Platform

- [ ] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS 10.14 "Mojave"; Ubuntu 18.04.06 LTS.

### Additional Information

I get the same quirky behaviour on both MacOS (MacBook) and a Dell Desktop running Ubuntu. About one in 10 (or 20?) attempts actually produces the editable area. Why? I have no idea.

**Possibly related**

- #1893 (footnote planning thread)
- #2839 (buggy CTRL-CLICK for opening links)

(Is `CTRL-CLICK` being asked to do too many different tasks?)

**Comment by nathanlesage** [comment]
You have to click the actual `^<number>`-part. I.e. if your footnote is `[^1]` you have to Ctrl/Cmd-click the `^1`. I agree that we should look into being able to click the brackets as well, but something prevented me from doing that earlier (I think mainly because the formatting brackets have a different CSS class)

**Comment by dajare** [comment]
> You have to click the actual `^<number>`-part. I.e. if your footnote is `[^1]` you have to Ctrl/Cmd-click the `^1`. ...

Well, yes — that's exactly what I was clicking! My note anchors have the form `[^xkc6]` (alway last four alphadigi's of a hash), and I end up with two or three cursors until I clear and try again...

**Comment by nathanlesage** [comment]
ehm … what?

Okay, just tried this out and … what the heck. Clicking just on the circonflex (`^`) works, but not on the footnote name. That is super weird.

Oh wait, it might be because I remember that at some point I explicitly checked for NUMBERS and not alphanumerical characters, so it could be that Zettlr just refuses to open anything with letters in it (pls don't judge my former me)

**Comment by dajare** [comment]
> Clicking just on the circonflex (`^`) works, but not on the footnote name.

THAT'S IT!! Thank you for solving the mystery. The question now is: is that a "bug" or a "feature"? 🤔 😬

**Comment by dajare** [comment]
> Oh wait, it might be because I remember that at some point I explicitly checked for NUMBERS and not alphanumerical characters, so it could be that Zettlr just refuses to open anything with letters in it (pls don't judge my former me)

Oh! Wait . . . Is that related to #364, "[All-text footnote anchor not recognized as footnote anchor][1]"? That was also me. Oops. Thanks for mopping these up!

[1]: https://github.com/Zettlr/Zettlr/issues/364

**Comment by nathanlesage** [comment]
> is that a "bug" or a "feature"?

Definitely a bug, since alphanumerical identifiers are perfectly fine as well. But the other issue was just related to hovering over a footnote ref, whereas this issue is about actually editing it – and that should definitely also work :D
