### ISSUE TITLE
[Feature] Link navigation without keyboard

### ISSUE THREAD

**Issue by zh217** [Zettlr/Zettlr#2874]
### Description

Currently the only way to navigate links (that I know of) is to hold down ctrl/command key and click. This is inconvenient when browsing through files.

### Proposed Changes

Have a method of navigating links without pressing any keys, suggestions:

* Contextual menu on right click
* Middle-click
* We have a preview popup on mouse-over the link, the popup can act as a further target so that click or double click on it opens the linked article

### Caveats

Contextual menu is certainly very safe. I am not sure if middle-clicks have any other functionality.

### Do you Wish to Attempt Implementing this Yourself?

Maybe

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

12.0.1 (21A559)

**Comment by nathanlesage** [comment]
Context menu will work, middle clicking not since we need that to enable force-opening in a new tab (to align with browser-style behavior).

> We have a preview popup on mouse-over the link, the popup can act as a further target so that click or double click on it opens the linked article

Even more so, we might be able to add a button to follow a link.

**Comment by zh217** [comment]
> Context menu will work, middle clicking not since we need that to enable force-opening in a new tab (to align with browser-style behavior).

Adding to context menu is fair enough, but I don't think the planned behavior aligns with that of browsers, since for browsers (and most applications) the behavior is that middle click and ctrl-click are the SAME (whatever that behavior is). My understanding is that ctrl-click always acts as a replacement for middle click for mouses without a middle button.

**Comment by nathanlesage** [comment]
> the behavior is that middle click and ctrl-click are the SAME

That is true, but on webpages you normally don't edit text, so you don't have to differentiate between normal clicks (intent: edit) and Control-clicks (intent: follow the link). So in this case we must differentiate between Control-left-Click and Control-Middle-Click.

**Comment by zh217** [comment]
> So in this case we must differentiate between Control-left-Click and Control-Middle-Click.

I agree, but this does not imply that middle-click without control should be a no-op.

**Comment by nathanlesage** [comment]
> I agree, but this does not imply that middle-click without control should be a no-op.

Right, middle-clicks are currently no-ops. Didn't think about that. Ctrl+Middle should still be reserved for forcing a new tab, so when someone forgets to press Ctrl it'll open in the same tab (if the corresponding setting is set). However, in tandem with issue #1590 this should pose not that much of a problem.

**Comment by leo-hstone** [comment]
I would like to porpose a double-click to open a link. This is, for example, how notepad++ handles file links in plaintext or markdown documents.

**Comment by nathanlesage** [comment]
Almost forgot about this issue. So, right now you can either hover over the link for some time and then click the clickable link in the popup that appears, or use the right mouse button to follow the link. Double clicks would be pretty difficult to implement (and not that transparent, I would suppose …?)

**Comment by leo-hstone** [comment]
I didn't knew these methods exit. Unfortunately the option that appears after right click is not working (just nothing happens). Clicking on the popup works fine.

Tested with this code on 2.1.2:
```
www.google.com
[Test](./link_to_local_pdf.pdf)
```

I would prefer the right click method as it is faster.
