### ISSUE TITLE
[Bug] Second title bar on export error window

### ISSUE THREAD

**Issue by Antoine-Meloche** [Zettlr/Zettlr#2883]
### Description

There are two title bars on the export failed dialog window.
![Screenshot from 2021-12-05 18-36-19](https://user-images.githubusercontent.com/53838501/144768592-63ae6266-f221-4f38-8ce2-1a515ccdae43.png)

### Reproducing

Export to latex pdf without texlive installed

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux 5.14.16-205.current x86_64 GNU/Linux

### Additional Information

I am running Solus Budgie with zettlr installed with the appimage

**Comment by nathanlesage** [comment]
Do you have "Use native appearance" active in your advanced settings?

**Comment by Antoine-Meloche** [comment]
No I did not, That solved it thanks

**Comment by nathanlesage** [comment]
Okay, still that sounds like a bug because Zettlr should EITHER use the native title bar OR the custom one, but never both :D I'll have a look nevertheless!
