### ISSUE TITLE
[Feature] Table generator

### ISSUE THREAD

**Issue by SebastianGrans** [Zettlr/Zettlr#289]
## Description
Instead of manually having to make tables, I sometimes use https://www.tablesgenerator.com. 
I especially like the feature of specifying the table size and I think that it could be a useful tool in Zettlr as well. I made a mock-up that is basically a copy of their design. 

**EDIT:** Just noticed you wrote this: "_it's best to discuss your ideas on the forum or on reddit first._" [here](https://docs.zettlr.com/get-involved/). I'll post it on Reddit as well and see what people think. :)

<img width="597" alt="tablegenerator" src="https://user-images.githubusercontent.com/10030015/62833595-c8d7e900-bc41-11e9-9f68-3da73e98a655.png">

![table-generation](https://user-images.githubusercontent.com/10030015/62833589-b493ec00-bc41-11e9-9ce8-1b6946739302.png)

**Comment by nathanlesage** [comment]
Good idea, and already planned, because simply inserting a 2x2-table once someone clicks that button is hardly sufficient :D
