### ISSUE TITLE
[Bug] Wrong hashtag detection in markdown anchor

### ISSUE THREAD

**Issue by MediocrityXT** [Zettlr/Zettlr#2893]
### Description

`[head](#title1)` links to the markdown anchor title1. However, zettlr seems to auto detect  #title1 in the brackets as a hashtag.

### Reproducing

just type `[head](#title1)`, then the hashtag #title1  will appear in your file manager.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Monterey 12.0.1

### Additional Information

Well, the web links successfully elude the hashtag detection...

**Comment by nathanlesage** [comment]
I could reproduce this but weirdly specific: I have a file with a "manual" table of contents containing a lot of these anchors, and ONLY the top-level list items are wrongly detected:

![image](https://user-images.githubusercontent.com/17251683/145670166-875767da-4df6-49b9-9749-21603fe24212.png)

As you can see, only the top-level items are detected as tags. I'll have a look, but please, feel free to check if you notice any other patterns, since that might help speed up the process!

**Comment by MediocrityXT** [comment]
> I could reproduce this but weirdly specific: I have a file with a "manual" table of contents containing a lot of these anchors, and ONLY the top-level list items are wrongly detected:
> 
> ![image](https://user-images.githubusercontent.com/17251683/145670166-875767da-4df6-49b9-9749-21603fe24212.png)
> 
> As you can see, only the top-level items are detected as tags. I'll have a look, but please, feel free to check if you notice any other patterns, since that might help speed up the process!

I tested these.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/56628462/145673231-f4be0d66-e0ed-4239-859f-5fcf427ffa20.png">
Only these anchors are detected.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/56628462/145673216-bc8d5460-c7f7-4095-b458-adff5ddc0af3.png">
(by the way, is there source code mode in zettlr so that i don't have to switch to other editor to see spaces clearly?)
<img width="660" alt="image" src="https://user-images.githubusercontent.com/56628462/145673248-2bf7cd8c-8924-4e15-9a78-fc5a9f626377.png">

Using 4 spaces indentation can avoid the detection(but why?), but wrong detection still happens in many more situations.  Maybe your manual didn't include anchors outside of the list i guess?XD

**Comment by nathanlesage** [comment]
> (by the way, is there source code mode in zettlr so that i don't have to switch to other editor to see spaces clearly?)

You can disable all rendering elements in the display preferences, then it will render solely the source code. Additionally, switching to Bordeaux or Bielefeld will use monospaced font, so it actually looks like a code editor! You may have to switch back and forth between the file to make the prerendered elements go away.

> Using 4 spaces indentation can avoid the detection(but why?)

Well, that's the question we're all asking :D

**Comment by nathanlesage** [comment]
Just tested out the regular expression that detects tags and, oh boy, the weirdness doesn't stop:

![image](https://user-images.githubusercontent.com/17251683/145674151-6efe7071-8f94-4bdb-bb88-1ebb0e7b3189.png)
