### ISSUE TITLE
[Feature] open pdf file by clicking on citation

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#2898]
### Feature Proposal

Problem: I would like to keep my pdf's in Zotero and have a way not only to reference these documents, but also to link to these documents. The problem ist, that if I use normal external links, they would stop working if I change my computer.

Solution: I want my Zotero references not only to be simple references, but also links to the pdf files in my Zotero library.
Then I could link to my external file (saved in my zotero library) with a simple reference. If I click on the reference to file would open. These external links would not break, even if I switch to another computer.

### Example Workflow

If I reference documents, I could simply click on it, to go back to the text, without going to the document tab. 

### Caveats

maybe it can be combined with point 5 of the roadmap "Support for Arbitrary File Locations" that I cite a Zotero reference, but it opens the file in my nextcloud. 

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
This is already possible. When you cite works using the citekeys you have the ability to right-click them and open the corresponding PDF attachment (Zotero needs to be running). You do need to have Better BibTex installed, though. But then, regardless of which computer you're using, you can open the corresponding PDF file.

I will add a small paragraph explaining that to the docs.

**Comment by JJger148** [comment]
that's amazing, I didn't know that.
