### ISSUE TITLE
[Request] Alias names for root directories

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#291]
In case there are two or more root directories with equal names it is not really easy and intuitive to choose the right one in the file list besides checking their content.

Therefore if it's not too complicated to realize I'd like to see a posibility to assign alias names to root directories.

For example if you have a bunch of project folders with an equally named subfolder structure and a lot of non Zettlr-related files whithin it would be desirable to only view the notes subdirectories of the projects as root directories in the Zettlr file list. As all these might have the same name, a project specific alias name for them would be helpful.

**Comment by nathanlesage** [comment]
Interesting usecase, haven't stumbled upon this before! It certainly makes sense and could be implemented. However, I can offer you a compromise of which I can ensure that it'll make it into the 1.4:

If you have two root files with the same name, Zettlr will detect it already and, in this case, display the containing directory name behind it. This functionality is already implemented and it'll take me one small adjustment to activate it for root directories as well. Would this be a feasible option?

![grafik](https://user-images.githubusercontent.com/17251683/63330412-120bf500-c334-11e9-8f17-cb9f0314e9a0.png)

**Comment by jothanne** [comment]
Your suggestion sounds promising and I'd like to try out this option and see if it's suitable for the described usecase. Thanks a lot!

**Comment by nathanlesage** [comment]
Perfect, it's on the list!

**Comment by nathanlesage** [comment]
Like this?

![image](https://user-images.githubusercontent.com/17251683/63455830-d49b8a80-c44d-11e9-885f-535f0696bc75.png)

**Comment by jothanne** [comment]
Yes - very nice!

**Comment by nathanlesage** [comment]
Perfect :)
