### ISSUE TITLE
[Bug] Export using CiteProc: PandocLuaError "table expected, got Block\n\twhile retrieving list"

### ISSUE THREAD

**Issue by j2l** [Zettlr/Zettlr#2916]
### Description

Hello!
First of all, thank you very much for this great project :)

On Ubuntu 21.04, using Zettlr 2.0.3,
I followed your tutorial at https://www.youtube.com/watch?v=0egU3eLSSew and installed 
- Zotero (5.0.96.3 from snap), 
- pandoc 2.9.2.1-1ubuntu3
- pandoc-citeproc (0.17.0.1-1build2),
- python3-citeproc (0.5.1-1) and 
- pandoc-citeproc-preamble (1.6-1build1).
- Bibtex 5.6.11
After successfully adding a citation (automatically proposed from JSON) in the welcome.md document (Zettlr default doc), 
I tried exporting to PDF (latex) to current directory and get an error:
```
An error occurred on export: Error running filter /home/pm/.config/Zettlr/lua-filter/links.lua:

Error running filter /home/pm/.config/Zettlr/lua-filter/links.lua:
PandocLuaError "table expected, got Block\n\twhile retrieving list"
stack traceback:
[C]: in field 'walk_block'
/home/pm/.config/Zettlr/lua-filter/links.lua:47: in function </home/pm/.config/Zettlr/lua-filter/links.lua:41>
```
I searched in previous issues and on Google without luck.

Any idea what I did wrong? Or is it a bug in Linux?
Thanks!

### Reproducing

- Install ubuntu 21.04, Zettlr 2.0.3 (deb package), Zotero (5.0.96.3 from snap), pandoc-citeproc (0.17.0.1), python3-citeproc (0.5.1-1), pandoc-citeproc-preamble (1.6-1build1), Bibtex 5.6.11
- Zotero > export CSL JSON (keep updated)
- Zettlr > cite [@ZoteroYourPersonal]
- click export (PDF, PDF (latex), html to current directory (~/Documents)

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3 (UUID: 1a0f4c35-ab03-4f60-8481-d784f7d9abe4)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

PopOS (Ubuntu) 21.04

### Additional Information

PopOS flavor (System: linux 5.15.5-76051505-generic (architecture: x64))
**Pandoc is installed at /usr/bin/pandoc BUT below it looks for it at /opt/zettlr/resources**
Removing my pandoc and citeproc to keep resources/ ones didn't fix it.

Renderer flags
/opt/Zettlr/Zettlr
--type=renderer
--user-data-dir=/home/pm/.config/Zettlr
--app-path=/opt/Zettlr/resources/app.asar
--no-sandbox
--no-zygote
--field-trial-handle=1979288485036319880,17041230113095961137,131072
--disable-features=SpareRendererForSitePerProcess
--lang=en-US
--num-raster-threads=4
--enable-main-frame-before-activation
--renderer-client-id=8
--no-v8-untrusted-code-mitigations
--shared-files=v8_context_snapshot_data:100
Environment Variables
SHELL: /bin/bash
SESSION_MANAGER: local/3060:@/tmp/.ICE-unix/1977,unix/3060:/tmp/.ICE-unix/1977
QT_ACCESSIBILITY: 1
XDG_CONFIG_DIRS: /etc/xdg/xdg-pop:/etc/xdg
SSH_AGENT_LAUNCHER: gnome-keyring
XDG_MENU_PREFIX: gnome-
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
GTK_IM_MODULE: ibus
MANDATORY_PATH: /usr/share/gconf/pop.mandatory.path
LC_ADDRESS: fr_FR.UTF-8
GNOME_SHELL_SESSION_MODE: pop
LC_NAME: fr_FR.UTF-8
SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
XMODIFIERS: @im=ibus
DESKTOP_SESSION: pop
LC_MONETARY: fr_FR.UTF-8
GTK_MODULES: gail:atk-bridge:appmenu-gtk-module
PWD: /home/pm
XDG_SESSION_DESKTOP: pop
LOGNAME: pm
XDG_SESSION_TYPE: x11
GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
XAUTHORITY: /run/user/1000/gdm/Xauthority
GJS_DEBUG_TOPICS: JS ERROR;JS LOG
WINDOWPATH: 2
HOME: /home/pm
USERNAME: pm
LC_PAPER: fr_FR.UTF-8
LANG: en_US.UTF-8
XDG_CURRENT_DESKTOP: Unity
INVOCATION_ID: 4a6acd6d0b504029adc7d8281428cd49
MANAGERPID: 1696
GJS_DEBUG_OUTPUT: stderr
XDG_SESSION_CLASS: user
LC_IDENTIFICATION: fr_FR.UTF-8
DEFAULTS_PATH: /usr/share/gconf/pop.default.path
USER: pm
DISPLAY: :0
SHLVL: 0
LC_TELEPHONE: fr_FR.UTF-8
QT_IM_MODULE: ibus
LC_MEASUREMENT: fr_FR.UTF-8
XDG_RUNTIME_DIR: /run/user/1000
LC_TIME: fr_FR.UTF-8
JOURNAL_STREAM: 8:34516
GTK3_MODULES: xapp-gtk3-module
XDG_DATA_DIRS: /usr/share/pop:/home/pm/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
PATH: /opt/Zettlr/resources:/home/pm/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
GDMSESSION: pop
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
GIO_LAUNCHED_DESKTOP_FILE_PID: 72222
GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/Zettlr.desktop
LC_NUMERIC: fr_FR.UTF-8
CHROME_DESKTOP: Zettlr.desktop
ORIGINAL_XDG_CURRENT_DESKTOP: pop:GNOME
GDK_BACKEND: x11
PANDOC_PATH: /opt/Zettlr/resources/pandoc
ZETTLR_IS_TRAY_SUPPORTED: 1
GIT_SUPPORT: 1

**Comment by nathanlesage** [comment]
This is due to an error I accidentally made in the Lua filter for Zettelkasten links. It works fine if you select "Do not touch internal links" in the Export settings, and in the current nightlies AND it will work in the next release.

**Comment by j2l** [comment]
That's the fastest bug fix I've ever seen :smile: 
Thank you very much!
