### ISSUE TITLE
[Bug] Duplicate file more than two times lead to loss of information

### ISSUE THREAD

**Issue by fl-la** [Zettlr/Zettlr#2922]
### Description

(I had the issue at least two times).
I work a lot with file templates (lets say file A) and usually use the "duplicate file" functionality. If you work with yaml-header, the file name will be overruled in the sidebar. Therefore I missed to rename the file after duplicating it (duplicate 1 is called B). So you fill the (duplicated) file (B) with information. Once you duplicate the template file (A) once more it (to get a new file C) will overwrite the duplicated files (B) because of inproper file creation process (Linux). 

### Reproducing

- Create a template file
- duplicate it through the menu
- fill the file with inforamation
- duplicate the template file once more to see that the file is overwritten

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

pop!_OS 20.04

**Comment by nathanlesage** [comment]
Culprit line that needs to be adapted:

https://github.com/Zettlr/Zettlr/blob/4ef520cc3cca913999acf558c5d62eea0422a0c6/source/main/commands/file-duplicate.ts#L67

**Comment by fl-la** [comment]
Thanks a lot for the quick response and the fix!
