### ISSUE TITLE
[Bug] Closing and re-opening the file manager shows wrong directory

### ISSUE THREAD

**Issue by BabakFarshchian** [Zettlr/Zettlr#2929]
### Description

I go into distraction free mode by pushing Ctrl+J in Windows, with my project file browser window showing my files. When I push Ctrl+J to go back to normal mode, the file browser window has moved up one level and shows the parent folder of my project folder.

### Reproducing

In Windows, open a project folder with multiple files, push Ctrl+J twice to go to distraction free more and back. The content of the file browser window to the left side now shows the parent folder.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This might be related to the fact that we don't yet store info about which directories are collapsed and which are uncollapsed. Just for later reference when I get to this, would you mind sharing two screenshots — one showing how you saw it prior, and one how it becomes later?

**Comment by BabakFarshchian** [comment]
Here are some screenshots:

Before going to distraction free (DF):

![before-ctrl-j](https://user-images.githubusercontent.com/1062643/148202377-5d01cc6e-a27f-4461-9ef9-f5c671fe95a5.png)

During DF:

![during-ctrl-j](https://user-images.githubusercontent.com/1062643/148202375-d055b356-8991-4d10-a33d-48e85716cac8.png)

After going back from DF:

![after-ctrl-j](https://user-images.githubusercontent.com/1062643/148202373-fa8f89de-373a-4ebc-9562-752d5b838843.png)

**Comment by nathanlesage** [comment]
@BabakFarshchian Ah alright, so the file manager needs to remember if it has shown the file list or the file tree before being hidden. I think I can do that!

**Comment by nathanlesage** [comment]
This should be fixed by now.
