### ISSUE TITLE
[Request] Option to remove root files from file list

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#293]
There seems to be no option to remove/close (not 'delete') root files from the file list as it is possible for root directories in their context menu.
As the list of root files grows every time you open a file by double click in the file explorer of the operating system (Windows), things are getting a bit confusing over time.

**Comment by nathanlesage** [comment]
Yep, I've already spotted the error myself, I have it on my ToDo-List!

**Comment by nathanlesage** [comment]
There we go!
