### ISSUE TITLE
[Feature] display markmind json files

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#2930]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

I would love to use [markmind diagrams](https://github.com/MarkMindCkm/obsidian-markmind) in Zettlr. 
Please forgive me if this request is out of scope or does not make sense. 
But if it is posssible, I would love to see this support here. 

### Example Workflow

I use markmind as my MOC or context list for other notes. 
It helps me a lot to keep things organized.

### Caveats

no 

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
Not implementing this. Reasons:

1. Zettlr already ships with Mermaid, which works already fine
2. We cannot possibly support every diagram language (we might add PlantUML and/or diagrams.net, but that is not yet decided)
3. Markmind is not Open Source, and I will not add anything closed source to Zettlr.
