### ISSUE TITLE
[Bug] Image resizing in "Insert image from clipboard" prematurely rounds numbers

### ISSUE THREAD

**Issue by zh217** [Zettlr/Zettlr#2942]
### Description

Mildly frustrating behaviour when attempting to input manually the dimensions of the pasted image

### Reproducing

* Copy an image to the clipboard (my image has dimension 1340x824
* Paste in Zettlr with Ctrl-V
* In the dialogue that opens, attempt to set the size of the image
* For example, I want the width to be 400
* I attempt to type 400 in the resize image box, but probably due to some rounding up, what appears in the box after I press "4" is actually "3"

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

12.1 (21C52)

**Comment by nathanlesage** [comment]
Please add the version of Zettlr you currently use, since I thought I fixed that bug in 2.0.2

**Comment by zh217** [comment]
The bug is still present on 2.0.3

**Comment by nathanlesage** [comment]
Ah, I can make the re-calculation lazy and apply only after the input field has lost focus (so that you can type one number in full without the algorithm fiddling with it, and THEN tab away or click away and have the other number be calculated correspondingly)
