### ISSUE TITLE
[Bug] Exporting Project fails with embedded Images

### ISSUE THREAD

**Issue by newhinton** [Zettlr/Zettlr#2948]
### Description

When a Projectfolder contains notes with images that are stored in subfolders, the exporter fails with the following error:
`
ERR_FILE_NOT_FOUND (-6) loading 'file:///home/user/zettlr/folder/folder.html'`

Projects with a "flat" structure do not fail, aswell as projects without images

### Reproducing

1. Create Project
2. Add Subfolder
3. Create note with image in subfolder
4. export project

### Zettlr Version

Right off the develop branch

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 20.04

**Comment by nathanlesage** [comment]
This works in the current dev branch.
