### ISSUE TITLE
[Bug or Enhancement] Most relevant search results on top

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2953]
### Description

Whenever I search for something, the least relevant notes seem to go on top. 

Or more precise: the _least recently modified_ notes go on top, regardless of project folder sort settings.

So I always have to scroll down to find the most relevant note.

![image](https://user-images.githubusercontent.com/1702193/147175734-9752716f-e1a7-4165-8c47-655da36994d7.png)

### Proposed Changes

1. Because someone is more likely to search in their more recent work in progress, I think it makes logical sense to put the _most recently modified_ notes on top.
2. Alternatively, if this is by design for reasons unknown to me, there should be a setting for this.
3. Alternatively, the search result sorting order should follow the project folder sort settings

### Additional Information

I'm not sure if this is by design or not, making this an enhancement request or a bug report respectively.

**Comment by nathanlesage** [comment]
Good suggestions!

**Comment by nathanlesage** [comment]
Closed via 826f37b!
