### ISSUE TITLE
[Bug] Checkbox padding inconsistent with regular list item padding

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#2954]
### Description

Checkboxes now get quite a bit of horizontal padding---much more than non-checkbox list items.  This means that if we make a list with mixed checkable and uncheckable items, their hierarchy is obscured.

The reason this would be desirable is because sometimes I like adding notes underneath a checkbox item to flesh it out.  This used to work fine in older (pre-2.0?) versions of Zettlr.  Now, it looks confusing.

### Reproducing

Add this text:

```
- [ ] A checkbox item
    - With a nested note
```

Observe that these appear as if they are at the same level of hierarchy in the rendered view, even though the uncheckable list item is nested one level deeper.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 18.04

### Additional Information

I tried to fix this with custom CSS, but it was very difficult, because the left padding is specified via inline `style` attributes on the HTML tags, and because I had a hard time figuring out how to select specifically container elements which contained list items with checkboxes.

**Comment by nathanlesage** [comment]
Good catch! That was caused by an increased margin for especially the settings checkboxes.

**Comment by chiphogg** [comment]
Beautiful, thanks!
