### ISSUE TITLE
[Bug] The popup of Japanese Input Method hides the text

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#2958]
### Description

When I input Japanese text using IME(Input Method Editor), the suggestions pop-up overlaps the text I'm typing.

This is the same problem for which I once created a workaround.
[Issue #537](https://github.com/Zettlr/Zettlr/issues/537)
[Pull request #544](https://github.com/Zettlr/Zettlr/pull/544)

on zettlr 1.8.5: 
![image](https://user-images.githubusercontent.com/15438757/147403730-97664133-6c4b-45ff-94bb-ef0474cccb99.png)

### Reproducing

Input any Japanese text with Microsoft IME. (and possibly other languages/IMEs)

### Zettlr Version

Stable (but an older version)

### Specify version

1.8.5  or later

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
It can very well be that the workaround broke again in the meantime. Does this bug also occur in the most recent stable, that is: 2.1?

**Comment by nathanlesage** [comment]
I just checked, and your workaround code is still in the codebase:

![image](https://user-images.githubusercontent.com/17251683/147405050-62bc3951-5559-4774-a9d5-987cca726566.png)

**Comment by ryota-abe** [comment]
> It can very well be that the workaround broke again in the meantime. Does this bug also occur in the most recent stable, that is: 2.1?

Yes, it also occurs in v2.1.0
And now I am trying to fix my previous workaround.

**Comment by Serenade600** [comment]
This issue also occurs when Inputting chinese. On the same operating system and zettlr version.
