### ISSUE TITLE
Feature Request: Tray Icon with last x opened files

### ISSUE THREAD

**Issue by yennor** [Zettlr/Zettlr#296]
As it seems you're already planing to implement a tray icon, see: #175 .
It would be great if that tray icon when clicking on it would show the last 10 (configurable) edited files (notes). Since most probably I quickly want to open one of those.

**Comment by nathanlesage** [comment]
It would be simple to add the recent files to the context menu, so no problem

**Comment by v3ss0n** [comment]
Please this is necessary , stale bot close it too soon. 
Jus a tray icon would b efine.
