### ISSUE TITLE
[Bug] Maths editing sometimes fails for no apparent reason, and then any further math rendering also stops

### ISSUE THREAD

**Issue by zh217** [Zettlr/Zettlr#2965]
### Description

After failure the following errors are logged in the rendering process

<img width="553" alt="Screen Shot 2021-12-27 at 11 32 02" src="https://user-images.githubusercontent.com/2103823/147431651-970a39e4-22b9-4572-8eab-784b41ead319.png">

### Reproducing

I haven't yet found out a reliable way to trigger this, but it occurs several times per hour under heavy editing.

Closing Zettlr and reopening restores editing ability.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.0

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

12.1 (21C52)

**Comment by nathanlesage** [comment]
I couldn't trigger it reproducibly as well, but I just checked the culprit file (`render-math.ts`). There's one line where we access a `from` and a `to`, and that's the viewport we're using to render things. This indicates that maybe sometimes the `getViewport` method returns undefined, but that sounds bogus.

I also noticed that when someone clicks on the equation we should actually focus the editor again which is currently not happening, but that is a minor detail.

CC @tobiasdiez

**Comment by zh217** [comment]
I believe I encountered this bug before, but it becomes much more frequent after upgrading to 2.1.0.

Could we first fix this by "defensive programming", for example by catching the error so as not to let the whole math-rendering apparatus crumble? If the problem is really with `getViewport`, this is the most we can do anyway.

**Comment by nathanlesage** [comment]
While going after #2945, I accidentally found the bug that causes this issue :D
