### ISSUE TITLE
[Bug] Renamed directory names are not saved to config.json

### ISSUE THREAD

**Issue by gruhby** [Zettlr/Zettlr#2972]
### Description

Adding a directory to the file manager adds its name to `config.json`. Renaming this directory inside Zettlr via right click and "Rename directory" renames the directory in the file manager and in the file system but does not save this change to `config.json` on closing Zettlr. After restarting Zettlr the old directory name is shown with a "disconnected" icon.
Using right click and "Close workspace" on that directory it is immediatly removed from the file manager and also from `config.json` after closing Zettlr.

### Reproducing

* Add new Workspace directory
* Rename directory
* Close Zettlr
* Restart Zettlr => "disconnected" icon appears in front of old directory name

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.2

**Comment by nathanlesage** [comment]
Good catch, thanks for reporting!
