### ISSUE TITLE
[Enhancement] Do not display "No update available. You already have the most recent version."

### ISSUE THREAD

**Issue by sphh** [Zettlr/Zettlr#2973]
### Description

Currently whenever I start Zettlr, I get a notification, which tells me, that there are not updates available and that I already have the most recent version. It also tells me a about all updated languages, even if I do not use them.

### Proposed Changes

Please only display a notification message, if an update – either to Zettlr itself or to the selected language – is actually available.

### Caveats

Some people might prefer to be notified, that they are already at the latest version. But to be honest, I do not know of any software, which displays this as an automatic notification (it should be displayed, if the check was initiated manually).

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Linux Mint 20.2

### Additional Information

If there is an update available, it should not be displayed every time, Zettlr is started. It could be displayed once a day or once a week. I believe that would be enough.

**Comment by nathanlesage** [comment]
> But to be honest, I do not know of any software, which displays this as an automatic notification

You're right. Sounds like a very reasonable request.

**Comment by sphh** [comment]
Thanks @newhinton  and @nathanlesage‼
