### ISSUE TITLE
Image would not open externally 

### ISSUE THREAD

**Issue by ptbeck** [Zettlr/Zettlr#2974]
### Description

Image is found and represented normally on the Zettel. 

If you click on the top of the right hand corner to open it eternally that is with your standard image viewer, thenappears a caption which reads: 'image could not be found.' 

Problem is: At least on Windows there is a slash at the beginning of the line that prevents the image to be opened by your external app.
![Zettlr_too much slashes](https://user-images.githubusercontent.com/96795537/147699081-89f7882b-49b9-4952-8d09-f611db08bc59.jpg)

### Reproducing

Every time. 
Insert an image link from any directory which is not a sub-directory of your zettels. 
Image will be shown on the zettel, but be given an defective link so it could not be opened.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3 / 2.1.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This should no longer happen in the current dev branch.
