### ISSUE TITLE
[Enhancement] pressing enter from "Restrict search" box should search too

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#2977]
### Description

When selecting a note from a subdirectory on the tree view, the directory is auto-filled into the _"Full-Text Search"_ dialog in the _"Restrict search to directory"_ input. This can be convenient in certain cases, but if the user is looking for something completely different, they want to remove this constraint. 

They may intuitively press `tab`, `del`, `enter` to search without the directory restriction, only to find out that nothing really happens. To remedy this, they may want to press `shift + tab`, `enter` to switch back to the search term and activate search from there, only to find out pressing enter/return previously while _"Restrict search to directory"_ was focused had blurred the input box (i.e. removed the cursor) so there is no more 'going back'.

Both keyboard thingies should be available for the keyboard warrior.

### Proposed Changes

These are all little enhancements sort of related to the same form and same use case, so I'll just list them here.

1. Pressing enter/return while _"Restrict search to directory"_ is focused should search too.
2. Cursor should stay, allowing shift+tab to switch back to the _"Search terms"._
3. When selecting other unrelated notes (from tabs), the pre-filled "restrict search" value should be cleared, or directories should be popped off until the common parent folder that both the previous value and the currently selected note share is left.
4. Pressing `esc` on _"Search terms"_ should clear the search, just like it does when pressing `esc` on _"Restrict search"_ - #2970

### Caveats

no caveats

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Linux Mint 20.2 AKA Ubuntu 20.04.2

### Additional Information

![image](https://user-images.githubusercontent.com/1702193/147768276-507ae65b-379c-469c-a8c7-049bb19b0364.png)

**Comment by nathanlesage** [comment]
Totally forgot that I wanted to do that for 2.1 already! Thanks for reminding me
