### ISSUE TITLE
1.4.0-beta.2 issues

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#298]
I finally managed to install the new beta and it seems that there are no more issues with the `.ztr-directory` files when starting, although in the Console there is still a notice of `Directory Contents have changed!`

What surprised me is that the `Custom.css` information is dismissed in the editor. All my format is gone: font-family, size, colors. Can you please check what is happening?

**Comment by nathanlesage** [comment]
o.o

Okay the good news: Only one issue. But, the bad news: this one issue. Nevertheless, is the `custom.css`-file still present on disk in your data folder?

**Comment by samarulmeu** [comment]
Yes. Nothing changed. And when I use the Developper Tools and check the paragraph font (let's say) it reads the properties from the `Custom CSS` but they are strikethrough, returning to Zettlr fonts and colors.

**Comment by nathanlesage** [comment]
Ah, then this is likely an issue with changed scopes, as I've mentioned — the sidebar refactoring has brought about a lot of changes, so some of the Custom CSS has to be re-written for that update …

**Comment by samarulmeu** [comment]
But this did not happen in the beta.1! I mentioned then that I had to change the scopes for the sidebar, but inside it read my custom.css . The editor scopes (i. e. p styles -- it reads them correctly from my styles, but ignores them) would still remain the same.

**Comment by nathanlesage** [comment]
Aahhh, almost sounds like an issue with the order in which the styles are read. Do you mind sending me a screenshot example for one case in which the internal styles override your custom CSS?

… and have a look whether or not the custom CSS indeed is the last stylesheet imported in the document?

![image](https://user-images.githubusercontent.com/17251683/63653511-f5c1eb00-c76d-11e9-9f92-38ae89b97a04.png)

**Comment by samarulmeu** [comment]
Ok. First thing in the morning.

**Comment by samarulmeu** [comment]
Here is my screenshot. The strange thing is that font is correctly loaded for the sidebar: 

![customCSS](https://user-images.githubusercontent.com/39216570/63668135-e16a0680-c7de-11e9-9d07-1790d7497f0f.png)

**Comment by samarulmeu** [comment]
**Solved**:

`.CodeMirror-line` became in beta.2 `.CodeMirror-lines`

**Comment by nathanlesage** [comment]
Aaaaaah, yes, I wanted to say, that due to the most recent updates CodeMirror has also had some polish to its CSS classes: https://github.com/codemirror/CodeMirror/releases/tag/5.48.4

Sorry that I forgot this, I just saw it in your code!

Btw, concerning the non-quitting application: Same happens on Windows, as I just found out — I'll investigate! (But I can close this now, right ...? Or is there more? Then please comment :)

**Comment by samarulmeu** [comment]
It's OK. Then I'll also close the #290. Concerning the non-quitting -- I'll have to remember always to use the shortcut. If you want we can open a new issue or have it in your TO-DO list.

**Comment by nathanlesage** [comment]
I'll be testing it shortly on my Windows-machine to see what it spits out when I click the X. Maybe it's just a small logical error, otherwise I have to dig deeper!

**Comment by samarulmeu** [comment]
Maybe this could help you as it might be related. 

Today, by *mistake*, I closed the app using `Alt+F4` and I got the following error:

![errorZettlr](https://user-images.githubusercontent.com/39216570/63745854-eb0d7000-c8ab-11e9-8f1b-0741883b4c9c.png)

**Comment by nathanlesage** [comment]
Interesting, … say, did you press `Alt+F4` directly after starting the app? Then this might be because the watchdog wasn't started already … In any case, I just added an additional check to make sure the error isn't thrown!

**Comment by samarulmeu** [comment]
No. I had a lot of windows opened (Firefox, many folders in separate windows in the file manager and Zettlr). I worked for some time in Zettlr and then I started to close the file windows with `Alt+F4` and in the process of switching between them I ”accidentally” closed Zettlr. And then appeared the error, so not immediately. And it is always reproducible.

**Comment by nathanlesage** [comment]
Aaaaaaaaah you're right, it's 100 % my stupidity! The watchdog is now a service provider, so no wonder the variable is undefined. I just fixed that once and for all!

**Comment by samarulmeu** [comment]
That means you also solved the bug of the processes hanging in the backround when closing the window by clicking the x mark?

**Comment by nathanlesage** [comment]
... wait a moment - Yes, I think so o.O This could really be it!

Only question is: Why doesn't windows present me with the same JavaScript error, then …?

However: I'll do a nightly-build in the afternoon and send it to you, so then you could check if the error is also gone on Linux. If so, we can go onto the finishing line for 1.4! :)

**Comment by samarulmeu** [comment]
Perfect! I'll wait for the build. The 1.4 is already awesome! Meanwhile I should update the Romanian translation ;)

**Comment by nathanlesage** [comment]
Perfect, and I'll drop a mail to the French translators as well, because they're lagging behind a little bit, hehehehe

**Comment by nathanlesage** [comment]
As I don't know which Linux you're on, here are both RPM and DEB files:

Debian: https://drive.google.com/file/d/1-SvzzRC2tIT44mGirZpMBzAy85NvmkNv/view?usp=sharing
Fedora: https://drive.google.com/file/d/18G8USfUEG4ifbAnVm5y4lX4xz1vW2_X1/view?usp=sharing

**Comment by samarulmeu** [comment]
I'm using a Debian based distribution. I'll try it tomorrow. Hope it will install as it has the same name (beta.2)

**Comment by nathanlesage** [comment]
Perfect! If it doesn't, I think a previous uninstall may work …? Let's hope that works, so that we can release that monster on the beginning of September :)

**Comment by samarulmeu** [comment]
I wished I had better news. First I installed over and then I did an uninstall and a clean install. The same behaviour as before. Zettlr quits only with `Ctrl+Q`.

Closing it using `Alt+F4` displays this error:

![2019-08-27-194010_1366x768_scrot](https://user-images.githubusercontent.com/39216570/63791058-49b20880-c903-11e9-8167-84aa68320d88.png)

I think that we may have to live with it.

**Comment by nathanlesage** [comment]
Nope, we don't have to live with this. I just figured out I forgot a `shutdown()`-method on a provider. I guess the main problem indeed is that I only have a macOS-testing environment and therefore it takes a lot of time to detect such subtle bugs.

Here's a fixed debian-file, if you don't mind testing once again: https://drive.google.com/file/d/1sM_RmXEBfab1NP3ami7_hm8jC66zzuBN/view?usp=sharing

**Comment by samarulmeu** [comment]
I'll give it a try in the morning.

Maybe you should try VirtualBox and install a light Linux distro (Lubuntu is great) and have a testing platform.

**Comment by samarulmeu** [comment]
Hurray! `Alt+F4` and the `X` button work as expected. No more process in the background. Great job and Thank you!

Now I think you can concentrate on releasing the 1.4 and then maybe enjoy a well deserved holiday!

**Comment by nathanlesage** [comment]
<3 Perfect! :)

And as for testing: I honestly would love to, but despite lacking resources (128GB SSD MacBook, it's hard to fit whole Operating Systems on there) I simply lack the time to do more than coding and testing on macOS; after all I still have research to do :D 

But that's what I have people like you for, who are such a great help in testing out the app on many different operating systems and helping me find bugs that don't, e.g., trigger on macOS!

Btw this reminds me that I'm currently thinking of founding some sort of "beta testing league" of people who always test the app on as many different settings as possible and help develop some guidelines for testing!

**Comment by samarulmeu** [comment]
I really appreciate what you do and I imagine that you have a limited amount of time and it truly amazes me that you still are able to develop the app. I suggested the virtualization thinking that you need a fast feedback. 

Otherwise I am really happy to help you as Zettrl helps me tremendously in my writing -- it's such a joy to use it. And it becomes better and better. So count me in the "beta testing league". As I mentioned I'm using a Debian based distribution. And you can send me packages to test at any time.
