### ISSUE TITLE
Add a way for toolbar customization

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#2987]
Since we have had multiple requests (#2980; #2685) for new toolbar buttons in the past weeks after I cleaned up the toolbar, we need some mechanism to customize the toolbar. There are basically two ways of doing this:

1. The "cool" macOS way with drag and drop (hard to implement)
2. (For now) a simple array of checkboxes in the settings to programmatically activate/deactivate buttons to show up

If anyone wants to give that a shot before me, feel free, the three places to touch would be the config (to store the choices, using the current (!) array as defaults), the App.vue component in the main window (where you can instead of simply returning the array of toolbar buttons build that array programmatically depending on the config) and a new preferences schema in the preferences window offering a new tab with all these choices.

***

If you wish to get on this, please comment here so we know someone is working on this.

**Comment by lanceli237** [comment]
Hi Nathan, this is Lance, hope you are doing well. We are a course group of six members from The University of Adelaide, trying to complete this issue and make a contribution. Thanks for your three hints above about the toolbar feature. We will try to kick off this issue from next week. If you come up with any more ideas, please don't hesitate to contact with us. Cheers

**Comment by nathanlesage** [comment]
@lanceli237 Thank you for tackling this issue! Please feel free to reach out in case you have any questions! Please also feel free to share here a first concept as soon as you came up with one so we can have a look collectively if it's good or if there could be improvements made! :)

**Comment by haoliudev** [comment]
@nathanlesage Hello Nathan,  as mentioned by @lanceli237, we are a group of students from the University of Adelaide and we love to learn from and contribute to the Zettlr project. 

We have added a new preference window [toolbar] to save the config control button display.
The code is here: https://github.com/EdgarTang/Zettlr/tree/customize-toolbar

Now We have two questions regarding toolbar customization. 

1. Is it a good idea to add a boolean "visible" attribute to button objects(which is set to true by default)? In this way, we can display/hide by ticking/unticking an array of checkboxes to change the "visible" values. To avoid affecting other buttons, the corresponding button will only be hidden when "visible" exists and is set as false.

2. When the toolbar config is changed, we noticed that the GUI must be refreshed for the settings to take effect. The problem is that we do not know how to call the method to refresh the GUI. Could you please give us some advice or explanation?


![2987](https://user-images.githubusercontent.com/85983213/165676827-74197cbf-891f-4785-9839-223f9ba64c62.gif)

**Comment by nathanlesage** [comment]
@haoliudev Hej, thanks for the efforts!

> We have added a new preference window [toolbar]

This is a solid solution. My only fear is that we may end up getting too many tabs in that window, and I don't have any good idea of how to mitigate that problem. Do you maybe have an idea? (If not, this is strictly speaking not in scope for this issue, and therefore you don't have to worry about this specific problem!)

> Is it a good idea to add a boolean "visible" attribute to button objects (which is set to true by default)?

Yes. This is how its done in other places as well.

> In this way, we can display/hide by ticking/unticking an array of checkboxes to change the "visible" values. To avoid affecting other buttons, the corresponding button will only be hidden when "visible" exists and is set as false.

Absolutely correct. Display by default, but allow selective switching off.

> When the toolbar config is changed, we noticed that the GUI must be refreshed for the settings to take effect.

The keyword here is reactivity. Basically you need to listen to changes in the configuration, which can be done automatically with a little bit of magic by vue:

Since the toolbar buttons are configured in the `App.vue` component, you want to add some logic in there. Specifically, you need to create a new `computed` property that returns the corresponding config. See this property taken from the component as an example:

```js
sidebarVisible: function (): boolean {
  return this.$store.state.config['window.sidebarVisible']
}
```

You can simply access the config value as you have defined it in the global config.

Then, in the toolbar config property, you want to access these computed properties to conditionally display or hide the button. See, again, another code snippet, also taken from App.vue, that does precisely this:

```js
{
  type: 'button',
  id: 'show-tag-cloud',
  title: trans('toolbar.tag_cloud'),
  icon: 'tags',
  badge: this.hasTagSuggestions
}
```

Pay attention to how the `badge` property is set to either `true` or `false` depending on the computed property `hasTagSuggestions`. This here will toggle on and off the badge on the tag button in the toolbar. It works similar for your use-case, just with your property and the corresponding `computed` properties.

Then it will work automatically without the need to refresh. The reason is that the store will be notified once the config has changed, it will then reload the config, and Vue will notify every component that accesses the config that it has changed, and therefore will call all of those functions one by one until the toolbar is being filled with the new, updated state.

***

One last thing, though: We might want to add many more toolbar buttons in your upcoming PR. All of them should then be disabled by default except those buttons that are on the toolbar as of now. This way, users will not see a changed toolbar (since the same buttons are present) but can add those that they additionally need, and then individually disable those they don't need.

One button for example is a button to create a "new file". I dropped that one and ever since users have complained, so if you could also add that one (albeit disabled, as I said), this would be awesome.

One last thought: While we're at it, we could extend this to enable or disable *every* element on the toolbar, including the word counter and the pomodoro timer? (but NOT the file manager three way toggle and the sidebar. These buttons need to stay no matter what because disabling them will have unintended consequences)

**Comment by EdgarTang** [comment]
@nathanlesage Hello Nathan, this is Edgar from @lanceli237 team.
Thank you for the help about reload UI. We have multiple config settings for the toolbar. I think one function to get them is better than writing many functions in `computed`. So I set a new `method` function to get the config. Now it can auto-reload after the user changes the setting. 
~~~
customizeToolbarVisible: function (configName: string): boolean {...}
~~~ 

> One last thing, though: We might want to add many more toolbar buttons in your upcoming PR. All of them should then be disabled by default except those buttons that are on the toolbar as of now. This way, users will not see a changed toolbar (since the same buttons are present) but can add those that they additionally need, and then individually disable those they don't need.
> 

Of course yes, we can do the same change for all the toolbar controls.
I have already finished a demo for  #2980 
![2980](https://user-images.githubusercontent.com/48198383/165903597-9b48a84a-3dff-4863-aa42-602dbc984e83.gif)

> One button for example is a button to create a "new file". I dropped that one and ever since users have complained, so if you could also add that one (albeit disabled, as I said), this would be awesome.
> 

I have already finished a demo for  #2685 
![2685](https://user-images.githubusercontent.com/48198383/165903696-457a8321-4bda-4904-baff-d6d5f7a6b52a.gif)

> One last thought: While we're at it, we could extend this to enable or disable _every_ element on the toolbar, including the word counter and the pomodoro timer? (but NOT the file manager three way toggle and the sidebar. These buttons need to stay no matter what because disabling them will have unintended consequences)

![2987](https://user-images.githubusercontent.com/48198383/165903916-8ba5d3ed-80de-4fa0-ae42-3787a3702549.gif
I have tried. All the changes as been uploaded to [my fork](https://github.com/EdgarTang/Zettlr). We will submit a pull request after all is finished.

**Comment by nathanlesage** [comment]
> I think one function to get them is better than writing many functions in computed. So I set a new method function to get the config.

Wait, and that is reactive, i.e. it updates automatically as soon as a config change happens …? Or do you have to do some magic to make that happen …?

With regard to the other things: Amazing, this looks awesome! I can't wait for the PR!

**Comment by EdgarTang** [comment]
> Wait, and that is reactive, i.e. it updates automatically as soon as a config change happens …? Or do you have to do some magic to make that happen …?
> 
That's my question. I am not familiar with Vue.Js. I know Vue is reactive. How ever I can not understand why `visible: (global as any).config.get('customizeToolbar.showNewFileButton')` is not working. But never mind, currently the code is working well now.

code in `computed:`
![WeChat3b6ef570e877acad65b82289ec152748](https://user-images.githubusercontent.com/48198383/165908616-3271bde8-40eb-48ad-a116-4acdd19700e9.png)

code in `method:`
![WeChat127d9988bdbc0cbab3273ef0b0937d8a](https://user-images.githubusercontent.com/48198383/165908633-7dc408f3-5957-4335-9e3c-2d3302296742.png)

By the way, should I allow users to customize the button on the yellow part displays or not?
![WeChat98f26044948d76d195e9e09652952285](https://user-images.githubusercontent.com/48198383/165909964-9ffc0ad3-93e8-4e45-addc-2acec5d8b3ef.png)

Last question, before we submit the PR. How can I add new translations?  Should I hard code them in `static/lang/eu-EU.json` first, or do it on [Zettlr Translate](https://translate.zettlr.com/) after the merge?

**Comment by EdgarTang** [comment]
> Last question, before we submit the PR. How can I add new translations? Should I hard code them in `static/lang/eu-EU.json` first, or do it on [Zettlr Translate](https://translate.zettlr.com/) after the merge?

And can I use menu translate on the toolbar? Like:
![WeChat9426e48fd561bd5f8a1e258fc091235e](https://user-images.githubusercontent.com/48198383/165910511-44ec0054-bcf2-40ec-8512-80812087636d.png)
I know this is not good.....

**Comment by nathanlesage** [comment]
> How ever I can not understand why visible: (global as any).config.get('customizeToolbar.showNewFileButton') is not working.

Ah okay. I thought as much. In order to make the app react to changes in those settings, you **must use computed properties** -- one per config setting. It does make the app more verbose, yes, but then it will be reactive. So you would want to add a computed property as I showed you. Also, this would make your PR much more in line with the code style of the rest of the repository.

> By the way, should I allow users to customize the button on the yellow part displays or not?

The first yellow rectangle not because these are important buttons. The share button should also be always visible. But you can also allow people to hide the readability mode button.

> How can I add new translations? Should I hard code them in static/lang/eu-EU.json first, or do it on [Zettlr Translate](https://translate.zettlr.com/) after the merge?

The latter. The most ideal way would be for you to simply provide me with a list of all new translation strings that you have implemented as well as a suggested wording for English. This way I can just copy and paste that into Zettlr translate!

> And can I use menu translate on the toolbar?

Absolutely. This is the intended usage!

**Comment by EdgarTang** [comment]
@nathanlesage thank you for the help us so much, Nathan. These new features are all done, we'll be testing them on macOS, Linux and Windows this weekend, and if all goes well we'll submit a PR next week.

**Comment by nathanlesage** [comment]
@joaocarvalhoopen Wrong issue ;) I believe there is a setting in the preferences that when you're on Windows you can actually do that already. You just need to enable said setting and then turn on distraction free mode.

**Comment by joaocarvalhoopen** [comment]
Hello @nathanlesage Hendrik,
Thank you, that works well in Linux!
After I test it in F11 – Full screen mode, I didn’t understand why the window bar didn’t disappear. That would be awesome.

Best regards, João

**Comment by nathanlesage** [comment]
> After I test it in F11 – Full screen mode, I didn’t understand why the window bar didn’t disappear. That would be awesome.

Again, different issue! Please feel free to collect some screenshots and open a new one, if not already happened!
