### ISSUE TITLE
Menu accessible by shortcuts [Enhancement] 

### ISSUE THREAD

**Issue by ptbeck** [Zettlr/Zettlr#2995]
### Description

That would make life easier.

For instance Next / Previous step in history Ctrl + [   /  Ctrl + ] 

As far as I see on a German keyboard it is not even possible to pinch this connection. 

### Proposed Changes

So I would propose something like

for English keyboard 

Alt - f (Menu file), then Letter “n” or “p” for next and previous. 

Modification for other languages would be great, but not indispensable. 
Alt - d for “Datei”, then “n” or “v”. 

### Caveats

Do not see how. 

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
All of this has to do with how Electron assigns menu shortcuts. To cut a long story short: It's a mess. I'm currently evaluating options of just not using the menu accelerators anymore since they are so unreliable.

Please see this issue for more context: #818

Closing in favor of #818
