### ISSUE TITLE
[Feature] Keyboard Shortcut for Code

### ISSUE THREAD

**Issue by Viguro79** [Zettlr/Zettlr#2997]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

 Create a keyboard shortcut to make the selection `Code` or insert new `Code` formatting characters, as `Cmd/Ctrl+B` does in order to make the selection **bold** or insert new **bold** formatting characters.

### Example Workflow

No workflow

### Caveats

No caveats

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by leo-hstone** [comment]
I built myself a small workaround with a snippet, maybe this is also suitable for you :)

![image](https://user-images.githubusercontent.com/62036826/149510784-14aa7a69-dc07-4cbe-9df2-b88acf3f80b8.png)

You can find the Assset Manager here: File > Preferences

You can insert the snippet by typing a semicolon followed by the snippet name:
```
:python
```

**Comment by kyaso** [comment]
An alternative/addition to what @leo-hstone proposed above would be to create an _AutoCorrect_ (in Preferences). This is especially useful for _inline_ code. For example, you could use key `.c.` (or whatever you prefer) to automatically insert two backticks.

As for turning a selection into code, Zettlr already has that (admittedly, not a keyboard shortcut, but still). Simply highlight the text, and wait for the tooltip to pop up. Then click on the `< >` (second from right in the picture below):
![image](https://user-images.githubusercontent.com/18646029/150549600-c4a66758-8da1-44c5-9db7-b77f059a3790.png)

**Comment by nathanlesage** [comment]
This issue almost sounds as if we should improve the documentation to cover these things, doesn't it? Would anyone like to do a PR to the docs with this?

**Comment by MithrilMan** [comment]
Having shortcuts for code fences would help a lot, I second that.
Coming from Typora what I miss most, actually, are really these shortcuts:

- code fences (select code, press keyboard combination and it surround your selection with single backtick for inline code or triple backticks for multiple line of code)
- set heading size (e.g. CTRL + 1 = # , CTRL + 2 = ##, etc...)

P.S.
I just started using this product and I need to use it mostly to generate technical software documentation that often contains code and sequencing diagrams (mermaid)
