### ISSUE TITLE
[Bug] icon next to workspace not updating

### ISSUE THREAD

**Issue by developpeur-pro** [Zettlr/Zettlr#2999]
### Description

Unable to change the icon associated to a workspace.

### Reproducing

- In the workspaces pane, I open the properties of a workspace and choose an icon -> the icon displays correctly on the left of the workspace name.
- Now, I want to change the icon. I open the properties and choose a new icon -> the icon does not update :
![image](https://user-images.githubusercontent.com/16106898/148207088-651e906e-2df2-4899-8308-2c480aef24e3.png)

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I could not reproduce this locally. Would you mind removing the `.ztr-directory`-file in that directory, and try it again? Maybe the file has become corrupted at some point.

**Comment by developpeur-pro** [comment]
After deleting the file, I can indeed change the icon, and it apparently works. But the problem is in fact not solved.

Here's a repeatable scenario:

1. Close Zettlr
2. Delete the ztr-directory file
3. Launch Zettlr
4. Assign the 'heart-broken' icon to the workspace.
5. Close then reopen the properties and assign the icon 'crown' → the icon is not displayed.

In the ztlr-directory file, we can see the following text:
`{"sorting": "name-up", "project": null, "icon": "crown"} roken "}`
The file is therefore effectively corrupted. It must be deleted in order to be able to assign the desired icon.

**Comment by nathanlesage** [comment]
The file you show is definitely corrupted, yes. But even though I followed your exact steps, I cannot reproduce this issue :/

Are there any errors logged to the console after the bug appears?

**Comment by developpeur-pro** [comment]
hmm, strange...
No, I don't see any error in the console.
The zrt-directory file seems to show that when it is written, the existing line is not completely replaced. If the new line is shorter than the old one, the last characters of the old line remains. Looking at the code, can you see something that confirm this ?

**Comment by atspaeth** [comment]
I had the same problem in version 2.2.4 on Ubuntu 21.10 AMD64. So I guess it must not be at the OS level, but it's some kind of Heisenbug. I removed my user preferences directory from `~/.config/Zettlr` and let Zettlr generate a new one, which solved the issue, and it didn't come back when I put the old preferences directory back in place.

**Comment by nathanlesage** [comment]
Hmmm, interesting. @developpeur-pro Would you mind trying the same as @atspaeth ? Maybe it helps?

**Comment by nathanlesage** [comment]
Due to inactivity, and since I could never reproduce this, I'm going to assume this issue is fixed.
