### ISSUE TITLE
[Bug] 1.4.0beta-2: No images in exported PDF via Pandoc

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#300]
## Description/Reproducing

As far as I can evaluate, there are no images shown in exported PDF files, no matter what kind of image paths (absolute/relative) are used within the Zettlr/Markdown file. The image descriptions however are converted correctly.

## Platform
 - OS: Windows
 - OS Version: 7 & 10
 - Zettlr Version: 1.4.0beta-2

**Comment by Raqbit** [comment]
Same here, it seems like images are not exported at all, just descriptions.
It does work for http(s) urls though.

---
OS: Ubuntu 19.04
Zettlr Version: 1.4.1

**Comment by nathanlesage** [comment]
No errors or stuff?

**Comment by jothanne** [comment]
Yes - no errors or other messages on my Windows 7 & 10 computers.

**Comment by nathanlesage** [comment]
Found the culprit: Zettlr always made sure a `file://`-protocol was present. I blamed the file back but couldn't find the commit where I added that code, so I'm not sure _why_ I added the code but apparently HTML output was broken at some point. I may have to re-do the function at some point, but it *should* work now. Comes in 1.4.2.
