### ISSUE TITLE
[Feature] Toggle to source code mode

### ISSUE THREAD

**Issue by chchen2021** [Zettlr/Zettlr#3003]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Can Zettlr offer a quick switch between the normal mode (with customized rendering options) and the source code mode? 

The vast majority of the time, I am in the normal mode. But occasionally I would like to do troubleshooting or some fancy search and replace, for which it is handy to reveal the source code and then quickly go back to the normal mode. 

Of course one can click all the rendering options off to get the source code, but it is rather cumbersome to click back and forth so many options. I also tried changing config.json, but it does not seem to affect things. (As an example, I tried changing the papertype from a4paper to letter. Although the change persisted, the PDF Document Export was not affected.)

### Example Workflow

Ideally a button on the toolbar to toggle between the source mode and normal mode. Alternatively, a menu item for the toggle so it's easy to do keyboard shortcut. (The requested toggle has been implemented in Typora and Obsidian.)

### Caveats

Potential conflicts with the Display Preferences. 

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [ ] Windows
- [X] macOS
- [ ] Linux

**Comment by leo-hstone** [comment]
As a workaround for your issue I can recommend to open the file in a good text editor. I recommend Notepad++, as it has builtin syntax highlighting for Markdown. In addition you can activate the option in Zettlr "always load remote changes to current file" (General Tab)

**Comment by chchen2021** [comment]
Thanks for the tip. If a file is local, I can always use another editor to view the source code and then come back to Zettlr. However, for iCloud files, opening in another editor often leads to a saving conflict. This is the primary reason for me to suggest the "toggle to source code" feature within Zettlr, in addition to the obvious convenience of being able to do everything in one place. 

Not exactly sure what is causing the problems when an iCloud file is opened by both Zettlr and another editor. On Zettlr, the autosave is turned off. Nearly all iOS apps will autosave. This might be one of the problems, but Zettlr seems to be particularly problematic with iCloud files that are open by another app. The "always load remote changes to current file" option is enabled on my Zettlr.

**Comment by nathanlesage** [comment]
There are plans to integrate an easy toggle between `WYSIWYG` (all rendering on), `WYSIWYM` (all rendering off) and `custom` (manually select, just as it is now) in the settings.
