### ISSUE TITLE
how to use app language translation(json)？

### ISSUE THREAD

**Issue by y-forbetter** [Zettlr/Zettlr#301]
once download a translation json document,how to apply it?

**Comment by nathanlesage** [comment]
## Zettlr 1.3

Download the respective translation from [Zettlr Translate](https://translate.zettlr.com/), open your app, then go to the `File` menu -> `Import Translation…`. This will open the translation folder. Put the translation there. Then, open the settings and your translation should automatically be detected. Select it, save the preferences and restart the app. The translation should now be loaded.

To update, simply re-download the updated translation and overwrite your translation file in the folder.

## Zettlr 1.4

Open your preferences, click on the language you would like to use. Zettlr will automatically download it from Zettlr Translate, place it in above-mentioned folder, and apply it. Restart your app, and the translation should now be loaded.

Zettlr 1.4 will automatically download translations if they have been updated in the meantime. This requires an active internet connection at the start of the app.
