### ISSUE TITLE
[Enhancement] Indicate in Table of Contents tab the section the cursor is in

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#3012]
### Description

The Table of Contents tab currently enables you to go to any section you want to by clicking on it, but it doesn't currently give a visual guide as to which section you are actually in. When working with a large document it's often helpful to be able to see at a glance which section you're in. Either emboldening or highlighting the name of the section the cursor's currently in on the Table of Contents tab would help with awareness of one's current location in the document. 

### Proposed Changes

Change the drawing of the TOC tab, so that the section the cursor's in is made more obvious -- either by highlighting it, or displaying it in bold.

### Caveats

This would require redrawing the TOC when the cursor goes from one section to another, but I don't think that this would be computationally expensive. 

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by kyaso** [comment]
I would also welcome this feature!

**Comment by nathanlesage** [comment]
@kyaso This should be fairly easy to implement, if you like give it a shot!

All the information you need is already available to the MainSidebar component.

The ToC entries contain the starting line, so the cursor must be greater than or equal to the line of a ToC entry while being less than the next entry. The line where the cursor is at is stored in `this.$store.state.activeDocumentInfo.cursor.line`

**Comment by kyaso** [comment]
> This should be fairly easy to implement, if you like give it a shot!

Indeed, I have thought about giving it a try, as I have plenty of time this weekend :smiley: 

Thanks for the hints, that should save me some time!

**Comment by kyaso** [comment]
@nathanlesage I crafted something over at #3071.

Also, currently, only the _cursor_ position is relevant. However, I know of examples, where additionally the _scroll_ position is also considered (e.g. Google Docs). What do you think?

**Comment by nathanlesage** [comment]
@kyaso Yes, definitely. For this we could add the viewport information to the document info. Then we could do that. The question would be which one makes more sense 🧐 idk, maybe discuss that on Discord...?

**Comment by kyaso** [comment]
> maybe discuss that on Discord...?

Sure, feel free to start a thread!

**Comment by nathanlesage** [comment]
Done!
