### ISSUE TITLE
[Bug] Zettlr 2.1.1 conflicts with Draw.io desktop (rpm installs)

### ISSUE THREAD

**Issue by tleepa** [Zettlr/Zettlr#3013]
### Description

Zettlr 2.1.0 can co-exist with with Draw.io, but Zettlr 2.1.1 can not.

I had Zettlr 2.1.0 installed along with latest draw.io desktop (16.1.2). I was trying to update Zettlr to the latest (at that time 2.1.1) version, which failed.

I have uninstalled Draw.io and installed Zettlr 2.1.1 only - working fine, however trying to install draw.io along has failed with the same error.

### Reproducing

1. Install draw.io: `sudo dnf install https://github.com/jgraph/drawio-desktop/releases/download/v16.1.2/drawio-x86_64-16.1.2.rpm`
2. Install Zettlr: `sudo dnf install https://github.com/Zettlr/Zettlr/releases/download/v2.1.1/Zettlr-2.1.1-x86_64.rpm`
3. Observe error message

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Linux 35 (KDE Plasma)

### Additional Information

Error log:

```shell
❯ sudo dnf install zettlr        
Last metadata expiration check: 0:02:13 ago on Sat 08 Jan 2022 04:53:00 PM CET.
Dependencies resolved.
===========================================================================================================================================================================================================
 Package                                          Architecture                                     Version                                           Repository                                       Size
===========================================================================================================================================================================================================
Installing:
 zettlr                                           x86_64                                           2.1.1-1                                           local                                            85 M

Transaction Summary
===========================================================================================================================================================================================================
Install  1 Package

Total size: 85 M
Installed size: 392 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/17/be10f23f85f57671bfb21ecf8c105a64ab6ef1 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/55/dc566f6c0bf7712c5313dbb6abc93a241353e7 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/5e/454361d23477f6c57f2b93cbcb0db9deda9f48 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/72/104f9eac4e2f4f11acbe134348fb2de234d273 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/ae/95cfe865250b789af383a3d41377f602ec8ef9 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/d4/aab0a51d28bbc3ab1aec6c0745f0b7b1f32638 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/d7/e87eb010f04dcd7e5a1256848fff65fc6ce03b from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/e8/e657160f7e7a726708fbca8f2e918308b54433 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/ec/ca5e0942d94160bcb65f93943ad95aa9293e02 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
  file /usr/lib/.build-id/f7/8ba2ea803e9af2418b17b26f175b7279e73a71 from install of zettlr-2.1.1-1.x86_64 conflicts with file from package draw.io-16.1.2-1.x86_64
```

I would guess that draw.io desktop may not be the only electron app failing to co-exist with latest Zettlr, but am unable to provide more examples.

I noticed `Update to Electron 16` changelog entry, which may look as the good candidate for a culprit, but I know nothing about it, so it may be a blind guess.

**Comment by nathanlesage** [comment]
We've had these problems in the past. Something in the manifest files of Electron conflicts between versions of Electron, so if Zettlr used 16, and draw.io uses 15 or so, that can be a problem. I'm unsure we can take any action here :/

**Comment by tleepa** [comment]
One more question: 

I am not a developer, nor I have any idea on how to package applications for rpms, etc. but AFAIK Electron is supposed to be bundled with an app - separate electron copy for each app, so - in theory - they should not get in each other ways, right?

I have more electron-based applications installed: VSCode, Insomnia, Postman, but these do not conflict with Zettlr - only Draw.io. Do you have any idea why?

And please, do not treat this as a rant or request for you to fix this - I am grateful for the software and your work and perfectly fine for this issue to be unresolved - I can live with the workarounds :)

**Comment by nathanlesage** [comment]
> so - in theory - they should not get in each other ways, right?

Precisely.

> I have more electron-based applications installed: VSCode, Insomnia, Postman, but these do not conflict with Zettlr - only Draw.io. Do you have any idea why?

That is the problem: I don't know :S 

I just double-checked, but Zettlr does not define any external dependencies in the build process, so I don't know what might be causing this :/

> And please, do not treat this as a rant or request for you to fix this

Don't worry, no offense taken! What you experience is objectively non ideal, so it's good you report this -- even though I don't know what the cause is.

**Comment by tleepa** [comment]
Great! Thank you for your time.
Shall I close this issue?

**Comment by nathanlesage** [comment]
Yeah, as long as we don't know sure! If anything regarding info changes, feel free to reopen this issue and add that info :)
