### ISSUE TITLE
[Bug] Closing tab with MMB copies clipboard to other note

### ISSUE THREAD

**Issue by shaunirwin** [Zettlr/Zettlr#3019]
### Description

When closing a tab using the middle mouse button, the clipboard contents get copied into a remaining open note.

### Reproducing

1. Open two notes in tab "A" and "B"
2. In tab A, select some text and ctrl-C to copy
3. Middle mouse click tab A to close the tab
4. The clipboard contents will often be copied into the note in tab B

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by kyaso** [comment]
Duplicate of #2663

**Comment by shaunirwin** [comment]
Apologies for not having spotted the other ticket! Yes, it is indeed a duplicate. I will close this one.

**Comment by nathanlesage** [comment]
@kyaso Thanks, I just had a re-read of this issue and I found this reference to another issue: https://github.com/atom/tabs/issues/461

I'm not sure whether this might actually be a fix, would you mind trying it out? It should work by going into `source/win-main/DocumentTabs.vue` and in line 242 remove `event.stopPropagation()` and instead put `return false` after the next statement, `this.handleClickClose(event, file)`

Maybe that workaround from over at Atom works and we can fix this bug for good?

**Comment by kyaso** [comment]
@nathanlesage Sure, I'll have a look into it later today!

**Comment by kyaso** [comment]
I modified the `handleClickFilename` like shown below, but unfortunately, the issue remains :(

```vue.js
handleClickFilename: function (event: MouseEvent, file: any) {
    if (event.button === 1) {
      // It was a middle-click (auxiliary button), so we should instead close
      // the file.
      event.preventDefault() // Otherwise, on Windows we'd have a middle-click-scroll
      //event.stopPropagation() // In response to #2663       <=== removed
      this.handleClickClose(event, file)
      return false                                         // <=== added
    } else if (event.button === 0) {
      // It was a left-click. (We must check because otherwise we would also
      // perform this action on a right-click (button === 2), but that event
      // must be handled by the container).
      this.selectFile(file)
    }
  }
```

**Comment by nathanlesage** [comment]
Dammit :( it's such a bummer that such a neat feature can malfunction so much…
