### ISSUE TITLE
Problem with new notes and ordering (1.4.0 beta 2)

### ISSUE THREAD

**Issue by dambaras** [Zettlr/Zettlr#302]
1.4.0 beta 2 problem:
 I have set my notes to sort by date modified in descending order. When I create a new note, it is added to the bottom of my list of notes, even though it should appear at the top of the list. Even after auto-save, the note remains at the bottom of the list. I have to manually click on the sort order button again (twice!) to bring it to the top. 

Needless to say, this is not how things should work. Most important, not being able to see the note name in the list while writing is very disconcerting and causes me to lose time and flow by having first to confirm that the note has actually been titled as I intended.

(I should add that in general, for as long as I've been using Zettlr, the note ordering has been less natural than it should be. I come at this from having used nvAlt for years and then The Archive for a while. I just want to see the newest note at the top of the list, without having to worry about it. Thanks for reading; I hope this makes sense.)

**Comment by nathanlesage** [comment]
Thanks for reporting the bug, had two lines of code interchanged! It'll work in the next release!

**Comment by samarulmeu** [comment]
This is happening for all the notes, not only for the new ones. So you have to do a manual time reordering in order to get the ones that you work on and save them them on top, where they belong. 
Hope it will work too.

**Comment by nathanlesage** [comment]
Yup, as I said, I simply forgot to retrieve the actual modification time BEFORE sorting (so the sorting function basically only sorted zeroes) — stupid mistake, but thankfully we found the bug!
