### ISSUE TITLE
[Bug] Inserting a link to another md file pastes the name twice

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3028]
### Description

![image](https://user-images.githubusercontent.com/62036826/149192336-bcbb9017-36c0-493f-bced-b7e7e78af74b.png)

If I begin to type a link with two square brackets open, Zettlr automtically recommends files. If I press enter or tab, the selected name of the file is pasted twice.

![image](https://user-images.githubusercontent.com/62036826/149192530-97a63c38-426d-4378-b182-ed4aa487b9a5.png)

If this is intended behaviour, I would like to turn this into a feature request to disable this behaviour :D 

### Reproducing

See description above.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.1 

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

System: win32 10.0.18363 (architecture: x64)

### Additional Information

Operating System Version took from the "About Zettlr" page.

**Comment by nathanlesage** [comment]
Does the following setting in the "Zettelkasten" tab of the preferences possibly look like this?

![image](https://user-images.githubusercontent.com/17251683/149205714-946d1c2c-6605-46ff-911c-5101bbc03686.png)

If you set it to "only when linking with ID" or "never", Zettlr shouldn't add the filename a second time.

If this solves your issue, please close this issue. If it doesn't, you probably found a bug!

**Comment by leo-hstone** [comment]
This solved my issue. I suggest to add this setting to the Guide to use Zettlr as note taking app (https://docs.zettlr.com/en/guides/guide-notes/)

**Comment by nathanlesage** [comment]
@leo-hstone Huh, these guides still exist? I thought I deleted them a while ago o.O But it's actually good since some people wanted those guides back online either way. Good point to discuss.
