### ISSUE TITLE
[Bug] Option windows like Preferences open outside visible screen after swapping multimonitor setups

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3037]
### Description

When switching betweend external monitor setups Zettlr sometimes opens option windows like preferences or the asset manager outside the screen area ("on the unplugged monitor"). 

Possible fix: always open the option windows on the monitor where the main instance is displayed.

### Reproducing

1. Use Zettlr in a multimonitor setup with all monitors to the left of a laptop. 
2. Have Zettlr opened on an external monitor and work with preferences on this external monitor. 
3. Close Zettlr (and shutdown system).
4. Open Zettlr on another multimonitor setup with the monitors on the right.
5. Open the preferences. 

I can't really locate the opened window. It is also not visible in the taskbar. 

With the tool [Borderline](https://www.taenarum.com/software/Borderline.html) you can bring all open hidden windows back to monitor 1. This is the only workaround I have found that works.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

win32 10.0.18363 (architecture: x64)

### Additional Information

For everyone having the same issue with Zettlr or with other programs have a look at the  [Borderline](https://www.taenarum.com/software/Borderline.html) tool.

**Comment by nathanlesage** [comment]
> Possible fix: always open the option windows on the monitor where the main instance is displayed.

That is already what is happening. Whenever a window is opened, Zettlr performs a sanity check that the windows are in view. Apparently there's a logical error somewhere in the code. Relevant code:

https://github.com/Zettlr/Zettlr/blob/develop/source/main/modules/window-manager/index.ts#L405-L438

**Comment by nathanlesage** [comment]
Does this still happen?
