### ISSUE TITLE
[Enhancement] Typewriter-Mode should focus on the visually displayed line & different shortcut

### ISSUE THREAD

**Issue by dagdrommer** [Zettlr/Zettlr#3039]
### Description

1. The Typewriter-Mode is a handy tool that let me focus to what is atm relevant (the line of text I'm writing). But atm the typewriter focuses the "real", complete line of the markdown document. Zetters margin settings are often visually breaking a line (which makes sense and is good as it is). As Zettler is aiming for scientific writing and colleges and me prefer to write down our thoughts quickly (multiple sentences in one row), the Typewriter focus gets quickly cluttered and looses its aim.

2. Furthermore, on may Linux distros Ctrl+Alt+T opens the terminal and is therefore not a useful shortcut to start the typewriter mode.

### Proposed Changes

1. Let the Typewriter focus on the visually displayed line, instead of the actual complete line.
2. Give users the option to change shortcuts.

### Caveats

Not that I am aware of.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Arch Linux, Win 10

**Comment by nathanlesage** [comment]
> Let the Typewriter focus on the visually displayed line, instead of the actual complete line.

This is not possible with the current implementation of CodeMirror. In order to achieve this, you'd have to manually break the lines.

> Give users the option to change shortcuts.

That's a whole different story and is being actively discussed [here](https://github.com/Zettlr/Zettlr/issues/818).

Closing since 1. is unfixable and 2. is discussed in #818

**Comment by dagdrommer** [comment]
Thank you for the immediate response.

Thats surly a pity, but ok. Is there a way that allows to trigger the scrolling a little earlier, so that the cursor won't end up that much down in a page?
