### ISSUE TITLE
[Bug] Export Project - ERR_FILE_NOT_FOUND (-6) loading 'file:///Users/ ... html'

### ISSUE THREAD

**Issue by 1eneh** [Zettlr/Zettlr#3041]
### Description

Hello,
I am operating Zettlr on a MacOS Big Sur, v. 11.6. I updated Zettlr recently to Version 2.1.2 (2.1.2). In the past, I have been able to export projects to PDF and .docx. However, today I encountered two types of errors:
1) ERR_FILE_NOT_FOUND (-6) loading 'file:///Users/...html'
2) YAML parse exception at line 2, column 2: mapping values are not allowed in this context

After resetting the app (https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app), I now only face the first error: ERR_FILE_NOT_FOUND (-6) loading 'file:///Users/...html'

How do I solve the problem and regain the functionality to export projects?

Thanks,
e

### Reproducing

I have YAML frontmatter for each file.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.6

**Comment by nathanlesage** [comment]
So error number two is likely because at some point you may have created a map where something else was required:

```yaml
# The following is a map
some_var:
  prop1: 1
  prop2: "Hi"
```

However, the other error seems to relate to the fact that Zettlr can't find the intermediary file for a PDF export. Let me guess: You are exporting `PDF Document` and not `PDF (LaTeX)`, right? In that case, an intermediary HTML file is being written, which I suppose it can't find. However, this would not explain the error during docx-export.

Are there any error logs after you encounter this error? (Activate the debug mode in the advanced preferences and then, in the newly appearing menu, choose "Open logs")

**Comment by 1eneh** [comment]
Thanks for the quick response. I toggled PDF (LaTeX) in addition to PDF document and Microsoft Word.

Here is what appears in the error log:
Export failed: YAML parse exception at line 2, column 2: mapping values are not allowed in this context
ERR_FILE_NOT_FOUND (-6) loading 'file:///Users/...Notes.html'
Could not load URL file:///Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/renderer/error/index.html: ERR_FAILED (-2) loading 'file:///Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/renderer/error/index.html?title=Export+failed%3A+YAML+parse+exception+at+line+2%2C+column+2%3A%0Amapping+values+are+not+allowed+in+this+context&message=Export+failed%3A+YAML+parse+exception+at+line+2%2C+column+2%3A%0Amapping+values+are+not+allowed+in+this+context&contents='
[20:31:56]	Export failed: YAML parse exception at line 2, column 2: mapping values are not allowed in this context

**Comment by nathanlesage** [comment]
That is weird: The error suggests that the entry point of an internal window could not be found, which should not happen o.O

I will have a look. (And again: There is some error, either in a frontmatter, or your corresponding defaults file that Pandoc doesn't like)

**Comment by 1eneh** [comment]
Thanks so much.

**Comment by 1eneh** [comment]
Hallo, any prospect of resolving this issue? Anything I can do?

**Comment by nathanlesage** [comment]
Ah sorry, forgot about this! Let me have a look … Alright, I cannot reproduce this, so I think my intuition is right that I just accidentally messed up the error window in 2.1.2 and then fixed it in the meantime. I want to release 2.1.3 in a short amount of time, then the errors will be gone for good!

(But not your YAML error, that is a different error ;)
