### ISSUE TITLE
[Enhancement] [vim mode] Make CTRL-C copy instead of exiting insert mode

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3042]
### Description

Currently, `CTRL-C` in Vim-mode does exactly what you expect from it in regular Vim: exit _insert_ mode and return to _normal_ mode. (To not confuse Vim's _normal_ mode with Zettlr's _Normal_ editor mode, I will call Zettlr's Normal mode "Default mode")

However, if you use a GUI-based editor like Zettlr, you usually associate `CTRL-C` only with "copy". Therefore, it would be nice if there was a way to override the default behavior of CodeMirror's Vim-mode `CTRL-C`, so that it instead performs a "copy".

---

**Additional info**
- In _insert_ mode, `CTRL-V` and `CTRL-X` work as in Default mode.
- Copying workaround for now: We can still right-click and then select "Copy" from the context menu; that still works.

### Proposed Changes

Instead of Vim-mode's default behavior for `CTRL-C` (in _insert_ mode), always perform a "copy" action.

I found this [issue](https://github.com/codemirror/CodeMirror/issues/3075) over at the CodeMirror repo, asking for the same question. There, the solution was to remap the keys in some custom vim key-binding config (specific to that code editor that uses CodeMirror).

### Caveats

Might mess with some people's muscle memory. -> Maybe make that feature an option?

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
Since I'm not the vim guy either way would be fine with me. However I don't exactly know how the vim mode works and a friend of mine already wants that status bar, so I'm not putting this as high priority, if that's okay?

**Comment by kyaso** [comment]
> I'm not putting this as high priority, if that's okay?

Yeah, no worries!

I think, for now, the benefits of the other Vim features (which work great so far!) outweigh the occasional burden of having to reach to the mouse for copying. And this only matters when you want to copy text from Zettlr into some _other_ application; within Zettlr, you can still use Vim's _yanking_ (which btw, also works across tabs!).

**Comment by nathanlesage** [comment]
> Vim's yanking (which btw, also works across document tabs!).

Unintentional, but I'm glad that it works 😄 I'm really just using the plugin that's already there!

**Comment by kyaso** [comment]
Related issues: #1065, #977
