### ISSUE TITLE
[Bug] 1.4.0beta-2: Accidentaly overwriting files

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#305]
Sorry for being so late, but I just discover this bug and maybe you'll be able to fix it before launching 1.4.0 as I think it is very important and **dangerous**. 

So create 2 files `test1` and `test2`. Then rename `test1` in `test2`. Zettlr overwrites the `test2` without asking, so the content of `test2` is gone forever. The normal behavior will be to check if a file with the same name exists and ask if it is ok to overwrite.

**Comment by nathanlesage** [comment]
Well, this behaviour has been around since like ever, and it didn't become much of a problem until now. I already uploaded the binaries, and I'm out of town now, so it won't make it in 1.4, but there's always the possibility to patch it later on! Thanks for reporting, anyway, because you're right: We should at least check! :)

**Comment by samarulmeu** [comment]
Ok. Then in a later patch. I discovered it the hard way -- if I did not have a backup, I would have lost an article. No I'll try to check it every time.

**Comment by nathanlesage** [comment]
Btw just found a way to ask for replacing files, but while I did that I realised that I should be updating the whole dialog-thing with the app :D But it's in there already, so it shouldn't be too long :)

**Comment by samarulmeu** [comment]
Waiting for it. I think that is a serious bug and it is strange it was not discovered till now. For me was not so much of a problem as I am using git and doing a regular backup, but for someone without it could mean disaster. 

Congratulations on the 1.4.0!!! I'm going right away to download and install it. Zettlr is *almost* perfect and you did an amazing job! You can party or just relax ;-)

**Comment by nathanlesage** [comment]
That was the plan 😁

**Comment by nathanlesage** [comment]
Will be closed with issue #308, so I'll close this for maintaining a clean issue list! :)
