### ISSUE TITLE
[Feature] integrate polulus-viewer

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#3058]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Integrate [populus-viewer](https://github.com/opentower/populus-viewer) (open-source) for collaborative document annotation. 

### Example Workflow

I'm sorry, but the video shows the potential way better than I could explain. 

### Caveats

no

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
Zettlr is an offline app, so I do not see any way in which we could reasonably integrate something that requires running a server.

Among other things, why we cannot integrate that, or Hypothes.is, for that matter, into Zettlr as it stands now:

- It requires a team of some sort (a department, a company, a university) that has their own server architecture
- It is built around PDF, not around Markdown
- It requires online usage on a server, not offline inside a desktop app

What could be possible is a way to pull in any annotations from such an instance into Zettlr, but that would need to be done by the team of populus.
