### ISSUE TITLE
[Bug] Asset Manager code editors do not scale with window.

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3066]
### Description

![image](https://user-images.githubusercontent.com/62036826/150531597-fc14730b-06aa-42e2-a627-98130c9000f6.png)

It would be a lot easier to have a larger editor :D 

Or can one edit the file externally?

### Reproducing

Open Asset Manager and resize window.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by leo-hstone** [comment]
Small addition: A link to the docs in the snippet window would be great! I found out about the extended syntax way too late^^

```
Snippets let you define resuable pieces of text with variables. See the docs for some examples!
Insert a snippet by writing a smicolon and the snippet name.```

**Comment by kyaso** [comment]
> Or can one edit the file externally?

Yes, you can! At least on Linux, the snippets are located your **config directory** (`~/.config/Zettlr/snippets`). On Windows, it should be something like `C:\Users\<username>\AppData\Roaming\Zettlr\snippets` (@nathanlesage correct me if I'm wrong).

**Comment by nathanlesage** [comment]
@kyaso That looks perfectly right! :)
