### ISSUE TITLE
[Bug] AutoCorrect symbols are detected as spell checking error

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3068]
### Description

Zettlr marks my arrows `-->` as spelling error. All symbols in the AutoCorrect list should be automatically ignored.

### Reproducing

Activate spell checking for German. Type `-->` or paste any other no-ascii symbol.

### Zettlr Version

Nightly

### Specify version

2.1.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

Happened on stable before and now sill on nightly.

**Comment by kyaso** [comment]
For now, you could add your symbols manually to the dictionary (right-click symbol -> "Add to dictionary").

But I see your point. It can be indeed visually annoying when every symbol is marked as "incorrect".

@nathanlesage What is your opinion on this?

**Comment by nathanlesage** [comment]
@kyaso At one point I actually added these values to the spell checker, but it broke, and I haven't gotten into the mood of looking that up again 🙈  Basically, we need to cache the value of the corresponding key in the dictionary provider in an array, and simply look into the array when a request from a renderer comes in.

**Comment by nathanlesage** [comment]
Fixed!
