### ISSUE TITLE
Copy filename in editor pane context menu

### ISSUE THREAD

**Issue by xerocross** [Zettlr/Zettlr#3069]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

As a Zettlr user, I want to easily link my zettels together to form a zettelkasten. It would make things a little easier if I could copy the filename (minus extension) of a file (zettel) from the editing pane tab using the context menu.

### Example Workflow

As a zettelkasten user of Zettler, I want to quickly create links between relevant notes/files/zettels. I have a few of them open in the editing pane currently. I use the filename as the ID, which Zettlr already supports as default behavior. I want to quickly grab the ID of one of my existing zettels so I can put a link to it in another one I am editing. So I simply click the other file to get its context menu, I select "copy name" or something like that, and this copies the name of the file to my clipboard. I can then easily paste it into a link in another file.

### Caveats

The context menu currently has very few items, so I think there is no caveat against this addition.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

[](url
![feature_request](https://user-images.githubusercontent.com/2170147/150576740-8d3dbd51-acb9-4da5-bb48-a92bf8f216e0.PNG)
)

**Comment by kyaso** [comment]
When typing an internal link `[[`, Zettlr shows you a list of files as you type. There you can quickly select the target file.

I agree that having a copy file (or path) option in the context menu might still be useful.
