### ISSUE TITLE
[bug] 1.4.0 "delete file" dose not delete

### ISSUE THREAD

**Issue by afenc** [Zettlr/Zettlr#307]
## Description
"Delete file" dose not work.

1. Right-click and choose "Delete file" on any file at sidebar.
2. Nothing happened.

## Expected behaviour
The chosen file should be trashed.

**Screenshots**

## Platform
 - OS: Mac
 - OS Version 10.14.6 
 - Zettlr Version 1.4.0

**Comment by nathanlesage** [comment]
Please refer to the collection thread to stay tuned when the fix for this problem will arrive: https://github.com/Zettlr/Zettlr/issues/308
