### ISSUE TITLE
[Bug, Nightly] Renaming files broken

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3070]
### Description

After renaming a file in the file tree with rmt+contextmenu the file was correctly renamed on drive but the file tree has not updated the file name nor is the file not clickable.

### Reproducing

1. create file
2. rmt on file in file tree > rename file
3. file is renamed on disk
but
- filetree is not updated
- file in filetree is not responsiv

Logfile

[-1642785371020.log](https://github.com/Zettlr/Zettlr/files/7916064/-1642785371020.log)
e

### Zettlr Version

Nightly

### Specify version

2.1.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Just tried this out, I saw that this doesn't even work when just creating a new file and then typing stuff. Apparently the file descriptor is not correctly sent. However, since this works on macOS, there must be something platform specific afoul ...

**Comment by nathanlesage** [comment]
Fixed it at some point in one of the latest releases apparently :D
