### ISSUE TITLE
[Bug] Character counting error.

### ISSUE THREAD

**Issue by Yan-Zero** [Zettlr/Zettlr#3075]
### Description

File manager counts words instead of character although I ticked "Count character instead of words".

![image](https://user-images.githubusercontent.com/32036413/150682637-a09d420b-7394-482b-aca0-5433c996495d.png)

### Reproducing

Ticked "Count character instead of words"?

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by derwok** [comment]
I think I've got an idea how to fix this. 🧐
https://github.com/Zettlr/Zettlr/blob/92e75b3e83293e87ea02d2843ce17ce2956646d7/source/win-main/file-manager/file-item.vue#L295-L302

I already spotted, we need two places for the fix: one for directories and one for files.
I will give it a shot...

**Comment by nathanlesage** [comment]
@derwok Oh Gosh, that TODO must be in there for months 👀

But yes, should be easy to fix! Feel free to open a PR if you'd like to :)

**Comment by derwok** [comment]
Here you go.
First time me getting in contact w/ Vue's reactivity (only did Metoer.js a few years back...)

**Comment by nathanlesage** [comment]
> Here you go. First time me getting in contact w/ Vue's reactivity (only did Meteor.js a few years back...)

I understand this sentence only too well. If you wanna read about my suffering with Vue's reactivity, feel free: https://www.hendrik-erz.de/post/death-by-proxy
