### ISSUE TITLE
[Bug] RevealJS Export fails when using variables

### ISSUE THREAD

**Issue by vtcarlino** [Zettlr/Zettlr#3076]
### Description

Zettlr fails to exports in reveal.JS format when I use variables in the YAML frontmatter or in the defaults file.

This bug happens when output destination is set to temporary and current directory.

### Reproducing

Add any reveal.JS variable (for example: `progress: false`) to YAML frontmatter or file defaults and export file to reveal.JS format.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.2

### Your Platform

- [X] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 and macOS 10.15.7

### Additional Information

Error message: 

`ENOENT: no such file or directory, open '/var/folders/h4/nw9l_1cj5y93y5gkt49n709c0000gn/T/Support_Sociologie_journalisme.revealjs'`

**Comment by nathanlesage** [comment]
Thanks! I think in general we might want to look up whether we can just run a standard Pandoc export, instead of all the code Harakiri that Zettlr currently does. That might potentially fix other issues that haven't yet surfaced.

**Comment by nathanlesage** [comment]
This is obsolete now with the revealjs weirdness I did gone.
