### ISSUE TITLE
[BUG] Dialogs malfunctioning [COLLECTION]

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#308]
This should serve as a collective thread, because many bugs currently reported pertain to a single issue: That the dialogs stopped working in 1.4. So if you encounter any dialog not doing its work, it's best to discuss it here. This is meant as a safeguard not to flood the issuelist with things that relate and will be fixed by the hotfix 1.4.1, due to release tomorrow at latest.

## What?

Yesterday, we released Zettlr 1.4. We were proud to finally have a new release. Nevertheless, prior to releasing, we've updated the underlying Electron binary to 6.0.7. According to the official documentation, nothing should've happened. Nevertheless, they've changed the signature of the dialogs to promise-based Object returns. This resulted in all the prior functions to not work correctly anymore.

## Oh, snap!

To make things worse, new users won't be able to open any directories, as the dialog doesn't return the selected directory, so the function will fail silently. Additionally, some users can't quit the app normally, as the "There are unsaved changes!"-dialog box won't report that the user has indeed just reiterated his/her desperate wish to FINALLY exit the app without having to kill it with the lethal instruments.

## And now?

I discovered the bug a few hours ago. I won't be able to complete the work on refactoring all these functions until tomorrow, but you can be sure: weekend is canceled to make sure 1.4 works as expected and not with all of these issues!

Stay tuned, and please accept my apologises for the inconveniences!

P.S.: As long as you use the app as intended, you should actually be fine, as the most important dialogs (Preferences, Custom CSS, Tag Management, etc.) are not using the builtins, but my own solution. So sometimes it _does_ help to re-invent the wheel, apparently …

**Comment by nathanlesage** [comment]
In case anybody could confirm dialogs working again on Linux/Windows, I could close this issue!

**Comment by samarulmeu** [comment]
I can confirm that #305 is solved.

**Comment by nathanlesage** [comment]
And the dialogs work again?

**Comment by samarulmeu** [comment]
I did not encountered any of the other's problems so I can't say. On my Lubuntu seems ok, although I leave for tomorrow the extensive testing.

**Comment by nathanlesage** [comment]
Alright, I'll keep the issue open until verification :)

**Comment by afenc** [comment]
on Mac 10.14.6
keyboard shortcut for delete file  "cmd+delete" dose not trigger the dialogue.

**Comment by nathanlesage** [comment]
Closing as the issue seems to be remedied

**Comment by Brli** [comment]
1.4.1 still failed to launch on Arch.

How can I create more verbose output for debug?

**Comment by samarulmeu** [comment]
Although this issue is closed, I added here something I found today. If I try to move a file in a directory where a file with the same name exists, Zettlr just tells me only that the file exists. It will be nice to have the option in the dialog to overwrite as sometimes it is what you want to do. Now the only way is to go trough the file manager way out of Zettlr.

**Comment by nathanlesage** [comment]
Yup, I implemented the "nono"-dialog because I needed to do it quick'n'dirty for release with the 1.4.1, so the overwriting will be implemented, but when I have more time :) If I forget it prior to 1.4.2, please remind me!

**Comment by samarulmeu** [comment]
OK. Hope my memory will not fail me again 😉
