### ISSUE TITLE
[Feature] Option to turn off tag detection.

### ISSUE THREAD

**Issue by wiwikuan** [Zettlr/Zettlr#3082]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Everything after the `#` is recognized as a tag, but maybe there's someone like me who doesn't use tags. But I can't find an option to turn that off.

### Example Workflow

I often use markdown files to write music chord charts, and in chord charts we use a lot of `#` and `b` to mean altered notes. Like:

`Eb7(#9) | Ab13(b9) | Db7(#5, #9) | Gb13`

The #5 and #9's in text are all recognized as a tag by Zettlr and have a different color, which is a bit annoying.

Or, are there any ways that I can disable the tag coloring instead?

### Caveats

No.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

This is a screenshot of me trying to do chord charts in Zettlr:

![image](https://user-images.githubusercontent.com/4676714/150977179-85ca3f04-ab5a-44a3-9d51-f874e3968839.png)

**Comment by kyaso** [comment]
One option would be to put everything inside a **code block**, like so (three backticks above and below):
![grafik](https://user-images.githubusercontent.com/18646029/150982339-259c9242-8cfc-4bc1-ba57-a633ce18e33a.png)

Note, that you can't use any other formatting (e.g. bold or italics) inside a code block.

Alternatively, you can remove the styling of tags with this custom CSS:
```css
body #editor .CodeMirror .cm-zkn-tag {
  color: unset;
  font-weight: unset;
}

body.dark #editor .CodeMirror .cm-zkn-tag {
  color: unset;
  font-weight: unset;
}
```

**Comment by nathanlesage** [comment]
@kyaso I would rather use `inherit` rather than `unset`, or? (I have never used the unset value there, so I may be wrong here!)

**Comment by kyaso** [comment]
@nathanlesage Oh, could be that `inherit` also works! I only tested it with `unset` and it seemed to do its job.

**Comment by wiwikuan** [comment]
@kyaso Thanks! This solves 99% of my problems! 

It would still be nice if there's an option to turn off tag **suggestions**, because every time I enter a `#` a pop-up menu still appears. 

Screenshot: 

![image](https://user-images.githubusercontent.com/4676714/151099416-ecca704f-1fa4-4ebb-8c83-58950534359a.png)

**Comment by nathanlesage** [comment]
Hm. We could add an option to programmatically activate/disable those autocomplete lists …?

**Comment by kyaso** [comment]
> We could add an option to programmatically activate/disable those autocomplete lists …?

I have no objections against this.

**Comment by wiwikuan** [comment]
> Hm. We could add an option to programmatically activate/disable those autocomplete lists …?

That would be great!

**Comment by nathanlesage** [comment]
Then I'm gonna close this one and open a new one!
