### ISSUE TITLE
[Enhancement] Show text labels under the icons in the Settings window for easier navigation (Windows 10)

### ISSUE THREAD

**Issue by barinovdesign** [Zettlr/Zettlr#3083]
### Description

On Windows 10, the tabs in the Settings window are labeled with icons only and no text. This makes it difficult to understand what kinds of settings each tab contains.

![image](https://user-images.githubusercontent.com/77417160/150978212-a51a941a-7612-4606-a19f-de877437f217.png)

### Proposed Changes

Add text under the icons (the same way it is done on MacOS) or show only the text because text is more descriptive than the icons.

### Caveats

The only caveat is that showing both the icons and the text could take up more screen real estate (depending on how the tabs are designed), but the UX improvements would be worth it, in my opinion.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10 (10.0.19044)

**Comment by nathanlesage** [comment]
This was a recent change: If the preferences window is too narrow the labels will be hidden. To show them again, just increase the width of the window. I haven't yet found a suitable UI model of how to place labels underneath the icons within the Windows Metro design …

**Comment by barinovdesign** [comment]
Ok, great! I didn't realize that the Settings window was resizable. Thank you.
