### ISSUE TITLE
[QUESTION/FEATURE REQUEST]: Superscript, Subscript

### ISSUE THREAD

**Issue by DutchPete** [Zettlr/Zettlr#309]
## Description
If I am not mistaken superscript and subscript, i.e. Abc<sup>5</sup>, H<sub>2</sub>O (as examples), do not work in Zettlr, even though they are part of Github Flavoured Markdown, as shown here.

If that is correct, I would like to request it.

## Expected behaviour

**Screenshots**

## Platform
 - OS Version [e.g. 11]
 - Zettlr Version [e.g. 0.15]
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
You can use superscript and subscript like so:

```markdown
Some ~subscript~ and some ^superscript^ here.
```

It'll work with Pandoc.

**Comment by DutchPete** [comment]
@nathanlesage : I have Pandoc installed and am using Zettlr 1.4.1, but your suggested markup for sub and superscript does not work.
OS: Linux Mint 19.2.

**Comment by nathanlesage** [comment]
This is weird … it works for me (but not always on LaTeX) — nevertheless, it's dependant on Pandoc and/or XeLaTeX, so it's out of the bounds of Zettlr.

**Comment by DutchPete** [comment]
@nathanlesage : I upgraded to the latest version of Pandoc, 2.7.3, but it still does not work.
You say it is out of bounds of Zettlr, but the rendering is controlled by Zettlr. Zettlr on Linux is not rendering this, in other words
`H~2~O`
is not rendered as H<sub>2</sub>O, but remains with the tildes.

**Comment by nathanlesage** [comment]
So you mean the simple previewing, _not_ the actual exporting? Then this would be something to consider for the WYSIWYG-Plugin. However, I'm hesitant adding this as support is not that great, and if you see something rendered superscript when, in fact, the engine that you use (you could easily use another one), does not support that. Hence, I'd currently opt against this, as it's not in the [CommonMark specs](https://spec.commonmark.org/0.29/).

**Comment by DutchPete** [comment]
Yes, I mean the previewing.

I do not quite understand your reasoning, maybe due to my lack of technical knowledge, but when one wants to show bold text with 2 asterisks on each side of the text, it is rendered as bold in the previewing. Why can that not be the same for super/subscript?

BTW, I thought Zettlr complies with Github Flavoured Markdown; in GFM sub/superscript is part of the specs, although it is done with`<sup>text</sup>`.

**Comment by nathanlesage** [comment]
To cut a long story short: The superscript and subscript are not yet implemented in the GFM-mode of CodeMirror (which Zettlr uses), as this demo shows:

![grafik](https://user-images.githubusercontent.com/17251683/64519446-69c6cc00-d2f4-11e9-8f13-b0aad3787467.png)

[Here the link to the demo](https://codemirror.net/mode/gfm/index.html)

If you'd like to have it supported, please implement it and open a PR on the CodeMirror repository. Then, Zettlr will also support this beginning from the next time CodeMirror gets a new release and Zettlr then receives a new release.

**Comment by DutchPete** [comment]
OK, issue can be closed.
