### ISSUE TITLE
[Enhancement] Leipzig glossing

### ISSUE THREAD

**Issue by ashprice** [Zettlr/Zettlr#3093]
### Description

It would be wonderful for me as someone who works with linguistics texts a lot be able to write my glosses _in_ Zettlr in a way that is low-friction. Currently I have to use tables, use plaintext and a lot of spaces (both of which give very hard to read results, particularly with long examples) or compile a gloss in LaTeX and input a screenshot. Please see here if you're unfamiliar with the concept/practice: https://en.wikipedia.org/wiki/Interlinear_gloss

### Proposed Changes

The inclusion of a Javascript library in the same vein as KaTeX or Mermaid to allow for frictionless interaction with interlinear glosses. An example of such a utility is here: https://bdchauvette.net/leipzig.js/

It would make sense for Leipzig glosses to be edited in the same way we currently interact with Mermaid, with a code block where Mermaid is specified. In terms of the editing of the gloss, the curly brace syntax where everything between braces belongs to one 'morph'/word/individual item around which spaces are present should be familiar to most linguists using any of the major glossing packages/libraries in LaTeX or the web. 

### Caveats

Aside from the small space taken up by a utility like Leipzig, I can't think of any. 

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

5.16.2-arch1-1

### Additional Information

I am willing to try to write my own utility or to backwards-engineer Leipzig into working with Zettlr. I have very little experience of programming outside of bash scripting and statistical work with python, but I will spend some time looking at how Zettlr, KaTeX, Zettlr + KaTeX, and Leipzig work under the hood over the next few weeks.

**Comment by ashprice** [comment]
Hmm - I don't think I had much business volunteering to implement it, but I wanted to try to figure it out to learn. 

I opted to take the package approach. Using the examples of the image, katex, and mermaid renderers I made a glossSpan element, but I'm unsure how to pass the code block to the Leipzig function. I'm not able to test it yet to see what happens as I've stalled on figuring out how to make a declaration file; I will have another stab at this tomorrow.

**Comment by nathanlesage** [comment]
Please don't stress yourself: All work here is voluntarily, so no need for rushing :)

**Comment by ashprice** [comment]
Mostly I was worried that I was stuck, and I think I still am. Do I need to write a type declaration file for Leipzig (I'm not sure how to, but I've been doing some reading on it), or can I just import it from the node_modules directory? Presumably there's a better way to do it than writing the full relative path?

**Comment by nathanlesage** [comment]
Yes. If you have installed it as an NPM package, you should `import leipzig from 'package-name'`, that should work. With regard to types, if it doesn't have some, we might have to declare them (similar to how I did with regard to citeproc).

In case you're really stuck, I have two suggestions: First, open a **draft** PR already, even though the code is not working. This way more people can look at the code and give you much more useful hints. Second, especially for small questions, it would be good to ask these directly on Discord, we have a developer channel there!
