### ISSUE TITLE
Add support for textbundle

### ISSUE THREAD

**Issue by seeseekey** [Zettlr/Zettlr#31]
It would be nice if Zettlr would support the markdown interchange format Texbundle, see http://textbundle.org/

**Comment by nathanlesage** [comment]
Looks interesting! I'll have a look and implement it as soon as I find some time for it!

**Comment by nickmilo** [comment]
Second!

**Comment by jcuenod** [comment]
I'll add my name to the list of supporters of this idea.

**Comment by nathanlesage** [comment]
@jcuenod As Textbundle is precisely thought of as an interchange format, the implementation by Zettlr of Textbundle would be strictly import/export-related, i.e. that internally, Zettlr still uses plain old Markdown.

**Comment by nathanlesage** [comment]
It's coming in 1.2! 🎉

**Comment by filipgoc** [comment]
A little celebration of this milestone: 

As of July 2019, Zettlr is still the only Free (beer/speech) app listed on http://textbundle.org/ to support Textbundle on Windows. 

🍾

**Comment by nathanlesage** [comment]
Not that difficult, given the fact that TextBundle has been designed for macOS, the only environment where people think it's cool to charge subscription fees for things as simple as a Markdown editor 🤷‍♂
