### ISSUE TITLE
FR: PDF prefs > chapter numbering off

### ISSUE THREAD

**Issue by thob** [Zettlr/Zettlr#310]
It would be very nice to enhance this part of the settings. It helps _tex-challenged users_ to still achieve a few scenarios.
 - another one would be left-aligned as an option

**Comment by nathanlesage** [comment]
Hey,

both issues you reported cannot be achieved with settings, but need to be put manually, but it's actually rather easy:

First, for the left/right/center/justified-alignment, see our FAQ: https://docs.zettlr.com/en/faq/#i-cant-seem-to-align-the-text-just-or-right

Please see also: https://docs.zettlr.com/en/academic/custom-templates/

And, to disable chapter numberings, after each of your headings you'll need to put `{-}`:

```markdown
# This is some header without number {-}

Some text

## This heading will have a number
```

**Comment by thob** [comment]
OK! I just thought that via settings you could somehow add `\raggedright` or `\setcounter{secnumdepth}{-\maxdimen}`

**Comment by nathanlesage** [comment]
I think you can achieve what you want, by [savingthe Zettlr default template](https://github.com/Zettlr/Zettlr/blob/master/source/main/assets/export.tex) somewhere on your computer, [selecting it in your preferences](https://docs.zettlr.com/en/reference/settings/#general-preferences) and add whatever you'd like to the template!
