### ISSUE TITLE
[Feature] Show bib resource title preview

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3101]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

To simplify the workflow with multiple bib resources from the same group of authors, a preview of the document title would be great. 

One possible implementation could be to display the title like a link when hovering over links with the mouse pointer.
In this case, other bib information could be displayed as a summary. A click directly on the "Attachment" field in this preview could also simplify or supplement the workflow to open an attached pdf file.

### Example Workflow

Multiple bib resources with the same author (group) can be distinguished easily.

### Caveats

None to my knowledge.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
I'm not sure I understand what exactly you mean here. Would you mind giving an example, maybe even with screenshots? That would be great, thanks!

**Comment by leo-hstone** [comment]
![Screenshot 2022-01-30 164951](https://user-images.githubusercontent.com/62036826/151707128-e9588860-c050-4edc-be8d-e3630e5149a7.png)

behold my paint skills :D In this screenshot you can see the problem I am having. I cant see quickly which article is which. My suggestion is a preview of the title while hoveirng over the citation.

**Comment by nathanlesage** [comment]
Aaaah now I see :D Yeah sure, that should be possible I think. What I can offer is that on hover you just see the full reference as displayed in the reference manager. That also includes a lot of other information, but it would be the lazy way to implement this :D 

> Did you consider adding link functionality to citations (strg + click) already in the past?

You mean, like you Ctrl+Click on these things and the PDF opens? That doesn't work for multi-author citations, which is why the context menu, it's one click more but it should be generally okay-ish I'd say

**Comment by leo-hstone** [comment]
The more information the better! The summary sounds great. 

> You mean, like you Ctrl+Click on these things and the PDF opens? 
Exactly! Jep its definitly OK right now - I was just wondering I you did not consider it yet.
