### ISSUE TITLE
[Bug] Footnotes in project chapters are once again overwriting previous chapters' footnotes

### ISSUE THREAD

**Issue by cbop-dev** [Zettlr/Zettlr#3103]
### Description

Issue #45 seems to have reemerged, for me, on the Debian desktop (AMD) package, from at least version 2.1.0 onward (to 2.1.3). That is, in any project, when later chapters have footnotes with the same numbers (1, 2, 3...) as earlier chapters, the later footnotes overwrite the earlier chapters' notes in the output (including html and pdf). Can this be fixed again? 

### Reproducing

Create a new project with two markdown files. Add footnotes to each file, beginning numbering from 1, 2, 3...etc within each file. Export project and look at output. The notes of first file are overwritten by those of second.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.3 Cinnamon

**Comment by nathanlesage** [comment]
Would you mind trying to add the following line to the corresponding defaults file (either HTML or PDF, etc.) in the assets manager?

```yaml
file-scope: true
```

This issue should help precisely with that, see the Pandoc documentation: https://pandoc.org/MANUAL.html#option--file-scope

If that helps, I can integrate something like that in the defaults files so that other users won't notice any errors.

**Comment by cbop-dev** [comment]
Yes, setting `file-scope: true` in the defaults files fixed the problem. By default, this had been set to `false` in the two defaults files I checked, PDF and HTML. I had to change it manually for each file, but now it works. 

Is there any reason not to have this set to `true` by default for each output type upon installation? Or at least have any given project automatically change it to true when exporting (since, by their very nature, projects involve more than one file)?

In any case, many thanks!

**Comment by nathanlesage** [comment]
> Is there any reason not to have this set to true by default for each output type upon installation?

No, there is no reason. When I created the defaults files, I basically just chose some sensible defaults, but there were definitely judgmental errors, so I'm glad whenever something like this comes up so we can fix it gradually!
