### ISSUE TITLE
[Bug] Pasting image doesn't work in 2.1.3

### ISSUE THREAD

**Issue by wiwikuan** [Zettlr/Zettlr#3107]
### Description

In 2.1.3, when pasting image into a markdown file, Zettlr doesn't create the markdown syntax.

### Reproducing

1. Paste an image from clipboard into a markdown file in Zettlr.
2. A window appears, asking you where to save the image.
3. Click "Save", and Zettlr does nothing.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS 10.14

### Additional Information

When I paste an image into Zettlr, this window shows up:

![image](https://user-images.githubusercontent.com/4676714/151699426-4a1521e3-fb5e-4e0e-bbcd-f5f45a5bfe32.png)

In 2.1.2, after I click "save", Zettlr correctly generates the markdown syntax of the image; But in 2.1.3 this no longer works.

**Comment by nathanlesage** [comment]
My bad, sorry!
