### ISSUE TITLE
[Bug] Cursor in the wrong place after pasting heading text

### ISSUE THREAD

**Issue by wiwikuan** [Zettlr/Zettlr#3109]
### Description

When pasting text with heading mark `#` in front, cursor will be in the wrong place (as if they are regular small text) right after pasting. Only after you hit backspace or arrow keys the cursor will return to the correct place.

### Reproducing

1. Enter some text with heading mark `#`.
2. Copy this whole line of text.
3. Paste to the other line.
4. The cursor should be at the end of the line, but it's not. The cursor size is wrong, too. (the cursor thinks the text is small)

![Peek 2022-01-31 02-19](https://user-images.githubusercontent.com/4676714/151712337-ec6ad536-8dc8-4fa4-9921-3c41c0b65c7c.gif)

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS 10.14, pop_os 21.10

**Comment by nathanlesage** [comment]
This is fixed in the current nightly.
