### ISSUE TITLE
Zettlr 1.4.1 on Mac OS 10.11.6 has problems saving

### ISSUE THREAD

**Issue by alexandreroberts** [Zettlr/Zettlr#311]
## Description

I've just downloaded Zettlr for the first time to try it since its features sound like just what I'm looking for. But suprisingly enough I have failed even to save a file. When I click new file and edit it a bit and then select "Save", it asks me "There are unsaved changes to the current file. Do you want to omit them or save?" When I click the button "Save", it then says "Please select a directory so that the new file can be saved." It's not clear to me how I should select a director in which to save it since there is no dialogue box that pops up.

## Expected behaviour

It should open a dialogue box allowing me to choose a directory in which to save the new file.

## Platform
 - OS: MacOS
 - OS Version 10.11.6
 - Zettlr Version 1.4.1

## Additional information

As I have fiddled with pre-existing files in Zettlr, I have found related issues with saving, but I'll save that for another bug report if fixing this one doesn't fix those issues.

**Comment by nathanlesage** [comment]
Hey, yes, I need to introduce some first-start-guide, as it's not immediately obvious that you need to open a directory first.

Zettlr is meant to have one (or more folders) **permanently** open, so you have some "working" directories, in which all your Markdown files reside. Then inside it you can save, edit and do stuff to your files! If you don't have any directory opened & selected, Zettlr doesn't know where to save your file.

But if you open a directory (by using ´Cmd/Ctrl+O` or the icon on the Toolbar), select it and THEN hit save, your file will be saved — to that directory.

Zettlr works somehow different than other Markdown editors, it **does not work like single-file-window editors**. I hope that helps, and I'll see to making this more obvious to new users!

Please also have a look at our Quick Start guide: https://docs.zettlr.com/en/5-minutes/

**Comment by alexandreroberts** [comment]
Thanks for clearing that up!

**Comment by nathanlesage** [comment]
You're welcome!
