### ISSUE TITLE
[Bug] Internal Link Autocomplete pop-up does not reopen when current terms deleted

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3110]
### Description

When creating an internal link, and then deleting the word(s) you typed (so that you are just left with the `[[]]`), the autocomplete pop-up disappears. When you now start typing again, the pop-up still doesn't appear. Only when you again fully delete the word(s), the pop-up reappears. See the video below:

https://user-images.githubusercontent.com/18646029/151713600-36ff190a-ec25-46b2-998b-fef45dc29674.mp4

### Reproducing

1. Start an internal link `[[]]`
2. Type something
3. Delete everything you typed (only leave the `[[]]`)
4. Start typing again -> The pop-up does not show up anymore
5. Delete everything again
6. Type again -> Pop-up shows up

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux manjaro 5.14.21-2

### Additional Information

I don't know when this issue first appeared (I believe since 2.x, but don't quote me on that). Somehow I just got used to it, so I forgot to report.

**Comment by nathanlesage** [comment]
@kyaso Please check commit https://github.com/Zettlr/Zettlr/commit/06a1cb070098ffb7ddf1fa91893a9caa480c2e7c because I just implemented this shortly before cooking, I don't know if I forgot an edge case :D

**Comment by kyaso** [comment]
Wow, that was quick :rocket:! I'll take a look!

**Comment by nathanlesage** [comment]
Yeah ... everything I can do to procrastinate to not take a look at my diss 😂🙈

**Comment by kyaso** [comment]
> Yeah ... everything I can do to procrastinate to not take a look at my diss

I feel ya :D

The bug is indeed gone!

**Comment by nathanlesage** [comment]
Purrfect 🐱
