### ISSUE TITLE
[Bug] Global search: When search term is in file name or as a tag inside the file, the search result entry in the sidebar is incomplete

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3111]
### Description

When you do a full-text search for the term, say `honey`, files that either contain "honey" in their file name, or contain a tag "#honey" are found, but the search results don't list any lines of that file that contain "honey".

The only "result" that's shown is something in the form:

```
-1: <file-name>.md
```

### Reproducing

1. Create a file named, e.g. "honey-bee.md"
2. Write some text and make sure to add a couple of lines containing "honey"
3. Search globally for "honey" -> "honey-bee.md" should be found
4. Observe that the lines containing "honey" are missing
5. Rename the file to "bee.md" (i.e. remove "honey")
6. Search again for "honey" -> This time the lines are found

The above steps can be applied to a file containing a tag "#honey" as well (file name does not matter in this case). For example, simply add the tag "#honey" to the `bee.md` from above, and search again for "honey".

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux manjaro 5.14.21-2

### Additional Information

The issue is also present in 2.1.2, and after searching a bit in past issues, I found this comment: https://github.com/Zettlr/Zettlr/issues/874#issuecomment-744025291

Is that maybe still the reason?

**Comment by nathanlesage** [comment]
That's called ~optimization~ 😠  No jk, I have implemented a shortcut, if all search terms are indeed contained in the tags, so that the search stops early because it's already good. That was back in the times when we had the heatmap search, but now that we're actually listing search results, well …

**Comment by kyaso** [comment]
> That's called \~optimization\~

I see, it's a feature, not a bug :grin:

**Comment by kyaso** [comment]
> but now that we're actually listing search results, well …

Shall we remove the optimization then?

**Comment by nathanlesage** [comment]
Yes, yes!

**Comment by kyaso** [comment]
I'll give it a shot then, if that's ok for you :D

**Comment by nathanlesage** [comment]
Yes absolutely! Just make sure to run a few checks that the search doesn't underperform with a lot of files afterwards :)
