### ISSUE TITLE
Font in Custom CSS does not alter Bielefeld theme font

### ISSUE THREAD

**Issue by DutchPete** [Zettlr/Zettlr#312]
## Description
I am using the Bielefeld theme, but want to have a different font with it. So, according to your documentation page, this what I put in the Custom CSS file:
```
#editor {
    font-family: '<DejaVu Sans Condensed>', <sans-serif>;
}
```
But that does not change the font in Bielefeld.

## Reproducing
Add the code above to Custom CSS, and see the non-result.

## Expected behaviour
I would expect the Custom CSS file to take prevalence.

**Screenshots**

## Platform
 - OS: Linux Mint
 - OS Version 19.2
 - Zettlr Version 1.4.1
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
I strongly assume the greather-than and less-than-signs (`<` and `>`) are not part of the font's name, correct? It might help if you'd remove these. But thanks for the info, I haven't updated the class-list yet.

**Comment by DutchPete** [comment]
I deleted the angled brackets, but that does not make any difference after closing and reopening the app. Anything else I am not doing right?

**Comment by nathanlesage** [comment]
It might be that the Bielefeld-theme is overwriting the font at another place. The best way is to switch to develop mode and actually inspect the editor element, then you'll see where it stems from.

Ah, found it. You'll need to namespace it with the body-element, so this should work:

```css
body #editor {
    font-family: 'DejaVu Sans Condensed', sans-serif;
}
```

**Comment by DutchPete** [comment]
Thank you @nathanlesage, that works. You can close the issue.

**Comment by balthild** [comment]
It doesn't work for me.

<img width="1112" alt="图片" src="https://user-images.githubusercontent.com/2662758/66640540-c0089100-ec4b-11e9-9929-5b0bd6939464.png">

**Comment by nathanlesage** [comment]
In Frankfurt, the font-family is namespaced to `#editor .CodeMirror`:

![image](https://user-images.githubusercontent.com/17251683/66658762-6f406a80-ec42-11e9-8263-e598df32def7.png)

I'll keep this in mind when we refactor the design in future releases to make this homogeneous across themes.
