### ISSUE TITLE
Better naming/handling of defaults files

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#3120]
Right now, the naming convention and the names in the GUI of Zettlr are hardcoded. That is, the names for the defaults files in the sidebar of the assets manager are hard coded, as are the names these files have:

![image](https://user-images.githubusercontent.com/17251683/151756400-783dd3a6-7f60-4a41-922e-0cd6c9a9061a.png)

The problem with that is twofold:

1. We cannot give the users the ability to create more assets files as they need it
2. We have to ship with a quite large amount of defaults files to begin with
3. Although one can easily change the `writer` option of an existing file, that makes the export options semantically meaningless (i.e. one can change the writer of the Word default file to rtf, and then the app would always export to RTF, but it would still display as Word)

I don't know how we could make this dynamic, but CC @tarleb @Kangie since you have experience with Pandoc and maybe have an idea!

**Comment by Spacecortez** [comment]
What about making it possible to add, remove and rename defaults files the way we do with Snippets?

![Customizeable defaults](https://user-images.githubusercontent.com/17038430/174085493-99eaddf0-11b9-425d-b5cb-b7c25cbe5d3d.png)

**Comment by nathanlesage** [comment]
@Spacecortez See https://github.com/Zettlr/Zettlr/pull/3550 .
