### ISSUE TITLE
[Enhancement] Allow jumping to correct page in PDFs

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#3122]
### Description

I'm quite surprised no one has yet opened this issue, but since most PDF readers allow some form of "jump to page", we could implement this in the handler for opening PDFs from the citation context menu. That is: If a locator is given in the form of page number, why not attempt to also jump to the correct page number?

### Proposed Changes

First, implement page ranges in the render-citation plugin, then adapt this file: https://github.com/Zettlr/Zettlr/blob/develop/source/main/commands/open-attachment.ts

In that file, whenever we are opening an attachment using `openPath` we can provide a page number in whichever format necessary. That would be something to inquire.

### Caveats

As far as I know, there are somewhat differing standards as to how to jump to specific pages. I know that Zotero does this via scripting (which is visible when you click on links generated by Zotfile, since that will sometimes open the PDF renderer and then quickly execute some actions on the GUI of the app).

We would need to research into how we could do this as consistent as possible with different editors. Another possibility would be to implement this just within Zettlr as soon as we implement viewing PDF files. That would save us the hassle of looking up different ways of jumping to lines, since we can directly control PDFjs from within the webview.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

any

### Additional Information

I have indicated that I do not wish to implement this myself, which is not quite true. Of course I would like to implement that, but this way if someone feels they want to do the research and implement it, please come forward!

**Comment by leo-hstone** [comment]
Damn, that sounds awesome!
