### ISSUE TITLE
[Enhancement] Remember size and opening status of sidebar and file manager after a restart of Zettlr

### ISSUE THREAD

**Issue by dagdrommer** [Zettlr/Zettlr#3130]
### Description

As the title says: After I restart Zettlr it does not remember if I had the file manager or status bar opened before the last close and furthermore Zettlr does not remember how large I sized the windows during my last use of Zettlr.

### Proposed Changes

As Zettlr remembers last used documents, maybe there is a way to write opening and size status of the in-app windows in that save-file.

### Caveats

--

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Arch Linux

**Comment by kyaso** [comment]
I'd like this feature!
