### ISSUE TITLE
[Enhancement] Reverse sort order option

### ISSUE THREAD

**Issue by hajush** [Zettlr/Zettlr#3131]
### Description

Often newer entries are more relevant in the file manager, especially for dated log entries. Having the option to have a reverse sort order in the Preferences in Sort Order section as a checkbox would really help such a use case.

### Proposed Changes

This simplest fix for this would be to add a reverse sort order checkbox in the Sort order section in the preferences. When the checkbox is checked, show the elements in an inverted order.

This would be harder, but better, like in a file manager to have an up triangle/down triangle toggle at the top (maybe next to the filter) so that the order could be quickly toggled.

### Caveats

Can't see a caveat for this. Either implementation seems straight forward. But doing this with a toggle will need some user interface review or testing in beta before finalizing it.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 20.04.3 LTS

**Comment by nathanlesage** [comment]
Do you mean this setting in the directory properties?

![image](https://user-images.githubusercontent.com/17251683/152032689-4b6490d5-4325-4660-ad58-c976c9260141.png)

**Comment by hajush** [comment]
As Emily Latella said - never mind! Sorry I'm a new user - please close this one.
