### ISSUE TITLE
[Bug] Bibliographic references render weirdly before the Zotero json library file updates

### ISSUE THREAD

**Issue by wilkohardenberg** [Zettlr/Zettlr#3135]
### Description

Since I updated to 2.1.3 instead of rendering as @soandso9999 in red, before the json file updates bibliographic references bibliographic references are rendered by repeating the last couple of lines (see images).

![Screenshot 2022-02-02 at 13 09 35](https://user-images.githubusercontent.com/1612993/152151574-c2cc3541-2ed8-4211-b713-dc17ad158a70.png)
![Screenshot 2022-02-02 at 13 09 29](https://user-images.githubusercontent.com/1612993/152151575-dcd24025-451e-4822-bc8c-4b6a2c746e8f.png)
)

### Reproducing

Try inserting a new bibliographic reference for which the json has not been updated yet.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Mojave 10.14.6

**Comment by nathanlesage** [comment]
That has been reported a few days ago, and the issue is already fixed — comes with the next update!
