### ISSUE TITLE
[Bug] Spellcheck error indication conflicts with strikeout

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#3136]
### Description

![image](https://user-images.githubusercontent.com/51254/152165734-88f2e987-9bf4-49a8-882a-c4bdc26428f0.png)

Since 2.1.3, the strikeout bar is not added if a word to be "struck out" has a spelling issue. 

### Reproducing

1. create a checklist containing several items, some of which have spelling errors
2. check and uncheck each of the items
3. observe that works with spelling errors do not get the strikeout

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by efficacy** [comment]
BTW. How come Zettlr is not in its own dictionary?

**Comment by nathanlesage** [comment]
> BTW. How come Zettlr is not in its own dictionary?

Umm … I do put it there by default, did you happen to delete it at some point? Oh wait, you wrote it with a lower case `z`, right?

And with regard to this bug: I'm not sure if we can fix it since both strikethrough and the red underlining are text decorations and text can only have one decoration applied

**Comment by efficacy** [comment]
In case it helps, I have tried changing Zettlr to use a capital Z, but it still fails the spellcheck

As for the conflict, it seems that there are two possible solutions:
- I would argue that strikethrough should take precedence over spelling error indication. Semantically, a strikethrough means that the content of the text is no longer relevant or has been superseded, so spellcheck is less important
- or, you can use `text-decoration` for the strikethrough, and `border-bottom` for the error indication. These two CSS attributes play nicely with each other and can be applied to the same `span` element with no conflict.

**Comment by nathanlesage** [comment]
> and border-bottom for the error indication.

Mh, then we wouldn't have the line go through `g`s anymore. Honestly, at some point someone changed that to a dashed line, which upset me back then, so probably now is a good time as ever to fix that!
