### ISSUE TITLE
[Bug] Pressing tab key not showing any effect

### ISSUE THREAD

**Issue by therealjeybe** [Zettlr/Zettlr#3142]
### Description

Pressing the tab key inside the editor doesn't show any effect -> no tab gets inserted. This is the case no matter where the cursor is placed and no matter if text is selected or not.

### Reproducing

Press the tab key anywhere in the editor. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian 11

### Additional Information

AppImage package used.

**Comment by kyaso** [comment]
Does it work for you in 2.1.2?

I'm also running AppImage and having no problems.

**Comment by therealjeybe** [comment]
Hey, sorry for the late answer. It seems that is was a problem somewhere other than Zettlr. Now it is working perfectly fine, so I think no need to keep this open.
