### ISSUE TITLE
[Feature] Consistent change of note title

### ISSUE THREAD

**Issue by nistude** [Zettlr/Zettlr#3143]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

With named links between notes, a note's title is a bit of a special property. It would be great, if Zettlr supported a dedicated mechanism to change the title of a note in the current file and all links pointing to this file that used the old note title. The replacement operation should ignore case for matching as I sometimes like to change capitalization of the 1st character of the link title to have the other note read better.

The functionality described here is comparable to the "rename page" feature in Confluence or "rename function" refactoring in modern IDEs.

If you don't want to implement the special feature, global search & replace would be a helpful alternative.

### Example Workflow

Let's say I have a note with title "My most beloved Zettlr shortcuts".

### Example 1

When I change the title directly in my note, nothing else happens

### Example 2

1. When I activate the "change title" refactoring, a popup opens that has a field "current title" filled with the current title of the note and an empty field called "new title". The cursor waits in "new title" for input.
2. When I enter "Some Zettlr shortcuts" into "new title" and hit return, Zettlr replaces the title of the current note with "Some Zettlr shortcuts", regardless if the title was configured in yaml frontmatter or as H1 heading.
3. Zettlr goes through all my notes in all my workspaces to find links pointing to this current note. When it finds a link and the link text, according to my configuration of how links are to be set, contains an exact, case-insensitive match with the old title, it replaces the text with the new title. If there is no text match, Zettlr moves on.

### Caveats

Searching through all notes in all workspaces may be very time consuming for larger note collections. Eventually there may be a need to index note links in some kind of metadata database.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by brunoarine** [comment]
This is a feature I would love to see, and which, frankly, is holding me back from adhering to Zettlr. It would be great to have an option so that changes to a note's title would be propagated to all notes linking to it.

**Comment by Raphapere** [comment]
This issue is relevant. Please, consider to implement it.

**Comment by nathanlesage** [comment]
Implemented. Note, however, that capitalization is important. What the mechanism will do is, if you rename a file, it offers you to replace that link with the file's new name across all loaded files. I have to dig deeper to see if that may cause a problem down the line, but the base functionality is in there.
