### ISSUE TITLE
[Bug] Weird behavior when referecing something that does not exist + The tutorial is a trap. 

### ISSUE THREAD

**Issue by ElCharpi** [Zettlr/Zettlr#3146]
### Description

So, I tried the Reference tutorial. I thought [@Marx1962, chapter 23, p. 249] would give me a proper reference to 'Le Capital'. 

![image](https://user-images.githubusercontent.com/99125217/152681595-c506d216-1c5c-4ef8-b94e-360806c07441.png)

Instead, it gave me this : 

![image](https://user-images.githubusercontent.com/99125217/152681607-34200b2b-9e15-4b09-8963-9a25c0128489.png)

Which is basically the previous paragraph, almost completely, repeated. 

I tried it again somewhere else... 

![image](https://user-images.githubusercontent.com/99125217/152681645-0b5a1026-2f1b-4815-857a-6f92493a02f1.png)

Again, it repeated the paragraph : 

![image](https://user-images.githubusercontent.com/99125217/152681664-d03b470c-e058-40cb-86b0-a2947b12cf28.png)

I tried with another reference : 

![image](https://user-images.githubusercontent.com/99125217/152681684-49551d7a-8d95-48cc-ad8b-d9d37c059b1c.png)

Same problem : 

![image](https://user-images.githubusercontent.com/99125217/152681690-ab13cf19-ea66-4799-81a8-bc73bf347ee0.png)

I finally understood that this was how Zettlr behaves when you use Id a reference that does not exist. 
Also, I understood that, whereas the tutorial was encouraging me to add a reference to @Marx1962 : 

![image](https://user-images.githubusercontent.com/99125217/152681978-877944b8-b404-4325-8c2c-1478eeed2f5a.png)

The proper reference in to Marx1971.

![image](https://user-images.githubusercontent.com/99125217/152682000-8e645a20-aab3-4fe6-97d7-3ddd7362523d.png)

I do not think it is intended. If it is, it is quite misleading. 

I think it would be better if : 
- an error "reference not found" appeared instead of repeating the previous paragraph.
- the tutorial would ask us to reference Marx1971. 
- if there was another goal (like, have us learn about how to change the date for a reference of something), it should be done, amha, step-by-step.

### Reproducing

Trying to reference something with a ref that does not exist. 
Trying the Tutorial.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
The problem with the weird display on wrong citations has luckily already been fixed. Wrt to the tutorial itself, I'll have a look. It is a tad outdated either way!

**Comment by nathanlesage** [comment]
I just checked it, and I noticed that the English tutorial is fine, so someone just accidentally forgot to put the correct citation into the French tutorial.
