### ISSUE TITLE
[Bug] Zettlr 2.1.3 no longer opens Markdown relative links to file or folder 

### ISSUE THREAD

**Issue by sebzeter** [Zettlr/Zettlr#3154]
### Description

When clicking on a Markdown relative link (absolute link starting with `file:///` works) that reference a local file or folder, Zettlr 2.1.3 no longer opens the respective file or folder but instead the parent directory of the edited Markdown file. 
This used to work perfectly before v2.1.3.

### Reproducing

Open a Markdown file in Zettlr 2.1.3, then click on a Markdown link that reference a local file or folder like the following example:

Absolute `[link](file:///home/user/file/or/folder/)` works.

Relative `[link](../../../file/or/folder/)` does not work.

### Zettlr Version

Stable (most recent version)

### Specify version

v2.1.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

openSUSE Leap 15.3 x86_64

**Comment by nathanlesage** [comment]
Would you mind checking out if this also occurs in the current nightly? We're planning on releasing this soon, so if the bug is fixed in these, it'll also be fixed in the next release! https://nightly.zettlr.com

**Comment by sebzeter** [comment]
`Zettlr-2.1.3-x86_64.rpm` built on Mon Feb 7th, 2022 21:06:03 gives a JavaScript error in the main process (screenshot [attached).

![JavaScript-error](https://user-images.githubusercontent.com/99181970/152932681-982f6cdc-2a0f-4061-8179-26d265b661b6.png)

**Comment by nathanlesage** [comment]
Ouh, that's not good. Thanks for sharing the screenshot, I'll look into it asap!

**Comment by nathanlesage** [comment]
Fixed that error you were experiencing. I'm going to trigger a new nightly build, which should be ready in about an hour. Feel free to test this out again!

**Comment by sebzeter** [comment]
`Zettlr-2.1.3-x86_64.rpm` built on  Tue Feb 8th, 2022 12:01:28 fixes this issue.

Thanks Nathan!

**Comment by nathanlesage** [comment]
Perfect! Then I'm closing this issue as fixed and I'll release a new version within a few days — of course just keep using the Nightly until then, it should work fine :)
