### ISSUE TITLE
[Bug] Zettlr doesn't render HTML tags properly.

### ISSUE THREAD

**Issue by tribbloid** [Zettlr/Zettlr#3155]
### Description

When editing for doc to be published for github. Sometimes I need to convert equations to images to be rendered by a third-party MathJax engine (as github-flavoured markdown doesn't support it).

E.g.

$$
\frac{1}{2}
$$

can be converted to:

<img src="https://render.githubusercontent.com/render/math?math=%5Cfrac%7B1%7D%7B2%7D" height=100>

But it won't be displayed in Zettlr.

### Reproducing

add:

```

<img src="https://render.githubusercontent.com/render/math?math=%5Cfrac%7B1%7D%7B2%7D" height=100>
```

into any document

render it in editor mode

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3 (UUID: 71e8e655-cdb3-4a2b-b309-ad4defe2451a)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by nathanlesage** [comment]
You need to wrap that link into a valid Image tag:

`![Title](https://render.githubusercontent.com/render/math?math=%5Cfrac%7B1%7D%7B2%7D)`

That will work just fine. Both in Zettlr and on GitHub.

**Comment by tribbloid** [comment]
it worked but won't preserve the height or other formats, but the implication is much more than this:

Most variants of markdown (e.g. https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html)

claimed that they are superset of HTML. This may not applies to all variants, but zettlr should either publish its own variant, or be explicit about what kind of variant or standard it tries to comply

**Comment by nathanlesage** [comment]
There is no real standard, but the thing coming closest to Zettlr's implementation of Markdown would be Pandoc's Markdown. Also, we are quite explicit on this all over the documentation.

Also remember HTML images will work on export and elsewhere, they just won't be pre-displayed in Zettlr, since we can't add a full HTML parser on top of the Markdown parser, that would be a complete overkill.
