### ISSUE TITLE
[REQUEST] Searching globally over all/selected root directories

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#316]
If you want to search for a tag or string in more than a few root directories, it is really time consuming to do this for one after the other. For example if you have a lot of ToDo-files within a bunch of project directories (= root directories in Zettlr) and want to search for the tags '#open' or '#closed'.

Therefore it would be very helpful, if one could mark all (or a subset) of the root directories for the global searching.

**Comment by nathanlesage** [comment]
Not sure how I would achieve this. I would first try to have a look at your directory structure: Is it really necessary to have that many open directories or would it be possible to store them in one parent directory which you could then open?

**Comment by jothanne** [comment]
There IS one parent directory. But I recognized a massive 'laggy' behavior using Zettlr with this parent directory as root directory because it contains really a lot of not Zettlr related files and folders.

Here is a simplified directory structure for clarification:
<pre>
Customers
|- Customer 1
|  |- Memos (Zettlr-created files)
|  |  |- Infos
|  |  |- HowTos
|  |  |- ToDos
|  |- Docs
|  |- Projects
|     |- Project 1
|     |- Project 2
|     |- etc.
|- Customer 2
|  |- Memos (Zettlr-created files)
|  |  |- Infos
|  |  |- HowTos
|  |  |- ToDos
|  |- Docs
|  |- Projects
|     |- Project 1
|     |- Project 2
|     |- etc.
|- etc.
</pre>
And the exemplary task for this use case is to find all ToDo-files tagged with '#open'.

The only other way I can see to work around the described problem would be to have all the 'Memos'-directories extracted and stored in a separate structure this way:
<pre>
Memos
|- Customer 1
|  |- Infos
|  |- HowTos
|  |- ToDos
|- Customer 2
|  |- Infos
|  |- HowTos
|  |- ToDos
|- etc.
</pre>
But this would mean to break the 'Customer'-centric directory sturcture since now there are customer data located in different places.

**Comment by nathanlesage** [comment]
Ah, this might be solved once symlinks are enabled!

**Comment by jothanne** [comment]
OK - will this feature then be OS-independent?

**Comment by nathanlesage** [comment]
Obviously (as long as the operating system supports Symlinks, but I think all do)

**Comment by jothanne** [comment]
Thanks for the info.

**Comment by nathanlesage** [comment]
Just confirmed, Windows, macOS and Linux-based Distros all support symlinks, and node does as well.

**Comment by nathanlesage** [comment]
Closing this in favour of #541
