### ISSUE TITLE
[Bug] paste image does not work

### ISSUE THREAD

**Issue by w-markus** [Zettlr/Zettlr#3163]
### Description

pasting an image from the clipboard to a md-document does not work.

### Reproducing

- copy an image to the clipboard
- in Zettlr press CTRL-V
- "Paste image" pops up
- press "Save" (i.e. "Speichern", using DE)
- "Paste image" window disappears
- nothing else happens in the document
- the image has been saved at the given destination

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

### Additional Information

from the log:
`[R] [Main Window] TypeError: i.default.basename is not a function (index.js:2)`

**Comment by nathanlesage** [comment]
Thanks for reporting this! Would you mind checking out the most recent nightly? We're planning to release this soon, and iirc I implemented some fix regarding image pasting behavior, so this bug might already be gone! If not, I will see to fix this before releasing.

**Comment by marvin-te** [comment]
Can confirm: Issue is fixed in the newest nightly. :)

**Comment by w-markus** [comment]
Yes, works like a charm!

Thanks a lot!

**Comment by w-markus** [comment]
Dear all,

a follow up question/comment/bug(?):

if I define an *absolute* path in Settings->Editor for uploaded images, the software converts it to a relative one in md-documents. That's not what I expected, when setting up an absolute path.

I'd like to have an absolute path like
`/home/me/.soft_link_collection/Zettlr_Resources/`
i.e.  `/home/me/.soft_link_collection/Zettlr_Resources/my_image.png`
whereas in my case `Zettlr_Resources` is a *soft link* to `some folder in my file system`. Whenever I decide to change `some folder in my file system` to `some OTHER folder in my file system`, I only have to change the link in `/home/me/.soft_link_collection/Zettlr_Resources`. So far, that's the idea. ;-)

(I have just started using Zettlr, thus I am not completely sure whether folders will stay, where they are at the moment.)

However, if I put the above link (`/home/me/.soft_link_collection/Zettlr_Resources/`) into Settings->Editor->DefaultImagePath, pasting does NOT work at all, i.e. the image is not stored and no changes to the md-document.

best wishes
Markus

**Comment by w-markus** [comment]
...
putting the *soft link* in the document by hand does work: the image is found and displayed. Thus one could set up some fancy `sed` script to replace relative paths by absolute ones, but having this functionality within Zettlr would be far better. ;-)
