### ISSUE TITLE
Searching for "//" crashes Zettlr

### ISSUE THREAD

**Issue by AlvaroDeMenard** [Zettlr/Zettlr#317]
## Description
Searching for "//" crashes Zettlr.

## Reproducing
Open any document and search for "//".

## Expected behaviour
Not crash.

## Platform
Win 7, Zettlr 1.4.1

**Comment by nathanlesage** [comment]
Short correction: It only crashes the renderer, reloading will fix it. However, this is not desirable, I'm on it!

**Comment by nathanlesage** [comment]
This is the affected line:

https://github.com/Zettlr/Zettlr/blob/dae0541df97f4aa9f568a822f6c83a0dadf45869/source/common/util/make-search-regex.js#L29

Need to change that regular expression to:

```javascript
/^\/.+\/[gimy]{0,4}$/
```

**Comment by nathanlesage** [comment]
Fixed & will ship with the 1.4.2!
