### ISSUE TITLE
[Bug] [2.2.0] Saving files not working

### ISSUE THREAD

**Issue by MaPeras** [Zettlr/Zettlr#3172]
### Description

With the new version 2.2.0 saving files does not seem to work

### Reproducing

1. Open Zettlr
2. ctrl+n
3. Write something in new file
4. Trying to save, but no response by Zettlr

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr 2.2.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04.3 LTS

**Comment by MaPeras** [comment]
From Log Viewer:

[09:28:28]	Error saving file: Maximum call stack size exceeded
[09:28:28]	[R] [Main Window] Retrieved a falsy result from main, indicating an error with saving the file. (index.js:2)

**Comment by nathanlesage** [comment]
Ah, maybe I made an accident with regard to in-memory files. Right-clicking directories to create new files should work as usual!

**Comment by nathanlesage** [comment]
Just tried this, and couldn't reproduce this. Could this be an access error? Something to do with write rights…?

**Comment by MaPeras** [comment]
Weird. Worked on my other machine. I just reinstalled it (not via Ubuntu GUI Installer, but through the terminal) and now it works. Surry for the hustle!

**Comment by nathanlesage** [comment]
Phew, let's hope it was just a hiccup and not some super exotic bug!

**Comment by stormgrass** [comment]
I have the same issue! Installed via the AppImage (I wrote [a post ](https://www.reddit.com/r/Zettlr/comments/sp6n9w/zettlr_220_on_linux_cant_save_files/)in the subreddit about it as well).

**Comment by tobijakobi** [comment]
I have the same issue on the Mac. Reinstalled a couple of times via brew. Tested it on two different macs. Both Macs run Big Sur 11.6.3

System log tells me (if that is of any help): getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory

Any other info I could provide to find the bug?

**Comment by nathanlesage** [comment]
@ethanbass 

> opening it from memory does not.

This means to create a new *unsaved* file that needs to be manually saved first, right?

**Comment by ethanbass** [comment]
> @ethanbass
> 
> > opening it from memory does not.
> 
> This means to create a new _unsaved_ file that needs to be manually saved first, right?

yes, exactly. sorry if I was unclear

**Comment by nathanlesage** [comment]
Thanks for confirming!

**Comment by ChestRockwel** [comment]
Same bug on Windows 11. Intel architecture, just installed today. Can only edit the template files, any new file cannot be saved.

**Comment by iron-td** [comment]
Same issue after updating to 2.2.0. Windows 10, AMD architecture. I tried downgrading to 2.1.3 but can't save on that either.

**Comment by ethanbass** [comment]
Just so people know, I found that this issue goes away when I activate debugging mode (Preferences: Advanced: Enable debug mode), as noted in my other duplicate version of this issue. This could perhaps be a simple solution (assuming it works for other people) until the issue is resolved.

**Comment by iron-td** [comment]
> Just so people know, I found that this issue goes away when I activate debugging mode (Preferences: Advanced: Enable debug mode), as noted in my other duplicate version of this issue. This could perhaps be a simple solution (assuming it works for other people) until the issue is resolved.

Can confirm. This worked for me.

**Comment by kyaso** [comment]
> I found that this issue goes away when I activate debugging mode

I can reproduce this issue when disabling debug mode. @nathanlesage For you as well?

**Comment by nathanlesage** [comment]
@kyaso Yes! That was it! I'm so used to simply keeping debug on that I didn't check that. It was basically an endless loop, because I'm an idiot and simply forgot to add the corresponding translation string :D
