### ISSUE TITLE
[Bug] v2.2.0 won't open previous working directory

### ISSUE THREAD

**Issue by JanLeendertse** [Zettlr/Zettlr#3173]
### Description

Working directory used with v2.1.3 won't open anymore with v2.2.0.

### Reproducing

OS: Ubuntu LTS 20.04

Working directory has 1.8GB and 2.343 objects.

- Downloaded v2.2.0 and installed with `sudo dpkg -i [filename]`
- Opened Zettlr: previous working directory has disappeared
- Opened previous working directory via menu. Got error message:

![Error_Open-working-directory](https://user-images.githubusercontent.com/12598231/153393488-6ec38fee-e99e-4171-9374-26c7888e081e.png)

- Re-installed v2.1.3 with command see above
- No problem to open working directory

I checked if opening is possible when removing .ztr-directory. Result: some behaviour.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu LTS 20.04

### Additional Information

May it be that the working directory is too large?

**Comment by nathanlesage** [comment]
I see I really was successful in improving the information contained in those error messages ... not.

Would you mind having a look at the logs to see if there are more explanative errors in there on why the directory couldn't be loaded?

**Comment by JanLeendertse** [comment]
I am open for everything. Name the files or we might have a video conference session guided by you.

**Comment by nathanlesage** [comment]
Alright, this error is much more useful: Apparently Zettlr can't find the directory anymore. Could it be that Zettlr doesn't have the rights to see that folder? On macOS for example no app is allowed to access some directories such as the Documents folder until you explicitly grant that, maybe there was an update on your operating system that does something similar …?

In order to test this: Does opening a newly created directory work regularly? And, if so, if you just copy a few files over, does that work as well? This might be indicative of a rights issue, possibly.

**Comment by JanLeendertse** [comment]
I thinks it's an attribute of that folder v2.2.0 cannot cope with. I re-installed v2.1.3 because I am working productive with Zettlr. With 2.1.3 I have no problem to open the working directory at all.

And other directories can be opened in v2.2.0 like for instance the Zettlr Tutorial.

So I would be surprised to see it connected to something like access authorization.

**Comment by nathanlesage** [comment]
Well, I'm relatively sure it's a bug I somehow snuck into the app, but I'm not quite sure where. Especially weird is that I can't reproduce this on neither Windows nor macOS, which makes fixing this harder :/

**Comment by kyaso** [comment]
> Maybe it's the size or the complexity of the directory.

Could you try duplicating it, and then shrink its size by removing files, and see what happens?

**Comment by JanLeendertse** [comment]
((Sorry, I was some days absorbed.))

I reorganized my folder structure, so that Zettlr does not parse binary files anymore . Zettlr 2.1.3 starts properly. 

After installing v2.2.0, it doesn't start at all.

After installing v2.2.1, I get following error message:

![Bildschirmfoto vom 2022-02-16 11-50-08](https://user-images.githubusercontent.com/12598231/154249887-0e1dc870-dad2-4582-9e62-c2d2c6883daf.png)

With v2.2.2 I am back in the game.

So I guess this issue can be closed. Thanks for your patience.
