### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'showErrorMessage')

### ISSUE THREAD

**Issue by Pascalio** [Zettlr/Zettlr#3176]
### Description

Executing the Appimage of 2.2.0 aborts with:

```
[17370:0211/094648.236865:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
TypeError: Cannot read properties of undefined (reading 'showErrorMessage')
    at m.boot (/tmp/.mount_Zettlr6MdjSe/resources/app.asar/.webpack/main/index.js:2:1405702)
    at async t.default.boot (/tmp/.mount_Zettlr6MdjSe/resources/app.asar/.webpack/main/index.js:2:1389580)
    at async t.bootApplication (/tmp/.mount_Zettlr6MdjSe/resources/app.asar/.webpack/main/index.js:2:1393182)
```

This might be related to: https://askubuntu.com/questions/1230508/19141191410425-011526-129520errorsandbox-linux-cc374-initializesandbox
An implementation fix is proposed in the forum answer. I don't know if it applies to Zettlr...

### Reproducing

Every time. Zettlr cannot be started and it always crashes spitting this error message.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

KDE Neon 5.24

**Comment by nathanlesage** [comment]
The real error message is below the one you used:

```
TypeError: Cannot read properties of undefined (reading 'showErrorMessage')
    at m.boot (/tmp/.mount_Zettlr6MdjSe/resources/app.asar/.webpack/main/index.js:2:1405702)
    at async t.default.boot (/tmp/.mount_Zettlr6MdjSe/resources/app.asar/.webpack/main/index.js:2:1389580)
    at async t.bootApplication (/tmp/.mount_Zettlr6MdjSe/resources/app.asar/.webpack/main/index.js:2:1393182)
```

The GPU error is not necessarily relevant for Zettlr and should not cause a crash.

**Comment by McGlear** [comment]
Whatever is causing this can happen on Windows 10, too:
- v2.2.1 throws the error message "Could not start m: Cannot read properties of undefined (reading 'showErrorMessage')"
- v2.2.0 simply won't start (silently, no error message)
- v2.1.3 works as expected

**Comment by nathanlesage** [comment]
Alright, we're getting somewhere. "m" is not a really useful name but I've now adapted that one. However, I can now tell you that there is an error loading your main database! Because the citeproc provider is the only one accessing `showErrorMessage` during boot. That in itself should not be an error anymore (fixed that, too), so from the next version on you should be able to see what is going on!

**Comment by pharaoh23** [comment]
Just to confirm, the same issue ( "Could not start m: Cannot read properties of undefined (reading 'showErrorMessage')" also happens in Zettlr 2.2.1, in MacOs 11.6.3, BigSur. As my .bib database had a few errors, it might be the reason for the problem, as Nathan suggested

**Comment by nathanlesage** [comment]
> As my .bib database had a few errors, it might be the reason for the problem, as Nathan suggested

Absolutely, but that should not prevent Zettlr from starting altogether. HOWEVER, I think I fixed that particular issue. It would be awesome if you could try out today's nightly once it is uploaded (at around ~2pm CET today), and report back if it fixes this issue!

**Comment by pharaoh23** [comment]
Dear Hendrik,
Thanks for the reply.
I confess that I also have a Mac still with Catalina, and it did not throw
any problems in Zettlr 2.2.0, in spite of having the same malformed .bib
file. Is it actually MacOs specific?
As I am 6 hours ahead of CET, it means roughly 8pm for me, but I will check
the or a bit later.


Rob

**Comment by pharaoh23** [comment]
Dear Hendrik,
with the nightly release, Zettlr is now starting, and it gives the
following message as warning,: ENOENT: no such file or directory, open
'/Users/macmini2018/Dropbox/My Mac (MacMini2018’s Mac
mini)/Desktop/Bibliography (BibTeX copy).bib'[

Now Zettlr is working.

Thanks,

Rob

**Comment by Pascalio** [comment]
Same here, on Linux! Starting but reporting ENOENT.

**Comment by nathanlesage** [comment]
Alright. Is the file notably existent? Or could it be that the file is indeed missing?

**Comment by Pascalio** [comment]
Yes, the file had never existed.
($HOME/Documents/Zettlr Tutorial/references.json , on Linux)
Unsetting the string in the quotation tab of the settings did the trick.

**Comment by Pascalio** [comment]
(I'm sorry for these pressings of the close/reopen button by mistake...)

**Comment by nathanlesage** [comment]
Nah, mistakes happen! Don't worry. I'm glad the problem has been solved :)
