### ISSUE TITLE
[Bug] Internal links doesn't work on Zettlr 2.2.0

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#3177]
### Description

When I click on an internal link, Zettlr create a new markdown file with the same ID instead of open the existing file.

### Reproducing

1. Create a new note
2. Type `[[` and it's autocompleted with `]]` (as usual)
3. Select a markdown file from the drop-down list
4. The internal link is created, something like `[[AAAAMMDDHHMMSS]] Name` (as usual)
5. When I use `Ctrl + click` on that link, doesn't open the file, but create a new markdown file called AAAAMMDDHHMMSS.md (beside the existing AAAAMMDDHHMMSS-Name.md file)

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ubuntu 20.04.3 LTS

**Comment by hiperterminal** [comment]
Hi.
This is working now on Zettlr 2.2.1, even without ticking that checkbox in the image. I can go back and check to know what was happening, but now there is no problem.
Many thanks!

**Comment by nathanlesage** [comment]
Great! Then apparently I made a mistake and it's now fixed, these bugs are the best bugs! ;)
