### ISSUE TITLE
Zettlr 1.4.1 speed

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#318]
I think that after upgrading to electron 6 there is some downgrade in performance terms. 

Although Zettlr starts immediately it takes a lot of time to **read** the folders (the same as before). Moving files takes a little more time between refreshing the folders. And sometimes, after long periods of writing it appears a delay between typing and the actual display. 

And also the problem of rendering files with a lot of links in them appeared again, although not in the same severe category as before. 

Overall I feel that it is a bit *harder* to work now. Maybe is just a behavior on Linux?

**Comment by nathanlesage** [comment]
Mh, could very well be my insufficient Vue.js-skills. There's for sure some overhead performance losses due to bad design, currently (because of past experiences I tend to update the renderer once more instead of one time too less).

Concerning the reading-time, it's in part due to the fact that it at the same time reads the file AND starts up the window, which may have a read-surge on the disk. I'm not quite sure, but if you'd like you could have a look into the dev tools' performance analyser and see if there are bottlenecks in the renderer. If there are not, we know they are in the main process!

**Comment by samarulmeu** [comment]
Here are some screenshots. I'm not so sure if it helps. 

![1](https://user-images.githubusercontent.com/39216570/64596016-ce992980-d3bb-11e9-9a28-c4336e451a94.png)
![2](https://user-images.githubusercontent.com/39216570/64596024-d1941a00-d3bb-11e9-9d71-41c569a18695.png)
![3](https://user-images.githubusercontent.com/39216570/64596029-d2c54700-d3bb-11e9-8b57-7a452936f99a.png)

**Comment by samarulmeu** [comment]
In one I see the spellchecker, but I have none active.

**Comment by nathanlesage** [comment]
Yes, this is the right direction. Just for clarification: What we would be interested in are function calls (e.g.: scripts) that take a long time. Have a look at what I've circled here:

The upmost circle is around something where we can see that some script took extraordinarily long (this horizontal bar is the timeline from beginning to ending of recording). Yellow are the scripts. The other stuff we can't for the most part control.

So you can drag in this timeline to only zoom in on one of these "hills".

The second thing I've circled (with the arrow down) is the function _stack_. This is vertical, with the first function that has been called on top. And below it, every other function it has called, and so on. So we'll be interested in looking at the upmost function and then go down until we can see a pattern where a certain function has taken a long time. Then we have the name of a function that we need to look into.

At the bottom is a sometimes more concise display of this stack. If you expand it more and more you can see where a function has taken a lot to compute. So we would want to expand this hierarchy and look at the stack to see where the potential bottleneck resides.

![grafik](https://user-images.githubusercontent.com/17251683/64607233-63098900-d3c8-11e9-8972-70ff3a34a4e8.png)

**Comment by samarulmeu** [comment]
Some new ones. Hope they are of help. 

![a](https://user-images.githubusercontent.com/39216570/64612380-54c56800-d3dc-11e9-88ab-e65c006b5d5b.jpg)
![b](https://user-images.githubusercontent.com/39216570/64612376-5131e100-d3dc-11e9-9295-254a503f31e2.jpg)
![c](https://user-images.githubusercontent.com/39216570/64612409-6444b100-d3dc-11e9-8311-11aa2d5ed1db.jpg)
![d](https://user-images.githubusercontent.com/39216570/64612415-6870ce80-d3dc-11e9-90e5-381e8f899368.jpg)

**Comment by nathanlesage** [comment]
Looks as if file loading takes some time, but in the CodeMirror itself. I'm wondering, how big is that file approximately?

**Comment by samarulmeu** [comment]
Maybe I should have explained a little. I was opening files from the sidebar and navigating through them. They are small files (1-2k words), but some of them have links in them (maximum 20 links).

And this navigation between files is considerably slower than in the last beta. Even using `Ctrl+2` or 3 to navigate takes more time.

And also the typing, sometimes it just lags and I have yo slow down.

And the folder structure is the same.

**Comment by nathanlesage** [comment]
So it seems to be parsing the links, \*again\*. This module begins to annoy me =D

Could you please start a performance recording, than immediately open such a slow file, and, once it has loaded, stop the recording? I think one of the functions will then reveal itself as the slowpoke!

**Comment by samarulmeu** [comment]
New screenshots. Same file, first one with all the plugins enabled, the second one with render images and render links plugins disabled. In both cases, spellcheck is disabled.

![a](https://user-images.githubusercontent.com/39216570/64681585-a4fa0400-d488-11e9-910c-3ccb78cb229f.jpg)
![b](https://user-images.githubusercontent.com/39216570/64681719-e7bbdc00-d488-11e9-9297-b9ed6238431a.jpg)

As a side note (I didn't think it was necessary for a new issue) will it be possible that Zettlr at startup search for *ghost* directories, the ones that are not found? If I forget to mount an external drive then I have to manually tell Zettlr to search for them. At startup will be nice.

**Comment by nathanlesage** [comment]
Hmm … it has some appeal of coffee grounds reading, I can only see that something is really causing a huge CPU surge, but I'm still not sure...

The spellchecker-stuff btw is negligible. The mode will \*always\* perform spellchecking (easier to implement), but in case everything is disabled, the main process will just return "correct" for each and everything the renderer sends to it immediately.

> If I forget to mount an external drive then I have to manually tell Zettlr to search for them. At startup will be nice.

It's already doing this on startup. Each opened directory will remain in the config file, and on each startup Zettlr will check the existence, and as soon as a directory is *not* found, Zettlr will create such a directory placeholder. As long as the folder is found, Zettlr will at startup simply load it normally.

**Comment by samarulmeu** [comment]
> It's already doing this on startup. Each opened directory will remain in the config file, and on each startup Zettlr will check the existence, and as soon as a directory is _not_ found, Zettlr will create such a directory placeholder. As long as the folder is found, Zettlr will at startup simply load it normally.

My mistake! I was just not waiting long enough. Sorry for the misleading. 

About the speed: you also don't experience any lag when you navigate through files using `Ctrl+number?`

**Comment by nathanlesage** [comment]
Nope, not really :/

There's some startup lag if I open my huge Zettelkasten folder (10.000+ files), but apart of that during runtime it's rather smooth …

**Comment by jimvine** [comment]
I am also having slow performance in version 1.4.2 on Windows 10. There is a very noticeable lag on some operations. For example:

* Scrolling. It takes about 2 seconds to scroll when I'm using my mousewheel. And sometimes pauses for around 1 second when scrolling with Page Up / Page Down. But seems to be near-instant if I scroll using the scroll bar.

* Clicking the cursor to move the caret - maybe about 1 second.

I only have about 30 files. Most of them are pretty small. There are a few that have up to about 2500 words.

I am happy to post performance screenshots or anything else that might help debug this, but would need a pointer as to how to do that.

**Comment by nathanlesage** [comment]
The scroll-issue seems to be related to something else (it's definitely not the size of the files, as these are detached from the list), because JavaScript and the DOM rendering processes tend to suffer in performance at one point because of some bottleneck at a whole different location in the frontend. I don't know why but I'm certain there's something else interfering with the scrolling. Sounds as if there's a slow event handler attached to that, but I'm not sure.

Concerning the caret clicking: Same story. I've had instances very seldomly where this operation would take a long time for me as well.

What could probably be interfering (especially for rendering) is another Electron app running. Yes, you've heard correctly: For some reason, the Blink engines of the Chrome browser and multiple electron apps are in some way intermingled and if one application is slow, it actually slows down the other ones. I have no idea how this could happen, but it does. I experienced this with Stack. Once I closed it, Zettlr ran perfectly again.

For a guide on how to measure performance in Chrome, [have a look at these instructions](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance).

**Comment by nathanlesage** [comment]
Ah, so maybe Windows features similar behaviour than Electron 6 on macOS, because since a short amount of time I experience Zettlr simply not opening successfully after booting my MacBook. I have no idea what the Electron team did with 6.0, but hopefully they'll remedify these issues quickly …

**Comment by nathanlesage** [comment]
I'm closing this issue as we're now at 1.4.3 — additionally, I think, Electron 6 has still a lot of problems. Let us head forward to 1.5, and if in 1.5 these same issues still persist, please feel free to open up a new issue! :)
