### ISSUE TITLE
[Bug] Codeblocks with specified language and other attributes are rendered wrong

### ISSUE THREAD

**Issue by N0rbert** [Zettlr/Zettlr#3183]
### Description

Scientists may want to put code fragments to Zettlr notes using the syntax shown below. 
Currently Zettlr 2.2.1 shows the following erroneous output in Print preview:

![print-preview](https://user-images.githubusercontent.com/309456/153710625-7120b86c-7be9-4b44-9086-968c60e1c1bc.png)

### Reproducing

First code block is below

    ```{example, code-blink}
    : example LED blinking program
    ```
    ```{sh, echo=FALSE, comment=""}
    cat 'code/blink/blink.ino'
    ```
Second code block is below

    ```{example, scilab-demo}
    : example Scilab program
    ```
    ```
    clc;
    ```

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu MATE 18.04.3 LTS

### Additional Information

You can test above code rendering using [babelmark2](https://johnmacfarlane.net/babelmark2/?text=First+code+block+is+below%0A%0A%60%60%60%7Bexample%2C+code-blink%7D%0A%3A+example+LED+blinking+program%0A%60%60%60%0A%60%60%60%7Bsh%2C+echo%3DFALSE%2C+comment%3D%22%22%7D%0Acat+%27code%2Fblink%2Fblink.ino%27%0A%60%60%60%0A%0ASecond+code+block+is+below%0A%0A%60%60%60%7Bexample%2C+scilab-demo%7D%0A%3A+example+Scilab+program%0A%60%60%60%0A%60%60%60%0Aclc%3B%0A%60%60%60).

Other Markdown text editors like RStudio, Retext, Typora, MarkText renders above fragments normally.

**Comment by nathanlesage** [comment]
Since this rendering is done by Pandoc, not by Zettlr, maybe it doesn't understand the syntax you use?

**Comment by N0rbert** [comment]
Thanks, actually you are right. I forget that two `{example...}` is pre-processed by Knitr first.
