### ISSUE TITLE
Some untranslatable strings

### ISSUE THREAD

**Issue by Carmina16** [Zettlr/Zettlr#3185]
What has been found so far:

https://github.com/Zettlr/Zettlr/blob/7b10c6e897307ddabdf76c16d9bdb9fff58bac58/source/common/vue/form/elements/List.vue#L80

https://github.com/Zettlr/Zettlr/blob/4ef520cc3cca913999acf558c5d62eea0422a0c6/source/win-main/PopoverPomodoro.vue#L39

https://github.com/Zettlr/Zettlr/blob/4ef520cc3cca913999acf558c5d62eea0422a0c6/source/win-main/PopoverPomodoro.vue#L50

https://github.com/Zettlr/Zettlr/blob/141b612a58fc0c26991331525ba117005f5ffeaa/source/win-main/PopoverTags.vue#L77

https://github.com/Zettlr/Zettlr/blob/141b612a58fc0c26991331525ba117005f5ffeaa/source/win-preferences/schema/zettelkasten.ts#L44

https://github.com/Zettlr/Zettlr/blob/141b612a58fc0c26991331525ba117005f5ffeaa/source/win-preferences/schema/zettelkasten.ts#L54

**Comment by nathanlesage** [comment]
Ouh, that's a very good initiative! It happens easy to just forget to replace the hard coded English version with a translatable string!
