### ISSUE TITLE
[Enhancement] Copy FileList-shortcuts to combined mode tree view

### ISSUE THREAD

**Issue by DutchPete** [Zettlr/Zettlr#319]
## Description
On the [Shortcuts](https://docs.zettlr.com/en/reference/shortcuts/) page it says <kbd>Arrow Up</kbd> will open the previous file, in the list I assume. However, I am in the *Combined* Side Bar mode and the up or down arrow just moves the list up or down.

## Reproducing
Set the Side Bar mode to combined and use the up or down arrow.

## Expected behaviour
As described on the Shortcuts page.

**Screenshots**

## Platform
 - OS: Linux Mint
 - OS Version 19.2
 - Zettlr Version 1.4.1
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Ah yes, this works only in the file list ... currently. I'll keep it in mind!

**Comment by DutchPete** [comment]
@nathanlesage OK Hendrik, thank you.
