### ISSUE TITLE
[Bug] v. 2.2.0 and 2.2.1: still strange behaviours

### ISSUE THREAD

**Issue by hildebrand-institute** [Zettlr/Zettlr#3197]
### Description

1. With v. 2.2.1 and using the AppImage file the compilation to obtain LaTeX pdf succeeds for a project (case 1) but not for another (case 2). Except for the presence in the second case of a bibliography, I cannot say what could be a relevant difference in the structure of the two project (but even excluding the bibliography, the compilation does not seem to occur)
2. With v. 2.2.0 and using the AppImage file the compilation at a first attempt worked in both cases, but than only in the first case, like with version 2.2.1
3. When using v. 2.2.1 after a while and only in some moments I experienced a relevant slowing down of the whole OS (Garuda)

### Reproducing

Compilation of LaTeX pdf using LaTeX model

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.0 and 2.2.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Garuda (last)

### Additional Information

Before giving up using Zettlr's AppImage files (which are less intrusive for the OS) and trying to install Zettlr via "yay" (one of the package managers for Arch based OSs), I'd like to understand what is going on.

**Comment by nathanlesage** [comment]
Does this still happen in 2.2.4? If so, would you mind sharing more information, such as error messages, etc.? As it stands now I cannot really help you

**Comment by nathanlesage** [comment]
Due to lack of information, and since the next Zettlr version is around the corner, I consider this issue fixed.
