### ISSUE TITLE
[Bug] Emphasis Rendering breaks Underscores in Inline Code

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3200]
### Description

Assume we have the following code: `foo_bar_`. With the new emphasis rendering it will be rendered as follows:

![grafik](https://user-images.githubusercontent.com/18646029/153944941-cb3af5fd-a2d3-4840-bf64-b6fc1f9d8e07.png)

### Reproducing

1. Enable emphasis rendering in preferences
2. Write some inline code that contains two underscores, e.g.: `foo_bar_`
3. Click somewhere else so the rendering gets applied

-> The code part between the underscores is rendered italic

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux manjaro 5.14.21-2

**Comment by kyaso** [comment]
I also found that this happens to underscores which are inside links:

https://user-images.githubusercontent.com/18646029/153946806-e3f3966f-dd11-4c13-b2cb-4feffc60ce24.mp4

Notice how the link is not rendered when the emphasis is active; only when you click the italic part (so the "edit" mode is entered), and you _then_ click outside, the link is finally rendered.

**Comment by nathanlesage** [comment]
Yeah, the new emphasis rendering has quite a lot of edge cases where it's difficult to decide what the plugin should do. Maybe a good idea could be to first collect a few of these cases and decide what should happen in each of these instances and then do one clean up PR to fix these. What do you think?

**Comment by kyaso** [comment]
> Maybe a good idea could be to first collect a few of these cases and decide what should happen in each of these instances and then do one clean up PR to fix these. What do you think?

Sounds like a plan!

**Comment by Redsandro** [comment]
> \[Let's] collect a few of these cases and decide what should happen

There are two problems here. 

**Problem one, the easy part.** The emphasis renderer is breaking the markdown convention of _requiring a space_ before and after the marked phrase. For example, the middle part should not be in italics:

> test_italics_test

But in Zettlr, it is:

> ![image](https://user-images.githubusercontent.com/1702193/154372309-65724d86-a5fa-4f20-8761-c72941b8727c.png)

Fixing this would fix some but not all problems. At least the reported problems, so arguably the most prevalent one. I will create a PR for this.

**Problem two.** Even when there are spaces, there should not be any (further) rendering of markdown on text in these cases:

1. `` `inline code` ``
2. `[round brackets of link](here)`
3. ` ```code blocs`

I haven't seen any problems inside code blocks though, so that leaves the two cases.

---

Quoting part of #3223 to keep it combined:

> The **option to hide markup annotations** https://github.com/Zettlr/Zettlr/issues/2377 incorrectly renders inside an URL notation.
> 
> Here's a recording of the issue:
> 
> ![zettlr url italics problem](https://user-images.githubusercontent.com/1702193/154326862-360bf36a-b994-4e2d-998b-fa52ec1c07e2.gif)

**Comment by nathanlesage** [comment]
At least specific thing has been fixed now. There are a few issues, but looking at the amount of open bugs I want to close those where at least the specific request has been fixed, even though the emphasis rendering needs more love to be sure!

**Comment by kyaso** [comment]
Alright!
