### ISSUE TITLE
[Enhancement] Hungarian names in bibliography

### ISSUE THREAD

**Issue by hegedusbela** [Zettlr/Zettlr#3203]
### Description

I apologise in advance for being unprofessional.
I have my bibliography in Zotero, I save to Better JSon automatically, from there I paste the items into Zettlr. I write mostly in Hungarian, German and English. In Zotero I always specify that the item is in "hu", "de" or "en" etc. The Hungarian naming order is different from other languages, we always use the family name first. I have noticed that the Zettlr bibliography displayer always displays the names correctly. If it is a Hungarian work, it does not put a comma after the surname. And when bibliographic items are pasted directly from Zotero into OpenOffice (usually in Chicago style), the names are always in the correct order. However, when I export the markdown file (with pandoc), the naming order is no longer correct. I can't figure out the reason for this, but it would be very important if there was a solution.

### Proposed Changes

Actually, I would be most happy if the markdown export showed exactly the same result as the direct paste from Zotero into OpenOffice.

### Caveats

No caveats. :-)

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Linux KDE Neon

**Comment by nathanlesage** [comment]
Pandoc is by default using a different citation style as Zettlr. I believe Zettlr uses Chicago Manual of Style, but I could be wrong. In any case, I think that this might be the cause!

**Comment by hegedusbela** [comment]
Thank you for your reply.

Unfortunately I was not clear. I use the Chicago author-date style in all cases, as does the Zettlr display. When exporting from Zettlr Markdown to odt, the language is set to hu-HU.

1. Item from Zotero to OpenOffice directly.

[zotero_odt_pdf.pdf](https://github.com/Zettlr/Zettlr/files/8067816/zotero_odt_pdf.pdf)

It can be seen that if the language of the referenced source document is Hungarian, there is no comma after the surname at the beginning, but if it is "lat", "de" and "it", then yes. The order of the names of the contributors is also correct.

2. Zettlr bibliography viewer.

![inZettlr](https://user-images.githubusercontent.com/36314734/154036107-194ab707-8988-4249-910b-f8698cfa1218.png)

Same as before.

3. Exported markdown file from Zettlr to odt.

[zotero_md_odt.pdf](https://github.com/Zettlr/Zettlr/files/8067834/zotero_md_odt.pdf)

In all cases, it displays the names as if they belong to a non-Hungarian text.

I'm thinking that there might be some difference between the way pandoc citeproc and citeproc.js work.
