### ISSUE TITLE
2.2.0and 2.2.1for mac cannot use!

### ISSUE THREAD

**Issue by zhangzhaoyue919** [Zettlr/Zettlr#3204]
### Description

2.1.3 is can use 
but but but, 2.2.0 and 2.2.1 for mac intel cannot use! hope modify!

<img width="1193" alt="报错01" src="https://user-images.githubusercontent.com/63541289/153984471-0b297678-5bb3-44ef-ae75-a288ecbc67d7.png">
<img width="552" alt="报错" src="https://user-images.githubusercontent.com/63541289/153984534-9c7e2ad0-656d-4ceb-bd53-bdb98175e7ff.png">

### Reproducing

<img width="552" alt="报错" src="https://user-images.githubusercontent.com/63541289/153984729-ac947765-390c-4f59-afa6-8e149de45f60.png">

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

2.2.0,2.2.1 mac intel cannot use 

### Additional Information

2.2.0 and 2.2.1 mac intel cannot use! but 2.1.3can use 
<img width="1193" alt="报错01" src="https://user-images.githubusercontent.com/63541289/153984679-8176f69e-314b-4061-8fac-d19141a33cbe.png">

**Comment by nathanlesage** [comment]
Would you mind trying out today's nightly? It should have fixed that issue!

**Comment by zhangzhaoyue919** [comment]
Thanks I have used ,because my MAC update later ,could use!Thanks!

**Comment by zhangzhaoyue919** [comment]
No problem! my mac have updated later, this soft version could update!

**Comment by nathanlesage** [comment]
So with the nightly it's working? Perfect, then I'm going to close this issue, a patch will be published shortly.
