### ISSUE TITLE
[Bug] Table editor does not recognise well-formatted markdown table

### ISSUE THREAD

**Issue by scokobro** [Zettlr/Zettlr#3208]
### Description

It seems that the following table is not recognised as such by the table editor:

```
| Var | Jp | UK |
|:----|---:|---:|
| *n* |  1 |  2 |
| Av  |  1 |  8 |
```

The problem seems to be the first character (ie the asterisk) in the top row of content. Deleting the asterisk solves the problem.

### Reproducing

Create a new markdown file, paste in the above table.

### Zettlr Version

Stable (most recent version)

### Specify version

Version 2.2.1 (2.2.1)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

12.0.1

**Comment by nathanlesage** [comment]
I just added your table to the unit tests and they pass with flying colors, so the problem is not the table parser but the detection of the tables in the corresponding CodeMirror plugin.

**Comment by scokobro** [comment]
Thanks. 
2.2.3 release seems to have fixed this issue.

**Comment by Baytars** [comment]
In 2.2.4, the issue seems to reappear.
Platform: Manjaro Linux
