### ISSUE TITLE
[Feature] Share-as Email, with at least an MD and PDF option

### ISSUE THREAD

**Issue by sten0** [Zettlr/Zettlr#3210]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Hello!

At least [edit: two] users of Zettlr I know, plus myself, miss LibreOffice's:
  File->Send->Email as (Native format, odf in LOs case, md in Zettlr's)
and
  File->Send->Email as PDF

The former is often used for collaboration, and the latter is most often used for submissions (eg: papers, assignments) or sharing documents with colleagues, friends, family, etc.  I'm not sure how LibreOffice does it in a reliable cross-platform way, but it appears to be totally viable!  

Beyond the three Zettlr users I've mentioned, I know a number of people who collaborate on documents by mailing them back and forth, by using Dropbox, iCloud, or Google Drive, or by using cloud-hosted software.  Yeah, everyone who doesn't just use git ;-)

I've found that "non-technical" users who struggle to find a file to manually attach to a manually composed email absolutely *adore* Zettlr!  In particular, I think you've finally solved the organisational problems that plague people who work on multiple large projects.  Zettlr impresses me more than any Desktop full-text search since the defunct Google Desktop.  I'm impressed, and I say this as a die-hard Emacs fan who hasn't been impressed with anything else.  Other than missing a share-via-email function, I haven't been able to find anything wrong with Zettlr.  Thank you :-)

### Example Workflow

It could be a quick-access button that opens a menu, if more "Share To:" transports will be added, or desired.  GNOME behaves this way, with an icon similar to this one [edit: in the top right-hand corner of the window, underneath the title bar]:
  https://en.wikipedia.org/wiki/Share_icon#/media/File:Sharethis.svg

I think macOS might also behave this way.  I'm not sure what the current Windows convention is, post MS Office "Ribbons", but LibreOffice uses the traditional pre-ribbon menu.  Finally, a keyboard shortcut is an option, but to be honest, I don't think advanced keyboard shortcut users are the target audience of this feature.

### Caveats

The only caveat that I can think of is the case where a default mail client has not been registered, but this should be less of an issue with the dominance of Chrome and Gmail, which offer to register Gmail-in-Chrome as the default MUA.  AFAIK Apple Mail is part of a default install (with online account registration on first login?  iCloud stuff?).  Finally, Evolution or Geary tend to be part of the default installation on (beginner-friendly) distributions that use GNOME (with online Account registration on first login).  My major blindspot is I'm not sure what the current situation is on Windows...and then there are the users with webmail providers that do not (or cannot) register themselves as a MUA.  In cases like these, check for the provider, and if there is none then maybe display a popup dialogue, optionally with a link to online documentation?  I'd be happy to write a few words there, if necessary!

The only other thing I can think of is how adding too many buttons, options, or menus can be distracting/overwhelming.  If the proposed functionality may cause this, then maybe it could be disabled with a toggle in Preferences?

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
I certainly see the use-case of such a feature in the context of Zettlr to aid academics in their day-to-day work. One thing we might want to sort out, though, is how to implement this cleverly.

As it stands now, Zettlr features an export menu that is also marketed somewhat as a "share" menu. Additionally, sometime this year we'll add the ability to create custom exporters. And now these "share as" items you propose basically add a second step to the exporter. The question is:

* Should we add it to the regular exporter? (Could be confusing, but would add the option to add many more share possibilities, such as direct upload somewhere, etc.)
* Should we create an explicit share menu that semantically represents "Export with an additional step afterwards"?
* Or should we treat this as a use-case of an "arbitrary command" that is simply shipped by default (see issue #1842)?

**Comment by sten0** [comment]
Hendrik Erz ***@***.***> writes:

> I certainly see the use-case of such a feature in the context of Zettlr to aid academics in their day-to-day work. One thing we might want to sort out, though, is how to implement this cleverly.
>

Thank you!  Agreed :-)

> As it stands now, Zettlr features an export menu that is also marketed
> somewhat as a "share" menu.

Ah, yes, in at least the Dropbox case, writing the exported file to a
path under $HOME/Dropbox would share it; this could be achieved with a
configurable "Export target Directory" (Global?  Per-file?
Per-project?).  When using the desktop-native file picker, it is also
possible to write file data into the desktop's VFS stuff (iCloud network
target on macOS, GDrive or SFTP on GNOME, MS Cloud Drive on Windows,
probably WebDAV on all of them, etc), which would then use the
OS/Desktop method to write to the target.  At this very moment I'm
unable to confirm whether File->Open on GNOME allows Zettlr to
open/import files from GDrive, since I normally use KDE Plasma, where
the GNOME file picker can't see KDE Plasma network targets.

I agree, the current "Share the current file as…" button (also triggered
by Ctrl/Cmd+E and File->Export) is really more "export" than "share".

> Additionally, sometime this year we'll add the ability to create
> custom exporters.  And now these "share as" items you propose
> basically add a second step to the exporter.

Yes, from an implementation perspective, I agree, but not from a UI
perspective.  More on this below.

> The question is:
>
> * Should we add it to the regular exporter? (Could be confusing, but
> would add the option to add many more share possibilities, such as
> direct upload somewhere, etc.)

From a user perspective, it looks to me like current current HIG
maintain that Save, Export, and Share are distinct actions/verbs, and
that this distinction may be in the process of being deepened.  For
example, note the prominent "Share" button in the upper right of GNOME
native applications:

  https://wiki.gnome.org/Design/OS/Sharing

The Share button then opens a menu of targets.  More on this in the next
section.

> * Should we create an explicit share menu that semantically represents "Export with an additional step afterwards"?

Yes, from an implementation perspective, I agree these are the desired
semantics.  In addition to the LibreOffice example previously given, see
this Apple HIG example (similar to LibreOffice) for user experience
semantics:

  https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/

  File -> Share -> Sub-menu of Share Targets

In both the GNOME case, and the macOS case, the semantics appear to be:

  File(eg: currently opened/focused file) -> Action/Verb
       -> Target/Object (or sub-menu of targets/Objects)

In this model, Action/Verb can be (Save, Backup?, Save-as?, Export,
Print, Share, Rename, Delete, etc.)

P.S. I mean "object" in the linguistic/grammar sense rather than in the
OOP sense.

> * Or should we treat this as a use-case of an "arbitrary command" that is simply shipped by default (see issue #1842)?
>

I just read the issue, and as I understand it, from an implementation
perspective this "arbitrary command" issue looks like this:

  Zettlr UI -> Export -> (Pandoc || "arbitrary command" )
    -> (when Pandoc (Zettlr open file and write post-pandoc data))

The talk about custom scripts also makes me wonder if users will want to
write scripts that do various types of transforms/munging operations on
the currently focused file.  If that's the case, then I'm not sure where
it would fit cleanly into the UI.  Maybe

  File -> Custom Actions (if they exist) -> (sub-menu of custom action
                                             names)?

For example, I wonder if the scope of #1842 includes not only custom
export, not only transforms/munging of the currently focused file, but
also ability to scrape data from Jupiter Notebooks (or generate
references to specific points in them), query a remote system, or query
a database?  I guess the question for #1842 is if

1. What if the script steals and writes to the currently focused file in
Zettlr? (does this trigger a rescan of the file?)
2. Should it be marked "for custom export only…here be dragons if you
steal and write to the file"?
3. Will callbacks be supported?
3.1 Would it be useful if these scripts could return file paths?
3.2 Should Zettlr associate these paths with a file or project?
    Yes, this could be clutter, but it seems like it may be part of a
    "project management/organisation" role.
3.3 And not index them?

Sorry if this is a bit long, it's my best effort at a minimally complete
response to the issues you've raised!  My perspective is that the share
action is distinct, more rigid, and doesn't require as much thought
about how to mitigate potential pitfalls.

**Comment by sten0** [comment]
Gentle ping to sate the the stale bot

**Comment by sten0** [comment]
Any new thoughts on this issue?  The users I support have been asking about it more frequently.  To keep things simple for now, maybe just implement a button (someplace obvious and self-evident) that launches xdg-email with the current document as an attachment (unconverted markdown)?  I'm sure there's a library for platform abstracting mailto link handling ;)  Then once that functionality is proven it can be incrementally enhanced.

**Comment by sten0** [comment]
Gentle ping.  Users that I support are becoming increasingly frustrated that Zettlr still doesn't have this functionality, and they're starting to talk about going back to LibreOffice.

**Comment by nathanlesage** [comment]
Wait for 3.0.0, there are custom commands now that will allow you to launch any arbitrary app
