### ISSUE TITLE
PDF note taking

### ISSUE THREAD

**Issue by AtomicNess123** [Zettlr/Zettlr#3212]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [ ] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

It would be great to implement PDF note taking with referencing like other packages do (eg., logseq). Would like to hear comments about this possibilty.

### Example Workflow

Here see an example: https://youtu.be/vIDyXyEj_FI?t=462

### Caveats

NONE!

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [ ] Windows
- [X] macOS
- [ ] Linux

**Comment by AtomicNess123** [comment]
This is a relevant features desired by many users: PDF annotation!

**Comment by nathanlesage** [comment]
@AtomicNess123 I recently actually looked up the options, but none of them are viable within my tight time limits … feel free to propose something yourself!

**Comment by nathanlesage** [comment]
Then I'm afraid we'll have to wait for this feature ;)
