### ISSUE TITLE
[Bug] magic quotes

### ISSUE THREAD

**Issue by framatophe** [Zettlr/Zettlr#3213]
### Description

Although activate "Magic quote", it does'nt work when typing default quotes on my keyboard (num. 3 on french Azerty keyboard).

### Reproducing

Zettlr 2.2.1
Auto-correct : activate (french)
Magic quote choice is : « ... » (but the same problem with other choices)

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04.3 LTS

### Additional Information

thanks !

**Comment by nathanlesage** [comment]
I just tried it out, at least using the regular quote character `"`, I cannot reproduce this. Does the French keyboard already map to `«` and `»` or does that quote character yield `"` in normal text fields?

**Comment by framatophe** [comment]
The character `"` get a `"` in normal text. I just tried the same thing with another PC with Windows 10 and another keayboard : the problem remains the same. The only difference is that, on my Ubuntu PC, I'm able to write `«` and `»` with `Alr Gr + w/x`.
Note that with LibreOffice, the equivalent magic quotes works perfectly.

**Comment by nathanlesage** [comment]
Just for excluding any stupid issues I may have made, would you mind changing the MagicQuotes to English ones (the first option below disable) and try to see if you can write english text normally?

**Comment by framatophe** [comment]
Please have a look on the following videos :)
Wether on Windows or Ubuntu, Zettlr has the same behavior.

English quotes : https://asso.framasoft.org/drop/r/6Li03JCi2V#T7dOcuc4gpC1iVcn0rMe8C2r9y0o536zRGGTYjVdgsk=

French quotes  : https://asso.framasoft.org/drop/r/SFR2ukoAXE#WB43PLl94PUnhXmIX07otR+W6G8N3zrm50b+fveC15A=

**Comment by nathanlesage** [comment]
The problem was that you only enabled one type of magic quotes. I accidentally checked that BOTH needed to be set for the functionality to be activated. Fixed that now.
