### ISSUE TITLE
[Enhancement] render footnote call

### ISSUE THREAD

**Issue by framatophe** [Zettlr/Zettlr#3215]
### Description

Footnote marks are currently redered with bold + color. It would be useful indentifying the footnote calls in the text itself, with the same color + bold. Especially when typing long texts. 

### Proposed Changes

It can be a regex, something like : [^(.+?)]

### Caveats

no

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Operating System Version

Ubuntu 20.04.3 LTS

**Comment by kyaso** [comment]
You can achieve this through a small hack via the _custom.css_:

```
.cm-link {
    color: var(--c-primary);
    font-weight: bold;
}
```
Note that this will also change the color and style of the square brackets part of regular Markdown links (`[]()`).

**Comment by framatophe** [comment]
Nice ! this solution is not so bad. Thanks!
