### ISSUE TITLE
[Bug] Zettlr does not start: error starting f - could not start f:unexpected end of JSON input

### ISSUE THREAD

**Issue by zteli** [Zettlr/Zettlr#3218]
### Description

When starting Zettlr the following error is displayed:

error starting f - could not start f:unexpected end of JSON input

### Reproducing

everytime when starting Zettlr

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.1.

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterey 12.2.1

**Comment by nathanlesage** [comment]
This has been fixed with the new nightly — tomorrow we'll release 2.2.2 that will ship that to everyone :)

**Comment by zteli** [comment]
perfect and many thanks!

**Comment by boutil** [comment]
Hi,

I get a resembling error with 2.2.2 after upgrading from 2.1.3 today (Debian package on amd64).
```
Error starting TranslationProvider

Could not start TranslationProvider: Unexpected end of JSON input
```
Is this related?

**Comment by boutil** [comment]
that is a different problem. I'll open a proper issue.
