### ISSUE TITLE
Case insensitive search inside editor

### ISSUE THREAD

**Issue by Shandi97** [Zettlr/Zettlr#322]
It appears that if you search via ctrl-f inside the file it searches case sensitively.
So if I have wight and Wight it will only find one and I can't switch between those, which is quite problematic  for larger files.

Is it possible to make the search either case insensitive or to give us a way to switch between sensitive and insensitive search?

**Comment by nathanlesage** [comment]
Culprit line (have to add an "i" as a flag):

https://github.com/Zettlr/Zettlr/blob/dae0541df97f4aa9f568a822f6c83a0dadf45869/source/common/util/make-search-regex.js#L38

But to remedy the issue instantly, there's sorta misuse of the regular expressions. If you search for `/wight/i` it'll do a case insensitive search for "wight". If you only want to exactly capture "wight" and "Wight" but not "wIgHt", use `/[wW]ight/`!

(Explanation: The search will convert anything into a regular expression, but I forgot to add the "i" flag to the "normal" search. But in case of a regular expression, the flags of the expression are concatenated and passed to the search, so this way you can force Zettlr to use the "i", hence case-insensitive, flag.)

**Comment by nathanlesage** [comment]
Works from 1.4.2. Case-sensitive searching can then be done using regular expressions!
