### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#3221]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Hellohello, the new Graph View is fantastic! I just wondered if it would be possible to somehow include tag similarity in the graph view, as it is already included in the sidebar. I think this could be a bit challenging to implement, but nevertheless very insightful when drawing new connections between zettels and notes.

### Example Workflow

Maybe here someone with more experience in graphical visualisation may jump in, but anyways, this is how it popped up in my mind:

There could be a toggle to use links or tags in the graph (I think we can't have both at the same time?)

In the tag mode, it could look like this:
* Tags appear as simple dots, maybe differently shaped
* The graph displays the connections of file-dots to the tag-dots. just like in the link-graph

### Caveats

Opens up a completely new story when development actually was meant to focus on the graph view for links ¯\_(ツ)_/¯

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
Please see this discussion I created: https://github.com/Zettlr/Zettlr/discussions/3220
