### ISSUE TITLE
[Enhancement] Graph view scroll

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#3222]
### Description

Right now, scrolling in the graph view moves the actual graph out of the window. 

### Proposed Changes

More intuitive would be a behavour as in map apps: Scrolling = zooming in and out

### Caveats

Don't think there are any

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Win10

**Comment by nathanlesage** [comment]
I tried out both, and I found that scrolling is nicer, because if you have a really large graph, it makes it good to move from A to B. But I do admit that this works flawlessly mainly because of the high precision of MacBook trackpads. I'm happy to hear more suggestions!

**Comment by halloichbingunnar** [comment]
Ah, maybe I should add that I'm using a mouse 🐭 with it, the scroll is so sensitive that it's hard to really navigate the graph. 
I remember that for example miro also has different modi of navigation for mouse (zoom=scroll) and trackpad (zoom=movement like zooming on a smartphone).
