### ISSUE TITLE
[Bug] [2.2.2] Can't create new directory

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3224]
### Description

In 2.2.2, whenever I try to create a new directory, I get an error saying that a directory with the same name already exists. I double-checked, and that directory did not exist.

In 2.2.1, this issue is not present.

### Reproducing

Simply try to create a new directory.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.2

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux manjaro 5.14.21-2

### Additional Information

Creating new files works in 2.2.2.

**Comment by kyaso** [comment]
After git bisecting, this commit was revealed as the source of the regression: 23b98d6ca35801c8fb37aebac043ae427f669c9c

**Comment by nathanlesage** [comment]
It likely has to do with this signature change:

![image](https://user-images.githubusercontent.com/17251683/154355870-f4495da7-691a-4e49-8864-379aca774606.png)

I did check all the commands, but I may have missed the directory creation command. The error almost certainly emanates from there.

**Comment by rialistic** [comment]
I have the same issue with MacOs system.
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/74057150/154626607-a9618dfc-3024-4129-9606-c2bca7731c8e.png">

**Comment by nathanlesage** [comment]
Fixed in 0cd8843
