### ISSUE TITLE
[Bug] 2.2.2 on Debian amd64 fails to start with a "Error starting TranslationProvider" popup

### ISSUE THREAD

**Issue by boutil** [Zettlr/Zettlr#3225]
### Description

Trying to run Zettlr 2.2.2 installed from the amd64.deb package, on Debian "sid", I get the following Error popup:
```
Error starting TranslationProvider
Could not start TranslationProvider: Unexpected end of JSON input
```

In the terminal, I get the following output until the popup appears:
```
[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /opt/Zettlr/resources/pandoc
[Application] Environment check complete.
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[68176:0216/214732.486076:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

After pushing the [ok] button of the popup, the following appears in the terminal
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f._getTranslationMetadata (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1582047)
    at async f.boot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1580633)
    at async t.default._informativeBoot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1393038)
    at async t.default.boot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1389239)
    at async t.bootApplication (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1394613)
```

The main window does not appear at all.

### Reproducing

Just try to run Zettlr from the menu, or from the command line (for terminal output)

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.2

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian "sid"

### Additional Information

I upgraded straight from 2.1.3 when I encountered the bug for the first time.
Then I rolled back, and tried to upgrade step by step to 2.2.0, then to 2.2.1, then 2.2.2.
(2.2.0 and 2.2.1 did not start for reasons already reported and already fixed)

**Comment by nathanlesage** [comment]
Almost sounds as if the translations have been only partially downloaded. Would you mind removing all downloaded translations from the config directory and see if that fixes it? (I think it's in `~/.config/Zettlr`, proper path can be found in the troubleshooting docs)

**Comment by boutil** [comment]
Thanks! That was it: I deleted `~/.config/Zettlr/lang/`, and then could launch Zettlr without issue (so far). I will be able to play with the new graph feature :)

Maybe then the error popup should propose a button to erase the old translations and fetch fresh ones?

**Comment by zteli** [comment]
I've had the same error message. Deleting the files in ../Application Support was the solution. Thanks for this hint.

**Comment by nathanlesage** [comment]
Perfect! For now I'm going to assume that your internet connection just had a slight hiccup. If anything new comes up, feel free to reopen.
