### ISSUE TITLE
[Feature Request] Highlighter like used in Bear or Typora

### ISSUE THREAD

**Issue by myn-user** [Zettlr/Zettlr#323]
Hi,

would it be possible to integrate a **Highlighter-function** in Zettlr?

Bear uses `::`, Typora and Epsilon Notes (Android) uses `==` for highlightning a text passage.
Examples: 

1. `::This is a text passage I found very important::` 
or
1. `==This is another important passage==`

If you can do this please use both symbols and give the user the possibility to choose between the both (like you did it with **bold** and _italic_), in order to read files/texts from users of Bear, Typora etc.

**Comment by nathanlesage** [comment]
Mhmh, planned this some time ago. Not high priority, but it's on the list!

**Comment by nathanlesage** [comment]
Easier than I though, here you go.

![image](https://user-images.githubusercontent.com/17251683/64921745-3b9b2d80-d7c7-11e9-8c4a-ccccfb4c8735.png)

**Comment by samarulmeu** [comment]
Did you also implement a shortcut or an entry in a right-click menu so that a selected text could be easily highlighted?

**Comment by nathanlesage** [comment]
Not right now, I'm a little bit lazy lately (also due to me moving to a different town)

**Comment by samarulmeu** [comment]
Or maybe you could add it in the formatting menu alonside blocquotes and headers?

**Comment by nathanlesage** [comment]
Yeah, obviously, but as I said: I was too lazy :D

**Comment by samarulmeu** [comment]
Highlighting text is a very nice feature, but unfortunately it seems to work only inside paragraphs. 

So something like this does not work

```
The quick brown fox jumps over the lazy dog. ==The quick brown fox jumps over the lazy dog. 

The quick brown fox jumps over the lazy dog==. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. 
```

Maybe you can address this when you implement a menu shortcut.

**Comment by nathanlesage** [comment]
Nope, highlighting is an inline-element. Actually, this is closer to how PDF-readers treat highlighting in PDF, where you have to highlight the first part of a sentence on one page and then also highlight the second part on the next page!

**Comment by samarulmeu** [comment]
But not the way eBook readers treat highlighting text. I'm thinking of a markdown file as a continuous document (at least between sections) and not as a paged document as PDF is, but, in the end, is your choice.

**Comment by nathanlesage** [comment]
Yes, I clearly see where you're going at! And I know how ebook-readers treat text, you're right! Nevertheless, it's easier to implement in this rather static way as ebook readers do than in CodeMirror where the text _itself_ may change at any time. Besides, CodeMirror works best if you treat lines as encapsulated things (i.e. the block and inline element-division that is applied everywhere)! It might be possible, but I am pretty sure that Markdown itself is envisioned in a way where you can't have something start on one line and end somewhere in the middle of the next line, at least as far as the specs go … I hope this makes sense :)
