### ISSUE TITLE
[Bug] Preferences changed if preference window clicked back to focus

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3233]
### Description

Having zettlr and the preference window side to side, clicking somewhere to bring the preferences to focus has a high chance to toggle an option accidentally.

Possible solution: Only toggle e.g. checkboxes if the box is clicked directly.

### Reproducing

As described above.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I have a better idea: Currently Zettlr is set to already register the first click on a window while gaining focus. There's a [handy setting](https://www.electronjs.org/docs/latest/api/browser-window) I could expose in the config:

> `acceptFirstMouse` boolean (optional) - Whether clicking an inactive window will also click through to the web contents. Default is `false` on macOS. This option is not configurable on other platforms.

Oh, wait. Why isn't that configurable on other platforms? 🤨

Alright, forget about that. But I think that the `labels` should also trigger a preference change. So maybe this is something we shouldn't fix …? (It's definitely not a bug!)

**Comment by leo-hstone** [comment]
If the labels change the preference is up to you, but the white space right to it should not in my opinion: Imagine this example:

![grafik](https://user-images.githubusercontent.com/62036826/154803460-b21a83d8-53d7-4501-947a-c1fe5cfcf908.png)

If I click anywhere in the grey space visible of the preference window, there is a high chance, that a preference is swtiched by accident (which happend to me multiple times before I discovered this behaviour).

**Comment by nathanlesage** [comment]
Aaaaaaahhhhh, yeah that's something one might want to fix, indeed!
