### ISSUE TITLE
[Bug] Zettlr can't find documents referenced from Mendeley BibTex on Windows

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#3234]
### Description

Ona Windows system the Mendeley Desktop software handily synchronizes a .bib file, which I have routed into my Zettr Workspace. This mostly works, once I have told Zettlr where to find it, and correctly identifies and replaces the citation key with the paper name.  However, the parsing of the path to the associated file fails (because of something stupid Mendeley does, but that's out of our control) so that trying to click through to the document will never work.

An example file reference from the Mendeley bibtex file is:

`file = {:C$\backslash$:/Users/Frank/AppData/Local/Mendeley Ltd./Mendeley Desktop/Downloaded/Mart{\'{i}}nez‐prieto et al. - 2008 - Enhancing literary electronic books with logical structure electronic work Enhancing literary electronic.pdf:pdf},`

There are two issues with this.
* The first is that it somehow uses a \ in the filename, which is a special character,  to escape an accent. Somehow Mendeley manages to deal with this.
* The second is that the drive letter part of the filename, which should just be `C:` is stored as `C$\backslash$:`. This is the bit which screws up the parsing as it makes no sense as a path or a drive letter.

### Reproducing

1. Download and Install Mendeley Desktop on a Windows system
2. Load in some references, with associated documents, (for bonus points, with accented characters)
3. Tell Mendeley to save and synchronize a bibtex file at a known location
4. Examine the generated bibtex file to see the file location definitions
5. Tell Zettlr where to find the generated bibtex file
6. Mention some of the citations from 2, observe that there is no way to click through to the document

![image](https://user-images.githubusercontent.com/51254/154806460-518e2f01-adad-4262-868c-5c52922dc6b7.png)

![image](https://user-images.githubusercontent.com/51254/154806557-e5eb3ca6-7e5c-4d6f-9f73-267650d67432.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Do I understand it correctly that *Mendeley* inserts that weird `$backslash$`-thing? If so, is that a recognized BibTeX standard? If not, I think we shouldn't "fix" that. Mendeley is, after all, part of Elsevier, and idk, I can't tell you this, but I would argue JabRef and Zotero are in any case the better choice …

However, what Zettlr is doing is utilize a third-party library (Astrocite) that handles all the BibTeX magic. Could also be that there is an issue because while Zettlr can recognize `C:\` and will do so flawlessly, it cannot recognize `C:$backslash$`

**Comment by efficacy** [comment]
I'm sure it is a problem with Mendeley. Their developers don't seem to know what they are doing and I am getting increasingly fed up with the product. 

I would love to move to something such as Zotero but I work on a lot of different machines and rely on cloud storage for papers. I currently have about 1.7GB stored in Mendeley for free, which greatly exceeds the free space with Zotero. I would consider paying and moving over if I was sure of the benefits, but evaluating reference tools is yet another distraction from the actual work of my PhD :(

**Comment by nathanlesage** [comment]
Understandably, but iirc Mendeley is a kind of a fork from Zotero, and a colleague recently switched, and it works fine! With regard to storage, true, I use Nextcloud to store the PDFs, and that works perfectly well.

If you'd like to consider this, I've documented exactly how I do it [here](https://hendrik-erz.de/post/how-i-work-part-iv-reference-management-reading-literature).

**Comment by nathanlesage** [comment]
I'm going to close this issue because it's not in scope for Zettlr … Mendeley needs to get its s\*\*\* together …

btw: The newly released Zotero 6 looks slick! ;)
