### ISSUE TITLE
[Bug] Backlinks not showing in "Related Files"

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3237]
### Description

In 2.2.2 and 2.2.3, backlinks are not shown anymore (tags work fine).

This worked fine in 2.2.1.

### Reproducing

For a file where you know that there are other files linking to it, open the sidebar "Related Files" tab -> Backlinks are not shown.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.2, 2.2.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux manjaro 5.14.21-2

### Additional Information

I solely use ZKN IDs for linking.

**Comment by kyaso** [comment]
It looks like the recent changes in the LinkProvider could be the reason for this?

**Comment by kyaso** [comment]
It looks like the recent changes in the LinkProvider could be the reason for this?

**Comment by kyaso** [comment]
This commit 43b26b85a7887be596871ee78c295a99d2b59b05 changed the logic of the `get-inbound-links` considerably. If I'm not mistaken, IDs aren't considered at all anymore?

**Comment by ricfos** [comment]
I found the same bug running Zettlr 2.2.2 and 2.2.3 on Windows 10. 

I did some testing with older versions and the last versions that showed correctly all backlinks in "Related Files" where 2.1.3 and 2.2.0.  For me version 2.2.1 only showed backlinks in "Related Files" if the related file was opened at some point during the session in the editor! 

Example: 

1. I start Zettlr and load/open directory D with files a.md, b.md and c.md. The files b.md and c.md contain a directt link [[a]]. No files are open in the editor at start.
2. With 2.1.3 or 2.2.0: if I open file a.md in the editor , then "Related Files" shows correctly all the backlinks b and c.
3. With 2.2.1:  if I open file a.md in the editor "Related Files" shows nothing. If I open file b.md and switch to a.md then "Related Files" shows b. Now I open file c.md and again switch to a.md. "Related Files" shows b and c.

To me it seems that the problem with backlinks in "Related Files" started with version 2.2.1 and got worse in 2.2.2 (2.2.2 never shows backlinks in "Related Files" even if the related files were open in the editor).

**Comment by nathanlesage** [comment]
Ah, that's what that ID database was for 👀  I may have been a little bit to orderly when refactoring the link provider

> With 2.2.1: if I open file a.md in the editor "Related Files" shows nothing. If I open file b.md and switch to a.md then "Related Files" shows b. Now I open file c.md and again switch to a.md. "Related Files" shows b and c.

This is a good hint, because I did remove the link reporting from the FSAL. Instead the link provider listens to events from the FSAL. I'll have to check this out myself, but it's a good chance that @kyaso has found the origin of that.

**Comment by efficacy** [comment]
This is only an opinion, but backlinks and tags are very different things and, even when this is working, the result is often a cluttered list which makes things harder to find rather than easier. I would very much prefer that backlinks and notes related by tag get separate panels if at all possible, or at the very least a switch to disable each type.

**Comment by nathanlesage** [comment]
@efficacy Mh, I don't know whether that's such a good idea. I don't want to introduce an extra setting for that, and I feel that the current order (first backlinks, then backlinks and tags, then tags) is fine? Idk, it's difficult, because I feel that tags and links can be used very similarly, so it might be difficult to find a way to compensate for that, or what do you think?

**Comment by kyaso** [comment]
> the result is often a cluttered list which makes things harder to find rather than easier

This was indeed bugging me as well, so I decided to add a visual highlight to backlinks:

![grafik](https://user-images.githubusercontent.com/18646029/154822335-21ccb6e2-0381-49cd-ba1b-4a7bd8cb1cee.png)

I have this in my current custom fork, but can open a PR for this if this interesting for the community!

**Comment by efficacy** [comment]
This may be a difference in ways of working, but I use tags and backlinks for very different things.

I am liberal with tags, often giving each note several tags and each tag having many notes. For example, all my notes about papers are tagged with #paper, all my ideas are tagged with #idea, all my notes about people are tagged with #person  etc. This means that when I look at any paper, the related items fills up with all the other papers, and if I look at any person the related items fills up with all the other people pages. The great majority of the time I don't want or need to see those, they are there for searching, filtering, and counting, not linking.

Backlinks (and forward links, of course) are much more important to me. They are the lifeblood of relationships between notes and how I find related concepts when I am not expecting them. If the panel were to only show backlinks I would keep it open at all times and use it to follow a train of thought in the Zettelkasten way.

**Comment by nathanlesage** [comment]
> (the link icon was somehow not enough for me :D).

Then how about we add a class `link` and/or `tag` based on the relationship and let people customize the layout? This would be a perfect case for our Custom CSS section!

@efficacy Mh, I see. Maybe a simple (persistent) filter might be enough? Then we wouldn't waste too much screen real estate and still have conditional display of both types of relations

**Comment by kyaso** [comment]
> Then how about we add a class link and/or tag based on the relationship and let people customize the layout? This would be a perfect case for our Custom CSS section!

Like this? https://github.com/kyaso/Zettlr/commit/5055f60af80039246d5a25f54b6407161294948c

**Comment by nathanlesage** [comment]
Yup! But without the custom styling, which should be part of the Custom CSS section. This way everyone has the icon, and if that doesn't work, they can apply said CSS themselves? Does this sound like a deal? :) (Oh, and plus with a specific `tags` class, makes it more explicit in case you want to care more about the tags)

**Comment by kyaso** [comment]
Totally agree. Let's do it!

**Comment by efficacy** [comment]
As an aside, I have noticed that when I delete or rename a note, it leaves a kind of unclickable "ghost" in the related files with a full path to a now nonexistent file!

![image](https://user-images.githubusercontent.com/51254/154823058-6da93b57-0d38-4027-a43f-602c0bebb088.png)

**Comment by nathanlesage** [comment]
👻

**Comment by nathanlesage** [comment]
Just saw that this issue is still open — it's fixed and comes with the next release!
