### ISSUE TITLE
[Enhancement] Add possibility to customize appearance of backlinks/tags in sidebar

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3238]
### Description

**Background**: As pointed out by https://github.com/Zettlr/Zettlr/issues/3237#issuecomment-1046122251, some users find it challenging to quickly distinguish backlinks and tags from each other in the "Related Files" tab of the sidebar. Even though the entries are ordered (first backlinks, then tags) and also have icons attached, it can still be difficult to quickly gain an overview of, e.g., all the backlinks.

One way how to address this would be to add more distinct styles (e.g., colors) to the different types of entries. However, hardcoding these styles might again not please every user. Therefore, the compromise would be to add the possibility to style the related files entries through the **Custom CSS** section.

### Proposed Changes

Add classes to the entries (backlink, tags) of the "Related Files" section. These classes can then be referenced in the custom.css to apply custom styles.

We would need three classes, as Zettlr currently defines three relation bins:

* Backlink+Tag(s)
* Backlink
* Tag(s)

### Caveats

None.

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Operating System Version

Linux Manjaro

**Comment by nathanlesage** [comment]
Two classes should suffice, since people can target `.tags.backlinks` ;D

#optimization

**Comment by kyaso** [comment]
> Two classes should suffice, since people can target `.tags.backlinks` ;D
> 
> #optimization

Makes sense :D

**Comment by nathanlesage** [comment]
Hey, I'm currently on the road and can't push my changes, but I just implemented a way so that you can retrieve the link status and we can differentiate between inbound, outbound, and bidirectional links, so we can maybe utilize this information as well. Shall I already add those classes to the DIV element or do you want to do that?

**Comment by kyaso** [comment]
Feel free to do so! I assign this issue to you then.

**Comment by nathanlesage** [comment]
Perfect, done! I'm going to push as soon as I have WiFi again 🙏🏼😌
