### ISSUE TITLE
[Bug] Citations in inline latex not resolved

### ISSUE THREAD

**Issue by pstadler1990** [Zettlr/Zettlr#3239]
### Description

When using the markdown citation (@...) in a document with inline latex statements, the citations are not resolved.

**Example:**
```latex
\begin{figure}[h!]
    \includegraphics[width=.5\linewidth]{myimage.png}
    \caption{The caption and an image credit [@imagecreditkey]}
\end{figure}
```

The expected output would be a resolved citation within the latex statement, however the @-statement keeps unresolved as plain text.

I imagine that this is probably a pandoc issue, however it could be beneficial for Zettlr if that'll work.

### Reproducing

Add citation to a latex statement in a markdown document

```latex
\begin{figure}[h!]
    \includegraphics[width=.5\linewidth]{myimage.png}
    \caption{The caption and an image credit [@imagecreditkey]}
\end{figure}
```

or `\mylatexstatement{@citekey}` ..

and compile to PDF using Latex (Pandoc)

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This is working as intended: when you drop in some TeX or HTML then you need to stick to that language within that block. I.e. you need to use proper \cite syntax It's cool that you can add such blocks inside a Markdown document, but there are limits to software 😅
