### ISSUE TITLE
[Bug] 2.2.3 core dumped on start

### ISSUE THREAD

**Issue by Donearm** [Zettlr/Zettlr#3242]
### Description

After installation, 2.2.3 Zettlr crashes a couple of seconds while trying to start with:

```
[823238:0221/105050.962537:ERROR:wayland_connection.cc(205)] Failed to connect to Wayland display
[823238:0221/105050.962813:FATAL:ozone_platform_wayland.cc(231)] Failed to initialize Wayland platform
zsh: trace trap (core dumped)  zettlr
```

### Reproducing

I installed 2.2.3 and had the same message as #3240 . I restarted Zettlr and since then only the core dumped message is what I get. I reverted to 2.2.2 (which was working fine for days) and same message.

Removing the config directory doesn't make any difference. If it helps, I am running the same kernel version (an old LTS) since Zettlr 2.2.1.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

ArchLinux

**Comment by kyaso** [comment]
> [823238:0221/105050.962537:ERROR:wayland_connection.cc(205)] Failed to connect to Wayland display
[823238:0221/105050.962813:FATAL:ozone_platform_wayland.cc(231)] Failed to initialize Wayland platform
zsh: trace trap (core dumped)  zettlr

Maybe this [thread](https://github.com/OSSystems/meta-browser/issues/232) potentially has an answer for you?

**Comment by Donearm** [comment]
I don't use wayland, nor chromium. Firefox and X11.

I tried assigning the global variables mentioned in that thread (DISPLAY and XDG_RUNTIME_DIR I had already, only WAYLAND_DISPLAY no) but the error message doesn't change.

**Comment by Donearm** [comment]
On Arch, tried with both [zettlr](https://archlinux.org/packages/community/x86_64/zettlr/), [zettlr-bin](https://aur.archlinux.org/packages/zettlr-bin) (which is the rpm repackaged) and [zettlr-git](https://aur.archlinux.org/packages/zettlr-git) (multiple versions).

**Comment by kyaso** [comment]
Hmm, could you maybe try out the AppImage?

**Comment by nathanlesage** [comment]
Holy hell, why are there so many different Zettlr-packages on the AUR? 😨

**Comment by Donearm** [comment]
> Holy hell, why are there so many different Zettlr-packages on the AUR? fearful

Many as "2"? One is the git version and another the precompiled binary.

**Comment by Donearm** [comment]
Update on my issue: with the latest rebuilt of the community's Archlinux package, Zettlr starts just fine with a clean configuration. If I copy back my config directory, I meet with the #3240 crash on start.

**Comment by nathanlesage** [comment]
So it seems to be a configuration issue? Then it would be great if I could take a look at this faulty configuration file to see if there is anything in there we might want to investigate.

**Comment by Donearm** [comment]
It seems that something was broken in the previous packages and now it is fixed. These were the [recent changes](https://github.com/archlinux/svntogit-community/commits/packages/zettlr/trunk).

As per the configuration, I copied my original config.json into the new directory created when Zettlr is first ran and no issues were shown. Is there any other configuration file that I could check, perhaps?

**Comment by nathanlesage** [comment]
Ah, alright, so just an issue with the build? That would be even better (since I didn't touch the config parser in the meantime, so it seemed odd that it would be the config).

**Comment by Donearm** [comment]
@nathanlesage not exactly as I only copied the config.json from my configuration directory. If I copy the whole thing, Zettlr crashes with the #3240 . There is then something in the configuration directory that makes Zettlr crash even with the most recent Arch build.

**Comment by Donearm** [comment]
2.2.4 also crashes. The only change in the Arch PKGBUILD is the upgrade to [Electron 17](https://github.com/archlinux/svntogit-community/commit/05866d17ca96eb712be7a831ef61fb1695390bdb). It crashes also with a clean configuration.

**Comment by nathanlesage** [comment]
Does this still happen with a clean 2.2.6 install?

**Comment by nathanlesage** [comment]
Since there has been no news on this issue, I am going to assume it being fixed.
