### ISSUE TITLE
Issues when connecting files

### ISSUE THREAD

**Issue by Nissentott** [Zettlr/Zettlr#325]
Fantastic tool, been using it from since before 1.0 as an educator and researcher in history and social studies and implementing it in my zettelkasten routine. I do however have a problem that started after 1.4

When I add a link to another zettel i.e. write the [[ID]] I just want the "[[ID]]" in the link, as it were before. Now since 1.4 I get "[[ID]] ID - Title of the note"

Example:
I get:
[[201908191701]] 201908191701 - Folgezetteln
When I just want: 
[[201908191701]]

This means I have to delete the things after the ]] for each connection I make, is there some way to disable this behavior in the app?

**Comment by nathanlesage** [comment]
I added this as some people wanted to automatically have the filename also added. But an option should be possible, yes!

**Comment by dambaras** [comment]
If we're getting really picky, I would like the following option:

1. Create new note: automatically assigns ID and prompts for additional title. So created note title is, e.g., YYYYMMDDhhmm.SomethingSomething

2. [[]] yields: [[YYYYMMDDhhmm]] SomethingSomething (as opposed to [[YYYYMMDDhhmm]] YYYYMMDDhhmm.SomethingSomething

Could that be an option?

**Comment by nathanlesage** [comment]
Sure, it's what we call "Fleißarbeit"; easy but tedious long work :D But yeah, if I'm at it I can include this as well.

**Comment by nathanlesage** [comment]
P.S.: The auto-ID is already implemented, when you create an ID you have the option to add a title behind. What this feature would do is let you choose:

- Do nothing on linking (hence ID in brackets and good)
- Add the full title w/o file extension after the link
- Add the full title but remove ID if possible (simple substring replacement)

**Comment by dambaras** [comment]
Thanks!

**Comment by nathanlesage** [comment]
For cleanliness of this issue; I just discovered that there is also this issue, addressing the same stuff, so I'm going to close this one here. If anything's missing, please simply drop it over there: https://github.com/Zettlr/Zettlr/issues/391 :)
