### ISSUE TITLE
[Enhancement] Ability to remove the restrict search to directory

### ISSUE THREAD

**Issue by biva** [Zettlr/Zettlr#3250]
### Description

Hello, I use a lot the Full-Text search: this works very well, but I'm confused about the usage of the _Restrict search to directory_ : indeed, I work within the same folder all the time, and I would like to search within the whole folder, never to restrict the search in sub-folders.

### Proposed Changes

Would it be possible to add an option, so that there's no directory selected by default, but instead that this remains empty.

### Caveats

As it would be an option, user are free to use it or not

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

### Additional Information

Thank you so much for your work!

**Comment by Raphapere** [comment]
@nathanlesage is already thinking about a solution to that (#3247). It would be a great feature!

**Comment by biva** [comment]
Great, thanks! Should I keep this issue open?

**Comment by nathanlesage** [comment]
@biva Yes, sure. The reason why I'm not simply disabling the autofill is that in some instances having this field autofilled is handy, and I want to create a heuristic as to when autofilling makes sense, and when not, so feel free to share your thoughts!
