### ISSUE TITLE
Synthwave 84 Theme [enhancement]

### ISSUE THREAD

**Issue by jrcharney** [Zettlr/Zettlr#326]
One of my favorite themes in Visual Studio Code is [Synthwave '84](https://github.com/robb0wen/synthwave-vscode).  There are there synthwave/vaporwave themes like [City Lights](http://citylights.xyz/) and [Horizon](https://github.com/jolaleye/horizon-theme-vscode).

If you like adding themes, consider taking a look at [VS Code Themes](https://vscodethemes.com/), [Vim Colors](http://vimcolors.com/), or [Terminals Are Sexy](https://terminalsare.sexy) for ideas.

I like the idea of having a dark theme with bright colors in it but non of the current themes seem to do this very well. It's also very hard to see colors when using bold, italic, links, or blockquotes in dark mode.  Hopefully using something like this will allow for more visible and aesthetically pleasing themes.

**Comment by nathanlesage** [comment]
We're currently planning to re-do the visuals. If you'd like to have more themes added, I'm happy to discuss some ideas before merging a PR ;)
