### ISSUE TITLE
[Bug] Wrong label "dialog.preferences.dark_mode" in the "View" menu

### ISSUE THREAD

**Issue by fstamour** [Zettlr/Zettlr#3269]
### Description

The label of the menu item in the `View` menu (in the menu bar) is showing `dialog.preferences.dark_mode` (see screenshot)

![image](https://user-images.githubusercontent.com/2881922/155725826-7538b6bc-9dfc-49fa-99f7-7e5ad8fe37ae.png)

### Reproducing

1. Click on the View menu in the menu bar.
2. behold

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by fstamour** [comment]
I don't have this issue anymore... might be hard to reproduce.

**Comment by nathanlesage** [comment]
My take would be that the API had a hiccup and delivered a partial file. I think it's safe to close this issue, but please comment here if you notice the issue occurs more often!
