### ISSUE TITLE
[Enhancement] Possibility to search for file while using space, colon, etc. inside squarebrackets while linking

### ISSUE THREAD

**Issue by xauximan** [Zettlr/Zettlr#3272]
### Description

I faced a problem quite often in the last weeks: Everytime I want to link a file inside my structure notes for my Zettelkasten, I was not able to use characters like space, colon, dots, etc. because the search for the filename stops working afterwards I used this characters. I guess it will be an improvement if it is possible to use these characters inside the squarebrackets while linking, especially when you are having a ton of notes with similar titles.

### Proposed Changes

Allow searching with characters like space, colon, dots, etc. inside the squarebrackets for linking, so that the search doesn't stop working anymore. 

### Caveats

No idea. I think probably it will even increase efficiency because possible results getting limited. 

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by kyaso** [comment]
For spaces there is already an option: Preferences -> Editor -> "Accept spaces during autocompletion"
