### ISSUE TITLE
[Bug] Problem exporting to Reveal.js

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#3278]
### Description

When I try to export from Zettlr to Reveal.js, nothing happens.

### Reproducing

1. I write a markdown file
2. Choose `Export > reveal.JS > Temporary folder > Export`
3. Display an error message: "ENOENT: no such file or directory, open '/tmp/path-to-file"

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ubuntu 20.04.3 LTS

### Additional Information

When I try to export to HTML the error message is:
> Unknown option --defaults.
> Try pandoc --help for more information.

I try to change `Settings > Exports > Use the internal pandoc for exports` and in both cases I have the same result.

Many thanks for the help.

**Comment by nathanlesage** [comment]
I had this issue myself, and it's possibly gone with the most recent nightly, would you mind trying that out?

**Comment by hiperterminal** [comment]
I installed the version 2.2.4, in `Settings > Export > Use internal pandoc` I checked the box and now it works. Many thanks @nathanlesage !
