### ISSUE TITLE
.Rmd isn't supported

### ISSUE THREAD

**Issue by Sisi-Wiciel** [Zettlr/Zettlr#328]
## Description
I found that it could be set "Enable Rmarkdown file support" in the advanced preferences. But I couldn't open  .Rmd files. Is there any other setting should I do?

## Reproducing
I only did the following steps: preferences-->Advanced--> Enable Rmarkdown file support

## Platform
 - OS: Windows
 - OS Version :10
 - Zettlr Version: 1.4.0
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information
The .zip file is the screenshot video
[zettlr-rmarkdown.zip](https://github.com/Zettlr/Zettlr/files/3614797/zettlr-rmarkdown.zip)

**Comment by nathanlesage** [comment]
Please don't include ZIP-files on computer-related sites …

Anyway, this should not happen. Did you re-start the app? Because the app needs to be restarted once to re-read the file tree to apply the change.

**Comment by Sisi-Wiciel** [comment]
OK. I had tried re-start the windows systems and the app, but it didn't work. And I tried to import the Rmd-files, but it failed. 
![捕获](https://user-images.githubusercontent.com/21168981/64951323-31a12980-d8b0-11e9-9743-fb3989845167.PNG)

**Comment by nathanlesage** [comment]
Ah, damn! I'm on it!

**Comment by nathanlesage** [comment]
I think it's related to the fact that you've capitalised the filename (`Rmd` instead of `rmd`) and I forgot to make it case-insensitive

**Comment by Sisi-Wiciel** [comment]
yeah, I changed the Rmd to rmd, it worked

**Comment by nathanlesage** [comment]
Alright, then I know what to do! Thanks for reporting

**Comment by nathanlesage** [comment]
And fixed!

**Comment by jsstanley** [comment]
Hi @nathanlesage, apologies for pinging you over such a trivial issue but I believe this bug still persists i.e. it works with `.rmd` but not `.Rmd` files

I'm on the latest version of Zettlr - `1.7.1`

**Comment by nathanlesage** [comment]
>  it works with .rmd but not .Rmd files

… wait a moment … Mh, opening .Rmd-files was always possible, but I forgot to make the new file/file renaming command case-insensitive. Should work now.

**Comment by ecodiv** [comment]
> 
> 
> > it works with .rmd but not .Rmd files
> 
> … wait a moment … Mh, opening .Rmd-files was always possible, but I forgot to make the new file/file renaming command case-insensitive. Should work now.

On Windows, when including Rmd (with first capital letter) to the list of file extensions under the advanced tab in the preferences, it is changed to lower-case upon saving. 

I guess this is the reason I can open files with *.rmd, but not *.Rmd in Zettlr via the Window explorer. 

Strangely enough, via the attachment pane in Zettlr, I cannot open Rmd or rmd files. Even though both show up in the attachment pane. Double clicking results in the message that Zettlr cannot open the file. 

Not sure if the above is related to the fact that Rmd files are not showing up in the Workspace as edible files, like they used to do in versions 1.7.* (see issue https://github.com/Zettlr/Zettlr/issues/1556#issuecomment-751471118)

**Comment by petrbouchal** [comment]
@nathanlesage Just to add that on the latest release on a Mac 

- Rmd files will not open via the open diagogue unless renamed to .rmd (i.e. nothing happens after clicking on the file in the open dialogue)
- Rmd files do not appear in the file pane unless renamed to .rmd

I also do not see the Rmd option in the preference pane [which is mentioned in the documentation](https://docs.zettlr.com/en/reference/settings/#advanced) but maybe that is now unnecessary.
