### ISSUE TITLE
[Bug] 2.2.3 New files aren't added to workspace until application restart in macOS M1

### ISSUE THREAD

**Issue by subhodeeps** [Zettlr/Zettlr#3282]
### Description

When I try to create a new file by pressing `cmd` + N, or from the file menu, a new file is opened but it is not displayed in the File Manager on the left side until the app is restarted.

### Reproducing

Add a new markdown file by clicking cmd+N or from the file menu. 

You will see that it is not displayed in the file manager.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

macOS Monterey on M1

### Additional Information

I am running the app on Apple Silcon. I saw another bug report where it was said that the problem has been fixed but it is still persisting. 

https://github.com/Zettlr/Zettlr/issues/3248

**Comment by nathanlesage** [comment]
Already fixed in codebase, comes with the next patch. In general: If you find an issue that is closed, this indicates that the bug is fixed, but it will take to the next release.
