### ISSUE TITLE
Crash after idle for extended time

### ISSUE THREAD

**Issue by ajlewis2** [Zettlr/Zettlr#3283]
Twice I have left Zettlr open and come back in a couple hours to find it had crashed. I tried to save my work and close, but the save would not work and the only way to get the program working was to close without saving. Then I could open the program and use it again. I am running on Linux 1.8.9+nightly-20210719.  Yesterday was the first time I've experienced it, but I'm not sure if I've ever left the program open like this before, so I do not know if it is a new problem.

**Comment by kyaso** [comment]
Please try one of the newer Zettlr versions. The newest is 2.2.3.

**Comment by ajlewis2** [comment]
Thanks. I haven't got notification of a new version and didn't get anything when I when I clicked on "Check for Updates" so I didn't realize there was a new edition. I should have realized that the 'nightly' build wouldn't update. I'll test it by leaving it open to see if it helps. Thanks again for the fast response!

**Comment by ajlewis2** [comment]
Okay, it is working fine now. In fact, I'm glad I had the problem so that I found out about the new versions I had missed and the goodies packed in. I'm enjoying some changes like how nicely footnotes are working. Thanks again for the help. I'll click "Close with comment now.

**Comment by kyaso** [comment]
You're welcome!
