### ISSUE TITLE
[REQUEST] Menu item and shortcut for strikethrough text

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#329]
It would be nice, if you could implement a menu item for strikethrough text accompanied with an appropriate shortcut as well as the automatically closing of the '~~' when creating strikethrough text by typing.

**Comment by nathanlesage** [comment]
Should be no problem

**Comment by jothanne** [comment]
Thank you!

BTW: Is there any (maybe nowhere mentioned) shortcut for starting a task list? Always typing '- [ ]' is a bit cumbersome since I often make use of this list type.

**Comment by nathanlesage** [comment]
I'm actually not quite sure, but I don't think so …
