### ISSUE TITLE
[Bug] Downgrading from v2.2.4 to v2.2.3 reopen bug #3154

### ISSUE THREAD

**Issue by sebzeter** [Zettlr/Zettlr#3298]
### Description

As a workaround to bug #3295 I've downgraded from v2.2.4 to v2.2.3 but this reopen issue encountered with closed bug #3154.

### Reproducing

Upgrade from v2.2.3 to v2.2.4 then downgrade from v2.2.4 to v2.2.3.
Now,  Zettlr v2.2.3 no longer opens the respective file or folder but instead the parent directory of the edited Markdown file.
This used to work perfectly in v2.2.3 before upgrading to v2.2.4 and then downgrading to v2.2.3.

### Zettlr Version

Stable (but an older version)

### Specify version

v2.2.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

openSUSE Leap 15.3 x86_64

**Comment by sebzeter** [comment]
A new upgrade from v2.2.3 to v2.2.4 solves the problem but it's not an option because of bug #3295.  So will stay with v2.2.3 for now.

**Comment by nathanlesage** [comment]
Just to keep the tracker clean let us close this bug report (since it is indeed fixed in 2.2.4), so that we can focus on the bugs of 2.2.4 instead.
