### ISSUE TITLE
Add Tree Navigation for Tags

### ISSUE THREAD

**Issue by heussd** [Zettlr/Zettlr#33]
I would love to see a navigation area for tags in the tree view. It could include all tags used in all files in the current root folder.

Each tag could contain each other tag it is combined with. So for example:

`File1.md tagged with t1, t2`
`File2.md tagged with t2`
`File3.md tagged with t2, t3`

The tag tree could look like this:

`|- t1`
`|   |-t2`
`|-t2`
`|   |-t1`
`|   |-t3`
`|-t3`
`|   |-t2`

Clicking on a tag could issue a corresponding search for this tag / tag combination.

This is tremendously useful to structure information collected with the Zettelkasten methodology.

**Comment by nathanlesage** [comment]
Uh, this is a nice idea. And it also reminds me that I wanted to enable triggering a search by clicking on the tags in the preview pane, which I totally forgot the last versions 🙄

It's on my list!

**Comment by nathanlesage** [comment]
Heya, after these months and a lot of stuff happening with Zettlr, I've realised I'm not able to integrate this into the app, so I'm closing this issue now!
