### ISSUE TITLE
Tags are extracted from code

### ISSUE THREAD

**Issue by narnaud** [Zettlr/Zettlr#331]
## Description
Tags are extracted from any word starting with a `#`, but it should ignore those in code.

## Reproducing
1. Create a new file
2. Paste this:
```
    ```cpp
    #include <vector>
    ```
```
3. THe file has a tag name `include`

## Expected behaviour
No tags for this file

## Platform
 - Windows 10
 - Version 1.4.1

**Comment by nathanlesage** [comment]
Thanks for reporting, I'll see into it!

**Comment by nathanlesage** [comment]
Done!
