### ISSUE TITLE
[Bug] Zettlr blocks automatically hidden taskbar on Windows

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#3311]
### Description

I have hidden the taskbar to de-clutter my screen. Since the last update, when Zettlr is maximized, it blocks the taskbar from appearing. When touching the bottom of the screen, Zettlr shows a resizer mouse instead. 

### Reproducing

Happens constantly. I can provide more info if necessary!

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 10

**Comment by nathanlesage** [comment]
Did this really only occur in 2.2.4? Or are there previous versions that expose this behavior? It would be very kind if you could check this so that we have something to work with!

**Comment by halloichbingunnar** [comment]
Thanks for the quick replay! I'm using Zettlr on a daily basis and never experienced it before – it started after updating today, so I guess it's limited to 2.2.4...

**Comment by halloichbingunnar** [comment]
Update: Just updated to 2.24 on my second device (win11) and checked behaviour before (taskbar appearing normally) and after update (not appearing)

**Comment by nathanlesage** [comment]
Okay, so it's likely due to an update in Electron 17. Let me quickly check their changelogs … no, nothing in there :(

**Comment by nathanlesage** [comment]
Does this still happen with the most recent beta release?

**Comment by halloichbingunnar** [comment]
No, this one is solved! 👍🏻
