### ISSUE TITLE
[Bug] Word count does not work when line starts with 4 or more spaces

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#3312]
### Description

I use nested lists quite a lot.  I've noticed that the word count for files where I've got nested lists is always lower than it feels like it should be.  With a bit of experimentation I found that Zettlr ignores words in any line that starts with 4 or more spaces.

I can see this is desirable if you're using 4 spaces to start lines in code blocks, but for a list the words should still count!

### Reproducing

In a new file make yourself a list with nesting, e.g.

* a list item
    * another list item
    * yet another one

Look at the word count, this will display 3 words (the number in the non-nested list item).

If you highlight the words in one of the nested list items the "selected" number will be accurate but if you highlight the whole line including the initial whitespace the "selected" number will be 0.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by nathanlesage** [comment]
> if you're using 4 spaces to start lines in code blocks,

👀 🙈

**Comment by EdgarTang** [comment]
Hi, I find that the word count function will remove all the text starting with a tab like the code line before it counts words. So I remove that code and fix this problem. I have already submitted my pull request https://github.com/Zettlr/Zettlr/pull/3349.
If you want to fix this question quickly, just remove following code line by yourself.
location: source/common/util/count-words.ts line 35
  content = content.replace(codeRE, '') // Code blocks

**Comment by EdgarTang** [comment]
> Hi, I find that the word count function will remove all the text starting with a tab like the code line before it counts words. So I remove that code and fix this problem. I have already submitted my pull request #3349. If you want to fix this question quickly, just remove following code line by yourself. location: source/common/util/count-words.ts line 35 content = content.replace(codeRE, '') // Code blocks

Sorry for the reckless pull request, I have closed it.

The word count bug is because text starting with 4 spaces and a tab will be recognized as code and ignored. (Ignored parts include <~~~>, <4space>, <tab> and <```>, which are the symbols used to mark code in markdown)

Whether Zettlr should count the words in this section is not up to me.

Zettlr can correctly distinguish code blocks from ordinary text blocks. So word count bugs should probably be fixed as well.
![WeChatd7aa77c20cca329cbf5a3d9593ffaf60](https://user-images.githubusercontent.com/48198383/164272628-7d2fec20-b429-4cf6-8999-a5b4df845a73.png)


I will try this fix again in my spare time

**Comment by nathanlesage** [comment]
Don't ask me why I just today stumbled upon this bug, but it literally bugged me and so I fixed it.
