### ISSUE TITLE
[Bug] can not localize menu items in File menu of macOS/Windows

### ISSUE THREAD

**Issue by juggernautjp** [Zettlr/Zettlr#3319]
### Description

(non-critical Bug) 
Both "Previous file" and "Next file" menu items, that are included in "File" menu, do not exist in Zettlr Translation, 
so we can not translate them.

### Reproducing

1. Input `Ctrl + ,` key, then select "Japanese" for language in the Preference Dialog.
2. Restart Zettlr.
3. Select "ファイル" of menubar.
4. Confirm "Previous file" and "Next file" in the pulldown menu. (see. the figure attached)

Also, you can not search the translation keys, `menu.previous_file` and `menu.next_file`, in [Zettlr Translation](https://translate.zettlr.com/).

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

### Additional Information

<img width="280" alt="image" src="https://user-images.githubusercontent.com/56490448/158045994-bc4f10d1-067d-4f17-b86c-347fd5b392f1.png">

### How to fix this issue

1. Add the following {key: strings} pairs to [Zettlr Translation](https://translate.zettlr.com/).

| Translation key      | en-US.json    |
|:---------------------|:--------------|
| `menu.previous_file` | Previous file |
| `menu.next_file`     | Next file     |

2. Modify the source/app/service-providers/menu/menu.{darwin, win32}.ts files as follows:

- menu.darwin.ts

| line number | before modification | after modification |
|:------------|:--------------------|:-------------------|
| 205         |  label: 'Previous file', | label: trans('menu.previous_file'), |
| 216         |  label: 'Next file', | label: trans('menu.next_file'), |

- menu.win32.ts

| line number | before modification | after modification |
|:------------|:--------------------|:-------------------|
| 173         |  label: 'Previous file', | label: trans('menu.previous_file'), |
| 184         |  label: 'Next file', | label: trans('menu.next_file'), |

**Comment by nathanlesage** [comment]
My bad, I just forgot to make them translatable. The items are now available in Zettlr Translate! Thanks for spotting this.
