### ISSUE TITLE
Fatal error on debian buster

### ISSUE THREAD

**Issue by yennor** [Zettlr/Zettlr#332]
## Description
I've just installed the deb package for zettler 1.4.1. When trying to start it, following error appears

> [5379:0918/092327.579838:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Zettlr/chrome-sandbox is owned by root and has mode 4755.
[1]    5379 trace trap  zettlr

## Reproducing
Install the deb package on debian buster and try to start the program

## Platform
 - OS: Debian Linux
 - OS Version Buster (stable)
 - Zettlr Version 1.4.1

## Additional information
The permissions of the file are:
-rwxr-xr-x
After setting them to 4755 zettlr starts up.

**Comment by nathanlesage** [comment]
Ah well, the guys over at electron-builder have said that it would work now, but apparently not so …

From 1.4.2, I'll have the patch running again to prevent this! Thanks for reporting!
