### ISSUE TITLE
[Enhancement] Examples of CSS selectors

### ISSUE THREAD

**Issue by tio-trom** [Zettlr/Zettlr#3320]
### Description

Show us please some CSS selectors so that we know how to tweak the thheme.

### Proposed Changes

In the Custom CSS box showcase several CSS selectors.

### Caveats

I do not see any.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Arch

**Comment by kyaso** [comment]
Maybe this helps you: https://docs.zettlr.com/en/core/custom-css/

**Comment by tio-trom** [comment]
Ah yes that's perfect. Thanks!
