### ISSUE TITLE
Removed files are not removed from virtual folder.

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#333]
1. Create a file in folder A and but it in virtual folder B.

Goal : move the file to another zettlr project.

2. It's not possible to move the file from a virtual folder not to easily find it in its "true" folder from the virtual one.

3. Move it from folder A to another project.

4. The file is still in virtual folder B with "wrong date provided" (and is displayed as empty)

**Comment by nathanlesage** [comment]
"wrong date provided" is the fallback Vue uses if the modtime is undefined, that is not set. I knew there were problems with virtual files, I'll look into it.

**Comment by nathanlesage** [comment]
Closing as virtual directories are gone in 1.7 in favour of other options.
