### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kcarfyk** [Zettlr/Zettlr#3330]
### Description

I get the Mac OS X error every time I open Zettlr: "Zettlr quit unexpectedly. Click Report to see more detailed information and send a report to Apple." Nothing unusual or wrong occurred in the prior use of the program. 

### Reproducing

The error notice appears every time I open the program. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Catalina 10.15.7

**Comment by nathanlesage** [comment]
Would you mind sharing the results of that error message with us?

**Comment by nathanlesage** [comment]
Closing in favor of #3364
