### ISSUE TITLE
Hide hidden file in file manager [Bug] 

### ISSUE THREAD

**Issue by CommunyAS** [Zettlr/Zettlr#3341]
### Description

On my MacBook hidden files are not displayed in the file manager. On my Win workstation they are and I don't find a way to hide them. I tried via the Windows system setting, no change.

How can I hide them in file manager on Win?

### Reproducing

Just open a directory or workspace.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Could you please specify some example filenames for those hidden files?

As a note: Zettlr does not respect the "hidden" attribute that Windows assigns to "hide" files because this is not implemented in the underlying engine. We treat files as hidden that begin with a dot as it is common on every non-Windows system.

**Comment by CommunyAS** [comment]
I only have this issue in my Win workstation, not on my Mac, as already noted.
See attached screenshot
![Screenshot](https://user-images.githubusercontent.com/74900017/160107854-74ec5635-4257-4fbf-b5f5-718191f85a64.PNG)
.

**Comment by CommunyAS** [comment]
additionally, I just realized that the TOC is not working correctly - the chapter numbering disappeared today (restarting the PC did not fix it)
![screenshot2](https://user-images.githubusercontent.com/74900017/160108746-8d9c1469-efbc-4851-b318-ea9620e3864f.PNG)
y

**Comment by nathanlesage** [comment]
> I only have this issue in my Win workstation, not on my Mac, as already noted.

I was asking because Windows has these `thumbs.db` files which do not start with a dot.

It's weird indeed that Windows shows them. But there is a chance that all of this boils down to a few more checks in the `fs.readdir` handler.
