### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sushant-gupta7** [Zettlr/Zettlr#3342]
### Description

If making a list in zettlr,

 -[ ]SOMETHING NEW
 -[ ]TEST FEATURE

if you check or uncheck any of the checkboxes it won't do anything since there is no space between the checkbox and the next word after it. It will just select or unselect the checkbox.

If making a list in zettlr,

 -[ ] SOMETHING NEW
 -[ ] TEST FEATURE

In this case, space is given between the list checkbox and the next word after it ([] something or [] test). In this case, if we select the list checkbox it will select or unselect the whole adjacent line with the checkbox and put a line on the center of it.
![Screenshot 2022-03-25 at 11 41 44 AM](https://user-images.githubusercontent.com/45813579/160032695-e2334d8a-9bba-4079-8491-24b5d82aa86c.png)

### Reproducing

Just make a list and follow the steps described in description with image

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Mojave

**Comment by nathanlesage** [comment]
This is intended behavior. Please always use spaces to delimit the checkbox-part from the list sign and the text. Use the task-list shortcut `Cmd/Ctrl+T` to save time with this.

```
Correct:

- [ ] Some item
* [ ] Another item
+ [ ] A last item

Wrong:

-[]Some item
- [ ]Some item
-[ ] Some item
-[ ]Some item
```
