### ISSUE TITLE
Cannot use command bar in VIM mode

### ISSUE THREAD

**Issue by gnailuy** [Zettlr/Zettlr#3346]
Hi,

Just found this awesome editor from Tomas Vik's blog. Love it!!

I found a little problem in the VIM mode, that the command bar is not shown properly. I tried to debug it and seems it is hidden below the editor area.

In the screenshot below, I disabled the `margin-bottom: 0px;` for class `.CodeMirror-scroll`, and the command bar appeared. (The `:w` on the lower-left corner of the editor area, the class name is `.CodeMirror-dialog-bottom`.)

<img width="1332" alt="Screen Shot 2022-03-26 at 1 13 01 AM" src="https://user-images.githubusercontent.com/1468648/160171999-2cf3ac8d-b795-4ad6-a511-4f5bb01da3d2.png">

I see in the [source code](https://github.com/Zettlr/Zettlr/blob/3c6aea9c4662892f97eac6ba25029f8bd16920f5/source/win-main/MainEditor.vue#L1072) that these two CSS rules were added intentionally for some calculations for the table editor. So is there a better fix for this issue?

Thanks a lot!

**Comment by nathanlesage** [comment]
Huh, I have never seen this. (But I'm in the "Eww, vim" camp.)

I mean, sounds like a few lines of CSS should fix that — if anyone wants to get into that, feel free!

**Comment by gnailuy** [comment]
Thanks for the quick fix. Improved my CSS skill from learning your solution 😄
