### ISSUE TITLE
[Enhancement] Pin Tabs

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#3348]
### Description

There are tabs that are more prominent than others. Its not uncommon that I copy fragments form several text files into one file.

Ok here is are real word examples why this would be useful for me:

1.) I navigate through my zettelkasten follow tags or links to gather information. This new Information I need for creation. IMHO this is the great benefit of a zettelkasten: It helps me to recreate content from my zettelkasten archive. 
2.) I often cluster (https://k12.thoughtfullearning.com/blogpost/dr-ricos-magic-key-clustering) for generating new, fresh ideas. this task i do almost every day. (the clusters shares all the same tag). After several Weeks I read all clusters and copy the Idea that i still find fresh in  a new file and create something new (e.g. a peom, a character for a story)

This tool already helps me to be creative, to focus on that what matters (nobody cares about formatting, spellchecking and other distraction stuff in the early stages of creation). This enhancement would lift up zettlr to a new level. 

### Proposed Changes

Like in the Webbrowser: right click on the tab, in the context menu "Pin Tab" (or unpin, if its already pinned)

### Caveats

No. You don't need to use it if you dont like it.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro Linux, i3, packages up to date.

**Comment by nathanlesage** [comment]
Thanks for opening the issue; it's one of the things that I already have on my roadmap for future versions.
