### ISSUE TITLE
[Bug] Export pdf on Linux, xelatex not found

### ISSUE THREAD

**Issue by moedn** [Zettlr/Zettlr#3351]
### Description

Hey there, long time no see :) Thanks for this amazing piece of software; I keep promoting Markdown (& Zettlr) at my institute; markdown is the future :)

When I export using the option `PDF (latex)` I get the following error: 

```
An error occurred on export: xelatex not found. Please select a different --pdf-engine or install xelatex

xelatex not found. Please select a different --pdf-engine or install xelatex
```

However, I do have xelatex (and I'm running a pandoc version higher than 2.x.x)

### Reproducing

1. Open a markdown document
2. Export to `PDF (LaTeX)`
3. Get the error :)

Package Version:

- Zettlr 2.2.4
- XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020)
- pandoc 2.9.2.1 (Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5)

### Zettlr Version

Stable (most recent version)

### Specify version

 v2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 34

### Additional Information

possibly related to https://github.com/Zettlr/Zettlr/issues/251

**Comment by nathanlesage** [comment]
Could you please confirm whether or not you use the `flathub` release of Zettlr? That one is very restricted and has no access to the TeX binaries by default (i.e. doesn't find them).

Additionally, could you please confirm whether you use the built-in Pandoc or the external one? The built one in is already at `2.17` or something-ish, albeit I doubt anything broke in between.

**Comment by moedn** [comment]
1. :heavy_check_mark: I'm using the flathub release, yes
2. pandoc version
  - I have pandoc installed since I use it independently from Zettlr (v2.9.2.1)
  - How can I check the built-in pandoc version? The `Environment Variables` under `Debug Information` say `PANDOC_PATH: /app/zettlr/resources/pandoc`, however there is no such directory on my system; there is `/opt/zettlr/resources/pandoc/app`, but that's empty

**Comment by moedn** [comment]
whooohooo, works for me, thanks!

However, +5GB to be able to convert into PDF from the GUI instead of running pandoc seems a little exaggerated ^^

Anyways, my problem is solved. Should we close this issue or are there any next steps attached to this? (updating the documentation etc.)

**Comment by nathanlesage** [comment]
Yes I think this issue is solved!
