### ISSUE TITLE
[Bug] Crash while installing Portuguese pt-PT dictionary is stalls the program forcing it to exit.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [Zettlr/Zettlr#3354]
### Description

I have tried multiple times to install the pt-PT Portuguese dictionary and from the URL that you kindly  provide in the manual, the Portuguese language dictionary is your use case in the manual.

GitHub wooorm - dictionaries
https://github.com/wooorm/dictionaries/tree/main/dictionaries/pt-PT

It appears in the list of dictionaries in the configuration window, but when I select it in stalls the Zettlr program and forces me to exit the program. 

I tried also a different version of the dictionary directly from the pt-PT project at uminho from the maintainers of the dictionary and the behaviour is the same.

### Reproducing

Download the pt-PT dictionary from the github site:

GitHub wooorm - dictionaries
https://github.com/wooorm/dictionaries/tree/main/dictionaries/pt-PT

menu -> import dictionary

Create directory pt-PT
copy files:
pt-PT.dic
pt-PT.aff

then select the configurations window and the dictionary pt-PT appears correctly.
Select the dictionary and exit the window.

A window will appear forcing you to exit because the Zettlr program will stall. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

Thank you for all the work!

**Comment by afrigeri** [comment]
Reporting same behavior described by @joaocarvalhoopen, with the very same procedure but with it-IT and OSX 12.5.1 and Zettlr 2.3.0

**Comment by nathanlesage** [comment]
The portuguese dictionary doesn't work, and won't work until we find a replacement for nspell, which manages spell checking for Zettlr.

**Comment by mgirdwood7** [comment]
having a similar issue with a hungarian dictionary - Zettlr crashes as soon as I try to select it for spellchecking. v2.3.0
