### ISSUE TITLE
[Bug] Unable to View Files/Folders When Opening Workspace

### ISSUE THREAD

**Issue by bradonomics** [Zettlr/Zettlr#3356]
### Description

When trying to open a new workspace, I am unable to see the file list. There are no words, only boxes. Here is a screenshot:
![](https://user-images.githubusercontent.com/5723185/160654201-c4419e95-9d68-47bf-b723-0d23958b86d4.jpg)

### Reproducing

This is a new install of Zettlr using [Flathub](https://flathub.org/apps/details/com.zettlr.Zettlr). I made no modifications and changed no settings.

Note: This does not happen when using the .deb file on the downloads page.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.3

### Additional Information

I am using Cinnamon desktop, version 5.2.7. I'm on kernel version 5.4.0.

**Comment by nathanlesage** [comment]
These boxes are called "tofu" and indicate that whatever font you have does not contain the required glyph. Since you probably have no font that has no ASCII characters, though, I would suspect it to be a bug.

@Lunarequest This is potentially something you have more insight into, right?

**Comment by Lunarequest** [comment]
By any chance @bradonomics are you using CJK chars?

**Comment by Lunarequest** [comment]
Could you send a list of folder names?

**Comment by bradonomics** [comment]
Are you asking what I have in my home directory? It's the standard stuff. Desktop, Documents, Downloads, etc.

**Comment by Lunarequest** [comment]
I have a feeling this is a flatpak bug that has already been fixed. Maybe mint's packages are out of date?

**Comment by nathanlesage** [comment]
I'm closing this issue because it seems to … be fixed …?
