### ISSUE TITLE
[Enhancement] - Usability UX – In find inside the editor, the previous search term should already be selected to clear automatically when when you start typing.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [Zettlr/Zettlr#3360]
### Description

Usability UX Enhancement - In find inside the editor, the previous search term should already be selected to clear automatically when when you start typing. If you want to search a modified version of the previous search term you just have to press the arrow keys left or right to deselect the term and modify the search term.

This will make search much faster!

### Proposed Changes

-The previous search term should already be selected.

### Caveats

No caveats.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Linux Ubuntu 20.04

**Comment by nathanlesage** [comment]
Fixed in one of today's commits (couldn't find this issue back then because GH search is weird)
