### ISSUE TITLE
[Bug] - The performance with a big note with done checkbox's is really bad even when the checkbox show feature is turned off, because text crossing isn’t disabled.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [Zettlr/Zettlr#3361]
### Description

The checkbox "- [x] Task 1" will be crossed even if you choose to not show the checkbox in the configuration windows. For for big files, this makes the editing and cursor movement incredible slow and very difficult to do.
To the point that I had to change my done check boxes from “- [X] Task 1” to “V – Task 1” so that the cross didn’t occur, and in that case the performance even with a really big file was good.

If in the Config, the show parameter for the checkbox is not set, the crossing should not occur or appear, so that the performance will not be negatively hit for big files. When you set the show Checkbox's is when you should also see the crossing functionality on the editor's view. 

### Reproducing

Case 1 – Small file

do:
```
- [x] Task 1
- [x] Task 3
- [ ] Task 3

```
 
And go to the config and disable in the show tab the checkbox’s.

The crossing will still appear and it shouldn’t.

Case 2 – Big file, with many done tasks

```

- [x] Task 1 long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text

- [x] Task 3 long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text

- [x] Task 1 long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text

- [x] Task 3 long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text

…… do this for 50 tasks to 200 tasks.


- [x] Task 50 long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text

- [ ] Task 51

```

It will be incredible slow to the point that you almost can’t edit the text.

And go to the config and disable in the show tab the checkbox’s.

The crossing will still appear and it shouldn’t.

Test again and it will be really fast to edit.

In my case I tested with a file that maybe had 50 to 100 checkbox crossing with the checkbox option disabled in the Config show window, and with maybe 500 lines of text with several Heading and several list points. But I isolated the problem to the crossing while the checkbox’s are disabled.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Ubuntu 20.04

**Comment by nathanlesage** [comment]
The CSS you referenced only affects the checkboxes themselves, but not the text crossing. The fact that that is still running even if you disable "render task lists" is that it's being applied by a different plugin.
