### ISSUE TITLE
Open workspace or file dialogue unable to access full file system in flatpak version

### ISSUE THREAD

**Issue by jchalifour** [Zettlr/Zettlr#3366]
### Description

Using the Zettlr flatpak on Linux does not enable the same access to my file/folder directory structure as other ways of installing Zettlr do (e.g. via a deb, AUR, etc. installation). 

I had been using Zettlr on Manjaro as well as Ubuntu (both with the Gnome desktop). When it was installed through the distribution's native package or the AppImage, there is no problem. However, I recently tried installing the flatpak instead, thinking maybe I'd try switching. When you go to open a workspace in the flatpak version it will only show you "Documents" within your home directory. Any other directory in that location will not appear in the dialogue so actually I cannot access my Zettlr notes, which I keep outside of the Documents folder.

Other flatpaks that I have installed do not have this issue but I have seen it happen occasionally with a flatpak (can't recall another example at the moment though). I'm not sure what other info I can provide about this but I'm attaching two screenshots to show the difference.
![zettlr-deb-screenshot_20220401](https://user-images.githubusercontent.com/5346551/161315218-ebfc48da-7a12-46fb-adf5-17f63412ad48.png)
![zettlr-flatpak-screenshot_20220401](https://user-images.githubusercontent.com/5346551/161315228-fef47682-4f2d-448e-bb07-fd1b11fa90db.png)
 

### Reproducing

Install the flatpak of Zettlr
Go to the File menu
Click Open Workspace...

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro (Gnome, testing current) and Ubuntu (22.04)

**Comment by nathanlesage** [comment]
As far as I know that was kind of a deliberate decision by @Lunarequest when they added Zettlr to the flathub. I have no idea about the culture with using flatpaks, so I'd like to stay out of this discussion …

Also, I'm unsure whether this issue wouldn't make more sense in this repository here: https://github.com/flathub/com.zettlr.Zettlr

**Comment by Lunarequest** [comment]
giving access to say `home` or `host` is a security issue hence it not being allowed for most flatpaks. The reason it is boils down to a program running in home can edit a shell init file to run malicious code. We tend to avoid giving over reach permission like these for those reasons. If you do require them flatseal is a great tool for modifying permission via GUI
https://flathub.org/apps/details/com.github.tchx84.Flatseal

**Comment by jchalifour** [comment]
Ah-ha, I see now. Thanks for the tip about Flatseal, I was not aware of it and just tried it out, which took care of my issue and will probably be useful for other cases.
