### ISSUE TITLE
"Error starting FSAL" [bug]

### ISSUE THREAD

**Issue by corrugatedbox** [Zettlr/Zettlr#3369]
### Description

Hi there!

I have encountered an issue after updating from Zettlr 1.8.9 directly to 2.2.4
After downloading and installing the new version, Zettlr fails to load and instead crashes with the following error message "Error starting FSAL. Could not start FSAL: Cannot read properties of undefined (reading 'startsWith')" 

I have restarted my computer and performed several re-installs but this failed to resolve the issue. I finally tried re-installing the older version (1.8.9) to see if that would resolve it, but that version also fails to run now, too. 

I wonder if the issue is that Zettlr is trying to load a file path/directory that in some way doesn't meet the current standards? 
I have observed that sometimes the new version of Zettler loads just for a few seconds and I see the same directory I had loaded as when I was running 1.8.9, before I get the crash message again, and the program shuts down. 

Any possible solutions to this?

### Reproducing

Install Zettlr 2.2.4 directly replacing an older install of 1.8.9
Try to access .md files made in the older version of Zettlr, or simply to try to start the program 
 

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I'm pretty sure removing the config.json should fix this. Could you test that out? Skipping so many versions is definitely a strain on the configuration provider, and I'd argue not a bug. But as I said, removing the config should solve it!

**Comment by corrugatedbox** [comment]
Thanks for getting back to me so quickly!  

I will be happy to try this out-- only I can't locate the config.json. Its not in Zettlr program files, nor do I see any such file in any more my Zettlr workspace folders. Where should I be looking?

**Comment by nathanlesage** [comment]
> I will be happy to try this out-- only I can't locate the config.json. 

It's in `C:\Users\<your username>\AppData\Roaming\zettlr`

**Comment by corrugatedbox** [comment]
Thank you!
Yes, I deleted the config.json and now Zettlr is working just fine.

**Comment by nathanlesage** [comment]
Perfect.
