### ISSUE TITLE
Link to heading ID not working

### ISSUE THREAD

**Issue by guga14** [Zettlr/Zettlr#3371]
### Description

Trying to proceed as https://github.com/Zettlr/Zettlr/discussions/2410#discussioncomment-1346510 returns nothing. 

### Reproducing

1. Inside a note, enter \[Some text](#headerID)
2. Ctrl+LClick the link
3. Nothing happens

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by guga14** [comment]
It apparently has something to do with characters like "á" and "ê". Still can't fix it.

**Comment by leo-hstone** [comment]
Works fine on my system (also Win 10, latest version)

Can you provide an example file where it does not work in your case?
