### ISSUE TITLE
Header semantics not correct in MS Word output

### ISSUE THREAD

**Issue by GrazingScientist** [Zettlr/Zettlr#3379]
### Description

The header semantics in a MS Word output is incorrect. A header 1 becomes a header 2. The header hierarchy however remains correct.

### Reproducing

When having a simple Zettlr document like 

```
# My Header 1
Lorem Ipsum

## My Header 2
Lorem Ipsum
```
and exporting it to Word, the header 1 is presented as header 2. However, the header hierarchy remains correct (the header 2 element is a header 3 element in the output).

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

I am using the AppImage.

**Comment by nathanlesage** [comment]
This is not a bug, this is simply a defaults setting. Specifically, this one:

```yaml
shift-heading-level-by: 1
```

Set this to 0 or remove the line completely to prevent this behavior. For more, please refer to [this section in the Pandoc manual](https://pandoc.org/MANUAL.html#reader-options).

**Comment by GrazingScientist** [comment]
Thanks, @nathanlesage . As a semantic text person, this behavior drives me crazy. But good to know. 😄
