### ISSUE TITLE
Sidebar Toggle not working

### ISSUE THREAD

**Issue by MaroGM** [Zettlr/Zettlr#338]
## Description
**Toggle Sidebar** does not seem to work (neither via menu interaction nor via keyboard shortcut. An error is logged in the console every time toggle sidebar is selected. Same behaviour even if all directories are closed and the sidebar is empty. Restart / reinstall does not change behaviour.

**Screenshots**
<img width="1076" alt="Screenshot 2019-09-23 at 15 56 51" src="https://user-images.githubusercontent.com/8853839/65432484-8ba76f00-de1b-11e9-9aac-8ee0d5d9aed7.png">

## Platform
 - OS: [Mac OS]
 - OS Version [10.14.6]
 - Zettlr Version [1.4.1]

**Comment by nathanlesage** [comment]
Okay, problem line is:

https://github.com/Zettlr/Zettlr/blob/master/source/renderer/zettlr-rendereripc.js#L447

This code shouldn't be there. I'll get to it! But the arrow toggle does indeed work, so the app should work with the arrow toggle until I find time to fix this.

**Comment by MaroGM** [comment]
Ah, I think then I also misunderstood the functionality of the toggle. I thought it would be used to hide/show the sidebar - not switching between Folder list / Content view. At least that's when an arrow appears for me.

**Comment by nathanlesage** [comment]
Jep, if you want to hide the sidebar completely, use the "distraction free" mode, because it'll resize the editor to use the full width of the app! :)

**Comment by nathanlesage** [comment]
There you go! :)
