### ISSUE TITLE
Vim command line remains not visible

### ISSUE THREAD

**Issue by sebzeter** [Zettlr/Zettlr#3383]
### Description

Although v2.2.5 changelog says "Make Vim command line visible",  no command line is displayed even after enabling Vim input mode in the editor preferences.

### Reproducing

- Open Zettlr
- Enable Vim input mode in the editor preferences
- The command line remains not visible

### Zettlr Version

Stable (most recent version)

### Specify version

v2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

openSUSE Leap 15.3 x86_64

**Comment by kyaso** [comment]
AFAIK, the command line only appears when you enter command mode using `:`.

**Comment by sebzeter** [comment]
@kyaso : indeed, that works! Thanks for the reply and sorry for the noise.
