### ISSUE TITLE
HTML export - override toc values in YAML frontmatter

### ISSUE THREAD

**Issue by Viguro79** [Zettlr/Zettlr#3385]
### Description

The toc-title is correctly named in the final html document (New TOC title name).
But the toc-depth is still 2, will it should be 4.

### Reproducing

Set default HTML export assets with those lines:
```
toc: true
toc-depth: 2
```

Set theYAML frontmatter like:
```
title: "My title"
toc: true
toc-title: "New TOC title name"
toc-depth: 4
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I noticed that recently myself, and it appears that Pandoc is overriding some YAML frontmatter properties with defaults properties, instead of the other way round. Maybe @tarleb has some insight …?

**Comment by tarleb** [comment]
I'm kind of surprised that this seemed to work at some point. Pandoc uses only the *toc* and *toc-depth* settings it gets from the command line or default files; values passed via metadata may become available in the template, but the TOC has already been constructed at that point.

In summary: I doubt that there's a way to make it work (and we probably shouldn't).

**Comment by nathanlesage** [comment]
Thanks for your quick reply! So basically the ToC will be constructed and THEN the YAML frontmatter will be considered?

Since this is not the first instance where something like that comes up, I wonder whether I should just by default dump the YAML frontmatter into the defaults file (i.e. the `metadata` prop) on every export? This might solve a lot of problems, or do I overlook some elephant in the room …?

**Comment by tarleb** [comment]
One problem would be that metadata entries in a defaults file cannot contain any markup, which would give bad results for fields like `title`.  I think it also wouldn't help in this case, as the document metadata-value is ignored when constructing the TOC -- only the command-line options (and their corresponding defaults-file settings) are considered.

**Comment by tarleb** [comment]
I don't have a good solution for this. The only reasonable approach could be to write a [custom writer](https://pandoc.org/custom-writer) that checks for these metadata fields and overrides any other settings. Something like

``` lua
function Writer (doc, opts)
  if doc.meta['toc-depth'] then
    opts.toc_depth = meta['toc-depth']
  end
  return pandoc.write(doc, 'html', opts)
end
```

**Comment by nathanlesage** [comment]
Sounds like some Lua action is incoming … Pandoc settings are an art! But thanks already for the incredible help in understanding Pandoc, this is really awesome! :)

**Comment by tarleb** [comment]
> Pandoc settings are an art

Yep. So much stuff that I'm still looking up, sometimes even though I wrote it.

Sounds like we could do some pair programming next time we have a beer :)

**Comment by nathanlesage** [comment]
Uhh, absolutely!

**Comment by nathanlesage** [comment]
Closing this issue as the behavior is possible with correct Pandoc switches.
