### ISSUE TITLE
HTML export # toc-title value not recognized in default assets

### ISSUE THREAD

**Issue by Viguro79** [Zettlr/Zettlr#3386]
### Description

When exporting to html document, I get the following error message:
```
Error parsing C:\Users\VINCEN~1\AppData\Local\Temp\defaults.yml line 21 column 0:
Unknown option "toc-title"
```

### Reproducing

Add a `toc-title` value in the default html export asset and try to export to html a .md document.
(Adding a `toc-title` value to the frontmatter yaml at the beginning of the document is working as intended.)

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 8

**Comment by nathanlesage** [comment]
Quick update: It's indeed:

```yaml
toc: true
toc-depth: 2 # Any heading level
variables:
  toc-title: Table of Contents
```

With this it works, at least in the current betas/nightlies.
