### ISSUE TITLE
Highlight results from global search in the main editor text

### ISSUE THREAD

**Issue by IgnacioHeredia** [Zettlr/Zettlr#3388]
### Description

Hi,

I just freshly installed 2.2.5. From reading the changelog I see:
```
* Highlight results from global search in the main editor text
```
However I still don't see the results being highlighted in the main text. Searching in the Main Editor Search does highlight results.

Is this the intended behaviour or am I missing something?

Thanks!

Ignacio

Global Search:
![image](https://user-images.githubusercontent.com/16413205/162730614-2a15b0f3-4ea1-44ea-a745-c93530e143db.png)

Main Editor Search:
![image](https://user-images.githubusercontent.com/16413205/162730673-1e358508-682a-4c53-986f-b15a0973b423.png)

### Reproducing

Just search for the same word in the Global Search and in the Main Editor Search.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

Installed with deb package.

**Comment by mousetrappling** [comment]
I have found it doesn't render the highlighting till you change to a different tab and back again.

**Comment by nathanlesage** [comment]
Works with the new CM6 implementation.
