### ISSUE TITLE
False rendering of inserted link when typing a minus in the line directly after

### ISSUE THREAD

**Issue by captainsky25** [Zettlr/Zettlr#3390]
### Description

I inserted a Link in the form [...](...). When I hit enter and start the next line with a minus sign "-", the link will be rendered, as if it was a heading. This wrong rendering persists, when a space is following the minus and disappears after starting to write the first letter of a word or phrase.
When I keep one line free after the link, there is no wrong rendering.

### Reproducing

Follow the Description while using Windows 11.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
This is intended behavior: Anything followed by a line containing only spaces and dashes will be considered a heading level 2 in accordance with the Markdown specifications. To avoid this short "wrong" behavior, consider padding the list with an empty line to also make it visually clear that it is a new paragraph.
