### ISSUE TITLE
Writing Statistics Date Not Filling

### ISSUE THREAD

**Issue by GummyDonut** [Zettlr/Zettlr#3396]
### Description

After having written content for the day, and then restarting zettlr it seems to fail to register the day you have written an entry.
This start occurring after the 2.2.5 update.
![CaptureDay](https://user-images.githubusercontent.com/5553615/163690449-0956aa90-197b-4dd8-a165-60ea544e4734.PNG)
Wrote stuff for today on April 16 of 2022

![CaptureStatistics](https://user-images.githubusercontent.com/5553615/163690452-c81390cb-635c-495c-be14-428b6d2cfbc4.PNG)
Restarted Zettlr and the app fails to punch in the date of writing for april 16th of 2022. Circled in blue

### Reproducing

1. Write Some notes.
2. Confirm that you have written something by click the chart icon in the top left.
3. Click the "more statistics..." button
4. Notice that the date is not highlighting the colored average for that day.
5. Tried restarting zettlr to see if it updates only restart
6. Click the chart icon again in the top left, clicked "more statistics" again. Noticed that it has still not updated

This has been occurring since version 2.2.5 update. Missed those days.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

Other (please specify below)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

Update was done through zettlr's update tool. Gave me an exe and ran that.

**Comment by nathanlesage** [comment]
The calendar will only color days on which you have written at least the average of the last ... 30 (?) days. Therefore, if you have written less than that, the day won't be colored. Can you confirm this?

**Comment by GummyDonut** [comment]
> The calendar will only color days on which you have written at least the average of the last ... 30 (?) days. Therefore, if you have written less than that, the day won't be colored. Can you confirm this?

That seems to be the case, just manually typed stuff random stuff. Typed close to my average and now it is registered in the calendar thanks.

**Comment by GummyDonut** [comment]
Side question though. How does the counting of words work in zettlr there seems to be quite a delay?
![CaptureWord](https://user-images.githubusercontent.com/5553615/163716876-bf255c70-e817-4f38-82f8-80813fa46967.PNG)
I typed 268 words manually to run the above test. But it only took 211 words as seen below?
![CaptureStat](https://user-images.githubusercontent.com/5553615/163716878-4d7ffc6a-47be-4849-8205-08f7e0aa4693.PNG)

**Comment by nathanlesage** [comment]
Okay, good! With regard to the delay: if you paste in content, it is not counted towards the writing goal (since the idea is to write something yourself; it is meant as a motivational piece). This explains the gap between the counts!

Closing as solved.
