### ISSUE TITLE
[Bug] Massive lags when checking for related files

### ISSUE THREAD

**Issue by therealjeybe** [Zettlr/Zettlr#3399]
### Description

When Zettlr is checking for related files in a file that actually has many related files (in my case >1000) it massively lags. (At least the guess is, that the related files functionality is causing this.)

### Reproducing

**Following the exact steps how to reproduce**
1. Make sure to have a folder with many files that relate to each other through tags or links. You can create one via script or [download an example folder (the link is valid for one week](https://share.anoxinon.de/f.php?h=1r9a5vibd7nuFzTM8ZpOr2). 
2. Open that folder as workspace in Zettlr
3. Create or open an file, make sure that the file relates to the others by putting the respective tag or link into the file. For my example this would be `#someTag` (case sensitive!)
4. Open the sidebar
5. Switch to the related files tab, if not already open
7. You will notice a lag immediately
8. Work in the file. 
9. Let it save automatically or save it manually
10. The related files list will empty, probably Zettlr is re-calculating it
11. Immediately type or do something again, after saving
12. It lags/freezes until the related files are shown again

**Following is how your Zettlr view should look like for reproducing.** 

* First image is showing Zettlr whit the related files list filled, no lag appears.

![Screenshot of Zettlr with a example workspace, an example file with `#someTag [...]` and the sidebar with related files tab open, showing a list of related files](https://user-images.githubusercontent.com/73606096/164289676-9bf63ea4-7aa6-49ed-85b9-b3454a194826.png)

* Second image is showing Zettlr whit the related files list empty, when probabaly re-calculating, this is when it freezes

![Screenshot of Zettlr with a example workspace, an example file with `#someTag [...]` and the sidebar with related files tab open, showing an empty list of related files](https://user-images.githubusercontent.com/73606096/164289622-fbe2fe26-0126-421b-a9be-9996fe0af79a.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE Tumbleweed; Debian Bullseye (But only tested a few days ago there with version 2.2.4. However, all other info applies there as well and the Zettlr config is exactly the same)

### Additional Information

This issue was caused out of #3295

**Comment by Redsandro** [comment]
I can reproduce this, exclusively with the "related files" tab open, upon file open or (auto)save.

@nathanlesage I have never used this tab before, so I am not sure how it used to work, but my initial thoughts:

1. Fix: Use Workers/Threading so the list refresh will not be blocking for the editor.
1. Workaround: The list should not refresh on save, only on open.
    - Or have _an option to_ refresh on save, so that users with a smaller workspace can still get the live refresh.
    - Or autodetect the workspace size, and auto-deactivate refresh on save above a certain size.
        - Optionally show warning in "related files" tab: _"You have too many workspaces open. Refreshing on save is temporarily disabled until you close some workspaces."_

**Comment by AIBN60** [comment]
Same low performance here on Ubuntu 20.4 but happens although there are only a few related files. turning off dictionaries helped a bit. No problem with Ubuntu 18.4

**Comment by nathanlesage** [comment]
@Redsandro I think the fastest fix for now would be to simply limit the amount of related files displayed, or also make use of the virtual scroller (as we have it for the file list). The biggest performance impact in long lists is most of the time not the actual calculation of the list since JavaScript is insanely fast thanks to jit compilation, but rather the displaying of so many elements in the DOM.

But web workers and threads is something we can't avoid for much longer anyhow. The only problem is that JavaScript doesn't like multithreading

**Comment by nathanlesage** [comment]
I have now opened #3429. First tests look promising. The PR is not completely ready, but the lag appears to be gone. Thanks @Redsandro for the quick n dirty testing command!
