### ISSUE TITLE
Emphasis rendering fails with strikethrough

### ISSUE THREAD

**Issue by davidoskky** [Zettlr/Zettlr#3406]
### Description

If you enable the option render emphasis, words with more than one effect are not rendered correctly.

### Reproducing

Test sample:
```
~~_Test_~~
**~~Test~~**
~~**Test**~~
_~~Test~~_
```

This is rendered as:
```
~~Test~~ strikethrough is only on the ~
~~Test** It's only bold
~~Test~~ strikethrough is only on the ~
Test correctly rendered
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

AUR (Arch Repository)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Arch Linux

**Comment by nathanlesage** [comment]
Closing this in favor of #3696
