### ISSUE TITLE
Wrong StartupWMclass in .desktop file causes two instances of the app on plank dock

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#341]
Wrong entry in a desktop file; For some Linux docks (like plank)  it cause two instances of the app (one pinned launcher to dock and one running instance without icon).
In the zettlr.desktop file entry is 
`StartupWMclass=Zettlr`
but according to the `xprop` the window name should be `zettlr`

Changing 'Zettlr' to 'zettlr' fixes that.

**Comment by nathanlesage** [comment]
Seems to be an issue with variables passed to `electron-builder` — would you mind investigating where the `.desktop`-file pulls its contents from? Then I know where to tweak the config!

**Comment by nathanlesage** [comment]
I just specified the `executableName` in the build script, and let's hope that it indeed does what it says in the documentation ….

If it does not work, please open an issue on the `electron-builder`-repository, as it's then their problem to solve! I'll keep this issue open until 1.4.2!

**Comment by danieltomasz** [comment]
I dont know  much about electron, they mention the same issue here https://github.com/electron-userland/electron-builder/issues/2598

**Comment by nathanlesage** [comment]
Ah, thanks a lot! I stumbled upon the Desktop-configuration, but was wary to change that as I didn't know whether or not this would mean I have to include the full desktop config and not only the missing one as this is not mentioned in the docs. Thanks!

**Comment by nathanlesage** [comment]
Implemented, please let me know if this does not work on the next release!
