### ISSUE TITLE
Zettlr is slow when writing: Have to wait until the text shows on screen when typing fast

### ISSUE THREAD

**Issue by Vlad-O-Sh** [Zettlr/Zettlr#3421]
### Description

Hi, 

I am not sure, if this is a bug, but I experience significant lag when typing. When I type, I have to wait up to a half a second for the text to show up on the screen. The last time I experienced such a thing was when I was using a Win 98 PC. I am not sure what causes this problem, but it seems to get worse with every open tab. 

I am using the latest version of Zettlr 2.2.5 on a Mac Book Pro 2015 i7 with 16GB Ram. 

UPDATE: I just noticed a process named "Zettlr renderer" in my Activity Monitor that is "not responding" at times. It may be part of the problem. 

Greetings
Vlad

### Reproducing

Happens almost every time, but gets worse when my computer uses resources for other tasks. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.6.5

**Comment by kyaso** [comment]
Does your file have a lot of related files? If so, it might be related to #3399.

If not, it is likely the same issue as #3295, which will be fixed with the next version!

**Comment by kyaso** [comment]
There is not ETA yet (unless @nathanlesage knows better?).

In the meantime, you could downgrade to 2.2.3 and see if that helps.

**Comment by nathanlesage** [comment]
No ETA yet. It should work fine, but I want to wait to see if I can manage to squeeze in a few more bug fixes before releasing. I'm not really happy releasing just a single line Changelog as a patch :D 

Let's see on the weekend. If I fix two or three more things, I'll release next week. Feel free to also stuff one or two bug fixes into the app before that … I'm afraid we have many to choose from.

**Comment by nathanlesage** [comment]
Until then, as always: Feel free to grab a [nightly](https://nightly.zettlr.com/) if you're eager for the fix.

**Comment by nathanlesage** [comment]
Closing as fixed with 2.2.6!
