### ISSUE TITLE
Cannot insert horizontal ruler

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#3436]
### Description

For a bunch of versions now, I cannot write a horizontal ruler.

```
---
```

It disappears.

### Reproducing

Write a document with some random content so Zettlr doesn't think you're writing a frontmatter.

Then enter the magical `---`, either on a new line or in the middle of a line, and after [space] or [enter], it disappears.

### Zettlr Version

Nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.2 AKA Ubuntu 20.04.2

### Additional Information

The same is true for `...`. Personally I use it less often because I copy/paste the ellipsis icon, but it is still a bug.

Workaround for writing `---` or `...` is to write two characters, a space, and then the third character (e.g. `.. .` `-- -`) and then backspace the space.

**Comment by nathanlesage** [comment]
Well, the three individual dots `...` get replaced with an (typographically correct) ellipsis sign (`…`) by default, and the three individual hyphens (`---`) will turn into an em-dash (`—`). This is intended behavior.

You have actually three ways of circumventing this:

1. Hold down Shift while pressing Enter. This will (in the LibreOffice style Autocorrect which is the default) prevent the replacement. I think with the Word-style AutoCorrect you will have to just once immediately press Backspace to undo the replacement before continuing to press Enter.
2. Remove those AutoCorrect replacements from the table to prevent those characters from being replaced (Pandoc will automatically replace two or three hyphens with proper en/em dashes on Export, iirc)
3. Just use `***` to indicate a horizontal ruler (that's the solution I've chosen)

**Comment by Redsandro** [comment]
https://user-images.githubusercontent.com/1702193/166322701-dbede88b-866a-4cbe-86a3-c19d776707ec.mp4

Workaround 1 and 3 work!

Now that you mention it... I don't recall ever toying with the AutoCorrect settings, but everything gets replaced by nothing:

![image](https://user-images.githubusercontent.com/1702193/166323229-d158820e-0092-40aa-a29a-85706b69631e.png)

These are supposed to have a default value, right? Did I mess up my settings with some alpha version? Can I restore the defaults for this page only without changing my other configuration settings?

I can now fix this problem for myself, but I think `---` should not be replaced by default. It's a much used horizontal ruler. Two dashes is already em-dash. Everything else in that list looks good to me.

**Comment by nathanlesage** [comment]
> I don't recall ever toying with the AutoCorrect settings, but everything gets replaced by nothing:

THAT looks like a bug o.O

Try removing the `config.json`, that should hopefully fix it -- if not, this might be a serious bug!

> I can now fix this problem for myself, but I think `---` should not be replaced by default. It's a much used horizontal ruler. Two dashes is already em-dash.

I understand your perspective, but it's kind of a trade off. In fact, the rule `--` = – and `---` = — is typographically the correct one and also widely used (i.e. Pandoc differentiates between two and three hyphens). This would therefore be a discussion that we can lead, but I think that if you're a person who solemly requires `---` to be used as a ruler, it is easy to just remove that AutoCorrect entry, and therefore I'd say let's keep it in there. It is much easier to remove that quickly, rather than inserting it. Therefore, keeping it as a default is the best course of action.

**Comment by Redsandro** [comment]
> Try removing the `config.json`

But that removes all my settings, correct?  

**-instant edit-** I'm looking at the contents now. Let me try to remove just the `editor.autoCorrect.replacements` part. I'm willing to bet only missing parts of the config will be reset.

**-instant edit-** Yes, this works! It's back!

![image](https://user-images.githubusercontent.com/1702193/166438427-81464e50-da65-4028-b4ef-05660c1075c6.png)

This makes a lot of sense. I have been wondering why certain phrases would just get removed. It was not annoying enough, so I thought since Zettlr version 2, I'd give it a good amount of time before I start complaining. :sweat_smile: 

There probably was an alpha version at some point that had an issue and I just never thought about cleaning up the config.

> it's kind of a trade off. In fact, the rule `--` = – and `---` = — is typographically the correct one and also widely used

Wait, there is an even longer dash? I already dislike the medium long dash because I grew up in a world where it was too wide to make sense. But okay yes it makes sense now. I thought both were the same. In that case I agree with you. Easier to remove than to add.

**Comment by nathanlesage** [comment]
> There probably was an alpha version at some point that had an issue and I just never thought about cleaning up the config.

Yes, very likely — and yes, just removing a specific config key also always works, but it's so much easier to just tell the people to ditch the full file instead of trying to explain them how to fix a certain key in a JSON object :D
