### ISSUE TITLE
[Enhancement] Pin sidebar tabs to the top so they don't disappear when scrolling down

### ISSUE THREAD

**Issue by raphraph** [Zettlr/Zettlr#3437]
### Description

When a document has a long "Table of contents", or a long list of "Other files", for example, the different tabs of the sidebar disappear from the view as you scroll down.

Therefore to switch from one tab to the other, you need to scroll back up in order to select the needed tab.

In some use cases this "tab switch > scroll down > scroll up > tab switch" actions can be regular and unpleasant.

### Proposed Changes

Pinning the tabs at the top (I mean to take them out of the scrollable area) so that they do not disappear when scrolling down would allow to easily switch from one tab to the other.

### Caveats

I don't think that there are any. I don't see any use case where you would need the tabs to not be seen.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
Is already planned, comes with one of the next updates (probably not the very next one). I have to disaggregate the Sidebar component before being able to implement this (see also PR #3422 for more info)
