### ISSUE TITLE
App starts but is totally invisible (with workaround)

### ISSUE THREAD

**Issue by micapam** [Zettlr/Zettlr#344]
## Description

When I start the app, it is completely invisible. I can tell that the app is running because other windows 'beneath' it cannot be accessed - and when I mouse over different parts of the screen, I can see that the cursor changes (e.g. a text cursor on the right hand side of the screen, on another area a hand cursor that brings up a - visible! - file open dialgoue when I click it) but the window itself is invisible.

## Reproducing

I can reproduce this issue every time just by starting the app (either by running an installed app or by running `yarn start` in my local clone of the source code), on **any version above 1.2.3** (the problem does not occur in version 1.2.3). 

## Expected behaviour

The app should be visible when it opens.

## Platform
 - OS: ElementaryOS 
 - OS Version: 0.5 Juno (64-bit)
 - Zettlr Version: 1.4.1 (I can also reproduce this bug using 1.3.0)
 - Screen Resolution: 1920x1080

## Additional information: workaround

I can fix this bug by changing one line in `source/main/zettlr-window.js`: in the `winConf` object, I have changed the `show` attribute from `false` to `true`. As per diff:

```
josh@pottage ~/L/Zettlr> git diff source/main/zettlr-window.js 
diff --git a/source/main/zettlr-window.js b/source/main/zettlr-window.js
index 2b7713f..ea7cd09 100644
--- a/source/main/zettlr-window.js
+++ b/source/main/zettlr-window.js
@@ -71,7 +71,7 @@ class ZettlrWindow {
       acceptFirstMouse: true,
       minWidth: 176,
       minHeight: 144,
-      show: false,
+      show: true,
       icon: 'icons/png/64x64.png',
       webPreferences: {
         // Zettlr needs all the node features, so in preparation for Electron
```

The weird thing is that (by putting console.log lines in to check) I can see that the `ready-to-show` event _is_ firing, so the call to `show()` is being passed to the `_win` object. Looks like on my system (ElementaryOS) that doesn't show the window, though. 

I have not raised a PR to fix the issue, because I'm not sufficiently familiar with Electron or with the Zettlr source code to know if my change is a good idea - plus I don't know the rationale behind making the window start with `show: false`. So I don't know if my one-line workaround is a good enough fix from maintainers' perspective.

However, with that line changed as shown above, the app works just fine, both from `yarn start` and when I release a build of the app and run it on my system. And I don't see any bad side effects.

I hope this is useful information.

**Comment by nathanlesage** [comment]
Hey,

yeah, it surely sounds like an Electron/Elementary-related bug, so I'd suggest you open a bug report on the electron repository, providing this information that the `show()`-method on a BrowserWindow-object does not have any visible effect. I'm not sure what electron-version-change happened between 1.2.3 and 1.3 (I think I switched to Electron 5), but I would assume it has been introduced by this.

The rationale behind not opening the window right away is (I just took that from the Electron docs) that by not showing the window, it has time to build up, load the engines, etc. pp so that you don't see the window literally building itself but only the final window.

**Comment by nathanlesage** [comment]
Oh and btw thanks for already verifying that the ready-to-show-event does fire! This is helpful information :)

**Comment by nathanlesage** [comment]
I just did a search on the internet but I couldn't find any hints as to what might be causing this effect. I currently suppose that probably a library on ElementaryOS is conflicting with what the Electron-binary expects, but I'm not quite sure …

**Comment by nathanlesage** [comment]
Does this issue still persist?

**Comment by nathanlesage** [comment]
Closing to unify the necessary discussion on this issue over at #448!
