### ISSUE TITLE
Inconsistent behaviour when adding / opening folder 

### ISSUE THREAD

**Issue by mathueb** [Zettlr/Zettlr#345]
**Description**
When I try to add existing folders, nothing is happening. If I restart the application after opening a folder one in ten times the folder is added after the restart. 
The more files and subfolders are in the folder the more unlikely it is, that a restart of the application will fix the missing folder. The behaviour is the same for directories in my home dir, as well as smb shares or mounted devices. 

**Reproduction steps**
- Pick "[Open existing folder...]" from the top left menu. 
- Select a folder. 
- click Ok
 

**Expected behaviour**
The folder should be added. In case of an error-event, an error code should be displayed.
In case the folder import/open process takes longer than expected by the user, the user should be informed. 

## Platform
 - OS: Xubuntu
 - OS Version 18.04
 - Zettlr Version 1.4.1

I have the same problem in Windows 10.

**Comment by nathanlesage** [comment]
> The more files and subfolders are in the folder the more unlikely it is, that a restart of the application will fix the missing folder.

Ah, here you have the answer. It simply takes some time to read in the full folder. So it's not so much a bug but more a problem relating to the user feedback as Zettlr doesn't tell you "please wait, scanning directory". It should work if you wait long enough (I've experienced that myself recently).

**Comment by nathanlesage** [comment]
Added a notification that will inform you both when Zettlr attempts to load a valid new root directory as well as when it is done loading it. The new root directory will be added to the configuration file only after the contents have successfully been parsed, so it's now easier to open huge directories: Simply wait until Zettlr confirms the directory has been loaded, then you can safely close the application!

The patch will probably release tomorrow.
