### ISSUE TITLE
Add "file name" to Snippet variables

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3453]
### Description

It would be cool when there was a snippet variable that inserts the current file's name.

This would be useful in workflows where the file name and title match.

### Proposed Changes

* Add a new snippet variable, e.g. "FILE_NAME" to the snippet logic.
* When the snippet gets inserted, the variable should be replaced with the current file's name (excluding the extension)
* Also, update the [documentation](https://docs.zettlr.com/en/core/snippets/) accordingly.

### Caveats

No.

### Do you Wish to Attempt Implementing this Yourself?

Yes (_if I find some time, I might tackle this, but if anybody else is faster, go ahead!_)

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
Sounds good! As far as I know there is already a variable based on the file itself, so it should be fairly straightforward to copy that!
