### ISSUE TITLE
Character count is incorrect when including lists in the YAML frontmatter

### ISSUE THREAD

**Issue by reneraab** [Zettlr/Zettlr#3458]
### Description

I checked the number of characters in my file and noticed that it showed 573 words, 4,668 characters and 5,646 characters (w/o spaces). The number of characters without spaces is larger than the total number of characters which should never be the case. After some investigation, I noticed that this bug appears when including lists in the YAML frontmatter (see example below).

### Reproducing

Example that shows the problem:
```
---
title: Test
id: 20220509113624
date: 2022-05-09
tags:
  - test
...


# Test
```
Zettlr shows 1 word, 5 characters and 70 characters (w/o spaces). The count becomes correct if you remove the list of tags from the frontmatter.

### Zettlr Version

Stable (but an older version)

### Specify version

2.2.4

### Installation Method

AUR (Arch Repository)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro 21.2.6 (Qonos)

**Comment by nathanlesage** [comment]
Feel free to check if that also happens in 2.2.6 and then please report back! I'll then have a look at it.

**Comment by reneraab** [comment]
I was able to test version 2.2.6 now and the problem shows up even without the YAML frontmatter in the file:

Example:
```
# Test space
```
shows as 2 words, 11 characters and 11 characters (w/o spaces) (or 10,10 if there is no new line after this line, so new-line characters are being counted as well)

**Comment by nathanlesage** [comment]
Thank you for confirming!

**Comment by nathanlesage** [comment]
I just experienced that a list itself is also not counted, why ever:

![image](https://user-images.githubusercontent.com/17251683/169527002-373cec5f-9c27-4982-984a-c004a87ee3f2.png)

And if I select one space less:

![image](https://user-images.githubusercontent.com/17251683/169527047-ca042da5-1a9d-4186-afd3-759978b089e0.png)

**Comment by nathanlesage** [comment]
Fixed it! Thank you for your test code!
