### ISSUE TITLE
The painful Reaction Time after reopen Zettlr

### ISSUE THREAD

**Issue by GitPlayB** [Zettlr/Zettlr#3466]
### Description

I don't know if you guys have problems like this, but this is really annoying me. That is, every time I reopen Zettlr, **the application seems still asleep**, during this time I couldn't do anything, I can't even open a **.md** document because it can't even recognize the document type, it's just like sleeping dead. No matter I reopen it directly or double click a .md file(and it will invoke Zettlr automatically), it just didn't work. **After about 5-10 minutes**, the file recently used or I just opened suddenly flashed and **Zettlr waked up!** Everything becomes normal again. At first I thought this is a language setting problem, but when I set it to English, the problem still exists. These are the screenshots I got.

1. In the **Zettlr** menu you can't see the **Preferences** or **Resource Manager** button.
![Still Asleep](https://user-images.githubusercontent.com/33520768/167998569-c3511bed-2017-4a98-b80c-22c1f00fa1d7.jpg)

2. In the **File** menu **it's all EMPTY!** 
![Still Asleep](https://user-images.githubusercontent.com/33520768/167998958-d097e507-e71c-45e9-a8a2-a9bd7541bec3.jpg)

3. I opened the **Preferences** window through the button on the left side
![Preferences](https://user-images.githubusercontent.com/33520768/167999128-129c2541-338d-47ca-a0be-0e2c2a9a8c9b.jpg)

4. **After a LONG while**, the Zettlr menu displayed like this
![Normal Zettlr menu](https://user-images.githubusercontent.com/33520768/167999361-8b91ea4e-21c6-403a-9367-90a523679a9f.jpg)

5. **After a LONG while**, the File menu displayed like this
![Normal File menu](https://user-images.githubusercontent.com/33520768/167999441-c041b3d2-11f7-4093-bbd9-85ac64951302.jpg)

I don't believe this is a problem of my Mac or something else, because it runs smoothly on all other apps. So, will there be any technical experts that help me solving it?

### Reproducing

in Mac press Command + Q, and reopen it.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Monterey 12.3.1

**Comment by nathanlesage** [comment]
@GitPlayB This almost sounds as if one of your directories is large or has something in it that makes Zettlr painfully slow in loading it. There are two things you could try out to check that:

First, if you activate the debug mode in the preferences, you can check the logs via Develop --> Open Logs. There should be some lines indicating how long certain directories took to load. The culprit directory should tell you something with 300 seconds (which equals 5 minutes).

Secondly, if that is the case, please try out unloading that directory and attempting to restart Zettlr. If it is then fast again, there was really something in the directory and we can take another look at what that might be.

Please also feel free to share the logs here with a screenshot; especially if there are red lines in there, indicating errors.

**Comment by GitPlayB** [comment]
Hey, thanks for reply and this is what I've done after read all that you told me.
1. First I opened the dubug mode and got some logs. But before I got it, when it opened at first, I couldn't find the **Develop->Open Logs** menu. 
1. There is no **Develop** menu in there, and down in the **View** menu I tried **Reload** and **Force Reload**, and it didn't work either, just a flash and then nothing.
![Zettlr 1 with no DEVELOP menu](https://user-images.githubusercontent.com/33520768/171830019-509bd19e-92a8-4502-abf0-590c85f1caae.jpg)

2. I open the preferences menu and **Re-unchecking the  Open Debug Mode** and then the whole **Develop** menu comes out.
<img width="1005" alt="Zettlr 2 Re-unchecking the  Open Debug Mode" src="https://user-images.githubusercontent.com/33520768/171830049-389182bb-f256-47a6-83a7-d46699a35e54.png">


<img width="984" alt="Zettlr 3 Re-checking the  Open Debug Mode" src="https://user-images.githubusercontent.com/33520768/171830078-77afa24f-3d20-4b09-aef1-3edf162cbb4b.png">

3. This time I saw the logs it printed.
<img width="766" alt="Zettlr 4 LOW Booting Up Logs" src="https://user-images.githubusercontent.com/33520768/171830748-173ea8a7-1095-4fdc-86c1-de8800bfe569.png">

I found that when it was stuck the logs stopped at *Writing Configuration File to...*, just the line before the red allert, or the **Error** part.

4. I opened the **config.json** after that.
<img width="1535" alt="Zettlr 5 Config json Looks Like" src="https://user-images.githubusercontent.com/33520768/171831227-0a7c6f82-f12e-4b86-8def-ccfb329d2780.png">

I don't know if this is the reason but, the **openPaths** and the **openFiles** are a little too much. I don't know why Zettlr has to check that every time I open it, might be convenient to see **Recently Opened Files**? If it just check the same directory where the file I just opened or the directory(Only the last one) correspondent to that lastly visited file, I understand. But it seems to find all the directories I've ever opened that contained some .md documents. So, how am I going to fix this? And what do you mean by **unloading that directory**, is it to delete the config.json or what? Please tell me🙏 
Waiting for your reply!

**Comment by GitPlayB** [comment]
Hi, I probably understand it. And another question, Where is the **Right click -> Close file** and **Right click -> Close Directory**? Are they under the **File** menu?
<img width="386" alt="image" src="https://user-images.githubusercontent.com/33520768/172034546-7c782d13-95de-4d10-9e78-352259e6ab8d.png">

**Comment by nathanlesage** [comment]
Right click means to right click on the corresponding file or folder.

**Comment by GitPlayB** [comment]
> Right click means to right click on the corresponding file or folder.

But there's only **Delete File** option as the picture showed above.

**Comment by nathanlesage** [comment]
No, if I say "right click" I literally mean to right-click that specific folder or file in the file tree. This option is **not** in the File menu. See attached screenshot:

![image](https://user-images.githubusercontent.com/17251683/173446316-38116241-daae-4fcd-a9ef-a36e14d04516.png)

**Comment by nathanlesage** [comment]
I just saw the issue you were experiencing: Apparently the network connection was extremely slow. Before I fixed that in late last year, Zettlr would wait for the update check before actually loading everything. By now, this shouldn't happen anymore.
