### ISSUE TITLE
[Feature Suggestion] Cite by doi or url

### ISSUE THREAD

**Issue by jobindj** [Zettlr/Zettlr#347]
It will be nice to be able to cite by doi or url, similar to the function implemented in R package [knitcitations](https://github.com/cboettig/knitcitations).

**Comment by nathanlesage** [comment]
You mean with searching only? I could try to provide searching for DOI or URL!

**Comment by jobindj** [comment]
No, I meant including a citation in the markdown. For example, citep("10.1890/11-001...") will create a citation @FirstAuthorsLastName_Year and include it in bibliography at the end of the document. The citation key can be resused again in the document and is added to the bibtex file automatically. You can find the examples here: https://github.com/cboettig/knitcitations

**Comment by nathanlesage** [comment]
So you mean simply dump the citation key and replace it with a DOI or URL?

Concerning URL: If this Greycite (for which I did not find any information online, which is weird) is the only method of citing by URL, I have bad news: The API seems to be pretty much down.

**Comment by jobindj** [comment]
Sorry, I meant the other way. DOI is easy to get from most research articles. So if I copy-paste the DOI to the editor, then some process of converting the pasted DOI to a citation key might make life simpler. Otherwise I will need to create a BibTex entry, or rely on Zotero or other software as intermediate step to make a citation.

When I use R Markdown, knitcitations creates the citations keys and the .bib file automatically from the DOIs in the document. I haven't used the URL feature yet.

**Comment by nathanlesage** [comment]
Aaaaaaaah. I see what you mean. Well, Zettlr itself is more or less designed to interact with Zotero, it does not try to handle the generation of citations and the storage itself, as it's only meant as an editor; so I think this might be well out of the scope of the app.

After all, Zettlr relies on you providing it with a ready BibTex/CSL-JSON-file that it can simply read. Generating citekeys on its own might well conflict with a loaded database.

**Comment by jobindj** [comment]
I see! Thank you, @nathanlesage . In case you find some way that Zettlr can edit the loaded database without conflicts, then this can be a useful feature. Thanks!

**Comment by nathanlesage** [comment]
I'll keep it in mind!
