### ISSUE TITLE
Add Powerpoint (pptx) as an export format

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#3475]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [ ] I have searched the documentation to make sure I did not overlook it.
- [ ] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Add Powerpoint as an export format. 

Pandoc now supports pptx as a fully featured export format for presentations. As Powerpoint is much more widely used globally than reveal.js, and conferences often require it, the ability to export to pptx would be useful for many users. 

I think that the standard Zettlr defaults file (e.g. as used for export to Word) would work fine.

### Example Workflow

Adding pptx as an export format would allow users to export a presentation to Powerpoint. This would be a very useful addition to reveal.js. 

### Caveats

No caveats - except that if you add other additional new export formats (e.g. epub as well, see https://github.com/Zettlr/Zettlr/discussions/3450), then the dropdown selector for export formats might perhaps need a bit of reorganisation to avoid seeming cluttered.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
Should in principle be easy, by adding a corresponding defaults file and adapting the correct places in the code. Whoever wants to, feel free to open a PR.

**Comment by vedranmiletic** [comment]
A much better option would be to integrate [Marp](https://marp.app/) which can export slides to PowerPoint, among other formats.

**Comment by nathanlesage** [comment]
@vedranmiletic This depends upon support by Pandoc. There must be a *really* good reason if we are to circumvent the Pandoc engine, and I don't see one for that output format.

**Comment by jgsw** [comment]
Can be closed now the new approach to exporting has merged.
