### ISSUE TITLE
Export and save statistics 

### ISSUE THREAD

**Issue by sgtskips** [Zettlr/Zettlr#348]
i started using zettlr last month and really enjoyed the stats feature which helped me to stay focused and improve daily but i recently had to reset my windows setup and i couldn't find a way to export the stats i had now i have to start all over again 
i lanaged to make screenshots for personnal use but i wish i could save it and re import it once i did the fresh install 
thank you !

**Comment by nathanlesage** [comment]
Good idea! Until it's implemented: The Stats are insight the Data directory, a file called `stats.json` — it's plain text, so you can simply export them by copying this file :)

See this path here: https://docs.zettlr.com/en/install/#windows-7-or-newer
