### ISSUE TITLE
Unintentional jumping of text

### ISSUE THREAD

**Issue by CommunyAS** [Zettlr/Zettlr#3488]
Since a while, when writing (in my particular case a paper containing comments and citations) the text jumps frequently so that the line with the cursor is locate near the windows lower end after jumping. This is very disrupting.

I found that this issue also affected many users in an older release and was then marked as solved: [Experiencing unintentional "jumping" of text #1621](https://github.com/Zettlr/Zettlr/issues/1621)

To me it seems, the problem or a similar problem turned up again. But I don't have this problem on my MacBook, only in my Windows notebook.

Any solutions?

**Comment by nathanlesage** [comment]
Please try to replicate this behavior. Once we can reliably cause it, it will be very easy for us to determine what causes this.

**Comment by nathanlesage** [comment]
Ahh, I have a suspicion where this may come from. Do you sync your files to a cloud provider, and if so, which one?

**Comment by CommunyAS** [comment]
No, I don't sync my Win-workstation to the cloud (contrary to my MacBook without causing problems)

**Comment by nathanlesage** [comment]
Okay, weird. Something must be messing with the modtimes of the files. Maybe closing Zettlr and then removing the FSAL cache directory might help, see our troubleshooting guide: https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app

**Comment by CommunyAS** [comment]
It took a few days to try your suggestion - it worked
