### ISSUE TITLE
Disable tag detection within fenced code blocks

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3492]
### Description

Currently, when a fenced code block contains a hashtag (#) followed by some text, Zettlr interprets that as a tag. However, a hashtag inside a code block is most certainly not intended to be a tag.

For example, in the following code block (thanks @davidzoli), the strings "12345", "12346" and "12347" would be falsely recognized as tags:

~~~
"orders": [{
  "type": "multi",
  "options": [
    { "label": "Order #12345", "value": "order12345" },
    { "label": "Order #12346", "value": "order12346" },
    { "label": "Order #12347", "value": "order12347" }
  ]
 }
~~~

### Proposed Changes

When parsing the file content for tags, ignore any fenced code block. While we are at it, fenced LaTeX blocks (delimited by `$$`) should also be ignored.

### Caveats

I can't think of any. Maybe if some people actually intentionally use Zettlr tags inside code blocks, this might mess them up.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

This issue was opened following the discussion in #3082.

**Comment by nathanlesage** [comment]
Relevant file: /source/app/service-providers/fsal/util/extract-tags.ts

I simply forgot to remove code blocks when I refactored that 🙈

**Comment by kyaso** [comment]
Still relevant, I guess.

**Comment by nathanlesage** [comment]
I think I fixed it again in the current dev branch, so should work now!
