### ISSUE TITLE
CSS class names for tags are missing a letter

### ISSUE THREAD

**Issue by IgnacioHeredia** [Zettlr/Zettlr#3495]
### Description

When you use a `#tag`, Zettlr creates an associated CSS class for that tag. This is nice because it allows to customize specific tags. The problem is that the generated CSS class names are missing the first letter, thus could potentially collide with one another messing with customizations (tag cloud seems unaffected though).

 For example, example tags `#bug` and `#hug` will create the same CSS class (`.cm-zkn-tag-ug`).

### Reproducing

For example, `#software` class produces `.cm-zkn-tag-oftware` CSS class.

More examples [here](https://gist.github.com/IgnacioHeredia/df82281250eacee16fd5eb644fbeba4e).

### Zettlr Version

Stable (but an older version)

### Specify version

2.2.5

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by IgnacioHeredia** [comment]
BTW, @Redsandro [mentionned](https://github.com/Zettlr/Zettlr/discussions/2863#discussioncomment-2804064) that when using tags inside a YAML frontmatter, the CSS class names are not created.

Not sure if this is better dealt in a separate issue, but mentioning it here just in case.

**Comment by nathanlesage** [comment]
The missing letter is 100% a substring issue and should be easily fixable. Will have a look at it tonight.
