### ISSUE TITLE
AppImage x86_64 fails to run in Ubuntu 22.04 without installing libfuse2

### ISSUE THREAD

**Issue by StevenMaude** [Zettlr/Zettlr#3517]
### Description

# Expected behaviour

Zettlr to run.

# Actual behaviour

```
$ Zettlr-2.2.6-x86_64.AppImage
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

As of Ubuntu 22.04, libfuse2 is no longer installed by default. It's still available in Ubuntu's package repositories, but [must be installed by a user themselves](https://bugs.launchpad.net/ubuntu/+source/lubuntu-meta/+bug/1965636).

# Workaround

`sudo apt install libfuse2` fixes this and allows Zettlr to run.

### Reproducing

1. Install Ubuntu 22.04 x86_64. 
2. Download a current Zettlr x86_64 AppImage.
3. Run the Zettlr AppImage: see the `libfuse.so.2` error.
4. Install `libfuse2` via `sudo apt install libfuse2`.
5. Run the Zettlr AppImage: observe that Zettlr now runs.

### Zettlr Version

Beta (if applicable)

### Specify version

2.2.6

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04 LTS

### Additional Information

1. Please feel free to either close this issue, as it's not really fixable until upstream fix it, or leave this issue open until this AppImage runs without the extra dependency.

   The related upstream issue — AppImage/AppImageKit#877 — looks fairly active. Hopefully it's fixed soon :hammer:

   Reporting here for visibility/search helpfulness, as I couldn't find the issue here and it may help other users.

2. This may well affect the arm64 AppImage too, but I can't test that.

3. It may affect other Ubuntu-based distributions, if they similarly don't install libfuse2.

**Comment by nathanlesage** [comment]
Thanks for reporting this. However, as you have acknowledged yourself, this is nothing we can really fix, and given that we still have quite a long list of issues to tend to with regard to bug fixed, I am going to close this issue to keep the issue list sane. If there is anything we could do in this regard, feel free to comment here so we can sort things out.
