### ISSUE TITLE
Headings containing citations display incorrectly in table of contents

### ISSUE THREAD

**Issue by jpeacock29** [Zettlr/Zettlr#3518]
### Description

When citations are included in a heading, they do not display correctly in the Table of Contents side bar. Examples of Markdown followed by how it displays in the table of contents:

#### Example 0
> \# @SorokowskiUniversality2021

> 1 Sorokowski et al. (2021)21

#### Example 1
> \# Foo Bar Lorem Ipsum Foo @SorokowskiUniversality2021 Bar

> 1 Foo Bar Lorem Ipsum Foo Sorokowski et al. (2021) @SorokowskiUniversality2021 Bar

#### Example 2

> \# Foo Bar Foo @SorokowskiUniversality2021 Bar

> 1 Foo Bar Foo Sorokowski et al. (2021)iversality2021 Bar

### Reproducing

1. Open a Markdown file with Zettlr configured to display citations.
2. Create a section header containing a citation. See the provided examples.
3. Open the Table of Contents sidebar and view the corresponding entry.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.6

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.6.4

**Comment by nathanlesage** [comment]
This is luckily fixed in the current dev branch. Today's nightly will also have this fix available!
