### ISSUE TITLE
Tables won't process unless they are perfectly spaced

### ISSUE THREAD

**Issue by jrcharney** [Zettlr/Zettlr#352]
In Markdown, it usually doesn't matter how many spaces or hyphens there are between the pipes when creating a table.

```md
| Header 1 | Header 2 | Header 3 | Header 4 |
|:---|:---:|---:|---|
| Left | Center | Right | Default |
| Row 2 | Cell 2 | Cell 3 | Cell 4
| *Italic* | **Bold** | ***Both*** | Neither
| `code` | [Link](https://github.com/) | | Row 4 |
| *`Italic code`* | **`bold code`** | [`code link`](https://github.com/) | ~~`strike code`~~ |
| Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  | Long test | ~~Strikethru~~ |
```

| Header 1 | Header 2 | Header 3 | Header 4 |
|:---|:---:|---:|---|
| Left | Center | Right | Default |
| Row 2 | Cell 2 | Cell 3 | Cell 4
| *Italic* | **Bold** | ***Both*** | Neither
| `code` | [Link](https://github.com/) | | Row 4 |
| *`Italic code`* | **`bold code`** | [`code link`](https://github.com/) | ~~`strike code`~~ |
| Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  | Long test | ~~Strikethru~~ |

(BTW, Zettlr should be able to process Markdown EXACTLY like in the example I just demonstrated above, along with a few other inline combinations. This is basically every other request in the Issues queue.)

However, almost nothing processes like in the above demonstration, and if the contents are not perfectly spaced, the table will not process at all!

Such as with this disaster I still have to clean up.
![image](https://user-images.githubusercontent.com/1954239/66420868-5af33800-e9cc-11e9-9a27-e98e8ad57971.png)

Initially, I started out using the table generator, but then the table generator had some trouble after processing.  Eventually, things started to fall apart.

Zettlr's markdown processing, especially for tables, needs improvement. If at very least, an option to preserve or discard padded space when processing tables. (Discard would be better, as the data should be read sort of like a comma separated value (CSV) file where the separator is the pipe character (`|`).) Space preservation can be done between words, but between the column separation character (the pipe), Zettlr should abide by [extended Markdown rules](https://www.markdownguide.org/extended-syntax/) or [Github Flavored Markdown rules](https://github.github.com/gfm/) for table extensions, So that tables do not dissolve into a muddled space filled mess.

**Comment by nathanlesage** [comment]
Thank you for your message!

Surely, the Table Editor has a lot of room for improvement, but it seems there's some misunderstanding concerning the Table Editor's capabilities.

The Table Editor will process any table that is not perfectly spaced. The only requirements are that the line starts directly with a pipe operator and ends with one. If there is a trailing space, it won't render. This of course requires some attention, but not too much. The spaces in between the table cells are irrelevant, you can pad them as you want; as soon as the Table Editor processes your table, it will trim the cell contents to remove preceding and trailing whitespaces.

Furthermore, the Table Editor will not render tables where the column numbers don't add up. If you have forgotten a pipe character on any row, it will fail to render as it expects a well-formed table. You should see an error logged to the development console in that case, if I'm not mistaken.

Then, for the inline elements within the table. Of course it would be great if the Table Editor will one time also render inline Markdown within Table cells, but this is unrealistic at this moment. The Table Editor makes use of contenteditable cells, and editable content within HTML documents is at the current stage a catastrophe in each and every browser, so implementing inline Markdown element rendering __within__ contenteditable cells will take an unreasonable amount of time, especially given the fact that I am the only developer of the app currently.

If I understand your last paragraph correctly, you opt for the Table Editor spitting out tables that are not padded, do I read you right here? If so, it should be easy to implement such an option.

Besides that, I'd like to ask you what precisely your concrete issues with the TableEditor are that, given the above information, would be possible to fix?

**Comment by jrcharney** [comment]
> If I understand your last paragraph correctly, you opt for the Table Editor spitting out tables that are not padded, do I read you right here? If so, it should be easy to implement such an option.

Well, the table editor can *appear* padded in graphical form, however, the data in raw form should **not** preserve added spaces, not even between words.

In this example, I attempt to use regular spaces to pad the data.

```markdown
| Column 1 | Column 2 | Column 3 |
|---|---|---|
|Spaces    are    should    not    be    preserved    here | Nor here        |         And not here either |
| |         Definitely not here        | |
```

| Column 1 | Column 2 | Column 3 |
|---|---|---|
|Spaces    are    should    not    be    preserved    here | Nor here        |         And not here either |
| |         Definitely not here        | |

However, if I try using a non-breaking space (`&nbsp;`), padding can be preserved.

```markdown
| Column 1 | Column 2 | Column 3 |
|---|---|---|
|Spaces&nbsp;&nbsp;&nbsp;&nbsp;are&nbsp;&nbsp;&nbsp;&nbsp;preserved&nbsp;&nbsp;&nbsp;&nbsp;here | And here&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And also here |
| | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Here too!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | |
```

| Column 1 | Column 2 | Column 3 |
|---|---|---|
|Spaces&nbsp;&nbsp;&nbsp;&nbsp;are&nbsp;&nbsp;&nbsp;&nbsp;preserved&nbsp;&nbsp;&nbsp;&nbsp;here | And here&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And also here |
| | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Here too!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | |

Here's what happens when I paste (`CTRL+Shift+V`) the first example from the first post in this thread.
![image](https://user-images.githubusercontent.com/1954239/66507114-3793c000-ea94-11e9-9b18-47b06ed92d27.png)

When I add the proper number of pipes, this happens.
![image](https://user-images.githubusercontent.com/1954239/66507890-ade4f200-ea95-11e9-8625-d234176b24bc.png)

I was under the assumption that the table header row and the rest of the table was separated by a line with pipes, hyphens, and colons to set the alignment. So why is the first row of data being treated as the table header row and not the row that was defined before it? My syntax is correct according to the [extended markdown rules](https://www.markdownguide.org/extended-syntax/#tables).  Of course, the syntax inside doesn't process.

At least, let's see if I can add another row on top to the first row in the table.
![image](https://user-images.githubusercontent.com/1954239/66508321-82163c00-ea96-11e9-817a-806e6f4b64b2.png)

And it exploded into a textual mess. Full of spaces and extra hyphen. Hardly the neat code that created the example.

> Markdown element rendering within contenteditable cells will take an unreasonable amount of time, especially given the fact that I am the only developer of the app currently.

That is a problem. However, it is one you more than likely solved already. Lists and Blockquotes are [block elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) like Tables. I think you have to solution, but it hasn't crossed your mind yet.  I'll take a look at the source myself and see how this problem can be resolved.

Besides, it will be interesting to see if I can get Zettlr to run on a Raspberry Pi. ;-)

**Comment by nathanlesage** [comment]
Now I understand what you mean. I simply need to ensure that the header-delimiting row with only hyphens and colons is NOT treated as a correct table if no correctly numbered row directly follows. Also make sure that no more than one row precedes the header-delimiting row.

Culprit function:

https://github.com/Zettlr/Zettlr/blob/9778467c3130961ba897f0d9d252b21cc40a348f/source/renderer/util/table-helper.js#L156-L229

Should be easy to fix.

**Comment by nathanlesage** [comment]
Oh, just did some more examples and actually, the TableEditor is more intelligent than myself — because there's actually two steps involved in building the corresponding DOM-Element, some errors such as misplaced header rows simply are converted correctly.

So what is happening (and what explains your upsetness with the table) is the following:

1. The Markdown table gets loaded into a buffer completely, line by line.
2. The TableEditor is started, and the Markdown Table as text is being passed to it.
3. The TableEditor makes sure that the columns add up
4. If there is a header row ANYWHERE within the table, it will be parsed correctly.
5. Then the table editor parses this into an Abstract Syntax Tree
6. This Syntax Tree is being used to generate the DOM element.
7. The DOM element is overlaid on top of the original Markdown table.
8. As soon as you alter anything within the table, the original Markdown Table will be overwritten with the correctly parsed table.
9. Additionally, in this step, the TableEditor rebuilds the Markdown Table from the Abstract Syntax Tree and additionally makes sure that all cells are padded correctly, resulting in the mess you see.

Which leads me to the following:

1. What you really strive for is a preferences option to turn off the automated padding of the tables.
2. I'll leave the table editor as it is, as this is definitely a good thing to have, especially for the target group of Zettlr — academics!
