### ISSUE TITLE
Is transclusion on export possible

### ISSUE THREAD

**Issue by anthrolisp** [Zettlr/Zettlr#354]
It is possible to include other markdown docs inside another and have it render on export? Imagine if I wanted to create a master outline of zettels and export it. Is it possible through Zettlr? Many thanks in advance!

**Comment by nathanlesage** [comment]
It might be possible, but I would strongly advise against adding this to the exporter itself to not mingle up functionalities. What I could imagine would be some sort of a "rendering" plugin that, when called on a root file, is able to recursively pull in all referenced files and save it as one single MD-file which then could be exported as is.
