### ISSUE TITLE
File renaming/creation: cursor can't be moved using arrow keys

### ISSUE THREAD

**Issue by onemenzel** [Zettlr/Zettlr#3548]
### Description

When renaming / creating a file, I expect that I can move the cursor to enter the file name using the arrow keys. This does not work.

### Reproducing

1. in the file manager, create or rename a file
2. while entering a file name, try to move the cursor using the arrow keys

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Montery 12.4

**Comment by onemenzel** [comment]
I think this is due to the new file selection method using arrow keys: while renaming the file, the arrow keys still do move the seletion highlight in the file manager.

**Comment by nathanlesage** [comment]
Yes, sounds as if I just need to stop the propagation of arrow events in those renaming text fields
