### ISSUE TITLE
Tables are glitchy

### ISSUE THREAD

**Issue by kazmath** [Zettlr/Zettlr#3553]
### Description

There are several things that I find weird in how tables are displayed in the editor, so I'll just write them all in this issue:

1. The position of the cursor when using the arrow keys to move through them is off.
![image](https://user-images.githubusercontent.com/66137568/174421968-f9f91840-58ae-48d1-b7c8-fb3de110b288.png)
![image](https://user-images.githubusercontent.com/66137568/174421974-eb90f56d-ed2b-41d2-9993-0ddae12eb3d2.png)
![image](https://user-images.githubusercontent.com/66137568/174421978-7d31365a-8dfd-42f3-9a9e-4b9c787cb918.png)

2. Using the usual `ctrl+b` and `ctrl+i` shortcuts to make text bold/italic only works visually, but when switching cells or clicking out of the table, the text that was supposed to be appended and preppended `*`s remains the same
* Also, manually added formatting only shows when switching cells or clicking out of the table
* And moving through parts that are only visually formatted with the arrow keys switches cells
![image](https://user-images.githubusercontent.com/66137568/174422117-7f51c2ab-509a-4914-97bc-48b232cd27d4.png)

3. Inline codeblocks (with \`) shows up differently in tables (Which could be a design choice, because I kinda like how it looks, but it's still inconsistent)
* Also, same problem as `2.` regarding to only showing when switching cells
![image](https://user-images.githubusercontent.com/66137568/174422204-3ba63463-80bb-48ef-aa83-2c405681324b.png)

4. Tables inside tables (which don't even work in github flavored markdown) show up in a weird (but cool) way, but don't render again if you refresh the page or restart the app
![image](https://user-images.githubusercontent.com/66137568/174422216-f86883d8-bfa0-4735-a780-e266c74f7f58.png)
![image](https://user-images.githubusercontent.com/66137568/174422234-8832b84b-7430-4c81-82df-875679cdca79.png)
![image](https://user-images.githubusercontent.com/66137568/174422226-3624270a-9d54-41b3-849c-0b59ccfeb153.png)
![image](https://user-images.githubusercontent.com/66137568/174423139-82fd3f8d-b2cc-4922-9ff3-66a3d5365e47.png)
* If possible, I ask that only the rendering problem is solved, as I really like that look

### Reproducing

1. Bug
* 1. Create table
* 2. Click outside of the table
* 3. Move through the table with arrow keys

2. Bug
* 1. Create table
* 2. Write something in a cell
* 3. 1. Select part or all the text in the cell
* * 2. Press `ctrl+b` and/or `ctrl+i`
* * 3. Click outside of the cell/table
* * 4. Click back into the cell
* 4. 1. Put `*` characters in equal amounts before and after part or all the text
* * 2. Click outside of cell/table

3. Bug
* 1. Repeat steps `i.` and `ii.` of previous bug
* 2. Put one \` character before and after part or all the text
* 3. Click outside of cell/table

4. Bug
* 1. Create table
* 2. Paste this in one of the cells (it is impossible to do it without pasting):
  ```markdown
  |  |
  |--|
  | Item 1 |
  ```
* 3. Click outside of cell/table
* 4. Create more tables with or without text written in them
* * With two newlines between each table, not doing so will just paste the table format without actually rendering it, which could be another bug or not, because one newline after a table is not actually a newline in the markdown file, so adding another table there wouldn't even be possible with normal markdown
* 5. Close/kill and open app again (or press `f5` with developer mode enabled)

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.3 x86_64

### Additional Information

* The logs when restarting the app and clicking anywhere in the document show errors like:
```
[R] [Main Window] Could not instantiate table between 0 and 7: Malformed Markdown Table! Found 1 columns on line 3 (should be 2). (index.js:2)
```
And keep spamming that each time I click another part or the same part of the document.

* I am using the AppImage provided in the releases section of the github page, if that is relevant

**Comment by Kazuma-chan** [comment]
Other than those, there are some inconsistencies in the interactions with bullet point lists, numbered lists, codeblocks and maybe more that could be solved by either enabling line breaks in the cells or just disabling that functionality entirely like github does:

|  |  |
|--|--|
| * bullet point | 1. 1. numbered |

* bullet point

1. 1. numbered

(but please keep them)
