### ISSUE TITLE
[BUG] Crash while installing Italian it-IT dictionary. Zettlr stalls forcing it to exit and disinstall.

### ISSUE THREAD

**Issue by lordmax** [Zettlr/Zettlr#3554]
### Description

I have tried multiple times to install the it-IT Italian dictionary and from the URL that you kindly provide in the manual

GitHub wooorm - dictionaries
https://github.com/wooorm/dictionaries/tree/main/dictionaries/it

It appears in the list of dictionaries in the configuration window, but when I select it in stalls the Zettlr program and forces me to exit the program.
And from that moment on there's no way to start Zettlr. I have to disinstall it.

A window will appear forcing you to exit because the Zettlr program will hang.

The problem exist at least from version 2.2.4

### Reproducing

Download the it-IT dictionary from the github site:

GitHub wooorm - dictionaries
https://github.com/wooorm/dictionaries/tree/main/dictionaries/it

menu -> import dictionary

Create directory it-IT
copy files:
index.dic
index.aff

then select the configurations window and the dictionary it-IT appears correctly.
Select the dictionary and exit the window.

There's no way to close. Pop-up window hang.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

windows 10 fully updated - linux Mint 20

### Additional Information

Thanks for your work

**Comment by nathanlesage** [comment]
This issue is long known. There are already appropriate issues open here (esp. in relation to the Portuguese dictionary), the relevant issue is this one: https://github.com/wooorm/nspell/issues/11
