### ISSUE TITLE
[Enhancement] Text highlighting during Export

### ISSUE THREAD

**Issue by jimvine** [Zettlr/Zettlr#356]
I spotted that recent versions of Zettlr support highlighting text using `==` or `::` around a block of text. This works nicely in Zettlr.

When I export to PDF or docx, however, the text is not highlighted, and the literal `==` or `::` characters are output instead.

**Comment by nathanlesage** [comment]
Pandoc unfortunately does not support highlighting in export, but Zettlr depends upon Pandoc. The highlighting in Zettlr is something I'm not proud of myself, as close-to-no interpreters correctly interpret these. So the highlighting mainly is intended for use within Zettlr itself, not for exporting. To achieve that, you can use corresponding HTML- or LaTeX-commands, such as `<mark>Highlight</mark>`

**Comment by jimvine** [comment]
Thanks for the response.

As outputting the highlighting is not an option, would it be possible instead to (a) remove the markup characters (`==` or `::`) and, ideally, (b) pop up a message letting the user know that highlighting has been removed on output?

I guess it would be possible to re-use the code that Zettlr uses to identify which text to highlight to do this identification.

And even better might be to have this as an option in settings, like 'Strip formatting unsupported by Pandoc on export?'. Because that would let someone who has the skills to code up highlighting support in a Pandoc lua script or whatever to retain it.

**Comment by nathanlesage** [comment]
> would it be possible instead to (a) remove the markup characters (== or ::)

yup

> (b) pop up a message letting the user know that highlighting has been removed on output?

Nah, you wouldn't want to see it every time you export something!

> I guess it would be possible to re-use the code that Zettlr uses to identify which text to highlight to do this identification.

Nah

> And even better might be to have this as an option in settings, like 'Strip formatting unsupported by Pandoc on export?'

Yah!
