### ISSUE TITLE
Links to local files do not open said files

### ISSUE THREAD

**Issue by tramir** [Zettlr/Zettlr#3562]
### Description

When creating a link to a local file, Cmd+clicking on the link, or clicking on the link in the popup, does not do anything. The link was creating by dropping a file from the Attachments sidebar onto the note, and clicking on the file in the Attachments sidebar opens it in the external application.

### Reproducing

Create a note. Drag a file from the Attachments sidebar onto the note. Cmd+click on the link.

Expected behavior: file is opened in external application

Actual behavior: nothing happens

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterey 12.4

### Additional Information

Same behavior occurs when installing Zettlr via macports.

**Comment by nathanlesage** [comment]
I cannot reproduce this in the current development branch (also on Mac). Would you mind having a look into the logs to see if something was happening? Any error or warning logged? Also, with which file type did you try that? Could you give the exact contents of one such misbehaving link?

**Comment by tramir** [comment]
Thanks for looking into this. I figured out the problem. According to the documentation:

> The relative path is always relative to the document in which you place it. The directory .. tells Zettlr to look for the image in the parent directory (i.e., to traverse up one directory).

This was confusing to me, because typically `..` means "one folder up," i.e., the parent folder of the folder in which the document is located rather than the folder in which the document is located (for which I would have used `.`. Is there any reason for this convention in Zettlr?

**Comment by nathanlesage** [comment]
Zettlr doesn't reinvent conventions, it follows them. A link to `./file.md` will reference a file in the same directory (or folder), a link to `../file.md` references a file one directory up.
