### ISSUE TITLE
Add .qmd as a Markdown extension

### ISSUE THREAD

**Issue by julianmatthewman** [Zettlr/Zettlr#3564]
### Description

Hi, I can't seem to open Quarto markdown (.qmd) files, even after adding .qmd to the list of extensions. These files are markdown-formatted plain text with YAML metadta and code chunks, and I have no problem opening them in notepad or any other markdown editor. Strangely enough, I can open R markdown (.Rmd) files in Zettlr, which are essentially the same type of file.
Thank you!

### Reproducing

Files with the .qmd extension can't be opened and don't appear in the sidebar.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I sometimes really don't get why every idiot needs to put (kind-of) standard Markdown into their own extension ... I mean I can add that as an extension as well so that Zettlr recognizes that, too. Until then, rename them to open them with Zettlr.

**Comment by julianmatthewman** [comment]
The need for custom markdown extensions aside, the reason I reported this as a bug is that the setting where you can "Enter all the file extensions that you want to see in the sidebar." doesn't behave as expected. It lets me add the extension to the list but the files don't show up in the sidebar.

**Comment by nathanlesage** [comment]
> "Enter all the file extensions that you want to see in the sidebar."

Yes, these are non-Markdown files that Zettlr should show you *additionally* in the sidebar (the right side, the left side is the file manager). This is expected behavior, as outlined in the documentation:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/17251683/175559170-4fcd0b20-f760-4d0a-9a63-d68fd92924ea.png">

Let me fix your issue for you real quick.

**Comment by julianmatthewman** [comment]
Ah I see, thanks for clarifying and adding the extension!
