### ISSUE TITLE
Nightly // New Pandoc export behavior

### ISSUE THREAD

**Issue by sewag5** [Zettlr/Zettlr#3567]
### Description

The new export.X works in some cases not as before.
export.html (temp directory): no images are displayed (html source is .\image.jpg)
export.revealjs (any directory): not working at all. Just a html site is displayed in browser

I know, it is in an early state, so I just wanted to tell you, what I saw.

### Reproducing

Use a document you exported before and export it the new way.

### Zettlr Version

Nightly

### Specify version

Tue Jun 28th, 2022 10:56:57

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 21H2 (Build 22000.739)

**Comment by nathanlesage** [comment]
> I know, it is in an early state, so I just wanted to tell you, what I saw.

In that case, screenshots would be helpful. I cannot do anything with what you've just reported here. Describe what steps you are taking, what you are doing, and then what happens.

**Comment by sewag5** [comment]
# Presentation
RevealsJS export:
![image](https://user-images.githubusercontent.com/54976115/176180425-9d872975-293d-4a4c-acd9-944140fa4b6a.png)


Result
![image](https://user-images.githubusercontent.com/54976115/176180688-b10f0de0-a932-4c44-ab1f-f56434f4bb26.png)

Just plain html with no images.
Old export works as expected.

# hmtl to temp folder
html export:
![image](https://user-images.githubusercontent.com/54976115/176181157-d68d044d-c515-4d84-872b-13ec21fa489c.png)

result:
![image](https://user-images.githubusercontent.com/54976115/176181245-fef09293-c7db-46f3-9ae5-0ca84ec9afb2.png)

screen from sourcecode:
![image](https://user-images.githubusercontent.com/54976115/176181604-870953c8-531c-4ced-9503-70357d3dfb44.png)


Hope that helps :-)

**Comment by nathanlesage** [comment]
Yes, these are the "old" profiles — there should be newer ones with more readable names that do the same. Especially for revealJS, the old one is expected to not really work anymore! Would you mind trying that out?

![image](https://user-images.githubusercontent.com/17251683/176205383-91c21dfc-5fba-42c3-ba9e-8258ed07fcc3.png)

**Comment by sewag5** [comment]
Oh, I thought the export.x are the new ones.

Hendrik Erz ***@***.***> schrieb am Di., 28. Juni 2022, 16:31:
