### ISSUE TITLE
Feature: Browser-Support

### ISSUE THREAD

**Issue by ledeniz** [Zettlr/Zettlr#357]
How probable is it that there will be a Zettlr web client? In order to collaborate with other people, one has to be at a desktop computer with the Zettlr client installed. I think it'd be more accessible if there'd be a webapp client.

The first issue that comes to my mind is that there's the chance of overwriting each other, since real-time collaboration is probably really hard to implement. But nonetheless I think it'd be a step forward.

Thanks for the beautiful Zettlr software!

**Comment by nathanlesage** [comment]
Actually, there are already plans to port Zettlr to a web-app capable of facilitating team-efforts. Nevertheless, it's out of bound of the desktop app (which this repository is for) and currently there are no resources to further development.
