### ISSUE TITLE
File name cannot be change in the file manager in combined view

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#3575]
### Description

It is possible to edit the file name, but it cannot be confirmed with enter. After Enter, the file that is on top of files opened outside of Workspaces opens itself. This file is constantly highlighted. After closing all files that are loaded outside a Workspace and trying to rename a file, the same file opens, even though it is no longer visible above Workspace (cache).

Closed files return loaded and visible even after Zettlr reload.

### Reproducing

Reproducing is trivial.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

In fact, when top single file isn't highlighted somehow, the first attempt of other file name change by pressing enter brings coursor to the end of that file name and edition mode is sustained.

I think here is same bug report:
https://www.reddit.com/r/Zettlr/comments/vbus17/cannot_rename_files/

**Comment by exanrauzer** [comment]
Hi! Could we consider this urgent? Every new User downloading Zettlr under Windows now will rather dismiss the program if there is no possibility to file change.

**Comment by nathanlesage** [comment]
Chill, please. You can still rename files in other views so it's not a total deal breaker. I have no resources right now. If you feel this needs to be fixed asap, please give it a try! Otherwise, please be patient until I can get to this.

**Comment by exanrauzer** [comment]
Sure. I just wanted to know how urgent this might be.

**Comment by nathanlesage** [comment]
Works in the current develop branch/nightlies!

**Comment by exanrauzer** [comment]
Thank you!
