### ISSUE TITLE
AutoCorrect automatically changes partial words (ending)

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#3576]
### Description

I have just implemented some AutoCorrect elements to fix common typos with diactric marks  (which are common in my native language as general). For example `się` is always written (being a single word) as `się`, and `sie` (non diacritical `e`) is a grammar error. But many words ends up with `sie` in my native language fe: czasie, lesie, etc and AutoCorrect changes it as well. I thought that AutoCorrect is restricted to exact match. I think it is not desired behavior.

Moreover when a word contains an AutoCorrect element it doesn't change it, fe: dzis is AutoCorrected to dziś but dzisiaj isn't fixed to dziśiaj (and this is desired behavior).

### Reproducing

Reproducing is trivial.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

Already mentioned on Discord:
https://discord.com/channels/609436111860793355/874677388053717052/969869636734685184

**Comment by Joeyata** [comment]
Hello, I‘m interested with this bug. I will look at this issue and raise the PR ASAP.

**Comment by exanrauzer** [comment]
Thank you!

**Comment by exanrauzer** [comment]
@Joeyata any chances to make a PR?

**Comment by exanrauzer** [comment]
Omg! Thank you!

**Comment by nathanlesage** [comment]
Ah crap, remind me that I have to replace `\s` with `\W` at some point otherwise it breaks with brackets and punctuation marks.
