### ISSUE TITLE
Quote after bullet point not properly highlighted

### ISSUE THREAD

**Issue by jonas-sk** [Zettlr/Zettlr#358]
## Description

When creating a quote as a bullet point by typing "* > ", the syntax highlighting fails.

## Reproducing

1. Open a new or existing document
2. Type "* " and see it get transformed into a list and be highlighted in green
3. Now type "> " to add a quote in the same line

## Expected behaviour
Zettlr should have working syntax highlighting for the quote. When exporting, this configuration of a bulleted blockquote works. 

(as a note on the side, does Zettlr not require two line-breaks for bulleted lists to break and instead only one? At least the syntax highlighting suggests it by, upon pressing enter, adding the "*" on the next line and not intending that text under the previous bullet instead)

**Comment by nathanlesage** [comment]
Please direct this issue to the [repository of CodeMirror](https://github.com/codemirror/CodeMirror/issues), as this pertains basic Markdown highlighting, which is fully handled by the `gfm`-mode of CodeMirror. Zettlr only overlays some specials such as tags, highlights, and Zettelkasten-functionality.

What exactly do you refer to with your sidenote? I can't quite follow you there.

**Comment by jonas-sk** [comment]
@nathanlesage Apparently the Markdown part of CodeMirror is not actively maintained anymore https://github.com/codemirror/CodeMirror/issues/6029#issuecomment-586728814

Regarding my side note: Markdown generally requires two new lines for a paragraph break. That means that normally there are two new lines until the next bullet point, so one could hit enter in a list while still staying within the same bullet point. This is possible when removing the bullet point but that looks quite awkward in the preview

**Comment by nathanlesage** [comment]
> Apparently the Markdown part of CodeMirror is not actively maintained anymore

Well, a PR is welcome according to Marijn. I don't have time for that, but please feel free to go forward with this! I'll upgrade CodeMirror asap ;)
