### ISSUE TITLE
Selected text pop-up menu overlaps selected text

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#3580]
### Description

Sometimes selected text pop-up menu ovelaps the text. It is connected with position of the text on screen.

Below link to bug recording.
https://youtu.be/2vrohN0APgk

### Reproducing

Some popup are normal and some overlaps. Try to select random text couple of times or the same text at dif position on screen.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This should no longer be an issue with the new Codemirror implementation!

**Comment by exanrauzer** [comment]
Najs!
