### ISSUE TITLE
Images change the saved position in a document

### ISSUE THREAD

**Issue by davidoskky** [Zettlr/Zettlr#3582]
### Description

If you have a document, you can switch to another tab and come back to it; the position in the document will be the same as when you left it.
If the document contains an image before that position however, the document scrolls down.
This makes it difficult to work on two separate documents if one of the two contains images because the position will keep shifting every time you switch document.

### Reproducing

Create two documents and open them in two separate tabs.
In the first document insert an image at the top, after the image insert enough text to fill the whole screen.
Scroll the screen so that you don't see the image anymore, but you didn't reach the end of the document.
Click on the tab of the second document
Click on the tab of the first document
The position in the document is changed; you can check the first line to ensure you are not in the same position as before.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 pro

### Additional Information

Before and after image

![imagen](https://user-images.githubusercontent.com/13107368/177147643-623eb303-add0-4738-b278-b40cc2bb176e.png)
![imagen](https://user-images.githubusercontent.com/13107368/177147721-8a6c1af1-bf05-4495-b47f-2322f5f84a3d.png)

**Comment by nathanlesage** [comment]
This cannot completely be avoided, but the current nightlies allow several files to be open side-by-side, so if you're working with lots of images and need to go back and forth between documents, you should now be able to do so without any glitches.
