### ISSUE TITLE
Pressing left on keyboard while renaming a file instead collapses the workplace directory

### ISSUE THREAD

**Issue by adrienneteicher** [Zettlr/Zettlr#3583]
### Description

When renaming a file, if the filename is long, sometimes I need to navigate to the start of the file name to change some characters. Normally I can rely on pressing the left mouse button to do this, but in Zettlr pressing left at this moment instead collapses the current workspace in the workspace tree on the left of the Zettlr interface. This makes renaming files challenging.

### Reproducing

1) right click on file, choose rename
2) press left on keyboard

### Zettlr Version

Stable (most recent version)

### Specify version

2.30

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Mac 12.4

**Comment by exanrauzer** [comment]
Yes. Using mouse while editing a filename is an unpleasant feeling.

**Comment by nathanlesage** [comment]
This has been already fixed, but will only come with 3.0.0, since we're currently heavily modifying the codebase.

**Comment by adrienneteicher** [comment]
ah okay. thanks for your work comrade.
