### ISSUE TITLE
Suggested snippet is based on the content of this snippet, not on snippet name.

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#3587]
### Description

I have a snippet :y1 in which I have Yaml section with 'author' (a word that conitains 'ho') and the snippet :hour which brings me current hour (current_hour).

Then while I type :ho the system suggests me the snippet :y1 in the first place (not :hour) because the 'ho' is a part of 'author' inside snippet :y1 yaml content.

Same with snippet :day (which gives me a date, and an hour) - it is also suggested because it contains 'current_hour' (which contains 'ho').

It disallows the fast usage of one- or two-letter snippets, slows down te writing process and breaks the flow.

### Reproducing

Make a snippets :y1 and :ho. Inside :y1 type author and inside :ho type current_hour and check the snippet suggestion after writng :ho

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Works as expected in the v3.0 branch.
