### ISSUE TITLE
Deleting tags in tag cloud does not work

### ISSUE THREAD

**Issue by pizzakinggod** [Zettlr/Zettlr#359]
## Description
Deleting tag by clicking x button in tag cloud pop-up shows exception error.

## Reproducing
Write some tags, open up tag cloud, click x button to delete it

## Expected behaviour
Tag should be removed

**Screenshots**
![](https://i.imgur.com/PdRANb7.png)

## Platform
 - OS: Windows 10 Home
 - OS Version: 1803
 - Zettlr Version: 1.4.2
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Tags cannot be removed from within the tag cloud, the number after the `x`-symbol actually refers to the times they occur within files. But nevertheless, that error shouldn't be there.

**Comment by nathanlesage** [comment]
Fixed.
