### ISSUE TITLE
Both words and signs count and display (document info)

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#3591]
### Description

There are dozens of services that converts characters for words, words for characters, words per page etc. Lets have an ability to see both. This limitation to see only one type of counting seems to me not unnecessary restriction.

### Proposed Changes

Just show the number of words AND the number of characters. And by that - remove unnecessary option from options menu.

### Caveats

No caveats.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
The option is NOT unnecessary since the counting characters was mainly introduced for non-Western symbolic scripts such as CJK, where Whitespace has no semantic meaning. But having both could be an idea, yes. Feel free to provide more info as to where you would like to see that info, how it may look etc etc

**Comment by pvandyken** [comment]
In my context, academic writing (grants, etc) often imposes length restrictions in terms of character count (and sometimes spaces are counted, sometimes not). Seeing both character and word counts would thus be useful for me.

I wonder if the setting could be a toggle, so you can toggle on/off both word and character count. You could have an additional toggle to show character incl. spaces (giving two separate character counts), or you could have a checkbox indicating whether the single character count should include spaces. Either way, in the UI the counts would be displayed side-by-side in the current location, with maybe a `,` between them.

**Comment by nathanlesage** [comment]
The indicator in the toolbar is simply too small to usefully display both. To a certain degree, this has upset me as well, but in the current betas, there's a new statusbar. That one has plenty of space for displaying all kinds of information, and one is that both word and character count is being displayed. I can also show both in the document info popup, but the toolbar position is too small, as I said.

**Comment by pvandyken** [comment]
I actually didn't realize till just now that I could click on the word count to get a popup with the character information. That's good enough for my purposes.

**Comment by exanrauzer** [comment]
This issue is no longer relevant since the status bar exists.
