### ISSUE TITLE
Middle Mouse Button in File Manager Buggy

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3594]
### Description

Clicking with the MMB on a file in file manager is supposed to open the file in a new tab.
Instead the mouse turns into the scolling icon (same behaviour when clicking mmb somewhere in the web browser).

Unfortunately I can't provide a screenshot, since the mouse turns back to normal as soon as the screenshot starts.

### Reproducing

As I wrote my comment here #3387 it still worked without problems. Unfortunately I don't have a second device at hand to reproduce.

### Zettlr Version

Nightly

### Specify version

2.3.0 latest nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
No worries. But I do have two more questions now: Workspace …? What `>`-button are you referring to?

**Comment by nathanlesage** [comment]
ah well, yeah, you can't really middle-mouse-click those chevrons, but I think I can just disable middle mouse buttons there so that the app doesn't start to scroll.

**Comment by nathanlesage** [comment]
Should work better now I hope
