### ISSUE TITLE
Toggle sidebar does not work correctly

### ISSUE THREAD

**Issue by petzi53** [Zettlr/Zettlr#3606]
### Description

As far as I understood, the sidebar should toggle between the right side panel, global search, and back (closing the right side panel). 

### Reproducing

On my app 

- the first click on the toggle sidebar icon (three columns) opens the right-side panel with TOC, References, Related Files, and Other Files (Attachments) (That seems ok for me!)
- the second click closes the right side panel (?)
- the third click does nothing (?)
- the fourth click starts the process again, e.g., opens the right side panel. (OK!)

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0.

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterey 12.4.

**Comment by nathanlesage** [comment]
This was a bug due to some stupidity on my side. But fortunately, I have already fixed that in one of the more recent commits. However, it may be that it will take a while to ship. But rest assured: it's fixed!
