### ISSUE TITLE
Tasklists/checkboxes cause Editor to go blank or to show duplicate lines

### ISSUE THREAD

**Issue by Xezarior** [Zettlr/Zettlr#3612]
### Description

This bug is similar to #3368 and #3462, but more general.

Files containing markdown tasklists or checkbox-lists (like `- [ ] item`) break the editor view of Zettlr on my system.
**None of these problems concern the quicklook. This always does work correctly. I overlayed it in the screenshots for comparison.**

1. Adding a tasklist via the "tasklist" button of the toolbar correctly inserts `- [ ] ` but does not show it and also hides the following user-input. The input is recorded but weirdly duplicated (like `test` to `tttetetestestesttest`) and written to file on save, but not shown. Closing and reopening the file doesn't help. Closing and expanding the section causes it to be displayed twice. See Screenshot below.
![image](https://user-images.githubusercontent.com/9007496/179357540-2bd568cf-23ed-47e9-b2da-7f58c921d21e.png)
Content of the file at this point:
```
# test
test
- [ ] tttetetestestesttesttest
```
Switching between files at this moment can cause the view-duplication to go further and further, never showing the other file's contents. The behavior continues every time the file is loaded.

2. Loading a pre-made file with a more complete tasklist (that is, supposedly more syntactically correct) causes the second appearance the problem takes: an empty editor view where text is invisible/hidden but somehow selectable.
![image](https://user-images.githubusercontent.com/9007496/179358108-9f0f3daa-dc64-4dbd-a36e-1fde556539b9.png)
This files contains:
```
# test
test

- [ ] tttetetestestesttesttest
- [ ] test2

.
```
as I hoped it would somehow "close" the open tasklist completely.

3. Writing a tasklist manually. This causes the same behavior as (1), but freezing on the closed bracket `]`:
![image](https://user-images.githubusercontent.com/9007496/179358221-156f6f25-66ac-456b-95a6-b1d9833b10fe.png)
Contents of the file after saving in Zettlr:
```
# test
test
- [ ]   t t te tes tes test test
```
The duplication is apparently made for each new character that I input (`test`). (Note: the screenshot does not show exactly this as it was from a previous attempt where I didn't write exactly that.)

### Reproducing

I could not find a way to create a functioning tasklist without causing this bug. 
Therefore, the reproducing steps are simply:

1. Have Zettlr closed.
2. Create an empty directory.
3. Open it as a workspace in Zettlr.
4. Create a new file in Zettlr.
5. Type the inputs described above. For (2): create the file beforehand with another editor.
6. Try around: closing/reopening the file(s) or Zettlr, saving them (CTRL+S)... I deleted each file between each of the three variants.
7. Monitor the contents of the files written by Zettlr in another editor (in my case: Notepad++).

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 

### Additional Information

I am very keen on seeing these bugs fixed, as they currently make it impossible for me to use Zettlr. I rely heavily on tasklists and did so already on all my previous notes. Currently, using a different software is the easiest for me, but I want to switch to Zettlr one day.
From my perspective, this bug is critical.

I had no need for Zettlr for around 2-3 years. Before that, Checkboxes worked as expected. I do not remember the version number from then. Maybe it even was the portable version.
But 6 months to a year-and-a-half ago I installed the then-current stable and the problems occured. The following updates up to now have not fixed the problem.

I'll gladly give more information if needed.
This is my first public Issue on this sort of project, I am open for constructive criticism.

**Comment by nathanlesage** [comment]
This should be fixed with the new Codemirror v6 implementation.

**Comment by Xezarior** [comment]
I just tested the nightly from Tue Jan 3rd, 2023 17:13:45.
It works!
I can successfully write tasklists (both manually and via toolbar button), and it now loads my existing files containing tasklists!

Thank you for the great work and for closing the issue. This is really great news for me at this start of 2023!
