### ISSUE TITLE
Can't open Zettlr 2.3.0 on MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by manbaum** [Zettlr/Zettlr#3615]
### Description

Drag the App into the Application folder, then open it, It crashes immediately, Mac OS crash report appears automatically.

### Reproducing

Double click to open the App.

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr-2.3.0-x64.dmg

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS Sierra 10.12.6

### Additional Information

The following is the crash report generated by MacOS. (partial, because of the 64k limit)

Process:               Zettlr [6094]
Path:                  /Applications/Zettlr.app/Contents/MacOS/Zettlr
Identifier:            com.zettlr.app
Version:               2.3.0 (2.3.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Zettlr [6094]
User ID:               501

Date/Time:             2022-07-18 11:19:46.979 +0800
OS Version:            Mac OS X 10.12.6 (16G2136)
Report Version:        12
Anonymous UUID:        341F4AED-FC7A-4492-5B78-AF5DF72D47E2

Sleep/Wake UUID:       8C8F98A0-CC04-45C8-918A-73B3EA456176

Time Awake Since Boot: 2600000 seconds
Time Since Wake:       250000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [0]

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x0000000112625634 node::AsyncResource::get_async_id() const + 19903812
1   com.github.Electron.framework 	0x000000010ee9c3f5 v8::internal::CallInterfaceDescriptor::IsValidFloatParameterRegister(v8::internal::Register) + 67077
2   com.github.Electron.framework 	0x000000010ed37c45 v8::internal::SpaceIterator::~SpaceIterator() + 28325
3   com.github.Electron.framework 	0x000000010ed946e6 v8::CodeEventHandler::~CodeEventHandler() + 174150
4   com.github.Electron.framework 	0x000000010ed945a8 v8::CodeEventHandler::~CodeEventHandler() + 173832
5   com.github.Electron.framework 	0x000000010fd5655b v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12651
6   ???                           	0x0000004907f0aa38 0 + 313665825336
7   ???                           	0x0000004907e8c862 0 + 313665308770
8   ???                           	0x0000004907e8c862 0 + 313665308770
9   ???                           	0x0000004907e8c862 0 + 313665308770
10  ???                           	0x00000049000d2c9f 0 + 313533475999
11  ???                           	0x0000004907e8a89c 0 + 313665300636
12  ???                           	0x0000004907e8a5c7 0 + 313665299911
13  com.github.Electron.framework 	0x000000010fe2641c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 684
14  com.github.Electron.framework 	0x000000010fd07049 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 713
15  com.github.Electron.framework 	0x0000000115335768 node::CallbackScope::~CallbackScope() + 2184
16  com.github.Electron.framework 	0x0000000115335a53 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) + 195
17  com.github.Electron.framework 	0x000000010ee6bd8d v8::CodeEvent::GetScriptName() + 171933
18  com.github.Electron.framework 	0x000000010edbdbfd v8::CodeEventHandler::~CodeEventHandler() + 343389
19  com.github.Electron.framework 	0x000000010edaa78d v8::CodeEventHandler::~CodeEventHandler() + 264429
20  com.github.Electron.framework 	0x000000010edaa86d v8::CodeEventHandler::~CodeEventHandler() + 264653
21  com.github.Electron.framework 	0x000000010ede03ca v8::CodeEvent::GetCodeSize() + 4090
22  com.github.Electron.framework 	0x00000001118ff25e node::AsyncResource::get_async_id() const + 6115694
23  com.github.Electron.framework 	0x000000010ede06cb v8::CodeEvent::GetCodeSize() + 4859
24  com.github.Electron.framework 	0x0000000111e853f8 node::AsyncResource::get_async_id() const + 11907848
25  com.github.Electron.framework 	0x0000000111e89695 node::AsyncResource::get_async_id() const + 11924901
26  com.github.Electron.framework 	0x0000000111e869ed node::AsyncResource::get_async_id() const + 11913469
27  com.github.Electron.framework 	0x00000001120a922f node::AsyncResource::get_async_id() const + 14151999
28  com.github.Electron.framework 	0x0000000111b4557e node::AsyncResource::get_async_id() const + 8500366
29  com.github.Electron.framework 	0x0000000111b63379 node::AsyncResource::get_async_id() const + 8622729
30  com.github.Electron.framework 	0x0000000111ba29c5 node::AsyncResource::get_async_id() const + 8882389
31  com.github.Electron.framework 	0x0000000111ba1b32 node::AsyncResource::get_async_id() const + 8878658
32  com.github.Electron.framework 	0x0000000111ba20ff node::AsyncResource::get_async_id() const + 8880143
33  com.apple.CoreFoundation      	0x00007fffcbb43e51 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
34  com.apple.CoreFoundation      	0x00007fffcbb250cc __CFRunLoopDoSources0 + 556
35  com.apple.CoreFoundation      	0x00007fffcbb245b6 __CFRunLoopRun + 934
36  com.apple.CoreFoundation      	0x00007fffcbb23fb4 CFRunLoopRunSpecific + 420
37  com.apple.HIToolbox           	0x00007fffcb082ebc RunCurrentEventLoopInMode + 240
38  com.apple.HIToolbox           	0x00007fffcb082cf1 ReceiveNextEventCommon + 432
39  com.apple.HIToolbox           	0x00007fffcb082b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
40  com.apple.AppKit              	0x00007fffc9617a04 _DPSNextEvent + 1120
41  com.apple.AppKit              	0x00007fffc9d937ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
42  com.apple.AppKit              	0x00007fffc960c38b -[NSApplication run] + 926
43  com.github.Electron.framework 	0x0000000111ba32d6 node::AsyncResource::get_async_id() const + 8884710
44  com.github.Electron.framework 	0x0000000111ba1ba2 node::AsyncResource::get_async_id() const + 8878770
45  com.github.Electron.framework 	0x0000000111b63d0a node::AsyncResource::get_async_id() const + 8625178
46  com.github.Electron.framework 	0x0000000111b2da11 node::AsyncResource::get_async_id() const + 8403233
47  com.github.Electron.framework 	0x0000000110e353c4 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5185924
48  com.github.Electron.framework 	0x0000000110e36d02 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5192386
49  com.github.Electron.framework 	0x0000000110e32ad0 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5175440
50  com.github.Electron.framework 	0x000000010efee7a5 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 1957
51  com.github.Electron.framework 	0x000000010efef973 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 6515
52  com.github.Electron.framework 	0x000000010efef3f1 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 5105
53  com.github.Electron.framework 	0x000000010efed9ad v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 12173
54  com.github.Electron.framework 	0x000000010efee2e3 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 739
55  com.github.Electron.framework 	0x000000010ed20548 ElectronMain + 152
56  libdyld.dylib                 	0x00007fffe176c235 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0xfffffffffffffffd  rbx: 0x0000000000000000  rcx: 0x832ed390c1570074  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x00007fffca23b5b5  rbp: 0x00007fff552f0530  rsp: 0x00007fff552f04d0
   r8: 0x00000000080023b9   r9: 0xffffffffffff3d90  r10: 0x000000010ecba110  r11: 0x00007fffcc240a35
  r12: 0x00007fc2cf853800  r13: 0x00007fff552f0770  r14: 0x0000000000000000  r15: 0x00007fffe0e29000
  rip: 0x0000000112625634  rfl: 0x0000000000000246  cr2: 0x000000010ee9c3b0
  
Logical CPU:     2
Error Code:      0x00000000
Trap Number:     3

VM Region Summary:
ReadOnly portion of Libraries: Total=443.3M resident=0K(0%) swapped_out_or_unallocated=443.3M(100%)
Writable regions: Total=374.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=374.0M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        2 
Activity Tracing                   256K        2 
CG backing stores                  560K        4 
CG image                            24K        7 
CoreAnimation                       16K        3 
CoreUI image data                  384K        4 
CoreUI image file                  184K        5 
Foundation                          32K        3 
IOKit                             15.5M        2 
Kernel Alloc Once                    8K        2 
MALLOC                           106.8M       39 
MALLOC guard page                   48K       10 
Mach message                        24K        4 
Memory Tag 242                      12K        2 
Memory Tag 253                    32.0G       32 
Memory Tag 255                     4.0G       32 
OpenGL GLSL                        256K        4 
STACK GUARD                       56.1M       36 
Stack                            219.3M       38 
VM_ALLOCATE                       5688K       28 
__DATA                            37.8M      277 
__GLSLBUILTINS                    2588K        2 
__IMAGE                            528K        2 
__LINKEDIT                       120.9M       14 
__TEXT                           322.4M      280 
__UNICODE                          556K        2 
dylib (reserved)                    64K        2         reserved VM address space (unallocated)
mapped file                       69.1M       17 
shared memory                     16.4M       12 
===========                     =======  ======= 
TOTAL                             37.0G      838 
TOTAL, minus reserved VM space    37.0G      838 

Model: MacBookPro8,1, BootROM 87.0.0.0.0, 2 processors, Intel Core i5, 2.3 GHz, 8 GB, SMC 1.68f99
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353237334348302D4348392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353237334348302D4348392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 5.0.5f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Samsung SSD 860 EVO 1TB, 1 TB
Serial ATA Device: OPTIARC DVD RW AD-5970H
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB2.0 Hub
USB Device: G102 LIGHTSYNC Gaming Mouse
USB Device: Varmilo
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1

**Comment by nathan-artist** [comment]
I too tried installing Zettlr-2.3.0-x64.dmg on on MacOS Sierra 10.12.6, and the application would not launch; it would only crash immediately. This is a problem because the Zettlr documentation says that macOS 10.11 or newer is supported.

**Comment by nathanlesage** [comment]
I am going to close this issue accordingly as the others, since there is nothing I can do to remedy this.
