### ISSUE TITLE
Problem with links containing parantheses

### ISSUE THREAD

**Issue by tobiaswjohn** [Zettlr/Zettlr#3620]
### Description

There seems to be sometimes a problem, if a link, e.g. a url, contains parentheses; even if the link is well-formed, i.e. there is a closing parenthesis for every opening one. 

### Reproducing

I tried to add a link to wikipedia like this:
`[bounded lattice](https://en.wikipedia.org/wiki/Lattice_(order)#Bounded_lattice)`
If I try to open the link, Zettlr tries to open `https://en.wikipedia.org/wiki/Lattice_(order#Bounded_lattice)`. For some reason, the first parenthesis gets deleted instead of the last one.

### Zettlr Version

Stable (but an older version)

### Specify version

2.2.6

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04.4 LTS

**Comment by nathanlesage** [comment]
Interesting find. This sounds like a minor bug in the parenthesis-detection algorithm. If anyone wants to have a look, look no further than here:

https://github.com/Zettlr/Zettlr/blob/3e2158f367da92432953a4840f8afff8e7be7675/source/common/modules/markdown-editor/plugins/render-links.ts#L88-L116
