### ISSUE TITLE
Randomly created filename of pasted image used as Zettelkasten ID

### ISSUE THREAD

**Issue by rakta** [Zettlr/Zettlr#3626]
### Description

# Behaviour

When pasting an image from clipboard, Zettlr randomly creates a filename containing 32 hex characters. In my case, the filename by coincidence contained 14 subsequent numeric characters, which Zettlr conts as an ID. 

The random image filename is:
![48326653126464d3d95dc6126ff80e16.png](48326653126464d3d95dc6126ff80e16.png)

The link to the note containing the image is thus
[[48326653126464]] instead of the filename [[20220719_asdf]]

# Probability for a 32 character hex string to contain a valid zettlr ID

The probability for 14 subsequent hex characters to be numeric is $(10/16)^{14}$, while in a 32 digit string, there are 19 possibilities for such a numeric string, resulting in a probability of $19 (10/16)^{14} = 0.026$. 
However 15 or more subsequent numeric characters also contain a valid ID, resulting in a probability of $19 (10/16)^{14} + 18 (10/16)^{15} + [...] + 1 (10/16)^{32} = 0.064$
If i am right, the probability of a random image filename to contain a valid zettlr ID is thus **6,4%**

# Expected Behaviour

Pasting an image from clipboard should not result in maybe assigning a random ID.

# Possible solutions
Adapt the algorithm which is creating filenames to exclude filenames containing a valid ID.

### Reproducing

The bug occurs with a probability of 6.4% when inserting an image from clipboard into a note.

### Zettlr Version

Stable (but an older version)

### Specify version

2.2.4

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04 LTS

**Comment by nathanlesage** [comment]
I just saw this issue: 6.4% is relatively low and imo in a good range. So I think that is fine. (See this as a prompt to name your images properly, this hash is just a default placeholder).
