### ISSUE TITLE
Internal "File name" links contains .md extension

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3630]
### Description

If parameter `"linkFilenameOnly"` is set to `true` or if the linked file don't have any ID.

Internal link contain `.md` extension if it is made from Zettlr file explorer (by drag and drop).

Normally, there is no extension in the link, for instance if it is done by select in the dynamic list opened by typing `link start` characters of internal link (`[[` by default).

### Reproducing

Create a note named `My-note.md` using `CTRL+N` then `CTRL+R`.

Type the start link characters (`[[` by default) and select `My-note`.
You get the followed link : `[[My-note]]`

In the Zettlr file explorer (left panel), drag and drop `My-note`.
You get the followed link : `[[My-note.md]]`instead of `[[My-note]]`.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04.4 LTS

**Comment by etienne-tr** [comment]
By right-clic on a file tab, and select `Copy file name`, I get the file name with its `.md` extension. If, as for the `Copy ID` action, it helps to make links by hand, it should not contain the extension.

**Comment by etienne-tr** [comment]
It would fit there is no file shown in Zettlr file tabs or file explorer but `md` one.
