### ISSUE TITLE
Table export to html

### ISSUE THREAD

**Issue by fuadlabgit** [Zettlr/Zettlr#3641]
### Description

The table editor looks awesome but there seem to be some minor bugs when the table is changed. If I export to html (I also have some short TeX code in my table and also want to include references), the formatting is not always updated. maybe its I dont know what I should do to make it work... I just make the table (it looks nice in Zettlr). on export, the table looks different (?). It might also be because Zettlr does something weird to the "\" letter.

### Reproducing

In Git the table also looks nice: 

| Parameter     | Value | Description                                                |
|---------------|-------|------------------------------------------------------------|
| $\theta_{CX}$ | 0.5   | share of labor                                             |
| $\theta_{CZ}$ | 0.5   | share of leisure                                           |
| $\alpha_{TZ}$ | 0.5   | leisure parameter of household                             |
| $\alpha_{TL}$ | 0.5   | leisure/labor parameter of household                       |
| $\theta_{XV}$ | 0.97  | share of value added in the $X$ sector                     |
| $\theta_{XS}$ | 0.096 | cost share of energy services in the $X$ sector            |
| $\theta_{VL}$ | 0.5   | cost share of labor in value added sector                  |
| $\theta_{VK}$ | 0.5   | cost share of capital in value added sector                |
| $\alpha_X$    | 0.97  | share of capital in $X$ sector                             |
| $\alpha_E$    | 0.03  | share of capital in $E$ sector                             |
| $\sigma_X$    | 0.5   | elasticity in $X$ sector between value added and services (Ballard 2000)  |
| $\sigma_C$    | 0.4   | elasticity between consumption and leisure                 |
| $\sigma_V$    | 0.5   | elasticity between labor and capital                       |

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

### Additional Information

Doesnt seem to be a matter of windows version

**Comment by nathanlesage** [comment]
Could be a problem with the Pandoc export? There is, for example, the issue that for Pandoc the lengths of the columns actually has a meaning, and it tends to produce weird looking tables if you have too much content in the cells. It's a tad difficult to implement, but I'll see to it later. (Or someone else with time can surely open a PR)

**Comment by nathanlesage** [comment]
I just tested this out - works as expected, so the bug possibly got fixed along the way!
