### ISSUE TITLE
Keybing to automaticaly add code block when I paste

### ISSUE THREAD

**Issue by Camiyo** [Zettlr/Zettlr#3643]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Have a keybing to automaticaly add code block when I paste something.
This will save us a lot of time.

### Example Workflow

I got this in my clipboard : 

#!/bin/bash
echo -n "hello"

I press "CTRL + SUPER + V" and it pastes this :

\```
#!/bin/bash
echo -n "hello"
\```

### Caveats

No caveats I suppose

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
There is already a way to do so:

Simply create a snippet that inserts a code block and automatically inserts the contents of your clipboard using the clipboard variable. Read more here: https://docs.zettlr.com/en/core/snippets/
