### ISSUE TITLE
Allow scrolling down to slightly below existing text

### ISSUE THREAD

**Issue by jpeacock29** [Zettlr/Zettlr#3647]
### Description

It's nice to have an uncluttered screen for writing or continuing to write something you're working on. So users might want to scroll so only the last few lines of the text they wrote are visible. This could probably be enabled all the time without inconveniencing anyone.

Currently, one can only add many empty lines after their text to allow scrolling down. Alternatively, typewriter mode allows scrolling further down but resets the text position to the middle of the screen when you type.

### Proposed Changes

Allow the user to scroll just past the bottom of the written text.

### Caveats

Nothing comes to mind.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

MacOS Big Sur

**Comment by nathanlesage** [comment]
This is a great idea for a custom CSS adaptation. The editor itself has a bottom and top margin. Those are, e.g., also increased when you activate typewriter mode. Feel free to play around with the corresponding CSS rules a little bit. The documentation can be found here: https://docs.zettlr.com/en/core/custom-css/

**Comment by jpeacock29** [comment]
Thanks for this suggestion! Implementing myself is beyond my (non-existent 😄) CSS skills, but I will leave my non-functional attempt here in case it's a useful breadcrumb for someone else to take up the task:

```
#editor .CodeMirror-scroll {
  padding-bottom: 100vh;
}

#editor .CodeMirror {
  margin-bottom: 100vh;
}

#editor {
  bottom-margin: 100vh; 
}
```

**Comment by exanrauzer** [comment]
Enhancement is mentioned on Discord as well:
https://discord.com/channels/609436111860793355/874677388053717052/996489702427340920

**Comment by nathanlesage** [comment]
> One thing is the default padding for continuous writing and the other thing is the ability to scroll beyond that line to have the text more on top of the screen.

That is literally both the same. Zettlr is not a simple code-editor, the paddings are adjusted so that it feels more like actual writing. Enabling "scroll to last line" by increasing the padding is a user-preference that can be enabled with custom CSS, but should not be part of the main app's feature set.
