### ISSUE TITLE
New notes are ignored until the app is restarted

### ISSUE THREAD

**Issue by lillemets** [Zettlr/Zettlr#3648]
### Description

I would like to use Zettlr on a Chromebook and have notes synced via Google Drive. 

To do this, I run Zettlr in ChromeOS where (as I understand) it runs in a Linux container. When I open a directory that is inside the container then Zettlr runs fine. However, when I open a ChromeOS directory that is shared with Linux, I can save new notes but they do not appear in the file tree nor can they be linked. New notes only appear after Zettlr is restarted. 

The fact that the shared directory is mounted in the container might cause the issue, but I'm not sure why it would. It is related to the way Zettlr updates its note "database" but I have not found any information on how that works.

### Reproducing

Run Zettlr in ChromeOS and open a shared folder.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Debian 11 and ChromeOS

**Comment by nathanlesage** [comment]
A shared container may be causing this iff the container is mounted after Zettlr has already been started. From what you describe in this issue, the problem could come from anywhere, so it would be great if you could share logfiles. If the container couldn't be found, etc., there should be warnings/errors. Also, if new files are detected in some loaded folder, you should see an info message in this regard.

**Comment by lillemets** [comment]
The logs contain just a few warnings and an error. The warnings seem to hint to the slow speed of loading the workspace:

```
[21:26:31] [Warning] [FSAL Directory] Path /mnt/chromeos/GoogleDrive/MyDrive/note took 2082.474264997989ms to load.
[21:26:31] [Warning] [FSAL] Path /mnt/chromeos/GoogleDrive/MyDrive/note took 2101ms to load.
[21:26:31] [Info] [FSAL] Loaded all files and workspaces in 2.156995140001178 seconds
```

When I create and attempt to save a new note, it is saved but followed by an error:

```
[21:27:11] [Info] Saving file 20220731212644.md...
[21:27:17] [Info] Saving file to /mnt/chromeos/GoogleDrive/MyDrive/note/1Index/20220731212644.md...
[21:27:23] [Info] [Stats Provider] Writing statistics to file
[21:27:23] [Info] File 20220731212644.md saved.
[21:27:23] [Error] [R] [Main Window] The descriptor for path /mnt/chromeos/GoogleDrive/MyDrive/note/1Index/20220731212644.md was empty! (index.js:2)
```
The last line could explain the issue. The error message seems be be specific to Zettlr so I'm not sure how to proceed.

**Comment by nathanlesage** [comment]
Ah, the last error message indicates that the descriptor has been loaded but wasn't available in the main window. Just to be sure, let's try the following steps:

1. Activate debug mode if not already done
2. Do what you normally do, but when the file doesn't show up, click the reload item in the develop menu
3. If the file then shows up, quit Zettlr, and, in the data directory, remove the complete fsal folder, then try again. That might solve it.
