### ISSUE TITLE
Solarized theme

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#365]
Would be nice to have a solarized theme as explained in https://ethanschoonover.com/solarized/

**Comment by nathanlesage** [comment]
The theme looks pretty well-written. It's actually a good update. Maybe even for the Bielefeld-theme? I'm not sure, but I've written the Bielefeld with this solarised in mind (but more because it resembled yellowed paper).

Nevertheless, there's no such thing as too many themes, so it sounds like something to keep in mind! Anyways, it might take some time, as I'm hesitant to blindly implement this without having the revamp of the app itself :)

**Comment by nathanlesage** [comment]
Quick question, because this just crossed my mind: Is there anything speaking against simply applying these solarized colours to the Bielefeld theme? I've never been happy with that fruity-orangy tone of the theme, and this would enable us to kill two birds with one stone

**Comment by ploum** [comment]
take my vote ;-)

**Comment by nathanlesage** [comment]
fyi, I just used the solarized theme to provide basic syntax highlighting to the revealJS and HTML exports!

**Comment by ploum** [comment]
Maybe discussions about themes should be separate from the bug tracker? I don't know. It is so subjective and it changes so frequently.

**Comment by nathanlesage** [comment]
> Maybe discussions about themes should be separate from the bug tracker? I don't know. It is so subjective and it changes so frequently.

Yep, I think that the forum is the best way to discuss themes, whereas PRs can then integrate them … which reminds me that actually, re-doing the Bielefeld theme with solarized colours is super easy, but I'm not motivated atm because of all the other issues …

**Comment by grst** [comment]
More generally, can't the color palettes just become a configuration option in the settings instead of having hard-coded themes?
For instance, a field where to paste some CSS. Like that "unofficial" themes could be shared easily.

**Comment by nathanlesage** [comment]
> More generally, can't the color palettes just become a configuration option in the settings instead of having hard-coded themes?

This is certainly possible. But before we could make this happen, I'd like to have the themes "standardized" so that this incorporation is easy and not prone to errors.

> For instance, a field where to paste some CSS. Like that "unofficial" themes could be shared easily.

You mean [Custom CSS](https://docs.zettlr.com/en/core/custom-css/)?

**Comment by cloudhan** [comment]
How about support VSCode's theme plugin directly, reuse all of them might be possible?

**Comment by nathanlesage** [comment]
> How about support VSCode's theme plugin directly, reuse all of them might be possible?

Impossible, as VSCode uses Monaco as a code editor, not CodeMirror. Besides, the colors, class names and IDs will be totally different.
