### ISSUE TITLE
Wrong download link for deb64 link?

### ISSUE THREAD

**Issue by ardref** [Zettlr/Zettlr#3650]
### Description

https://www.zettlr.com/download/deb64 downloads the Zettlr-2.3.0-amd64.deb package!

Is that correct? It doesn't install properly on my Ubuntu laptop!

### Reproducing

Using https://www.zettlr.com/download & and DEBIAN (X86_64) link.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04.4 LTS

**Comment by nathanlesage** [comment]
Yes, deb64 should download the 64bit AMD Debian package for Zettlr, so yes, this is correct. Could it be you're accidentally running a 32bit OS?
