### ISSUE TITLE
Italics format mark (underscore) still appear in certain case when Render emphasis enabled

### ISSUE THREAD

**Issue by radifar** [Zettlr/Zettlr#3659]
### Description

Ideally when we enable `Render emphasis` both format mark for Italics or Bold get hidden. But I found a specific use case that prevent the format mark from hiding.

### Reproducing

In Preferences > Editor I use double asterisk as Bold and single underline as Italics formatting characters.

Write some text in Zettlr, some have underscore in the middle (e.g. food_list, cook_good_food). Formatting Italics to usual text is fine, but for `food_list` or `cook_good_food` the formatting character still appear so it will appear italics with leading and trailing underscore (as if `Render emphasis` got disabled)

### Zettlr Version

Nightly

### Specify version

2.3.0+nightly-20220801

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 36

**Comment by radifar** [comment]
Just found out that the same happen with Bold emphasize. So when I bold a phrase that contain underline in it the formatting character will not be hidden.

**Comment by nathanlesage** [comment]
This is a problem with our current implementation. I couldn't find the correct issue quickly, but there is one already open. I will not tackle this while still on CodeMirror 5, but I will fix it for the next CodeMirror 6, which I'll be implementing going forward (no ETA, unfortunately).
