### ISSUE TITLE
Alternate fonts & 'visual mode' 

### ISSUE THREAD

**Issue by ashprice** [Zettlr/Zettlr#366]
Is it possible to have alternate fonts used by Zettlr? 

The main reason I ask, is not, in fact, so one may pick _any_ font - rather, with the current font, I am struggling to distinguish an \<i\> from an <í> which can be extremely problematic writing in my L2.

The second thing I would be interested in would be a 'visual mode'; similar to how it is implemented in vim. I would certainly not want all vim features and bindings (or I'd be using vimǃ), but being able to quickly navigate the document by escaping and using a particular keybind would be useful in absence of having some more visual way of doing this (such as the sidebar 'overviews' common to many IDEs and editors such as Sublime. The equivalent keybinds in vim would be things like <)> to move forward a sentence; <}> to move forward a paragraph, etc. 

Personally, I think such 'overviews' are needlessly intrusive and complicated when a keyboard-driven solution suffices, but there may be an interest from others in it as a toggle-able feature more generally. 

Big fan of everything so far - thanks for the hard work!

**Comment by ashprice** [comment]
Another useful feature would be consistent numbering of footnotes. Say I move a paragraph back a few, or write a new one before some other one. It would make sense for the footnote for this paragraph to have a lower number than those following it.

**Comment by nathanlesage** [comment]
Automatic footnote renumbering is something quite difficult to achieve, as it requires the whole document's contents to be read in as an AST, before moving to ensure consistent behaviour. Additionally, as these footnotes will be correctly numbered on output (b/c Pandoc also performs AST operations), this enhancement has an extremely low priority.

Concerning the fonts: Please consider using Custom CSS for that matter: https://docs.zettlr.com/en/core/custom-css/

On potential namespacing problems (= the fonts not being loaded albeit specified in certain themes) cf. the corresponding issues (currently closed, keep that in mind while searching!)

The vim-keybindings also have an open issue somewhere in the issue tracker so the second part seems duplicate. If there's anything else, please feel free to comment further!
