### ISSUE TITLE
`Reset zoom` is not available when `Zoom behavior` is set to `Zoom changes the editor font size`

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#3663]
### Description

`View > Reset zoom` is not available when `Preferences > Advanced > Zoom behavior` is set to `Zoom changes the editor font size`

### Reproducing

* Set `Preferences > Advanced > Zoom behavior` to `Zoom changes the editor font size`.
* Change the zoom level of a note in the editor using `Ctrl-+` or `Ctrl--`.
* Attempt to mouse over the `View > Reset zoom` menu item.

The `View > Reset zoom` menu item does not highlight while moused over and and cannot be selected.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

`pacman -S zettlr` (Manjaro Community repo)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
Heya! I just discovered this issue, sorry for not seeing it earlier :D 

This is expected behavior as there is no "default" editor font size (you can change it in the preferences), so there is no inherent meaning of "resetting" the "zoom".
