### ISSUE TITLE
`Ctrl-0` keyboard shortcut is dead; does not reset zoom level

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#3664]
### Description

When `Preferences > Advanced > Zoom behavior` is set to `Zoom resizes the whole GUI`, the keyboard shortcut (`Ctrl-0`) for `Reset zoom` does not work. The zoom level is not reset and hitting `Ctrl-0` does not execute any action, so far as I can tell.

Selecting the same action from the menu (`View > Reset zoom`) works as expected.

_Note that this issue is separate from the [other bug report I filed](https://github.com/Zettlr/Zettlr/issues/3663), in which `View > Reset zoom` does not work at all when `Preferences > Advanced > Zoom behavior` is set to `Zoom changes the editor font size`._

### Reproducing

* Set `Preferences > Advanced > Zoom behavior` to `Zoom resizes the whole GUI`.
* Change the zoom level of a note in the editor using `Ctrl-+` or `Ctrl--`.
* Type `Ctrl-0`.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

`pacman -S zettlr` (Manjaro Community repo)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
Could you try this with one of the nightlies please? For me it worked fine just now.

**Comment by nathanlesage** [comment]
I suppose this is now fixed…? If not, feel free to comment.
