### ISSUE TITLE
Navigate back to original Zettel where link click was referred from?

### ISSUE THREAD

**Issue by namanyayg** [Zettlr/Zettlr#367]
Hey

Thank you so much for making such a wonderful and speedy product! Love it, massive productivity gains from a short duration of use already.

I was wondering if there's anything like a "back" functionality after clicking on a link -- it seems like it launches a search, and if the Zettel is linked at multiple places, the sidebar can become quite difficult to navigate and we can lose track of the original Zettel we were referred from.

Is there a "back" functionality like in web browsers that I'm missing somewhere? How does one return to the source zettel after checking a referencing a leaf zettel to continue their review?

**Comment by nathanlesage** [comment]
There's currently no Back-functionality implemented. This is because I tend to also add a backlink to the outlines to my notes (so that I can click on links in both places). But it does seem we could improve here.

**Comment by namanyayg** [comment]
I see -- how do you manage many links to a single file in this case? How can this be managed if one leaf has multiple parents and siblings linking to it? 

Do you not create many to one relations? Or do you add all incoming links like trackbacks to the bottom of each file?

**Comment by nathanlesage** [comment]
Yeah, I only link back to the outline itself, not to other referring notes. Actually, I kind of like the fact that I'm unable to return, because this way I have to keep looking to everything listed at the side ;)

**Comment by namanyayg** [comment]
Ah, thanks for sharing your workflow. And the sidebar is just timestamped filenames right? Or is there some way to include additional metadata like the title or tag name in the sidebar itself?

I'm basically trying to figure out a better way to navigate and "revise" my zk, currently I'm failing in remembering my spot when I dive down descendants and I wish to figure out a good approach to be able to execute a full depth first or breadth first revision.

**Comment by nathanlesage** [comment]
Well, I personally don't include the notes' ID in the filename. My files look like this:

Title: A descriptive short name explaining what the note is about

Within the note:

```markdown

[[§§ Outline-Name]] // <-- For Outlines, I don't use IDs but their filename, makes it more descriptive

20191018120000 // <-- The file's ID

# This is the descriptive title, repeated

#tag1 #tag2 #tag3 #something-else

See further:

- [[12341212565656]] Another note's title
- [[12341212565656]] Another note's title
- [[12341212565656]] Another note's title

> Mainly, I put a blockquote here with some additional explanations above or below

## Literature

- A full literature reference (or more than one) so that the note is completely self-contained.
```

**Comment by namanyayg** [comment]
I believe that's the difference for which I feel the need of a back button where your workflow doesn't -- there's an index already available on the sidebar for you.

The official docs and default config creates timestamped filenames by default. Do you simply edit the filename during creation and then continue the rest as normal or is there some other difference in your configuration?

Do you find yourself naming the title at the end, after the note is complete; or do you write it in the beginning? Do you ever find yourself renaming old notes?

Again, thank you for your assistance and for making this software. I feel very fortunate to receive your guidance for setting up my zk.

**Comment by nathanlesage** [comment]
> I believe that's the difference for which I feel the need of a back button where your workflow doesn't -- there's an index already available on the sidebar for you.

Yup, and this is why I feel this might help more people than just you, which is why I'll keep that issue.

> The official docs and default config creates timestamped filenames by default. Do you simply edit the filename during creation and then continue the rest as normal or is there some other difference in your configuration?

No, the automatic "ID-ification" was demanded so I implemented it — I simply type the filename, because when you create a new note, the note's title is already selected. It's not any problem for my workflow here!

> Do you find yourself naming the title at the end, after the note is complete; or do you write it in the beginning? Do you ever find yourself renaming old notes?

Always in the beginning, because when I create a note I already know what it will be about — it's extremely compartmentalised in my folder, and if I can't think of a straight forward name, it's not a single-item note or I have to let it rest some more time! I usually don't rename notes once they are created, but of course this happens from time to time.

> Again, thank you for your assistance and for making this software. I feel very fortunate to receive your guidance for setting up my zk.

You're welcome! ;)

**Comment by namanyayg** [comment]
I believe #170 is relevant for someone who finds this later

**Comment by nathanlesage** [comment]
> Just to confirm, your filename would thus be "Full Sentence Title.md" not something like "short-abbr-kebab-case.md" right? Nor is there any timestamp/ID present in the filename?

Correct!

> Might be worthwhile to suggest users to rename zettel filenames to note titles directly in the official Zettlr docs, I think it would make linking and browsing a zk using Zettlr much more productive vs just IDs.

Please feel free to update the documentation as you deem adequate! :)

**Comment by mlevison** [comment]
I've spent the past week running from half implemented open source software to the next - perhaps there is a clever way to achieve the back function and a interesting piece of functionality. In Sublimeless and a few other tools. Add a way of displaying the notes that link to "this" note. In doing so you provide a way of navigating back and the context the note participates in. _If you want me to spin up a separate issue - yell_

**Comment by nathanlesage** [comment]
> Add a way of displaying the notes that link to "this" note.

This would indeed require another issue (but please forgive me for *not* yelling at you for this!), but additionally this will have to be postponed a lot, b/c I won't implement this before there is some Graph-functionality within Zettlr.

*(To elaborate a little bit: A Zettelkasten works like a Graph database, so any features like relationships a.k.a. the links we're talking about, would be supported by a graph representation. Nevertheless, there's first the new FSAL I'm addressing in another issue, and only then would I be able to implement a decent API to build an in-memory database from the notes, and only then would it be easy and especially *safe* to perform such high-level queries. I'm not monkey-patching anymore, the software is too big for that. So maybe keep this issue in mind and open it once the FSAL is resolved, because open issues make me nervous!)*

**Comment by Zverik** [comment]
I second this, and also have found few ways the back button would be beneficial. For example, just now I've commented on another issue with a part of Custom CSS that I keep in one of the notes. After finding the note and copying the text I needed to return to the note I was working with.

Also, returning to previous notes would be helpful when you're searching not by id, but looking for a correct note using tags. The size of the back buffer should be virtually infinite, but there's no need to persist it.

**Comment by nathanlesage** [comment]
Concerning text copy-and-pasting, tabs would be more appropriate, but I'm too lazy to search for the open issue, but there is one :D

**Comment by Zverik** [comment]
Yes, but I believe adding one button and one list would be easier both design- and code-wise than adding tabs :)

**Comment by nathanlesage** [comment]
Sure! I mean, the list is already there — you can cycle through the last ten notes using Cmd/Ctrl+<number> :D The only piece missing would be that back/forth thingy

**Comment by khakhalin** [comment]
Can I please vote for the "Back" button? Here, I really do vote for the back button. When adding cross-links, especially from a longer document to smaller dictionary-like entries, it would really help!

**Comment by nathanlesage** [comment]
Basically, `Cmd/Ctrl+2` should work exactly like this … but don't worry, I managed to implement document tabs yesterday, so you may not even need a back button but rather `Ctrl+Tab` and `Ctrl+Shift+Tab` for navigating the tab bar!

**Comment by Zverik** [comment]
I finally learned how to operate Cmd+1/2/3, but still I'd prefer a linear movement :) Thank you for working on tabs!

**Comment by khakhalin** [comment]
Yep, Hendrik, in your original comment above you said "you can cycle through the last ten notes using Cmd/Ctrl+ :D", and for a few days I couldn't figure out what this Ctrl+:D could have meant :) Just didn't want to bother you if you were taking a break. But Ctrl-2 does work like a one-time back button (or rather Alt-Tab-like-button), which is nice!

Anything Ctrl-i for i>2 feels too 4D chess for me, but maybe other people can relate to them better!

**Comment by khakhalin** [comment]
BTW, I think I discovered in tiny bug in the current Ctrl-2 implementation. If you have just created a new note, it doesn't seem to get into the history!

The way it works for me: I am at page A. I then visit a page B. I then create a new page C. If at this point I press Ctrl-2, it sends me to page B (correctly), but pressing Ctrl-2 again sends me to page A, not to page C as it presumably should.

**Comment by nathanlesage** [comment]
> If you have just created a new note, it doesn't seem to get into the history!

Yup, welcome to the wonderful world of remaining file system bugs 🌈 

The tabs, on the other hand work. But even with the new FSAL, newly created files are still not pushed to the "recent docs" array 😂 It's a mess beyond imagination, but I'll get there, somehow!

**Comment by nathanlesage** [comment]
As we already have the tabs, and we're currently discussing the way transiency will be achieved, I'll close this issue in favour of the tabified behaviour, as back functionality can be implemented via `Cmd/Ctrl+Click`-opening links in a new tab, and then navigation back and forth using `Cmd/Ctrl+(Shift)+Tab`. This way we have an easy way for "back" functionality without adding yet another piece of code.
