### ISSUE TITLE
Related Files tab not working properly

### ISSUE THREAD

**Issue by kazmath** [Zettlr/Zettlr#3670]
### Description

After some time using zettlr, I ran into this bug that doesn't show anything in the related files tab in the right. Graph view is also unable to load all the files, freezing at 69....
![image](https://user-images.githubusercontent.com/66137568/183276361-de70fc9b-53eb-4b02-8aa6-2ecdda828eeb.png)
![nice](https://user-images.githubusercontent.com/66137568/183276276-8c9a660b-9458-45c5-9718-fc88cb889992.png)

I have no idea what's causing it, but I can temporarily fix it by moving all of the files out of the workspace I'm currently on, restarting the app (reloading doesn't work, I'm pretty sure) and moving the files back in, restarting it back afterwards is probably optional, but that's what I did it last time. But even after doing that, the bug randomly comes back the next day (maybe after reboot? idk).

Also, if that's any useful, the way I launch zettlr daily is by this script I have set up to launch on boot:
```bash
#!/bin/sh

sed -E -e "/^date:$/s/$/ $(date +%d-%m-%Y)/" \
-e "/^# Afazeres$/s/$/ - Dia $(date +%d\\/%m\\/%Y)/" \
~/Documentos/Outros/Daily_todo.md > /home/kazuma/Documentos/Caixa_de_Notas/_todo_daily.md

nohup /home/kazuma/bin/zettlr --launch-minimized &> /tmp/zettlr.log &
```
Basically, it updates a file in my workspace and then launches Zettlr (AppImage) with the `--launch-minimized` while dumping all of the output to a log file in my `/tmp` directory.

### Reproducing

I have no idea how to reproduce, it became like this at some point and, if I fix it, it goes back after a reboot, but I think a possible cause would be this:

I have two workspaces at `/home/kazuma/Documentos/Caixa_de_Notas/` and `/home/kazuma/Documentos/Projetos/Livro/ToA/` always open, but the `ToA` one (it is a project) has one weird file that shows up with no name in the explorer tab on the left:
![image](https://user-images.githubusercontent.com/66137568/183275319-6d59efa1-774f-4049-8106-a9b37f67c834.png)
but shows with the filename in the tab title:
![image](https://user-images.githubusercontent.com/66137568/183275351-e3f9e607-5129-4b07-afc1-4f2475a956a7.png)
It contains some yaml info, but I think the interpreter got confused when it saw this part, even though it is supported in pandoc for exporting ebooks:
![image](https://user-images.githubusercontent.com/66137568/183275377-856f7f8c-cbf3-43be-981b-178ca6c80dae.png)
My guess is that, when Zettlr sees that file, it breaks, but it's not immediate, as it only comes back after a reboot.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.3 x86_64

### Additional Information

Screenshots, as I have sent on discord (click the images for message links):

Logs (first showed on boot, second when opening graph view)
[![image](https://user-images.githubusercontent.com/66137568/183276485-b79d5093-115c-48c4-a64a-2ec694383d93.png)](https://discord.com/channels/609436111860793355/874677388053717052/998744597964521563)
Graph view
[![image](https://user-images.githubusercontent.com/66137568/183276434-b42121cd-6e8c-4f13-a02d-f3917b319249.png)](https://discord.com/channels/609436111860793355/874677388053717052/997686886413893712)

**Comment by nathanlesage** [comment]
With regard to your note not having a title: You have defined `title:` in your YAML frontmatter but have not provided anything, and this explains why the explorer doesn't show anything. I'm right now working on fixing that one. With regard to the other ones: I know that in the link provider there's this error, I haven't yet had the chance to deeply look into those undefined errors, but it's on my radar. With regard to the graph view I'd have to have another look …

**Comment by Kazuma-chan** [comment]
The `title:` in that format is supported by pandoc and interpret

**Comment by Kazuma-chan** [comment]
The `title:` in that format is supported by pandoc and its `main` property is interpreted as the actual title, while the rest is just some more metadata that is allowed for the Epub format.

And I'm pretty sure the graph view and the links issues are extremely related, if not the same bug, that's why I only opened one issue.

**Comment by nathanlesage** [comment]
Can these issues be reproduced in the current nightlies?
