### ISSUE TITLE
Export to HTML renders paragraph inside embedded 

### ISSUE THREAD

**Issue by wesleywerner** [Zettlr/Zettlr#3671]
### Description

When you have embedded HTML in a document, like a `video` tag, any paragraph text following the embed gets rendered inside the `video` tag, instead of after it. If the embed code is followed by a heading of the same level as the previous (H1 ala the page title), then a block element delineates the embed correctly.

### Reproducing

1. Create a new document with the content below
2. Export the document as HTML
3. The paragraph which reads "this does not display", is not visible due to it rendered as a child element of the `video` tag.

![capture_20220807_161034_Sun](https://user-images.githubusercontent.com/551913/183277991-742d40a3-20c7-4c5f-91b0-4f1aac2d07a1.png)

![capture_20220807_161745_Sun](https://user-images.githubusercontent.com/551913/183278027-af42e894-255c-47e1-ac23-9550b3253be1.png)

```
# main title

<video controls loop>
    <source src="videofile.webm" type="video/webm">
    Sorry, your browser doesn't support embedded videos. Try this direct link instead:
    [descriptive_title](./videofile.webm)
</video>

# second heading
Some text after embedded video. this shows correctly.

<video controls loop>
    <source src="videofile.webm" type="video/webm">
    Sorry, your browser doesn't support embedded videos. Try this direct link instead:
    [descriptive_title](./videofile.webm)
</video>

Additional text after embedded video, this does not display, as it gets rendered inside the `<video>` element.
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
If this happens on export, that might indicate an error with Pandoc. Mh, would you mind attempting to export the file to Markdown? If the video tag then ends up weird that's a good indicator that something within Pandoc is problematic.

**Comment by wesleywerner** [comment]
That is a negative @nathanlesage . Exporting to Markdown places the paragraph below the video tag, as expected.

I did run the generated HTML through validator.w3.org and found the malformed structure - The two pairs of closing tags are transposed incorrectly.

actual:
```
<video controls loop>
<p>Sorry, your browser doesn’t support embedded videos. </video></p>
```

expected:
```
<video controls loop>
<p>Sorry, your browser doesn’t support embedded videos. </p></video>
```

**Comment by nathanlesage** [comment]
Okay, just to be sure: Please try to export your file via the command line to make sure we know where the problem comes from. If it then works, it's a problem with our defaults files. Try to use the bundled Pandoc version, which is located in `C:\\Program Files\\Zettlr\\Resources\\pandoc.exe` (assuming Zettlr is installed in C Program Files)

If that places the paragraph correctly, it is a problem with the defaults file. If not, it's a bug in Pandoc, and then we need to transfer this issue over there.

**Comment by wesleywerner** [comment]
@nathanlesage your guess is correct, Pandoc is generating the malformed HTML.

I will see to raising a issue there. Thanks for the troubleshooting assist! 👍 

```
pandoc.exe -f markdown -t html test.md
<h1 id="main-title">main title</h1>
<video controls loop>
<source src="videofile.webm" type="video/webm">
<p>Sorry, your browser doesn’t support embedded videos. </video></p>
```
