### ISSUE TITLE
Display math does not render correctly, and breaks down correct rendering of following paragraphs. 

### ISSUE THREAD

**Issue by osbama** [Zettlr/Zettlr#3674]
### Description

When I enter display math, (i.e. using `$$`...`$$` notation) It is not rendered correctly, and breaks down the correct rendering of the following text. The editor practically forces me to use inline math only. 
![Screenshot from 2022-08-08 08-04-02](https://user-images.githubusercontent.com/15921496/183343233-307c5377-5016-4f7e-bc43-6930066c4b19.png)
![Screenshot from 2022-08-08 08-03-25](https://user-images.githubusercontent.com/15921496/183343248-b80c299d-f657-4c4c-9ad5-a67737b5d7b5.png)

### Reproducing

The following excerpt is rendered correctly in GitHub MD, but not in Zettlr (as seen in the above screenshots). After the first display math, the figures are not rendered, paragraphs are rendered in "code block" form, and some formulas are not rendered for no apparent reason: 

The polarisation of a dielectric medium represents the dipole per unit volume. As such it would be natural to define a macroscopic (i.e. unit cell averaged) polarisation for an infinite periodic bulk system as 

$$\mathbf P = \frac{e}{V_\textrm{cell}}\int_{V_\textrm{cell}} \mathbf r n(\mathbf r) d\mathbf r$$  where $n$ includes the ion point charges as well as the delocalised electron charge ($e > 0$). It is, however, obvious that this definition is not meaningful as it depends on the chosen unit cell (see p. 365 in Grosso and Parravicini 2nd. ed.). Instead, it turns out that only *changes* in polarisation are physically meaningful, and in fact all experimental measurements of bulk polarisation indeed probe the difference in polarisation between two states of the crystal. In this and the next section we show, following two different routes, that such quantities are indeed well defined.

Before we derive a unit-cell independent formula for the change in polarization, it should be noted that expression $P$ cannot be directly applied to determine such a change. This point should be clear from Figure $P_\text{cell}$.

![An illustration of the dependence of the polarization change on the choice of unit cell when computed using Eq. $P$. Here we induce a change in the electron density by moving an atom which could induce a change in the polarization of the material. However, depending on the choice of unit cell (top and bottom panel) some fractional amount of electrons will be folded back into the unit cell ($\delta n$) and yield arbitrary values for the induced polarisation.](./figures/born_charge.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Flathub

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

PopOS 21 and Windows 10

**Comment by santidingo** [comment]
Just wanted to confirm I'm having the same issue, and have been able to reproduce it several times as described.

Although it used to be a problem I could fix by fiddling around, it's now pretty consistent.

**Comment by nathanlesage** [comment]
Please remember this issue and test it again once the CM6 PR has been merged and is available on nightly. There is a high chance that the bug will be gone then: https://github.com/Zettlr/Zettlr/pull/3776

**Comment by nathanlesage** [comment]
Fixed it. Was a small bug-counteraction that went rogue:

![image](https://user-images.githubusercontent.com/17251683/199961634-64a7ff14-d5ef-47a8-a319-862615d77cad.png)
