### ISSUE TITLE
Cannot paste images if "Default image path" is a symbilic link

### ISSUE THREAD

**Issue by rpezzi** [Zettlr/Zettlr#3675]
### Description

I have projects with several subfolders and would like to save images in an unique folder per project. Absolute paths are large and not portable, while relative paths make it difficult to move images between different project subfolders.

A possible solution is to use symbolic links:  
1. create one `images` folder per project
2. set `images` as default location and
3. add symbolic links to `images` folder on each subfolder.  

This would allow one to 
* Avoid absolute paths (which are too large and not portable)
* Move text with images between markdown files on different subfolders
* Reuse the same image on different project folders

However, Zettlr fails to paste images on markdown files if the image location is a symlink.

### Reproducing

Use a symbolic link as default image location

### Zettlr Version

Stable (most recent version)

### Specify version

2.30.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

20.04

**Comment by nathanlesage** [comment]
Closing this in favor of #3165
