### ISSUE TITLE
Create new note from selected text with hotkey

### ISSUE THREAD

**Issue by raoul-van-oosten** [Zettlr/Zettlr#368]
Hi!

Sublimeless-ZK has the option to create a new note from selected text by pressing Shift-Enter. In this case the selected text becomes the title of the new note.

It would be great if this could be implemented in Zettlr too

**Comment by nathanlesage** [comment]
There's another open issue somewhere where something similar (concerning hotkeys) is demanded. Until I get to unifying the hotkey management within the app (which currently is, honestly, quite a mess), I can't implement this. But I'll keep this open for then.

**Comment by raoul-van-oosten** [comment]
I guess it is related to [Issue 90](https://github.com/Zettlr/Zettlr/issues/90) and [Issue 178](https://github.com/Zettlr/Zettlr/issues/178)

**Comment by nathanlesage** [comment]
To a certain extent, yes!

**Comment by patmaddox** [comment]
This is a dream feature for me with zettelkasten. It's refactoring notes. Write a long note, run a shortcut to extract some text to a note. Also the reverse to inline notes, to build up a longer document from a list of zettels.
