### ISSUE TITLE
Code blocks being exported to HTML or PDF without background highlinting as in the editor

### ISSUE THREAD

**Issue by MatveyM11** [Zettlr/Zettlr#3680]
### Description

Zettlr can't properly export code blocks with their background highlight - 
![image](https://user-images.githubusercontent.com/23504691/183622031-ba3c1684-992d-4ea7-8bf8-a86dc75857ea.png)

Though in the editor preview it's fine - 
![image](https://user-images.githubusercontent.com/23504691/183622175-652fb8d4-8ef0-4ebb-afaa-a57120b2b456.png)

It's can be handled with custom CSS blocks - 

![image](https://user-images.githubusercontent.com/23504691/183623771-99a17939-3940-4b69-b95c-ebace19c7997.png)

![image](https://user-images.githubusercontent.com/23504691/183622517-e9589484-f211-4bcc-af72-11e5f1df638a.png)

But Zettlr by the default won't export it to PDF properly and you will need to export it to HTML, open HTML to browser and from here save it as a PDF.

But in other MD editor - MarkText, Obsidian, you can easily just export codeblocks without such problems - 

ex.(MarkText)
![image](https://user-images.githubusercontent.com/23504691/183623310-da4e918d-52a8-43dd-b1ab-ddaa0d1a21fd.png)

### Reproducing

Try to export this codeblock as PDF or HTML.

```python
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style("darkgrid")
iris = sns.load_dataset('iris')
sns.FacetGrid(iris, hue ="species",
    height = 5).map(plt.scatter,
    'sepal_length',
    'petal_length').add_legend()

plt.show()
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

EndeavourOS(Arch Linux)

**Comment by nathanlesage** [comment]
I'm far too removed from the 2.3 by now but it could be that your computer fails to download the appropriate styles (it uses Highlightjs to render code blocks, could be that Pandoc couldn't get the highlighter package online). Could also be that you use a custom template that forgot to include the necessary library? Is that maybe the reason?

**Comment by MatveyM11** [comment]
@nathanlesage, nope, the only thing that I customized was this Custom CSS

>  {
>    color: rgb(0, 0, 0);
>     font-family: "Times New Roman";
> }

Without it it's still the same.

**Comment by nathanlesage** [comment]
Custom CSS only affects the editor, NOT the exports.

And I just re-read the title again and saw that you were specifically referring to the backgrounds: the default templates don't color the background, you'd have to adapt the stylings. For that I would refer you to the Pandoc manual, but you can add some more CSS for the HTML export and some LaTeX directives for the PDF export to achieve precisely that.
