### ISSUE TITLE
Regression in nightly for Table of Contents

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#3687]
### Description

In the current Nightly, clicking on headings in the Table of Contents in the sidebar tab has no effect. Clicking on a heading should move to the corresponding section of the document, as it does in Zettlr 2.3.0. 

### Reproducing

See above

### Zettlr Version

Nightly

### Specify version

Zettlr 2.3.0+nightly-20220809

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Working by now
