### ISSUE TITLE
url links in a table

### ISSUE THREAD

**Issue by krisdez** [Zettlr/Zettlr#3691]
### Description

Hello
When I want to create a link to a URL in a table, it works.
But when I export (HTML or PDF Latex), I find the text of the URL but this link is not clickable even if I use HTML.

### Reproducing

Create a table
Insert a url

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Can you, when you export to HTML, right-click and select "Inspect" and see if the element is in fact an `<a>`-element? Feel free to also add a screenshot here.

**Comment by krisdez** [comment]
Here is a screenshot of the resulting code. The link is not exported with <a href=...>...</a> tags.
![13162405](https://user-images.githubusercontent.com/16731341/184498499-be9e7c73-5666-4ce2-81a3-e7e1f3e4becb.png)

**Comment by nathanlesage** [comment]
Sorry for the very late response.

This is not a bug, but expected. You have three ways of mitigating this:

1. Create a “proper” Markdown link (`[https://www.google.com](https://www.google.com)`)
2. Surround the link with `<` and `>` to explicitly mark it as a URL (`<https://www.google.com>`)
3. Activate the [`autolink_bare_uris`](https://pandoc.org/MANUAL.html#extension-autolink_bare_uris) extension in the export profile (Assets manager ⇾ Navigate to the profile you're using ⇾ change the default `writer: markdown` to `reader: markdown+autolink_bare_uris` (accounting for any other extensions you have enabled)
