### ISSUE TITLE
Zettlr not rendering block quotes and mermaid diagrams.

### ISSUE THREAD

**Issue by MatveyM11** [Zettlr/Zettlr#3694]
### Description

Blockquotes are rendered only on export but not in the WYSIWYG editor.

Editor -
![Editor](https://user-images.githubusercontent.com/23504691/184554391-8dad0527-807f-420d-b9fc-11615f9510c0.png)

PDF -
![PDF](https://user-images.githubusercontent.com/23504691/184554397-aacb251b-df21-4f2e-a00d-ac7f4a3433a8.png)

With the mermaid diagrams here's an opposite situation, properly rendered in the editor -
![image](https://user-images.githubusercontent.com/23504691/184554452-46335748-bccb-4ca2-9a75-2c76286e9d97.png)

And nothing on the export to PDF - 
![image](https://user-images.githubusercontent.com/23504691/184554474-ba6c7faf-c7e6-476b-a2e9-f06a849547d2.png)

### Reproducing

1) Create file with this content - 

> test

`test`

```mermaid
classDiagram

 Animal   <|--   Duck

 Animal   <|--   Fish

 Animal   <|--   Zebra

 Animal   :   +int age

 Animal   :   +String gender

 Animal:   +isMammal()

 Animal:   +mate()

 class   Duck{

 +String beakColor

 +swim()

 +quack()

 }

 class   Fish{

 -int sizeInFeet

 -canEat()

 }

 class   Zebra{

 +bool is_wild

 +run()

 }
```

```mermaid
graph LR
MyApp --> DB(<font color=white>fa:fa-database MySQL)
style DB fill:#00758f
```

2) Export it to PDF

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

EndeavourOS(Arch Linux), Kernel: 5.18.16-arch1-1,  DE: Plasma 5.25.4

**Comment by nathanlesage** [comment]
Everything Works as expected:

1. Blockquotes aren't prerendered because there is no WYSIWYG editor in Zettlr
2. Mermaid codeblocks require a special Pandoc filter. I agree that it's difficult to comprehend, but there is a pandoc filter for the job. I have no experience with that myself, so maybe ask in the Discord for that!
