### ISSUE TITLE
`Render emphasis` display issues

### ISSUE THREAD

**Issue by eugeneilyin** [Zettlr/Zettlr#3696]
### Description

This is a summary for the actual issues related to the [**Render emphasis**](https://github.com/Zettlr/Zettlr/pull/3265) feature introduced by @Redsandro includes #3659, #3406 which are not be fixed by @nathanlesage till CodeMirror 6 integration as he mentioned [here](https://github.com/Zettlr/Zettlr/issues/3659#issuecomment-1203852948). ETA 2025-2026 ;)

Here is a test markdown with all inlined combinations of `emphases`, `strong`, `strikethrough`, and `code` spans.
The `==highlight==` spans are failed in almost all mentioned cases (instead of changing only the background-color (to highlight the internal spans) - the whole highlighted internal formatting is corrupted).

```md
1. _Emphases_
2. *Emphases*
3. __Strong__
4. **Strong**

5. ___Strong Emphases___
6. ***Strong Emphases***
7. __*Strong Emphases*__
8. *__Strong Emphases__*
9. _**Strong Emphases**_
10. **_Strong Emphases_**

11. ~~Strikethrough~~
12. ~~_Strikethrough Emphases_~~
13. _~~Strikethrough Emphases~~_
14. ~~*Strikethrough Emphases*~~
15. *~~Strikethrough Emphases~~*
16. ~~__Strong Strikethrough__~~
17. __~~Strong Strikethrough~~__
18. ~~**Strong Strikethrough**~~
19. **~~Strong Strikethrough~~**

20. ~~___Strong Strikethrough Emphases___~~
21. ___~~Strong Strikethrough Emphases~~___
22. ~~***Strong Strikethrough Emphases***~~
23. ***~~Strong Strikethrough Emphases~~***
24. ~~__*Strong Strikethrough Emphases*__~~
25. __~~*Strong Strikethrough Emphases*~~__
26. __*~~Strong Strikethrough Emphases~~*__
27. ~~*__Strong Strikethrough Emphases__*~~
28. *~~__Strong Strikethrough Emphases__~~*
29. *__~~Strong Strikethrough Emphases~~__*
30. ~~_**Strong Strikethrough Emphases**_~~
31. _~~**Strong Strikethrough Emphases**~~_
32. _**~~Strong Strikethrough Emphases~~**_
33. ~~**_Strong Strikethrough Emphases_**~~
34. **~~_Strong Strikethrough Emphases_~~**
35. **_~~Strong Strikethrough Emphases~~_**

36. _`Emphased Code`_
37. *`Emphased Code`*
38. __`Strong Code`__
39. **`Strong Code`**

40. ___`Strong Emphased Code`___
41. ***`Strong Emphased Code`***
42. __*`Strong Emphased Code`*__
43. *__`Strong Emphased Code`__*
44. _**`Strong Emphased Code`**_
45. **_`Strong Emphased Code`_**

46. ~~`Strikethrough Code`~~
47. ~~_`Strikethrough Emphased Code`_~~
48. _~~`Strikethrough Emphased Code`~~_
49. ~~*`Strikethrough Emphased Code`*~~
50. *~~`Strikethrough Emphased Code`~~*
51. ~~__`Strong Strikethrough Code`__~~
52. __~~`Strong Strikethrough Code`~~__
53. ~~**`Strong Strikethrough Code`**~~
54. **~~`Strong Strikethrough Code`~~**

55. ~~___`Strong Strikethrough Emphased Code`___~~
56. ___~~`Strong Strikethrough Emphased Code`~~___
57. ~~***`Strong Strikethrough Emphased Code`***~~
58. ***~~`Strong Strikethrough Emphased Code`~~***
59. ~~__*`Strong Strikethrough Emphased Code`*__~~
60. __~~*`Strong Strikethrough Emphased Code`*~~__
61. __*~~`Strong Strikethrough Emphased Code`~~*__
62. ~~*__`Strong Strikethrough Emphased Code`__*~~
63. *~~__`Strong Strikethrough Emphased Code`__~~*
64. *__~~`Strong Strikethrough Emphased Code`~~__*

65. ~~_**`Strong Strikethrough Emphased Code`**_~~
66. _~~**`Strong Strikethrough Emphased Code`**~~_
67. _**~~`Strong Strikethrough Emphased Code`~~**_
68. ~~**_`Strong Strikethrough Emphased Code`_**~~
69. **~~_`Strong Strikethrough Emphased Code`_~~**
70. **_~~`Strong Strikethrough Emphased Code`~~_**

71. ==Highlight==
```

Click to [expand](https://user-images.githubusercontent.com/14204888/184647248-743904f1-991b-4d99-a210-696215c2e040.png):
![inline-span-issue-1](https://user-images.githubusercontent.com/14204888/184647248-743904f1-991b-4d99-a210-696215c2e040.png)
Click to [expand](https://user-images.githubusercontent.com/14204888/184647268-04331561-ba06-49ba-a41c-07df041409bb.png):
![inline-span-issue-2](https://user-images.githubusercontent.com/14204888/184647268-04331561-ba06-49ba-a41c-07df041409bb.png)

The same rendering issues should be checked against:
- **inside/outside links**
- **headers**
- **inside/outside links** in **headers**
- **table cells**
- **inside/outside links** in **table cells**
- **headers** in **table cells**
- **inside/outside links** in **headers** in **table cells**

### Reproducing

- Install the recent Zettlr 2.3.0
- Copy the markdown provided above
- Enable `Settings -> Display -> Rended emphasis` checkbox
- Observe the formatting elements and failed `code` or `==highlight==` renderings

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

# Suggested improvements
- It will be cool to rename **Render emphasis** to **Render inlines** for better mathing with the feature context
- The headers formatting (`h1`, `h2`, ..., or `#`, `##`, ...) could also be hidden **if** this feature is enabled (to get fully formated text without any formatting elements visible).

**Comment by nathanlesage** [comment]
Thanks for collecting the list! We should add them to the test suite. I'm pretty confident this will work before 2025. Also I can confirm that Codemirror 6 does exactly what we need for this to work properly: a syntax tree!

I'd say ETA 2023 at the latest.
