### ISSUE TITLE
support Video and audio 

### ISSUE THREAD

**Issue by johans3** [Zettlr/Zettlr#370]
## Expected behaviour
I would love to embed audio and video (maybe also url-video) into notes. 
Content is multimedial nowadays, and to have everything about my research in one place helps me to clean up the file management on hard drive
My previous experiences were: MacJournal and DevonThink on Mac OS

## Platform
 - OS: Linux Manjaro
 - OS Version: latest
 - Zettlr Version 1.4.2

**Comment by nathanlesage** [comment]
Zettlr is not a replacement for MacJournal or DevonThink. It's a Markdown editor.

Nevertheless, you can embed audio and video. They can be listed as attachments, if configured that way ([see the docs](https://docs.zettlr.com/en/reference/settings/#advanced)). Then, you can link them just like any other file. Videos can also be embedded by using an iframe, which will be rendered.

Apart from this, Audio and Video support is to be delegated to other applications, as Zettlr focuses on text (and images), not on other media.

**Comment by jediwarrior77** [comment]
On Typora I can drag and drop local videos and watch them inside the editor. Is it possible with Zettlr?

**Comment by nathanlesage** [comment]
Yes, if you use an iframe, check my comment above!
