### ISSUE TITLE
Use a Note's First Heading as Default Filename for New Notes

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#3702]
### Description

Because I want my notes to have human-readable filenames, I typically use the title of my note as the filename, which in turn is usually the content of the note's first level-1 heading (e.g., `# My Heading`). To expedite the process of naming files in this way, I think it would be handy to have a settings option that would tell Zettlr to auto-suggest a note's first level-1 heading as the filename in the save dialogue.

Currently, I must re-type (or remember to cut-and-paste) the content of my first level-1 heading as the filename when saving a file, which seems like an unnecessary step and also opens up the possibility of typos, etc. Moreover, I doubt I'm the only user who prefers to save their .md files with the heading as the title for human-readability. The fact that, elsewhere in the `Preferences`, there is an option to display files within Zettlr with the first level-1 heading in place of the filename speaks to how often people use this heading as the title of the note. Giving users the option to also easily set it as the filename seems like a logical next step. 

### Proposed Changes

When saving a new note, Zettlr already suggests a filename. And it's already possible to customize the naming pattern for these suggestions under `Preferences > Advanced > Pattern for new filenames`, which allows users to construct a template string from a number of standard date-time presentation variables.

I suggest adding a new variable — e.g., `%firstheading` — to the list of available variables, which would make the note's first level-1 heading (or first heading of any sort) available as a variable users can use in the template string. Since some markdown headings may include formatting characters that would make for messy or non-unix-friendly filenames, it may be wise to strip formatting characters from headings or sanitize the heading content in other ways when implementing.

An alternative to adding a variable to the list of available variables would be to have a checkbox _separate_ from the `Pattern for new filenames` field. Users could then simply check the box (e.g., `Use first heading as filename for new notes`). Checking the box would supersede the content of the `Pattern for new filenames` field, which could be grayed out when the `Use filename…` box is selected. The same proviso about sanitizing heading strings when using them as filenames applies here.

### Caveats

I don't think there are any caveats here.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro Linux (rolling)

**Comment by nathanlesage** [comment]
This won't be necessary anymore in the newer versions since I've dumped the "in-memory-files". A lot of people have complained that this is apparently unintuitive and those people wanted a 1-to-1-mapping of files in Zettlr and files on disk.

(Additionally, it is very tempting for me since the logic to maintain in-memory-files is really difficult to make bug-free)

**Comment by wideaperture** [comment]
:+1: Sounds good!
