### ISSUE TITLE
The syntax highligh in tilde code block `~~~` is missed

### ISSUE THREAD

**Issue by eugeneilyin** [Zettlr/Zettlr#3703]
### Description

The syntax highlight in tilde code blocks `~~~` is missed:

~~~md
```js
  const results = []
  while (checks.length) {
    results.push(...await Promise.allSettled(
      checks.splice(0, maxParallelChecks ?? checks.length).
        map(({ name, login }) => login((emit, _, acc) => {
          let props = []
```
~~~
```md
~~~js
  const results = []
  while (checks.length) {
    results.push(...await Promise.allSettled(
      checks.splice(0, maxParallelChecks ?? checks.length).
        map(({ name, login }) => login((emit, _, acc) => {
          let props = []
~~~
```

Click to [expand](https://user-images.githubusercontent.com/14204888/184947266-06e393e6-ff65-4d7e-8636-b50ba0bfa26f.png):
![tilde-code-block-rendering-issue](https://user-images.githubusercontent.com/14204888/184947266-06e393e6-ff65-4d7e-8636-b50ba0bfa26f.png)

### Reproducing

1. Install the recent Zettlr 2.3.0
2. Copy markdown above
3. Observe the issue
4. Think how to fix it and where the tilde code blocks `~~~` are not specified for syntax highliting in Zettlr sources
5. Profit!

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
That is to be expected due to a limitation in the multiplexer plugin. Will possibly work with the new CodeMirror iteration I'm currently working on.

**Comment by nathanlesage** [comment]
Just double checked: Works in the current develop branch, i.e. will work in the upcoming betas and releases:

![image](https://user-images.githubusercontent.com/17251683/199960601-c23647d6-6e30-4169-9ae5-d4fbc2de092a.png)
