### ISSUE TITLE
Add special display for metadata

### ISSUE THREAD

**Issue by almet** [Zettlr/Zettlr#371]
Markdown seems to support two different formats for metadata. It would be great if these could be displayed in a special way in Zettlr : they are currently shown as just text, and that would make sense to me to have them editable only when you click on them, for instance.

What do you think?

YAML Frontmatter : 

```
---
layout: post
title: Blogging Like a Hacker
---
```

[MultiMarkdown Metadata](http://fletcher.github.io/MultiMarkdown-5/metadata.html)

```
Title:    A Sample MultiMarkdown Document  
Author:   Fletcher T. Penney  
Date:     February 9, 2011  
Comment:  This is a comment intended to demonstrate  
          metadata that spans multiple lines, yet  
          is treated as a single value.  
CSS:      http://example.com/standard.css
```

**Comment by nathanlesage** [comment]
Yeah, this belongs to the greater realm of supporting front matters; I've been struggling in correctly supporting them for quite some time now, there are some other issues open in the tracker, so I'll try to address them as a bundle as soon as I'm able to get to these.

**Comment by almet** [comment]
Okay, thanks for the feedback. What's the struggle with these?

**Comment by nathanlesage** [comment]
Well, the best idea would be to simply display them with correct syntax highlighting, but CodeMirror is not playing well with that. The idea of displaying these information extra also came to my mind but this would de-facto split up some contents from the same file (which is, on a purely UX level, not the best idea). But I think it's going to be that!

**Comment by almet** [comment]
So, it seems to be [a mode to help us with Yaml front matter](https://codemirror.net/mode/yaml-frontmatter/index.html). it doesn't solve how we should do with Multimarkdown metadata, but it seems good enough for a start, don't you think?

**Comment by nathanlesage** [comment]
WHAT?! Why didn't I see that mode? o_O

That's EXACTLY what I was looking for! 😍

**Comment by nathanlesage** [comment]
YAML Frontmatter support is now included, so closing now!

**Comment by almet** [comment]
You rock :-)
