### ISSUE TITLE
Use F2 to edit the name of the currently selected file.

### ISSUE THREAD

**Issue by almet** [Zettlr/Zettlr#372]
It would be very useful to be able to trigger a rename with a shortcut. The default one on my desktop environment is `F2`, but it might be another one on other environments.

**Comment by nathanlesage** [comment]
`F2` sounds pretty much like Windows; I'm not sure as to what Linux does. But adding a new shortcut shouldn't prove to be a problem so far!

**Comment by almet** [comment]
`F2` is for Linux. This works with KDE and Gnome apps at least.

**Comment by nathanlesage** [comment]
Then I think both Windows and Linux have this shortcut, so I can simply put it in!

**Comment by Zverik** [comment]
Let's keep this.

**Comment by nathanlesage** [comment]
@Zverik Are you searching for work? :D

**Comment by nathanlesage** [comment]
Closing in favor of new collective issue
