### ISSUE TITLE
Dragging & dropping content with special characters does not work

### ISSUE THREAD

**Issue by politikundbildung** [Zettlr/Zettlr#3724]
### Description

When dragging & dropping text into Zettlr that contains special characters like ä, ö, ü, ß, Zettlr messes them up. I've attached a screenshot of text inserted from Zotero but the problem also persists with content from other applications.

![grafik](https://user-images.githubusercontent.com/74705055/186611758-0afc4ddf-3e3f-429d-a87e-d0f29f1448d5.png)

### Reproducing

1. Highlight text containing special characters like ä, ö or ü in any application
2. Drag the the text into Zettlr and drop it

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 22.04

**Comment by nathanlesage** [comment]
This looks like an encoding issue. I don't have solid knowledge about Ubuntu-based GUIs to really know where the issue may be caused. Zettlr internally handles everything using UTF-8, but I don't know how the interaction with Kubuntu in this regard is …

**Comment by politikundbildung** [comment]
If there's any way I can help troubleshoot this, I am happy to help. When dragging & dropping into other editors like LO Writer or Kate the problem doesn't occur, however.

**Comment by nathanlesage** [comment]
Hey, would you mind testing out the most recent [nightly](https://nightly.zettlr.com/) and see if the bug occurs there as well?

**Comment by politikundbildung** [comment]
I've just tried the Nightly (AppImage) and as far as I can see I cannot drag & drop anything into Zettlr anymore (also the app takes ages to launch).

**Comment by nathanlesage** [comment]
Thanks for confirming. Will have a look!

**Comment by politikundbildung** [comment]
I've now managed to install the .deb-version of the Nightly and the problem exists there too. I cannot even drag & drop text inside Zettlr.
