### ISSUE TITLE
zoom out

### ISSUE THREAD

**Issue by sbwiecko** [Zettlr/Zettlr#373]
1. The shortcut 'ctrl+-' for zooming out does not work, yet zoom in shortcut works fine.
2. Would be great to leave the zoom level as it is when closing the program, so that we don't have to re-zoom every time we start Zettlr.

## Platform
 - OS: Windows 10
 - OS Version 1903
 - Zettlr Version 1.4.2

**Comment by nathanlesage** [comment]
1. So the shortcut is not working, but the menu entry?
2. Good idea!

**Comment by tryptofan68** [comment]
1. The zoom out menu entry works fine

**Comment by nathanlesage** [comment]
Alright, thanks for the clarification — just to be sure: Does `Ctrl+Shift+-` work? Sometimes, Electron overrides shortcuts, which is out of my control, afaik.

**Comment by tryptofan68** [comment]
No `Ctrl+Shift+-` doesn't work, this shortcut does nothing visible

**Comment by nathanlesage** [comment]
Okay, then I'll have a look at this!

**Comment by pihentagy** [comment]
Maybe he has non-English keyboard.

**Comment by nathanlesage** [comment]
That's not the problem -- as far as I understood some of the issues on the Electron tracker, shortcuts for, e.g., zooming, are hard-coded into the Chromium base, which effectively means that I can use any accelerator without having any effect. So some shortcuts are simply unavoidable ...

**Comment by pihentagy** [comment]
> No `Ctrl+Shift+-` doesn't work, this shortcut does nothing visible

Nost just <kbd>Ctrl</kbd> + <kbd>-</kbd>?

**Comment by nathanlesage** [comment]
Was just my first idea without checking, but yes, it's supposed to be <kbd>Ctrl</kbd>+<kbd>-</kbd>

N.B.: On my Windows 7 machine at work Ctrl + - works just fine for zooming out

**Comment by hueyy** [comment]
On Windows 10, <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>+</kbd> and <kbd>Ctrl</kbd><kbd>-</kbd> work for me.

**Comment by pihentagy** [comment]
> 2. Would be great to leave the zoom level as it is when closing the program, so that we don't have to re-zoom every time we start Zettlr.

Actually that one is very annoying (have to re-calibrate every time)

**Comment by nathanlesage** [comment]
@pihentagy If the default font size doesn't suit you, a little bit of [custom CSS](https://docs.zettlr.com/en/core/custom-css/) will save the day:

```css
#editor .CodeMirror {
  font-size: 1.5em; /* Adjust this to your liking */
}
```
