### ISSUE TITLE
Strange keyboard interaction when creating new file

### ISSUE THREAD

**Issue by kellertuer** [Zettlr/Zettlr#3732]
### Description

On Zettlr 2.3.0 when creating a new File in a folder,
editing its name is a little stressful. Hitting arrow keys collapses the folder and stops the creation of the file. This is not nice as an interaction mode

### Reproducing

Richt click on a folder in Workspace and choose File->“New File...”
Then hit the left arrow key.

The workspace collapses, the file is not created.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

macOS Monterey 12.5.1

**Comment by nathanlesage** [comment]
I noticed this recently, it's weirdly intermittend on the nightlies, but I've noticed this and will get to this after I've fixed a few remaining bugs regarding the file operations.

**Comment by nathanlesage** [comment]
Fixed that yesterday!
