### ISSUE TITLE
File and Directory recurrence after delete: associated with Issue #3278

### ISSUE THREAD

**Issue by celtickuma** [Zettlr/Zettlr#3733]
### Description

After deleting files and directories, performing a save, and closing the app, those files and directories which were deleted recur in the workspace.  This is associated with Issue #3278.

### Reproducing

Create a test directory.
Create one or more files in the test directory.
Populate the files with text.
Close the Application.
Open the Application.
Delete a file.
The file disappears from the workspace.
Delete the test directory.
The test directory disappears from the workspace.
Perform a save.
Close the Application.
Open the Application.
Those items which were deleted from the workspace reappear.
This behavior occurs whether the directory is stored on Dropbox or locally.

### Zettlr Version

Stable (but an older version)

### Specify version

2.1.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Catalina 10.15.7

**Comment by nathanlesage** [comment]
> those files and directories which were deleted recur in the workspace.

I unfortunately missed to remove workspace dirs/files from the config after deletion. It's fixed in the Codemirror 6 PR, and thus will make its way into the main release soon.
