### ISSUE TITLE
Differentiate between tags and heading IDs

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#3734]
### Description

Zettlr supports internal links within documents by allowing users to link to heading IDs. E.g., a heading formatted like so…

`# My Heading {#myheading}`

…can be linked to like this:

`This is [my link](#myheading).`

In leveraging this functionality, I've included many heading IDs within my documents. The trouble is that in other contexts Zettlr regards them as tags. The "Additional Information" view and other parts of the interface that display tags are all displaying my internal heading IDs, which is interfering with my attempts to create and use actual tags, since real tags get mixed in with heading information that's not semantically useful. Thus, I'd like Zettlr to be able to differentiate between heading IDs and tags.

### Proposed Changes

Whatever regex or script is scraping tag info from notes could be amended to ignore instances where the `#` symbol is preceded by characters associated with IDs and internal links.

For example, `#foo` would be scraped, but `{#foo` and `(#foo` would be ignored.

### Caveats

Perhaps some people think of their heading IDs as semantically useful outside the scope of the immediate document they're editing and are thus fine with the software regarding them as tags. I suspect these folks are few and far between, however. Perhaps including a toggle in the `Preferences` pane could allow them to choose whether or not Zettlr regards heading IDs as tags.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro (Rolling)

**Comment by nathanlesage** [comment]
> In leveraging this functionality, I've included many heading IDs within my documents.

Well, one thing that might help would be to tell Zettlr that these are also valid IDs. Right now, heading ID's are ONLY generated based on the heading text, those Pandoc-style explicit IDs are ignored as of now 🙈 

(For the tightness of the integration between Zettlr and Pandoc, I surely missed a ton of features in core parts of the app, lol)

**Comment by wideaperture** [comment]
> Right now, heading ID's are ONLY generated based on the heading text

I'm finding the opposite is true? Neither of the following headings…

`# heading`
`#heading`

…can be linked to using the `[my link](#heading)` syntax. But if I format my heading like so…

`# heading {#heading}`

…then and only then does the `[my link](#heading)` link work.

**Comment by nathanlesage** [comment]
The syntax `#heading` is NOT a heading. It is a tag. The space between pound sign and the text is important in the context of Zettlr. But then, it loos like a bug. I'll get to it once I'm finally merging the Codemirror 6 instance.

**Comment by ShrewFather** [comment]
I stumbled upon this issue while trying to solve the same problem. I'm an avid HumHub user, and I really appreciate how the wiki widget there allows linking to different headings both **within** a page and across different pages. So I was a bit surprised to find out that Zettlr doesn't support this feature yet. Although I'm aware of the workaround by using tags, I still believe having this feature would be really useful.

I'm not sure how complicated this would be to implement. Is there plans to add this in the near future?

**Comment by nathanlesage** [comment]
Well, one thing I have planned relatively soon is to replace the bodged file parser with the AST based approach I recently implemented. That will get rid of any misattributions as "tags". Another step would then be to not just allow to link to other files but also to headings within these files, which is much more tricky, because you have to (a) first tell Zettlr to open the corresponding file and then (b) after an asynchronous timeout tell Zettlr to jump to a specific section within this file. It's definitely possible, but difficult to implement. As always, PRs welcome.

**Comment by nathanlesage** [comment]
Closing this issue, since heading IDs should not be detected as tags anymore.
