### ISSUE TITLE
When exporting to Latex, citations are saved as plain text and not bibtex

### ISSUE THREAD

**Issue by josh-ashkinaze** [Zettlr/Zettlr#3744]
When you have any references in Zettlr and then export to Latex (source), the references are saved as plain text. This makes it difficult to transfer to something like Overleaf. Any way to make it so exporting to Latex saves references using bibtex and not just the plain text citations?

**Comment by nathanlesage** [comment]
According to the Pandoc manual, you can use `biblatex: true` in your defaults file: https://pandoc.org/MANUAL.html#citation-rendering

> Use [biblatex](https://ctan.org/pkg/biblatex) for citations in LaTeX output. This option is not for use with the [--citeproc](https://pandoc.org/MANUAL.html#option--citeproc) option or with PDF output. It is intended for use in producing a LaTeX file that can be processed with [bibtex](https://ctan.org/pkg/bibtex) or [biber](https://ctan.org/pkg/biber).

**Comment by josh-ashkinaze** [comment]
Hi can you explain which file in particular to modify? I just tried to add
that to `zettlr/defaults/export.latex.yaml` and got an error

Best,
Josh

**Comment by josh-ashkinaze** [comment]
Hi can you explain which file in particular to modify? I just tried to add
that to `zettlr/defaults/export.latex.yaml` and got an error

Here is what `export.latex.yaml` looks like. Note the last line.

```

# ZETTLR DEFAULTS FILE
# ====================
# Conversion: Markdown --> LaTeX document
# More info: https://pandoc.org/MANUAL.html
reader: markdown
writer: latex
self-contained: false
variables: {}
metadata-files: []
include-before-body: []
include-after-body: []
include-in-header: []
bibliography: []
filters:
- type: citeproc
top-level-division: chapter
wrap: none
columns: 78
dpi: 72
toc: false
toc-depth: 2
number-sections: false
number-offset:
- 0
- 0
- 0
- 0
- 0
- 0
shift-heading-level-by: 1
section-divs: true
identifier-prefix: ''
title-prefix: ''
eol: lf
strip-comments: false
indented-code-classes: []
ascii: false
default-image-extension: .jpg
highlight-style: pygments
tab-stop: 4
preserve-tabs: false
fail-if-warnings: false
biblatex: true

```

**Comment by yansh** [comment]
You need to add: 

```cite-method: natbib ```

in Asset Managers -> Latex: 

More info here: https://pandoc.org/MANUAL.html
