### ISSUE TITLE
[Bug] Rename duplicate file

### ISSUE THREAD

**Issue by JsThiago** [Zettlr/Zettlr#3747]
### Description

I tried to duplicate a file and then rename the new one. But the name does not change in UI. But when i go to the file's property the name is correct.
Image:
[https://i.ibb.co/JsftxkL/2022-09-05-10-27-11.png](url)

### Reproducing

Create a new file -> duplicate the file (with right mouse button and choosing the option duplicate file) -> rename the new file (again with right mouse button)

### Zettlr Version

Stable (most recent version)

### Specify version

v2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Gentoo Base System release 2.8

### Additional Information

Sorry about my english : - )

**Comment by JsThiago** [comment]
> There have been some issues with renaming/moving/creating in the 2.3 release. I'm currently en route to fixing these bugs in the upcoming 3.0 release. Please have a little bit of patience, I'm on it.

Seems like the name was comming from the yaml at the beginning of the document.  I'm using jekyll and i need to use something like:
---
layout: post
title: "[neetcode] 213. House Robber II"
---
at the beginning :). idk if this is default or bug...

**Comment by JsThiago** [comment]
> There have been some issues with renaming/moving/creating in the 2.3 release. I'm currently en route to fixing these bugs in the upcoming 3.0 release. Please have a little bit of patience, I'm on it.

Seems like the name was comming from the yaml at the beginning of the document.  I'm using jekyll and i need to use something like:
\-\-\-
layout: post
title: "[neetcode] 213. House Robber II"
\-\-\-

at the beginning :). idk if this is default or bug...

**Comment by nathanlesage** [comment]
If the name came from the title than this is absolutely to be expected. There is a setting of what Zettlr uses as the display name for your files.
