### ISSUE TITLE
Fix file dragging when using combined sidebar.

### ISSUE THREAD

**Issue by almet** [Zettlr/Zettlr#375]
It would be great to have a way to move files from one folder to another one easily directly from the Zettlr interface.

**Comment by nathanlesage** [comment]
… this … is already possible. Simply drag&drop the files onto the folder where you want them to be.

**Comment by almet** [comment]
So, it seems not to be working for me. I'll investigate why it's not working :-)

**Comment by almet** [comment]
I don't have a way to reopen this issue, but it seems to be a bug : after the dragndrop, nothing seems to happen. Let me know how I can help :-)

**Comment by nathanlesage** [comment]
Ouh, that's not good :S 

Then first things first:

1. Does anything show up in the console? (To open: Enable Debug in the Preferences, then from the menu choose Develop -> Developer Console) — errors are bright red!
2. Then: Did something happen on your disk? That is: Did Zettlr move the file without indicating so?
3. Does the rest of the app still work or does anything else stop working as well? (Normally an indication that something went wrong in the main process --> These errors won't show up in the console)

**Comment by almet** [comment]
Thanks for the instructions. I've followed them. No error seem to show up in the console.
When I move the file, I see this in the console, not sure if related : 
![image](https://user-images.githubusercontent.com/67073/68060514-909fee00-fcf8-11e9-823c-41e051169a2d.png)

**Comment by almet** [comment]
(And the rest of the app seem to continue working properly, yes!)

**Comment by samarulmeu** [comment]
If you are using Linux, Zettlr doesn't handle well moving files between different storage devices. I had trouble moving files between a usb stick and my /home or an remote mounted folder.  

Maybe this is the case...

**Comment by almet** [comment]
I'm using Linux, yes ! But I'm moving a file from one parent folder to a child parent, on the same storage device.

**Comment by nathanlesage** [comment]
It might be related to how the file system is handled. In the past two releases, the Electron team developed a good sense of breaking critical APIs without notifying people, so it might be because of this. But I would have to investigate.

And the console output is some debug code I forgot to remove, it should contain all loaded files and folders as JSON representation 😅

**Comment by dcanl** [comment]
Hi guys,

Same problem here, on a Windows 10 machine with v. 1.4.3

Good luck for fixing this! :)

**Comment by nathanlesage** [comment]
Thanks for your input!

I think I already found the error — let me guess: You're using the **combined** sidebar, and not the thin or expanded one?

If so: I just did a quick test and indeed using the combined mode file moving does not work, while moving in thin or expanded works as expected!

@dcanl @almet Would you mind giving that a try?

**Comment by almet** [comment]
> I think I already found the error — let me guess: You're using the combined sidebar, and not the thin or expanded one?

Yes, it's the case! Using thin and expanded sidebar works like a charm :-)

**Comment by nathanlesage** [comment]
Tadaaaaa!

Well, not so Tada, as I now have to find the error in the Vue templates 🤪

**Comment by dcanl** [comment]
Yeah, congrats for finding the exact circumstances! I confirm: behavior is ok in thin and expanded sidebar, but not in combined sidebar.

I now use another display mode for the sidebar as a temporary workaround.

**Comment by nathanlesage** [comment]
Found it, fixed it, did it 😎

(Probably the modern veni, vidi, vici, but idk)

**Comment by almet** [comment]
Neat!
