### ISSUE TITLE
"Citing with Zettlr" Tutorial - Bad Instructions

### ISSUE THREAD

**Issue by J-Kappes** [Zettlr/Zettlr#3752]
### Description

The tutorial says to go to the "references database" field in the "Export" tab in the preferences.
I actually had to go to the "Citation Database" field in the "Citation" tab in the preferences.

### Reproducing

Read the "Citing with Zettlr" Tutorial.

### Zettlr Version

Stable (most recent version)

### Specify version

v2.3.0 Fedora Flathub

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 36 GNOME 42.2

**Comment by wideaperture** [comment]
I noticed the same thing and will create a PR when I have an opportunity to fix the problem. For future reference, note that there's [a separate ticket system for issues with the documentation.](https://github.com/Zettlr/zettlr-docs/issues)

**Comment by nathanlesage** [comment]
@wideaperture Yes and no. In this case, the files that need to be updated are here in the repo, in the `static` directory. Please feel free to update the instructions there and start a new PR with them. Thanks!

**Comment by nathanlesage** [comment]
Just doublechecked, the tutorial looks fine now. Feel free to suggest any changes, nevertheless!
