### ISSUE TITLE
Yaml Parse error when export file to PDF (latex) or HTML

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [Zettlr/Zettlr#3758]
### Description

When I try to export a file to HTML or PDF (latex), It gives the following YAML error:
```
An error occurred on export: YAML parse exception at line 2, column 50:

YAML parse exception at line 2, column 50:
mapping values are not allowed in this context
```

The YAML preprocessor is copied straight from an example file, which does export.

### Reproducing

- Open the MD file
- Export to PDF (LaTex) or HTML
- Error pops up

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterey 12.5.1

### Additional Information

I installed full MacTex as per the instructions in Zettlr.
I use the following features that are "extra" in my mind:
1. Imported Zotero sources as per the instructions
2. JSON codeblocks
3. Tables and images?

**Comment by TeaDrinkingProgrammer** [comment]
It is fixed somehow. When I opened the file today, it showed the 3 dots at the end behind the last line. When I put "---" under the last line and tried exporting again, the issue is fixed. Current yaml preformatter line:
```yaml
---

title: "Title" 
author: Name

---
```

**Comment by nathanlesage** [comment]
Yes you do have to put the three dots or three dashes on their own line (but you don't have to space them out with a blank line as in your example).
