### ISSUE TITLE
Ability to access multiple attachments via footnotes/Zotero

### ISSUE THREAD

**Issue by joep1977** [Zettlr/Zettlr#3759]
### Description

When Zettlr and Zotero are connected you can open linked attachments in Zettlr through Zotero. 

![Schermafbeelding 2022-09-10 151530](https://user-images.githubusercontent.com/96820649/189485023-a6557ce1-340b-4cb6-b5c4-d8a97b3167d4.png)

![Schermafbeelding 2022-09-10 151650](https://user-images.githubusercontent.com/96820649/189485071-c848684a-2bb9-4213-8315-de8388507c65.png)

This is awesome! But, occasionally, I have more then one attachment (PDF's) connected to a resource and I would like to choose which one to open. Now, it only opens the attachment that is first listed.

### Proposed Changes

I would like to chose between the available attachments instead only have the option to open the first that is listed in Zotero.

### Caveats

There are no caveats I can think of.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
In theory should be fairly easy, although I have never seen using multiple PDF attachments! Right now, Zettlr always simply uses the first one.

**Comment by joep1977** [comment]
I understand. It would be convenient accessing multiple PDF's but It's minor, so don't break your neck for it ;)
