### ISSUE TITLE
How to quickly insert mathematic symbols?

### ISSUE THREAD

**Issue by librix** [Zettlr/Zettlr#376]
I want to know how everyone can quickly enter mathematical symbols. I always feel that my typing speed can't keep up with my own thoughts.
I know some tools, like:
![image](https://user-images.githubusercontent.com/10742127/68026468-cb9b2500-fcea-11e9-9b85-ca50aa017c3e.png)
[When using a backslash](https://www.mathcha.io/), a dialog box will be called up with common symbols.
Some tools automatically add the remaining unentered parts of a word when entering few letters. If there are multiple candidate words, press the tab key to switch around. 

Is it possible for zettlr or its pramgram language to add a similar feature, OR some tips on how to insert mathematic symbols quickly, which can be used with Zettlr?

**Comment by nathanlesage** [comment]
The main target group of Zettlr is social scientists. While we strive to make the app accessible to any group, especially bigger features (such as the one you are proposing) will only happen if we have the time and resources, which we currently don't. Nevertheless, we have kept the editor itself very open, which means that you should be able to easily plug helper programs (such as an "emoji picker", only for Math symbols) into your workflow!
