### ISSUE TITLE
Newlines ignored in texmath.

### ISSUE THREAD

**Issue by LeSnake04** [Zettlr/Zettlr#3761]
### Description

When exporting documents using texmath, new lines inside 
$$ 
1+2 = 3\\
3+4 = 7
$$ 
dont get exported.
the export looks like this instead.
1+2=33+4=7

Happens with
+ pdf-latex
+ pdf
+ html

On .odt formulas using $$  $$ get exported as plain text.

Example:
![image](https://user-images.githubusercontent.com/47243761/189528234-b286db38-5c26-444b-b4e7-dc44b40008d3.png)
becomes 
![image](https://user-images.githubusercontent.com/47243761/189528253-2819d66a-ead2-4ea2-b60d-62d70b6bb193.png)

### Reproducing

Write a document using
$$
<Fomula>
$$
 that uses \\\\ to seperate lines.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

### Additional Information

Installed through Pacman,
Also happend with flathub version (didnt test pdf-latex on flatpak)

**Comment by nathanlesage** [comment]
@tobiasdiez @kyaso You two have more experience than I do with KaTeX/MathTeX. Any ideas?

**Comment by tobiasdiez** [comment]
Not sure, it seems like Katex is rendering it correctly. Maybe try to put the content in additional `\begin{xyz}...\end{xyz}` environments with `xyz` being something like `equation` or `align` depending on the packages you are using.

**Comment by LeSnake04** [comment]
I am using katex in html without any modifications

**Comment by nathanlesage** [comment]
Oh right, it's not the fault of KaTeX. Mh, as this happens during export the next idea I would have is to manually choose a MathTeX renderer. Try to modify the `reader` property in the respective defaults files to not read `markdown` but `markdown+tex_math_dollars`. Maybe explicitly activating that extension helps?

**Comment by LeSnake04** [comment]
Doesn't look like its changing anything. Also I noticed its not completely ignored - the \\ clearly get detected, since are not printed. 

But it somehow doesn't render the new line

**Comment by LeSnake04** [comment]
I found the upstream issue: https://github.com/mathjax/MathJax/issues/2312

The current workaround is wrapp[ng everything in \displaylines{
}

Can you implement that all $$ ... $$ get wrapped in that?

**Comment by nathanlesage** [comment]
I think that's something you can fix with the Pandoc default files in the meantime. I don't know exactly which version Pandoc uses, but you should be able to either (a) use a different Math parser, (b) use specifically MathJax v2, or (c) write a small piece of code that performs the wrapping on export.

Maybe @tarleb already knows where in the docs those options are explained?
