### ISSUE TITLE
Cursor misalignment when starting to type heading

### ISSUE THREAD

**Issue by memeplex** [Zettlr/Zettlr#3762]
### Description

When I type `# ` in order to start entering a markdown header the cursor temporarily misaligns as shown in the following image:

<img width="133" alt="image" src="https://user-images.githubusercontent.com/2845433/189547482-82c7212c-04f5-484a-917c-009f5ef5702b.png">

### Reproducing

1. Enter `# `

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Monterey

**Comment by nathanlesage** [comment]
This is a known bug and there's unfortunately nothing we could do about it. But the issue will be remedied as soon as we switch over to Codemirror 6. There the cursor position is perfectly fine.
