### ISSUE TITLE
Unable to copy ID

### ISSUE THREAD

**Issue by memeplex** [Zettlr/Zettlr#3763]
### Description

The Copy ID function does nothing.

### Reproducing

1. Create a blank page
2. Use Cmd-L (or Edit/Generate new ID) to enter an id
3. Use Cmd-Shift-L (or Edit/ Copy ID) to copy the id
4. Try to paste the ID with Cmd-V (or Edit/Paste)
5. Nothing happens or previous contents of the clipboard are pasted instead of the ID

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Monterey

**Comment by nathanlesage** [comment]
This has been fixed I think two weeks ago. Works in the current nightlies.
