### ISSUE TITLE
Misinterpreting folder as file when the name contains special char (+=)

### ISSUE THREAD

**Issue by Deadbush225** [Zettlr/Zettlr#3768]
### Description

I'm trying out my obsidian vault in Zettlr but I noticed that my folder that contains (+) is not showing its content. I double-checked it and I discovered that it also does this behaviour with (=). 

**This is the view in Zettlr:**
![2022-09-13 - 3925 -  15-02-30](https://user-images.githubusercontent.com/75558018/189833916-b6b7e26f-8ec6-4bc7-b250-e99ccb0a04be.png)

**While this is the view from windows explorer:**
![2022-09-13 - 3926 -  15-09-15](https://user-images.githubusercontent.com/75558018/189834352-82a8615a-4dab-4606-afd5-02310f82e5a4.png)

### Reproducing

You just need to create a folder/directory in your workspace, and name it that contains any of these characters (=) (+).

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.6

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Two things I'd like you to do before we can dig into the issue:

1. Please update to the latest version (2.3.0) to double-check that the issue hasn't been fixed in the meantime.
2. Please have a look in the logs if something seems off there.

**Comment by nathanlesage** [comment]
Works perfectly fine in the current nightlies.
