### ISSUE TITLE
Moving files externally generates an error message.

### ISSUE THREAD

**Issue by almet** [Zettlr/Zettlr#377]
Sometimes, when I move files around in my file explorer for instance, I'm getting an error in Zettlr, here is a screen cap:

![image](https://user-images.githubusercontent.com/67073/68032129-f2d6ff80-fcb4-11e9-8128-f7b6e94f3542.png)

**Comment by nathanlesage** [comment]
Ah, thanks for the notice! I'll see to it! :)

**Comment by nathanlesage** [comment]
As I've completely rewritten that whole code, I think the error should be fixed. However, if it isn't please comment so that we can look at it again!
