### ISSUE TITLE
File has been changed remotely

### ISSUE THREAD

**Issue by joep1977** [Zettlr/Zettlr#3773]
### Description

All of sudden I get "file has been changed remotely" notifications. When I change a single character, after a few seconds, the notifications pops up. I run Zettlr both on a PC and laptop and it seems that one wants to overwrite the other. The issue BTW also occurs when I run Zettlr exclusively on my PC.

### Reproducing

Change a character and the notification pops up.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
Do you use any Cloud provider to backup your files? Or anything else?

**Comment by joep1977** [comment]
Yes, I use Google Drive on both machines. But just as sudden as it occurred, it stopped. So, currently it works fine. Maybe an hickup on Google Drive's end?

**Comment by nathanlesage** [comment]
That might be. Cloud synchronization can sometimes really be finnicky!

I'm going to close the issue; if it returns feel free to take as many notes as you can and comment here so we can reopen it.
