### ISSUE TITLE
macOS: If I copy & paste a file / image only the icon is gonna be pasted to Zettlr markdown file.

### ISSUE THREAD

**Issue by exislow** [Zettlr/Zettlr#3778]
### Description

If I copy an image / any file using `cmd + c` from Finder and paste in a Zettlr markdown file using `cmd + v` only the icon of the copied file is going to be inserted into the markdown file.

But I do not want to have the icon inserted, but rather the actual content of the file. This is only possible while performing a drag & drop using my touchpad, which actually only inserts a relative link to this file but at least not the unnecessary icon of the file.

### Reproducing

`cmd + c` & `cmd + v` of any file from your file system.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterey 12.6

**Comment by nathanlesage** [comment]
Just tried this out, I'd have to think about this. The reason Zettlr behaves like this is because Google Chrome, for example, always writes BOTH the image to the clipboard as well as the link from which it came. I might need to develop a better algorithm for this.

Feel free to already think about in which instances inserting text instead of the image might be appropriate. The more info I have the better I can do this.

**Comment by exislow** [comment]
So what actually would be very beneficial ist, whem I have copied a file and I paste it via `cmd + v` into Zettlr, I would like to have the file actually copied into my Zettlr `assets` directory and linked within the markdown file. Is this possible to acomplish?

When I drag any file into Zettlr I would like to have just file linked (absolut link) into the markdown file without copying the file. Or you also could realize the same behaviour for drag and drop as for `cmd - v`: Copy the file and link it. I don't mind.

@nathanlesage: What do you think about this?

**Comment by nathanlesage** [comment]
@boutil Alright, so on Linux it apparently works as expected: Only the actual file is being copied/pasted, not its file-manager icon. That is good to know.

Then to @exislow:

> Is this possible to acomplish?

Yes, and there have been a few calls to this. I do not have the time needed to implement this yet.

**Comment by exislow** [comment]
In my opinion and apparently towards the calls of others this is a super handy feature, which could boost the productivity working with Zettlr times 1000 (maybe I exaggerate times 10 ;-)). Is it possible to prioritize this feature somehow to a certain factor? Big thanks in advance and thank you very much for your effort towards Zettlr v3.

**Comment by nathanlesage** [comment]
> Is it possible to prioritize this feature somehow to a certain factor?

Unfortunately no. I'm completely overworked and barely getting to fixing the existing bugs for 3.0. But if you know someone who knows how to code feel free to give them this task.

**Comment by exislow** [comment]
Thanks a lot!
