### ISSUE TITLE
Zettlr-win32-x64-1.4.3.exe is 532 Kilobytes.

### ISSUE THREAD

**Issue by Noisecommander** [Zettlr/Zettlr#378]
The Zettlr 1.4.3 installer for Windows is only 532 Kilobytes.
It doesn't open an installer and if I unpack it, it only has the the file "Z_\Users\hendrik\Documents\Zettlr\release__uninstaller-nsis-zettlr.exe" in it.

The SHA-256 sum that comes with it is correct for this package, though.

![zettlrkb](https://user-images.githubusercontent.com/47405126/68063752-c43c4180-fd13-11e9-8eb0-86e00bc131bf.png)

**Comment by nathanlesage** [comment]
Huh, I didn't see that. Just re-ran the setup and saw that apparently wine is broken. I'll see to running a build asap on another machine!

**Comment by nathanlesage** [comment]
Release is fixed, the Windows installer should work now! Sorry for the mess I made, I hope it's all good now!

**Comment by Noisecommander** [comment]
Cheers man, enjoy your weekend.
