### ISSUE TITLE
Document wiped clean. Where is version control?

### ISSUE THREAD

**Issue by datavectors** [Zettlr/Zettlr#3780]
### Description

This is the second occasion that I have been writing an important Markdown document, on Ubuntu 20.04, and it has been wiped clean while typing. Lost. 

I recollect that I was doing a string replace "string1" replacing "string2".
In fact earlier I lost all letters "i" and you can imagine the effect. I could not unwind.

There seems to be no version control to go back say 10 minutes or delete actions taken. Version 2.3.0 in use.
I am very wary now and plan to build my own backup system.
I have about a dozen other documents in the file system. All vulnerable.

### Reproducing

I do not know what UI action caused the deletion. If it is a Zettlr action a warning note should appear to warn the writer. Instead I am left with just a few characters on the screen.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

No such events seen in other editors used in past on my desktop such as Atom, Visual Studio, Sublime Text. Just Zettlr which although having a nice UI cannot be trusted on important documents without having a script to make frequent rolling backups.

**Comment by nathanlesage** [comment]
This sounds like a very annoying bug. Please try to replicate this – if it is indeed a malfunctioning search-and-replace operation it should be easy to find and fix.

**Comment by datavectors** [comment]
This is a journal of my attempts to reproduce the "glitch" I experienced. I accept that there is a possibility that rather than this being a bug this is due to my inexperience in navigating Zettlr UI.

I start by going to File  > New File > Markdown.

I note that I an unable to create a filename at this stage. The "buffer file" is crypto named 20220921170154.md. But I see that this interim file name be changed at the first point of saving.

>_I note that I have several such coded file names in my documents folder and I suspect that this might be one clue to my broken use of UI_.

>_I recollect that when I was using Zettlr at time of document loss there were several "File Save As" sessions attached to the Zettlr icon in my docking bar (in Ubuntu)_. 

After typing some sentences, now to avoid losing content, I copy and save to another note editor CherryTree which in fact pushes down several archived versions at defined intervals (I choose 3 versions at 5 minute intervals). A feature I would like to see in Zettlr.

But in the interim I will use a custom background automation script for this purpose. That is backup Zettlr documents to CherryTree which has built in backup control in its Preferences.

At time of writing this journal I am backing up manually from time to time - Zettlr to CherryTree - to guard against possible document loss.

>_Perhaps a useful addition to Zettlr UI would be to add File > Backup (to defined file or note editor such as into CherryTree node. CherryTree has a [command line feature](https://www.giuspen.com/cherrytreemanual/#_command_line)_. 

I now attempt to reproduce the loss of document I recently experienced. 
 
Since earlier I had to hit a deadline, I rewrote the lost document in Atom (now regrettably being "sunset" by Github in favour of Visual Studio Code, Microsoft's flagship editor) with [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/) package installed. That went very smoothly, but I do still like the clean UI of Zettlr, once I become familiar with workflow and possible bear traps.

>_It would be appealing if Zettlr could also add Markdown Preview Enhanced as an option_. 

Next I attempt to change characters in my document open in Zettlr.  It might be that I tried this _before_ the buffer file had first been saved. Hence the multiple "Save File As" sessions I later saw in my docking bay.
 
>_Perhaps before some actions are applied Zettlr should first check that the document has been securely saved or archived in its present form before applying Find in File. Thus any mishaps would be recoverable._

I venture to try finding letter "I".

Edit > Find in File

"I" to "i".

Hit “Replace all occurrences”.

Horror. I cannot read.

If I inadvertently change “I” to blank “” it is worse.

I hit Edit > Undo, but I cannot correct this incorrect action.

Conclusion.

* I need to have a scheduled backup process in frequent use automatically every n minutes in a pushdown stack (outside Zettlr).

* I need to go back to different snapshots.

* I need to safely reverse Search and Replace actions.

**Comment by nathanlesage** [comment]
Alright, so the current release of Zettlr allows you to have files which are not (yet) saved on disk, and instead are kept in-memory only. The benefit of this was that you could quickly create a sort of scratch pad with info you didn't need to write to disk. However, that has in the meantime been ditched, so every file open in Zettlr will be stored somewhere on disk.

Until then, do not ignore these "Save file as"-dialogs, and use them in order to keep all your files. I hope to be starting the next beta phase soon which is when I will have much more time and mental resources to get into such details as in here.

**Comment by datavectors** [comment]
Thank you for the advice.  So this seems not to be a "bug". Just my misunderstanding of Zettlr workflow.

I am very content with the clear UI of Zettlr, but I have decided to use Zettlr in concert with either Atom or Visual Studio Code or Sublime Code. My reasoning is that I can draft document in Zettlr then finish off by applying the multitude of external external packages (not least Markdown Preview Enhanced).  I have read that you prefer Zettlr to be lean in features and this is a good goal. But this way I can get the best of both worlds cooperating in a tool chain. And you need not be pressed to consider new "features".

**Comment by nathanlesage** [comment]
As in-memory files are now gone anyways and it seems to be based on a miscommunication, I will be closing this issue.
