### ISSUE TITLE
Setting language for citations/bibliography not working (dutch)

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [Zettlr/Zettlr#3785]
### Description

I am using Zetlr and loving it so far! The problem is that I want my citations in dutch when exporting to PDF, as the report I am writing is in dutch. I have set APA as the default by setting the [apa.csl file](https://www.zotero.org/styles/apa) from the [Zotero repository](https://www.zotero.org/styles?q=apa) as the default. To set dutch as the default language I tried the following to no avail:
```yaml
lang: nl
```
and in the asset manager under PDF:
lang: nl.

I keep getting sentences like: "Retrieved January 1, 2022" in my bibliography.

### Reproducing

1. Cite using Zotero as described in the docs
2. Export using PDF
3. Set lang: nl in YAML preprocessor
4. Bibliography is in English.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 36

**Comment by nathanlesage** [comment]
If I remember correctly the standard APA style requires English, I don't know if this can be solved with a different version of the stylesheet, but there are a few varieties of the APA style on the Zotero repository, maybe one of them does it. Another test might be to try out a style that you know works in dutch and see if it still exports as English.

**Comment by TeaDrinkingProgrammer** [comment]
> If I remember correctly the standard APA style requires English, I don't know if this can be solved with a different version of the stylesheet, but there are a few varieties of the APA style on the Zotero repository, maybe one of them does it. Another test might be to try out a style that you know works in dutch and see if it still exports as English.
Thanks, I'll try using a dutch style, see if that works

**Comment by TeaDrinkingProgrammer** [comment]
I tried with [this style](https://www.zotero.org/styles?q=id%3Awolters-kluwerbrede-schrijfwijzer-author-date) which has nl-NL as the default locale, but it doesn't seem to work.
Yaml frontformatter:
``` yaml

title: "Stageverslag" 
author: Stijn van Houwelingen
lang: nl
csl: wolters-kluwerbrede-schrijfwijzer-author-date

```

**Comment by nathanlesage** [comment]
Since I saw you included the CSL style within the YAML frontmatter directly: Zettlr will overwrite that with whatever CSL style you chose in the preferences, so you'd need to change it there instead. Would you mind trying this out?

(Also, I need to look up how YAML frontmatter versus defaults file variable resolution works in Pandoc, dammit)

**Comment by TeaDrinkingProgrammer** [comment]
I have found the issue, it was my bad. It had to do with the way I formatted my YAML frontformatter, not with languages or styles. For future reference:
 ```
---

title: "Stageverslag" 
author: Stijn van Houwelingen
lang: nl

---
```
is not a valid frontformatter, as it has whitespace.

```
---
title: "Stageverslag" 
author: Stijn van Houwelingen
lang: nl
---
```
is valid.  
Do you think this would be something to add to the documentation (which I would have no problem doing) and/or to mitigate in code or should it stay as it is? It says as much in the documentation, but not explicitly this issue.

**Comment by nathanlesage** [comment]
> Do you think this would be something to add to the documentation (which I would have no problem doing) and/or to mitigate in code or should it stay as it is?

Ouh, let me quickly check if the linter already has such a rule, as we have this new little helper, it would be ideal to add a rule for that.

**Comment by nathanlesage** [comment]
Even easier: I have now disallowed frontmatter parsing when there's leading whitespace (trailing whitespace, i.e. after the frontmatter is perfectly fine). In other words: If there's now leading whitespace, the frontmatter simply won't render as a frontmatter anymore, giving enough clues to users that what they're typing won't be recognized as a frontmatter.
