### ISSUE TITLE
Cursor jumping on newline

### ISSUE THREAD

**Issue by newhinton** [Zettlr/Zettlr#3798]
### Description

When adding a newline, a short time later, the focus&cursor jums to the beginning of the file. 

### Reproducing

- Type in note
- add newline via enter-key
- dont stop typing
- see mouse jumping, leading to input at wrong place

### Zettlr Version

Right off the develop branch

### Specify version

a87e0d99c51694d0a622d192a3ab0e08c466a5fd

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

KDE 22.04

**Comment by nathanlesage** [comment]
I'm closing this issue since it will soon be superseded with the Codemirror 6 implementation. What you could do is try it out with that PR. If it exposes the same behavior, we can reopen this issue!
