### ISSUE TITLE
[Wish] support MetaWeblog

### ISSUE THREAD

**Issue by jeffery9** [Zettlr/Zettlr#380]
## Description
need the support of MetaWeblog

## Expected behaviour

**Screenshots**

## Platform
 - OS Version [e.g. 11]
 - Zettlr Version [e.g. 0.15]
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Sorry, currently we're not supporting automated posting of files to external APIs. Maybe at a later time, when we have more resources left.
