### ISSUE TITLE
Footnote duplication

### ISSUE THREAD

**Issue by getkey** [Zettlr/Zettlr#3807]
### Description

When a footnote is used multiple times on the same page, it gets duplicated in the export.

### Reproducing

Here is a reproduction case:

```md
This sentence has a footnote.[^1] So does this one, the same actually.[^1]

[^1]: a very interesting comment.
```

And this is what it looks like when exported.

![image](https://user-images.githubusercontent.com/6908397/193867343-4abc6c3b-fb86-45f8-9f0e-90ab8e36dc79.png)

### Zettlr Version

Stable (but an older version)

### Specify version

2.2.6 (from https://github.com/NixOS/nixpkgs/blob/81a3237b64e67b66901c735654017e75f0c50943/pkgs/applications/misc/zettlr/default.nix, which is the official AppImage)

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

NixOS 22.05

**Comment by jgsw** [comment]
This is a known bug with Pandoc (which is used for all the exports from Zettlr). Unfortunately, it doesn't seem like it's likely to be fixed in Pandoc any time soon: https://github.com/jgm/pandoc/issues/1603. So it may not be feasible to fix it from within Zettlr.

**Comment by nathanlesage** [comment]
I just saw this issue – sorry for the late response. As @jgsw mentioned, this pertains to Pandoc, not Zettlr.
