### ISSUE TITLE
[BUG] Zettlr crashes on some Windows 10 installations

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#381]
## Description

I'm opening this issue, as some folks over at both Reddit and YouTube have indicated that 1.4.3 does not work on their Windows 10 machine (some also that none of the previous versions worked). I am not sure as to the cause of the problem, but as multiple persons experience these problems, I assume we need to look into it. 

## Reproducing

Unknown, apart from using a Windows 10 computer.

## Expected behaviour

Zettlr should start and be usable.

**Screenshots**

## Platform
 - OS: Windows
 - OS Version. 10
 - Zettlr Version: 1.4.3, for some down until 1.3.0

## Additional information

As I lack the resources to check out the exact reason behind this, I would appreciate it, if someone who owns a Windows 10 machine could dive into that problem and see whether or not they can find some hints as to what might be the problem. I honestly don't have any clue.

**Comment by StoltHD** [comment]
I dont get any windows logs thats detailed, but It appairs to be a problem with registrations of COM objects.
It installs if installed only for the user, but doesn't work after started.
Can't see folder even when the program tells you it has opened one, can't create new files...

After installed for "user", zettlr do not show in the list for installed apps, so you have to go to the apps folder to uninstall it...

It looks like there are multiple COM objects (system object for i.e. files and folder) that do not get registered and/or installed)...

When trying to install for all users, the installer stops at 2/5 on the progress bar.

If you create a installer that lists the object names when installing, I can run it and see if I can see where it stops... or if you can create an installer with that either write to event log or to a log file... 

This is the eventlog (i have deleted changed the names of computer and user name and ID).
The log is in Norwegian, but you should get an idea...

this is an article about solving the problem, but it should be done with the installer somehow... I also have the problem with version 1.42

Even though this is only a warning that Microsoft say we can ignore, this is the only event log entry occuring  on my system and only when trying to install zettlr.
I run Windows 10 Insider build 19018.

If this is the only reason for the Hang/Crash/not working problem, i do not know, but its the only Event Log Entry I can find.

.........................................................
LOG
-------------------------------
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" /> 
  <EventID Qualifiers="0">10016</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2019-11-13T09:00:22.2442380Z" /> 
  <EventRecordID>988</EventRecordID> 
  <Correlation ActivityID="{f88e1c7b-5099-4b52-b4f6-e6f6349c96b6}" /> 
  <Execution ProcessID="1112" ThreadID="10068" /> 
  <Channel>System</Channel> 
  <Computer>Computername</Computer> 
  <Security UserID="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" /> 
  </System>
- <EventData>
  <Data Name="param1">programspesifikk</Data> 
  <Data Name="param2">Lokal</Data> 
  <Data Name="param3">Aktivering</Data> 
  <Data Name="param4">{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}</Data> 
  <Data Name="param5">{15C20B67-12E7-4BB6-92BB-7AFF07997402}</Data> 
  <Data Name="param6">Computername</Data> 
  <Data Name="param7">username</Data> 
  <Data Name="param8">XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx</Data> 
  <Data Name="param9">LocalHost (bruker LRPC)</Data> 
  <Data Name="param10">Ikke tilgjengelig</Data> 
  <Data Name="param11">Ikke tilgjengelig</Data> 
  </EventData>
  </Event>

**Comment by StoltHD** [comment]
1.5 beta can still not be installed on Windows 10...

**Comment by StoltHD** [comment]
@nathanlesage - You do know that you can download a trial of Windows 10 and install it on a Virtual Server Image?

**Comment by nathanlesage** [comment]
Yes I know, but I do not have the space for it on my computer (128 gig MacBook, you know what you get…). Nevertheless, I must apologise — I didn't fully comprehend where it's breaking before. It looks a lot like a problem with the installer rather than with the app itself. It might be that this issue is related to electron-builder. Would you mind searching the issue list there for something that resembles your problem? If there is one issue, this might point us forward.

The only things I could imagine are either a wrong configuration on my part or an error when building on macOS. Crossplatform does get ugly from time to time.

**Comment by StoltHD** [comment]
The strange thing is that I use multiple other programs/software packages thats build on Electron...

I have search the net but only thing I find that explain something are the one I linked to above...

I will take a look at the electron community

**Comment by nathanlesage** [comment]
Puh, I really don't know. I don't compile anything, I just take the Electron binary as it's delivered and package them using electron-builder into the final installer files :/ So if there is something, it's either because electron-builder is malfunctioning on a darwin kernel, I forgot some configuration options OR there's some bug (for instance, I have to apply a certain CHMOD to the sandbox binary for linux builds, which has not been fixed until now; the thing is known for months).

So, I don't know; one thing you could try would be to run a build run on your machine and see if the installer works better. If so, it's a thing with compiling on macOS. If it's not, it's something deeper rooted...

**Comment by StoltHD** [comment]
Problem is, im not a developer, I don't know how to build stuff...

man. 25. nov. 2019 kl. 09:38 skrev Hendrik Erz <notifications@github.com>:

**Comment by nathanlesage** [comment]
I totally understand, but this doesn't make the task of verifying the integrity of the installers easier …

**Comment by StoltHD** [comment]
I can seend you a Process Monitor log of files and registry if it might
help you, but then I need to send it to you personally... just send me a
email directly and I will replay on that... It might tell you more than it
does for me...
I have saved it as a csv (1,8MB)

man. 25. nov. 2019 kl. 16:59 skrev Hendrik Erz <notifications@github.com>:

**Comment by nathanlesage** [comment]
Closing b/c this issue seems to have somehow absolved itself …?

**Comment by bobvanvliet** [comment]
For me it hasn't. (fully updated W10 on Bootcamp). Here's what it looks like:

![Annotation 2020-02-19 120310](https://user-images.githubusercontent.com/1838537/74828974-5478b380-5310-11ea-923f-4464329897cc.png)

![Annotation 2020-02-19 120310a](https://user-images.githubusercontent.com/1838537/74828997-5e021b80-5310-11ea-8641-40ef892c93db.png)

![Annotation 2020-02-19 120310b](https://user-images.githubusercontent.com/1838537/74829005-6195a280-5310-11ea-831b-3471a183f87d.png)

![Annotation 2020-02-19 120310c](https://user-images.githubusercontent.com/1838537/74829011-65c1c000-5310-11ea-8739-5d3759bfaf92.png)

**Comment by nathanlesage** [comment]
As it is Windows10 on Bootcamp, it could very well be a driver issue, neither Apple nor Windows care so much about each other, and Bootcamp can prove to be a horrible experience. Does it work on the macOS installation?

**Comment by bobvanvliet** [comment]
I assume so, if there's no trouble with Zettlr on other MacOS instances. But I work exclusively in Windows (due to other software needs) and no apps are installed in MacOS other than bare installation.

I'll wait and see wheter future versions of Zettlr or Electron make the issue go away. One final bit of information that could possibly be relevant: I used to have Electron installed for fooling around with. If that's the case for others with the problem, that may leave something behind that mucks things up.

**Comment by nathanlesage** [comment]
Mh, it should not be, but Electron has had its due share of problems in the past, so I won't rule that out :/ I hope they get back on track soon
