### ISSUE TITLE
Impossible to rearrange Table of Contents by click & drag

### ISSUE THREAD

**Issue by Julianoe** [Zettlr/Zettlr#3811]
### Description

I can't rearrange sections of content using the Table of Contents in the sidebar.
The feature described here does not work for me https://github.com/Zettlr/Zettlr/issues/88

I checked the console log for errors and nothing seems to be output there. I just can't drag the titles.

### Reproducing

I tried using a fresh install and still can't interact with Table of Contents other than clicking on sections to scroll to it.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0-1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro 22.0.0 Sikaris

**Comment by nathanlesage** [comment]
There was a bug somewhere in time, but good news: I re-implemented that just yesterday in the upcoming Codemirror 6 PR, so it'll be a thing again in 3.0!
