### ISSUE TITLE
CURRENT_ID, FILENAME, DIRECTORY, EXTENSION snippet variables don't work

### ISSUE THREAD

**Issue by Shidouuu** [Zettlr/Zettlr#3822]
### Description

For some reason the variables in [this list](https://docs.zettlr.com/en/core/snippets/#snippet-syntax) starting from `CURRENT_ID` do not work and simply turn red instead of retrieving information like the other variables.  For `CURRENT_ID`, I expect it to fill in the current Zettelkasten ID.

![image](https://user-images.githubusercontent.com/36283656/195859723-f57c974b-0147-4328-9e0a-5816a6f1643b.png)
![image](https://user-images.githubusercontent.com/36283656/195859868-7dd521b6-5309-44ef-b19f-e307b9677277.png)

### Reproducing

1. Goto Asset Manager
2. Goto Snippets
3. Type in `$CURRENT_ID`
4. See results
5. ????
6. Loss.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Yeah that's known, I had intended to implement those and then literally forgot that. In case I still haven't done so when we're in the public beta for 3.0, please pong me again!

**Comment by Shidouuu** [comment]
Got it.

**Comment by nathanlesage** [comment]
The snippets variables have been added to source, and are available in the current nightly; they'll therefore ship with the betas and the regular 3.0 release.
