### ISSUE TITLE
Folder drag and drop seems to not be working

### ISSUE THREAD

**Issue by almet** [Zettlr/Zettlr#383]
I'm not sure if this is related to #375, so I'm opening a new issue.

I'm on the latest release, using the "wide" sidebar, but moving folders doesn't seem to be working. When I finish the drag and drop, just nothing happens.

So I though, while this is fresh in your memory, I'll open another ticket.

**Comment by nathanlesage** [comment]
Does this still happen in 1.5-beta?

**Comment by almet** [comment]
It seems to be fixed in the beta, good job :-)

**Comment by nathanlesage** [comment]
Nice to hear :)
