### ISSUE TITLE
Sorting files button does not appear in V2.3.0

### ISSUE THREAD

**Issue by Blistax** [Zettlr/Zettlr#3839]
### Description

I try to sort my files that are listed in the file list to dates. Now the sorting order is in alphabetical order. In previous versions I could go to the folder and a small icon appeared where I was able to change the sorting order. This is also instructed in the documentation (https://docs.zettlr.com/en/core/file-list/).

### Reproducing

Tried placing mouse over folder/filename where there should appear a button for sorting the files.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 Build 19044.2130 Version 21H2

**Comment by nathanlesage** [comment]
Ouh, the documentation is clearly outdated in this regard. Sorting should be possible via right-clicking the directory and choosing "Properties".

**Comment by Blistax** [comment]
Ah that worked @nathanlesage ! Thank you :)
