### ISSUE TITLE
Workspaces fixed path

### ISSUE THREAD

**Issue by aviler** [Zettlr/Zettlr#3842]
### Description

If I try to `File -> Open Workspace...` the select folder dialog only allows me to select something inside my `~/Documents/` folder. Would be good if I could select any folder on my system.

Could be because I installed Zettlr from flatpak?

### Reproducing

On a flatpak installation, go to `File -> Open Workspace...` the dialog should allow you to select any user's folder like `~/Pictures/` instead of just `~/Documents/`.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Fedora 36

**Comment by nathanlesage** [comment]
> Could be because I installed Zettlr from flatpak?

Yes, that's the reason. The maintainer of the flatpak repository has deliberately set the permissions of the flatpak to minimal but mentioned that there is another package that you can use to extend the access rights of the app to other folders! Unfortunately I have forgotten the name of the package, but it's out there!
