### ISSUE TITLE
Text could NOT display correctly

### ISSUE THREAD

**Issue by yangby-cryptape** [Zettlr/Zettlr#3843]
### Description

It's my first time to use this application, so there is no any legacy configurations.

Text could NOT display correctly when I opened the application first time, not only in editor but also in menubar, toolbar and so on.

Only the text in Markdown code blocks, the text in the settings dialog, the text in the menu and the text in the tip of toolbar buttons can be displayed correctly.

<details><summary>Click HERE to see Screenshots of this bug.</summary>

![image](https://user-images.githubusercontent.com/30993023/198826751-44927334-cd8e-49c1-a927-f46ceb277536.png)

</details>

### Reproducing

I don't know how to reproduce this, but in my laptop, the bug always exists.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian 11 (bullseye)

### Additional Information

My default language is English (`en_US.UTF-8`).
My default font is `Noto Sans Font Family`.

I tried both `Zettlr-2.3.0-amd64.deb` and `Zettlr-2.3.0-x86_64.AppImage` on both `i3` (my default window manager) and `GNOME`, the bug always exists.

I tried some other Electron-based applications in [this page](https://github.com/topics/electron), they don't have this bug.

I read the documents and add the following custom CSS, then all text are displayed correctly.
```css
* {
  font-family: "Noto Sans Mono";
}
```

<details><summary>Click HERE to see Screenshots with my custom CSS.</summary>

![image](https://user-images.githubusercontent.com/30993023/198827531-ad6fd086-dbde-4f08-9234-21946cf695a6.png)

</details>

There are many fonts in my OS, so I wonder that which font is the default font, but I missed.
And maybe Zettlr could use my default font that configured in `/etc/fonts`.

**Comment by nathanlesage** [comment]
Ah, fonts on Linux. I know there is some default ttf-package that one can install that will ensure all fonts are available that are required by Zettlr, but that one is not always preinstalled. Unfortuantely, I'm not completely versed in Linux these days, as I haven't been using Linux for several years now. I'll ask around on our Discord for others who may have an idea of how to fix that/add an entry to the FAQ that addresses this problem!

But I'm closing this issue as solved for now.
