### ISSUE TITLE
Export to any format: Error running filter - links.lua cannot open links.lua

### ISSUE THREAD

**Issue by DrumJB** [Zettlr/Zettlr#3844]
### Description

Hello, I am new to Zettlr community so I think I'm missing here something. I'm trying to export a Markdown file with Zettlr, but there is an error, which I can't solve: 
```
An error occurred on export: Error running filter C:\Users\USERNAME\AppData\Roaming\Zettlr\lua-filter\links.lua:

Error running filter C:\Users\USERNAME\AppData\Roaming\Zettlr\lua-filter\links.lua:
cannot open C:\Users\USERNAME\AppData\Roaming\Zettlr\lua-filter\links.lua: No such file or directory
```

### Environment
I have Windows 10. I installed MiKTeX and checked updates, pandoc 2.2.1 from GitHub zip file, and when I try to export the Markdown file with pandoc as PDF it works (from command line). I look for some help [here](https://github.com/Zettlr/Zettlr/discussions/2809), but it isn't the same problem

### Reproducing

When I try to export the current file with `Ctrl+E` and *Export*:
![image](https://user-images.githubusercontent.com/102988744/198834004-685be19e-ee23-4598-95e0-a523c73bb627.png)
It shows this error, as I mentioned before:
![image](https://user-images.githubusercontent.com/102988744/198834090-6693bca4-10a6-4f14-9c6b-a095d1584608.png)

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr 2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

As I wrote above, I think I'm missing something, but I can't find the right support. I'll welcome anything,
Thank you,

**Comment by DrumJB** [comment]
I try to change settings `Use the internal Pandoc for exports` to *No* and it isn't working but there is another error:
when exporting to *plain text*
```
An error occurred on export: Unknown option --defaults.

Unknown option --defaults.
Try pandoc --help for more information.
```

**Comment by nathanlesage** [comment]
Regarding your second comment first: It appears you are using an outdated version of Pandoc globally on your system (as this is what Zettlr uses if you do not use the internal Pandoc). Then, to your first error: It appears that somehow the filters have been removed somehow. I have no idea how this could happen, but the file that the app expects should be copied into the directory. I don't know why this doesn't happen, could maybe be a permission issue. Did you maybe do something to this directory? And, when was the last version that worked?

**Comment by DrumJB** [comment]
Ok, it seems to be my internal problem. I tried to uninstal and install everything (Pandoc and Zettlr), but that didn't solve anything. Thank you for quick response and explaining the problem!

**Comment by nathanlesage** [comment]
Feel free to follow the troubleshooting guide in the documentation and completely remove the directory of Zettlr in the AppData directory. Then, launch the app again. Then it should hopefully regenerate the directory structure including the expected Lua filters.
