### ISSUE TITLE
Zettlr stays dull on Manjaro xfce

### ISSUE THREAD

**Issue by nam1962** [Zettlr/Zettlr#385]
## Description
Once Zettlr launched, nothing appears on left panel, if trying to create new file or new directory, nothing happens, if trying to open directory, all .md (and other) files are greyed, if trying to right click open .md with Zettlr, empty Zettlr opens.

## Reproducing
Open Zettlr 1.4.3-1

## Expected behaviour

**Screenshots**

## Platform
`~]$ screenfetch

 ██████████████████  ████████     me@ordi
 ██████████████████  ████████     OS: Manjaro 18.1.2 Juhraya
 ██████████████████  ████████     Kernel: x86_64 Linux 5.3.8-3-MANJARO
 ██████████████████  ████████     Uptime: 3h 52m
 ████████            ████████     Packages: 1716
 ████████  ████████  ████████     Shell: bash 5.0.11
 ████████  ████████  ████████     Resolution: 1366x768
 ████████  ████████  ████████     DE: Xfce4
 ████████  ████████  ████████     WM: Xfwm4
 ████████  ████████  ████████     WM Theme: Agualemon
 ████████  ████████  ████████     GTK Theme: Adwaita [GTK2]
 ████████  ████████  ████████     Icon Theme: Numix-Circle
 ████████  ████████  ████████     Font: Noto Sans 9
 ████████  ████████  ████████     Disk: 291G / 922G (34%)
                                  CPU: Intel Core i3-2350M @ 4x 2.3GHz [56.0°C]
                                  GPU: Mesa DRI Intel(R) Sandybridge Mobile 
                                  RAM: 4491MiB / 11759MiB
`

 - Zettlr Version [e.g. 0.15] 1.4.3-1 from AUR

## Additional information

`~]$ cat .config/zettlr/config.json
{"openPaths":[],"dialogPaths":{"askFileDialog":"","askDirDialog":"/home/asatysco2/Bureau/Test","askLangFileDialog":""},"window":{"x":0,"y":0,"width":1366,"height":768,"max":true},"lastFile":null,"lastDir":null,"attachmentExtensions":[".pdf",".odt",".odp",".ods",".doc",".docx",".xls",".xlsx",".ppt",".pptx",".do",".r",".py",".sav",".zsav",".csv",".png",".jpg",".jpeg",".gif",".tiff"],"darkTheme":true,"alwaysReloadFiles":false,"autoDarkMode":"off","autoDarkModeStart":"22:00","autoDarkModeEnd":"06:00","fileMeta":true,"fileMetaTime":"modtime","hideDirs":true,"sorting":"natural","sortingTime":"modtime","muteLines":true,"sidebarMode":"thin","enableRMarkdown":false,"newFileNamePattern":"%id.md","newFileDontPrompt":false,"pandoc":"pandoc","xelatex":"xelatex","pandocCommand":"pandoc \"$infile$\" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $citeproc$ $standalone$ --pdf-engine=xelatex -o \"$outfile$\"","export":{"dir":"temp","stripIDs":false,"stripTags":false,"stripLinks":"full","cslLibrary":"","cslStyle":""},"pdf":{"author":"Generated by Zettlr","keywords":"","papertype":"a4paper","pagenumbering":"gobble","tmargin":3,"rmargin":3,"bmargin":3,"lmargin":3,"margin_unit":"cm","lineheight":"1.5","mainfont":"Times New Roman","sansfont":"Arial","fontsize":12,"textpl":""},"zkn":{"idRE":"(\\d{14})","idGen":"%Y%M%D%h%m%s","linkStart":"[[","linkEnd":"]]"},"editor":{"autoCloseBrackets":true,"defaultSaveImagePath":"","homeEndBehaviour":true,"enableTableHelper":true,"indentUnit":4,"countChars":false,"boldFormatting":"**","italicFormatting":"_","readabilityAlgorithm":"dale-chall"},"display":{"theme":"berlin","imageWidth":100,"imageHeight":50,"renderCitations":false,"renderIframes":true,"renderImages":true,"renderLinks":true,"renderMath":true,"renderTasks":true,"renderHTags":false},"selectedDicts":["en-US","fr-FR"],"appLang":"fr-FR","debug":true,"checkForBeta":false,"uuid":"80e57922-43c8-4981-a7cb-93a6bb3f18d1"}`

**Comment by nathanlesage** [comment]
Thanks for the report, but I think, judging from the information you provided, that you may have misunderstood how Zettlr is supposed to work:

1. When you first open Zettlr, it'll be empty. To start working with it, you'll need to open a directory (**not** a file!)
2. Once you've opened a directory, you can begin creating files and subdirectories.
3. This directory (or multiple) are supposed to stay opened within the app as your working directories.

As for the part that right-clicking MD-files don't open as expected, I am not sure. It might indicate a bug, but I would need the info if it works with at least one directory open.

**Comment by nam1962** [comment]
Hi, thanks for caring.
1. I already used successfuly Zettlr, the behaviour I describe is recent. I used to have the directory (and my working mdon the left pane, now it's empty.
2. If I try to open a directory, seems to work but left pane stays empty
3. if I try to open a file within a directory it's grayed.

Additional info if it may help : 

`~]$ zettlr
[16616:1108/162520.966178:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[16616:1108/162536.792571:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[16616:1108/162538.095521:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[16616:1108/162540.481540:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

`

**Comment by nathanlesage** [comment]
Sorry for the late answer. Re-reading your issue it seems as if there's the too-many-directories-issue happening. Does https://github.com/Zettlr/Zettlr/issues/343 address your issue?

**Comment by nam1962** [comment]
Hi, sorry to be late myself ! ;)

**Comment by nathanlesage** [comment]
Alright; would you mind testing out the 1.5 beta? I've switched to Electron 7 with this one, so maybe by updating the underlying framework it now works...?

**Comment by nam1962** [comment]
Hi, sorry for the delay.
1.5.0.1 on AUR has the same problem.

**Comment by nathanlesage** [comment]
1.5.0.1 …? I did not release such a version. Is it due to the AUR-Archives build process?

**Comment by nam1962** [comment]
Ooops : 1.5.0-1
https://aur.archlinux.org/packages/zettlr
https://aur.archlinux.org/packages/zettlr-bin

**Comment by nathanlesage** [comment]
Flatpak? Mhmh … what do the AppImages say? Aren't these supposed to run on all platforms as well?

**Comment by nam1962** [comment]
Well : 
* got the same issue with the AppImage of Zettlr
* FlatPak, when on Flathub has two advantages : visibility and community feedback
Generally speaking Appimages don't bring much confidence

**Comment by nathanlesage** [comment]
Hmhm, yes, it's surely worth considering, but I'm unsure whether or not this brings the changes wanted

**Comment by Sisi-Wiciel** [comment]
I got a similar problem on manjaro.
I can't open the app from the desktop or GUI. I have to open the app in the terminal by typing:
`sudo /opt/Zettlr/zettlr --no-sandbox`
But I can't change the input method on Zettlr.
The warnning or error massage form the terminal was like following:
![image](https://user-images.githubusercontent.com/21168981/74901281-58263c00-53dd-11ea-9414-f7c1c26067c7.png)
And I have tried the v1.6.0-4beta, I got the same problem.

**Comment by nathanlesage** [comment]
Have you tried opening an issue on the Electron tracker? Because I strongly assume that this has to do with the framework, not with Zettlr …

**Comment by Sisi-Wiciel** [comment]
> Have you tried opening an issue on the Electron tracker? Because I strongly assume that this has to do with the framework, not with Zettlr …
Well, I'll try it, thanks~

**Comment by nathanlesage** [comment]
Perfect, if there's a fix, just give me a quick shot, and I'll upgrade to the respective Electron version, so that the next release will then work on Manjaro!

**Comment by Sisi-Wiciel** [comment]
I edited the file in /usr/share/applications/Zettlr.desktop, it worked
I changed the "Exec=/opt/Zettlr/zettlr %U" to "Exec=/opt/Zettlr/zettlr %U --no-sandbox"
Then alll problems solved. But I don't know the reason.
And maybe it is the problem of electron 8.
The following warnings suggested something.
"The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397"

**Comment by nathanlesage** [comment]
Ah, so the sandboxing is the problem; in this case I'd recommend you open up an issue over at the electron-repository, because this has to do with the framework, not Zettlr!

And concerning the warning: I'm aware of that, but it's nothing important for Zettlr!

**Comment by nam1962** [comment]
@Sisi-Wiciel : what packaging do you use ? AUR (if yes, which one) ? AppImage ?

**Comment by Sisi-Wiciel** [comment]
> @Sisi-Wiciel : what packaging do you use ? AUR (if yes, which one) ? AppImage ?

I use the zettlr from AUR , named Zettlr rather than Zettlr-bin

**Comment by Sisi-Wiciel** [comment]
> Ah, so the sandboxing is the problem; in this case I'd recommend you open up an issue over at the electron-repository, because this has to do with the framework, not Zettlr!
> 
> And concerning the warning: I'm aware of that, but it's nothing important for Zettlr!

OK. I'll try it.

**Comment by Sisi-Wiciel** [comment]
@nathanlesage [similar issue has been opened up] https://github.com/electron/electron/issues/20856

**Comment by nathanlesage** [comment]
@Sisi-Wiciel Thanks for the info!

I think

```
"Exec=/opt/Zettlr/zettlr %U" to "Exec=/opt/Zettlr/zettlr %U --no-sandbox"
```

We need that desktop entry for the AUR builds (other linux distributions seem to be unaffected), but the AUR builds are not mandated by me, so one would have to contact the developer (and, in case I can do something to the build scripts, get back in touch with me, obviously!)

**Comment by nam1962** [comment]
No luck by me : even with `--no-sandbox` I'm still stuck and unable to open .md (they are grayed)

If I go to preferences and try to change tab (I.e another tab than "general") Zettlr freezes, my fans start to scream and I see an Electron process requiring 2.3 Go.

This is the terminal feedback. 
- launching zettlr
- opening preferences and trying to change tab
- closing Electron

```
~]$ zettlr
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

<--- Last few GCs --->

[5346:0x25bf59db6000]    87866 ms: Mark-sweep 2040.8 (2055.5) -> 2040.1 (2056.8) MB, 3181.5 / 0.7 ms  (average mu = 0.066, current mu = 0.006) allocation failure scavenge might not succeed
[5346:0x25bf59db6000]    90815 ms: Mark-sweep 2042.1 (2056.8) -> 2041.3 (2057.5) MB, 2920.9 / 0.1 ms  (average mu = 0.038, current mu = 0.010) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x5593b7161719]
Security context: 0x1ef7a01bf051 <String[#39]: file://E80BA6E92488F15CD4EB9A5DF2DB7B89>
    1: /* anonymous */ [0x1e032212ca51] [/usr/lib/zettlr/renderer/assets/vue/vue-sidebar.js:~6] [pc=0x2228f67078d0](this=0x299b924ac8c1 <De map = 0x35d9f222b2b9>,0x1e6a08dd7831 <Object map = 0x35858aafeb31>)
    2: new De [0x2fe7cc1745b9] [/usr/lib/zettlr/renderer/assets/vue/vue-sidebar.js:6] [bytecode=0x2db0eb63ac...
```

**Comment by nathanlesage** [comment]
>  I'm still stuck and unable to open .md (they are grayed)

Wait a moment, did you try opening them using the "Open ..."-dialog of the app? If so, it's meant for directories, not standalone files (which can nonetheless be opened with Zettlr, but you have to right-click them and say "Open with ...") -- have a look at the Quick Start Guide for that.

> If I go to preferences and try to change tab (I.e another tab than "general") Zettlr freezes

That is not good, but also seems to be an issue with Electron itself, not the Zettlr codebase

**Comment by nam1962** [comment]
I tired 3 ways :
- clicking on the folder icon, it opens the desktop folder, and I see all .md grayed
- clicking on the hamburger, then open - file and I see all .md grayed
- right clicking on a .md then "open with" it opens Zettlr... that stays empty...
In all instances the call for resources is gigantic.

**Comment by nathanlesage** [comment]
> clicking on the folder icon, it opens the desktop folder, and I see all .md grayed

This opens the "Open …" command, which is meant for opening directories

> clicking on the hamburger, then open - file and I see all .md grayed

This is the same as the toolbar option — meant for opening directories!

> right clicking on a .md then "open with" it opens Zettlr... that stays empty...
In all instances the call for resources is gigantic.

This is definitely not how it's supposed to be, but I currently assume it has to do with problems on Manjaro XFCE. I only write Zettlr's codebase, not the underlying binary :/

**Comment by nam1962** [comment]
Well, as I also have the issue with AppImage, I'm not sure Manjaro Xfce is the culprit.
(By the way, that's also why I continue to hint a Flatpak, that would eliminate the distro/version/flavor questions)

You puzzle me with this opening directory functionality.
What is the use of opening directories and... just looking at them.

More precisely, how can "file" - "open" (or [Ctrl + O] **not** open a file.
I've **never** seen such a feature !!!

**Comment by nathanlesage** [comment]
> I'm not sure Manjaro Xfce is the culprit

Didn't wanna imply that, I mistakenly forgot to add that *electron on Manjaro* seems to be the problem. Something with the framework is causing the problem, but I'm oblivious as to what …

> (By the way, that's also why I continue to hint a Flatpak, that would eliminate the distro/version/flavor questions)

Isn't that what AppImage is supposed to do?!

> You puzzle me with this opening directory functionality.

:D Long story short: Zettlr is meant as an "open once, forget the explorer"-solution. Not edit stand-alone files, but create full directories of Markdown notes which are managed within Zettlr. For instance, I have all these directories open all the time:


Whenever I need something, I just go into the respective directory and open the file from within Zettlr. I hate switching between explorer and app, I want to have this as immersive as it gets, and this is how I did it for Zettlr. Simply open one directory and store all your MD-files there. The root file-section is only for rare occasions when you have to edit MD-files not within any of your opened directories.

It should be clear [in the docs](https://docs.zettlr.com/en/5-minutes/), but if it isn't, please feel free to suggest changes to make it more verbose!

**Comment by nam1962** [comment]
Hello !
One good news : I've been able to open a .md with the new 1.6.0-2
One problem : I can't use Zettlr because it freezes with a gigantic (Electron ?) RAM toll

For your question concerning the doc, nope its not cristal clear to me, I suggest you use the term "project" instead of "directory" as it's your specific logic.

Alternative to Flatpak because not only cross platform but also cross device & cross OS : use PWA like [Marp web](https://github.com/marp-team/marp-web#desktop-pwa)
