### ISSUE TITLE
Nigtly: Text in new files don't get wrapped properly

### ISSUE THREAD

**Issue by Duckbilled** [Zettlr/Zettlr#3854]
### Description

In the new nightly, the text of new files don't get wrapped properly when resizing the window. Existing files still work, though. It actually also requires me to open a new window to get a new file. So maybe I am not even writing in a new file?

I can't remember how to create a log file, but this is what I found in the log viewer:
> Could not create new file 20221102_183910.md: The selected directory is not loaded in Zettlr!
> [FSAL Watchdog] The chokidar process falls back to polling. This may lead to a high CPU usage.
> [Assets Provider] Found outdated filter tags.lua; copying ...

Please let me know if something needs clearifying.

### Reproducing

opening a new file

### Zettlr Version

Nightly

### Specify version

2.3.0+nightly-20221102

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS Ventura

**Comment by Duckbilled** [comment]
Maybe this has to do with choosing another folder than the ones loaded in Zettlr, I am able to create a new file in a folder which is opened in the workspace

**Comment by nathanlesage** [comment]
> Maybe this has to do with choosing another folder than the ones loaded in Zettlr, I am able to create a new file in a folder which is opened in the workspace

That's an interesting observation. Please try to reproduce this and also feel free to make a screenshot so that I can see how it looks!

**Comment by Duckbilled** [comment]
I managed to upload the video after all (needed some compressing). Sorry for being to lazy to make screenshots :)

https://user-images.githubusercontent.com/52334713/199695724-f1bbcbbd-477f-491a-aeb6-1457a82beec9.mp4

**Comment by nathanlesage** [comment]
Aaaaaaaaaaahhhhh now I see. There's no file loaded! I have to fix that, thanks for the video!

**Comment by Duckbilled** [comment]
Well, it is the least I could do :)
