### ISSUE TITLE
:q or Ctrl-W not working in Vim editor mode

### ISSUE THREAD

**Issue by samjohn24** [Zettlr/Zettlr#3863]
### Description

:q or Ctrl-W not working in Vim editor mode

### Reproducing

Select Vim editor mode and try Ctrl-W or :q. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0 

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
The old vim plugin will be retired b/c we're now on CM6, so I'll mark this as outdated. Someone mentioned they wanted to reinstate the vim plugin in CM6 (which is a different plugin, so has different workings and different bugs´)
