### ISSUE TITLE
Reinstate the right click menu spelling corrections.

### ISSUE THREAD

**Issue by Duckbilled** [Zettlr/Zettlr#3866]
### Description

In the new nigtly it is unclear and inefficient to adjust the spelling. Before, the spelling correction was in the left click menu:
<img width="255" alt="right click menu" src="https://user-images.githubusercontent.com/52334713/200122983-59f216ae-404e-4883-8bc4-44f6ddd777ee.png">

Now, there is this pop-up which is not really clear to me how it works (I thought I might had to use the option key, but that doesn't do anything). I found out you can click 'option', but this still is less efficient, or at least a less common solution, than right clicking. 
<img width="285" alt="new option pop up" src="https://user-images.githubusercontent.com/52334713/200123060-91c21c9f-07d4-40b1-a661-164334e5691b.png">
<img width="232" alt="option pop up with correction" src="https://user-images.githubusercontent.com/52334713/200123095-756eb92d-2136-44b3-b3b0-3332e63f0ca9.png">

### Proposed Changes

Revert back to the previous version (e.g. 2.3.0)

### Caveats

.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

MacOS Ventura

**Comment by nathanlesage** [comment]
You are absolutely right. With the new CodeMirror version, we have a `linter` interface which is much more efficient for spell checking. However, it was a little bit difficult to use the interface to directly retrieve the suggestions, so I had to utilize the context menu to make that asynchronously.

I am aware of this and will see if I can find a better way to do so.
