### ISSUE TITLE
Graph Map: Markdown internal links are not display

### ISSUE THREAD

**Issue by samjohn24** [Zettlr/Zettlr#3867]
### Description

Markdown internal links are not display in Graph Map, just wikilinks `[[ ]]`

### Reproducing

Link two files using Markdown syntax `[]()` and open the Graph Map.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This is intended behavior and not a bug.
