### ISSUE TITLE
Order of files in Projects

### ISSUE THREAD

**Issue by anthrolisp** [Zettlr/Zettlr#387]
Thanks for all of your work on this. It's a life saver.

I'm sure I'm just missing something obvious, but where, or how, to tell Zettlr the order of the files to export in projects?

Also, documentation mentions a "preview pane"? How to access this?

Many thanks again!

**Comment by nathanlesage** [comment]
"preview pane" is actually the file list — where did you spot it? This way we can change this and correct the wrong name!

And the order can be determined using the sorting indicators (when you hover over a directory, to the top right) — you can sort by date (either creation or last modification, can be set in the preferences) or by filename, ascending or descending. Additionally, you can determine the sort order using certain filenames (such as using `001 ... 002 ... 003 ... 231 ... 999` as affixes)
