### ISSUE TITLE
[Bug] Zettlr blank screen when installed to directory with special character in name

### ISSUE THREAD

**Issue by pinuke** [Zettlr/Zettlr#3870]
### Description

To separate programs that require admin access to install vs ones that don't, I have created a directory environment under "C:\#". Applications in this directory do not require admin access (admin access to Program Files or access to the Registry) to run or install.

When trying to install Zettlr in this directory, Zettlr runs with a blank screen identical to #3140.

When trying to install Zettlr in a directory with no special characters, it runs fine.

**UPDATE:** This issue also exists on Linux. Instead of "C:\\#", on my linux box I used "\#"

#### _on Windows:_

Install zettlr to C:\\#\bin\zettlr to produce bug.

Install zettlr in C:\\test and it will run fine

#### _on Linux:_

`dpkg-deb -x /path/to/downloaded/package.deb /#` to produce bug

`dpkg-deb -x /path/to/downloaded/package.deb /test` and it will run fine

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10, Linux (Ubuntu)

**Comment by smartguy1196** [comment]
Note that this is NTFS Windows and not FAT which does not support these kind of characters in directory names

**Comment by smartguy1196** [comment]
Actually, since this is the FOSS community, I'll go ahead and try to reproduce it my Linux box. For funsies

**Comment by smartguy1196** [comment]
Couldn't get the app to install with dpkg-deb -x packagename /#

Got the App_Image to run from it though.

Gonna continue trying to get the normal dpkg install to work

**Comment by smartguy1196** [comment]
dpkg-deb install reproduces the same problem. Updating original issue

**Comment by smartguy1196** [comment]
And for funsies, I'll go ahead and attempt to install this on android to reproduce the problem on ARM64

**Comment by smartguy1196** [comment]
Can't get it to work on android. Will need someone else to check ARM64

**Comment by nathanlesage** [comment]
If it runs into a blank screen, can you try opening the dev tools and see if an error is logged? If the window opens but doesn't show content this means that Electron runs but my code throws an error. I don't have the resources to double-check it on my end unfortunately.

**Comment by smartguy1196** [comment]
@nathanlesage not sure that I can in release. F12 does nothing for me in the working or broken versions of the app. How do I pull devtools in the released version? Is there a command line flag for it?

**Comment by nathanlesage** [comment]
> How do I pull devtools in the released version?

Ctrl+Alt+I or Ctrl+Shift+I should do the trick.

**Comment by nathanlesage** [comment]
Closing due to lack of inactivity
