### ISSUE TITLE
[bug]: the arrows on each side of the editor window do nothing on left mouse click

### ISSUE THREAD

**Issue by marek-lach** [Zettlr/Zettlr#3878]
### Description

When you have a folder with documents open, I assume the left/right arrows near the top of the document window should navigate through previous/next document in that folder.

![the_collapse_arrows_not_working_on_Windows](https://user-images.githubusercontent.com/45913977/200589877-2c8c50be-2c19-4c62-9bb5-77a6f2aa4fb7.PNG)

But upon a left mouse click on either of these arrows, they don't do anything at all, they do not function in any way whatsoever that I can observe.

### Reproducing

1. Install Zettlr (I have a Windows version, maybe that's relevant)

2. Browse for example through the default tutorial folder, by left-mouse clicking on the navigation arrows that are at the edge of the editor window, on each side.

3. These arrows should most probably navigate you through the folder's documents, up and down, but they don't actually work at all for any purpose it seems?

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
These arrows can be used to navigate through the open documents if they don't fit on the screen. The problem I had in 2.3 is that I couldn't reliably show/hide them depending on how much content there was in the tab bar. But in the current branch, they will only show when there are too many tabs, making it clearer what they are meant for. There are arrow buttons that you can show in the toolbar, however, that let you navigate through the most recent files. See Preferences --> Toolbar for that.
