### ISSUE TITLE
Show title in Zettelkasten sidebar?

### ISSUE THREAD

**Issue by anthrolisp** [Zettlr/Zettlr#388]
Is it possible to show the title of the file in the zettelkasten view instead of the (id) file name? Thanks in advance!

**Comment by nathanlesage** [comment]
Should be possible once we parse YAML Frontmatter (but I'm not sure as to when this will happen …)

**Comment by nathanlesage** [comment]
Just saw that this issue is already mitigated — comes with the 1.5 release on Christmas!

**Comment by lucmos** [comment]
Would it be possible to show the title defined in the first header, if there isn't a title in the yaml frontmatter?

**Comment by nathanlesage** [comment]
@lucmos There is already an issue open demanding that somewhere

**Comment by teopost** [comment]
I can't find any other issues on this topic.
