### ISSUE TITLE
Zettlr fails to update user dictionary

### ISSUE THREAD

**Issue by diocrates** [Zettlr/Zettlr#3886]
### Description

Zettlr allows to add new words to the user dictionary, and lists them in the preferences (spellchecking tab), but it does not save these entries in the 'user.dic' file in C:\Users\<your username>\AppData\Roaming\Zettlr, i.e., it does not update the 'user.dic' file. Closing and restarting Zettlr does not remove the words from the preferences, i.e., the added words are still available. **Upon rebooting the PC the entries disappear**. On my computer, the 'user.dic' file was last updated on July 24, 2022, the day I updated to version 2.3.0. I tried the suggested troubleshooting reset and reinstalled the application, but the issue still exists. Today, I resorted to update 'user.dic' manually.

### Reproducing

Add words to the user dictionary. Check spellchecking in preferences to verify the addition of the words. Reboot the computer. Use the words in a document. Check for the words in the spellchecking tab of preferences. Check for the words in C:\Users\<your username>\AppData\Roaming\Zettlr\user.dic. The words are missing.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
I cannot reproduce this anymore in the current develop branch, and given that we're about to start the public beta, I can recommend you switching to the [nightly](https://nightly.zettlr.com/) releases already at this point. Should the bug reoccur please ping me again.
