### ISSUE TITLE
YAML frontmatter folding

### ISSUE THREAD

**Issue by lcsolano** [Zettlr/Zettlr#3889]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

I'd like to propose that the YAML front matter can be foldable, as is the case in other parts of Zettlr (keywords inside the YAML font matter itself, headings, etc.).

I did a mockup (small triangle un red).

![ZettlerYAMLfolding](https://user-images.githubusercontent.com/19916268/201482923-0f4d8494-453f-4624-8165-9ebaa8494eb8.png)

### Example Workflow

YAML Front Matter can be quite big according to user needs, so, folding it will avoid distraction while editing a file.

### Caveats

No caveats.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
This works in the current nightly! Coming officially in the betas/Zettlr 3.0!
