### ISSUE TITLE
improve section changes in the preferences window, 

### ISSUE THREAD

**Issue by almet** [Zettlr/Zettlr#389]
When I'm using the french language, when I click on the parameters gear and I want to go to a specific category, I move my mouse pointer on the category, and click on the grey area, nothing happens.

In the english version, as the category names are shorter, it doesn't seem to be a problem.
See https://framadrop.org/r/uzWnrisVo2#DPqS5k8Bw55TfkHFXFc/Rhfj9KibgrN0P9/pXle0olw= for a video capture.

**Comment by nathanlesage** [comment]
Thanks for the notice; I didn't know the preferences titles are growing so big for French! Reminds me to think about icons for the tabs …

**Comment by almet** [comment]
That's a good idea, or maybe have a rule to stick with short titles instead of large ones :-)

**Comment by nathanlesage** [comment]
Yes, this would be preferable, but after all it's in the realm of translators to check their translations and make sure they look somewhat acceptable 🙈

**Comment by nathanlesage** [comment]
This was *extraordinarily* easy to fix, I'm surprised!

**Comment by almet** [comment]
Thanks!
