### ISSUE TITLE
Drag and drop from file explorer do nothing (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3891]
### Description

Drag and drop from Zettlr files explorer do nothing (instead of creating a link according to Zettlekasten option `always filname` or `ID if exist`)

### Reproducing

If I drag and drop a note from Zettlr file explorer, it shows a `+` sign on dragging and do nothing when I do the drop (mouse click release)

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
I implemented that sometime during the week, so it should be available with the next nightly :)
