### ISSUE TITLE
Drag and drop from OS files explorer works sometimes (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3892]
### Description

Drag and drop from OS file explorer does sometime link with absolute path, sometime not.

By the way, would that not rather be make a link with the relative path like `[filename](./relative-path/filename)` ?

### Reproducing

If I drag a file from OS file explorer, `Nautilus` by my case, it does sometimes nothing, and some other times that print `[filename](/full-path/filename)`. Some other times it also adds string like `0:-10:248:22` just after the filename. I don't find any regularity.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
It is not unexpected that there are still bugs to this. Please try to find any regularities so that we can hunt this bug down!

**Comment by Etienne-TR** [comment]
I found that it is related to Nautilus (Gnome) file explorer. With Dolphin (KDE) that works well.

Also, in Nautilus, it seems to me always random between : 
1. no link
2. normal link
3. weird link that way : `[test.txt0:-10:248:22](/home/etienne/test.txt0:-10:248:22)`

In the third case, `0:-10:248:22` is automatically added at the end of the file name.

Below the test where I tried to find regularities.
```
Test start : 2022-11-19 09:36

1. -
2. -[test.txt](/home/etienne/test.txt)
3. -[test.txt0:-3:248:22](/home/etienne/test.txt0:-3:248:22)
4. -[test.txt](/home/etienne/test.txt)
5. -[test.txt](/home/etienne/test.txt)
6. -[test.txt](/home/etienne/test.txt)
7. -
8. -
9. -[test.txt](/home/etienne/test.txt)
10. -
11. -[test.txt](/home/etienne/test.txt)
12. -
13. -[test.txt](/home/etienne/test.txt)
14. -[test.txt](/home/etienne/test.txt)
15. -[test.txt](/home/etienne/test.txt)
16. -
17. -[test.txt](/home/etienne/test.txt)
18. -[test.txt](/home/etienne/test.txt)
19. -
20. -
21. -[test.txt](/home/etienne/test.txt)
22. -
23. -[test.txt](/home/etienne/test.txt)
24. -
25. -[test.txt](/home/etienne/test.txt)
26. -
27. -[test.txt](/home/etienne/test.txt)
28. -
29. -[test.txt](/home/etienne/test.txt)
30. -[test.txt0:-6:248:22](/home/etienne/test.txt0:-6:248:22)
31. -[test.txt](/home/etienne/test.txt)
32. -
33. -[test.txt](/home/etienne/test.txt)
34. -
35. -[test.txt](/home/etienne/test.txt)
36. -
37. -
38. -
39. -[test.txt](/home/etienne/test.txt)
40. -
41. -
42. -[test.txt0:-5:248:22](/home/etienne/test.txt0:-5:248:22)
43. -[test.txt0:-8:248:22](/home/etienne/test.txt0:-8:248:22)
44. -
45. -[test.txt](/home/etienne/test.txt)
46. -[test.txt0:-10:248:22](/home/etienne/test.txt0:-10:248:22)
47. -
48. -[test.txt](/home/etienne/test.txt)
49. -[test.txt](/home/etienne/test.txt)
50. -
51. -[test.txt](/home/etienne/test.txt)

Test end : 2022-11-19 09:38
``

**Comment by Etienne-TR** [comment]
It works well also with Thunar that I will adopt meanwhile.

**Comment by Etienne-TR** [comment]
I change the initial bug report because behavior has changed with last nightly. Zettlr does link with absolute path (and not only paste the absolute path).

**Comment by nathanlesage** [comment]
So … is it fixed…?

**Comment by Etienne-TR** [comment]
The bug is still here in yesterday nightly as in description. Sometimes no link, sometimes markdown link with full path, some other times with additional string like this : 

`[20220831140503.md](/full-path/20220831140503.md0:-4:301:22)`
or
`[20220831140503.md0:-2:301:22](/full-path/20220831140503.md0:-2:301:22)`

**Comment by nathanlesage** [comment]
That looks super weird, but I can guarantee that Zettlr itself does not generate these additional strings, so it seems definitely to be related to something external.

**Comment by nathanlesage** [comment]
I just had a look, and it definitely seems to be external. The drop handlers had another issue (especially with colons in them, but I'm going to close issue #4822 with that). Other than that, it really might be the file browser. Looking at the numbers again, especially the negative numbers remind me of file access flags, but I may be wrong …
