### ISSUE TITLE
Title sections can not be toggled (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3893]
### Description

The toggle arrow is not displayed.

### Reproducing

If I write a title line like `## My title note`
And then some content until another level 2 title.

I can't see any arrow left to the title line to toggle the title section.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
… additionally, somehow paragraphs with single line breaks can be toggled. I haven't yet understood the logic behind that, but I have that on my mind as well.

**Comment by Etienne-TR** [comment]
I find it is practical that paragraphs (defined as bundle of lines with only single line breaks) can be toggled.

Maybe it can't have a toogle (paragraph in a title section) inside another toggle at the same level (the title section that contain the paragraph) ?

**Comment by nathanlesage** [comment]
Yeah, let's keep it at that. I just reimplemented the toggling of headings, we can still adjust this during the betas!

**Comment by Etienne-TR** [comment]
That works well on today nightly ! I like the way toggles are displayed only on mouse over in the left margin :-)
