### ISSUE TITLE
Delete file action in File menu do nothing (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3894]
### Description

`File Menu > Delete file` do nothing

`Delete file` works well in the context menu when right click on the file in file explorer.

### Reproducing

Open a note, click `File Menu > Delete file`.
Nothing happens.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by Etienne-TR** [comment]
Could that be the occasion to homogenize menus (right-click on tab, right-click in file explorer, main window file menu) ? It is sometimes confusing to find wished action.

**Actually, we get that :** 

Close tab : only in tab menu
Close others : idem
Close all : idem

Save : file menu only

Properties : file explorer only
Rename : not in tab menu
Delete : not in tab menu
Duplicate : file explorer only

Copy name : not in File menu
Copy full path : tab only
Copy ID : not in file menu

Overview : file explorer only
Mount file : idem

Delete folder : file menu only

Inspect Element : all menus

**I purpose these changes :** 

Save : file menu only

Properties : in both tab and file explorer menus
Rename : idem
Delete : idem
Duplicate : idem

Copy name : in both tab and file explorer menus
Copy full path : idem
Could be added here a Copy relative full path ?
Copy ID : idem

Overview : all 3 tab, file explorer and main window file menus
Mount file : idem

Delete folder : file explorer only

Inspect Element : main window menus only

**Comment by nathanlesage** [comment]
> Could that be the occasion to homogenize menus

Uff. That's quite some work. I mean, some menu items cannot really be toggled in the main menu (as this is not aware of context), some only there (because they need direct access to the main process), so I would rather keep that.

But: Feel free to go through all the menus and reorder them as you see fit. Right now I don't have the mental capacities to do so myself, but I'm happy for any conceptual help I can get.

**Comment by Etienne-TR** [comment]
Yeah I understand. I will begin making an enhancement request limited to the actions that are actually most missing me (and make sometimes workflow does a bit resistance). A more global approach will come later, so a lot of work already in progress !

**Comment by nathanlesage** [comment]
I am a bit embarrassed looking at how long this issue has been open … but … it has been fixed, after all.
