### ISSUE TITLE
Troubles in tabs (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3895]
### Description

- Click on the right arrow stop moving tabs when the first tab on the right is shown even if there are more tabs left on the right.
- The right arrow is masked by the right panel buttons if the main windows is too much reduced.
- Context menu when click on a tab is incomplete and not traduced. It shows `Close leaf` and `Inspect element`.

### Reproducing

Open few notes.
Reduce main windows.
Use arrows to horizontal scroll tabs.
Right-click on tabs to show context menu.

By the way, it could be practical that horizontal scrolling action on tabs could be done by simple mouse wheel without `CRTL` as it is in Firefox for instance (and keep it working with `CTRL`).

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
Thanks for reporting, will keep that on my mind!

**Comment by Etienne-TR** [comment]
It's a pleasure :-)
Thanks to you and your work !
