### ISSUE TITLE
Feature: disable automatic entry of "matching characters"

### ISSUE THREAD

**Issue by akavel** [Zettlr/Zettlr#39]
I find that some characters which get automatically entered (for example, when I type <kbd>\`</kbd>, a matching `` ` `` gets inserted automatically after cursor position) give me more trouble than benefit: I often have to edit them afterwards, which can get twiddly, and kinda interferes with my "flow" of writing. Personally, I'd prefer to disable this feature; I'm a fast typer, so it's not a trouble for me to enter the matching characters by hand.

**Comment by nathanlesage** [comment]
Good thing I just refactored the config to easily add new options! I'll add this option in the release 0.21 (I'm not adding new things to the 0.20, because it's already packed with enormous amounts of fixes and new things).
