### ISSUE TITLE
Display of text and arrows in the gutter (nightly)

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#3905]
### Description

Thank you so much for all your efforts, I love the new possibilities opening up with the multi-pane editor!

While testing the new nightly, I came across a few bugs or inconsistencies how text and the new arrows in the gutter are displayed:

A: <img width="123" alt="Bildschirm­foto 2022-11-16 um 11 04 08" src="https://user-images.githubusercontent.com/64837252/202151672-d51ff264-88e1-4b84-87d2-ffce6f5aff95.png">
In this case, text is offsetted to the left into the gutter. Sometimes it looks like this, I haven't figured out how to reproduce… 

B: <img width="409" alt="Bildschirm­foto 2022-11-15 um 16 51 54" src="https://user-images.githubusercontent.com/64837252/202152073-fb9fd653-c505-4784-bc1d-17df381bf82a.png">

I often structure documents like this – I have a title or description and then a list of bullet points. It would seem to me more consistent, if the drowdown-arrow would be placed in the line above the list. Also, bullet points appear slightly tilted outwards as well. 

This might be more of an enhancement, I guess, as it connects to the export from Zettlr: Here, it is necessary to have a newline between "title" and bullet points to export an actual list – as opposed to github and gitlab (no newline necessary). 

Thanks for considering! 

### Reproducing

-

### Zettlr Version

Nightly

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ventura 13.0

**Comment by nathanlesage** [comment]
> This might be more of an enhancement, I guess, as it connects to the export from Zettlr: Here, it is necessary to have a newline between "title" and bullet points to export an actual list – as opposed to github and gitlab (no newline necessary).

The thing is, the CommonMark spec doesn't really require newlines between a ton of different elements, but both Pandoc and Zettlr try to also enforce kind of a better "code style" in this regard. I'll also be adding a linter that highlights stuff (i.e. a paragraph directly following a heading) in the next weeks to make it easier.

Other than that, I just pushed a commit that should reposition gutter elements to the center of the given line. Please have a look next Monday with the new nightly how it looks.

**Comment by halloichbingunnar** [comment]
Thank you so much for the quick reply, and great that so much is on the way at the moment!

However, I am not quite sure if a linter enforcing newlines is the best solution to the issue. Logically, for me, list and heading words/sentence/paragraph are one element. So when having arrows to fold/unfold parts of the text I'd think it would be much more helpful to have the heading sequence always displayed and the rest folded (without newline). Why enforce splitting them? 

Does this make sense for you or am I just doing it all wrong? 🙃

**Comment by Etienne-TR** [comment]
I remark that list indentation formatting is done as soon as there is a string like `[0-9]\.\s` in a list line (whatever it is at the beginning of the line or not).

**Comment by halloichbingunnar** [comment]
Sorry for over-attaching myself to this issue, I was writing a bit in Zettlr today, and with larger lists the arrows become quite present and produce visual clutter:
<img width="86" alt="Bildschirm­foto 2022-11-16 um 17 20 47" src="https://user-images.githubusercontent.com/64837252/202237095-c7f4953e-c921-46b4-8b2a-2c916e51e91b.png">

I had to think of Logseq: There, arrows are only displayed on hover. Also, the visual structure with lines for each level works reallly well – if the display of lists is still an open issue for 2.3.x, maybe this can offer inspiration?
<img width="302" alt="Bildschirm­foto 2022-11-16 um 17 22 20" src="https://user-images.githubusercontent.com/64837252/202237576-bd8a7f08-d776-421f-b7ff-14b5fb2baf7e.png">
<img width="270" alt="Bildschirm­foto 2022-11-16 um 17 22 40" src="https://user-images.githubusercontent.com/64837252/202237586-3c6c583e-3a2e-46f2-9589-06d2bf89f22d.png">

**Comment by nathanlesage** [comment]
> I remark that list indentation formatting is done as soon as there is a string like [0-9]\.\s in a list line (whatever it is at the beginning of the line or not).

That's definitely a potential bug in the indentation. [Oh yes, it actually is. Sometimes I'm an idiot …](https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/plugins/visual-indent.ts#L56) Give me a minute to fix that :D 


Regarding the many arrows to fold lists: Well, that's provided by the underlying Markdown mode. Three options in this regard:

1. I can definitely hide except on hover (similar to VSCode/logseq) but that would then also hide the linter warnings unless the user hovers. Possibly not the most elegant solution.
2. I can just throw out the lint folding (caveat: I don't know if that's even possible) and re-implement any foldable area that should be foldable. Possibly the most complicated but most clean solution.
3. Ask Marijn whether we could adapt the folding service. This might the most difficult solution to achieve, honestly.

**Comment by nathanlesage** [comment]
Okay, forget what I just said, I figured out a neat way to hide the fold gutter unless you're hovering over it without completely hiding the other gutters. It's coming with Monday's nightly!
