### ISSUE TITLE
CTRL+D do not work (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3908]
### Description

CTRL+D do not work

### Reproducing

Line is not deleted as expected.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
It seems the command you are looking for has a different keybinding now:

![image](https://user-images.githubusercontent.com/17251683/202502633-6ebc1028-eae0-4315-aba6-1e35aa2d899f.png)

Do I see this right?

**Comment by nathanlesage** [comment]
(Also, [here is the full list of all available commands in CodeMirror 6](https://codemirror.net/docs/ref/#commands))

**Comment by Etienne-TR** [comment]
All right, thank you ! So I can close issue, that was an easy one :-)
