### ISSUE TITLE
[ENHANCEMENT] More Settings for File Linking

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#391]
## Description

When linking files, the current behaviour of Zettlr is to put the ID in the brackets and add the file name (excluding the extension) afterwards in all cases, even if the file has no ID and will therefore be linked using only the filename. This is undesirable. Nevertheless, there may be certain preferences by different users regarding that policy, so we need to make it accessible using a settings option.

## Proposed Enhancements

1. If the link contents equal the filename, do not add the filename.
2. If desired, do not add the filename at all.

This can be achieved by adding a new radio option in the Zettelkasten-tab with three states:

- Never add the filename when choosing files to link to.
- Add the filename when choosing files to link to, if these files have an ID.
- Always add the filename when choosing files to link to, even if they do not have an ID.

## Wording

The proposed wording for the English translations is:

```
Add the filename after linking to a file:

( ) Always
( ) Only if linking with ID
( ) Never
```

**Comment by raoul-van-oosten** [comment]
Yes, I would love this! Currently, mine is linked as "[[ID]] ID <title>". Is that normal behavior?

**Comment by raoul-van-oosten** [comment]
Of course, that makes sense. Maybe I should discard ID from the title, then, because I always (have to) remove it manually now.

**Comment by nathanlesage** [comment]
Tadamm 🎶
