### ISSUE TITLE
Text overflows in overview (on mouse over internal link) (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3910]
### Description

Text overflows on the right of the overview popup that shows up on mouse over an internal link.

### Reproducing

For instance if the overviewed note contains an url like `https://github.com/Zettlr/Zettlr/issues/3905`

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
Do you have a screenshot for me?

**Comment by Etienne-TR** [comment]
Yes !

![Screenshot 2022-11-19 17-15-10](https://user-images.githubusercontent.com/107387699/202861086-8080d9e5-c845-4aef-a867-392d4078be4e.png)

**Comment by nathanlesage** [comment]
Wonderful! Should be easy to fix, I'll get to it possibly in a fortnite (next week is full!)
