### ISSUE TITLE
File has been changed remotely (again)

### ISSUE THREAD

**Issue by gour** [Zettlr/Zettlr#3911]
### Description

I've just installed Zettlr on my Fedora Linux machine and do experience the same problem as described in #2413 or #3773.

Using Zettlr-2.3.0 installed from RPM for Fedora.

Sincerely,
Gour

p.s. Tried Obsidian, Joplin, Logseq, org-roam and explored several other (neo-)-vim based utilities for note-taking/Zettelkasten, but Zettlr is the best by a large margin!

### Reproducing

Just going through the tutorial I experience the problem although not using any cloud/backup software on my machine.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 37

**Comment by nathanlesage** [comment]
Current betas should fix that problem; at least I tried out out this week a few times -- could you confirm if this issue is still relevant? Otherwise I'm going to close it.

**Comment by nathanlesage** [comment]
Closing – but if I was simply too fast for your, please comment.
