### ISSUE TITLE
List and quotation markers over interpreted (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3912]
### Description

If a line contains one of these `>+-*` characters or the `[0-9]\.\s` pattern, it is interpreted as a quotation or a list item even if the marker is not at the beginning of the line.

It is linked with issue #3905

### Reproducing

For instance
```
- item1
some text - some another
```
give two indented lines as if they were both list items.

It could have meaning for a line like `Item 01. Some text` to be interpreted as an item list but in that case `Item 01.` should be displayed as list number and not only `01.` text.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by Etienne-TR** [comment]
I remark that the over interpretation also happens inside a code section or piece of inline code.

**Comment by nathanlesage** [comment]
Ah, I closed that issue yesterday, should be good now!
