### ISSUE TITLE
External and local links troubles (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3913]
### Description

1. If there are two URL in two consecutive lines, they are read as if there was only one.
2. Popup on mouse over a markdown link or a URL is not clickable to follow the link.
3. Markdown link is broken if there is an empty space into the address.

### Reproducing

1. For instance
```
https://github.com/Zettlr/Zettlr/issues/2307
https://github.com/Zettlr/Zettlr/issues/857
```
open a popup on mouse over that contains the both links.

2. For instance
```
[text link](https://github.com/Zettlr/Zettlr/issues/2307)
https://github.com/Zettlr/Zettlr/issues/2307
```

3. For instance
```
[text link](./My local file.pdf)
```

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by Etienne-TR** [comment]
Well, whatever the content after a line that ends by an URL, all the following lines (without space or double breaklines) will be considered as the URL continuing.

**Comment by Etienne-TR** [comment]
Glad to see that work already in progress about local links :-)

I found another case that makes link broken. I don't know if it is also some sloppy syntax. This is in the text part this time, not in the link part : when there are 2 (or more) points and that the second (or more) one is followed by more than 2 alphabetic characters.

For instance : 

Broken : 
```
[my.link.zz](https://wikipedia.org)
[my.k.zz](https://wikipedia.org)
[my.k1.zz](https://wikipedia.org)
```
Not broken : 
```
[my.link.z](https://wikipedia.org)
[my.link.1z](https://wikipedia.org)
```

**Comment by nathanlesage** [comment]
@Etienne-TR This looks as if the Link regex is interfering here… oh wait. Yes, I think I fixed that two days or so ago? So it should come with tomorrows nightly, please feel free to check the next one and report back then! :)

**Comment by nathanlesage** [comment]
Closing this issue as the upcoming version gets rid of this sloppy link parser. I can no longer reproduce the issues you have, fortunately!
