### ISSUE TITLE
Clicking on related files in sidebar does not open the file (nightly)

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#3918]
### Description

Maybe this is already known – and the title is pretty much it: related files are displayed properly, but clicking on them in the sidebar does not open the files. 

### Reproducing

Zettlr nightly, Win10, in every note

### Zettlr Version

Nightly

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win10

**Comment by Etienne-TR** [comment]
Could that be the occasion to add a right-click (and/or mouse over) context menu with this actions (at least the second one) : 
- Open
- Open in a new tab
- Quicklook

Or even better (but probably more difficult to code) the same overview that is displayed on mouse over an internal link into the editor window (that already contains `Open` and `Open in a new tab` buttons).
