### ISSUE TITLE
Marking text in code block not visible (nightly)

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#3919]
### Description

When marking text in a code block, it seems like the background of the code block is in front of the marker, so it's not visible:
![Screenshot 2022-11-18 105914](https://user-images.githubusercontent.com/64837252/202675272-c1083be2-77d6-4a1e-a7ce-d851a2078cd9.jpg)

### Reproducing

Happns in any code block

### Zettlr Version

Nightly

### Specify version

2.3.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win10

**Comment by Etienne-TR** [comment]
So do I.

**Comment by nathanlesage** [comment]
The problem is that the order of line background and selection layer has changed. I have not found a good solution yet.

**Comment by bjonnh-work** [comment]
The way I fixed it temporarily is to have:
```
body .main-editor-wrapper .cm-editor .code-block-line {
    background-color: #dfdfdf48;
}
```
in my custom css
