### ISSUE TITLE
Zettlr does not recognize auto-completed links created via LSP-marksman and vice-versa

### ISSUE THREAD

**Issue by gour** [Zettlr/Zettlr#3920]
### Description

Hello,

when I create a link to the note using some LSP-capable editor using [Marksman](https://github.com/artempyanykh/marksman), Zettlr does not recognize them, reporting that such files does not exist.

Similarly, when I create a link to another note from within Zettlr, other external editors (e.g. Helix) do not recognize such links created in Zettlr by reporting: `Link to non-existing document with the title...`.

Ability of Zettlr to use markdown files created externally without any modification is one of it killer features which made me to abandon many other note-taking apps, so wonder what do I miss to get desired functionality?

### Reproducing

1. created two simple notes:

```
---
title: "First Note"
tags: ["test"]
---

# Heading of the First Note

This is a first note with a LSP link to the second:
```

```
$ cat second.md 
---
title: "Second Note"
tags: ["test"]
---

# Just a header

Just some text to test Marksman.
```

2. using Helix editor create a link to the second note in the first one using Marsksman-assisted auto completion:

```
cat first.md
---
title: "First Note"
tags: ["test"]
---

# Heading of the First Note

This is a first note with a LSP link to the second: [[just-a-header]]
```

Here is the shot showing auto-completion dialog in Helix:

![helix-auto-completion](https://user-images.githubusercontent.com/114592/202855514-f9a7da7f-186e-4321-8709-8c99b22c58f3.png)

3. Open Zettlr and creating now note by using its auto-completion yields the following content:
```
$  cat first.md 
---
title: "First Note"
tags: ["test"]
---

# Heading of the First Note

This is a first note with a LSP link to the second: [[just-a-header]]

Here is the link created from within Zettlr: [[second]]
```

Now, the Zettlr does complain about `[[just-a-header]]` with: "File just-a-header does not exist", while Helix does complain about `[[second]]` link with: `Link to non-existing document with the title 'second'`.
[first.md](https://github.com/Zettlr/Zettlr/files/10047193/first.md)
[second.md](https://github.com/Zettlr/Zettlr/files/10047194/second.md)

### Zettlr Version

Nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Linux (linux 6.0.8-300.fc37.x86_64 (architecture: x64)

**Comment by nathanlesage** [comment]
Well, as of now Zettlr only understands links with ID or filename. First h1 or yaml title are additional possibilities but we would need to think implications before touching that ...

**Comment by gour** [comment]
> Well, as of now Zettlr only understands links with ID or filename. 

OK, so I am interested if there is any way to make Zettlr work with external editors using LSP auto-completion?

Ability to Zettlr to allow me (occasionally) working with external editors, is a killer feature not forcing vendor-lock-in, sos I just wonder how?

> First h1 or yaml title are additional possibilities but we would need to think implications before touching that ...

I'm not attached to depend on YAML stuff...

**Comment by nathanlesage** [comment]
> OK, so I am interested if there is any way to make Zettlr work with external editors using LSP auto-completion?

Just to make sure we're on the same page here: LSP is simply a protocol that allows an editor to communicate with a server running somewhere on the computer. That protocol does not prescribe how functionality is to be implemented. In other words: The inability of some editors to follow links that point towards a filename (as opposed to some heading) is an implementation specific design choice that has nothing to do with the protocol.

To be honest, I can't quite understand the rationale of linking to *headings* by default, as opposed to a filename. I mean, sure, linking to files and THEN to headings (as in `[[some-file.md#heading]]`) makes sense and could be implemented on my side but if there's a plain link with nothing, why would any program assume it has to open every file and look for a heading that matches that text in the first place …? This seems counterintuitive to me.

Could it be that it is simply a configuration issue? As far as I understand the Marksman README, it seems that it attempts to match on filenames, not headings, doesn't it?

**Comment by gour** [comment]
> Just to make sure we're on the same page here: LSP is simply a protocol that allows an editor to communicate with a server running somewhere on the computer. That protocol does not prescribe how functionality is to be implemented. In other words: The inability of some editors to follow links that point towards a filename (as opposed to some heading) is an implementation specific design choice that has nothing to do with the protocol.

Right.

> To be honest, I can't quite understand the rationale of linking to _headings_ by default, as opposed to a filename. I mean, sure, linking to files and THEN to headings (as in `[[some-file.md#heading]]`) makes sense and could be implemented on my side but if there's a plain link with nothing, why would any program assume it has to open every file and look for a heading that matches that text in the first place …? This seems counterintuitive to me.

You're right. I also believe that linking to filename should be the default...

> Could it be that it is simply a configuration issue? As far as I understand the Marksman README, it seems that it attempts to match on filenames, not headings, doesn't it?

But I also wonder about the situation when Zettlr does use IDs since, I 'd prefer to use (unique) IDs to provide for possible/future note renaming sine there is no automatic update when one uses filenames...

**Comment by nathanlesage** [comment]
> But I also wonder about the situation when Zettlr does use IDs since

That's true, in this case, Zettlr is also inconsistent. (Most people use IDs as filenames, but when a file is loaded in Zettlr, Zettlr already knows the ID)

It's difficult to make an educated choice for what Zettlr should support and what not because there is no clear standard :/

**Comment by gour** [comment]
> It's difficult to make an educated choice for what Zettlr should support and what not because there is no clear standard :/

Well, the point is that, for me, Zettlr is a wonderful tool to do note-taking deploying Zettelkasten methodology and write Markdown, but isolated from other editors, iow. as a stand-alone tool.

However, deploying  it with other editors could be problematic...

In regard to the standard, maybe it is worth considering that John (aka `jgm`) - the author of Pandoc and active collaborator on Commonmark spec worked and, presumably, [added](https://codesti.com/issue/jgm/commonmark-hs/69) support for `[[Wikilinks]]` to his Haskell implementation of Commonmark parsing [library](https://codesti.com/repo/jgm/commonmark-hs) ? :thought_balloon:

**Comment by nathanlesage** [comment]
I'll close this issue now as not-planned. Zettlr has better and better support for wikilinks; but I have yet to see an app that links to headings by default. What I strive for is mainly intercompatibility with the main competitors, that is Obsidian and Logseq, and others as possible, but I do not see any viable way of implementing that from a cost-benefit perspective at this point.
