### ISSUE TITLE
Tab cannot be positioned within existing pane (nightly)

### ISSUE THREAD

**Issue by halloichbingunnar** [Zettlr/Zettlr#3922]
### Description

Maybe this is already obvious, known and in the pipeline – when dragging and dropping a tab to another pane, it is only possible to create a new pane, not add the tab to an existing one. 

### Reproducing

Happens both on Win10 and MacOS Ventura

### Zettlr Version

Nightly

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win10, Ventura 13

**Comment by nathanlesage** [comment]
Have you tried dropping it in the center of a pane? I.e. not on any of the four edges? This is how it's supposed to work (it doesn't work directly on the tabbar right now, but that is then a different issue)

**Comment by nathanlesage** [comment]
> Also, the "blue highlight" that indicates where a new pane opens is not displayed while dragging into center of a pane (if that is the expected behaviour)

That is expected. Basically, the idea is the following: If you want to split an editor pane, you can move a file to the border which will highlight blue if you can split it. If it doesn't highlight blue, that basically means that you'll add the file to the given editor pane (if it's not already part of it)
