### ISSUE TITLE
Quicklook action not available (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3927]
### Description

The quicklook action is not displayed into the context menu on right-click on note into file explorer.

### Reproducing

Well just right-click to have a look on the context menu.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
… what Overview action? Can this be an off-translation from French? A screenshot or a quick switch to English might help here!

**Comment by Etienne-TR** [comment]
Well in proper English it is `Quicklook` action (just behind `Copy filename` and `Copy id` in the context menu) !

**Comment by nathanlesage** [comment]
Ah, quicklooks have been nuked in this version; it's also in the Changelog:

> Quicklook windows are gone completely now, since they can be more than replaced by the new split views and multiple windows

That was the intention behind that :)
