### ISSUE TITLE
Distraction free mode gets traces on top of the window (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3928]
### Description

When I activate distraction free mode I get a screen where there are unexpected piece of thin and grey lines on the top of the window, like this: 
![Screenshot](https://user-images.githubusercontent.com/107387699/202922062-3c47484f-24ee-4d57-8be9-fb038ecf676f.png)

### Reproducing

Quickest way is `CTRL-j`

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
Yeah, this is definitely some artifact as the height of the toolbar has changed since 2.3. Someone with Linux can feel free to check which CSS style we need to adapt (it should be a `top:`-property on any of the wrappers) so that I can adapt it. Or open a PR!

**Comment by nathanlesage** [comment]
This is fixed by now!
