### ISSUE TITLE
Spell-checking: adding a new word to the user dictionary takes a restart to be effective

### ISSUE THREAD

**Issue by mgiugliano** [Zettlr/Zettlr#393]
## Description
While using the spell-checking options, an unrecognised word can be "added to the dictionary" by the right mouse button. This adds the word to the user-populated list, visibile from the settings but Zettlr still recognises such a word as "wrong/unknown".

## Reproducing
Type a new term in a text, such as "neocortical", while using the (British) English dictionary. The word should appear underlined by a red line, signifying that the word has not been recognised by the spell checker dictionary. Right mouse click on the word and add it to the "user dictionary".
The original word is still indicated in red, until Zettlr is not restarted.

## Expected behaviour
Like in Microsoft Word, once the word is added to the custom user dictionary it immediately becomes recognised by the spell checker.

**Screenshots**

## Platform
 - OS: macOs
 - OS Version: 10.15
 - Zettlr Version: 1.4.2
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Once you add a word to the user dictionary, this will trigger an "invalidation" in the process, which re-loads the whole user dictionary, including the newly added word. But the red line under the newly added word will only refresh if you type in that same line. Could you please verify that indeed typing anything in the line of said word makes the red line disappear?

**Comment by mgiugliano** [comment]
You are right: the red line under the (previously) unknown word disappears upon typing any letter in the same line.

**Comment by nathanlesage** [comment]
Perfect. Apparently there's no good way to force the re-render of a line, except re-setting the `mode` completely, according to this issue: https://github.com/codemirror/CodeMirror/issues/3318

So I think in most instances you'll be writing something on the line after adding some word to the dictionary, so I'll keep it that way until some better method comes around :)
