### ISSUE TITLE
zettlr.com is down

### ISSUE THREAD

**Issue by Mpic** [Zettlr/Zettlr#394]
Looks like the website is down... Cannot access the docs (docs.zettlr.com) either.

**Comment by nathanlesage** [comment]
It's working fine for me. Which exact address did you visit and what's the browser error message?

**Comment by nathanlesage** [comment]
Totally forgot to close this issue. **For the future: DO NOT open issues on this repository for notifying me when zettlr.com appears to be down. Please DM me on [Twitter](https://www.twitter.com/zettlr), [Reddit](https://www.reddit.com/r/Zettlr), or [Facebook](https://fb.me/zettlrapp). I'll get the notification and react accordingly.**

This issue tracker is for the Zettlr app only. Thank you!
