### ISSUE TITLE
Overview popup on internal link goes away too fast (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3940]
### Description

When poping up the overview of a note by mouse over an internal link, it is difficult to reach the popup and so the buttons `open` and `open in a new tab` with the mouse pointer.

Popup should stay displayed a little bit longer and/or the area to be on mouse over it should be extended a bit to the bottom.

When moving mouse pointer on the internal link, popup should not be hidden an displayed again just a little further but simply stayed visible where it is.

### Reproducing

![Screenshot overview popup](https://user-images.githubusercontent.com/107387699/203378400-8eccc8e2-65d1-431b-8cd3-1521e78ddbd1.png)

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
> When moving mouse pointer on the internal link,

That's a good indicator where I need to look, give me a few days to figure this out.
