### ISSUE TITLE
Filter field weird behavior with arrow keys (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3941]
### Description

In filter field in file explorer, left and right arrows don't work. It think it should move cursor into the text written in the field.

With up and down arrows, it navigates into the listed notes but press enter does not open the selected one (as it is in stable release).

### Reproducing

![Screenshot filter field](https://user-images.githubusercontent.com/107387699/203382285-e3c49e4a-bfe8-4b81-86c9-2b6cda81fcee.png)

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
That the arrow keys don't really work is intended, because otherwise you would have arrow-key navigation simultaneously in the file tree as well as in the filter field, which would lead to unwanted behavior. Regarding the opening: That's definitely an issue. Give me a second …

Here we go!
