### ISSUE TITLE
Create a new ID doesn't work (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3943]
### Description

ID aren't created by `CTRL-L` or `Menu > Edition > Create a new ID`

### Reproducing

Not much to add.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by Etienne-TR** [comment]
I see Copy ID with `SHIFT-CTRL-i` don't work either. It is probably not a bug but just not implemented yet. To devs, courage !

**Comment by nathanlesage** [comment]
I cannot reproduce this locally. For me, ID generation works fine.

**Comment by Etienne-TR** [comment]
Outch. I thought it might be an installation issue so I tried to install deb package instead of running AppImage. Installation seems to be ok but application doesn't show up into applications menu.
Well I get a second bug and no more information to help reproduce the first one.
Just, `CTRL-d` and `Menu/Copy ID` just do nothing here.
What can I do ?

**Comment by nathanlesage** [comment]
Well, for starters, the shortcut for the IDs is ctrl L not ctrl D. And then ... I don't know, try out various configurations to try to see where the error starts...?

**Comment by Etienne-TR** [comment]
I did fresh install and config but this is not better yet.
Maybe a track, two others actions don't work in the same window edit menu : `Paste` and `Paste without style`.
These two are reachable from shortcuts `CTRL-v` and `CTRL-SHIFT-v` (contrary to `Create new ID` and `Copy ID` actions that don't work from shortcuts neither for me).

`Paste` and `Paste without style` work for you from window edit menu ?

**Comment by Etienne-TR** [comment]
I succeed install nightly from `.deb` thanks to @gour in that post #3939 but the bug remains.

**Comment by nathanlesage** [comment]
Paste works without any troubles, but there's something off with paste without style, I have to get into that.

**Comment by Etienne-TR** [comment]
I made new tries on a liveusb ubuntu and a new user cession on my current ubuntu install. I get the same result on both :
- `CTRL+L` does work (so I still have to find out when it went wrong on my cession)
- `Copy ID` action still doesn't work

Do `Copy ID` work for you ?
I see  @gour you are on a Debian, does this action work on your cession ?
