### ISSUE TITLE
Insert image from clipboard window doesn't show up (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3945]
### Description

If there is an image in the clipboard, when `CTRL-v` into the editor, Insert image from clipboard window doesn't show up.

### Reproducing

In stable release, I get : 
![Screenshot Insert image from clipboard](https://user-images.githubusercontent.com/107387699/203601089-559c992e-8856-41ce-b4d3-a22556508087.png)

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
Very good catch, thank you!
