### ISSUE TITLE
After editing the text in the table, the edited content cannot be saved

### ISSUE THREAD

**Issue by xyk1027** [Zettlr/Zettlr#3947]
### Description

Enter some contents in the table, and then save the file. These contents will not be saved

### Reproducing

1. Create a new file
2. Insert a table
3. Enter something in the table
4. Press Ctrl+S or click File->Save
5. Close the file
6. Reopen the file
7. There's just an empty table

Screen recording:
https://user-images.githubusercontent.com/20372156/203704308-5db2eba2-725e-49ee-a63e-c8417d4c9ab3.mp4

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
The problem is that you have to click outside of the table, somewhere in the document in order for the table to actually copy over the changes you made. In the upcoming version this is made transparent with a save indicator that will tell you whether the table has been modified or not. I know that it's a difficult UX right now!

**Comment by xyk1027** [comment]
@nathanlesage I did, but the problem still exists. Here's the demonstration:

https://user-images.githubusercontent.com/20372156/203949403-9bbc2b15-4276-496c-95d9-dbfcb0330ef5.mp4

**Comment by nathanlesage** [comment]
Unfortunately I can't get the video to work (tried Chrome, Safari & Firefox), so I can't have a look at it.

**Comment by xyk1027** [comment]
@nathanlesage The file may be corrupt, so let me describe it with words and pictures. This video contains two parts:

Part I:
1. Create or open a new markdown file
![1](https://user-images.githubusercontent.com/20372156/204177132-6fff697d-0f54-48e5-a726-076e59ded258.jpg)
2. Click the "Insert Table" icon at the top of the interface to insert a table with two rows and two columns
![2](https://user-images.githubusercontent.com/20372156/204177564-77106db2-a81a-40f6-8805-dfa34d7eb619.jpg)
3. Enter some text in the newly inserted table
![3](https://user-images.githubusercontent.com/20372156/204177635-d0d18483-31b0-4681-ad65-4da53e5c4343.jpg)
4. Click the area outside the table
![4](https://user-images.githubusercontent.com/20372156/204177687-2f238c9d-4576-4dda-aed2-6ec37ad4827e.jpg)
5. Click the "File" - "Save" menu
![5](https://user-images.githubusercontent.com/20372156/204177719-f2e6007c-f016-48b2-bd82-781253952eac.jpg)
6. Click the "Close" icon on the tab
![6](https://user-images.githubusercontent.com/20372156/204177755-d4d042f9-68ae-4f13-9482-08215bd0614f.jpg)
7. Click the file on the left side of the interface to reopen it

Result:
The file contains an empty table with two rows and two columns
![7](https://user-images.githubusercontent.com/20372156/204177864-32f46f8a-4a34-4819-a4ea-f644d4a664a7.jpg)

Part II:
Change step 4 of Part I to "Click the area outside the table, and then enter some text below the table (such as 'aaa')". The other steps are the same as those in Part I
![8](https://user-images.githubusercontent.com/20372156/204180170-a5a50376-5663-46ea-af8b-dd97f81e26be.jpg)

Result:
The file contains an empty table with two rows and two columns, and there are some words "aaa" below the table
![9](https://user-images.githubusercontent.com/20372156/204180216-1ef6be88-5219-45d2-bc5f-3ade7222425a.jpg)

In addition, I found that the table generated by Zettlr is different from markdown syntax:
![10](https://user-images.githubusercontent.com/20372156/204190879-f83aab60-6131-4199-9911-a684a9ed385b.jpg)

**Comment by xyk1027** [comment]
@nathanlesage Oh, it doesn't matter. As long as the new version fixes this problem, I have nothing to worry about. I'm just worried that this problem has never been discovered and thus never been solved either. Finally, thank you for your reply. I'm already looking forward to the new version!
