### ISSUE TITLE
Rendereing of python comments in Readability mode as headings

### ISSUE THREAD

**Issue by srosenbu** [Zettlr/Zettlr#3951]
### Description

Some python comments in a code block are visualized like markdown headings when the document is viewed in readability mode. 
![bug](https://user-images.githubusercontent.com/69848361/203987806-574149d4-c80f-462c-843f-0b291ea19023.PNG)

Comments without a space after the `#` are visualized correctly.
This bug does not break anything, but I assume it is not supposed to look like it does.

### Reproducing

Insert the following code block into markdown
```python
#this comment is displayed correctly

# This comment looks like a heading
```

Then switch to readability mode and the 2nd comment should look like a heading.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I can confirm that this is no longer an issue in the upcoming 3.0 branch. You can try to switch to the [nightly branch](https://nightly.zettlr.com/). It is relatively stable (although I cannot give a guarantee for that yet, so the warnings apply).
