### ISSUE TITLE
generateAssets hook fails on Win10

### ISSUE THREAD

**Issue by learn-more** [Zettlr/Zettlr#3955]
### Description

When running `yarn start` on Windows 10, the `generateAssets hook` step fails.
Full output (Contents of the 'Terminal' window within VS Code):
```
PS E:\Projects\Zettlr> yarn start
yarn run v1.22.19
$ cross-env NODE_ENV=develop electron-forge start
✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies: 1 / 1 [15s]
❯ Running generateAssets hook
  ✖ Running generateAssets hook from forgeConfig
    › Failed to download Pandoc: Process quit with code 0. If the code is 0, then there was error output.

An unhandled rejection has occurred inside Forge:
Error: Failed to download Pandoc: Process quit with code 0. If the code is 0, then there was error output.

Electron Forge was terminated. Location:
at ChildProcess.<anonymous> (E:\Projects\Zettlr\forge.config.js:41:16)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:298:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducing

* Install nvm for windows (https://github.com/coreybutler/nvm-windows/releases)
* Install latest nodejs version (`nvm install latest`)
* Activate latest nodejs (`nvm use latest`)
* Install yarn (`npm install -g yarn`)
* Skip installing curl (already installed)
* Install Zettlr's dependencies (`yarn install --frozen-lockfile` from the Zettlr dir)
* Open visual studio code from Zettlr's root dir.
* Open a shell in visual studio code (``Ctrl+`)``
* Run `yarn start`

### Zettlr Version

Right off the develop branch

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 22H2

### Additional Information

Commit `ed91aac85489ac016f26f1a734e53ad34d8df7a5` (`git describe` fails because of a lack of annotated tags)

**Comment by learn-more** [comment]
Diving into `forge.config.js` (only reasonable result when searching for `generateAssets`),
it tries to launch:
`const argWin = [ 'bash.exe', [ './scripts/get-pandoc.sh', platform, arch ] ]`
Which suggests `bash.exe ./scripts/get-pandoc.sh win32 x64`
Running that manually in VS Code's shell:
```
PS E:\Projects\Zettlr> bash.exe ./scripts/get-pandoc.sh win32 x64
Working directory is /mnt/e/Projects/Zettlr/resources
Downloading: pandoc-2.19.2-windows-x86_64.zip ...
Extracting ...
./scripts/get-pandoc.sh: line 126: unzip: command not found
./scripts/get-pandoc.sh: line 127: unzip: command not found
Extracted to:
Moving binary from ./ to resources directory ...
mv: cannot stat './pandoc.exe': No such file or directory
Cleaning up ...
Successfully downloaded Pandoc for win32/x64!
```

**Comment by nathanlesage** [comment]
Thank you for running the command manually! `forge` is good at swallowing all and every piece of info logged to the console.

So, it fails because there's no unzip command found, but there is a possibility to have some unzip command available as the CI here on GitHub that also runs Windows has no problems downloading Pandoc. Unfortunately, I'm relatively unfamiliar with Windows. A quick search suggested that (at least newer versions of) Git Bash bundle `unzip`. Could that be the cause, that the Git install on your computer is a little bit older?

@kyaso Do you happen to use Windows sometimes and have an idea, or are you on Linux? I unfortunately don't remember …

**Comment by learn-more** [comment]
This runs inside the `wsl` environment in windows (note the `bash.exe` in front of the command).
There is a metric ton of pre-installed stuff on github runners:
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
or
https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md

**Comment by kyaso** [comment]
@nathanlesage A bit late to the party, but yes, I'm on Linux :)

**Comment by weissenbacherpwc** [comment]
got the same error on Mac. Any clues how to solve this on Mac?

**Comment by learn-more** [comment]
> got the same error on Mac. Any clues how to solve this on Mac?

Follow the same steps as I did to debug the issue.
