### ISSUE TITLE
export in pdf impossible

### ISSUE THREAD

**Issue by Colibri-fr** [Zettlr/Zettlr#396]
## Description
export in pdf impossible.
pandoc (1.19.2.4) : « --pdf-engine=xelatex » error

## Expected behaviour

**Screenshots**

## Platform
 - OS: Ubuntu
 - OS Version : 18.04 LTS
 - Zettlr Version 1.4.3
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information
Pandoc 1.19.2.4
working solution : pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $citeproc$ $standalone$ **--latex-engine=xelatex** -o "$outfile$"

**Comment by nathanlesage** [comment]
Zettlr requires Pandoc 2.0 or newer, as the `--pdf-engine`-option has been added in this one.

**Comment by nathanlesage** [comment]
P.S.: Please also see the corresponding FAQ-entry: https://docs.zettlr.com/en/faq/#on-export-zettlr-says-the-pdf-engine-wasnt-recognised

**Comment by Colibri-fr** [comment]
Thank you for your quick reply.
Sorry to open a discussion for this fake bug
