### ISSUE TITLE
Text jiggles around while typing (Nightly)

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#3960]
### Description

There's a bug in the display of bulleted lists, which can cause text to jiggle around while typing.  If you are typing in the paragraph *after* a list of bullet points, the text in the bullet points will start moving around randomly, as if it is being continually reformatted. I've noticed that the same effect also seems to lead to toggling in the display of headings.   A MWE is provided below. 

### Reproducing

The lorem ipsum below should allow the problem to be reproduced. Copy the lorem ipsum into Zettlr, and then place the cursor where I've marked "start adding text here", and then type at a normal pace. You should notice the bullet points above the cursor flashing and moving around, and the Heading below the cursor toggling between appearing as a large heading, and as ordinary sized text. The effect is more noticeable some widths of the main workarea than others, so if the effect isn't initially obvious, you could make the main window narrower. I don't think the problem is related to autosave, as it occurs even with autosave off.

Urna condimentum mattis pellentesque id nibh. Elementum integer enim neque volutpat. Orci ac auctor augue mauris augue neque. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Nisl nisi scelerisque eu ultrices vitae auctor eu. Risus viverra adipiscing at in tellus. Lacinia quis vel eros donec ac odio tempor orci. Facilisis gravida neque convallis a cras semper auctor neque vitae. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Velit ut tortor pretium viverra suspendisse potenti nullam. Eget velit aliquet sagittis id consectetur purus ut. Urna nec tincidunt praesent semper feugiat nibh sed. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Eget est lorem ipsum dolor sit amet consectetur adipiscing. Consequat id porta nibh venenatis cras sed felis. Pharetra vel turpis nunc eget lorem dolor. Cursus sit amet dictum sit amet justo donec enim diam.

Vulputate eu scelerisque felis imperdiet proin fermentum. Facilisis sed odio morbi quis. Rhoncus est pellentesque elit ullamcorper. Ac turpis egestas integer eget aliquet. Elementum integer enim neque volutpat ac tincidunt vitae. Elementum curabitur vitae nunc sed velit dignissim. Aliquam malesuada bibendum arcu vitae elementum. Nulla at volutpat diam ut venenatis tellus in. Feugiat sed lectus vestibulum mattis. Ac feugiat sed lectus vestibulum mattis ullamcorper. At elementum eu facilisis sed odio morbi quis commodo. Sem integer vitae justo eget magna fermentum. Convallis a cras semper auctor neque vitae tempus. Lacus vestibulum sed arcu non. Elit eget gravida cum sociis natoque. Vitae semper quis lectus nulla at volutpat diam.

- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu dictum varius duis at consectetur lorem donec. Tortor aliquam nulla facilisi cras fermentum.
- In mollis nunc sed id. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Elit at imperdiet dui accumsan. Quam vulputate dignissim suspendisse in. Ultricies integer quis auctor elit sed vulputate mi sit amet. Pretium nibh ipsum consequat nisl vel. Neque viverra justo nec ultrices dui. Urna porttitor rhoncus dolor purus non enim praesent elementum.
- Interdum posuere lorem ipsum dolor sit. Et sollicitudin ac orci phasellus egestas tellus. Pulvinar neque laoreet suspendisse interdum consectetur libero. Lacus vel facilisis volutpat est velit egestas dui. mlmlml  ml ml ml ml ml ml ml mlm
- Proin libero nunc consequat interdum varius sit amet mattis. Proin fermentum leo vel orci porta non pulvinar. Ut faucibus pulvinar elementum integer enim neque volutpat. Sit amet aliquam id diam maecenas ultricies mi eget mauris.
- Platea dictumst quisque sagittis purus sit amet volutpat. Nunc non blandit massa enim nec dui nunc. Tristique magna sit amet purus gravida quis blandit. Vitae justo eget magna fermentum iaculis eu. Arcu dictum varius duis at consectetur. Senectus et netus et malesuada fames ac turpis egestas. Mi eget mauris pharetra et ultrices neque. Ac odio tempor orci dapibus ultrices in. Et netus et malesuada fames ac turpis egestas sed.

**Start adding text here**, and you'll notice the text jiggling.  

# Faucibus nisl tincidunt eget nullam non. 

Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Proin nibh nisl condimentum id venenatis. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Consequat interdum varius sit amet mattis vulputate. Elementum nisi quis eleifend quam adipiscing. Malesuada bibendum arcu vitae elementum. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Porttitor rhoncus dolor purus non. Feugiat scelerisque varius morbi enim nunc.

Quis ipsum suspendisse ultrices gravida dictum. Montes nascetur ridiculus mus mauris vitae ultricies. In tellus integer feugiat scelerisque varius morbi enim nunc. Tortor condimentum lacinia quis vel eros donec ac odio. At augue eget arcu dictum varius duis at consectetur lorem. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Purus semper eget duis at tellus at. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Vel pharetra vel turpis nunc eget lorem dolor sed. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Etiam tempor orci eu lobortis elementum nibh tellus molestie. Tortor aliquam nulla facilisi cras fermentum odio eu.

Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Massa sed elementum tempus egestas sed. Amet consectetur adipiscing elit pellentesque. Id porta nibh venenatis cras sed felis eget velit. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Fames ac turpis egestas sed tempus. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Faucibus nisl tincidunt eget nullam. Malesuada proin libero nunc consequat interdum varius sit. Enim eu turpis egestas pretium.

Egestas integer eget aliquet nibh. Sed risus ultricies tristique nulla aliquet enim tortor. Id ornare arcu odio ut. In cursus turpis massa tincidunt dui ut ornare lectus. Nisi lacus sed viverra tellus in hac habitasse. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Ultrices mi tempus imperdiet nulla malesuada. Dolor sit amet consectetur adipiscing elit. Accumsan tortor posuere ac ut. Sit amet mattis vulputate enim. Velit ut tortor pretium viverra suspendisse potenti. Pulvinar sapien et ligula ullamcorper.

Integer vitae justo eget magna fermentum iaculis eu non. Eget velit aliquet sagittis id consectetur purus ut faucibus. Urna duis convallis convallis tellus id interdum velit laoreet. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Viverra nam libero justo laoreet sit amet cursus. Leo integer malesuada nunc vel risus. Quam adipiscing vitae proin sagittis nisl rhoncus. Dignissim enim sit amet venenatis urna cursus eget nunc. Ut faucibus pulvinar elementum integer enim. Blandit massa enim nec dui nunc mattis. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Euismod quis viverra nibh cras pulvinar mattis nunc sed. Duis convallis convallis tellus id interdum velit laoreet id. Neque viverra justo nec ultrices. Aenean sed adipiscing diam donec. Enim lobortis scelerisque fermentum dui faucibus in ornare. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Ut ornare lectus sit amet est placerat.

Nulla at volutpat diam ut venenatis tellus in. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Ultrices tincidunt arcu non sodales neque sodales ut. Elementum tempus egestas sed sed risus. Dapibus ultrices in iaculis nunc sed augue lacus. Ut diam quam nulla porttitor massa id neque. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Arcu ac tortor dignissim convallis aenean. Tristique senectus et netus et malesuada fames ac turpis. Ultricies mi eget mauris pharetra. Quam pellentesque nec nam aliquam sem et tortor consequat id. Dolor morbi non arcu risus quis varius quam quisque. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi.

### Zettlr Version

Nightly

### Specify version

2.3.0nightly20221128

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I fixed that in one of the last commits, after finding the culprit. It shipped with the last beta.

**Comment by jgsw** [comment]
Thanks very much! I can confirm that this bug is now fixed in Beta 1 for bulleted lists.

Unfortunately, I just discovered that the same bug still exists for _numbered_ lists.

**Comment by nathanlesage** [comment]
I don't use too many numbered lists so I couldn't reproduce, but I'm relatively certain it has nothing to do with lists ... please observe that as we go forward, so we can take action if necessary!
