### ISSUE TITLE
Right arrow button to go to the next note is gone (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3963]
### Description

The right arrow should be next the left one.

### Reproducing

Have a look on the toolbar.

### Zettlr Version

Nightly

### Specify version

2.3.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
Did you make sure to double check the preferences?

**Comment by Etienne-TR** [comment]
Oups you're right, Next button was unchecked !
