### ISSUE TITLE
No access to directories other than `Documents` in Ubuntu

### ISSUE THREAD

**Issue by sati-bodhi** [Zettlr/Zettlr#3974]
### Description

Zettlr cannot create new files and directories on Ubuntu 22.04

When setting a new workspace and creating a new note outside the default `Documents` folder, Zettlr seems unable to access the file system, resulting in new files and directories (or workspaces) that exist only on memory. A restart of the App would erase everything, leaving the original file system intact. 

### Reproducing

1. Install Zettlr on Ubuntu 22.04 from [Flatpak](https://flathub.org/apps/details/com.zettlr.Zettlr).
2. Create a new workspace outside the `Documents` folder. 
3. Create a new file in that new workspace. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

![Screenshot from 2022-12-06 23-38-43](https://user-images.githubusercontent.com/7592695/205956449-0644cf65-a113-47d1-8295-9e2011604543.png)

**Comment by nathanlesage** [comment]
The flatpack install has only very limited default rights by choice. You can use a package called "flatseal" to increase the access rights of Zettlr towards more parts of the file system. See more here: https://github.com/flathub/com.zettlr.Zettlr/issues/13
