### ISSUE TITLE
Use cursor keys to edit filename

### ISSUE THREAD

**Issue by mottech20** [Zettlr/Zettlr#3987]
### Description

When creating a new file, the filename which is pre-populated with the default filename can't be edited with the keyboard: the cursor keys can't be used to move left and right and user must click on the filename itself to add text to the beginning or end of it.

### Reproducing

Set a custom pattern for new filename. Create a new file. Try to change part of the name by moving around (left and right) in the textbox.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This is already fixed and comes with the next update.
