### ISSUE TITLE
[BUG] Printing Preview not Working

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#399]
## Description

This was brought to my attention on the forum: https://forum.zettlr.com/discussion/71/print-error

It is meanwhile confirmed, I'll have a look.

## Reproducing

Simply try to open the print preview. Get an error in form of a small notification.

## Expected behaviour

Preeeeeeeetty much obvious, I hope.

**Screenshots**

Cf. the forum entry

## Platform
 - OS: At least macOS, pretty sure other OS's are also affected.
 - Zettlr Version: 1.4.3

## Additional information

I'll do the usual: Do a full-text search of the error and find the culprit. Stay tuned.

**Comment by deathrush** [comment]
On 1.5.0-beta Windows， Printing Preview is still notwWorking

**Comment by nathanlesage** [comment]
I know. I would've closed this issue if I had already fixed that.

Simple rule:

- Open Issues: Still an issue.
- Closed issues: Already shipped with a release, or will be shipped with the next release.

**Comment by nathanlesage** [comment]
Fixed, ships with next beta.
