### ISSUE TITLE
Javascript error when opening settings tab

### ISSUE THREAD

**Issue by Imusten** [Zettlr/Zettlr#3998]
### Description

Hi,

I just installed Zettlr on my new computer (MacBookAir M2 w. MacOs 12.5) and I keep receiving an error message when trying to open the settings tab.

<img width="313" alt="Capture d’écran 2022-12-20 à 23 31 46" src="https://user-images.githubusercontent.com/121136451/208780051-a4d7f87a-4557-47b9-9d07-5e1c48afd39d.png">

Can you help?

Thx a lot!

### Reproducing

Open the settings tab.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterrey 12.5

**Comment by nathanlesage** [comment]
This bug was a nasty one that really was bad, but it is fixed in the current develop branch and it will ship with the next release! The betas for 3.0 are starting in January!

**Comment by nathanlesage** [comment]
One quick fix for now, though: First quit Zettlr. Then, open a Finder window, select "Go", hold down "Option" and click on the appearing entry "Library", move to "Application Support" -> "Zettlr" and then remove the file "window_state.json". Then restart Zettlr, the settings window should then appear without problems.
