### ISSUE TITLE
[Feature] Need for font customization and multiple tabs

### ISSUE THREAD

**Issue by deathrush** [Zettlr/Zettlr#400]
## Description

Like VNote, Mark Text, support change font family and font size.
Besides, a tab bar is a great thing.

**Comment by nathanlesage** [comment]
Concerning your need for fonts, it's addressed by Zettlr's Custom CSS-feature. Please see the documentation for all information concerning this: https://docs.zettlr.com/en/core/custom-css/

And the tabs are covered by #243, so closing as duplicate.
