### ISSUE TITLE
Is there a keyboard shortcut or button to create a 'saved file' (within the current directory)

### ISSUE THREAD

**Issue by bjohas** [Zettlr/Zettlr#4006]
### Description

I've installed Zettlr 2.3.0 on Ubuntu.

My main question is this: Is there a keyboard shortcut or button to create a 'saved file' (within the current directory)? I read this discussions,  https://github.com/Zettlr/Zettlr/issues/2480 but it's not clear to me whether the changes have been implemented or what the 'solution' is. 

Basically, I don't want in-memory/temporary files. I would like a keyboard shortcut or button that creates a new file, within the current workspace directory, that is named with the date/time string (as Zettlr does), without any prompting. The ctrl-n / + button do this, but create an in-memory file. Is there a setting that will just create a file within the current directory? Any solutions? 

(I am aware that I can do 'right click + enter' on the workspace directory... however, I am looking for an application that allows me to take notes very quickly, e.g., during an unexpected call, hence looking for keyboard shortcut ideally...)

Many thanks!
Björn

### Reproducing

N/R

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu

**Comment by exanrauzer** [comment]
Hi Bjorn!

Your entry is rather a question, not a bug report. Maybe consider opening a discussion post in [Discussions](https://github.com/Zettlr/Zettlr/discussions) section or join [Discord](https://discord.gg/PcfS3DM9Xj) to get the feedback from other users.

**Comment by nathanlesage** [comment]
I think there's a setting for that, but I'd have to look it up.

As for this part of your question:

> Basically, I don't want in-memory/temporary files.

Those are gone in 3.0.
