### ISSUE TITLE
How to use CSL locale files with zettlr

### ISSUE THREAD

**Issue by Martin15135215** [Zettlr/Zettlr#4019]
### Description

I use zettlr with zotero, however when i trie to use german words Seite instead of page in the citations, it does not recognize:

Example [@somekey, Seite 100] instead of [@somekey, page 100]

### Proposed Changes

i then read here https://docs.zettlr.com/en/academic/citations/ -> there i found a link to pandoc's citeproc engine https://pandoc.org/demo/example19/Extension-citations.html and there it reads:

> Pandoc uses some heuristics to separate the locator from the rest of the subject. It is sensitive to the locator terms defined in the [CSL locale files](https://github.com/citation-style-language/locales). Either abbreviated or unabbreviated forms are accepted. In the en-US locale, locator terms can be written in either singular or plural forms, as book, bk./bks.; chapter, chap./chaps.; column, col./cols.; figure, fig./figs.; folio, fol./fols.; number, no./nos.; line, l./ll.; note, n./nn.; opus, op./opp.; page, p./pp.; paragraph, para./paras.; part, pt./pts.; section, sec./secs.; sub verbo, s.v./s.vv.; verse, v./vv.; volume, vol./vols.; ¶/¶¶; §/§§. If no locator term is used, “page” is assumed.

And so in the repo https://github.com/citation-style-language/locales there is a local for page

![image](https://user-images.githubusercontent.com/110968398/210780467-058ddd79-8554-46b4-b4b9-0168748abc31.png)

### Caveats

i think there is only a need for e new path after CSL-Style (optional)

Like CSL-Locale (optional)

![image](https://user-images.githubusercontent.com/110968398/210780989-c83c8d89-fa29-4f71-94a0-867ee4485e45.png)

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by nathanlesage** [comment]
Zettlr actually ships with all CSL files already; see this directory: https://github.com/Zettlr/Zettlr/tree/develop/static/csl-locales

The locale, however, only determines the _output_ of citeproc. The detection happens at another stage, and at that stage, Zettlr supports English, German, and French already. See this file:

I can confirm that the detection works fine within Zettlr:

![image](https://user-images.githubusercontent.com/17251683/210827327-c677e900-b08c-45df-a4b8-20d594b25b4f.png)

Are you referring to an export that fails to recognize this convention, or is this happening within Zettlr? In the latter case, it could be a bug of 2.3 that will be obsolete when I start the public beta next week. In the former case, we would need to dig deeper first.

**Comment by Martin15135215** [comment]
So i write this in zettlr 

![image](https://user-images.githubusercontent.com/110968398/210970858-74e5f0b4-e45d-4ee3-84e3-1a4d2ecfe207.png)

it would change to that

![image](https://user-images.githubusercontent.com/110968398/210970930-46b01b11-2b32-4523-9581-9c82283a501f.png)

After that i export with pdf (LaTeX) 

![image](https://user-images.githubusercontent.com/110968398/210971177-63c4be01-6cf0-45c8-a98c-c707191adfbd.png)

Footnote

![image](https://user-images.githubusercontent.com/110968398/210971222-7868918f-442d-4d73-ae00-1966ad9d6a82.png)

so my question is, why in the Footnote on the last image, its only 100 instead of Seite 100 -> has it something to do with the CSL Style, if so, can you point me to the appropriate csl style so i can test Seite?


I am happy to hear there will be a new version of zettlr. I am looking forward to the new version of zettlr. In this new version, is there the possibility with pandoc filter cross-ref, i need it in my report to cross ref my images. And will there be also an shortcut for exporting a project, that would be nice.

**Comment by nathanlesage** [comment]
Ah I see. So, both Pandoc on export, as well as Zettlr while you write recognize "Seite" appropriately as a locator. The citation style that is being used by Zettlr (I think Chicago or Harvard) simply omits page locators, as these are the default. Also, the style you use to export doesn't include that info either.

So there's nothing wrong and other styles may include that info. You can confirm this behavior by using "chapter"/"Kapitel" to check, this might be included in the output more likely since it is not as usual as it is to reference pages (but styles may omit that just as well).

If you want a style that explicitly includes that info, you would have to search for one. Head over to www.Zotero.org/styles -- you may find something there. Then, just point Zettlr to that style and it will be used during export. (Within Zettlr, it will always use the same style as it can't handle dynamic footnotes, see for more info the documentation,)
