### ISSUE TITLE
(3.0.0-beta) files cannot be opened correctly and the file is displayed incorrectly or sometimes not at all.

### ISSUE THREAD

**Issue by Br0nur** [Zettlr/Zettlr#4032]
### Description

After updating to 3.0.0-beta, the files are no longer displayed correctly or do not open at all.

### Reproducing

Update to 3.0.0.-beta in my case. 

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0.-beta

### Installation Method

None

### Your Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by foss-** [comment]
Here's a sample file `mangled markdown.md` (30 days): https://upload.disroot.org/r/G5vaoP2E#ZFtQFuio9xoG7DlvMe6uHFPTJC4BeDUSdkO5m0ZFzgM=

It did show fine in Zettlr 2.x.

This is how it shows in zettlr Version 3.0.0-beta (3.0.0-beta):

![1](https://user-images.githubusercontent.com/5708172/211594162-70ca8805-6719-4257-9f54-a973e9ea4eee.png)

**Comment by nathanlesage** [comment]
Thanks for the file! The link rendering broke with the bad formatting of the file.

Until the next beta is out, you can mitigate this error by disabling the link rendering in Preferences ⇾ Display.

**Comment by foss-** [comment]
Awesome, thanks for the quick fix and workaround. Also lets please not talk about how this is a poorly formatted md file.

**Comment by Br0nur** [comment]
Thanks!
