### ISSUE TITLE
File conflict issue with 3.0.0 beta-1 x64 rpm release

### ISSUE THREAD

**Issue by erentar** [Zettlr/Zettlr#4035]
### Description

```
user:Downloads/ $ sudo dnf install ./Zettlr-3.0.0-beta-x86_64.rpm        [0:15:54]
[sudo] password for user: 
Last metadata expiration check: 1:36:48 ago on Tue 10 Jan 2023 10:39:35 PM.
Dependencies resolved.
======================================================================================
 Package         Architecture    Version                  Repository             Size
======================================================================================
Upgrading:
 zettlr          x86_64          3.0.0_beta-1             @commandline           81 M

Transaction Summary
======================================================================================
Upgrade  1 Package

Total size: 81 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/07/85e1c34a4493148e34cd008dc07c48ae317ae5 from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
  file /usr/lib/.build-id/0b/2d3819251c22687b07ada79840c28de14e3e8a from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
  file /usr/lib/.build-id/10/30c7e15926230e57045d01a9cc572c5dec5a5b from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
  file /usr/lib/.build-id/45/d706bf2544edbb97329b19dbb529eecb07b77c from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
  file /usr/lib/.build-id/4a/52404baa65a5317ca0f35c8791495bd96b9df1 from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
  file /usr/lib/.build-id/57/6a5a8b505f341086e0dac747e8224d325db05d from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
  file /usr/lib/.build-id/90/9d0b5007ba7bf20d9e4205235b3fe5a9f3309e from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
  file /usr/lib/.build-id/bf/d1a7f70351f11e4e50fcd7a83c19a2d762a6d4 from install of zettlr-3.0.0_beta-1.x86_64 conflicts with file from package jupyterlab-desktop-3.5.1_1-1.x86_64
```

### Reproducing

1. install jupyterlab desktop
2. dnf install zettlr beta
3. above error happens

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0 beta-1

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 37

### Additional Information

The conflicting files should not be included in the RPM package.

**Comment by erentar** [comment]
https://github.com/jupyterlab/jupyterlab-desktop/issues/552

**Comment by nathanlesage** [comment]
Oh well, I haven't seen one of these in quite some time. I'll have a look into the issue list here. We had that problem once, and we somehow managed to solve that, but I don't remember how ...

Feel free to also look through the issues here, in case I can't find it.

**Comment by nathanlesage** [comment]
Here's one: https://github.com/Zettlr/Zettlr/issues/3013

**Comment by nathanlesage** [comment]
@erentar I have now implemented the solution provided for there and started another build. Since the Windows builds are currently failing, it won't be uploaded to the nightly directory, so here's what I would like you to do:

Go to the corresponding run of our build pipeline: https://github.com/Zettlr/Zettlr/actions/runs/3891441734

After the "Linux" build is finished (indicated by a green checkmark), you should see an "artifact" below the summary called Linux (see screenshot). Download this (it's a Zip file), extract it, and then try it out with the RPM file (the ZIP file contains all Linux builds, so you can ignore the others).

![image](https://user-images.githubusercontent.com/17251683/211769775-78a29a73-966e-4d40-97fc-ce07f87f43f4.png)

**Please report back if this fixes your issue!**

**Comment by nathanlesage** [comment]
Ignore the above comment, the option is buggy and cannot be used right now. I'll get back to you when I have a solution.

**Comment by erentar** [comment]
Thank you very much for your effort! i saw you spent your morning on this issue

**Comment by nathanlesage** [comment]
Please check the current nightlies. I've switched from Electron Builder to Electron Forge, which at least on Debian has mitigated quite a few issues.
