### ISSUE TITLE
Copy as html does not work

### ISSUE THREAD

**Issue by oliviercrouzet** [Zettlr/Zettlr#404]
## Description
When you try to copy a selected text in the editor through the "Copy as html'  contextual menu, the content of clipboard is emptied but nothing is sent to it  (observed on Windows 10)

## Expected behaviour

**Screenshots**

## Platform
 - OS Version [e.g. 11]
 - Zettlr Version [e.g. 0.15]
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Can confirm on macOS

**Comment by nathanlesage** [comment]
Aaaand fixed.
