### ISSUE TITLE
`Replace next occurrence` does not work as expected

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#4041]
### Description

There are actually two issues here.

First, the main bug is that when I use `Replace next occurrence`, the next occurrence is not actually replaced. Rather, it is simply highlighted as though I'd run a simple "Find."

Second, when I scroll down while viewing a long document and then call the `Find in file` dialogue using `Ctrl-F` or `Edit > Find in file`, the viewport returns to the top of the document (scrolls all the way up). This behavior is incommensurate with some uses of the `Find in file` feature. For example,using `Replace next occurrence`, is difficult or impossible when it's unclear what the "next occurrence" is — i.e., when I can no longer see the cursor location, since it's placed toward the end of the document and outside the viewport.

### Reproducing

See above.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro (Rolling)

**Comment by exanrauzer** [comment]
Another words - window to replace text is pinned to the document and is not floating.

From my experience I like HackMD way of dealing with text replacement. It is done in one line above the text, and with keybord only. I think this form matches Zettlr style and could be picked up:

![Recording 2023-01-11 at 23 21 52](https://user-images.githubusercontent.com/103963891/211930685-61f18421-5638-4e37-ae88-e69c07e11e6a.gif)
