### ISSUE TITLE
Intention in YAML Frontmatter

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4047]
### Description

I might remind myself wrongly, but if I recall correctly, in Zettlr 2.3 there was an automatic intention within YAML Frontmatter. When I had a frontmatter like further below and I pressed enter after the `A`, the appropriate number of spaces were already added to the next line. With 3.0 (which is a great release, congratulations!) I need to type every space by myself. This might not be annoying when it is just one space, but gets annoying when you have to add eight spaces multiple times.

### Reproducing

Put the following code into a file.
```
---
key:
  nested-key:
    - A
    - B
---
```
Put the cursor behind `A` and press enter.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0-beta (b0c84fe2-f4b7-401d-977e-d65120b203f0)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
The reason is that we don't have an indent service for the YAML mode. I'll have to write one at some point (aka once I figure out how to do that).

**Comment by nathanlesage** [comment]
> The reason is that we don't have an indent service for the YAML mode. I'll have to write one at some point (aka once I figure out how to do that).

That was completely wrong. I just had to correctly bind the `newlineAndIndent` command. 🙄
