### ISSUE TITLE
Error on opening Zettlr 3.0.0 beta (m1 mac)

### ISSUE THREAD

**Issue by ethanbass** [Zettlr/Zettlr#4048]
### Description

I downloaded the arm64.dmg build of Zettlr 3.0.0 beta, but I am not able to open it on my computer (m1 mac running mac os 12.5.1). When I attempt to open it, I get the following error message:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: dlopen(/private/var/folders/63/yn9cxpy52tg1ywn5r6n514xc0000gn/T/AppTranslocation/1027FE4C-B06C-45A3-B9BD-C498695148CE/d/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 0x0001): tried: '/private/var/folders/63/yn9cxpy52tg1ywn5r6n514xc0000gn/T/AppTranslocation/1027FE4C-B06C-45A3-B9BD-C498695148CE/d/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13328)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at 19572 (/private/var/folders/63/yn9cxpy52tg1ywn5r6n514xc0000gn/T/AppTranslocation/1027FE4C-B06C-45A3-B9BD-C498695148CE/d/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1152799)
at r (/private/var/folders/63/yn9cxpy52tg1ywn5r6n514xc0000gn/T/AppTranslocation/1027FE4C-B06C-45A3-B9BD-C498695148CE/d/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2150899)
```

After throwing the error, the application actually stays open and I can click around the menu at the top, but I can't get anything to open.

### Reproducing

see above.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Monterey 12.5.1

### Additional Information

I tried the x64 version for good measure and I can't open that one either. It doesn't throw an error message, but just quits right away when I try to open it.

**Comment by nathanlesage** [comment]
The issue has been fixed, the next beta will work fine. Until then, please download the x64 version, that will work fine as well.

**Comment by ethanbass** [comment]
Thank!. FIY, the x64 version didn't seem to be working on my computer either (see "Additional Information"). I'm not sure why exactly since there was no error message.

**Comment by nathanlesage** [comment]
@ethanbass Do you have Rosetta installed? Because I believe it's not on macOS by default, but has to be installed once. It's required to translate the x64 architecture binary for M1/M2.

**Comment by ethanbass** [comment]
Nevermind. The x64 build is working now. I'm not sure what changed from yesterday though...

**Comment by nathanlesage** [comment]
@ethanbass Probably the first start prompted macOS to download Rosetta in the background and now it's installed and so it just works :D

**Comment by ethanbass** [comment]
thanks it's working now with the new beta.1, as promised
