### ISSUE TITLE
Beta 3.0.0 Fails to Open (Debian)

### ISSUE THREAD

**Issue by cyanitol** [Zettlr/Zettlr#4049]
### Description

When running application it fails to open and produces the following error:
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_ZettlrNiLWyo/resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 19572 (/tmp/.mount_ZettlrNiLWyo/resources/app.asar/.webpack/main/index.js:2:1151389)
    at r (/tmp/.mount_ZettlrNiLWyo/resources/app.asar/.webpack/main/index.js:2:2148597)
`

### Reproducing

Attempt to run the program. AppImage and .deb both have the same issue.

### Zettlr Version

Stable (most recent version)

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian 11.6

### Additional Information

Linux dddd 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/LinuxArchitecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
Stepping:                        9
CPU MHz:                         799.712
CPU max MHz:                     3900.0000
CPU min MHz:                     400.0000
BogoMIPS:                        5799.77
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        4 MiB

**Comment by cyanitol** [comment]
Additional details:
#:~strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXXXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by nathanlesage** [comment]
Puh, I've read someone mentioned libgcc needs updating, but I'm not too versed with Linux to correctly give advise here. @kyaso do you have an idea here?

**Comment by kyaso** [comment]
Not sure either, unfortunately, but does [this](https://stackoverflow.com/questions/65349875/where-can-i-find-glibcxx-3-4-29) maybe help, @cyanitol?

**Comment by cyanitol** [comment]
Hey all,
Sorry for the delay.  Caught a wonderful cold.

So for the packaged .deb there's two issues it appears.  One is that after install /opt/Zettlr has the wrong permissions.  The second is that Debian stable with backports only libgcc 3.4.28 is the maximum version available for install.

/opt/Zettlr install permissions: drwx------  4 root root 4.0K Jan 25 22:26  Zettlr

**Comment by cdelavegamartin** [comment]
I'm finding the same issue with Ubuntu 20.04:
$ cat /etc/*ease
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ sudo apt-get install libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version (10.3.0-1ubuntu1~20.04).
libstdc++6 set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 2 not to upgrade.

$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by SN-CH** [comment]
I can confirm results reported by @cdelavegamartin (exactly the same OS, the output of `cat /etc/*ease` and `strings usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` is perfect match to what is listed above).

**Comment by te2dy** [comment]
I seem to have more or less the same error (I am unable to say what it means, so…) on macOS.

I've updated the app from v3.0.0-beta to v3.0.0-beta.1 with the built-in downloader. Since this update, the application does not open and the following error message is displayed:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: dlopen(/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 0x0001): tried: '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (no such file), '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13328)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at 19572 (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1153497)
at r (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2156778)
```

**Comment by nathanlesage** [comment]
@te2dy Your error is a completely different one, not the one discussed here. Additionally, the error you are experiencing has already been fixed. Feel free to download one of the current nightlies, these will work fine: https://nightly.zettlr.com

**Comment by te2dy** [comment]
@nathanlesage I apologize for my incompetence and thank you for your help.

**Comment by nathanlesage** [comment]
@MaPeras What problem do you experience?

**Comment by MaPeras** [comment]
I installed the .deb package, but Zettlr won't appear among applications and I can't figure out a way to open it.
