### ISSUE TITLE
Problems with export formulas in PDF

### ISSUE THREAD

**Issue by sedol1339** [Zettlr/Zettlr#4058]
### Description

Hello! When I export formulas in PDF, I get multiple render problems: overlapping symbols, too small braces etc.

![342543634](https://user-images.githubusercontent.com/5188731/212609186-815f32d6-3c77-4a63-b6e6-8e75d4687f7d.png)

How can I get better results?

### Reproducing

Export the following in PDF:

$\text{Huber}(y, \hat{y}) = 
\begin{cases}
\frac{1}{2} (y - \hat{y})^2,& \text{if } |y - \hat{y}| \leq \delta\\
\delta (|y - \hat{y}| - \frac{1}{2} \delta),& \text{otherwise}
\end{cases}$

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This works, at least on the current beta:

![image](https://user-images.githubusercontent.com/17251683/213717722-82d7fa2f-2686-49a1-8890-b5949f098eb4.png)

Note, however, that there are indeed inconsistencies in the “Simple PDF” exporter. In that case I defer you to either look at the Pandoc documentation regarding HTML export for options. You can adapt the HTML export profile to adapt it. This is out of scope for Zettlr.
