### ISSUE TITLE
Icon Beautification

### ISSUE THREAD

**Issue by ScreeperC** [Zettlr/Zettlr#4059]
### Description

The desktop icon of this program is too small to be beautiful. It looks out of place on my desktop.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94523517/212620287-84674e60-71e1-4162-a478-f7e7cf717bb4.png">

### Proposed Changes

I want the desktop icon to be larger (like edge or Vivaldi)

### Caveats

In my opinion, just magnifying LOGO will not affect other functions of this program.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
If someone with experience in design wants to tackle this, please go ahead. @marc2o did that some time ago with the macOS icon, and I agree that the Windows & Linux icons deserve an overhaul as well.

I can't do that, unfortunately, due to lack of experience (and a sense for good visuals).

**Comment by 08262** [comment]
Nice to see that issue #4059 seems to have been resolved by #4286. Maybe this issue can be closed.

**Comment by nathanlesage** [comment]
Oh you're right!
