### ISSUE TITLE
Typing $ (dollar sign) causes the surrounding text to transform in a randomish way

### ISSUE THREAD

**Issue by max-l** [Zettlr/Zettlr#406]
In some circumstances usually when I write a price in dollar, ex: $10, a portion of text surrounding the phrase that I am typing transforms into a weird text, that appears to be a random transformation displayed in italic.  It is hard to reproduce, if I write it in an empty doc, it will not happen.

**Comment by nathanlesage** [comment]
It sounds as if the LaTeX inline renderer does this. Try escaping the dollar-signs, because it will happen as soon as you have two dollar signs on a line. If you do not use LaTeX math equations at all, you can also completely deactivate this behaviour in the settings. Does this solve the issue?

**Comment by max-l** [comment]
I see. How do I disable the behavior, I don't see a setting for that ? 

Thanks

**Comment by nathanlesage** [comment]
In the "Display" tab (Math equations)

**Comment by max-l** [comment]
Oh, it was staring at me and I couldn't see it ! 

Thanks !

**Comment by nathanlesage** [comment]
Perfect, good to hear!
