### ISSUE TITLE
Zettlr 3.0.0-beta fails to launch: »A JavaScript error occurred in the main process« (macOS)

### ISSUE THREAD

**Issue by marc2o** [Zettlr/Zettlr#4061]
### Description

When trying to launch Zettlr (either via double click, right-click + open or terminal) the following error message is displayed, and nothing else (unfortunately it does not let me copy the text):

<img width="632" alt="Bildschirm­foto 2023-01-16 um 12 51 29" src="https://user-images.githubusercontent.com/75239777/212673338-42cfa9ca-6f9a-4684-9f8a-f1963571d046.png">

Running `/Applications/Zettlr.app/Contents/MacOS/Zettlr` directly from the terminal additionally results into this message: `objc[3841]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x23d97b110) and /Applications/Zettlr.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10a78bf38). One of the two will be used. Which one is undefined.`

### Reproducing

Remove older version of Zettlr. Optionally remove all the Zettlr folders in ´~/Application Support`. Launch the app.

1. Double click the app icon
2. Right click the app icon and select open.
3. Launch via terminal using `open /Applications/Zettlr.app`
4. Run from terminal directly calling `/Applications/Zettlr.app/Contents/MacOS/Zettlr`

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

13.1 (22C65)

### Additional Information

The latest stable 2.3.0 runs just fine. But I have been getting this weird behavior from any of the nightlies as well.

**Comment by exanrauzer** [comment]
There were couple of similar issues recently, but they were closed - check them out.

**Comment by nathanlesage** [comment]
There was an issue compiling the first beta. Please download the current nightly, it's basically the dame as the first beta sans the issue you are experiencing: nightly.zettlr.com
