### ISSUE TITLE
Memory of text edition is lost after tab switch

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#4063]
### Description

I've just found out that when I cut (ctrl + x) portion of text, switch tab, and go back to initial tab - i can't redo (ctrl + z) the text I had cut.  This is very nasty bug that I was dealing with on iA Writer (a little modified). It causes potential **text loss**.

In 2.3.0 every tab had its own 'memory' of text edition. Now, in 3.0.0 beta, memory of file edition is lost every time you switch the tabs.

### Reproducing

Open couple of tabs. Write some text. Check if redo works. Write some text again. Switch tab and switch to initial tab. Try if redo works.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Ouh, that can be tricky. In order not to have tens of separate editor instances, there is only one instance that always resets when you switch tabs. However, that info is still available, since the document is persisted in the main process.

I'll need a way to figure out how to synchronize the editing history over the IPC bridge, which could be very nasty. I can't promise quick help, but you do have a point.

**Comment by exanrauzer** [comment]
Every time I switch tab I lost also position of a document on screen - it is always brought to the top. I guess this is based on the same issue. 2.3.0 handles this very well.

**Comment by nathanlesage** [comment]
> I guess this is based on the same issue.

Nope, it is not—the editor does save the document position. There is a mechanism to remember the scroll position in the editor, but it's a bit difficult to handle, since CodeMirror 6 is much more aggressive in its rendering of widgets.

**Comment by nathanlesage** [comment]
This should no longer happen, I've just begun caching the documents, so that when you switch tabs, the history should be retained!

… yup, confirmed – coming with the next nightly.

**Comment by exanrauzer** [comment]
Great!
