### ISSUE TITLE
[Feature request] NOT operator for searching notes

### ISSUE THREAD

**Issue by raoul-van-oosten** [Zettlr/Zettlr#407]
It would be great if a NOT operator would be functional. For instance to search for orphan notes (simply searching for notes that so not contain "[["). Using the exclamation mark?

**Comment by nathanlesage** [comment]
Using the exclamation mark was the plan — I simply did not come around to implementing it yet!

Related: #179

**Comment by nathanlesage** [comment]
And here we go!
