### ISSUE TITLE
Internal link chooser displaying ID and not title or first header 1

### ISSUE THREAD

**Issue by victor-fancelli-capdevila** [Zettlr/Zettlr#4076]
### Description

After updating to 3.0.0 (btw congratulations :partying_face: , you've done a wonderful work!), when I open an internal link with [[ ]], the prompt displays
```nameoffile:nameoffile```
like
```20230105084215: 20230105084215```

![Zettlr](https://user-images.githubusercontent.com/98529522/213667519-af679492-584d-4e9c-ab9d-cf6146558390.png)

I expected the second one to be the title or first header of the file (I check and that is properly configured). If I write text inside the square brackets, it founds nothing (except the numbers). And of course, it does not add the file title after the link.... The same for citation or tags works perfect...

In the left column, titles of files are correctly rendered

Thank you!

### Reproducing

1. open a new Zettl
2. write [[
3. check for the options it offers

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 37

### Additional Information

I normally use the rpm, but the error also occurs in the AppImage, also in the nightly version.

It is something with my configuration, isn't it?
* The ID regular expression is set to ```(\d{14})```
* Pattern for new IDs ```%Y%M%D%h%m%s```

I looked at the logs and I found nothing related...

**Comment by nathanlesage** [comment]
You are right, this is platform independent. I'll have a look!

**Comment by nathanlesage** [comment]
Had a look: What you're experiencing is if you take the filename as an ID. Until now, Zettlr would only show you the filename, and neither H1 nor YAML title. This was not a bug. But I've now included a display name that can deviate from the filename. (Note, though, that files whose filename only consist of an ID will still be solely linked using this ID)
