### ISSUE TITLE
Escape key not working for the popup that opens when beginning a code block

### ISSUE THREAD

**Issue by BenjaminHerbert** [Zettlr/Zettlr#4077]
### Description

When I am begin a codeblock, the popup to choose syntax highlighting opens up.

I press <kbd>Esc</kbd> to close it.

The popup stays there.

### Reproducing

1. Type <code>```</code> (popup opens).
2. Press <kbd>Esc</kbd>

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr Version: 2.3.0 (UUID: d59bb5be-27f5-42bb-96be-c0bc943b50ef)  

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

System: linux 6.0.12-200.fc36.x86_64 (architecture: x64)

**Comment by nathanlesage** [comment]
This is fixed in the current Beta!
