### ISSUE TITLE
Extra scroll bar in the middle of the page in distraction-free mode

### ISSUE THREAD

**Issue by tkeiderling** [Zettlr/Zettlr#4078]
### Description

In distraction-free mode the text is compressed and a scroll bar appears in the middle of the page where none used to be.  Also, the text continues above the blue menu bar. 

![image](https://user-images.githubusercontent.com/90908474/213754285-3436a122-1654-4079-a0c4-69699f8db7de.png)

### Reproducing

Turn on distraction-free mode either through the keyboard shortcut or the dropdown menu. 

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Could you please provide a full screenshot of how your Zettlr window looks like? I can have a look later.

**Comment by tkeiderling** [comment]
![image](https://user-images.githubusercontent.com/90908474/213781622-c36a0c9e-2c6d-4a20-a0e2-ab6882d28c55.png)

**Comment by nathanlesage** [comment]
Forgot to close the issue – fixed that some time in the end of last week :)
