### ISSUE TITLE
Table of contents unreliable for long documents 

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#4079]
### Description

On loading a document, or on switching the active tab, the Table of Contents does not display fully for longer documents. This may partly depend on the speed of the computer - but on my machine, for any document longer than around 500 words, the ToC displays only partially. 

If you start typing, and autosave kicks in, the ToC then usually appears correctly.  However, if you flick to another active tab, and back again, ToC will again be displayed incorrectly. 

### Reproducing

A MWE is below. When this file is loaded, the ToC will display only Headings One to Four. On modifying the file, all the headings  (One to Nine) appear in the ToC. However, if you flick to another active tab, and back again, then the ToC will again show only headings One to Four.

To reproduce, copy the markdown below into Zettlr, save the file, close and reopen. This should reveal the ToC problems. 

# Heading one

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Accumsan in nisl nisi scelerisque eu ultrices. In iaculis nunc sed augue. Id ornare arcu odio ut sem nulla pharetra. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non. Id porta nibh venenatis cras sed. Vitae nunc sed velit dignissim sodales ut eu. Suspendisse faucibus interdum posuere lorem ipsum. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Ac auctor augue mauris augue neque gravida. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Amet nisl purus in mollis nunc sed id semper risus. Ornare aenean euismod elementum nisi quis eleifend. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. At risus viverra adipiscing at in. Sagittis vitae et leo duis ut diam quam nulla.

# Heading two

Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Tortor aliquam nulla facilisi cras fermentum odio eu. Ultricies mi quis hendrerit dolor magna eget est. Est sit amet facilisis magna etiam tempor orci eu lobortis. Aliquet nec ullamcorper sit amet. Magna fermentum iaculis eu non diam phasellus vestibulum lorem. At elementum eu facilisis sed odio morbi quis commodo. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Ipsum dolor sit amet consectetur adipiscing elit ut. Et malesuada fames ac turpis egestas integer eget aliquet. Odio morbi quis commodo odio aenean sed adipiscing. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Vitae tempus quam pellentesque nec. Venenatis cras sed felis eget. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Aliquet porttitor lacus luctus accumsan tortor posuere. 

# Heading three

Pharetra convallis posuere morbi leo urna molestie at. Elit eget gravida cum sociis natoque penatibus et magnis. Pharetra vel turpis nunc eget lorem dolor. In metus vulputate eu scelerisque felis. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Vestibulum lectus mauris ultrices eros in. Consequat id porta nibh venenatis cras sed felis. Dui nunc mattis enim ut tellus elementum. Rutrum quisque non tellus orci ac auctor. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Amet consectetur adipiscing elit duis tristique sollicitudin. Auctor augue mauris augue neque gravida in fermentum. Facilisi nullam vehicula ipsum a arcu. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Vulputate dignissim suspendisse in est.

# Heading four

Id venenatis a condimentum vitae. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Senectus et netus et malesuada fames ac turpis egestas integer. In est ante in nibh mauris cursus mattis molestie. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Congue quisque egestas diam in. Donec massa sapien faucibus et molestie. Faucibus purus in massa tempor nec feugiat. Dolor magna eget est lorem. Pellentesque sit amet porttitor eget dolor morbi non. Massa ultricies mi quis hendrerit. Leo duis ut diam quam nulla porttitor massa id. Arcu vitae elementum curabitur vitae nunc sed velit. Ac turpis egestas integer eget aliquet nibh. Adipiscing diam donec adipiscing tristique. Urna molestie at elementum eu facilisis sed.

# Heading five

Habitant morbi tristique senectus et netus et. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Sapien et ligula ullamcorper malesuada proin. Quis eleifend quam adipiscing vitae. Blandit libero volutpat sed cras. Platea dictumst vestibulum rhoncus est pellentesque. Pellentesque eu tincidunt tortor aliquam. Est pellentesque elit ullamcorper dignissim. Vitae congue mauris rhoncus aenean. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Id donec ultrices tincidunt arcu. Elit pellentesque habitant morbi tristique senectus et.

# Heading six

# Heading seven

# Heading eight

# Heading nine
 

### Zettlr Version

Nightly

### Specify version

3.0.0 Beta 1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

I'm guessing this bug will be related either to a hard limit on the number of characters Zettlr is parsing for the ToC on loading the file, or to a timeout. If it's a timeout, then it may not be reproducible with the markdown file above. On a faster machine, possibly you will need a longer file to see the effect.

**Comment by BabakFarshchian** [comment]
I have the same issue. It seems like the ToC is trimmed at the end. It goes to some point and then does not show the rest. This is true for a file of 519 words, but also for longer files. I have a file of 17200 words where only "Introduction" is shown in ToC

**Comment by nathanlesage** [comment]
It is not “unreliable”, it's very predictable. But yes, CodeMirror by default only parses the document partially at first since for long documents generating the table of contents can be expensive and will make the whole editor stutter.

I can have a look if I can tickle CodeMirror to give me the full Syntax Tree, but I can't guarantee it.
