### ISSUE TITLE
Implement proper markdown parsing

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#4080]
I just came across the [tree-sitter project](https://github.com/tree-sitter/tree-sitter), which implements a general framework for incremental parsing of documents/code and also has [markdown support](https://github.com/ikatyang/tree-sitter-markdown).

Being not sure about the current state, but last time I worked with the code, the parsing of most markdown elements was done using advanced regexs. I think for the overall performance and stability, having one parsed representation of the md document in memory, and then accessing this parsed rep in the different modules seems like a good idea.

Just dropping this here...

**Comment by nathanlesage** [comment]
This is precisely what's happening right now. codemirror uses its own syntax tree and it needs its own, but for the rest of the code, I've now switched to re:mark so we have one proper representation!

**Comment by tobiasdiez** [comment]
Okay perfect!
