### ISSUE TITLE
Insert footnote option missing in the latest beta

### ISSUE THREAD

**Issue by joep1977** [Zettlr/Zettlr#4083]
### Description

I am running the latest beta (3.0.0-beta.1) and I miss the 'insert footnote' option. 

### Reproducing

I miss the 'insert footnote' option. 

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.1

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by JonRoo** [comment]
I have a similar issue on Linux (Ubuntu 22.10; .deb installer; Zettlr version 3.0.0-beta.1). The button for inserting a footnote is there and is functional, but it lacks an icon:
![afbeelding](https://user-images.githubusercontent.com/68818155/214612317-88de1956-efa0-401d-9b22-ceb0f3fdd727.png)

A similar thing happens in the right-click menu when text is selected: there is no icon to mark the selected text as a comment. Additionally, the button to format text as an in-line code-block uses the icon for comment. Both buttons are functional though:
![afbeelding](https://user-images.githubusercontent.com/68818155/214612847-36c78f1b-d6a8-4ae4-9539-8403e465dd93.png)

**Comment by nathanlesage** [comment]
Yeah, I recently switched the icon library, there are apparently still some teething issues ;)

I'll get to it (as always PRs welcome, this should be a simple fix)

**Comment by nathanlesage** [comment]
Fixed that in one of the recent commits last week.
