### ISSUE TITLE
Search Speed in Slower in Current Version

### ISSUE THREAD

**Issue by passionate2023** [Zettlr/Zettlr#4085]
### Description

I have imported 500mb of text files (500 files - each of 1 mb) 

The full text search i.e content search is very slow.

### Reproducing

Search speed is slow

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I'll close this but I have on my radar that the search could be a tad faster; but it's not really a bug.
