### ISSUE TITLE
List indentation ist not working correctly in 3.0

### ISSUE THREAD

**Issue by marc-von-step** [Zettlr/Zettlr#4088]
### Description

List character changes to * after identation and inconsistent amount of indentation and unidentation.

![grafik](https://user-images.githubusercontent.com/123473839/214307966-826ba603-e785-46e5-83a3-c62e061abf29.png)

### Reproducing

1. create a list by typing `- list intem`
2. press `enter` to create a new list item item and then `tab` to indent

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
For monospaced themes this now works, for variable-width fonts I still haven't been able to properly implement that.
