### ISSUE TITLE
Tauri

### ISSUE THREAD

**Issue by chrisemke** [Zettlr/Zettlr#4090]
### Description

Have you thought about using the tauri library? it's a library made in rust that makes cross plataforms apps using JS. It's compatible with electron as i know but I don't know much of JS

### Proposed Changes

Use Tauri: https://tauri.app/

### Caveats

learning curve and migration

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Arch

**Comment by nathanlesage** [comment]
Thought about, yes. But when is absolutely impossible to say. For now, Zettlr will stay with Electron.

(Closing as this is an un-actionable issue)
