### ISSUE TITLE
Add COBOL language support to fenced code blocks

### ISSUE THREAD

**Issue by Caroline-Thies** [Zettlr/Zettlr#4095]
### Description

Hi,
this might be a slightly unusual request, but I was wondering if you could add syntax highlighting for COBOL in fenced codeblocks. I checked the documentation and it is not already supported, however it is listed in the potentially available ones: https://codemirror.net/5/mode/cobol/index.html
I'm using zettlr for university and we have a course on COBOL, so this would be really useful to me - but I recognize that I might be the only one there :D

### Proposed Changes

If I write a fenced codeblock and specify the language as cobol, like this:
```cobol
       IDENTIFICATION DIVISION.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       PROCEDURE DIVISION.
           DISPLAY "HELLO WORLD".
           STOP RUN.
```
I want the displayed text to be highlighted as cobol code.

### Caveats

None

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

XFCE Manjaro Linux

**Comment by nathanlesage** [comment]
It's also available in CodeMirror v6 (which Zettlr now uses): https://github.com/codemirror/legacy-modes/blob/main/mode/cobol.js
