### ISSUE TITLE
Clicking link does not open target

### ISSUE THREAD

**Issue by cjpoor** [Zettlr/Zettlr#41]
## Description
In Zettlr file (a) I create a link to another Zettlr file (b) using either the path or the ID.
The link turns green, confirming the path (or ID) is valid.
Clicking on the text with link, in file (a), opens the (link_path_or_ID) as text in file (a) but does not open file (b) as expected.

Using Zettlr 0.20.0 on Linux Mint 18.1

**Comment by nathanlesage** [comment]
Does opening with IDs work? Please remember that to open files by file name you'd have to put into the link brackets _only the name_, and not the extension!

Basically:

`[[file]] --> This would open file.md, FILE.MD, file.markdown, file.txt, etc ...`

If you provide the extension, Zettlr would look for "file.md.md". This is thought of as a convenience, as the extension is likely to be exactly the same for all files inside your directories, so to omit it is much more convenient.

Have a look at how files decide whether or not they are an exact match to a search term, here: https://github.com/Zettlr/Zettlr/blob/3beb5ccc97da020b1b48a256c1cfd1a146514710/source/main/zettlr-file.js#L254-L265

As you can see, they try to either match their ID, or their filename (w/o extension) against the search term.

**Comment by cjpoor** [comment]
Hi Nathan. Thanks for your quick response. 
I get the same behaviour whether I use ID, name (without extension) or path.
For example, when I am in the file "Lilburne" and I click on (cursor becomes hand) the text with link: Reformation it becomes  [Reformation](13.10.2018. 17:52) 
where 13.10.2018. 17:52 is the ID of the Zettlr file "Reformation"
but the file does not open (that is, the editor still displays the original file "Lilburne").

**Comment by nathanlesage** [comment]
Aaaaaah I think I understand what your problem is now!

Zettlr uses two different types of links: Regular Markdown links and internal links. A regular Markdown link in the form of \[link text\](www.link-target.tld) cannot link to internal files, because a Markdown parser will simply transform this to, e.g., \<a href="www.link-target.tld"\>link text\</a\>.

To link to files internally and have the option to open them, you'd need to use so-called Wiki-Links in the form of [[file-name]].

That said, to link to internal files, you'd need to use a link in this form:

[[13.10.2018. 17:52]] (although I'm interested in what RegEx you are using to make Zettlr detect _that_)

Here's an example of how my own internal links look like:

<img width="774" alt="screenshot 2018-10-14 at 14 45 37" src="https://user-images.githubusercontent.com/17251683/46916804-e9062f80-cfbf-11e8-8a7c-784806600faf.png">

Each one of the green IDs, encapsulated as internal links with two square brackets, opens the respective file if I `ALT`-click it.

**Comment by cjpoor** [comment]
Hi Nathan. Thanks for your quick response. 
I get the same behaviour whether I use ID, name (without extension) or path.
For example, when I am in the file "Lilburne" and I click on (cursor becomes hand) the text with link: Reformation it becomes  [Reformation](13.10.2018. 17:52) 
where 13.10.2018. 17:52 is the ID of the Zettlr file "Reformation"
but the file does not open (that is, the editor still displays the original file "Lilburne").

**Comment by cjpoor** [comment]
Great! That works with the name in the link. Although on my (unusual) keyboard I need to Ctrl-Alt click.
I think I was mistaking the timestamp below the filename for the ID (which needs to be generated manually). Link with ID: 20181015022308 also works. Am I correct in assuming that the ID can be placed anywhere in the file?
Thank you for your help - and thank you for developing this lovely app. I am hoping to use it to organize my notes, Zettelkasten-style.

**Comment by nathanlesage** [comment]
That's nice to hear! Thanks a lot for the compliments.

Concerning your IDs: You can in the settings choose how the ID is generated (beginning from version `0.20`) and how the ID is generated, you can customise it, if you want to. And you can then simply hit `Ctrl+L` to generate an ID automatically as a convenience.

You can place the ID anywhere in your file, only remember that the **first** ID that the regular expression recognises (by default: 14 consecutive numbers) will be assumed your ID. So as long as you don't have fourteen-digit numbers somewhere in your files, you can place the ID anywhere you want!

You can read more in the now updated settings manual and in my guide to the Zettelkasten:

- [Zettlr Settings](https://www.zettlr.com/docs/settings)
- [Zettelkasten Method](https://www.zettlr.com/docs/zkn-method)
- [Use Zettlr as a Zettelkasten system](https://www.zettlr.com/docs/guide-zettelkasten)

**Comment by a-gerescher** [comment]
Nonexisting links to another local note do not open a new note with editor opened. 
eg. `[Note about javascript](./Javascript.md)` or  `[[Javascript]]` do only work if i have the corresponding file already on my disc.
Is it possible to change this? Zettlr would be the only software i know on Windows where it is possible to do this.

Awesome software btw!

**Comment by nathanlesage** [comment]
@a-gerescher Hey, this definitely sounds nice, but it deserves its own issue! This way it's easier for all of us to keep track of what is currently being implemented, and I don't have to search for new comments on old issues! ;)
