### ISSUE TITLE
Recent documents is always empty on Linux

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4100]
### Description

Recent documents is always empty on Linux, no matter how many documents and tabs you open. I'm using the latest beta version.

### Reproducing

See above.

### Zettlr Version

Beta (if applicable)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE Tumbleweed KDE

**Comment by nathanlesage** [comment]
I was observing the same behavior on macOS, I have that on my to-do list.

**Comment by AkechiShiro** [comment]
@nathanlesage 

Could there be a [project maintained like for 2.x](
https://github.com/Zettlr/Zettlr/projects/7) ? If you don't have time to maintain the project and would like to work your way on your todo list, it's fine as well, it's just a recommendation, for people interested in contributing and for others to see what is planned and what is in stale.

**Comment by nathanlesage** [comment]
> Could there be a [project maintained like for 2.x](https://github.com/Zettlr/Zettlr/projects/7) ? If you don't have time to maintain the project and would like to work your way on your todo list, it's fine as well, it's just a recommendation, for people interested in contributing and for others to see what is planned and what is in stale.

One reason I didn't continue this is that I felt it didn't bring a benefit, because it didn't raise engagement from the community. I'm open to giving another shot, but it costs time that then isn't spent on coding.

**Comment by kyaso** [comment]
Bumping this issue, as the bug can be observed in 3.0

**Comment by nathanlesage** [comment]
I think I found it: I never added the documents to the RecentDocuments provider when they opened 🙄
