### ISSUE TITLE
Mac disk image icon and app icon are identical

### ISSUE THREAD

**Issue by matthewpaulthomas** [Zettlr/Zettlr#4101]
### Description

1. Download Zettlr for macOS.
2. Open the disk image from your browser’s list of downloads.
3. Drag the app to your Desktop instead of Applications, because you’re just trying it out for now.
4. Look at your desktop, and try to tell which is the disk image and which is the app.

What you see: Zettlr’s disk image icon and app icon are identical.

### Proposed Changes

What you should see: The icons are obviously distinct.

The simplest way of achieving this would be to stop customising the disk image icon. BBEdit and Typora, for example, use an uncustomised icon.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/19801137/215302196-cb2116d8-4d51-44ba-bc58-09c04f6e4f33.png">

### Caveats

None known.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

macOS 13.0.1

**Comment by nathanlesage** [comment]
The icon is set by Electron-Builder, which requires a custom disk image icon for us to use. I do not customize that in any way. Please research a disk image icon that we could use, then I can reference that.

**Comment by nathanlesage** [comment]
Thanks for opening up the issue over with Electron Builder. I am going to close this issue here since it's now in progress over there and Zettlr will automatically feature this change once it's released.
