### ISSUE TITLE
Citation Regex fails after single newline

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#4107]
### Description

The citation syntax @BibTexName2023 is correctly recognized almost everywhere in a document, except after a single newline.
I have attached a screenshot showing the same citation in three types of location - in a line, after a single newline, and after a double newline (a.k.a paragraph break). The inline and double newline versions are correctly recognized and rendered, but the single-newline usage is not recognized and so not rendered.

![Zettlr-citation-bug-2](https://user-images.githubusercontent.com/51254/215849926-0fc05969-3772-46f1-8a08-cddf0da29c4a.PNG)

### Reproducing

Attempt to create a citation immediately after a single newline, or open a document which contains such a citation

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Wi

**Comment by nathanlesage** [comment]
There is a chance that it's fixed in the current nightlies. I remember fixing such a bug relatively recent. (The main reason why there is not yet a new beta is because Windows on ARM has proven to be a b****)

**Comment by nathanlesage** [comment]
@efficacy Did you have the chance to test out the last nightly yet?

**Comment by efficacy** [comment]
Still fails in Nightly from 2023-02-05

**Comment by nathanlesage** [comment]
Fixed now, coming with today's nightly.
