### ISSUE TITLE
Pasting a text block containing images will be saved to temp folder instead of the configured image path

### ISSUE THREAD

**Issue by DennisL68** [Zettlr/Zettlr#4109]
### Description

When I paste a text block from Word 2019 containing one or more images, they will be saved in the user temp folder instead of the configured Editor default image path.

### Reproducing

1. Select a text block in MS Office Word containing some text and an image.
2. Copy the selection
3. Paste the clip to Zettlr
4. Notice that the file path is Temp instead of default image path

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 Enterprise LTSC

**Comment by nathanlesage** [comment]
This is expected behavior: the images are normally contained within the Word file, so to display them, Word temporarily stores them in the temp folder. In Order to retain them, you'll need to save them explicitly out of the Word file.
