### ISSUE TITLE
Zettlr won't show working directly immediately when running on Windows Server

### ISSUE THREAD

**Issue by DennisL68** [Zettlr/Zettlr#4110]
### Description

When starting Zettler on a Windows Server, it will take about a minute before any working directories are displayed.

### Reproducing

Start Zettlr on a Windows Server.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows Server 202 Standard 21H2

### Additional Information

On a Windows Server 2012 R2, the delay is a little shorter.

**Comment by nathanlesage** [comment]
I do not plan on supporting Windows server directly, as Zettlr is a client application. If it starts, that's a cool thing! But I suspect the delay is because of some file system oddities. As long as these issues do not propagate to Windows 10/11, it's nothing we can fix.
