### ISSUE TITLE
Integrate support for the VS Code plugin Front Matter CMS

### ISSUE THREAD

**Issue by DennisL68** [Zettlr/Zettlr#4112]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

[Front Matter CMS for VS Code](https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-front-matter) is an extension that adds support for Content Management to mark down documents by providing file templates and a content type configuration file consisting of what YAML Frontmatter to support and how those fields should be formatted.

### Example Workflow

When opening a `Zettlr` workspace that contains a `Front Matter` project it will be able to configure the YAML Frontmatter using the VS Code extension `Front Matter CMS`.

### Caveats

This will require a component for using/parsing VS Code Extensions or a cooperation with Elio Struyf.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

Adding CMS capability to Zettlr will make it even more useful.

**Comment by nathanlesage** [comment]
I do not plan on integrating deeply with VS Code. Supporting exports to content management systems is definitely something that's on my wish list since a long time, but not by integrating with a semi-proprietary plugin API. I'm definitely happy to discuss other alternatives, but mind you that the first step will be support for custom commands (can't search for the exact issue right now, I'm on mobile).

**Comment by DennisL68** [comment]
Both VS Code and Front Matter CMS are Open Source :)
But I see your point.

**Comment by DennisL68** [comment]
`estruyf` (the creator of Front Matter CMS Extension) would like to know i Zettlr do, or will, support extensions for codespaces such as GitHub or Gitpod.

**Comment by nathanlesage** [comment]
What will be implemented eventually is some more functionality for git itself, but I don't see any benefits of supporting GitHub yet ...?
