### ISSUE TITLE
Add support for ASCIIDOC

### ISSUE THREAD

**Issue by DennisL68** [Zettlr/Zettlr#4113]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

[AsciiDoc](https://asciidoc.org/) is a strict markdown format that has many features not supported in plain Markdown that would eliminate almost all restrictions of Markdown while still being easy to read in raw format.

### Example Workflow

Click in File - New File... and select AsciiDoc

### Caveats

A new/extended parser need to be implemented if an external module for AsciiDoc can't be used as the one used in [Antora](https://docs.antora.org/) or [Pandoc](https://pandoc.org/).

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
We've had the AsciiDoc discussion several times already. The thing is, Zettlr is a Markdown editor, and while I'm definitely not an enemy of AsciiDoc, implementing that as a supported file format is simply nothing I could implement on the fly. In general, I will remain open to the idea, but there are a lot of other issues that take precedence.

Should AsciiDoc at some point accidentally become popular among the academic community, this would certainly be one reason to think more often about that. But currently, my PhD is absolutely more important.
