### ISSUE TITLE
Ability to specify Pandoc's workdir

### ISSUE THREAD

**Issue by Amejonah1200** [Zettlr/Zettlr#4118]
### Description

When using YAML frontmatter to specify reference-doc (docx) or template (LaTex), it cannot be relative to the file or workspace.

### Proposed Changes

So we need to be able to specify the workdir of pandoc to: default, specific location, workspace, current file.
Also be able to specify `--data-dir` (for example `.` so it would take the workdir).

### Caveats

N/A

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

3.0.0 Beta.1

### Your Platform

Windows

### Operating System Version

Windows 10

### Additional Information

Putting `data-dir: .` in defaults seems to work... but why not in Frontmatter?

**Comment by nathanlesage** [comment]
> Putting data-dir: . in defaults seems to work... but why not in Frontmatter?

Some variables unfortunately only work in defaults files. But luckily, you can create multiple profiles with the upcoming 3.0!
