### ISSUE TITLE
[Feature Request] Show table of contents in the Sidebar

### ISSUE THREAD

**Issue by golfben** [Zettlr/Zettlr#412]
## Descritption
I would love to see the posibilty to show the table of contents of the current file in the sidebar. Since I navigate more often through the structure of my current file, than opening another file in the current directory, I thought this feature might come in handy.

**Comment by nathanlesage** [comment]
The only option I could think of now would be the attachments sidebar to the right (have to rename it anyway). This way you could keep the ToC visible even in Distraction Free.

**Comment by golfben** [comment]
That would be a possible solution. But personally, I would also be fine with replacing the directory sidebar on the left, making those two views switchable or even spliting the sidebar horizontally, to make both functions visible.

**Comment by nathanlesage** [comment]
This would require a deeper rewriting of the sidebar, so I'm not sure that it's implemented faster this way. Compromise: I'll do it on the attachment sidebar, and if you really don't like it there in six months from implementation, we can re-visit this issue!

**Comment by golfben** [comment]
I am okay with either way. Thanks :)

**Comment by nathanlesage** [comment]
Perfect, I'll see to it!

**Comment by yashha** [comment]
You can think of pinning the attachments/toc sidebar. Then you would be able to have both always visible. The file tree and the toc.

**Comment by nyanpasu64** [comment]
I just found this issue and was looking for a table of contents. This issue shouldn't be closed.

**Comment by fabiensc0ville** [comment]
I would totally need a TOC on the sidebar as well. 

It would so much improve navigation and overview of the document!

**Comment by nathanlesage** [comment]
Implemented!
