### ISSUE TITLE
Page preview window pop-up appears only once

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#4121]
### Description

When I hover my mouse over an internal link, a page preview window pops-up to show a summary of the start of the referenced page. However, the pop-up appears only once. Zettlr carries on and seems to be working, but hovering over a link never creates another pop-up window until Zettlr is restarted, at which point it allows just one more pop-up before failing again.

Logs shows:

`[19:46:13]
[Assets Provider] Found outdated filter links.lua; copying ...
[19:46:13]
[Assets Provider] Found outdated filter tags.lua; copying ...
[19:46:19]
[FSAL Directory] Path G:\My Drive\Notes took 5832.82800000906ms to load.
[19:46:19]
[FSAL] Path G:\My Drive\Notes took 5849ms to load.
[19:46:27]
[Application] Error received while running command: Cannot read properties of undefined (reading 'length')
[19:46:27]
[R] [Main Window (05f76703-d373-48b9-bca0-7f76ff9c317a)] CodeMirror plugin crashed: Error: fromMillis requires a numerical input, but received a undefined with value undefined (index.js:2)
[19:46:32]
[Application] Error received while running command: Cannot read properties of undefined (reading 'length')`

![zettlr-hover-bug1](https://user-images.githubusercontent.com/51254/216149522-95ee8bc7-0bb2-4c4d-a604-b3a64f532e4c.png)

![zettlr-hover-bug2](https://user-images.githubusercontent.com/51254/216149568-d63532a4-5baa-413b-86d1-27f302ec5f23.png)

### Reproducing

1. Open a document containing internal links
2. Hover over one of the links, observe the pop-up summary
3. move the pointer off the pop-up, so it disappears
4. move the pointer over another link, observe that no pop-up appears

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Ahh, looking at your screenshot reminded me that due to some weirdness in the file preview plugin it doesn't correctly find the beginning and ending of links … I'll have a look!
