### ISSUE TITLE
Error on project properties

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4129]
### Description

The project properties window does not show the current project properties. I can still change the project properties, but they are not shown when I reopen the window (so everything must be typed again).

### Reproducing

Click “Enable Project” on a directory and then “Project properties” (or however this is named in the English). Type a Project Title, close the dialog and reopen it again. The Project Title is lost.

### Zettlr Version

Nightly

### Specify version

3.0.0-beta.1 (Thu Feb 2nd, 2023 11:02:07)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

`[17:18:51] [R] [Project Properties] TypeError: Cannot read properties of undefined (reading 'profiles') (index.js:39617)` is written to the log files.

**Comment by Alexandros81** [comment]
I can confirm that the same issue happens with the AppImage version. It seems the settings are memorized, but never shown and if one of them is changed, then one have to re-set all of them.

**Comment by nathanlesage** [comment]
This has been fixed after the last beta in commit 372789f16021322635658c06f2adf7f47c77260e. I will be releasing the next beta later this week that will contain this fix.
