### ISSUE TITLE
Buggy behavior of "Search for dictionaries" in Preferences > Spellchecking

### ISSUE THREAD

**Issue by sensologica** [Zettlr/Zettlr#4131]
### Description

In Preferences > Spellchecking, there is a search bar titled "Search for dictionaries" that behaves strangely.

- If one types "us", the search surfaces "ru-RU" instead of "en-US";
- If one types "GB", the search surfaces nothing instead of the expected "en-GB";
- If one types "en", the search surfaces "en-GB", "en-US", and "fr-FR". It surfaces "fr-FR" because there is, indeed, the string "en" in the word "Fr**en**ch (France)". However, if one types "united" in hopes of finding "English (**United** Kingdom)" and/or "English (**United** States)", those results do not surface;
- If one types "eng" or "english", the search surfaces nothing, instead of "English (United Kingdom)" and/or "English (United States)".

See video below:
![zettlr_bug_search-for-dictionaries](https://user-images.githubusercontent.com/119978540/216833492-c102b23e-673f-497e-b16f-4aa4c085bc1b.gif)

### Reproducing

Try typing the strings mentioned in the description of this issue into the "Search for dictionaries" search bar to recreate the problem. Example strings: "en", "us", "fr", "united", "english".

### Zettlr Version

Nightly

### Specify version

3.0.0-beta.1+nightly-20230123

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura 13.0.1 (22A400)

**Comment by auroramylin** [comment]
I am interested in this bug. I will look at this issue and raise the PR ASAP.
