### ISSUE TITLE
Mermaid syntax error messages accumulate and pollute the sidebar

### ISSUE THREAD

**Issue by tillgrallert** [Zettlr/Zettlr#4132]
### Description

I recently began adding mermaid diagrams to markdown files and was pleasantly surprised to see Zettlr automatically rendering them. However, writing diagrams I will inevitable make some syntax errors and somehow these error messages are rendered in the left sidebar underneath the folder structure in my workspace. In addition, the error messages accumulate one below the other.

![Screenshot showing the error messages in the sidebar on the left](https://user-images.githubusercontent.com/5872574/217091449-78d5d2d7-4ccd-47af-ac83-e49bc8239ee2.png)

### Reproducing

Add a basic mermaid diagram such as this:

```mermaid
---
title: something
---

flowchart LR
    %% nodes
    software[Software]
    method(Methods)
    theory(Theories)

    %% edges
    theory -->|informs| method
    method -->|is implemented\nby| software
```

Zettlr's implementation, unlike Github's, does not support the YAML block at the beginning and will cause an error message.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura 13.1

**Comment by nathanlesage** [comment]
So, first, I am happy to announce that apparently Titles are also supported by Zettlr now. (I'm pretty sure that happened automatically with some update in the past). Furthermore, if I force errors to appear, they don't end up in the body element anymore, and aren't visible on the sidebar therefore.
