### ISSUE TITLE
Show the file title when creating internal links

### ISSUE THREAD

**Issue by avakslo** [Zettlr/Zettlr#4134]
### Description

When creating a link in the editor only the file name is shown, and not the title as given in the YAML-frontmatter and shown on dropdown menue. See image. 
![Skjermbilete (1)](https://user-images.githubusercontent.com/118901229/217102988-23ad7ab3-3199-4ede-bba5-345fbad39a66.png)

The title, along with ID, is visible in the dropdown. 

### Reproducing

Use YAML-frontmatter snippet, 

Link to another file with title. 

### Zettlr Version

Nightly

### Specify version

beta 3.0.0 + nightlie Mon Feb 6th, 2023 

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This is as intended, this is not a bug. We can, however, most certainly add the title as an additional piece of information.

**Comment by avakslo** [comment]
Okay! I see. I may have explained the issue really badly, so just to double- check:

What I mean is that the file-name the (long unreadable combination of letters) isn't rendered into the legible title from the YAML frontmatter. Like in the following where there is the file ID in square brackets followed by the what I entered in the title. In this case Notat - Peppermø

![image](https://user-images.githubusercontent.com/118901229/217316232-00679289-b78e-431b-ab96-67660d9c0743.png)

**Comment by exanrauzer** [comment]
Yeah, twisted explanation! So you mean that after ID you got that white text when you create a link:

![image](https://user-images.githubusercontent.com/103963891/217350660-ed39453a-b47f-4f0f-b635-c782df596b24.png)

**Comment by avakslo** [comment]
Yes, that's what I mean! Sorry for the twistedness (trying to be precise just made it worse)

**Comment by pnbrm** [comment]
To me this appears to be a bug within the beta 3.0.0. In 2.3.0 it works as expected: When creating an internal link, the respective title as defined in the YAML-frontmatter is automatically placed after the brackets.

**Comment by avakslo** [comment]
Okay. Thank you for looking into it. Then I have an option of using the 2.3.0 until the 3.0.0 is fixed with respect to this bug. 

I'll leave it up to you to decide whether this issue  should be closed. Thanks again!
