### ISSUE TITLE
Spellcheck disrupts highlighted text upon right-click

### ISSUE THREAD

**Issue by bwprog** [Zettlr/Zettlr#4145]
### Description

Non-critical bug. If you have text not within a code block, the spellcheck will underline anything it finds wrong. If you highlight multiple words or commands and then right-click over the properly spelt highlight section, it works as expected. 
![Zettlr Highlight](https://user-images.githubusercontent.com/124224572/218622068-4d36b016-770c-4d06-9e74-8b5f6e12f288.png)
![zettlr right-click spelled right](https://user-images.githubusercontent.com/124224572/218622210-bd4c613c-9c49-4d90-82f4-827f72471bbf.png)
If you right-click over the misspelt word, the highlighted section will shrink to just the misspelt word. Copy from the menu will only copy the newly shortened highlighted text instead of the intended full highlighted text.
![zettlr right-click spelled wrong](https://user-images.githubusercontent.com/124224572/218622287-176dd68c-50bc-463a-8afe-d84a47f825fd.png)

### Reproducing

As shown in the description:
1) write a sentence or phrase that includes both properly spelt and misspelt words.
2) highlight the whole section.
3) right-click on the misspelt word and notice the highlighted section shrinks to just the misspelt word.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSuse Tumbleweed | KDE Plasma | Wayland

### Additional Information

Application: Zettlr-3.0.0-beta.2-x86_64.AppImage
Command-Line Arguments: --enable-features=UseOzonePlatform --ozone-platform=wayland

**Comment by nathanlesage** [comment]
This is desired behavior. In general, Zettlr overwrites selections according to the following rules upon right-click:

1. If there is no selection, it will select the word under the cursor (“word” here being defined by the CodeMirror library, specifically, [this function](https://codemirror.net/docs/ref/#state.EditorState.wordAt))
2. If there is a selection, Zettlr will generally not attempt to overwrite that, except for a few defined cases. One of them is when you have a context menu over a misspelled word. The reason Zettlr overwrites the selection here and forces you to apply a spelling correction to a defined range is that the suggestions would make no sense if more (or less) than the actual misspelled word is selected. There is the chance that a user selects a whole paragraph accidentally, clicks on a suggestion, and would see their entire section being deleted.

What you describe here is an edge case, where I choose to favor “regular” users that normally do not run into this specific problem you are describing here; and I think that the tradeoffs for you are reasonable, and not too harsh.
