### ISSUE TITLE
Sidebar gets stuck after following a link

### ISSUE THREAD

**Issue by mlevison** [Zettlr/Zettlr#415]
My sidebar only displays two notes when I have 9 or 10.

Start in note one. Click on a link to jump to another note. Now the sidebar only displays two notes the one I came from and the one I navigated to. 

Nor can I find a way back short of quitting the application

?? I don't know ?? If this is a feature may the rest of the list should appear below in the sidebar but greyed out.

Original state:

![Zettlr_2019-11-27_17-31-14](https://user-images.githubusercontent.com/140902/69763925-b58f5180-113c-11ea-826e-df2076e48bd6.png)

Defect:
![Zettlr_2019-Sidebarbug](https://user-images.githubusercontent.com/140902/69763935-bf18b980-113c-11ea-9d44-62632b0efc03.png)

## Platform
 - OS: Windows 10
 - OS Version 10.0.18362
 - Zettlr Version 1.5 Beta (also a problem with 1.4.3)

**Comment by nathanlesage** [comment]
This is perfectly valid. What is happening? When you follow a link, Zettlr will automatically start a search for all notes that contain said link, that is: Either the ID of the file, or its filename. This is useful if you want to only navigate within clusters of notes.

To exit the search, either click the `x` in the global search field, or hit `Ctrl+Shift+F` and then `Esc`.

_P.S.: This means you can even "misuse" links to save searches. Simply surround the search query with square brackets, and whenever you click them, Zettlr will start this search._
