### ISSUE TITLE
[3.0 beta] Can't create new file from Zettlr

### ISSUE THREAD

**Issue by pagiraud** [Zettlr/Zettlr#4150]
### Description

Hi,

I noticed this annoying bug since the first beta release of the 3.0 but I thought it was a common one and that it would be fixed in subsequent releases. Since it's not the case, I checked from the issues (open and closed) and didn't see anything that seemed related. Please excuse me if I didn't find the relevant issue.

The bug is simple: you can't create a new file from Zettlr. If you try to do so, nothing happens: the new file window closes, no tab is opened, no file is created.

### Reproducing

1. Go to File > New file > Markdown or press ctrl+N
2. Select a directory and enter a file name (or leave the default one)
3. Press Enter or click Save

### Zettlr Version

Beta (if applicable)

### Specify version

3.0 beta 2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 22.10

### Additional Information

I encounter another bug. I think they are somehow related but I will create another issue.

I don't know if it's of any matter, but I install from the . deb file.

**Comment by dm5n** [comment]
Confirming this occurs also on macOS x64 build.

**Comment by nathanlesage** [comment]
to be more specific: If you create a new file and navigate into a directory that is loaded in Zettlr, it will create that file just fine. It's just that it refuses to do so in a directory not loaded in Zettlr. It's an old remnant of back in the days when everything needed to be contained.

**Comment by yansh** [comment]
I am experiencing a similar issue with Zettlr 3.0 on Mac OS 14 x64. 

When I am attempting to create a new file, Zettlr becomes responsive.

Creating a file outside Zettr and opening it with Zettr works fine.
