### ISSUE TITLE
[3.0 beta 2] Can't open file from file browser if Zettlr is not already open

### ISSUE THREAD

**Issue by pagiraud** [Zettlr/Zettlr#4151]
### Description

On my system, I associated the .md files to Zettlr, so that a click on it opens them in Zettlr. It works nicely if Zettlr is already open but if not, it opens Zettlr in its previous state (ie same opened tabs) without loading the file. Thus, I have to click again on the file to open it in Zettlr.

### Reproducing

Well, just click (or double-click, depending on your configuration) the icon of the file.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0 beta 2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 22.10

### Additional Information

I use Dolphin as a file browser. I installed the app from the .deb file.

**Comment by Himra** [comment]
The same behavior also with Win10 64bit

**Comment by nathanlesage** [comment]
Can't reproduce on macOS, here it works perfectly fine. There could be implementation differences in the 'open-file' (macOS) event and the 'on-second-instance' (Windows/Linux) events that happen.

**Comment by dadams-AU** [comment]
I can confirm the same issue on my Linux Ubuntu. Beta 2 Version, ARM 64: it requires the second instance. I can't reproduce this on my macOS.

**Comment by nathanlesage** [comment]
I double-checked the code: It could be that the `extractFilesFromArgv` function is somehow misbehaving…? At least this would be the easiest explanation … can anyone who has set up Zettlr in a dev pipeline do a quick check of that on either Windows or Linux?

**Comment by nathanlesage** [comment]
Argh, I'm an idiot, I forgot the "if Zettlr is not already open" part … fixed!
