### ISSUE TITLE
Setext-style headings lose initial characters in table of contents

### ISSUE THREAD

**Issue by cbaile19** [Zettlr/Zettlr#4161]
### Description

When Setext-style headings are listed in the table of contents, they lose characters at the beginning.

Example: 

     Example Heading
     ============

is listed as “1 ample Heading.”

This does not happen with ATX headings:

     # Example Heading

is listed correctly as “1 Example Heading.”

![Zettlr-Setext-headings-in-table-of-contents](https://user-images.githubusercontent.com/125898339/220146585-069388d1-0a77-4246-8683-526a4e622500.gif)

### Reproducing

As far as I can tell, it always happens with Setext headings.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.2

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 Home version 10.0.22621

**Comment by nathanlesage** [comment]
I've fixed this basically just after I've released that beta! Coming soon!
