### ISSUE TITLE
Text edit bubble/pop-up placed over selected text

### ISSUE THREAD

**Issue by jelkejelke** [Zettlr/Zettlr#4165]
### Description

In some cases when I select text in Zettlr, the pop-up bubble that allows to make the selected text bold/italic/add a link etc is placed over the selected text. See screenshots for what this looks like (just to be sure: the selected text is invisible). 

![Screenshot 2023-02-21 at 14 39 22](https://user-images.githubusercontent.com/61508639/220362281-36a2d220-d7f0-49b3-b5dd-14e11101d1a7.png)
![Screenshot 2023-02-21 at 11 20 45](https://user-images.githubusercontent.com/61508639/220362288-0fed205b-93d3-4570-9e27-3f321241f3de.png)

### Reproducing

This happens about 5% of the times I select text, but I'm unable to figure out why/when it happens. 

### Zettlr Version

Stable (most recent version)

### Specify version

Version 2.3.0 (2.3.0)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ventura 13.1 (22C65)

### Additional Information

If you can tell me where to look, I'd be happy to try to find out in developer mode what happens exactly when this issues occurs.

**Comment by jelkejelke** [comment]
I just figured out that whether the bubble is placed over the selected text depends on where the text is relatively located on my screen: if I scroll up or down, the bubble moves relative to the selected text: 
![Screenshot 2023-02-21 at 15 25 06](https://user-images.githubusercontent.com/61508639/220371723-2b2394d5-2737-4521-ad00-369f5c7fcf15.png) 
This is what the text looks like when it's at the top of the window. 

![Screenshot 2023-02-21 at 15 25 12](https://user-images.githubusercontent.com/61508639/220371729-29458912-d488-442f-82c9-b5318164cb29.png)
... and this is what it looks like when I scroll up (and the text moves to the bottom of the screen). 

Strangely enough, I'm not always able to reproduce this issue, even with the same snippet of text. (Perhaps this has something to do with me scrolling manually or the text scrolling over the screen as I write?)

**Comment by nathanlesage** [comment]
This was indeed an annoying problem, and one I suffered from myself as well. Luckily, in the current betas, this problem has evaporated!
