### ISSUE TITLE
Zettlr crashes immediately on old MacOS

### ISSUE THREAD

**Issue by aisavnin** [Zettlr/Zettlr#4172]
### Description

Zettlr crashes immeditely
Log, if started in command line:
/Applications/MacPorts/Zettlr.app/Contents/MacOS/Zettlr -vvvv
[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /Applications/MacPorts/Zettlr.app/Contents/Resources/pandoc
[Application] Environment check complete.
[73726:0225/172520.531124:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Trace/BPT trap: 5

### Reproducing

Just start from command line or by clicking

### Zettlr Version

Stable (most recent version)

### Installation Method

Mac Ports

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS 10.13.6

### Additional Information

Are there any command line options, to turn of something "unnesessary"?
Or maybe recompile older version?

**Comment by nathanlesage** [comment]
As you yourself note, you are running an older macOS. As stated in the documentation, Zettlr requires at least macOS 11.6 (see https://docs.zettlr.com/en/install/#macos-1160-or-newer).
