### ISSUE TITLE
Does not correctly calculate tab width on startup

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#4174]
### Description

It is possible to get Zettlr into a state where the tab bar is full, and possibly overfull, but does not show the < and > sideways scroll arrows. It looks like this is because it is not calculating the width of the tabs correctly

### Reproducing

1. Open Zettlr on a workspace with plenty of documents
2. Open enough documents to fill the tab bar and show the < and > scrolling arrows in the tab bar
3. Exit Zettlr
4. Open Zettlr again
5. Note that the previously open tabs are open again, but that the < and > scrolling arrows are not present

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0b2

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by efficacy** [comment]
Note that resizing the window seems to detect the situation correctly and add the scroll arrows as needed

**Comment by nathanlesage** [comment]
I think I got it! Should come with tomorrow's nightly.
