### ISSUE TITLE
[3.0 beta] Documents tab bar is slightly scrollable

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#4178]
### Description

The documents tab bar is scrollable, as the following screen capture shows:

https://user-images.githubusercontent.com/18646029/221690837-064e8260-1599-4047-a7b5-53fb344851aa.mp4

### Reproducing

1. Hover over the documents tabs
2. Scroll with mouse wheel up and down
3. Observe the tabs scrolling slightly (as shown in the screen capture)

---

Not sure if the height of the tab bar gets affected by the file names, but just in case, here are the file names I was using for the screen capture above:
- .README.md
- §-comp-arch-index.md
- §-riscv-index.md
- What is Computer Architecture.md
- Microarchitecture Design Principles.md
- endianness.md

### Zettlr Version

Right off the develop branch

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

### Additional Information

I didn't notice this behavior in 2.3

**Comment by nathanlesage** [comment]
That smells suspiciously like a one-pixel-too-high-tab in the Linux CSS rules. Feel free to investigate that, I don't have too much time over the coming two weeks (3 presentations in 3 countries)

**Comment by nathanlesage** [comment]
Does this still happen?

**Comment by exanrauzer** [comment]
Not affected with $ or dot in file name. Win 10, beta5.
