### ISSUE TITLE
Snippet preview obscures the list of snippets to select from

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#4181]
### Description

I currently have four snippets defined, but when I try to insert one by typing a colon I can't see the list to choose from, because it is obscured by a preview window of the first snippet in the list.

![snippet-menu](https://user-images.githubusercontent.com/51254/221881931-6b6c6e19-a6bd-4602-bb37-7844f54fa9e7.png)

This is made particularly annoying by the way that letters following the colon are treated. rather than matching the actual sequence of letters typed against the snippet name, it seems to be treating the letters in the name of the snippet as a set, and matching any which contain all the entered characters, wherever they are in the name.

As a concrete example, I currently have four snippets: **concept**, **paper**, **project** and **person** ( see https://discord.com/channels/609436111860793355/924313423947399168/1079477675170726028  for the background). When I type a colon, a menu with all four names appears (obscured by the preview, as above), I can reduce that list by typing characters.

Imagine I want to use the snippet for a person:
- type 'p' does nothing, as all names have a 'p'
- type 'e' does nothing, as all names have a 'p' and an 'e'
- type 'r' eliminates _concept_, but the other three are still there.
- type 's' and finally there is only one, so I can type enter to accept it.

I realise that I could just go direct to the 's' in this case, but if I were to have another snippet which had all the letters of **person**, say **response**, then I would never be able to reduce the list to just one item. This system really needs to prioritise matching the actual sequence of characters typed, particularly if they appear at the start of a snippet name.

The combination of the visual UI being obscured and the keyboard UI operating in a non-intuitive manner makes snippets much harder to use than the should be.

The bad positioning of the preview is certainly a bug, but if that is fixed, then the problems with the keyboard UI are less severe, so could probably be downgraded to a feature request

### Reproducing

1. ensure you have at least three snippets defined, preferably using a mixture of the same characters. For the most repeatable results use the four (or five) names given above
2. create a new file
3. type a colon
4. observer that the snippet list is obscured by the preview
5. type some further characters and try to guess which snippets have been selected
6. type enter and see if you were correct!

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0b2

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
> In this example I am clearly typing person but paper is still at the top of the list

That surprises me, it should already do that correctly o.O I'll have another look at that.

> It doesn't even include the line breaks.

Yes, this I wanted to get to myself as well, but … well, too much work :D And it's not completely unusable, so I deprioritized that a little bit.

In general, my idea was to keep a relatively long beta phase and not rush anything, to arrive at an actually super nice release, rather than what we had in the past where I basically published a new release and a day later or so had to already release a hotfix because something broke.

**Comment by efficacy** [comment]
> In general, my idea was to keep a relatively long beta phase and not rush anything, to arrive at an actually super nice release, rather than what we had in the past where I basically published a new release and a day later or so had to already release a hotfix because something broke.

That makes a lot of sense. After all, we are not really in the crazy world of startups and time-to-market here. but in academia where the clock only ticks once per year ;)

**Comment by nathanlesage** [comment]
I think this works now in the current dev branch — if you really make the window insanely small, it still happens, but then at least it has a reason: space constraints. As long as the window is reasonably large, it won't happen anymore.
