### ISSUE TITLE
Zettlr has some problems with tag recognition

### ISSUE THREAD

**Issue by GwokHiujin** [Zettlr/Zettlr#4187]
### Description

1. Zettlr sometimes fails to correctly read the tag in the YAML Frontmatter and display it in the workspace, as shown in the following image. I tried restarting the software several times but it did not solve the problem, the only way to fix this is if I retype the tag again —— The files with the error are ones I have previously written in other Markdown editors, files that I created and wrote in Zettlr do not have this problem. Can it be fixed?

![image](https://user-images.githubusercontent.com/70586936/222721799-21d35e3b-a3ab-49f4-8bc7-d9fe6541e939.png)

2. I know that Zettlr can recognize tags in the form of `#tag`, but this causes similarly formatted text in code blocks (e.g. `#include`, `#define` in C programs) to be incorrectly recognized as tags and displayed in the tag system, as shown below. I hope this problem can be solved.

![image](https://user-images.githubusercontent.com/70586936/222722665-61861cfc-08d4-4bad-9039-8c860971a056.png)

### Reproducing

1. For issue 1, the problem does not occur if you create a new file in Zettlr and write the tag in YAML Frontmatter, but it may be reproduced if you open a local Markdown file in Zettlr (which has the tag information filled in YAML Frontmatter but was previously written in another Markdown editor).
2. For issue 2, the problem can be reproduced by editing a codeBlock in the Markdown file that contains a keyword like `#include` .

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
These bugs have luckily been found and fixed for the current 3.0 betas. I invite you to switch to the beta which does not have these bugs.

**Comment by GwokHiujin** [comment]
> 

Thank you for replying this! 😊I'm really looking forward to the next stable release and hope Zettlr gets better and better!
