### ISSUE TITLE
[3.0 beta] Contents of tabs mix up when switching using back/forward buttons

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#4188]
### Description

When switching between two tabs using the back/forward navigation buttons, one of the tabs will start showing the content of the other tab. See the following screen recording:

https://user-images.githubusercontent.com/18646029/222988380-08200bd3-a012-4017-b961-4b23a867ad19.mp4

When I edit (& save) "test1", the changes are _not_ reflected in the broken "test2" tab.

### Reproducing

1. Open two tabs
2. Switch between the two tabs using back/forward buttons (as shown in the screen recording above)

### Zettlr Version

Right off the develop branch

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by kyaso** [comment]
Might be related (or even duplicate) of #4168

**Comment by nathanlesage** [comment]
Yes, that looks like a duplicate, but what you provide here is another valuable insight which furthers that my initial suspicion was right. I'll have to re-work the whole document loading process to make it more resilient. Let's add the info from here to the other issue to concentrate our efforts.
