### ISSUE TITLE
Asciidoc format

### ISSUE THREAD

**Issue by genofire** [Zettlr/Zettlr#4193]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Asciidoc is already optimisied for writing Text and has no flawor (like Markdown with github).

See: https://asciidoc.org/

### Example Workflow

Support adoc files

### Caveats

Support asciidoc

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
@ailintom Thank you for researching the previous issues that we had in this regard!

Closing with the same reason – maybe for a future update! :)

**Comment by genofire** [comment]
ups,sorry have not seen/found this issues.
