### ISSUE TITLE
Importing ODT file does not work

### ISSUE THREAD

**Issue by AdelleBernal** [Zettlr/Zettlr#4194]
### Description

I try `File > Import Files > myfile.odt` but Zettlr does nothing.

### Reproducing

`File > Import Files > myfile.odt`

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Catalina

**Comment by nathanlesage** [comment]
Importing ODT-files in the current nightlies works. You have two options: You can either try out the most recent beta version, where it will work, or wait for the 3.0 to be released later this year, if you prefer stable versions.
