### ISSUE TITLE
[Feature Request] Keyboard Shortcut to copy current note ID

### ISSUE THREAD

**Issue by mleo2003** [Zettlr/Zettlr#421]
## Description

I would like to have a keyboard shortcut to activate the "Copy ID" function for the currently selected Note.

I have Zettlr setup to create new notes without prompting me, which creates a file with just a Zettel ID as the filename. I then either paste in content, or start typing the note as I think of things. When I am ready to call the note "done", I like to make the first line of the file match the filename, and vice-versa. So, currently I will find the Note in the File Menu on the left, Right Click it and Select "Copy ID". Then, I go back into the Note Editor part, paste the ID as part of the First line of the file. I then use the "Copy whole line with no selection" feature to copy that line, use the Shortcut to "Rename Current File", Paste the First Line as the new filename (Zettlr automatically adds the file extension back), and everything is set.

This works ok for now, as I make sure to create new notes in an Inbox folder that I keep relatively clean, so finding the notes there to right-click on is easy enough. But, I would like to stop using such a folder, and at that point, having so many files on the left-hand side makes right-clicking the new note not as easy (can sort to fix that, but then that messes up any other sorting I need for other reasons). A new keyboard shortcut for the current Note ID would keep my fingers typing/moving instead of having to stop and use the mouse for that "finalization" step.

I'm open to a different workflow for doing similar things, if someone knows of a better way to accomplish this. I just am not sure how else to go about this, except external scripts that try to keep the first line and filename in sync automatically for me, and then just ignoring the original ID upon file creation (which I might just go with something like it, or just using the New ID shortcut in the title and ignoring the ID it was created with).

**Comment by nathanlesage** [comment]
Another shortcut should not be the problem — just choose one that works for all platforms, or two that work for all: https://zettlr.com/shortcuts

**Comment by mleo2003** [comment]
Only one I could think of that was free and made a little since, was Control/Command+Shift+L. Contrl/Command+L already inserts a brand new ID, so having the same thing with Shift either copy (or just paste) the current note ID seemed to follow along nicely.

**Comment by nathanlesage** [comment]
Good thinking! Then I'll keep this on my bucketlist!

**Comment by Zverik** [comment]
Let's keep this: a shortcut shouldn't be hard to add, and this is useful to some.

**Comment by nathanlesage** [comment]
> Only one I could think of that was free and made a little since, was Control/Command+Shift+L. Contrl/Command+L already inserts a brand new ID, so having the same thing with Shift either copy (or just paste) the current note ID seemed to follow along nicely.

Anyone against this? Respond until Sunday and then I'll implement.

**Comment by nathanlesage** [comment]
Closing in favor of newer central issue for all of these small shortcut requests
