### ISSUE TITLE
Remove mention of the Arch Linux AUR

### ISSUE THREAD

**Issue by UweKrause** [Zettlr/Zettlr#4218]
The Zettlr documentation sometimes references to the Arch Linux User Repository (AUR). Zettlr got promoted (I don't know when) from an AUR package to a "regular" Arch Linux package. As regular packages are way more convenient and more trustworthy, it is better to remove the not longer valid mention of AUR and just link to the current (better) state.

I have seen two (no longer valid) mentions of the AUR:
* in the readme
  * See #4217 
* on the [website](https://zettlr.com/download)
  * 404 to the AUR
  * I was not able to locate the code for the website and make a PR. Therefore this issue.

The [documentation](https://docs.zettlr.com/en/install/#arch-linux) ([German](https://docs.zettlr.com/de/install/#arch-linux) also) links to the Arch Linux Wiki entry for [Zettlr](https://wiki.archlinux.org/title/Zettlr). This is a good thing.
The documentation of the other languages don't mention Arch Linux or the AUR (which would maybe a thing for another issue)

The correct link target for the Arch package is: `https://archlinux.org/packages/community/x86_64/zettlr/`.

Sometimes it has its advantages to link to the package search: `https://archlinux.org/packages/?name=zettlr`.
This is the way the Zettlr documentation currently links to the package. I don't see any problem with this.

The correct link target for the Arch Wiki is: `https://wiki.archlinux.org/title/Zettlr`.

Maybe you want to consistently link to the package, the package search or the wiki.
If so, I think the wiki would be the best link target.

**Comment by nathanlesage** [comment]
Thanks for mentioning this. I never fully understood what I should be linking, but I think you have a valid point with your Wiki article.

I have now linked the website to the Wiki article and merged your PR. I think this is the best way as it (a) shows users who may want to install it from source the `zettlr-git` link, and it also looks a tad better than the search.

Thanks again!
