### ISSUE TITLE
File becomes unsavable after renaming

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#4227]
### Description

Files can become un-saveable after renaming. The way to mitigate is only to copy the contents with any modifications out of the file, restart Zettlr, and then paste them in the file again.

CC @efficacy @wideaperture

### Reproducing

1. Open some new file in Zettlr
2. Rename it while it is open
3. Observe that the tab doesn't show the "modified"-indicator afterwards

### Zettlr Version

Right off the develop branch

### Specify version

git HEAD

### Installation Method

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

macOS Ventura 13.2.1

### Additional Information

PR #4215 unfortunately has the same problem (and a ton more).

**Comment by wideaperture** [comment]
Thank you for the heads up, @nathanlesage! Perhaps I could file this separately as a feature request, but it seems to make sense in the context of the auto-save bug, but might it be possible to have some sort of more visible warning when auto-save stops working? For example, a narrow red banner with a warning message that appears at the top of the screen. I get that the ideal is to _fix_ any auto-save bugs, but a more attention-grabbing warning system for moments when data is at risk seems like a good redundancy to have.

**Comment by nathanlesage** [comment]
I've outlined why I think that might be nonsensical in your issue – I hope it makes sense!

**Comment by nathanlesage** [comment]
UPDATE to PR #4215: I just double checked, there was a different error, it works like a charm there.
