### ISSUE TITLE
Markup-checker formatting suggestions conflict with Zettlr's default formatting

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#4228]
### Description

When I select and italicize text using `Ctrl-i` or the italicize button, Zettlr inserts underscores on either side of the highlighted passage, as it always has. However, in version 3, this also causes a formatting suggestion to pop up (a yellow triangle in the left-hand margin of the document), which states "Emphasis should use `*` as a marker."

Underscores and asterisks are obviously both acceptable ways to italicize text in different variants of markdown, and Zettlr accepts either choice. If Zettlr accepts both, then the formatting suggestion shouldn't flag the underscores as a problem — especially when the software inserts this version of the markup by default.

### Reproducing

Select text in a buffer and italicize it using either `Ctrl-i` or the italicize button.

Watch the yellow warning triangle appear afterward in the left-hand margin beside the paragraph.

Mouse over the warning triangle to see the conflicting error message.

### Zettlr Version

Nightly

### Specify version

3.0.0-beta.2.nightly

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro (Rolling)

**Comment by nathanlesage** [comment]
This was definitely annoying behavior, but I managed to finally fix that in this commit: https://github.com/Zettlr/Zettlr/commit/780c8883d7d57e5c02e603f52e7a7fb704489001

Now, the Markdown linter should only complain when you're using emphasis markers that you didn't set as default! I think it's not yet in the nightlies, but will come with the next one!
