### ISSUE TITLE
Feature Request: Add two digit year

### ISSUE THREAD

**Issue by asteres** [Zettlr/Zettlr#423]
My current datetime stamp for notes uses a two digit year which I can't bring over to Zettlr. I understand this is done to make the date more unique but I don't plan to use Zettlr for 100+ years. I looked into the code to add this feature and will submit a matching pull request. 
ed1eb3087f31155a44a54594db5c9a14585709db

**Comment by nathanlesage** [comment]
I've already answered your PR, looks good apart from one small detail!

**Comment by nathanlesage** [comment]
Btw I'll close this one as we can discuss on the PR directly

**Comment by Jos512** [comment]
Can this issue be reopened? I see the PR fell through but I'd also like to use a two digit year. (I can also open a new GitHub issue for that, if preferred.) :slightly_smiling_face:

**Comment by nathanlesage** [comment]
Yeah, no one answered on the PR, so I closed it due to inactivity 🤷🏼‍♂️

2-digit years can be made, but it has not that high of a priority right now due to the FSAL refactor, I wanna get this finished by the end of the week

**Comment by Jos512** [comment]
Totally fine by me! :+1:  I should have perhaps clarified that it's a 'nice to have feature'. So nothing critical, essential, or required.
