### ISSUE TITLE
Inconsistency between file and what's shown in Zettlr

### ISSUE THREAD

**Issue by a12l** [Zettlr/Zettlr#4234]
### Description

The content of the file

```console
$ cat a7d87806-ac43-490b-8ab6-a995413f3ea7.md
# Symbols with special meaning inside the Zettelkästen

| Symbol | Unicode | Name   | Used fro        |
|--------|---------|--------|-----------------|
| •      | U+2022  | Bullet | Structure notes |
```

doesn't match what's shown in Zettlr displaying that file (no unsaved changes)

![2023-03-31_19-24](https://user-images.githubusercontent.com/38804798/229291696-f85266bb-b1da-49c6-a427-55caa64e8a62.png)

(it's the heading for the fourth column in the table)

I think I corrected this in Zettlr, but the change wasn't written to disk. The content of the file on disk was shown in Zettlr after I changed to another file in Zettlr and then changed back. After correcting the error again in Zettlr and saved the correction was written to disk.

### Reproducing

Haven't tried to reproduce it yet. I'll write when I've tried (I guess it isn't trivial to find a way to reliable reproduce this).

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

NixOS 22.11

### Additional Information

My workspace directory is located on a ZFS file system.

**Comment by nathanlesage** [comment]
This has been improved in the current 3.0 branch to be transparent about when the table's contents are actually reflected in the file.
