### ISSUE TITLE
Beta version in Flatpak

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4236]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

It would be great if Zettlr beta is also available in Flatpak. Flatpak is gaining more popularity in the recent years.

### Example Workflow

N/A

### Caveats

N/A

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
I can't move this issue, unfortunately, so we'll have to manually do this: please direct this request against the flat pack repository instead of here: https://github.com/flathub/com.zettlr.Zettlr
