### ISSUE TITLE
No exports working at all, help I'm mid dissertation.

### ISSUE THREAD

**Issue by clarkie1977** [Zettlr/Zettlr#425]
Hi there, sorry to be so "urgent" but I'm in a bit of a panic. No exports from Zettler are working for me. I get the following error message:

**Export failed**

An error occurred on export: Command failed: pandoc Narf'foldersf35fr977p0511756nbsn870qmszOOOOgn/Tz’exporttmp -f markdown -t html ‐‐template=/var/fo|ders/35fr977p051175onbsn870qmszOOOOgn/T/templatetpl ‐‐fi|ter pandoc-citeproc –bib|iography /Usersfrichardclark/Documents/Reference Management/My BibTex Files/Better CSL JSON (Zettlr).json ‐-cs| fUsersfrichardclark/DocumentsfReference Management/Cite Styles/harvard‐coventry-universitycsl –pdf-engine=xelatex -o Nar/folders/3s1r977p0511756nbsn870qmwz80000gn/T/Test Spacehtml pandoc‐citeproc: Error in $: Incompatible API versions: encoded with [1,175.4] but attempted to decode with [1,20]. CaIIStack (from HasCallStack): error, called at ./Textf’Pandocz’JSON.hs:112:48 in pandoc-types‐1.20‐KTt4MbZ4an3N9yUroj60X:Text.Pandoc.JSON Error running filter pandoc‐citeproc: Filter returned error status 1

pandoc-citeproc: E r r o r in $: Incompatible API versions: encoded with [1,17,5,4] but attempted to decode with [1,29]. CallStack (from HasCallStack): error, called at ./Text/Pandoc/JSON.hs:112:48 in pandoc-types-i.20-KTt4MbZ4an3N9yUroj60x:Text.Pandoc.JSON Errorrunningfilter pandoc-citeproc: Filter returned error status 1

![Screenshot 2019-12-02 at 19 54 59](https://user-images.githubusercontent.com/50876078/69996218-85372100-1549-11ea-8f55-dd43a0cb5fa5.png)

Any advice will be very welcome! Thanks for such an awesome app.

**Comment by nathanlesage** [comment]
Huh, interesting error — Google didn't yield many helpful results for this one. But what I would like you to check prior is whether or not both pandoc and citeproc are the newest versions — as the two are distinct programs, it might be that one of them is outdated and the other one doesn't work with it anymore.

(Context: In the debian package repositories, there's still a pandoc `1.x`, although we're already at `2.x`, which leads to errors often)

Another possibility, which I just discovered, means that probably there's a unicode character in one of your markdown files which might cause problems. One Google result told me that apparently, in this case, encoding/decoding might refer to different character sets used during writing as opposed to during export.

Do exports on fresh Markdown documents with just some English tet work?

**Comment by clarkie1977** [comment]
Hi Hendrik,

Thank you for getting back to me about this. I am no programmer, asides some HTML & CSS from ten years ago, I don't know any code etc. I am quite systems minded so I have tried many of these suggestions (if I understand them correctly).

I have fully uninstalled and re-installed Zettlr, I have reinstalled Pandoc & Citeproc using Home-brew also I have reinstalled MacTex. 

I have export available for some formats, but PDF nothing and I will include the new error messages below. Furthermore with RTF I only get an export of what is on the top line of text.

I have tried different documents to export to PDF, from different MD files to ones from a project and normal PDF export. None seem to work.



I am sorry to ask for help and any is very much appreciated. I am trying to get this fixed for my MSc dissertation. I am firefighter and working on the Grenfell disaster, it is very testing of ones self.

Thanks again,

Kind regards,

Rich. 


iCloud
Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by clarkie1977** [comment]
![Screenshot 2019-12-03 at 10 53 06](https://user-images.githubusercontent.com/50876078/70046904-dcc3a400-15be-11ea-8783-0abe1e04d3d8.png)

**Comment by nathanlesage** [comment]
Hey, thanks for sharing the error message! When LaTeX reports that a certain environment is not defined, this mostly indicates that you need to pull in a specific package.

See this link for explanations on why this happens: https://www.overleaf.com/learn/latex/Errors/LaTeX_Error:_Environment_XXX_undefined

I have just had a short google search for what this `cslreferences`-environment refers to. It seems you are using RMarkdown, am I correct? Because I found this pull request, which adds the necessary environment: https://github.com/jaranta/digra-latex-md/pull/4/files

Here's the code:

```tex
%Defines cslreferences environment
%Required by pandoc 2.8
%Copied from https://github.com/rstudio/rmarkdown/issues/1649
$if(csl-refs)$
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{cslreferences}%
  {$if(csl-hanging-indent)$\setlength{\parindent}{0pt}%
  \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces$endif$}%
  {\par}
$endif$
```

This is not applied within the default Zettlr template, so to use it, here's what you need to do:

1. Download a copy of [Zettlr's standard template](https://github.com/Zettlr/Zettlr/blob/master/source/main/assets/export.tex), or [Pandoc's standard template](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex) and save it on your computer
2. Open the PDF-Preferences, either the global ones (`Cmd+Option+,`) or the ones of your project, if you're writing your dissertation as a project. Point Zettlr to use the template you just downloaded.
3. If you downloaded the Zettlr template: Open the respective template, and add the above mentioned code into the header (somewhere before `\begin{document}`)
4. In case you decided to use the Pandoc template, it should work out of the box without editing the template!

Then I hope it should work!

And solidarity to you for helping the Grenfell victims! ✊🏼

**Comment by clarkie1977** [comment]
I can't tell you how much I appreciate this. I am getting somewhere with your help but its not fully fixed. The PDF export now works from the top menu, however, trying to export the project (right click) doesn't work and I get a new error message:





I chose to add the code to the Zettlr template and use that one. It works mainly as described above and I thought I'd try the other Pandoc option to see if it helped but Zettlr doesn’t allow me to select the other template, it is greyed out when I search my files to select.

**Comment by nathanlesage** [comment]
> it is greyed out when I search my files to select.

Ah, maybe you need to rename it from `.latex` to `.tex` — pandoc has some weird policy on how `.tex`-templates are called!

The error message, unfortunately, didn't load — what does it say?

**Comment by clarkie1977** [comment]
Hi Hedrik,

Sorry for my brief response but here is the text:

 Export failed
An error occurred on export: Command failed: pandoc "/Users/richardc|ark/Library/Mobile Documents/com~app|e~CIoudDocs/My Zettlr Folder/Coventry University/Projects/Disaster & Emergency Planning - MlloGED/Disaster & Emergency Planning/exporttmp" -f markdown -t latex --temp|ate=/Users/richardclark/Library!Mobile Documents/com~apple~CIoudDocsfMy Zettlr Folder/Coventry University/Projects/Disaster & Emergency Planning ‐ MlloGED/Disaster 8. Emergency PIanning/templateiatex --toc --toc-depth=1--fi|ter pandoc-citeproc --bib|iography "/Users/richardclark/Documentsr’Reference Management/My BibTex Files!Better CSL JSON (Zettlr).json" --c5| "/Users/richardclark/Documents/Reference Management!rCite Stylesz’harvard-coyentry-universitycsl" --pdf-engine=xelatex -o "f Usersr‘richardclark/Library/Mobile Documents/com~apple~CIoudDocs/My Zettlr Folder/Coventry University/Projects/Disaster & Emergency Planning ‐ MiléGED/Disaster 8. Emergency Planning/Disaster and Emergency Planningpdf" fbin/sh: Emergency: command not found f’bin/sh: Emergency: command not found pandoc: sters/richardclark/Library/Mobilelatex: openBinaryFiIe: does not exist {No such file or directory)
lbin/sh: Emergency: command not found
lbin/sh: Emergency: command not found
pandoc: IUsers/richardclark/Library/Hobile.1atex: openBinaryFile: does not exist (No such fi l e or directory)


Thanks again for all your help with this. 

iCloud
Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by nathanlesage** [comment]
Seems it does not find the file `Mobile.latex`, if I deduct the OCR fragments correctly … oh, I may have an idea what is happening: Apparently the spaces in the filename seem to cause an error within pandoc (it might be that the template file is not properly escaped, I'll have a look) — in the meantime, it might work if you put the template file onto your desktop, as your user folder seems to have no spaces in it. Then it might work!

**Comment by nathanlesage** [comment]
Update: Just checked the exporter and yes: the template path has not been quoted, e.g. any space would end the template path. I fixed this and it'll be within the next version, but until then I recommend only putting the template somwehere where there are NO SPACES in the path — sorry for this mistake!

**Comment by clarkie1977** [comment]
Hi again,

Ive tried what you have suggested with both files Zettlr & Pandoc. Still no joy. So, Ive searched me Mac with spotlight for “Mobile.latex” and it doesn't find any file at all with that name. Another symptom which I noticed before (and may be solved now) is that the Project Settings window would crash after a few second, so I’d have to be quick if I needed to make any changes. I dont know if this Information helps at all. Thanks again.

Rich. 

Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by nathanlesage** [comment]
I still think it's about spaces (after "Mobile" in your file there are more words, right? But separated by spaces --> Pandoc simply stops as soon as it encounters a space)

**Comment by clarkie1977** [comment]
Hi Hendrik,

Im a bit lost with it now. Ive moved the .tex file to my desktop file path is: /Users/richardclark/Desktop/export.tex

The error message when i try to export form a project is: 



Project Settings:



I am very sorry to have to keep asking, about this. I am sure it is my lack of knowledge that is the issue here. I don see any spaces now that it is on the desktop. Also, the file it can’t find appears to be a different file to the tex template. I have searched my mac for the file’s/directory's it is asking for: Mobile.latex or openBinaryFile and I cant find them anywhere.

Once again sorry to be a pain.

kind regards, 

Rich. 

iCloud
Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by nathanlesage** [comment]
Hey, sorry for the late response, the error message is still not showing up in the issue :( Maybe it's due to your email settings ...? However, does the problem still persist ...?

**Comment by clarkie1977** [comment]
Hi Hendrik,

No worries, we are all busy and I didn't want to hassle you anymore. Unfortunately, yes it does still persist. I am also not sure that I understood what you were saying to me before, I do apologise. I have made a PDF of the two images I tried to send in my last email and attached it to this one. I OCR’d the text and have copied and pasted it below (just incase the PDF doesn't come through) but there may be mistakes in the OCR. I am at a real loss of how to get this to work and getting worried for when I complete the writing if I will be able to create my project. Any help will be very much appreciated. I dont programme or no LaTex and Pandoc etc… to be honest I am not really sure what they do.

Custom TeX Template:

/Users/richardclark/Desktop/export.tex

Error message:

Export failed

An error occurred on export: Command felled: pandoc ”/Users/rlchardclark/Library/Moblle Docurnents/com~apple-CloudDocs/My Zettlr Folder/Coventry University/Projects/Disaster & Emergency Plannlng - M116GED/Disaster & Emergency PIanning/export.tmp" ff markdown ‐t latex Wtemplate=sters/richardclark/Library/Mobile Documents/com‐appIe‐CloudDocs/My Zettlr Folder/Coventry Universlty/Projects/Disaster 8. Emergency Planning 7 MlléGED/Dlsaster & Emergency PIanning/templatelatex --toc --toc-depth=1 --ﬁlter pandoc-clteproc --bibllography "/Users/rlchardclark/Documents/Reference Management/My Bleex Files/Better CSL JSON (Zettlr).]50n" --csl “lUserS/richardcIark/Documents/Reference Management/Cite Styles/harvard‐coventry‐universltycsl“ ‐‐pdf‐engine:xelatex ‐o "/Users/richardclark/Library/Mobile Documents/com~apple~cloudDocs/My Zettlr Folder/Coventry Unlversity/Projects/Disaster & Emergency Planning MlléGED/Disaster & Emergency Planning/Disaster and Emergency Planninglpdf” lbin/sh: Emergency:command not found /bin/5h: Emergency:command not found pandoc: /Users/richardcIark/Library/Mobile.latex: openBlnaryFile: does not exist (No such ﬁle or directory)

/bin/sh: Emergency: command not found 
/bin/sh: Emergency: command not found 
pandoc: /Users/richardclark/Library/Mobile.latex: openBinaryFile: does not exist (No such ﬁle or directory)

Close




iCloud
Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by nathanlesage** [comment]
Hey, thanks for the response! I think the problem originates because you're sending the comments as mail, but I'm answering them directly on the issue tracker, I think the email-to-comment-feature has some issues, but nevertheless, I think the problem originates with the file names. Because in your source file you still have spaces (which might cause some of the problems) and an ampersand -- and I think that ampersand is causing much problems. I think you might be well off if you'd try to rename the "Disaster & Emergency Planning" to something like "disaster_emergency_planning" -- something without spaces and the ampersand. Then it might work!

The problem, after all, is because Zettlr itself runs the command and if there are any unforeseen characters, console programs still tend to behave very irradically ...

**Comment by clarkie1977** [comment]
Oh I see. The export file, haha! I’m thinking there are no spaces etc... while looking at the template file and it’s location. I’ll try that when I’m back from the school run and let you know. Thank you! 🙏🏻

iCloud
Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by clarkie1977** [comment]
Ok, so that worked for exporting pdf using the button at the top of zettlr but if I try to export the same file by right clicking and exporting project I get this error:

pandoc: /Users/richardclark/Library/Mobile.latex: openBinaryFile: does not exist (No such file or directory)


Also, when I try to export as rtf (top button) it still only exports the first line of the text? 

iCloud
Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by nathanlesage** [comment]
Mhh... I have no idea where this Mobile.latex comes from. And what do you mean it only exports the first line of text? o.O

**Comment by clarkie1977** [comment]
Hi again, I am so sorry about all of this. 

Ok, so I figured that mobile thing out, it was iCloud. I’ve moved my Zettlr folder into my documents folder on my SSD in my MacBook - sorted! I can now export as pdf from both projects and files.

The RTF Issue, however, remains (although for now it’s not too much of a worry) I like the rtf output as a fail safe option. It is easy to export to rtf to get my citations and my reference list and then rebuild the paragraph formatting in pages or similar if I need to. I don’t know LaTex yet to create my own template. My University stipulate the formatting. Your template meets 99% of their requirements, except I need to figure out how to move the main chapter headings to the centre.

 For your info, the RTF issue, is the following: 

If I export an RTF file, the text window opens with only the first line or paragraph of text. Often this is the title of course but I’ve tried it with other elements and it appears to be the first block of text such as a paragraph . I am not sure of the correct terminology but I want to say the first “block level item” ? There is no error message or anything just the RTF as stated, shy of content. 

Thank you for your help with all this. I have enough to do the job now but would like to know your thoughts on this RTF issue but only if and when you get time. 

Thanks again,

Kind regards ,

Rich.

iCloud
Richard Clark GIFireE
t: 07832710882
e: clarkie1977@me.com

**Comment by nathanlesage** [comment]
> Your template meets 99% of their requirements, except I need to figure out how to move the main chapter headings to the centre.

Concerning this: It might help to put one of these two inside the header (before the `\begin{document}` statement):

Either: `\RedeclareSectionCommand[font=\centering]{section}` (should work as Zettlr already uses KOMA classes)

or, if above mentioned doesn't work:

```
\usepackage{sectsty}
\sectionfont{\centering}
```

(This one would mean to download the package sectsty [I'm not completely sure that's the correct name, but Google is your friend on this one!])

Source: https://latex.org/forum/viewtopic.php?t=29618

As most issues seem to be fixed, I'll be closing the issue now. I'll be having a look at the RTF-issue next year; I'm more than overworked with releasing 1.5 this Christmas already, so I hope it works out for now! If it persists, please feel free to knock at my door somewhere end of January!

But it's good to know that iCloud does seem to provide some issues; I've never used it until now because I feared exactly such kinds of issues …
