### ISSUE TITLE
Lag in updating when typing quickly in a large file [Beta 3]

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#4250]
### Description

In Beta 3, there is a noticeable lag in updating the screen when typing quickly in a large file. This is a regression relative to the Nightly of 29 March.

### Reproducing

In order to see the effect, you need a fairly large file (e.g. 4000 words). If you hit keys very quickly at random, you'll notice that Zettlr takes a few seconds to catch up. The effect becomes really obvious in a very large file (e.g. 12,000 words). This problem is not present with the previous Beta or with the Nightly of 29 March. It may be due to https://github.com/Zettlr/Zettlr/pull/4242.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta-3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Do you have autosave turned on? If so, does this lag disappear if you turn it off and save manually? I can guarantee you #4242 has nothing to do with any lag within the editor itself.

**Comment by jgsw** [comment]
I still get the lag even with autosave turned off.

**Comment by nathanlesage** [comment]
Oh, you are right, I forgot that I changed the counter as well! Maybe you've actually faced a performance penalty due to that, as Tobias already feared. (I have a relatively beefy machine so that's possibly why I don't experience it this strong).

Could that be? What processor are you running? If it turns out to be that issue, I'll have to get to the word/char counter once again.

**Comment by jgsw** [comment]
That makes sense. My machine is pretty slow (midrange laptop that's now four years old).

**Comment by nathanlesage** [comment]
Alright! But hang on, I just experienced this lag myself on a quite beefy machine, so it's not you, it's me!

@tobiasdiez your intuition proves right and my solution was wrong 🙈

**Comment by nathanlesage** [comment]
It's amazing how much faster it became once I didn't tell Zettlr to do double-work … now same update frequency and same information with same precision, but in a fraction of the time.

@jgsw please download next Monday's nightly release and try it out again if it really has improved, and report back. That would be awesome, thanks!

**Comment by jgsw** [comment]
Thanks - I've just tried the nightly, and can confirm that the bug is gone! No typing lag, even in a very long file (12,000 words).
