### ISSUE TITLE
Updater text being cut-off

### ISSUE THREAD

**Issue by learn-more** [Zettlr/Zettlr#4251]
### Description

When viewing the release notes from the recent 3.0.0-beta3 update, it appears that certain parts of the text were cut off. (For example, contributor names):

![image](https://user-images.githubusercontent.com/610685/230990626-053a17f1-11af-40f7-98c3-c0b6e65cb21b.png)

### Reproducing

* Click on help->check for update
* Wait until the download is completed
* View the release notes.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 22H2 (Build 19045.2728)

**Comment by nathanlesage** [comment]
That should've been fixed in https://github.com/Zettlr/Zettlr/commit/d2e00a00dc409ea190e4f5115dcad7f184eb1e89.

(The reason is that GitHub mentions use the same syntax as citations; now the updater passes a no-op citation callback which should consistenly leave GitHub mentions as they are)
