### ISSUE TITLE
Text runs over the bottom edge of the page while typing in distraction-free mode.

### ISSUE THREAD

**Issue by tkeiderling** [Zettlr/Zettlr#4257]
### Description

When I have Zettlr 3.0.beta.3 in distraction-free mode, the cursor is set below the bottom of the screen and does not move. The text simply runs off the bottom of the page. 

### Reproducing

In the latest beta, enter distraction free mode either through the keyboard shortcut (ctrl+j) or the menu item under "view." 

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.beta.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
I cannot reproduce this, unfortunately. Can someone else confirm? Also, a screenshot may help me make sense how it looks for you.

**Comment by tkeiderling** [comment]
![image](https://user-images.githubusercontent.com/90908474/231562775-076acdfe-0bee-4ad7-a2cf-71ce22ed6581.png)

**Comment by tkeiderling** [comment]
In the above image (hopefully it uploads) the final note on the page runs two lines below what is on the screen and I cannot get it to move up.

**Comment by nathanlesage** [comment]
Ah this looks like a CSS error; on macOS there's no titlebar and menu bar. I'll have a look.
