### ISSUE TITLE
Hashtags after single LF not detected

### ISSUE THREAD

**Issue by ailintom** [Zettlr/Zettlr#4258]
### Description

Whereas Zettlr 2.3.0 did detect hashtags at the beginning of a new line following a non-empty line, Zettlr 3.0 beta 3 only detects hashtags when preceded by a space or a double LF (an empty line before the hashtag). 

### Reproducing

Create a new .md file, type some text, press enter and then type a hashtag. 
Example: 

`

sometext
#hashtag

#another-hashtag #third-hashtag

`

In Zettlr 2.3.0 all three hashtags are formatted as hashtags and become clickable, whereas in 3.0 beta 3 only the second and the third one. 

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0 beta 3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 

### Additional Information

This new peculiarity would require fixing a lot of older .md files when migrating to 3.0. It does not seem to be documented and thus does not seem to represent the desired behaviour.

**Comment by nathanlesage** [comment]
Hashtags on the beginning of a line should be detected as such, you are right. I just tested it out and can confirm that there's a bug in the tag parser.
