### ISSUE TITLE
Beta3 3 does not start on Ubuntu

### ISSUE THREAD

**Issue by Schnarrschrecke** [Zettlr/Zettlr#4262]
### Description

Starting Zettlr in a terminal, the messages end with an error, waiting and nothing happens

[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /opt/Zettlr/resources/pandoc
[Application] Environment check complete.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### Reproducing

Start new installed Zettlr3beta3 from a terminal under Ubuntu 22.04

### Zettlr Version

Beta (if applicable)

### Specify version

Beta3-3

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
I did a quick google search – could it be that you may need to update your graphics driver? See this issue, which describes the same error you have:

https://github.com/electron/electron/issues/30902

**Comment by nathanlesage** [comment]
I updated the Electron version in between beta2 and beta3, so there's a chance that the new beta requires a newer driver.

**Comment by 87113** [comment]
Hi, have Ubuntu 22.10 and I just upgrade Zettlr to the v3.0.0-beta.3 with the .deb
I don't know why it's not working with ubuntu 22.04 but  is working well form the cli or gnome. 

Tell me if I can help with more data.

**Comment by Schnarrschrecke** [comment]
Thank you for your support, but I didn't find a way. I have an AMD graphics, installed the latest deb from AMD, but without effect. 
Starting Zettlr -no-sandbox --disable-gpu-sandbox --disable-seccomp-filter-sandbox
suppresses the error code, but Zettlr doesn't start either. I tried to start under Xorg instead of Wayland, but this has no effect. There are numerous links on the web regarding this error, but I didn't find a solution.

**Comment by nathanlesage** [comment]
I'm gonna drop this issue into the Discord server, maybe someone there has an idea. My experience with desktop Linux is unfortunately very limited.

**Comment by nathanlesage** [comment]
The current novel build pipeline should have fixed these issues; feel free to try out the current nightly: https://nightly.zettlr.com/
