### ISSUE TITLE
Relative paths do not work properly for images

### ISSUE THREAD

**Issue by ailintom** [Zettlr/Zettlr#4265]
### Description

In 3.0 beta 3 Zettlr tends to look for images referred to with relative paths in the program folder instead of the document folder. 

### Reproducing

In 3.0 beta 3 on Windows create a new .md file, save it, copy and paste an image into that file and agree to save it at the default location -- in the same folder where the .md file was saved. For example, save it as "cc410e0be06091713d989a8b791f3c7e.png" in the folder %USERPROFILE%\Documents\Notes

Zettlr creates the following line in the .md file: 

`
![cc410e0be06091713d989a8b791f3c7e.png](./cc410e0be06091713d989a8b791f3c7e.png "cc410e0be06091713d989a8b791f3c7e.png")
`

Now save the .md file and close it. 
Reopen the saved .md file, and Zettlr will fail to show the saved image file, displaying an "Image not found" instead
![image](https://user-images.githubusercontent.com/24455000/231684552-a0f8dc6f-b955-43cb-a58a-41c47263b993.png)

 According to ProcMon, Zettlr is trying to locate the linked image file under %USERPROFILE%\AppData\Local\Programs\Zettlr\cc410e0be06091713d989a8b791f3c7e.png  rather than in the same folder where the md file is located. 
![image](https://user-images.githubusercontent.com/24455000/231685647-b5fcfbb2-8b58-4e5b-b1d5-77831d15b68d.png)
Obviously the current path in Zettlr 3.0.0 beta 3 is at some point switched to the program location instead of the current .md file location. 
If you now click several times on the image inside the .md switching between the .md code and the image preview, the image will at last be loaded correctly. Apparently when switching between editing and preview mode, Zettlr changes the current path back to the .md file location.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0 beta 3
and 
3.0 beta 3 nightly (Apr 17th, 2023)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

### Additional Information

The problem does not occur in Zettlr 2.3.0

**Comment by nathanlesage** [comment]
This is likely an issue with how the config is set upon instantiation of the editor. It has to receive the path after instantiation, which gives the editor a very short amount of time to try to locate the image at the wrong path.

In the meantime, you can work around this by moving into the image and out of it again with your cursor. This will re-render it, but this time with the correct path.
