### ISSUE TITLE
tables don't detect changes nor save properly

### ISSUE THREAD

**Issue by mattzjack** [Zettlr/Zettlr#4268]
### Description

Tables don't seem to be able to detect changes properly, and they don't save properly, unless I add / delete a row / column.

### Reproducing

1. Create a markdown
2. Create a table
3. Enter some text in the table
4. Notice that the tab doesn't have a * to indicate change
5. Press ctrl+s anyway to attempt to save
6. Go to another md and come back ==> the text in the table is not saved
7. Enter some text in the table, then add a row
8. There is a *. Press Save. Leave and come back ==> changes are saved

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This bug is fixed in the current v3.0 branch.
