### ISSUE TITLE
[Feature Request] Show save/unsaved indicator next to currently opened file

### ISSUE THREAD

**Issue by keiichiiownsu12** [Zettlr/Zettlr#427]
## Platform
 - OS: Linux (Arch)
 - OS Version: Kernel Version: 5.4.1
 - Zettlr Version 1.4.3

## Brief description of feature requested
In the sidebar, for the indicator that marks the currently open file:

![image](https://user-images.githubusercontent.com/37505464/70088509-421d9200-15cb-11ea-9366-40fef476a676.png)

Could a feature be implemented to where this changes color to show if a currently open file has any unsaved changes?

**Comment by nathanlesage** [comment]
It could, yes. BUT as I will be tackling tabs in one of the next versions, I'd rather focus my energy there and then a saved/unsaved indicator will make much more sense. Even though, Zettlr automatically saves every five seconds and everytime you switch the file, close the app etc. pp, so it shouldn't be much of an issue!
