### ISSUE TITLE
What is the last version of Zettlr that supports macOS 10.15

### ISSUE THREAD

**Issue by cddehsy** [Zettlr/Zettlr#4270]
### Description

What is the last version of Zettlr that supports macOS 10.15

### Proposed Changes

What is the last version of Zettlr that supports macOS 10.15

### Caveats

What is the last version of Zettlr that supports macOS 10.15

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

macOS 10.15

**Comment by nathanlesage** [comment]
For questions, please either open a discussion topic or ask on Discord. Do not use the issue tracker for that.

Regarding your question: Electron has dropped support for Catalina relatively soon, possibly beginning of 2022, so anything before that will probably work. My suggestion: begin with 2.3 and try out the releases until you find one that works.

As Catalina is no longer officially supported, I don't, too.
