### ISSUE TITLE
High CPU use

### ISSUE THREAD

**Issue by rebastion** [Zettlr/Zettlr#4278]
### Description

Using the latest Beta, Zettlr still uses lots of CPU. The way I notice is that the laptop's fan jumps on and stays on, and only gets quiet again when using Zettlr. There must be some unnecessary resources used because for just editing some text this shouldn't happen. Unclear how to pin this down exactly, happy to provide additional info.

### Reproducing

Open latest Zettler beta (installed from .deb) in Ubuntu, listen to laptop's fan noise and feel heat development.

### Zettlr Version

Beta (if applicable)

### Specify version

latest

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.10

**Comment by nathanlesage** [comment]
Could it be that this here is the cause: #4250?

Please try out the most recent nightly and see whether the CPU usage is down again: https://nightly.zettlr.com

**Comment by rebastion** [comment]
Hi. definitely not that. the file is tiny and I dont need to be typing in it to reproduce. I will however give a latest nightly a chance to see if the problem has disappeared in some other way

**Comment by rebastion** [comment]
Problem persists with yesterday's nightly

**Comment by nathanlesage** [comment]
Mh, could you give me a screenshot from `top` of some monitor of how much CPU Zettlr is using? And, would you mind completely wiping everything, *then* installing a naked, new version of Zettlr and see if the issue persists even if you don't load anything in there?

**Comment by rebastion** [comment]
Hi. Of course. Here is a top excerpt from when Zettlr (nightly from a few days ago) is running with one relatively small and simple text document running. CPU use is very high:
![image](https://github.com/Zettlr/Zettlr/assets/13915837/8e9cb2b9-a1f1-4fac-b17e-37968d795550)

I now wiped zettlr as much as I could. I am working on installing the new beta from a few hours ago. Stay tuned... having a whole different problem with that one....

**Comment by rebastion** [comment]
Seems to be fixed? No high CPU use with today's daily build. Need to observe a bit longer, but as a short positive update to this issue :)
