### ISSUE TITLE
md Export to PDF display wrong character when include Chinese,Japanese,Korea.

### ISSUE THREAD

**Issue by blue-dog** [Zettlr/Zettlr#428]
# Prepare md file in the Zettlr 1.4.3 

20191205134510.md

```
This is a test.

这是一个测试。

這是一個測驗。

이것은 테스트입니다.

これはテストです。
```

# Export this file to PDF in Zettlr 1.4.3

![02](https://user-images.githubusercontent.com/8454995/70207805-c2c4c580-1766-11ea-960d-6d8e712deb09.png)

# Open the exported PDF displayed the wrong character

![03](https://user-images.githubusercontent.com/8454995/70207806-c35d5c00-1766-11ea-8f9d-1cb04b42bc48.png)

# Other information

pandoc.exe 2.8.0.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3

MiKTeX 2.9 

Windows 10 64 bit
Zettlr 1.4.3

**Comment by nathanlesage** [comment]
It very much looks like the font that's being used by LaTeX does not contain Chinese, Japanese, or Korean characters. Zettlr defaults to Times New Roman, which might explain it. Try using different fonts in the PDF-Preferences!
