### ISSUE TITLE
Zettlr 3.0.0-beta3 does not collapse links

### ISSUE THREAD

**Issue by learn-more** [Zettlr/Zettlr#4282]
### Description

When writing links, normally they would be collapsed to the text when the cursor leaves the link,
but this does not seem to be happening in the latest beta.

### Reproducing

Create a file `test.ini`.
Add the following links in a document next to the file:
```
- [test](file://test.ini)
- [test](test.ini)
- [test](./test.ini)
```
The links no longer collapse:

![image](https://user-images.githubusercontent.com/610685/233481321-b1752955-f1eb-4a66-a8cb-b3978f12a92c.png)

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 22H2

**Comment by nathanlesage** [comment]
I cannot reproduce this on the current dev branch.

![image](https://user-images.githubusercontent.com/17251683/233609711-333ae2e4-2742-41b4-abf7-a901bef24518.png)

Would you mind trying out the current nightly release to see if this happens in there? There's a chance I accidentally fixed this bug in the meantime: https://nightly.zettlr.com

**Comment by learn-more** [comment]
Indeed fixed by the nightly.

**Comment by nathanlesage** [comment]
Wonderful, thanks for double-checking! Probably had something to do with a bug in the parser, there have been a few in the past weeks.
