### ISSUE TITLE
Issue with minimatch glob patterns in project settings

### ISSUE THREAD

**Issue by Alexandros81** [Zettlr/Zettlr#4283]
### Description

When trying to compile through "export project" voice menu (with XeLaTeX PDF.yaml and a custome LaTeX template), nothing at all happens... However, when I do the same with Zettlr-3.0.0-beta.2-x86_64.AppImage things go the right way.

### Reproducing

Attempt to export a project to obtain a pdf via XeLaTex.

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Last ArcoLinux

**Comment by Alexandros81** [comment]
The following one is the incriminated error found within the log file:

`[12:05:34] [Error] [Application] Error received while running command: e.split is not a function | Native Error: TypeError; e.split is not a function Stack Trace: TypeError: e.split is not a function -->     at R.slashSplit (/tmp/.mount_Zettlrt4wHT6/resources/app.asar/.webpack/main/index.js:2:3058476) -->     at R.match (/tmp/.mount_Zettlrt4wHT6/resources/app.asar/.webpack/main/index.js:2:3058701) -->     at t.minimatch (/tmp/.mount_Zettlrt4wHT6/resources/app.asar/.webpack/main/index.js:2:3047967) -->     at /tmp/.mount_Zettlrt4wHT6/resources/app.asar/.webpack/main/index.js:2:3049257 -->     at Array.filter (<anonymous>) -->     at u.run (/tmp/.mount_Zettlrt4wHT6/resources/app.asar/.webpack/main/index.js:2:1783445) -->     at W.run (/tmp/.mount_Zettlrt4wHT6/resources/app.asar/.webpack/main/index.js:2:1816663) -->     at /tmp/.mount_Zettlrt4wHT6/resources/app.asar/.webpack/main/index.js:2:1815342 -->     at node:electron/js2c/browser_init:2:97909 -->     at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)`

Thanks

**Comment by nathanlesage** [comment]
Ah, this looks as if there may be an error while running the Project GLOB. You're probably exporting a project, and there may be an error in one of the glob filters you are using. Could that be?

**Comment by Alexandros81** [comment]
Sorry, but I don't know what a glob filter is and where I'm supposed to have set one of them..., may be within my LaTeX template?

**Comment by Alexandros81** [comment]
The only filter I find in XeLaTeX PDF.yaml is the default `- type: citeproc`, but commenting it does not avoid the same to be raised...

**Comment by nathanlesage** [comment]
No no, the filters I mean are in the project settings (the glob ones) -- do you use those?

**Comment by Alexandros81** [comment]
Yes, the problems are related to the "glob patterns" used to filter specific files at the moment of compilation within the project directory. But why? It seems that no pattern at all is accepted. As a matter of fact compilation starts only without any pattern being set... Is there a new syntax for patterns?

**Comment by nathanlesage** [comment]
Not a new syntax, but I did update the corresponding library. Could be that I missed an update step. I'll rename to properly reflect what the issue is, and then get to it asap.

**Comment by nathanlesage** [comment]
Fixed it. And now you even get a visible error message if your glob filters are accidentally set up to remove every file.

**Comment by Alexandros81** [comment]
Danke dir!
