### ISSUE TITLE
Export does not include images (tried textbundle, pdf)

### ISSUE THREAD

**Issue by sirpeanut** [Zettlr/Zettlr#4285]
### Description

When I export a doc that contains images to textbundle, the assets directory that is created is empty.

Note this seems like similar behaviour to #653, but that was fixed years ago, so it's probably a different root cause.

### Reproducing

Create a doc containing an image, like 
```
![test.jpg](./test.jpg)
``` 

Then try to export as textbundle.

The image shows up just fine inside the Zettlr editor, but it's missing from the generated assets dir (which is empty).

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by sirpeanut** [comment]
A bit more detective work:
* exporting to PDF in stable (2.3.0) also does not preserve the image
* exporting to PDF in 3.0.0-beta.3 DOES preserve the image (yay!)
* trying to export to textbundle in 3.0.0-beta3 fails, though ("Cannot run Textbundle exporter: Wrong profile given!"), so that's not a feasible workaround

**Comment by nathanlesage** [comment]
There's a high chance that I accidentally borked the Textbundle export; I'll have to get to that at some point, thanks for the issue!
