### ISSUE TITLE
click on first entry in the list leads to workspace and not to the note.

### ISSUE THREAD

**Issue by maxwowpow** [Zettlr/Zettlr#4289]
### Description

First note in the list not openable.

### Reproducing

- a workspace with 2 folders.

- enter the 1st workspace.

- try clicking on on the first folder/note.

#### Expected:
note shown on the right.

#### Actual:
workspace view / parent folders shown (the hovering back-button gets triggered) - independent of cursor position.

### Zettlr Version

Beta (if applicable)

### Specify version

beta3  5a48b156-bf97-4a3f-81ba-a7db61f6d92f

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 10

**Comment by nathanlesage** [comment]
CC @sensologica Maybe a UX issue?

**Comment by sensologica** [comment]
Yes it is. Making a note of this so we can address it.
