### ISSUE TITLE
Add the ability to compile a project to docx, not just pdf

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#43]
Since this can be done relatively easily in pandoc, it shouldn't be difficult to add it as an option in Zettlr. Currently, projects can only be compiled into pdf format from inside Zettlr. What I would like is for Zettlr optionally to run a command like this for me:

`pandoc -s "Intro.md" "chap1.md" "chap2.md" "chap3.md" "chap4.md" "Conclusion.md" -o My_Book.docx -f markdown -t docx --standalone --top-level-division=chapter --toc`

(I'm aware pandoc ignores some of those options with docx format, it's more of a wishlist!) OK, I'm lazy, I could just run it myself in pandoc, but since Zettlr is aimed at Arts and Humanities researchers, most of my colleagues and students would freak out if you ask them to run a command-line program. And most publishers unfortunately want work submitted as docx, and won't accept pdf for obvious reasons.

**Comment by nathanlesage** [comment]
> most of my colleagues and students would freak out if you ask them to run a command-line program.

Haha, I think you just pinpointed the gist of what Zettlr is about.

I didn't think of that when I introduced the Project feature, although I know publishers and their eccentrics. I'll see to it!

**Comment by nathanlesage** [comment]
Comes in the next version!

**Comment by Jaifroid** [comment]
Many thanks!

**Comment by mberasategi** [comment]
Is there a way to set a specific (local, if possible) Word template to compile through pandoc? Maybe in the project settings? Not necessarily through the GUI, but somehow in the project settings (`.ztr-directory`) file...? Or at least through the YAML front matter. I've been going through open and closed issues but couldn't find it. Thanks!

**Comment by nathanlesage** [comment]
@mberasategi See issue #1193
