### ISSUE TITLE
[Dev] Is there a way for hot-reloading after code change?

### ISSUE THREAD

**Issue by ttdtrang** [Zettlr/Zettlr#430]
I couldn't find the instructions for hot reloading while developing Zettlr, not sure if it's currently possible. Could you please advise?

**Comment by nathanlesage** [comment]
Hot reloading is only possible in the renderer; by having active debug mode and hitting `F5` -- just like in the browser. The main process can't be hot reloaded b/c the code is punched into the system memory and the server has to be rebooted to acknowledge code changes!
