### ISSUE TITLE
Zettlr stops responding when adding pt-PT dictionary

### ISSUE THREAD

**Issue by brunoamaral** [Zettlr/Zettlr#4300]
### Description

I'm running v2.3.0 and tried with several dictionaries for european portuguese, and when I select them, the app stops responding.

Noticed some discussion about this on closed issues, but none of the suggestions worked for me. The latest dictionary I tried to use was from the University of Minho, https://natura.di.uminho.pt/download/sources/Dictionaries/mozilla/Pos-AO/.

### Reproducing

1. download https://natura.di.uminho.pt/download/sources/Dictionaries/mozilla/Pos-AO/pt-PT-dictionary-20.10.5.1.xpi
2. place the files in the dictionaries directory
3. select the pt-PT dictionary
4. wait a few seconds and the app stops responding with the spinning beach ball.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

MacOS Ventura 13.3.1

**Comment by nathanlesage** [comment]
This issue is known and won't be fixed in the v2.x branch of the app. Instead, if you need it, I recommend that you switch to the betas which implement a novel algorithm that works with any dictionary.
