### ISSUE TITLE
Citing with zettlr

### ISSUE THREAD

**Issue by johnf53** [Zettlr/Zettlr#4302]
My first ever post, so this may be the wrong place. My issue is simple. In setting up citations under Export I'm trying to find the file browser of the references. But there is nothing there - no way to open a file. I'm using the most recent version, have installed/uninstalled twice on two computers. But nothing, so I can't follow what the guide says, nor the documentation because I can't load either the test Zotero database or any other of my own. I've checked every document online I can find - no help. Am I missing something?

Regards

### Discussed in https://github.com/Zettlr/Zettlr/discussions/4297

<div type='discussions-op-text'>

<sup>Originally posted by **WombatBeutler** April 28, 2023</sup>
Dear all,
I use Zettlr and Zotero for academic work. Citing in Zotero used to work fine until today: 
When I try to cite in Zettlr and type [@]  the list of reference still appears, but it has no more then 50 titles. Because there are more than 90 references in my Zotero Libary the list appearing in zettlr (which is alphabetical sorted) ends with a citation key starting with M. All references beginning with  o unitl z are not displayed. If I add a new titel with an author whos name starts for example with a B I will find it in the list, when I try to citate in Zettlr- but the title with the citationkey beginning with M will dispear from the list. It seems to me that it is not possible to display more than 50 titles. I restartet Zettlr and Zotero several times, disconntected zettlr and zotero and connect them again, but the problem remains. 
If there is anybody who has an idea what may had happen and what will help, I would by extremly thankful!!
Best Regards
</div>

**Comment by johnf53** [comment]
I have solved the problem of citing with Zettlr that I wrote about in my first post. What it requires is a change in Zettlr's documentation, which is completely misleading. 

Zettlr's Introduction says to load the citation database "first head over into the preferences and into the tab “Export.” Once there, navigate to the file using the file browser of the references database-field." Not so. You have to go to the tab *next* to Export - the one with the quote marks. There, and only there, will you find a way to open Citation Database. After that: all good.

Same problem in the online documentation. It reads "Now it is time to import your library to Zettlr. To do so, open Zettlr's preferences, go to the Export tab and click the small file icon located to the right to the Citation Database input field."

No. Go to the quotation marks NEXT to the Export tab. Then follow the steps after you've set your directory for your database. There is no such option in the Export tab itself. I don't know how this has been noticed or commented before, but please, please change it (someone - I don't know how this happens).

John

**Comment by nathanlesage** [comment]
Ah, yes, that was a mistake in the documentation. The docs for 3.0 will be corrected!
