### ISSUE TITLE
Custom CSS not working in 3.0 beta

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4308]
### Description

I'm on beta 3.0 beta 4 Flatpak version. For some reason custom CSS completely stopped working apparently no matter which CSS style I tried.

### Reproducing

See above

### Zettlr Version

Beta (if applicable)

### Specify version

3.0 beta 4 

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE MicroOS

**Comment by nathanlesage** [comment]
The most recent beta does work with CustomCSS, I checked this out after someone else mentioned this. This is very likely a FlatHub permissions issue. See the corresponding note in the documentation: https://docs.zettlr.com/en/install/#flatpack

If that doesn't work, please head over to the Flathub repository.

**Comment by sith-on-mars** [comment]
Interesting I don't think it's the Flatpak permission issue, since CustomCSS is located in the config folder. I'm not sure why Flatpak has this bug though...
