### ISSUE TITLE
Autocorrect screws up commenting

### ISSUE THREAD

**Issue by dambaras** [Zettlr/Zettlr#431]
When autocorrect is enabled for -->, the commenting framework `<!--  -->`  gets screwed up, so one has to disable that autocorrect option. Just fyi.

**Comment by nathanlesage** [comment]
Ouhh, never thought about that! I have an idea for that! Thanks for reporting!

**Comment by nathanlesage** [comment]
Aaaand fixed, will be shipped with the next beta on Friday! :)

**Comment by dambaras** [comment]
Thanks!
-- 
David R. Ambaras
Professor and Director of the History Honors Program
Department of History, Campus Box 8108
North Carolina State University
Raleigh, NC 27695-8108
Phone: 919-513-2228 | Fax: 919-515-3886
Email: dambaras@ncsu.edu | Skype: dambaras
http://history.ncsu.edu/people/faculty_staff/dambaras

*Now in paperback:* *Japan's Imperial Underworlds: Intimate Encounters at
the Borders of Empire*
<https://www.cambridge.org/gb/academic/subjects/history/east-asian-history/japans-imperial-underworlds-intimate-encounters-borders-empire?format=PB>
(Cambridge University Press, 2018)
*New spatial history site:* Bodies and Structures: Deep-mapping Modern East
Asian History <http://scalar.chass.ncsu.edu/bodies-and-structures>
