### ISSUE TITLE
<details> appears to be broken (or not supported?)

### ISSUE THREAD

**Issue by Pomax** [Zettlr/Zettlr#4318]
### Description

github flavored markdown has full support for the HTML details element, which is a godsend for long technical documents with large blocks of full, working code to supplement examples in text. In fact, let me demonstrate it right here since we're on github:

This is a small illustrative section of code:
```js
app.ws("/", (socket) => {
  // create a socket proxy between the web client, and the API server
  clientSocket = socket;
  clientSocket.on(`message`, (msg) => socketToAPI?.send(msg.toString("utf-8")));
  console.log(`Client socket established.`);
  if (socketToAPI) clientSocket.send(`connected`);
});
```
<details>
<summary>And here is the full code block that you usually shouldn't need to see</summary>

```javascript
import express from "express";
import expressWs from "express-ws";
import WebSocket from "ws";
import open from "open";

import dotenv from "dotenv";
dotenv.config({ path: `../.env` });
const { WEB_PORT: PORT, API_PORT } = process.env;
const API_SERVER_URL = `http://localhost:${API_PORT}`;

const app = express();
expressWs(app);

app.use(express.static(`../public`));
app.get(`/`, (_, res) => res.redirect(`/index.html`));

let socketToAPI;
let clientSocket;

app.ws("/", (socket) => {
  // create a socket proxy between the web client, and the API server
  clientSocket = socket;
  clientSocket.on(`message`, (msg) => socketToAPI?.send(msg.toString("utf-8")));
  console.log(`Client socket established.`);
  if (socketToAPI) clientSocket.send(`connected`);
});

app.listen(PORT, () => {
  console.log(`Server listening on http://localhost:${PORT}`);
  setupSocket();
  if (process.argv.includes(`--open-browser`)) {
    open(`http://localhost:${PORT}`);
  }
});

async function setupSocket() {
  try {
    await fetch(API_SERVER_URL);
    let socket = new WebSocket(API_SERVER_URL.replace(`http`, `ws`));
    socket.on(`open`, () => {
      console.log("API Server socket established");
      socketToAPI = socket;
      socketToAPI.on(`message`, (msg) =>
        clientSocket?.send(msg.toString("utf-8"))
      );
      clientSocket?.send(`connected`);
    });
    socket.on(`close`, () => {
      console.log(`going back into wait mode`);
      clientSocket?.send(`disconnected`);
      socket = undefined;
      socketToAPI = undefined;
      return setupSocket();
    });
  } catch (e) {
    console.log(`no API server (yet), retrying in 5 seconds`);
    setTimeout(setupSocket, 5000);
  }
}
```
</details>

### Reproducing

Just put the following valid github flavored markdown in a new document:
```
##### TEST

<details>
<summary>this should be a heading</summary>

And this should be something you can only see when the details block is expanded.
</details>
```

which, since we're on github, should render as:

##### TEST

<details>
<summary>this should be a heading</summary>

And this should be something you can only see when the details block is expanded.
</details>

(Note that there has to be an empty line between the summary and expandable content)

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

win10 x64 pro

### Additional Information

While the details element is technically HTML, Github fully embraced it for collapsible text and is fairly essential to have in any editor that offers github flavored markdown support.

**Comment by Pomax** [comment]
also, it looks like the bot response template has an error in its list, causing item (2) to end up as part of item (1) rather than being its own item in the ordered list.

**Comment by nathanlesage** [comment]
This is all expected:

1. You can, in fact, collapse the `details` tag, since HTML code folding is supported in Zettlr. Furthermore, since you'll want to add a fenced code block within the `details` tag, you can collapse that in Zettlr as well (may require the current betas, I don't know if that works on 2.3)
2. Upon export, support for the `details` tag depends on the browser, but it will be exported as is
3. I do not plan on adding a specific renderer for the details tag, mainly because that would introduce possible vulnerabilities that I do not wish to have.

**Comment by Pomax** [comment]
I'm a confused: I'm trying this syntadx in the current release of Zettlr and it _doesn't_ work, whereas your point (1) suggests it should?

**Comment by nathanlesage** [comment]
> I'm a confused: I'm trying this syntax in the current release of Zettlr and it doesn't work (as in, it does not collapse) whereas your point (1) suggests it should?

As I mentioned: It could be that this only works in the current beta (which I'm using) — 2.3 is really old, and the current betas are very stable and recommendable.

> I'm trying to find an alternative to Typora that actually supports github markdown, in the sense that what I write gets rendered the same way it will render on github

You may want to read this: https://docs.zettlr.com/en/concepts/wysiwym/

**Comment by Pomax** [comment]
cheers

**Comment by nathanlesage** [comment]
@IgnacioHeredia

> 1. Detail tag can be collapsible but when the file is opened again it is no longer collapsed

Which is intended and expected behavior.

> 2. The detail tag only collapses content up until the first line break. Not between the two tags defining the whole collapsible section. ([HTML specification](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details))

This is again intended and expected. Zettlr is a MARKDOWN editor, not an HTML editor, so linking the HTML specification has no bearing on the main editor. It conforms to Markdown specifications, not HTML specifications.

> 3. The detail tag just seems to behave like any other random HTML tag. Not sure if intended.

Absolutely intended and expected, since this is merely code folding, not the implementation of details-specific visualizations.

Also, this issue has been closed for a long time, please avoid commenting on old issues, and instead consider opening new issues instead (as GitHub will definitely have mentioned to you as well). Except I don't think opening a new issue in this regard will help much, since my position on this hasn't changed since the last time this issue was opened.

**Comment by IgnacioHeredia** [comment]
@nathanlesage I see your points.

If one would like to support collapsible sections, maybe this could be done via admonitions. Like [Obsidian Callouts](https://help.obsidian.md/Editing+and+formatting/Callouts), which are collapsible by default. But the admonitions issue in Zettlr has been stale for a while (https://github.com/Zettlr/Zettlr/issues/532).

Anyway, thanks for the reply!
