### ISSUE TITLE
Data loss in footnote editor too easy

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#4319]
### Description

In the popup footnote editor (activated by clicking "Edit"), it's currently much too easy to lose data. 

As soon as the mouse leaves the dialog box, then all unsaved changes to the footnote are lost. The dialog already has a "Cancel" as well as a "Save" button, so it seems unnecessary also to cancel all changes when the mouse moves outside the dialog.

One suggestion would be to persist the dialog until the user explicitly selects Save or Cancel.

### Reproducing

Happens whenever the footnote editor dialog is open.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0Beta 4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Fixed with a new, better navigational system between footnote refs and footnote ref bodies.
