### ISSUE TITLE
Presentation: Relative image path not working in Windows

### ISSUE THREAD

**Issue by cutterkom** [Zettlr/Zettlr#432]
## Description
When exporting an file as a presentation, image paths have to be absolute on Windows. Otherwise the image cannot be found.

## Reproducing
Export an md-file as a presentation on Windows

## Expected behaviour
Image should be displayed when using a relative path, as the documentation states https://docs.zettlr.com/en/academic/presentations/

**Screenshots**

## Platform
 - OS: Windows 10
 - Zettlr Version 1.4.3

## Additional information
It might be enough to add a caveat for Windows users in https://docs.zettlr.com/en/academic/presentations/#images (I could do that)

**Comment by nathanlesage** [comment]
Hey, thanks for reporting! It's due to the fact that Zettlr makes the image paths absolute even when exporting to revealJS, I'll have to tweak the exporter to account for that fact!

**Comment by nathanlesage** [comment]
Aaaand fixed! :)

**Comment by cutterkom** [comment]
great, thanks!
