### ISSUE TITLE
Table of content display only updated when file is active

### ISSUE THREAD

**Issue by etbo** [Zettlr/Zettlr#4320]
### Description

The ToC is only updated when a document get the focus by clicking inside it.
Thus, we can have on the screen the ToC of another document displayed.

### Reproducing

- Open 2 files with some headings (to fill both ToC)
- Write few things in file 1
- Clic on file 2 tab
**-> the ToC is still the one from file 1 <-**
- Clic inside file 2, the ToC is now the one from file 2

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0 beta4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Closing this in favor of the slightly more general issue #4469
