### ISSUE TITLE
Update mermaid (yaml title block error, elk renderer not available, etc)

### ISSUE THREAD

**Issue by goyalyashpal** [Zettlr/Zettlr#4324]
### Description

the title and similar markup stuff is not getting picked up.

#### Steps:

1. Paste the following code in zettlr, 
2. click in empty space to make zettlr to trigger the preview (ugh)

Parts of the source/glosaary used are took from: node[^node-default], rendered[^renderer], directives[^directives], yaml[^yaml]

[^node-default]: [flowchart#a-node-default] 
[^renderer]: [flowchart#renderer] elk requires mermaid v9.4+
[^directives]: [directives] alongside definition inside `%%{ }%%` to change the applied config
[^yaml]: [yaml] settings

[flowchart#a-node-default]: https://mermaid.js.org/syntax/flowchart.html#a-node-default "mermaid.js.org"
[flowchart#renderer]: https://mermaid.js.org/syntax/flowchart.html#renderer "Configuration: Renderer"
[directives]: https://mermaid.js.org/config/directives.html#changing-loglevel-via-directive
[yaml]: https://mermaid.js.org/syntax/gantt.html#output-in-compact-mode

There are 2 flowcharts shown here, the issues shown with these are:
* The "top" one shows couldn't render due to the yaml matter[^yaml] (here, title)
removing these yaml matter lines (here: 3) will render it
* the `'theme': 'light'` ain't respected and renders in dark despite even zettlr not being in dark mode
* For the bottom, `'defaultRenderer': 'elk'` is not available either
so, the top and bottom look identitcal in zettlr, compare with the output here in github issue/vscodium itslef.

### Code:

<table>

<tr>
<td>

```mermaid
---
title: Node
---
%%{ init: {
        'loglevel': 'warn',
        'theme': 'light',
        'flowchart': {
            'useMaxWidth': false,
            'curve': 'basis',
            'defaultRenderer': 'dagre-wrapper'
        }} }%%
flowchart TD
    subgraph Top
    id --> bc
    end
    id --> ab
```

</td>
<td>

````markdown
```mermaid
---
title: Node
---
%%{ init: {
        'loglevel': 'warn',
        'theme': 'light',
        'flowchart': {
            'useMaxWidth': false,
            'curve': 'basis',
            'defaultRenderer': 'dagre-wrapper'
        }} }%%
flowchart TD
    subgraph Top
    id --> bc
    end
    id --> ab
```
````

</td>
</tr>
<tr>
<td>

```mermaid
%%{ init: {
        'loglevel': 'warn',
        'theme': 'light',
        'flowchart': {
            'useMaxWidth': false,
            'curve': 'linear',
            'defaultRenderer': 'elk'
        }} }%%
flowchart TD
    subgraph Borrom
    id --> bc
    end
    id --> ab
```

</td>
<td>

````markdown
```mermaid
%%{ init: {
        'loglevel': 'warn',
        'theme': 'light',
        'flowchart': {
            'useMaxWidth': false,
            'curve': 'linear',
            'defaultRenderer': 'elk'
        }} }%%
flowchart TD
    subgraph Borrom
    id --> bc
    end
    id --> ab
```
````

</td>
</tr>

</table>

#### Screenshot:

Github (expected):
<img src="https://github.com/Zettlr/Zettlr/assets/19423063/7cee20a6-19ca-4d17-a401-049de3961880" width=500px />

Zettlr (unexpected):
<img src="https://github.com/Zettlr/Zettlr/assets/19423063/8ca20bfc-a3ba-49d2-83f4-168b7b7f8b12" width=180px />

#### Outcome:

It says: 

```
Could not render Graph:

Parse error on line 1:
...nderer": "elk"}} }%%---title: Node---
-----------------------^
Expecting 'SEMI', 'NEWLINE', 'EOF', got 'LINK'
```

```
Could not render Graph:

Parse error on line 1:
---title: Node---
^
Expecting 'open_directive', 'NEWLINE', 'SPACE', 'GRAPH', 
got 'LINK'
```

### Zettlr Version

Stable (most recent version)
4.3.0
From the Website or GitHub

Mermaid version: not knowable from app

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

no issue shown in VSCodium or typora

**Comment by goyalyashpal** [comment]
https://github.com/Zettlr/Zettlr/tree/dependabot/npm_and_yarn/mermaid-10.1.0

**Comment by nathanlesage** [comment]
Could you please provide more context to what you are attempting to say here?

**Comment by goyalyashpal** [comment]
yeah, some error was being shown in zettlr, but not in typora with same code. it was related with mermaid version. i can't recall what it was, i am trying to replicate it now

**Comment by goyalyashpal** [comment]
yeah, got it:

the title and similar markup stuff is not getting picked up.

see the following quoted example from [mermaid.js.org](https://mermaid.js.org/syntax/flowchart.html#a-node-default)

````markdown
```mermaid
---
title: Node
---
flowchart LR
    id
```
````

**Comment by goyalyashpal** [comment]
![image](https://github.com/Zettlr/Zettlr/assets/19423063/7c50ecb5-31c0-43a9-8666-35fb7cc9be8a)

the text in the node is clipped from bottom as well

**Comment by goyalyashpal** [comment]
i was just listing the examples - and all the examples i added are different. 

i have made all the major changes in the description itself - if "spamming" were my motive, then i would have posted those too as new comments. even i have myself hid my former comments.

> it's not as if I didn't have other things to do as well.

i never created any urgency, i was just documenting the faults i found... when did i request for anything to be done immediately?
