### ISSUE TITLE
Hotkeys cycle through tabs/notes in the wrong sequence

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#4326]
### Description

**Expected behavior:** Pressing `Ctrl`+`Tab` or `Ctrl`+`Shift`+`Tab` navigates through tabs/notes either forward or backward in the sequence shown in the GUI, respectively.

**Buggy behavior:** Pressing `Ctrl`+`Tab` or `Ctrl`+`Shift`+`Tab` navigates through tabs/notes either forward or backward in the sequence that they were opened, respectively.

### Reproducing

Open four tabs/notes, then (by dragging/dropping with the mouse) switch positions of tabs #2 and #3. Then, pressing `Ctrl`+`Tab` four times will move you through the tabs in the following order: #1 → #3 → #2 → #4

NOTE: I'm seeing another tab-switching bug, but am still trying to figure out how to reproduce it: Sometimes `Ctrl`+`Tab` simply won't navigate to certain tabs.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I can't reproduce this on the current dev branch. Additionally, I just checked the code, and the code does what I would expect it to. Do you still experience this bug?

**Comment by exanrauzer** [comment]
Works fine on same system on beta5.

**Comment by IgnacioHeredia** [comment]
I can confirm that tab switching behaviour is "weird" in 3.0 stable (Ubuntu 20.04).
Instead of cycling through all the opened tabs, it only cycles through the two last used.

**Comment by hungvvu** [comment]
Can confirm that the bug still exists on 3.0.5. I've attached a recording of it below. 
[recording.webm](https://github.com/Zettlr/Zettlr/assets/63649200/14fc8771-d81a-4b1b-8680-21b7f08e2e18)

**Comment by nathanlesage** [comment]
Works in the current dev branch (3.2.2 upcoming)
