### ISSUE TITLE
Numbers don't update correctly when reordering list items

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#4327]
### Description

**Expected behavior:** When moving items up or down in an ordered list, the list content should move while the list numbers don't, maintaining a proper sequence. 

**Buggy behavior:** When moving items up or down in an ordered list, the list numbers follow the content, breaking the proper sequence of the list. 

### Reproducing

Write a list:

1- apple
2- banana
3- coconut
4- daikon

Navigate the caret to list item #2, press `Alt`+`↑` to move that item into #1 position. That yields the following output:

2- banana
1- apple
3- coconut
4- daikon

(I'm using "2-", "1-" etc. because if I use "2.", "1." etc. then github will render them sequentially rather than in my custom order, above.)

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by Kinack987** [comment]
I'm having a look into this issue now. Should hopefully have more details and potentially a PR up soon.

**Comment by mattstring** [comment]
I've played around with this a bit and it isn't specific to moving lines with alt+up/alt+down, ordered lists item numbers don't update in general when altering them in some way (For example, if you have list 1 2 3 4 5 6, and you copy element 6 to clipboard then paste it above element 2, the list is now ordered 1 6 2 3 4 5) (The same behaviour as described above, but occurs in general when moving items around in existing lists).

**Comment by Kinack987** [comment]
I've opened a pull request #4406 to fix this issue. However, for now, I have only addressed the case of moving lines with alt+up/alt+down. There is another pinned issue #937 open since 2020 which addresses the issue of fixing list numbers when deleting / copy-pasting items in an ordered list. As such, I'd suggest this issue could be safely closed if the above pull request is found to be sufficient.

**Comment by noah-arroyo** [comment]
Ah gotcha, good catch. Guessing this requires someone else's weigh in -- I don't object to what you're describing.

**Comment by nathanlesage** [comment]
As I've also written in the PR: There is this function that can automatically correct list markers for those lists that are touched by any of the selections within the editor.

Under the assumption that this function works as expected (which I'd love to have another person double check), then we could simply write a `transactionExtender` that *always* triggers if the document contents have been changed. This includes, but is not limited to, exchanging lines, adding new ones, deleting items, pasting content, and so on. This would also eliminate the current "sonderweg" we have to do with the tab character (list item indentation).

**Comment by nathanlesage** [comment]
Fixed by #4407
