### ISSUE TITLE
Switching back from Distraction Free mode, content displayed is not updated

### ISSUE THREAD

**Issue by Julianoe** [Zettlr/Zettlr#4330]
### Description

When you come back and forth from distraction mode, coming back to normal mode the content is not updated. You have 2 versions (in my case the distraction mode one is the "real" one that is saved in file.

### Reproducing

- type some text
- switch to distraction free mode
- continue your composition
- switch back to normal mode
- text has not been updated with the content typed while in distraction free mode.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro 22.1.1 Talos

### Additional Information

Installed with AppImage

**Comment by noah-arroyo** [comment]
Confirming that I have this bug too.

Also on 3.0.0-beta.4.

I'm using Windows 10, Intel 64bit

NOTE: This forking bug doesn't seem to activate until you start typing in Distraction Free mode. Up until then, toggling between that and regular mode will show identical text.
