### ISSUE TITLE
Files containing an array of bibliography files in YAML frontmatter do not open in the editor

### ISSUE THREAD

**Issue by NiekPas** [Zettlr/Zettlr#4346]
### Description

I have a brand new workspace with a markdown file that contains YAML frontmatter, which has a 'bibliography' field that refers to several files:

```
---
bibliography: [../somefile.bib, someotherfile.bib]
---

hello world! This file doesn't work :(
```

If I try to open the file in Zettlr, the 'active tab' in the tab bar changes, but the file doesn't actually open (the contents of the editor don't change). If I previously had another file open, that file remains open, and I can still edit it. 

This also happens when I use quotes around the file paths, or when the array contains only a single file entry, or none:

```
---
bibliography: ["../somefile.bib", "../someotherfile.bib"]
---

// or:
---
bibliography: [../somefile.bib]
---

// or:
---
bibliography: []
---
```

This problem only occurs in the bibliography field, as far as I can tell. The following works fine:

```
---
otherfield: []
---
```

I'm not familiar with the internals of Zettlr, but perhaps the square brackets are throwing a parse error somewhere along the bibliography-parsing chain? When I use a single filename rather than an array for the bibliography field, the file opens without problem.

### Reproducing

1. Create a new workspace
2. Create a file with any name, and add YAML frontmatter containing an array of bibliography files (or an empty array, as shown above).
3. Try to open the file
4. Sadness

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura 13.1 (22C65)

### Additional Information

I've tried a bunch of other Zettlr versions, and it seems that this behavior was introduced in version 2.0 — but I'm not 100% sure about that, I didn't rigorously test all the releases.

**Comment by nathanlesage** [comment]
Just saw this issue, sorry for the late reply: Zettlr unfortunately does not support multiple bibliographies in the frontmatter. However, I have now added a fix to account for that: Zettlr internally will use the first bibliography it finds, Pandoc will be able to use all bibliographies.
