### ISSUE TITLE
Buttons, checkboxes and dropdown menu not working in "Graph" section (Zettlr 3.0.0-beta.4)

### ISSUE THREAD

**Issue by neur0b** [Zettlr/Zettlr#4347]
### Description

When viewing the Graph (View Stats -> More stats -> Graph) it's impossible to click on any button, checkbox or to access the drop down menu.

### Reproducing

Open the Graph View under: View Stats -> More stats -> Graph. Once in the Graph View try to click on any checkbox, button or dropdown menu without any corresponding reaction. The checkbox cannot be selected, the dropdown menu cannot be accessed and buttons are not working.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 38 KDE Plasma Spin

**Comment by nathanlesage** [comment]
I noticed there were some styling issues and I remember that I worked on the graph view. It could be that I already fixed this in one of the nightlies, would you mind checking that?

**Comment by neur0b** [comment]
> I noticed there were some styling issues and I remember that I worked on the graph view. It could be that I already fixed this in one of the nightlies, would you mind checking that?

Thanks for your quick answer. I checked the last nightly and it couldn't reproduce the problem, so I think it has been fixed.

**Comment by nathanlesage** [comment]
Wonderful, Thank you for checking it out!
