### ISSUE TITLE
Beta 4 installation incomplete on Debian 11 (64 bits): can’t launch Zettlr.

### ISSUE THREAD

**Issue by benoitvalery** [Zettlr/Zettlr#4348]
### Description

Currently testing the last Zettlr beta version, I found some bugs but before posting about it, I suspect they are related to a primary issue : on Debian 11, the installation of the beta through unpacking the `Zettlr-3.0.0-beta.4-amd64.deb` file with `dpkg` seems not to be complete. The installation (with the command-line) seems to unfold without any trouble, but yet, at the end, no Zettlr application is available, and I’m forced to use the AppImage, which I don’t want to.

Below, the command used : 

```sh
sudo dpkg -i Zettlr-3.0.0-beta.4-amd64.deb
```

I tried to identify what is messing up with a very limited knowledge. I compared the process between with the last stable version (i.e., `2.3.0`). With this version, a Zettlr shortcut appears in the `/usr/bin/` folder, which points to `/opt/Zettlr/Zettlr`. The same happens when unpacking the beta-4, but no icon is available and the only way to launch the application is to get administrator privileges (`sudo`), move to the `/opt/Zettlr/` directory and execute `Zettlr` from the command-line, with restrictions (I applied a workaround mentioned in #4262, maybe related, to be able to execute Zettlr this way, with the following command).

(See also the EDIT below)

```sh
sudo su
(password)
cd /opt/Zettlr/
./Zettlr --no-sandbox --disable-gpu-sandbox --disable-seccomp-filter-sandbox
```

At least I was able to execute it, but anyway: the installation is incomplete, and I’m forced, for now, to use the .AppImage, wich I suspect to trigger some other bugs.

### Zettlr version

3.0.0-beta-4

### Your plastform

Linux Debian 11, Intel 64 bits

### Installation method

Unpack the .deb file (`Zettlr-3.0.0-beta.4-amd64.deb`)

### Reproducing

(Not sure) On Debian 11 (64 bits), just unpack the last `.deb` file with `dpkg -i`. Be sure to remove a potentially older version with `sudo apt remove zettlr` or `sudo apt purge zettlr`.

### Workaround and related bug (EDIT)

A partial workaround is indicated in the #3939 (same or related bug?), just run:

```
chmod -R 755 /opt/Zettlr/
```

and the `/usr/bin/Zettlr` becomes executable. Still the shortcut does not appear.

### Additional information

Thanks for your highly appreciated work.

**Comment by TheElectronWill** [comment]
I've managed to make zettlr work and the icon visible! The desktop database just needed to be updated after fixing the permissions:
```sh
chmod 755 /opt/Zettlr/
sudo update-desktop-database
```

**Comment by nathanlesage** [comment]
Yes, this issue is not going to get fixed unless someone with a Linux machine and some coding experience can take a look at it. I have tried today but figured out I am unable to test for Linux.

**Comment by rebastion** [comment]
still no dice in beta7

**Comment by nathanlesage** [comment]
I now gave it a try to manually run the shizzle on a Debian system. This is how the permissions look like after the package step:

```
total 208388
drwx------ 4 hendrik hendrik      4096 Aug  8 17:38 .
drwxr-xr-x 3 hendrik hendrik      4096 Aug  8 17:38 ..
-rw-r--r-- 1 hendrik hendrik    136579 Aug  8 17:37 chrome_100_percent.pak
-rw-r--r-- 1 hendrik hendrik    197691 Aug  8 17:37 chrome_200_percent.pak
-rwxr-xr-x 1 hendrik hendrik   1246464 Aug  8 17:37 chrome_crashpad_handler
-rwxr-xr-x 1 hendrik hendrik     53840 Aug  8 17:37 chrome-sandbox
-rw-r--r-- 1 hendrik hendrik  10544880 Aug  8 17:37 icudtl.dat
-rwxr-xr-x 1 hendrik hendrik    251064 Aug  8 17:37 libEGL.so
-rwxr-xr-x 1 hendrik hendrik   2877488 Aug  8 17:37 libffmpeg.so
-rwxr-xr-x 1 hendrik hendrik   6435400 Aug  8 17:37 libGLESv2.so
-rwxr-xr-x 1 hendrik hendrik   4565640 Aug  8 17:37 libvk_swiftshader.so
-rwxr-xr-x 1 hendrik hendrik   6396248 Aug  8 17:37 libvulkan.so.1
-rw-r--r-- 1 hendrik hendrik      1096 Aug  8 17:37 LICENSE
-rw-r--r-- 1 hendrik hendrik   8247912 Aug  8 17:37 LICENSES.chromium.html
drwxr-xr-x 2 hendrik hendrik      4096 Aug  8 17:37 locales
drwxr-xr-x 3 hendrik hendrik      4096 Aug  8 17:38 resources
-rw-r--r-- 1 hendrik hendrik   5214565 Aug  8 17:37 resources.pak
-rw-r--r-- 1 hendrik hendrik    259202 Aug  8 17:37 snapshot_blob.bin
-rw-r--r-- 1 hendrik hendrik    578034 Aug  8 17:37 v8_context_snapshot.bin
-rw-r--r-- 1 hendrik hendrik         6 Aug  8 17:37 version
-rw-r--r-- 1 hendrik hendrik       107 Aug  8 17:37 vk_swiftshader_icd.json
-rwxr-xr-x 1 hendrik hendrik 166316624 Aug  8 17:37 Zettlr
```

Looks good to me so far. Then, I ran the release step that takes this directory and creates an executable `.deb`-file from it. I couldn't install that one (because I'm on a server), but this highly suggests the error does not originate from Zettlr, but electron builder.

An accompanying issue is open on the repo since five years with no solution yet: https://github.com/electron-userland/electron-builder/issues/2682

I'm going to try electron-forge next.

Please try out this new package: https://hendrik.zettlr.com/zettlr_testbuild_forge_x64.deb

This is a Debian installer, 64bit Intel architecture (not ARM) off the most recent dev branch (i.e. the same as this Monday's nightly), but this time built via electron forge, not via electron-builder. Please download it and install it, and try out if that fixes the issue (plus, notify me of potential other issues since I had to provide some config options that electron builder does not use).

Here's the config that I used to create that build (I'm especially uncertain about the icon size I had to provide):

```js
{
  name: 'zettlr',
  bin: 'Zettlr',
  categories: [ 'Office', 'Education', 'Science' ],
  section: 'editors',
  description: 'Your one-stop publication workbench.',
  productDescription: 'Your one-stop publication workbench.',
  recommends: [ 'quarto', 'pandoc', 'tex-live' ],
  genericName: 'Markdown Editor',
  icon: './resources/icons/png/96x96.png',
  priority: 'optional',
  mimeType: [ 'text/markdown', 'application/x-tex', 'application/json', 'application/yaml' ],
  maintainer: 'Hendrik Erz',
  homepage: 'https://www.zettlr.com'
}
```

**Comment by rebastion** [comment]
Your deb installs fine on my machine, correctly sets it up and creates an icon to launch the app. It also launches without problem. Yay.

**Comment by nathanlesage** [comment]
Perfect, then give me a few minutes to properly implement the forge builds (I'm gonna switch the entire Linux pipeline, makes things easier to maintain) and then we can see how the next nightly's are going. Maybe we can dump builder for good.

**Comment by nathanlesage** [comment]
After some back and forth, the build process now works; proper packages are available here and with the next beta: https://nightly.zettlr.com/
