### ISSUE TITLE
Duplication of ' #' character when using hashtag quicksearch

### ISSUE THREAD

**Issue by neur0b** [Zettlr/Zettlr#4349]
### Description

When I type the '#' character a letter in order to search through hashtag the '#' is duplicated at the beginning of the word, creating _de facto_ a new tag.  (See attachments)

<img width="563" alt="screen_zettlr1" src="https://github.com/Zettlr/Zettlr/assets/105542684/e187e765-4610-4933-9fc8-81f4d5602e1e">
<img width="352" alt="screen_zettlr2" src="https://github.com/Zettlr/Zettlr/assets/105542684/73f5b871-6101-4940-a1fb-bc47410e6e52">

### Reproducing

type the '#' character, followed by a letter in order to trigger the tag quicksearch. 
Select a suggestion from the dropdown windows.
See the duplication of the '#' character.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 38 KDE Plasma Spin

**Comment by benoitvalery** [comment]
Surely related to the fact that any tag added manually (via a # outside the YAML header) is rendered with a double hashtag into the file properties (Linux Debian 11, Intel 64 bits).

**Comment by neur0b** [comment]
> Surely related to the fact that any tag added manually (via a # outside the YAML header) is rendered with a double hashtag into the file properties (beta4, via .deb file, Linux Debian 11, Intel 64 bits). So for instance if one hit `#keyword` into a file, the file property will show `##keyword`.

Thank for you answer. Should I assume that it's a normal behaviour?

**Comment by benoitvalery** [comment]
No @neur0b, I just wanted to complete the issue by describing one of its consequences that I observed on my side. It’s not a normal behavior.

**Comment by nathanlesage** [comment]
This has been fixed by a recent PR – however, you need to clear your FSAL cache, you can do so by quitting Zettlr, and then going to config directory ([see docs for path](https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app)) and remove the `fsal` folder, then relaunch. May take a while to rebuild the cache.
