### ISSUE TITLE
list breaks code block

### ISSUE THREAD

**Issue by derWalter** [Zettlr/Zettlr#4357]
### Description

if I start a codeblock with " ` " then the text from there on gets a grey background and a monospace font.
but as soon as the codeblock reaches a list, it stops with marking the text as code, which is a shame,
as I use this also as a visual element to highlight or distinct text parts. 

### Reproducing

write some text and mark parts of it as code with " ` " and put a list in the middle of it

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 11

### Additional Information

I've checked all open issues, but couldn't find it reported.

**Comment by nathanlesage** [comment]
This is desired behavior according to spec: Certain block level elements force-end inline-elements, and list items are just such an element.
