### ISSUE TITLE
Custom CSS margin stopped working in 3.0 beta

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4358]
### Description

Previously, I have reported about [custom CSS not working in 3.0 beta](https://github.com/Zettlr/Zettlr/issues/4308). I thought custom CSS just completely stopped working, which was not the case.

Upon further investigation, I realised that only custom CSS margin/maximum width stopped working since the beta version.  Here is the margin css file I use:

```
#editor {
  --side-margin: calc( 0px ); 
}

#editor .CodeMirror {
  margin-left: var(--side-margin);
}

#editor .CodeMirror-scroll {
  padding-right: var(--side-margin);
}

#editor.fullscreen {
  --side-margin-fullscreen: calc( 0px ); 
}

#editor.fullscreen .CodeMirror-fullscreen {
  margin-left: var(--side-margin-fullscreen) !important;
}

#editor.fullscreen .CodeMirror-fullscreen .CodeMirror-scroll { 
  padding-right: var(--side-margin-fullscreen) !important; 
```

Can you please look into this? Thank you!

### Reproducing

See above.

### Zettlr Version

Beta (if applicable)

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Silverblue

**Comment by nathanlesage** [comment]
This is not a bug. In the Changelog I Outline that a lot of the DOM structure and class names have changed in the migration of CodeMirror 5 to 6. Now, for example, there is no `.CodeMirror-scroller` anymore but (afaik) `.cm-scroller`. You can still apply custom CSS but you'll have to research the corresponding new class names and elements yourself using the method outlined in the docs.

Oh, and `#Editor` ist also gone, it's now a class that you can find using inspect element.

**Comment by sith-on-mars** [comment]
Thanks a lot for explaining! I would be great if the document could be updated one day accordingly.

**Comment by nathanlesage** [comment]
There is currently a task force en route to fully upgrade the documentation.
