### ISSUE TITLE
Using single quotation mark creates spelling mistakes for the last word sometimes 

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4359]
### Description

If I use single quotation mark, sometimes the last word inside the quotation mark is considered having spelling mistake. For example:

![image](https://github.com/Zettlr/Zettlr/assets/37974764/877cbb04-33ef-4672-a6dc-d8e307e10754)

And here is the result if you correct the word based on spellcheck's suggestion:

[Screencast from 2023-05-20 18-50-12.webm](https://github.com/Zettlr/Zettlr/assets/37974764/b1d80b38-33d4-4a67-a270-bb6156026458)

There is no such problem if I use the double quotation mark.

### Reproducing

See above

### Zettlr Version

Beta (if applicable)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Silverblue

**Comment by sith-on-mars** [comment]
I still have the issue on beta 5. Can you please reopen it?

**Comment by nathanlesage** [comment]
It could be that I fixed it right after beta.5, then it's in the nightly, would you mind checking? (Same with the other issues you have commented)

**Comment by sith-on-mars** [comment]
I confirm that the issue is fixed in the nightly.
