### ISSUE TITLE
Fresh installation with visualizing and opening folders problem

### ISSUE THREAD

**Issue by filippogambarota** [Zettlr/Zettlr#436]
Hi, I'm trying Zettlr for the first time. I've read the documentation but I'm not able to find a problem in my approach so maybe is a OS problem or something else.
I'm on windows 10 using the 1.5.0-beta.2 version (I've also tried with the version on the official website instead of the github repo). The problem is that if I try to open a new folder or create a new file nothing happens. On the left I cannot see any folders or files but only "no files or folder".
I've tried to drag and drop a folder but it doesn't work. How can I do?

**Comment by nathanlesage** [comment]
Could it be that you tried to open a folder with more than seven or eight sublevels? If so, there's currently an issue within the Electron core which needs to be resolved — currently it does not support nesting that much, and we all hope the team will implement the bugfix soon. Is that the problem, that is: do freshly created, empty directories work? (It might be that you have to remove the `config.json` prior from the AppData directory)

**Comment by filippogambarota** [comment]
thanks for the answer. I've read about this problem of handling complex and nested folders but I've tried with one empty folder with the idea to use it as main folder.

**Comment by nathanlesage** [comment]
Alright, I've just tested it with a clean install (a.k.a. fresh config), but I had no problems opening the folders — could you please have a look at the logs (Debug mode on in Preferences and then Develop -> Logs) and see whether there's some activity after trying to open something?

**Comment by dbux** [comment]
I'm having the same issue, on Pop!_OS 19.10, on both 1.4.3 and 1.5.0-beta.2 versions of Zettlr. I'm just trying to load a test folder containing three small Markdown documents and nothing appears in the sidebar (just persistently states "No directory selected" and/or "No open files or folders")

The contents of my log file:

> [13:12:40]` [Info] こうんいちわ！　Booting Zettlr at Thu Dec 19 2019 13:12:40 GMT+0000 (Greenwich Mean Ti>
> [13:12:40] [Info] Electron reports ready state. Instantiating main process...
> [13:12:40] [Warning] The translation string was malformed: Open Logs!
> [13:12:43] [Info] No command registered with the application for command get-tags
> [13:12:44] [Info] No command registered with the application for command get-tags-database
> [13:12:44] [Info] No command registered with the application for command get-paths
> [13:12:44] [Info] No command registered with the application for command citeproc-get-ids
> [13:12:47] [Info] No command registered with the application for command dir-open
> [13:12:52] [Info] No command registered with the application for command win-menu
> [13:12:52] [Warning] The translation string was malformed: Open Logs!
> [13:16:42] [Info] No command registered with the application for command handle-drop

**Comment by nathanlesage** [comment]
So at least we know no error is produced in the main process. Maybe after trying to open there are errors written to the console of the developer tools (Develop -> Open Dev Tools)?

**Comment by dbux** [comment]
Here's what I get in the dev console after trying to open a directory (either from File > Open or by dragging it into the main window):

> /opt/Zettlr/resources/app.asar/renderer/zettlr-renderer.js:293 Uncaught TypeError: this._paths is not iterable
>     at ZettlrRenderer.findObject (/opt/Zettlr/resources/app.asar/renderer/zettlr-renderer.js:293)
>     at ZettlrRenderer.setCurrentDir (/opt/Zettlr/resources/app.asar/renderer/zettlr-renderer.js:599)
>     at ZettlrRendererIPC.handleEvent (/opt/Zettlr/resources/app.asar/renderer/zettlr-rendereripc.js:303)
>     at ZettlrRendererIPC.dispatch (/opt/Zettlr/resources/app.asar/renderer/zettlr-rendereripc.js:202)
>     at EventEmitter.<anonymous> (/opt/Zettlr/resources/app.asar/renderer/zettlr-rendereripc.js:72)
>     at EventEmitter.emit (events.js:203)
>     at Object.onMessage (init.ts:50)
> findObject @ /opt/Zettlr/resources/app.asar/renderer/zettlr-renderer.js:293
> setCurrentDir @ /opt/Zettlr/resources/app.asar/renderer/zettlr-renderer.js:599
> handleEvent @ /opt/Zettlr/resources/app.asar/renderer/zettlr-rendereripc.js:303
> dispatch @ /opt/Zettlr/resources/app.asar/renderer/zettlr-rendereripc.js:202
> (anonymous) @ /opt/Zettlr/resources/app.asar/renderer/zettlr-rendereripc.js:72
> emit @ events.js:203
> onMessage @ init.ts:50

**Comment by nathanlesage** [comment]
Ahhh perfect, this log output looks promising in finding out the error! I‘ll be on vacation until next year, but I‘ll get to it asap then!

**Comment by nathanlesage** [comment]
Oh, one more thing, after that error message, could you please run the command “renderer._paths” and tell me what the output looks like? Hopefully this will then lead to a very quick (New Years) resolution!

**Comment by dbux** [comment]
Ahh I'm also now away from my work machine until the new year, but I'll try that when I return in January and let you know!

**Comment by dbux** [comment]
Running `renderer._paths` after the error message simply returns `null`

**Comment by nathanlesage** [comment]
Ouhh, that's not good, because this indicates that either an error during transfer occurred, or the loaded files and folders haven't at all been transferred to the renderer :(

**Comment by zerreo** [comment]
Hello
same problem for me:
- new install Zettlr version 1.5 on Windows 10 (looks like I had some problem with the previous one)
- no file or folder view
- cannot create any file !!
- no saving file
app is unusable :(

**Comment by nathanlesage** [comment]
Mhh... and removing the `config.json` from the application data directory does not solve the problem?

**Comment by zerreo** [comment]
All data has been manually deteted from data directory, fresh install.
I even tried to change directory, but now:
```
Error opening file for writing
C:\Program Files\Zettlr\Uninstall Zettlr.exe
```
Not possible to reinstall the beast.
Windows 10 is maybe getting really buggy nowadays..

**Comment by zharijs** [comment]
Hi. I had same issue (folders not loading / files not showing up in side bar) with 1.4.x and 1.5 versions. Here's how I fixed it:

1. Uninstall all versions of Zettlr
2. Manually delete  remaining AppData
2.1. Delete C:\Users\[user_name]\AppData\Roaming\Zettlr\
2.1. Probably not necessary, but I also deleted C:\Users\[user_name]\AppData\Local\zettlr-updater\
3. Install Zettlr 1.5 

**[Issue solved]** everything works fine now. Did not look more into it, but probably nothing to do with windows, but some settings tags have changed between zettlr or likely electron versions that crashes the loader / renderer if old config from 1.3 version is present. 

**[Suggestion]**  Maybe make installer check if older version config exists and delete it on update-install. Or as a dirty fix - just make installer delete the AppData folder for Zettlr. Loosing old settings is less painful than having it not working, especially for new / inexperienced users / students.

**Comment by nathanlesage** [comment]
Thanks for sharing, but I am extremely confident that this has nothing to do with the app. Why? Because when adding new config options and changing the structure, the app will always throw away everything that does not look good and add the new stuff, so it won't be the config.

What is way more likely, because we've had this in the past, is that something in Electron changed that conflicted with other cache things, because in the AppData-folder there are also a lot of files generated by Electron, not only those from the app itself!

**Comment by zharijs** [comment]
@nathanlesage I have no experience programming with electron, but that does sound likely or at very least reasonable, yes. Then maybe you can just flush the AppData folder altogether when updating? Or if this is the case, maybe just flush the electron files on install - that's even better as you would keep the older config.

**Comment by zharijs** [comment]
PS: if you want me to test it at some point, I still have 1.3 on other machine with same issues updating. I have no problem sitting on that if you want me to test the updated installer at some point later.

**Comment by nathanlesage** [comment]
Mh, the updater unfortunately gives me no ability to clean out the AppData directory — besides I believe that this was a temporary issue that appeared due to some incompatible updates in Electron somewhere between Electron 5 (Zettlr 1.3) and Electron 7 (Zettlr 1.5), so for now I hope that these are only temporary issues …

**Comment by zerreo** [comment]
Okay, thank you for your help, but i'm still stuck.
I deleted all files in Appdata (roaming and local), but it didn't help.
A fresh zettlr 1.5 install get aborted like this:
![image](https://user-images.githubusercontent.com/33457675/72219935-c6105580-354b-11ea-815a-273d001acf26.png)
I'll wait patiently for the next release :)

**Comment by zharijs** [comment]
Oh, well, in that case, for anyone still having this problem - just run this from **start -> run** window before installing 1.5:
`cmd /c rmdir /q /s  %appdata%\Zettlr\`

**Comment by zharijs** [comment]
@zerreo I would delete manually the zettlr folder form program files too and try again. If that does not help, I'd re-download the 1.5 installer - maybe you have it corrupted..

**Comment by nathanlesage** [comment]
What, I've never heard of the installation freezing o_O This looks serious

**Comment by zerreo** [comment]
@zharijs 
no zettlr folder in appdata or both program files pathes.
new fresh download of Zettlr-1.5.0.exe
same bug.
What strange is that even after uninstalling Zettlr (no more files), it appears in the "add or remove Program". But not possible to get rid of it:
![image](https://user-images.githubusercontent.com/33457675/72224421-c116ca80-357a-11ea-91d1-faacf68dbbec.png)

**Comment by nathanlesage** [comment]
@zerreo This is due to wrongly removed keys in the Windows registry. This happens sometimes on Windows, unrelating the app.

**Comment by zharijs** [comment]
I noticed that it did not disappear from add/remove apps list in my case too, but 1.5 still installed over with no problems.

**Comment by zerreo** [comment]
@zharijs Good news. At first I had no problem reinstalling. But then I installed older Zettlr version (because of the opening folder problem), same problem, and come back with de 1.5
But now unable to install.

**Comment by sdstrong** [comment]
I was having the same/similar problem using Zettler 1.5 (fresh install- no prior installation of other versions) on Mac OS 10.14.6. I could see notes in the editing pane (and follow links— Zettler opens with the most recently viewed note displayed), but there was no list of notes on the left-hand side. 

The issue resolved after deleting `config.json` located at 
`~/Library/Application\ Support/zettlr/config.json`.

Some more info on app behavior:
Before deleting `config.json`, I re-opened the directory, and Zettler displayed notifications "opening new root zettelkasten" and "zettelkasten has been loaded" (the name of the directory is 'zettelkasten'), but the left-hand pane still read 'no directory selected.'

The linking previewer also didn't work (I attempted to enter a new link in the editor, but no list of notes appeared), but I was still able to follow links to different notes, and I could create new links to other notes by ID. The search filter still worked, but did not display any results in the left-hand pane.

Clicked on a link I created to this note, which put the ID in the filter box, and displayed the note:
![0 2 Organizational Systems md 2020-01-16 11-35-35](https://user-images.githubusercontent.com/59975373/72556842-5f917d00-3854-11ea-89d8-98e7ddcc2c3d.png)

After clearing the filter:
![0 2 Organizational Systems md 2020-01-16 11-36-53](https://user-images.githubusercontent.com/59975373/72556910-82239600-3854-11ea-9afb-8c914fb21e4b.png)

**Comment by nathanlesage** [comment]
It looks as if the view is the problem — if you go on the top-left corner of the list, an arrow should appear letting you select a directory!

**Comment by tone1** [comment]
I'm having the same issue with Zettlr 1.6.0 and macOS 10.15.5. Installed it for the first time and I'm unable to create a new directory or a new file. Nothing happens when I try. I deleted config.json but didn't make a difference. Does anyone have any suggestions?

**Comment by leventemo** [comment]
I had the same problems when going from v1.6 to v1.7.1 on MacOS 10.12.6: I was unable to see and handle my files and folders in the sidebar/pane on the left.

Deleting the config.json file at ~/Library/Application\ Support/zettlr/config.json, as suggested by sdstrong  on Jan 16 (see above), sorted it out.
