### ISSUE TITLE
Duplication of footnotes between panels

### ISSUE THREAD

**Issue by neur0b** [Zettlr/Zettlr#4361]
### Description

I often work with two panels open, on the right I usually look at the notes and on the left I write my article. When I click on "footnote" (since I write for journals I have to use footnotes a lot) a footnote is created in both panels: on the one on which I'm currently writing and on the other one, where I'm only reading the notes I took.

### Reproducing

Open two different panels. Place the cursor on the panel in which you actually want to write something. Click on "footnote". A footnote is created in both panels.

### Zettlr Version

Nightly

### Specify version

Zettlr 3.0.0-beta.4.nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 38 KDE Plasma Spin

**Comment by neur0b** [comment]
See the attachment below:

<img width="960" alt="screen_zettlr" src="https://github.com/Zettlr/Zettlr/assets/105542684/8330595a-2d1d-4404-96c7-b22a8b95a6ee">


PS. I can reproduce the bug almost always. Sometimes when I create new notes the bug doesn't show, so I cannot identify what triggers it.

**Comment by lcsolano** [comment]
This is happening to me not only with footnotes. It also happens when inserting an image, a link, etc.

https://github.com/Zettlr/Zettlr/assets/19916268/6d100ffc-8630-4aba-845c-0249599baf88

**Comment by nathanlesage** [comment]
This is an apparent bug that I didn't fix in one of my recent patches -- this seems to happen with any Toolbar button.
