### ISSUE TITLE
Zettlr sometimes stops creating footnotes

### ISSUE THREAD

**Issue by neur0b** [Zettlr/Zettlr#4362]
### Description

I don't really know how to reproduce the bug, but while I was working on a article I noticed that when I try to create a footnote it is just "graphically" created, but it doesn't actually work. If I place the mouse on the footnote index the pop-up just says: "No footnote text", and of course if I try to export the document all the footnotes, starting from the first one which didn't work, are not imported. 

### Reproducing

I don't know how to reproduce it because I don't know what actually caused it. If I create a new document the footnotes work again but I can't copy the text of the old document, since it means that I have to write all the article from the start.

### Zettlr Version

Nightly

### Specify version

Zettlr 3.0.0-beta.4.nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 38 KDE Plasma Spin

**Comment by nathanlesage** [comment]
I need more information to verify this bug, maybe some code example of what doesn't work. A footnote cannot be "graphically done but not work", this could be a syntax error produced by the footnote insertion logic, but for that, as I said, I will need more information.

**Comment by MaPeras** [comment]
Happens to me, too. Somehow, it starts, when I reach footnote 10.

Zettlr 3.0.0-beta.6

Need anything else?

---

From the Logs:
[20:43:43]
[R] [Main Window (04fb5c67-009e-47f7-aa37-eb8d736b81d7)] RangeError: Invalid line number 0 in 1-line document (index.js:2)
[20:43:44]
[R] [Main Window (04fb5c67-009e-47f7-aa37-eb8d736b81d7)] RangeError: Invalid line number 0 in 1-line document (index.js:2)
[20:43:53]
[R] [Main Window (04fb5c67-009e-47f7-aa37-eb8d736b81d7)] RangeError: Invalid line number 0 in 1-line document (index.js:2)


---

# Title

Here is some text.[^1]

More Text.[^2]

More Footnotes. [^3]
More Footnotes.[^4]

[^5]
[^6]
[^7]
[^8]
[^9]
[^10]

[^1]: First footnote.

[^2]: Second footnote
[^3]: Okay 

[^4]: asdf
[^5]: asdf

[^6]: asdf

[^7]: asdf

[^8]: asdf

[^9]: adsf

[^10]: Does not work
