### ISSUE TITLE
Keywords not recognized in YAML frontmatter

### ISSUE THREAD

**Issue by dandennison84** [Zettlr/Zettlr#4366]
### Description

```
—-
keywords: [foobar]
—-

Some Text
```
No variation of keywords are recognized: [foobar], foobar, - foobar. Changing keywords to tags doesn’t work either. Adding #foobar outside the frontmatter works.

### Reproducing

Copy minimal md above.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta 4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by dandennison84** [comment]
I should update that the release version works fine. The beta has broken the behavior.

**Comment by UFOMelkor** [comment]
I would guess there is something missing in the [https://github.com/Zettlr/Zettlr/blob/e920dee0741641c82707e04a30d9002ecb74d00a/source/app/service-providers/fsal/util/file-parser.ts#L118](file-parser).

Perhaps something like this

```typescript
      if (file.frontmatter.tags) {
        for (let i = 0; i < file.frontmatter.tags.length; i++) {
          if (!file.tags.includes(file.frontmatter.tags[i])) { file.tags.push(file.frontmatter.tags[i]) }
        }
      }

      if (file.frontmatter.keywords) {
        for (let i = 0; i < file.frontmatter.keywords.length; i++) {
          if (!file.tags.includes(file.frontmatter.keywords[i])) { file.tags.push(file.frontmatter.keywords[i]) }
        }
      }
```

But there would still be a cache problem, as the old entries are cached and would not recognize the tags from frontmatter.

**Comment by nathanlesage** [comment]
> But there would still be a cache problem, as the old entries are cached and would not recognize the tags from frontmatter until the cache is cleared once.

Just saw this comment of yours: No worries, since it will check if the file has been modified, and only use the cache if the modtime of the file is exactly the same as the one from the cache, so no worries about that!
