### ISSUE TITLE
Zettlr doesn't work in elementaryOS (Ubuntu)

### ISSUE THREAD

**Issue by abrahambahez** [Zettlr/Zettlr#437]
## Description
After installation of the `.deb` file the app just shows anything

## Reproducing
I've installed the `.deb` version of the app in ElementaryOS Hera, using `sudo apt install <path/to/file.deb>` but when I ran it, it looks like if it were working but nothing is showed. In the screenshot attached, the bug can be better appreciate, the dark background of the top bar indicates an active app (in this case Zettlr), but nothing is showed.

## Expected behaviour
Running normally

**Screenshots**
![Screenshot from 2019-12-18 09-42-14](https://user-images.githubusercontent.com/53906659/71101335-20e8a400-217c-11ea-995f-dc5a77e978dd.png)

## Platform
 - OS and version: ElementaryOS 5.1
 - Zettlr Version: 1.4.3
 - Screen Resolution: 1366x768px

**Comment by nathanlesage** [comment]
I'm getting the impression that all of these bugs with custom Linux distributions pertain to something deeper within the Electron framework. It's certainly nothing with the sole codebase of Zettlr, as in that case it would not run on linux platforms at all. It might be some packages are missing, but I cannot be completely sure. The only thing that seems certain is that on Debian, Ubuntu, and Xubuntu Zettlr works out of the box …

So I'm somewhat unsure whether I could be of help at all :/

**Comment by ploum** [comment]
You could try to run Zettlr from a terminal and see what is displayed there

**Comment by nathanlesage** [comment]
> You could try to run Zettlr from a terminal and see what is displayed there

With the avalanche of logging I've smashed into 1.7 beta this might even work hehehe
