### ISSUE TITLE
Directory sort order not working as expected for Fogelzettel IDs as filenames

### ISSUE THREAD

**Issue by dandennison84** [Zettlr/Zettlr#4371]
### Description

I would expect Natural sort order to provide the following order with Fogelzettel numbers as filenames:
`1_1a
1_1a1
1_1a1a
1_b`

This works on my current OS (Windows 11 directory).

Zettlr provides the following directory order (with either sort toggle, natural or ascii):
`
1_1a1
1_1a1a
1_1a
1_1b
`

### Reproducing

As above. Just create the named files in an empty directory.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
Would you mind testing out the most recent beta to verify if this is still an issue right now?
