### ISSUE TITLE
Incorrect spell check

### ISSUE THREAD

**Issue by perekoo** [Zettlr/Zettlr#4373]
### Description

I have installed Zettlr and activated the German spell checker. Unfortunately, I get a lot of errors, even though they are known and undoubtedly correctly spelled terms. If I add these terms to the dictionary, they are deposited in the dictionary, but still marked as wrong.

### Reproducing

This German (nonsensical) sentence: "Ein kühler Wind würde ein Schauspiel sein." shows me errors at: "kühler",  "würde", "Schauspiel" und "sein", although these are common terms.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 (22H2)

**Comment by nathanlesage** [comment]
Are you 2.3? If so, there has been a major upgrade in the dictionary loader for the current betas, there is a good chance the problems are much lighter or even went away in the current betas. Would you mind trying them out?

**Comment by perekoo** [comment]
With the beta 4 of the spell checker runs correctly. Unfortunately the scrolling in the table of contents doesn't work there anymore. I am creating a new bug report for this.

**Comment by nathanlesage** [comment]
> Unfortunately the scrolling in the table of contents doesn't work there anymore. I am creating a new bug report for this.

I think I fixed that already some time ago, likely after beta.4

**Comment by perekoo** [comment]
Thanks for the tip. Since I plan to use Zettlr productively for a novel, I'd rather wait (with some anticipation) for the next beta release.
