### ISSUE TITLE
Scrolling in the table of contents

### ISSUE THREAD

**Issue by perekoo** [Zettlr/Zettlr#4376]
### Description

In version 2.30 scrolling a longer table of contents still worked, in beta 4 of version 3 nothing happens when scrolling.

### Reproducing

Create an arbitrary file with a sequence of headings until the table of contents no longer shows all of them. Scrolling to the last headings in the table of contents is then no longer possible.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 22H2

**Comment by sarahtelford** [comment]
I have tried to replicate this issue. Can you please specify how may how many heading to create? I have created 1000+ headers and am not experiencing any issues.

**Comment by perekoo** [comment]
I produced just enough nested! headings that scrolling was necessary. Significantly less than 1000.

**Comment by nathanlesage** [comment]
Ah, I fixed that a few weeks ago, belongs to a set of layouting issues I resolved – next beta is building right now.
