### ISSUE TITLE
[Question] Where is configuration stored?

### ISSUE THREAD

**Issue by ttdtrang** [Zettlr/Zettlr#438]
It seems Zettlr is storing config information somewhere independent of the installation, but I couldn't find it anywhere. I scoured Zettlr's documentation and github issues and found the mention of a _config.json_ file in _Application Support_, but couldn't find it on my system.
Where is Zettlr storing this config file and is there a way to configure where it should be stored?
Thanks!

**Comment by nathanlesage** [comment]
All installation-independent files such as `config.json`,  `stats.json`, log files, or dictionaries are stored within the application data directory on your operating system. This path is not the same throughout the different OSs. Please have a look at the documentation, for each operating system the respective paths are outlined: https://docs.zettlr.com/en/install/
