### ISSUE TITLE
New files not appearing in Zettlr File Manager

### ISSUE THREAD

**Issue by jamalainm** [Zettlr/Zettlr#4382]
### Description

When I create a new file via the '+' button or the file menu and save it in a subdirectory of my workspace the file does not appear in the Zettlr File Manager. 

If I right click on the file manager to create a new file, it will appear there, but adding a title will not change the appearance of the file in the Zettlr File Manager (e.g., I created a test file that was immediately named '20230528172047', and I gave it the title: starting the file with 3 hyphens, followed by 'title: testing functionality' and three periods below that.

If I close the workspace and open it again everything appears as it should, but the File Manager does not update its view as new files are created.

### Reproducing

Create a new file within Zettlr with the '+' button or the 'File > New File...' menu.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian 11

**Comment by nathanlesage** [comment]
Sorry for my late response, just saw this -- would you mind trying out the most recent beta release, and confirm whether this happens also there?

**Comment by nathanlesage** [comment]
Assuming this to be fixed in the current v3.0 branch
