### ISSUE TITLE
Flickering, loss of drop-shadow, no window borders on Linux distros in Gnome and Wayland

### ISSUE THREAD

**Issue by jchalifour** [Zettlr/Zettlr#439]
While using Linux with Wayland and Gnome, the Zettlr application has two fairly noticeable problems. The first is that it loses its overall shadow and because it lacks any sort of window decoration or border, it ends up blending in flat with whatever is behind it. This makes it really difficult to distinguish from other applications that are in use and hard to know where to click to move the window. 

The second issue is that resizing the window makes the whole application flicker. 

Both of these issues do not happen if Xorg is used rather than Wayland. 

Start a Linux, Gnome session in Wayland and launch Zettlr

It would be great if Zettlr used the regular window decorations / header and borders so it behaved like other Gnome applications and was more manageable. (Zettlr is a super promising application!)

**Screenshots**

## Platform
 - OS and version: Manjaro 18.1.4 Gnome edition & the exact same issues happen on Ubuntu 19.10 Gnome
 - Zettlr Version: 1.4.3 and 1.5
 - Screen Resolution: 3840x2160 (but it's the same at other resolutions)

**Comment by nathanlesage** [comment]
Closing to unify the necessary discussion on this issue over at #448!
