### ISSUE TITLE
Buggy behaviour in rearranging windows

### ISSUE THREAD

**Issue by sarahtelford** [Zettlr/Zettlr#4399]
### Description

**Expected behavior:** Rearranging the pane's will dynamically adjust to meet the desired layout. 

**Buggy behavior:** When dragging a window into a new pane section. The pane-creation zone will highlight and remain visible after releasing cursor. 

### Reproducing

1.Open at least three notes, so that your window shows the notes as adjacent tabs in a single pane.
2.Open a second pane by drag/dropping one of the notes/tabs into the zone that will have that effect, at the bottom of the current note.
3.Attempt to drag an the third tab to between the two existing tabs, a pane-creation zone will appear in both existing pane's.  
4.After the cursor reaches the intended zone, and you "drop" the tab there by releasing the mouse button, both zones will remain highlighted and the layout will not change.
5.Sometimes it's possible to make the highlighted zone disappear by dragging another tab across that zone (recreating step 3).

### Zettlr Version

Right off the develop branch

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

macOS Ventura

### Additional Information

<img width="1147" alt="Screenshot 2023-06-06 at 9 17 18 am" src="https://github.com/Zettlr/Zettlr/assets/84111693/df2602e9-93c4-4979-9b7f-2ec32a95e374">

**Comment by exanrauzer** [comment]
Hi! I encourage you to use gifcap.dev to record the issue. One gif is worth a thousand of images;)

**Comment by nathanlesage** [comment]
@exanrauzer No need for a screencap, I know what is causing this issue. I just don't have a proper way of mitigating this yet.
