### ISSUE TITLE
Contextual menu doesn't work in the cells of a table

### ISSUE THREAD

**Issue by ProgrammingBoulderer** [Zettlr/Zettlr#4400]
### Description

When using the contextual menu bold shortcut actions in the cells of a table, the elements **** that would make the text bold will be printed outside of the cell where the caret was last placed outside the table. This bug also applies for all contextual menu shortcut actions

### Reproducing

Bold example

1) Create a table
2) Add data to the cell (numbers or words)
3) Highlight the data
4) Right click to open contextual menu
5) Choose any of the shortcut actions
6) In this example choose the bold shortcut
7) Upon clicking, four asterisks will be printed out outside of the table where the caret was lasted placed before accessing the cell of the table.

This applies to all shortcut actions in the contextual menu

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0 Beta

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

<img width="959" alt="Method1" src="https://github.com/Zettlr/Zettlr/assets/100819917/7a55e28b-eea2-4063-af67-13c9cdc3fa5d">

<img width="960" alt="Method2" src="https://github.com/Zettlr/Zettlr/assets/100819917/6cedd881-765c-4277-8e9c-6f59113d955f">

**Comment by nathanlesage** [comment]
Fixed recently.
