### ISSUE TITLE
Zettlr doesn't syntax-highlight section references without square brackets.

### ISSUE THREAD

**Issue by leventov** [Zettlr/Zettlr#4404]
### Description

This issue: https://github.com/jgm/pandoc/issues/5099 seems to still affect the latest version of Zettlr. `(@sec:foo)` is not highlighted, only `([@sec:foo])` is highlighted.

### Reproducing

See above

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS

**Comment by nathanlesage** [comment]
Would you mind trying this out on the most recent beta, which'll be released in a few minutes? Just to confirm whether it's happening there as well.

**Comment by nathanlesage** [comment]
Just tried it out myself, works like a charm.
