### ISSUE TITLE
Incorrect Arrow Key Identifiers 

### ISSUE THREAD

**Issue by Kinack987** [Zettlr/Zettlr#4407]
### Description

Currently, the source code uses key identifiers in the form of 'Up' and 'Down' instead of 'Arrow-Up' and 'Arrow-Down'.
It is specified in the codemirror documentation that key identifiers should be as they appear in the Mozilla docs. 
Excerpt from codemirror documentation: "Key identifiers are based on the strings that can appear in [`KeyEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)."

Any key identifiers using the codemirror API that use arrow keys written in the wrong form will not currently be functional.

### Reproducing

I have noticed this issue in the keymap.ts file under '\source\common\modules\markdown-editor\commands\keymap.ts'. There are two lines which use incorrect key identifiers for arrow keys (Lines 47 and 48 at time of writing).
PR #4406 fixes this issue for the two cases in keymap.ts, however, I am not sure if this issue exists elsewhere as well so I'm opening this issue so that it can be addressed comprehensively if necessary, or in case PR #4406 is not accepted.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 v22H2

**Comment by nathanlesage** [comment]
Fixed by #4407
