### ISSUE TITLE
Update problem: "beta 1.5 more recent  than  stable 1.5"

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#441]
There was problem when updating on Ubuntu 18.04 to the latest version - system packager manager was saying that the  latest beta was more recent than stable 1.5 release.

I needed to uninstall beta  version in order to update Zettlr.

**Comment by nathanlesage** [comment]
Someone else mentioned this problem a while ago. The problem, if I'm not mistaken, lies within the Semver implementation on Ubuntu, which seems to evaluate `1.5.0-beta.1` to be greater than `1.5.0`. Nevertheless, the versioning of Zettlr strictly adheres to [the official semver specifications](https://semver.org/), so unless the `apt`-mechanisms aren't altered I fear this will remain.

[Here's the link](https://jubianchi.github.io/semver-check/#/%3E1.5.0-beta.1/1.5.0) to a check that `1.5.0` is indeed higher than `1.5.0-beta.1` for SemVer.
