### ISSUE TITLE
Settings dialog in Windows displaying code rather than text for some options

### ISSUE THREAD

**Issue by TraceyC77** [Zettlr/Zettlr#4411]
### Description

Some options in the preferences dialog show the code name rather than the human readable text
Ex: dialog.preferences.dark_mode

Version: 2.3.0 (up to date)
OS: Windows 10 installed via chocolately

I do not see this problem with Zettlr on Solus Linux, installed through flatpak

### Reproducing

Open Zettlr and go to File - Preferences. On the main page, see the first entry (as shown in the screenshot). There are others on other tabs.

### Zettlr Version

Stable (most recent version)

### Installation Method

Chocolatey

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by TraceyC77** [comment]
![zettlr_win10_preferences](https://github.com/Zettlr/Zettlr/assets/10402612/ee1034c0-b917-4b5a-b55d-c3a61041d585)

**Comment by nathanlesage** [comment]
That is not code, that is an ID from the old system. It has been replaced with a more robust translation system in the current betas. If you would like to see the improvements, I invite you to try out the betas, which you can find here on GitHub in the releases section.
