### ISSUE TITLE
[3.0.0-beta-4] Exporting a project to latex-pdf mixes up notes

### ISSUE THREAD

**Issue by Aktemon** [Zettlr/Zettlr#4413]
### Description

Trying out the beta-4, I noticed that a project exported to latex-pdf got the notes from the different files all mixed up in the output document (e. g. note 2 from file 3 now appears as note 2 for a section in file 1). 

I did not previously experience this behaviour : I exported said project again on the stable release, and the notes in the output were in the expected order.

On the stable release, a note having the same reference number as another note in a separate file is normally distinguished and renumberd in the output document according to the order of their appearance.

### Reproducing

1. Create a project with several files
2. Add some distinct notes in each file, with shared note-numbers (note 1, 2, 3 in file 1, same in file 2, etc)
3. Export to latex-pdf

I couldn't reproduce the bug myself with this method: beta-4 did not allow me to set a new folder as a project. 

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta-4

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 21 Vanessa

**Comment by nathanlesage** [comment]
> I couldn't reproduce the bug myself with this method: beta-4 did not allow me to set a new folder as a project.

That was a different bug, I just fixed it – it should be shipped with tomorrow's nightly. Regarding your other problem: Could you provide us with a set of minimal files including contents to trace this issue?

It is sufficient to just write out what files we would need to create, so that we avoid having to upload/download zip files here.

**Comment by Aktemon** [comment]
I should have provided a minimal (non) working example from the start, sorry for that. Here are four small files to create in a project that get the undesirable behavior. I kept the preamble identical with the one I had, not knowing what could be the cause of the problem.

**0_Preamble**
```
---
documentclass: article
header-includes:
    - \usepackage[french]{babel}
    - \usepackage[utf8]{inputenc}
    - \usepackage[a4paper, twoside, top=2cm, bottom=2cm, inner=2.50cm, outer=3.50cm, heightrounded, marginparwidth=3cm, marginparsep=0.75cm]{geometry}
    - \usepackage{ebgaramond}
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}
    - \fancyfoot[C]{}
    - \renewcommand{\headrulewidth}{0pt}
    - \fancyhead[LE,RO]{\thepage}
    - \fancyhead[RE,LO]{}
    - \hyphenpenalty=10000 
    - \tolerance=2000
    - \emergencystretch=10pt
    - \widowpenalty = 10000
    - \clubpenalty = 10000
    - \AtBeginDocument{\def\labelitemi{\smblkcircle}}
    - \setlength{\parskip}{5pt}
    - \usepackage[fulladjust]{marginnote}
title:
mainfont: EB Garamond
fontsize: 11pt
indent: true
linestretch: 1.5
toc: false
toc_depth: 3
numbersections: true
secnumdepth: 3
block-headings: true
---
```

**1_Chapter 1**

```
# Chapter 1

Lorem ipsum dolor sit amet[^1], consectetur adipiscing elit[^2], sed do eiusmod[^3] tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

[^1]: Note 1 from chapter 1
[^2]: Note 2 from chapter 1
[^3]: Note 3 from chapter 1
```

**2_Chapter 2**

```

# Chapter 2

Sed ut perspiciatis[^1] unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis[^2] et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum[^3] exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?[^4]

[^1]: Note 1 from chapter 2
[^2]: Note 2 from chapter 2
[^3]: Note 3 from chapter 2
[^4]: Note 4 from chapter 2
```

**3_Chapter 3**

```
# Chapter 3

At vero eos[^1] et accusamus et iusto odio[^2] dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.

[^1]: Note 1 from chapter 3
[^2]: Note 2 from chapter 3
```

As you can see in this picture, notes from chapter 3 are repeated, and  replace notes from chapter 1 : 

![Capture d’écran du 2023-06-18 23-12-49](https://github.com/Zettlr/Zettlr/assets/136176476/37fcb562-6593-4c01-a2d2-a27ccbe7c1b8)

**Comment by nathanlesage** [comment]
Ahhh, so we are talking about *footnotes*, not *notes* as in files!

So, as Zettlr basically just provides Pandoc with a list of files, it should be capable of doing that itself. There is even an option to do so: `--file-scope`.

I believe within an exporting profile for Zettlr it needs to be written as `file-scope: true` (or `True` with a capital T?). Here's the documentation: https://pandoc.org/MANUAL.html#reader-options

There is a chance that this is not default behavior and that you'll have to manually set this option in your export profile in the assets manager. Would you mind double-checking this? If necessary wait for tomorrow's nightly which fixes the other issue that you can't create new projects.

**Comment by Aktemon** [comment]
My apologies for the confusion: my french is showing where it should not!

I can confirm that the nightly version of beta-5 allows to set a new folder as project. Folders already set as project before the update only need to be parametered again for the desired output format.

In the export profile (in my cas XeLaTex), the option to add is indeed `file-scope: true` (with lowercase t).

The pdf-latex output then organises the footnotes in the correct order, without duplicates or replacement. Problem solved as far as I am concerned!

The only thing that remains odd is I already got the correct order of the footnotes on the 2.3.0 release. I can only guess I added the proper option in the export profile a long while ago and completly forgot about it... Since this option may be of interest for many users working with projects, may I suggest adding a warning about it in the documentation, or in the list of things to check when switching to the next release?

**Comment by nathanlesage** [comment]
> The only thing that remains odd is I already got the correct order of the footnotes on the 2.3.0 release.

The reason for this is that back in the days, I would painstakingly do all of that myself, so there was a lot of preprocessing involved in 2.3, which I decided to ditch for 3.0 and let it handle Pandoc! And, as we can see, it can do that very well indeed with the right options :)
