### ISSUE TITLE
Settings don't affect 'matching character pairs' auto-close behavior

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#4416]
### Description

Regardless of the settings, certain matching character pairs automatically close while typing, while others don't.

### Reproducing

**Expected behavior:** In settings, if the box for "Automatically close matching character pairs" is unchecked, then typing an open parenthesis renders only that character: `(`. If the box is checked, then typing an open parenthesis renders both the open and close parenthesis, with the caret positioned between them: `(`[caret here]`)` 

The same is true for single and double quotations.

**Buggy behavior:** Regardless of whether the "Automatically close matching character pairs" box is checked, the matching pairs for parentheses always render, while the matching pairs for single and double quotations don't.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Good catch. I'm currently pondering if we even need this. In my opinion, disabling this option would make things harder rather than easier, or what is your opinion on that?

**Comment by noah-arroyo** [comment]
I love the functionality that auto-matches the ending characters for parens and quotations, as it saves me time. It's a reason why I also use Sublime Text.

If anything, I'd ask that the functionality become more robust to include curly quotes (this has never worked for me in Zettlr) rather than only "dumb quotes," as well as strikethrough and highlight.
