### ISSUE TITLE
Putting a link in a table cell reduces to showing the url instead of the label of the link

### ISSUE THREAD

**Issue by Julianoe** [Zettlr/Zettlr#4425]
### Description

Title. In a table, when I do a link in markdown, it reduces down to only showing the clickable url and hide the link content while it should to the opposite, reduce to only display the link content with a clickable url attached

### Reproducing

Create a table.
Add a link.
Click out of the table cell.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro 23

**Comment by nathanlesage** [comment]
Could you provide a quick sample table that we can just copy and paste to a test instance to see what's going on?

**Comment by Julianoe** [comment]
Here is the table 

```
| Solution                                              | Abonnement | Tarif             | Paiements hors €  | Wordpress                                               | Pays |
|-------------------------------------------------------|------------|-------------------|-------------------|---------------------------------------------------------|------|
| Payzen                                                |            |                   |                   |                                                         |      |
| [Easytransac](https://www.easytransac.com/fr/tpe-pme) | 0€/mois    | 1,2% + 0,15€      | 2,5% + 0,25€      | [plugin](https://fr.wordpress.org/plugins/easytransac/) | FR   |
| payplug                                               | 10€/mois   | 1,2% + 0,25€      | 2,5% + 0,25€      |                                                         | FR   |
| paypal                                                |            |                   |                   |                                                         | US   |
| stripe                                                |            | 1,5% + 0,25€ (EU) | 2,5% + 0,25€ (UK) |                                                         | US   |
```

I have also noticed that when selecting something in a table, the selection color is transparent (while by default it is green outside of a table
