### ISSUE TITLE
[Develop] Structured Clone cannot clone arrays

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#4426]
### Description

Hey @UFOMelkor If you have time to look into this, I just discovered this error on the console:

![image](https://github.com/Zettlr/Zettlr/assets/17251683/ec53c4ec-d1df-4df1-89b6-f8aa9388898f)

### Reproducing

See above

### Zettlr Version

Right off the develop branch

### Installation Method

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

macOS Ventura 13.2.1

**Comment by UFOMelkor** [comment]
Looks like `structuredClone` does not work with `Proxy` objects, in this case, especially the `autocorrect.replacements`, which contains a proxy of an array.

**Comment by nathanlesage** [comment]
Ah alright, if the issue is proxy objects, then it's possibly best to track the error before randomly returning back to parse/stringify-combos. I'll see where it originates, and whether we have to actually use safeAssign in that context.

**Comment by nathanlesage** [comment]
I just had a look, and this happens all over the place. I'm asking myself if it wouldn't be simpler to just construct a _new_ object, populate it with properties from the reference object, and optionally overwrite with the value from the new object, if that has the same key.

In the end, the only thing this function shall do is merge the two objects, and "safe" just means "do not take random properties from the new object" … this could be definitely simpler …

**Comment by nathanlesage** [comment]
I have now rewritten the function to never clone the `referenceObject` and instead recursively create an entirely new object, taking all properties of `referenceObject` as well as their values by default, overwriting only those properties which `obj` also has.

Tests pass, and it seems to work fine with proxys.

**Comment by nathanlesage** [comment]
But: The trick with `structuredClone` was a very good one, I'm going to keep that in mind.

**Comment by UFOMelkor** [comment]
Just one question about this: Is it safe to copy arrays as a whole? Besides this, I'm totally fine with this (and do not see another solution either).

**Comment by nathanlesage** [comment]
I'm not really copying arrays, just the reference to them (so mutating them on one object would mutate them on the reference as well). But I mean, internally the function is basically only used to merge configurations so that we don't have to provide full config objects, but partial ones suffice. That's basically all that this function does, and I didn't yet encounter any errors, so it seems to work.
