### ISSUE TITLE
[Feature] Shortcut for moving lines up or down

### ISSUE THREAD

**Issue by enricllagostera** [Zettlr/Zettlr#443]
## Description

In many code editors, there is a shortcut for moving up or down the line (or selection) the cursor is on. In Markdown, that could mean one whole paragraph or maybe a multi-line section of a bullet-list. In VS Code (Windows), for instance, this is accomplished by using the Alt/Option+Up/Down combinations. When doing so in bullet-lists, the indentation level of the line / selection is preserved. 

This would greatly improve efficiency when re-organizing list items, re-flowing text or creating outlines.

## Example Workflow

This would work by pressing the Alt/Option+Up/Down key combinations when the cursor is focused on the editor. The line in which the cursor is on (or the selected lines) are moved up or down accordingly, basically switching places with the lines that were in the intended position before (e.g. cursor is on line 02, Alt+Up is pressed, line 02 becomes line 01 and line 01 becomes line 02).

## Caveats

I believe this shortcut (Alt/Option+Up/Down) does not impact any of the current standard shortcuts. While pressing Alt enters the link-clicking / search mode, pressing Up or Down in that situation should not be a problem. There might be issues when doing this on the Table Editor mode, but even then the switching / moving behaviour might be helpful.

**Comment by nathanlesage** [comment]
Interesting, I just checked the CodeMirror manual and indeed there's no command available for switching lines! When I read your title I was so sure that all it took would've been to activate that shortcut.

Ah, just found the commands; they're implemented [in the sublime.js keymap for CodeMirror](https://codemirror.net/keymap/sublime.js) (search for "swapLineUp" and "swapLineDown")

So what I'll do is simply hook up the sublime keybindings and then activating only these two functions. If I understand the demo correctly, it should work out of the box!

The only missing piece then is a shortcut, so I'd like you to go to www.zettlr.com/shortcuts and have a look which ones make most sense for all platforms!

**Comment by enricllagostera** [comment]
That's great! I hope it works out of the box. I checked the Zettlr shortcuts, and I think the following shortcuts are the best candidates:

- [Alt/Option] + [UpArrow] for Swap Line Up
- [Alt/Option] + [DownArrow] for Swap Line Down

Reasoning:

1) It seems to me that there are currently no Zettlr shortcuts (on any of the platform/keyboard layout combinations) using the above shortcuts.

2) They are two-key shortcuts with a clear mapping. The shortcuts above have the benefit of being the same as in VS Code. I should note there is no consensus of shortcuts for this kind of function anyway: In Atom, the shortcuts are Ctrl+Up/Down, which would conflict with the current file list navigation in Zettlr. In Sublime Text, the shortcut for this functionality is Ctrl+Shift+Up/Down, which would also conflict with file list navigation.

**Comment by nathanlesage** [comment]
Sounds pretty good! I'll get to it after the holidays, unless some critic comes around, hehe

**Comment by nathanlesage** [comment]
And done! Works like a charm.
