### ISSUE TITLE
Vertical scroll bars stop working after moving tabs

### ISSUE THREAD

**Issue by lcsolano** [Zettlr/Zettlr#4438]
### Description

When tabs are rearranged/moved in the same pane, vertical scroll bars stop working. Splitting a pane make them work again.

### Reproducing

Move any tab in the same pane.

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr-3.0.0-beta.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Pop!_OS 22.04 LTS x86_64

### Additional Information

https://github.com/Zettlr/Zettlr/assets/19916268/e9c99d56-5d51-4de2-a27c-fac1b2be7b0f

**Comment by nathanlesage** [comment]
I cannot reproduce your description, could you elaborate more, maybe using screenshots instead of a video?

**Comment by lcsolano** [comment]
Open two files in the same pane:

![image](https://github.com/Zettlr/Zettlr/assets/19916268/d3296d12-7d5e-49c4-adf5-4fd8b25a3627)

Then swapt them:

![image](https://github.com/Zettlr/Zettlr/assets/19916268/b0183662-f00b-4212-9a7e-a84dffdf5dcb)

The scroll bars will stop working.

You can see in the video the different in the cursor shape. When vertical scrollbars are working, the cursor looks like this:

![image](https://github.com/Zettlr/Zettlr/assets/19916268/c0eae178-38a2-4bf9-90cd-7a4eb22afd78)

When they stop working, like this:

![image](https://github.com/Zettlr/Zettlr/assets/19916268/61f1cdd2-e564-4ef5-bdad-9ec020a6e5ad)

**Comment by nathanlesage** [comment]
Have you tried manually scrolling with the mouse wheel? Does that work? CodeMirror tries to be efficient in rendering and I've observed that sometimes the scroll bars weren't rendered at first but worked fine after scrolling with the wheel.

**Comment by exanrauzer** [comment]
Confirmed. Unable to grab the scroll bar when changing tab layouts. Scrolling with the mouse wheel is possible, but only within the document area, excluding the margin areas and scroll bar field.

Windows 10, beta5.
