### ISSUE TITLE
Orange border appearing around document area

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#4443]
### Description

After using the scroll and pressing the escape key, an orange border appears around the document area.

<details>
<summary>Gif:</summary>

![Recording 2023-06-24 at 08 55 10](https://github.com/Zettlr/Zettlr/assets/103963891/4f33cc43-14d2-42ee-bb41-4e36a8517f91)

</details>

### Reproducing

1. Scroll through the content using the scroll bar.
2. Press the escape key.
3. Observe that an orange border appears around the document area.

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr 3.0.0-beta.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This is both expected behavior AND a CSS bug 😀 So the orange border you see after pressing Escape is CodeMirror telling you that now you can press tab to move away from the editor area. This is valuable for people who need to use the keyboard to navigate the app, since it'll enable them to use tab to move between elements.

However, I did remove that outline on macOS, I have no idea why it appears on Windows since strictly speaking these both should have the same property. I'll have to take a look.

**Comment by nathanlesage** [comment]
Okay, I don't get this issue on the Windows layout – do you maybe have some Custom CSS that may cause that?

**Comment by exanrauzer** [comment]
Hi!

I get only this:

```
#editor.fullscreen {
  --side-margin-fullscreen: calc( 62vw - 30em ); 
}

#editor.fullscreen .CodeMirror-fullscreen {
  margin-left: var(--side-margin-fullscreen) !important;
}

#editor.fullscreen .CodeMirror-fullscreen .CodeMirror-scroll { 
  padding-right: var(--side-margin-fullscreen) !important; 
}
```

**Comment by nathanlesage** [comment]
This definitely shouldn't affect this. I'll have to dig deeper, when I get back to my Windows machine. (As always: PRs welcome if you find it sooner!)

**Comment by exanrauzer** [comment]
Thank you, but I'm just a self-proclaimed QA tester! :)

**Comment by nathanlesage** [comment]
Quick update: are you possibly using the Vim insertion mode? I just tried this out recently and noticed an orange border as well.

**Comment by exanrauzer** [comment]
No, regular. My update: Other way to recall the border (every time):

1. Click on the document area.
2. Use the scroll bar.
3. Press shift.

<details><summary>Gif:</summary>

![Recording 2023-07-02 at 16 26 41](https://github.com/Zettlr/Zettlr/assets/103963891/4c563f2e-bb2b-4256-9dc7-57762a394fc5)

</details>
