### ISSUE TITLE
Incomplete scrolling of the scrollbar to the end of the document.

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#4444]
### Description

The scrollbar fails to reach the bottom of the document when scrolling.

<details><summary>Gif:</summary>

![Recording 2023-06-24 at 09 19 21](https://github.com/Zettlr/Zettlr/assets/103963891/1809d468-ed77-4f8c-96d6-fa145645d623)

</details>

This issue typically occurs after opening a file.

### Reproducing

1. Open the document with a scrollable content.
2. Scroll to the bottom of the document using the scrollbar.
3. Observe that the scrollbar does not reach the very end of the document, leaving a portion of the content hidden.

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr 3.0.0-beta.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

Another small issue (to pack it together) is: the scrollbar handle does not align with the scrollbar arrow indicators.

<details><summary>Gifs</summary>

![image](https://github.com/Zettlr/Zettlr/assets/103963891/55b05e70-bc9c-4cae-81de-66f9cdd0bcde)

![image](https://github.com/Zettlr/Zettlr/assets/103963891/c09789c5-3460-485b-b76d-81a95a354c8e)

</details>

**Comment by nathanlesage** [comment]
That looks suspiciously like a CSS bug; I haven't tested the windows Lay-out in quite some while.

**Comment by exanrauzer** [comment]
I suggest to resign with arrow buttons in the scrollbars as well.

**Comment by nathanlesage** [comment]
… resign? I'm not sure I understand?

**Comment by exanrauzer** [comment]
I apologize for the inaccuracy. What I meant is that the arrow buttons in the scrollbar seem unnecessary. Many applications are opting to remove these elements, which I believe is a justified move as I consider them to be unused by users.

**Comment by nathanlesage** [comment]
This should have been fixed in the meantime.
