### ISSUE TITLE
[ENHANCEMENT] Narrow window mode

### ISSUE THREAD

**Issue by readtedium** [Zettlr/Zettlr#446]
## Description

I’m coming from MacOS, where a lot of editors are set up for thin interfaces in fullscreen mode. This allows for the ability to do research in a web browser/PDF client at the same time as writing. Most Linux-based Markdown editors do not seem to offer an editor interface with this use case in mind.

![Screenshot from 2019-12-26 10-34-55](https://user-images.githubusercontent.com/470216/71481321-6552f000-27cb-11ea-9a7c-983707a9b8e1.png)

Of the ones I’ve tried, however, Zettlr gets closest as far as general capabilities, but its management of interface options and spacing in a narrow interface gets confusing and cluttered. (See screenshot above.) There are a few options that would be useful at a thin length in this bar, such as the open folder/new directory setup, and a visible word count would be nice, but the fact that all of the menu options are kept makes it hard to use outside of a full interface.

## Proposed Changes

Cut down on the number of icons in narrow mode, pushing them down to a menu interface or collapsible second row, shrinking the text after a certain window width, and cutting down on margin/padding in the editor theme.

## Caveats

There are things that would be made less accessible by this move, but I think it would help improve the editor’s consistency in a minimalist setup.

## Additional Information

Some examples of apps that handle this interface approach very well are the Mac apps iA Writer and Bear.

**Comment by nathanlesage** [comment]
Congratulations, you found the problem I was avoiding for a year (which is why I don't use Zettlr in split screen mode) 🙈

I'm not sure if we could simply monkey-patch the toolbar, or if the approach mentioned in #448 to completely overhaul the GUI and thereby also address this is good.

Nevertheless, I'll keep this open as it's not strictly related to the Window decorations. Our options would be:

- Hide certain secondary buttons on resize (would be ridiculously easy to implement but may impact the user experience)
- Group buttons into submenus that expand while clicking on them (difficult, but might look nicely; I'm thinking of the TouchBar on newer MacBooks for that)
- Another UX approach I don't know? Maybe remove the toolbar and replace it with another design style?

What's your idea?

**Comment by readtedium** [comment]
Thanks for getting back, and apologies for hitting your pain point. 🙂

Barring a complete UX overhaul, I would consider using the bottom of the screen as an area for real estate. 

I think if you approached the top as a place for global functionality (say, file functions, which I think you could definitely include in a single menu if you wanted) and the bottom as a place for article-specific utility (word count, readability mode, pomodoro counter), it might help simplify things. 

Other suggestions that could ease the pressure in narrow interfaces:

* In a narrow interface, make the file drawer go on top of the editor, rather than pushing the editor to the side.
* Move the search dialog into the file drawer—users aren’t probably going to need it if the file drawer is closed, and there’s already an article-specific find-replace anyway. As that’s the largest element of the structure, it could make things much more efficient up top.
* A lot of Mac apps set a minimum width for fullscreen. Where possible, I would look into setting that.

**Comment by nathanlesage** [comment]
Yeah, the idea with having a status bar crossed my mind multiple times! However, I have fear that it might look ugly, but nevertheless, this would not only ease the pain on many issues you rightfully addressed, but also a huge bunch of other ones! Only need to find something to style it! But the Word counter might prove tricky: In most applications it's in the status bar, but having it at the top looks nicer … hmm

**Comment by Zverik** [comment]
Btw I use this Custom CSS (Menu → Zettr → Custom CSS) to make the window narrower and, if you want, to make the font closer to the "Notes" app (works best with the "Bielefeld" theme):

```css
#editor .CodeMirror {
  max-width: 800px;
  font-size: 100%;
  font-family: -apple-system, Helvetica, "Liberation Sans", Lato, sans-serif !important;
}
```

**Comment by nathanlesage** [comment]
I think the main problem of narrow window would be the toolbar, like that:

![image](https://user-images.githubusercontent.com/17251683/74315901-bf5a4580-4d78-11ea-9dcd-7b0098e49531.png)

:D

**Comment by danieltomasz** [comment]
So I was trying to write about that (either by creating an issue or commenting somewhere)

Would be nice to have  button to hide/unhide sidebar (or to activate focus mode) which it is the same,  but would involve thinking about other buttons (it would create too many buttons on the bar)

**Comment by nathanlesage** [comment]
> Would be nice to have button to hide/unhide sidebar (or to activate focus mode) which it is the same, but would involve thinking about other buttons (it would create too many buttons on the bar)

you mean `Cmd/Ctrl+J`?
