### ISSUE TITLE
Autocompletion for citation stopped working

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4465]
### Description

Since c650506df8d4955d517899ffca8b90e7bf17abe2 the autocompletion for citations is broken for me (the rendering works well). The citations should be loaded from the database which I have configured in the options.

When I add the path to the database in the YAML frontmatter (`bibliography: /path/to/better-cls.json`), autocompletion works fine.

### Reproducing

Open any document, type `@` and get nothing.

### Zettlr Version

Right off the develop branch

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
Just fixed that in https://github.com/Zettlr/Zettlr/commit/39ad73109871bc657ff7015788f7bb6ea74136dc – same as last issue!
