### ISSUE TITLE
Autocompletion could not be accepted by enter anymore

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4466]
### Description

Since a0d2877845c342ece823218cf00546860a3d1065 pressing tab is needed to accept an autocompletion entry. When pressing enter, a newline is added instead of accepting the autocompletion.

### Reproducing

Type `@` to open the citation autocompletion and then press enter.

### Zettlr Version

Right off the develop branch

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
Just fixed that in https://github.com/Zettlr/Zettlr/commit/37149224db06e02f6f4ac3dde7af1275ed02bdb6 – I was a little too slow with responding on Discord :)
