### ISSUE TITLE
I can't open any folder

### ISSUE THREAD

**Issue by jakeoung** [Zettlr/Zettlr#447]
## Description
As shown below, I can't open any folder. Even if I choose a folder, it doesn't work.

## Expected behaviour

**Screenshots**
<img width="331" alt="image" src="https://user-images.githubusercontent.com/2376897/71486234-a5d75b80-2815-11ea-9c05-65b2cba863a0.png">

## Platform
 - OS and version: 10.15.2
 - Zettlr Version:1.5
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Mh, this pretty much looks like the feared eight-sublevels-folder-problem in #343. Would you mind having a look at the config file? (Finder -> Go -> Hold down <kbd>opt</kbd> -> Library -> Application Support -> Zettlr -> `config.json`)

If the `openPaths`-property contains something, then it's a folder with too many subfolders within it. It's a bug within Electron's internal JSON-stringify-engine. There's a Pull Request open on the Electron repository, but it hasn't been merged for months now. We're all waiting for it to finally get in the source …

Workaround for now: Remove that property (or remove the config-file if you don't mind re-setting some settings; this is the safer approach) and choose a directory which you checked does not exceed too many sublevels!

**Comment by jakeoung** [comment]
Oh thank you very much! I've been struggling to fix this problem. After removing config.json file, I've finally came back. I didn't have many sub folders before, but it seems better to have less folders.

**Comment by nathanlesage** [comment]
Let's hope we won't run into that problem for long, hopefully! But glad it worked :)
