### ISSUE TITLE
Context menu not available on the newly created file's tab

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#4471]
### Description

After creating a new file within the application, the tab representing the newly created file does not provide a context menu upon right-clicking. The lack of a context menu restricts users from accessing options and actions.

### Reproducing

1. Create a new file (ctrl +n).
2. Put content into documnet.
3. Press ctrl +s to save.
4. Right-click on the file's tab to access the context menu.
5. Observe that the context menu does not appear.

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr 3.0.0-beta.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I cannot reproduce this in the current development branch. There will be a new nightly in a few minutes or something (check the "Actions" tab on the repository here to see when the action starts), please check it again if you can still reproduce the issue.

**Comment by exanrauzer** [comment]
Checked this nightly.

Same, but I got it:

This applies to files that are created and saved outside of the open workspaces. I create a file in the parent directory of my workspaces (where I keep loose files).

**Comment by nathanlesage** [comment]
Alright will have a look.
