### ISSUE TITLE
not saving table content

### ISSUE THREAD

**Issue by sviatoplok** [Zettlr/Zettlr#4474]
### Description

when changing something in a table, Zettlr does not save the change, whil it does with changes outside the table

### Reproducing

change something in a table
export to other format or close document and reopen
watch out for your change -- it's gone

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

windows 10

**Comment by nathanlesage** [comment]
This has been reported already, and is fixed in the current betas.
