### ISSUE TITLE
Citation autocomplete in footnote not working correctly sometimes

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4485]
### Description

I put citation in my footnote and autocomplete normally will render them. For example [@Author2015, p.123] will become (Author 2015, 123). However, the autocomplete of some citations doesn't work at all. See citation 10-12 below:

![image](https://github.com/Zettlr/Zettlr/assets/37974764/2eb9595c-f420-48b9-90e7-eba9e22dd9c5)

### Reproducing

See above.

### Zettlr Version

Beta (if applicable)

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Silverblue

**Comment by nathanlesage** [comment]
Two potential issues: you seem to have some conflicts in your database. The other issue is that there could be an issue in the renderer. To check that it would be great if you could just copy and paste the corresponding Markdown code in here so that I can copy and paste it to dig into the issue.

**Comment by sith-on-mars** [comment]
Do you mean this?

```
[^10]: [@distlerSecessionistConflictsUnresolved2022]
[^11]: [@distlerSecessionistConflictsUnresolved2022]
[^12]: [@fernsAustraliaAgeInternational2020]
```

They render fine if I put them as in-text citation.

**Comment by sith-on-mars** [comment]
If I hover the cursor on footnote 10-12, it says 'no footnote text found'.

**Comment by nathanlesage** [comment]
> Do you mean this?

Yes, thank you. I'll paste it into my dev environment and analyze the parser state, I have a hunch there's something going wrong with the parsing.

**Comment by nathanlesage** [comment]
Found the bug. It's super stupid: I forgot to make the parser work with identifiers with more than one letter (i.e. anything over number 9) …
