### ISSUE TITLE
Some citations are rendered incorrectly

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4486]
### Description

I use Better BibTex in Zotero so that Zettlr can read the citation entry from the cls file it generates.

Sometimes the citation autocomplete doesn't work correctly. I have a statue entry in Zotero and my citation in Zettlr is `[@UnitedNationsCharter1945]`. However, the citation autocomplete render it as `(<i>United Nations Charter<i> 1945)`. It seems that Zettlr tries to italicise the citation autocomplete, but can't render it correctly.

### Reproducing

See above.

### Zettlr Version

Beta (if applicable)

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Silverblue

**Comment by nathanlesage** [comment]
Ah, yes, i always forget to implement that 🙈 I'll see to it!
