### ISSUE TITLE
Ctrl + I is selecting Paragraph instead formating as italic

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#4497]
### Description

When I mark a text and press Ctrl + I the text should be formated as italic. When I do the same on the same computer with Zettlr 2 the text is formated correctly as italic .

### Reproducing

1. Select Text
2. Press ctrl +I
3. Paragraph is Select (instead of formated as italic, Ctrl + b for bold works as expected)

### Zettlr Version

Beta (if applicable)

### Specify version

3, Beta 6

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro, latest Packages

**Comment by exanrauzer** [comment]
Confirmed Win 10 beta6. But lets keep it! Such a handy feature! 😁

**Comment by nathanlesage** [comment]
This was a stupid mistake I made for the beta. Fixed and ships with next nightly on Monday.
