### ISSUE TITLE
Grammarly integration

### ISSUE THREAD

**Issue by axelkennedal** [Zettlr/Zettlr#4501]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

When writing in Zettlr it should be possible to enable Grammarly to continuously check the text which is being written, and to accept quick-fixes/suggestions. There should also be a list somewhere of all the suggested fixes for the current document.

### Example Workflow

1. I'm writing a text but would like to make sure it is grammatically correct and well written.
2. I enable the Grammarly integration within Zettlr.
3. Now Grammarly provides suggestions for improvements inline for my text.
4. I click accept on some suggested fixes.
5. Now the quality of my text has increased.

### Caveats

Perhaps it could clash a bit with the existing spell checking. Maybe you would have to choose to use only one or the other.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

I think this would be a huge advantage over other writing apps.

There is a Grammarly plugin for Visual Studio Code, might be used for inspiration: https://marketplace.visualstudio.com/items?itemName=znck.grammarly

**Comment by mol** [comment]
Late to the party, but I just happened upon this. We're using Grammarly, and their [Text Editor SDK is deprecated](https://developer.grammarly.com/sdk-deprecation) yeah, and will cease to work on January 10, 2024.

In our project, we'll be seeing if we can get the Chrome extension to work with [CefSharp](https://github.com/cefsharp/CefSharp), our internal browser.

**Comment by nathanlesage** [comment]
Okay, so now that we have the confirmation that Grammarly will disable their API, then I guess we can't integrate Grammarly anymore. I don't have the time trying to monkey-patch around an extension, unfortunately … if someone wants to get on it, feel free, but I'm not going to be pouring my time into this and instead focus on other improvements and features.

**Comment by mictadlo** [comment]
Hi @mol and @nathanlesage, Does Sapling or any other AI work with Zettlr?

**Comment by nathanlesage** [comment]
Please see the corresponding forum thread for AI integration for Zettlr: https://forum.zettlr.com/d/9-ai-writing-tools-for-zettlr
