### ISSUE TITLE
What are the hotkeys for the previous/next file buttons?

### ISSUE THREAD

**Issue by SN-CH** [Zettlr/Zettlr#4502]
### Description

Here is the screen-shot of the relevant page of Zettlr documentation.

![image](https://github.com/Zettlr/Zettlr/assets/42577865/374ea5d4-b864-4b08-8c6e-dcda4370a920)

I don't get the meaning. Hitting Arrow-up/Arrow-down (hot)keys in Zettlr clearly results in moving the caret one line up/down just as it does in any sane text-processing piece of software.

According to the File menu of Zettlr the hotkeys should be Ctrl-[ / Ctrl-]. These key combinations look reasonable, but what they actually do on my machine is unindenting/indenting the current line in stead (selecting the mentioned menu items has no any visible effect at all, the corresponding buttons of the tool bar works just as expected, though).

So, what are the proper hotkeys? Am I terribly wrong (and, apparently, dumb) or is something seriously messed up here?

### Reproducing

1) Hit Arrow up / Arrow down.
2) Hit Ctrl-[ / Ctrl-].
3) Go to File / Previous file or File / Next file.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0 beta 6

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by exanrauzer** [comment]
I think these are crumbs from previous versions where there were no tabs.

Together with issues of the menu: https://github.com/Zettlr/Zettlr/issues/4476

**Comment by SN-CH** [comment]
@exanrauzer Thank you, the picture is a wee bit clearer now.

This issue is obviously not the most burning one in 3.0.0, but it still would be nice to have the mess sorted out when the developers have a piece of time (I sincerely hope they do have it this time and another).

**Comment by nathanlesage** [comment]
There is currently an enormous branch just waiting to be merged that includes proper documentation for the upcoming 3.0. I simply do not have the time to fix the older 2.3 documentation as well. If you want to have a sneak preview, have a look here: https://github.com/Zettlr/zettlr-docs/pull/166/files#diff-291b58e742821d1c04b74ee2b897ce7063ad1998c539881f68bafa9b499bc94e

In case I have missed something, please suggest changes (on the corresponding repository, not here)

**Comment by exanrauzer** [comment]
Looks like people demands updates like crazy.

**Comment by SN-CH** [comment]
@exanrauzer No, I have not demanded anything. I just asked a question about what looked like a bug...

**Comment by exanrauzer** [comment]
@SN-CH I was joking. Cheers! 💚

**Comment by SN-CH** [comment]
@exanrauzer I see, no bad blood :-).
