### ISSUE TITLE
How do I open .java files inside Zettlr?

### ISSUE THREAD

**Issue by itsraghz** [Zettlr/Zettlr#4506]
### Description

I have been using Zettlr for the few days and it seems to be an ultimate solution to all my needs on the documentation needs (for my training materials) with an in house export facility (into HTML, PDF etc.,) - in my Macbook Pro. 

I dont find a way to look at my source code - *.java files inside the Zettlr editor. I explored all the settings options but really could not find a way. Is this something appropriate to look for? OR is it only for the .md files? 

### Reproducing

I dont find a way to look at my source code - *.java files inside the Zettlr editor. I explored all the settings options but really could not find a way. Is this something appropriate to look for? OR is it only for the .md files? 

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura 13.4.1 (c)

**Comment by nathanlesage** [comment]
This is a conscious design decision not being able to simply open and read all types of code files.

**Comment by itsraghz** [comment]
Thank you @nathanlesage . So at least we can show the files in the directory right? to just ensure the presence of the file.

**Comment by nathanlesage** [comment]
> So at least we can show the files in the directory right? to just ensure the presence of the file.

Yes. Currently to view non-Markdown files in Zettlr, select the folder and then have a look at "attachments" (the last tab in the sidebar).

> Also is there a way I can customize the list of files I can allow?

Yes, there is the ability to add and remove file extensions to be displayed in said tab.

Note, however, that this is deprecated. In a relatively soon version I want to just display all files in the file manager to make it faster for users to open those files in other programs.

**Comment by itsraghz** [comment]
@nathanlesage Thank you. 

I somehow feel and wish that the files can still be displayed in the explorer (or the file tree) so that it confirms the presence of the file at least. A facility to open the file inside the editor Zettlr may still be a choice you can take.  However, I wish and request we can allow the files of type ASCII - like Source Codes (like `*.java`, etc., ) as they are NOT binary (like PDF, image etc.,).

**Comment by nathanlesage** [comment]
As i mentioned: changes are in planning, I simply don't want to promise anything that I in the end cannot fulfill!

**Comment by itsraghz** [comment]
@nathanlesage it shows only a .pdf and .png files.. but NOT the *.java files (source code), even after I added those files (`*.java`, and `*.class`) in the Settings and Reopened the Zettler App.
