### ISSUE TITLE
File content disappears while scrolling in long file

### ISSUE THREAD

**Issue by StuporMundi1337** [Zettlr/Zettlr#4507]
### Description

I encountered the following problem today: 
1. I'm working on a file, that's relatively long (more than 5k words), with a lot of task list items. It's basically a layout for writing a chapter of my thesis, including references and links to other files.
2. All of a sudden while writing, the cursor froze and didn't move. Upon further scrolling, the content of the file completely disappeared, even when scrolling back up. After this event every other file I opened didn't show its content any more (everything just white). 
3. I could reopen the file, but when I'm scrolling beyond the point, where it froze for the first time, it turns white again.

**What I already tried**
I cleared the cache, restarted my PC and finally completely uninstalled Zettlr (including deleting all the personal settings in the AppData directory). 
Unfortunately, I still encounter the same problem. 

**Observations**
1. The contents of the file(s) are still there: I can open them in other programs (I tried with Notepad).
2. The "whiteout" happens consistently at the same scrolling distance. Whenever I pass a certain point in the document, everything just blanks, and other files also simply blank.
3. By cutting the file beyond the point of the whiteout (in Notepad) I can open it with Zettlr and scroll normally. 
4. When cutting out the part beyond the point of the whiteout and pasting it into a new file (using Notepad), I can reproduce the bug: Zettlr won't show anything of the file, and then continues to whiteout all other files as well.
5. UPDATE: When not scrolling with the mouse wheel, but by moving down by using the Arrow Down key, I can still reproduce the bug. However, the cursor behaves as if the contents are there, and I can still type. It still won't show, but when I open the file in another program the typed words are there. So it doesn't seem to be a "functionality" issue, but rather a problem with the proper display of the file.

**My guess**
There's something corrupt in the file, that whites out when it's supposed to be displayed.
Are there any suggestion, which part could be the problem?

**My approach**
I will continuously try cutting different parts of the file, abstract by abstract. Maybe I can hit the right part.
I'm also installing Zettlr right now on another PC, trying to reproduce the bug.

### Reproducing

I can simply reproduce the bug by opening the file.
However, I don't know how we can get you to reproduce the bug. I can't really share the file, since it contains sensible information about my thesis.
Do you have any ideas, what the possible whiteout-reason could be?

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by StuporMundi1337** [comment]
Upon further investigations, I cut the problematic part of the file, saved the top part, and then pasted the problematic part in. For now it seems to work just fine...

**Comment by gbmllr** [comment]
I had the same problem, but in the development version of Zettlr, not in the 2.3 (stable). It was also in a long, complex file

**Comment by StuporMundi1337** [comment]
Now the same problem occurred in a shorter file (less than 1,000 words), however there's also a mix of links, tasks and headings. Wasn't able to reproduce the bug on another PC.

**Comment by nathanlesage** [comment]
As I've been telling other people: Please switch to the current v3.0 betas. This issue should not occur in there. If it still does, please comment here.
