### ISSUE TITLE
Zettlr is available on iPad? or all the other iOS platforms?

### ISSUE THREAD

**Issue by itsraghz** [Zettlr/Zettlr#4509]
### Checklist

- [ ] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [ ] I have searched the documentation to make sure I did not overlook it.
- [ ] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Hey, Not sure whether it is appropriate. I am planning to buy an iPad or iPad Pro - and wanted to check with the team @nathanlesage or others - whether Zettlr is available at iPad / iPad Pro and for that matter all the devices running on iOS - or only with iMac / Macbook.

### Example Workflow

Hey, Not sure whether it is appropriate. I am planning to buy an iPad or iPad Pro - and wanted to check with the team @nathanlesage or others - whether Zettlr is available at iPad / iPad Pro and for that matter all the devices running on iOS - or only with iMac / Macbook.

### Caveats

Hey, Not sure whether it is appropriate. I am planning to buy an iPad or iPad Pro - and wanted to check with the team @nathanlesage or others - whether Zettlr is available at iPad / iPad Pro and for that matter all the devices running on iOS - or only with iMac / Macbook.

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [ ] Windows
- [X] macOS
- [ ] Linux

**Comment by nathanlesage** [comment]
Please read the corresponding FAQ entry: https://docs.zettlr.com/en/faq/#are-there-any-plans-of-porting-zettlr-to-mobile-phones-and-tables-for-android-or-ios

**Comment by itsraghz** [comment]
Thank you @nathanlesage

**Comment by anschmieg** [comment]
Hi! To revive this, I would like to refer back to [#3739](https://github.com/Zettlr/Zettlr/issues/3739) where @nathanlesage stated: 

> Basically all it would need is a bunch of volunteers – no one of those would even need to code. A set of reliable beta-testers that can give me detailed feedback plus a few "official" community moderators

I appreciate that the situation might have changed by now. However, I would like to emphasize that I, for one, would be more than happy to alpha-test such an application and, as far as my skills allow, potentially contribute to any development efforts. 

There is a faint hope left in me that enough interested devs and users have come up by now.
