### ISSUE TITLE
Auto-replace fails if typing with shift pressed

### ISSUE THREAD

**Issue by khakhalin** [Zettlr/Zettlr#451]
If you type with space pressed, auto-replace doesn't happen.

Try `TYPING --> THIS`, for example. Even though shift-spaces become normal spaces, they don't trigger the auto-replace event. 

It also makes it harder to type fast (and that's actually how I noticed it): it turns out that after typing `-->` of one of my custom codes, like `:sum:` for ∑, I don't always fully release Shift before pressing Space, because in no other program it ever mattered. But in this case, Zettlr misses an auto-replacement if you fail to release Shift.

Latest version of Zettlr 1.5.0, Windows

**Comment by nathanlesage** [comment]
I've also noticed that, but thought it's a good idea if you don't want to have that single instance replaced (it's faster than typing the space ahead of time and then insert the string). I'm not sure what would be best from a usability perspective ...

**Comment by khakhalin** [comment]
As an update: I'm gradually getting used to this, so I'm no longer sure it is necessarily a "bug" :) It is definitely not how most editors handle the issue of auto-substitution, but it's not the only thing that Zettlr does differently... So unless many other users find it annoying, maybe it can be considered a feature :)

**Comment by nathanlesage** [comment]
Alright, I'll leave this open a bit and see what others say!

**Comment by nathanlesage** [comment]
Heya, concerning recent developments and as a "bail out" method, I think for the time being, I'll leave that behaviour, as I believe it will have more benefits than drawbacks! In case it becomes a nuisance either way, simply comment so we can reopen the discussion at a later point!
