### ISSUE TITLE
Zettlr does not show the border on the tables when exporting (PDF, HTML)

### ISSUE THREAD

**Issue by itsraghz** [Zettlr/Zettlr#4511]
### Description

Zettlr does not show the border on the tables when exporting (PDF, HTML). However it is shown in the .md file inside the Zetler App.

### Reproducing

Export a .md file with the Table (I used the Table Editor to create a Table). You see that the table generated does not have the borders.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ventura 13.4.1 (c)

**Comment by nathanlesage** [comment]
This is not a bug, this is a design decision of the template creators. You can either adapt an existing template, e.g. via CSS or LaTeX to draw these borders, or you can download and use some template that already has borders.

Zettlr only shows the table borders inside the editor as it makes it easier to find relevant cells.

**Comment by itsraghz** [comment]
@nathanlesage  Thank you. I am not sure whether I get it 100% right. Do you mean to say - if at all I want to see the borders on the Table in the exported files, i should be explicitly using a different theme/template? For now I have been able to customize and play around the themes - switched from the default theme of Berlin (light green) . to Frankfurt (blue color) . What exactly is the template I should be using it for getting the borders on the exported tables?

**Comment by exanrauzer** [comment]
It is not about the template of the editor, but the template of the (css) export.

**Comment by itsraghz** [comment]
@exanrauzer, @nathanlesage , thank you. So you want to use a customized CSS on the theme we use! Let me try that . Thank you.

**Comment by nathanlesage** [comment]
Could you please move this and further discussions to Discord? I keep getting notifications, and I would like to be able to focus on actual issues. Thanks a bunch!
