### ISSUE TITLE
Visualize invalid YAML Frontmatter in the File manager

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4518]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

My files are shown in the file manager by the title from YAML Frontmatter (if available). This title often differs from the file name. Occasionally, when writing, I do not notice that I change the YAML in a way that makes it invalid, like a missing `,` between two strings in an array `["a" "b"]`. When opening the editor some days later, it's hard to find the file, especially if a file list is long and searching is not really an option. 

If the file manager showed a little icon instead of the document icon in such cases, it would be easier to find such documents.

### Example Workflow

If a YAML becomes invalid, show another icon in the file manager so that it becomes easier to find.

### Caveats

It might have a slight performance overhead because the YAML needs to be parsed. But I guess the state can be cached, so  this should be a real problem.

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
Wouldn't a linter be better? 99% of the YAML errors you make and THEN close the file, so it would be more helpful without adding even more logic to the file manager (people have already complained that the file manager needs a new design 🙈)

I wanted to implement a YAML frontmatter linter anyways but didn't get around to it. But it should actually be very simple, by just "ab"using the existing YSML file linter.

**Comment by nathanlesage** [comment]
I mean, what is planned ... :D Feel free to copy, paste, and adapt if you have some motivation to tinker, I think the YAML linter with very few adaptations (because it builds on the YAML parser) should already work pretty well. If not, it shouldn't be too difficult for me as well :)
