### ISSUE TITLE
Issue with YAML keywords

### ISSUE THREAD

**Issue by maia-sh** [Zettlr/Zettlr#452]
## Description
Great to have YAML frontmatter with version 1.5, however `keywords` isn't working isn't working with multiple keywords. Perhaps I am combining them incorrectly, but I'm not seeing documentation on how to combine keywords.

## Reproducing
The document starts with
```
---
keywords: tag1, tag2
---
```
I've also tried
```
---
keywords: tag1; tag2
---
```

## Expected behaviour
This should produce two tags: `tag1` and `tag2`
Instead it produces `tag1, tag2` or `tag1: tag2` depending on the input.

## Platform
 - OS and version: Catalina
 - Zettlr Version: 1.5
 - Screen Resolution: unknown

## Additional information
It would be great to get some documentation on what properties the YAML frontmatter supports (beyond `title` and `keywords` as mentioned in the version release notes).

**Comment by Wieke** [comment]
In yaml a sequance of values is defined as follows:

```YAML
multiline:
- foo
- bar
singleline: [foo, bar]
```

(Granted the single line example above is some kind of unholy combination of YAML and JSON, which works because YAML is a superset of JSON. As I understand it the multiline version is idiomatic YAML.)
