### ISSUE TITLE
"Add" button to add profiles for project export not working - 3.0.0-beta7 Win10

### ISSUE THREAD

**Issue by jdnicholas** [Zettlr/Zettlr#4528]
### Description

When trying to turn a directory into a project on the latest beta on Windows 10, the add button does not work when selecting profiles for the export. The warning: _PIease select at least one profile to build this project._ shows, and if the window is just closed, any profiles selected are not maintained when checking the project settings again.

### Reproducing

Try to create a new project from a directory, then go to Project Settings. The add button at the bottom of the settings window appears to be non-functional.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-Beta7

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Good catch!
