### ISSUE TITLE
.md and .txt files cannot be imported because filetype is not recognized

### ISSUE THREAD

**Issue by cjpoor** [Zettlr/Zettlr#454]
## Zettlr should recognize and import .md or .txt files.

**Screenshots**

## Platform
 - OS and version:
 - Zettlr Version:
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Markdown-files and Text-files are the default format for Zettlr, which means they don't need to be imported. If you want to put them into any of your opened folders, simply put them there using your Exporer, Finder, or other file browser! Imports are only for those formats that need special treatment to convert them into Markdown!

**Comment by cjpoor** [comment]
Ach so! Vielen Dank! I should have guessed that :-\
