### ISSUE TITLE
Installing 3.0.0-beta.8 over 3.0.0-beta.7 results in a downgrading warning

### ISSUE THREAD

**Issue by sphh** [Zettlr/Zettlr#4544]
### Description

When downloading the Debian package v3.0.0 beta8 and installing it over v3.0.0 beta7 I get this warning message:
```sh
sudo dpkg -i Zettlr-3.0.0-beta.8-amd64.deb
dpkg: warning: downgrading zettlr from 3.0.0-beta.7 to 3.0.0~beta.8
```
It looks like the hypen `-` between the version number `3.0.0` and `beta.7` was replaced with a tilde `~`.

### Reproducing

1. Download and install https://github.com/Zettlr/Zettlr/releases/download/v3.0.0-beta.7/Zettlr-3.0.0-beta.7-amd64.deb.
2. Download and install https://github.com/Zettlr/Zettlr/releases/download/v3.0.0-beta.8/Zettlr-3.0.0-beta.8-amd64.deb.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.8

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 21.2 Cinnamon

### Additional Information

When opening the beta8 Debian package in the `gdebi-gtk` GUI, it is not possible to install it, because `gdebi-gtk` believes, that beta7 is more recent.

**Comment by nathanlesage** [comment]
This is a benign warning: I don't know why Electron Forge tampers with the version strings everywhere it can, but the `~`-sign will work fine when upgrading to 3.0.0 stable, and afterward, as long as this behavior doesn't change, it should work fine.

**Comment by sphh** [comment]
Well, it is not benign for `gdebi-gtk`, which installs downloaded `.deb` files with a GUI: This program simply refuses to install it.

Anyway you are right (as I understand it) that updating to the final 3.0.0 stable should not be affected by it. It is just the change from `-` to `~`, which is annoying!

**Comment by sphh** [comment]
Maybe you want to add a note regarding this behaviour to the release page?
