### ISSUE TITLE
Clicking a global search result places the cursor one line above the result line

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#4547]
### Description

When clicking a global search result, the cursor gets placed one line above the actual result line.

Also, the line where the cursor is placed gets entirely highlighted (selected), causing the formatting toolbar to show. (the same happens when clicking on a ToC item btw; not sure if this new jump-to-line behavior is intended or not)

**Expected behavior**: Cursor gets placed at the actual result line.

### Reproducing

1. Search something via global search
2. Click on a search result
3. Observe the cursor located one line above the actual result line

### Zettlr Version

Right off the develop branch

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
I've now fixed the jump-to-line behavior, but I agree that the search still needs an overhaul. Currently, it returns lines and indices on that line, but CodeMirror has in the meantime switched to only take from:to ranges. And, apart from that, the search is … puh.
