### ISSUE TITLE
Regression in Debian package v3.0.0-beta.8: Defunct .deskop file

### ISSUE THREAD

**Issue by sphh** [Zettlr/Zettlr#4548]
### Description

After installing the Debian package v3.0.0-beta.8, no icon is shown in the menu and Zettlr cannot be started from it. Maybe the `.desktop` file was not correctly updated?

### Reproducing

1. Install the [Debian package v3.0.0-beta.7](https://github.com/Zettlr/Zettlr/releases/download/v3.0.0-beta.7/Zettlr-3.0.0-beta.7-amd64.deb) and open the menu: Zettlr is shown with icon and can be started.
2. Install the [Debian package v3.0.0-beta.8](https://github.com/Zettlr/Zettlr/releases/download/v3.0.0-beta.8/Zettlr-3.0.0-beta.8-amd64.deb) and open the menu: No icon.

### Zettlr Version

Beta (if applicable)

### Specify version

v3.0.0-beta.8

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 21.2 Cinnamon

### Additional Information

When starting `zettlr` from the command line, the program starts ok but does not show an icon in the window list.

**Comment by nathanlesage** [comment]
Can you please paste the contents of the Desktop file in a code block as a comment here so that I can have a look at how it looks? Feel free to add other contextual information as appropriate.

**Comment by sphh** [comment]
The contents is
```ini
[Desktop Entry]
Name=Zettlr
Comment=Your one-stop publication workbench.
GenericName=Markdown Editor
Exec=zettlr %U
Icon=zettlr
Type=Application
StartupNotify=true
Categories=Office;Education;Science;
MimeType=text/markdown;application/x-tex;application/json;application/yaml;
```
The funny thing is, that today (the computer has been restarted) the icon is displayed correctly and Zettlr starts correctly and also shows the icon when started from the terminal. I've no idea, where that hick-up came from and why it works now.

I close this as working again.
