### ISSUE TITLE
Changing 'tabs' in right-hand column clears the related files list

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#4549]
### Description

When I open a file, it shows the related files in the right-hand column. If I click one of the other 'tabs' at the top of that column (such as the paperclip icon to see any other files associated with this one) then when I return to the related files tab it is empty.
Switching to another file and back re-fills the related files list.

This list should either not be cleared on changing 'tabs', or should be filled again when returning to the related files tab.

![rfelated-files-1](https://github.com/Zettlr/Zettlr/assets/51254/dba33e93-e8ad-461b-a722-74b61623de13)
![rfelated-files-2](https://github.com/Zettlr/Zettlr/assets/51254/56bb4326-4fa9-4c50-afa6-05cf248d6c20)
![rfelated-files-3](https://github.com/Zettlr/Zettlr/assets/51254/2e18a197-21a7-41f3-84d5-624647dcc913)

### Reproducing

1. open a file with a variety of related files (incoming links, outgoing links, files with similar tags, etc.)
2. observe the list of related files in the right-hand column
3. click the fourth tab (paperclip) to see 'other files'
4. observe that the list of other files is empty
5. click back to the third tab (whatever that image is)
6. observe that the previously full related files list is now empty
7. open another file or click on one of the main editor tabs to another open file in the main editor
8. observe that it has its complement of related files
9. click back to the original file
10. observe that the list of related files is full again

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta 8

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This should now be fixed (other instances in which the list doesn't work properly are not yet completely fixed)
