### ISSUE TITLE
Cursor is not moved outside of ZKN link after autocomplete

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#4550]
### Description

When adding a ZKN link via autocomplete, the cursor is not moved outside of the link (i.e. after the closing brackets `]]`), but stays inside.

This applies when "Link with filename only" is enabled in the "Zettelkasten" preferences.

### Reproducing

1. Enable "Link with filename only" in the "Zettelkasten" preferences
2. Start adding a ZKN link and press Enter to apply autocomplete
3. The cursor will be located before the closing square brackets

### Zettlr Version

Right off the develop branch

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
If you want to, you can take a shot, it must be located here:

https://github.com/Zettlr/Zettlr/blob/6e97fe7c1d17d7f77773c74a6918e07e2f2c33b2/source/common/modules/markdown-editor/autocomplete/files.ts#L52-L79
