### ISSUE TITLE
Table Editor does not detect changes to cells

### ISSUE THREAD

**Issue by visatu** [Zettlr/Zettlr#4562]
### Description

Using the Table Editor, Zettlr does not detect changes to the file unless the row count of the table is altered or the cell in focus is changed. **Clicking away after modifying a value does not register as a change.** 

Demonstration, before edit:
![image](https://github.com/Zettlr/Zettlr/assets/43018278/667b9169-186a-4670-aceb-7223ac6ecb7e)

Changing "4" to "5" in the table does not result in an asterisk in the "delme" name in the Zettlr tab, indicating that the file was changed. Pressing `Ctrl + S` or `File > Save` does not alter the file.

![image](https://github.com/Zettlr/Zettlr/assets/43018278/8922577d-52f9-4abc-854f-5d2c441cede5)

After adding a row to the table using the mouse or changing the cell in focus the change is detected.

This is especially problematic when you have a table and update multiple values without altering the table otherwise, and continue to do other work. The old values in the table will persist in the file even when the new values are displayed.

### Reproducing

1. New file
2. Create a table with some data
3. Edit the cell contents without modifying row count
4. Click away
5. Save

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Chocolatey

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 22H2 / OpenSUSE Leap 15.4

### Additional Information

Linux installation uses Flathub as the installation method.

**Comment by nathanlesage** [comment]
Please switch to the most recent beta or wait for the 3.0 release on Sept 1, a better saving strategy has been implemented there (see Changelog for details).

**Comment by visatu** [comment]
Thank you. My bad for not checking.
