### ISSUE TITLE
Flatpak installation has access only to the files in ~/Documents 

### ISSUE THREAD

**Issue by Mr-Blue-Sky-Candy** [Zettlr/Zettlr#4563]
### Description

I cannot open files outside Documents. Also I can only see Documents folder.
![image](https://github.com/Zettlr/Zettlr/assets/131680576/e0413bd5-6708-4b69-aa58-233ac138efad)

On usually does not keep the README.md files of the source codes in Documents folder so one should have access to home folder from Zettlr.

I also tried changing the flatpak settings I gave every filesystem access and added xdg-home but to no avail.
![image](https://github.com/Zettlr/Zettlr/assets/131680576/da7a2f8a-0846-4ff3-863f-3dee1f72ab64)

I also tried: `sudo flatpak override com.zettlr.Zettlr --filesystem=/home/mrbluesky/` without success.

### Reproducing

When right click on a file and click open with zettlr. Zettlr lunches but do not open the file. Inside Zettlr, when I click on open file I can only see Documents folder

### Zettlr Version

Stable (most recent version)

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 39 64 bit

**Comment by nathanlesage** [comment]
Please read the notices in the Flatpack installation manual: https://docs.zettlr.com/en/install/#flatpack

Open further inquiries please against the proper repository, which is the flathub repo, not this one.

Thank you!
