### ISSUE TITLE
Broken frontmatter causes PDF export to fail with bad error message

### ISSUE THREAD

**Issue by seanofw** [Zettlr/Zettlr#4574]
### Description

Today I was working on a document at work and accidentally mistyped the frontmatter section:
```
---
title: "Foo"
author: "Sean Werkema""
date: "Fri, 25 Aug 2023 12:21:00 EDT"
---
```
You'll notice the extra quotation mark on the second line.

Zettlr was able to edit the document fine, but when I went to export it to PDF, I got this inscrutable error message:
```
Error

ERR_FILE_NOT_FOUND (-6) loading 'file:///.../foo.html'
```
I figured that the `.pdf` file was locked or something, and deleted it, and tried again, and tried several other things before studying my document and realizing the frontmatter was invalid.  I fixed the extra quotation mark, and had no trouble then exporting to PDF.

As this is a small reproducible test case, I thought I would provide it here so that a better error message could be provided for it instead of a strange "file not found" error.

### Reproducing

1. Create a new document with improperly-structured frontmatter at the top, such as the example below:
```
---
title: "Foo"
author: "Sean Werkema""
date: "Fri, 25 Aug 2023 12:21:00 EDT"
---
# Foo
```
2. Click on File > Export.
3. Choose "PDF" and click "OK."
4. You will be presented with a strange `ERR_FILE_NOT_FOUND (-6)` error, instead of a more useful error like "Cannot export due to invalid or damaged frontmatter."

### Zettlr Version

Stable (most recent version)

### Specify version

Version: 2.3.0.  UUID: bd470ef0-7b62-4a54-9671-8cd2eab832c9

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
There's no need to add custom error messages to indicate a broken frontmatter. The error does not originate with Pandoc which works fine, but rather with the YAML frontmatter being broken.

Your issue reminded me that I wanted to add a dedicated YAML Frontmatter linter, which, fortunately, was very easy since we already have a YAML linter. I did so in the attached commit. Now such a broken YAML frontmatter looks like this:

![image](https://github.com/Zettlr/Zettlr/assets/17251683/e26e798a-23bf-435e-b659-bd5dd7bc5f15)

… or this:

![image](https://github.com/Zettlr/Zettlr/assets/17251683/9a5f4487-1b81-4e71-ab3c-8aa459acb5c4)

**Comment by seanofw** [comment]
I agree that a frontmatter linter is a valuable addition, and it would definitely have prevented this issue! 👍

That said, the YAML standard is complex and has many, many obscure corner cases, and different YAML parsers can (and do) treat it differently.  And front matter isn't a standard either; there's not really a well-established set of keys or expected values for them.

So the concern I still have is that even with a really great linter (which, again, I'm happy that you've added!), it still could be possible that that linter and whatever code is currently parsing the frontmatter would interpret it differently, resulting in the same inscrutable "file not found" error message for some hapless user.  The linter helps a lot to avoid the error message, but it doesn't guarantee the error message will never appear:  Not changing the underlying error-handling to report the problem better may just result others filing more frontmatter-related GitHub Issues in the future.

My two cents, anyway.

**Comment by nathanlesage** [comment]
I disagree. While you are right in that YAML is not the most precise markup language, at least for the purposes of Markdown it is standardized enough for a simple linter to suffice. We don't do anything wild with the frontmatter.

Besides, if the YAML has no syntax errors, the error messages provided by Pandoc will become MUCH more intelligible. That is also the reason why there's nothing regarding errors that I could fix: this error emanates from Pandoc, not Zettlr.

**Comment by seanofw** [comment]
If the error comes from Pandoc, you're right that there's not much more that can be done other than checking the YAML before it's sent.  It's a shame that there isn't a better answer, but I agree that your answer is probably the best that can be done. 👍
