### ISSUE TITLE
Code tags inside a table render on their own line (and without background).

### ISSUE THREAD

**Issue by learn-more** [Zettlr/Zettlr#4578]
### Description

Input:
```
| Text in a table                 | And more text in a table        |
|---------------------------------|---------------------------------|
| Some `code` inline in the table | Some `code` inline in the table |

Some `code` inline outside the table
```

Result:
![image](https://github.com/Zettlr/Zettlr/assets/610685/119a9b4b-f67d-4983-b929-153912eb0e43)

Neither of the cells show the background for the code tag,
and the inactive cell displays the code tag as block, while the cell that is being edited currently does display it inline.

### Reproducing

Paste the above markdown in a file

### Zettlr Version

Nightly

### Specify version

3.0.0-beta.8

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win10 22H2

**Comment by nathanlesage** [comment]
Fixed that in one of today's commits!
