### ISSUE TITLE
Italics bleeds out of latex section

### ISSUE THREAD

**Issue by khakhalin** [Zettlr/Zettlr#458]
If you type in latex (between dollar signs), most underscore signs are processed correctly, and don't trigger italics. However, if you use _ after curly brackets, it turns italics on. Moreover, this italics stays on (is rendered as "on") even after you leave the $$ segment, and it gets replaced with a nice formula.

Type this:

$(a^{ij}_k)$ This part becomes italics

Ideally, italics should never turn on when between $$ signs, either in editing mode, or in render. If it is too hard, at least check for it at render stage, once editing is done?

Zettlr 1.5.0, Windows 8

**Comment by nathanlesage** [comment]
Yeah, the underlying Markdown mode doesn't understand MathTex within Markdown, the rendering of the formulas is taken over by an overlay. But I can certainly try to amend this!

**Comment by nathanlesage** [comment]
I'll be tackling this issue in the evening, because I got a pretty good idea not only to prevent certain formatting characters of influencing the surrounding Markdown, but also to add syntax highlighting to the Math formulas (basically keeping a state object and returning the STEX mode instead of the GFM mode for these things.)

**Comment by nathanlesage** [comment]
So, after a lot of fiddling with CodeMirror I have bad news: I cannot access the underlying GFM mode's state in any way and therefore cannot change that the mode will render italics even within math formulae. What we would need is a full rewrite of the underlying mode, which I cannot do right now. So unfortunately, I'll have to close the issue for now. But please don't hesitate to remind me once this is underway that I do not forget it!

**Comment by khakhalin** [comment]
I am sorry for not understanding your response completely, but it is equally hard _during_ the editing (when you are within a formula), and _after_ one leaves the formula and it gets rendered? Naively, one would think that once the formula is rendered, the text that generated the formula is excised from the text, and so a "_[*]_" pattern shouldn't match it... It's almost as if just switching the order of these two operations would fix the issue, no?

(If what I'm saying doesn't make sense, please ignore this message; I honestly tried to look into this CodeMirror thing, but I don't know JS well enough to even start to understand it :)

**Comment by khakhalin** [comment]
Update: It seems that the best workaround for a user (me, for example :) is to just include subscripts in curly brackets when this italics-matching happens, as it doesn't trigger italics. Or surround an underscore symbol with spaces; it also seems to work!

Some sample behaviors:
This is fine before $(a^{ij}_k)$ but becomes italics after
This is italics before $(a^{ij}_ k)$ but is fine after
This is fine both before $(a_{k}^{ij})$ and after
This is also fine both before $(a _ k^{ij})$ and after

**Comment by nathanlesage** [comment]
Ah good that at least a workaround works! :)

And yes, Italics are even rendered within such formulaes, because the underlying mode doesn't care about formulae, and I cannot teach it not to do that!
