### ISSUE TITLE
Footnote rendering if the footnote contains, e.g., a link

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4580]
### Description

When a footnote contains a closing square bracket `]` (like a link), it stops rendering the footnote at this location.

![image](https://github.com/Zettlr/Zettlr/assets/571106/fafab5c6-50c6-4bff-9f6b-1b7f000be4b5)

### Reproducing

Insert the following text into a document.

```md
For a zettelkasten you do not need special software.^[But you can use [Zettlr](https://zettlr.com), it is really cool].
```

### Zettlr Version

Right off the develop branch

### Specify version

00b6dd77

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
My advice is to not use inline footnotes for anything except short clarifications, etc. Footnotes are not standard Markdown anyhow and inline footnotes even less so, so I will not tamper with the ability of the Link parser to detect links as it does right now. Regular footnotes should have no trouble working with links.
