### ISSUE TITLE
Wrong language code for Catalan locale

### ISSUE THREAD

**Issue by jordimas** [Zettlr/Zettlr#4583]
### Description

The current filename for Catalan translation is:

https://github.com/Zettlr/Zettlr/blob/develop/static/lang/ca-CA.po

This follows the language-country convention. CA is the country code for Canada where no Catalan is spoken.

The most common language code for Catalan is "ca-ES"

### Reproducing

Explained already

### Zettlr Version

Stable (most recent version)

### Specify version

latest

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Any

**Comment by nathanlesage** [comment]
That's a good find! Would you mind opening a PR that changes this? I have another incoming PR that tries to update the Catalan translation, and we have to be careful to include those two changes one after another to not mess anything up. I think you're even able to rename the file on the web interface (plus everywhere it is referenced). That would be a tremendous help.

**Comment by jordimas** [comment]
I can give it a try.

As you point out, we should merge https://github.com/Zettlr/Zettlr/pull/4576 first.

**Comment by nathanlesage** [comment]
Fixed by a recent PR (not the one mentioned here)
