### ISSUE TITLE
CSS classes for tags are not available

### ISSUE THREAD

**Issue by IgnacioHeredia** [Zettlr/Zettlr#4589]
### Description

Not sure if this is a bug, or intended, so filling it as a bug just in case.

In Zettlr `2.*` the HTML had custom CSS classes for each tag name. For example, `#software` would generate a CSS class `.cm-zkn-tag-software`.

In my case, I used this to created [fancy tag displays](https://github.com/Zettlr/Zettlr/discussions/2863#discussioncomment-2803515) for each tag name.

In Zettlr `3.0` these CSS classes seemed to have gone. Is this intended behaviour?

PS. Multipane view looks great, thanks!! 🚀 

### Reproducing

Described above.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

Installed from deb package.

**Comment by nathanlesage** [comment]
> In Zettlr 3.0 these CSS classes seemed to have gone. Is this intended behaviour?

Yup. I'll have a look but since CM6 works almost entirely differently I won't promise anything.

**Comment by IgnacioHeredia** [comment]
Thanks for taking a look! 🙏🏽
