### ISSUE TITLE
CSS class for monospace mark

### ISSUE THREAD

**Issue by IgnacioHeredia** [Zettlr/Zettlr#4593]
### Description

Hi,

I'm customizing the editor view and I'm faced with the following case:

```
* `demo`
* **bold**
```
the are three markers here:
1. bullet points `*` with CSS classes `cm-list cm-content-span cm-code-mark cm-meta`
2. monospace markers with CSS classes `cm-list cm-content-span cm-code-mark cm-meta`
3. bold markers `*` with CSS classes `cm-list cm-content-span cm-strong cm-content-span cm-code-mark cm-meta`

So, as you cansee, 1 and 2 are identical, so I cannot treat them separately, as I would do for bold markers.
![image](https://github.com/Zettlr/Zettlr/assets/16413205/8e9048bc-152f-4d63-b1bf-ebf98b918e66)

Initially, I would have suggested adding to the `cm-monospace` class to the markers, but that would also make them appear in monospace, and that would not be pretty.

So I have no good solution apart from creating a dedicated class (eg. `cm-monospace-mark`) 

### Proposed Changes

Described above.

### Caveats

The proposed adding of an additional class can make classes look more clunky?

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 20.04

### Additional Information

Installed from deb package.

**Comment by nathanlesage** [comment]
I am fairly certain that I cannot change that. The reason is that the underlying Markdown parser (that I do not control) uses generic class names. You may have success looking at nesting CSS classes instead.

**Comment by IgnacioHeredia** [comment]
I don't think it's possible, because they are on the same HTML level. There isn't a way to tell them apart.

For example:
```
* `demo` 
```
will produce the following HTML:
![image](https://github.com/Zettlr/Zettlr/assets/16413205/b3c18ba5-fb8d-46e7-8aa0-cfc8e39cb351)

When monospace is outside a bulletpoint list, it will work fine though.

In any case, I can live with it. 😅 Thanks for the fast reply!
