### ISSUE TITLE
Monospace font not rendered

### ISSUE THREAD

**Issue by IgnacioHeredia** [Zettlr/Zettlr#4594]
### Description

More testing!

I'm afraid monospace font is not rendering. This is how monospace looks off the shelf (no custom CSS or anything):

![image](https://github.com/Zettlr/Zettlr/assets/16413205/2190f185-0074-4884-b37d-a808aec1e09a)

As you can see, the font is the same as the default font in the Bielefeld theme. You just get the grey background.

### Reproducing

Described above.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

Installed from deb package.

**Comment by nathanlesage** [comment]
Damn it, this slipped my view. It's a result of https://github.com/Zettlr/Zettlr/pull/4564

See attached fix.

**Comment by IgnacioHeredia** [comment]
Thanks @nathanlesage !

Minor aesthetic comment. In code-blocks (which work fine btw), the grey background seems to _slightly_ overflow to the next line. Nothing big.

![image](https://github.com/Zettlr/Zettlr/assets/16413205/7bab230f-8e43-470c-9a3e-95cdd2833206)

**Comment by nathanlesage** [comment]
Your screenshot looks like a syntax error to me 👀

**Comment by IgnacioHeredia** [comment]
I don't think it is. I looks like Zetllr is acting a bit weirdly.

Approximate steps to reproduce:

* Just after opening Zettlr, code-block is rendered fine:
![image](https://github.com/Zettlr/Zettlr/assets/16413205/e645b721-0f62-42d1-a67c-076f652eb094)
* Wait a few seconds
* Edit the code-block, and the overflow shadow appears
![image](https://github.com/Zettlr/Zettlr/assets/16413205/41189db9-d3d5-4c6b-9a8c-c8933104cb4f)

Here it is recording my screen:
https://github.com/Zettlr/Zettlr/assets/16413205/a3d37273-69e6-4107-9c9d-ab9bcefc8c8d

When you select the code-block, you can see the margin starts a bit left from the text, just like the overflow part that is shaded.
![image](https://github.com/Zettlr/Zettlr/assets/16413205/15a8dca8-860b-4841-a4c8-624888feae06)

Probably related to that.

**Comment by IgnacioHeredia** [comment]
I can open a separate issue if you prefer.

**Comment by nathanlesage** [comment]
Well, observe it first and reproduce it consistently. If you then give me a block of Markdown source that I can just throw into the test environment I can take a look. What I do know is that it has to do with the linked PR.
