### ISSUE TITLE
x86-64 version of Nodehun.node on Linux ARM64 (Zettlr doesn't start)

### ISSUE THREAD

**Issue by LaPingvino** [Zettlr/Zettlr#4595]
### Description

When starting Zettlr 3.0.0 on Linux ARM64 (Debian Sid via Crostini on my Chromebook) it crashes with `Uncaught Exception: Error: /usr/lib/zettlr/resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node: cannot open shared object file: No such file or directory`

### Reproducing

Install any 3.0.0 version on Debian Sid ARM64, problem reproduced with either .deb or .AppImage

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Debian Sid on Crostini (Chromebook)

### Additional Information

```bash
[1m[47m[31mA JavaScript error occurred in the main process
[30mUncaught Exception:
Error: /usr/lib/zettlr/resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 19572 (/usr/lib/zettlr/resources/app.asar/.webpack/main/index.js:2:1543033)
    at r (/usr/lib/zettlr/resources/app.asar/.webpack/main/index.js:2:3470579)[0m
[7724:0901/231628.578694:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```

**Comment by LaPingvino** [comment]
Hm, it looks like somehow the file IS there. running the file command on it gives
`/usr/lib/zettlr/resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=b01d9498432aa549f3031af30687b9923025cc7b, not stripped` which suggest that it's a mistake in the build pipeline.
Copying over an ARM64 version of the same file compiled by me makes Zettlr coredump.

**Comment by LaPingvino** [comment]
manual compilation which compiles with yarn as in the instructions and then copying over the Nodehun.node does fix the issue and Zettlr starts correctly. File that works added: 
[workingfile.zip](https://github.com/Zettlr/Zettlr/files/12502433/workingfile.zip)

**Comment by LaPingvino** [comment]
(Maybe check if the cross-env build needs aarch64 instead of arm64?)

**Comment by nathanlesage** [comment]
This sounds like very much related to: https://github.com/Zettlr/Zettlr/issues/4068

> (Maybe check if the cross-env build needs aarch64 instead of arm64?)

Would you mind testing this…? Because I don't have an ARM64 Linux machine at hand, I cannot really do more than reading tea leaves — but if you change that in `package.json` and then run `yarn release:linux-arm`, does this then produce workable installers? If so, then we would have a fix, and you can open a PR. I didn't touch this because I wasn't sure what the various platform names were, especially since aarch64 and arm64 are essentially almost-synonyms.

**Comment by LaPingvino** [comment]
Testing shows that this doesn't make any difference for this specific problem... I will continue to look if I can find a fix, and if you have an idea yourself I'm happy to test :D.

**Comment by LaPingvino** [comment]
![image](https://github.com/Zettlr/Zettlr/assets/10294/077ae6d5-eb29-4797-8d2c-5763c93fbe74)

... when you run your tests, you should have a pretty good idea if it's likely to work by running the file command on the Nodehun.node file. This definitely seems to be going wrong. It looks like the Nodehun.node compilation doesn't cross compile. If you need an ARM64 VPS to compile on, I just read that GCP is introducing ARM machines that will be free until somewhere next year. I might try one of those to compile on because running the release locally already made the system reboot and it goes really slowly...

**Comment by LaPingvino** [comment]
Okay, simple fix:
1. Add zig to the build system, make sure it's in the PATH
2. Add `CC=\"zig cc -target aarch64-linux-gnu\" CCX=\"zig c++ -target aarch64-linux-gnu\"` to the cross-env environment variables on the two linux-arm lines in the package.json
3. Release as normal

**Comment by nathanlesage** [comment]
What exactly is zig? And, is there really no way of nudging the install pipeline to properly compile on first attempt? I really would like to avoid adding a new dependency if possible.

**Comment by LaPingvino** [comment]
For cross compilation the system will need a whole set of the same compiler for a different system either way. That's a nightmare to figure out. I think the solution will look kinda similar but worse otherwise.

zig is a new programming language that bundles clang (the llvm C compiler) with some magic to make cross compilation a breeze: https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html

It's the only way I know to cross compile C easily. I guarantee you everything else will be more complicated and irky.

**Comment by LaPingvino** [comment]
https://wiki.osdev.org/GCC_Cross-Compiler

**Comment by LaPingvino** [comment]
Compiling on the target platform works and cross compiling works with a compiler that supports cross compiling. The latter was not done to avoid adding extra dependencies.

**Comment by LaPingvino** [comment]
> And, is there really no way of nudging the install pipeline to properly compile on first attempt?

No

**Comment by nathanlesage** [comment]
@LaPingvino I didn't not add cross compile support to have fewer dependencies. Rather, I didn't yet have the time to implement this. If you have already done so successfully, would you mind opening a PR that implements the necessary changes so that the build pipeline spits out properly compiled Linux ARM binaries? This way we could have a working ARM build again! This would be a great help!

**Comment by nathanlesage** [comment]
Also, if you need any guides through the codebase or how the GitHub actions workflow works, please reach out, I'm happy to help.

**Comment by LaPingvino** [comment]
> @LaPingvino I didn't not add cross compile support to have fewer dependencies. Rather, I didn't yet have the time to implement this. If you have already done so successfully, would you mind opening a PR that implements the necessary changes so that the build pipeline spits out properly compiled Linux ARM binaries? This way we could have a working ARM build again! This would be a great help!

Yeah we got a bit stuck in the discussions at the time. I kinda got my suspicions confirmed later on which was not as strong when we talked it through. I'll give it a try, the solution is basically tried and tested, I just need to make sure it works with Github Actions as you said.

**Comment by LaPingvino** [comment]
@givtrah can you give the builds on https://github.com/LaPingvino/Zettlr/releases/tag/untagged-05b8b6bea1f8789e3cb6 a try? That fork tests the change I made in PR #4910

**Comment by givtrah** [comment]
@LaPingvino if would love to, but the link is not working.

**Comment by LaPingvino** [comment]
ah bc it's a draft, one moment...

**Comment by LaPingvino** [comment]
@givtrah I updated the link to https://github.com/LaPingvino/Zettlr/releases/tag/v3.0.3 and it shouldn't be a draft anymore. Give it a go!

**Comment by nathanlesage** [comment]
@LaPingvino Thanks a bunch even for running a test build, that's extremely nice of you! I'll wait until people here report back but it seems you already caught most issues :)

**Comment by givtrah** [comment]
> @givtrah I updated the link to https://github.com/LaPingvino/Zettlr/releases/tag/v3.0.3 and it shouldn't be a draft anymore. Give it a go!

@LaPingvino @nathanlesage I can confirm that  Zettlr-3.0.3-aarch64.rpm linked above now starts as expected and the problems with Nodehun.node seems to be gone. Tested on Asahi Fedora Remix 39 fully updated on an M2 Macbook Air.

**Comment by nathanlesage** [comment]
Perfect, thank you all for your help here! :)
