### ISSUE TITLE
Allow option of Natural or ASCIIbetical sorting for document previews

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#46]
I am using Zettlr under Windows 10, and I am experiencing the infamous ASCIIbetical vs Natural sort order issue in the Zettlr preview pane. Windows Explorer implements Natural sort order, but it seems Zettlr is offering only ASCIIbetical or filesize. For info on this, see [Sorting for humans](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/), and here for [a solution in JavaScript](https://stackoverflow.com/a/38641281/9727685). The precise details of my issue are below. 

I have a document made up of several sections, named like this (I've missed out intermediate files):
```
§0 Introduction.md
§10 Of modernity....md
§20 The Table of Dreams.md
§30 The degradation of language.md.
… …
§100 Pizza, birra, faso (1997).md
§110 Mundo grúa (1999).md
§120 Cultured_Cities.md
§130 Works Cited.md
```
When I look at these files in Windows File Explorer, they are in Natural order (when ordering by title). However, when I look at them in the Zettlr document preview, the order is ASCIIbetical, i.e. `0, 10, 100, 110, 120, 130, 20, 30`. When I hover over the top of the pane, there are two buttons, one showing A-Z, which gives the non-natural order. The other shows increasing line sizes, and that one gives what I think is an ordering by file size.

Lastly, with a [PowerShell one-liner](https://stackoverflow.com/questions/5427506) I can easily compile all the `*.md` files to a single document in Natural order with pandoc, but I'd like to be able to see them in Natural order in Zettlr, otherwise it is difficult to work with the files! Clearly this should be a user-selectable option, because not all filesystems implement Natural sorting order.

To be clear, I think the JavaScript solution for sorting the array of files is:
```
var collator = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'});
var myArray = ['1_Document', '11_Document', '2_Document'];
console.log(myArray.sort(collator.compare));
```
… but I haven't tested it.

**Comment by nathanlesage** [comment]
I'll be getting on it. Although I'm hesitant, because for maximum compatibility it shouldn't be allowed to nudge users to use cross-platform workable file names (i.e. 2018-11-03 instead of 1, 2, 3, 4, 5, 10, 20, 30).

Totally overlooked this issue until now!

**Comment by Jaifroid** [comment]
The thing is, both OSX (I understand) and Windows (I can confirm) present the user with natural file order in their file explorers, so it's likely to cause a lot of confusion if (when!) Zettlr becomes the go-to Word Processor for the masses!!

**Comment by nathanlesage** [comment]
Are you sure? Because this "natural file order" is actually something I've never heard of. I mean, I completely know what you mean, but currently I'm asking myself why I had established a convention of naming my files in the format yyyy-mm-dd - title, if there's natural ordering ...

I'll have a look into this, because yes, it would definitely confuse users to have a different sorting mechanism internally as in the file system!

**Comment by Jaifroid** [comment]
For Windows, I'm 100% sure -- it's why I noticed the issue in the first place. File order in Explorer uses natural sort ordering. For Mac, I'm going on what is stated here: https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/ , particularly the reference to the Mac Finder. That article also explains the issue, if you haven't heard of "natural sort ordering" vs "ASCIIbetical".

**Comment by nathanlesage** [comment]
Yeah, I see I'm one of these ignorant dudes =D

I've researched a little bit by myself and indeed it seems that macOS's finder uses natural sorting (so much for "paying attention" on my side), which means that I'll need to implement it prior to 1.0, which is why I removed the Post 1.0-label.

But I think, as I'm accustomed to ASCIIbetical (what a word!) and others are as well, I'll leave it to the user somewhere in the settings as to what kind of sorting Zettlr should apply in case of order-by-name. Default will be natural sorting, obviously.

**Comment by nathanlesage** [comment]
Tada, number two!

**Comment by Jaifroid** [comment]
Thank you very much for working on this!

I've been testing (Windows 10, npm installed version of latest dev), but I can't seem to get it to work. The preference is there, and I've turned it on, and restarted for good measure, but I'm still seeing this in the UI:

![image](https://user-images.githubusercontent.com/4304337/48947458-28ae2880-ef29-11e8-97ae-d4914e562314.png)

You'll notice in the left-hand pane that the end-matter of the book appears before Chapter 2. Also, in the right-hand pane, section 10 comes before section 5....  NB I've deliberately set the files like this to test the issue (I normally work with the numbers padded to work around the issue). Any thoughts as to what is going wrong?

**Comment by Jaifroid** [comment]
@nathanlesage , not sure if you saw my comment above, because this issue is closed. Unless I'm obviously doing something wrong, it might be worth re-opening?

**Comment by nathanlesage** [comment]
Ahhhh! I saw it but forgot it again =D

Sorry for that — but I see the issue. I only implemented the sorting algorithm in the file list (where it is correct), but not in the directory list.

Give me ten minutes!

**Comment by nathanlesage** [comment]
So, the newest commit to the develop-branch should fix this behaviour! Please feel free to test whether or not this works!

**Comment by Jaifroid** [comment]
Excellent!

![image](https://user-images.githubusercontent.com/4304337/48968696-011f9480-efeb-11e8-966b-eb6248eb53bc.png)

Many thanks!! It looks like it's working!

**Comment by nathanlesage** [comment]
Nice! So hopefully I can close this for good now :D 

If not, as always: Please complain!
