### ISSUE TITLE
Recent documents empty

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#4606]
### Description

The "Recent documents" menu under the "File" tab stays empty.

**Expected behavior**: Recent documents menu should be populated with recently accessed files.

Related: #4100, #2245

### Reproducing

1. Open and switch between a bunch of files
2. Check the Recent documents menu -> empty

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Manjaro

**Comment by nathanlesage** [comment]
Isn't this a duplicate of #4100 as you've already linked? If so, can we close this one and bump the other instead?

**Comment by kyaso** [comment]
Okey dokey!
