### ISSUE TITLE
Internal links do not work inside markdown links

### ISSUE THREAD

**Issue by doojonio** [Zettlr/Zettlr#4608]
### Description

After 3.0.0 update control + click on a link like `[this]([[20230904094937]] 20230904094937-my-thoughts)` will not redirect user to the file. Both `ctrl + click on rendered link` and `click on a link, then ctrl + click on internal link inside a parenthesis` methods do not work.

### Reproducing

1. Create a link with ctrl + k
2. Write a label
3. Place an internal link to some file inside a parenthesis
4. Try to click on a link
5. Or try to click on a internal link inside a parenthesis
6. Doesn't redirect

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Linux 38 (Wokstation Edition)

**Comment by itokeiic** [comment]
I have version 3.01 on Windows and I have the same problem with the internal link.

**Comment by nathanlesage** [comment]
What I've commented in another, similar issue: This was never intended to work, so it is not a bug. I will implement internal link titles and prerendering, but I will not "bring back" this old bug.

**Comment by doojonio** [comment]
> What I've commented in another, similar issue: This was never intended to work, so it is not a bug.

Internal links inside markdown links feature is documented [here](https://docs.zettlr.com/en/advanced/zkn-method/#internal-linking). I suppose now it needs to be removed there

**Comment by nathanlesage** [comment]
Good catch, I've removed this now!
