### ISSUE TITLE
Rename a file with Ctrl+R is not working

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#4613]
### Description

When I press ' Ctrl+R' in a note , Zettlr is not opening the text to rename the file.

### Reproducing

* I create a new note.
* Filled in with a Snipped
* Press Ctrl+R to change the name of the file
* Nothing happens, when should open a text box to change the name of the file.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0 Stable release

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ubuntu

### Additional Information

Many thanks for your help.

**Comment by nathanlesage** [comment]
Works in the current version, I think I fixed that with the 3.2.2, if I remember it right!
