### ISSUE TITLE
exporting Markdown profile with default: `gfm+raw_html` produces "undefined" error in 3.0

### ISSUE THREAD

**Issue by mazal** [Zettlr/Zettlr#4620]
### Description

After upgrading to 3.0 via Homebrew, exporting the standard Markdown profile produces an "undefined" error. I have tested every single other export profile—the new ones, the old ones, the strange ones. Each works fine—even the esoteric (to me) profiles, like `.icml`, or `.rst`, or `revealjs`, export with their proper file extension.

In v. 2.3.0 the Markdown profile exported with the default `.markdown` extension. After reading the documentation for 3.0, I was expecting the same—it does actually export but with an `.undefined` file extension. Since the file attempts to open automatically, Apple throws the error dialogue box for unknown app.

I've found several workarounds:
- With `Get Info` in macOS finder, I can specify which app opens that file, and make it the default for every `.undefined` doc. I've done so with the editor I wished to target with the export, so at least the failed dialogue boxes stopped. After that, I can simply change the extension manually—but that's not ideal, and really just kinda weird. Ironically, the targeted editor will open "undefined" just fine, but Zettlr throws a fit if I try it with her. ha!
-  I can also adjust the line, `writer: gfm+raw_html` in the Markdown profile (which appears to be the default?). 
    - If I change it to simply `writer: markdown` that suffices to append the readable `.md` extension. I've tested several formats (from `pandoc --list-output-formats`). With an exception or two, most worked as expected with a routine `.md`.

So despite being able to work w/in this minor "bug," I have gotten very used to my friend, `.markdown` <3. I routinely swap editors/parser-renderers, and rapid test markdown snippets. As documented by Zettlr, the `.markdown` extension is a well-considered device, that has saved me grief by not overwriting my regular `.md` files. I'm not an experienced developer, but I feel like I ought to have been able to figure out through the documentation how to append `.markdown`. I've spent some hours going through Zettlr and Pandoc docs, but I simply can't find it—or gets too in the weeds.

Is there a solution I can deploy? Is `gfm+raw_html` the actual default, or some holdover? I've only been using Zettlr for a couple of weeks, so I don't have a firm knowledge of what the Markdown profile _was_, but the old and the new profiles appear identical, and I don't believe I've made any changes, other than to test various formats. The log notes: `[Assets Provider] Found outdated filter tags.lua; copying` — is this related?

<img width="780" alt="Screenshot 2023-09-06 at 5 23 59 PM" src="https://github.com/Zettlr/Zettlr/assets/2043333/796dfcc6-e37b-40a1-8fef-0edb6112ea06">

<img width="747" alt="Screenshot 2023-09-07 at 1 21 56 AM" src="https://github.com/Zettlr/Zettlr/assets/2043333/ae66b896-afdb-4147-8ae2-af79090813f2">

### Reproducing

Assuming the Markdown.yaml profile on my system is the default standard, simply pull up the export menu (⌘/Ctrl+E) and choose `Markdown (gfm+raw_html)`. In the body of my description, I present the various tests I applied so it's reproducible on my setup. I'm attaching an image of the profile, taken from the Asset Manager. Aside from this one profile, every other profile "works" as expected (meaning no error), except that with LaTeX to Markdown, it appends an `.md` where I would expect `.markdown` appended.

<img width="1249" alt="Screenshot 2023-09-07 at 12 13 01 AM" src="https://github.com/Zettlr/Zettlr/assets/2043333/79d994ab-e1dc-43cd-8c47-6720e882d8c2">

### Zettlr Version

Stable (most recent version)

### Specify version

Version 3.0.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Venutura 13.5.1 (22G90) 

### Additional Information

This is a non-critical bug. The Log Ouput is: [Assets Provider] Found outdated filter tags.lua; copying ...

**Comment by nathanlesage** [comment]
> After reading the documentation for 3.0, I was expecting the same—it does actually export but with an .undefined file extension.

Could be because I made a mistake with separating extensions from the actual writer property. I'll have to look at this but if my reasoning is right, you should be able to export successfully without extensions, and it should produce the "undefined" extension whenever there is any extension in there. In other words, mitigation until there's a fix: rename the file afterwards.

**Comment by mazal** [comment]
Thank you, Hendrik! Yes, that's what I've been doing—mitigation. I see you've worked on this already, which is awesome. I'll show my true ignorance—do I need to update Zettlr to effect the fix? I'm not familiar/comfortable with nightly installs and the like. Should I wait for a version update? 🙏

**Comment by nathanlesage** [comment]
Yes of course you will need to update -- I'm going to wait a little bit longer until I release an update, simply so that I can bundle a tad more fixes. If you don't want to wait for that long, you can definitely install the next nightly. There haven't been any unstable changes yet!

**Comment by mazal** [comment]
I'm thrilled I could contribute an observation that made it into Zettlr's workflow. Of course, I'll wait. 

In the meantime, you forced me to think deeply about GitHub/git to navigate these pages—time well spent. I will pass on the nightlies; I know what they are and what they do, but I'm not ready to cope if I mess up. 😬

A final thought: I accidentally stumbled into the update by upgrading some other Homebrew formulae. I found out Brew decides to upgrade *everything* all at once. Yipes!  👀 

I had read enough of Zettlr's announcement and a portion of the README to close all my files and even shut down my workspaces in anticipation of a deep dive into a new install. Brew made that decision for me, and I'm glad it worked out great. I love the powerful new features. Although, you might add a warning near the top of the README for Homebrews, considering how much emphasis is placed on prepping for 3.0. in the documentation.

Congrats on a fantastic upgrade! 🎉 Again, thanks, Hendrik— I'm happy to have found this community. <3
