### ISSUE TITLE
Why insisting on US spelling?

### ISSUE THREAD

**Issue by kerryland** [Zettlr/Zettlr#4627]
### Description

Given I have every language preference I can find set to `en_GB`, why does Zettlr insist on using US Spelling checks?

![pref](https://github.com/Zettlr/zettlr-docs/assets/398113/5b54b907-b5a4-41fe-930e-c7c722a353a4)

Actual behaviour:
![why-us](https://github.com/Zettlr/zettlr-docs/assets/398113/bd0f232c-348a-4e99-b389-915816fadc84)

Also, the tiny little box in the bottom-right of second image that says "US" can be clicked to change the language, but the choice doesn't seem to have an effect, doesn't seem to be stored, and likes to revert to "Auto"

Thanks for listening. I hope this helps.

### Reproducing

Configure as above.

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr Version: 3.0.0 (UUID: 6c414122-4a3a-48c7-a6f3-cec55b393258)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

win32 10.0.19042 (architecture: x64)

**Comment by nathanlesage** [comment]
There are two spell checkers. You have activated the British one, but you also use LanguageTool, and LanguageTool is very keen on always using American English. I haven't yet had a chance to figure this out entirely but their documentation contains potentially useful settings that I simply need to support in the app to nudge it towards, e.g. British English instead.

**Comment by ABrads** [comment]
I have the same problem as @kerryland, but only on Zettlr. I have no problems with british English on Obsidian. Hope this helps.

**Comment by ams-123** [comment]
Same issue here. LanguageTool auto-detects the language as US. If manually set to UK, spelling suggestions are still based on US spellings.

**Comment by nathanlesage** [comment]
Bonjour!

So, I now did some testing with the LanguageTool API, and I think I've found a good path to implementation. Here's what I've found:

1. LanguageTool just defaults to `en-US` when `language` is set to `auto`
2. When `language` is set to `auto`, there is a parameter that Zettlr currently doesn't use called `preferredVariants`. This list accepts just a big array of language variants (the "main" language doesn't matter, I've had success with a list of `en-GB, de-AT, fr-CA`, and it would auto-detect the appropriate language group)

This is independent of the `montherTongue` setting that Zettlr already uses.

So here's what I'm going to do: Add another setting that will allow you to select from a list all preferred variants that you want. This then will make language detection better.

What I will also do is implement a check for a possible YAML frontmatter value of `lang: en-GB` or similar so that LanguageTool will use that one instead of falling back to `auto` where possible.

**Comment by kerryland** [comment]
> This is independent of the montherTongue setting that Zettlr already uses.

But why is it independent? Why not use `motherTongue`?

> Add another setting that will allow you to select from a list all preferred variants that you want.

But can't I already see that setting in the first screenshot? "select the languages for which you wish to enable automatic spell-checking"

**Comment by nathanlesage** [comment]
> But why is it independent? Why use auto? Why not use motherTongue?

I don't know. If we were to use motherTongue, this would really annoy bilingual writers (such as myself). Auto with preferred variants is smarter here.

> But can't I already see that setting in the first screenshot? "select the languages for which you wish to enable automatic spell-checking"

No? As I already mentioned, the spell checkers are NOT language tool.

**Comment by kerryland** [comment]
Ah. No problem. It's true that I am monolingual, so definitely not the expert here!

> > But can't I already see that setting in the first screenshot? "select the languages for which you wish to enable automatic spell-checking"
> 
> No? As I already mentioned, the spell checkers are NOT language tool.

Sure, but why would the configuration values be different? Would you want to support one set of languages for spell checking and a different set for "language tool"? Isn't that unlikely?

Again, I acknowledge my ignorance on the subject!

**Comment by nathanlesage** [comment]
> Would you want to support one set of languages for spell checking and a different set for "language tool"?

Basically, yes. The spellcheckers basically only perform spell checking, and LanguageTool does that and much more (style and grammar checking). A spell checker cannot detect the language, LanguageTool can. I even mentioned somewhere in the docs that I do not recommend running both a spell checker and LanguageTool at the same time.

I agree that it can be somewhat confusing, but a new preferences UI is also in the works. (In fact, I need that one to be merged before I can add this novel setting…)

**Comment by nathanlesage** [comment]
I think last week or so I finally implemented preferredVariants, so it should now work.
