### ISSUE TITLE
Blank TOC page when exporting to latex beamer

### ISSUE THREAD

**Issue by dranjor** [Zettlr/Zettlr#4631]
### Description

When exporting to Beamer, an empty table of contents is created (no slide title, no content). `toc-title` works, but page is empty. No Pandoc export via command line works fine.

### Reproducing

1. Create profile for beamer 

2. Create a test file
```
---
title: Test Presentation
toc: true
toc-title: "My TOC"
toc-depth: 1
---

# Sec 1

## Slide 1

<!-- content -->

## Slide 2

<!-- content -->

# Sec 2

## Slide 3

<!-- content -->

## Slide 4

<!-- content -->
```
3. Export to beamer

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Gentoo

**Comment by samcarter** [comment]
I've seen similar problems with pandoc in the past. The usual culprit was that pandoc did not run latex often enough to populate the toc. 

Can you check the intermediate .tex file if it contains `\tableofcontents`?

**Comment by nathanlesage** [comment]
Thank you, @samcarter, for chiming in. I agree that this is likely a solely Pandoc-based problem and thus not in scope for Zettlr per-se.
