### ISSUE TITLE
Changes to "Editor Input Mode" ignored until restart

### ISSUE THREAD

**Issue by kerryland** [Zettlr/Zettlr#4635]
### Description

When I change "Editor Input Mode" nothing actually changes until I restart Zettlr.

### Reproducing

- Start Zettlr
- Open Preferences
- Set "Editor Input Mode" to "Normal" and close "Preferences"
- Create a new file, containing the text "Hello World"
- Save the file
- Open Preferences
- Set "Editor Input Mode" to "Vim" and close "Preferences"
- Type "dd" on the "Hello World" line

I expect the line to be deleted, because that's what "dd" does in vim, but instead I see "ddHello World" on the screen.

If I exit and restart Zettlr I find that the editor now behaves as expected -- ie: it really is in vim-mode.
 

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0 (UUID: 6c414122-4a3a-48c7-a6f3-cec55b393258)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

win32 10.0.19042 (architecture: x64)

**Comment by nathanlesage** [comment]
Works in the current dev branch
