### ISSUE TITLE
Ctrl-k doesn't delete the rest of the line

### ISSUE THREAD

**Issue by richardbatty** [Zettlr/Zettlr#464]
On MacOS I'm very used to using Ctrl-K when editing text to delete everything on a line that's after a cursor. In Zettlr, Ctrl-K inserts link markdown, whereas because of googledocs I'm very used to link insertion being Cmd-K. From looking in the settings, it looks like this is because Zettlr doesn't distinguish between Cmd and Ctrl shortcuts. Could we have a way to customise these shortcuts, and ideally distinguish between Cmd and Ctrl?

**Comment by nathanlesage** [comment]
Yes, it has to do with CodeMirror internal shortcut handling, I certainly can amend this, because Ctrl+K is not intended to trigger a link on macOS, only on Windows and Linux!

**Comment by nathanlesage** [comment]
Cleaned up the shortcuts, now the `Ctrl`-shortcuts are only registered on non-Apple computers, while `Cmd`-shortcuts are only registered on macOS!
