### ISSUE TITLE
Zettlr does not start (Win 10) 

### ISSUE THREAD

**Issue by matzefrey** [Zettlr/Zettlr#4651]
### Description

The installation runs smoothly, but then I can not open Zettlr. The first time I try, the "Open Workspaces" window still comes up, but stops working and I need to crash the window. The second time I try to start, nothing happens. Still, it shows Zettlr Background processes running, but nothing happens. 

### Reproducing

I don't know, how you can reproduce this. I have deleted and reinstalled the program several times. Version 2.3.0 runs without any problems. 

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 [Education] (10.0.19045 Build 19045)

**Comment by nathanlesage** [comment]
Have you also tried removing the `config.json` as outlined in the troubleshooting documentation?

**Comment by scotrod** [comment]
> Have you also tried removing the `config.json` as outlined in the troubleshooting documentation?

Can you please point the parent directory of this file, for Windows? I can't find anything under `C:\Users\Miro\AppData\Local\Programs\Zettlr` and its subfolders.

**Comment by scotrod** [comment]
> Have you also tried removing the `config.json` as outlined in the troubleshooting documentation?

Can you please point the parent directory for Windows? I cannot find the config under `C:\Users\User\AppData\Local\Programs\Zettlr` and the subfolders in it.

**Comment by matzefrey** [comment]
> Have you also tried removing the `config.json` as outlined in the troubleshooting documentation?

Now I did! And now it works - thanks a lot. 

However, 3.0.0 has problems to open a big workspace with a lot of subfolders. 

> Can you please point the parent directory for Windows? I cannot find the config under C:\Users\User\AppData\Local\Programs\Zettlr and the subfolders in it. 

I found the config file in: 
C:\Users\Myname\AppData\Roaming\Zettlr

**Comment by scotrod** [comment]
![Screenshot 2023-09-15 144636](https://github.com/Zettlr/Zettlr/assets/45900128/728d89e1-b672-4bab-81f8-c531873299f1)
This is really strange. There is no such config there.

**Comment by scotrod** [comment]
Thanks, I was searching it under local, where the Zettlr executable is pointing to... However after deleting the config, I'm still unable to open my Workspace:
https://github.com/Zettlr/Zettlr/issues/4646

Hope that some dev will pay attention to this soon. It's unusable at this point.
