### ISSUE TITLE
"New File" does nothing when no folder is opened

### ISSUE THREAD

**Issue by frederik-elwert** [Zettlr/Zettlr#467]
## Description

When clicking the "create new file" button (or the corresponding menu entry), nothing happens if no folder is open in Zettlr.

## Reproducing

1. Open Zettlr and make sure no folder is open.
2. Click the "create new file" button or choose the corresponding menu entry.
3. Nothing happens.

## Expected behaviour

Given Zettlr’s auto-save policy, I understand that it’s not an option to create a new file in an “unsaved state” (which is what most text editors would do). So I see two options:

1. When no directory is open, present a file chooser dialog to let the user specify the location of the new file.
2. Alternatively, at least show a message with something like "To create a new file, open a folder first."

**Screenshots**

## Platform
 - OS and version: Ubuntu 18.04
 - Zettlr Version: 1.5.0
 - Screen Resolution: 1920×1080

**Comment by nathanlesage** [comment]
Good point; currently a lot of functionality is based on the fact that at least a directory is selected. It should be part of the UX design improvement I'm planning for the second halve of the year!

**Comment by KnowledgeGarden** [comment]
Yup. Booting 1.6 on latest MacOS, gave it permission to access disk, then had to create a new /Documents/zettlr/ directory, which it took as root. Now, I can create new files.

**Comment by KnowledgeGarden** [comment]
Odd there's a bot marking things as stale; this was an issue to be dealt with; what would a bot know about that?

**Comment by nathanlesage** [comment]
Now there's a notification prompting you to select a directory
