### ISSUE TITLE
Save resets file to a former version

### ISSUE THREAD

**Issue by StuporMundi1337** [Zettlr/Zettlr#4670]
### Description

Hello there!
I'm encountering a bug concerncing the auto save function (I suspected a connection to https://github.com/Zettlr/Zettlr/issues/4628, but after some testing, it seems to be worthy of a standalone issue).

Sometimes when Zettlr automatically saves, the file is reset to a former version and the progress is lost. 
It happened twice this morning in a period of around 2h, killing my work of around 40 minutes in total. The first time I literally watched it happen: I stopped typing, thinking about what to write next, and when the asterisk in the file tab disappeared after 5 seconds ("auto save after a short while") so did my last few paragraphs. Just completely gone, no Ctrl+z etc. possible. The second time I didn't watch, but I also didn't save manually before looking out the window, upon looking back, I realized, that the same thing happened again.
I'm not completely sure, but I think that the file reset to a state that it had for a longer time, i. e.: each time it reset to the version that was there BEFORE I had a pomodoro session break of five minutes. 

However, I then changed to auto saving immediately and now I can reproduce the bug in a matter of seconds. I'm just typing stuff and just randomly on auto-save it resets the file. I did a short video of it: 

https://github.com/Zettlr/Zettlr/assets/100134191/67b98a31-7b5c-466a-ac73-cb8d048b2cf3

In this recording, I'm literally doing nothing else but typing! As you can see, sometimes parts of it just randomly disappear.
This is really unfortunate. I will try turning off the auto save option, maybe that'll help. I hope this doesn't happen randomly on manual saves, too...

### Reproducing

Auto-save a bunch of times, preferebly with "auto save immediately".

### Zettlr Version

Stable (most recent version)

### Specify version

3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows	10.0.19044

**Comment by nathanlesage** [comment]
Thanks for another issue with a different angle on that problem. All of this should be fixable (for now) by disabling autosave. I suspect the main issue is that when you type *while* Zettlr is (auto)saving, this creates an inconsistency that it cannot properly handle, and then it gets confused. When you manually save, you kind of "force" yourself to not write a character while you press Ctrl/Cmd+S, and this means that Zettlr won't choke.

**Comment by StuporMundi1337** [comment]
Thanks for the quick response. I suspected something like that, however when I first encountered the problem, I didn't type, I just watched it happen.
But the good news is: I've been using manual save for the rest of yesterday and today, and so far, fingers crossed, didn't encounter any problems.

**Comment by StuporMundi1337** [comment]
Changed the title cause the bad news keep coming...
I was able to reproduce the bug with manual save and kill quite an amount of my recent work...
It seems that the bug also happens when the last input is too close to the saving process. I just hit Enter and then immediately pressed Ctrl+S, all of a sudden the cursor jumped to the top of the file and a good amount of the text I'd just written was gone.

I experimented a little and with pressing random keys immediately before and after Ctrl+S I can now reproduce the mistake quiet reliably (see video).

https://github.com/Zettlr/Zettlr/assets/100134191/25831b8e-0883-49d7-b3b1-4ee3e0da8e08

So to everybody: Wait a second or two before saving.

**Comment by nathanlesage** [comment]
> It seems that the bug also happens when the last input is too close to the saving process. I just hit Enter and then immediately pressed Ctrl+S, all of a sudden the cursor jumped to the top of the file and a good amount of the text I'd just written was gone.

Yes, this is what I was fearing. I think I forgot to implement a locking mechanism during file saves …

**Comment by StuporMundi1337** [comment]
Another observation: Today I worked quite a lot with Zettlr, and unfortunately I noticed that even when I wait for a couple of seconds after the last input before I manually save, the file is also sometimes reset. As it's happening around 1/5th of the time, this makes Zettlr hardly usably for me right now... I've been loosing so much stuff recently. I will try a reinstall, but I'm not sure, if it will help.

**Comment by nathanlesage** [comment]
So, I just did some digging, and … puh, I think I have an idea of how to fix it, but I need to say that it will be hard for me to debug this problem, as I don't experience it. However, here are some observations:

1. First and foremost, if you have "Load remote changes" active, disable that checkbox NOW (see screenshot). I have changed the default for this option to "true" for 3.0.0 because I thought it was more convenient; but it turns out I should've done a bit more thinking when implementing this — so this is my apology number 1. Sorry!
2. Disabling this method will open a few dialog boxes that ask you whether to "reload changes" (which you should say no to if you didn't modify the file with another program), BUT this will prevent any data loss.
3. I have found out numerous issues with the document handling process while tracing what is going on, and I have a few ideas what might be happening. I am prioritizing this bug now to ensure it gets fixed fast.

So, apology number 2 for pushing you into; I believe nobody should ever experience data loss and it really does hit me that it now has happened. I understand your frustration, and I will get to it asap.

![image](https://github.com/Zettlr/Zettlr/assets/17251683/0a601f3c-730a-4ae2-86fc-b6e3f7a8c747)

**Comment by StuporMundi1337** [comment]
Okay, thank you very much. I've read about it in the changelog, I also know the window from before, but didn't give it further attention. It seems to work just fine now. 
I'm sorry, I didn't mean to sound harsh or anything, I was a little frustrated, because it kept me from working in the brilliant environment that Zettlr is. Since I've already a created a big ecosystem of multiple thousand files it would be a real shame if I had to move all that stuff into another environment.

Thank you for your transparency, your way of handling problems and communicating with the community, as well as your excessive use of Zettlr for your own work are honestly a huge selling points for Zettlr!

**Comment by nathanlesage** [comment]
> I'm sorry, I didn't mean to sound harsh or anything, I was a little frustrated, because it kept me from working in the brilliant environment that Zettlr is.

I did not experience you sounding harsh, so no worries. Data loss is a serious issue, and so it's absolutely understandable to be a bit frustrated!
