### ISSUE TITLE
Custom CSS not working

### ISSUE THREAD

**Issue by carnendil** [Zettlr/Zettlr#4675]
### Description

Custom CSS snippets (as described in the [docs](https://docs.zettlr.com/en/advanced/custom-css/#css-code-snippets)) does not work on Zettlr 3.0.0.

Specifically, custom font, background and maximum width no longer work in my case, after upgrading to version 3.0.0.

Related: #4609 and (maybe) #4589.

### Reproducing

Follow instructions to use [custom CSS snippets](https://docs.zettlr.com/en/advanced/custom-css/#css-code-snippets).

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Please read the entire document. To quote from the custom CSS section:

> The examples in this document haven't been updated in some time, so they may not work out of the box.

I am aware that those examples do no longer work, but I also do not have time to think of new CSS customizations.

This is not a bug. I am waiting for the community to update these examples. Feel free to team up with people over on Discord, I'll happily merge any PRs on the documentation repository that improve upon the examples.
