### ISSUE TITLE
Middle Clicking Links opens Websites in Electron Browser instead of the System's Webbrowser

### ISSUE THREAD

**Issue by H0d3nk0b0ld** [Zettlr/Zettlr#4684]
### Description

Title says it.

Whenever I middle click (pressing down the mouse wheel) on a Link to a Website Zettlr opens the Site inside a new Window with Electron.

This _might_ also be a **security problem** since opening rogue Websites in said Electron window might make you vulnerable to attacks when it is not set up for this in the first place, but I don't really know, so I leave this for others to judge.

### Reproducing

- Open a markdown file with Zettlr
- Paste `[Test Link](https://www.example.com)` into the file
- Middle Click the Link

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.1

### Installation Method

AUR (Arch Repository)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Arch Linux

### Additional Information

I use the Version from the official Arch repository, no further modifications done.

I posted this on Reddit and was advised to open an issue about this:
https://www.reddit.com/r/Zettlr/comments/16nuy29/middle_clicking_links_opens_built_in_browser/

**Comment by pseandersson** [comment]
@nathanlesage I will take a look on this, it is opening the electron GuestWindow on middle click.

**Comment by nathanlesage** [comment]
> @nathanlesage I will take a look on this, it is opening the electron GuestWindow on middle click.

Please don't, I already did a fix and will open an according PR sometime over the day -- you can absolutely do a review of it, though!
