### ISSUE TITLE
Disable cursor blinking

### ISSUE THREAD

**Issue by philippludwig** [Zettlr/Zettlr#4687]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Is it possible to get a setting for disabling the blinking of the cursor?

I found [this old reddit thread](https://www.reddit.com/r/Zettlr/comments/paq6a6/cursor_blinking_in_zettlr_program/) but the provided solution does not work (anymore).

### Example Workflow

Some checkbox or similar to disable it. A working CSS snippet is fine, too.

### Caveats

None.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by philippludwig** [comment]
Nevermind, figured it out myself with the help of the documentation:

```
.cm-layer {
  animation-duration: 0ms ! important;
}
```

**Comment by tkuismin** [comment]
The described solution doesn't work anymore. This does, however:

```css
.cm-editor * {
  animation: none !important;
}
```

**Comment by nathanlesage** [comment]
Instead of blocking all animations, I suggest you only block the cursor animations. Take a look into the main editor theme, where they are defined. This way you won't accidentally break potential future animations.
