### ISSUE TITLE
Citation format is wrong when pasting a full BetterBibTeX Citation Key instead of using autocomplete.

### ISSUE THREAD

**Issue by Mela** [Zettlr/Zettlr#4689]
### Description

My citation options in Zettlr are set to the following: 

![Bildschirmfoto 2023-09-24 um 08 16 06](https://github.com/Zettlr/Zettlr/assets/361364/32c612f1-0408-4353-a6b4-86e02e15520c)

If I type `@` and then use the citation autocomplete, the citation format in my document has the format I've chosen in the settings: 

![Bildschirmfoto 2023-09-24 um 08 18 14](https://github.com/Zettlr/Zettlr/assets/361364/92581659-de43-412c-8f49-a78037052849)

But if I copy the full citation key from Zotero and copy it into my Zettlr document, the in-text citation style now looks linke the second or third setting:

![Bildschirmfoto 2023-09-24 um 08 19 10](https://github.com/Zettlr/Zettlr/assets/361364/996e2b5b-2247-4a57-a98e-79cc95d4b7ad)

Result:

![Bildschirmfoto 2023-09-24 um 08 21 08](https://github.com/Zettlr/Zettlr/assets/361364/845deac3-1497-4850-9486-b4f117bc8869)

This is bothersome, because sometimes copying the full citation key without having to go through the autocomplete process would speed things up. 

### Reproducing

1. Go to Zotero. 
2. Open a source document
3. Look for the first letters found in the 'Citation Key' field. 
4. Switch to Zettlr
5. Open a Zettlr document 
6. Type in `@` and then followed by the first letters of the citation key.
7. Chose the right entry from the dropdown menu that will pop up.
8. ---
9. Go to Zotero. 
10. Open a source document
11. in the entry details copy the value of the topmost field ('Citation Key')
12. Switch to Zettlr
13. Open a Zettlr document.
14. type `@` and paste the citation key value into it. 

### Zettlr Version

Stable (most recent version)

### Specify version

3..0.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

13.5.2 (22G91)

**Comment by nathanlesage** [comment]
Is there any difference in the actual characters (these appear when you select the text so that the citation kind of "un-renders")?

**Comment by Mela** [comment]
... oh ... 

*steigt von der Leitung*

**Comment by nathanlesage** [comment]
I consider that as a "Der Groschen ist gefallen", okay? 😄
