### ISSUE TITLE
Website install instructions (Homebrew) outdated

### ISSUE THREAD

**Issue by mgiugliano** [Zettlr/Zettlr#469]
## Description
The information on the websites, concerning the Homebrew install procedure (macOs) is outdated and return errors.

## Reproducing
Typing at the prompt - as suggested -
$ brew tap caskroom/cask
returns the error: "Error: caskroom/cask was moved. Tap homebrew/cask-cask instead."
But also the new command:
$ brew tap homebrew/cask-cask
returns a new error and fails.

Supposedly, the correct install command is only the second one appearing in the install instructions: 
$brew cask install zettlr
However, this one does not fetch the very latest release from GitHub and it is stuck to 1.4.3

## Platform
 - OS and version: macOs Catalina 10.15.2 (19C57)

**Comment by nathanlesage** [comment]
Hey, sorry to miss your issue for so long — cask is apparently now included in homebrew, so just running `brew cask install zettlr` is indeed enough. I removed the line therefore!
