### ISSUE TITLE
Adding a reader extension to the YAML defaults file makes it unselectable in Project Settings

### ISSUE THREAD

**Issue by jdnicholas** [Zettlr/Zettlr#4699]
### Description

When adding an extension to the reader line of the Markdown -> PDF Defaults file
e.g. `reader: markdown+rebase_relative_paths`, 
the Export Profile is no longer selectable in the Project Settings menu when choosing which profile to export with.

The profile description in the Assets manager shows up as markdown+rebase_relative_paths  -> PDF (lowercase markdown), rather than the standard Markdown -> PDF (capitalised Markdown)

### Reproducing

- Create new custom defaults file

- Add `reader: markdown+rebase_relative_paths` to the line as below:

```
# ZETTLR DEFAULTS FILE
# ====================
# Conversion: Markdown --> PDF (requires TeX suite to be installed)
# More info: https://pandoc.org/MANUAL.html
reader: markdown+rebase_relative_paths
writer: pdf
...
```
- Save the file.
- Make a directory into a project
- The defaults file is not selectable as an export profile.

If the profile was previously created without the extension, and selected as a project export profile, and the default file then edited to include the extension, it remains active for exporting the project, but the option to view or select it disappears in Project Settings.

If the extension is deleted from the defaults file and the file saved, the option reappears in the project settings, and is still selected.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

The Export Profile is still visible and selectable when exporting a single file.

**Comment by nathanlesage** [comment]
This is likely an easy fix. I'll have a look later today. We've had a very similar issue a week ago.

**Comment by nathanlesage** [comment]
I know that I've recently added a commit that iirc fixes this; could you please try out 3.0.2 and close this issue if your issue is fixed now, or quickly mention that it still doesn't work?

**Comment by jdnicholas** [comment]
Unfortunately, it seems like the issue still persists in v3.0.2

**Comment by jdnicholas** [comment]
I did some digging, and as far as tell, in the `App.vue` file in the `win-project-proprties` folder, there are the following lines:

```
import { PANDOC_READERS, PANDOC_WRITERS, SUPPORTED_READERS } from '@common/util/pandoc-maps'

...More Code...

exportFormatList: function (): ExportProfile[] {
      // We need to return a list of { selected: boolean, name: string, conversion: string }
      return this.profiles.filter(e => SUPPORTED_READERS.includes(e.reader)).map(e => {
        const reader = e.reader in PANDOC_READERS ? PANDOC_READERS[e.reader] : e.reader
        const writer = e.writer in PANDOC_WRITERS ? PANDOC_WRITERS[e.writer] : e.writer
        const conversionString = (e.isInvalid) ? 'Invalid' : [ reader, writer ].join(' → ')
```

which from my very basic understanding of what's going on, means that only the "SUPPORTED_READERS" from `common/util/pandoc-maps.ts` are loaded as options?

If I edit the `pandoc-maps.ts` file to include:

```
export const PANDOC_READERS: Record<string, string> = {
     ....<More Options>....
    'markdown+rebase_relative_paths': 'MarkdownRebase',
     ....<More Options>....
}

....<More Code>....

export const SUPPORTED_READERS = [
  'commonmark',
  'commonmark_x',
  'gfm',
  'latex',
  'markdown',
  'markdown_mmd',
  'markdown_phpextra',
  'markdown_strict',
  'markdown+rebase_relative_paths'
]
```

I can get the export profile I created with `reader: markdown+rebase_relative_paths` to appear in the Project Export options, so I think this confirms my thinking.

Unfortunately, I don't know what this means for a solution, as just editing the supported readers to add various extensions doesn't seem like an ideal option. But hopefully this might be useful information still.

**Comment by nathanlesage** [comment]
Found the last remaining issue: I only fixed that for the single file export, now it's also fixed in the project settings, so it should work coming with the next update.
