### ISSUE TITLE
Dissemination of the app to repositories (Brew Cask, Launchpad, etc.)

### ISSUE THREAD

**Issue by Inoverse** [Zettlr/Zettlr#47]
## Description
The app is currently only available through Github and/or website download.

## Reproducing
-

## Expected behaviour
A cask for downloading/installing the app through [cask](http://caskroom.io/) would be great!

**Screenshots**

## Platform
 - OS: [e.g. iOS] macOS
 - OS Version [e.g. 11] Doesn't matter
 - Zettlr Version [e.g. 0.15] Latest
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information
Would be great for people which streamlined their macOS setup with homebrew / cask.

**Comment by Jaifroid** [comment]
Could I suggest this issue title is changed to "Allow publication of Zettlr in supported app stores"? There are various places it could be published.

**Comment by Inoverse** [comment]
Yep, would be great!

**Comment by nathanlesage** [comment]
Let's be frank: I'm extremely overworked with all the features I've put into Zettlr so far (and am likely to continue to add features, albeit much slower than currently), so it would cost me too much time to publish to every single app store I stumble upon. This is why I'm fond of the idea by @Jaifroid. Letting users take matters into their hands in disseminating the app to the various stores is a great idea of multitudinal crowd power.

But we'd have to envision a procedure of how to do this. On the one hand I'm happy that so many are trying to help the app grow more popular, while on the other hand I'm still anxious as to letting it completely loose (you know, parental feelings for the app and stuff).

Any thoughts on this?

**Comment by nathanlesage** [comment]
Sounds like a good start. Yep, the Zettlr-account here is organisation level, I don't even know anymore why I did this, but it worked out pretty well!

I think the first platforms to disseminate the software to should be Launchpad (for Debian), and the respective alternatives for Fedora-based systems and Arch (there have been requests, and there's also this rogue package).

This would basically only need some small amount of coordination between people committed to doing this (e.g. I'll push to the master branch after a release is done, then all people can `git pull` to their computers, compile and then share the files with me for uploading here and upload them to these platforms. Afterwards I'll publish the official release).

Maybe we should also discuss, where else we could publish the app to (Brew Casks was the first idea, but there are other things for sure).

**Comment by Jaifroid** [comment]
It might be a better process if you provided any dev you're partnering with access to a forked and suitably named repository in the Zettlr GitHub domain, so you / the Zettlr organization have access to the source code for compiling the app, rather than the dev doing it on their own computer only and sending you the final compiled executable/bundle. Just a suggestion (based on what we do at [Kiwix](https://github.com/kiwix) -- you'll see the multiple repos with different flavours if you scroll down).

**Comment by nathanlesage** [comment]
Yeah, the criss-cross sending of files is indeed not the optimal solution. So for compiling to different platforms it would make sense to grant people committed to compiling access to the releases section, so that everyone can directly upload compiled packages to a draft release. This should work!

The benefit is that Zettlr only needs one code section for all different platforms and therefore it's even easier, and we can use the Zettlr domain for potential additional softwares/plugins/whatever.

**Comment by Jaifroid** [comment]
Problem is that GitHub releases require that the source code be available in a branch. If you're wary about giving direct push access to a separate app space on your repo, I guess you could create different branches for each store release, and ask a dev to make a PR from a forked repo, using the "Compare across forks" option. You could then approve or not the PR, so it can be incorporated into the branch, using [this procedure](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). A release can then be based on that branch. But this workflow could become complicated if you have to rebase each branch every time you merge main-app changes to master...

**Comment by nathanlesage** [comment]
Short update: With a friend I managed to set up a Jenkins build server, which means that at least in a short amount of time we'll be able to offer any binary possible, so we're getting somewhat closer to being able to publish the app to various platforms :)

**Comment by nathanlesage** [comment]
Is there any update here? Anybody willing to do this for any repository?

**Comment by Jaifroid** [comment]
I compile and publish the Open Source apps Kiwix JS, WikiMed and Wikivoyage to the Microsoft Store for Windows 10. For Electron apps, the process looks fairly straightforward here:

https://electronjs.org/docs/tutorial/windows-store-guide 

I'd be willing to have a go, though can't promise anything about timescales at the moment. Is it of interest? Unless you have an account (there's a one-time set-up fee), I'd publish it on my account, but would of course make 100% clear where the open source code is, and comply fully with the licence. The resulting binary can be published (and installed) independently of the Store, so can be made available on GitHub (and Jenkins?).

**Comment by ploum** [comment]
Zettlr seems to be distributed more than when this issue was created (for instance, it is now available on brew cask). 

I would suggest closing this issue and opening one for each of the specific appstores where Zettlr would be needed.

**Comment by Jaifroid** [comment]
I agree!

**Comment by nathanlesage** [comment]
Good point. Besides, now as we have a forum we can discuss it over there 👍
