### ISSUE TITLE
Nested lists: tabulations cannot be used

### ISSUE THREAD

**Issue by Beurt** [Zettlr/Zettlr#470]
Hi,

Thank you for Zettlr, it seems a very interesting tool!

I found a strange behaviour with nested list in my own Mardown files (I have already thousands!): when the list levels are marked with tabs they are not recognized by Zettlr. For instance (`\t` is for a tabulation):

```
- level 1
\t- level 2
- level 1
```
Renders as:

> - level 1
> - level 2
> - level 1

But it should render as:

> - level 1
>     - level 2
> - level 1

When tabs are converted into (4) spaces, the rendering is correct.

**Comment by nathanlesage** [comment]
Sorry for only answering now, I have forgotten to do so earlier!

To your question: Tab doesn't insert a tab character in Zettlr, but this is by design. Why?

- Tabs can be replaced with four spaces (most commands do that)
- Tabs are sometimes hard to distinguish from multiple spaces, and depending on implementation, you may accidentally end up exporting tabs instead of spaces, so this can be seen as a failsafe.
- Concerning list indentation: If the cursor is between the list sign and the text, you can use `Tab` and `Shift-Tab` to (un)indent the list automatically.

**Comment by Beurt** [comment]
I'm sorry too for the late answer.

The problem was not with new files created with Zettlr, but that if we use in Zettlr some old Markdown files including nested lists using tabulations instead of (4) spaces, their render will be messed up.

For instance, I already have hundreds of such files (my previous Markdown notes) and it is a no go for Zettlr since all my nested lists (that I use a lot) are broken (no more nesting).

**Comment by nathanlesage** [comment]
Ah! Mh … well, after all, maybe it should display either way. Let me have a look

**Comment by felipehw** [comment]
@nathanlesage 
I have a lot of files with markdown indentation marked consistently by TABs. I tried to write with Zettlr but he opts for spaces instead of TABs for indentation.
For what I've read here .... this is by design.
So Zettlr never will support TAB indentation?

**Comment by nathanlesage** [comment]
Well, you can use tabs in Markdown files, but spaces are recommended in cross-device-situations, so that is what's the default, yes. But Zettlr does support tab indentation

**Comment by felipehw** [comment]
But is there a way to configure the nested items in a list, for example, to be marked using TAB instead x whitespaces?
Because I perceive that my TABs got mixed with the whitespaces of the "automatic" indentation ...

**Comment by nathanlesage** [comment]
Umm, might be config option …?

**Comment by felipehw** [comment]
The only option that I find about indent was *Indent by the following number of spaces* at *Preferences* → *Editor*.
Is there an option to indentation being TABs instead whitespaces?

**Comment by nathanlesage** [comment]
Not now, which is why I said it might be a config option
