### ISSUE TITLE
Internal ([[xxxx]]) links enclosed within Markdown link format don't work.

### ISSUE THREAD

**Issue by AnomalousG** [Zettlr/Zettlr#4700]
### Description

After upgrading to version 3.0.1, the markdown style internal links `[Title]([[20230927151434]])` in my collection no longer work.

Bare internal links, e.g. `lorem [[20230927151434]] ipsum`, work as expected.
But once I enclose an internal within markdown link format it stops working. Hovering shows a tooltip with ` "safe-file:///home/.../active/workspaces/folder>/[[20230927151434]]" ` , there is no preview, and I can't Ctrl+Rclick to open the link. 
It should also be noted that though I always insert links via `[[` to search and select the file I require, the location shown in the aforementioned tooltip is not the actual location of the file I chose, but always seems to default to current active folder in the workspaces panel followed by the ID of the file I chose, though that really doesn't matter since the link is unusable, anyway.

I reverted back to 2.3.0 and everything works as expected.

Thanks!

### Reproducing

Using version 3.0.1, create a markdown link to create titled internal links.
Video demonstration and Zettelkasten settings below.

https://github.com/Zettlr/Zettlr/assets/13608108/472a9a7c-0091-44f1-96c8-ef747269c003

![Screenshot-092720231542-693x399](https://github.com/Zettlr/Zettlr/assets/13608108/7f68af1b-6e8f-4bcf-a0ef-6fb87ac04ad5)

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by NateAM** [comment]
This is also an issue on Ubuntu 22.04

**Comment by nathanlesage** [comment]
This is intended behavior. Enclosing internal links within Markdown links was never supported, it worked due to a bug. I will enable titles and pre-rendering of these links in another issue that is already open.
