### ISSUE TITLE
Clicking on graph nodes no longer opens the document

### ISSUE THREAD

**Issue by NateAM** [Zettlr/Zettlr#4701]
### Description

I have updated to version 3.0.1 and clicking on the nodes in graph view now no longer open the files when clicked. I have also observed issues with the linking as reported in https://github.com/Zettlr/Zettlr/issues/4700. The connections in graph view were not made until I changed the format to [[filename]] rather than (my text)([[filename]]) and restarted Zettlr.

### Reproducing

Updated to version 3.0.1 from version 2.3.0 and observed issue

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

**Comment by pseandersson** [comment]
Relates to https://github.com/Zettlr/Zettlr/pull/4669
