### ISSUE TITLE
Table with multiline cells not handled correctly

### ISSUE THREAD

**Issue by BAKFR** [Zettlr/Zettlr#4705]
### Description

A table with multiline cells will derail the whole document display.

The table and all following text are "hidden" in the editor. However, the fold arrow on the side are present where they should be.

I'm not sure what format of table is supported by Zettlr. Anyway, it think it shouldn't block the display of the whole document.

### Reproducing

Document markdown:
```md
# server.domain.im

### Network

4 ports Ethernet:

| Nom        | Adresse MAC         |
|------------|---------------------|
| `enp3s0f0` | `68:b5:99:78:68:ac` |
|            | `68:b5:99:78:68:ae` |
|            | `68:b5:99:78:68:b0` |
|            | `68:b5:99:78:68:b2` |
This sentence is not displayed.

# Title

This is also ignored.


```

Result:

![Screenshot of Zettlr](https://nextcloud.ebak.fr/s/Hm64Sab9HnEiSxJ/download/bug-report-zettlr-2023.09.29.png)

### Zettlr Version

Stable (most recent version)

### Specify version

v3.0.1

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Gentoo

**Comment by chagmed** [comment]
Add a blank line between the end of the table and `This sentence is not displayed`

**Comment by nathanlesage** [comment]
Adding to what @chagmed has mentioned, tables must be padded on the top and bottom with blank lines. Then your code snippet works flawlessly.
