### ISSUE TITLE
[macOS] Zettlr triggers macOS native popup recommending XCode CLI tools installation

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#4709]
### Description

Got a bug via email, quickly pasting it in here:

> Start up Zettlr 3.0.0 or 3.0.1 on MacOS Ventura or Monterey, and the pop-up window with the question ["Would you like to install the XCode Command line tools?"] appears. It also happens when you close Zettlr via the Dock (right-click, stop) and restart Zettlr. The pop-up is not displayed when Zettlr is already running and I click on the dock icon.

### Reproducing

I am very confident this is simply if you don't have the Command line tools installed and furthermore no git installed (e.g. via Homebrew).

Apparently, on macOS, `git` points to a script that will show this popup as soon as anything attempts to access this command, which is what Zettlr does to determine git support.

I see two potential avenues:

1. Make git integration optional, off by default. Since Zettlr cannot do much besides detecting git support yet, I suppose it doesn't do harm
2. Add a special flag for macOS that, instead of simply checking whether `git` exists, sees if `which git` may output a spurious path that suggests the CLI tools will trigger said popup. This would require a normal Mac. I will ask the user for feedback for that.

### Zettlr Version

Stable (most recent version)

### Specify version

v3.0.0 and above

### Installation Method

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura/Monterey

**Comment by nathanlesage** [comment]
The user just got back, apparently `which git` outputs `/usr/bin/git`, a.k.a. where the `git` command also resides when you do in fact install the command line tools.

In other words, Apple apparently adds a symlink to that place, leaving us basically no other choice than to make git integration optional.

Oh, how I don't like that …

**Comment by nathanlesage** [comment]
Okay, for now I'll be issuing an FAQ entry because I can't just completely remove `git` integration for everyone because macOS can't simply say that git isn't installed.

![image](https://github.com/Zettlr/Zettlr/assets/17251683/1869b45b-82cf-4e8e-b97d-7f4cde48f1c8)

**Comment by obitwrite** [comment]
For anyone landing on this issue from Google or another search engine. The FAQ entry is here: https://docs.zettlr.com/en/reference/faq/#macos-asks-me-whether-i-want-to-install-xcode-commandline-tools-when-i-start-zettlr
