### ISSUE TITLE
[Mac OS] : Unable to export since Sonoma

### ISSUE THREAD

**Issue by pausanias123** [Zettlr/Zettlr#4712]
### Description

Hello, 

Since I updated my operating system (Sonoma, apple), I get an error message when I try to export a document (pdf, doc, etc.) 

pandoc: invalid argument (cannot encode character '\768')

I think it has something to do with French accents. 

I've tried reinstalling zettlr, pandoc, mactex, clearing the cache... Nothing works. 

Can you help me?

### Reproducing

every time I try exporting 

### Zettlr Version

Stable (most recent version)

### Specify version

3,0,1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Sonoma 14,0

**Comment by tobiasmuecksch** [comment]
Hi @pausanias123 . I'm experience a very similar issue. How have you been able to fix it?

**Comment by pausanias123** [comment]
Hello @tobiasmuecksch 

Sorry for answering late. If I remember well, I fixed this error by changing the filename, replacing an "é" by a "e" without accent. I hope it will help !
