### ISSUE TITLE
Tab character is still inserted (in place of spaces) when we press "tab" key, in indented unordered list and sublist.

### ISSUE THREAD

**Issue by abhishekbarua** [Zettlr/Zettlr#4717]
### Description

- abc
    - efg

In preference, it has been configured to replace "tab" with "spaces".

Ideally, infront of "- efg", there should be only spaces. If we open the file in some other editor, we can see that Zettlr has inserted tab character before "-efg".

### Reproducing

- abc
    - efg

In preference, it has been configured to replace "tab" with "spaces".

Ideally, infront of "- efg", there should be only spaces. If we open the file in some other editor, we can see that Zettlr has inserted tab character before "-efg".

### Zettlr Version

Stable (most recent version)

### Installation Method

AUR (Arch Repository)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Arch

**Comment by nathanlesage** [comment]
I cannot reproduce this; when I enable the 'Use tabs' setting it will add tabs, if I disable it it will add spaces. Could you please elaborate on what your issue exactly is?

**Comment by abhishekbarua** [comment]
To reproduce the bug:
Make a unordered list. Indent a few items as sub-items.
Like this:
- abc
- efg
    - mnp
- xyz

The above has been typed in GitHub, so do not take it literally.
After saving the file and opening the file in another text editor, you will see that tab acharacter has been inserted. It was supposed to be replaced by spaces as per the settings.

**Comment by nathanlesage** [comment]
> After saving the file and opening the file in another text editor, you will see that tab acharacter has been inserted. It was supposed to be replaced by spaces as per the settings.

Could you maybe please activate the setting to use "tabs", then quit Zettlr and restart it, then disable the setting again, quit Zettlr again and restart it, and then see if this still happens? If it does, please follow the troubleshooting guide in the docs to back up your configuration and remove it entirely, then start Zettlr and see if the issue still happens.
