### ISSUE TITLE
Rendering of bold text doesn't work if formatted string starts with a space

### ISSUE THREAD

**Issue by jelkejelke** [Zettlr/Zettlr#4718]
### Description

When a string/sentence starts with a space and is formatted bold (put between double asterisks) it does not render. 
Relatedly, the formatting inside the blinking/highlighted cursor is off, and the baseline seems to jump up a few pixels.

https://github.com/Zettlr/Zettlr/assets/61508639/ea12314c-732f-4720-ba5d-10ed427577cb

### Reproducing

See attached video. 
I'm using the Frankfurt theme, but experience the same issue with other themes.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS 13.3.1 (a)

**Comment by jgsw** [comment]
I don't think this is a bug in Zettlr: Pandoc Markdown bold syntax requires that there is no space between the opening asterisks and the text to be shown in bold. So Zettlr is correctly showing what the text will look like when exported. 

(You can test this out on Pandoc's site here: https://pandoc.org/try/?params=%7B%22text%22%3A%22**+Hello**+world%21%22%2C%22to%22%3A%22html4%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3A%22pygments%22%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

**Comment by nathanlesage** [comment]
As @jgsw has correctly pointed out: Emphasis markers for both bold and italic must not be padded with spaces according to the Markdown spec. This is not perfectly ideal from a perspective while writing, as it can make text appear a bit flickering, but there are some ways around it. Given the time and energy it might take to find a solution that respects the Markdown standard AND appreciates this request, it is the best course of action to leave this as it is.
