### ISSUE TITLE
German Secondary Guillemets (›…‹) missing from MagicQuotes Setting

### ISSUE THREAD

**Issue by macologe** [Zettlr/Zettlr#472]
## Description
It is just a minor mistake: In the preferences the German simple print quotes ›…‹ are wrong (›…›).

**Screenshots**
<img width="526" alt="Bildschirmfoto von Zettlr (15-01-20, 02-11-47)" src="https://user-images.githubusercontent.com/8957685/72396780-164f0980-373e-11ea-962b-751871952b95.png">

## Platform
 - OS and version: macOS Mojave, 10.14.6
 - Zettlr Version: 1.5.0
 - Screen Resolution: 2880 x 1800 (and others on external monitors)

## Additional information
Thank you for this great software! I love it!

**Comment by nathanlesage** [comment]
The ones you're showing are not wrong (there are in fact languages that use >…>), I simply forgot the >…<! Thanks for spotting!

**Comment by nathanlesage** [comment]
And done!
