### ISSUE TITLE
CPU usage of v3.x on macOS Catalina

### ISSUE THREAD

**Issue by grizzlydev-sarl** [Zettlr/Zettlr#4730]
### Description

I notice a massive increase in CPU usage since v3.x on macOS 10.15 Catalina, even when the app is idle. The renderer uses about 70% of a core, constantly.
v2.3.0 does not consume CPU at all when idle.

![Screenshot 2023-10-10 at 14 08 47](https://github.com/Zettlr/Zettlr/assets/47630949/86673898-9ee3-41d9-bac8-44487896e45d)
![Screenshot 2023-10-10 at 14 09 22](https://github.com/Zettlr/Zettlr/assets/47630949/ff9800ef-5303-4755-8514-73a4a261a8a6)

### Reproducing

Open Zettlr, and that's it.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0, 3.0.1, 3.0.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Catalina 10.15

### Additional Information

Debug info from "about" screen:
```
General Information
Zettlr Version: 3.0.2 (UUID: 6c213d9f-9b65-44e3-b46d-e423b8eca1e3)

System: darwin 10.15.7 (architecture: x64)

Build Dependencies
This build was compiled using
Node.js v18.15.0
Electron v25.9.0
Chrome v114.0.5735.289
v8 engine v11.4.183.29-electron.0
Zlib v1.2.13
OpenSSL v1.1.1

Helper programs
Pandoc: 3.1.6.2
Quarto: not available
Git SVN: 2.24.3
Renderer flags
/Applications/Zettlr.app/Contents/Frameworks/Zettlr Helper (Renderer).app/Contents/MacOS/Zettlr Helper (Renderer)
--type=renderer
--user-data-dir=/Users/incognito/Library/Application Support/Zettlr
--app-path=/Applications/Zettlr.app/Contents/Resources/app.asar
--no-sandbox
--no-zygote
--lang=en-GB
--num-raster-threads=3
--enable-zero-copy
--enable-gpu-memory-buffer-compositor-resources
--enable-main-frame-before-activation
--renderer-client-id=6
--time-ticks-at-unix-epoch=-1696170569145932
--launch-time-ticks=769823249401
--shared-files
--field-trial-handle=1718379636,r,217596312453136398,7982524615735477735,262144
--disable-features=SpareRendererForSitePerProcess
Environment Variables
USER: incognito
MallocNanoZone: 0
PATH: /Applications/Zettlr.app/Contents/Resources:/usr/local/opt/openssl@1.1/bin:/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/Users/incognito/.nvm/versions/node/v14.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/Android/sdk/platform-tools:/Applications/Android/sdk/tools:/usr/local/lib/node_modules/karma/bin:/opt/homebrew/bin
LOGNAME: incognito
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.CowTeK4Lmw/Listeners
HOME: /Users/incognito
SHELL: /bin/bash
__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
TMPDIR: /var/folders/sw/6bmb9nz95zl9b3lxv5s2ym_00000gn/T/
XPC_SERVICE_NAME: com.zettlr.app.14204
XPC_FLAGS: 0x0
ORIGINAL_XDG_CURRENT_DESKTOP: undefined
PANDOC_PATH: /Applications/Zettlr.app/Contents/Resources/pandoc
QUARTO_SUPPORT: 0
GIT_SUPPORT: 1
GIT_VERSION: 2.24.3
ZETTLR_IS_TRAY_SUPPORTED: 1
PANDOC_VERSION: 3.1.6.2
```

**Comment by nathanlesage** [comment]
I don't see anything like this happening here, leaving a lot of opportunities for what it may be. I would like to ask you first to follow the troubleshooting guide from the docs to see if that may fix it.

**Comment by grizzlydev-sarl** [comment]
That's indeed a false alarm: the CPU usage dropped to normal values after resetting the `Application Support/Zettlr` folder. Something must have gone corrupt there, one way or another. 
Sorry for the noise and not having RTFM first.
And thanks for the app and the quick support.
Cheers

**Comment by nathanlesage** [comment]
Wonderful, glad it worked out!
