### ISSUE TITLE
Very confusing closing dialog

### ISSUE THREAD

**Issue by sviatoplok** [Zettlr/Zettlr#4734]
### Description

Confusing choice when closing file:

![grafik](https://github.com/Zettlr/Zettlr/assets/46528983/6fa65436-180e-4616-b3ba-8ff845bb79a0)

What happens when I hit "Ja" ?

Verwerfen or speichern?

### Reproducing

Change a file and close it, read dialog.

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 10

**Comment by nathanlesage** [comment]
I remember that I've adapted the dialog recently. Let me quickly check if I also updated the German translation … whoops, nope. I just did that, this should make the dialog look less weird!
