### ISSUE TITLE
All quotes in HTML appear as curly quotes (US English)

### ISSUE THREAD

**Issue by senatorforlife** [Zettlr/Zettlr#4735]
### Description

(US English) Quotes in HTML code, whether typed or pasted into Zettlr, appear in the editor as "curly" quotes, i.e. typographical quotes. This is confusing and requires using an external code editor to verify that the code is valid HTML, and thus valid Markdown. For example, if I type:

``` html
<figure id="fig1">
    <figcaption>
        My friend says this is a "great" image.
    </figcaption>
</figure>
```
All of the quotes appear to be curly quotes, but their true status can't be determined. For example, I typed the text in this screenshot with Magic Quotes off, but they still appear as invalid typographical quotes:

![Screen Shot 2023-10-12 at 5 13 58 PM](https://github.com/Zettlr/Zettlr/assets/67700892/1e085b6f-15b9-426f-b412-09beb1e89986)

### Reproducing

Open a new document. Turn off Magic Quotes, then type something in HTML, e.g. `<figure id="fig1"></figure>`. The quotes appear to be typographical (i.e., curly quotes). Save the file, then open in a code editor. The quotes are in fact straight quotes. This is valid HTML, but its validity can't be verified within the Zettlr editor. 

Open a new document. Turn on Magic Quotes, then type something in HTML, e.g. `<figure id="fig1"></figure>`. The quotes appear to be typographical (i.e., curly quotes). Save the file, then open in a code editor. The quotes are in fact curly quotes. This is invalid HTML.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterey 12.7

### Additional Information

Ideally, quotes typed within HTML brackets < > would always be set as straight quotes (" '), whereas text between brackets > < would be set according to the Magic Quotes setting. Thus, with Magic Quotes on, we'd get: 
``` html
<figure id="fig1">
    <figcaption>
        My friend says this is a “great” image.
    </figcaption>
</figure>
```

**Comment by nathanlesage** [comment]
It is sometimes difficult to detect whether MagicQuotes are good to go or whether it should not tamper with the quotes. I managed to do that with the YAML frontmatter, so maybe I'll manage the same with HTML code.

**Comment by nathanlesage** [comment]
That was easier than expected. Note, however, that detecting HTML code can be a bit difficult within a Markdown context, as anything that is not clearly valid HTML code will not be parsed as such, re-enabling the MagicQuotes replacement.

Note, however, that anything with smart quotes that does not contain a space will form a valid attribute value. I.e., in the example 

```html
<a name=”test”>Test</a>
```

The value for the attribute "name" is `”test”`. Therefore, it can be hard to spot whether there are quotes.

My tip: first write the attribute value, then select it entirely, and then press `"` to enclose it in quotes. Other than that, there is not much I can do; as I said, HTML within Markdown can be tricky to detect.
