### ISSUE TITLE
exporting files became very slow, exporting projects impossible

### ISSUE THREAD

**Issue by pausanias123** [Zettlr/Zettlr#4736]
### Description

Good evening, 

I can no longer export projects, and exporting documents is slower than before. 
This has happened since I switched over 
- the image files I use
- and the bibliographic files (CSL and JSON) 
into two sub-folders of the project I'm working on. 

Every time I try to export the project, I do get a message indicating that the export has started, but It's never successful. After waiting several minutes, I get an error message from Mac OS explaining that the file doesn't exist. Or I get nothing at all.

Here are the messages in the journals : 

For 1 file, it works (slower than before)
[00:46:17]
[Exporter] Exporting 1 files to /var/folders/j8/t7rhpgxn36z6n800g_88kltc0000gn/T/
[00:46:26]
Successfully exported file to /var/folders/j8/t7rhpgxn36z6n800g_88kltc0000gn/T/1. genealogie.pdf

for the project, I get : 
[00:46:37]
[Project] Exporting redaction HDR as html (Profile: HTML.yaml).
[00:46:37]
[Project Export] Exporting 10 files to /Users/jules/Documents/Hdr/redaction HDR
[00:52:12]
[WATCHDOG] Ignore event: change:/Users/jules/Documents/Hdr/redaction HDR/.ztr-directory
[00:52:13]
[WATCHDOG] Ignore event: change:/Users/jules/Documents/Hdr/redaction HDR/.ztr-directory
[00:52:17]
[WATCHDOG] Emitting event: addDir:/Users/jules/Documents/Hdr/redaction HDR
[00:52:17]
[FSAL] Could not process add event for /Users/jules/Documents/Hdr/redaction HDR: Parent directory not found.

NB I got this one once too : [FSAL Directory] Path /Users/jules/Documents/Hdr/redaction HDR took 156.38133299999754ms to load.

### Reproducing

every time I try to export the project

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.0

### Additional Information

I hope I've described the problem correctly. Thank you for your help.

**Comment by pausanias123** [comment]
I notice another thing : 
[08:28:58]
[Application] Could not return descriptor for /Users/jules/Documents/Hdr/rédaction HDR: Neither file nor directory.
[08:28:58]
[R] [Main Window (9ea50516-4c28-4cb1-96b3-ae2f002477ff)] The descriptor for path /Users/jules/Documents/Hdr/rédaction HDR was empty! (index.js:2)

there's a problem because in the path given by the log, there's an accent (é). But this accent doesn't exist in the system file. 

I don't know how to solve this ... If you can help I'd be very grateful :)

**Comment by nathanlesage** [comment]
Hm … difficult to pin down what might be causing the issue. So I'd first like you to try out the following steps:

1. Try an export with the `HTML.yml` profile that your project export also uses. Your single file export was successful, but it was using one of the PDF profiles. If that fails, there may be a mistake in the HTML profile, so in that case you can "delete" the HTML profile (which will recreate the default that provably works).
2. If a single file export with said profile works, then it's not a cause of the profile. Then, try out transforming another directory (preferably with only a few files) into a project and see whether this works. If so, then it's also not a bug with the project feature.

What makes me suspicious is that there is no error message, which indicates that Pandoc possibly takes a long time to export, but that's just a suspicion with the amount of information there is.

**Comment by pausanias123** [comment]
Good morning,

Many thanks for your help.

The Html export worked fine.

I then tried transforming another directory as indicated, and that worked
too.

Then I try to move copies of my previous project in a new directory, and
transform it into a new projet, and everything works fine, thank you !

I wonder if the error came from having transformed the name of the folders
inside the project, once the project had been created.

In any case, thank you very much for your help. Have a nice day!

Le sam. 14 oct. 2023 à 22:03, Hendrik Erz ***@***.***> a
écrit :

**Comment by nathanlesage** [comment]
> I wonder if the error came from having transformed the name of the folders
inside the project, once the project had been created.

Mh, I don't know. But please feel free to monitor this, and should this happen more often, please comment here so that I can have a look. Glad it works now!
