### ISSUE TITLE
[My text]([[<my-doc-id>]])

### ISSUE THREAD

**Issue by joep1977** [Zettlr/Zettlr#4739]
### Description

In the new version [My text]([[<my-doc-id>]]) doesn't seem to work anymore.

### Reproducing

When I format an internal link like below and when I click the link I get an error (see below). Translation of error: Cannot find file...Check if you have entered the name correctly...etc. 

[My text]([[<my-doc-id>]])

![image](https://github.com/Zettlr/Zettlr/assets/96820649/1229cb1c-03c3-44a4-b573-505e4faaea81)

When I format the link like this 

[[<my-doc-id>]]

the linking does work.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.2

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
It's already gone from the documentation: This was never intended to work, I'll provide proper workarounds soon-ish.

**Comment by joep1977** [comment]
Okay, but it is still here in the documentation (https://docs.zettlr.com/en/academic/zkn-method/).

What kind of workaround are you planning? The beauty of how it worked, is that the link does not necessarily has to equal the file name, e.g.: [Napoleon]([[The history of Napoleon]. 

I use titles for my notes, so the title of my note is "The History of Napoleon" but the file name is something like 20231018115253.md, When I now want to link internally the text says: Jospehine was the love of [[20231018115253]] which is not only not pretty but also not functional.

**Comment by joep1977** [comment]
I cannot re-open the issue but I would be very much appreciated if you could have a quick look at it. Thank you!

**Comment by nathanlesage** [comment]
> Okay, but it is still here in the documentation

Would you mind removing it from the documentation? That would really help me out.

> What kind of workaround are you planning?

Basically implement what Pandoc has implemented: Allowing a title for those links, i.e. `[[20231018115253|The History of Napoleon]]` or the other way around.
