### ISSUE TITLE
Insert footnote keyboard shortcut not working

### ISSUE THREAD

**Issue by savoyad** [Zettlr/Zettlr#4747]
### Description

The insert footnote keyboard shortcut (ctrl-alt-f) does nothing.

Expected behaviour:  press ctrl-alt-f, zettlr inserts footnote notation, i.e. same behaviour as if I had pressed the footnote button at the top.

Actual behaviour: no response. The only way to insert a footnote is to press insert footnote button with mouse (or type manually)

### Reproducing

with cursor in text editor press ctrl-alt-f
nothing happens

### Zettlr Version

Stable (most recent version)

### Specify version

30.02

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by savoyad** [comment]
Update - the MacOS shortcut (R, not F) works in windows.
So this is a tiny bug. Admittedly easy to workaround - but only if you know.

**Comment by nathanlesage** [comment]
I forgot to include that; it's fixed now and should work as expected on the next update.
