### ISSUE TITLE
[ENHANCEMENT] Better NSIS Installer Images

### ISSUE THREAD

**Issue by keunes** [Zettlr/Zettlr#475]
## Description
When installing (on Windows), the last screen contains an image with an unknown logo (or is it a logo? maybe it's just a creative square with blobs in it). I'd like to suggest (if possible) to replace this installer image with something Zettlr-specific, to make things feel more personal.

## Proposed Changes
Something basic (Zettlr colour with notes/writing-related visuals in (transparent) white) would be great.

![zettlr installer](https://user-images.githubusercontent.com/11229646/72416793-c2611680-3777-11ea-91bd-96d9e77b7e36.png)

**Comment by nathanlesage** [comment]
What you see is the default NSIS imagery, which indeed can be replaced!

However, as I'm developing on macOS and therefore can't really test on Windows, I haven't gotten into creating the necessary images. [See the values here for images that can be created](https://www.electron.build/configuration/nsis).

If you feel creative, please feel free to suggest some concepts! (Or, for that matter, anyone else reading this is also invited).

The [DMG background image](https://github.com/Zettlr/Zettlr/blob/master/resources/icons/dmg/dmg_back%402x.png) (macOS only) is obviously also open for discussion, in case anybody has something better to offer!

**Comment by keunes** [comment]
It seems it is the `installerSidebar` that should be defined:
> String - assisted installer only. MUI_WELCOMEFINISHPAGE_BITMAP, relative to the [build resources](https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources) or to the project directory. Defaults to build/installerSidebar.bmp or ${NSISDIR}\\Contrib\\Graphics\\Wizard\\nsis3-metro.bmp. Image size 164 × 314 pixels.

I can provide an image and test on Windows - anything in between (like building (?)) I can't as I don't have any development experience :) Would the Zettlr logo be available in svg format somewhere? Or for example the feather that's on the empty state screen?

**Comment by nathanlesage** [comment]
I wouldn't use the feather, it was only meant as a drop-in. The logo is PNG-only, the big versions are here: https://github.com/Zettlr/Zettlr/tree/master/resources/icons/png

**Comment by keunes** [comment]
Thank you bot for reminding me. As I have no coding experience, I hope you can implement either of the two attached images @nathanlesage. [Zettlr installer image_.zip](https://github.com/Zettlr/Zettlr/files/4606716/Zettlr.installer.image_.zip)

**Comment by nathanlesage** [comment]
Thanks! I'll give it a shot later the day! :)

**Comment by nathanlesage** [comment]
Yes, it was some time, I'm sorry, but I could make use of the image and adapted them a little bit. Feel free to test out building a Windows installer on the current develop-branch for you locally and see if it looks good! Feel free to also add screenshots here :)

**Comment by keunes** [comment]
Don't think I'll invest in learning how to make a build, but I'll try it once the next version/installer is out, if I remember :)

**Comment by nathanlesage** [comment]
Yeah, as I know the crowd, there'll be like 10 issues notifying us of the bug, if there is one :D
