### ISSUE TITLE
Displays both the file name and the title in the file manager

### ISSUE THREAD

**Issue by ZuoAoyu** [Zettlr/Zettlr#4769]
### Description

Now I use the ID as the file name, and use the ID and ‘real title’ as the title. For example, my filename looks like `cf.ddd.22.0329.2235.md`, and my title looks like `cf.ddd.22.0329.2235 note_real_title`. In a file manager, files are displayed this way `cf.ddd.22.0329.2235 note_real_title`.

It looks nice, but it was done by hand. Once I wanted to change the filename, it was a disaster to make the filename match the title one by one.

So I have this need: Displays both the file name and the title in the file manager. When I re-edit the file name, the modified results can be reflected in the display content.

### Proposed Changes

For example, my filename looks like `cf.ddd.22.0329.2235.md`, and my title looks like `note_real_title`. Finally appears in the file manager as `cf.ddd.22.0329.2235 note_real_title`. 

This makes it easy to keep the file names in sync with what is displayed in the file manager

### Caveats

no.

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

Windows 11

**Comment by ZuoAoyu** [comment]
I have used the Obsidian to achieve the desired effect. Plugin name: Front Matter Title.

So goodbye!

**Comment by nathanlesage** [comment]
I am relatively unsure as to what exactly you want to achieve … but it is good to hear that you have found a way to do so.
