### ISSUE TITLE
[Enhancement] Options to adjust default LaTeX and Mermaid apperances

### ISSUE THREAD

**Issue by jrcharney** [Zettlr/Zettlr#477]
I was thinking about how LaTeX appears. While the font is appropriate for LaTeX processing, I was wondering what would it be like if we had an option to adjust the font size for LaTeX.  The font appearance does apply to inline LaTeX (sort of), but when LaTeX is processed, it's processed like an image. Inline symbols are scaled based on the surrounding text (which is why if you use something like sigma notation, the arguments that appear on the top and bottom in a LaTeX block appear to the right of the sigma symbol in inline LaTeX.

The image processing is how MathJax (which I assume that is what we are using for a LaTeX processor) scales font using typesetting, but I think this feature can be adjusted.

The LaTeX font as it is is fine, and is at a proper size, but if a user wanted to adjust the font to their preference (espeically for accessibility purposes), I think it would be a good thing to have.

On a side note, I know Mermaid is not part of Zettlr yet, but I'm including it in this enhancement feature idea since the default color scheme it uses (which UML Class Diagrams are using this kinda ugly cornflower blue and purple color scheme), but when you get around to adding it, it would be good if a black-and-white theme was used, or (for dark themes) a white-and-gray color scheme.

Mermaid has options to adjust the appearance of charts, but these adjustments are either part of a separate JSON code block or could be put into a separate document. (See their [Live Editor](https://mermaid-js.github.io/mermaid-live-editor/) for example.) So styling should be configurable.

There is no rush to add these features. So apply them at your convenience. This is just some stuff to consider for the future.

**Comment by nathanlesage** [comment]
> if we had an option to adjust the font size for LaTeX

Yes, the [PDF Preferences window](https://docs.zettlr.com/en/reference/settings/#pdf-preferences).

> Inline symbols are scaled based on the surrounding text

I'm not sure I fully understand what you mean …?

> MathJax (which I assume that is what we are using for a LaTeX processor)

I think, yes. I never delved into that. I only implemented Math previews using [KaTeX](https://katex.org/), but never really bothered with how the LaTeX-compiler does this. For me, it works so far.

> I think this feature can be adjusted

… do the PDF Preferences do what you imagine, or do you mean deeper settings? In that case, would [Custom TeX Templates](https://docs.zettlr.com/en/academic/custom-templates/) do the job?

> but when you get around to adding it, it would be good if a black-and-white theme was used, or (for dark themes) a white-and-gray color scheme

This would be great to have as a comment in the original Mermaid issue, as it would be part of the initial implementation ;)

**Comment by jrcharney** [comment]
OK. I keep forgetting Zettlr uses KaTeX instead of MathJax. (Which is why I switched to Typora.)

I just wanted to put that idea on the table for getting preferences set up for Mermaid whenever that feature comes out.

**Comment by nathanlesage** [comment]
Don't forget: Only Zettlr internally uses KaTeX to render equations. When it comes to PDF-rendering, it'll use whatever the LaTeX installation has, which in most cases is MathJax. So the final PDF-output from Zettlr will be rendered using MathJax in most cases. Besides, the differences are marginal.

**Comment by stites** [comment]
Doesn't latex use pandoc under the hood? If so, that means that you can include their latex variables in a specific document's YAML-frontmatter and change your layout on a case-by-case basis. See [Pandoc User Guide](https://pandoc.org/MANUAL.html#variables-for-latex).

**Comment by alerque** [comment]
@stites Do you mean "Doesn't Pandoc use LaTeX under the hood?" If so yes, that is _one_ of the possible backends for Pandoc to generate PDFs. It is not the only one.

**Comment by stites** [comment]
ah, sorry, I meant "doesn't Zettlr use pandoc under the hood"?
