### ISSUE TITLE
Autosave triggers change of focus in document

### ISSUE THREAD

**Issue by derWalter** [Zettlr/Zettlr#4777]
### Description

when autosave occurs while working on a longer document the focus/point jumps to the beginning of the document, or to a random location somewhere in the document. whic is ofc highly distracting.

most of the time I also get this error message on save: 
![image](https://github.com/Zettlr/Zettlr/assets/158642/e5a49ee0-dbb3-4fbf-acf2-fff417edd943)
the frequency of the error appearing can be lowered by changing the autosave option to "after a short delay" instead of instantly.

this bug was introduced with the upgrade from 3.0.0 to version 3.0.2

### Reproducing

work on longer document

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2 UUID: a7324926-355a-4c89-a25a-f95cf7523276

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 Pro, Version: 22H2, Build: 22621.2506, Windows Feature Experience Pack 1000.22662.1000.0

### Additional Information

i use nextcloud sync client with "virtual file system" (VFS) feature enabled

**Comment by kyaso** [comment]
This is a known issue that will be fixed with next release v3.0.3, see https://github.com/Zettlr/Zettlr/pull/4760. In the meantime, you could try the latest nightly (https://nightly.zettlr.com/) release which contains the fix.
