### ISSUE TITLE
new file does not work

### ISSUE THREAD

**Issue by RMHogervorst** [Zettlr/Zettlr#4785]
### Description

I cannot create new files in zettlr. When I press command+n or move to File > new file > markdown nothing happens. 
I do see a mac spinner cursor (busy I think?) and then the program is just stuck. 
According to activity Monitor Zettlr is pinned at 99% cpu and the 4 helpers use 0% cpu.

### Reproducing

current version of zettlr on Mac OS Monterey
on a MacBook Pro (Retina, 13-inch, Early 2015) (Intel chip)

### Zettlr Version

Stable (most recent version)

### Specify version

V3.0.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Montery

### Additional Information

I don't understand what changed, because it suddenly stopped working this week. There were no updates.

**Comment by nathanlesage** [comment]
Does this problem go away if you click on any directory in the file tree before hitting Cmd+N?

**Comment by RMHogervorst** [comment]
Yes, that actually helps! At first I thought not, but clicking on the workspace folder allowed me to create a new file, and now I can create new files from other places too. What an interesting bug!

**Comment by nathanlesage** [comment]
Perfect, thanks for checking this out; now I know where the bug is located at. Until I fix it, always make sure to select some directory, then it should work!

**Comment by RMHogervorst** [comment]
thank you for responding this fast!

**Comment by phourglass** [comment]
Hello,

Same problem on windows 10.

I got onto this issue from that one:  https://github.com/Zettlr/Zettlr/issues/2480
It is unclear from the thread if creating a file in memory was maintained or not (cf. last message before merging).

Not to reopen the debate but I use that all the time: I start taking notes and realize at the end of the meeting I did not write anything except for the first 5 minutes. I just don't save. The software is stable enough not to worry and if I start writing a lot then I save and also decide at that point where it should be stored (I don't always know before). There is a also comment saying that a file is nothing outside a collection and I disagree. I index my .md separately (voidtools everything with content indexing).

Anyhow, thanks a lot for Zettlr!
Philippe

**Comment by nathanlesage** [comment]
> It is unclear from the thread if creating a file in memory was maintained or not 

There are no more "in memory" files in v3 – that was too confusing for most people.

**Comment by obitwrite** [comment]
Just a +1 that I also encountered this issue. For some reason it seemed to have started out of the blue. The workaround (create and select a workspace / folder) fixed it for me.

**Comment by awanger** [comment]
I'm having this issue as well as of today.
