### ISSUE TITLE
Add "Copy ID" context menu for files without ID, defaulting to file name

### ISSUE THREAD

**Issue by khakhalin** [Zettlr/Zettlr#479]
I already mentioned this on Twitter, but for the record, should probably post it here as well :) As of version 1.5.0, if you right-click on files in the file list, for some files you get an option "Copy ID", above the "Quicklook" item. But if file's name doesn't match the id regex, this option doesn't appear.

I propose that instead, if the filename doesn't match the regex, we'd get "Copy filename" option in the exact same place. Slightly different wording, but essentially same functionality. Or maybe even us same wording; it doesn't matter.

The rationale: file names totally work in `[[ ]]` links, and the "Copy id" item is probably mostly used for cross-linking cards. Having a contextual "Copy filename" would help to use one process both for "summary" (named) files, and for "classic" Zettelkasten cards. Tiny feature, but it would streamline it a bit.

**Comment by nathanlesage** [comment]
Ah, yeah, thanks for reminding me of this! I can add this, too :)

As it's just a super-simple addition, it'll also make it into 1.6, for which the beta phase hopefully starts end of January :)

**Comment by nathanlesage** [comment]
You know what? It's Sunday and I'm in an extremely good mood, so here you go :)
