### ISSUE TITLE
Not saving changes in imported files

### ISSUE THREAD

**Issue by Wietor-bb** [Zettlr/Zettlr#4799]
### Description

When I import a file, e.g. docx (via File/Import), and then change something in the resulting md file, these changes do not save! 

I have lost several hours of work this way....

I have found a "temporary workaround" – copy (via Copy/Paste ) the contents of .md file created after import into a new, empty .md file.  Only then can changes be made, which will save themselves. 

Copying the converted file (e.g. with the Duplicate function) does not help. A new file must be created. 

This is very strange and very inconvenient. 

### Reproducing

Import docx, make some changes, save, close file.
Open again...

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by RaidOpe** [comment]
3.03 win11 here.
I'm assuming that the file being imported is called by a different program, so what appears to be a save occurs but is not actually saved. My situation is similar to yours. When I am editing a file, I use gitbash of windows to commit. If gitbash is not closed, any restart of the software or opening from the source location will revert to the state before saving. I have tested it twice. I have to completely close gitbash and zettlr, wait 5-10 seconds, and then open the file from the source location to run normally.

**Comment by Wietor-bb** [comment]
This error was present in 3.0.2 / Win11. 
In the current version 3.0.3 / Win11 I notice the same problem.
Regarding what RapiOnde wrote: the application where the source file comes from is closed. Maybe there is a problem with pandoc here? 
I did such a test: imported a docx file. I turned off Zettlr. I waited 30 seconds. I started up Zettlr. I changed something in the file. The changes did not save again....

It was certainly fine in versions 2.... or maybe even in the first betas of version 3, I don't remember.

**Comment by RaidOpe** [comment]
Do you have '*'  top buffer?
When a save bug occurs, the most obvious feature is that the save symbol '*' will disappear. No matter what is entered, as long as you switch from the workspace or open the software again, the data will be traced back. I'm assuming some behavior ends the file memory call and the file will be fine. Just like word import, the data will not be saved until it is put into another memory.




> This error was present in 3.0.2 / Win11. In the current version 3.0.3 / Win11 I notice the same problem. Regarding what RapiOnde wrote: the application where the source file comes from is closed. Maybe there is a problem with pandoc here? I did such a test: imported a docx file. I turned off Zettlr. I waited 30 seconds. I started up Zettlr. I changed something in the file. The changes did not save again....
> 
> It was certainly fine in versions 2.... or maybe even in the first betas of version 3, I don't remember.

**Comment by nathanlesage** [comment]
Please refer to the main issue: #4959
