### ISSUE TITLE
Footnotes are misinterpreted when in close proximity to links

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#48]
## Description
Footnotes are not displayed properly when there is a `[…](...)` link in the same sentence.

## Reproducing
Paste the following real-world example textually into a new Zettlr document:
```
This is a form of *bricolage*, to use the term Jacques Derrida adopted from Claude Lévi-Strauss.[^1] Indeed, it aims to make the *bricolage* process explicit, a form of [autopoietic](https://en.wikipedia.org/wiki/Autopoiesis) writing.

[^1]: Derrida, Jacques, “Structure, Sign and Play in the Discourse of the Human Sciences”, *Writing and Difference*, trans. by Alan Bass (London: Routledge, 2005 \[1967\]), pp. 351-70 (360ff).
```
In Zettlr, visually it looks like this:
![image](https://user-images.githubusercontent.com/4304337/47493501-554a2400-d847-11e8-949d-7d80bae8836e.png)

## Expected behaviour
Show the footnote correctly, and not assume it is part of the hyperlink.

**Screenshots**
See above.

## Platform
 - OS:  Windows 10
 - OS Version: 1803
 - Zettlr Version: 0.20.0

**Comment by nathanlesage** [comment]
Thanks for the notice, attached patch should fix this!
