### ISSUE TITLE
Global search strips leading and ending spaces even in exact search mode

### ISSUE THREAD

**Issue by khakhalin** [Zettlr/Zettlr#480]
As it turns out, there's no way right now to look for exact instances of a word without finding all compound words that contain your search string as a subword. In most cases it's a feature (like the trooper / stormtrooper example from Zettlr documentation), but for exact search with trailing or leading spaces it becomes a bug. Typically, to find an isolated instance of a word, one would search for things like `"storm "` (note a trailing space), or `" trooper"` (note a leading space inside the quotation marks). Yet now, a search for `" trooper"` still finds a "strormtrooper" word, despite the fact that it doesn't have a space before "trooper". (see the screenshot)

![image](https://user-images.githubusercontent.com/17154125/72824404-318cae00-3c43-11ea-94e9-33415f0dc6da.png)

To reproduce this behavior, find a sequence of letters that is rarely used in your Zettelkasten. Create a card that contains this sequence as a substring, and another card that contains it as a stand-alone word. Try to come up with a search string that finds the 2nd card, but not the first. You'll fail.

I suppose there's a trim() function somewhere that removes leading and trailing spaces from search terms. This function should not be invoked if `"exact search"` is used.

## Platform
Zettlr 1.5.0, windows

**Comment by nathanlesage** [comment]
Piece of cake 😎🤙🏼

**Comment by nathanlesage** [comment]
btw I just realised how INCREDIBLE precise your analysis was:

> I suppose there's a trim() function somewhere that removes leading and trailing spaces from search terms. This function should not be invoked if "exact search" is used.

100 % nailed it

**Comment by khakhalin** [comment]
I'm happy =) Thanks!
