### ISSUE TITLE
[3.0.0] Memory leak during hibernation

### ISSUE THREAD

**Issue by Zaharatot** [Zettlr/Zettlr#4800]
### Description

The problem has manifested itself over the past month. I always send the computer to hibernation, instead of shutting down, and I began to notice a strange behavior of the editor - he began to slow down when typing. Today I found the reason - the task manager displayed memory consumption of 3.5 Gb. After restarting the application, the consumption became around 200 Mb. I didn't think to take a screenshot of the status, and the next time the problem will appear only in a few days.

### Reproducing

1. Launch the application.
2. Open two relatively small files (I have 2 tabs open, one with a 208 Kb file, the second with 1 Kb).
3. Send the computer to hibernation mode and turn it on again (repeat several times).
4. After several iterations (it takes about 5-7 days for me to do this), the memory consumption of the application will increase many times.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
Oh, how gracious of you to only suspect one memory leak – the entire main process code is probably leaking out of many holes 🙈 I am relatively certain, however, that those memory problems exclusively stem from me not properly GC'ing some of the arrays, which is not a security problem and merely a nuisance.

I do suggest restarting Zettlr at least every 24 hours in any case but yes, we can take a general look at this.

**Comment by Zaharatot** [comment]
It seems that I made a big mistake by pointing out the main cause of the problem is hibernation. Since then, I have put the computer into hibernation several times, but there was no memory leak. However, I recently restarted the application, and this is what I saw in the task manager. 
Also, there was an even stranger app behavior today. When I wrote the text, after each letter, all the lines jerked back and forth by a couple of pixels.
![Zettlr](https://github.com/Zettlr/Zettlr/assets/14033497/4d8e5893-a0ca-4ff4-bc32-688442721425)

**Comment by nathanlesage** [comment]
> When I wrote the text, after each letter, all the lines jerked back and forth by a couple of pixels.

That is likely the "jumping lines" bug that is caused when you use tabs for indentation instead of spaces, so unrelated to this one.

**Comment by nathanlesage** [comment]
Does this issue still occur?

**Comment by Zaharatot** [comment]
Unfortunately, I have not updated the version yet - I was still on v3.0.0. Now, after your message, I have updated to the latest (3.2.2), and I will write about the results within a couple of days.

**Comment by Zaharatot** [comment]
Addition. The problem of "jumping lines" disappeared after the update. It was 100% likely to occur when using numbered lists (I have found out for sure since then), and now it is definitely not there. Regarding the problems with memory leaks, I will unsubscribe a little later.

**Comment by Zaharatot** [comment]
Good day! I have been monitoring memory consumption for about two days, and I can confidently say that the problem has been solved - memory consumption remains stable and does not start to grow dramatically.
