### ISSUE TITLE
In deb packages, recommends parameter is not correct

### ISSUE THREAD

**Issue by pagiraud** [Zettlr/Zettlr#4804]
Please consider correcting the code below:

https://github.com/Zettlr/Zettlr/blob/efd4fe9c4ff6b722d049be9bf08fd551cf03888e/forge.config.js#L342

There is no `tex-live` package on Debian or Debian derivative distributions, but there is a `texlive` package. What’s more, one can choose `texlive-base` or `texlive-full` packages, that will also work well with Zettlr.

So, I would recommand to correct the line as follows:

`recommends: [ 'quarto', 'pandoc', 'texlive | texlive-base | texlive-full' ],`

Although the pipe is the correct character to indicate an alternative in a DEB package description file, I’m not sure the above syntax will work in your .js file.

Thanks for this great piece of software.

**Comment by nathanlesage** [comment]
Good find – I just ran a test build, worked without errors, so possibly that's all good this way. Please try out the new nightly that will be released sometime during Monday, and which you can get here, to check if the recommendations are now computed properly in the Debian installer: https://nightly.zettlr.com

**Comment by nathanlesage** [comment]
Amazing, thanks a ton!
