### ISSUE TITLE
"Double" inserting  link to  other zettlr 

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#481]
After using [[]] (double bracket)  and autocomplete to insert a link to existing XYZ zettelkasten the effect is 
```
[[201901300512 XYZ]] 201901300512  XYZ
````
This is a bug or feature? Should the effect be rather
```
[[201901300512 XYZ]]
```
Latest Zettlr version on Ubuntu 18.04.

**Comment by nathanlesage** [comment]
It's coming in 1.6; the beta should start soon! See #391 for more information
