### ISSUE TITLE
Error exporting PDF

### ISSUE THREAD

**Issue by fredygamez** [Zettlr/Zettlr#4816]
### Description

An error occurred on export: Pandoc exited with code 47

xelatex not found. Please select a different --pdf-engine or install xelatex

### Reproducing

- MD document
- File > Export
- Select XeLatexPDF
- Clic on Export
- Error is shown: "An error occurred on export: Pandoc exited with code 47

xelatex not found. Please select a different --pdf-engine or install xelatex"

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Xubuntu 20.04

**Comment by nathanlesage** [comment]
As the error says, you'll need to install XeLaTeX. The corresponding instructions are in the documentation: https://docs.zettlr.com/en/getting-started/installing-latex/
