### ISSUE TITLE
Zettlr 3.0.2: regular expressions do not seem to work anymore

### ISSUE THREAD

**Issue by Alexandros81** [Zettlr/Zettlr#4827]
### Description

The following regular expressions do not seem to work, not even with the checked regexp box. E.g.: /{.+?}/, or /"(.+?)"/, or /\_.+?\_/

And, by the way, menu does not work, I have to use the key combination (ctrl+F) in order to make the searching boxes to appear...

### Reproducing

Use ctrl+F

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Last ArcoLinux

### Additional Information

I use Zettlr Appimage file

**Comment by nathanlesage** [comment]
Just tried it out, works fine, but you need to (a) use `(` and `)` instead of `{` and `}`, and also the new search box doesn't need the `//` anymore, so simply type without those.

Also, Cmd+F works fine here, cannot say something about Ctrl+F, though.
