### ISSUE TITLE
3.0.3 Windows10: App theme stuck in broken combination, cannot be changed from Preference.

### ISSUE THREAD

**Issue by hann482** [Zettlr/Zettlr#4834]
### Description

App theme in newly installed 3.0.3 seems to be stuck in strange Berlin-Frankfurt hybrid, with blue UI elements and in-editor hyperlinks. Fonts seems to be correct ones for Berlin, and in-editor Markdown syntax highlights are in green. 
~~Theme selection in Preference have no effect.~~ I double-checked, and fonts settings are applied correctly. Only the colors are stuck.
<img width="960" alt="スクリーンショット 2023-12-05 101927" src="https://github.com/Zettlr/Zettlr/assets/138005406/453cb22f-aaa1-4b60-b1cd-2ae45063b847">

My first encounter with the issue was after I updated 3.0.2 to 3.0.3 using 3.0.3 installer, but this issue is reproducible even after I removed \AppData\Roaming\Zettlr.

### Reproducing

Install Zettlr 3.0.3 via released installer. Clearing \AppData\Roaming\Zettlr, or choosing between Local/Admin installation seems to not matter.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by hann482** [comment]
Saw this point being discussed in discord., going to close it.

**Comment by siriux** [comment]
@hann482 did you find a solution to this or you know where can we track the discussion/progress of this problem?

Thanks

**Comment by nathanlesage** [comment]
@siriux The simplest way is to:

0. Close the app
1. Go to the app data directory (see the documentation)
2. Rename `custom.css` to something else, e.g., `custom.backup.css`
3. Start the app again; now it should work
4. Copy the CSS rules over one by one until it doesn't work anymore, then you know what CSS rules broke the app
5. Remove those rules and copy over everything else back into the `custom.css`

**Comment by siriux** [comment]
thanks @nathanlesage but it didn't work. Even removing the whole data directory doesn't fix the problem.

**Comment by nathanlesage** [comment]
Okay perfect, thank you for having a look. I'll have to investigate the issue, so it may take a while, feel free to do research yourself as well.

Can you open any other directories, just not the tutorial one, or can't you work at all with the app?

**Comment by siriux** [comment]
Yes, the app seems fully functional, just the color of the toolbar, menus, ... are blue instead of following the theme (Berlin in my case). Selecting the Frankfurt theme at least makes everything consistent.

**Comment by nathanlesage** [comment]
Ah yes, Zettlr uses the windows accent color there, you can override this with ... I don't know exactly the variable, but you can override it easily.

**Comment by siriux** [comment]
I've found the problem. This option has been removed on 3.0.3, as described in the changelog.

> - Removed the accent color setting: now the accent color will always be the
>   system accent color on macOS and Windows, and Zettlr's brand green on Linux;
>   themes do not provide an accent color anymore
