### ISSUE TITLE
Pandoc not found on Windows 10

### ISSUE THREAD

**Issue by suntarliarzn** [Zettlr/Zettlr#4836]
### Description

I install the newest version of both Zettlr and Pandoc on my Windows 10. But I can not export the file to any other file types. It pops up the window says：“Pandoc has not been found on this system. Please install Pandoc prior to exporting or importing files.”  
I downgrade the versions of both Zettlr and Pandoc. But it still doesn't work. And I used to export md files in Zettlr and it worked fine. But now even the old version does not work any more.

I try to export md files with typora, and it works fine, which means Pandoc should be installed properly.
I also uncheck the box of Use the internal Pandoc for exports. Nothing changes.

### Reproducing

Upgrade from 2.3 version to 3.0.3 version and then I can not export.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

log file goes like this:
Pandoc has not been found on this system. Please install Pandoc prior to exporting or importing files. | Native Error: Error; Pandoc has not been found on this system. Please install Pandoc prior to exporting or importing files. Stack Trace: Error: Pandoc has not been found on this system. Please install Pandoc prior to exporting or importing files. -->     at Object.run (D:\Program Files\Zettlr\resources\app.asar\.webpack\main\index.js:2:1898782) -->     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) -->     at async t.makeExport (D:\Program Files\Zettlr\resources\app.asar\.webpack\main\index.js:2:1902022) -->     at async f.run (D:\Program Files\Zettlr\resources\app.asar\.webpack\main\index.js:2:1897509) -->     at async W.run (D:\Program Files\Zettlr\resources\app.asar\.webpack\main\index.js:2:1926237) -->     at async D:\Program Files\Zettlr\resources\app.asar\.webpack\main\index.js:2:1924913 -->     at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89091)

**Comment by nathanlesage** [comment]
Does exporting using the bundled Pandoc work? (Check the corresponding checkbox, restart Zettlr, and then try to export)

**Comment by suntarliarzn** [comment]
No, I even uninstall the Pandoc that I have installed before. No matter I check or uncheck the internal Pandoc checkbox in Perferences. I does not work.

**Comment by nathanlesage** [comment]
Please try out the current nightlies; I remember fixing a very similarly sounding bug just a few weeks ago, it might've fixed yours too. If not, I can investigate further.
