### ISSUE TITLE
Allow to copy error on export message

### ISSUE THREAD

**Issue by keunes** [Zettlr/Zettlr#484]
I just installed pandoc but getting an error message after trying to export a document. For debugging/support purposes, it would be nice to be able to copy the message that Zettlr presents.

Currently, only the error message output is copyable (though that's not very discoverable). It would be useful to also be able to copy the the command that lead to the error (which is visible in the Zettlr window, but not copyable).

**Comment by nathanlesage** [comment]
99 percent of all errors that Pandoc produces are related to something like having to re-install some package or so, so I don't see any added value in having the command copyable?

**Comment by nathanlesage** [comment]
Fixed with one of the recent commits
