### ISSUE TITLE
Font awesome in Zettlr presentations

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#4840]
### Description

I will love to use [Font awesome](https://fontawesome.com/v4/icons/) in Zettlr presentations using Reveal.js.

### Proposed Changes

When you create a presentation exported using Reveal.js, the HTML's head should have this code: 

`>    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">`

Then, when you create a md file using Zettlr, the code can include something like this, to generate font awesome icons:

`> <span class="fa fa-heart"></span>`

### Caveats

Maybe the generation of offline presentations can be affected.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu

### Additional Information

Thanks for considerate this!

**Comment by nathanlesage** [comment]
You can do so easily with the [corresponding Pandoc writer settings](https://pandoc.org/chunkedhtml-demo/6.2-variables.html#variables-for-html). In the best case it should be possible to specify the FontAwesome CSS directly in the profile (see link), in the worst case you simply need to copy and paste Pandoc's default reveal.js template and adapt this. In any case, this would be a great discussion to have on [Discord](https://go.zettlr.com/discord).
