### ISSUE TITLE
[ENHANCEMENT] Image path that consist the notes filename

### ISSUE THREAD

**Issue by hyphone** [Zettlr/Zettlr#485]
First, thank you very much for this amazing markdown tool.
I finally found a great solution for my usecase :heart_eyes: 

## Description

When I have note "test.md" I would like to save my images into a folder named for example ".test.md.assets".

This is quite useful for example when I copy the document to an email client and the images are missing. I don't have to hunt the image in a big folder where all images are.

Another usecase would be if I delete the document but the image is not deleted. So I can just delete the folder thats named like the document itself to keep my folder structure clean.

## Proposed Changes

Here is an example from Typora:
![Bildschirmfoto von 2020-01-23 21-52-14](https://user-images.githubusercontent.com/6410852/73022893-b7b71900-3e2a-11ea-9ebf-312f75aa1515.png)

I'm able to set a filename variable to the relative path.

##

**Comment by nathanlesage** [comment]
Corresponding snippet

https://github.com/Zettlr/Zettlr/blob/4a608194ac929101e0e913da6df3a24292234d83/source/main/commands/save-image-from-clipboard.js#L56-L59

Modify:

```javascript
// Set default path to current file's dir, if the config path is empty.
if (isCwd && defaultPath.trim() === '') {
  defaultPath = currentFilePath
} else {
  defaultPath = replaceStringVariables(defaultPath)
}
```

Plus all the ado around that change

**Comment by adamprada** [comment]
As mentioned in Issue #3199, I believe that this feature is very generally useful and it seems like it requires little programming effort. Is there any chance it could get included?
