### ISSUE TITLE
AutoCorrect toggle always reverts to "Turn on AutoCorrect"

### ISSUE THREAD

**Issue by brandonblock** [Zettlr/Zettlr#486]
The autocorrect toggle always reverts to "Turn on AutoCorrect"

## Reproducing
Go to Settings, navigate to the AutoCorrect toggle. Switch it off and Save. Re-open settings and see the toggle is still on

Autocorrect toggle stays in the position in which it's saved

## Platform
 - OS and version: macOS Catalina 10.15.2
 - Zettlr Version: 1.5.0 
 - Screen Resolution: 3440 x 1440

## Additional information
Thanks!

**Comment by nathanlesage** [comment]
Ouhhhhh, yes, I know what I missed, sorry :speak_no_evil:

**Comment by nathanlesage** [comment]
Fixed it!
