### ISSUE TITLE
Internal links aren't shown in sidebar if use `[<text>]([[<id>]])` syntax

### ISSUE THREAD

**Issue by dustdfg** [Zettlr/Zettlr#4867]
### Description

Internal links aren't shown in sidebar if use `[<text>]([[<id>]])` syntax. If I just put `[[<id>]]`, it appears in sidebar but if it is wrapped into usual markdown link it isn't considered as link. It can't be open with `Ctrl+click` and when I hover it it shows me `safe-file:///path/to/repo/[[<id>]]`

### Reproducing

Just put `[[<id>]]`, save, try to wrap it to `[<text>]([[<id>]])`, save, see results

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian12

### Additional Information
I also found that if I place link somewhere in heading `## [[<id>]]`, it also won't appear in the sidebar

**Comment by nathanlesage** [comment]
This is intended behavior. We are aware that users wish for links in the form `[[note|title]]` or `[[title|note]]`, which we haven't yet implemented. I'll be bumping this now since more and more stumble upon this issue.

**Comment by dustdfg** [comment]
> This is intended behavior. We are aware that users wish for links in the form `[[note|title]]` or `[[title|note]]`, which we haven't yet implemented. I'll be bumping this now since more and more stumble upon this issue.

Just want to add my two cents: org mode use `[[LINK][DESCRIPTION]]` which is also a good choice

**Comment by nathanlesage** [comment]
Mh yes, that's one of the issues I have with the overall thing when something is not standardized: everybody does it differently.

With the choice I outlined I'll be following what Pandoc already supports, so that is simple for the users to understand, since they don't have to jump through any hoops to simply export their files.

**Comment by dustdfg** [comment]
OK. Pandoc is cont argument for my following idea too but...

Link regexps? Just decided that it is enough flexible and especially with id regexps
