### ISSUE TITLE
[ENHANCEMENT] After CMD-n return focus to editor pane

### ISSUE THREAD

**Issue by chasrmartin** [Zettlr/Zettlr#487]
## Description
When creating a new slip with CMD-n, return the focus to the editor pane. Right now it requires a mouse click to focus on a new slip.

## Proposed Changes
When creating a new slip with CMD-n, return the focus to the editor pane.

**Comment by nathanlesage** [comment]
Right, as we now have the shortcut to focus the file list again, this makes sense!

**Comment by nathanlesage** [comment]
Aaaand here we go

**Comment by chasrmartin** [comment]
Groovy!
