### ISSUE TITLE
Segmentation Fault on start when running on wayland Fedora

### ISSUE THREAD

**Issue by Lcchy** [Zettlr/Zettlr#4877]
### Description

Hi, since my last system update, when starting Zettlr on wayland, the application crashes immediately after start.
Here is the error log I am getting:

```
$ flatpak run com.zettlr.Zettlr --enable-features=UseOzonePlatform --ozone-platform=wayland
[3:0103/131957.661657:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0103/131957.983138:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0103/131957.983178:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /app/zettlr/resources/pandoc
[Application] Quarto not found on system. *.qmd-files will be exported with Pandoc.
[Application] Environment check complete.
/app/bin/start-zettlr: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper /app/zettlr/Zettlr "$@"
```

Without the wayland flags it runs correctly:

```
$ flatpak run com.zettlr.Zettlr
[3:0103/132328.671877:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0103/132328.980275:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0103/132328.980315:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /app/zettlr/resources/pandoc
[Application] Quarto not found on system. *.qmd-files will be exported with Pandoc.
[Application] Environment check complete.
```

Does Zettlr officially support wayland?

Thanks a lot for any help! 

### Reproducing

Run `flatpak run com.zettlr.Zettlr --enable-features=UseOzonePlatform --ozone-platform=wayland`

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora 39

**Comment by nathanlesage** [comment]
Hey! It appears you're trying to run the Flatpak version of Zettlr. There is some magic going on there besides simply running the app.

Here's what I would advise: Attempt to run the regular `rpm` release (since you're on Fedora, `yum` should eat that file). Does this fix it? Then please report this issue on the correct repository: https://github.com/flathub/com.zettlr.Zettlr/

If not, please comment here again so we can again investigate. But those `bus connection errors` in the log do appear to me as if they have something to do with Flatpak, but I might be wrong.

**Comment by Lcchy** [comment]
Hi there, thanks for the reply @nathanlesage .

I tried it using the rpm release and sadly I also get a memory right at startup, here is the log:

```
 $ zettlr --enable-features=UseOzonePlatform --ozone-platform=wayland
[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /usr/lib/zettlr/resources/pandoc
[Application] Quarto not found on system. *.qmd-files will be exported with Pandoc.
[Application] Environment check complete.
fish: Job 1, 'zettlr --enable-features=UseOzo…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by nathanlesage** [comment]
@Lcchy Thabks for checking it out as then it could either be an issue with Wayland OR in our build process. @kyaso Do you have time to look into this? Or ... does anyone have a fedora WITHOUT wayland and could test it out? :D 

If the problem turns out to be Wayland, we can close this issue because there's nothing we can do, but I'll keep it open since it's at least not related to the flat pack release.

**Comment by Lcchy** [comment]
I can confirm that the issue only arises when running Zettlr in native Wayland.

I think this might come from this underlying electron Bug: https://github.com/electron/electron/issues/37531

It seems that the only solution is to update the used electron version to at least 28.

I appreciate that it might take some time for Zettlr to migrate to this version. Out of interest, what is the current electron version used in Zettlr?

**Comment by nathanlesage** [comment]
> It seems that the only solution is to update the used electron version to at least 28.
> 
> I appreciate that it might take some time for Zettlr to migrate to this version. Out of interest, what is the current electron version used in Zettlr?

It is 28; I just updated a few days ago. It's ready in the current nightlies, and it will become available via the betas and finally 3.1 stable in a few weeks, hopefully.

**Comment by Lcchy** [comment]
Ah nice! I thought that I saw 24 in some files, I will be testing when its released and will close if fixed, thanks!

**Comment by nathanlesage** [comment]
If you want to, you can try out if you can run the current nightly: https://nightly.zettlr.com -- if that runs, then the stable will also run, but it would keep the issue tracker a bit uncluttered :)

**Comment by nathanlesage** [comment]
Wonderful! There will be an unexpected patch to Zettlr coming up in the next few days, this should give you the same functionality as 3.0.3, but with the added benefit that it ships with Electron 28 and thus won't segfault on Wayland.

**Comment by Lcchy** [comment]
Cool! Thanks again!
