### ISSUE TITLE
Missing list environment error with version 3.0.3 but not with 3.0.2

### ISSUE THREAD

**Issue by Alexandros81** [Zettlr/Zettlr#4879]
### Description

After Zettlr 3.0.3 installation (I use the AppImage file), I get the following error (which on the contrary it is not raised at all when using version 3.0.2 under the same exact conditions), while attempting to produce a PDF via my XeLaTeX template: "Error producing PDF. ! LaTeX Error: Lonely \item--perhaps a missing list environment. See the LaTeX manual or LaTeX Companion for explanation. Type H <return> for immediate help. ... l.10235 \bibitem[\citeproctext]{ref-Abba2009}".

### Reproducing

Compiling PDF through pandoc and my XeLaTeX template

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Last ArcoLinux

### Additional Information

I use Zettlr's AppImage file

**Comment by nathanlesage** [comment]
I just double-checked the Pandoc releases. Zettlr 3.0.2 shipped with Pandoc `3.1.6.2`, whereas 3.0.3 ships with `3.1.11`. Indeed, with Pandoc `3.1.7`, the team has changed the citation rendering of the LaTeX exporter. In other words, there might be a chance that that broke and, since there have been a few additional releases since then, that they've silently fixed that.

Therefore, would you mind manually installing the most recent Pandoc version (https://github.com/jgm/pandoc/releases/latest), disabling the internal Pandoc in the Settings, and trying again?

**Comment by Alexandros81** [comment]
Many thanks, I'll do it and brief you about the resuts as soon as possible...

**Comment by Alexandros81** [comment]
Unfortunately, also with pandoc 3.1.11-1 installed on my OS and with the internal pandoc disabled I get the same exact error message...

**Comment by Alexandros81** [comment]
The following one is the chunck of code that solved the issue (to be put within the preamble of the LaTeX template), which seems to be due to the interaction between citeproc (a Haskell library for bibliographies formatted according to a CSL styles) and LaTeX:
```
$if(csl-refs)$
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
\begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
% allow citations to break across lines
\let\@cite@ofmt\@firstofone
% avoid brackets around text for \cite:
\def\@biblabel#1{}
\def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
{\begin{list}{}{%
	\setlength{\itemindent}{0pt}
	\setlength{\leftmargin}{0pt}
	\setlength{\parsep}{0pt}
	% turn on hanging indent if param 1 is 1
	\ifodd #1
	\setlength{\leftmargin}{\cslhangindent}
	\setlength{\itemindent}{-1\cslhangindent}
	\fi
	% set entry spacing
	\setlength{\itemsep}{#2\baselineskip}}}
{\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
$endif$
```
Credits for the solution have to be given to the creators of the Eisvogel LaTeX template: [here](https://github.com/Wandmalfarbe/pandoc-latex-template/issues/361) and [here](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/tag/2.4.2)
