### ISSUE TITLE
The citation right-click to open pdf doesn't work

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#488]
## Description
The citation right-click to open pdf doesn't work on windows 10. It also doesn't show the same citation rendering as previous zettlr version did (instead of showing (Ngai, 2015) it shows @ngaiSocialMediaResearch2015)

## Reproducing
I use Zotero and a new zotero add-ons: Zotero Scihub 0.05 by Ethan Willis for automatic download of PDFs from Scihub. I insert the citation to Zettlr, however, none works, whether it comes from older files which attachment wasn't downloaded by the add-ons, or the new ones. 

## Expected behaviour
Zettlr should have shown the special grey-highlighted citation, and if clicked, it should oscillate between (Ngai, 2015) and @ngaiSocialMediaResearch2015. And it should also include the pdf in the attachment and a right-click menu to access attached pdf from the citation

**Screenshots**
![Screenshot 2020-01-26 10 36 03](https://user-images.githubusercontent.com/30141705/73130280-08479580-4028-11ea-8ebc-697bfad105c4.png)

## Platform
 - OS and version: Windows 10, Intel(R) core(TM) i5 8250U CPU @ 1.60GHz 1.80 Ghz. 
 - Zettlr Version: 1.6.0-beta
 - Screen Resolution: 1366 x 768

## Additional information
Thanks, Hendrik :)

**Comment by nathanlesage** [comment]
Simply add a space (or, better, a list item) before your citations. They need to be rendered (a.k.a. with the light grey-ish background) in order for that to work! Meanwhile I'll have a look why something needs to preceed them …

**Comment by nathanlesage** [comment]
Aaaand fixed! :)

Lookbehinds can be nasty sometimes …

**Comment by shanvrolijk** [comment]
Thanks Hendrik  :)
