### ISSUE TITLE
Incorrect URL detection

### ISSUE THREAD

**Issue by Fedik** [Zettlr/Zettlr#4881]
### Description

I have noticed that any text with dot in it marked as URL.
This is very confusing, especialy when writing list of files or emails or other "special" text that require dot in it.

### Reproducing

Use following text:

```
Files list:

foo/bar.jpg
foo/bar2.jpg

Emails:

foo@example.com
bar@example.com

Remote addresses:

ssh://foobar@example.de
foo://foobar@example.de/path/to/foobar.txt

index.php?var=foobar
```

It should be rendered as normal text, but rendered partly as link:

![Screenshot 2024-01-06_18-53-52](https://github.com/Zettlr/Zettlr/assets/1568198/b32258a7-fb70-4bd7-b975-c83848278ec4)

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

I have disable "Link preview" and "Show links" (in Display tab) options, but it does not help.

**Comment by nathanlesage** [comment]
You are correct -- which is why I have modified the link detection to be much less aggressive. This will come with the next release, and is documented in the Changelog file -- feel free to have a look!
