### ISSUE TITLE
Update Electron to supported release

### ISSUE THREAD

**Issue by alerque** [Zettlr/Zettlr#4887]
Upstream ended support for Electron 25 when [Electron 28 was released](https://releases.electronjs.org/release/v28.0.0), making it EOL and not receiving backports of Chromium security bug fixes. Many distros (including Arch Linux for which I package Zettlr) are working on dropping packages for EOL Electron versions.

Supported [releases](https://releases.electronjs.org/) as of this writing are the 26, 27, and 28 series.

I would like to encourage Zettlr to take the first opportunity to update to something newer. Preferably all the way up to the newest stable release of course, but if that proves to be a large development effort even bumping up to 26 as a patch release so that distro packaging can stop including EOL Chromium builds that would be appreciated.

Typically what happens is if there is no upstream action on this distro packages are forced to do the update themselves, which sometimes works but sometimes breaks apps or leaves rough edges that upstream bumping and testing would have iron out better. I don't want to see that happening to Zettlr packages.

**Comment by nathanlesage** [comment]
Thanks for reminding me, I have that on my radar. It's on the roadmap; I am right now in this very moment working on preparing the migration all the way from 25 to 28. As far as I'm concerned, nothing much has changed, but someone would have to do the work of sifting through Electron's changelog and see if we actually use some of the deprecated/removed APIs which would break during upgrade.

If you would like to do that (read the Electron changelogs and do a quick search over Zettlr's codebase if the corresponding function names are even called) that might speed it up.

**Comment by nathanlesage** [comment]
Quick update: The Electron releases appear to be applicable even though I can't yet upgrade Electron Force, so I'm gonna see if I can get all the way to 28 tonight.

**Comment by nathanlesage** [comment]
Alright, that was easier than expected. Zettlr v3.1 will be on Electron 28, or 29 if they release it before 3.1 stable.

**Comment by alerque** [comment]
Not something to change during the beta release phase for 3.1.x, but just a note to suggest that the *first* thing that should happen in the next development cycle as soon an the minor version is tagged in upgrade Electron. The v29 being shipped with the upcoming release will be okay for a *little* while, but it is already not the current latest release...before Zettlr has even shipped it. Then as long as you're not in a beta series leading up to a release keep bumping it during the development cycle so it doesn't freeze until just before a release.

**Comment by nathanlesage** [comment]
I intend to run a full update cycle before releasing 3.1 stable, which includes upgrading the Electron version. I really don't like the fact that they run these insane breakneck update cycles, however, so I'll do my best, but I cannot and will not guarantee that Zettlr always has always the most recent version. I do plan on going on faster update cycles, however, instead of the 6 month wait times we have currently.
