### ISSUE TITLE
[ENHANCEMENT] Copy files to directory when dropped into a slip

### ISSUE THREAD

**Issue by chasrmartin** [Zettlr/Zettlr#489]
## Description
When I drag and drop a file onto the attachments or editor pane, copy the file from its current location into the Zettlr directory.

## Proposed Changes
Removes several clicks and drags when creating a slip with attachments, thus reducing the time and effort

**Comment by nathanlesage** [comment]
Good idea! Will take some effort, but I certainly see the benefits of it!

**Comment by chasrmartin** [comment]
I pulled a fork last night maybe I’ll take a look

**Comment by nathanlesage** [comment]
Well, the main problem is currently that the IPC-calls are a mess, a better design is needed, until then it's only a monkey patch (but still worth implementing)
