### ISSUE TITLE
Unexpected display of e-mail links

### ISSUE THREAD

**Issue by HJKLE** [Zettlr/Zettlr#4895]
### Description

If they do not correspond to a certain structure, email addresses are not fully transformed into clickable links.

### Reproducing

Use a combination of strings with or without a period in the username (the part before the @-sign):

![Bildschirmfoto_2024-01-12_16-50-42](https://github.com/Zettlr/Zettlr/assets/133958042/9e3f8fb8-5fd5-4dc8-8f80-cb38c5a1fe3b)

If I remember correctly, the problem has only occurred since Zettlr version 3+.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.3 (Kernel 5.15.0-91-generic) with Xfce 4.16

**Comment by nathanlesage** [comment]
This is fixed in the current develop branch and will come with the next update. Please make sure to read the Changelog for that one.
