### ISSUE TITLE
Background color lost with version 3.0.3

### ISSUE THREAD

**Issue by 2364c66e322e44d99b0caeee94b8010c** [Zettlr/Zettlr#4913]
### Description

After installing version 3.0.3, the background color is lost (see below)

![berlin](https://github.com/Zettlr/Zettlr/assets/1226730/355389a2-82cc-42a7-83bd-719fb1c50b90)

![Frankfurt](https://github.com/Zettlr/Zettlr/assets/1226730/c14b5e68-2c3f-4216-a904-4cd1eaf434c9)

### Reproducing

install version 3.0.3
remove ~/Application Support/Zettlr (fresh start)
launch Zettr. Select theme -> no color

install version 3.0.1
remove ~/Application Support/Zettlr (fresh start)
launch Zettr. Select theme -> colors are back

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.1 (1.2 same issue)

### Additional Information

I also dig into the debugging tool, and .main-editor-wrapper{ background-color : #fffffff } is always set this way, while in previous version each theme was setting it properly with the relevant color (green or red or blue etc..)

**Comment by nathanlesage** [comment]
I am afraid I do not completely follow what the issue here is …?

**Comment by nathanlesage** [comment]
Ooooohh, I see what you mean. That looks like a bug!

**Comment by 2364c66e322e44d99b0caeee94b8010c** [comment]
thank you!

If can be useful, 
.cm-scroller{
    background-color: #F3F3E7;
}
this custom css temporarily restored it.

If you have the plan to align with the others, then maybe a flag or a note in the docs with the above config (with the precise color is different) for the people who prefer it the old look and feel could be an option too.

**Comment by exanrauzer** [comment]
Please - to bring the old feeling - restore the font color. Thank you! I don't know if other aspects were flushed. I just love the Bordeaux dark theme.
