### ISSUE TITLE
Heading structure issue when exporting to .docx.

### ISSUE THREAD

**Issue by fr-laurentn** [Zettlr/Zettlr#4917]
### Description

Hello, 

I've been giving Zettlr a try for the last few days and so far, I love it.

I only have one issue :
When I export my .md to the .docx format, the heading structure is wrong.

For instance, a h1 in Zettlr will become a h2 in Word, a h2 becomes a h3…
The heading structure is correct in Zettlr, and I don't understand how it can happen.

Also, how can I change the default theme used to generate the .docx file? I don't want the headings to be colored in blue (#4F81BD).
![zettlr](https://github.com/Zettlr/Zettlr/assets/15927630/1779259c-191b-4508-8b16-411729c7bfd2)
![word](https://github.com/Zettlr/Zettlr/assets/15927630/1d8a155c-117d-47d2-b15e-512396d34b44)

### Reproducing

Create a file with at least a h1 and several h2.
Export it to Word (the location of the directory doesn't matter).

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by lcsolano** [comment]
This is not a bug.

1. Regading heading levels, you have an offset. Look at the `shift-heading-level-by` value in the assets manager.
2. Regarding the template:

https://www.reddit.com/r/Zettlr/comments/1821h3f/defining_reference_documents_for_docx_and_odt/

**Comment by nathanlesage** [comment]
I just saw that the docx export has a setting "Shift heading level by 1". So I think you should be able to fix this by modifying the MS Word export profile and change a 1 in this shift setting to a zero.

Regarding a custom template: for this you'll need to go to the Pandoc repository: https://github.com/jgm/pandoc

Then go to data -> templates, and you will see a folder that contains a few XML files for the word template. Download this folder, zip it, and change the ending to .docx. Then, modify the styles to your liking and provide that file as a reference doc for the export profile.

I'm on mobile so I can't search for all the various links, but I think everything should be buried somewhere in the documentation -- let me know if you have further questions!

**Comment by fr-laurentn** [comment]
Thanks @nathanlesage, it worked!

However, I don't understand the logic behind this setting.
@lcsolano Why do you say that it is not a bug (assuming this is a feature)?

For further reference, the solution that worked:
1. Go to Files > Preferences > Assets Manager
2. Open the Microsoft Word asset and search for `shift-heading-level-by:`. 
3. Change the value to 0 and save.

Thanks for the link about the template, I'll have a look.

**Comment by lcsolano** [comment]
> Thanks @nathanlesage, it worked!
> 
> However, I don't understand the logic behind this setting. @lcsolano Why do you say that it is not a bug (assuming this is a feature)?

Take a look at the Pandoc User's guide:
https://pandoc.org/MANUAL.html

```
--shift-heading-level-by=NUMBER
Shift heading levels by a positive or negative integer. For example, with [--shift-heading-level-by=-1](https://pandoc.org/MANUAL.html#option--shift-heading-level-by), level 2 headings become level 1 headings, and level 3 headings become level 2 headings. Headings cannot have a level less than 1, so a heading that would be shifted below level 1 becomes a regular paragraph. Exception: with a shift of -N, a level-N heading at the beginning of the document replaces the metadata title. [--shift-heading-level-by=-1](https://pandoc.org/MANUAL.html#option--shift-heading-level-by) is a good choice when converting HTML or Markdown documents that use an initial level-1 heading for the document title and level-2+ headings for sections. [--shift-heading-level-by=1](https://pandoc.org/MANUAL.html#option--shift-heading-level-by) may be a good choice for converting Markdown documents that use level-1 headings for sections to HTML, since pandoc uses a level-1 heading to render the document title.
```

**Comment by lcsolano** [comment]
For the template, you can do something even easier:

1. Create a generic note in Zettlr. A note with headings, some text, bullets, numbered list, a quote, etc.
2. Modify the styles on that document, content doesn't matter.
3. Use that document as a template. In the assests manager for the ms word export (where you changed the offset) add a line to define that document as the template with the command: `reference-doc: '/path/to/your/template/odtTemplate.odt`

For windows it'll look like this (assuming that the filename for the template is zettlrDocxTemplate.docx):

`reference-doc: "C:/Users/yourUser/Documents/something/something/zettlrDocxTemplate.docx"`

**Comment by fr-laurentn** [comment]
Thanks @lcsolano.

I've read the doc, and it still doesn't make much sense to me, especially why this is a default feature.

For the template, this what I did :

1. I created a template.docx file with the styles I want,
2. Added the path to `reference-doc:`

And that's it. ^^

I still have an issue with the font that does not match the one from the template, but it's not a big deal for me.

Thanks for your help!

Should I close this ticket?

**Comment by lcsolano** [comment]
Great it worked!

Yes, better close/delete the ticket.

And regarding the tempalte, do whatever you want in MS Word, you have total control.

For example, I add a break in the style for the Table of Content title. This way, it it generated automatically in a new page.

I also do that for Heading 1 in some documents. So, every new H1 is automatically in a new page. I also add some more space after the H1.

That's the power of Zettlr/Markdown/Pandoc: you tune the template once and forget about formatting and focus in writting!

**Comment by fr-laurentn** [comment]
If that's OK, I'm not deleting the issue since it may help someone else.

**Comment by nathanlesage** [comment]
@lcsolano Amazing, I didn't think of this much more ergonomic way of creating a modifiable docx reference -- and I think we should put this in the docs. Would you mind adding a new guide page with this info, maybe even generalisable to any other templates to be filled in later? Or shall I do this and reference you with your permission?

**Comment by lcsolano** [comment]
I can sure write something about it. I even had the intention to do a video tutorial, but you know, lack of time.

But just give me some days to write something for the docs, I will gladly do it.
