### ISSUE TITLE
Collapse arrows showing in non-text space

### ISSUE THREAD

**Issue by internationils** [Zettlr/Zettlr#4918]
### Description

I am in typewriter mode and you can see the arrows that are being shown before the first line of text (the H1 heading). Clicking them collapses the H1.

### Reproducing

To reproduce, create some H1s and some text, go into TW mode and select the first line, then move the mouse to where the collapse arrows are.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win11

**Comment by internationils** [comment]
![image](https://github.com/Zettlr/Zettlr/assets/14021625/73aff3b9-de6f-4044-a9be-7901d4098e11)

**Comment by nathanlesage** [comment]
Interesting issue -- I'll have a look.
