### ISSUE TITLE
[ENHANCEMENT] macOS: notarize app so it can easily be opened

### ISSUE THREAD

**Issue by foss-** [Zettlr/Zettlr#492]
## Description

Notarize Zettlr.app on macOS.

## Proposed Changes

1 June 2019 was the day from which all apps shipped by developers outside the App Store are expected to be not just signed, but hardened and notarized as well.

In practice this means that non notarized apps will open with this dialog:

![cannot be verified](https://user-images.githubusercontent.com/5708172/73210686-0fb38f80-414b-11ea-8e76-9393ab216120.png)

The workaround is to open System Preferences > Security > General and click "Open Anyway".

![workaround](https://user-images.githubusercontent.com/5708172/73211184-0aa31000-414c-11ea-809d-bb3cd1afdd76.png)

Notarization makes the build process more complex as the macOS build will have to wait for Apple to do their notarize foo before it can be finished. In the past months there were several occasions where [notarize service would behave unecpectedly](https://eclecticlight.co/2019/11/05/apples-notary-service-cant-compete-with-a-supermarket-restroom/). Yet it seems notarize is here to stay and the new default for macOS builds.

**Comment by nathanlesage** [comment]
Already planned, this is why we moved to continuous deployment builds during the weekend — in preparation for exactly that.

**Comment by nathanlesage** [comment]
Hah, just found it! Aaand closed because it's implemented!
