### ISSUE TITLE
Show the Title instead of the file name in the popup file preview

### ISSUE THREAD

**Issue by lcsolano** [Zettlr/Zettlr#4921]
### Description

When the cursor is over a link, it shows a small file preview.  I'd like that window to show the note title instead of the file name.

![image](https://github.com/Zettlr/Zettlr/assets/19916268/b47fd85b-2099-459d-a2b3-75cc404b2a4d)

### Proposed Changes

To show the title if it exists instead of the filename.

### Caveats

None.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Pop!_OS 22.04 LTS x86_64

**Comment by nathanlesage** [comment]
Good suggestion!
