### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by niklasliebig** [Zettlr/Zettlr#4928]
### Description

I try to figure out how to export documents that make use of image captions and table captions as explained here:
https://pandoc.org/MANUAL.html#extension-implicit_figures
https://pandoc.org/MANUAL.html#extension-table_captions
```
![caption](file.png)
Table: Caption

```
Table captions work fine for me when I export them to html and latex. However, figure captions appear in Zettlr (mouse hover) but do not show up when I export to html or xelatex (pdf). I have double checked that I have activated the extension +implicit_figures.

### Reproducing

Create a markdown file with images e.g.: `![caption](file.png)` and export it to html or xelatex (pdf). The caption is not visable in the exported file.

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I can't really reproduce this. For me, image captions always showed up. Also, I am a bit confused because you say something about image and table captions, and in your example provide a table-style caption below an image that, as far as I know, already supports captions within the image tag?

**Comment by niklasliebig** [comment]
The code block example is only meant to summarize table and image captions and show how they are used in Markdown, as shown in the Pandoc links above. It is not intended to put a table caption under an image. Sorry for the confusion. As for the problem, I solved it for myself by putting a blank line above and below the image tag. The captions are rendered fine now.

**Comment by nathanlesage** [comment]
Ah yes, captions for images will usually only be rendered if the image is a block on its own, and not inline. Thus, blank lines above and below are required if you need actual captions to show up. That's probably not as clearly documented as necessary!
