### ISSUE TITLE
Lost Data after accidentally "Not saving" file 

### ISSUE THREAD

**Issue by Sklanfurt** [Zettlr/Zettlr#493]
Dear Nathan, 
I am currently writing my first thesis in Zettlr and I am pretty close to the deadline right now. For the last two days I wrote about 2000 words that now seem to be lost (worst case scenario). 
After I duplicated my file, Zettlr showed me a prompt that stated that there are unsaved changes and asked me if I want to save them. I think that I clicked Yes, but maybe I misclicked to No. Anyways, those 2000 words are lost now. I have not powered down my computer for two days and obviously Zettlr did not autosave my .md-file. As I did not delete the file, I can not recover it from the recycle bin and my latest recovery is 2 days old. 
Do you know of any method to save or recover the lost data?
Thanks and Greetings, 
SKlanfurt

**Comment by nathanlesage** [comment]
Did you shut down Zettlr? Or is it still running? In super rare occasions, Zettlr exhibits this bug, and I haven't been able to pin down why it would do so, but if Zettlr is still running, I'd recommend copying the contents out of it and into any other editor, re-start Zettlr and paste the contents back in.

If the contents are not in the file they are only in memory, which gets freed once Zettlr is closed.

**Comment by Sklanfurt** [comment]
Today I again randomly lost 1000 words of text because Zettlr did not "hard" safe the changes to the .md-file. Unfortunately I can not tell why this happened. I was writing on the same file for some days and today the app crashed, so I had to fore quit it (unfortunately I did not copy the text, because I thought that I had safe-files). After restarting the app the text of the last three days of work was gone (which is bad but not worst). As I already had this problem with Zettlr (as described in this issue) I made several safe-files a day. But after opening my safe-file I realized, that Zettlr did not safe the changes into the file (so I just saved the same old file a dozen times). 
I understand that this is hard to fix without anything to clinge on, but as this (at least for me) is possibly the worst bug a writing app could have, this should be addressed and maybe there are others who also encountered this strange behavior. 
Greetings
Sklanfurt

**Comment by nathanlesage** [comment]
Well, there are about 1.5 years between the first incident and this one, which I personally deem very much acceptable.  I can certainly fix the crash if you can reproduce it, but with regard to the lost progress, the only I can offer you is the potentially condescending notion of "Save early and save often". Data loss is always possible (irrespective of any saveguards) and saving requires you to literally hit two keys on your keyboard, which is certainly possible.

**Comment by Sklanfurt** [comment]
Hi, I don't know if this came through, so I'll say it again: I did safe the file (probably 100 times). The little "*" mark by the file name disappeared after hitting cmd+s and the problem is, that I lost the progress nevertheless. I don't know how to explain it better. I just thought maybe it would help, if I posted this error, as I really appreciate the effort you put into developing the app and I would like to be able to use it in the future. 
Thanks.

**Comment by Sklanfurt** [comment]
I think I found out what caused the data loss: Some days ago, I decided to move the project folder, but then I decided to move it back to the same place it was before. Maybe Zettlr in the foreground saw that the file is still where it used to be but in the background tried saving to a file that did not exist anymore.

**Comment by nathanlesage** [comment]
> The little "*" mark by the file name disappeared after hitting cmd+s and the problem is, that I lost the progress nevertheless. I don't know how to explain it better.

Ah, that is weird indeed.

> Some days ago, I decided to move the project folder, but then I decided to move it back to the same place it was before. Maybe Zettlr in the foreground saw that the file is still where it used to be but in the background tried saving to a file that did not exist anymore.

So that means in the meantime you didn't close Zettlr?

**Comment by Sklanfurt** [comment]
> So that means in the meantime you didn't close Zettlr?

That's right. Maybe the app needs a procedure to check if the file is still where it is supposed to be. I mean, sometimes apps ask you to relink the file, when you moved it from its original place (I don't know if this is helpful, as I don't have any clue how this works, just trying to be helpful :-))

**Comment by narekkay** [comment]
Hi,
I was working on a text for 9 hours.

Ctrl+s at every major progress,
And after my final save, I hit "close", it prompted me do I want to save, hit yes, and it took me all the way back to the first few lines.

Lost 9 hours.

I can't express my pain.

Never using zettlr again.

Wish I never used this.

F***

**Comment by Epicrex** [comment]
It's funny how this dev is saying stuff like: 
"1.5 years between the first incident and this one, which I personally deem very much acceptable."
""Save early and save often". Data loss is always possible"

Thinking that the user has to change and not the software, and to somehow think that if there is any possibility of losing data even occasionally, that that's just fine and dandy. It's great that it's not happening every month but that doesn't make it good all of a sudden that it happens only once a year.

Hot take buddy, but no one should be clicking Ctrl+S EVER except for at the end of sessions. It's ridiculous to be saying oh it's your fault for losing all of your work, you didn't save. Ever heard of auto save, it's a magical thing only spoken of in legends, I know.

**Comment by nathanlesage** [comment]
If you don't like my approach that balances out my free time I spend on this free app for you to use, and my sanity, then there are plenty of good alternatives out there.

**Comment by Epicrex** [comment]
OK you have a point, this is nothing commercial. I guess I just let out some steam on this topic, and it happened to be here of all places. Allot of commercial software also doesn't have auto save and I often see people in the community defending it by saying how it's so easy to just Ctrl + S.

**Comment by kyaso** [comment]
Well, "commercial" means that something is sold for a price. I don't see a price tag anywhere for Zettlr, so it clearly isn't commercial. Patreon is there to cover parts of the development costs.

Hendrik is doing all of this in his _free time_. People should be a bit more respectful considering how an amazing piece of software Zettlr is, especially when realizing this is essentially a one-man army.

Most users of Zettlr don't face any serious issues (e.g. I've been using Zettlr for almost 3 years now (on a daily basis), and never had any data loss). If you happen to be one of the rare unlucky ones, and refuse to accept a zero-friction workaround until the issue can be reproduced and fixed, then, I guess, it's time to look for alternatives.

**Comment by silviaesparza** [comment]
Dear Nathan, 

I am writing my thesis in Zettlr too. Today I have lost the information in all my files. All files are simply blank. 

Like SKlanfurt, Zettlr showed me a prompt that stated that there are unsaved changes and asked me if I want to save them. I think I clicked Yes.

Even though the files were supposed to be saved already, I lost them all. :(

Silvia

**Comment by sidney-eliot** [comment]
> Dear Nathan,
> 
> I am writing my thesis in Zettlr too. Today I have lost the information in all my files. All files are simply blank.
> 
> Like SKlanfurt, Zettlr showed me a prompt that stated that there are unsaved changes and asked me if I want to save them. I think I clicked Yes.
> 
> Even though the files were supposed to be saved already, I lost them all. :(
> 
> Silvia

Accept the fact that you made a wrong decision, as you first decided to work with Zettlr. Learn from your mistake and use a proper editor in the future, aka Obsidian

Also, I'm sorry for your loss, I know it must suck.

**Comment by nathanlesage** [comment]
@silviaesparza Hey, that is tragic -- honestly. Is there any backup of these files that you can recover from? It would greatly help prevent this if you could share what happened right before you closed the app -- ideally even with the logs！

**Comment by sidney-eliot** [comment]
Pretty sad that you guys deleted that comment, doesn't look good to hide critical opinions/ warnings for others to see. But I'll unsubscribe from this tragic thread, so I don't feel tempted to reply to any other messages in the future.
