### ISSUE TITLE
Save problems

### ISSUE THREAD

**Issue by internationils** [Zettlr/Zettlr#4931]
### Description

I have files in Dropbox, and can access and modify them no problem. However:
- some files when I modify them are not marked as modified (the asterisk in front of the filename)
- I can't save them (saving does nothing)
- when I close them and reopen, I see the previous contents (i.e. the changed file was not saved)

### Reproducing

Try 3.0.3 with dropbox and a folder structure 2-3 levels deep, nothing complicated. Not sure if there is anything specific that is needed to reproduce. Is there a debug log somewhere?

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

win11

**Comment by niklasliebig** [comment]
The same applies to me on Windows 10 with Zettlr 3.0.3. For some files, Zettlr simply does not notice that they are being edited. However, in my case this only seems to affect imported files that use a yaml frontmatter. When I create a new file from within Zettlr, it works so far. There are some logs in "AppData\Roaming\Zettlr\logs\" on Windows. However, they don't show any helpful entries in my case.

**Comment by nathanlesage** [comment]
I have just started building a new nightly. In the past three days I've extensively worked on the app, and maybe by chance fixed that issue as well. Please try it out and tell me if the issue still persists. If so, I'll have to somehow get my hands onto a Windows computer with a Dropbox folder …

**Comment by igstef** [comment]
Same for me on Windows 11. Local files. No asterisks to indicate edits. Autosave not working. Clicking on cross to close Zettlr window closes immediately without warning and without saving the file.

**Comment by stickers-art** [comment]
Maybe I have a slightly different issue, but it sounds similar: 
I am running 3.0.5 on Ubuntu/linux 6.1.0-1029-oem (x64). I don't use Dropbox, but save my files locally. 
I can open new files and it saves just fine. However, when I modify an existing file, the changes are not saved. The asterisk persists, even if I do ctlr+s or save manually. When I close the app, all changes are lost. When I reopen the app, I need to reopen the file. 
Sometimes, but not regularly, I am prompted to save unsaved changes, and then it works.

**Comment by nathanlesage** [comment]
This all belongs to a singular issue that we have in the document manager. I still haven't fully tracked it down, but it's in that module. The various weird flukes you all are seeing all belong to a bigger problem. Therefore, please copy & paste all info to this issue: https://github.com/Zettlr/Zettlr/issues/4959

The more concentrated the info is, the easier it is for me (and the faster I will be) to fix this issue for good. I'm going to close this issue so that we can focus on the one issue. Thanks!
