### ISSUE TITLE
at mentions and snippets do not play well together

### ISSUE THREAD

**Issue by gforcada** [Zettlr/Zettlr#4938]
### Description

I use snippets to produce markdown links to relevant issues (i.e. `[#4899](https://github.com/zettlr/zettlr/pull/4899)` and that works wonderfully ✨ 

I recently discovered that writing `@something` highlights it (in my theme with a red colored font and a subtle background).

But combining them works, or not:

✅ on the same line a markdown link and, afterwards an `@something`
❌ on the same line a `@something` and then a markdown link
❌ if the line is on list, after typing the `@something` if I then write `:` the snippets autocompletion dialog does not show up at all

### Reproducing

On an empty line type: `@something [test](https://github.com)` 

Notice that the highlight of the `@something` expands until `[test]` and then the link in parenthesis is not omitted and does not turn `[test]` into a visual `test` with an underline.

On an empty line type: `- text @something :` see that the dropdown menu to enter snippets does not show up

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Linux 39

**Comment by nathanlesage** [comment]
This is not really a bug. What you are trying to achieve is utilize strict Github flavored Markdown, but Zettlr is biased towards Pandoc's Markdown.

Specifically, what you are noticing is an interference with the citation syntax. Zettlr does not support "@"-ing someone; instead it will assume that you are citing someone.

To ensure the behavior you want (sans actually "@"-ing someone), you'd need to escape the @-character with a backslash.

I am not certain if there is a way to accommodate both citation AND GitHub-people-referencing at the same time, but this is a question for a discussion (either here in the discussions section or, preferably, on Discord), not an issue here on the tracker.

**Comment by gforcada** [comment]
Thanks! and sorry for the noise. I will `@mention` my colleagues on my notes then 😊
