### ISSUE TITLE
LaTeX Export Not Working - Pandoc Error 47

### ISSUE THREAD

**Issue by Myarlathotep** [Zettlr/Zettlr#4949]
### Description

The "XeLaTeX to PDF" export recipe does not work, and neither does creating a new export template as is shown [here](https://docs.zettlr.com/en/academic/custom-templates/), the following message is displayed:

> An error occurred on export: Pandoc exited with code 47
> xelatex not found. Please select a different --pdf-engine or install xelatex

A similar error occurs if I change the pdf-engine to `pdflatex`, and every other export option works, including "Simple PDF". Pandoc error 47 is apparently: 

>PandocPDFProgramNotFoundError

I am running Pop!_OS and installed Zettlr via the PopShop.

I have installed the TeX suit using the instructions [here](https://docs.zettlr.com/en/installing-latex/), and have tried both the basic and full install, neither worked. 

I have checked that `xelatex` is part of my PATH, and it does appear in `/user/bin/` after using the `which` command.

I have tried uninstalling and re-installing, and clearing cache, but Zettlr does not seem to find my install of TeX. 

Any suggestions greatly appreciated.

M

### Reproducing

From a fresh install:

1. Open any .md file (e.g. the tutorial files included in Zettlr)
2. Click the "Export the current file" button or File -> Export
3. Select "XeLaTeX PDF (pdf)" from the drop down options
4. Export

### Zettlr Version

Stable (most recent version)

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Pop!_OS

### Additional Information

Installed via PopShop

**Comment by jonahfang** [comment]
I use Zettlr on windows 11 and have the same problem, after installed latex full version and reinstall Zettlr sovled the problem.
