### ISSUE TITLE
IDs-as-link-targets broken in V3

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#4954]
### Description

In v2.x, I made (very very) liberal use of internal links, in the following style:

```
[link text]([[20240212111447]])
```

This was the only way I knew of to link to an internal document by its ID, but have the rendered text be readable.

I seem to recall (although I can't find where) that I had previously asked for Ctrl-Click to open the link internally, just as it does with external documents.  The request was not granted, for reasons I do not fully recall.  Nevertheless, I was happy to live with the workaround, which was:

1. Click on the rendered text (thus exapanding the underlying markdown)
2. Ctrl-click on the (newly-exposed) internal link (i.e., the thing inside of the `[[...]]`.)

In 3.0.5, this does not work at all.  Ctrl-click does nothing.  When I mouse over the link, it gives me this:

```
safe-file:///home/chogg/notes/work/[[20230807113801]]
```

It looks like it's interpreting the `[[` and `]]` to be part of the filename?

While #4024 is merely inconvenient, this present change is an absolute deal breaker for me: it makes the program impossible to use with my Zettels.  I'm going to need to revert to 2.3.0 until it gets fixed.

The ideal fix would be for there to be some way for me to follow all of the thousands of links I've created over the past few years, without updating them.  An alternative would be if there's some other preferred way for me to specify the render text for an internal link, I could consider attempting an automated search-and-replace over all internal links.

### Reproducing

1. Type this code: `[rendered text]([[`
2. This should produce an autocomplete with Zettlr pages.  Select any of them; it doesn't matter which.
3. Observe that a link is created, rendered as `rendered text`.  Mouse over the link, and see the `safe-file:///` URI.
4. Try Ctrl-clicking on the rendered link: observe that nothing happens.
5. Try clicking on the link to expand the markdown, and ctrl-click on the internal link: observe that nothing happens.

My preferred behaviour would be that step 4 would open up the zettlr page.  Failing that, I'd like for step 5 to be a way to do that.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

I installed via dpkg from a .deb download.

**Comment by chiphogg** [comment]
Ah, now I think I understand --- the user can choose which syntax they prefer, probably as a setting.

Do you have a plan for how to find out which one is more common?  Personally, I don't know how I would go about doing that. 

One consideration is that the usual markdown syntax for a link, `[title](link)`, puts the title first.  I think this will be overwhelmingly familiar to most users.

Another consideration is the failure mode.  Users who pick the wrong syntax will get immediate feedback that they got it wrong, because the rendered text would be the link instead of the title.  IMO this means the choice of default doesn't actually matter very much.

So if you need to make a decision, I'd suggest going for `[[title|link]]`!  :slightly_smiling_face: 

In any event, I'm really looking forward to having an officially sanctioned syntax for internal links.  By the way, do you plan to make them Ctrl-clickable in the same way that regular links are?

**Comment by nathanlesage** [comment]
> So if you need to make a decision, I'd suggest going for [[title|link]]! 🙂

Since that is also what Obsidian uses, I think I'll be going with that one, indeed.

> By the way, do you plan to make them Ctrl-clickable in the same way that regular links are?

That's the whole point ;)

**Comment by nathanlesage** [comment]
I'm going to close this issue since I inadvertently implemented **both** changes over the weekend. Which means: (a) Wikilinks in the form `[[link|title]]` (or reverse) are now supported, and (b) I re-added Zettlr's ability of following the Logseq-style links in the form of `[title]([[link]])` (but they won't be detected as internal links when it comes to, e.g., generating related files)

**Comment by chiphogg** [comment]
I'm using 3.1.1 now.  The smoother navigation is a tremendous upgrade!  Thanks so much for doing this.
