### ISSUE TITLE
File manager sometimes opens the wrong file (Nightly)

### ISSUE THREAD

**Issue by jgsw** [Zettlr/Zettlr#4956]
### Description

On the latest NIghtly, I've found that the File Manager will often open the wrong file. You click on one file, and the File Manager opens a file in another directory.  This bug doesn't happen immediately - only after you've opened a few different files in different directories.  I particularly noticed it in Expanded and Combined mode.

### Reproducing

I haven't worked out exactly how to reproduce the bug. The File Manager works okay when Zettlr's first loaded. Something about opening a sequence of files in different directories seems to cause it. 

### Zettlr Version

Nightly

### Specify version

3.0.5 Nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by jgsw** [comment]
I don't seem to be experiencing this bug any more. Last week, I closed all my open files and all workspaces, then cleared the FSAL cache, and restarted. I don't think I've experienced it since. I'll report back if I do find a way to reproduce, but for now, it seems fixed for me.

**Comment by nathanlesage** [comment]
This should be fixed together with #4968!
