### ISSUE TITLE
No indication of which windows has focus under i3wm

### ISSUE THREAD

**Issue by Barabas5532** [Zettlr/Zettlr#4957]
### Description

It is clearly indicated when the Zettlr window has focus

### Reproducing

- Run Zettlr under [i3wm](https://i3wm.org/)
- Open a new window (CTRL+SHIFT+N)
- Move focus back and forth between the two windows

Notice that Zettlr does not indicate if it is focused, and it also doesn't draw the native i3wm window decorations. It is not possible to tell which of 2 Zettlr windows are focused.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5-2 from Arch Linux

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Arch Linux

### Additional Information

Installed from official `extra` Arch Linux repostiories, not AUR as available in the dropdown.

Suggested fixes:
- Grayscale the logo, or make the titlebar color darker when unfocused
- Re-enable the native i3wm decorations
- Change the accent color from green to  grayscale for unfocused windows

**Comment by Barabas5532** [comment]
This can be worked around by adding a line to the i3 config:

```
for_window [class="Zettlr"] border normal
```

This brings back native title bar with the correct focus indication, but wastes some vertical space, so I'll leave the issue open.

**Comment by nathanlesage** [comment]
That is precisely why you can enable window decorations on Linux in the preferences; I think advanced. @sensologica Would you mind having a look what specifically we could be doing to indicate focused / unfocused windows color wise? Once we have a clear list of things to change we can implement that.

**Comment by sensologica** [comment]
Lots of things to take into account here. Let's discuss and build a list of potential ways to address this.

Is this not automatically handled by the OS? Can we control styling based on whether or not a window is active? On MacOS, for example, there aren't any colorful elements in the toolbar that we can switch to grayscale, apart from the MacOS "stoplight" that are OS-specific window controls. Maybe we could use shadows or opacity or a dark overlay? To discuss.

@Barabas5532 could you please provide some screenshots to demonstrate what the two windows look like side by side on your system? I do not have a Linux environment available at the moment to examine this behavior myself. Thanks!
