### ISSUE TITLE
"Check for new version" button not clickable in 3.0.5

### ISSUE THREAD

**Issue by Mela** [Zettlr/Zettlr#4963]
### Description

If you open the "check for new version" window the button to check for a new version is not clickable. 

![Bildschirmfoto 2024-02-15 um 00 55 56](https://github.com/Zettlr/Zettlr/assets/361364/00dbbcc2-16e6-48b8-a668-065b6e12aff4)

### Reproducing

1. Click in the main menu on "help"
2. Click on "check for new version" 
3. In the new window try to click on the button

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.3.1 (23D60)

**Comment by nathanlesage** [comment]
I believe it is clickable, but if your internet connection and computer are fast, the update check will take only a few milliseconds. Is it that you wish that there was an indication that there is "No new update available" after clicking that button to have some visual feedback that the button in fact worked?

**Comment by Mela** [comment]
Maybe. I guess just a quick shade of the button to have a "yeah, that did something" would be sufficient.

**Comment by nathanlesage** [comment]
I see! I'll reclassify this as an enhancement as the button works as expected, but I absolutely understand what your issue with it is.
