### ISSUE TITLE
Project Glob Patterns are a Pain to Work with

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#4966]
### Description

I still am questioning my decision of being extra fancy and allowing for glob patterns to select which files (and in which order) will be included in a project export.

I just had to move around a bunch of files just to ensure that they weren't included because I literally had no idea how to appropriately adapt the glob patterns.

### Reproducing

Make a folder a project; apply some glob patterns to try to ensure that only the right files are exported. If you aren't completely careful, this will not work.

### Zettlr Version

Right off the develop branch

### Installation Method

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Sonoma 14.3.2

### Additional Information

Why did so few people complain about this …? Do y'all just not have encountered this issue, or don't you use the project feature …? 👀 

@sensologica Something you may want to take a stab at, since it's 99% user experience.

**Comment by sensologica** [comment]
Yes, let's discuss in detail during our next meeting
