### ISSUE TITLE
[beta 1.6] newly created  notes fulfilling search conditions are not displayed   in search view [bug/enhancement proposition]

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#497]
I am using Zettlr on Ubuntu 18.04

After creating a new note, the note is not visible in search view, even if it fulfills the search conditions (so this is an idea  for enhancement  - after creating a new note, the search view/results should be updated, if the new note  fulfill the search condition too)

**Comment by nathanlesage** [comment]
Ah, thanks for reporting! Never noticed that!

**Comment by danieltomasz** [comment]
in 1.6 after deleting note in search view, the note is still displayed  giving 
'The requested file was not found.'

**Comment by nathanlesage** [comment]
It did so before as well … the search is not as dynamic as it could be! I'll get to it with the new file system; it already makes progress!

**Comment by danieltomasz** [comment]
@nathanlesage Zettlr is developing in a cosmic speed, thank you for all your hard work!
I know that this is the same issue as before, and it waits for solving, but anyway I wanted to report it  so the other user could find info here

**Comment by nathanlesage** [comment]
Yeah, thanks for opening it up! This way it won't get lost while I work myself up from the bottom of the issue list! :D
