### ISSUE TITLE
Zettlr crashes when creating na ew file and copying parts of the name into the clipboard

### ISSUE THREAD

**Issue by gieselbusch** [Zettlr/Zettlr#4972]
### Description

If I create a new document using Ctrl+n, name it and copy the name (or parts of the name) via Ctrl+c, Zettlr crashes the moment I'm using a snippet or takes a lot of time if I try to generate an ID via Ctrl+l.

### Reproducing

Please see above.
Some times I'm able to use a snippet but then Zettlr also takes a lot of time for generating an ID.
If I don't use Ctrl+c in the file creating / saving dialog, I'm able to use snippets and generate IDs as much as I would like to.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian 12.1 (desktop: gnome)

**Comment by nathanlesage** [comment]
Would you mind trying out the new nightly that will be released tomorrow and see if this issue persists there as well? Thanks! You can find the nightlies here: https://nightly.zettlr.com

**Comment by gieselbusch** [comment]
Thank you. But the issue persists.

**Comment by nathanlesage** [comment]
I was just able to reproduce this issue on Manjaro, interesting.

So, the app itself is not crashing per se, but it suddenly becomes unresponsive for a few seconds. Running a performance check, we can see that there is a 12 second (in my case) system load applied that cannot be traced from the JavaScript debugger:

![image](https://github.com/Zettlr/Zettlr/assets/17251683/ec97a010-47e1-4ea0-b2b6-7c5aa4cbcd66)

Here in all its g(l)ory:

![image](https://github.com/Zettlr/Zettlr/assets/17251683/91f64099-8146-4d2b-8cd1-3101d67bab9b)

Once I copy something else from Zettlr, the behavior disappears again. If I copy something from the file save dialog again, the behavior consistently reoccurs (creating the file or not makes no difference). Looking at the clipboard, it is just normal text that's in there.

Interestingly, trying to paste the stuff into a file also takes an insane amount of time.

This means that there's something up with the clipboard access. This also explains why you can't really use snippets: Whenever a snippet is being inserted, the app will read the clipboard contents, and that is actually what takes so long.

However, I don't know what exactly causes this. I just tried pasting the same thing on Firefox and it works fine. So we know:

* Something makes Electron being unable to read the clipboard if the contents of it originate in the file save dialog of Electron
* The contents are always just plain text (`text/plain`), as expected
* Only the *originating* Electron app itself is affected
* Furthermore, other Electron apps are not affected by a copy from the same app (tried this with Discord and VSCode)
* Copying other pure plain text from somewhere else works fine
* The behavior is not limited to the main editor, I can't paste into regular text fields either
* **However** the behavior IS reproducible in other apps: I just forced VS Code to give me a save dialog, copied the file name, and tried to paste it into VS Code itself -- and it hung.
* However, pasting that into *other* Electron apps works again.

This means there's a bug somewhere in Electron itself. I'll file one.

**Comment by nathanlesage** [comment]
Issue is now filed: https://github.com/electron/electron/issues/41466

**Comment by gieselbusch** [comment]
Thank you for the time you put into this!

**Comment by nathanlesage** [comment]
You're welcome! Always happy to find a bug in Electron itself!

Also, I'm going to close the issue as it pertains to Electron – Zettlr will receive the fix as soon as Electron fixes that.
