### ISSUE TITLE
[HELP WANTED] Custom Mermaid.js Styling for Zettlr

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#498]
こんばんは、

I just finished initial implementation of Mermaid. I understand that this thing is huge, and that there is a lot of flexibility with regard to the charts. I personally don't use charts (maybe I'll start now since the option is there lol), which is why I would like to **ask for help**!

A lot of you have requested the Mermaid feature, and I've gladly implemented it, **but** it needs custom styling. This has actually been mentioned somewhere on Twitter I think (?), and it's necessary. Why? Because the built-in themes don't have night mode support. See proof:

![image](https://user-images.githubusercontent.com/17251683/73613099-783eb880-45f2-11ea-9159-187be66ff37b.png)

But I thought hey let's go one step further and provide a minimal base theme for that thing, using the Zettlr-internal colours and fitting the appearance into the app itself. Mostly, it should suffice that we define it *once* in the Berlin theme, because anything will propagate to the other themes. This would also enable users to further customise the styling using CustomCSS!

But **here's where you come in**: Do you use Mermaid in your daily work? Then I would like to ask you to share as many different things you can do with Mermaid so that I don't forget something and we can prevent bugs in the future!

The goal is to arrive at a full list of all things that need styling (elements, class names, and the like) and write two themes.

So in each of these steps, I gladly receive any help, whether be it deciding upon the actual styles, in sifting through the Mermaid themes to collect the info we need, or even coding the LESS into the stylesheet!

I'll be releasing another beta this week, which includes the basic mermaid support, and from then we can work together to make this happen!

Cheerio!

## Resources

- [Here is the link to all themes and styles that come with mermaid, which we need to override](https://github.com/mermaid-js/mermaid/tree/develop/src/themes)
- [This file is where we need to put the custom theme, except it's too big, then we need a new file. Look out for the class "mermaid-chart"!](https://github.com/Zettlr/Zettlr/blob/develop/resources/less/theme-berlin/light/codemirror.less)

**Comment by maehr** [comment]
Hi @nathanlesage 

I haven't used mermaid excessively yet. But here is a real example https://gist.github.com/maehr/55be6c49ac414f3ec464c2728026e56c
Till now I only used PlantUML. But I am going to ditch it in favor of mermaid and vega-light.

Cheers m

**Comment by nathanlesage** [comment]
Perfect, thanks! I'll include that in the test file! :)

**Comment by nathanlesage** [comment]
For now, I've opted for a background-color and a fixed theme simply so that the feature can be tested better. The theme can then be customised in further releases!

**Comment by Zverik** [comment]
Help still wanted, I guess. Mermaid charts still look alien to the UI. Removing the stale tag.
