### ISSUE TITLE
[ENHANCEMENT] Add Proxy Setting

### ISSUE THREAD

**Issue by akasolace** [Zettlr/Zettlr#499]
## Description

Trying to use Zotero with Zettlr.

I followed instructions from https://docs.zettlr.com/en/academic/citations.
I set for CSL-Style: dentistry-journal.csl  downloaded from Zotero

When trying to export the file as pdf I got an error message.

Is it possible to specify a proxy server ?

## Reproducing

Behind firewall, File export -> pdf with zotero citation

**Screenshots**

![image](https://user-images.githubusercontent.com/1136496/73672950-1cd20080-46ae-11ea-8b7a-f9543994d95c.png)

**Comment by nathanlesage** [comment]
It looks like you used the HTTPS-online link, right? Have you tried downloading the style and then pointing the engine to the offline version?

**Comment by akasolace** [comment]
> It looks like you used the HTTPS-online link, right?

@nathanlesage Yes I guess this is it: I downloaded the style I want to use from Zotero.
It is a csl file which content is available [here](https://www.zotero.org/styles/dentistry-journal?source=1)

> Have you tried downloading the style and then pointing the engine to the offline version?

I don't know where I can find a version of the csl that can be used offline. Do you have any idea ? 
Also for my info, does Zettlr works for such cls file that requires internet connection? I mean is it just a firewall issue or is it not a supported feature?

Thank you

**Comment by nathanlesage** [comment]
Try [this link](https://www.zotero.org/styles/dentistry-journal) and download the file. Then, point Zettlr in Preferences -> Export to the file.

**Comment by akasolace** [comment]
@nathanlesage  this is what I did (see below)

![image](https://user-images.githubusercontent.com/1136496/73849746-b9211200-482a-11ea-891e-e8743841d969.png)

**Comment by nathanlesage** [comment]
Eeh, so do I understand it correctly that the CSL file basically contains a reference to a URL which it cannot download?

**Comment by akasolace** [comment]
@nathanlesage  I managed to solve my issue by setting my proxy to the environment variable `http_proxy`  (see https://github.com/jgm/pandoc/blob/6a1476e7e26b603bb69112a2666c47ac883ee36f/src/Text/Pandoc/Class.hs#L496)

**Comment by nathanlesage** [comment]
Ah, so it was an issue with Pandoc. Thanks for reporting! :)

**Comment by akasolace** [comment]
> Ah, so it was an issue with Pandoc. Thanks for reporting! :)

Yes it is an issue with pandoc or at least it desserves a more descriptive error message.
Pandoc looks for proxy information by getting environement variable `http_proxy` if it does not find it it assumes there is no proxy. In my case I need to go though a proxy but that variable was not set. It took me a bit of time to see what was wrong ...

**Comment by nathanlesage** [comment]
Ah, alright. You could, of course, try to induce the proxy variable by prepending it to the pandoc command in the Advanced tab (Preferences window); on macOS and Linux something like this could work:

```
$ export http_proxy=192.168.0.1 pandoc [here follows the rest of the pandoc command]
```

**Comment by akasolace** [comment]
> You could, of course, try to induce the proxy variable by prepending it to the pandoc command 

yes this works

Also note that for the same reason I can't upgrade via the app (firewall blocking it) but it works if I launch zettlr from the command line and set the proxy variable at launch time.

  maybe you want to introduce a proxy support within Zettlr ....

**Comment by nathanlesage** [comment]
> yes this works

Perfect.

> maybe you want to introduce a proxy support within Zettlr ....

This would be an idea, albeit it will ONLY work with Zettlr itself, still not Pandoc obviously, because different program, different process, therefore different network stack. Feel free to open an issue for this!

**Comment by akasolace** [comment]
> This would be an idea, albeit it will ONLY work with Zettlr itself, still not Pandoc obviously, because different program, different process, therefore different network stack. Feel free to open an issue for this!

Considering the proxy can be set by the command line, it should work no ?
If Zettlr had a setting to set proxy, it can use the proxy for fetching update, but it could also prepand the pandoc command with appropriate proxy information .....

**Comment by nathanlesage** [comment]
Fair point!
