### ISSUE TITLE
document frozen with no cursor until toggle of Light / Dark mode. WIN11, Bielefeld

### ISSUE THREAD

**Issue by digbyphonic** [Zettlr/Zettlr#4997]
### Description

windows 11; latest version, Bielefeld theme.

i have found an issue when opening a file in a new tab where the document is unresponsive.
no flashing cursor and usually coloured highlight text is unhighlighted.

i've stumbled upon a fix instead of re-opening the program: toggling Light / Dark mode immediately displays the expected flashing cursor and allows work to continue.

### Reproducing

i am unable to reliably cause the issue to occur.
but when it does the solution described above works.

### Zettlr Version

Stable (most recent version)

### Specify version

3.05

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

windows 11 Pro 23H2

**Comment by nathanlesage** [comment]
This has nothing to do with the theme or something, but rather that something in the provided file doesn't work — that has been a bug that I have fixed a few weeks ago, it should be fixed in the nightly!
