### ISSUE TITLE
Forward Backward Navigation

### ISSUE THREAD

**Issue by GavriYashar** [Zettlr/Zettlr#50]
It would be nice to have forward and backward navigation keys (mouse forward/backward)

**Comment by nathanlesage** [comment]
Do you mean Redo/Undo or File Forward/Backward?

**Comment by GavriYashar** [comment]
When navigating through a library of files (file1, file2, file3...) it would be nice to just press mouse backward button to open/jump to previous files (fileN, fileN-1, fileN-2...). Mouse forward to open/jump to next file in this "history" (fileN-2, fileN-1, fileN).

**Comment by nathanlesage** [comment]
So you mean you have two special buttons on your mouse that you want to use for this?

**Comment by GavriYashar** [comment]
These are no special buttons. It's just a common and cheap 5-Button mouse. Also it doesn't have to be a mouse only feature, could be a keystroke as well.

**Comment by nathanlesage** [comment]
Yes, these are special buttons. We live in an era where most people have turned to Laptops which only feature left, right and scrolling — most not even a middle mouse button.

What I could offer you (without guarantee as to the "when") would be a preferences area with some arbitrary commands where you could define keystrokes for triggering those actions. Then these actions are not hard-coded and you can decide what you want to use for them.

**Comment by GavriYashar** [comment]
Sounds good.
`when`: of course. as you see fit.
