### ISSUE TITLE
Color issues in dark mode in typewrite mode

### ISSUE THREAD

**Issue by tkeiderling** [Zettlr/Zettlr#5006]
### Description

In typewriter mode in Windows in version 3.0.5 the colors blur out the text so that it is impossible to read it. 

### Reproducing

In the latest stable version on Windows, enter typewriter mode. 

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5 x 64

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

### Additional Information

![image](https://github.com/Zettlr/Zettlr/assets/90908474/62b147df-6129-482d-9ea2-8f8968cf0271)

**Comment by nathanlesage** [comment]
That is not blurring – I forgot to adapt the background color of the active line in the 3.0 release. Fortunately, that has been fixed and has shipped with the most recent beta.

**Comment by tkeiderling** [comment]
![image](https://github.com/Zettlr/Zettlr/assets/90908474/08c80a49-9444-461e-a1c6-328b203e1507)

**Comment by tkeiderling** [comment]
Similar issue in the preferences screen in latest beta.
