### ISSUE TITLE
Paste Image Hangs.. most times - Zettlr Version 3.0.5 (3.0.5), MacOS Sonoma 14.3.1 (23D60)

### ISSUE THREAD

**Issue by jduprey** [Zettlr/Zettlr#5007]
### Description

When I paste an image from clipboard, oft times it hangs - spinning beachball.  I have to force quit... sometimes pasting again will work, other times not.  I've resorted to NOT trying to paste - instead putting image in relative local assets folder, then dragging and dropping it in.  Its very reproducible for me.  If someone can tell me how to capture logs for this, I'll provide more info.

### Reproducing

`<cmd>-v` and image from clipboard.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS Sonoma 14.3.1 (23D60)

**Comment by nathanlesage** [comment]
This has to do with the fact that apparently the document is not focused; I just could reproduce the issue and received an exception in the console. I'll have to look into it.

**Comment by jduprey** [comment]
Thank you @nathanlesage .  Do I download the nightly to get this fix?  Or what is the best place to get it?

**Comment by nathanlesage** [comment]
Yes. I'll release another beta probably next week. Until then, the nightlies are your friend.

**Comment by jduprey** [comment]
Thank you so much!
