### ISSUE TITLE
Unable to collapse top open folder in files manager

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#5008]
### Description

![Recording 2024-03-03 at 10 05 47](https://github.com/Zettlr/Zettlr/assets/103963891/90f8a0cd-2443-4c02-a3ca-d4f08977845d)

### Reproducing

Click over documents and folder and observe that collapse can't be done.

### Zettlr Version

Stable (most recent version)

### Specify version

3.1.0-beta

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

Clicking area to collapse is no longer 'file-manager-wide' in 3.1.0-beta

**Comment by Mela** [comment]
Ran into a similar problem on Mac, but didn't look deeper into it.

**Comment by nathanlesage** [comment]
You can close the directory by pressing the button a few times. Somehow the directory gets pushed into the corresponding array that manages these open directories multiple times, and per click on the arrow button, one of these entries is removed. As soon as no entry remains, the directory will close.

I need to get back to this at some point, but this is the workaround for now.

**Comment by nathanlesage** [comment]
Okay, somehow the bug disappeared after a ton of cleaning up yesterday and today. Should it return, feel free to complain again
