### ISSUE TITLE
Lost icons bar fixed width

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#5009]
### Description

There is a visual issue with the icon bar when viewed on wide monitors. The icon bar has lost its fixed width, and as a result, the icons are not adjacent to each other. This spacing issue causes the icon bar to look unsightly on wider screens.

![image](https://github.com/Zettlr/Zettlr/assets/103963891/6236da06-2106-4080-91d5-f6bf0e6f29d3)

The expected behavior is for the icon bar to maintain a consistent layout, with icons closely aligned, regardless of the screen width.

### Reproducing

Layout issue.

### Zettlr Version

Stable (most recent version)

### Specify version

3.1.0-beta

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
This was caused due to a few refactorings; I personally liked that because it looked a bit less cluttered, which is why I didn't change that.
