### ISSUE TITLE
[ENHANCEMENT] YAML front matter comments

### ISSUE THREAD

**Issue by maehr** [Zettlr/Zettlr#501]
## Description

Inside YAML front matter Zettlr renders comments `# comment` as ATX-Headers.

## Proposed Changes

Do not render headings inside YAML codeblocks/front matter.

## Caveats

I think there is none.

## Additional Information

**Example (fenced)**

```markdown
---
title: Example
# abstract: "There sure will be an abstract one day."
keywords: stuff # add more keywords if you must
---

# Heading 1

Text text...
```

**Example (not fenced)**

This example does not work on GitHub because `---` is rendered as a line.

---
title: Example
# abstract: "There sure will be an abstract one day."
keywords: stuff # add more keywords if you must
---

# Heading 1

Text text...

**Comment by nathanlesage** [comment]
Thanks for reporting! Hopefully this'll make it into 1.6!

**Comment by nathanlesage** [comment]
Sooo, I just rewrote the mess concerning the mode cascade into another mess, but now the YAML mode is correctly detected in the frontmatter, meaning:

- MagicQuotes are disabled there (-> string escaping)
- AutoCorrect won't trigger (-> no `---` to — conversion)
- Comments will work, obviously

Basically: It now works as it is supposed to be :D

**Comment by stites** [comment]
I think I was just about file a related issue -- thanks for being on top of this!
