### ISSUE TITLE
Went blank when rendering $\text{...}$ and inspecting element simultaneously

### ISSUE THREAD

**Issue by LukeBriton** [Zettlr/Zettlr#5010]
### Description

Zettlr went blank when it's rendering `$\text{any\ text\ here}$`, or with `textit`, `textbf`, `textrm`, `textsf`, all of them has the problem here: when I want to inspect element (through the menu or using DevTools), Zettlr just went blank (black for me using Dark Theme). Still DevTools seems work, but with msg like this:
![image](https://github.com/Zettlr/Zettlr/assets/9190294/8057b934-ed73-4728-b394-8d2c824a4012)

And the reason why I point out "rendering", is that situation like below just works fine, when the text in `$\text{any\ text\ here}$` is divided into two lines:
![image](https://github.com/Zettlr/Zettlr/assets/9190294/1e00d9c3-d909-4efd-aa90-e9cc83c25229)

Besides, `mathbb`, `mathtt`, `mathit` as I test don't seem to have this problem.

### Reproducing

In a .md, with any code as easy as:

```Markdown
$\textit{debug}$
```
Make sure it's rendered, then Menu>Develop>Inspect Element.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 19042.1237

**Comment by nathanlesage** [comment]
Does it at least render properly? Or is the rendering also broken?

**Comment by LukeBriton** [comment]
Yeah it renders OK.

**Comment by LukeBriton** [comment]
Thanks for checking it. My OS doesn't seem to support the latest beta version of Zettlr (I don't know whether this is because of my OS version or a bug, if the latter I may have to open another issue), so I tried it on my vm Fedora 36. It seems in 3.0.5 on Linux the problem also happens, but in 3.1.0 it's okay. So I guess it's fixed in the beta version.

**Comment by LukeBriton** [comment]
Oh, 3.1.0 can be used now on my Windows 10, strange. But anyway it's good that it got solved. Thanks for your efforts. 🎉

**Comment by nathanlesage** [comment]
Perfect, thank you very much for double-checking this issue!
