### ISSUE TITLE
Placing a Table Caption directly beneath a table makes it impossible to save changes via the TableEditor

### ISSUE THREAD

**Issue by Mela** [Zettlr/Zettlr#5011]
### Description

Table editor does not save table after change

![Bildschirmfoto 2024-03-04 um 23 04 12](https://github.com/Zettlr/Zettlr/assets/361364/e45defbe-0408-4e5c-af5e-3e0aaa5fbf71)

### Reproducing

I've created a table using [Tables Generator](https://www.tablesgenerator.com/markdown_tables#). After copying the finished table into Zettlr I've added a caption to the table, using ": Bla bla bla". This first change was saved. When adding more text to the caption, the change was not saved and the "save icon" stayed red. 
.

### Zettlr Version

Beta (if applicable)

### Specify version

Version 3.1.0-beta (3.1.0-beta)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma: 14.3.1 (23D60)

### Additional Information

Clicking on the save icon produces an error in the logfile: [22:58:22]
[R] [Main Window (8862ae86-88d9-40b5-a97b-67bf02289ebc)] Uncaught TypeError: Cannot read properties of undefined (reading 'length') (index.js:2)

**Comment by nathanlesage** [comment]
Huh, this looks like a bug if the parser recognizes the caption as part of the table (which it shouldn't do) 👀 

The error is likely because the caption would appear to only have one cell instead of however many columns you have in that table.

**Comment by Mela** [comment]
I wondered why it displayed the caption as part of the table. But since it looked in the output as it should, I didn't question it further.

**Comment by nathanlesage** [comment]
Does it work correctly if you explicitly make sure there's an empty line between the table and its caption?

**Comment by Mela** [comment]
Yes. It works. 

![Bildschirmfoto 2024-03-07 um 05 36 19](https://github.com/Zettlr/Zettlr/assets/361364/cb2620a6-9b3b-41de-ba98-762edc0b8181)


![Bildschirmfoto 2024-03-07 um 05 34 52](https://github.com/Zettlr/Zettlr/assets/361364/b9ab54e8-fefd-44d6-9ba3-19bce75b79f3)

**Comment by nathanlesage** [comment]
Perfect. I'll have to see if there is something afoul with Zettlr, or if this is a bug that Marijn has to fix. For now, the workaround seems to be simple, so I'm not going to prioritize this too much for now, but I'll keep the bug open with an amended title.

**Comment by nathanlesage** [comment]
I just looked up how table captions are supposed to work: There's nothing wrong with the parser, table captions are required to be placed with one empty line in between, so directly attaching them to the table won't work, and isn't intended to.
