### ISSUE TITLE
Text before or after image is deleted while/after editing alt text of image

### ISSUE THREAD

**Issue by stephankoe** [Zettlr/Zettlr#5021]
### Description

Recently, I am writing a Markdown document with a few pictures and text in-between. To make the document more accessible, I provide an alt-text to every image. Zettlr displays a text box below the image to edit the alt text of it. When entering text into this text box, Zettlr will put the alt text into the square brackets as well as a quoted copy behind the image path. Before and after every image, I leave an empty row. My document is for example:

```markdown
Culpa maxime impedit magnam accusantium quibusdam quae amet quis hic cum.

![Alt text here](./img/image.svg "Alt text here")

: Consequuntur labore quo animi.

Reiciendis distinctio vel architecto, iusto perspiciatis nulla sint expedita repellendus velit possimus eos illum sit?

![Alt text 2 here ](./img/image.svg "Alt text 2 here")

: Voluptatem quia aspernatur accusantium vitae earum.

Deserunt id dolor, neque expedita commodi suscipit eligendi nostrum debitis facilis maxime iure error.
```

After having edited already existing alt text and leaving the text box by clicking somewhere else or moving the cursor with the keyboard, it occasionally happens that Zettlr highlights the text starting from the next image's closing bracket `)` up a few lines. In other occasions, a big portion of the text between these images is deleted and a part of the alt text of the above image is copied into the region after the first image's closing bracket. Once I even got another copy of the below image within the text in between the images. My alt text consists of alphanumerical characters with common punctuation, excluding quotation marks. These issues appear frequently, yet seem quite random.

The changes made to the document cannot always be reverted with CTRL+Z. Hitting CTRL+Z or Undo will revert the alt text, but deleted text doesn't come back.

It appears that Zettlr's logic to insert the alt text into the markdown document selects the wrong location. It may have something to do with documents with multiple images.

### Reproducing

This issue describes a set of different, yet connected problems that occur during editing the alt text of images. Zettlr appears to exhibit these issues randomly -- sometimes, changing the alt text (insert, delete) does not affect the surrounding text, sometimes the same actions do. Hence, I wasn't able to reliably reproduce these issues in a way that I can make any action-effect relation. However, these issues appear frequently, so randomly changing the alt text of the two images in above example document will exhibit these issues.

I observe this issue in the Flatpak version 3.0.3 and the most current AppImage version 3.0.5. If needed, I can provide screen recordings.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 23.10

**Comment by nathanlesage** [comment]
First of all, thanks for this very elaborate description of the bug, it was very easy to understand what the problem is. Then: I know that there have been bugs with this selection logic, and it might be that this one has slipped away until now. I'll see to reproducing this issue and then get back to you.

**Comment by stephankoe** [comment]
Ok. When there's anything, I can do to assist in reproducing, I'll be happy to help.
