### ISSUE TITLE
Table Editor is not supporting blank cells / empty cells

### ISSUE THREAD

**Issue by jimbrewer1** [Zettlr/Zettlr#5025]
### Description

This is a non-critical bug.

# The Table Editor no longer supports empty cells correctly.

## Two related symptoms:

1. An empty table is not rendered at all by the Table Editor. This would be the case anytime a table is created/inserted using the icon in the toolbar. The structure of the markdown for the empty table is generated, but the Table Renderer does not recognize it as a table.
This error is logged when trying to render an empty table:
`[R] [Main Window (dc151fd9-b173-496c-b61f-757333c70d7f)] Error: Could not instantiate TableEditor widget: Cannot instantiate TableEditor: Table had zero rows. (index.js:2)`

2. In a table that has some cells filled and some empty, filled cells are rendered left to right, skipping any blank cells. Entire empty columns are skipped. Entire empty rows are skipped.
Each cell in this table identifies its column and row. The rendered content is packed left to right, Row 3 is missing, and Col 3 is missing.
<img width="612" alt="Screenshot 2024-03-12 at 1 17 00 PM" src="https://github.com/Zettlr/Zettlr/assets/47892155/1ed6b9bd-b8b4-4dcd-af72-21375c301c2a">

I don't see errors in the logs for a partially filled table.

### Reproducing

1. Use the table icon in the toolbar to select to create a 4x5 table. That will generate this markdown for an empty 4x5 table as expected, but the Table Editor doesn't render it. The table size is not of importance. 

```markdown
|  |  |  |  |
|--|--|--|--|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
```

2. Type content directly to the table markdown.
```markdown
| Title Col 1 | Title Col 2 |  | Title Col 4 |
|--|--|--|--|
| Row 1 Col 1 | Row 1 Col 2  |  | Row 1 Col 4 |
| Row 2 Col 1 |  |  | Row 2 Col 4 |
|  |  |  |
|  | Row 4 Col 2  |  |
```
As long as one cell has content, when you leave the table markdown (arrows on keyboard or click elsewhere), the table renders. Blank cells are not rendered correctly. The rendered cells that contain content fill from left to right.

This is how the Table Editor renders that markdown:

<img width="616" alt="Screenshot 2024-03-12 at 1 30 50 PM" src="https://github.com/Zettlr/Zettlr/assets/47892155/2711e92a-0904-4d3b-b216-e6e938996b99">

And for reference, this is how GitHub renders it:

| Title Col 1 | Title Col 2 |  | Title Col 4 |
|--|--|--|--|
| Row 1 Col 1 | Row 1 Col 2  |  | Row 1 Col 4 |
| Row 2 Col 1 |  |  | Row 2 Col 4 |
|  |  |  |
|  | Row 4 Col 2  |  |

I did not attempt to edit the content in the Table Editor and save.

### Zettlr Version

Beta (if applicable)

### Specify version

Release v3.1.0-beta

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Sonoma 14.3.1

### Additional Information

I obtained Release v3.1.0-beta through the updater within the application. I downloaded from there, then closed zettlr and installed by double clicking the dmb and dragging the app into applications. 

As mention in the description, this error is logged when attempting to render an empty table.
`[R] [Main Window (dc151fd9-b173-496c-b61f-757333c70d7f)] Error: Could not instantiate TableEditor widget: Cannot instantiate TableEditor: Table had zero rows. (index.js:2)`

I'm not aware that errors or warnings are logged when rendering a partially filled table.

**Comment by Mela** [comment]
Ran into this problem, too.

**Comment by niklasliebig** [comment]
I still have found some errors in this context when using 2 empty cells next to each other (version 3.2.3).
Markdown:
```
|  1 | 2 | 3 | 4 |
|--|--|--|--|
| 1 |  |  | 4 |
|  |  | 3 | 4 |
| 1 | 2 |  |  |
```
Visualisation in Zettlr:
![image](https://github.com/user-attachments/assets/a309a97f-3497-463a-bc30-94d972fdb909)

As you can see, the contents of the cells are moved to the wrong columns. The correct table would look like:
|  1 | 2 | 3 | 4 |
|--|--|--|--|
| 1 |  |  | 4 |
|  |  | 3 | 4 |
| 1 | 2 |  |  |
