### ISSUE TITLE
Update default number-sections settings according to new behaviour pandoc.

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [Zettlr/Zettlr#5029]
### Description

Previously in Pandoc there was [an issue](https://github.com/jgm/pandoc/issues/5071) which meant that headings would show up as 0.1, 0.2 etc. when `number-sections` was set in the frontformatter. The issue has been [resolved](https://github.com/jgm/pandoc/commit/03bb426a4a65918bfd6fbd63d5bb32a657df5568), but the "fix" is still in the default frontformatter, so it now introduces a bug.

This
```yaml
number-sections: false
number-offset:
- 0
- 0
- 0
- 0
- 0
- 0
shift-heading-level-by: 1
```

Can now just be set to this:
```yaml
number-sections: false
```

### Reproducing

See mentioned issue

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

N.A

**Comment by nathanlesage** [comment]
Three questions:

1. Do i understand correctly that we should remove two of the three properties that you removed in the second code block?
2. Can you provide example outputs for both settings?
3. Would you mind opening a PR with these changes?

**Comment by TeaDrinkingProgrammer** [comment]
Hi there!
1. Yes, that's right
2. I can do that
3. I'll look into opening a PR-request some time soon.

**Comment by nathanlesage** [comment]
Amazing, thank you!

**Comment by TeaDrinkingProgrammer** [comment]
So I have done some more digging, and these are my findings.

On Zettlr X, XeLaTex X and Pandoc X, when you take the XeLaTeX PDF template and change `number-sections` from `false` to `true` and generate a PDF from this MD file:
```
---
title: "Test"
---
# Chapter 1
## Chapter 1.1
### Chapter 1.1.1
# Chapter 2
# Chapter 3
## Chapter 3.1
```
You get this:
![image](https://github.com/Zettlr/Zettlr/assets/20358521/3733d86f-7982-49cd-8af7-cd9bc80279b1)


When you change the base config and remove:
```
shift-heading-level-by: 1
```
And then change `number-sections` from `false` to `true`. This is the result:

![image](https://github.com/Zettlr/Zettlr/assets/20358521/a45d6cf7-8d52-466b-b3f9-ea0868726cc3)


The [`number-offset`](https://pandoc.org/MANUAL.html#option--number-offset)  flag doesn't seem to change anything after all. It doesn't do anything at all in PDF per definition, but in HTML it also doesn't seem to matter so the problem is solely with the `shift-heading-level-by` flag.
