### ISSUE TITLE
Zettlr 1.5.0 - AutoCorrect cannot be disabled.

### ISSUE THREAD

**Issue by odkr** [Zettlr/Zettlr#503]
## Description
When I disable "Turn on AutoCorrect" and click "Save", then when I enter, for instance, "-->" in the editor, it's Zettlr still replaces it with "→". When I re-enter the preference dialogue, "Turn on AutoCorrect" is again shown as enabled. 

## Reproducing
1. Disable "Turn on AutoCorrect".
2. Click "Save"
3. Enter "-->" or re-enter the preferences.

## Expected behaviour
Disable AutoCorrect.

## Platform
 - OS and version: macOS v10.14.6 (18G2022)
 - Zettlr Version: 1.5.0

**Comment by nathanlesage** [comment]
This has already been reported, and also was fixed in the 1.6 beta!

**Comment by odkr** [comment]
Sorry, my bad. I forgot to check for closed issues.

**Comment by nathanlesage** [comment]
No problem!
