### ISSUE TITLE
Image pop-up for internal note links

### ISSUE THREAD

**Issue by ice7512** [Zettlr/Zettlr#5041]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Provide an option to enable images to be rendered in the pop-up file preview.
Currently the file preview for internal notes looks like this when there is an image at the top of a note

![zettlrImage](https://github.com/Zettlr/Zettlr/assets/66206256/e656ec1c-19c6-499c-b02d-e42985a457e7)

I would like it to look like this:
![image](https://github.com/Zettlr/Zettlr/assets/66206256/66b8d1b8-8fd9-4cb0-a0f8-02bd96b05cdb)

### Example Workflow

**Motivation**
Recently was thinking about when I look for old articles on news websites or when I search for music online , the main thing that helps me recognise it's the right piece of info is the thumbnail or a large associated image. For example, when I'm searching for a specific piece of music on SoundCloud or YouTube, I use the thumbnail to recognise if it's the right song (or album) first before I read the text. The large image that's usually at the top of an article helps me remember what the article is about.

**Experimentation**
I started to put images at the top of my notes a few days ago, and it made it far easier to recognise my notes when I got to them. In fact, when I thought about my system of notes, it was much easier to recall the notes that that had an image at the top of them. However, I thought, when navigating my notes, **wouldn't it make more sense to be able to know that it's the right note by just hovering my mouse over the link to it?**

**Workflow**
Whether you are a designer, writer or researcher, being able to navigate your notes with **ease** and **reliability** is of the utmost importance. Hence, if you are using Zettlr, you probably already understand that. However, as a project of any kind grows larger, notes that become disused become difficult to navigate back to and find just by recognising text. By allowing the user to hover over an internal note link to an image, they can more **easily**, **reliably** and **confidently** _identify_ notes that have become slowly disused.

Where do you get the images from you ask?
Well what I do, is I search up a word or key word that's in the note and then I just put that into google image search or Pinterest. Then I copy an image and then paste it at the top of the note. That's all there is to it.

### Caveats

The image may end up pushing away most of the text out of the pop-up file preview (as seen in the feature proposal image). **However,** that's why I say it should be an **option** that the user can turn on our off.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [ ] macOS
- [ ] Linux

### Additional Information

I am willing to work on this, but I don't have the time to right now, maybe in a month or so.

**Comment by nathanlesage** [comment]
This is actually a bug in the Markdown parser, I'll see to it.
