### ISSUE TITLE
Unconfuse Save Unsaved Changes Dialog

### ISSUE THREAD

**Issue by dm5n** [Zettlr/Zettlr#5042]
### Description

This is the save dialog box that pops up if user attempts to exit app with unsaved changes:

![Screenshot 2024-03-17 at 17 29 41](https://github.com/Zettlr/Zettlr/assets/5894141/4b9c5025-1920-40b6-a8d6-3c4ce5bf8c3e)

### Reproducing

Try to exit app with unsaved changes

### Zettlr Version

Nightly

### Specify version

Version 3.1.0-beta-nightly (3.1.0-beta-nightly)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.3.1

### Additional Information

Perhaps change options to (1) Save Changes and (2) Exit Without Saving?

**Comment by nathanlesage** [comment]
You have set en-GB as your locale correct?

**Comment by dm5n** [comment]
Do you mean Settings > General > Application Language? It's set to English (UK)

**Comment by nathanlesage** [comment]
Knew it. I haven't updated the UK English translation in a while and gettext sometimes tries to fuzzy-match novel translation strings. I still have to figure out how to stop it from doing that.
