### ISSUE TITLE
custom internal link markers do not work

### ISSUE THREAD

**Issue by Jnath-alf** [Zettlr/Zettlr#505]
## Description
Customizing internal link markers makes internal links ineffective. Linked notes do not open.

## Reproducing
Go to Preferences / Zellelkasten => Link start and Link ending, and change the default values, namely “[[” and “]]”.

## Expected behaviour
All types of characters are accepted as markers; so internal links other than [[ID]] should also open the linked note.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: Zettlr 1.6.0-beta (the problem also existed on 1.5.0)

## Additional information
For example “{{” and “}}” instead of “[[” and “]]”; the links are then written {{ID}}.

1) The link is clickable but does not open the linked note; Zettlr exports “{{ID}}” to the search bar, instead of just exporting “ID”.

2) Typing "{{" does not open the list of addable links; on the other hand, typing “[[” continues to open it (although the marker “[[” should now be inoperative).

In addition, there is a problem updating the change of markers, in case the changed link is written before making the change in preferences.

For example, I first write a link using a new marker: [§ID], then I change in the Preferences Zettelkasten Link start for “[§” and Link ending for “]”. I save and return to the note, but the link is not clickable. If I write a new link [§ID], the latter is clickable, but the former remains inactive. If I open another note, and go back to the previous note, then the link that was inactive is now clickable.

But Zettlr exports “§ID” in the search bar, instead of “ID”, and the link does not open the linked note.

This seems to apply to all characters other than Square brackets.

Note that a link between single square brackets [ID] opens the linked note, like links between double square brackets [[ID]]. Zettlr exports “ID”, not “[ID]” in the search bar. However, typing "[" will not open the list of addable links, only "[[" remains efficient in this case.

**Comment by nathanlesage** [comment]
Thanks for opening the issue! I just had a look at the source code and immediately found at least one instance, where `[[` as link opening is hardcoded into the source, which is not what we want. I'll get to it!

**Comment by nathanlesage** [comment]
Hey, so I think I fixed all of that now. While doing so, I found some logical bugs, very old remnants and in general cleaned that mess up :D

So now it should work out of the box with whatever links you want, and in addition the link starts and ends are now even slightly transparent, fully in line with the formatting characters of emphasised and bold text, so it's even nicer now!

Tomorrow I'll release yet another beta, and hopefully it's going smoothly then :)
