### ISSUE TITLE
[macOS] The menu entry paste without styling doesn't work

### ISSUE THREAD

**Issue by obitwrite** [Zettlr/Zettlr#5052]
### Description

Pasting without styling via the Edit menu doesn't work.
The shortcut SHIFT+COMMAND+V does work.

### Reproducing

A quick reproduction of the bug on macOS:
* Create a new file
* Copy some text from any source (LibreOffice, TextEdit, Firefox, doesn't matter)
* Go to the menu entry: Edit > Paste without styling (I'm using the Dutch translation, so might say something slightly different in English)
* Result: No text is pasted
* The shortcut SHIFT+COMMAND+V does work.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura

**Comment by nathanlesage** [comment]
Good news: It works with the current betas (or, at least the current dev branch), so the fix will come eventually!

**Comment by obitwrite** [comment]
Those are the best bugs: the ones that already have a solution. Thanks @nathanlesage !

**Comment by obitwrite** [comment]
Just an addition: it doesn't work in v3.1.0-beta.1 – but perhaps it does in the nightly / dev branch.

**Comment by obitwrite** [comment]
Unfortunately the bug isn't fixed yet @nathanlesage 

Clicking 'Paste without styling' still doesn't work in v3.1.0-beta.2.

The keyboard shortcut does work (and has always worked). But clicking the menu item does nothing.

**Comment by obitwrite** [comment]
Tested in the Zettlr v3.1.1, this still doesn't work.

I know you closed this @nathanlesage assuming it was fixed, but on my setup it just doesn't work. Could we perhaps re-open this issue?

**Comment by obitwrite** [comment]
Thanks for reopening, if you need me to check or test anything, let me know.

**Comment by obitwrite** [comment]
Retested in v3.2.0 – not working.

**Comment by nathanlesage** [comment]
There's likely just a wrong path that's taken so that the menu item doesn't work. It shouldn't take too long, but I'll have to trace what's happening with the menu item, and for that I need a bit of free time; I'll get to it hopefully soon!

**Comment by obitwrite** [comment]
Thanks @nathanlesage – I am aware of all the time you put into Zettlr, so I'm never in a rush. Too bad I'm not a programmer/developer myself :-). I can however help by doing these bug reports, and do some testing to make Zettlr a polished experience!
