### ISSUE TITLE
Internal links get exported if on a multiple elements' bullet list

### ISSUE THREAD

**Issue by chlodowich** [Zettlr/Zettlr#5053]
### Description

Hello! I have been using Zettlr for a bit, loving it so far. I have encountered an issue however that seems a bit mysterious.

Whenever I export to html, xetex pdf or simple pdf, internal links in bullet lists are visible, while the expected behaviour is for them to disappear like they normally do in paragraphs.

The only solution I have found so far is to add a new line after every single bullet element; however, this adds quite an amount of unecessary spacing.

Edit: forgot to add that the option "remove internal links completely" is selected in the "Export.." preferences section.

### Reproducing

To demonstrate, here's the text I've used:

``` 
# Test

This is a test to demonstrate that [[20240322092930]] **internal links** of normal paragraphs do not appear when exported (expected behaviour). However, this is not the case if they are inserted in a list:

* [[20240322093115]] this link and the ones after it do appear in the exported file.
* cause seems unknown and it does not matter wheter they are at the start or the end of the bullet point line [[20240322093432]]
* [[20240322093028]] line 3
* line 4 [[20240322093057]] 
```

Here's what my Zettlr editor looks like:

![Schermata_20240322_094946](https://github.com/Zettlr/Zettlr/assets/164070649/894359d2-243f-4560-ab7d-14ed0a1dfb8a)

Here's what is shown if I either press ctrl-p or export through xetex/simplepdf:

![Schermata_20240322_094902](https://github.com/Zettlr/Zettlr/assets/164070649/85626d5e-6670-42d7-b12b-7b5c42796325)

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation 

AppImage from the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE Tumbleweed

**Comment by chlodowich** [comment]
I've just found the same issue mentioned here, even though it's marked as closed: https://github.com/Zettlr/Zettlr/issues/3171

**Comment by nathanlesage** [comment]
This is very likely a new bug in the corresponding Lua filter.

I am planning on removing that filter and not fixing it anymore. It stems from a time when Pandoc didn't support Wikilinks.

Now, with the appropriate settings, Pandoc will automatically detect such wikilinks, and you can then filter them out, if you want to, but they will be properly parsed now. Just remember to use the appropriate Markdown extension.

(See the CHANGELOG.md at the root of this repository, it contains some explanations).

**Comment by chlodowich** [comment]
> This is very likely a new bug in the corresponding Lua filter.
> 
> I am planning on removing that filter and not fixing it anymore. It stems from a time when Pandoc didn't support Wikilinks.
> 
> Now, with the appropriate settings, Pandoc will automatically detect such wikilinks, and you can then filter them out, if you want to, but they will be properly parsed now. Just remember to use the appropriate Markdown extension.
> 
> (See the CHANGELOG.md at the root of this repository, it contains some explanations).

Thank you! I took a look at the changelog but I had some difficulty finding the information I was looking for. Sorry to bother, but would it be possible to have a practical example as to where to filter out wikilinks through pandoc settings?

Also, what do you mean by «Just remember to use the appropriate Markdown extension»?

**Comment by nathanlesage** [comment]
The extensions are `wikilink_title_before_pipe` or after (somewhere at the top of the changelog), and for filtering out you'll need to write your own Lua filter. The Pandoc manual has a ton of documentation on that. I plan on improving the filter experience with Zettlr somewhere in the future when I have more time.

I can always recommend our [Discord](https://go.zettlr.com/discord), where you will find many people who can help you.
