### ISSUE TITLE
Tabular Data is Not-Saved/Deleted

### ISSUE THREAD

**Issue by BCHarker-OCT** [Zettlr/Zettlr#5056]
### Description

When working with tabular data I have noticed that data in my tables is getting completely wiped. I had an issue when I would also remove whitespace above the table and it would also delete all contents in the table. 

### Reproducing

**System Information:** 
Use Zettlr Version: Version 3.0.5 (3.0.5) 
Use macOS Sonoma 14.2.1 (Apple silicon)

**Method 1:** 
1. Create a table using the GUI table dialog
2. Populate the table with contents 
3. Navigate to another document 
4. Return to the original document with tabular data
5. All of the tabular data is now permanently erased 

**Method 2:**
1. Create a new document 
2. Use the following Markdown template (must be implemented in Zettlr itself, not setup in a file and saved outside of Zettlr, or the data is saved, see notes below)

```test.md
#  Document


|  Data| Data  |
|--|--|
|  Data  |  Data  |
|  |  |
|  |  |
```
3. Remove or add a line break before the table, or do practically anything and the data gets wiped out from the GUI view.
4. Note: If I `cat` the contents of the Markdown file at anytime from the terminal, even when the tabular data is filled and after manually saving, the contents of the file show that no tabular data was ever saved. It appears that tabular data is getting wiped out as soon as it is created. 
5. Note: If the Markdown file is edited in another program the data is successfully saved, and Zettlr does not wipe out the saved data. No new data may be written to the table, or it is also unsaved. 

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Sonoma 14.2.1

**Comment by nathanlesage** [comment]
In order to save table edits, you must as of now click the red disk icon at the top of the table. This ensures that your changes are actually applied.

I am aware that the table editor needs an overhaul and lots of improvements, and this is on the roadmap.

Please search the closed issues in this regard for more information.
