### ISSUE TITLE
Problem opening .md files

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#506]
## Description
When I open a .md file by double-clicking on it or right click 'open, with',  Zettlr does not open that file but simply opens Zettlr with the last file that was opened.

## Reproducing
As above

## Expected behaviour
That the correct file is opened

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.60 beta

**Comment by nathanlesage** [comment]
Is the file you wanted at least open in the sidebar in the standalone section on top? Or isn't it anywhere in the app?

**Comment by marcusyoung** [comment]
It's no where in the app.

**Comment by nathanlesage** [comment]
Alright, I'll have a look. Just to be sure: You double-click a Markdown file in Windows Explorer that is NOT inside any directory that you've opened, right?

**Comment by marcusyoung** [comment]
I will check and maybe upload a screencast. What should the behaviour be if you double click on a file that is in a directory that has been opened?

**Comment by nathanlesage** [comment]
It should be opened in the sidebar, in the upmost-left corner. I just checked it on a Windows 7 system, and for me it worked.

![image](https://user-images.githubusercontent.com/17251683/73927910-89c5e000-48d2-11ea-89b4-7f797f0cb471.png)

**Comment by marcusyoung** [comment]
OK, I will do a screencast for you.

**Comment by marcusyoung** [comment]
@nathanlesage

Here's a link to a screencast showing the issue. You'll notice that at the end the file test.md does open ok. I wonder if it's a file name issue?

http://screencasts.graspit.co.uk/watch/cYn1odwFmC

**Comment by nathanlesage** [comment]
Okay this is super weird, because it's totally unpredictable behaviour o_O

I mean you have one `catch-up` already open. Then you open the second one, which works. Then, none of the others work (so it's not a problem with the filename, because they follow exactly the same format), and suddenly, `test.md` works again?!

Do the logs say something? (In Debug mode, go in the Menu -> Develop -> Open Logs) Maybe there's an error… or, rather: hopefully, because otherwise I have no idea where this comes from.

**Comment by marcusyoung** [comment]
The only errors in the logs are quite a few:

>The translation string was malformed: Open Logs!

I also got this after playing around testing opening and closing things:

![error](https://user-images.githubusercontent.com/10391966/73960377-b134a100-4902-11ea-87d7-0b19525e7146.jpg)

**Comment by marcusyoung** [comment]
This may help. When I was in debug mode I couldn't get it to replicate the behaviour. As soon as I turned off debug mode it came back again.

**Comment by nathanlesage** [comment]
> As soon as I turned off debug mode it came back again.

This is weird, because debug doesn't alter any behaviour except giving you the additional menu … mh, I have to investigate! And concerning the malformed string, don't worry, it's just a string I was too lazy to translate
