### ISSUE TITLE
[3.1.0-beta.1] Keyboard shortcut not working for New File and New Directory

### ISSUE THREAD

**Issue by tafli** [Zettlr/Zettlr#5066]
### Description

Creating a new file with shortcut Cmd-N does not seem to work. This shortcut works in current 3.0.5 version.

Also Cmd+Shift+N does not create a new directory but opens a new window. In this case, this shortcut does also not work in 3.0.5 as it seems to be defined also as _New Window_.

I didn't check other shortcuts.

![Screenshot 2024-03-26 at 11 00 00](https://github.com/Zettlr/Zettlr/assets/15720039/4d822ea6-b9af-4ae8-8932-c455e0e662a2)
![Screenshot 2024-03-26 at 10 59 30](https://github.com/Zettlr/Zettlr/assets/15720039/0d8c4e77-87e8-495b-ae58-f61b487ae6cc)

### Reproducing

* Instal latest nightly
* Create a file using shortcut Cmd+N -> Does not work
* Crate a new directory using Cmd+Shift+N -> Opens new window

### Zettlr Version

Beta (if applicable)

### Specify version

3.1.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.4

**Comment by tafli** [comment]
Just found out, that the shortcut probably would work. A new file will not be created at all, even when clicking on "New File" directly. It doesn't matter which type of file. This affects "New Directory" as well.

**Comment by nathanlesage** [comment]
I just fixed the open directory shortcut; and tested the new file shortcut. I remember that I recently changed something related to creating new files as I discovered some wrong code in that command, so it's probably solved in the nightly that's coming on Monday – please feel free to try it out then.

**Comment by tafli** [comment]
Just tested latest nightly and can confirm that these shortcuts work again. Thank you for fixing!
