### ISSUE TITLE
[3.1.0-beta.1] [macOS] When closing via Dock, the unsaved changes popup gives the same 2 options

### ISSUE THREAD

**Issue by obitwrite** [Zettlr/Zettlr#5067]
### Description

When you have an unsaved file and close Zettlr using the macOS Dock, the popup asks to save unsaved changed, but the options given are incorrect. See below.

### Reproducing

* Create a new file
* Type something
* Right-click Zettlr in the macOS Dock, click Stop
* Zettlr shows a prompt asking to save unsaved changes, but the two options are the same. Both read 'Unsaved Changes' (tranlsated from Dutch, might be slightly different)

### Zettlr Version

Beta (if applicable)

### Specify version

3.1.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura

**Comment by nathanlesage** [comment]
This was due to fuzzy translations being on. I disabled that, but translators will have to update the file once to remedies this issue.
