### ISSUE TITLE
"Unsaved Changes" dialog - German translation is ambiguous

### ISSUE THREAD

**Issue by GrippenDynamik** [Zettlr/Zettlr#5072]
### Description

When you close Zettlr and there are unsaved changes, it asks the user what to do.

**English:**

![Save-English](https://github.com/Zettlr/Zettlr/assets/25545671/ee4b52e5-dfdd-4a9f-9316-08271937ef69)

Unsaved Changes
There are unsaved changes. Do you want to save them first?
Yes / No / Cancel

(actually, the buttons always say "Ja / Nein / Abbrechen", even when the Zettlr language is set to English, because my operating system locale is German - but that's a separate issue)

**German:**

![Save-German](https://github.com/Zettlr/Zettlr/assets/25545671/ceb52e41-6475-4949-8706-1b5e8c5e67ba)

Ungespeicherte Änderungen
Die Datei enthält ungesicherte Änderungen. Verwerfen oder speichern?
Ja / Nein / Abbruch

**Translation:**
The file contains unsaved changes. Discard or save?

**Problem:**
1. It's an either/or question, so the user can't answer with yes or no.
2. The user will probably assume that "yes" refers to the first option (discard) and "no" to the second (save), because that's the order the buttons are in.
3. But the buttons always do the same things, no matter what language Zettlr is set to.
"yes" saves and "no" discards.

### Reproducing

1. Change the Zettlr language to German
2. Open a file
3. Change something
4. Close Zettlr

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 21.3

**Comment by nathanlesage** [comment]
This is an issue with the fuzzy translations of gettext; to solve this someone just needs to update the translation with Poedit as outlined in the Readme. If I don't forget it I can do it, but this would be a great opportunity for a contribution!
