### ISSUE TITLE
Light mode has too little contrast between text and background in the panes.

### ISSUE THREAD

**Issue by victormnielsen** [Zettlr/Zettlr#5087]
### Description

When I have the program set on "not dark mode", I can barely read the text in the side panels:

<img width="373" alt="image" src="https://github.com/Zettlr/Zettlr/assets/112893188/0b617b3d-6ce7-40fb-807d-7385a1281f2f">

### Reproducing

This happens in all of the display settings. So all you have to do is to add a side panel and turn off dark mode (I just prefer writing black on white). 

I noticed that it depends a little on which program is behind the app, but there still isn't quite enough contrast between the text and background. 

In front of Zotero (which is light):
<img width="444" alt="image" src="https://github.com/Zettlr/Zettlr/assets/112893188/954f6b75-1cfd-48df-8bd5-627b3a0db97e">

In front of Whatsapp (which is dark):
<img width="369" alt="image" src="https://github.com/Zettlr/Zettlr/assets/112893188/e5fd55e6-cd37-410a-aa1a-0eae368bc14b">

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5 (3.0.5)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.2.1

**Comment by nathanlesage** [comment]
Could you please try out the current nightly to confirm whether the issue happens there, too?

**Comment by victormnielsen** [comment]
Hello

It doesn’t:

￼

When I switch:

￼

Best regards
Victor

**Comment by nathanlesage** [comment]
Perfect, so it seems fixed in the current nightly, and subsequently any new release, thank you!
