### ISSUE TITLE
Prevent numbered headings in PDF export

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#509]
In standard markdown headings aren't numbered. This is respected when I export to HTML or Word. But when I export to PDF they get numbered. Is there a way to stop this behaviour?

**Comment by nathanlesage** [comment]
Add `{-}` behind the heading (must be the last thing on the line). If you also want to exclude certain headers from an optional table of contents, add `{.unlisted}`. Combine like this: `{- .unlisted}`.

Example:

```markdown
\tableofcontents

# This header will both not be numbered and not in the ToC {- .unlisted}

Lorem Ipsum

## This header will be unnumbered {-}

Lorem Ipsum Dolor

## This header will be both within the ToC and numbered

Lorem Ipsum Dolor Sit Amet
```

Result:

![image](https://user-images.githubusercontent.com/17251683/73965931-535d8480-4915-11ea-951e-c866bd8ffdd0.png)

Added to the FAQ: https://docs.zettlr.com/en/faq/#in-pdf-output-i-want-certain-headings-to-be-unnumberednot-listed-in-the-table-of-contents

**Comment by RaphP** [comment]
Hi, 
I would like to get unnumbered pdf by default, without having to add a {-} after each header. 

I read that by default pandoc does not number the sections. 

Can I do as I wish by playing with the pandoc command in the advanced section of the parameters ? I don't really understand how the variables such as $citeproc$ refers to and can be modified.

Thanks !
R

**Comment by nathanlesage** [comment]
> EDIT : I removed the $tpl$ variable in the pandoc command and it did the job for unnumbering sections, but I lose all the nice formating of default Zettlr ! I read that tpl is "A template directive for pandoc." but no clue on where is this template on a mac for exemple.

Yes, `$tpl$` inserts the default Zettlr template, which it generates from within the source code. If you leave it out, Pandoc uses its default template. If you'd like to retain many of the good things of Zettlr without sacrificing the ease of access, feel free to adapt [the default Zettlr LaTeX template](https://github.com/Zettlr/Zettlr/blob/develop/source/main/assets/export.tex) to your needs and point to it in the Preferences (Custom Template directive, in the Export-tab)

**Comment by webbj74** [comment]
For my future self: placing the following into the default Zettlr template (on its own line before the `\title` directive) will remove sub/section numbering:

```tex
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
```
