### ISSUE TITLE
Youtube embed

### ISSUE THREAD

**Issue by padreputativo** [Zettlr/Zettlr#5098]
### Description

When you add a YouTube link, the thumbnails do not appear and the embed is not performed correctly. Additionally, URLs cannot be added to the whitelist; they can be deleted, but not added, such as img.youtube.com to try to solve the issue (it also does not work even if I edit the configuration file manually).

### Reproducing

As simple as putting (youtube)[https://www.youtube.com/watch?v=gnRMlm3_O5M]

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro KDE

**Comment by nathanlesage** [comment]
This is not how YouTube embeds work: You'll have to use the `iframe` embed code. It's outlined in the documentation: https://docs.zettlr.com/en/reference/markdown-basics/#zettlr-markdown-additions

But I agree it might be more clear in the documentation. I don't have a bandwidth right now, but feel free to open an issue on the documentation repo instead: https://github.com/Zettlr/zettlr-docs

**Comment by nathanlesage** [comment]
That is absolutely in your right. Zettlr is focused on long-form writing, and as such the use case of simply linking to a YouTube video without having it automatically render is what users here expect.

What I could do as a feature request would be to modify YouTube link previews to enable you to view the video in the preview window. But it is certainly not a bug.

**Comment by padreputativo** [comment]
No one expects that. A YouTube link is more durable than an iframe to a YouTube video, which you may need to change the structure of periodically to accommodate new parameters such as those created for increased privacy. If you don't know how to do it or have some sort of aversion to YouTube, that's your right, but at least allow others to create plugins to solve such senseless limitations. If you're so keen on perpetuity, there are services that convert YouTube videos into downloadable thumbnails.

**Comment by nathanlesage** [comment]
This has nothing to do with an aversion to YouTube, quite the opposite. Also, that is far from a "senseless" limitation, and the discussion of a plugin system has been happening over the years, feel free to read it up. But I guess it appears that your issue with Zettlr seems to not primarily be driven by the way it works, so I think it is best to leave the discussion at that. Thanks again for your response, and have a great day!
