### ISSUE TITLE
Impossible to export files on Flatpak builds

### ISSUE THREAD

**Issue by neur0b** [Zettlr/Zettlr#5099]
### Description

Everytime I try to export the current document (doesn't matter which format i choose) I always get the following message:

`pandoc: getCurrentDirectory:getWorkingDirectory: does not exist (Current working directory no longer exists)`

### Reproducing

The bug shows everytime the user try to export the current markdown file in another format using the internal pandoc.

### Zettlr Version

Stable (most recent version)

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

openSUSE Tumbleweed

**Comment by nathanlesage** [comment]
This likely has to do with permissions that are deliberately set very strict by default; see the corresponding info on the setup page: https://docs.zettlr.com/en/getting-started/setup/#flatpak

If there are any issues with the flatpak build, please refer to the correct repository: https://github.com/flathub/com.zettlr.Zettlr
