### ISSUE TITLE
Dragging attachments into doc inserts incorrect links

### ISSUE THREAD

**Issue by woodae99** [Zettlr/Zettlr#512]
## Description 
When dragging a file from attachments pane into text, the wrong attachment is inserted - see video of behaviour below
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/60781904/74031309-0d520080-49a9-11ea-933c-afd539a271b5.gif)

## Reproducing 
Please see the video for steps

## Expected behaviour
Zettlr should insert a link to the correct attachment

**Screenshots**
See video of

## Platform
 - OS and version: Windown 10 1909 - all current updates
 - Zettlr Version: 1.5.0
 - Screen Resolution: 2560x1440

**Comment by woodae99** [comment]
Close Zettlr and re-open it and the behaviour is as expected

**Comment by nathanlesage** [comment]
Looks as if the heading that is being inserted is in the clipboard, so it seems dragging and dropping the attachment does not override clipboard contents, which are inserted instead. I'll have a look!

**Comment by woodae99** [comment]
> Looks as if the heading that is being inserted is in the clipboard, so it seems dragging and dropping the attachment does not override clipboard contents, which are inserted instead. I'll have a look!

I didn't consider that it might be pulling in data from clipboard. If it helps - I use the clipboard function in windows 10 that allows you to copy multiple items and paste them selectively by pressing windows key +V

**Comment by nathanlesage** [comment]
I think that specific function only fills the clipboard with certain snippets; I simply have to see what is happening underneath!

**Comment by nathanlesage** [comment]
There you go.

**Comment by woodae99** [comment]
Nice work! :)

**Comment by nathanlesage** [comment]
Shortly reopening, as I found out this fix still does not cover images

**Comment by nathanlesage** [comment]
So … äh, I think I fixed it …? I'm really not sure at this point what is happening, as both CodeMirror and Electron are battling for rule over the clipboard, but I think I somehow fixed it ¯\\\_(ツ)\_/¯
