### ISSUE TITLE
Tag cloud selection no longer prepend hashtag (#) symbol to the search query in 3.1.0-beta.2-nightly

### ISSUE THREAD

**Issue by hungvvu** [Zettlr/Zettlr#5124]
### Description

In previous versions, selecting from the tag cloud will start a search query for the given tag, with the # symbol prepended. For example, selecting "example-tag" in the tag cloud menu will search for "#example-tag". This behaviour seems to have changed in the latest nightly and clicking on the tag in tag cloud menu no longer add the "#" symbol but instead just search for the tag name itself (in the previous example would be "example-tag").

### Reproducing

1. Open the tag cloud menu
2. Select a tag to start global search for that tag

### Zettlr Version

Nightly

### Specify version

3.1.0-beta.2-nightly

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

### Additional Information

Also tested on dev branch.

**Comment by chiphogg** [comment]
I'm seeing this on Linux as well.  The downside to the user is that it can return many unrelated results.

The workaround in the meantime is either to find a real tag and ctrl-click on it, or to manually prepend the `#` to the search term.

**Comment by chiphogg** [comment]
This is working in 3.2.2 --- awesome!
