### ISSUE TITLE
Issue saving in some circumstances 

### ISSUE THREAD

**Issue by woodae99** [Zettlr/Zettlr#513]
## Description
Zettlr won't allow user to select another file until cancelling save. App prompts user to save or "proceed without saving". Pressing "save" button dissapears the dialogue box, but it reappears whenever another file is selected. This continues until user chooses to "proceed without saving"

## Reproducing
See this clip:
![Zettlr save error](https://user-images.githubusercontent.com/60781904/74041608-e18d4580-49bd-11ea-994f-6176ac0b2cb4.gif)

## Expected behaviour
Selecting "save" option in dialogue box should save the file and allow the user to move on to other files

**Screenshots**

## Platform
 - OS and version: Windows 10 1909 with all updates
 - Zettlr Version: 1.5.0
 - Screen Resolution: 2560x1440

**Comment by nathanlesage** [comment]
This is a rare issue prevalent on all platforms, where I have encountered this. I'm not exactly sure why that is happening, but something does happen. In case, would you have any luck looking into the log files? The log feature is rather new, and I specifically intended to solve — among others — this specific bug!

**Comment by woodae99** [comment]
> This is a rare issue prevalent on all platforms, where I have encountered this. I'm not exactly sure why that is happening, but something does happen. In case, would you have any luck looking into the log files? The log feature is rather new, and I specifically intended to solve — among others — this specific bug!

Sure thing - where can I find the log file? I have just enabled de-bugging mode, is that necessary to generate the logs?

**Comment by nathanlesage** [comment]
No, don't worry, the logs are generated in either way! The logs are in the app's data directory, in the log-subdirectory. They are kept for seven days and then removed in order to keep the folder size small!

**Comment by woodae99** [comment]
[2020-02-06.log](https://github.com/Zettlr/Zettlr/files/4173224/2020-02-06.log)
[2020-02-07.log](https://github.com/Zettlr/Zettlr/files/4173225/2020-02-07.log)
Here are the two log files in the directory - hope this helps!

**Comment by nathanlesage** [comment]
Dammit, there's nothing in there :/ I'll have to have a look at what is happening there, apparently …

**Comment by Zverik** [comment]
Encountered the same issue yesterday on Fedora 31. Will check the logs when I see it again.

**Comment by nathanlesage** [comment]
Yes, please! I'll also keep an eye out and check ALL logs as soon as some file suddenly stops responding!

**Comment by nathanlesage** [comment]
Sooo, I just dumped a bunch of error loggings into the file-saving command, hopefully this turns out something useful! The next time, this error pops up, immediately open the logs (Debug mode on, then Develop -> Open Logs) and look out for errors!

**Comment by mkoliba** [comment]
Same issue on MacOS.  Reproduced repeatedly by: opening file, write something, Command+Z for Undo, try to switch to another file.

After pressing Command+Z and trying to switch to another file following lines shows in log but no error:
[21:54:17]	Trying to run command through Application: file-modified
[21:54:17]	No command registered with the application for command file-modified
[21:54:35]	>>> IPC IN: file-get
-23401595
[21:54:35]	Trying to run command through Application: file-get
[21:54:35]	No command registered with the application for command file-get
[21:54:53]	<<< IPC OUT: file-save
[21:54:57]	>>> IPC IN: file-get
-23401595
[21:54:57]	Trying to run command through Application: file-get
[21:54:57]	No command registered with the application for command file-get

After selecting another file and clicking proceed without saving logs show following:
[21:56:51]<<< IPC OUT: mark-clean
[21:56:51]	<<< IPC OUT: file-set-current
[21:56:51]	<<< IPC OUT: config-update
[21:56:51]	<<< IPC OUT: file-open
[21:56:51]	The translation string was malformed: Open Logs!

Zettlr: 1.5.0
MacOS: 10.15.3

**Comment by Zverik** [comment]
I also remember pressing undo before having this issue. Maybe the undo action doesn't change some state or trigger an autosave, like entering text does?..

**Comment by nathanlesage** [comment]
> I also remember pressing undo before having this issue. Maybe the undo action doesn't change some state or trigger an autosave, like entering text does?..

THAT'S IT! Just tried it out: Immediate reproducing!

1. Have a saved state file.
2. Enter some text
3. BEFORE autosave happens (after 5sec) IMMEDIATELY press Cmd/Ctrl+Z
4. The Editor will say "Unchanged!" while the main process still has the edit flag set to true!

**Comment by nathanlesage** [comment]
And fixed! :)
