### ISSUE TITLE
Focus tag filter after clicking tag selector

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#5138]
### Description

In previous versions of Zettlr (e.g., I had been on 2.3.x previously), I was able to click on the "Tags" button, and immediately start typing to filter for the tag.  Currently (I'm on 3.1.1), when I click, the note window still has focus, so if I start typing, the text gets added to the note.  I would need to make two clicks to start typing.

### Reproducing

1. Click the main note window to focus it.
2. Click the "Tags" button.
3. Start typing.

I would expect this text to go to the filter, as it used to, but it goes into the note instead.

### Zettlr Version

Stable (most recent version)

### Specify version

3.1.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

**Comment by chiphogg** [comment]
Any update on reproducibility, and/or how hard the fix is?

This bug litters my various documents with meaningless little strings (i.e., the first few characters of my attempted tag search), in ways that are hard to find later.

**Comment by nathanlesage** [comment]
Heya, sorry that issue fell right into my "I can't look at GitHub" phase -- I guess it should be an easy fix. So thanks for bumping I'd say

**Comment by nathanlesage** [comment]
Yup, as I thought:

https://github.com/Zettlr/Zettlr/blob/develop/source/win-main/PopoverTags.vue

There on line 110 it needs to be the after mount hook, not before mount.
