### ISSUE TITLE
"Zettlr offers some basic git functionality"

### ISSUE THREAD

**Issue by rolfedh** [Zettlr/Zettlr#5148]
### Description

[Here](https://docs.zettlr.com/en/reference/faq/#macos-asks-me-whether-i-want-to-install-xcode-commandline-tools-when-i-start-zettlr), the FAQ states, "Zettlr offers some basic git functionality, and for that must check whether git is installed on the computer."
I've searched both the UI and documentation for more information about this functionality and can't seem to find it.
This suggests three possibilities:
-  I'm searching incorrectly, and it's right there beneath my nose. (Ask my wife about this sometime!)
- The functionality exists but hasn't been documented.
- The functionality doesn't exist, and the statement in the FAQ is misleading. 

### Proposed Changes

Depending on the nature of the issue, there are several courses of action:
-  Improve the findability of this information for silly folks like me. 
- Document the functionality.
- Remove misleading information from the FAQ.

### Caveats

No caveats!

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Fedora Linux 39

**Comment by nathanlesage** [comment]
Zettlr currently can detect `git` repositories and tell you this fact in the directory properties, but that's about it. There are plans on integrating much more for it in future updates but this all being a mostly one-man-show, things tend to move forward a bit slower.

Since this is a question and not so much an enhancement request, please refer to the [discussions section](https://github.com/Zettlr/Zettlr/discussions) next time to ask questions. Thank you!

**Comment by rolfedh** [comment]
Thank you for sending me the link to the discussion section. However, I respectfully disagree with the assessment that this is a question. In my opinion, it is more of a bug report. The statement is aspirational and does not accurately describe the current capabilities of the system. This may mislead users to look for additional documentation and functionality that is not yet available. I am not saying this to be critical, but simply to communicate the impact this information had on me as a user. I understand that this is a minor issue and that this project is resource-constrained. I'd be very happy to contribute a PR to update the documentation and to take on other documentation tasks, if you like.

**Comment by nathanlesage** [comment]
Please, I'm always happy for documentation updates as I can't do that very much myself!

**Comment by rolfedh** [comment]
For example:

To allow a person to self-assign an issue in your GitHub project, you'll need to grant them the role of "Triage" or higher on your repository. Here's how you can set this up:

1. **Navigate to your repository**: Go to the main page of the repository on GitHub.

2. **Access the Settings**: Click on the "Settings" tab near the top of the repository page.

3. **Manage Access**: Click on "Manage access" on the left sidebar menu. You might need to confirm your password to proceed.

4. **Invite a collaborator**: If the person is not yet a collaborator, click on "Invite a collaborator", then enter their GitHub username or email address and send the invite.

5. **Assign roles**: Once the person has accepted the invite, or if they are already a collaborator, you can adjust their role. Click on the gear icon next to their name in the "Collaborators & teams" section.

6. **Set the role to Triage**: In the role settings, choose "Triage". This role allows users to manage issues and pull requests without giving them write access to the code.

7. **Confirm the changes**: Make sure to save any changes if prompted.

The "Triage" role is particularly useful because it allows the person to manage issues and pull requests, label and tag issues, and self-assign issues without being able to push code changes. This can be very handy for project managers or external contributors who primarily need to organize work but not necessarily contribute code.
