### ISSUE TITLE
[ENHANCEMENT]Internationalize the message "Empty directory"

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#515]
## Description

Opening an empty directory will show "Empty directory" in the sidebar, but it is not translatable.

![image](https://user-images.githubusercontent.com/15438757/74085766-f5b96b80-4abf-11ea-9929-711e3c9ecd6d.png)

## Proposed Changes

It'd be nice to be able to translate this message too.

**Comment by nathanlesage** [comment]
Thanks for reporting this! I totally forgot to translate that message, but fixed it right now, and added it to Zettlr Translate. Thank you for your effort in translating the app into Japanese, btw! I really like the language and therefore I'm always happy to see that Japanese is always up-to-date :)
