### ISSUE TITLE
Can't find and replace "\[" in the GUI.

### ISSUE THREAD

**Issue by antmoev** [Zettlr/Zettlr#5150]
### Description

<img width="603" alt="Screenshot 2024-05-08 at 08 35 05" src="https://github.com/Zettlr/Zettlr/assets/2613844/77629e8c-df24-4d5b-915a-31e6c7ed2cdc">
I'm trying to replace the "\[" caracters to "$". But it seems that it cannot be found nor replaced.

### Reproducing

Just write a LateX equation : `\[ \log_b(x^n) = n \log_b(x)\]`, hit CMD/CTRL+R, and try to replace `\[`.

### Zettlr Version

Stable (most recent version)

### Specify version

Version 3.0.5 (3.0.5)

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Sonoma 14.4.1 (23E224)

**Comment by lcsolano** [comment]
Escape the backslash, use:

`\\[`

**Comment by jpggithub** [comment]
The tip could be indicated in this dialog window.

**Comment by nathanlesage** [comment]
This issue seems solved. To me it looks as if you had to escape the `$` sign as it can also be used to reference capture groups.

Feel freel to amend the documentation at the other repository; since that is where such an info tip should go.
