### ISSUE TITLE
Omit Authors in Inline Footnotes

### ISSUE THREAD

**Issue by dstark** [Zettlr/Zettlr#5154]
### Description

As I understand it, author names can be suppressed by adding `-` ahead of the `@` symbol. This works fine for "regular" citations. But for citations in inline footnotes, the suppression doesn't appear to work. Instead, the `-` simply gets added before the citation as in the screenshot below.

<img width="812" alt="Screenshot 2024-05-09 132639" src="https://github.com/Zettlr/Zettlr/assets/205528/656b7bc9-4d4f-4995-acc6-f07b3c0ecfd2">

### Proposed Changes

Have author suppression work by adding `-` before `@` including in the context of inline footnotes.

### Caveats

It should be possible to escape `-` if that literal character needs to be printed, so I'm not seeing any downsides. (Though, admittedly, this is quite new … and my apologies if the request results simply from my not finding and following the proper syntax.)

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10 and 11

**Comment by nathanlesage** [comment]
If I'm not mistaken, suppressing authors in online citations is not possible; I think that only works for citations within square brackets. Also, a good indication is that the citation in your file is not rendered, which is usually a good indicator that Zettlr does not recognize it as one, and subsequently it won't be exported properly either.

**Comment by dstark** [comment]
Got it. So, it seems it would also _not_ be possible to suppress an author name in a non-inline note _and_ avoid parentheses around that citation. Does that sound right?

![image](https://github.com/Zettlr/Zettlr/assets/205528/ee1eaf1e-f75c-4ea0-b16d-08f5fd8e8145)

**Comment by nathanlesage** [comment]
I don't know. The Pandoc manual on citations is definitely the authoritative resource here.

**Comment by dstark** [comment]
> I don't know. The Pandoc manual on citations is definitely the authoritative resource here.

Thanks, @nathanlesage. I haven't been able to sort this question out from the Pandoc manual and have asked in [the discussion forum](https://github.com/jgm/pandoc/discussions/9771).

**Comment by dstark** [comment]
> I haven't been able to sort this question out from the Pandoc manual and have asked in [the discussion forum](https://github.com/jgm/pandoc/discussions/9771).

In case anyone else stumbles upon this thread looking at this issue, it's now been handled in Pandoc 3.2 (see [here](https://github.com/jgm/pandoc/issues/7219)).

**Comment by nathanlesage** [comment]
Thanks for notifying me! Does Zettlr display this correctly? If not, please open another issue because then I'll have to adapt Zettlr's citeproc renderer so that it aligns with Pandoc's behavior again. It should be an "enhancement" request.

**Comment by dstark** [comment]
> Does Zettlr display this correctly? If not, please open another issue because then I'll have to adapt Zettlr's citeproc renderer so that it aligns with Pandoc's behavior again. It should be an "enhancement" request.

Yes, I'll watch for it. Apparently, it's not quite in Pandoc though but will be in [the next release _after_ 3.2](https://github.com/jgm/pandoc/commit/2d74c75666a9b40623addf5a09346aba826c6ccd).
