### ISSUE TITLE
`musl` systems not supported

### ISSUE THREAD

**Issue by notramo** [Zettlr/Zettlr#5167]
### Description

The AppImage release do not run on Linux systems that use `musl` instead of `glibc` (e.g. Alpine Linux, Void Linux musl edition).

### Reproducing

Download Alpine Linux and try to launch the official AppImage.

### Zettlr Version

Stable (most recent version)

### Specify version

any

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [X] ARM 64bit

### Operating System Version

any `musl`-based Linux distro

### Additional Information

It seems that the AppImage is trying to load `glibc` dynamically, which is not found on `musl` systems.

If the AppImage would be linked statically with `musl`, it will run both on `glibc` and `musl` based systems.

**Comment by nathanlesage** [comment]
Hi,

This is out of scope for us. Adding support for external libraries requires custom built electron binaries which we do not provide. We use the default ones provided by the electron team.

The electron team does not support musl at this point: https://github.com/electron/electron/issues/9662#issuecomment-420480342

Once electron supports this setup officially, I will reconsider, but for now Zettlr will not support this.

**Comment by notramo** [comment]
@nathanlesage In this case, I think it's possible to bundle `glibc` into the AppImage as any other library.

**Comment by nathanlesage** [comment]
If you submit a PR that does this change so that it works, without maintenance and without breaking something else, I'm happy to merge.

**Comment by notramo** [comment]
Unfortunately, I'm not very keen on contributing to software I can not even try. I don't know if I would like it.

**Comment by blacklightpy** [comment]
> In this case, I think it's possible to bundle glibc into the AppImage as any other library.
@notramo Not possible yet https://github.com/AppImage/AppImageKit/issues/877.

You can use this instead: https://flathub.org/apps/com.zettlr.Zettlr
