### ISSUE TITLE
Zettlr fails to modify Windows files.

### ISSUE THREAD

**Issue by jxerome** [Zettlr/Zettlr#5180]
### Description

When the markdown files use Windows end of lines `<CR><LF>`, the modification of the file fails with a "Document out-of-sync" error.
![331602000-36dda9b9-8027-45be-866a-6465c96dc919](https://github.com/Zettlr/Zettlr/assets/1355634/f7595a8e-13ca-41ac-80c0-9c8e235ff8d6)

See more details in discussion #5166 

If Zettlr don't produce files with Windows end of files, there are many reasons an .md file can have such line terminaison on Windows:

* Modification of the file by another editor.
* Git introduce `<CR><LF>` on file checkout (that means that the whole workspace becomes impossible to edit.)

### Reproducing

1. Use Windows.
2. Checkout a workspace from git or write a .md file with another editor.
3. Ensure that the end of file is <CR><LF>
4. Open the file on Zettlr, try to modify it 💥
5. Close Zettlr.
6. Change the file with the other editor to makes lines end with <LF>.
7. Open the file in Zettlr.
8. Try to modify the file ✅ 

### Zettlr Version

Stable (most recent version)

### Specify version

3.1.1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by andriyyatsykiv** [comment]
I am also having this issue, with the same system details as you except for Win10. This makes Zettlr impossible to use in conjunction with any markdown published to github, which may cover quite a few projects.

**Comment by nathanlesage** [comment]
Good news: I spent some time today to fix that issue. I don't know why I did what I did (apologies) but the nightly that is currently in the making and should be available soon at https://nightly.zettlr.com should make working with windows line endings usable again!
