### ISSUE TITLE
.webp images not rendered

### ISSUE THREAD

**Issue by abadyr** [Zettlr/Zettlr#5181]
### Description

In Zettlr version 3.1.1, any images in the .webp format is not displayed, unlike previously.
To clarify, I'm talking about images "linked" through markdown syntax, this one: '\!\[\](image.jpg)'.

The "image not found" placeholder is displayed instead, which I take to mean Zettlr does not recognize the webp format for images anymore.

Webp images were displayed properly in version 2.3.0, which I used previously, and they are supported by Chromium.

### Reproducing

Link any image in the .webp format in a markdown file open with Zettlr, using markdown syntax.

### Zettlr Version

Stable (most recent version)

### Specify version

3.1.1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 Home

### Additional Information

Screenshot of 2 images with the same path (same folder and name) except the top one is webp, the bottom png.

![zettlr webp 2024-05-24 115224](https://github.com/Zettlr/Zettlr/assets/102581554/6008aaa3-922d-408e-9891-0e232f3c136b)

**Comment by nathanlesage** [comment]
This works in 3.2.2. May have been an unrelated bug or an Electron issue.

**Comment by abadyr** [comment]
Still doesn't work for me. 
I guess it means something went wrong on my side, but I uninstalled and reinstalled, and it did not fix it. 
(and my settings and open tabs were still there, though I don't see how the 2 could be linked when the issue appeared after I updated the software last...)

**Comment by nathanlesage** [comment]
Without seeing the path you are using, I cannot judge what may go wrong, but I can again confirm that in 3.2.2 webp images are properly rendered and work as expected.
