### ISSUE TITLE
Incorrectly formed path when image dragged from attachments

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#519]
## Description
A leading `/` is appended at the beginning of the file path when an image is dragged and dropped from attachments:

`![index.jpg](/C:/Users/marcu/img/index.jpg)`

This does not work on Windows. Pandoc fails on export to PDF with error:

> OpenBinaryFile: invalid argument (Invalid argument)

## Expected behaviour
Image to display in PDF.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.6.0-beta1
 
## Additional information

Would be preferable I think, if the file link was relative to the document when a file is dragged from the attachments?

**Comment by marcusyoung** [comment]
Also should add that even with correct full path the image is not rendered in PDF. Only rendered in PDF when relative path is given.

**Comment by nathanlesage** [comment]
Thanks for reporting, I'll have a look into that!

**Comment by nathanlesage** [comment]
I cannot reproduce this on macOS, but I've just added some debug console.logs — I'll be releasing yet another beta in a few minutes and then I'd like you to test it; the first console.log after dragging an image onto the editor will be the full thing that you've pasted, while the second will be what the editor will insert. If you could check this, it would be perfect! :)

**Comment by marcusyoung** [comment]
See below (not sure if I've picked what you wanted here?). The issue appears to occur at the pandoc stage. The directory path is written twice.

```
>>> IPC IN: file-save
charCount: 20
content: # Test image drag ![index.jpg](/C:/temp/zettlr/index.jpg)
creationtime: 1581699116847
dir: zettlr
ext: .md
frontmatter: {}
hash: -324643813
id: 20200214165155
linefeed:
modtime: 1581700004090
name: 20200214165155.md
parent: {"attachments":[{"canDrag":false,"ext":".jpg","hash":1211450781,"name":"index.jpg","parent":null,"path":"C:\\temp\\zettlr\\index.jpg"}],"children":[],"hash":797342388,"modtime":1581699116847,"name":"zettlr","parent":null,"path":"C:\\temp\\zettlr","project":null,"sorting":"name-up","type":"directory"}
path: C:\temp\zettlr\20200214165155.md
tags: []
type: file
wordCount: 3
wordcount: 1
```
```
<<< IPC OUT: file-replace
file: {"charCount":59,"creationtime":1581699116847,"dir":"zettlr","ext":".md","frontmatter":{},"hash":-324643813,"id":"20200214165155","linefeed":"\n","modtime":1581700069802,"name":"20200214165155.md","parent":{"attachments":[{"canDrag":false,"ext":".jpg","hash":1211450781,"name":"index.jpg","parent":null,"path":"C:\\temp\\zettlr\\index.jpg"}],"children":[],"hash":797342388,"modtime":1581699116847,"name":"zettlr","parent":null,"path":"C:\\temp\\zettlr","project":null,"sorting":"name-up","type":"directory"},"path":"C:\\temp\\zettlr\\20200214165155.md","tags":[],"type":"file","wordCount":4}
hash: -324643813
```

## Pandoc error

```
An error occurred on export: Command failed: pandoc "C:\Users\marcu\AppData\Local\Temp\export.tmp" -f markdown -t latex --template="C:\Users\marcu\AppData\Local\Temp\template.latex" --pdf-engine=xelatex -o "C:\Users\marcu\AppData\Local\Temp\20200214165155.pdf" --filter pandoc-crossref --filter pandoc-citeproc --bibliography "C:\Users\marcu\PhD\Publications\References\docs\phd.bib"
pandoc: C:\temp\zettlr\C:\temp\zettlr\index.jpg: openBinaryFile: invalid argument (Invalid argument)

```

**Comment by nathanlesage** [comment]
Ah, the debug logs will only appear in the DevTools, which means: Activate Debug mode (Preferences -> Advanced), and then Menu: Develop -> Open Developer Tools. There in the "Console"-Tab!

**Comment by marcusyoung** [comment]
Ah, right, I'm with you:

`file:///C:/temp/zettlr/index.jpg`

`/C:/temp/zettlr/index.jpg`

**Comment by nathanlesage** [comment]
aha! Knew it! On Windows the third slash is unnecessary. Fixed it!

Thank you very much! :)
