### ISSUE TITLE
[ENHANCEMENT] Option for Zettel search to use the root directory for searching

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#520]
## Description

Currently when you type `[[` into a note, you can search for a note from the current directory. I propose adding a switch to the Zettelkasten tab to switch between using current and root directories for searching for notes.

## Example Workflow

I split my notes into directories for years: 2019, 2020, and so on. That is to prevent any directory from having too many files, which might put a strain on either the file system, or the cloud sharing software. Works pretty well as long as I have the root directory opened. But when I'm adding tons of notes, I open the directory for the current year only, so that I won't have to drag notes into it afterwards. And with that, I can only add links to notes in the current directory, which is not always useful.

## Caveats

One more switch in the configuration dialog, which might confuse users. Also, this might be not the best Zettel practice, and users might start relying on it.

## Additional Info

Similar to #316, but this is about a single root directory with multiple sub-directories.

**Comment by nathanlesage** [comment]
Sounds good, and should be easy to implement!

We simply need to exchange the current dir here with the corresponding root (as in `while dir not root dir = dir.parent`)

https://github.com/Zettlr/Zettlr/blob/a96f7a20373d3c92f2f121748b5d3369f7133d61/source/renderer/zettlr-editor.js#L274-L290

**Comment by Zverik** [comment]
Yeah, I would do that as a pull request, but I'm not comfortable with changing the configuration UI with regard to i18n and stuff like that. Thank you for adding this to your todo list!

**Comment by nathanlesage** [comment]
Aaaand done!
