### ISSUE TITLE
Collapsed-Text-indicator doesn't have dedicated dark mode colors

### ISSUE THREAD

**Issue by johnnyboisssss** [Zettlr/Zettlr#5204]
### Description

At the moment, the three-dot icon that appears next to compressed text looks good in light mode, but in dark it contrasts weirdly and looks bad.

### Proposed Changes

Possibly recolor the three-dot icon for dark mode, or simply make the icon 3 periods so that it always matches.
<img width="142" alt="Screenshot 2024-06-06 at 11 03 15" src="https://github.com/Zettlr/Zettlr/assets/93165360/cdd969e6-36d0-4238-bf1d-7da1464bedd1">
<img width="149" alt="Screenshot 2024-06-06 at 11 03 31" src="https://github.com/Zettlr/Zettlr/assets/93165360/7bd318a9-5656-4d3c-a502-03dd7afb04a3">

### Caveats

none

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Operating System Version

Mac OS 14.0

**Comment by nathanlesage** [comment]
This is merely a small fix in the editor's base theme to add said changes, so it should be fairly simple to fix.

**Comment by K0Stek122** [comment]
If no one is up to this i'll be happy to start working on it. Please let me know.

**Comment by nathanlesage** [comment]
Please do it!
