### ISSUE TITLE
Support CTRL-F shortcut on macOS

### ISSUE THREAD

**Issue by lldong** [Zettlr/Zettlr#521]
Now 1.6 support using CTRL-B to move the cursor backward, but the CTRL-F shortcut used to move the cursor forward is still broken.

**Comment by nathanlesage** [comment]
Still broken? When did it break?

Ah, nevermind, found it:

https://github.com/Zettlr/Zettlr/blob/a96f7a20373d3c92f2f121748b5d3369f7133d61/source/renderer/assets/codemirror/generate-keymap.js#L33

**Comment by nathanlesage** [comment]
And fixed!
