### ISSUE TITLE
Repeated workspace loading

### ISSUE THREAD

**Issue by PaulKSchuler** [Zettlr/Zettlr#5220]
### Description

When starting Zettlr and the workspace is loaded as intended, the "Loading workspace" popup repeatedly appears without end.
![Screenshot 2024-06-10 102405](https://github.com/Zettlr/Zettlr/assets/66969708/1df00a16-8b54-4e28-bd99-9d684bff2d5b)

### Reproducing

Opening Zettlr in version 3.1.1 leads to the issue. When removing the config JSON file from Roaming, the behaviour disappears.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
Just to be sure: You deleted the config and now the behavior isn't reproducible anymore?

**Comment by PaulKSchuler** [comment]
When I deleted the config the behaviour disappeared. When I restored my backed-up config file the behaviour reappeared. However, after opening another workspace, the behaviour stopped altogether. Therefore, I assume it is an issue with my personal settings I cannot reproduce for other users.
