### ISSUE TITLE
Code Formatting Pretty Unusable

### ISSUE THREAD

**Issue by everythingability** [Zettlr/Zettlr#5221]
### Description

I expected to be able to paste in some javascript and have it display prettily, with colours etc.

### Reproducing

So I pasted in some Javascript and got this...

https://static.everythingability.opalstacked.com/numberToEnglish.html

So all the escape chars and lack of tabs make this pointless. I'd have to go back and re-tab the code to to make it look nice and for braces to be in the "correct" position.

So for documenting lumps of code this just doesn't work.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

14.5 (23F79)

### Additional Information

Zettlr has improved so much since I last used it, thanks all...

**Comment by nathanlesage** [comment]
This is expected. Specifically: It is impossible for an application to detect whether you have Markdown code in the clipboard that should be pasted as-is, or some code. Therefore, Zettlr transforms everything to Markdown *except* when you "paste without style". So basically the default behavior is always to transform when you press Ctrl+V, but if you know it's just plain text and it should be pasted as-is, press Ctrl+Shift+V, which will then result exactly in what you're looking for: Everything as-is for readable code.
