### ISSUE TITLE
Mermaid does not render in preview

### ISSUE THREAD

**Issue by tikkatek** [Zettlr/Zettlr#5228]
### Description

Hi there,

I'm a new user, so apologies if this is a duplicate. Honest, I did check first 👼 .

So, the issue I've come across is that when I produce a a Mermaid flowchart, then hit Ctrl+P to print the doc, I get the Mermaid code block instead of the render.

Please do let me know if I'm missing anything.

Thanks

### Reproducing

1. Create a new document
2. I gave it a title
3. Add the Mermaid code block. This is what I'm using
```text
flowchart LR
	classDef state fill:#0099ff,color:#fff
	classDef process fill:#ca00ca,color:#fff
	s1("Draft")
	s2("Awaiting Approval")
	s3("Ready")
	s4("Work In Progress")
	s5("Ready for Testing")
	s6("Testing")
	s7((Hold))
	s8("Complete")
	s1:::state --> s2
	s2:::state -- Approved --> s3
	s3:::state --> s4
        s4:::state -- Missing Requirements --> s1
	s4 -- Peer Review --> s5
	s5:::state --> s6
	s6:::state -.-> s7
	s6 -- Failed --> s4
	s7:::process -.-> s8:::state
```
4. The diagram render in the page without issue
5. Hit Ctrl+P on the keyboard
6. Notice that the Mermaid code shows instead of the diagram

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

EDIT: Updating the first description as the data is requested later in the form.

**Comment by nathanlesage** [comment]
You'll need to run the Pandoc Mermaid filter for achieving that. I'd recommend joining the [Discord](https://go.zettlr.com/discord) to get help on how to do that. Basically, you'll just need to drop it in the filters directory. I'll take care of making the process of adding a filter in more streamlined.

CC @sensologica There are a few minor UX decisions involved, do we already have this on the horizon?

**Comment by tikkatek** [comment]
Aha. Thanks @nathanlesage. I've have a look at that.
