### ISSUE TITLE
Document out of sync

### ISSUE THREAD

**Issue by PaulKSchuler** [Zettlr/Zettlr#5231]
### Description

When opening and editing the markdown file in RStudio, Zettlr cannot save the document anymore. This happened with Markdown, RMarkdown, and Quarto documents.  

![image](https://github.com/Zettlr/Zettlr/assets/66969708/16f68dcd-9681-4fab-a485-7b5a57d7f7aa)

### Reproducing

Open a .md document that has been created in Zettlr in another programme (e.g. RStudio), edit and close it. Then reopen it in Zettlr and try to modify it and save the changes.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
Which version are you on?

**Comment by PaulKSchuler** [comment]
I was on 3.1.1 but after your response saw the update to 3.2; now it seems to work perfectly. Thanks a lot!

**Comment by nathanlesage** [comment]
Hah, that was the aim! Thanks for confirming that my fix in 3.2 actually did exactly what I wanted it to do :D

**Comment by PaulKSchuler** [comment]
Is it possible that Zettlr now does not recognise changes on the other side made in other programmes like RStudio?

**Comment by nathanlesage** [comment]
It ... should? Even more precise than before, if I'm not mistaken. If there is a novel issue, try to reproduce it and then open a new issue please!

**Comment by PaulKSchuler** [comment]
No, there seems to be an issue with recognising changes made in RStudio (possibly other software, too) at least for quarto and RMarkdown documents. 
Happy to open a new issue, just to be precise enough, would a description like the above be acceptable or is more information needed?
