### ISSUE TITLE
Do I need to install Zettlr via admin account? Zettlr not working at work

### ISSUE THREAD

**Issue by ElectronicTeaCup** [Zettlr/Zettlr#524]
## Description
Zettlr simply does not function for me at my work place. I've always used it on my personal computer, however, now I have to use it at my institute more (i.e behind a firewall etc)

I can't open a directory or save, it just all behaves very oddly. I am on a network, however, I am saving files locally.

**Screenshots**
Below I opened the directory, and it prompted that it loaded up. But I can't see anything on the left.
![image](https://user-images.githubusercontent.com/31346583/74168734-72685900-4c2a-11ea-86eb-4c123c37b426.png)
It also keeps crashing. On startup it says "you got the latest version of Zettlr" (paraphrasing). Works fine at home on my own PC, never had issues like this before.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.5
 - Screen Resolution: 1920x1200

## Additional information
Behind an institute based firewall etc (in Germany). Installed as a non-admin user.

**Comment by nathanlesage** [comment]
I've received this firewall-issue before already. Concerning non-admin: This is fine. I'm also on an institute in Germany, workplace, installed as non-admin, and it's working fine. If it tells you "You got the latest version of Zettlr", the firewall is not a problem (if it were, Zettlr would tell you that it couldn't check for updates).

It can also not be the issue with too many sub-directories … mh … Do the logs say something? Either in the renderer or the system logs (Menu -> Develop -> Open Logs)

**Comment by ElectronicTeaCup** [comment]
Hey, thanks for the prompt reply! I can't find the Develop tab, Am I to look for it in the Preferences? Or the "File, Edit, view, help" menu? I can't seem to find it anywhere.

**Comment by nathanlesage** [comment]
Yes, Preferences -> Advanced -> Enable Debug

Then the menu will be available!

**Comment by ElectronicTeaCup** [comment]
Weird now I'm having an error message pop up.
![image](https://user-images.githubusercontent.com/31346583/74334569-731ffd00-4d9a-11ea-8030-00cfbfc1d012.png)

JuliaPro is atom based IDE that I use—which is also an electron app. I tried using Zettlr on my home pc (which also has JuliaPro) and it seems to be working fine. But could this be the culprit?

**Comment by nathanlesage** [comment]
Seems as if `fsPromises.readdir()` fails to an "unknown" reason. I'm not sure, which of the directories is the one that you opened as root? Seems as if the filename is simply too long (afaik Windows 10 still has the limitation of about 255 characters maximum path length)

**Comment by ElectronicTeaCup** [comment]
I've change the startup directory, and then tried opening a folder:

![Zettlr](https://user-images.githubusercontent.com/31346583/74342898-833fd880-4daa-11ea-9f11-810ddf0c938e.gif)

In this gif it's running quite smoothly. Earlier this morning It crashed 4-5 times and was very sluggish. Let me know if I can give you any additional information.

**Comment by nathanlesage** [comment]
Thanks for the GIF! I'll have a look later on
