### ISSUE TITLE
What exactly is the CSS required to reduce the editor left-margin padding

### ISSUE THREAD

**Issue by evdcush** [Zettlr/Zettlr#5241]
>               > If you use the instructions defined in the custom CSS docs you should be able to find the corresponding selectors, I think it is a padding set on the `.cm-scroller` element
> 
> Thank you for your help! 🙇🏻‍♂️
> I took a look at https://docs.zettlr.com/en/advanced/custom-css/
> 
> I tried some various snippets out for my `custom.css`, but I was not able to reduce the padding.
> 
> I hope this is directly configurable from the settings some day (like in Joplin and MarkText). 🤞🏻

_Originally posted by @evdcush in https://github.com/Zettlr/Zettlr/issues/122#issuecomment-1712663116_
            

Hello and thank you for Zettlr! ❤️

I am struggling with reducing the Zettlr editor's margin padding still.

I have tried the CSS hack again suggested in the documentation:
https://docs.zettlr.com/en/advanced/custom-css/#set-a-maximum-width-for-the-text

But the margin padding remains the same.

![screencap_2024-06-22_14-10-56](https://github.com/Zettlr/Zettlr/assets/28853935/0c70777f-4c91-44c1-8759-d73aea0c5f1a)

I'm sorry, I don't know anything about CSS, so I apologize for the dumb question (maybe it's super obvious).
May I ask what is the *exact* CSS to control for this?

**Comment by nathanlesage** [comment]
Afaik it's a 50px padding on the `.cm-scroller` element now. But beware: this margin also includes a gutter for displaying various elements at the side, so you won't get rid of the margin completely.

Also, for such questions please head over to our [discord](https://go.zettlr.com/), where a ton of people can help out with it, and this keeps this issue tracker clean. Thanks!
