### ISSUE TITLE
Tab docking--what library?

### ISSUE THREAD

**Issue by abalter** [Zettlr/Zettlr#5242]
What library does zettlr use for tab docking? Or if custom, where can I see the code? I searched the code for "tab" and "dock" and didn't find anything that looked like it was for managing repositioning and docking tabs.

**Comment by nathanlesage** [comment]
I do not know what you mean by "tab docking", but should you be referring to the editor tab bar on top of the files, then there is no library. Here: https://github.com/Zettlr/Zettlr/blob/develop/source/win-main/DocumentTabs.vue
