### ISSUE TITLE
Ctrl-S does not work when checkbox is selected

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#5246]
### Description

When I click a checkbox, and do the `Ctrl-S` shortcut, it doesn't save the file.  However, if I click outside the checkbox to focus some regular text, then the shortcut works again.

### Reproducing

1. Make a file.
2. Add a checkbox: `- [ ] My item`, say.
3. Click the checkbox and immediately `Ctrl-S`: observe that the file does not save.
4. (If your setting is to "save after a short delay", as mine is, then wait a little bit so that it saves.)
5. Click the checkbox, then immedately click the text (e.g., inside of the `My item` part), then type `Ctrl-S`: observe that it saves.

### Zettlr Version

Stable (most recent version)

### Specify version

3.2.0

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

Installed downloaded file via `dpkg -i`.

**Comment by nathanlesage** [comment]
I have the suspicion that this might have to do with the `ignoreEvents` setting I have on the renderers. We probably need a more fine-grained approach for that. I noticed this on the new table editor recently, and it's likely a thing with other renderers, too — at least those and introduce new DOM elements.

**Comment by vanako** [comment]
chiphogg, thanks so much for noticing this. I have the same issues with the same system/Zettlr version. Today I opened my document again to see that my changes are lost, and I thought I was being delusional, because I failed to reproduce the bug, but turns out I am not. Now I can resume my work in peace (and watch out, I encountered some mysterious saving issues in the past few months but am yet failing to reproduce them consistently).

**Comment by K0Stek122** [comment]
I'm happy to work on this if no one else is.

**Comment by chiphogg** [comment]
Great, thanks @K0Stek122!  It doesn't look like anyone else has claimed it, so I think it's all yours.

**Comment by chiphogg** [comment]
When do you think you'll be able to begin work, @K0Stek122?

**Comment by K0Stek122** [comment]
Hi, sorry for the delay. I've had a busy period. Will resume work 13th December.

**Comment by K0Stek122** [comment]
I'll try to resume earlier. It will be 13th at the latest.

**Comment by nathanlesage** [comment]
Don't worry, the issue has just been fixed!
