### ISSUE TITLE
Table of contents button does not work

### ISSUE THREAD

**Issue by hueyy** [Zettlr/Zettlr#525]
## Description

The table of contents button on the top bar does not work.

## Reproducing

Click the button on the top bar

![image](https://user-images.githubusercontent.com/6523121/74222996-9faa1b00-4cad-11ea-9259-650a4a86cf0d.png)

## Expected behaviour

It should open the table of contents dropdown (as it did, before the latest beta version). Right now, nothing happens when it is clicked. Other buttons on the top bar work.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.6.0-beta.1
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
"Duplicate" of https://forum.zettlr.com/discussion/92/beta-1-6-beta-1-table-of-contents
