### ISSUE TITLE
Allow case-specific regex searching

### ISSUE THREAD

**Issue by dstark** [Zettlr/Zettlr#5250]
### Description

[Regex](https://regex101.com/) `[E][X][A]` finds `EXAmple` but not `Example`. But in Zettlr, `[E][X][A]` finds results where `e`, `x`, and `a` appear in that order together irrespective of case. One has to also select the `match case` option in order to limit results to `EXAmple.`

### Reproducing

See the description above.

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 10

### Additional Information

Making Zettlr's regex search respect regex case restrictions would allow some of a search to be case-restricted but not all of it. With the `match case` option currently, the whole search has to be restricted to case-matched results or not. This adjustment would also make Zettlr's behavior more consistent with results from other regex query checkers.

**Comment by nathanlesage** [comment]
Regex already works flawlessly in Zettlr, and I think you may be overthinking regex. A few points:

* By default, the regular expression has the `i` flag set (for case insensitivity)
* Selecting "match case" removes that flag, so you'd have to define any cases you want to actually target
* `[E][X][A]` is not how you would write that. Do you want to search for any occurrence of the letters e, x, and a? Then use `[exa]`. Do you want them in a specific order? Then use `exa`. Do you need some in upper, some in lower-case? Then use `[ExA]` or `ExA` depending on your use case.

I recommend having a look at the documentation, and specifically the linked JavaScript Regex explainer there: https://docs.zettlr.com/en/core/search/#searching-in-files
