### ISSUE TITLE
[BUG] Inlined tags are no longer highlighted

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#526]
## Description

In 1.5.x, tags were highlighted: e.g. "Click here to find notes → #notes" would display the tag in different colour. This is not the case in 1.6.0 beta2. Tags are displayed in the same way as regular text, and you cannot Alt+click on them for searching.

## Reproducing

Type "Tag #whatever". There will be autocompletion for the tag, but it won't be highlighted. But if you start a line with a tag ("#whatever"), it will be highlighted.

## Platform
 - OS and version: macOS 10.14.5
 - Zettlr Version: 1.6.0 beta2

## Additional information

May be related to #79, but that was fixed very long ago, and in 1.5.0 inline tags worked.

**Comment by nathanlesage** [comment]
Ah crap, I start to regret having rewritten the whole mode cascade just for the sake of having YAML frontmatters render correctly :rage:

**Comment by danieltomasz** [comment]
What is weird, after finding  the tag using "cloud tag view"  and using the "hyperlink" the tag will stay higlighted in different color, even after closing the search and browsing other files

**Comment by marcusyoung** [comment]
Seems to still be working ok on Windows 10 with 1.6.0 beta2 - highlighted and Alt-click for search.

**Comment by nathanlesage** [comment]
This is weird; this should not be platform-dependant behaviour o_O

Nevertheless, (I hope that) I just fixed that!

**Comment by Zverik** [comment]
Indeed it woks now — thanks!
