### ISSUE TITLE
Blinking editor window when creating a link from the keyboard shortcut with more than a URL on the clipboard

### ISSUE THREAD

**Issue by dstark** [Zettlr/Zettlr#5261]
### Description

When creating a link from the keyboard (e.g., `Ctrl+K` on Windows 11), Zettlr tries to paste in a URL if it finds one on the clipboard. This feature is helpful. But if the clipboard contains both a URL and substantial additional text, Zettlr still tries to include the clipboard text as the link target. Upon doing so, the text in the editor window blinks and blanks out in substantial sections, leaving it unclear whether text has somehow gotten deleted or whether it's a purely visual issue. The document needs to be reloaded in a new tab to show the current state of its text.

![image](https://github.com/Zettlr/Zettlr/assets/205528/b2dc805c-bf9d-49cf-94e7-919b4b0dd5e9)

### Reproducing

See the description above.

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
Please provide some more info:

1. a link (more specifically: a link to a website that contains such a link) that, when you copy it to the clipboard, will cause this effect (also, which browser? There are differences)
2. Do you then select some text and press CTRL-K, or does this also happen if you don't select anything?

**Comment by dstark** [comment]
@nathanlesage, actually, it now looks like there might have been a video/display issue. I wasn't seeing the same behavior anywhere else besides Zettlr. But since posting the above, I also haven't been able to reproduce the issue in Zettlr. I'll close this issue for now and reopen if it crops up again in a way I can consistently reproduce.
