### ISSUE TITLE
New file creation disables file explorer

### ISSUE THREAD

**Issue by edern-appere** [Zettlr/Zettlr#5266]
### Description

I'm using Zettlr 3.1.1 Flatpack under Ubuntu 22.04. 

Whenever I create a new file within the file explorer (left sidebar), Zettlr behaves like this : 

1. New file is created
2. File explorer gets replaced by a link to the location of the newly created file
3. No way to display the usual workspace inside the file explorer anymore
4. Closing the app and opening once again does not do anything to solve the issue

The only way I found to circumvent this is to open the file "config.json" located in this directory : 
/home/.var/app/com.zettlr.Zettlr/config/Zettlr
and to replace the content of "openPaths" by the location of my usual workspace (it gets populated by the location of the newly created file). 

I'm using the same version of Zettlr on my work computer and it does not behave like this, so I'm a bit confused about the source of the issue. If anyone has any way to solve this, it would be great. 

### Reproducing

1. create a new file within the file explorer (left sidebar)
2. New file is created
3. File explorer gets replaced by a link to the location of the newly created file
4. No way to display the usual workspace inside the file explorer anymore
5. Closing the app and opening once again does not do anything to solve the issue

### Zettlr version

3.1.1 flatpack

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Ubuntu 22.04

**Comment by nathanlesage** [comment]
Does this behavior still occur in v3.2.0?

**Comment by edern-appere** [comment]
This behavior still happened in v3.2.0 on my computer but I think it was related to some issue with my config data. 
I uninstalled completely Zettlr (with all config data), then installed once again (3.2.0 from Flathub) and it now works properly... except that when I create a new file from within the file explorer, the file is created and opened but does not show up in the file explorer (until a reboot of the app). 
The weird thing is that I have the same config at work (Zettlr 3.2.0, installed from Flathub) but this bug never happened...
