### ISSUE TITLE
[ENHANCEMENT] Make sure an id for the file is preceded by a newline or a space

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#527]
## Description

Similar to #79, but for identifiers. Currently when there is no id in the file name, the editor looks for the first id regexp match in the file. As mentioned in [a comment](https://github.com/Zettlr/Zettlr/blob/develop/source/main/zettlr-file.js#L268), it can take an id from a link. Which often happens for me, since I decided to put node id and its tags in the last line of each note.

Setting `(?<= |\n|^)(\d{14})` for an id regexp seems to work.

This should solve the issue of using a link for an id.

## Proposed Changes

I propose adding `(?<= |\n|^)` to the `idRE` when searching for the file identifier.

There might be sense in including a tag character there (` |\n|\t|^`).

## Caveats

Might fail on notes without spaces before ids: e.g. when a user is used to type `id:12387129323`. Not sure if that is a viable case.

**Comment by nathanlesage** [comment]
Your caveat case is precisely why I can't add it. It would add unexpected behaviour. We have the ID regexp, so basically an extremely low-level internal exposed to the user in order to have maximum flexibility. If the user cannot override the regex, because some positive lookbehind is always added, this will cause a lot of frustration. Even more so as you can easily just add this precise regexp addition in the preferences!

But feel free to add this possibility of adding this lookbehind to the appropriate positions of the docs!

**Comment by Zverik** [comment]
Okay, I understand, thanks.

But still, [this note](https://docs.zettlr.com/en/reference/settings/#the-internal-links) from the documentation is currently false: "Note that files will not assume any link as an ID. If a file finds an ID that is surrounded by the internal link formatting, it will not use this ID." Should I file it as a separate bug, or should the documentation be corrected?

**Comment by nathanlesage** [comment]
With link I meant the square-bracket things, because these are filtered out, indeed. It's not Markdown-links (which are not filtered out), but I see the confusion that may arise. Please feel free to make a PR that changes this wording to something more adequate, I'd gladly merge this!

**Comment by Zverik** [comment]
I know, it's pretty obvious you mean square-brackets links. But they are not filtered! See ids in the sidebar here and a part of note:

![Screenshot 2020-02-11 at 16 51 13](https://user-images.githubusercontent.com/766031/74242334-c177c200-4cee-11ea-88e9-f20a5a95289c.png)

**Comment by nathanlesage** [comment]
Ahh, okay that is indeed a bug, because the file `lyft-presto` should have the ID 20200211125627 and not 20200207125609. That's right, it's (yet another) bug

**Comment by Zverik** [comment]
Cool — filed #528 for that. Thank you for being responsive!
