### ISSUE TITLE
Prompts filename when use Ctrl + N

### ISSUE THREAD

**Issue by doojonio** [Zettlr/Zettlr#5277]
### Description

Zettlr prompts new file's name and destination, but "Do not prompt for filename" is checked.
In previous versions Zettlr didn't ask for filename, if this setting was checked.
It also opens in system's file explorer a fallback directory (~/Documents), when creating a new file,  not the workspace's directory.

### Reproducing

1. Ensure the "Settings > Advanced > Do not prompt for filename when creating new files" checkbox is checked
2. Open workspace
3. Press Ctrl + N or click File > New File > Markdown
4. It opens file explorer in ~/Documents with generated filename in placeholder

Expected: Ctrl + N creates a new file in selected workspace with set name pattern and opens the file in Zettlr without asking a path where to create it.

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Fedora Workstation 40

**Comment by ailintom** [comment]
Thank you! I believe, this is a duplicate of https://github.com/Zettlr/Zettlr/issues/5141 and relates also to https://github.com/Zettlr/Zettlr/issues/5123

**Comment by doojonio** [comment]
Yeah, that's true. Didn't find them before creating an issue. Sorry
