### ISSUE TITLE
[BUG] File ID is taken out of links

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#528]
## Description

[The documentation](https://docs.zettlr.com/en/reference/settings/#the-internal-links) currently says: "Note that files will not assume any link as an ID. If a file finds an ID that is surrounded by the internal link formatting, it will not use this ID."

This is false for 1.6.0 beta2: see ids in the sidebar here and a part of note:

![Screenshot 2020-02-11 at 16 51 13](https://user-images.githubusercontent.com/766031/74242334-c177c200-4cee-11ea-88e9-f20a5a95289c.png)

## Reproducing

Write an id inside of a note that doesn't have an id in its file name, and above it, link to another note. Then in a few seconds observe the note id.

## Expected behaviour

Note ids are not taken from double-bracketed (or whichever configured) links.

## Platform
 - OS and version: macOS 10.14.5
 - Zettlr Version: 1.6.0 beta2

## Additional information

Branched this issue from #527.

**Comment by nathanlesage** [comment]
Found it! Super stupid logical mistake on my side 🤦🏼‍♂️
