### ISSUE TITLE
Previous and Next Tab commands apply to all panels in split view

### ISSUE THREAD

**Issue by lewallen** [Zettlr/Zettlr#5282]
### Description

If I'm using split view and run the Previous Tab or Next Tab command, then the tab changes in every panel which has multiple tabs, rather than just the focused panel. It's possible this is the intended function, but I assume it should apply to the focused panel only.

### Reproducing

Create multiple panels (split view) with multiple tabs in each one, then run the Previous Tab command.

### Zettlr version

3.2.0

### Installation Method

Other (please specify below)

### Installation Method (Other)

I built this version myself (so I could have section folding commands), but ASAP I'll test in the homebrew version.

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Sonoma 14.5

**Comment by nathanlesage** [comment]
Oh, that's a fun finding! And also easy to fix :)
