### ISSUE TITLE
[Request] option to hide folders without notes

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#529]
## Description
Option to hide visibility of sub-folders  without notes in tree view

## Proposed Changes

I store images for notes in subfolder. Now,  when  I divided my zettlekasten for academia and private notes, the subfolder with images appears between the othertwo  folders and it is annoying,

**Comment by nathanlesage** [comment]
Thought about that for sometime, but would require the addition of some form of "mini-toolbar" on top of the file list, and then we have a lot of issues that I'd like to address first, but we can certainly keep that in mind

**Comment by danieltomasz** [comment]
In 1.7 i dont see anymore folder with images, so maybe this is solved?

**Comment by nathanlesage** [comment]
huh, as far as I know I didn't implement this … mind to double check?

**Comment by danieltomasz** [comment]
> huh, as far as I know I didn't implement this … mind to double check?

yes, after checking, the image  folder is still present, but at the bottom of the view (previously was in the top part of the view of the catalogue), also it does not appear when the directory tree is minimalised (which was earlier a problem for me)  

So apparently as a side effect of other changes, it become less obtrusive (at least for me)

If there is still need for such an option, maybe would be   easier to implement it by  adding a global option in settings, that will work for all folders (to check/uncheck if user need to see such folders)

**Comment by nathanlesage** [comment]
> If there is still need for such an option, maybe would be easier to implement it by adding a global option in settings, that will work for all folders (to check/uncheck if user need to see such folders, also with the possibility to user specify which kind of folders/files could be ignored)

Sure … let's keep this issue open until either other people say they would like to have this. If not, in 2 months the stalebot will come and clean up!

**Comment by claford-v-lawrence** [comment]
Yes, it's a great feature! Now I don't have to see my `_resource` folder!

**Comment by danieltomasz** [comment]
> > huh, as far as I know I didn't implement this … mind to double check?
> 
> yes, after checking, the image folder is still present, but at the bottom of the view (previously was in the top part of the view of the catalogue), also it does not appear when the directory tree is minimalised (which was earlier a problem for me)
> 
> So apparently as a side effect of other changes, it become less obtrusive (at least for me)
> 
> If there is still need for such an option, maybe would be easier to implement it by adding a global option in settings, that will work for all folders (to check/uncheck if user need to see such folders, also with the possibility to user specify which kind of folders/files could be ignored)

Or some kind of .Zettlrignore file ;P

**Comment by nathanlesage** [comment]
> Or some kind of .Zettlrignore file ;P

Yeah, let's just introduce more and more Zettlr-only files so that people are vendor-locked into using Zettlr, completely what I planned to do all along, hahahaha :P 

But actually that gitignore-idea has surfaced somewhere, and I'm inclined to support that. But there's the need for better attachment managing as well … ahhh, so many construction sites for so many great features!
