### ISSUE TITLE
when indenting bullets the text start to jiggle

### ISSUE THREAD

**Issue by paypalguy** [Zettlr/Zettlr#5296]
### Description

on MacOS (Sonoma not Beta version)

When indenting text the whole text starts to jiggle everytime I type a new word. 
This resolves if I outdent the bullet points.
I tried checking and unchecking "Indent using tabs instead of spaces"

https://github.com/user-attachments/assets/d5fa79d4-0dae-48f4-8c00-a01e043089fa

### Reproducing

if you make a bullet list and indent the text it should be reproducible

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Installation Method (Other)

Sonoma

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Sonoma 14.5

**Comment by lcsolano** [comment]
It's a well known bug:

https://github.com/Zettlr/Zettlr/issues/4602

Try using spaces instead of tabs, you can configure that so when you press the `TAB` key, Zettlr will add spaces instead. This is in fact recommended for other reasons as well.

**Comment by nathanlesage** [comment]
Recently fixed, closing as completed.
