### ISSUE TITLE
Unsplash Source being deprecated (Nov 25, 2021)

### ISSUE THREAD

**Issue by chla-conscia** [Zettlr/Zettlr#5323]
### Description

[changelog.unsplash.com](https://changelog.unsplash.com/deprecations/2021/11/25/source-deprecation.html) - Nov 25, 2021

### Unsplash Source being deprecated

> Unsplash Source is being deprecated.  
Existing uses will continue to work, however for new projects use the full [Unsplash API](https://unsplash.com/developers).

maybe find another way to get random pictures?

### Reproducing

i never got a random background to work in the first place.

### Zettlr version

Version 3.2.0 (3.2.0)

### Installation Method

Homebrew

### Installation Method (Other)

Sonoma 14.5

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Sonoma 14.5

**Comment by nathanlesage** [comment]
You probably looked at the docs right? This is not an issue with Zettlr, as it doesn't itself use the unsplash API. Please feel free to open an issue on Zettlr docs, or even fix the section in the documentation directly!
