### ISSUE TITLE
[ENHANCEMENT] Option to use note header for a zettel link title

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#534]
## Description

Currently when you type a zettelkasten link by using autocomplete, it adds a file name near it as a way to describe the contents. I propose to give users a choice: to not add anything, to use file name or a note title.

## Proposed Changes

There should be a drop-down field in "Zettelkasten" config tab with options for annotatin sk links:

* File name (default): add a file name, like it does now.
* File name without id (like suggested in #325).
* Title: use the first h1 (single `#`) title to annotate the link.

This would require parsing notes for their titles — which might help later with other features.

Having instead a switch for "use note header instead of file name" would also do.

## Caveats

Looks like nothing would be changed by this. When there's no h1 title, a fallback to "file name" should be done.

## Additional Information

Inspired by #367 and my file naming scheme: I use only lowercase English words and hyphens (`presto-make-tables.md`), while writing full titles in the first line, often in Russian (`# How to Make Tables in Presto`).

In #325 you mention that something has been done on this, but not sure how to test that.

**Comment by nathanlesage** [comment]
This feature already exists:

![image](https://user-images.githubusercontent.com/17251683/74335054-97300e00-4d9b-11ea-80d0-c89848c5592b.png)

**Comment by Zverik** [comment]
Wait, no, that's a different feature. What exists is an option to sometimes add a file name. I propose a switch to choose what exactly should be added: a filename, an abridged filename, or a title from a header.

I'll remove "none" option to make that more clear.

**Comment by nathanlesage** [comment]
No, it's not a different feature, it's exactly the same feature. Yet, I see that you want an additional option, right?

**Comment by Zverik** [comment]
Existing feature: "when to add the file name"

Proposed feature: "what exactly to add: file name or some other thing"

With this proposal there would be options to add a full filename, a filename without an id (like suggested in #325), or a title. This does not intersect with the existing feature, namely _when_ to add that string.

For example, in "when linking files..." you can choose "only when linking by id", and in "what" you can choose "title", and the title will be only added when linking by id.

**Comment by nathanlesage** [comment]
> Existing feature: "when to add the linked note description", which currently can be only file name.
> Proposed feature: "what exactly to add: file name or some other thing"

Dude, that is an _enhancement_ to an _existing_ feature. :D It simply gives more options how the links should look like. You even put it in the issue title :D

**Comment by Jos512** [comment]
This would be an incredibly helpful feature because now I'm often repeating myself (as in, typing over the title of the linked note).

To add some more context to this note, at the end of my notes I often include something like:

~~~md
## Related 
- [[2020-04-20 191908]] History of C++
- [[2020-04-20 191129]] Background on the C language
~~~

The text after those links I typed over from the title of those notes. So if Zettlr can include that automatically, it would be a nice win! :slightly_smiling_face:

**Comment by Zverik** [comment]
I would still like this: I'm using headers, not yaml frontmatter (not enough of a techie for that, and a single `#` is easier to type that `title: ... ---`)

**Comment by nathanlesage** [comment]
Certainly correct, it'll need some modifications to file-parsing, but shouldn't take long!

**Comment by Zverik** [comment]
Yeah, no hurry, I've commented just to keep the stale bot away :)

**Comment by nathanlesage** [comment]
"This is not the bot you are looking for" 👀

**Comment by nathanlesage** [comment]
Here ya go

**Comment by Zverik** [comment]
Thanks!
