### ISSUE TITLE
Drag and drop files from file explorer into leafs

### ISSUE THREAD

**Issue by IgnacioHeredia** [Zettlr/Zettlr#5344]
### Description

The ability to open a file in a particular leaf by drag and dropping.

### Proposed Changes

When you have several leafs opened, I think it could be nice if you could click on a file in the file explorer, hold it, drag to one leaf and drop it there. For reference, VScode has this feature.

https://github.com/user-attachments/assets/f7e0bdd1-a77c-4157-aa4d-e22ae2355751

### Caveats

None

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (but an older version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 20.04

### Additional Information

I'm running Zettlr 3.0.1 (because [I want old link behavior](https://github.com/Zettlr/Zettlr/issues/5171)) but from reading the release docs, I assume the proposed enhancement hasn't been implemented since then.

**Comment by nathanlesage** [comment]
Huh, you're right, Zettlr will always open in the first leaf, even if dropped onto the tab bar of another one. I suspect this might be an easy fix. Relabeling as bug because this is clearly not transparent behavior of the app.
