### ISSUE TITLE
[Request/Enhancement] Possibility to save frequent search

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#535]
## Description

Would be nice to  have a possibility in a handy way to save a  search results
This is similar to https://github.com/Zettlr/Zettlr/issues/189

## Example Workflow
Possible inspiration https://help.evernote.com/hc/en-us/articles/209005267-How-to-create-a-saved-search

Or another implementation here
https://github.com/renerocksai/sublime_zk#zettelkasten-mode

## Additional Information
Its probably involve  much work anyway, so its a suggestion for a distant future.

**Comment by nathanlesage** [comment]
Yes, it's planned, but I have abandoned it due to priority and time issues for the time being. However, after some other issues, I could take up the `ZettlrFilter`-approach again.

**Comment by Zverik** [comment]
I believe a Zk way would be to have outline notes with all the relevant links and tags. Saving searches would mean them being slowly outdated. What might help instead is pinning notes. Some kind of a "favourite" / "quick access" for outline notes for projects you're working on.

**Comment by nathanlesage** [comment]
Pinned notes is also already open somewhere on the issue tracker, and is also blocked due to the missing file system stuff, which is why I've opened the roadmap issue :D There's so much possible, once I implement this new file system. I'll create a special repository only for that thing soon, and then we'll see to get this going until June or July!

**Comment by danieltomasz** [comment]
is possible that pinned notes find its way in 1.7 realese or they will be waiting for better times?
This is especially useful for meta notes

**Comment by nathanlesage** [comment]
Pinning notes should be easy now, so let's pin this …

**Comment by danieltomasz** [comment]
If possible, pinning directories also would be great - I have several directories, some of them contained notes that I want to clean and after the end of week put to another, more ordered directory 

But maybe it is too much ;P

**Comment by nathanlesage** [comment]
Closing, since Zettlr now saves searches!
