### ISSUE TITLE
Wrong Colors in Readability Mode

### ISSUE THREAD

**Issue by hnsstrk** [Zettlr/Zettlr#5355]
### Description

I've encountered an issue with the color display in the Readability mode of Zettlr. The text highlighting does not match the expected behavior as outlined in the documentation and the source code.

## Expected Behavior

According to the documentation, the Readability Mode in Zettlr is designed to provide a visual indication of the readability of each sentence. Sentences are highlighted using a color scale ranging from green to red:

Green: Indicates that the sentence is easy to understand.
Blue and Purple: Indicate average readability.
Yellow, Orange, and Red: Indicate poor readability, meaning the sentence is harder to understand.

```
    // Define the readability classes. Red, orange, and yellow indicate bad scores
    // Purple and blue indicate average scores, and green indicates good scores
```
Source: https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/plugins/readability.ts

## Actual Behavior

To test the functionality, I used the text "Bartleby, The Scrivener," which is provided as an example on the [Zettlr Readability webpage](https://www.zettlr.com/readability).

In the attached screenshot, the left side shows the correct color coding as per the expected behavior, while the right side demonstrates how the Readability mode is currently displaying the text on my system.

The colors used for highlighting sentences do not correspond to the expected scale; instead, they appear to be incorrectly assigned or inverted.

This issue occurs consistently across all four readability models (ARI, Dale-Chall, Gunning-Fog, and Coleman-Liau).

![zettlr](https://github.com/user-attachments/assets/282f8788-38fb-4810-9d24-63c715703e16)

### Reproducing

- Open Zettlr and enable Readability Mode.
- Select any of the four readability models (ARI, Dale-Chall, Gunning-Fog, Coleman-Liau).
- Use the text "Bartleby, The Scrivener" as provided on the Zettlr website as an example.
- Observe the text highlighting and compare it with the descriptions provided in the documentation and the expected color coding from the source code.
- Notice that the color coding and readability scores do not align with the expected output.

### Zettlr version

3.2.0

### Installation Method

Other (please specify below)

### Installation Method (Other)

winget

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
I have updated the colors in the readability algorithm some time ago to include blue (so that we have more colors available for the 10 different types of readability scores). They are outlined [here](https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/plugins/readability.ts) at the bottom. The webpage is not accurate anymore.

I do agree that the scale could be a bit more intuitive. Here's how it's supposed to work:

```
// Define the readability classes. Red, orange, and yellow indicate bad scores
// Purple and blue indicate average scores, and green indicates good scores
```

Tbh I'm not the best at colors and I know there's a better way to produce a color gradient from red to green, but I admit that I didn't fully get there yet. I take any suggestions as to how to improve that.

**Comment by hnsstrk** [comment]
Perhaps I didn't express myself clearly. My issue is that sentences that are shown as green (indicating they are easy to read) on the website are displayed as red in the software.

**Comment by hnsstrk** [comment]
"I'm not a programmer, so I'm not entirely sure if I fully understand the calculations and code. The readability models assume that a higher score indicates a more difficult text to read. The `zTransform` function maps this to a scale from 0 to 10, and colors are then assigned based on this scale. The code `&light .cm-readability-0': { backgroundColor: '#ff0000aa', color: '#444' },` shows that a low score is displayed in red, which suggests poor readability. However, it would ideally be green, as the text is easy to read."

**Comment by nathanlesage** [comment]
Umm, I won't say I might not have messed up the score direction. 🫠  I'll have a look into that, could be very well that when I redid the colors I didn't think about whether small or large numbers are the hard-to-read ones. In that case it should actually be a stupidly simple fix.

**Comment by hnsstrk** [comment]
This could work ...

export const readabilityMode = [
  readabilityModePlugin,
  EditorView.baseTheme({
    '&light .cm-readability-0': { backgroundColor: '#7cf87eaa', color: '#444' },  // Mehr Grün
    '&light .cm-readability-1': { backgroundColor: '#88f98daa', color: '#444' },
    '&light .cm-readability-2': { backgroundColor: '#95fa93aa', color: '#444' },
    '&light .cm-readability-3': { backgroundColor: '#a1fb99aa', color: '#444' },
    '&light .cm-readability-4': { backgroundColor: '#adfca0aa', color: '#444' },
    '&light .cm-readability-5': { backgroundColor: '#f4f4a8aa', color: '#444' },
    '&light .cm-readability-6': { backgroundColor: '#f8c576aa', color: '#444' },
    '&light .cm-readability-7': { backgroundColor: '#fc9743aa', color: '#444' },
    '&light .cm-readability-8': { backgroundColor: '#ff6911aa', color: '#444' },
    '&light .cm-readability-9': { backgroundColor: '#ff3b00aa', color: '#444' },
    '&light .cm-readability-10': { backgroundColor: '#ff0000aa', color: '#444' },  // Rot

    '&dark .cm-readability-0': { backgroundColor: '#7cf87eaa', color: '#ccc' },  // Mehr Grün
    '&dark .cm-readability-1': { backgroundColor: '#88f98daa', color: '#ccc' },
    '&dark .cm-readability-2': { backgroundColor: '#95fa93aa', color: '#ccc' },
    '&dark .cm-readability-3': { backgroundColor: '#a1fb99aa', color: '#ccc' },
    '&dark .cm-readability-4': { backgroundColor: '#adfca0aa', color: '#ccc' },
    '&dark .cm-readability-5': { backgroundColor: '#f4f4a8aa', color: '#ccc' },
    '&dark .cm-readability-6': { backgroundColor: '#f8c576aa', color: '#ccc' },
    '&dark .cm-readability-7': { backgroundColor: '#fc9743aa', color: '#ccc' },
    '&dark .cm-readability-8': { backgroundColor: '#ff6911aa', color: '#ccc' },
    '&dark .cm-readability-9': { backgroundColor: '#ff3b00aa', color: '#ccc' },
    '&dark .cm-readability-10': { backgroundColor: '#ff0000aa', color: '#ccc' }  // Rot
  })
];

**Comment by nathanlesage** [comment]
Indeed, this looks fine — it changes a few things (such as removing the blue and purple colors), so we'll have to announce it properly. One issue is that the dark mode font color doesn't look very well, so I'd love to find a better gray to accompany the colors (or just use a separate color scheme for dark mode). I'll have a look.

**Comment by hnsstrk** [comment]
"Sorry that I didn't provide an explanation for it. I really like the classic traffic light system. It's intuitive and, as far as I know, fairly uniform worldwide, so it doesn't need to be learned anymore.

However, I also see that the individual colors may be difficult to distinguish from each other, and it makes sense to introduce more colors.

If we stick to the color spectrum, we could start with purple or blue. However, this doesn't feel particularly intuitive to me.

So I would suggest making the red darker, which would intuitively be perceived as more red.

I will try out a few alternatives."

**Comment by hnsstrk** [comment]
First of all, here's the general fix for color display:

```
export const readabilityMode = [
  readabilityModePlugin,
  EditorView.baseTheme({
    // Define the readability classes. Red, orange, and yellow indicate bad scores
    // Purple and blue indicate average scores, and green indicates good scores
    '&light .cm-readability-0': { backgroundColor: '#7cf87eaa', color: '#444' },
    '&light .cm-readability-1': { backgroundColor: '#f67b2baa', color: '#444' },
    '&light .cm-readability-2': { backgroundColor: '#e5a14faa', color: '#444' },
    '&light .cm-readability-3': { backgroundColor: '#e3e532aa', color: '#444' },
    '&light .cm-readability-4': { backgroundColor: '#d4c1fdaa', color: '#444' },
    '&light .cm-readability-5': { backgroundColor: '#538fe9aa', color: '#444' },
    '&light .cm-readability-6': { backgroundColor: '#53bce9aa', color: '#444' },
    '&light .cm-readability-7': { backgroundColor: '#53e7e9aa', color: '#444' },
    '&light .cm-readability-8': { backgroundColor: '#4ad14caa', color: '#444' },
    '&light .cm-readability-9': { backgroundColor: '#53e955aa', color: '#444' },
    '&light .cm-readability-10': { backgroundColor: '#ff0000aa', color: '#444' },
    // Dark styles
    '&dark .cm-readability-0': { backgroundColor: '#7cf87eaa', color: '#ccc' },
    '&dark .cm-readability-1': { backgroundColor: '#f67b2baa', color: '#ccc' },
    '&dark .cm-readability-2': { backgroundColor: '#e5a14faa', color: '#ccc' },
    '&dark .cm-readability-3': { backgroundColor: '#e3e532aa', color: '#ccc' },
    '&dark .cm-readability-4': { backgroundColor: '#d4c1fdaa', color: '#ccc' },
    '&dark .cm-readability-5': { backgroundColor: '#538fe9aa', color: '#ccc' },
    '&dark .cm-readability-6': { backgroundColor: '#53bce9aa', color: '#ccc' },
    '&dark .cm-readability-7': { backgroundColor: '#53e7e9aa', color: '#ccc' },
    '&dark .cm-readability-8': { backgroundColor: '#4ad14caa', color: '#ccc' },
    '&dark .cm-readability-9': { backgroundColor: '#53e955aa', color: '#ccc' },
    '&dark .cm-readability-10': { backgroundColor: '#ff0000aa', color: '#ccc' }
  })
]

```

I took another look at the colors.  
I was surprised by how much the dark background affects color selection.  
I've revised my original idea again. Now, it only has a minor issue with "Readability 5: Slightly difficult to read. Background: #f4f4a8aa" on a dark background.

As an alternative, I shifted the colors slightly towards red. However, I quickly encountered two problems:  
"Readability 3: Average readability. Background: #c9f87caa" on a dark background is a bit hard to read, and "Readability 10: Very difficult to read. Background: #990000ff" became a self-fulfilling prophecy.

![image](https://github.com/user-attachments/assets/96ec6aef-7d74-4e1e-b465-6ae9ce10b9ba)

**Comment by hnsstrk** [comment]
3_first_idea

```
export const readabilityMode = [
  readabilityModePlugin,
  EditorView.baseTheme({
    '&light .cm-readability-0': { backgroundColor: '#4ad14caa', color: '#444' }, // Grün
    '&light .cm-readability-1': { backgroundColor: '#53e955aa', color: '#444' },
    '&light .cm-readability-2': { backgroundColor: '#7df858aa', color: '#444' },
    '&light .cm-readability-3': { backgroundColor: '#97f749aa', color: '#444' },
    '&light .cm-readability-4': { backgroundColor: '#c3f749aa', color: '#444' },
    '&light .cm-readability-5': { backgroundColor: '#ebf749aa', color: '#444' },
    '&light .cm-readability-6': { backgroundColor: '#f8e114aa', color: '#444' },
    '&light .cm-readability-7': { backgroundColor: '#fca625aa', color: '#444' },
    '&light .cm-readability-8': { backgroundColor: '#ff6911aa', color: '#444' },
    '&light .cm-readability-9': { backgroundColor: '#ff3b00aa', color: '#444' },
    '&light .cm-readability-10': { backgroundColor: '#ff0000aa', color: '#444' }, // Rot

    // Dark styles
    '&dark .cm-readability-0': { backgroundColor: '#4ad14caa', color: '#ccc' }, // Grün
    '&dark .cm-readability-1': { backgroundColor: '#53e955aa', color: '#ccc' },
    '&dark .cm-readability-2': { backgroundColor: '#7df858aa', color: '#ccc' },
    '&dark .cm-readability-3': { backgroundColor: '#97f749aa', color: '#ccc' },
    '&dark .cm-readability-4': { backgroundColor: '#c3f749aa', color: '#ccc' },
    '&dark .cm-readability-5': { backgroundColor: '#ebf749aa', color: '#ccc' },
    '&dark .cm-readability-6': { backgroundColor: '#f8e114aa', color: '#ccc' },
    '&dark .cm-readability-7': { backgroundColor: '#fca625aa', color: '#ccc' },
    '&dark .cm-readability-8': { backgroundColor: '#ff6911aa', color: '#ccc' },
    '&dark .cm-readability-9': { backgroundColor: '#ff3b00aa', color: '#ccc' },
    '&dark .cm-readability-10': { backgroundColor: '#ff0000aa', color: '#ccc' } // Rot
  })
];
```

4_going_dark
```
export const readabilityMode = [
  readabilityModePlugin,
  EditorView.baseTheme({
    // Light mode styles
    '&light .cm-readability-0': { backgroundColor: '#4ad14caa', color: '#444' }, // Green - very readable
    '&light .cm-readability-1': { backgroundColor: '#53e955aa', color: '#444' },
    '&light .cm-readability-2': { backgroundColor: '#7cf87eaa', color: '#444' },
    '&light .cm-readability-3': { backgroundColor: '#c9f87caa', color: '#444' },
    '&light .cm-readability-4': { backgroundColor: '#e3e532aa', color: '#444' },
    '&light .cm-readability-5': { backgroundColor: '#f7d023aa', color: '#444' },
    '&light .cm-readability-6': { backgroundColor: '#e5a14faa', color: '#444' },
    '&light .cm-readability-7': { backgroundColor: '#f67b2baa', color: '#444' },
    '&light .cm-readability-8': { backgroundColor: '#ff0000aa', color: '#444' },
    '&light .cm-readability-9': { backgroundColor: '#bb0000dd', color: '#444' },
    '&light .cm-readability-10': { backgroundColor: '#990000ff', color: '#444' }, // Red - very difficult to read

    // Dark mode styles
    '&dark .cm-readability-0': { backgroundColor: '#4ad14caa', color: '#ccc' }, // Green - very readable
    '&dark .cm-readability-1': { backgroundColor: '#53e955aa', color: '#ccc' },
    '&dark .cm-readability-2': { backgroundColor: '#7cf87eaa', color: '#ccc' },
    '&dark .cm-readability-3': { backgroundColor: '#c9f87caa', color: '#ccc' },
    '&dark .cm-readability-4': { backgroundColor: '#e3e532aa', color: '#ccc' },
    '&dark .cm-readability-5': { backgroundColor: '#f7d023aa', color: '#ccc' },
    '&dark .cm-readability-6': { backgroundColor: '#e5a14faa', color: '#ccc' },
    '&dark .cm-readability-7': { backgroundColor: '#f67b2baa', color: '#ccc' },
    '&dark .cm-readability-8': { backgroundColor: '#ff0000aa', color: '#ccc' },
    '&dark .cm-readability-9': { backgroundColor: '#bb0000dd', color: '#ccc' },
    '&dark .cm-readability-10': { backgroundColor: '#990000ff', color: '#ccc' } // Red - very difficult to read
  })
];
```

**Comment by hnsstrk** [comment]
Personally, I like the revised version of the first idea the best, as the average readability is still within the acceptable range.

If you'd like, I can take another look at it by starting with purple and blue, which fit well within the color spectrum.

**Comment by nathanlesage** [comment]
First of all, thanks for this amazing work. Having these various colors panned out like so makes it incredibly easy to judge it. Thank you for doing this absolutely tedious work.

Then, I completely agree with you regarding the traffic light system. If you think about it, nobody really *needs* to be able to discern, e.g., level 3 from level 4. As long as a level 6 can be distinguished from a level 2, then it's fine. So I agree that we can drop blue and purple.

Then, my main gripes was that the dark colors indeed are a bit of a hassle. I just had exactly this issue while improving the highlighting background color (`==mark==`), and usually one can get to fairly good results by simply decreasing the luminance of the color, keeping the chroma/hue the same.

I, too, like `3_first_idea (but better)` very much and I think we can keep that one for the light mode. Regarding dark mode, I think we can experiment with removing luminance from the colors. Additionally, we can increase the luminance of the text to push the two further apart of each other, thereby automatically increasing contrast.

Would you mind giving that a try? I think we're on a very good way here, and all of that thanks to your help.

**Comment by hnsstrk** [comment]
I have created a small text environment to further experiment with the colors. So far, I have lightened the text color on dark backgrounds from #ccc to #eee and darkened the readability-0 green from #4ad14caa to #3db13faa.

The link to the repository is as follows: https://github.com/hnsstrk/readability

![image](https://github.com/user-attachments/assets/654f6446-ef34-4852-b17f-4e09c8e75181)
![image](https://github.com/user-attachments/assets/ff8c7e76-c83b-4253-ae96-4c02c425330d)

**Comment by hnsstrk** [comment]
"I darkened the red for readability-10 a bit. I also made some small additions to the text page. Overall, I’m confident that I’m on the right track. It was important to me to keep some green up to readability-5. The text remains easily readable as well."

![image](https://github.com/user-attachments/assets/e0b4e96c-4d97-4e05-a20e-1b37f441ccfa)

**Comment by nathanlesage** [comment]
Looks good! Quick announcement: I have a bit more work right now, so I would be happy if you could decide on new colors by yourself and then just open a corresponding PR using them. I think the general idea is great, with a gradient from green to red, and as long as everything remains readable, I'm absolutely happy with the suggestion. Feel free to open a PR so that your work gets acknowledged in the code base (& I just have to merge it).
