### ISSUE TITLE
[ROADMAP] Zettlr 1.7

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#536]
Yes, I know, Zettlr 1.6 is still in beta and not yet released, but due to the crazy amount of enhancements and feature requests I feel it's necessary to outline the path to the future, both for you to know what will be happening and for me to have mental ease to actually ignore quite a bunch of these issues due to the following reasons:

In the past months, the functionality and codebase of Zettlr was extremely enlarged, with more and more features adding to the app. While this is incredibly cool, and I actually switched to using many of these new features in my own workflow (such as YAML frontmatters, it's such a great thing!), it has also destabilised some core modules to a frightening degree. What I'm especially referring to is two broader issues that have become quite unstable over the last few releases: the IPC (InterProcessCommunication) between server and client processes, which is, bluntly put, an utter mess. This needs refactoring fast. And the second thing is the file system. Currently, it's a monkey-patch recursive read-in of the root directories and files using only two classes. It's both ineffective, straining on computer's resources, and has become prone to errors. For example, virtual directories are, as far as I know, pretty much unusable due to a lot of mistakes and logical fallacies I accidentally introduced.

Therefore, here's what the roadmap of Zettlr for the next two releases will be:

1. Finish beta testing of 1.6, closing only bugs, and then releasing it.
2. Afterwards, I will be completely ignoring feature and enhancement requests and dedicate all my spare time to fixing the above-mentioned issues. Which means: First the file system abstraction layer, and secondly, fixing the IPC.
3. After this is done, 1.7 will be released without any major visible overhauls, but with most bugs being solved. Then, it'll be fully safe to use the sidebar without any more issues.
4. Then, in 1.8 I'll begin again to incorporate some of these issues.

You can track the status on the 1.7 Project: https://github.com/Zettlr/Zettlr/projects/2

If you really want a feature, what you can do in the meantime is discuss it on the forum with other users. The benefit? Once I'm back at integrating more features, the feature request by you will be fleshed out to such a degree that I can basically just read along and hack in the lines of code required to make it happen! Division of labor, or something :D 

Any more questions? I'm happy to answer them!

**Comment by danieltomasz** [comment]
Great plans! I just registered to the forum :)

**Comment by Zverik** [comment]
Happy to see a planned future for the editor! All is clear now, it bothered me a bit that with the constant stream of issues you might have had little time to keep looking at the bigger picture.

One question: what would you do with pull requests until releasing 1.7?

**Comment by nathanlesage** [comment]
Yeah, I have only fixated on issues lately, which is why this happened in the first place. I'm really bad at simply ignoring such issues, but I have to in order to make Zettlr scale up much more.

Concerning PRs: It really depends. If they're small and/or super easy to understand and approve, I'll certainly manage to include them. But what they shouldn't address is **anything** that somehow relates to the file system or make use of the IPC, because this would mean additional workload for me when I knit in the new modules.

What I could really need help with is someone who cleans up the LESS files, fixes some design issues, has a look at the window behaviour on Linux and stuff. I mean I could certainly produce a list of issues that other people could solve while I hack together the two big modules? This would certainly help A LOT :)

**Comment by danieltomasz** [comment]
Talking about search algorithm, maybe more efficient would be use of external search  (like the silver searcher, this one is on the apache license https://github.com/ggreer/the_silver_searcher)

**Comment by nathanlesage** [comment]
I see the appeal of that, but that would require significant work, as anything using native code has to be transformed into a native node module. I've never done this (would be a nice exercise, though!)

Certainly something for a later improvement! :)

**Comment by Sklanfurt** [comment]
Dear Nathan, 
is the Bug that initiates complete Data loss (Issue #493) already fixed, or on your list for version 1.6? I recently recommended Zettlr to some of my fellow students and academic researchers, but now I am not sure if I can still use the App by myself, when it is possible that it loses data again. 
Greetings, 
Simon

**Comment by nathanlesage** [comment]
Hey @Sklanfurt , if you refer to the one that was also mentioned [here](https://github.com/Zettlr/Zettlr/issues/513), then yes, Zettlr should now don't exhibit this weird behaviour anymore! Fixed it this afternoon

**Comment by Sklanfurt** [comment]
> Hey @Sklanfurt , if you refer to the one that was also mentioned [here](https://github.com/Zettlr/Zettlr/issues/513), then yes, Zettlr should now don't exhibit this weird behaviour anymore! Fixed it this afternoon

This is indeed a part of the solution. Somehow, Zettlr also did not autosave the file for some days (I have not shut down the computer in this time, so probably everything I wrote was in the RAM) and after selecting "Proceed without saving" I lost two days of work.

**Comment by nathanlesage** [comment]
Then please use the latest 1.6 beta. Besides, if something like this happens, why did you not copy over the file contents into another editor, see what happens WiTHOUT losing your work? I don't quite understand this.

**Comment by Ziinc** [comment]
> Then please use the latest 1.6 beta. Besides, if something like this happens, why did you not copy over the file contents into another editor, see what happens WiTHOUT losing your work? I don't quite understand this.

I think it is due to the fact that there is no indication of saving, which @Sklanfurt had assumed was occurring in the background.

**Comment by Zverik** [comment]
I don't think it's stale until 1.7 is released.

**Comment by nathanlesage** [comment]
Didn't notice the stale thingy :D Thanks @Zverik — however, unpinning for now because I need space at the issue list top!

**Comment by tobiasdiez** [comment]
I think this can be closed now (and the 1.7 Project be archived).
