### ISSUE TITLE
duplicating File does not work

### ISSUE THREAD

**Issue by nannus12** [Zettlr/Zettlr#5360]
### Description

when i rightclick a file in the file overview bar and select duplicate file it does nothing. Bug is not existend on previous versions e.g. 3.0.5

### Reproducing

- Have Version 3.2.0 of Zettlr installed
- try to duplicate a file in the file overview via rightclick menu

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Installation Method (Other)

Windows Installer on Windows 11

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11

### Additional Information

Thanks in advance, and thanks for Zettlr and your great work!

**Comment by pointout** [comment]
I can confirm, that this is not working. (I am also on Windows 11/Intel 64bit)

**Comment by ngataringa** [comment]
v3.2.2 - 'Duplicate file' on right click option not working for my either (Linux Mint).
