### ISSUE TITLE
It is possible to add to Zettlr Pascal syntax in Fenced code blocks?

### ISSUE THREAD

**Issue by fabvit** [Zettlr/Zettlr#5368]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

It is possible to add to Zettlr the Pascal syntax in Fenced code blocks?
I have read the documentation and,under Fenced code blocks, where it says "More languages can be implemented on your request. If you need a specific language, please [refer to the available ones](https://codemirror.net/mode/) and open up an issue on GitHub, so that we know which one we should add!"
I checked and in the CodeMirror language modes page I can see that the Pascal is listed here.
I think it would be useful for Pascal developers to have syntax highlighting.
Thank you in advance 

### Example Workflow

just add Pascal syntax highlighting 

### Caveats

there are no caveats.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
Found it in the Legacy mode package (https://github.com/codemirror/legacy-modes), so this should be easy to add.

**Comment by fabvit** [comment]
Thank you Nathan!
I have cloned on my pc the Zettlr 's repo and digged it. But I am not familiar with the codebase so I am more than happy that you added my request to the Zettlr's Roadmap.
Thank you: I have started using Zettlr this summer an now I use it to document my Pascal project: fantastic.

**Comment by fabvit** [comment]
Thank you Nathan!
