### ISSUE TITLE
"How can I contribute?"

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#538]
Hello everyone,

as mentioned before, I am both happy and overworked with the incredible amount of good new issues that have been popping up in the past days alone. This shows me that this app is becoming better and better, and that it actually helps many people and sometimes motivates them to even help out — there have been some very cool PRs on the repository which I gladly merged, and which is why I decided to open this issue.

As mentioned by @zverik in [this comment](https://github.com/Zettlr/Zettlr/issues/536#issuecomment-585270976), the question is: What can other people do while I blatantly ignore all those good feature requests on the issue tracker while I work on the two huge core-modules that need to be in place for many issues to be solved quite easily?

This issue focuses on what contributors can do during the next months to push more and more features into the app!

## So, how can you help?

I will compile a list of issues here that can be tackled without having to worry about interfering with the proposed new modules, that is: They don't run in danger of being overwritten again when I place the new modules into the core of Zettlr.

Issues can generally be tackled in a PR which I'll then merge, if the following simple requirement is fulfilled: They don't touch any of the classes that _will_ be removed during the refactoring:

- `ZettlrIPC`
- `ZettlrFile`
- `ZettlrDir`
- `ZettlrVirtualDir`
- `ZettlrFilter`
- `ZettlrRendererIPC`
- potentially other ones, I'll add them as soon as I detect them -- feel free to ask in this issue with a comment, if a certain class is "safe" or should be added here! :)

**Update May 2020**: The respective files have now been deleted in the develop branch so it should be safe again!

This means, for instance, the Snippets-Issue cannot be tackled as this will require the new IPC module :(

## Where you can generally _always_ help

- Refactoring the LESS files (reorganisation is very welcome, as there's not much of a structure right now)
- ~~There's the need for a new Icon set. It can be either SVG or a Font-file. But it needs to be compatible to GNU GPL v3. I don't want Fontawesome, for that matter.~~ See https://github.com/Zettlr/Zettlr/issues/719 for more information.
- ~~Look at the window decoration on Linux distributions (I am thinking of re-adding the frame to Linux windows)~~ Default decorations coming back
- ~~Fixing the Virtual Scroller in the Vue-sidebar component so that it doesn't need to be emptyed out every time a new file list comes from main~~ Fixed
- Shortcuts, small usability stuff, in general everything that only pertains the GUI
- Write more Unit tests for all helper functions residing in `./source/common/util`

## What you can help with specifically (issue list)

- Devise an API that can afterwards be implemented with callbacks #140, please ping me via mail or Twitter for more infos!
- #178 because it does not involve new IPC calls but can use existing ones
- #179 
- #284 maybe?
- ~~#268~~ 
- #275 
- #284 
- ~~#316~~
- #329 
- [More will be coming once I've time again :D]

I'll be also adding a linting test soon, so that the resulting PRs pass the ESLint (JSStandard with the custom rules specified in `.eslintrc`)

In case of questions, please feel free to ask as always!

Cheerio :heart:

**Comment by Wieke** [comment]
> There's the need for a new Icon set. It can be either SVG or a Font-file. But it needs to be compatible to GNU GPL v3. I don't want Fontawesome, for that matter.

The [feather](https://feathericons.com/) icon collection is a possibility. It's released under the MIT license which is, as far as I understand it, GNU GPL v3 compatible.

**Comment by lol-russo** [comment]
I'm happy to work on migrating the project to using SVG icons rather than Icon fonts if @Wieke isn't already looking into it? I think Feather is an awesome choice!

**Comment by Wieke** [comment]
@lol-russo I was looking into it but ran into the issue that feather doesn't have all the icons we need (it's [lacking text formatting icons](https://github.com/feathericons/feather/issues/766) and project seems slow to process pull requests). Maybe the [bootstrap icons](https://icons.getbootstrap.com/) are a viable alternative? They're also released under a MIT license and despite being "alpha" seem more complete that feather.

**Comment by nathanlesage** [comment]
I'd be glad if someone took up that task of finding and testing out some icons :)

**Comment by Wieke** [comment]
@nathanlesage I'll pick it up. (Figured out to replace the existing icons with svg images already anyway. The harder part is figuring out what exact images to replace them with.) Do you want me to open a proper issue for this? Or should I leave that to you?

**Comment by nathanlesage** [comment]
@Wieke Feel free to open up issues as necessary for this! Isn't there already an issue open where we discussed the icon-issue? If not, feel free to open up a new one!

Basically, what we'd need to do is decide on a good icon set and then simply exchange the font-stuff in the LESS files … should be not that much work, the harder part is preparing mockups. Albeit, wait. It might make more sense to just take any SVG-set, implement that one, make a screenshot and then take one or two alternatives, implement them as well (as it SHOULD only consist of replacing some paths in the LESS files) and make some screenshots so that we can vote on them … except there are no alternatives, in which I'd gladly follow your choice!
