### ISSUE TITLE
[BUG] Zettel links are not closed

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#539]
## Description

I turned off Code Mirror's "Automatically close matching character pairs" because it is pain to type backticks code pairs with that.

Now when I type `[[`, choose a note from the list and press Enter, I get something like `[[20200212223908 coastline-validator` — file name is set, but note that there are no closing `]]`.

## Reproducing

1. Disable "Autoclose matching pairs" in Configuration → Editor.
2. Type `[[` in a note.
3. Choose a file.

## Expected behaviour

Something like `[[12039123longid123123]] file name`.

Actual: `[[2334234234234 file name`.

## Platform

 - OS and version: Fedora Linux 30
 - Zettlr Version: 1.6.0beta3 (built from the develop branch a minute ago)

**Comment by nathanlesage** [comment]
Aaaand here we go!
