### ISSUE TITLE
Paste should respect user-selected formatting characters for bold and italic.

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#5396]
### Description

If the user sets `Preferences > Editor > Formatting characters for bold and italic` to the underscore option, pasted rich-text content with italics should be marked up with underscores rather than asterisks.

Currently, pasted content that includes italics is marked up with asterisks, even when the formatting characters are set to underscores.

For that matter, any formatting characters that the user sets in the `Preferences` menu should be respected when content is pasted from the clipboard.

### Reproducing

See above.

### Zettlr version

3.2.1-nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Manjaro (Rolling)

### Additional Information

Thanks, as always!

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
