### ISSUE TITLE
Visual glitch in which find-replace flyout covers export menu.

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#5397]
### Description

When the find-replace flyout is active and the user subsequently selects the `Export the current file` icon, the export dropdown menu is obscured by the find-replace interface. Here's a screenshot:

![Screenshot from 2024-09-27 13-24-35](https://github.com/user-attachments/assets/8838ef3e-c26d-4765-a4e4-a8907dfdc20d)

### Reproducing

Type `Ctrl-f` to activate the find-replace flyout interface. Then click the `Export the current file` icon to reveal the export dropdown menu.

### Zettlr version

3.2.1-nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Manjaro (Rolling)

**Comment by nathanlesage** [comment]
That should be an easy fix with z-indices
