### ISSUE TITLE
Line following a blockquote should not be auto-quoted.

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#5398]
### Description

When I include a block quote in my writing — e.g.,

```
> Far from these occasions demonstrating the limitless independence of the Corporation, they reveal
   instead the extent to which the BBC is an important vehicle for capturing disagreements that percolate
   down from establishment sources. [@freedmanPublicServiceJournalism2019, 211]
```

…it's very rare that I want the subsequent paragraph to also be a block quote. So, when I type `Enter` at the end of a paragraph quoted with the `>` character, the next line should not include the `>` character by default. Currently, the opposite is true. When I hit `Enter` after typing a block quote, a quote character is automatically inserted on each subsequent line. E.g.,

```
> Far from these occasions demonstrating the limitless independence of the Corporation, they reveal
   instead the extent to which the BBC is an important vehicle for capturing disagreements that percolate
   down from establishment sources. [@freedmanPublicServiceJournalism2019, 211]
>
```

This is irksome, because I then have to delete the `>` character before I can begin typing again.

### Proposed Changes

Change the default behavior, such that when a user hits `Enter` at the end of a quoted paragraph, the next line does not include an initial `>`. 

### Caveats

If some users find this useful, perhaps the default behavior could be toggled in the `Preferences` menu.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro (Rolling)

**Comment by nathanlesage** [comment]
Quick question: does the block quote go away if pressing enter twice? Because that is how its meant to be (lists afaik don't do that right now and it drives me crazy, too)

**Comment by wideaperture** [comment]
Hmm. Sort of. You have to press `Enter` _three_ times. So if I have…

```
> Just a test.|
```

…and hit `Enter` once, I get…

```
> Just a test.
> |
```

Hit `Enter` twice, you get…

```
> Just a test.
>
> |
```

Hit enter *three* times and you finally get…

```
> Just a test.

|
```

(Where the `|` character above represents the cursor.)

**Comment by nathanlesage** [comment]
Hmhmhmhm … I can actually see why CodeMirror would do that: Blockquotes are block-level syntax that allow any other block-level syntax inside of them. So you could write the following:

```md
# Some heading

Some text

> This is a blockquote. It can contain **inline** syntax just fine.
>
> ## But, as you can see
>
> It can contain
>
> * entire
> * chunks
> * of text.
```

Pressing Enter three times makes sense from that perspective: The first time, it allows you to continue your block quote. The second time allows you to insert a blank line to separate blocks within the quote. And only on the third time will it break out of the blockquote.

I do agree that writing block-level things in quotes I use fairly rarely myself. I have the hunch that the same applies to probably most people, but it would be good to confirm this with a quick and dirty survey on Discord …

**Comment by wideaperture** [comment]
I’m actually much more cool with this note that I understand the behavior. Before I kept getting hung up on the quote being carried over and would start editing it out. Now that I know I can just hit enter three times, it’s no big deal.

**Comment by nathanlesage** [comment]
Hah, alright, to the benefit of keeping resources free then let's close this -- but maybe if you have the time feel free to explicate this in the documentation!
