### ISSUE TITLE
Trace/breakpoint trap (core dumped) using Ubuntu (24.04) .deb

### ISSUE THREAD

**Issue by thekswenson** [Zettlr/Zettlr#5406]
### Description

I get the following message when trying to open zettlr:

```
=> zettlr 
Trace/breakpoint trap (core dumped)
```

### Reproducing

Install Zettlr 3.2.1 on Ubuntu 24.04.
Try to open zettlr.

### Zettlr version

3.2.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Ubuntu 24.04

**Comment by nathanlesage** [comment]
This is unfortunately a bit too little info to make an informed decision. Usually, however, those deep system-level errors indicate an issue between the operating system and the underlying Electron framework, nothing that we could fix on our end (except waiting for an Electron update).

**Comment by thekswenson** [comment]
OK... 3.2.2 works on Ubuntu 23.10, so like you said there is something strange with the dependencies. I guess we'll consider this an upstream bug.
