### ISSUE TITLE
Image corrupted during Copy/Paste into zettlr

### ISSUE THREAD

**Issue by thekswenson** [Zettlr/Zettlr#5408]
### Description

Copying a .png in gnome file manager no longer works as expected. The paste dialog is properly opened, yet the image in empty and the .png that is copied into the folder has 0 bytes:

Pasting an image like so
![Screenshot from 2024-10-01 13-44-06](https://github.com/user-attachments/assets/ce6a435e-26ae-4ebd-98f5-223b65fd0846)

yields a document like this one:

![image](https://github.com/user-attachments/assets/50eaf078-c5b2-47be-9036-9aafa3e47c83)

### Reproducing

1. go to the "File Manager" (aka Nautilus) and copy a .png image.
2. in zettlr, paste the image

### Zettlr version

3.2.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Ubuntu 23.10

**Comment by thekswenson** [comment]
This is similar to the closed bug https://github.com/Zettlr/Zettlr/issues/5026

**Comment by nathanlesage** [comment]
I bet there have been some weird changes to the clipboard API in the most recent Electron or Chromium versions that cause all of these things to fall over. I'll have a look.

In the meantime, please try all of these ways of inserting images into Zettlr:

* Drag and drop from Nautilus into a document
* Drag and drop from the sidebar into a document
* Copying a file in Nautilus and pasting it
* Copying image data into the clipboard (e.g., via screenshot) and pasting this

Other parts may also have fallen over so it helps to know what doesn't work anymore.

**Comment by thekswenson** [comment]
> In the meantime, please try all of these ways of inserting images into Zettlr:
> 
>     * Drag and drop from Nautilus into a document

This copies the text that is the path of the document.

>     * Drag and drop from the sidebar into a document

I'm not totally sure what you mean by this, but if I open the sidebar and choose the "Other files" tab, then I can drag a PNG from the current folder into the current doc. This works as expected.
 
>     * Copying a file in Nautilus and pasting it

This is the case reported in the bug.
 
>     * Copying image data into the clipboard (e.g., via screenshot) and pasting this

This works as expected.

**Comment by nathanlesage** [comment]
Perfect, thank you very much. This indicates that the issue is not something intrinsically related to how Zettlr handles images, but rather to the way Nautilus represents files in the clipboard. One final step now: Please take an image and copy it in Nautilus. Confirm that it doesn't work in Zettlr, and then paste it into the following website: https://evercoder.github.io/clipboard-inspector/

Please share the info that the website gives you (feel free to modify sensitive information) here so that we can see what exactly Nautilus writes into the clipboard. With that information, it should hopefully be simple to fix.

**Comment by nathanlesage** [comment]
Thank you, I'll get to it. In the meantime I was able to properly reproduce this behavior on my side as well — including the realization that dragging and dropping images doesn't work at all on my side at all right now.
