### ISSUE TITLE
[ENHANCEMENT] Global search over the full file tree

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#541]
## Description

When searching by a tag or by id, results are displayed in a sidebar. But when searching by a file name, there are no results in the sidebar — regardless of whether the note was found.

## Reproducing

1. Have a file named `note.md`, for example, without an id in the file name (it can have one inside).
2. Switch to a different note.
3. Type "note" inside the search bar.

The note will be opened, but the sidebar will be empty.

When typing "not" (part of the file name), the note would not be found, and the sidebar would be still empty.

## Expected behaviour

I expected the editor to search notes by file names as well.

![Screenshot 2020-02-13 at 10 49 16](https://user-images.githubusercontent.com/766031/74412679-06b30580-4e4f-11ea-9cd0-5559c6f2b7c6.png)

↑ here I have a file named `ptv3.md`.

## Platform
 - OS and version: macOS 10.14.5
 - Zettlr Version: 1.6.0 beta2

**Comment by nathanlesage** [comment]
Sounds like a bug in the search engine

**Comment by nathanlesage** [comment]
Hey, I can't reproduce this one currently. Maybe it's been fixed in 1.6.0-beta.4…? Would you mind checking?

**Comment by Zverik** [comment]
Okay, got it. The issue is about another thing. This `ptv3` file resided in a different folder under root, other that the currently opened one. Consequently, it was found by a full file name, but neither partial file name, nor searching by tags (that were used in another folder only) produced any results in the sidebar.

Can you make the global search root to be the current root, not current dir?

**Comment by nathanlesage** [comment]
This would be counter-intuitive. To spoil some future GUI things: It has consistently been reported to me that people wish the global search to reside in the file bar, and NOT the toolbar, which will couple it even more to what you see. Hence: Global means: "Everything in the file list"

**Comment by Zverik** [comment]
Oh :(

Then this won't work with my notes directory system, which is simply "split notes by years". I click on a tag — and instead of all notes for that tag, I get only matching notes from the current directory. What is the purpose of tags then.

Could you please make an option somewhere to search in the entire tree instead of the current directory? It would help me a lot.

**Comment by nathanlesage** [comment]
Doesn't it help to select the root before triggering the search? I also tend to have a lot of directories, therefore having only that one searched actually helps a lot!

**Comment by Zverik** [comment]
Well, I could — but it's four clicks extra: 2 for changing the directory, then click on a tag to find all notes with that tag, do what I needed to do, then clear search, and 2 clicks to return to the directory I've been. Every time I need to find notes.

Since the expectation differs, I'd have this as a configuration option.

**Comment by nathanlesage** [comment]
Hm, yes. I'm currently thinking something as the GitHub search bar, which lets you choose to search the current repo, or all of GitHub

**Comment by Zverik** [comment]
Yes, this could help. But — this also applies to Alt+Clicks on tags, which is not expected to trigger a popup menus. Maybe at least tag searches could be made global, like id searches?

**Comment by nathanlesage** [comment]
Mh, I don't want to introduce too many ifs and elses to the search functionality, I'd rather keep it simple … but maybe I can add a small switch to the search field, which allows you to switch the search mode! Then it'd also be persisted, which might make it even easier

**Comment by doxavore** [comment]
> something as the GitHub search bar, which lets you choose to search the current repo, or all of GitHub
> ...
> add a small switch to the search field, which allows you to switch the search mode! Then it'd also be persisted, which might make it even easier

@nathanlesage I love this idea so much. I organize my notes into a few subdirectories, and the linking by ID works fine, but search is pretty painful for me right now. I'd really like a persisted option to search globally or in my current directory.

Have you given this any more thought or started work on it? I'm happy to contribute, though if you have any specific approaches you'd like to take in its implementation, perhaps we could connect before I started it?

**Comment by nathanlesage** [comment]
Hey, I've not begun working on it, but it might be worth a shot! If you'd like to implement it, we can surely talk about it — I can give you a heads up of how it's done currently, what I personally don't like at the approach and if you'd like to contribute, I'm more than happy!

**Comment by nathanlesage** [comment]
Duplicate of #316 — closing that one in favor of this.
