### ISSUE TITLE
Right click on a file in the sidebar selects a word

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#542]
## Description

When I right-click on a file in the file list, a word under cursor in the opened note is selected.

## Reproducing

1. Open a non-empty note.
2. Right-click on a file.

The first word of the note (or where the cursor was) gets selected.

## Expected behaviour

I did not expect any state changes. This feels a small bug, but may lead to unexpected bigger consequences: e.g. if an event is not contained, then you don't know which kind of events could go to the main window.

## Platform
 - OS and version: macOS 10.14.5
 - Zettlr Version: 1.6.0 beta4

**Comment by nathanlesage** [comment]
Nah, it's not that it's not contained, don't worry, it's just a small bug! And, above all, fixed!
