### ISSUE TITLE
Option to use ordinal date (day of the year) as Zettelkasten ID

### ISSUE THREAD

**Issue by marleschingus** [Zettlr/Zettlr#5424]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

It is common to use date-based Zettelkasten IDs. It would be nice to have the option to use the ordinal day (day of the year) as a variable in the pattern used to generate new IDs.

One reason to use ordinal date (padded) instead of month and day is to shorten the ID, as the ordinal date uses 3 digits, while month and day together use 4.

I talked to @nathanlesage on discord, who said that ordinal date is supported by the date library, it just needs implemented in Zettlr.

### Example Workflow

An example pattern used to generate new IDs that incorporates ordinal date (padded) could look like this: %y%ooo%h%m

The resulting date-based ID would look something like this: 242861345

### Caveats

No caveats.

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

### Additional Information

Attaching a few screenshots from the discord conversation:

![image](https://github.com/user-attachments/assets/e75d21d6-da87-4d40-a0d8-23fd1419b987)

![image](https://github.com/user-attachments/assets/eaf44a14-cfa8-487b-88cf-8f0fd6d6c073)

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
