### ISSUE TITLE
No selected-text color in typewriter mode

### ISSUE THREAD

**Issue by seldstein** [Zettlr/Zettlr#5430]
### Description

https://github.com/user-attachments/assets/9cf47520-1ab3-4825-b5b8-195b036a7ad3

### Reproducing

Turn on typewriter mode and select some text.

### Zettlr version

3.2.2 (3.2.2)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Sonoma Version 14.6.1

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
