### ISSUE TITLE
Files not displayed beyond 3rd nested directory in file manager

### ISSUE THREAD

**Issue by michmzr** [Zettlr/Zettlr#5442]
### Description

No files are displayed in file manager if files sits beyond 3rd nested directory
![image](https://github.com/user-attachments/assets/a9368d7b-5844-4065-9320-7898fe184f7b)

### Reproducing

Add workspace with nested directories - at least 3 levels, then add files in last levels

### Zettlr version

3.0.5 

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Sequoia 15.0.1 (24A348)

**Comment by nathanlesage** [comment]
First, the file manager currently only shows files Zettlr can actually open -- a JPEG file should show up in the other files tab of the right sidebar. Second, could you confirm whether a Markdown file created there shows up?

**Comment by michmzr** [comment]
Hi Nathan,

Yes, I confirm. I did some testing and the markdown files are showing up in very nested directories. 
It's confusing to me that the file explorer doesn't show all the files in the directories.

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
