### ISSUE TITLE
Default image name is not unique anymore

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#5449]
### Description

When pasting an image, the default image name is simply "image.png" instead of a unique ID:

![image](https://github.com/user-attachments/assets/29a35beb-ebb4-4b9d-bf99-96c79ded3605)

### Reproducing

Take a screenshot, or copy an image and paste it into Zettlr. Then check the "A unique filename" field.

### Zettlr version

3.2.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
Do you have a computer lying around whose regionale settings are completely in German? If so, would you mind looking if the image name then is still "image.png", or if Electron localizes this name (it's the default "file name" if there is no file)? If not, I just fixed that, otherwise we'll have to find the localization of that …

**Comment by standekker** [comment]
Can confirm I'm having the same issue, running Ubuntu 22.04.

**Comment by lcsolano** [comment]
I confirm this happens in both Linux and Windows 10. Locale of both computers: English US.

**Comment by nathanlesage** [comment]
I need someone with a NON-US locale setting to confirm that it's still `image.png` (or whether it might be `Bild.png` on German computers, etc.).

Once someone confirms, I have a fix ready to commit.

**Comment by lcsolano** [comment]
I installed a VM with Lubuntu, locale/language Spanish/Costa Rica, and I confirm it happens:

![image](https://github.com/user-attachments/assets/d7663c1b-5b11-4b08-a678-b420a4fcda9c)

**Comment by nathanlesage** [comment]
Thank you @lcsolano ! Then I'll quickly merge my fix for that.
