### ISSUE TITLE
[FEATURE] Highlight notes to which there are no links

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#545]
## Description

Since the idea of Zettelkasten is to have a wiki-like structure, where knowledge is linked together in a network, "detached" notes are incorrect: they should be mentioned in other notes, e.g. in an outline. I'd like to have a simple way to find all detached notes for processing.

## Example Workflow

1. Quickly create multiple notes e.g. when reading a book.
2. Press a button to show only detached notes.
3. For each note, find its place in the knowledge graph, and add relevant links.

## Caveats

This might be slow, since building a linked graph from all the notes takes much resources.

## Additional Information

This can be done in multiple UI ways. The simplest to implement would be adding a button or a menu item, or even just a shortcut. The most practical — mark such notes in a sidebar, alongside their id and tags.

**Comment by nathanlesage** [comment]
> This might be slow, since building a linked graph from all the notes takes much resources.

Well, this is one of the mid-term goals for Zettlr. Yet, it might take up to a year, until it might be integrated. It will come, but no promises as to when ;)

**Comment by Zverik** [comment]
I still think it would be nice to have.
