### ISSUE TITLE
Figures rendered on top of existing text

### ISSUE THREAD

**Issue by BabakFarshchian** [Zettlr/Zettlr#5465]
### Description

When I insert a figure in a file, the rendered figure covers text that is already in the file right after the location of the figure.

![image](https://github.com/user-attachments/assets/57baab6c-9a95-4323-8f40-7f12f5b6b0d6)

### Reproducing

Insert a figure in a file. It seems like it only happens when the figure is high.

### Zettlr version

3.2.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11

**Comment by Carnivorg** [comment]
I also had this problem today when inserting a very tall image, also using Windows 11 and Zettlr 3.2.3.

**Comment by asmibug** [comment]
Same problem with images covering text, Zettlr 3.2.3 on Linux. Images are now rendered larger than in the previous version I used (3.2.0), but the space reserved for them is the same.

**Comment by pausanias123** [comment]
Hello, 
I have the same problem with mac OS Sequoia 15.1 and Zettlr 3.2.3 (it was working fine with 3.2.2). 
Thank you :-)
