### ISSUE TITLE
[ENHANCEMENT]Make MagicQuotes cancelable

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#547]
## Description
When MagicQuotes are enabled, we cannot enter ASCII quotations any more, right?
(e.g. 
![image](https://user-images.githubusercontent.com/15438757/74657262-335e7880-51d3-11ea-899d-df4e6632a42c.png))🤷‍♂ 

## Proposed Changes
Make it cancellable with `cmd/ctrl+z`. (Just like MS Word)
That is, typing `"`→`ctrl+z` will display `"` (not `„`).

## Caveats
N/A

## Additional Information
MS Word is clever, and will choose an apostrophe depending on the situation.
![ms_word_magic_quote](https://user-images.githubusercontent.com/15438757/74658285-483c0b80-51d5-11ea-987a-2e54553848dd.gif)
It would be even better if this were possible with Zettler.

**Comment by nathanlesage** [comment]
Yes, you're right. I haven't done it right now, because I still have to figure out an efficient way to actually create two separate history events for this. But therefore I'll keep it open!

**Comment by nathanlesage** [comment]
Works now! Simply press `Backspace` after a MagicQuote was inserted to reset that to a regular quote (either single or double).
