### ISSUE TITLE
Drag & Drop Image doesn't work anymore after update to 3.2.2

### ISSUE THREAD

**Issue by francescapinton** [Zettlr/Zettlr#5475]
### Description

I used a lot the picture "drag and drop" on a document, which would create a relative link to the image location. I especially liked that I could do it with multiple pictures at the same time.

I have now updated Zettlr from 2.8 (I think) to 3.2.2 and this feature doesn't work anymore. Nothing happens when I drag and drop the picture. The only way to insert one seems now to be copy and paste the whole picture or the absolute path, after typing ![]() or using the "insert image" button (somehow the shortcut Ctrl+Shift+I also doesn't work for me).

I really liked the fact that the path was relative and that one didn't need to type, but only drag it on the document. Can I somehow restore this functionality?

### Reproducing

Drag and drop a picture from the File Explorer to a markdown file in Zettlr.

### Zettlr version

3.2.2

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Okay, maybe I should've looked closer: https://www.electronjs.org/docs/latest/api/web-utils
