### ISSUE TITLE
[BUG] JavaScript Error: Could not find child inside array to remove

### ISSUE THREAD

**Issue by ChristianNext** [Zettlr/Zettlr#548]
## Description
Fresh install of Zettlr on Ubuntu 19.10 throws exception while exporting one of my projects. Other projects run fine. Issue with 1.5.0 and 1.6.0 beta.4

## Reproducing
Export a project consisting of four files and an image directory. The PDF is generated fine. But I need to click away the pop-up error 10 times.

## Expected behaviour
Generate the PDF without errors.

![Screenshot from 2020-02-17 23-08-46](https://user-images.githubusercontent.com/29887671/74691765-fc409500-51db-11ea-8e44-947c6838ea6e.png)

## Platform
 - OS and version: Ubuntu 19.10
 - Zettlr Version: 1.5.0 and 1.6.0 beta.4
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
So you're exporting a project and it throws this error? I think I have an idea where this comes from.

**Comment by nathanlesage** [comment]
It was not a critical error, but I just made life a little bit easier -> instead of throwing the error, it's now logged with some useful information, in case this becomes a hassle, which I do not hope.
