### ISSUE TITLE
Images over the text

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#5482]
### Description

When you include an image, the text after the image is covered and you can not see it. Zettlr shows the image and this is not aligned in a way that you can read any text after the image.

### Reproducing

* Include an image
* Write text after the image
* When the code for the image renders, the cursor is under the image and you can not see what you are writing

### Zettlr version

3.2.3

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Ubuntu 22.04.2 LTS

### Additional Information

Many thanks!

**Comment by nathanlesage** [comment]
Fixed a few days ago in #5482.
