### ISSUE TITLE
Image obscuring text

### ISSUE THREAD

**Issue by digbyphonic** [Zettlr/Zettlr#5484]
### Description

1248 x 754 image with caption has existing text including a ### heading hidden behind it

### Reproducing

7 lines of text hidden behind 1248 x 754 image.
Previously the image did not obscure the text.

## heading
[[backlink]]
image (with caption)
at least 7 lines of text hidden behind image

### Zettlr version

3.2.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

windows 11 Pro 23H2

**Comment by nathanlesage** [comment]
Fixed only a few days ago in #5465.
