### ISSUE TITLE
Spell check decorations moves one whitespace to the left

### ISSUE THREAD

**Issue by gieselbusch** [Zettlr/Zettlr#5494]
### Description

The decoration of a wrong spelled word covers one white space before the word and leaves the last letter out sometimes. This even leads to the effect, that the last letter is left if the word is added to the dictionary.

### Reproducing

The effect somehow is connected to paragraphs containing words which are marked bold or italic. By changing the style of some words the effect can be triggered in both ways. It turns out, that two style changes are need inside one paragraph. The first needs to be before the word and the other after.

### Zettlr version

3.3.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Linux: Debian Bookworm

**Comment by gieselbusch** [comment]
Please find the video demonstrating the bug in this folder inside my private cloud: [screenrecoder zettlr](https://c.1und1.de/@809612886346308493/W3MNN7T-Ssyh0L91SLVSpg)
The link is valid until 21.12.2024.

**Comment by nathanlesage** [comment]
Interesting, I would've thought if something shifts spell corrections around, then it would be formatting *before* the affected position.

Anyways, I suspect there is some issue in the Plain text extraction mechanism that doesn't properly account for all offsets (see https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/linters/spellcheck.ts)

**Comment by nathanlesage** [comment]
Further observations:

1. I could reproduce the issue.
2. When there is one italic span in the sentence, it works (test sentence: `This iss a *file* with two tpyos in here. asdaa ss adas word word.`)
3. When there is a second one, however, the bug occurs: (`This iss a *file* with two tpyos in here. asdaa *ss* adas word word.`)

I currently suspect an issue with how the nodestarts are calculated for the nodes in the AST parser.

**Comment by nathanlesage** [comment]
Took some more digging, but I think I fixed the underlying cause.

**Comment by gieselbusch** [comment]
Thank you very much! I had a look at the file you linked. But solving this problem was way beyond my skills.
