### ISSUE TITLE
Footnote quotation bug (with workaround!)

### ISSUE THREAD

**Issue by micapam** [Zettlr/Zettlr#5507]
### Background

Situation is that I am at very late stage of my PhD candidature and exporting my exegesis from a large markdown file, which I've written using Zettlr, to an ODT with hundreds of footnotes. 

### Repro steps:
- Open Zettlr settings
- In the default tab, set Zettlr locale ('Application language') to en-GB ('English (United Kingdom)')
- Export document
- Look at the footnotes

### Expected outcome:
- Titles of journal articles should appear wrapped in single quotation marks, as per British English, e.g.:
```
Koch and Oesterreicher, ‘Language of Immediacy’, 451
```

### Actual outcome:
- Titles of journal articles appear wrapped in double quotation marks, which is wrong/american:
```
Koch and Oesterreicher, "Language of Immediacy", 451
```

### Thoughts

From what I've read on Zettlr forum posts (lost the URL, apologies), setting 'Application language' ought to be enough to ensure the output is correct. My OS locale is also en-GB. And when I look at a preview of the CSL (one of the built-in Chicago ones), I see the footnote shown correctly with single quotes. It's only when I export that I get the double quotes. 

I think this is either a bug that needs to be fixed, or there's a missing bit of documentation that explains how to export correctly. However, I did find an easy workaround, so probably not an urgent bug to fix. Describing it here so that anyone looking up this bug will see:

### Workaround 😁

Adding the locale in the YAML frontmatter fixes this problem, thus:

```
---
lang: en-GB
---
```

Once the markdown has this bit of frontmatter, Zettlr exports the document correctly with single quotes in the footnotes 🎉

### Zettlr version

3.0.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Sonoma 14.6.1

**Comment by nathanlesage** [comment]
Fingers crossed for getting your candidacy status!

Regarding what you describe: this is not a bug but expected behavior and even explained in the docs: https://docs.zettlr.com/en/advanced/yaml-frontmatter/#lang
