### ISSUE TITLE
Writing target tooltip does not show correct value

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#551]
## Description

Writing-target-info tooltip in the file list is not updated when saving the file. (since this commit: ["Fixed FileList glitches"](https://github.com/Zettlr/Zettlr/commit/5ce31d43dd3a9ad58bdccf0df7a0cde53d3c1921)).

## Reproducing

1. Set writing target to arbitrary file.
2. Open the file and type (or delete) some words.
3. `Ctrl-s`
4. Hover the writing target indicator in the file list.

## Expected behaviour

The correct word count should be displayed in the tooltip immediately.

## Platform
 - OS and version: Windows 10 Home 1903
 - Zettlr Version: 1.6.0-beta.4
 - Screen Resolution: 1366x768

**Comment by nathanlesage** [comment]
Thanks for pointing out the specific commit! I also noticed some lags in updating the tag views, which would also not always properly update. I'll get to it!

**Comment by nathanlesage** [comment]
And here we go! :)
