### ISSUE TITLE
Mermaid architecture diagram doesn't render

### ISSUE THREAD

**Issue by wgordon17** [Zettlr/Zettlr#5525]
### Description

Utilizing the new `architecture-beta` (https://mermaid.js.org/syntax/architecture.html) diagram type doesn't render

Receiving error
```
Could not render Graph:

undefined
```

### Reproducing

Utilizing the example in a new markdown file

```
\```mermaid
architecture-beta
    group api(cloud)[API]

    service db(database)[Database] in api
    service disk1(disk)[Storage] in api
    service disk2(disk)[Storage] in api
    service server(server)[Server] in api

    db:L -- R:server
    disk1:T -- B:server
    disk2:T -- B:db
\```
```

### Zettlr version

3.3.1

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

MacOS 15.1.1 (24B91)

**Comment by nathanlesage** [comment]
Could you please open the dev tools (Preferences -> Advanced -> Debug mode, then press Cmd-Alt-I) and see if the console contains maybe a better/more descriptive error?

**Comment by wgordon17** [comment]
Ok...I feel like an _idiot_ 🤦‍♂️ 

When I went back and tried it again, I discovered that copy/pasting from the example automatically escaped square brackets (I didn't notice that before). Un-escaping the square brackets got this to work just fine ¯\_(ツ)_/¯

**Comment by nathanlesage** [comment]
Wonderful, thanks for closing the issue! And happy holidays!
