### ISSUE TITLE
Workspaces removed and unable to be readded upon upgrade to 3.4.0

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#5526]
### Description

I recently upgraded to v3.4.0 and many of my open workspace folders had disappeared from the file manager. I attempted to re-open them using the standard `File > Open Workspace …` method, but am unable to do so. When I roll back to the 23 Dec nightly of 3.3.1, all the missing workspaces are repopulated.

### Reproducing

See above.

### Zettlr version

3.4.0

### Installation Method

From the Website or GitHub

### Installation Method (Other)

Appimage

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Manjaro (Rolling)

**Comment by AIBN60** [comment]
Confirmed under Ubuntu 20.04: Workspace wasn't found. Files weren't opened even when opened from file browser. Back to 3.3.1

**Comment by wideaperture** [comment]
From the log file. These errors cropped up right after boot on v3.4.0:

```
[11:24:15] [Error] [R] [Main Window (e9977e25-d90e-44e5-aec4-fec2df148c1d)] Error: Error invoking remote method 'documents-authority': TypeError: Cannot read properties of undefined (reading 'value') (index.js:2)
[11:24:15] [Error] [R] [Main Window (e9977e25-d90e-44e5-aec4-fec2df148c1d)] Error: Error invoking remote method 'application': TypeError: Cannot read properties of undefined (reading 'value') (index.js:2)
```

This error appeared when I tried to manually reopen the workspaces:

```
[11:25:50] [Error] Could not open root /home/josh/Dropbox/Slip Box because it was an ignored directory/file.
```

**Comment by rheslop** [comment]
Confirmed also for Fedora 41.
After update files opened appeared empty. Closed and re-opened Zettlr, and there was no workspace, and I couldn't add a workspace back. Relieved to find no data was actually missing from files. Downgraded to 3.3.1 for now.

**Comment by chiphogg** [comment]
This is happening to me too, on Ubuntu 22.04.  However, not all is well when rolling back: I can't seem to get the tag search to work.  The tag cloud is empty when I click the tag button.  However, entering the text of a tag, including the `#` sign at the start, does let me search for a tag.  And, I can click on a tag and still get results.

**Comment by cbaile19** [comment]
The same problem on Windows 11; reverted to 3.3.1, and workspaces were accessible again.

**Comment by hyuce** [comment]
The same problem on MacOS Sequoia 15.1.1 (24B91); I see a window is says "There was an error accessing "<unknown>"
undefined: Unknown error"

**Comment by nathanlesage** [comment]
I'm pretty sure I know where the error is. The most important part is that this does not lead to data loss at all. The worst that can happen is that you have to clear the FSAL cache when downgrading. (Saying this especially for when the tag search seemed to break, this should be fixed by an FSAL cache clear.)

I'll see to fix this after the holidays. Apologies y'all for a somewhat sour Christmas gift 😵‍💫 As I already said elsewhere, I really need to resist the urge to do some last minute fix out of a thought of "I wanna do good for the community" 🫣

I guess @sensologica you were right that I'm a bit too engaged 😂

**Comment by matthijsbro** [comment]
Maybe unpublish/hold back 3.4.0 now not everyone has updated yet? I found 3.3.1 to reinstall and that did fix this problem for me.

**Comment by nathanlesage** [comment]
Found the issue, it was literally one line of Code. I see it positively, this has finally made me search for a proper solution to finding those errors (for more info see #5529)

**Comment by nathanlesage** [comment]
Build is now commencing for 3.4.1, will release soon!

**Comment by nathanlesage** [comment]
Update 3.4.1 is now live, updating should now work as expected without any errors and bugs: https://github.com/Zettlr/Zettlr/releases/tag/v3.4.1

**Comment by chiphogg** [comment]
This is _much_ better.  And, I finally got to try out the fix for #5246, which worked beautifully!

**Comment by nathanlesage** [comment]
Great to hear! And apologies again 🫣

**Comment by matthijsbro** [comment]
> I'll see to fix this after the holidays. Apologies y'all for a somewhat sour Christmas gift 😵‍💫 As I already said elsewhere, I really need to resist the urge to do some last minute fix out of a thought of "I wanna do good for the community" 🫣

Thanks anyway! Have some good holidays!

**Comment by gijshvg** [comment]
Sorry to reopen this, but I see no positive change. Neither on Macbook, nor on Ubuntu 22 is it possible to open workspaces. I think I am going to downgrade to 3.3.

**Comment by gijshvg** [comment]
Yes, I am sorry.
  

  

  

  
  
Vriendelijke groet,
  
GijsH
  

  

        
  
  
>

**Comment by AIBN60** [comment]
> Even with 3.4.1?

Works fine on Ubuntu 20.04.

**Comment by gijshvg** [comment]
I use ubuntu 22.04. But on Macbook (MacOS Ventura) are the problems the same.

**Comment by gijshvg** [comment]
Update: I opened a number of single .md files. Went smoothly. Interestingly enough, after this the workspaces opened as well.

**Comment by ghost** [comment]
I still see this behavior.
* OS: Ubuntu 24.04
* Zettlr: v3.6.0

What I did: tried to open a workspace via File > Open Workspace.
What I expected: Workspace to open and either replace existing open workspace, or open below it.
What happened: Nothing. Previous workspace remains open, selected workspace doesn't open.

I've also tried closing/reopening app, of course, and also tried right-clicking and closing current workspace first. Same behavior.

**Comment by nathanlesage** [comment]
Please try out the 4.0 Beta of This continues.

**Comment by ghost** [comment]
> Please try out the 4.0 Beta of This continues.

Thanks Nathan, I installed v4.0.0-beta.2. Problem persists, exactly as with 3.6.0. It's like File>Open Workspace does nothing.

Specifically, installed from file `Zettlr-4.0.0-beta.2-amd64.deb`.

**Comment by nathanlesage** [comment]
Okay, is the workspace large? Currently, Zettlr does Not give Feedback as it is indexing the workspace behind the scenes, and as soon as it is finally done, the workspace should appear. I don't know how long you have waited until now ...?

**Comment by ghost** [comment]
> Okay, is the workspace large? Currently, Zettlr does Not give Feedback as it is indexing the workspace behind the scenes, and as soon as it is finally done, the workspace should appear. I don't know how long you have waited until now ...?

I've tried workspaces of varying sizes, including just one text file. The behavior is now: random, and seems unrelated to the size of the directory. A 'workspace' containing 20mb of image files opens instantly; a workspace of 10 markdown text files totaling <2mb doesn't open (for one example).

**Comment by nathanlesage** [comment]
This is super odd. Would you mind gathering some more information to describe any patterns or non-patterns that you have observed and open a new issue? Then we can see to reproduce and hopefully fix your issue!

**Comment by ghost** [comment]
> This is super odd. Would you mind gathering some more information to describe any patterns or non-patterns that you have observed and open a new issue? Then we can see to reproduce and hopefully fix your issue!

Hendrik, I looked at permissions, Zettlr logs, a variety of things--no luck. But *then* I did this:

1. Deleted `~/.config/Zettlr/config.json`.
2. Ran `zettlr --disable-gpu --disable-features=UseInotify'

Which gave me:
```[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /usr/lib/zettlr/resources/pandoc
[Application] Quarto not found on system. *.qmd-files will be exported with Pandoc.
[Application] Environment check complete.
(node:1519317) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `zettlr --trace-deprecation ...` to show where the warning was created)
```
2. It seemed pause/hang there, so I typed `Ctrl-C`, and Zettlr then launched with split view and the Zettlr tutorial open.

3. I was then able to open *any* workspace. No errors. 
4. BUT: when I tried this *again*, the random error (no workspace opens) reappeared.
5. So, I deleted the `~/.config/Zettlr/config.json` again, and ran the command above. Everything worked again--I could once again open any workspace.

Hope this helps. This seemed to work for both v3.6.0 *and* v4.0.0-beta.2. Perhaps there's a problem with open directories/paths in the config file?

Please let me know if there's anything else I can do.

My environment:
* OS: Linux Ubuntu 24.04
* CPU: AMD Ryzen 5 7430U (12) @ 4.39 GHz
* GPU: AMD Barcelo [Integrated]
* RAM: 24GB
* Machine: GEEKOM A5 2025 Edition Mini PC

**Comment by ghost** [comment]
> > This is super odd. Would you mind gathering some more information to describe any patterns or non-patterns that you have observed and open a new issue? Then we can see to reproduce and hopefully fix your issue!
> 
> Hendrik, I looked at permissions, Zettlr logs, a variety of things--no luck. But _then_ I did this:
> 
>     1. Deleted `~/.config/Zettlr/config.json`.
> 
>     2. Ran `zettlr --disable-gpu --disable-features=UseInotify'
> 
> 
> Which gave me:
> 
> ```
> [Application] Pandoc has been bundled with this release. Path: /usr/lib/zettlr/resources/pandoc
> [Application] Quarto not found on system. *.qmd-files will be exported with Pandoc.
> [Application] Environment check complete.
> (node:1519317) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
> (Use `zettlr --trace-deprecation ...` to show where the warning was created)
> ```
> 
>     2. It seemed pause/hang there, so I typed `Ctrl-C`, and Zettlr then launched with split view and the Zettlr tutorial open.
> 
>     3. I was then able to open _any_ workspace. No errors.
> 
>     4. BUT: when I tried this _again_, the random error (no workspace opens) reappeared.
> 
>     5. So, I deleted the `~/.config/Zettlr/config.json` again, and ran the command above. Everything worked again--I could once again open any workspace.
> 
> 
> Hope this helps. This seemed to work for both v3.6.0 _and_ v4.0.0-beta.2. Perhaps there's a problem with open directories/paths in the config file?
> 
> Please let me know if there's anything else I can do.
> 
> My environment:
> 
>     * OS: Linux Ubuntu 24.04
> 
>     * CPU: AMD Ryzen 5 7430U (12) @ 4.39 GHz
> 
>     * GPU: AMD Barcelo [Integrated]
> 
>     * RAM: 24GB
> 
>     * Machine: GEEKOM A5 2025 Edition Mini PC

Hendrik, I'm now realizing I overlooked one obvious thing. So, I just deleted the `config.json` and opened the app normally without disabling gpu, etc.--workspaces work. That seems to strongly point to the config file as the culprit.

**Comment by nathanlesage** [comment]
Aha! If that happens again, can you send the config json that causes this issue to me? Either paste here, or via email to hendrik@zettlr.com -- there's likely some issue Zettlr encounters here that should be visible from the malformed config!
