### ISSUE TITLE
PDF Export not working

### ISSUE THREAD

**Issue by mtzCCStudent** [Zettlr/Zettlr#553]
I installed the latest stable release v 1.5.0 of Zettlr from the website and followed the instructions in Zettlr help system for installing pandoc and latex on windows - i used the link given in your setup guide to install Windows: MikTeX. Installation worked fine but the PDF-Export of Zettrle allways gives this error:

Error producing PDF.
! LaTeX Error: File `xunicode.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.11 ^^M

**Comment by nathanlesage** [comment]
Hey, this is not a problem: It just means that the package `xunicode` needs to be installed additionally. For the first exports, this is to be expected, and has been covered in the [Frequently Asked Questions](https://docs.zettlr.com/en/faq/#on-export-to-pdf-i-constantly-get-error-messages)!
