### ISSUE TITLE
[FEATURE] text colors

### ISSUE THREAD

**Issue by yennor** [Zettlr/Zettlr#555]
## Description

It would be great if it somehow would be possible to integrate text-color and text-background-color into Zettlr. I know that unfortunately the markdown language doesn't really support color.
And I guess no sane person would call "<span style="color:red">" a solution...
Maybe if one could hide the "<span style="color:red">" part?
To be honest, I've got no idea, what would be a good way to integrate it. But maybe you do :-).
As it seems there are also some dialects around which supports it.

## Caveats

When using an dialect or a propietary extension, it wouldn't be compatible anymore do normal Markdown (for exports).

**Comment by nathanlesage** [comment]
hmm …? I'm not sure I understand what you are aiming for…?!

**Comment by yennor** [comment]
Sorry.
Basically I'd like to be able to choose the color of the text or of the text background to mark and distinguish certain information.
and as it seems github filtered out what was in the "" ;-).
in "" was: 
`<span style="color:red">`
which is the way most markdown interpreter would allow to change the color of the text. But which makes it really difficult to fluently read the source of it.

**Comment by nathanlesage** [comment]
Ahh, I see. Well, I don't see any way to accomplish this with Markdown, as it's precisely meant for _not_ overstyling documents as Word does. I mean it's not that bad to read, and the solution affects only a few people, I think. If there's greater need for this in the future, please feel free to comment this issue, in which case I'll reopen it!

**Comment by tio-trom** [comment]
I would love to see this being implemented. Color is helpful.
