### ISSUE TITLE
Export template

### ISSUE THREAD

**Issue by goncalomcorreia** [Zettlr/Zettlr#556]
Hi!

I'm looking into doing some changes to the template when exporting to PDF. I've checked this entry in the docs (https://docs.zettlr.com/en/academic/custom-templates/) but I'm still not sure how to do what I want. I would like to:

- Add some space after every paragraph
- Convert every $$ that are in their own lines to \begin{equation}\end{equation} environments in latex (center the equation, some vertical space above and below, number the equation)
- Add some space between the main text and the references and add the title "References" before them

Does anyone know how to do this or where can I find how to do this?

Thanks!

**Comment by nathanlesage** [comment]
Easiest way is to use the [Zettlr default export template](https://github.com/Zettlr/Zettlr/blob/master/source/main/assets/export.tex) or the [Pandoc one](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex) and modify it.

1. Add spacing: See snippet below
2. This is done automatically by Pandoc. You don't need to do this explicitly!
3. Simply end your document with `## References`, or use the respective frontmatter variable (see the Pandoc documentation for that). Further info also on this page: https://docs.zettlr.com/en/academic/citations/

```latex
\setlength{\parindent}{-1cm} % Negative hanging indent
\setlength{\leftskip}{0.5cm} % Overall indentation
\setlength{\parskip}{0.1cm} % Spacing between paragraphs
```
