### ISSUE TITLE
The use of asterisk (*) inside math notation induces unwanted WYSIWYG emphasis.

### ISSUE THREAD

**Issue by JohannesNE** [Zettlr/Zettlr#557]
## Description
Using an asterisk (*) inside a math formula ($math$) causes the following text to be highlighted as emphasis until the next asterisk. The behaviour is not there if the asterisk is surrounded by spaces (obviously).

Similar to https://github.com/Zettlr/Zettlr/issues/276, however I have an idea for a fix.

## Reproducing
Write something like 
```
This is math $2*2=4$ Due to the asterisk (*) what follows is in italics.
Other math $Y_x = x$  Underscore does not do this.
However. both can be fixed using spaces:
This is math $2 * 2=4$ Asterisk
Other math $Y_x = x$  Underscore 
```

## Expected behaviour

Ignore symbols in math notation when highlighting 

**Screenshots**
![image](https://user-images.githubusercontent.com/11048760/74911787-adeaec00-53bd-11ea-811b-a5d6cd6245ed.png)

## Platform
 - OS and version: Pop!_OS (Ubuntu) 19.10
 - Zettlr Version: 1.5
 - Screen Resolution: 1600x900

## Additional information
I suppose that this regex is central in the problem:
https://github.com/Zettlr/Zettlr/blob/3e8a0fc47c885a76a641a3a1dcf54782f45c26a3/source/renderer/assets/codemirror/zettlr-plugin-wysiwyg.js#L20

Someone better at regex than I am, might be able to come up with a pattern that does not match anything inside math notation.

**Comment by nathanlesage** [comment]
Nope, this regex has nothing to do with it, because it induces WYSIWYG, what you're referring to is WYSIWYM :D

However, after I split up the Markdown mode and brought it under my control, I can actually mitigate that problem by now!

**Comment by nathanlesage** [comment]
Ahhh, just had a look, the error is already fixed since all the betas, I forgot to look up that you're using 1.5! Sorry for that! 🙈
