### ISSUE TITLE
[ENHANCEMENT] Render Zettelkasten Links Like Regular Links

### ISSUE THREAD

**Issue by callanrowe** [Zettlr/Zettlr#559]
Hi, I'd love to be able to be able to render internal links in line. 

so rather than rendering 

> This relates to [[20191025071912]] 20191025071912 link to note  

it could render

> This relates to _link to note_

Syntacs could be something like [[Link to note|20191025071912]] or [[20191025071912]](Link to note)

This is the one thing that is really stopping zettlr from being my one stop shop for notes.

Thanks for all you do

**Comment by nathanlesage** [comment]
Mhhh … shouldn't prove too difficult. Sounds like a fair idea. But I have to sort it using a very low priority right now, but I'll keep it open!

**Comment by Nissentott** [comment]
It's basicly already possible if you use it as a link, this is what I do to hide the ID while reading/writing: 
[Title]([[ID]])

Example:
"was a paramilitary militia force in Poland during the [November Uprising]([[202002201139]])." 

Turns up as:
"was a paramilitary militia force in Poland during the _November Uprising_."

**Comment by callanrowe** [comment]
Amazing. Thanks!

**Comment by Ziinc** [comment]
It looks like a syntactic hack that serves the exact same purpose of a normal markdown link with an id reference, like `[my link ](./myfile#202015202525)`.

From a design standpoint, the end goal is the same, to achieve linking to a given target note. 
Furthermore, the current linking method breaks down when browsing notes on different platforms, like github/gitlab or vscode or sublime. 

I think that the current linking model and the way zettlr saves and parses the links should be reviewed to find a balance between customization, efficiency, and data portability. For example, if people don't have access to zettlr (maybe they're on mobile), they can at least still manually create notes that will still be recognised by zettlr.

I can contribute my brain cells in helping to improve the linking, which I have strong feelings about 😁

**Comment by callanrowe** [comment]
This kind of works, however if you change the file name it breaks, and if you don't have Zettlr as your default markdown app, it opens in another app

**Comment by nathanlesage** [comment]
> if you don't have Zettlr as your default markdown app

This is totally to be expected. Zettlr simply sends an open-request to the operating system (takes 200 less lines of code, and still works, albeit I'm willing to admit that the recurse to the operating system is funny to say the least).

And the breaking thing, yes, of course, file names are difficult to handle, which is why there are IDs. The original intent of these ID-links is to aid in Zettelkasten design, where you would link many things using `[[123456]] The file name`.

After all, a Zettelkasten is something different than a Wiki. And, while thinking about it, I just got the impression that indeed this should be two different things -- the Zettelkasten links versus Wiki-links (which can be implemented using regular Markdown links, after all).

**Comment by webbj74** [comment]
I wanted to note that in MediaWiki (Wikipedia et al) the syntax for rendering a wikilink with different name is to have `[[20191025071912|Link to note]]` (flipped order to what @callanrowe proposed). Other variations at: https://www.mediawiki.org/wiki/Help:Links

There are a few other markdown apps using wikilinks for internal links (NotePlan is one I've used the most). I think the syntax is comfortable for internal links. Markdown link notation is not very intuitive to me (I am forever forgetting if it's [] before () or vice versa).

**Comment by nathanlesage** [comment]
Good point. If we're extending internal links, then using the most common way is surely the best.

> Markdown link notation is not very intuitive to me (I am forever forgetting if it's [] before () or vice versa).

I can fully relate. However, I'd like to point out that both link types are necessary and used within Zettlr, and you cannot swap one for the other!

**Comment by varian93** [comment]
In my opinion, what would be ideal for internal links is that Zettlr would capture them as created and immediately on-the-fly translate them into a standard Markdown link for you.

This would allow for internal linking to be easy to use & remember, as well as aid in keeping Zettlr vendor agnostic. The Markdown files created by Zettlr would still be fully functional and able to be used anywhere else.

**Comment by webbj74** [comment]
My concern with automatically translating internal links into a standard Markdown link would be the impact for reorganizing notes into a different folder hierarchy later on. Keeping it as an internal link, Zettlr can be more flexible with how it resolves that link (e.g. recursing through all the dirs added to Zettlr until it finds a match), and the end-user can re-org their notes outside of the application without worrying about what links to them, as long as it's in a dir that Zettlr knows about.

So maybe there are some additional features to consider (besides what the OP has requested):
* Add a preference option to automatically convert internal links into a standard Markdown link.
* Add a contextual menu item to convert an individual internal link into a standard Markdown link.

**Comment by nathanlesage** [comment]
> My concern with automatically translating internal links into a standard Markdown link would be the impact for reorganizing notes into a different folder hierarchy later on.

This. Fully agree. Plus we should also not forget the semantic dimension, if you see an internal link, you know what it does. If you see a Markdown link -- same. But if both look the same, you won't be able to tell. And let's face reality, nobody wants to hover over a link, wait 2 seconds for the title to appear before clicking it.

**Comment by varian93** [comment]
I see the issues such behavior would create. My main motivation was to keep the files vendor agnostic. 

Perhaps internal links behavior could remain as it is now, but under the export menu Markdown could be added. When deliberately exported to Markdown Zettlr would then auto-convert any internal links into standard Markdown links.

**Comment by nathanlesage** [comment]
This is indeed an idea. Question would be of the "how" to do this

**Comment by rainbyte** [comment]
I didn't understand why regular links weren't working here. I think it would be useful to have them, because other apps, like the one I use on my phone, only accept standard links.

**Comment by nathanlesage** [comment]
> I didn't understand why regular links weren't working here.

Well, regular links linking to other Markdown files should work normally, or are you experiencing issues there?

**Comment by rainbyte** [comment]
Markdown files are opened inside other editor, as I understand because zettlr delegates this to the OS. Why not handle this inside the app?
I would like to leave the OS config as it is, because I prefer other editor to open project markdown files.

**Comment by nathanlesage** [comment]
> Why not handle this inside the app?

Because this saves, like, 200 lines of code :D But your point is valid, so maybe I could add a preference setting to change that behaviour.

**Comment by FloGom** [comment]
> Plus we should also not forget the semantic dimension, if you see an internal link, you know what it does. If you see a Markdown link -- same. But if both look the same, you won't be able to tell. And let's face reality, nobody wants to hover over a link, wait 2 seconds for the title to appear before clicking it.

@nathanlesage the two are compatible, I have used successfully classic Markdown links for "internal links" by adding a pair of `[]`.
For example one can have the link `[[my link](myNote.md)]`
