### ISSUE TITLE
Feature request: network graph (ok, backlinks first :))

### ISSUE THREAD

**Issue by pihentagy** [Zettlr/Zettlr#56]
It would be cool to have backlinks listed, or even some sort of network graph to be able to easily navigate  between the Zettles.

**Comment by nathanlesage** [comment]
Heya,

what do you mean by a listing of backlinks?

A network of different Zettels is already on my list. It won't be possible before 1.0, but it'll come some day!

**Comment by pihentagy** [comment]
Backlink: a list of all files, which has a link to the current page.

**Comment by pihentagy** [comment]
And to request a 'callback' can you direct me to that issue, which is about the netwokr graph?

**Comment by pihentagy** [comment]
A nice example of using backlinks is e. g. http://roamresearch.com/

**Comment by nathanlesage** [comment]
Yes, I've seen it gaining a lot of traction at the moment. I'll have a look, but only when I have time, currently it's one of the scarcest resources!

**Comment by sahmoli** [comment]
Thanks for your fantastic work, @nathanlesage 
I think the backlink is super important, and network graph will also help us see the near and far connections of notes.
A recently markdown editor has already incorporated backlink and network graph in it. https://obsidian.md/
