### ISSUE TITLE
[BUG] Zettel links are not closed again

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#560]
## Description

When CodeMirror's "autoclose pairs" is disabled, and Zk's "when linking, add the filename" is set to "never", closing brackets to Zk links are not added.

## Reproducing

1. Disable "Autoclose matching pairs" in Configuration → Editor.
2. Set "When linking files, add the filename" to "never" in Configuration → Zettelkasten.
3. Type `[[` in a note.
4. Choose a file.

## Expected behaviour

Something like `[[2334234234234]]`.

Actual: `[[2334234234234`.

## Platform

 - OS and version: macOS 10.14.5
 - Zettlr Version: 1.6.0beta4 (built from the develop branch few minutes ago)

## Additional information

Yes, this is very similar to #539. But that bug has been fixed, which I have also tested.

**Comment by nathanlesage** [comment]
Here you go!

**Comment by Zverik** [comment]
Thank you!
