### ISSUE TITLE
"Select all" in the context menu is not working

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#561]
## Description
"Select all" in the context menu is not working. (Though, `Ctrl+A` works properly, so I don't feel any inconvenience.)

## Reproducing
1. Right-click on the editor (or search field)
2. Click "Select all"
3. Nothing happens

## Expected behaviour
"Select All" should select all text.

**Screenshots**

## Platform
 - OS and version: Windows 10 Home 1903
 - Zettlr Version: 1.6.0-beta.5
 - Screen Resolution: 1366x768

## Additional information
The value of [role](https://www.electronjs.org/docs/api/menu-item#roles) seems to be incorrect.

**Comment by nathanlesage** [comment]
Thanks for spotting this! Fixed it :)
