### ISSUE TITLE
Zettlr doesnt respect system theme on Linux

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#562]
## Description
Zettlr doesn't respect system theme (other electron based apps change their appearance)
In the screenshot is an example (maximize, minimise and power buttons)

![Przechwycenie obrazu ekranu_2020-02-21_19-36-46](https://user-images.githubusercontent.com/7980381/75061822-cf44f880-54e1-11ea-8e87-7133673e1062.png)

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: Ubuntu 18.04, XFCE 4.14
 - Zettlr Version: Latest beta
 - Screen Resolution:

**Comment by nathanlesage** [comment]
This is because Zettlr uses a frameless window and draws the buttons itself. I have opened an issue, because I think this should be altered here: https://github.com/Zettlr/Zettlr/issues/448

Please feel free to comment there your thoughts :)
