### ISSUE TITLE
Add printing options

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#57]
I used the dev console to issue a `window.print();` command, and to my slight surprise, a list of printers came up. I chose a PDF printer for testing, and what came out looked like below (I cropped it to just the first few lines), and only the screen was printed, not the document. If the rendered document is in a child window / div / iframe, then issuing a print command on that div might allow printing the document. Even better would be if the Chromium native print preview dialogue would open, as it shows a nice preview of what will be printed. However I don't know whether it's included in Electron. It looks like it might be with https://electronjs.org/docs/api/web-contents#contentsprintoptions-callback : `contents.printToPDF(options, callback)` .

It may seem esoteric to want to print from Zettlr, especially as it doesn't have a concept of a "page", and of course we can export to PDF or to doc and print that way. But as I work more with Zettlr, I find myself wanting to print out a section quickly as a record of where I've got to, or even just to rest my eyes from the screen. I'm old-fashioned, I like hard copy, it doesn't disappear when the laptop battery runs out!!!

File this under long-term enhancement, wish-list, or whatever.

![image](https://user-images.githubusercontent.com/4304337/48487211-6fa76a00-e815-11e8-9ff3-3e841bfc42b7.png)

**Comment by nathanlesage** [comment]
Hey,

yeah printing is a topic for itself using electron, because as far as I know, Electron ditched most of the fundamental print support of Chromium. I opted against trying to enable printing natively, BUT there's a way I specifically intended for that: HTML export.

If you export your document to HTML, and then open the Print Dialog of your browser, you'll notice that I took care to add print CSS view, so that you can easily print it out via HTML. It may be a click more, but it's better than a half-heartedly native print support, which is not really supported :)

Cheers!

**Comment by Jaifroid** [comment]
Ooh yes, that's a great workaround! And yes, it looks really nice. Glad to have found out about that!
So, how about you have a Print dialogue box, also bound to Ctrl/Cmd-P, that tells the "naïve" user (like me) that it will export to HTML and the user should then print it from the browser? Maybe a "Print" button in that menu would do the export. Then maybe even a "Don't show this menu next time, just print to HTML" option, so that Ctrl-P will export the document without further clicking?

**Comment by nathanlesage** [comment]
Hmhm, sounds good. Although … really, having a "fake"-shortcut feels somewhat … strange =D

**Comment by Jaifroid** [comment]
It's more about discoverability than faking, IMHO. I hunted around for a Print option, and even went as far as opening console and issuing `window.print()` to see if there was an under-the-hood implementation. If you don't intend to do native printing, then it's not like you're tricking anyone by providing an explanation when they press Ctrl-P or look for a Print... menu item. A Word-processor replacement needs some kind of print option, and the one you've provided is very good, but currently undiscoverable.

**Comment by nathanlesage** [comment]
That's a good point. But I may even have a better idea: As Electron ships with the default print capabilities of Google Chrome, I would suggest that the implementation of printing from within the app is even more comfortable. Therefore I'll look into implementing "native" printing from within the app for 1.0!

**Comment by nathanlesage** [comment]
And heeeere we go!

**Comment by ryancwalsh** [comment]
Here is a new printing feature enhancement request: https://github.com/Zettlr/Zettlr/issues/4630
