### ISSUE TITLE
dark mode not persistent

### ISSUE THREAD

**Issue by mokkin** [Zettlr/Zettlr#570]
## Description
If I set the mode to dark mode an switch off the the automatic theme switch dark mode is working, but not persistent after system restart the next day.

## Expected behaviour
keep the saved settings the next day

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2938748/75348909-ffa2e300-58a3-11ea-9048-2101b195076a.png)

## Platform
 - OS and version: Ubuntu 18.04 x64
 - Zettlr Version: 1.6.0-beta.4
 - Screen Resolution: three displays with 1920*1200

**Comment by nathanlesage** [comment]
Is this issue still prevalent in newer versions? If not, we can close this issue.

**Comment by CodexEnt** [comment]
I experience this with Zettlr 3.5 on Windows 10
Dark mode is not persistent between restarts.

**Comment by dm5n** [comment]
Also on Zettlr 3.5.1 macos 15.5 - Dark Mode not persisting between restarts.

**Comment by nathanlesage** [comment]
Please do not comment on years old issues and open new ones instead.

**Comment by CodexEnt** [comment]
> Please do not comment on years old issues and open new ones instead.

It happens, and it is in response to your question
"Is this issue still prevalent in newer versions? If not, we can close this issue."

If you don't want this issue to be posted about, even as it continues into newer versions, drop the attitude and close the issue. Don't be scolding users for giving you updated feedback.

**Comment by nathanlesage** [comment]
There is no attitude here. It's a lot of work I have to go through (almost 500 issues) and sometimes I may overlook things. Please just open a new issue, so that this comes back onto my radar and I hopefully am able to get into fixing it soon.

**Comment by dm5n** [comment]
In my case, it looks like a user error. Dark Mode now persistent across app and system restarts.

<img width="1491" height="190" alt="Image" src="https://github.com/user-attachments/assets/45458a5e-4a6c-4fd1-bea5-24cc1a9d8a90" />

The issue was Dark Mode was toggled ON but Schedule also set to ON. Setting it to OFF and voila - glorious Dark mode. When I'm feeling braver, I'll try the other Schedule settings.

Thanks!

**Comment by nathanlesage** [comment]
I just fixed a bug that I found that essentially would only restore the dark mode setting on macOS, but not on other platforms. I hope that now fixes this.

**Comment by behrisch** [comment]
> I just fixed a bug that I found that essentially would only restore the dark mode setting on macOS, but not on other platforms. I hope that now fixes this.

Sorry, I was too late in reading this and already opened another issue. I will close it once the new release is there (of course you can already close it earlier ;-)
