### ISSUE TITLE
[ENHANCEMENT] Enable Ctrl+Scroll Zoom on Windows + Linux

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#571]
## Description

While on macOS, zooming is mostly performed by "pinching" (something I'd have to figure out), zooming in and out on Windows and Linux is commonly performed using the shortcut `Ctrl+Mousewheel`, and since Electron is unable to override the Zoom in-command, which is hardcoded to `Ctrl+Shift+Plus`, this would make it somewhat easier (because users expect this to happen when Control-Scrolling).

## Proposed Changes

Add a simple event listener to the `#editor`-instance, so whenever someone uses the mousewheel simply trigger the zoom-function of the Editor-instance. Something along the lines of this:

```javascript
$('#editor').on('mousewheel', (evt) => {
  if (!evt.ctrlKey) return

  if(evt.originalEvent.detail > 0) {
    editor.zoom(-1)
  } else {
    editor.zoom(1)
  }
})
```

## Caveats

None, as the combination Ctrl+Mousewheel is not taken atm

**Comment by Zverik** [comment]
Link for the future: [pinch zoom events on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures).

**Comment by Zverik** [comment]
Zoom would be useful, I'd like to keep this issue.

**Comment by nathanlesage** [comment]
Oh, already solved – closing!
