### ISSUE TITLE
RevealJS: Relative path plugins can't be loaded (e.g. highlight.js that comes with reveal.js)

### ISSUE THREAD

**Issue by AlexEne** [Zettlr/Zettlr#572]
## Description
The plugins that come with reveal.js can't be loaded using the method described here https://github.com/Zettlr/Zettlr/issues/281

## Reproducing
I tried loading a plugin with a path by either changing the reveal.js options or with <script> tags but that's not possible from what I can tell.

E.g:
```
<script type="text/javascript">
zettlrRevealOptions.dependencies = [
        {
            src: 'plugin/highlight/highlight.js',
            async: false, 
            callback: function() { hljs.initHighlightingOnLoad();}
        }
    ]
</script>
```

## Expected behaviour
I would expect that to work as it is the correct way to load it according to the documentation for reveal.js

**Screenshots**
None of the code is highlighted in presentations.

## Platform
 - OS and version: Any I think (tried OSX 10 Catalina and Windows 10)
 - Zettlr Version: 1.5.0
 - Screen Resolution: any

**Comment by AlexEne** [comment]
As an update, even using the highlight.js from [a cdn](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.9/languages/go.min.js) as described [here](https://highlightjs.org/usage/), `hljs` is not found so I am concerned that even if the path would be correct this might not work.

**Comment by nathanlesage** [comment]
I can tell you why it doesn't work: By default, Pandoc applies its own syntax highlighting, for which one might need to provide custom styling.

See here: https://vda-lab.github.io/2014/01/proper-syntax-highlighting-in-revealjs-using-pandoc

**Comment by AlexEne** [comment]
Isn't `reveal.js` the one that overrides it it in the end? I would expect that `reveal.js` code is executed in the browser as that the presentation gets rendered.

**Comment by nathanlesage** [comment]
> Isn't reveal.js the one that overrides it it in the end?

Unfortunately not, as the code blocks are parsed by Pandoc.

> Is there a way to get it highlighted? As far as I can tell in the article it requires pandoc to get certain cmd line arguments for this to work, but as far as I can tell, zettlr doesn't allow a user pass them (?)

I would like to invite you to have a look at the Advanced tab in the Preferences of the app, and then this documentation page: https://docs.zettlr.com/en/academic/custom-templates/, especially close to the end the command is explained pretty well

**Comment by AlexEne** [comment]
That's great, thanks
