### ISSUE TITLE
[1.6.0-beta.5] When only one note has a particular tag, it is not found when searching

### ISSUE THREAD

**Issue by terryroe** [Zettlr/Zettlr#577]
I'm using 1.6.0-beta.5 on MacOS.  I have one note with a tag of #zettelkasten and when I try to search for that tag nothing shows up in the sidebar.  If I add the tag to another note, then both notes show up in the sidebar when I search for the tag.

**Comment by terryroe** [comment]
This is a more general problem than just searching for tags.  If the search results only contains one result, the result is not shown.  It seems no matter what I search for, if there is only one result it doesn't show in the sidebar.

**Comment by nathanlesage** [comment]
Yeah, it's a bug @ryota-abe has found and is already in the codebase! It'll be solved with 1.6 stable :)
