### ISSUE TITLE
[TRANSLATION] License v Licence

### ISSUE THREAD

**Issue by webbj74** [Zettlr/Zettlr#579]
## Description

License has some peculiar spellings depending on whether it is:
- Used as a noun or verb
- Used by an American writer

## Reproducing

Visit "About Zettlr" to see the text impacted.
- `dialog.about.lead`
- `dialog.about.license`

### For en-US:
- Always with an "s"
 > "This project is licensed under the GNU GPL v3 license."

### For en-GB
- With an "s" when used as a verb, with a "c" when used as a noun.
 > "This project is licensed under the GNU GPL v3 licence."

## Additional information

This issue is to give background for translations I provided at https://translate.zettlr.com/en-US and https://translate.zettlr.com/en-GB 

Reference: https://www.grammarly.com/blog/licence-license/

**Comment by nathanlesage** [comment]
Grammar can be difficult indeed. But thank you very much for noticing (or notising? 🧐), I've voted for the new translations so they should be in the translations now! :)
