### ISSUE TITLE
[BUG] Default autocorrect entries conflict with composition of Yaml Frontmatter

### ISSUE THREAD

**Issue by webbj74** [Zettlr/Zettlr#580]
## Description

When composing YAML frontmatter in a note typing `---` conflicts with default autocorrect entries which transform `--`  to `–` or `---` to `—`.

[config-provider.js#L222-L223](https://github.com/Zettlr/Zettlr/blob/b58b3f3/source/main/providers/config-provider.js#L222-L223):
```js
            { key: '--', val: '–' },
            { key: '---', val: '—' }
```

## Reproducing

1. From a new install of Zettlr
2. Open a directory
3. Create a new file
4. Start typing YAML frontmatter: `---` and hit space. 
5. Remove the `---` in autocorrect preferences and goto step 3.

### Solution A:
Eliminate those two autocorrects (`---` and `--`)  from the default list.

### Solution B:
Automatically insert YAML frontmatter at top of file when creating a new file.

### Solution C:
Don't autocorrect `---` when it is at the start of a line.

**Screenshots**

## Platform
 - OS and version: OSX 10.15.3 (Catalina)
 - Zettlr Version: 1.5.0
 - Screen Resolution:

## Additional information

Keep up the great work!

**Comment by nathanlesage** [comment]
Yup, Was a bug in 1.5, which is why I rewrote the complete CodeMirror mode, and therefore it's already fixed! If you'd like to check it out, have a look at the most recent beta release on the releases page.
