### ISSUE TITLE
[FEATURE] Roam Research

### ISSUE THREAD

**Issue by davidlee321** [Zettlr/Zettlr#581]
# Description

While looking around for software like Zettlr, I came across [Roam Research](https://roamresearch.com/) "A note-taking tool for networked thought.". Roam Research's features seem well-thought out and supports zettel-kasten-ing (combining multiple "scattered" zettels seems particularly strong here) and markdown writing (including equations, tables, script-like evaluation).

It's **free** but **cannot be used offline**. Now in beta.

Videos of it in action [https://www.youtube.com/results?search_query=roam+research](https://www.youtube.com/results?search_query=roam+research)

I submitted this feature request with the intention of opening a discussion about features in Roam Research in the context of Zettlr. For example, should/could some of features inspire the future direction of Zettlr.

Thank you for reading.

**Comment by nathanlesage** [comment]
Hey,

funny that you mention it; I created a Roam account a few days ago to have a look what it's all about. Interestingly, Conor White-Sullivan (the dev of RoamResearch) is also a fan of Zettlr, and I believe there are some overlappings between both apps. According to him, for instance, cross-import/export between the apps seems to be possible.

The major benefits I've thought are with Roam Research are the networked thoughts, which will also become a feature of Zettlr at some time in the future, b/c while I'm doing research on neural networks, why not throw one at Zettlr.

In the end, I think that most Markdown editors, especially the ones in the writing/academic realm such as Abricotine, Typora, RoamResearch, and Zettlr, converge to a common ground, as I've noticed in the past that a lot of features Zettlr started gradually find their way into the other editors, and vice versa, as I've taken some inspiration from features others have.

Nevertheless, while I'm certainly open for any discussions pertaining this, as it's going to be really interesting, **please open up this very discussion over at the [discussion forum](https://forum.zettlr.com/), where it's more suitable**. With the huge amount of concrete feature requests and influx of discussion points here on the issue tracker, it's pretty important to divide all discussions across the respective platforms, I fear 🙈
