### ISSUE TITLE
[FEATURE] Define & use custom keys in YAML Frontmatter as global Filters

### ISSUE THREAD

**Issue by taubmann** [Zettlr/Zettlr#582]
## Description
Now as I am addicted to YAML Frontmatters to enritch my documents with metadata I feel the need for a cutomizable Filter (like the tag cloud) for predefinable keys like "status", "authors", "workflow_target", "categories", "importance" etc..

## Example Workflow
- In order to use these keys they have to be defined in the preferences (key-name, label, description)
- if some of these keys are found you have a dropdown for custom filters and a list (in future versions of the UI) or a "tag cloud" of all values associated to this key.

**Comment by taubmann** [comment]
Yes and no.
The definition of keys could work like the definition of colours.
I am not really interested in colors but in a list of values of pre-defined keys, so the search process could look like the tag cloud but with an additional dropdown where you can choose the key (represented by the label) to list all the values in all documents associated to this key. A click on one of this values would perform the search. The problem with the search is that values could be in lists as well (e.g. "authors: [Foucault, Deleuze]").
Adding a customizable filter for structured metadata would expand the possibilities to manage your files and tasks because you can add any possible "Order of Things" to your documents. If you want to build a simple ticket system to organize groups or you feel the need to pimp up your Zettelkasten with some additional meta-structures you are good to go. 
Of course in the future there could be demands like the combination of multiple searches (e.g. author + status) or the handling of numerical values and dates (e.g. duedate > 2020-03-06) but a first step behaving like the tag filter would also be a huge improvement.

**Comment by nathanlesage** [comment]
Sounds interesting, but I still can't quite figure it out — if you could prepare a sample workflow including code examples from YAML headers and how these would be represented, this would be helpful, but I'd like to direct you to the [forum](https://forum.zettlr.com/) for that!

**Comment by taubmann** [comment]
done
https://forum.zettlr.com/discussion/113/define-use-custom-keys-in-yaml-frontmatter-as-global-filters

**Comment by kastork** [comment]
I'm not sure if this relates or not, but...

I noticed today that when rendering PDF, some yaml metadata is not handled as one would expect by reading the pandoc markdown documentation.  For example, if I put

`keywords: [foo, bar]`

I would expect the PDF document to have those values in the PDF metadata for keywords.

or, if I put (as the docs suggest for XeLaTeX rendering)

`mainfont: TeX Gyre Pagella`

I would expect TeX Gyre Pagella to be use for body text.

Is this the expected behavior?

**Comment by nathanlesage** [comment]
Ah, please open up a new issue because the Zettlr template for PDFs needs an update for this!
