### ISSUE TITLE
Excluding some text for word count

### ISSUE THREAD

**Issue by nomad101** [Zettlr/Zettlr#583]
Hello, I've just discovered Zettlr and think it's great! Thank-you for developing this software.

Sorry if this is obvious - is there a method of selecting text which can excluded from the word count? For example, in a document, I have sections that are commented <!--- ---!> but they remain in the word count. Am I missing a way of doing this?

EDIT: Additionally, I also noticed that if text is striked out, it's still included in the word count. 

Thanks

**Comment by nathanlesage** [comment]
Hey,

strike-through text is always considered part of the word count, because it obviously constitutes part of what will be written! As to comments, this surely is a great idea!

**Comment by nathanlesage** [comment]
Aaaaand also done!

**Comment by nomad101** [comment]
Hi, I'm aware the plugin is being rewritten. Though I'm still using 0.77 with the legacy editor, as having a daily word count is crucial for my writing. However, I noticed that commented out text does not update the {word_count} as expected. But oddly, it still does update the {words_today} which should not happen. It would be great if could be fixed for those of using this feature. Thanks
