### ISSUE TITLE
Dragging image from attachment no longer works 

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#584]
## Description
When you drag an image from attachments just a file link is created, not the markdown code, so there's no image preview and the image doesn't appear in exports:

`file:///C:/temp/zettlr/index.jpg`

## Reproducing
Drag an image from attachments

## Expected behaviour
Markdown image code:

`![index.jpg](C:/temp/zettlr/index.jpg)`

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.6

**Comment by nathanlesage** [comment]
That damn drag&drop behaviour of JavaScript must've killed a decent amount of coders by now :D 

However, I just transferred the logic to wrap images into image links to the attachment sidebar (strange enough). Currently, the behaviour is as following:

1. Start dragging an image from the attachment sidebar, and the contents will be set to an appropriate image tag, which will be inserted into the editor.
2. Start dragging another file from there, and the link will be wrapped as a standard Markdown link.
3. Explicitly paste a normal (file) link, and nothing will happen to this.
4. Explicitly paste an image (file) link, and it will be rendered as an image.

I just discovered the inconsistency in the last two behaviours, and I'm pretty sure the last thing should not happen, right?

**Comment by marcusyoung** [comment]
Are you talking about new behaviour since 1.6 release? As in 1.6 neither 1 nor 2 happens.

R.e. 3 and 4. I'm not sure when you would actually be pasting links rather than files? And pasting image files doesn't do anything.

**Comment by nathanlesage** [comment]
> Are you talking about new behaviour since 1.6 release?

I am talking about the most recent commit I made two hours ago, so it's not in 1.6 :D

> R.e. 3 and 4. I'm not sure when you would actually be pasting links rather than files?

This is what I thought. Then I'll remove the reformatting from explicit pastes.

> And pasting image files doesn't do anything.

A.k.a. dragging image files from the explorer onto the app?

**Comment by marcusyoung** [comment]
Drag and drop from explorer produces an incorrect image tag. Displays ok in Zettlr but won't export because of the back slashes.

`![C:\temp\zettlr\index.jpg](C:\temp\zettlr\index.jpg)`

Copy and paste an image does nothing.

**Comment by nathanlesage** [comment]
> Displays ok in Zettlr but won't export because of the back slashes.

Does it work if the backslashes are replaced with forward-slashes?

> Copy and paste an image does nothing.

Just tried that out, interestingly, macOS does copy the image to the clipboard, but somehow Zettlr doesn't register that and instead only pastes the image filename. Could you please do me a favour of copying an image in Windows Explorer and then immediately "Inspect Clipboard" (in the develop menu with active debug mode), and tell me whether Windows does also copy the image data into the clipboard?

**Comment by marcusyoung** [comment]
> Does it work if the backslashes are replaced with forward-slashes?

Still displays in Zettlr but doesn't export.

Yes, the image is copied to the clipboard. Nothing at all is pasted though. That doesn't work, for example, in Typora either.  Not necessarily something I want, as long as you can get the images in from the attachments (and probably drag and drop too as Zettlr doesn't have an insert image menu option). Typora has a useful insert local image menu item that copies the image to the same directory as the doc and inserts it. That would be good to have.

**Comment by nathanlesage** [comment]
> Yes, the image is copied to the clipboard. Nothing at all is pasted though. That doesn't work, for example, in Typora either.

Hah, I think I can solve that issue pretty easily!

> Typora has a useful insert local image menu item that copies the image to the same directory as the doc and inserts it. 

This rings a bell, isn't there an issue open somewhere on this issue tracker with this request?

> Still displays in Zettlr but doesn't export.

Just for clarification: What is an image that will definitely export? Could you give an example of such an image tag (and, also the full absolute path to the image)? I still have a hard time understanding it, because I do not get all the different behaviours with links on Windows …

P.S.: Just implemented the pasting behaviour that when you copy an image from Windows Explorer Zettlr should from the next version onward offer you to copy the image to the current assets directory!

**Comment by marcusyoung** [comment]
This tag seems to work for HTML, PDF, ODT and DOCX:

`![index](file:///C:/temp/zettlr/index.jpg)`

Absolute path:

`C:\temp\zettlr\index.jpg`

**Comment by nathanlesage** [comment]
Alright, so WITH file, but WITHOUT backslashes … alright, I'm curious about the `file://`-protocol part (as this was causing problems on UNIXoid systems), but there will be some beta rounds where we can test out all possibilities!

**Comment by marcusyoung** [comment]
stale, but not fixed ... afaik

**Comment by nathanlesage** [comment]
Should work now in the most recent beta, please comment if it doesn't!
