### ISSUE TITLE
LaTeX is rendering in different sizes?

### ISSUE THREAD

**Issue by jrcharney** [Zettlr/Zettlr#585]
## Description

Well, this probably shouldn't be happening. I went to edit a markdown document with LaTeX in it and the font size got really big in some places.

## Reproducing
More than likely this is hapenning because a Math block is adjacent to a header, which this shouldn't happen.

```md
## Product-Chain Combo to show the Quotient & Reciprocal Rules
$$
\begin{aligned}
```

The Math block that follows is rendered in H2, despite it starting on the next line.

## Expected behaviour
Font should not change size.

**Screenshots**
![image](https://user-images.githubusercontent.com/1954239/76117187-fbb44680-5fb0-11ea-90e9-cd9ca0d354c9.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.6.0 (via Chocolatey)
 - Screen Resolution:

**Comment by danieltomasz** [comment]
I saw many times advice to leave blank line after headings, many parser have also sometimes problem with that https://github.com/DavidAnson/markdownlint/issues/143

**Comment by nathanlesage** [comment]
One screenshot as above but with only the source code visible would help to identify the problem!

**Comment by jrcharney** [comment]
> One screenshot as above but with only the source code visible would help to identify the problem!

Let me try a larger code sample.

Both of these code blocks are correct.
The code following the first H2, renders correctly, but the code following the second H2, renders larger in size.  This seems to alternate.

```md
## Product-Chain Combo
$$
\begin{aligned}
(f \cdot (h \circ g))' & = f' \cdot (h \circ g) + f \cdot (h \circ g)' \\ & = f' \cdot (h \circ g) + f \cdot (h' \circ g) \cdot g' 
\end{aligned} 
$$
What if the first term is the composition? Then we have this.
$$
\begin{aligned}
((h \circ f)' \cdot f) &= (h \circ f)' \cdot g + (h \circ f) \cdot g' \\
&= (h' \circ f) \cdot f' \cdot g + (h \circ f) \cdot g'
\end{aligned}
$$

## Product-Chain Combo to show the Quotient & Reciprocal Rules
$$
\begin{aligned}
(f \cdot (h \circ g))'(x) & = f'(x) \cdot (h \circ g)(x) + f(x) \cdot (h \circ g)'(x) & \text{Product Rule} \\
 & = f'(x) \cdot (h \circ g)(x) + f(x) \cdot (h' \circ g)(x) \cdot g'(x) & \text{Chain Rule}\\
 & = f'(x) \cdot h(g(x)) + f(x) \cdot h'(g(x)) \cdot g'(x) & \text{Function Composition} \\
 & = f'(x) \cdot [g(x)]^{-1} + f(x) \cdot [-g(x)^{-2}] \cdot g'(x) & \text{let}\ h(x) = \frac{1}{x}\\
 & = \frac{f'(x)}{g(x)} - \frac{f(x) \cdot g'(x)}{[g(x)]^2} & \text{Reciprocal} \\
 & = \frac{f'(x)}{g(x)} \cdot \frac{g(x)}{g(x)} - \frac{f(x) \cdot g'(x)}{[g(x)]^2} & \text{Factorization} \\
 & = \frac{f'(x) \cdot g(x) - f(x) \cdot g'(x)}{[g(x)]^2} = \left( \frac{f}{g} \right)'(x) & \textbf{Quotient Rule} \\
 & = \frac{0 \cdot g(x) - 1 \cdot g'(x)}{[g(x)]^2} & \text{let}\  f(x) = 1 \\
 & = - \frac{g'(x)}{[g(x)]^2} = \left( \frac{1}{g} \right)'(x) & \textbf{Reciprocal Rule} \\
\end{aligned}
$$
```

**Comment by nathanlesage** [comment]
Interesting … I fear this will require some more testing, because apparently Zettlr is — out of reasons I do not yet know — applying the heading-two-class to the code following the h2
