### ISSUE TITLE
Cannot open cited documents from Zettlr

### ISSUE THREAD

**Issue by nistude** [Zettlr/Zettlr#586]
## Description

According to the release notes, it should be possible to open cited docs with Zettlr. 1.6. Right-clicking on citekeys in the doc or citations in attachments does not provide any way to open files on Linux.

**Screenshots**
![Screenshot from 2020-03-07 06-11-48](https://user-images.githubusercontent.com/240915/76137248-ee439e80-603a-11ea-8f8d-9bc38866f01b.png)

## Platform
 - OS and version: Debian Linux
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
It is because the citation has not been rendered. The citation rendering must be turned on for this to work, because the context menu infers that it's a citation from the element type!

**Comment by nistude** [comment]
Thanks a lot for the quick reply, works as advertised :man_facepalming:
