### ISSUE TITLE
[ENHANCEMENT] Apply current search while changing folder

### ISSUE THREAD

**Issue by UBy** [Zettlr/Zettlr#588]
If you search (free form or tag) it would be nice if the search is then applied if you change folder.
I can, of course, search from the root folder, but sometimes that gives too many results.

In any case i'ts annoying having to activate and press enter in the search box every time you select a new folder. You could argue, that if the search is not applied, the search box should be cleared.

**Comment by nathanlesage** [comment]
Ohh, nice thought!
