### ISSUE TITLE
Zettlr does not update image preview on image change

### ISSUE THREAD

**Issue by escapedsalmon** [Zettlr/Zettlr#59]
## Description
When changing an image while it's loaded in Zettlr for preview it seems Zettlr is having issues updating the image.

## Reproducing
Include any image (in my case I used PNG) into your markdown file/code, wait for Zettlr to generate the preview. Then change the file, e.g. replace it with another image. Zettlr won't update the image, even if you use backspace and remove one of the brackets. Only removing the image tag and rewriting this helps - or restarting Zettlr.

## Expected behaviour
If not auto updating then at least refreshing the preview image if you use backspace and remove one of the brackets or so.

**Screenshots**
uh.. probably not useful here.

## Platform
 - OS: elementary OS
 - OS Version: 5 (based on Ubuntu 18.04)
 - Zettlr Version: current develop branch
 - Screen Resolution: nah

**Comment by nathanlesage** [comment]
The easy answer to this: Zettlr is fundamentally a browser, and a browser caches content, including images.

The hard answer: Electron does not feature any flush-cache-functionality during browser runtime.

The mind-numbingly simple solution: Add a fake URL-argument to the end of each image to make Electron reload the image everytime from disk 🤷‍♀️

I now feel stupid for having thought all day about this.
