### ISSUE TITLE
Zettlr crashed when performing folder-to-folder migration

### ISSUE THREAD

**Issue by light42** [Zettlr/Zettlr#593]
## Description
Zettlr hangs when I moved folder with only markdown files in it to another folder.

## Reproducing
1. Prepare two folders, each have more than 10 markdown files.
2. Try to move one folder to another.

## Expected behaviour
Operation should run without any problems.

**Screenshots**

## Platform
 - OS and version: Linux Mint Tricia 19.3
 - Zettlr Version: 1.6.0 AppImage
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
One of the reasons for the FSAL-rewrite, because operations such as these need to be faster. Closing in favor of the meta-issue, if you notice other things, where Zettlr is slow/laggy/fails completely, please feel free to comment! https://github.com/Zettlr/Zettlr/issues/392
