### ISSUE TITLE
[ENHANCEMENT] Modifications for Keyboard Navigation

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#594]
## Description

While I'm aware of requests such as VIM keybindings etc, this issue is to address some really minor things I'd like to improve. Concerning navigability of documents

## Proposed Changes

* When in a list-item, <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> should trigger at every single position within the line and indent/unindent
* When pressing <kbd>Pos1</kbd> (Win/Linux) or <kbd>Cmd</kbd>+<kbd>&larr;</kbd> in a list item, the curser should be moved in front of the first character of the list item, that is: _after_ the list-formatting character and its trailing space. If the cursor is already there, pressing <kbd>Pos1</kbd> or <kbd>Cmd</kbd>+<kbd>&larr;</kbd> again will move to the real beginning of the line. Similarly with other block-level elements (headings, blockquotes)
* If pressing <kbd>Tab</kbd> outside of a list item, it should insert the amount of indentation-spaces from the preferences. Why? Tab was originally meant to align text at given markers on the paper (which is what you can see in Word, for example). However, in the world of Markdown, this is nonsensical and has already been observed by many of you: Tab simply renders with zero width, because there is no grid to align it at. Tab-characters are a thing of the past, or at least they're confined to working with confined spaces.
* When emboldening text or emphasizing, it should work more like Word/LibreOffice, that is: Selecting text and pressing <kbd>Cmd/Ctrl</kbd>+<kbd>I</kbd> should take all text, detect if it's italic, and if it is, revert, and vice versa, taking into account formatting characters _outside_ of the text selection.

## Caveats

As keyboard shortcuts are something engraving itself in muscle-memory, this will certainly disrupt existing workflows to a certain degree. But in the end, I believe it'll be worth the risk, because in the long run it'll speed up writing again, because it works more _logical_ this way.

## Additional Information

Something missing? Please comment, and I'll add it to the list! Remember: This issue is only for these **very small** behavioral changes, not bigger requests such as VIM keybindings!

**Comment by unsungNovelty** [comment]
> When in a list-item, Tab and Shift+Tab should trigger at every single position within the line and indent/unindent

@nathanlesage This is also for a todo list (- [ ] task) and not just for list item. I am unable to indent a to do list item when I press tab (4 spaces). This is also a bit of a problem as I copy paste some of the note contents from my old note application. The indentation is removed. Hope this helps.

PS: Thanks for this app! :boom:

**Comment by nathanlesage** [comment]
Todolists are treated as lists.
