### ISSUE TITLE
[ENHANCEMENT] Import Support for Evernote ENEX Files

### ISSUE THREAD

**Issue by varian93** [Zettlr/Zettlr#596]
## Description
Add support for importing Evernote's ENEX export format.

## Proposed Changes
I'm not sure how helpful this might be, but there seems to be something that already supports this that might be available to be included: 

https://github.com/notable/dumper

I didn't look too terribly hard, there may be better/easier solutions.

## Caveats
Nothing comes to mind.

## Additional Information
I realize that Evernote supports exporting notes to HTML format and that Zettlr supports the importing of HTML files, however Zettlr's HTML importing (via Pandoc) is extremely sloppy requiring extensive manual cleaning. I anticipate that the simpler the  HTML document the more cleanly they'll convert, but Evernote's do not convert well & neither did a few random HTML files from the web.

**Comment by nathanlesage** [comment]
Yep, I also got that on my mind to build an ENEX-importer, however, currently low priority due to the other refactoring going on! But the library does seem like a good starting point that'll make the work easier!

**Comment by varian93** [comment]
Sounds great.

The application that used that library ([Notable](https://github.com/notable/notable)) choked earlier while importing a little over 500 notes from Evernote. It got to around 330 before giving the following [error](https://github.com/notable/notable/issues/1082). 

I'm not sure how you feel about that.

Later I tested [Joplin](https://github.com/laurent22/joplin) which also supports importing from Evernote and it worked without error. It might be a better choice from which to borrow code. The only down side was that any nested tags I had were un-nested by being imported, not a major issue. 

If nested tags are a functionality that you'd like to maintain then a simple "/" should work (e.g. #Parent/Child/Nested).

**Comment by nathanlesage** [comment]
Alright, I'll have a look. Maybe even a new library that works out of the box, if Joplin's library is not available standalone!
