### ISSUE TITLE
[ENHANCEMENT] Settings - Pop Up Descriptions On Hover

### ISSUE THREAD

**Issue by varian93** [Zettlr/Zettlr#597]
## Description
It would be quite helpful if when the mouse is hovered over any of the settings in the settings/preferences section of Zettlr a "pop up" dialog would appear with a brief description of what the settings does. 
 

## Proposed Changes
I don't know what would be required.

## Caveats
Nothing comes to mind.

## Additional Information
It would be even better if it would include something clickable that would take you to a more extensive description in the correct location of the documentation.

**Comment by nathanlesage** [comment]
> I don't know what would be required.

Well, the popups aren't the problem, as we're using Tippy.js either way so it's loaded into the app and'll work.

But what would be necessary would be description translations, hence a huge pile of stuff to put on Zettlr translate. :D But it's certainly worth considering, as well as a First-Start-Guide in-app
