### ISSUE TITLE
Extremely sensitive vertical scrolling

### ISSUE THREAD

**Issue by mgiugliano** [Zettlr/Zettlr#598]
Upgrading from 1.5 to 1.6, I noticed that on a macOs laptop, the velocity of vertical scrolling upon the two finger gesture on the track pad, is extremely high. Therefore scrolling is annoyingly too sensitive and almost unusable.

**Comment by nathanlesage** [comment]
I haven't noticed this during beta, so I'm puzzled — does it mean that you're experiencing this annoying "way too fast scrolling"-problem?

**Comment by mgiugliano** [comment]
Yes. I have been using Zettlr intensively in the last 2 weeks and now it is way too fast, after the upgrade. I did not upgraded the OS or changed any other component.

I can live with it, but it seems application-specific.

**Comment by nathanlesage** [comment]
This is, in fact, weird because it should've happened to me as well — I noticed this at some point as well, but only extremely rarely and not consistently, which is why I never investigated. Is it happening constantly for you, or only with specific contexts or files?

**Comment by mgiugliano** [comment]
Just tested: it happens irregularly, after (re)starting Zettlr. 

Now that I have publicly reported it to you, and just restarted Zettlr, it stopped (Murphy's corollary) :-)

Thank you for Zettlr and for your attention.

**Comment by nathanlesage** [comment]
> Now that I have publicly reported it to you, and just restarted Zettlr, it stopped

Hehehehe! Reminds me of this meme:

![image](https://user-images.githubusercontent.com/17251683/76394384-b491d100-6375-11ea-9696-268a42749202.png)

Okay, if you find out anything that may be causing this, please get back in touch here! :)
