### ISSUE TITLE
Unexpected behavior when pressing enter twice in global search

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#599]
## Description

If I search for word in global search and press enter twice quite fast, Zettlr shows the results twice on the sidebar.

## Reproducing

Press CTRL+SHIFT+F to activate global search. Write text that finds results. Press enter twice fast.

## Expected behaviour

Zettlr should start the search again when pressing enter the second time.

## Platform
 - OS and version: Windows 7
 - Zettlr Version: 1.6 stable

**Comment by nathanlesage** [comment]
Oh, yes! Good point!

**Comment by nathanlesage** [comment]
Now I see that there is approximately one duplicate file, but only if you are EXTREMELY fast in pressing return a second time, which is close enough!

**Comment by Zverik** [comment]
Yeah, tried that and could not reproduce, while in 1.6 it was very easy.
