### ISSUE TITLE
Feature Request: Attachment Pane

### ISSUE THREAD

**Issue by sahil48** [Zettlr/Zettlr#6]
It would be great to have a pane to the right of the editor that could show attachments like pdfs and images that exist in the same folder and subfolders of the document open. Double clicking on the attachment would open it in the system viewer.

**Comment by nathanlesage** [comment]
What do you mean by attachment pane? What kind of attachments are you thinking about? As I see it, it doesn't make sense to attach other documents/files/else to text documents, but I might be missing a way of using this, so please elaborate further!

**Comment by sahil48** [comment]
A list of documents (pdf, excel, matlab, etc) in the same folder or subfolders of the document open. That way, it is easier to get to documents you would reference while writing.

**Comment by nathanlesage** [comment]
Ah, I see what you mean. I'm unsure whether a separate pane would do it or a way to show/hide those files a little bit greyed out directly in the preview pane?

**Comment by sahil48** [comment]
I think a separate pane would be best. I view it as a supplement to the document being edited and would rather it not clutter the preview pane. It could even be enhanced into something akin to a research pane, where it could show definitions of the word you are on, and a link to a related Wikipedia article, and option to search in google. Basically, gives you a way to access documents and websites that could be relevant to the document you are editing.

**Comment by nathanlesage** [comment]
Ouh, that _does_ sound lovely. A multifunctional pane is definitely a good thing. I think I'll simply make it move in from the right side, thereby a little bit hiding the editor contents, just so that you can pull it in as long as you need it, and easily hide it again.

**Comment by karthikjipmer** [comment]
How do I attach a file (such as a pdf) stored in a different directory to the current document? Sort of like an external link.

**Comment by nathanlesage** [comment]
@karthikjipmer By copying it to the current directory. The attachment sidebar simply lists all documents whose extensions are in the config (see Preferences -> Advanced) that are in the currently listed directory. Symbolic links do not work with the attachment sidebar.
