### ISSUE TITLE
Support for escaped hash marks for non-tags

### ISSUE THREAD

**Issue by kwoodham** [Zettlr/Zettlr#60]
## Description

I have markdown notes that describe a list of items that are numbered using the hash sign in the original reference:

- Item `\#1`: This
- Item `\#2`: That

I am using `\` to escape the hash so that these items are not considered tags, but they are showing in my tag list as `1`, `2`, etc...

## Reproducing

See above

## Expected behaviour

Expecting that the use of the escape character would eliminate these items from being captured as tags.

**Screenshots**

## Platform
 - OS: Windows
 - OS Version 10
 - Zettlr Version 1.0.0-beta

## Additional information

Amazing work! Thank you!

**Comment by nathanlesage** [comment]
Whoops, I was sure I implemented the negative lookbehind in the RegEx. Apparently, I forgot it. Attached patch fixes this! :)

I also managed that escaped tags won't render as tags in the editor as well!
