### ISSUE TITLE
[ENHANCEMENT] Pomodoro timer could have a test volume level button

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#602]
## Description

Pomodoro timer should have a button; test sound. That way I can adjust the volume correctly. One option could be, that once the user activates the sound button, a sound could be heard and volume could be adjusted accordingly.

**Comment by nathanlesage** [comment]
Idea would be to set the sound bar to zero, and play the sound in the correct loudness as soon as you release it, which would keep the UI clean and still offer valuable feedback.

**Comment by nathanlesage** [comment]
And here we go! The sound will now always play as soon as you release the mouse on the volume slider.

![image](https://user-images.githubusercontent.com/17251683/76658928-73680f80-6575-11ea-8131-8b09356db5c4.png)
