### ISSUE TITLE
[FEATURE] Zettelkasten ID based on week number

### ISSUE THREAD

**Issue by jakeoung** [Zettlr/Zettlr#604]
## Description
I want to use shorter ID e.g., 2011xxx which means 2020 year 11 week and xxx can be any number. It would be nice to support

- two digits of year number
- week number

**Comment by nathanlesage** [comment]
Should be no problem to add to the ZKN variables!

**Comment by nathanlesage** [comment]
And done.

**Comment by jakeoung** [comment]
Thanks a lot for adding this feature. Just wonder if it's possible to add two digit year number. (e.g., 20 for 2020 year or 21 for 2021 or something).

**Comment by nathanlesage** [comment]
Feel free to [check out the commit](https://github.com/Zettlr/Zettlr/commit/de29756df9daadff716f3ec3b7265327aad21191) I did and reproduce this for two-digit years!
