### ISSUE TITLE
[ENHANCEMENT] Unconventional drag paint -selection in global search field

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#605]
## Description

Selecting global search -field text works unconventionally.

## Proposed Changes

Write something in global search field. Now make the field unactive. Now try to drag and paint the unactive search field text. Zettlr grabs the text for drag and drop.

Now test the same thing for example in browser URL field. Instead of dragging and dropping the text, cursor paints part of the text.

Latter should be normal behavior in Zettlr also.

Right now if I want to paint some of the text in Zettlr global search field, I have to click the search field twice before I can paint part of the text and prevent drag and dropping.

## Caveats

None.

## Additional Information

Zettlr 1.6
Windows 7

**Comment by nathanlesage** [comment]
Indeed! Curious. I'll investigate

**Comment by nathanlesage** [comment]
And got it.
