### ISSUE TITLE
[ENHANCEMENT] When in thin sidebar mode, left-clicking folder could navigate to upper folder

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#606]
## Description

When in thin sidebar mode, left-clicking folder could navigate to parent folder.

## Proposed Changes

I have ROOT\folder1\folder2.
If I am in folder2 and click back-circle-arrow, Zettlr goes to ROOT. If I want from folder2 to folder1, I have first go to ROOT and then to folder1.

Zettlr could go to folder1 when clicking folder2-titletext when in folder2.

Right now clicking folder2-titletext does nothing.

## Additional Information

Zettlr 1.6
Windows 7

**Comment by nathanlesage** [comment]
Alt-clicking will do the job! Click to enter a certain directory, alt-click to move to its parent!
