### ISSUE TITLE
[ENHANCEMENT] Clickable Tags in YAML Frontmatter 

### ISSUE THREAD

**Issue by privid** [Zettlr/Zettlr#607]
## Description
Make #tags included in the keywords: field of YAML frontmatter clickable.

## Proposed Changes
When you put #tags in the keywords: meta-data field of YAML front-matter, they should be clickable like in the rest of the document. This way I can prepend "keywords:" to the tag-list to nicely organise the file and still have the entire line disappear in exports. 

## Caveats
/

## Additional Information
<img width="502" alt="Screenshot 2020-03-11 at 15 41 09" src="https://user-images.githubusercontent.com/1971633/76429624-95179a00-63af-11ea-95cd-d328b6eb2afb.png">

**Comment by nathanlesage** [comment]
Sounds like a reasonable improvement! Albeit you should encapsulate the tags in quotes, because otherwise they'll be treated as comments! ;)

**Comment by LukeCarrier** [comment]
Apologies for spam, bumping because of stale bot. I'd love to see this feature too!
