### ISSUE TITLE
Search and replace -popup closes when selecting text and releasing left mouse button out of the popup

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#609]
## Description

Search and replace -popup closes when selecting text and releasing left mouse button out of the popup.

This used to occur also in settings dialog but it is fixed in Zettlr 1.6.
This problem still occurs with search and replace -popup.

Description taken from 1.6 release notes:
>Made the dialogs more resilient. Now you can select text somewhere on dialogs, and regardless of whether you accidentally moved too far (out of the dialog), it will not close anymore, when you release the mouse.

Source: https://github.com/Zettlr/Zettlr/releases

## Platform
 - OS and version: Windows 7
 - Zettlr Version: 1.6 stable

EDITED: As nathanlesage said, dialog --> popup.

**Comment by nathanlesage** [comment]
Dialog ≠ popup — the dialogs are the fullscreen things, popups the small … well, popups.

**Comment by nathanlesage** [comment]
And fixed!
