### ISSUE TITLE
[ENHANCEMENT] Down and up arrow keys could navigate up and down in sidebar file list

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#610]
## Description

Down and up arrow keys could navigate up and down in sidebar file list. Now the arrows do nothing when pressed.

## Caveats

None.

**Comment by nathanlesage** [comment]
They already do so, if the file list is focused (with `Alt` and `Ctrl/Cmd` navigating by ten files or to the end respectively). However, the shortcut is currently broken on Windows and Linux, which I'll investigate in a different issue which is already open!
