### ISSUE TITLE
retrieving relevant info from zettlr and opening or copying that

### ISSUE THREAD

**Issue by RMHogervorst** [Zettlr/Zettlr#611]
I just started using zettlr and quite dig it. I'm using the zettelkasten mode and although creating notes and connecting them works I have a question about retrieval of linked notes. 

What I'd like to do is follow a train of thoughts (zettels/notes, connected) and retrieve all relevant ones for a piece I'm writing. Ideally copying that to a new environment to work with. 

But I seem to be 'only' able to 

- open one note at the time
- create virtual folders? 

Is there a best practice, a guide on the docs page, a blog post I could read?
Or is this missing functionality? *

(*) seems unlikely, how are all the other users using this software if you never retrieve connected notes?

**Comment by IpeTek** [comment]
Retrieving links/connections in some form has already been discussed in #217. As maintained in the Roadmap to 1.7 new features won't be added until 1.8. 

I'll manage by browsing through the linked paths manually. And oftentimes it is a very efficient method keeping one immersed in the subject matter at hand. But sometimes I, too, long for a quick visualization of connections in between all my Zettels. Connectedtext offers one example of what I'm after with its navigator. But I hope Zettlr-links cater for an even better way to implement the needed function.

**Comment by nathanlesage** [comment]
> But sometimes I, too, long for a quick visualization of connections in between all my Zettels.

I fully understand this. I recently closed an issue again demanding this feature, and I understand that this is still a dealbreaker for many of you. However, as I am still the sole maintainer doing 99 percent of the coding, I have to make concessions. So I had to decide that 1.7 will not include anything except a rewritten file core (because it does not scale, and if I don't get to it now, it'll become an urgent problem in the next iteration of the app). Furthermore, implementing file linkages does require a rather complicated and hefty algorithm which needs to be planned accordingly.

I too wished all these features would make it into the app at once (because then I could have a free weekend for once again lol), but it's not realistic as long as there are no contributors.

**Comment by nathanlesage** [comment]
Concerning OP:

> But I seem to be 'only' able to open one note at the time

Yup, this will be changed in 1.7 with the rewritten file core. One of the plenty examples why this rewrite is urgently necessary. The current configuration is unable to handle more than one open file. Tabs will come in 1.7!

> Is there a best practice, a guide on the docs page, a blog post I could read?

Puhh, not really. The whole idea behind Zettlr is to enable everything without commanding anything. Many users of Zettlr make use of Zettelkasten information on the web (e.g. www.zettelkasten.de) and apply this in one or another way to the app! Nevertheless, if you feel some parts of the docs are missing, please feel free to [open up an issue for that](https://github.com/Zettlr/zettlr-docs/issues)!

> (*) seems unlikely, how are all the other users using this software if you never retrieve connected notes?

Depends on how you define missing — you can certainly manage with a combination of outline notes, the global search, and QuickLooks. But that's only my three years of experience speaking, it may be that there are other or simpler ways! But as I outlined in the comment above, a "real" tool in the sense of visualising linked notes will be coming, but not yet!

If you have further questions, please do not hesitate to ask them on the forum, and if it really becomes clear that a feature is missing, I warmly welcome you to open an issue for that!

**Comment by IpeTek** [comment]
Thanks for replying promptly. Very good to know that this feature is coming. So, it's donation time again! And no hurry: There are many tools providing visualization and I, at least, am willing to wait for a little longer for a well thought out implementation :) .

**Comment by RMHogervorst** [comment]
thank you for answering! I value your reply @IpeTek  but I probably didn't write it clear enough. 
Because I wasn't really looking for a linked graph of all linked notes, I agree that would be quite difficult. I wanted to manually open multiple notes while I go through them so I have all of them open. 
So cool that you are working on the ability to open multiple notes at the same time @nathanlesage 

I love this goal:

> enable everything without commanding anything

I will investigate outline notes, the global search, and QuickLooks
And maybe I'll add some details to the docs if I have that clear
Thanks!
