### ISSUE TITLE
Strange Spell Check Error Visualization Behavior

### ISSUE THREAD

**Issue by varian93** [Zettlr/Zettlr#613]
## Description

When a word is not found in the dictionary, its visualized by some somewhat difficult to notice sparsely placed red dots under the word. It seems as though it is "trying" to display red dots across the whole of the word, but is encountering difficulty. I've seen screenshots of what its supposed to look like & it does not match what I'm seeing. It's not a huge issue, but it is not consistent with what other users of the software are experiencing.

## Reproducing

Type any unrecognized word.

## Expected behaviour

A more easily noticed/consistent display beneath the unrecognized word. I don't take issue with the dots, but rather the lack of their completeness.

**Screenshots**

![example](https://user-images.githubusercontent.com/42175982/76680236-4c353080-65bd-11ea-89c1-d85b6d2ab86c.png)

## Platform
 - OS and version: Windows 10 (Home) version 1909 build 18363.720
 - Zettlr Version: Zettlr v1.6.0
 - Screen Resolution: Dual Monitors. Issue occurs on both. Monitor 1: 1920x1080 Monitor 2: 1280x1024

## Additional information

I searched for open issues on this & did not find any.

**Comment by nathanlesage** [comment]
The problem is concerning the baseline of the used font, sometimes it's too low, sometimes too high. I have not gotten to a consistent solution so far.

**Comment by ryota-abe** [comment]
How about using `text-decoration-skip-ink: none;` ?
Before: 
![image](https://user-images.githubusercontent.com/15438757/76702258-d5f31400-670b-11ea-9ac6-e9cd5f4a37a8.png)
After: 
![image](https://user-images.githubusercontent.com/15438757/76702247-bbb93600-670b-11ea-8073-d94ff805f7ca.png)

**Comment by nathanlesage** [comment]
Oooooh, I didn't know about that property o_O

Consider it in the codebase! Thanks again!
