### ISSUE TITLE
Table is invisible

### ISSUE THREAD

**Issue by AIBN60** [Zettlr/Zettlr#614]
## Description
When creating a table with the format button, the table is invisible in Zettlr. The table is created as can be seen in txt-output

## Reproducing

position cursor in text, press AA-Button and create table. Export to txt to verify 

## Expected behaviour

show table
![invisibleTable](https://user-images.githubusercontent.com/62201504/76698757-e91fc880-66a6-11ea-8c98-9e68885c6867.png)

**Screenshots**

## Platform
 - OS and version: 
Unix-Kernel: 4.15.0-88-generic
Ubuntu-Version: Ubuntu 18.04.4 LTS

 - Zettlr Version: 
1.6.0

 - Screen Resolution:
1920*1080

**Comment by nathanlesage** [comment]
Thanks for reporting! Found the error: Empty rows were also assumed to be header rows during the parse state. I just fixed that!
