### ISSUE TITLE
[FEATURE] Link/Relation Map

### ISSUE THREAD

**Issue by okaybadger** [Zettlr/Zettlr#617]
## Description
It will be valuable if Zettlr can help to visualize the relationship between wiki links, like Roam Research and Trilium does. Indeed, the foundation of the Zettelkasten method is helping the mind to recogize the relationship of ideas.

## Example Workflow
A sidebar to display the relation map will be cool.

**Comment by nathanlesage** [comment]
Hey! Thanks for opening the issue!

Zettlr will in fact be getting something like that. But not a link/relation map, something different ;)

More on that when it's ready!

**Comment by okaybadger** [comment]
I'm super excited to hear that! I very appreciate the enormous efforts you put into this project!

**Comment by endorama** [comment]
Hi @nathanlesage, I was searching for this exact same feature. I wasn't able to find it in the docs so I'm wondering if "will in fact get" has already been implemented or is still a work in progress :) 
Thanks for your time!

**Comment by nathanlesage** [comment]
@endorama Postponed due to a lot of other work. It has no priority, but there's an open PR that attempts something similar. Please check that out.
