### ISSUE TITLE
[ENHANCEMENT] More Verbose Output for Invalid Citation Library Entries

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#618]
## Description
When Zettlr encounters an invalid citation, then it displays "Invalid Citation - Invalid citation passed: bibtexkey". It would be nice to have more information what actually went wrong.

## Proposed Changes
Show (or at least log) more detailed information about why this particular citation is invalid.

## Additional Information
For example, the following entry seems to make trouble for Zettlr but I cannot figure out why:
```
@Book{Römer2005,
  author    = {Römer, H.},
  title     = {Theoretical optics: an introduction},
  isbn      = {3527404295},
  publisher = {Wiley},
  file      = {:Römer2005 - Theoretical Optics_ an Introduction.pdf:PDF},
  groups    = {Semi-classical},
  priority  = {prio1},
  year      = {2005},
}
```

**Comment by nathanlesage** [comment]
Yes, this is the plan! Have also a look at the [related forum thread](https://forum.zettlr.com/discussion/80/citation-database)!

**Comment by nathanlesage** [comment]
I just sat down, and now Zettlr will remove malformed citation items and provide you with extended error messages!

**Comment by tobiasdiez** [comment]
Thanks for your quick reaction. However, the newly added validation check doesn't find any errors. 
I debugged the problem and found out that the error is raised here
https://github.com/Zettlr/Zettlr/blob/497d9050a86ffa78ade5acdca264b50737d2a9b5/source/main/providers/citeproc-provider.js#L221-L224

This also reveals that the problem is the citation key (and not the bibtex code itself). This wasn't clear to me from the error message. 
By the way, the [biblatex documentation](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf) says the following about the entry key:
> Note that the set of characters allowed and usable in the string for entry key depends on the backend (biber, BibTeX) as well as the LaTeX engine (pdfLaTeX, Lua-LaTeX, XeLaTeX). Generally, ASCII-letters (a-z,A-Z) and numbers (0-9) are safe,so are the punctuation characters full stop (.) and solidus (/). The punctuation characters-_:;!?are also safe even if they are made active bybabel/polyglossia.If a Unicode engine is used, non-ASCII characters are also acceptable. Curly braces({}), commas, spaces, backslashes (\), hashes (#), percent characters (%) and tildes(~) are always forbidden. biber additionally forbids round brackets (()), quotation marks (",'), and the equals sign (=)

So in this sense `Römer2005` would be a valid key.

**Comment by nathanlesage** [comment]
> This also reveals that the problem is the citation key (and not the bibtex code itself). This wasn't clear to me from the error message.

Yes, this is something I realised after I pushed the changes, that misled citekeys are checked earlier than this, so what I wanted to do anyway is merge these two checks in the next week. I already have that on my radar!

> So in this sense Römer2005 would be a valid key.

That should — by now — work, because I defused the algorithm months ago, so I don't know why it does print a warning…?

Just did a quick test on the Citr repository, and here's nothing bad happening:

![image](https://user-images.githubusercontent.com/17251683/77339729-85437280-6d2c-11ea-98b7-de8cb4196260.png)

(P.S.: Also I saw this one "invalid-key" … have to get to the repository soon)

**Comment by tobiasdiez** [comment]
Sorry for the false alarm. There was indeed a problem in the key. It was `@Römer2005` where the umlaut was created using the combination U+006F : LATIN SMALL LETTER O U+0308 : COMBINING DIAERESIS instead of the usual `ö` U+00F6 : LATIN SMALL LETTER O WITH DIAERESIS .

This leaves the slightly confusing exception text, which should be fixed with https://github.com/Zettlr/Citr/pull/2.

**Comment by nathanlesage** [comment]
I just had a look at that PR! I'll give it more thought tomorrow! But I think the main part should be that Zettlr uses these errors correctly, which I'll get to after my moving!
