### ISSUE TITLE
[ENHANCEMENT] Support JabRef's fileDirectory feature

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#619]
## Description
JabRef allows the user to choose a directory and then all references in the `file` field are relative to this directory instead of relative to the bib file.

## Proposed Changes
It would be nice if Zettlr could support this. Right now it is assumed that the linked attachments are relative to the bib file, so that none of the pdfs are found if a user uses the `fileDirectory` feature of JabRef.

## Additional Information
JabRef stores the file directory at the end of the file in the format
```
@Comment{jabref-meta: fileDirectory:\\..\\..\\..\\..\\Literature\\;}
@Comment{jabref-meta: fileDirectory-tdiez-TUD205196:H:\\My Documents\\Literature;}
```
The link can be relative (to the bib file) or an absolute file. Moreover, it is possible to store file directories per user (e.g. to support different file structures on different computers). I guess the later is not that important for the moment.

If you give me some pointers where to look, I can also try to implement it myself.

**Comment by nathanlesage** [comment]
Hey, good idea to support! Should also not be too difficult to implement!

Here's how it goes currently:

1. On [this line](https://github.com/Zettlr/Zettlr/blob/develop/source/main/providers/citeproc-provider.js#L203) in the citeproc-provider, the attachments are parsed from the BibTex-file. As `basePath` we assume, as you correctly pointed out, the CSL file. But there's no need to change that line as the `basePath` is a sound fallback.
2. This function parses the BibTex-file (which is a JSON object) and extracts all attachments, converting those that are not absolute into absolute files. It returns a dictionary (a.k.a. nulled Object) in the form `'citeKey': ['/path/to/attachment_one.pdf']`

Some tips: You want to look at all `Comment`s prior to [this line](https://github.com/Zettlr/Zettlr/blob/develop/source/common/util/extract-bibtex-attachments.js#L31); it may help to `console.log(ast)` to see where the `fileDirectory` is stored, and also make sure to fall back to `basePath` in case there is no `fileDirectory`. [This line](https://github.com/Zettlr/Zettlr/blob/develop/source/common/util/extract-bibtex-attachments.js#L48) does the rest of the magic.

As soon as you're ready, make sure to PR to the `develop`-branch, and I'll be happy to merge! Don't forget to continue the good commenting!

**Comment by nathanlesage** [comment]
@tobiasdiez How's it going?
