### ISSUE TITLE
[ENHANCEMENT] auto-complete tags in global search field

### ISSUE THREAD

**Issue by varian93** [Zettlr/Zettlr#621]
## Description
Enhance the global search's auto-complete feature to include auto-completing of tags as well as file names. This would be useful when you're unsure of the exact tag or form used. Was it "art_ideas", "ArtIdeas" or some other similar ambiguity. 

## Proposed Changes
I'm unsure of how this could be implemented.  I just experienced the workflow impediment. 

## Caveats
Any potential ones could be solved through user preference settings. 

Global Search Auto-Complete:
* Tags[Y/N]
* File Names [Y/N]

**Comment by nathanlesage** [comment]
Could be a good thing, but it has to wait for the global search to be improved. I've been experimenting with contenteditables, and this would fit in there, so it has to wait but it's certainly a good idea!

**Comment by nathanlesage** [comment]
*push*
