### ISSUE TITLE
[FEATURE] UI has small icons and font size on 4K UHD monitors

### ISSUE THREAD

**Issue by tjerry** [Zettlr/Zettlr#623]
## Description
User interface has very small icons and font size on 4K/UHD monitors.

![file](https://user-images.githubusercontent.com/2649031/77229315-1c6dc600-6b85-11ea-9e93-ec16de54f45d.jpeg)

## Example Workflow

Make icons and font size scale on high DPI monitors.

**Comment by nathanlesage** [comment]
I want your display, it's so big uwu. Just joking, I've got a 4k myself :D I seldomly use it on there, which is why I never felt the necessity to explicitly support that, but now it's on the bucket list!

**Comment by tjerry** [comment]
Glad to hear it.

In the meantime I discovered that a little of custom CSS might do the job.
This snippet for instance takes care of the font size in the sidebar:
```
#sidebar {
  font-size: 30px;
}
```
I can't, however, find the header or class that targets upper toolbar.

**Comment by nathanlesage** [comment]
Mh, I'd assume that using something on the `body`-selector should take care of this. I'll dig into the LESS files later and see what I can find out — in the meantime, if you find out something, please feel free to drop it here!

**Comment by nathanlesage** [comment]
Keeping this open just for 1.7 to see if the new icons fix that
