### ISSUE TITLE
[ENHANCEMENT] Heatmap for Tag Cloud

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#624]
## Description
The available Tag Cloud already counts the amount of notes with certain tags but it displays the tags in green in the default theme, while they could be coloured in a similar fashion to search results, in different shades of the theme color.

## Proposed Changes
By colouring the tags differently, one could make assumptions about their uses.
A tag that is much more brightly coloured can more easily identify a cluster of notes with a specific context. A brightly coloured tag could also indicate a keyword, that might not be extremely useful as a search term, as it is hard to judge the relevance of the notes when they are in the hundreds. It could essentially make research in the Zettelkasten a bit more efficient. 

A tag that is less brightly coloured tag could indicate an area of knowledge that can be expanded upon. 

## Caveats
As this enhancement doesn't change anything regarding what's already implemented, I believe there are no real downsides to it.

**Comment by nathanlesage** [comment]
Sounds like a solid addition; just in case we could even experiment with a switch to turn on/off the selective colouring!

**Comment by PhilHem** [comment]
Sounds very reasonable. I don't think it would have to be more complicated that that for now 👍
