### ISSUE TITLE
[FEATURE] First-Start Welcoming Guide

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#627]
## Description

Just a quick issue so it can finally be put on the agenda. It's simple: Add a first start guide outlining the first steps interactively to the app, explaining the major breakpoints from existing workflows. The reason behind this is that one of the major stepping stones for new users when first starting the app is that they don't know obviously that Zettlr departs from all word processors in that it requires you to determine at least one major root working directory _before_ actually starting to use the app. Additionally, it shall also provide more guidance as to how to transfer everything from Word/LibreOffice to the app before really productively using it.

I am very much in favor of [intro.js](https://introjs.com/), but in case anybody has a better idea (maybe even an alternative to implementing it!) please come forward!

## Example Workflow

When the app is started for the first time it shall offer a series of hints with information on how to get started quickly. And, also add a link to the manual, because we all know it: Nobody reads the manual beforehand 🙄

1. Zettlr checks the existence of a `config.json`. If there is none, it's assumed to be a first start. (This is also good if someone wants to debug that whole thing)
2. If the main window is instantiated for the first time, it checks if this is the first start, and if so, simply sets in motion an (ostensibly simple) process of several things:
3. First, it'll show some "Welcome"-screen. I really like how Apple does it on new devices with simple scrolling through "Welcome" in several languages. Users could then even select their preferred language, which would require us to implement a "hot reload" of the language files. I didn't do that previously because I didn't know you can re-instantiate the menu during runtime (yeah, good old days where I didn't understand Electron :D), so it should be possible with no harm done. To keep maintenance simple, we could be lazy and after setting and loading the new language simply reload the renderer (programmatically hitting `F5`), thereby re-translating everything.
4. After the user has selected their preferred language and the renderer had time to reload, the user can click "Next" (or similar), and that is when intro.js will be started. What would need some consideration is how to time the guide so that it makes sense for the user.

## Caveats

We would need to discuss the preferred order in which the user can click through the app. From the top of my head, I think we should time it so that the user ends with "And now, simply open an existing directory as your workspace" or similar. This could mean:

1. The Editor
2. The Toolbar (split up into the three logical groups "global", "file", and "miscellaneous" from left to right)
3. The Sidebar

Furthermore, one question I have not finally decided is: Should we commit the necessary translations to the translate-service (user-friendly because it does not require a GitHub-account to contribute and is less technical) or in separate files here in GIT (requiring maintenance, albeit I think the quick start guide should not change too frequently after initial implementation, but it would give a much handier way to deal with longer blocks of text, which I assume should be made use of in that instance).

## Additional Information

Comments warmly welcome, because as of now I'm still sitting at the FSAL rewrite, so this feature either way will be sitting on the bench for some time!

**Comment by karolsputo** [comment]
I’ve just installed the app (love it) so I’m not quite ready to compose a fully fledged intro/tutorial, but I’d like to tackle this issue, because as a first time user I would have liked a little intro with some tips :D.

Intro.js looks nice, but I’ll look around for some alternatives to consider.

After I gain some proficiency with the app we can align and I’ll create a proposal.

**Comment by nathanlesage** [comment]
@karolsputo Hah, perfect! If you have any time on the Weekend, feel free to browse the now existing start up guide material, which resides in this folder: https://github.com/Zettlr/Zettlr/tree/develop/source/main/assets/tutorial/en

It's basically a folder that will be copied to the user's documents folder on the first start of an app (first start technically means: No config-file present) and opened in it so that the user will already start with an opened folder.

Feel free to browse the files and see if you'd like anything presented differently!

I'll close this particular issue because the guide is _technically_ implemented, but please, open up a new issue if you spot something you'd like to change concerning the guide! :)
