### ISSUE TITLE
Add support for Bibtex as CSL database

### ISSUE THREAD

**Issue by snauth** [Zettlr/Zettlr#63]
Supporting a workflow in which a bibtex file is automatically exported from Zotero (via the betterbibtex-zotero addin).

**Comment by nathanlesage** [comment]
This has already been implemented. It will be officially released with the 1.0 version, but if you want to use it right now, you can download the current beta version from the releases page. I also already unlocked the respective documentation on how to use it: https://www.zettlr.com/docs/citations

**Comment by pzhaonet** [comment]
Great tool! My database is in .bib format. Do I have to transform the .bib files into CSL JSON format via zotero + BetterBibTeX? Is it possible to import .bib database into Zettlr directly?

**Comment by nathanlesage** [comment]
Currently not, it's only CSL JSON. There are already discussions that Zettlr might support other formats as well (especially BibTex), but in fact these would only be converted internally before fed to the citeproc engine, as the Citeproc only accepts CSL JSON. This means the best performance will be achieved either way using a CSL JSON file!

**Comment by pzhaonet** [comment]
I just found that pandoc-citeproc can convert .bib into CSL JSON, which can be imported into Zettlr.

```
pandoc-citeproc --bib2json foo.bib > foo.json
```

Now I don't have to install Zotero any more!

**Comment by nathanlesage** [comment]
Say whaaaaaaaaaaaaat!

Okay, this tip is gold. Not only for others facing that problem, but also for Zettlr, b/c why not leverage pandoc-citeproc for on-the-fly conversions. Hah!

Thank you so much!

**Comment by nathanlesage** [comment]
Maybe we could use this thing: https://github.com/fiduswriter/biblatex-csl-converter

Easy API, and works natively, even if Citeproc is not installed.

**Comment by pzhaonet** [comment]
looks nice. Thanks!

**Comment by nathanlesage** [comment]
Just implemented it! Good to go 🎉
