### ISSUE TITLE
Tags with non-ASCII characters are not properly removed on export

### ISSUE THREAD

**Issue by pyrignis** [Zettlr/Zettlr#633]
Hi
I've seen your answer here https://github.com/Zettlr/Zettlr/issues/61 saying you wouldn't recommend using non ascii characters for tags but it seems this patch https://github.com/Zettlr/Zettlr/commit/d929667fc06b9dfcab4cb53fefbcc4958df556ec lifts this limitation.

## Description

When exporting the note as HTML or PDF (and probably other), non ascii characters and characters behind them are not properly erased by the "erase the keywords" in the export settings

## Reproducing
1 - Turn on the second slider of the Export tab of the settings (not sure how it's called in english/german) 
2 - print 3 different tags ```#acsii```, ```#français``` and ```#Straße```
3 - Export the page
4 - The ascii tag is properly removed but the others are printed as ```çais``` and ```ße```

## Expected behaviour
The whole words are properly removed from the export

## Platform
 - OS and version: Fedora 31, pandoc and xelatex from fedora repos.
 - Zettlr Version: 1.6

**Comment by PhilHem** [comment]
https://github.com/Zettlr/Zettlr/commit/d929667fc06b9dfcab4cb53fefbcc4958df556ec seems to acutally not allow for all unicode charaters rather than specific special characters.

**Comment by nathanlesage** [comment]
I'm pretty sure this is because in the commit lifting the limitation I only added the limitation for the rendering, and forgot to implement it for the tag extractor … so thanks for notifying!
