### ISSUE TITLE
Search results are displayed inconsistently

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#636]
## Description

I type "game" on the root folder, and first time I get two results. I press "Enter" again and get multiple results, in a weirdly spaced list. Every time I press "Enter" the list is reshuffled, it contains different number of results. I have `#games` hashtag, "game" in note titles, and sometimes just the word in note text.

![zettel-search-gaps](https://user-images.githubusercontent.com/766031/77818941-e6ca5f00-70e7-11ea-824d-4206ddf0995f.png)

Zettlr 1.6.0 release, Fedora Linux 30.

**Comment by nathanlesage** [comment]
oh my God, this looks like a nightmare o.O

**Comment by Zverik** [comment]
I'd be happy to help you debug, but I don't know how :)

**Comment by ME7DYCgw8M** [comment]
https://github.com/Zettlr/Zettlr/issues/599

Is this the same bug?

**Comment by Zverik** [comment]
Not exactly — I didn't rush it, and nothing is printed twice.

**Comment by nathanlesage** [comment]
> #599
> 
> Is this the same bug?

Nope, this is yet another one (actually, easier to mitigate)

**Comment by nathanlesage** [comment]
> I'd be happy to help you debug, but I don't know how :)

Hmmmmmm … I don't really know where to start (I can't reproduce the bug locally), but I'd probably try to get this information first (all in the dev console):

1. Is anything output to the console that seems to relate to this? (Everything vue/editor/search related; it might be easier to erase the log first and then start to reproduce the bug, as everything before likely doesn't relate to that bug)
2. How does the DOM of the sidebar look like? (see screenshot) — it might be that the list is actually always the same, but the virtual-scroller might mess things up (it did so in the past, so I won't rule out yet another undiscovered bug in that code either)
3. If the list does look weird, is anything "invisible" in the spaces?

Point 2 and 3 can be facilitated simply by hovering over the list items in the development console – the corresponding elements in the search results will then be highlighted

This might give us a heads up! Please also feel free to include additional screenshots, maybe there's something more in these!

**Comment by Zverik** [comment]
Could you please hint at how can I open the dev console?

**Comment by nathanlesage** [comment]
Oh, sure! Just make sure you have the debug mode enabled (Preferences -> Advanced) and then you can open them from the newly appearing "Develop" menu!

**Comment by nathanlesage** [comment]
How's this issue going with the new beta? @Zverik

**Comment by Zverik** [comment]
Just tried it and could not reproduce. I believe it's gone. Thanks :)
