### ISSUE TITLE
Add support for picking a citeproc reference from a CSL database

### ISSUE THREAD

**Issue by snauth** [Zettlr/Zettlr#64]
Similar to the Atom [zotero picker addon](https://atom.io/packages/zotero-picker)

**Comment by nathanlesage** [comment]
As I mentioned in the last issue, this is already supported!

**Comment by snauth** [comment]
The pop-up after typing @ did not work in the beta, but I have now switched to the develop branch where it works as advertised. Very nice, thanks!

**Comment by nathanlesage** [comment]
Yeah, that's why there will be more beta versions, until this runs smoothly! If something doesn't work as intended, please open up new issues as these bugs occur! :)
