### ISSUE TITLE
[FEATURE] Moving notes should update markdown references

### ISSUE THREAD

**Issue by mrVanDalo** [Zettlr/Zettlr#641]
- [x] Zettlr does not possess something similar (in which case it
        would be an enhancement, NOT a feature!)
  - [x] I have searched the documentation to make sure I did not overlook it.
  - [ ] Zettlr's current features cannot be used to approximate this behaviour.
  - [x] I have searched all issues (open and closed) to see if someone else
        wants something similar to which I could propose modifications (two
        features in one are easier and faster for us to implement).
  - [x] I will prepend "[FEATURE]" to my issue title (this makes the list look much cleaner ;)

## Description

When moving a note to a sub-folder or another folder (in the same box), markdown references are not update.

## Example Workflow

I have a document `zettlr/something.md` which contains the markdown reference `![someimage](someimage.png)`. I also have a file `zettlr/someimage.png`. 
Moving the document `zettlr/something.md` to `zettlr/subfolder/something.md` will result in a broken markdown reference.

It would be great if the references would be updated to `![someimage](../someimage.png)`.

Alternatively `zettlr/someimage.png` could be moved to `zettlr/subfolder` but of course it must be assured no other references are broken here.
Maybe magic dialog would help here.

## Additional Information

I'm talking about all markdown references, except the `[[id]]` references which luckily don't have that problem.

**Comment by nathanlesage** [comment]
Sure, sounds like a good enhancement! I'm on my way of extracting the file parsing logic from the rigid class structures either way, so after this is done it should be a piece of cake to implement this!

**Comment by mrVanDalo** [comment]
Ping
