### ISSUE TITLE
Alt-Clicking a linked Zettelkasten ID doesn't open the note

### ISSUE THREAD

**Issue by mpern** [Zettlr/Zettlr#645]
## Description

According to the docs:
>If an exact match is found somewhere in the system, an Alt-Click on an internal link will immediately open the first matched file

Unfortunately, it doesn't

## Reproducing

1. add a new note, generate a zettelkasten id
1. link the note via the id
1. <kbd>Alt</kbd>-Click the link
1. :no_entry: -> search is triggered

## Expected behaviour

Note is opened directly

**Screenshots**

## Platform
 - OS and version: Kubuntu 19.10
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1440p

**Comment by nathanlesage** [comment]
Cannot reproduce this … are both files loaded into Zettlr via any directory?

**Comment by guillermo2390** [comment]
Hello! I have the same issue. Alt+click triggers the search option with the ID number instead of going directly to the referenced note.

My files are in the same directory and my note's ID are in the format "yyyy.mm.dd_hh.mm.ss"

**Comment by nathanlesage** [comment]
> My files are in the same directory and my note's ID are in the format "yyyy.mm.dd_hh.mm.ss"

Did you adapt the regular expression to match those IDs? Remember Zettlr needs to detect the ID of a note in order so that note-linking works. This means:

1. Adapt your ID generator to the desired format in the Preferences
2. Adapt the regular expression for detecting IDs in your desired format in the Preferences
3. Make sure Zettlr actually detects IDs in that format by pressing the test button

Then it should work. You can easily see if it has worked by having a look at the sidebar, where an ID — if found — will be displayed.

**Comment by nathanlesage** [comment]
btw just saw this:

> -> search is triggered

This is actually expected behaviour, as Zettlr does two things when clicking on a note:

1. Trying to directly open that note — if it doesn't work now, it might be an accidental bug, however the current state of development works as expected
2. Start a search immediately, because this will highlight additional files that link to that file

**Comment by guillermo2390** [comment]
Hello Nathan,

First, let me congratulate for this fantastic effort you're doing with this app. Second, I forget to mention that the regular expression is validated (see attached image). I actually realize that when Alt+click a [[noteID]] **it indeed redirects me to the desired note but in addition it triggers the search box** with de referenced noteID. Is that the correct behavior of the app or it only should trigger the search box if the exact noteID was not founded (thus not redirected)?

I appreciate your help. thank you very much.

PS: I'm a basic user and don't have a coding or technical language knowledge background. I look forward to your patience xD

**Comment by nathanlesage** [comment]
> Is that the correct behavior of the app or it only should trigger the search box if the exact noteID was not founded (thus not redirected)?

It's wanted behaviour — if there is no such note, you'd still get all the references to the file, and if there is such a note, you get them as well plus it'll open the note! It's kind of a double-feature because this way you're prompted to look at the possible connections for your notes!

**Comment by guillermo2390** [comment]
Understood! It looks clear to me now. Thank you!

Greetings from Lima, Peru (beginning a small community to use Zettlr for academic writing and Zettelkasten)

**Comment by mpern** [comment]
Here are some screenshots to explain the behaviour of 1.6

Let's say I have some zettel with an embedded ID (created via <kbd>Ctrl</kbd>+<kbd>L</kbd>)

![image](https://user-images.githubusercontent.com/1476131/79865602-b40c4180-83db-11ea-883c-09b581008fa2.png)

That zettel is then linked via the ID in some other zettel:

![image](https://user-images.githubusercontent.com/1476131/79865661-ce461f80-83db-11ea-8daf-1b8e15f0123f.png)

But if I <kbd>Alt</kbd>+Click the link, it _only_ triggers the search

![image](https://user-images.githubusercontent.com/1476131/79865756-f766b000-83db-11ea-8cd6-00f05498bd0e.png)

**Comment by nathanlesage** [comment]
Hah, I see the issue: The identified ID is the filename, not the one you placed in your file. If you look exactly, the detected ID by Zettlr is the filename, that is, `20200421141527`. This is because the filename always supersedes the content of the file in order to find an ID.

**Comment by mpern** [comment]
Thanks for the clarification, now it makes sense
