### ISSUE TITLE
Feature Request: Paste images

### ISSUE THREAD

**Issue by wedza** [Zettlr/Zettlr#65]
I love using Zettlr for writing, mostly for all these awesome features for linking different files between them.

But I have one thing I miss from other writers, the availability to paste images from clipboard. This is very useful to draw graphs in other applications and integrate it in Markdown documents.

I love the way that Typora does this. When you hit Ctrl+V, it pastes the file it in a folder defined in the parameters of the application (see below), and insert the image with a relative link (very useful, because the path is recognised across applications and devices if you synchronise the folder).

Because Zettlr has file annexes support, it could be also interesting to have the image file display in the Annex panel.

![image](https://user-images.githubusercontent.com/20335741/49222962-b08aab80-f3dd-11e8-81c7-afb934e24db5.png)

I think this feature could be a great idea to improve Zettlr ability to manage complex files.

Thanks for making this awesome application.

**Comment by nathanlesage** [comment]
Hey, thanks a lot!

Indeed, this has also been on my agenda for some time, but currently I don't have the time resources necessary to implement this :/ It'll come, because it is definitely a crucial thing, but I think the most important thing will be to make the current app stable for the 1.0 release!

**Comment by nathanlesage** [comment]
Here you go! Feel free to test! :)

**Comment by michaelfresco** [comment]
@nathanlesage 
It would be really awesome if we could skip the dialogue window that appears after pressing cmd+v. The default settings are perfect. If you could skip this step, inserting images would become a lot quicker. :smile:

**Comment by nathanlesage** [comment]
You can skip it by hitting `Return`. The popping up dialog has the default option already selected, precisely because of this!

**Comment by michaelfresco** [comment]
![Screen Shot 2020-02-12 at 1 51 07 PM](https://user-images.githubusercontent.com/15065392/74336714-21c63c80-4d9f-11ea-86e6-77200fd04f67.png)

Awesome! I created this BTT shortcut to automatically send the `Return`, so it becomes even faster. :innocent:
