### ISSUE TITLE
[BUG] Textbundle export fails to include image files

### ISSUE THREAD

**Issue by scottfidge** [Zettlr/Zettlr#653]
When exporting to textbundle, no images are included in the assets folder and links are rewritten to point to the current folder (not the assets folder).

## Description

1. I'm on macOS 10.15.4, Zettlr 1.6, and pandoc 2.9.2.1
1. All image files are in the same folder as the .md files
2. All images show up fine in Zettlr's Editor (and Marked app, MMDC, etc etc)
3. All image links are relative and in this format: `![](image.jpg)`
    * I have tried other relative linking like `/image.jpg` and `./image.jpg`. All of these links also show up in the Editor, but still none of the images export
4. Exported image links are rewritten to absolute paths `/Users/UserAcct/Path/To/Folder/image.jpg` and contain no reference to the `assets` folder as expected for textbundle
5. I URL escape all my image links, but the rewritten image links are unescaped (not sure if this matters, but including it just in case)
4. I've tried exporting to the temp dir as well as the working dir but neither export properly
5. I haven't tested exporting to PDF yet, but exporting to .docx works fine (all images are  included)

I think that sums it up. Lemme know if I forgot anything, if I can test anything, or if I've made some boneheaded error!

**Comment by nathanlesage** [comment]
Hey, as already mentioned, I suspect there's an error in the exporting engine – would you mind trying at which version it did break? This will help me pinpoint where the bug has been introduced!

**Comment by scottfidge** [comment]
> would you mind trying at which version it did break?

Not sure what this means, but if you’re asking about app version, I was using Zettlr 1.6 and pandoc 2.9.2.1

I’ve only used Zettlr 1.6, so I have no idea when this issue started, sorry.

**Comment by nathanlesage** [comment]
> I’ve only used Zettlr 1.6, so I have no idea when this issue started, sorry.

That was the question, because when I implemented it, this worked, so i must've somehow accidentally broken it along the way …

**Comment by scottfidge** [comment]
Okay. Lemme me know if there's anything I can do to help/test.

**Comment by nathanlesage** [comment]
It would be a good start to check out 1.5, because if I remember correctly, the textbundle exports worked there because I tested them, so maybe then I only need to look at 1.5 -- 1.6!

**Comment by nathanlesage** [comment]
Found the error! It should work again now. I'll be releasing a new beta with this change today, and then let's see that it works!
