### ISSUE TITLE
[ENHANCEMENT] right-click "Show in Finder" for images

### ISSUE THREAD

**Issue by pusteblum** [Zettlr/Zettlr#654]
## Description
Show embedded images in the finder when right-clicking on the image or the path would be great. 

## Proposed Changes
This would make it easier to update or exchange images when working on a project. 

## Additional Information
I've just found Zettlr and may have missed the feature. Nothing happens when I shift-click (or anything else-click) URLs either as suggested in #12 , so maybe I did miss some settings, or something broke. Right-click on a file works as in #262 . 

This app is immensely useful, thanks for making it! 

mid-2012 macbook pro/ 2013 air running Mojave.

**Comment by nathanlesage** [comment]
> I've just found Zettlr and may have missed the feature. 

No, don't worry, this option currently does not work. But it sounds like a nice addition!
