### ISSUE TITLE
[FEATURE] Zettlr plugins

### ISSUE THREAD

**Issue by aidanhs** [Zettlr/Zettlr#657]
## Description

As a technical user, I'd like to be able to extend the functionality of Zettlr via a plugin interface. This would hypothetically allow me to alter things like live rendering and interactions with external systems by writing code, without needing to alter the zettlr source code.

## Example Workflow

 - Use case 1: I would like to have an automatic sidebar that shows me inward references to the currently open note - I'd like to achieve this by a) a plugin interface to create a new UI element and b) a way to populate this element from the result of running an external command
 - Use case 2: I would like to add live rendering for custom elements in my markdown, e.g. `!pdf[](customscheme://mypdfid)` that can run user-defined code to pull in data from external sources and present them to me in the zettlr editor (behind the scenes I think this one just translates to a codemirror plugin)

The crucial benefit here is I can easily customise the above, without needing to make changes to zettlr directly (especially since any changes may conflict with other people's workflow!).

## Caveats

There are a lot of caveats! The key ones that come to mind are around API design:

 - internal state - a plugin API can expose internal guts of a system and allows users to do unusual things that potentially violate existing assumptions. An API needs to either be narrowly focused/controlled enough to avoid this issue, or very permissive and 'buyer beware'
 - compatibility - when APIs change it's painful for plugin developers, when they stay the same they're an impediment to application development

My proposal to deal with both of the above is: have the API be extremely permissive (i.e. expose lots of internal state) and explicitly unstable. If it gains traction (i.e. enough people complain about breakage), that acts as an indicator as to which parts of the API are useful.

## Additional Information

Related discussions:
 - https://github.com/Zettlr/Zettlr/issues/140 - request for url scheme for zettlr (effectively acting as a limited API)
 - https://forum.zettlr.com/discussion/comment/331 - question around allowing user-defined codemirror plugins without adding them into zettlr itself
 - https://forum.zettlr.com/discussion/comment/22/#Comment_22 - adding a plugin system would enable people to build sophisticated systems as mentioned in this discussion

(keywords: extension, API, addon, add-on)

**Comment by nathanlesage** [comment]
Puuuuuhhhh … this is heavy. I constantly think about integrating a plugin API, but there's just SO MUCH in there that it's completely unrealistic right now :(

**Comment by aidanhs** [comment]
(fixed the title, just saw it was...not descriptive :grimacing:)

If you're generally open to the idea, I'm happy to start doing some experiments on my own and come back with my findings. I think a lot of concerns can be mitigated by not promising any stability at all, at least in the initial phases, to see how it integrates with the rest of the system.

**Comment by nathanlesage** [comment]
Sure, but I think at least this should be thought through (I'm not good at planning, but I know that this is necessary here) … so first maybe we need some concepts. I'd suggest you discuss this over at the [forum](https://forum.zettlr.com/) before we make any changes to the codebase!

**Comment by koppor** [comment]
In the context of JabRef, it offered a plugin functionality. Since there were only a few plugins and JabRef is 100% open source, we decided in 2015 to get rid of the plugins - and work to offer an easy wramp-up for new developers. I think, Zettlr is good to contribute to. Just submit a PR with the plugin idea.

For JabRef, we track details at https://github.com/JabRef/jabref/issues/152.
