### ISSUE TITLE
Deleting a file removes it from Zettlr but not from file system. Upon restart the file is back.

### ISSUE THREAD

**Issue by halcyonquest** [Zettlr/Zettlr#658]
## Description
Right click a file and select Delete File. The file is removed from the interface. Open file explorer in Windows and note that the file still exists. It will reappear next time Zettlr starts.

## Reproducing
On Windows, the delete works correctly on "regular" folders in which case the file is sent to the recycle bin. This issue was found on Windows 10 using a folder in the [Personal Vault](https://onedrive.live.com/about/personal-vault/) area of OneDrive. I am trying to use it so I can have a space with more sensitive information. Personal Vault requires additional authentication to access those files. As another alternative, I tried creating an encrypted drive using [Cryptomator](https://cryptomator.org/) and was able to reproduce the issue there as well.

## Expected behaviour
When delete file is selected, the file should be removed from Zettlr and deleted from the file system. Either soft or hard delete.

## Platform
 - OS and version: Windows 10 (1909)
 - Zettlr Version: 1.6

## Additional information
Thought this could be related to #158 but submitting as new issue,

**Comment by nathanlesage** [comment]
Well, the file should head over to the recycle bin … I'll let this issue open, because I'm right now coding the new logic for removing files, soooooo maybe it'll be solved in the next beta! If not, we have this issue … :D

**Comment by noah-arroyo** [comment]
I'm experiencing this problem.

I save my .md files to the cloud via [Box Drive](https://www.box.com/drive).

OS: Windows 10
Zettlr version: 1.7

**Comment by nathanlesage** [comment]
Do the logs expose any error after deleting a file?

**Comment by noah-arroyo** [comment]
Oops, so sorry. Was not watching for a response. I'm new to github.

I'm not seeing any obvious error message in the logs, following an effort to delete the file. But honestly I don't know what to look out for, aside from (presumably) "error."

Glad to try various approaches and deliver you logs, if it'd help.

**Comment by nathanlesage** [comment]
> I'm not seeing any obvious error message in the logs, following an effort to delete the file. But honestly I don't know what to look out for, aside from (presumably) "error."

Anything might help; sometimes the error might not be logged as an error because it is caused someplace else!
