### ISSUE TITLE
[FEATURE] Batch pdf export

### ISSUE THREAD

**Issue by wiesener** [Zettlr/Zettlr#661]
## Description
I would like to have the following feature. When I create a project or I have just a folder of markdown files I would like to export each md file into a separate pdf file with one command into a defined folder. Maybe this could be down as well via a command line interface.

## Example Workflow
Right click on folder and CMD + E => choose folder dialog or it is specified in the pdf settings.

## Caveats
No

## Additional Information
By the way very nice Editor. I really appreciate your work. Very well done.

**Comment by nathanlesage** [comment]
Sounds like an interesting idea. Albeit currently there's no time to implement this. I'm going to leave this open for further improvements on the automate-side of things.
