### ISSUE TITLE
[ENHANCEMENT] Slightly smaller 'x' icon in search field?

### ISSUE THREAD

**Issue by Jos512** [Zettlr/Zettlr#662]
## Description
The 'x' icon that clears the search field is relatively small. Because of that I occasionally (~5 per day) click wrong. It's a minor inconvenience, but if others also share this idea, it might be something for a change.

## Proposed Changes
Currently the 'x' icon looks like:

![2020-04-13_13-09-42](https://user-images.githubusercontent.com/13403160/79116189-120baa00-7d88-11ea-87e6-de8dd856b3f5.png)

To make it easier to click there are at least two options:

(1) Make the icon itself bigger. This has a visual consequence, so can impact the 'feel' and style of the app.

(2) Make the clickable area a little bit bigger.

Firefox for instance does this by not requiring a click precisely on the 'x':

![2020-04-13_13-03-24](https://user-images.githubusercontent.com/13403160/79116294-57c87280-7d88-11ea-84dc-7c10318dc3b8.png)

Zettlr doesn't have that feature. For instance, here my mouse pointer is super-close to 'x' but is still for text selection only:

![2020-04-13_13-12-56](https://user-images.githubusercontent.com/13403160/79116369-9b22e100-7d88-11ea-9d6d-cc26d2377e3f.png)

Only when the mouse is exactly on 'x' does it register:

![2020-04-13_13-13-05](https://user-images.githubusercontent.com/13403160/79116397-ab3ac080-7d88-11ea-8c34-c76c141fffb7.png)

## Caveats
If the first option is chosen, the look of the app might change and some people might find the bigger 'x' ugly.

With option two there's less potential for drawbacks. I assume that most people don't click near the 'x' when they want to select text. So if the clickable area becomes a little bit bigger, they won't notice.

Thanks for listening and allowing feedback from strangers. :slightly_smiling_face:

**Comment by nathanlesage** [comment]
Yeah, this is part of greater attempt to rewrite the GUI — after some other issues have been addressed!

**Comment by Jos512** [comment]
Hi Stale bot :wink: let's wait till the release of 1.8 before closing this issue. Chances are the 'x' icon is provided with the new icon set. :slightly_smiling_face:

**Comment by nathanlesage** [comment]
Watch the PR I just linked, there it's fixed
