### ISSUE TITLE
Dictionaries (again)

### ISSUE THREAD

**Issue by hayribakici** [Zettlr/Zettlr#664]
Hi,

first of, thank you for this program. Having a powerful slick markdown editor, that also is open source is just gold.

However, I have a slight issue with the dictionary... I activated only the german dictionary and it red-underlines real basic words such as "Hausarbeit" (homework) and "lassen" (to let). I also already tried to install the german dictionary from [here](https://github.com/wooorm/dictionaries) as mentioned in the zettlr documentation, with no luck.

Is there a way to fix this issue, rather than adding each word to the dictionary?

Thank you again and cheers

**Comment by nathanlesage** [comment]
Currently, no, as there is simply no time for either Titus or me or anyone else to rewrite the dictionary algorithm. It just can't handle hunspell-style dictionaries very well. I'm open to a PR addressing this — either to the nspell-repository, or to this repository with an alternative. But as this package is managed externally, I'm going to close this issue …
