### ISSUE TITLE
Markdown link does not convert after emptying a title text

### ISSUE THREAD

**Issue by pizzakinggod** [Zettlr/Zettlr#665]
## Description
Markdown link does not convert correctly when title is fully erased and newly typed.  
It requires a user to move a cursor to the url section of `[title](url)` for it to properly convert to a link.

This seems to happen because it checks whether a title is empty or not.   
As soon as a title text is emptied, the editor does not recognize it as a markdown link, which is fine.  
The problem is when it is retyped, it does not work as intended.

See below for demonstration.

## Reproducing
Navigate to markdown link so it expands in a form `[title](url)`.
Delete title by pressing backspace. Type a new title then press down or up to escape.
Link remains in the expanded form.

Change title then go to the url part by moving a cursor to the right.
There will be a font style change to url. Then you can move to other lines to convert it to a link

## Expected behaviour
A link will always convert to underlined title if it has a valid url and a title

**Screenshots**
Demonstrates the bug
![](https://i.imgur.com/bKJ8NGh.gif)
Deleting and typing title again.

![](https://i.imgur.com/go8V1up.gif)
You must move a cursor to the url section after deleting the title.

## Platform
 - OS and version: Windows 10 Home
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1080p

## Additional information
Is any of contributors aware of [#595](https://github.com/Zettlr/Zettlr/issues/595)?

**Comment by nathanlesage** [comment]
If anyone comes across with a good solution to this, I'd be happy. I couldn't think of anything, and it doesn't really bother me. Concerning parentheses: It's a constant problem since three years, but since no one came up with a solution so far, it persists.
