### ISSUE TITLE
Citation preview and pandoc export does not work on Windows

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#667]
[Zettlr 1.6 on Windows 10] When I select my Better-Bibtex exported json file in the Exports tab of Settings, Zettlr seems unable to use it, and pandoc exports also fail to transform my references. When I open Attachments, under References the message "Could not update bibliograpy!" is shown. Inline the @xxxx references appear in red.

However, if I **manually** add the pandoc bibliography switch in the advanced settings of Zettlr as `--bibliography="C:/Users/xxxxx/Documents/Books/My Library.json"`, replacing `$citeproc$`, then pandoc exports within Zettlr (e.g. the print command, or exports to Word) render my citations correctly (though Zettlr still cannot show them in Attachments and they still appear in red inline). Note that I insert the paths with forward slashes instead of backslashes in the pandoc command, and place the filename in quotation marks. Pandoc tends to throw a wobbly with backslashes, even double backslashes.

In case you're wondering if it's the space in the filename that causes the problem, I also tried renaming the file to `MyLibrary.json`, but Zettlr still can't use it when I pick the file from the Citation Database field of the Exports tab.

**Comment by nathanlesage** [comment]
This may also very well be related to malformed fields. Zotero somehow — I'm not sure why — seems to have especially problems with date fields. A lot of libraries I tested while enhancing the error reporting actually had some malformed date parts. I can only assume that `pandoc-citeproc` is much more lax with enforcing certain fields, but `citeproc-js` apparently is not!

**Comment by Jaifroid** [comment]
@nathanlesage So are you saying that it might not have anything to do with the filename format on Windows, or that there might be two issues here? If that's the case, it might be worth splitting this issue into the two different parts.

I can, however, *definitely* say that there is an issue with the file format, because it is not just citeproc-js that is not working internally in Zettlr, it is also any export that uses pandoc. Unless I manually change the filename and insert it with forward slashes and quotation marks around the filename in the Advanced tab, pandoc fails to find the file. When formatted as shown above, pandoc easily finds all references and beautifully formats the bibliography (as well as inline citations) when exporting to PDF or Word.

It's possible that double backslashes may work too (i.e. an escaped backslash), I haven't tested that, but I'm 95% certain the quotation marks are essential.

**Comment by nathanlesage** [comment]
> the quotation marks are essential.

The library file is quoted when it's passed to pandoc (see screenshot).

![image](https://user-images.githubusercontent.com/17251683/79261974-db6d8680-7e90-11ea-95f7-74b18000de8e.png)

> double backslashes may work too

Well, maybe that might have something to do with it, depending on how PowerShell works on Windows. I mean, after all they're using backslashes both as directory delimiters and as escape-characters …

One test, I'd like you to try: When you select the library file in the settings, could you _manually_ in the textfield replace all backslashes in one case with single forward slashes, and then also try out double-backslashes? Then this should work precisely as when you're simply overwriting the `$citeproc$`-variable. If it does, please let me know because then I know exactly where to put this Windows' _Extrawurst_.

**Comment by Jaifroid** [comment]
@nathanlesage I've done these tests, and the last one, as you'll see is a bit surprising to me. It does tend to suggest that you might have been right about the problem being with `citeproc.js:`

* Remove my manual modification to the pandoc statement and replace it with `$citeproc$`
* Edit the Export -> Citation Database field to look like this: `C:/Users/xxxxx/Documents/Books/My Library.json`. *Result*: Pandoc exports work (including Ctrl-P print, which exports to a PDF view), and citations are properly formatted in pandoc's output. However, references in the editor look like `@simmelGrossstadteUndGeistesleben2006` and are red (even after restarting Zettlr. Looking under Attachments, I still see "Could not update bibliography"
* Edit the the Citation Database field to look like this: `C:\\Users\\xxxxx\\Documents\\Books\\My Library.json`. *Result*: same, i.e. pandoc recognizes the file and can format references, but Zettlr internally does not
* Pick the Citation Database with file picker, so it looks like this: `C:\Users\xxxxx\Documents\Books\My Library.json`. *Result*: now, surprisingly, pandoc still works!! This is very surprising to me, because I first noticed the issue precisely because it didn't work in pandoc. I have restarted Zettlr a few times, and checked that my manual entry is not in the Advanced tab, so this is a bit mysterious. In any case, internally in Zettlr, I get the same errors as above.

**Comment by Jaifroid** [comment]
I'm actually quite astonished by the last test. I would never have experimented with the pandoc field if it had been working out-of-the-box. But I can't rule out human error, e.g. putting the reference inside parentheses like `(@simmelGrossstadteUndGeistesleben2006)` prevents them from being rendered by pandoc.

In any case, I think we have indeed isolated the issue to citeproc.js, and the filename field does not need to be changed.

**Comment by nathanlesage** [comment]
Imagine myself scratching my head right now. Technology is astonishing sometimes. I wish I had a Windows computer here to quickly test this out myself … do the logs tell anything about errors? (I'd recommend clearing out the library field, saving the preferences, then having a look at the logs and seeing when the last entries were made, and then re-filling the field, saving, and looking if there are any new errors logged, because the errors unfortunately are still somewhat buggy in the logs, I apologize!)

citeproc-js does not itself load the files, it's all done by Zettlr, but it uses standard system calls, so I'm curious as to why apparently the library path refuses to work normally …

**Comment by Jaifroid** [comment]
@nathanlesage I'll try to spin up my local repo clone of Zettlr and see if I can debug what's happening with citeproc;: at least find out if the library is being passed correctly to citerproc. Will check logs (you mean console.log or is there explicit logging to a file?).

I was running from the released version for stability while completing an article. Probably won't be able to do this till weekend.

**Comment by nathanlesage** [comment]
> or is there explicit logging to a file?

There is: The logs should be in Develop-menu -> "Open Logs". There's a lot of clutter and the log viewer is not the best, but library files should be logged as errors on the current develop branch, but don't fully trust me on that, during the last weeks I have completely lost my overview over the codebase and don't know what I did where and why :D

**Comment by Jaifroid** [comment]
@nathanlesage When I add a reference to Zotero standalone, I immediately get a notification in Zettlr that the library file has been updated and is reloading. So this suggests that the file is correctly loaded by Zettlr, and is being watched by its filehandling process, but something is going wrong in how citeproc uses it. It's probably a similar issue as in #671.

**Comment by nathanlesage** [comment]
hmhm, sounds about right. Argh, I wish I had more time but I'm so deeply entrenched in the FSAL refactoring right now that it's close to impossible to do something else right now …

**Comment by Jaifroid** [comment]
Don't worry! It's cosmetic. As I say, I'll try to debug this weekend.

**Comment by nathanlesage** [comment]
As there have been more modifications, I'll for now assume this issue solved, if not, please comment
