### ISSUE TITLE
Add context menu entry for copying a file's ID

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#67]
This issue has been suggested through the contact form via zettlr.com.

In short, what should be possible: **Add an entry to the contex menu for files in the file list to simply copy the ID to the clipboard (if one has been detected)**.

**Comment by edusantana** [comment]
How does this `Copy ID` works?

![copy-id](https://user-images.githubusercontent.com/3603111/87480388-97ab2a00-c603-11ea-8a7d-2229481b181a.gif)
