### ISSUE TITLE
[BUG] certain special letters in file path for images not allowed

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#670]
## Description
Special letters in the file path will cause problems when calling an image, even when using a relative file path.

## Reproducing

To reproduce this, create the folder somewhere called "#abcdefg", and within, another folder called "root". Create another folder called "img" within "root" and declare it as the relative image folder.
Should you now try to call an image from "img", it will not display the image, but show the dummy image when the calling fails. 

## Platform
 - OS and version: Windows 10 1903 / OS X Mojave 10.14.4
 - Zettlr Version: 1.6

## Additional information

I did not check which special letters don't work, but personally I use them to have have files and folders in my filesystem that appear at the top of the window, when I sort for name and I suspect I'm not the only one who does that.  

Actually, I don't really think it is necessary to fix this right away. As long as it doesn't work though, I think it might make sense to put it in the Zettlr FAQ, so people can fix it for themselves.

**Comment by nathanlesage** [comment]
Concerning the `#`-symbol: I stumbled upon this myself, and I concluded that Pandoc tries to treat these as sub-headings, albeit I did not double-check that behaviour!
