### ISSUE TITLE
BibTex files not working ?

### ISSUE THREAD

**Issue by vicleroy** [Zettlr/Zettlr#671]
Hello ! 

I've been using Zettlr for a short time, hoping I can use it for my Ph.D thesis. Everything's going fine, except when it comes to my bibliography. Somehow, every time I've tried to use one of my .bib files in Zettlr, it has never worked ; Zettlr tells me that the bibliography file cannot be charged, and that references cannot be updated. 
CSL-Json files work well, so of course I could just rely on that. But I've been using JabRef for many years and having to go back through Zotero to import and re-export my whole bibliography every time I add some new references is quite tiresome. 
Do you have any idea as to what might be causing this to happen ?

Thanks a lot in advance !

**Comment by nathanlesage** [comment]
Mh, I've improved the logging telling you what has gone wrong, but it's not yet been released, and it'll take some more time :/ the library files do tend to behave sometimes, it's been a constant issue, so I can have a look into it again in some weeks after the current massive refactoring is gone!
