### ISSUE TITLE
[ENHANCEMENT] Manage tags - multiple tags with same color, add scrolling

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#674]
## Description
Improved "manage tags" screen for use cases where coloring many tags is required. For example, I want all tags of a certain "family" to have the same color, but it is not enough to color just the main ones as there is no complete overlap.

## Proposed Changes

1. Allow setting the same color for multiple tags in the same GUI line (using some separator character?)
2. Today when trying to color many tags at some point the window overflows in the bottom the screen - should turn to scroll?

**Comment by nathanlesage** [comment]
> Allow setting the same color for multiple tags in the same GUI line (using some separator character?)

Hmm, the tag colouring was only intended for some "meta"-tags unrelated to the rest of the tags (in order to simply easily color-code some files by using short tags), so I'm not sure really how to handle this!

> Today when trying to color many tags at some point the window overflows in the bottom the screen - should turn to scroll?

Never added that many tags, so I didn't see that coming, but yes, it should scroll :D
