### ISSUE TITLE
[ENHANCEMENT] Tag Cloud QoL improvements

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#675]
## Description
Improvements to the tag cloud screen.

## Proposed Changes

1. Color tags as defined in the Manage Tags screen
2. Copy to clipboard should also write the frequency of occurrence for each tag
3. Allow sorting alphabetically and by frequency
4. Hitting escape should exit the screen (actually also applies to other screens)
5. Change text - it says "hover over the tags to see the number of times you've used them" - this is obsolete as the number is now always shown within the tag.

**Comment by PhilHem** [comment]
For clarity: Partial overlap with #624.

**Comment by nathanlesage** [comment]
1. Good idea, yes!
2. This is counter-intuitive, this should, if at all, be done via setting
3. Good idea!
4. Also good idea!
5. Alright, but I have to find out the translation string for that …

Generally, this seems to be like several issues at one :D
