### ISSUE TITLE
[BUG] Image caching parameters should use ampersands if there are already parameters in the image link

### ISSUE THREAD

**Issue by b3u** [Zettlr/Zettlr#677]
## Description
Image links that require a parameter to be viewed may not work with the id Zettlr adds.

For example, take <https://pbs.twimg.com/media/ETmWK8zWAAELbXI?format=png&name=900x900>. Without params or a file extension, it will result in a 404 error. Similarly, if you add `?1587152828619`, like `https://pbs.twimg.com/...?format=png?1587152828619`, it will also 404. 

## Reproducing
See the following _working_ image links:
- https://pbs.twimg.com/media/ETmWK8zWAAELbXI?format=png&name=900x900
- https://pbs.twimg.com/media/ETmWK8zWAAELbXI.png

Adding `?1587152828619` to either causes the url to result in a 404 error.

## Expected behaviour
The image only works without the added id. I would not add the ids, as they don't expose any feature to the end-user. If it's absolutely necessary, add a data attribute to the image tag.

**Screenshots**
N/A

## Platform
 - OS and version: Elementary OS (Ubuntu 18.04)
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1366 x 768

## Additional information
I peeked in the dev tools to find out that it was a 404 error.

**Comment by nathanlesage** [comment]
… heh? What exactly is the problem here? I can't see what you're getting at.

**Comment by b3u** [comment]
I add `![foo](https://pbs.twimg.com/media/ETmWK8zWAAELbXI?format=png&name=900x900)`. It adds writes `![foo](https://pbs.twimg.com/media/ETmWK8zWAAELbXI?format=png&name=900x900?1587152828619)`, which results in a 404 for the image.

**Comment by nathanlesage** [comment]
Ah. Yes, this is necessary because otherwise the renderer process will keep the image cached and changes are not visible to you. What I should change is merely that the parameter should be added using an ampersand (`&`) instead of always a question mark (`?`), however this will at least break the Twitter image API, which I cannot fix, so I'd recommend you download these images instead!

**Comment by b3u** [comment]
gotcha, thanks

**Comment by nathanlesage** [comment]
Fixed the ampersand/question-mark thingy in a recent commit.
