### ISSUE TITLE
[ENHANCEMENT] Hugo (or other) Blogging / CDN w/ Markdown

### ISSUE THREAD

**Issue by OneCricketeer** [Zettlr/Zettlr#681]
## Description

I am working on enhancing my [hugo](https://gohugo.io) site / blog, and would like a "richer" editor than just VS Code. I can go into more details what I would like to see, but starting out would just be abilities for better organization, in-line imaging, and tagging. 

## Proposed Changes

Shell out to a `hugo` binary, and render some stuff? Be able to track that content? Maybe have an embedded side-by-side webview like IntelliJ.  

## Caveats

Scope creep? This is mostly a markdown editor, not a blogging / web-site creation platform? 

## Additional Information

I like the design so far, although haven't got around to fully trying it out yet. 🥇

**Comment by PhilHem** [comment]
I think the scope question really needs to be adressed for this. As far as I see it, Zettlr is even only secondarily a Markdown editor and primarily a Zettelkasten app. There are still loads of open issues regarding the core competency off the app. 
But maybe there are aspects of your requests that would be beneficial to the Zettelkasten user. That might be interesting!

**Comment by cricket007** [comment]
> I think the scope question really needs to be adressed for this. There are still loads of open issues regarding the core competency off the app.

Absolutely understandable. 

> maybe there are aspects of your requests that would be beneficial to the Zettelkasten user

I certainly hope so. Never heard of Zettelkasten before, but researching it, I think I can take advantage of that mental model...

> That might be interesting!

🙏 😄

**Comment by cricket007** [comment]
Note: Markdown isn't the only option. https://gohugo.io/content-management/formats/

I've become a fan of Pandoc / AsciiDoctor / Restructured Text as well.

**Comment by nathanlesage** [comment]
> As far as I see it, Zettlr is even only secondarily a Markdown editor and primarily a Zettelkasten app

More the other way around :P The Archive would be an app that is primarily a Zettelkasten app and secondarily a Markdown editor. Zettlr tries to be a replacement for Word that also adds a whole load of Zettelkasten functionality!

Concerning this blogging thingy: During a previous refactoring I've loaded out the whole exporting logic to prepare exactly for this: That we can add small modules that enable exporting not only using pandoc, but maybe even post to Websites (e.g. WordPress using its REST API). This would be an example for this.

**Comment by Jos512** [comment]
I'm also a Hugo user myself, but don't see anything special about Hugo that Zettlr should accommodate to. In other words, Hugo simply renders Markdown (or other formats) into HTML. 

So if Zettlr gets more Markdown writing features, it also works more nicely with Hugo (and other static site generators).

Like PhilHem I'm concerned about the scope of this issue. It sounds like a big project now. Perhaps we can better discuss each of the separate changes/improvements in a separate issue? :slightly_smiling_face:

**Comment by nathanlesage** [comment]
> Like PhilHem I'm concerned about the scope of this issue. It sounds like a big project now.

Yeah, it basically encompasses a lot of these sub-modules at once. But implementing each one should not be that difficult — however, there are enough other open issues right now, so this'll have to wait :D I'll keep this one open for now in case others stumble upon it.

**Comment by cricket007** [comment]
I mean, I don't think anything I've mentioned so far is an unreasonably large request.

This is a markdown editor. Check. 
You can group 'blog posts" under a collection of projects. Check. 
The markdown text is rendered as its typed and images and links show in-line. Check.
Citation wizard helps link contents together for improving a web site's SEO. Check.

... Those are all the main features I personally want off the bat. 

I'm fine having to run Hugo in a separate terminal, but if there were simply some button/dialog for `os.exec`ing `hugo server`, then that would be awesome

**Comment by nathanlesage** [comment]
> I'm fine having to run Hugo in a separate terminal, but if there were simply some button/dialog for os.execing hugo server, then that would be awesome

Well, there's no dedicated functionality for that, but you could attempt to monkey-patch into the Pandoc command in the Advanced-tab for now

**Comment by cricket007** [comment]
> there's no dedicated functionality for that

Hence the feature request 😅

**Comment by Wieke** [comment]
Perhaps a per-project custom export command setting that overrides the pandoc command when doing a project export would be an easy way to facilitate things like this?

**Comment by nathanlesage** [comment]
> Perhaps a per-project custom export command setting that overrides the pandoc command when doing a project export would be an easy way to facilitate things like this?

Should also be possible. Given the current modularity of the exporter, all of this should not require all-too deep modifications to the codebase!

**Comment by Jos512** [comment]
> I don't think anything I've mentioned so far is an unreasonably large request.

True! But it's much easier to discuss separate components in separate issues, and makes keeping track of things for the contributors also easier.

Even a simple thing like 'group posts in a collection of projects' probably has 10 details we can discuss over in 30 posts. Plus all the other things to clarify from the collection of changes you like to see. 

Doing that all in one single issue might be a bit overwhelming! :smile:

**Comment by nathanlesage** [comment]
> Even a simple thing like 'group posts in a collection of projects' probably has 10 details we can discuss over in 30 posts.

welp 👀 Please spare me at least for now, there are SO MANY open issues, I always get a crisis when I look at the amount of open issues :D

**Comment by cricket007** [comment]
> I always get a crisis when I look at the amount of open issues 

Use tags and projects appropriately rather than [NAME] tags in titles

**Comment by nathanlesage** [comment]
> Use tags and projects appropriately rather than [NAME] tags in titles

This doesn't alter anything about the number of issues, which is what upsets me ;)

**Comment by marcusyoung** [comment]
IMO, for the sake of your sanity I think you would be better not to address enhancements until you have the capacity to deal with them. Just dedicate what time you have to bugs (depending on criticality) and the other structural issues you want to address. The core functionality is fine as it is. As the user base increases more bugs will inevitably surface.

**Comment by nathanlesage** [comment]
Yes, absolutely. You are right! I just wanted to keep this issue open for some time in order to give people the chance to see it before I close this again, because this will trigger some thought processes which might yield good results in a few months time :)

**Comment by cricket007** [comment]
btw -  https://gohugo.io/tools/frontends/

**Comment by nathanlesage** [comment]
Closing for now, but we might add this as plug-ins to the exporter. After all, it should be fairly simple to implement even now. So if anyone wants a custom exporter, feel free to open PRs!
