### ISSUE TITLE
[BUG] link autocomplete special character association

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#682]
## Description
Characters like ä,ö,ü, and presumably some others will not be identified with the same character as the same characters in the link suggestions. 

## Reproducing
Create a note called "Käsecracker" and try to find it via the link autocomplete. It will appear in the suggestions list up until you actually type ä.

## Platform
 - OS and version: OS X Mojave 10.14.4
 - Zettlr Version: 1.6

## Additional information
Possibly an error because of the use of different character sets for file names and the editor?

Also possible correlation with #668, although it seems to be a slightly different issue, because of the syntax.

**Comment by nathanlesage** [comment]
> Create a note called "Käsecracker"

lol

> Possibly an error because of the use of different character sets for file names and the editor?

Everything within the app is unicode, so this is unlikely the cause. But I'll investigate, because this sounds weird!

**Comment by PhilHem** [comment]
With the limited knowledge I have with debugging, I can't find any trace of that. What I did find though, is that when I copy the file name, it will actually find it, but if I type "ä" on my keyboard, it doesn't.

**Comment by PhilHem** [comment]
Also, Space as a character does not work. (Not sure if thats intentional)

**Comment by nathanlesage** [comment]
Yes, that space does not work is intentional: I've made the autocomplete dropdowns as volatile as possible, because they completely unnerve me in most applications, even VSCode — I want to simply close them as fast as possible! And Space is always a good choice for that. So space was the problem?

**Comment by PhilHem** [comment]
No, I just was not sure wether it is the same issue or a different one. To me, it would be nice to actually have the space letter, but thats outside of the scope of this bug then.

**Comment by PhilHem** [comment]
I have tested this issue on a Windows 10 system and it appears aswell.

**Comment by nathanlesage** [comment]
hm, maybe this has accidentally been resolved on the FSAL-refactor branch, which is what I'm currently on

**Comment by PhilHem** [comment]
After having found the debugger of Zettlr (lol), I can maybe add a little more information to the bug. There are some source maps that failed to parse, related to the drop-down menu:

showdown/dist/showdown.js.map
tippy.js/dist/tippy-bundle.cjs.js.map
tippy.js/dist/tippy.chunk.cjs.js.map
popper.js/dist/umd/popper.js.map


(and also mermaid/dist/mermaid.core.js.map, although I don't think that thats related)

Since I don't really know anything about js, I can't say wether this could be related, but the yellow little warning sign formed my best guess.

**Comment by PhilHem** [comment]
Just checked. On the windows system where it works, these same source maps do not fail to parse.

**Comment by nathanlesage** [comment]
> There are some source maps that failed to parse, related to the drop-down menu:

Source maps are only intended for debugging purposes. To give a short explanation: Today, most CSS and JavaScript is "minimized", that is: All whitespace, all comments and everything else is removed. This makes it easier for the browser (in this case the main application window) to read and interpret the code that's written there. However, these minimized versions obviously are hard to read for humans, and this is where sourcemaps come in: They tell the browser "Hey, if something in here breaks, the original position in the source code was at line 123 in file xyz.js" so that it's easier to read for people who have to find out bugs in the code.

That being said, I can't imagine that the failing of sourcemaps (which are not shipped in production, out of obvious reasons) could in any way be related to the failing of these special characters 🧐

But just another thing that came to mind: Which keyboard layout do you use? The one shipped with your Mac? Because it's easy to switch these, and I can tell from experience that it's super easy to accidentally forget to switch back (albeit I'm not sure if that's really the cause)

**Comment by PhilHem** [comment]
Ahh thanks for the explanation! :)
The layout that I use is "ABC-QWERTZ". I also tried out "German", but It did not change anything.

**Comment by nathanlesage** [comment]
Dammit, because I'm also on ABC-QWERTZ where I cannot reproduce that bug :(

**Comment by PhilHem** [comment]
![ezgif-7-2af6a45d2f3c](https://user-images.githubusercontent.com/34508934/80095217-dc28ab80-8567-11ea-8505-600a5267d4d3.gif)

Here is what it looks like, just so we are on the same page.

**Comment by nathanlesage** [comment]
Alright, so that I can reproduce, is the note's filename `Empfänger.md`? Is there any ID in there, or a YAML frontmatter title?

**Comment by PhilHem** [comment]
Yes the file has an ID, but nothing else.

**Comment by nathanlesage** [comment]
Super weird … we'll have to continue to investigate to see why this happens 🧐

**Comment by PhilHem** [comment]
Little update: 

I've had this issue till 1.7.10 beta on OS X 10.14.4.

I was experimenting with different fonts via css though, and after I did that, the issue with ä,ö,ü was gone, even when I changed it back to the original font.

**Comment by nathanlesage** [comment]
Interesting … but what does this mean? Can we see the issue as being resolved? (b/c custom css, very strictly spoken, is something out of the range for bugfixing :D)

**Comment by PhilHem** [comment]
I don't have an exact definition of "closed" but I think it means that the issue is resolved, no? Right now I still don't know what caused it or what fixed it. Maybe somebody else comes across this issue and will look for similar issues in the future, that are still open. I think the tag "stale" actually fits the description quite nicely. As I am not a moderator or anything though, I'll leave the decision about closing it for you  @nathanlesage  :)

**Comment by PhilHem** [comment]
Weeeeeell, oddly enough, the fix was seemingly only temporary. It's back not working again, and I suspect, changing css was not the fix I hoped for. I suspect, this answers the question, of wether to close the issue :P

**Comment by nathanlesage** [comment]
Gnargh … I hate bugs that have this mysterious aura of "somehow not working"

**Comment by PhilHem** [comment]
I have another update on this:

When I create a file such as `Dämpfung`, it might appear in the drop-down when the `ä` is called. 
However, when I rename the file within Zettlr with the same name, it will show in the drop-down.

**Comment by nathanlesage** [comment]
… either I don't get the necessary grammar, or you're basically saying that the file does show up as expected …?

**Comment by PhilHem** [comment]
Not exactly. 
When I create the File via `Create a new File`, the problem appears and only dissappears if I rename it. The next file therefore will have to be renamed again after creation in order for it to properly work in the completion.

**Comment by nathanlesage** [comment]
Ah, so basically what you are trying to express is:

- Create a new file --> it's missing initially from the dropdown
- Rename a file --> It then appears?

Then this would be easy to fix as I'd need to trigger a rebuild of the autocompletion on creationg of files, not just renaming!

**Comment by PhilHem** [comment]
Yes! This hits the nail on the head!

**Comment by nathanlesage** [comment]
💅  🔨

**Comment by nathanlesage** [comment]
Working on the 1.8.x-branch; I think I just forgot this issue.
