### ISSUE TITLE
[ENHANCEMENT] Haskell syntax highlighting

### ISSUE THREAD

**Issue by Kurren123** [Zettlr/Zettlr#684]
## Description
Syntax highlighting for haskell, by doing three backticks followed by "haskell".

## Proposed Changes
An additional language to the syntax highlighter. Haskell takes time to learn certain concepts, it would be great to make notes on these as I go along.

If you would accept this feature, I would be happy to try and make a PR.

**Comment by nathanlesage** [comment]
I didn't realize I didn't already have that enabled! But it is now, so here you go! :)

![image](https://user-images.githubusercontent.com/17251683/79724708-40d5d300-82e8-11ea-8410-c4740a8ddae8.png)

**Comment by Kurren123** [comment]
Hi @nathanlesage thank you for your quick reply. A couple of questions:

1. How did you figure that out? A search for "haskell" or "hs" in the repository didn't show up anything and there was nothing in the docs. Maybe I could update the docs for your
2. Is it possible to also have it detect haskell when doing three backticks then "haskell", as I think haskell would be the first obvious thing people would try. Again happy to attempt a PR if you'd like.

**Comment by Kurren123** [comment]
Apologies I didn't realise you just added the commit. Holy cow that was fast. Could I still perhaps request number 2 above?

**Comment by nathanlesage** [comment]
Hehehe, yeah, we simplified the process of loading in additional syntax highlighters a while, so adding a new language is as easy as adding two lines of code — as long as CodeMirror already supports that one!

**Comment by Kurren123** [comment]
@nathanlesage interesting. Is there a reason we whitelist certain languages rather than just allowing all languages that codemirror supports? Will it affect performance/download size?

**Comment by nathanlesage** [comment]
I'm not quite sure, but many apps only whitelist the languages actually wanted — I mean, I don't know what would happen if we simply add all languages ¯\\\_(ツ)\_/¯ 

But this way it's not a problem for me — someone mentions an additional language, and I can add it and this way it works. It's more … verbose, which means: I can spot possible problems while adding the language. As they say it: Never change a running system!

**Comment by Kurren123** [comment]
@nathanlesage in that case, may I ask for some more languages that I use? F#, Elm and VB.net. I'd be happy to follow what you did in that commit and make a PR if you'd like.

**Comment by nathanlesage** [comment]
> F#, Elm and VB.net

What are common abbreviations for these languages (as in "haskell" and "hs", as well as "js", "javascript", "node" or "typescript" or "ts")? And which does [highlight.js](https://highlightjs.org/) accept?

**Comment by Kurren123** [comment]
Thanks for your reply. Highlight.js accepts all of them. I'd say common abbreviations are:

- F#: f#, fsharp
- Elm: elm
- VB.net: vb.net, vb, visualbasic

**Comment by nathanlesage** [comment]
Thanks for the research, all of these should work out, so I'll get to it soon!

**Comment by nathanlesage** [comment]
It has been done!

**Comment by Kurren123** [comment]
You are a gentleman
