### ISSUE TITLE
Heatmap unreadable in night mode

### ISSUE THREAD

**Issue by wgslr** [Zettlr/Zettlr#689]
## Description
The night mode turns text white, which is hardly visible on a bright green background.

## Reproducing
Trun on the night mode and perform a global search. It surely depends on one's screen, but for me the white text is absolutely unreadable on best-match files.

## Expected behaviour
File names in the search results are readable. I suggest making the text black on sufficiently bright backgrounds even in the night mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/6932414/79805557-b3859380-8366-11ea-8d2d-4935fa81ddbb.png)

## Platform
 - OS and version: Arch Linux 5.6.4-arch1-1 x86_64 GNU/Linux
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Look what I just found in the source code 😄 

![image](https://user-images.githubusercontent.com/17251683/79835300-c3c16100-83ae-11ea-96e4-41257751258f.png)

Just forgot to uncomment! It's now in the codebase and will be shipped with the next release!
