### ISSUE TITLE
[ENHANCEMENT] Tag hierarchy stored in text, cascading through folder structure

### ISSUE THREAD

**Issue by whatsnewsisyphus** [Zettlr/Zettlr#692]
Putting my imagination hat on here for a moment.

What if we could define Tag Hierarchies, as in parent and child (and inferred sibling) in simple text files that would apply down the folder tree, meaning to all the files in the same folder, and subfolders from there on down.

For example, the text file could look like the following, though perhaps the UI would expose it in a better way like it does with the tag cloud, showing you tags that have not been added to the hierarchy below. The UI would obviously be a better way to interact with this but storing it as a txt file within the archive would help the archive contain itself like legends/meta cards in a card catalog.

- Food
- - Fruit
- - - Apple
- - - Pear
- - Vegetable
- - - Broccoli

You could then search for the tag Pear and the search could suggest Apples as well because they are siblings, along with Fruit and Food going down in relevance.

Just an idea! Thanks for zettlr.

**Comment by nathanlesage** [comment]
Hey! I think this might be better served using a custom script!
