### ISSUE TITLE
Zettle 1.6 Normal copy raw text from github doesnt work, only copy without style

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#693]
## Description

When copying raw text from github only Paste without style work (Shift+ Cmd+V) work,
after normal Paste nothing happening
Example https://necolas.github.io/normalize.css/latest/normalize.css

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: MacOS,
 - Zettlr Version: 1.6, Safari Browser
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Could confirm, but it's an error with turndown, if the console is not lying:

![image](https://user-images.githubusercontent.com/17251683/80019623-1f3b3e00-84d8-11ea-8585-70c85a880a1d.png)

I'll be reporting this to to the Turndown repository. As soon as they deliver a fix, Zettlr will automatically incorporate this as I'm keeping all dependencies up to date at all times :)

N.B.: Both Safari and Chrome spit out the error, while Firefox works fine (albeit in Firefox, it will not detect that it's a code-block and escape all the characters)

***

Please watch this issue for updates on this: https://github.com/laurent22/joplin-turndown/issues/11
