### ISSUE TITLE
[BUG] CPU-Spikes during regular use

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#697]
## Description
CPU load spikes from 2-5% up to 50-60% and Zettlr freezes for 1-2 seconds, every 2 minutes or so. Drive load stays at less then 1%.

## Reproducing

I suspect it got worse with a bigger number of files. I currently have roughly 3100 notes. Therefore I think you'll be able to reproduce it with a relatively big number of files. 

## Platform
 - OS and version: OS X Mojave 10.14 / Windows 10 1909
 - Zettlr Version: 1.6

## Additional information

Currently 3298 files in Folder (.md and images)
Total size: 12,8MB

I thought Node.js is particularly good with a lot of file interactions.
I am a bit concerned regarding the future stability if I continue working on my Zettelkasten. Luhmann had 90k. I don't want to crap out that early 😃

**Comment by nathanlesage** [comment]
> I thought Node.js is particularly good with a lot of file interactions.

nah, especially the readdir operations are a hell of a catastrophe :D Nevertheless, does the problem disappear, if you unload all files and only have a folder with, like, ten notes? If yes, it might work with the new FSAL core that is currently under review!

**Comment by PhilHem** [comment]
Oddly, I can't reproduce the problem myself consistently. Right now, it's going smooth for a few hours. 
Will report further when I find out a possible cause! Thanks for adressing it though! :)

**Comment by nathanlesage** [comment]
If anything reproducible occurs, please comment!
