### ISSUE TITLE
[FEATURE] UnifiedJs (ReMark, ReText, ReHype)?

### ISSUE THREAD

**Issue by twardoch** [Zettlr/Zettlr#699]
Not sure how heavily Zettlr relies on Showdown but I wonder if integrating with [UnifiedJs](https://unifiedjs.com/) (ReMark, ReText, ReHype) is in any way “in scope”. I personally find the ideas behind the ReMark world great — very easy integration of plugins (I’ve written a few, though I’m no JS coder), great integration with text-based linters via ReText. Whether the actual HTML export is still done via Showdown is, to me, secondary. I like Zettlr’s GUI management of Markdown, and I think plugging UnifiedJs into it might open up a huge world of flexibility, esp. for “professional“ usage of Markdown.

But I can totally understand if there’s infrastructural or other reasons why Zettlr relies on this or that stack.

**Comment by nathanlesage** [comment]
> Whether the actual HTML export is still done via Showdown is, to me, secondary

That would be the only position where UnifiedJS would make sense, because I assume you're referring to syntax highlighting and other stuff to put on the GUI, right? Well, UnifiedJS is meant as a Markdown parser, whereas CodeMirror (the editor at the core of Zettlr) works with a lot of shortcuts to make rendering as fast as possible. This includes: Re-rendering only of certain lines, or parts of the document. So it requires a completely different approach to parsing Markdown than UnifiedJS, except I didn't get the way they're doing it. But as far as I understand it, UnifiedJS takes a full Markdown text as input and gives you some output. And this won't work with the editor!

**Comment by twardoch** [comment]
I see. I'm thinking that some integration would be great though. First, UnifiedJS can turn Markdown into its MDAst, and it uses plugins for custom "node types". Then those node types can return a Markdown representation or a few (so you can normalize, prettify etc.), and they can return HTML nodes which are then passed to ReHype, which is then a HTML ast. And you can output it of course. But it can also pass the MDAst to ReText, which is then a plain-text ast, where there are plugins tray do style linting or spell check.

**Comment by twardoch** [comment]
There is a flurry of plugins for various extra MD syntaxes for Remark, and I think it'd be great to have it as an alternative final renderer, like Pandoc. While working in the editor, I could use the draft preview, which is fast, but I would love the option to render the final thing with Remark. And the whole prettifying of MD done by Remark is good.

**Comment by nathanlesage** [comment]
> First, UnifiedJS can turn Markdown into its MDAst

This is exactly what Pandoc also does!

> I think it'd be great to have it as an alternative final renderer, like Pandoc

This is already possible right now by amending the "Advanced" command — simply replace `pandoc` with the renderer of your choice (needs to be a command that can be run on the command line) and adapt the arguments as necessary. If additional parameters need to be output by Zettlr, simply open up separate issues for these :)

As for Unified within Zettlr itself, the only thing I could imagine would be specific CodeMirror commands that can run once, but I couldn't think of something where it might be useful — however, I never dove into UnifiedJS, so there surely might be things. If so, as for the additional parameters, feel free to open up issues, if some components prove helpful!
