### ISSUE TITLE
Feature Request: AutoSave and Revert Button

### ISSUE THREAD

**Issue by sahil48** [Zettlr/Zettlr#7]
Please add an option to autosave documents when edited, so that I do not have to explicitly click the save button. If anything, I would want a revert button to undo autosaved changes since I last clicked the save button. It's more likely that I want the document saved when I exit, and very infrequently, I want to revert those changes when I mess up my document.

**Comment by sahil48** [comment]
A lot of times, I think I have a great idea, and then realize after a while that it wasn't such a great idea and I want to start from where I left off. Or you're writing and writing, and don't seem to be getting anywhere and want to start over from where you were before in a different direction. Usually occurs over 5 or 10 minutes (happens a lot when writing emails or last minute drafts). So, I'm not looking for a version control system, and I agree that should not be in the scope of the app, but something that reverts what you edited since the last time you did a hard save. I would be open to having a temporary file with the last hard saved content in the same folder.

**Comment by nathanlesage** [comment]
Ah alright, then I'll get into it in the next days! I think this should be pretty easy to accomplish. The easiest way would be to simply save the original file contents in a variable to be recalled if one wishes.

That means, the revert feature would work like this:

1. Open a file.
2. The file will be temporarily saved in memory, and displayed as well.
3. You edit it, save it, etc. pp.
4. You realize you want to revert all you've added, so you click "revert".
5. The app overwrites the editor's contents with the old data, and lets you then save to overwrite.

Or, should it always replace this reversion status on "hard saves" as you've called them?

**Comment by sahil48** [comment]
Let's stick with temporarily saved in memory for now, and explore the need for other options later.

**Comment by nathanlesage** [comment]
Alright, it's noted. After I've managed the inline image previews and hardened the regular scans for changed folders and files, I'll get to it. I hope that this will be in the course of next week

**Comment by sahil48** [comment]
"hard" save.

**Comment by nathanlesage** [comment]
Alright. I think I'll simply do both and let the user decide in the settings (a.k.a. "What should the revert button revert to?")
