### ISSUE TITLE
Feature: Simplenote Integration

### ISSUE THREAD

**Issue by SamwiseK** [Zettlr/Zettlr#70]
It would be amazing to sync an individual folder with Syncnote.

You can find the documentation for the Simplenote-API here: https://simperium.com/overview/

**Comment by nathanlesage** [comment]
Sounds like a great idea, I'll look to it!

**Comment by Jaifroid** [comment]
But this is a paid service, no?

>Previously, we offered the Basic Plan for free for apps using less than 250k requests per month. Going forward, we are eliminating the Basic Plan and all users with under 250k requests per month will be offered a free one year trial. After the trial period ends, customers must upgrade to one of the paid Plans.

**Comment by nathanlesage** [comment]
@Jaifroid Oh dear, that doesn't look good. I must confess I only took a quick look at the API.

**Comment by nathanlesage** [comment]
Okay, I just have confirmed that access to the SimpleNote API will cost 25$/mo. for 250.000 users. I'm not going to integrate something that the app creator itself has to pay for, sorry =/

(other APIs: Just throw them at me!)
