### ISSUE TITLE
Integrate better with the Operating System (window decoration)

### ISSUE THREAD

**Issue by tiotrom** [Zettlr/Zettlr#700]
In Sort, I use TROMjaro (Arch based), and Gnome for my desktop, and when it comes to such a great app that can be used for note taking and more, I use to right click the top bar (the native one for most applications in Linux), and set it up on all virtual screens. I cannot do this for Zettlr since it seems to not follow the OS specific window decorations. Any way this could be enhanced?

Cheers! And Thanks!

**Comment by nathanlesage** [comment]
Heh, there's an upstream fix in the codebase that restores default window decorations on linux operationg systems, so no worries, in 1.7 window decorations will return to Linux!

**Comment by tiotrom** [comment]
Ah so awesome! Thank you sir!
