### ISSUE TITLE
[ENHANCEMENT] support tilde style for fenced code blocks (~~~ instead of ```)

### ISSUE THREAD

**Issue by dani-l** [Zettlr/Zettlr#703]
## Description
Almost all Markdown processors I've dealt with allow fenced code blocks to be either written with three backticks (```) or three tildes (~~~). Zettlr only supports the backtick version. I would be really happy if support for the tilde version would be added.

## Proposed Changes
Add support for fenced code blocks with tilde in addition to backticks, both with and without the language identifier.

```
~~~
general fenced code block
~~~
```

```
~~~python
python fenced code block
~~~
```

## Caveats
I will [most likely be proven wrong](https://xkcd.com/1172/), but side effects should be minimal. I can only think about somebody using tildes in their documents for different purposes.

## Additional Information
- I think it is good if Zettlr can handle both variants to be able to display existing files properly.
- Backticks are horrible to type on a standard German keyboard with dead keys...

**Comment by nathanlesage** [comment]
Albeit I know almost all xkcds, I'm always surprised to how many situations they fit.

> Backticks are horrible to type on a standard German keyboard with dead keys...

I invite you to try typing a tilde on a German-layout macOS keyboard 🙃

But as tildes are officially in the CommonMark spec and widely supported, this shouldn't prove too difficult to implement.

In fact, why not implement it now … tada!

**Comment by dani-l** [comment]
> In fact, why not implement it now … tada!

Awesome, thanks a lot! That was incredibly fast. :)

Just a minor observation: From a quick glance at the diff it seems like the new behavior will match a fenced block starting with ``` and ending with ~~~ and vice versa. This is certainly not standard behavior and also does not conform with the CommonMark spec.

On the other side, I personally really don't care and my workflow issue is perfectly fixed by the change. I also just learned that there are way more details to take of to conform to CommonMark. One example being that fenced code blocks can also be started with more than three backticks/tildes and end "with at least as many backticks or tildes as the opening code fence". That looks like fun to implement...

**Comment by nathanlesage** [comment]
> This is certainly not standard behavior and also does not conform with the CommonMark spec.

Absolutely, but I'm currently pondering about this vs. the "correct" rendering implementation (b/c on export these restrictions will kick in), because "correct" rendering would mean having double the amount of "modes". I have to dive into the multiplexing mode to gauge the resources impact!

> One example being that fenced code blocks can also be started with more than three backticks/tildes and end "with at least as many backticks or tildes as the opening code fence".

This is already implemented, as the regular expressions look for three chars at the _beginning_ of the line and don't care about anything beyond that!

**Comment by dani-l** [comment]
> This is already implemented, as the regular expressions look for three chars at the _beginning_ of the line and don't care about anything beyond that!

I doubt that this is implemented. First of all, Zettlr does not seem to correctly interpret the language identifer if 4 backticks are used. Second, the spec requires _at least_ as many backticks as the opening fence so that the code segments can contain 3 (or more) backticks/tildes without unintentionally closing the code block. At least in 1.6.0 this also does not work.

````
```
this example is created written using a fenced block with four backticks
```
````

(Again: I'm perfectly happy with the status quo. Just nitpicking.)
