### ISSUE TITLE
Theme and review comments

### ISSUE THREAD

**Issue by phisanti** [Zettlr/Zettlr#704]
First of all, I think this software is fantastic. At the level of a professional tool! Thus, I would like to contribute my little grain with two potential enhancements:

- Would it be possible to have some sort of repository where all the community could upload themes for zettlr?
- Would it be possible to add some kind of reviewing comment tool so that different authors can communicate within the same document?

Kind regards and keep up with this amazing tool.

S

**Comment by nathanlesage** [comment]
Heya,

this is more for of a discussion for the forum, so if you'd like to discuss it more, please feel free to head over to the [forum](https://forum.zettlr.com/)!

> Would it be possible to have some sort of repository where all the community could upload themes for zettlr?

Would be great, but it doesn't have priority for now. It's certainly worthwhile to ponder about, but currently there's no time to implement this!

> Would it be possible to add some kind of reviewing comment tool so that different authors can communicate within the same document?

Currently, I can't say too much on this, so the following has to suffice: There are plans in the background of doing something along the lines of this. Once it's public-ready, I'll announce more! ;)
