### ISSUE TITLE
Image cannot be exported successfully

### ISSUE THREAD

**Issue by TangdizhiH** [Zettlr/Zettlr#705]
## Description
I'm using Zettlr(newest version) with windows 10. I installed pandoc (also newest version) to export my markdown into word. But sadly the exported file has not rendered all the image in the .docx. I don't know why but only a image can be exported successfully. Below is the word 
this one is successfully rendered:
![image](https://user-images.githubusercontent.com/45258158/80551614-9ac84e00-89f6-11ea-9abf-83670b90356b.png)

below are not rendered image:
![image](https://user-images.githubusercontent.com/45258158/80551635-b6335900-89f6-11ea-8d74-aa60479bb1c9.png)
this is what it like in zettlr
![image](https://user-images.githubusercontent.com/45258158/80551650-c21f1b00-89f6-11ea-9f28-2e28cadd5eb5.png)

## Reproducing
1. open a zettlr file
2. insert a image by copy-paste
3. export to the word

## Expected behaviour
all images are successfully displayed in word

**Screenshots**

## Platform
 - OS and version:
 - Zettlr Version:
 - Screen Resolution:

**Comment by nathanlesage** [comment]
> But sadly the exported file has not rendered all the image in the .docx.

Would you mind posting here the full source of both images? The problem is already known, and there is already one issue open somewhere, and we're currently wondering why the hell this is happening! So maybe comparing the two images might give us an insight what is happening there! :)

**Comment by TangdizhiH** [comment]
Ok, sure I would love to help:
this one is the unrendered picture
![实验室系统组成](https://user-images.githubusercontent.com/45258158/80590541-a5aecd00-8a4e-11ea-8ecc-d30863b54c24.png)
this one is rendered
![9b507c6b7f081d3e9d52249a48f40eca](https://user-images.githubusercontent.com/45258158/80590697-f1fa0d00-8a4e-11ea-953b-a0bbe4e92969.png)

Hope my sources can be help, I think these two are representative because they are all screenshotted from the same iPad at the same time.

**Comment by nathanlesage** [comment]
Sorry, I forgot to mention that I mean the source URL that you personally used in your file, e.g. `![some alt text](/the/link/to/the/image.jpg)`!

**Comment by nathanlesage** [comment]
Quick update, I just found out that the exporter NEVER replaced or made absolute ANY paths. I have no idea what I thought when I did that (probably not that much), but I just did the following amendments:

1. Reenable absolution (hehe) of the image paths
2. Make the function much shorter
3. Wrote a unit test
4. The logic is now: "If exporting to the same path, don't alter the links, if not, absolutify them, or if the absolutePaths override is set [only for projects]"

Works like a charm for me now, so please test it!
