### ISSUE TITLE
Preview of quotes buggy

### ISSUE THREAD

**Issue by thgie** [Zettlr/Zettlr#708]
## Description
If I indent a paragraph with tab to create a quote, it sometimes works to display it as such and sometimes not. I attached an example. It looks fine in plaintext. In the third screenshot, I indented with two tabs.

## Platform
 - OS and version: Windows 10 1909
 - Zettlr Version: 1.6.0
 - Screen Resolution: Enough

![01](https://user-images.githubusercontent.com/731681/80721419-7a83b680-8afe-11ea-85e2-5b1597519430.jpg)
![02](https://user-images.githubusercontent.com/731681/80721437-81aac480-8afe-11ea-8071-d71068bee7a2.jpg)
![03](https://user-images.githubusercontent.com/731681/80721433-7fe10100-8afe-11ea-811f-8a0815bb3e26.jpg)

**Comment by tobiasdiez** [comment]
Isn't adding a `>` symbol in the first line the "proper" way to add block quotes?
See https://markdown-guide.readthedocs.io/en/latest/basics.html and https://pandoc.org/MANUAL.html#pandocs-markdown.

**Comment by thgie** [comment]
Yes, I guess you're right. I found out shortly after and didn't feel like the brightest...
  

  
Could be closed 😅
  

  

  

  
  
  
  
  
>

**Comment by nathanlesage** [comment]
It looks like code, but then we come back to the ugly hack where an improvement is currently under review in a PR …!
