### ISSUE TITLE
PNG Image not displayed

### ISSUE THREAD

**Issue by xtrails101** [Zettlr/Zettlr#709]
Hi,

when inserting a PNG-Image, that is in the same directory as the markdown file or in a different directory on the local computer, it is not showing in Zettlr. JPG-Images will show up in the editor. Other editors are displaying  the PNG.

Inserting from the internet with an URL http/https works for PNG.

<img width="736" alt="Zettlr-PNG-not-showing" src="https://user-images.githubusercontent.com/14128369/80862216-80e76f00-8c73-11ea-9730-5ed79d7663a8.png">

Best regards
Ralf

**Comment by nathanlesage** [comment]
Hey Ralf,

thanks for reporting this issue! Do the DevTools tell something of an error while loading the image? You can open them by activating debug mode, then heading to the menu "Develop" and then selecting "Open DevTools"! If there was an error loading the image, it should look like this:

![image](https://user-images.githubusercontent.com/17251683/80944168-2e2fc380-8de9-11ea-980c-a0cf6b437e8d.png)

That being said, I was able to load a PNG image, so something's going on …

**Comment by xtrails101** [comment]
Hi,
yes I'm getting "file not found" errors.
I have tried to rename the file to get rid of the "ä".
I have changed to the full path, not using the relative.
I checked macOS Security that Zettlr can access my Desktop.

But the PNGs still not found. And the JPG that was shown, when I wrote the initial post, is not shown. When I "Drag'n Drop" the JPG into Zettlr again, it shows up. When I do this with the PNGs, they are not showing up.

Attached you will find the log. I'm on Version 1.6.0 using macOS 10.15.4.
Here is a screenshot of the Zettlr Window.

<img width="1305" alt="Zettlr-ImageNotFound" src="https://user-images.githubusercontent.com/14128369/80953674-4c52ef00-8dfc-11ea-8cf5-46fa9b2fc8be.png">

**The Log File**

[2020-05-04 FileNotFound-1588585168091.log](https://github.com/Zettlr/Zettlr/files/4573870/2020-05-04.FileNotFound-1588585168091.log)

**Comment by nathanlesage** [comment]
> I have tried to rename the file to get rid of the "ä".
> I have changed to the full path, not using the relative.
> I checked macOS Security that Zettlr can access my Desktop.

That is good to hear, because this means it's definitely something wiiiiaaaaah I think I just spotted a very strange issue, as Zettlr seems to be trying to retrieve the file at path `file:///users/ /Users/`, which is worse than wrong… I'll get to it!

**Comment by BellLongworth** [comment]
Also happens to me on 1.7. PNG images definitely worked on 1.6. 

All images are now just:
![image](https://user-images.githubusercontent.com/63842998/81400898-c9e96880-9136-11ea-9f8d-37fef94ae796.png)

**Comment by BellLongworth** [comment]
Correction: Some images (also pngs) are displayed and sometimes I can get the images that aren't displayed to work by having an empty line between them and the previous text line. 
I'm not sure that's all there is to is, I couldn't figure out where the consistency is just yet.

**Comment by nathanlesage** [comment]
>  I couldn't figure out where the consistency is just yet.

If you begin to notice this consistency, please give me a heads up so that I know where to look!

**Comment by nathanlesage** [comment]
I just had this thing myself, but I have absolutely no idea what is happening on the editor. In fact, the document itself seems to "jump around" inconsistently during writing, and I have no idea where it's coming from.

**Comment by nathanlesage** [comment]
Does it work on the most recent beta from yesterday evening?

**Comment by xtrails101** [comment]
Sorry for the delay.
It is not working for the PNG Images from the original post. I have downloaded them from the Internet. When I load them in Preview on macOS Catalina and export them to PNG they are loading in Zettlr without problems. So maybe the PNG itself is the Problem.

Attached you will find the log file of a test with one image not found. This ist the one I have downloaded from the web. And as you can see in the Screenshot, the loaded image after exporting it from Preview.

<img width="684" alt="2020-05-22 SomePngLoading" src="https://user-images.githubusercontent.com/14128369/82662099-90802500-9c2d-11ea-8c1a-a66c98f6469b.png">

**Here is the log-file.**

[2020-05-22-1590145363232.log](https://github.com/Zettlr/Zettlr/files/4667674/2020-05-22-1590145363232.log)

**Comment by nathanlesage** [comment]
Thanks for testing this out! There's still that absolute-path-issue — but I see you already have tabs, are you on the most-recent beta version?

**Comment by xtrails101** [comment]
Test was under 1.7.0-b5

**Comment by nathanlesage** [comment]
Thanks, I'll diff and see if beta6 will change something this evening!

**Comment by nathanlesage** [comment]
It should work now, I've just spent some time on the algorithm again. If it doesn't work in the new beta later the day, please comment here.

**Comment by xtrails101** [comment]
Yes, the file not found error is gone. Tested in Beta-7 😃

**Comment by nathanlesage** [comment]
Perfect! 😄
