### ISSUE TITLE
[FEATURE] Disable auto save

### ISSUE THREAD

**Issue by markojurkovic** [Zettlr/Zettlr#712]
## Description

It would be great if Zettlr had the ability to disable/turn off the automatic saving of open files. Without the ability to disable it, the auto save behavior dirties the Last Modified times of files, which makes it impossible to know which version if which, for example when syncing up/down with a cloud storage server.

## Example Workflow

This is self explanatory. Opened files should not be saved until a key combination is pressed or a "Save" button is clicked.

**Comment by nathanlesage** [comment]
This should be possible with the new FSAL, there's still a little bit of work to do, but it might work. I'll keep this open because I need to get back to the editor's handling of the dirty state either way!
