### ISSUE TITLE
Math formulas are not correctly displayed after a reveal.js export

### ISSUE THREAD

**Issue by ranwez** [Zettlr/Zettlr#713]
## Description
Math formulas are correctly rendered when I export the md file into HTML or PDF, but they are not when I use export in "reveal. js" format. 

## Reproducing
The simple markdown file
```
# test
$y=x^2$
```
generated a reveal.js html file that displays
```
test
 \(y=x^2\) 
```

## Expected behaviour
a nice formula instead of raw text.

**Screenshots**

## Platform
 - OS and version: windows 10
 - Zettlr Version: 1.6.0
 - Screen Resolution:

## Additional information
The mathematical formula appears correctly when I slighly modify the HTML file generated by zettlr/pandoc by inserting the following lines just after the metadata:
``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by nathanlesage** [comment]
Did you happen to use Zettlr prior to 1.6, and if so, did you "reset" the pandoc command in the advanced settings as advised in the changelog …?

**Comment by ranwez** [comment]
No I didn't use older version. I just discovered Zettlr this week-end and this was my first installation.

**Comment by nathanlesage** [comment]
Alright, curious, because I thought I added the lines to the HTML template already, but apparently something went wrong 🤨 I'll investigate!

**Comment by nathanlesage** [comment]
Does this still happen in 1.7 beta?
