### ISSUE TITLE
[ENHANCEMENT] Search by title, but insert filename when making link

### ISSUE THREAD

**Issue by Jos512** [Zettlr/Zettlr#716]
## Description
Currently when we type `[[]]` in Zettlr, we can insert a link to another note. This works based on the filenames in our directory. For people that use numerical IDs as filenames (such as timestamps), this requires searching for the proper numbers when making links.

But I find numbers much harder to remember (and type efficiently) than words. So when making links, I often first have to search for the note to link to since I don't know its ID link. 

Wouldn't it be more productive if Zettlr searches in-line for a note, and then inserts the proper filename ID for us? :slightly_smiling_face: 

## Proposed Changes
To have Zettlr do some of the mental work of looking up numbers, it can work like this:

- We type `[[]]` to make a note link.
- Rather than showing a file of numerical file IDs, Zettlr shows a list of note titles.
- When we select one of those titles, Zettlr automatically inserts the proper numerical ID for that note. That makes an anti-fragile link to that particular note.

But why not switch from numbers and use the note's title in its filename? I don't like to do that because:

- Timestamp IDs are guaranteed to be unique, no matter how many notes we get in our Zettelkasten.
- Timestamp filenames ensure that I can quickly make a new note (less friction) rather than have to solve file naming conflicts and break a line of thought.
- A note's title can change but its filename should not (else the internal links between notes break).

## Caveats
This is best implemented as an optional feature. Some people might be very good at remembering numerical IDs or have a setup where the numerical ID contains value.

**Comment by nathanlesage** [comment]
I just cross-checked this for me, and it perfectly works with notes that fulfill the following:

- Filename: `12345678901234.md`
- `title`-property in frontmatter: `My title`
- On link autocomplete, I can search also for the title
- It'll insert the ID and add the title afterwards.
