### ISSUE TITLE
[BUG]Pomodoro timer sound does not play

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#717]
## Description
The sound of the pomodoro timer does not play in the latest development version. It plays in version 1.6.0 without problems.

## Reproducing
1. Click on the Pomodoro timer icon.
2. Adjust the volume (the sound is played at this time).
3. "Start" and wait until the work phase ends.
4. The finish sound will not be played.

## Expected behaviour
The sound should be played at the end of each phase.

**Screenshots**
N/A

## Platform
 - OS and version: Windows 10 1903
 - Zettlr Version: latest develop
 - Screen Resolution: 1366 x 768

## Additional information
N/A

**Comment by nathanlesage** [comment]
Thanks for testing out the latest develop version! I'll see to it quickly! :)
