### ISSUE TITLE
Search for a new icon set

### ISSUE THREAD

**Issue by Wieke** [Zettlr/Zettlr#719]
As discussed in #538 I'm going to be looking for a GNU GPL v3 compatible replacement icon set for Zettlr. I'm going to start by listing all the functions we need icons for and seeing if I can find appropriate icons in some icons sets I know of. These are the sets I've considered:

* [Feather](https://feathericons.com/) (MIT license)
* [Bootstrap](https://icons.getbootstrap.com/) (MIT license)
* [Material Design](https://material.io/resources/icons/) (Apache 2.0 license)
* [Clarity Design](https://clarity.design/icons) (MIT license) (Thanks to @mhyfritz)

According to [this graph](https://en.wikipedia.org/wiki/License_compatibility#/media/File:Floss-license-slide-image.png) they should all be compatible with GPLv3. Let me know if I missed any good sets.

Here's my attempt at matching icons to functions (I listed multiple if there wasn't a clear best option in my opinion). 

|  Function               | Clarity | Material | Bootstrap | Feather |
|-------------------------|---------|----------|-----------|---------|
| Menu                    | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/bars-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/menu/v5/24px.svg?download=true) | | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/menu.svg) |
| Open directory          | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/folder-open-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/create_new_folder/v5/24px.svg?download=true) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/folder-plus.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/folder-plus.svg) |
| Create file             | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/file-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/note_add/v5/24px.svg?download=true) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/file-plus.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/file-earmark-plus.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/file-plus.svg) |
| View Stats              | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/chart/line-chart-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/bar_chart/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/show_chart/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/bar-chart.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/pie-chart.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/bar-chart-2.svg) |
| Tags                    | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/tags-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/more/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/local_offer/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/label/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/tag.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/tag.svg) |
| Settings                | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/cog-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/settings/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/gear.svg) | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/settings.svg) |
| Export                  | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/technology/export-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/share/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/files.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/share.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/share-2.svg) |
| Rename current file     | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/pencil-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/edit/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/pencil.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/pencil-square.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/edit.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/edit-2.svg) |
| Remove current file     | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/trash-line.svg) | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/bars-line.svg) |![](https://fonts.gstatic.com/s/i/materialiconsoutlined/delete/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/delete_forever/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/file-minus.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/file-earmark-minus.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/trash.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/trash-2.svg) |
| Text format             | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/text-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/text_format/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/type.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/type.svg) |
| Tabel of contents       | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/tree-view-line.svg) ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/view-list-line.svg) ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/social/hash-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/toc/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/hash.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/hash.svg) |
| Find in file            | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/search-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/find_in_page/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/search.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/search.svg) |
| Toggle readability      | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/eye-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/visibility/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/menu_book/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/book.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/eye.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/book-open.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/eye.svg) |
| View Attachments        | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/attachment-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/attachment/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/attach_file/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/paperclip.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/paperclip.svg) |
| Reset text field        | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/refresh-line.svg) ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/times-circle-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/backspace/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/backspace.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/delete.svg) |
| Remove autocorrect      | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/times-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/remove/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/clear/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/x.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/x-circle.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/x.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/circle-x.svg) |
| Project                 | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/folder-line.svg) ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/social/star-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/folder_special/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/files.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/folder.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/archive.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/star.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/folder.svg)  |
| Choose file             | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/file-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/note_add/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/file.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/file-earmark.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/file.svg) |
| Header 1-6              | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/text-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/title/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/type-h1.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/type-h2.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/type-h3.svg)  |  |
| Bold                    | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/bold-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/format_bold/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/type-bold.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/bold.svg) |
| Italic                  | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/italic-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/format_italic/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/type-italic.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/italic.svg) |
| Code                    | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/technology/code-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/code/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/code.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/code.svg) |
| Comment                 | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/info-circle-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/comment/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/code-slash.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/message-circle.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/message-square.svg) |
| Link                    | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/technology/link-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/insert_link/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/link-45deg.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/link.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/link.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/link-2.svg) |
| Image                   | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/core/image-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/insert_photo/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/image.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/image-fill.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/images.svg)  | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/image.svg) |
| Blockquote              | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/block-quote-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/format_quote/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/blockquote-left.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/blockquote-right.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/message-circle.svg) ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/message-square.svg) |
| Numbered list           | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/number-list-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/format_list_numbered/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/list-ol.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/list.svg) |
| Itemised list           | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/bullet-list-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/format_list_bulleted/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/list-ul.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/list.svg) |
| Task list               | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/checkbox-list-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/check/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/list-check.svg) ![](https://raw.githubusercontent.com/twbs/icons/master/icons/list-task.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/check-square.svg) |
| Insert table            | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/table-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/border_all/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/table_chart/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/table.svg)   | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/hash.svg) |
| Divider                 | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/minus-line.svg) | ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/view_stream/v5/24px.svg) ![](https://fonts.gstatic.com/s/i/materialiconsoutlined/remove/v5/24px.svg) | ![](https://raw.githubusercontent.com/twbs/icons/master/icons/hr.svg)  | ![](https://raw.githubusercontent.com/feathericons/feather/master/icons/columns.svg) |
| Footnote                | ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/text-edit/superscript-line.svg) ![](https://raw.githubusercontent.com/vmware/clarity-assets/master/icons/essential/child-arrow-line.svg) |  |  |  |
| Remove footnote         |  |  |  |  |

None of the libraries have everything we need. The add/remove footnote function is a hard one (as are the smaller headings), I would probably just use text to create a sort of icon for those functions, assuming it looks acceptable. (Eg. **H1**, **H2**, **H3**, **H4**, **H5**, **H6**, **x<sup>1</sup>** **x<sup>~~1~~</sup>**)

If it were up to me I'd use the bootstrap icons for text formatting and use feather for everything else (until feather properly [supports](https://github.com/feathericons/feather/issues/766) them), cause I prefer the somewhat cleaner look of the feather icons. But I could see a case for only using a single icon set.

Any thoughts?

**Comment by nathanlesage** [comment]
This already looks very nice, especially the idea with the table and side-by-side comparision is very thoughtful. Thanks for the initial research!

> The add/remove footnote function is a hard one (as are the smaller headings), I would probably just use text to create a sort of icon for those functions, assuming it looks acceptable.

Precisely how I did it now! If I remember correctly, the H1-H6-icons are the ones in the formatting menu, right? If so, then yes, let's switch to simple font, because right now they're also simply just text, and not icons …

> But I could see a case for only using a single icon set.

Yes, but I also see your point. Question is, will we be quicker implementing new icons (because I'd like to bundle something more with this feature, as the whole GUI could take a new paint) than they in adding the necessary ones…?

And just fyi: The minimize, maximize and close-icons will not be needed, as I'm reverting to the default Window decorations for Linux distributions, AND depending on how much time I have, I'd ideally like a VSCode style Windows menu in the app instead of the rather counter-intuitive "burger menu" button …

**Comment by Wieke** [comment]
Given that the sole feather maintainer is currently getting overwhelmed by pull requests (due to a recent increase in popularity) I suspect I'd be quicker if we just use the bootstrap icons in the formatting menu for the time being. As long as we don't mix icon sets within the formatting menu things should stay fairly consistent stylistically speaking anyway.

**Comment by mhyfritz** [comment]
@Wieke Great initiative!

You might also want to consider the [icon set](https://clarity.design/icons) from [VMware's Clarity Project](https://clarity.design/), which is [MIT licensed](https://github.com/vmware/clarity/blob/master/LICENSE).

They even have a [dedicated subset of icons for text editing](https://clarity.design/icons#text-edit-shapes).

Hope that helps!

**Comment by Wieke** [comment]
@mhyfritz Oh that's a nice icon site and it has nearly everything we need. The only thing it lacks is a nice comment icon (though we could just remove the slash from the code icon, use that for code instead, and use the original code icon for comment).

**Comment by nathanlesage** [comment]
> Given that the sole feather maintainer is currently getting overwhelmed by pull requests (due to a recent increase in popularity) I suspect I'd be quicker if we just use the bootstrap icons in the formatting menu for the time being.

🙏🏼 You have my blessings for however you want to tackle this!

**Comment by mhyfritz** [comment]
@Wieke Thanks for adding the Clarity icons to your overview! These are beautiful (IMHO), so you definitely have my vote for them 😄 I do not know, however, how the project handles feature requests, how many updates are planned etc. so I cannot tell how future proof they are - just something to keep in mind...

Regarding comment icon: I see that you used speech bubbles for Material and Feather, Clarity also has two variants in their [Social Shapes](https://clarity.design/icons#social-shapes). That being said, I guess this is not what you have in mind - as these are *code* comments, not *conversational* comments / side notes, right? If you anyway have to design a custom icon, you could also use a `//` symbol, as this is a very common comment delimiter in programming languages and is also used by some as part of a (rather obscure) Markdown comment syntax, see [here](https://stackoverflow.com/a/20885980). If you want the icon to represent *HTML comments* (which Zettlr actually generates), one could also think of a `<!>` icon.

**Comment by Wieke** [comment]
Some of those icons in the table are just what seemed the most appropriate one they had, even if it isn't really appropriate, like using a bubble or circle-i for a code comment. And honestly when I was picking the clarity icons I just changed my mind that the cirle-i was slightly more appropriate than the bubbles. Though I think I'm just going to use the </> icon for comments and create a < > icon for code, cause that's how the current zettlr icons look.

I think I'm going to go with the clarity icons. 

Here's the top bar with outline icons:

![image](https://user-images.githubusercontent.com/6737186/81309863-afa28280-9083-11ea-9977-ab649205d42b.png)

Here's the top bar with solid icons where available:

![image](https://user-images.githubusercontent.com/6737186/81310006-dbbe0380-9083-11ea-8467-237b7b463d96.png)

(Personally I prefer the outline icons.)

The above was done by setting `background-image` of the buttons in css. I'm currently considering inlining the svg instead so it can be styled through css.

**Comment by nathanlesage** [comment]
> (Personally I prefer the outline icons.)

I'm with you here

> I'm currently considering inlining the svg instead so it can be styled through css.

Sounds good. This would even make it modular, we simply need a mapping that the `ZettlrToolbar`-class can make use of to read and display the appropriate SVGs at the correct positions

**Comment by Wieke** [comment]
Implemented inlining of svgs for the toolbar. If an 'icon' attribute is set on an element from the `toolbar.json` file and it ends with svg, it is assumed to be a path relative to `sources\renderer\assets\icons` and the files is loaded and the content added to the button div.

So now, by setting the stroke and fill of paths (in svgs in a button) to white in the dark theme, the toolbar looks like this in dark mode:

![image](https://user-images.githubusercontent.com/6737186/81331901-90671d80-90a2-11ea-822c-d50a94683e25.png)

So that is neat.

**Comment by nathanlesage** [comment]
> So that is neat.

+1

Btw while we're at this we could also add "delete"-icons to the dialogs (the "reset" buttons), because while many fonts have a good unicode symbol for that (&#9003;), Windows system fonts obviously do not and therefore we might want to make that unform as well … but I can handle this if there's a good icon for that!

**Comment by Wieke** [comment]
I was planning to replace those icons as well.

**Comment by tobiasdiez** [comment]
A bit late to the party, but have you considered font-based icon sets? Then you don't have to fiddle with svg files but just specify the icon font via css. For example, https://dev.materialdesignicons.com/getting-started. (Not 100% sure if/how this works with electron).

**Comment by Wieke** [comment]
The advantage of svgs is that they're quite easy to customize with inkscape (in my opinion anyway). Some of the icons sets I considered did have font versions (material design and bootstrap). But I ended going with the clarity set because I thought it looked nice, had most of the icons we needed and is the only one with a proper export document icon.

Inlining svgs is a bit of a hassle though so I'm just letting the clarity library handle it. Just pop `<clr-icon shape="cog"></clr-icon>` into a page and clarity places the cog svg in it automatically. Register a custom svg so you can insert it the same way. Works pretty well.

**Comment by nathanlesage** [comment]
I'm with Wieke, mainly because SVG-images scale perfectly everywhere, and therefore are in the tendency also better used for displays >2k (such as 4k screens and Retina displays on macOS). Plus the antialiasing of Windows is to this day pretty bad (which is why Zettlr on Windows doesn't use Lato but Segoe UI, as Lato looks horrible on Windows systems).

> Inlining svgs is a bit of a hassle though so I'm just letting the clarity library handle it.

Does this work with content being instantiated at a later point or is there an ini-function we have to call everytime the DOM changes?

**Comment by Wieke** [comment]
There's no init function, it works with elements instantiated at a later point. When you load the module it adds a custom element (the `clr-icon` element) to the [CustomElementRegistry](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry). It seems to work fine with the toolbar builder.

**Comment by nathanlesage** [comment]
Oh my, that is pretty cool!

**Comment by nathanlesage** [comment]
As we already have a new icon set, closing this one
