### ISSUE TITLE
Feature: Please add en-dash and em-dash to Editor.

### ISSUE THREAD

**Issue by leetang888** [Zettlr/Zettlr#72]

**Comment by nathanlesage** [comment]
What do you mean by this issue?

If you want to use en- and em-dashes, don't forget you're writing in Markdown, i.e. use `--` for en-dashes and `---` for em-dashes.

If you want to directly insert them, it's easier to use the shortcuts:

- en: macOS/Linux: `Alt+-`; Windows: `Alt+0150`
- em: macOS/Linux: `Alt+Shift+-`; Windows: `Alt+0151`
