### ISSUE TITLE
Help with packaging for nixos

### ISSUE THREAD

**Issue by maralorn** [Zettlr/Zettlr#720]
## Description

I am trying to package zettlr for nixos. I have never done anything with yarn or electron and on nixos everything is different. I understand completely if you cannot help me, but I thought I‘d give it a shot.

The problem is, that under nixos the build process has no network connectivity so I cannot just run `yarn install`. But I have to download the dependencies differently and set them up by myself.

Anyways I got actually quite far. Nixos has tooling for downloading all dependencies from a `yarn.lock` file. I can start the app with electron. But then I get a blank white window with a greyish empty titlebar. When I press `F1` it opens `docs.zettlr.com` in my browser so there is some zettlr in there.

## To "Reproduce"

Here is what I tried to do:
1. Download the app source.
2. Download all dependencies from yarn.lock and put them into node_modules
3. Run in that app directory
```
yarn less --offline
yarn handlebars --offline
yarn reveal:build --offline
yarn wp:prod --offline
```
4. Generate a wrapper that starts "electron path/to/zettlr"
5. Run that wrapper.

I can share the nix-build expression that I tried, if you want. But my guess is that you wont have much use for it.

## Question

I am very sure that the problem is that I haven‘t provided some resource at the right point, but the blank window is not telling me what is missing.

So maybe do you have any hints how I can go about debugging this, like opening a dev console in electron or enabling debugging output in zettlr?

## Platform
 - OS and version: nixos unstable
 - Zettlr Version: v1.6.0

**Comment by nathanlesage** [comment]
> The problem is, that under nixos the build process has no network connectivity so I cannot just run yarn install. But I have to download the dependencies differently and set them up by myself.

Ouh, this sounds awful. Well, you could simply run the whole stuff on a machine with network access, but I see the problem where Electron-builder attempts to download the binary for nixos, as I have no idea how that process looks behind the scenes … with network access, it'd be only a matter of some small config changes …

**Comment by danieltomasz** [comment]
Hi @maralorn I don't have experience with that kind of problem but did you tried https://github.com/svanderburg/node2nix ?

**Comment by maralorn** [comment]
I used https://github.com/moretea/yarn2nix don‘t think that node2nix would have had a significant advantage.

Just a quick heads up, that I have given up on this. Sorry for the noise.
