### ISSUE TITLE
Support for Chemistry

### ISSUE THREAD

**Issue by redoxmatlab** [Zettlr/Zettlr#721]
Hello,

I am new to Zettlr but being a scientist who enjoys writing in MD I wish to request support for mhchem package (https://mhchem.github.io/MathJax-mhchem/). 

This package is critical if we adopt Zettlr for technical writing. I have tried to add the equation below but it could not be exported correctly into PDF since mhchem is not supported. 
$\ce{CH4 + 2 $\left( \ce{O2 + 79/21 N2} \right)$}$

So, please do consider supporting this component in Zettlr. 

 Many thanks.

**Comment by nathanlesage** [comment]
As already mentioned in my reply mail, I'll add support as I manage with the time! :)

**Comment by redoxmatlab** [comment]
Excellent! I look forward to hear about progress on this. Thank you.
