### ISSUE TITLE
CSS template

### ISSUE THREAD

**Issue by redoxmatlab** [Zettlr/Zettlr#722]
Hi, 
I am new to Zettlr and interested in being able to modify the output of Zettlr. I think it would be useful if examples of CSS templates could be provided as examples so that non-experts could make a swift start. 

For example, how I could change the background color of a Blockquote and how I can ensure that this change is exported in the output PDF?
Thanks.

**Comment by nathanlesage** [comment]
> For example, how I could change the background color of a Blockquote and how I can ensure that this change is exported in the output PDF?

There's a lot in that one question!

First, CSS (or rather, in the context of this project, [CustomCSS](https://docs.zettlr.com/en/core/custom-css/#custom-css)) is solely used to style the editor itself. Zettlr's main selling point is to keep the final layout completely separate from the writing process, as writing and layouting are two different pair of shoes.

That being said: You style the *editor* using Custom CSS, and when it comes to exporting, you can customize a lot by providing a [custom LaTeX template](https://docs.zettlr.com/en/academic/custom-templates/). Basically the main requirement is that it's compatible to Pandoc, but as long as that's ensured, you go you!

Nevertheless, for this kind of workflow discussion, I would like to redirect you to the [forum](https://forum.zettlr.com/), as this would be a much more appropriate place for discussion!
