### ISSUE TITLE
support captions for figures

### ISSUE THREAD

**Issue by redoxmatlab** [Zettlr/Zettlr#723]
Currently, Zettlr does not seem to support figure/image caption. 
This is a beautiful feature in Ulysses (https://ulysses.app/styles/reference/figurecaptions) and I hope this could be implemented in Zettlr.

Thank you

**Comment by nathanlesage** [comment]
Something like https://github.com/Zettlr/Zettlr/issues/640 or https://github.com/Zettlr/Zettlr/issues/663?

**Comment by ecodiv** [comment]
Hi @nathanlesage, adding the option to add a caption would be great. This is not the same as #663. It would benefit from the ability to reference to the figure (#640), but it is more than that. It refers to the description that one normally adds to figures and tables in scientific articles.  In Word one would use the 'insert caption' options. In html this is implemented as:

```
<figure>
  <img src="pic_trulli.jpg" alt="Trulli" style="width:100%">
  <figcaption>Fig.1 - Trulli, Puglia, Italy.</figcaption>
</figure> 
```
