### ISSUE TITLE
Add support for auto-backup

### ISSUE THREAD

**Issue by redoxmatlab** [Zettlr/Zettlr#724]
At the moment Zettlr does not seem to support auto backup or version mechanism. Please consider adding this feature to avoid loss of data.

Thank you.

**Comment by nathanlesage** [comment]
Backupping was traditionally thought to happen via cloud services (Zettlr is a flat file management software, so backing up everything to a cloud instance of your choice works flawlessly). However, if you want something like git support, there's already an issue open somewhere — it's one of the next things I wanted to tackle!

**Comment by redoxmatlab** [comment]
Happy to hear this is the pipeline. Thank you
