### ISSUE TITLE
Current master does not work 

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#727]
This is how it looks for me:
![image](https://user-images.githubusercontent.com/5037600/81220036-f8552f80-8fe0-11ea-856a-aa2445874ee3.png)
I tried to run `yarn install` as well as running all the update scripts. Did I missed something?

Log output:
```
Zworski2012 {
  id: 'Zworski2012',
  type: 'book',
  author: [ { family: 'Zworski', given: 'Maciej' } ],
  title: 'Semiclassical Analysis',
  ISBN: '978-0-8218-8320-4',
  publisher: 'American Mathematical Society',
  'collection-number': 'Graduate Studies in Mathematics'
}
FSAL state changed: filetree
10316 ms: Loaded directory D:\Research
Starting chokidar ...
FSAL state changed: filetree
1096 ms: Loaded directory D:\Research\Notes
FSAL state changed: openDirectory
FSAL state changed: openFiles
+++++ SYNCING OPEN FILES WITH RENDERER +++++
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more 
information please check https://github.com/electron/electron/issues/18397
Done in 47.28s.
```
Before this, my complete bibtex file is printed (that's probably a bug as well).

**Comment by nathanlesage** [comment]
> my complete bibtex file is printed (that's probably a bug as well)

Actually, it's not :D But: Ever since I removed the CSL styles from Git, this happens whenever you switch branches — simply run `yarn csl:refresh` to retrieve the style files. If your library is printed this means this is missing — it's one remnant console.log which I have come to adore because it's the definite sign I need to update the CSL files. But I have no idea why I have to re-pull the files everytime…

**Comment by tobiasdiez** [comment]
Sadly, this command gives
> $ node scripts/update-csl.js
Receiving file locales-af-ZA.xml ...
Done. Writing to disk ...
An unexpected error occurred!
[Error: ENOENT: no such file or directory, open 'D:\Programming\Projects\Zettlr\source\main\assets\csl-locales\locales-af-ZA.xml']

In fact, there is no `csl-locales` folder. 


At JabRef, we had also constantly problems with the csl. These are gone since we directly include the files as a git subtree and update them regularly using the following github action: https://github.com/JabRef/jabref/blob/2af41eb82353e37e2a6730485dc76276457fd4af/.github/workflows/refresh-csl-subtrees.yml#L35

**Comment by nathanlesage** [comment]
Oh boy, I may have screwed up git a little bit — the folder itself SHOULD be in the git … wait, let me have a look

**Comment by nathanlesage** [comment]
Yup, as I suspected, in a short moment of _geistige Umnachtung_ I also ignored the gitignore file in the directory, so no wonder we had to pull down the CSL files every time …

**Comment by tobiasdiez** [comment]
Thanks for the update. The error is gone now. Sadly, it still doesn't work. Looks slightly better now:
![image](https://user-images.githubusercontent.com/5037600/81407419-a7a61980-913b-11ea-9d07-13fa4c733da7.png)
And the log output seems to be ok:
```
D:\Programming\Projects\Zettlr/node_modules/.bin/electron.cmd . 

FSAL state changed: filetree
Creating placeholder for dir D:\Programming\Projects\Zettlr\resources\MarkdownTest
FSAL state changed: filetree
7872 ms: Loaded directory D:\Research
Starting chokidar ...
FSAL state changed: filetree
1219 ms: Loaded directory D:\Research\Notes
FSAL state changed: openDirectory
FSAL state changed: openFiles
+++++ SYNCING OPEN FILES WITH RENDERER +++++
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

Any idea what's missing?

**Comment by nathanlesage** [comment]
Good question … hmmm … what does the console (in the Chrome DevTools) say? Because there _must_ be some error being thrown, otherwise e.g. the toolbar should've already instantiated itself. It very much looks like there's an error in the init function of the renderer, so hopefully there's an error on the console. You should be able to open the console using the shortcut!

**Comment by tobiasdiez** [comment]
Sorry, false alarm, was actually a problem with my code 🙈. Works now.
