### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by forkingpath** [Zettlr/Zettlr#729]
Hello Hendrik,

Thank you for this great software. I am enjoying using it. I tried to export to pdf. I downloaded LaTex and pandoc. However, the pdf output is not showing lists. It outputs other formatting (like bold and italics) but not lists. I am attaching a screenshot. May be I am not doing something right?

Thanks.

![pdf output](https://user-images.githubusercontent.com/4701866/81250700-3da84a00-903f-11ea-9e6e-8f4ebb70e5d8.jpg)
![Zettlr file](https://user-images.githubusercontent.com/4701866/81250751-59abeb80-903f-11ea-9e47-49f995537244.jpg)

**Comment by nathanlesage** [comment]
Hmmm, this is weird … I'm not sure but MAYBE the missing empty line between the list and the meta info is the cause …?

**Comment by forkingpath** [comment]
Indeed, it was. Thanks a lot.
