### ISSUE TITLE
Spacing before paragraph in pdf

### ISSUE THREAD

**Issue by forkingpath** [Zettlr/Zettlr#731]
There is a space before the paragraph begins when exporting to pdf. Is there a way to remove that space in export?
Thanks (and sorry to put this in the "bug" section)

![Annotation 2020-05-07 170810](https://user-images.githubusercontent.com/4701866/81290247-5b989d80-9085-11ea-8f39-4864c94f6050.jpg)

**Comment by nathanlesage** [comment]
Yes, it's a default setting in the template (hanging indent), you can remove that by either using a custom template altogether, or selectively for files by using

`\setlength{\parindent}{some number}` (This overrides the value for all following text until you re-set this again)

Browse the full template here: https://github.com/Zettlr/Zettlr/blob/develop/source/main/assets/export.tex

More info: https://en.wikibooks.org/wiki/LaTeX/Paragraph_Formatting
