### ISSUE TITLE
[ENHANCEMENT] Always use forward slashes on Windows

### ISSUE THREAD

**Issue by yhancik** [Zettlr/Zettlr#732]
First of all, thanks for your nice work on Zettlr!

On Windows, when images are added through drag&drop or copy-paste, Zettlr uses backslashes as a path delimiter. This is the default on Windows, but these paths don't work on other systems, or on Github.

## Proposed Changes
Since Zettlr seems to be able to display images when their path uses forward slashes, even on Windows, why not enforce forward slashes for all image paths on Windows?
(an HTML editor wouldn't use backslashes for its paths, would it?)

## Caveats
It might break some exports; some export processes might need to convert forward slashes back to backslashes to be able to load images properly.
(I only tested ODT export so far: relative paths work with either forward or backslashes. Absolute paths never seem to work so that doesn't change much)

**Comment by nathanlesage** [comment]
> Absolute paths never seem to work so that doesn't change much

That is some bug, I suspect, but it's one of the mosquito type, hence difficult to spot. But the idea to simply enforce forward slashes is in fact reasonable!

**Comment by yhancik** [comment]
I left a comment on issue #543 about the Windows + absolute path + export mess ;)
https://github.com/Zettlr/Zettlr/issues/543#issuecomment-625536943

**Comment by yhancik** [comment]
The main point kind of got lost in the export issues, but I still think that for standardisation & interoperability, enforcing forward slashes would be a good move. 

I can test exports on Windows if it's of any help. But so far I haven't encountered any issues manually using forward slashes in image paths :)

**Comment by nathanlesage** [comment]
> I can test exports on Windows if it's of any help. But so far I haven't encountered any issues manually using forward slashes in image paths :)

Yeah, I think so, but I'm always a little bit afraid of what happens if we just set forward-slashes in every case on Windows :S Unfortunately I don't have the time to investigate, so let's first see what the other issue does, and if the problems still persist, then f*** it and we have to go the additional mile

**Comment by yhancik** [comment]
If you have any indication of where in the code the path formating/normalisation happens, I can have a look and test (although JS is not my forte). I totally understand your concerns though ;)

**Comment by nathanlesage** [comment]
> path formating/normalisation happens

See: https://nodejs.org/api/path.html

The problem is we make use of this function, and changing it in a fair amount of places is simply not feasible …

**Comment by yhancik** [comment]
I gave it a try, together with my other suggestion to only use the filename+extension as the caption ;)
https://github.com/yhancik/Zettlr/commit/327686f014b570e0d1a611ba80a9fd4dde9e96ef

But I'm kinda hesitant to make a pull request on this because, as I mention in the commit comment, it should ideally be up to the user to choose whether they want this or not.

**Comment by nathanlesage** [comment]
Looks definitely cleaner than my old code =D

I don't know, are only images affected by this?

**Comment by yhancik** [comment]
Yes that's only for images during a drag&drop or paste.

(I don't know what else is created automatically with paths... dragging a .md file create an internal link [[id]], no slashes... pasting an internet links keeps the forward slashes... am I missing something?)

I guess if the change is applied like this, becoming the new default, some Windows users might have files mixing both old-style absolute paths + backslashes AND new, always-relative POSIX paths. I don't know. It might bother some people? They can still change it manually after an imagine insertion, though ;)

**Comment by nathanlesage** [comment]
Mh … I am still at a loss why ONLY this doesn't work o_O 

So … do the previews work? Or is it only the Pandoc exporting? Because if the latter, then I could message tarleb and ask him about this, maybe it's a bug …?

**Comment by yhancik** [comment]
Ooops, hold on, maybe there's a misunderstanding here!

I thought _"I don't know, are only images affected by this?"_ was for my suggested changes (I since made a PR of it).

Actually both previews & export work, and the only thing that is still not working in the current develop branch is this : https://github.com/Zettlr/Zettlr/issues/543#issuecomment-629724948 = backslashes in image captions are sometimes misunderstood as "control sequence" for Pandoc. 

A nice side effect of my proposal is that, since it's using only the basename in the image caption, there are no more slashes in it ;)

If you want to be extra cautious, you probably need to write a nice regex that escape all backslashes in images captions before sending everything to Pandoc?

**Comment by nathanlesage** [comment]
> backslashes in image captions are sometimes misunderstood as "control sequence" for Pandoc.

Aaah, I see!

> If you want to be extra cautious, you probably need to write a nice regex that escape all backslashes in images captions before sending everything to Pandoc?

If only the image captions produce errors, then I'd rather suggest something different: Keep all the paths the way they are BUT only implement a regex that escapes all backslashes (+ obviously only use the basename, I don't know why I didn't do that before)

**Comment by kulbhushanchand** [comment]
@nathanlesage Apologies for necromancy on this closed issue.  
Having forward slash in the generated path when drag-drop files is still not available, and presently I have to manually convert `\` to `/`
Is there any plan to implement this enhancement in future?
Thanks

**Comment by kulbhushanchand** [comment]
@nathanlesage Is it intentional to not provide forward slashes in url in windows when drag-and-drop images?
or is this issue is ignored for any reason?
Kindly help me understand if there is something missing at my end.
Thanks
