### ISSUE TITLE
[BUG] Deleting notes in Zettlr 1.7-beta doesn't work

### ISSUE THREAD

**Issue by Bubblbu** [Zettlr/Zettlr#733]
## Description

Deleting notes through Zettlr seems to be failing

## Reproducing

Simply deleting through right mouse click within Zettlr

## Expected behaviour

Note is removed and, if currently open in a tab, tab is closed.

**Screenshots**

## Platform
 - OS and version: Lubuntu 16.04
 - Zettlr Version: 1.7-beta
 - Screen Resolution: 1600x900

**Comment by nathanlesage** [comment]
Ah dammit, that was too quick for an error :D 

But the files are indeed deleted, I just forgot to implement to close them beforehand …

**Comment by nathanlesage** [comment]
Alright, due to fixing the other issues, this bug seems to have gone away. If it returns with the new beta, just comment and provide additional info of the state you are in when this bug occurs! :)

**Comment by Bubblbu** [comment]
I'm running the beta.2 but the bug still seems to be around for me.

I am opening Zettlr (no files open) and try to delete a note, confirm the deletion, and nothing seems to be happening. Note still accessible through sidebar + on disk.

```
FSAL state changed: openDirectory
FSAL state changed: openFiles
+++++ SYNCING OPEN FILES WITH RENDERER +++++
```

However, if I open the note, attempting to delete the note will trigger a file close.

```
Opening file ... -1805334987
FIle 20200507143834.md is now open
FSAL state changed: openFiles
+++++ SYNCING OPEN FILES WITH RENDERER +++++
FSAL state changed: activeFile
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
FSAL state changed: openFiles
+++++ SYNCING OPEN FILES WITH RENDERER +++++
FIle 20200507143834.md is now closed
```

**Comment by nathanlesage** [comment]
> I am opening Zettlr (no files open) and try to delete a note

Ah, this is a very important piece of context information. I'll have a look at this.

**Comment by nathanlesage** [comment]
For me it's working now (most recent beta build) — if not please feel free to comment!

**Comment by Bubblbu** [comment]
Still not working for me with beta.5. I confirm the note deletion, note is closed, but not removed from disk/sidebar.

Logs say:

```
[17:51:46]	>>> IPC IN: file-delete
[17:51:46]	Trying to run command through Application: file-delete
[17:51:47]	<<< IPC OUT: dir-replace
```

The last output for dir-replace contains quite a bit of content (which is also truncated) apart from the hash. Not sure if that would be helpful for you 2.

**Comment by nathanlesage** [comment]
> The last output for dir-replace contains quite a bit of content (which is also truncated) apart from the hash.

That is to be expected — if you remove a file, the main process will notify the renderer to update the containing (= parent) directory, and will send it along. That's why the output is so huge, it basically contains the full metadata of the whole directory that the renderer will replace subsequently.

Stupid sounding question, but: Does your file system have some specifities, such as network mounted volumes?

**Comment by nathanlesage** [comment]
Should work again
