### ISSUE TITLE
[FEATURE] Keyboard shortcut for tab management

### ISSUE THREAD

**Issue by Bubblbu** [Zettlr/Zettlr#735]
## Description

All the classic keyboard shortcuts for tab management would be great (if not crucial now that we have multiple tabs)

## Example Workflow

Ctrl+W: Close current tab
Ctrl+(Shift+)+Tab: Browse tabs

**Comment by nathanlesage** [comment]
Yes!

**Comment by BellLongworth** [comment]
@nathanlesage and @Bubblbu do you mind if I hijack this issue for a half related question regarding tab behavior?

I thought the tab system will work like in browsers, where you browse through pages in a single tab until you actively open another tab. 
In the beta whenever I click a note a new tab opens. At least for me this adds a lot of superfluous clicking when I browse through a few notes before coming back to the note I'm working on.
Ideally I would've opened a new tab, used it for browsing, and closed it when returning to the tab I'm actually working on. Right now I end up with 10 open tabs that I need to close one by one.

**Comment by nathanlesage** [comment]
@BellLongworth This sharply reminds me of this still handwarm issue: https://github.com/Zettlr/Zettlr/issues/734

**Comment by BellLongworth** [comment]
Oops, did not see that one. Thanks!

**Comment by nathanlesage** [comment]
Already implemented
