### ISSUE TITLE
[BUG] Closing a tab with file changes does not offer to save/discard/cancel

### ISSUE THREAD

**Issue by Bubblbu** [Zettlr/Zettlr#738]
## Description

Closing a tab with file changes does not offer to save/discard/cancel

## Reproducing

Open new tab, edit file, and close tab.

## Expected behaviour

Option 1: Zettlr should offer to save or discard the changes, or cancel closing the tab.
Option 2: Close tab, however, keep track of the version in the current working space including all local changes.

**Screenshots**

## Platform
 - OS and version: Lubuntu 16.04
 - Zettlr Version: 17-beta
 - Screen Resolution: 1600x900

**Comment by BellLongworth** [comment]
Wasn't the pre-tab behavior to automatically save whenever you navigate away to some other note? 
I got quite used to this Google Docs type of behavior where whatever I don't need to concern myself with saving and I would love for it to remain in Zettlr. 
If that happens, then there is no need for and an offer to save/discard at all.

**Comment by nathanlesage** [comment]
> Wasn't the pre-tab behavior to automatically save whenever you navigate away to some other note?

This is at least the idea, but there's still a small amount of functionality simply missing, this is (I think) one of it. And the `Cmd/Ctrl+W` shortcut for closing tabs.

**Comment by Zverik** [comment]
Wow, this is critical: changes are indeed not saved when a tab is closed. I've neved used the saving shortcut before, but must do it now.

Can we do without "unsaved" indicator and manual saving? Just save everything automatically and asynchronously.

**Comment by BellLongworth** [comment]
Another addition: Renaming a file seems to lead to close-reopen action, with all unsaved changes lost.

**Comment by nathanlesage** [comment]
Yep, I didn't fully implement the auto-save-intention for the new tab functionality, which is partly due to me always hitting `Ctrl/Cmd+S`, which is recommended either way ¯\\\_(ツ)\_/¯ 

> Just save everything automatically and asynchronously.

There's a timer that saves a file after no changes happened for 5minutes, plus many actions still trigger saves, albeit as you correctly found out, not all …

> Renaming a file seems to lead to close-reopen action, with all unsaved changes lost.

Good point.

**Comment by wgslr** [comment]
> Yep, I didn't fully implement the auto-save-intention for the new tab functionality, which is partly due to me always hitting `Ctrl/Cmd+S`, which is recommended either way ¯\_(ツ)_/¯

By reading the docs I understood the contrary - that relying on autosave is the standard, or at least sufficient apart from "feels":
> Cmd/Ctrl+S: Save the file. Zettlr automatically saves your files, but some people tend to feel better having the option to manually save.

So I definitely agree with previous comments that either the auto-save should be more reliable (and perhaps more frequent than 5 minutes?), or there should be clear advertisment of the need to save manually.

P.S. Thank you for your work on Zettlr. So far I'm discovering lots of useful features, and with the fleshed out FS handling I hope for an even better experience!

**Comment by nathanlesage** [comment]
> that relying on autosave is the standard, or at least sufficient apart from "feels"

Yes, absolutely. This morning I just was a little bit aggravated due to the high amount of new bugs and issues people found immediately … I just didn't handle this that well!

> So I definitely agree with previous comments that either the auto-save should be more reliable

Yes, as I said, there's a lot of work until we have a stable 1.7 …

> and perhaps more frequent than 5 minutes?

I meant seconds, not five minutes, sorry!

**Comment by wgslr** [comment]
> Yes, as I said, there's a lot of work until we have a stable 1.7 …

Sure thing, I knowingly installed a beta version :v: 

> > and perhaps more frequent than 5 minutes?
> 
> I meant seconds, not five minutes, sorry!

Oh, that's better :grin:

**Comment by BellLongworth** [comment]
> Yes, absolutely. This morning I just was a little bit aggravated due to the high amount of new bugs and issues people found immediately … I just didn't handle this that well!

Hey, that's a huge release! Lots of bugs are expected. 
The version is actually working and completely usable, that's the big achievement.

**Comment by nathanlesage** [comment]
> The version is actually working and completely usable, that's the big achievement.

❤️ 

I already know how to fix at least this discard/save-thingy, I wanted to do this today Buuuuut there was a video production in the way :D I'll see to it tomorrow or so …!

**Comment by nathanlesage** [comment]
From another issue:

> New note creation is sometimes obstructed, if there is another note open that is not yet saved manually. It will simply not create the note, without any error message.

This can be tackled exactly with all the other issues, because this as well depends upon that state change I'll need to add to the FSAL!

**Comment by nathanlesage** [comment]
Short update: I managed to prevent closing as long as any changes are unsaved, but now the window is too difficult to close, because I have to switch the source of truth on file modifications to the renderer process with this one … damn it, my own perfectionist aspirations are definitely not healthy when dealing with software that is simply supposed to work.

**Comment by Zverik** [comment]
Could you just get rid of the concept of "unsaved"? Because it automatically means one could lose their changes.

**Comment by nathanlesage** [comment]
If I would propagate every single change to main this is likely leading to race conditions, especially if there are manifold writes to the file system. :/ This is why I don't do this in the first place …

**Comment by nathanlesage** [comment]
There we go. Writing some pseudo code followed by traditional rubber duck debugging has in fact helped a lot, and I could additionally trash a lot of unnecessary code. I should definitely make this a habit.
