### ISSUE TITLE
[BUG] Loading Bibliography Broken

### ISSUE THREAD

**Issue by hubertau** [Zettlr/Zettlr#739]
## Description
Hi! Really excited about 1.7.0 beta :) Unfortunately bibliography files don't seem to be loading correctly into Zettlr anymore. I didn't change my Zotero exports in between changing from 1.6 to 1.7.

## Reproducing

I've included a sample of a Better BibTeX export from my library (also tried with Better CSL JSON which was what my original export was in): [Exported Items.bib.zip](https://github.com/Zettlr/Zettlr/files/4596743/Exported.Items.bib.zip)

And I see the following each time I open Zettlr:
![Bib Screenshot](https://user-images.githubusercontent.com/33794762/81364818-1b154000-90d6-11ea-8ba7-aa8d21c5a868.png)

## Expected behaviour
Load citations successfully

## Platform
 - OS and version: Mac OS 10.15.4
 - Zettlr Version: 1.7.0-beta
 - Screen Resolution: 2560*1440

**Comment by nathanlesage** [comment]
Just found the error:

![image](https://user-images.githubusercontent.com/17251683/81378643-e7530e00-9107-11ea-90b1-7dafebb16f79.png)

Somehow the rate limit on the CSL locales repository scrapped the build, as somehow no error was thrown. I'll just replace the macOS file … uno momento

**Comment by nathanlesage** [comment]
Fix update is released! According to the build logs it'll work now! If not, simply comment and I'll grab the pitchfork :D
