### ISSUE TITLE
[BUG] Switching tabs does not place input focus in the note

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#741]
## Description

The idea is to start typing immediately after opening a note or switching tabs.

## Reproducing

* Open a note and press some keys to type — doesn't work.
* Open a second note. Click on the text to put focus there.
* Click on the first tab and press some keys to type — doesn't work.

## Expected behaviour

I open a note and the cursor is immediately where I left it.

## Platform
 - OS and version: macOS 10.14.5
 - Zettlr Version: 1.7.0-beta1

**Comment by Zverik** [comment]
I'd like to highlight this issue again: it is very frustrating when you're switching between tabs and creating new notes every minute.

**Comment by nathanlesage** [comment]
Huh, totally forgot this. But don't worry, as long as we haven't solved that pesky remote-modification-but nothing's gonna release :D
