### ISSUE TITLE
[BUG] Table display reverts to markdown from preview after alt-tab

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#742]
## Description
Table display reverts to markdown from preview after alt-tab

## Reproducing
Create table, get it to be displayed in preview mode (not sure what the technical name is. It is when you see a pretty table and not markdown).
Click one of the cells so that the cursor is there
Alt-tab to some other window
Alt-tab back to Zettlr
Bug: The table is now presented in markdown and not in the pretty mode

## Expected behaviour
The table remains in the pretty mode.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7 beta
 - Screen Resolution: 1920*1080

**Comment by nathanlesage** [comment]
> The table is now presented in markdown and not in the pretty mode

Technical explanation: As soon as you move the focus away from the table editor (also due to focus switching of the windows), the Table editor regards this as an "Exit edit mode". Due to some small quirk in how the plugin itself works you have to trigger one additional cursor movement to re-render the table.

**Comment by sebastienvercammen** [comment]
I don't know if it's related, but:

- Create table, add some text
- Click anywhere outside of the table so it renders the pretty table
- Click inside any of the table cells and make any kind of change (e.g. edit some text)
- Click outside of the table again (but still inside of Zettlr, e.g. in some text above it)

This disables the rendering and turns it into Markdown again.

Clicking again anywhere outside of the table, e.g. in any surrounding text, re-renders the table. Even if you keep clicking outside text, the table render will now stay, at least until I make the next change.

**Comment by nathanlesage** [comment]
> I don't know if it's related

Exactly the bug, yes.

**Comment by sebastienvercammen** [comment]
> Exactly the bug, yes.

The title focused on alt-tab behavior, so I was being attentive. :eyes:

Can we generalize the issue ticket?
