### ISSUE TITLE
[ENHANCEMENT] Only open to new tab when needed

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#743]
## Description

I think it is unneccessary to open every md file to its own tab. I think it would be good to open new tab only when needed.

## Proposed Changes

Only open md file to new tab when (for example) CTRL  + SHIFT + leftclick is pressed, assuming the shortcut combination is available and not used by something else. CTRL + leftclick would use the current tab to open file.
This would be in line with internet browser behavior.

## Caveats

Can not think of any.

**Comment by nathanlesage** [comment]
I'm getting the impression this seems something you all can agree on. But it will take a lot of work to enable this behaviour, so I ask y'all to be patient!

**Comment by BellLongworth** [comment]
Copying my thoughts from the closed ticket:
The logical solution would be to implement a browser-like behavior.

You don't want to invent your own UX just yet ;). It is best to comply to a common design and avoid mix and match.

There are 3 possible designs to choose from:
1. Code editors
2. Browsers
3. Windows file explorer

As code editors were ruled out and Windows file explorer is not something that people interact with nearly as often as browsers, my conclusion at least is that a browser like behavior is best.

**Comment by nathanlesage** [comment]
Transient tabs are now implemented
