### ISSUE TITLE
[FEATURE] Closing tabs with CTRL click, middlebutton click and CTRL + w

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#744]
## Description

Would be nice to have easy ways to close tabs. CTRL + leftclicking tab could be one. Middlebutton clicking the tab could be other. CTRL + w could be third.

## Caveats

Can't think of any.

## Additional Information

This is basic behaviour in internet browsers.

**Comment by nathanlesage** [comment]
Shortcut will come, I just haven't had the time. I wanted to start this beta early on because what is much more important is that the FSAL works (which seems to be the case).

**Comment by nathanlesage** [comment]
Already implemented
