### ISSUE TITLE
[BUG] Renaming file switches focus to previous tab

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#745]
## Description
Renaming file switches focus to previous tab

## Reproducing
Open tab 1
Open tab 2 (appears to the right of tab 1)
Bring tab 2 to focus if it isn't already
Press Ctrl-R and rename tab 2
Bug: The tab that is now in focus is tab 1 

## Expected behaviour
Keep tab 2 in focus

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7 Beta
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Needs a state extension of `fsal._state.openFiles` array, along with a state flag for `activeFile` and a `modificationFlag`/`isDirty`
