### ISSUE TITLE
[BUG] Float numbers values are interpreted as ID in files view

### ISSUE THREAD

**Issue by elkrause** [Zettlr/Zettlr#747]
## Description

I have some location values in my notes and they are taken as ID in the files view.

## Reproducing

Create a new note and enter a floating point number like 9.992848284728239238
You will see that parts of this number are marked green.

## Expected behaviour

No misinterpretation.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53222869/81432273-ef8c6700-9162-11ea-981c-d88a6a0e8d85.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.0 Beta
 - Screen Resolution: 1920x1200

**Comment by nathanlesage** [comment]
This is not a bug, but precisely what it's meant to do. If you don't want such numbers to be detected as your ID, make sure to put the ID of a file at the top of your file. If you don't want an ID to be detected at all, you can either change the ID generator pattern to something more specific than the default, or you could also try encapsulating this in a code block!

**Comment by elkrause** [comment]
Thx for your feedback!
