### ISSUE TITLE
[BUG] Copying images by drag and drop is not working properly

### ISSUE THREAD

**Issue by elkrause** [Zettlr/Zettlr#748]
## Description

> Copying images from the Explorer/Finder/file browser now offers to insert them into the document, copying them over to the assets directory.

It is not working for me. When I drag and drop images from my desktop into Zettlr, there is only a link to the desktop file which will be created.

## Reproducing

Drag and drop any file.

## Expected behaviour
As described in the release notes: The images will be copied to the assets folder with a relative link in the markdown file

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53222869/81432829-e2bc4300-9163-11ea-84fa-5a5a6e5a4038.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.0 beta
 - Screen Resolution: 1920x1200

**Comment by nathanlesage** [comment]
Same here, I was wondering why I'd written that in the Changelog, but fortunately it's just a beta, and not the stable :)

**Comment by nathanlesage** [comment]
Ah, yes, I understand where my error was: "Copying from desktop" can mean two things, and this is precisely what I meant in the Changelog:

1. If you _copy_ the file (e.g. pressing `Cmd/Ctrl+C`), Zettlr will offer you to save the image to the assets folder.
2. If you drag and drop, only a link is created.

This is actually intended behaviour, so if you spot it elsewhere (not just in the changelog) please feel free to offer a revised wording!

**Comment by elkrause** [comment]
1) goes via the clipboard
2) is creating the reference link
OK, understood!
