### ISSUE TITLE
[BUG] Inserting images via clipboard is not working

### ISSUE THREAD

**Issue by elkrause** [Zettlr/Zettlr#749]
## Description

When inserting images via clipboard the dialog to write the file opens. I can chose to write it in the current directory or another directory - it doesn't work. The editor later shows that it can't find the file and the image is not inserted. The images is also not stored in any directory

> Copying images from the Explorer/Finder/file browser now offers to insert them into the document, copying them over to the assets directory.

## Reproducing

Copy image via clipboard into Zettlr

## Expected behaviour

It should save the image under the selected file namen and insert the link into the markdown file

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53222869/81433860-878b5000-9165-11ea-89ce-4bc332ad9e46.png)
![grafik](https://user-images.githubusercontent.com/53222869/81433874-9245e500-9165-11ea-814c-e0458e6747aa.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.0 beta
 - Screen Resolution: 1920x1200

**Comment by nathanlesage** [comment]
There's definitely something off with images in general, but I have so far not been able to pinpoint the issue.
