### ISSUE TITLE
Feature Request: inline file search pop-up when type '[[' to make zettelkasten link.

### ISSUE THREAD

**Issue by ggroh** [Zettlr/Zettlr#75]
Please add feature that inline pop-up when type '[['.
If user type '[[' then
inline pop-up appear and
user can find file with file name or tag in same folder and
select with arrow key and
press return to add zettelkasten link.

If user can select automatic link style, it will be great.
such as,
- [[20181221132730]] Link with only ID
- [[20181221132730 mynote]] Link with full file name

**Comment by nathanlesage** [comment]
Yup, it's coming!

**Comment by nathanlesage** [comment]
Here you go. Testing as always welcome!

**Comment by ggroh** [comment]
> Here you go. Testing as always welcome!

It's great work. Thanks.!!
File searching with not only file name and also tags will be more useful.

**Comment by nathanlesage** [comment]
Searching by tags might indeed be useful! I'll keep it in mind for future versions!
