### ISSUE TITLE
[BUG] Odd double LTR label in preferences

### ISSUE THREAD

**Issue by StefanoCecere** [Zettlr/Zettlr#752]
Version 1.7.0-beta.1 (1.7.0-beta.1) macOS

![Screenshot 2020-05-09 at 00 34 48](https://user-images.githubusercontent.com/640536/81454604-047df000-918d-11ea-8771-3be3d32c34ee.png)

**Comment by nathanlesage** [comment]
Yes, noticed this yesterday as well, but was too tired to fix it. These translations have been giving me some serious headache :D But I fixed it now!
