### ISSUE TITLE
Custom CSS doesn't work in Bordeaux theme

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#754]
## Description

This change appearence of Berlin theme but not Bordeaux
```
#editor { font-family: 'Avenir Next',  'Avenir Next', 'Avenir Next',  sans-serif ; 
}

#editor .cm-header{ 'Avenir Next', serif;font-weight: 400; }
```

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: MacOS
 - Zettlr Version: 1.7.1
 - Screen Resolution:

**Comment by nathanlesage** [comment]
I can remember that I aligned the CSS classes in one of the previous commits so that custom CSS works more consistently with all themes, so maybe `#editor .CodeMirror` may work now…?

**Comment by danieltomasz** [comment]
Your advice doesn't work 
The problem exists only for Bordeaux theme, every other theme is adapting to this custom CSS.

I don't want to open a new Github issue,  but should Frankfurt have a twice bigger font size than other themes?

**Comment by nathanlesage** [comment]
> should Frankfurt have a twice bigger font size than other themes?

A little bit yes, because Garamond is somehow smaller than the other fonts!

**Comment by nathanlesage** [comment]
You know what I just realized?

```
#editor .cm-header{ 'Avenir Next', serif;font-weight: 400; }
```

That's not even CSS 🧐 The `font-family` is missing here! :D 

I've made some changes to the CSS loader, so maybe it works now; in any other case please feel free to bark at me in the Small UX improvements thread! :P
