### ISSUE TITLE
[BUG] Note creation obstructed when unsaved note open

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#755]
## Description
New note creation is sometimes obstructed, if there is another note open that is not yet saved manually. It will simply not create the note, without any error message.

This happens quite frequently because of #738 and might be fixed by fixing that one.

## Platform
 - OS and version: 10.14.4
 - Zettlr Version: 1.7.0 beta 1

**Comment by nathanlesage** [comment]
Yeah, I'm pretty sure there is a `isModified() then return false` somewhere in that algorithm, so I'll pop this into the other issue (lest I'll lose my sanity in the face of all these issues)
