### ISSUE TITLE
[Bug] After changing name of external note Zettlr cannot find it

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#756]
## Description

I opened single note (not in the imported /added folder to Zettle) and then changed its name in Zettlr, Zettlr still displays old note name and keep saying that "The requested file was not found." Additionally, I cannot close this specific note, it only disappears after the restart of the program.
The note name was indeed changed.

## Expected behaviour

**Screenshots**

## Platform
 - OS and version:MacOS
 - Zettlr Version: Zettlr 1.7.1
 - Screen Resolution:

**Comment by nathanlesage** [comment]
> The note name was indeed changed.

Yes, this is something I saw that I overlooked!

**Comment by nathanlesage** [comment]
I'm beginning to like the new FSAL, it's just so much easier to find and resolve bugs and errors 😌

**Comment by danieltomasz** [comment]
This still happening in 1.7.2, this time when for the note in the added dir
The displayed note name doesnt  change & I get "The requested file was not found."  when trying to open

**Comment by danieltomasz** [comment]
After restarting this behaviour disappeared

**Comment by nathanlesage** [comment]
> This still happening in 1.7.2, this time when for the note in the added dir
The displayed note name doesnt change & I get "The requested file was not found." when trying to open

hm? Also I'm not sure if the corresponding patch has already made it into 1.7.0-beta.2 🧐

**Comment by danieltomasz** [comment]
if this is not yet in 1.7.2 it explains much ;P

**Comment by nathanlesage** [comment]
🙃

I think today I'll just drop the current develop branch into yet another beta! (The more betas I release now the sooner SmartScreen will stop annoying Windows users with "Be careful with this software! >:O"-alerts)
