### ISSUE TITLE
[BUG] - Keyboard shortcuts not working

### ISSUE THREAD

**Issue by TheAlmightyDada** [Zettlr/Zettlr#759]
## Description

The shortcuts to focus on the Tree and navigate the tree via the arrow keys are not working.

## Reproducing

Press Ctrl+Alt+T while on the editor.

## Expected behaviour

Shortcut Ctrl+Alt+T should focus on the Tree view and I should be able to navigate files with the arrow keys

Ctrl+Alt+E should focus on the editor. 

## Platform
 - OS and version: Windows 10 Pro; 1903
 - Zettlr Version: 1.6.0

**Comment by nathanlesage** [comment]
> Shortcut Ctrl+Alt+T should focus on the Tree view

This was always working, and never broken

> I should be able to navigate files with the arrow keys

This, however, did not work. I just fixed that!

**Comment by TheAlmightyDada** [comment]
Hi Nathan,

Must be something on my end then?

When I hit "Ctrl + Alt + E" I get this: "é"

When I hit "Ctrl + Alt + T" with the editor in focus, nothing happens.

Thanks for taking a look at the arrows, I am now on the beta 1.7 release.

**Comment by nathanlesage** [comment]
> When I hit "Ctrl + Alt + E" I get this: "é"

Wait a moment … Ctrl+Alt+E? I'm not quite sure if the shortcut wasn't Ctrl+Shift+E…? If the latter works, it's an error in the documentation!

**Comment by TheAlmightyDada** [comment]
I don't think those shortcuts are actually listed in the documentation. I found them while looking at #165 

Thanks for having a look, your efforts have made Zettlr an invaluable tool, day to day.  `Shift + Ctrl + T/E` absolutely do work. 

I'm a little wet behind the ears with FOSS - do I have to wait until the next update for the Up/Down functions?

**Comment by nathanlesage** [comment]
> Shift + Ctrl + T/E absolutely do work.

ah, good to know! If they aren't mentioned in the documentation, please feel free to add them on our documentation repo! :)

And concerning when the functionality is available: If you want to test out the (not completely stable) beta version, there's just a fresh new one on the releases page available! This includes the fix already!

**Comment by esm7** [comment]
Shouldn't this be in 1.7.4? At least for me (under Linux) these shortcuts don't do anything :(

**Comment by cdaven** [comment]
I would like to reopen this, since the keyboard shortcuts Ctrl+Shift+E and Ctrl+Shift+T and F2 doesn't work ON WINDOWS. Not in 1.7.5, not in 1.8.0-beta and not in develop.

`$(document).on('keydown', (event) => ...` just doesn't get triggered. If you read [Electron's tutorial on keyboard shortcuts](https://www.electronjs.org/docs/tutorial/keyboard-shortcuts), the best practise is to use menu items and accelerators. I experimented with that, and it works like a charm. Much simpler, and less code as well.

**Comment by nathanlesage** [comment]
> $(document).on('keydown', (event) => ... just doesn't get triggered.

This is not completely true, but I have fixed the bug, as it interestingly appeared on macOS as well. See my comment on your PR for more info!

**Comment by rafafallo** [comment]
I am using Zettlr 1.8.7 on Ubuntu 20.04, installed as AppImage on a laptop with Latin American keyboard, and Ctrl+0 (Reset zoom), and Ctrl+- (Zoom out) work, but Ctrl+Plus (Zoom in) does not. I have to go to View → Zoom in to accomplish the task.
