### ISSUE TITLE
Glitch when I try to scroll to bottom of preview pane

### ISSUE THREAD

**Issue by corypanshin** [Zettlr/Zettlr#76]
## Should scroll through all names to the end without a problem.

**Screenshots**

## Platform
 - OS: Windows 7 Pro
 - OS Version [e.g. 11]
 - Zettlr Version 1.0.0-beta
 - Screen Resolution 1024 x 768

**Comment by nathanlesage** [comment]
Hey, yeah this is a problem that Clusterize (what I'm using to render long file lists) runs into from time to time. It mostly happens if by some coincidence the list items are not the same size. Is that the case with your files? That some of them aren't the same size as the others?

**Comment by corypanshin** [comment]
The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any other MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- File information -----------
     File:  DEFAULT.BMP
     Date:  19 Nov 2001, 16:00
     Size:  358 bytes.
     Type:  Unknown

**Comment by nathanlesage** [comment]
That is, unfortunately, not helpful.
