### ISSUE TITLE
[ENHANCEMENT] Pin the directory item in the sidebar to the top of the screen

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#763]
## Description

Zettlr does not reorder files in the sidebar when dates has been changed. That might be okay — but when I need to update the order, I usually click "sort ascending" and then "sort descending". My issue is that after the first click, sidebar scroll position is suddenly at the bottom of the list, so I have to scroll it back up to click the same button the second time. I'd like the order to be reversed, but the scroll position stay the same.

## Reproducing

* Open a directory with many files.
* Click on a sorting button.

Affects all platforms and all versions at least since 1.6.0.

**Comment by nathanlesage** [comment]
Well, the sidebar attempts to always keep in view the currently opened file, so this absolutely wanted behaviour, and as the sorting triggers a directory update in the main, renderer has no way of knowing that in this very particular instance it should not do that … I don't really see the necessity of updating here!

**Comment by danieltomasz** [comment]
> Well, the sidebar attempts to always keep in view the currently opened file, so this absolutely wanted behaviour, and as the sorting triggers a directory update in the main, renderer has no way of knowing that in this very particular instance it should not do that … I don't really see the necessity of updating here!

Maybe a solution is a kind of floating bar with the name of the currently open folder file and the possibility to change sorting option? It could on the same height as the tab name in the main body
So the bar could be always there and it would be easy to click

<img width="959" alt="Screenshot 2020-05-11 at 01 23 01" src="https://user-images.githubusercontent.com/7980381/81513073-f911fc80-9325-11ea-9e93-e0ef3e484f7c.png">

Or adding the sorting option to the directories/files view, but pinning them so they will be always visible, more or less inspired by the explorer in VSC editor
<img width="384" alt="Screenshot 2020-05-11 at 01 28 03" src="https://user-images.githubusercontent.com/7980381/81513181-ad138780-9326-11ea-9b15-b04af7293224.png">

**Comment by nathanlesage** [comment]
This would not solve the problem at all, if I understood the problem correctly …

**Comment by danieltomasz** [comment]
Yes indeed, I rather described solution to my   problem ...
I also experience sometimes that after changing order of notes sometimes the is no other way   to easy go back to navigation & I need scroll whole dir

My solution would be detaching navigation settings from the displayed directory view (but this more for Zettlr 2.0 rather than for now :P @nathanlesage  you have more than enough work for now, I would like to help, but I program in 🐍 and don’t know enough us)

**Comment by Zverik** [comment]
Maybe a "scroll to top" button on the sidebar? I've no idea how you manage directories with more than a hundred files in them.

**Comment by nathanlesage** [comment]
> I program in 🐍 and don’t know enough js)

JS is basically the same as Python, only more wild-wild-west-style :D 

> I've no idea how you manage directories with more than a hundred files in them.

By searching for the notes, using the autocomplete feature of the global search. I normally don't scroll through a directory at all, I use the global search for everything … which is why I updated it so heavily in past versions, hehehehe

**Comment by Zverik** [comment]
Okay, so how does the workflow look when the sorting order is "time, ascending"? So that new notes are at the bottom, while the directory item is at the top?

Maybe keep it pinned to the top of the sidebar?..

**Comment by nathanlesage** [comment]
Well yes, we certainly can attempt to pin the open directory at the top of the file list. This should from a purely UX viewpoint be pretty straight forward and not induce any confusion

**Comment by danieltomasz** [comment]
> > I program in 🐍 and don’t know enough js)
> 
> JS is basically the same as Python, only more wild-wild-west-style :D

I would like to learn js and contribute to implementing my ideas, but probably this happens either if I  finish or give up with my PhD :P

**Comment by nathanlesage** [comment]
> but probably this happens either if I finish or give up with my PhD

Welcome to my daily struggle, only with "I can't really start my PhD as long as I have to clean up this excessively active issue list every morning" 😄

**Comment by nathanlesage** [comment]
I have a better idea: Let's move this discussion over to #813, because this will solve this problem as well (I'm currently in the mood for clean-up)
