### ISSUE TITLE
[BUG] Removing a project does not update .ztr-directory

### ISSUE THREAD

**Issue by wgslr** [Zettlr/Zettlr#767]
## Description
Using "Remove project" from the right-click menu of file browser only affects the current Zettlr session - the .ztr-directory file is not updated and restarted Zettlr shows the directory as a project again.

## Reproducing

1. Open a directory
2. Make it a project
3. Print the contents of .ztr-directory
4. Right click the project folder and use "Remove project"
5. Observe project icon disappear in Zettlr
6. Print the contents of .ztr-directory to see it wasn't changed
6. Restart Zettlr to see project markings show up again

## Expected behaviour
Correctly update .ztr-directory to remove project settings.

## Platform
 - OS and version: Arch Linux 5.6.4-arch1-1 x86_64 GNU/Linux
 - Zettlr Version: 1.7.0-beta.2
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Does this still happen in the most recent beta?

**Comment by wgslr** [comment]
> Does this still happen in the most recent beta?

No, it works now :tada:
