### ISSUE TITLE
[BUG] Opening a directory symlink doesn't work and gives contradictory messages

### ISSUE THREAD

**Issue by wgslr** [Zettlr/Zettlr#768]
## Description
Using a symlink to directory as the root directory doesn't work. Popup messages do not explain the reason of failure.

## Reproducing
1.
```bash
$ pwd
/tmp/tmp.HD0js5RHfn
$ mkdir workspace
$ ln -s workspace workspace-ln
```
2. Open path "/tmp/tmp.HD0js5RHfn/workspace-ln" in zettlr
3. No directory is opened, popups appear saying that "Could not open workspace-ln" AND "workspace-ln has been loaded".

## Expected behaviour
Preferably: support opening symlinked directories  
Otherwise: do not show successful-sounding messages ("workspace-ln has been loaded"), ideally provide the exact reason of failure.

**Screenshots**
![contradictory-zettlr](https://user-images.githubusercontent.com/6932414/81508104-48463600-9302-11ea-8818-879a3579910e.png)

## Platform
 - OS and version: Arch Linux 5.6.4-arch1-1 x86_64 GNU/Linux
 - Zettlr Version: 1.7.0-beta.2
 - Screen Resolution: 1920x1080

## Additional information
The same behaviour can be observed in 1.6.0.

**Comment by wgslr** [comment]
Sorry for not paying due to diligence to find out there is already a symlink support issue: #131.
At least my experience described here shows the behavior is the same before and after FSAL refactor.

Close or keep this issue as you see fit, although I think it might be useful for tracking the issue of unclear messages.

**Comment by nathanlesage** [comment]
Symlinks are on the roadmap, but not yet implemented … one thing after another :D they're currently not supposed to work. I'll close this one and close the other one once I add the support finally! :)
