### ISSUE TITLE
[BUG] Log isn't updated

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#774]
## Description

The panel that's opened with "Develop → Open Logs" stops updating in less than a minute.

## Reproducing

* Start Zettlr.
* Do something.
* Wait for 2-3 minutes.
* Do something again.
* Open Develop → Open Logs.
* See that the last actions were not recorded there.

## Expected behaviour

I expected the log to be very large and growing.

For example, 12:42:00 app started, last line was from 12:42:48. Just now I've restarted Zettlr. First and last lines:

```
[17:15:59]	こんにちは！　Booting Zettlr at Mon May 11 2020 17:15:59 GMT+0300 (Moscow Standard Time).
[17:15:59]	Electron reports ready state. Instantiating main process...
...
[17:16:17]	>>> IPC IN: file-modified
[17:16:17]	Trying to run command through Application: file-modified
[17:16:17]	No command registered with the application for command file-modified
```
Even though it's 17:18 already, and I've opened few notes and edited a saved them a few times after that.

## Platform
 - OS and version: macOS 10.14.5
 - Zettlr Version: 1.7.0-beta2

**Comment by nathanlesage** [comment]
Did I read your latest comment right that it somehow works again in the new beta …?

**Comment by Zverik** [comment]
Nope, that was a single occurence. Right now logs on both Linux and macOS display only the first minute.

**Comment by nathanlesage** [comment]
Alright … if you have time to look into it, it would be awesome, otherwise we can postpone it by a week or so to get to other bugs first!

P.S.: Just check the written log files – if everything is in there it's not a problem with the logger, but only with the log window!

**Comment by Zverik** [comment]
Do you know where can I find the log files on macOS?

**Comment by nathanlesage** [comment]
Yes, they're basically where the config is (`/Users/<name</Library/Application Support/Zettlr/logs`); Zettlr keeps 30 logfiles at maximum

**Comment by Zverik** [comment]
Thanks, I see these. This morning I've pressed Cmd+S, and immediately got the notification. In the log there was a single line:

    [11:09:43] [Info] Chokidar has detected a change event for file what-i-saved.md. Attempting to re-parse ...

**Comment by Zverik** [comment]
Regarding logs: could you please switch logging levels, so that the file log gets all "debug" messages, while the in-app log gets only "info" and above? I believe that should help find important messages in UI, while the text file can be searched, and debug messages in it won't be an issue.

**Comment by nathanlesage** [comment]
I understand what you mean; I'll have to rework the whole logging window either way, including filters to simply hide all the verbose messages. I haven't gotten to do that yet, though …

**Comment by nathanlesage** [comment]
Bonjour; still happening on the 1.8.x-branch?

**Comment by nathanlesage** [comment]
Finally completely overhauled the log viewer, fixed now.
