### ISSUE TITLE
bar with tab name   not displayed properly [if more than x tabs open]

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#777]
## Description

If there is more than 4 tabs open (but its depends how wide the window is) , the tab (closest to sidebar) is never properly displayed
<img width="691" alt="Screenshot 2020-05-13 00 24 47" src="https://user-images.githubusercontent.com/7980381/81751769-5f2a8b00-94b0-11ea-930e-0bff098de511.png">

Or this is done on purpose, to let the user know that he/she has more tabs than he/she see?

## Expected behaviour
Don't showing this 1/4 tabs? Users don't have access to all tabs (chrome-like) anyway, and having this "partial tab" doesn't help with anything

**Screenshots**

## Platform
 - OS and version:
 - Zettlr Version:
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Well, you can scroll left and right to get to all of the tabs, basically this is something I copied over from other code editors … any suggestions on how to make this plain and simple are welcome

**Comment by danieltomasz** [comment]
> Well, you can scroll left and right to get to all of the tabs, basically this is something I copied over from other code editors … any suggestions on how to make this plain and simple are welcome

Obviously there is a need to shorten the note title, VSC has the same solution

I will not propose any advanced solution but if a bar with the title is shorter than 1-2 cm (and have only two letters and  closing "x" visible)maybe it just simply shouldn't be displayed - it's more like UX consideration; so displaying rather 4 cards/tabs rather than "4 and 1/5 card"

But maybe currently implemented solution has this advantage that more tabs are accessible at the same moment...

What could help - the folder-like view of the opened tabs in the sidebar (also inspired by VSC code), 
but  maybe for one of future releases, for 1.7 is too much to think

**Comment by nathanlesage** [comment]
> Also clicking on the "mini tab bar with 2 characters" doesn't extend this tab-bar when I edit related note

This is because I haven't yet found a good way of how to "scroll" this thing into view, sadly … :D This is still ToDo

> it's more like UX consideration; so displaying rather 4 cards/tabs rather than "4 and 1/5 card"

I absolutely understand where you're going with this. The current implementation is basically first and foremost focused on ensuring this will work on all screen resolutions and window sizes, as I deemed this more important than the nuances of making the tab feature even better! But yes, there's a lot of room for improvement, and I think once the FSAL stuff is done I have more mental capacities to tend to those fine details of a nice implementation :)

**Comment by nathanlesage** [comment]
Let's do this in the #799 as it's basically the same issue: We need to add some visual hint that the tab bar is actually horizontally scrollable
