### ISSUE TITLE
[CSS/bug] unfocused  selection  is unreadable on dark mode 

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#779]
## Description

Dark mode use the same grey colour as "normal mode" when the note is unfocused

![image](https://user-images.githubusercontent.com/7980381/81754190-d0b90800-94b5-11ea-8d08-82b99b23e55a.png)

## Reproducing
* Setting dark theme
* select fragment of a text
* open another note
* come back to the previous note

## Expected behaviour
`Body.dark` has a different colour set to this selection t in dark mode, so the text is visible
I would try to do it myself, but I don't know the name of CSS object

BTW which CSS class is related to this yellow highlight of the result of the search?

**Screenshots**

## Platform
 - OS and version:  MacOS Catlina
 - Zettlr Version: 1.7.1
 - Screen Resolution:

**Comment by nathanlesage** [comment]
This is some rule in CodeMirror.css that I've found no time to find and fix yet. Basically it should consist of one line.

**Comment by nathanlesage** [comment]
> BTW which CSS class is related to this yellow highlight of the result of the search?

afaik `.search-result`
