### ISSUE TITLE
[Enhancement/Gui] Card with longer names in Preferences too tight

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#780]
The  titles of cards  with longer names are too tight, when the app window is 1/2 or 1/4 of the screen
<img width="675" alt="Screenshot 2020-05-13 02 08 11" src="https://user-images.githubusercontent.com/7980381/81757320-cbac8680-94be-11ea-8263-2042a64eec47.png">

## Description
maybe adding some " invisible box" around titles would help

**Comment by nathanlesage** [comment]
Padding should suffice, I'll look into it.

**Comment by nathanlesage** [comment]
Ah, already did this, tadaaaa!
