### ISSUE TITLE
[enhancement] possibility to remove/rename note with right click on the note title bar

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#782]
## Description
Going to the sidebar  to delete/rename note cause losing focus, additionaly when notes are in search view, there are more additional clicks; right click action could allow for "pining the note" when it will be implemented too or any additional action

**Comment by nathanlesage** [comment]
Certainly something good, but has to come at a later point! If someone wants to get hands on, please feel free to open up a PR with all of these additional things that are not yet implemented.
