### ISSUE TITLE
Indented checkboxes are breaking upon checking / unchecking

### ISSUE THREAD

**Issue by timtody** [Zettlr/Zettlr#784]
Indented checkboxes are behvaving unexpectedly up after multiple checking / unchecking cycles.

## Reproducing

![image](https://user-images.githubusercontent.com/23238268/81793699-07b90900-950a-11ea-8827-45cb4895a6ac.png)

![image](https://user-images.githubusercontent.com/23238268/81793735-130c3480-950a-11ea-8581-1a583fd0e247.png)

![image](https://user-images.githubusercontent.com/23238268/81793758-1b646f80-950a-11ea-9059-5d16bbdbe5a3.png)

![image](https://user-images.githubusercontent.com/23238268/81793787-23241400-950a-11ea-8fb8-e64f2f75274c.png)

## Expected behaviour
The checkboxes should
1.) keep their indentation as specified when creating
2.) do not produce additional markup i.e. "[ ]" as seen in the third image

**Screenshots**

## Platform
 - OS and version: Linux (Ubuntu 20.04)
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Keeping an eye out for this, but if anyone wants to get hands-on, don't wait for me, simply look here: https://github.com/Zettlr/Zettlr/blob/develop/source/renderer/assets/codemirror/zettlr-plugin-render-tasks.js

PRs welcome of course!

**Comment by timtody** [comment]
I would love to help, but I'm not a JS expert and this would be my first contribution ever. I'm going to have a look if I can make sense of it during the weekend.

**Comment by nathanlesage** [comment]
No need to rush, and it should be fairly easy. What you'd need to look up potentially is the documentation on CodeMirror plugins (as it is such a plugin)! Thanks for having a look!

**Comment by nathanlesage** [comment]
There you go, new beta will be coming this evening.
