### ISSUE TITLE
[ENHANCEMENT] add to GitHub Desktop-App "External-Editor"

### ISSUE THREAD

**Issue by jochmann** [Zettlr/Zettlr#785]
##  Description

As I try to use Version Control for my notes I would like to open Zettlr from within GitHub Desktop App as my editor of choice.

## Proposed Changes

Edit Zettlr capabilites as outlined in GitHub Docs for editor integration: <https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md>

## Caveats

May be out of scope and add unwanted complexity to the UI if the requirements of incorporating a command-line interface are too strict?

## Additional Information

May be a helpful stepping stone in incorporating Version Control as a concept more closely into the user experience.

**Comment by nathanlesage** [comment]
Zettlr does support manually adding files to open by attaching them as command line arguments, see for this the logic here: 

https://github.com/Zettlr/Zettlr/blob/67a7afcb1bd07ea7ae134eca80a49373c23dfed7/source/main.js#L87-L118

Everything else is — as of now — out of scope. But feel free to check back at a later time. If the flood of issues is ebbing away, there's more time to ponder about additional further integration!
