### ISSUE TITLE
[Enhancement] UX small  enhancements  request thread

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#786]
Instead of creating every time new issues to the horror of @nathanlesage  I will put here inconsistencies I noticed or small things that could improve workflow with the app

### Design/UX update
1. [UX]  Rename file/note bubble is too narrow, it doesn't display the full name of the note

###  Enhancements
2. [Enhancement] it is possible to trigger rename bubble centred on a note in sidebar view? when using rename right-click option on the note

3. ~~[enhancement] Open plain https link with alt. In this moment Zettlr open links only when in Markdown tags [1.7.2]~~

6. ~~Add "Open directory [in file manager]"  option when right-clicking on the directory in the sidebar~~

7. When moving files between directories and files exist add an option to ask if overwrite (with info which file is later edited)

### General/ possible bugs
4. Zettlr doesn't remember the width of the sidebar when restarted, every time I need to resize it (Zettlr 1.7.2)

5. ~~"New virtual directory" still as an option when clicking on a folder in the sidebar. As I understood the possibility to create virtual dir has bee removed in this release? Choosing this option it doesn't do anything anyway~~

**Comment by nathanlesage** [comment]
> Instead of creating every time new issues to the horror of @nathanlesage

❤️

**Comment by danieltomasz** [comment]
5.  "New virtual directory" still as an option when clicking on a folder in the sidebar. As I understood the possibility to create virt dir has bee removed in this release?

**Comment by nathanlesage** [comment]
someone also mentioned (while we're at UX) to enable dark styling of the dialogs. Just did that:

![image](https://user-images.githubusercontent.com/17251683/81818126-e833d780-952d-11ea-8274-7087fea1772a.png)

Virtual directory thingy is also gone in three, two …

**Comment by danieltomasz** [comment]
When the Zettlr window size is smaller than The Preferences Pane, the preferences pane start apperaring in different part of the screen when changing different Preferences tab

<img width="992" alt="image" src="https://user-images.githubusercontent.com/7980381/83328578-47ab1a80-a284-11ea-800e-9f3dba23e1b7.png">
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/7980381/83328585-57c2fa00-a284-11ea-8c3b-ee29a1b4e1a2.png">

<img width="992" alt="image" src="https://user-images.githubusercontent.com/7980381/83328614-8ccf4c80-a284-11ea-928f-063fd399e93e.png">

This is caused by the tab trying to  "fit" into current  window size, but this doesn't create good consistent user experience (this is my subjective opinion).

Zettlr 1.6 doesn't have this kind of behaviour, the window doesn't change where it start, and in my opinion, it was better behaviour

**Comment by danieltomasz** [comment]
Path to my  bibliography file disappeared when I updated.
 
Button to add CSL JSON file with bibliography doesnt work on Mac, but adding  path manually works.

**Comment by nathanlesage** [comment]
Here's how currently the algorithm works (calculations are made after the dialog window is displayed and then whenever the window is being resized):

1. Check the height of the dialog window
2. Is it bigger than the available window height? Then apply a margin top+bottom and make it scrollable
3. If not, apply a top-margin half of the available additional (unused) window so that the window stays centered.

This means that there is this small margin after which the dialog will suddenly "jump", but this should only happen if you are actively resizing the window.

Feel free to make suggestions.

> Button to add CSL JSON file with bibliography doesnt work on Mac, but adding path manually works.

This has nothing to do with UX enhancement, so please make an issue out of that, as I will have to look into that!

**Comment by danieltomasz** [comment]
"Jumpy" behaviour is only in specific "border" conditions;

> Feel free to make suggestions.

he solution that I could come really fast -
1.  Before opening get the height of all tabs, and the height of the dialogue window should be the max of all tabs
2. If the height of the dialog window is  bigger, create scroll (as in you recipe)
3. They say there is no free dinners, instead of jumping windows  the problem now will  be that for some tabs there will be much free space at the bottom


Sorry about the button, I was lazy to open a new issue, and I see it as a small thing

**Comment by danieltomasz** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/7980381/83550638-7258d580-a507-11ea-931c-36a8ba6b1173.png">

1. Too much space between header (when documents start) and the bar 
 This is especially bad when Zettlr has small font (its actually the same amount always, I would like an option to remove much of that space)
2. The ability to scale sidebar font too (maybe as an option in settings)

**Comment by nathanlesage** [comment]
hmhmhmhm …

To your first point: We could definitely see if we can find a solution that reduces the margin a little bit — but don't forget that this might boil down to taste! And concerning sidebar: I would like to only keep the editor zooming in/out — for the rest there's custom CSS!

**Comment by danieltomasz** [comment]
Yes this is subjective matter :)

**Comment by bmocanu** [comment]
To the point of editor zooming in and out, may I suggest an improvement: for my taste, the default font size is a bit too large. I saw that I can make the entire text smaller (headings and all) by Ctrl+'-' (on Windows) and Ctrl+Shift+'+'. However, this size is not persisted between restarts. Could you please add an option in the settings for the relative text size, which can also be synced with the editor resizing via commands? Thanks.

**Comment by doup** [comment]
Hi! I just recently found about your project and I must say it's an impressive app, tons of features and is working great so far. So, I've been toying around, and I noticed few UX issues, I've listed them below. I hope you appreciate the feedback.

I might try running the project on my machine to fix the issues. Meanwhile I list them here for reference:

### Remove gap between toolbar buttons
- This will increase the hit area and (hopefully) make the buttons easier to access
![image](https://user-images.githubusercontent.com/188612/86497745-28bc0e80-bd83-11ea-8f75-adfd2a3f994c.png)

### Search field improvements
- Increase clear find filter hit area
- Hide `x` when there is no filter applied
- Change `x` color on hover
![image](https://user-images.githubusercontent.com/188612/86497826-6f116d80-bd83-11ea-98c8-7759eac3f491.png)

### Toggle popover
- On the top toolbar, if an icon opens a popover, a second click should close the popover
![image](https://user-images.githubusercontent.com/188612/86497945-e6470180-bd83-11ea-999e-8ee3fb6811d9.png)

### Change BG color on hover on stats and pomodoro buttons
- For consistency with the other toolbar buttons, when hovering these two I would change the bg color
![image](https://user-images.githubusercontent.com/188612/86497999-2c03ca00-bd84-11ea-97c4-238cae9cb66c.png)

### Directories column improvements
- Increase contrast
- Improve tree hierarchy readability
![image](https://user-images.githubusercontent.com/188612/86498149-c19f5980-bd84-11ea-9d24-bb3c8e9ee092.png)

### File/documents list
- Margins & alignment adjustments
![image](https://user-images.githubusercontent.com/188612/86498219-31154900-bd85-11ea-812b-71da260cbc66.png)

### Sort file/documents
- Increase hit area
- Add tooltip explaining action
![image](https://user-images.githubusercontent.com/188612/86498308-9406e000-bd85-11ea-8dc8-28fc246ff628.png)

### File tabs
- Increase height
- Add border to visually separate unselected tabs
![image](https://user-images.githubusercontent.com/188612/86498392-f5c74a00-bd85-11ea-8b29-5f11831cb1a6.png)

### Improve section controls
- Make 🔽 toggle arrow hit-area bigger, ideally arriving the left margin
- Change 🔽 color on hover
- Increase 🔽 and header-size button hit-area, keep width, change size to match `line-height`, vertical-align center the text
![image](https://user-images.githubusercontent.com/188612/86498754-ab46cd00-bd87-11ea-8c2c-5adf83b70e5d.png)

### Don't vertically center settings modal
- I would put the modal to X% or px from the top to avoid the UI jumps when changing tabs
![screencast 2020-07-03 23-49-43](https://user-images.githubusercontent.com/188612/86498891-37f18b00-bd88-11ea-9c66-804ee93fe14a.gif)

### Modal buttons tweaks
- Keep consistent padding for buttons
- Increase buttons size
![image](https://user-images.githubusercontent.com/188612/86498979-d382fb80-bd88-11ea-9d42-8651b98f1d0c.png)

### Vertically center reset setting button icon
![image](https://user-images.githubusercontent.com/188612/86499048-3bd1dd00-bd89-11ea-81cb-534eca887d10.png)

**Comment by nathanlesage** [comment]
Thanks for the review! That's a lot of stuff, and you surely are right that the whole UI can actually use a good makeover. I'll be having a look into your PR asap!

**Comment by crbald** [comment]
I'd like to add to doups already very thorough suggestion list, specifically the tree hierarchy in the directory column part (also for the combined sidebar mode with files).

I find that the indentations of folders with and without subfolders/arrows, icons, and file names seem a bit inconsistent and I often get confused which folder/file is a subfolder/-file of another.
doup already mentioned this for sibling folders with subfolders/arrows and those without.
![TreeProblems](https://user-images.githubusercontent.com/68776321/88456598-03e92180-ce7f-11ea-8f87-961ed357bd0e.png)


My suggestion would be to have subfiles/folders and their icons at least as indented as the parent folder and to have sibling files and folders (with and without subfolder arrows or icons) have the same text indentation. The icons could also maybe have a bit more distance to the filename.

![TreeSuggestions](https://user-images.githubusercontent.com/68776321/88456022-ae127a80-ce7a-11ea-9d7e-204b0d016907.png)

As you can see this would eat a bit more horizontal space with each new sublevel but (in my opinion) would make it clearer which file/folder is a subitem of which folder.

![Comparison](https://user-images.githubusercontent.com/68776321/88456408-ed8e9600-ce7d-11ea-9fac-a8080f9c3de2.gif)

**Comment by doup** [comment]
Sorry for disappearing. I won't work on these issues as I'm going to use other solution (VS Code probably) to manage my markdown notes. Good luck and I hope the best for the project!

**Comment by nathanlesage** [comment]
@doup No worries, but thank you very much for communicating this fact, as this helps us to move on. I really appreciate this!

**Comment by nathanlesage** [comment]
Just cleaned up the file tree display, it's now all neatly aligned with each other:

![image](https://user-images.githubusercontent.com/17251683/90239780-656e3180-de28-11ea-97fd-a28224c4c63d.png)

**Comment by stevenfang1997** [comment]
It would be nice if there is a setting for setting up default font size in the editor. For me the default font is too large and I have to change the font size every time when I launch the app.

**Comment by nathanlesage** [comment]
> It would be nice if there is a setting for setting up default font size in the editor. For me the default font is too large and I have to change the font size every time when I launch the app.

Please use [Custom CSS](https://docs.zettlr.com/en/core/custom-css/) for this.

**Comment by yashha** [comment]
It would be good to have an option to be able to auto-hide the menu bar and just show it using the alt key. Esp. for Linux it is useful.

**Comment by TBiele** [comment]
One thing that I would like to see is a change to the section collapse controls. It constantly happens to me that I want to click into the beginning of a line but accidentally collapse the section instead. Maybe the hit box could be moved to the left or it could be confined to the arrow icon.

**Comment by nathanlesage** [comment]
@TBiele This has already been fixed and will be included in the next release.

**Comment by nathanlesage** [comment]
Gonna close this issue finally, a few remaining things have been opened in separate issues; but if something comes up, feel free to create new issues!
