### ISSUE TITLE
[bug] cannot close note if file is moved externally (in file manager)

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#788]
## Description
After moving file in file manager  the note stays open and cannot be closed
```Could not close file! No file with hash -1588692697 found!```
This may be related to this issue

https://github.com/Zettlr/Zettlr/issues/756

If this is solved, but not realeased yet @nathanlesage  fell free to close

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: MacOS
 - Zettlr Version:1.7.2
 - Screen Resolution:

**Comment by nathanlesage** [comment]
I'm pretty sure it hasn't been fixed
