### ISSUE TITLE
[bug] cannot enable debug mode 

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#789]
## Description

After enabling debug mode nothing change in app menu, also shortcut cmd +alt + i don't work. After restarting ` View-> Toggle developer tools` option  is visible only first 5 sec and then disappears

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: MacOs
 - Zettlr Version: 1.7.2
 - Screen Resolution:

**Comment by nathanlesage** [comment]
… what the heck? 🤨

**Comment by danieltomasz** [comment]
> … what the heck? 🤨 [cannot reproduce here …]

After reinstall app the problem is gone, issue solved

**Comment by nathanlesage** [comment]
Curious … please keep an eye out for additional errors like this, because normally this should have nothing to do with reinstalling! But glad it worked this time!
