### ISSUE TITLE
[bug] tag cloud displays only subset of tags +  recently edited tags

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#792]
## Description

First of all recent beta is beautiful!

I have problem with the tag cloud, it displays only a subset of tags +  recently edited tags.
I have tags in my old notes, they appear only when cut and paste a tag in the file.

After restart the recently edited tags dissaeaper from the tag cloud, only the same subset of old tags as before is visible again

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: MacOS Catalina
 - Zettlr Version: 1.7.4
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Please check again with the new beta, because I remember doing *something* to the tags, and I think this might have fixed it!

**Comment by danieltomasz** [comment]
Yes, now it shows all tags!

**Comment by nathanlesage** [comment]
:)
