### ISSUE TITLE
Beta 1.7.4 Attachments do not display

### ISSUE THREAD

**Issue by EcoFin** [Zettlr/Zettlr#794]
When I clilck the "attachcments" paperclip, nothing appears:

But in fact, there are several png files in that directory.  If I click on the file folder beside the "Attachments" I get a popup file explorer window that does show the files.  But that is not the expected behaviour in versions 1.6 or 1.7.1.

![image](https://user-images.githubusercontent.com/7763730/81878738-f1856a00-9556-11ea-9b4c-0cadec9e6942.png)

**Comment by nathanlesage** [comment]
Could be related to the error throwings I already reported over at #790

**Comment by EcoFin** [comment]
Hendrick,

 

I don’t think so because the attachment list displayed normally in beta 1.7.1.  But certainly overall 1.7.4 is much better with the different icons

 

ay

**Comment by nathanlesage** [comment]
> I don’t think so because the attachment list displayed normally in beta 1.7.1.

Well, but the icon set was introduced in beta 1.7.0-3 ;)

I'm gonna close this, Wieke is already informed. If it doesn't solve in a later beta, just let me know!
