### ISSUE TITLE
Attachments sidebar

### ISSUE THREAD

**Issue by henrique9i** [Zettlr/Zettlr#797]
## Description
The attachment sidebar has stopped displaying files and references are not updating. If I click on a note with references, it displays normally, but if I click on another note without references it does not update, it continues showing from the other note.

## Platform
 - OS and version: Win10 64bits
 - Zettlr Version: 1.7.0-beta.4
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
@Wieke fyi, maybe you remember something like this; I'll also have a look at this! But yes, there's clearly something wrong with the attachments. I'll be closing this issue in favour of #794, if that's alright?
