### ISSUE TITLE
Dollar signs ($) inside different code environments (`) rendered as a math equation

### ISSUE THREAD

**Issue by hojjatabdollahi** [Zettlr/Zettlr#798]
## Description
Dollar signs ($) inside different code environments (`) rendered as a math equation. So, all the text between the two code environment are rendered like a formula.

## Reproducing
To reproduce you can use this code:
`` You can replace `$(cat file)`  with the following which is faster `$(<file)` ``

## Expected behaviour
If the $ is in different code environments they should be rendered as $s. 

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/2222199/81969360-13283500-95db-11ea-9ab6-1a1254d1d7ae.png)

## Platform
 - OS and version: Ubuntu 18.04
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920x1080

**Comment by Zverik** [comment]
Even worse, converting everything between `$` to math equations does not allow writing something like "Expected $40, got $50". Dollar signs must be escaped now, and that is a serious issue for taking notes.

**Comment by nathanlesage** [comment]
> "Expected $40, got $50".

What? Ah damnit, there was a PR that was supposed to improve the behaviour but I suspected as much 😠 

I'll see to this … please feel free to provide some easily copy&pastable text that I can use for testing out that it works again!

**Comment by Zverik** [comment]
For me the issue with raw texts was with dollar amounts. Everything else, including Perl variables and escaping, goes into code blocks (the subject of this issue).

**Comment by nathanlesage** [comment]
Yeah but in both cases this shouldn't happen.

Actually, Zettlr should render pretty much the same as Pandoc in that matter, and if raw text isn't displayed properly, we certainly missed this target.

However, what I'm suspecting is that there's something that makes this pretty difficult to achieve: If I understand OP correctly, he means inline-codes. However, inline-code does not switch modes. The rendering plugins only check for different modes (and in code blocks the modes are different) but are unaware of these inline codes. I could make this, but I'm very hesitant, as querying the token names (e.g. code in this case) takes a lot of time and actually slows down the whole rendering process noticably. This is why I've removed that from some other plugins already. There's always the need for a balance between speed and comfort, and using Electron there's some ceiling. Maybe CodeMirror 6 solves this, but we'd have to wait for this ...
