### ISSUE TITLE
[BUG] Tabs are not closed on the first click in the latest develop branch

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#801]
## Description

I click once — nothing happens. Second time is the charm. Reproducible for me.

Console log:
```
+++++ SYNCING OPEN FILES WITH RENDERER +++++
FIle dungeonworld.md is now closed
Closing file ...
FSAL state changed: openFiles
+++++ SYNCING OPEN FILES WITH RENDERER +++++
FIle dungeonworld.md is now closed
FSAL state changed: activeFile
```

In-app log:
```
[10:16:24]	>>> IPC IN: file-close
hash: 1956154630
[10:16:24]	Trying to run command through Application: file-close
[10:16:24]	<<< IPC OUT: sync-files
0: -222181579
1: -770056756
2: 1956154630
3: -770056756
[10:16:24]	<<< IPC OUT: config-update
[10:16:34]	>>> IPC IN: file-close
hash: 1956154630
[10:16:34]	Trying to run command through Application: file-close
[10:16:34]	<<< IPC OUT: sync-files
0: -222181579
1: -770056756
2: -770056756
[10:16:34]	<<< IPC OUT: config-update
```

## Reproducing

* git merge upstream; yarn install; yarn start
* close a tab
* close the tab again

## Platform
 - OS and version: Fedora Linux 32
 - Zettlr Version: 1.7.0-beta4 built from source just now

**Comment by nathanlesage** [comment]
It works for me, but I've noticed that not all tabs close immediately … I'm not sure but maybe this has to do with the new icons … just testing this …

**Comment by nathanlesage** [comment]
Alright, short update: The file is closed everywhere except the editor, and the events are firing just as they should …

And it also happens on the very first close intent …

**Comment by nathanlesage** [comment]
Just found out that adding a `console.log` as the first line in the `_onClick`-handler in the `editor-tabs.js` fixes this bug consistently with the same start-states 🙂🔫

**Comment by nathanlesage** [comment]
Does this work now, or still something buggy?

**Comment by nathanlesage** [comment]
> Not immediately, but it is that way after some time.

Ah-hah! 🧐

Looks like some buffer is filling up quite fast. But I had to do some performance tests either way, because the performance of the current state is like terrible :D 

(btw if some of you just casually wanna do some performance analysis with regard to the whole new file/tab-stuff, feel free; the more bottlenecks (= functions that take something like > 200ms to run) we find, the better)

**Comment by nathanlesage** [comment]
Has it been fixed?

**Comment by Zverik** [comment]
I don't think so: just restarted Zettlr from the develop branch, and had to click twice on a closing button.

**Comment by nathanlesage** [comment]
Dammit, but thanks for the notice!
