### ISSUE TITLE
[Enhancement] Navigation with arrow keys

### ISSUE THREAD

**Issue by Amar0ks** [Zettlr/Zettlr#804]
## Description
So that notes or Zettel can be looked through quickly

## Proposed Changes
Make it possible to navigate with arrow keys.
Just a small adjustment I guess. 

A quick back and forth within the folder structure would also be great.
Similar to the browser.

**Comment by nathanlesage** [comment]
Already works, you simply need to focus the file list (achieve this by using `Cmd/Ctrl+Shift+T`). Then navigating works with the Arrow keys and optionally `Alt/Option` and `Cmd/Ctrl` as modifiers (see [the shortcut section](https://www.zettlr.com/shortcuts) on the website)

**Comment by Amar0ks** [comment]
Well then this doesn't work for me. Neither on windows or macos.

On Windows the focus goes out of the writing window. However navigating does not work.
On Macos the directory will get closed using cmd shift T. At least I get the message in the sidebar that no directory is selected.

Or does that only work with 1.7?

**Comment by nathanlesage** [comment]
> However navigating does not work.

Ah, right. Small addendum: I accidentally broke it in 1.6, but it's already working in the current betas, and henceforth will work in 1.7!
