### ISSUE TITLE
Latex templates

### ISSUE THREAD

**Issue by tormodb** [Zettlr/Zettlr#805]
Thanks for developing such a great program! Are you aware of the software `R` and IDE Rstudio? They integrate statistical analyses with markdown to produce manuscripts weaving code and prose. I have been using one package `rticles` that uses latex templates to format markdown according to format requirements for different publications/academic journals. Could such templates be used within zettlr to format exports? It is all pandoc based conversion, using yaml to format title page etc, so it could perhaps be compatible? Check out the repo of `rticles` here if you are curious: https://github.com/rstudio/rticles/tree/master/inst/rmarkdown/templates

**Comment by nathanlesage** [comment]
> Are you aware of the software R and IDE Rstudio?

Being a quantitative social scientist myself, yes, I do. Albeit I'm more prone to Python as I find R somewhat counter-intuitive ;) Zettlr also includes support for RMarkdown files.

I've just had a look, and if you convert these classes to templates, or build templates that build upon these classes, you can do exactly what you're requesting! Albeit Zettlr does not offer automated conversion etc. (out of scope) — but as long as you point Zettlr to a custom TeX template in the preferences, it should work!

If you have further questions regarding Zettlr's Pandoc/TeX-support, feel free to head over to our [forum](https://forum.zettlr.com/)!
