### ISSUE TITLE
[ENHANCEMENT] Incremental Search, or at least Option to turn off autocomplete

### ISSUE THREAD

**Issue by alpcantal** [Zettlr/Zettlr#807]
## Description

Hi, I've been using Zettlr for a couple of months now and I'm planning to use it for a very long time. Overall, I think it's a great app both for writing and knowledge management. (I even used the same CSS of my blog for the enhanced writing experience + some pandoc changes) I believe this can become even better when an option for autocomplete in the search can be turned off, or better yet, an incremental search like in The Archive.

## Proposed Changes
An incremental search option would be nice, although I think that might bring some difficulties due to the heatmapping. But if it's possible, (even at the cost of using a regular file tree) then there's no more I could ask for.

Concessively, I request at least the option to remove the autocompletion feature in the search. I speculate that other users would want that, too, to streamline their workflow.

**Comment by nathanlesage** [comment]
Hey, I've just added some more things to make the autocomplete fully inobstrusive — so now the most you'd have to do to turn it off is simply press backspace once you're done typing in your search. I figure this is much easier than having to go through the whole process of generating a new preferences option, which does take a lot of time. I understand that in 1.6 the autocomplete feature could be somewhat nasty, but I can promise it's not obstrusive anymore.

**Comment by nathanlesage** [comment]
As I've made several adjustments to how the search gets triggered, I'll consider this issue closed for now. If, after 1.7, there's something off, feel free to comment again!
