### ISSUE TITLE
[enhancement] Add option to save when closing app

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#808]
When closing Zettlw with tabs with unsaved content there is only two options,
* Proceed without saving
* Cancel

but it's lacking the most obvious in this case - save all changes.

**Comment by danieltomasz** [comment]
Also is the info is weird (duplicated the same note_:

"
There are unsaved changes. The following files have been modified:

- 20200307174221 Macbook apps.md
- 20200307174221 Macbook apps.md

Do you want to omit these changes?

"

When I have many notes opened there is no way to finding the one with changes without closing all the rest

**Comment by nathanlesage** [comment]
Looks like yet another thing to deal with. The "save all" option is missing because I haven't reimplemented it. It's quite difficult with more than one open file.

**Comment by nathanlesage** [comment]
Does it work in the new beta? In the meanwhile I heavily improved on the state management so the main process should now be able to save all the files if any are modified, if I didn't forget something!

**Comment by danieltomasz** [comment]
No, it still only two options "cancel" and "proceed without saving"

**Comment by nathanlesage** [comment]
Argh, dammit …
