### ISSUE TITLE
 [ENHANCEMENT] Folding for YAML Frontmatter and HTML Comments (by default)

### ISSUE THREAD

**Issue by taubmann** [Zettlr/Zettlr#811]
ATM the YAML Frontmatter block and HTML Comments are not foldable. Because especially the YAML Frontmatter could occupy a lot of the visible Area when opening a File it is quite distracting if you just want to concentrate on writing. In addition it would be perfect to define that/witch Elements are folded by default.

**Comment by nathanlesage** [comment]
> HTML Comments

These should be foldable. YAML frontmatter I can see how this helps.

**Comment by taubmann** [comment]
<img width="230" alt="Bildschirmfoto 2020-05-16 um 23 16 09" src="https://user-images.githubusercontent.com/1518022/82130398-50531980-97cb-11ea-8ac4-2d3e6553b3f8.png">
AFAIK Folding for HTML Comments disappeared in 1.6. (Mac)

**Comment by nathanlesage** [comment]
> AFAIK Folding for HTML Comments disappeared in 1.6. (Mac)

That sounds like a bug

**Comment by taubmann** [comment]
ok, I will create a separate Issue for that

**Comment by nathanlesage** [comment]
HTML comments work again, concerning YAML, I have no idea how to do this, but I'll try to have a shot at this …

**Comment by nathanlesage** [comment]
Totally forgot about this issue, works in 1.7.4
