### ISSUE TITLE
[ENHANCEMENT] Allow for automatic relative paths on images drag&drop

### ISSUE THREAD

**Issue by yhancik** [Zettlr/Zettlr#812]
## Description
Inserting an image by drag&drop automatically creates an absolute path.
It'd be great to have an option to choose whether we want to insert the image with an absolute or relative path.

## Proposed Changes
This could be done in two ways (possibly both):
- globally in the settings: "On image insert use: _relative path | absolute path_"
    - an additional setting could be "ask me every time"
    - this could be applied to copied-pasted images (save-image-from-clipboard.js seems to do such a check line 49?)
- and/or every time we insert an image, through a dialogue (as pasting an image does)

This would bring some consistency in the automatically created image links, because right now, depending on the method, I either get relative or absolute links.

**Comment by nathanlesage** [comment]
Bonjour, I just tested it out and for me it returns an absolute path in any case — could you describe which kind of drag and drop (from the sidebar, the finder, etc.) you make, so that I can try to reproduce this behaviour? Thanks!

**Comment by yhancik** [comment]
Yes it does return an absolute path! 

It's not a bug report, but a proposal: to have an option somewhere that allows us to choose whether we want image tags created from a drag & drop to be 1. Absolute or 2. Relative.

(maybe "depending on the method" was confusing - I meant that copy-paste creates relative links, while drag & drop creates absolute links ;))

**Comment by nathanlesage** [comment]
Aaaaaaahh, now I see what you mean! Yeah, this should be fairly simple, and in fact, it's exactly the same process as for the one feature I implemented during the screencap I uploaded recently: https://www.youtube.com/watch?v=sa_ehm0yDEo&t=1738s

So if someone wants to have a shot at implementing a switch to toggle between absolute and relative paths (relative to the file), this should be fairly simple to do and I know there are people who want to get involved more :)

**Comment by nathanlesage** [comment]
Hush, stalebot! Hush!

**Comment by nathanlesage** [comment]
Right now, image links are always relative to the document, so there's no more inconsistency. Image paths will be transformed to absolute whenever needed (i.e. export).

**Comment by yhancik** [comment]
Uhm, I feel I'm being a pain in the ass with this but it has never been the case for me in 2.0.x (on Windows).

Dragging images from the sidebar or from desktop into Zettlr always create an absolute, backslashed path .__.
Only pasting an image from clipboard creates a relative path for me.

Am I missing something? :/

**Comment by nathanlesage** [comment]
> Uhm, I feel I'm being a pain in the ass with this but it has never been the case for me in 2.0.x (on Windows).

Yes, but not in the upcoming 2.1, which is why I closed it :D Tested it out on the most recent develop, and it works fine! So you can either try out a nightly or wait for 2.1 :)

**Comment by yhancik** [comment]
Ohhhh my bad, and sorry for rereopening it then. Eager to test it later ;)
