### ISSUE TITLE
HTML Preview dosen't recognize Headings Level 2 and below

### ISSUE THREAD

**Issue by taubmann** [Zettlr/Zettlr#815]
## Description
The normal HTML Preview seems to ignore Headings rendering p-Tags instead of h-tags. H1 is rendered correct.

**Screenshots**
<img width="207" alt="Bildschirmfoto 2020-05-17 um 06 09 36" src="https://user-images.githubusercontent.com/1518022/82135654-5e259080-9805-11ea-8ad2-642ab006ff45.png">
<img width="395" alt="Bildschirmfoto 2020-05-17 um 06 09 20" src="https://user-images.githubusercontent.com/1518022/82135656-64b40800-9805-11ea-8b04-74ca8b8aa38a.png">

## Platform
 - OS and version: Mac OS 10.14.6
 - Zettlr Version: 1.7 Beta 5

**Comment by nathanlesage** [comment]
This doesn't look like an error on Zettlr's side, but rather showdown or Pandoc (depending)
