### ISSUE TITLE
[DISCUSSION/ENHANCEMENT] Switch Code Formatting Button Behaviour from Inline to Block Code

### ISSUE THREAD

**Issue by tiotrom** [Zettlr/Zettlr#816]
To put it simply, I'd love to see a button for fenced blocks. I think it makes sense. What do you think?

**Comment by nathanlesage** [comment]
… a button? I can't imagine this right now, what do you mean?

**Comment by tiotrom** [comment]
Like here
![image](https://user-images.githubusercontent.com/34804533/82262520-58dd5880-9961-11ea-8f1e-231c9fc9054b.png)
I find code blocks a lot better than the simple "code" that is line by line. At times you may have a lot of code into one document, and fencing it is a lot more handy I'd say.

**Comment by nathanlesage** [comment]
Ah so simply a way to add them easily? Where do you imagine this button should occur as well?

**Comment by tiotrom** [comment]
I'd pesonally say to replace the "code" button with the fenced code one. For example here in github the "code" button is fencing the code. And in many other places I've seen the code block acting similarly. 

To show you a very quick example. This is the default in Zettlr:
![image](https://user-images.githubusercontent.com/34804533/82317573-c4a9da80-99ce-11ea-8fa2-f8457399452f.png)

And this is how fenced code looks like:
![image](https://user-images.githubusercontent.com/34804533/82317633-e1461280-99ce-11ea-81c9-fa19e604ea37.png)


In my view it is much easier to deal with fenced code, especially when you have a lot of it. Or multiple chunks of it.

**Comment by tiotrom** [comment]
To make my point better understood, observe how in the code bellow many of the parts of teh code are not even highlighted as code, alongside the sign for the code block " ` " and that makes it confusing thinking that some of those bits do not belong to the code
![image](https://user-images.githubusercontent.com/34804533/82317984-67625900-99cf-11ea-9dda-588b13180080.png)

**Comment by nathanlesage** [comment]
Ah, I see! Let's see if others concur that we should change the behaviour of that button!

**Comment by danieltomasz** [comment]
+ 1 for fenced code
