### ISSUE TITLE
Ability to disable tabs

### ISSUE THREAD

**Issue by tiotrom** [Zettlr/Zettlr#817]
I am sure tabs are very useful, but there isn't a way to disable them. Would you mind adding this feature for those who do not use them? Thanks!

**Comment by ploum** [comment]
Adding my vote here as the new tab behaviour makes Zettlr completely unusable. It's confusing when using Zettlr and, to add insult to injury, it makes Zettlr slower and slower with every file I visit without any obvious solution but clicking to close each tab (which takes approximately 2 seconds for each tab)

**Comment by Sklanfurt** [comment]
Upvote! I can see how others could benefit from it but for me the tab feature just replicates the file tree on the left side and is therefore useless.

**Comment by nathanlesage** [comment]
As Zettlr's tab behavior is now much better and more predictable, I'm going to close the issue.
