### ISSUE TITLE
cursor keep coming back to the beginning of text

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#822]
## Description
The cursor is keep on coming back to the beginning of the text.

## Reproducing
There are two ways of reproducing this behaviour:
1. Rename a batch of files, and trying to write in one of the renamed file.
2. To let zettlr work in the background (while doing something in other apps), and somehow the cursor is already moved to the beginning of the text. 

## Expected behaviour
The cursor stayed where it supposed to be, both when I'm in the course of typing or when I do something in the background.

**Screenshots**

## Platform
 - OS and version: Windows 10, Intel(R) core(TM) i5 8250U CPU @ 1.60GHz 1.80 Ghz.
 - Zettlr Version: v1.7.0-beta.5
 - Screen Resolution: 1366 x 768

**Comment by nathanlesage** [comment]
Just to get your problem clearly:

1. You have files opened in Zettlr.
2. You rename them in the background (which is what I read implied by "batch")
3. You wonder why the cursor is at the beginning of the file?

**Comment by TheAlmightyDada** [comment]
This is happening for me also. No batch renaming going on, on my side. If I open Zettlr, edit a md file and wait for it to autosave the cursor jumps to the top again.

For me, it's the same problem as #773. Files are synced to cloud (Onedrive)

**Comment by nathanlesage** [comment]
hmhm … it almost looks like OneDrive is the common root cause (but that still doesn't answer the why and how, though …)

**Comment by TheAlmightyDada** [comment]
Seems so, files in a local directory do not have the same issue, and disconnecting from the internet stops unwanted behavior on files that are cloud-synced.

**Comment by nathanlesage** [comment]
Alright. I actually experienced this today as well with a way too huge Markdown file (> 10,000 words). So it seems like an edge case for local files, and maybe a problem with OneDrive … :S

**Comment by anoel-hub** [comment]
Hello, yes same bug for me,  Windows 10 ver1809 x64 and files synched with OneDrive. Thx for the redirection from 841 Nathan.

**Comment by shanvrolijk** [comment]
sorry for coming back so late. I use dropbox to save all my zettlr files. So, maybe that's the root of the problem

**Comment by TimMoser92** [comment]
This bug also occurs regularly on my MacOS system. Without large files, background renaming or any synchronization services running. There might be other background processes watching the files for changes, but without modifying them.

**Comment by nathanlesage** [comment]
Yeah, I'm getting more of these problems myself, I'm currently suspecting some weird hiccup processes running in the application somewhere, but the spaghetti code has currently too much tomato sauce on it to navigate it properly!

**Comment by TimMoser92** [comment]
No problem, I still like the software and am grateful for it's concept. Just wanted to add the suspicion, that it might not have to do with Cloud Sync alone :)

**Comment by jinxremoving** [comment]
Hitting this as well - seems like a combination of cloud sync and the General | Always load remote changes to the current file setting. Disabling this setting causes the reload dialog to pop every time the cursor would be returned to the start of the document - still annoying, but helpful in determining when it is happening.

Pausing synchronization of cloud sync eliminated the problem for me.

**Comment by nathanlesage** [comment]
Cursor is now retained as close as possible — for potential other issues see #746
