### ISSUE TITLE
Periodic Javascript failure alert

### ISSUE THREAD

**Issue by gonditeniz** [Zettlr/Zettlr#823]
## Description
While having Zettlr open for taking notes, a Javascript error alert periodically appears. This alert appears both while typing in a note or having just the application open in background.

## Reproducing
Just having the application open for some time.

## Expected behaviour
Not received that Javascript alert at any moment.

**Screenshots**
![image](https://user-images.githubusercontent.com/773516/82313326-7bef2300-99c8-11ea-9900-11545bab3383.png)

## Platform
 - OS and version: Windows 10 Version 1809 (OS Build 17763.1158)
 - Zettlr Version: 1.6.0
 - Screen Resolution: 2560x1440

## Additional information
The alert complains about different filenames:
- hiberfil.sys
- pagefile.sys

I cannot find any of those file in my filesystem.

**Comment by nathanlesage** [comment]
… do you happen to have your `C:\`-directory loaded into Zettlr? Like, the file system root?

**Comment by gonditeniz** [comment]
No, I don't have that directory loaded.

I have a directory called `zettelkasten` in my `Documents` folder. I load subfolders of the `zettelkasten` directory in Zettlr.

**Comment by nathanlesage** [comment]
This is super weird because Zettlr accesses neither the hibernation nor the paging file on Windows setups, and I've heard that just now for the first time. I'm actually at a loss trying to explain why it would run an `lstat` on either of these files. Add to this the missing stack trace of the JavaScript error which makes locating the source impossible :/

So let's see if someone else knows something about this!

**Comment by gonditeniz** [comment]
Could it be a third-party library is doing it for some reason? Is there a way of enabling a debug mode so that I can get more information to share here?

**Comment by nathanlesage** [comment]
> Could it be a third-party library is doing it for some reason?

That was my initial thought, but I couldn't find the file name in any of the dependencies, so it seems to be an accidental function call on either of these … but yes, you can activate a debug mode in Preferences -> Advanced, and then what will be helpful is to search the logs (Menu: Develop -> Open Logs) if there's anything helpful in there after this error occurs!

**Comment by gonditeniz** [comment]
I enabled the debug mode and restarted the application (close and open it). I waited for the error to appear and I open the logs.

Below are the logs since I restarted the app. Nothing relevant as far as I can see.

`[15:33:02]	Trying to run command through Application: win-menu
[15:33:02]	No command registered with the application for command win-menu
[15:33:02]	The translation string was malformed: Open Logs!
[15:33:07]	>>> IPC IN: win-menu
{ 'x': 15, 'y': 15 }
[15:33:07]	Trying to run command through Application: win-menu
[15:33:07]	No command registered with the application for command win-menu
[15:33:07]	The translation string was malformed: Open Logs!`

**Comment by nathanlesage** [comment]
Indeed, nothing wrong — does uninstalling the application, clearing the user data (I believe `C:\Users\<username>\AppData\Roaming\Zettlr`, but it's outlined in the docs) and re-installing help?

**Comment by gonditeniz** [comment]
Reinstallation didn't solve the issue.

Regarding the user data directory. I cannot find even the `AppData` one. Could it be related to that?

**Comment by nathanlesage** [comment]
> Regarding the user data directory. I cannot find even the AppData one. Could it be related to that?

It's a hidden directory, maybe your Windows Explorer doesn't show it…? I can't imagine a Windows installation working without that directory, or?!

**Comment by gonditeniz** [comment]
It is a windows image created by my company with some restrictions. I'm not sure if that could be the reason for that or if the information stored in that directory could be in a different place.

**Comment by nathanlesage** [comment]
Hmmm … might be? Depending on what restrictions are in place that might probably the cause, but I'm not really sure. I try not to touch anything outside of Electron in order to prevent such problems for as long as possible …

**Comment by MyGGaN** [comment]
Running Zettlr 1.7.1 get popups for those files (and in this order):
C:\DumpStack.log.tmp, C:\hiberfil.sys, C:\pagefile.sys, C:\swapfile.sys

**Comment by MatthiasMerk** [comment]
Same here with Zettlr 1.7.2 except its c:\{hiberfil,pagefile,swapfile}.sys
User Profile (ie .md files) are stored on a Network Share.

**Comment by passar** [comment]
Zettlr 1.7.4

I get the following errors periodicaly:
* C:\hiberfil.sys
* C:\pagefile.sys
* C:\swapfile.sys

Windows 10.
The software is distributed through my workplaces central admin.
My home folder is mounted seamlessly in some way and reachable as c: and a \\drive\users\my_username.

If it helps I had the IT department package Zettlr, pandoc and the other optional requirements 2019 because policies in our environment do not let you install any software yourself even if an admin logs in to your computer.
This was not an issue in early versions.
I have not kept any notes on it because I was just so happy to be able to use Zettlr at work. The problem started coming after I asked them to update in ether 1.4.3 in November 2019 or 1.5 in January 2020.


## Things that I have tried
I have tried to remove the zettlr folder in the C:\Users\my_username\AppData\Roaming\zettlr but it does not help.

Hibernation is disabled by default, so I do not understand why javascript ever would need to write anything to hiberfil.sys.
I have tried to turn it on but there seems to be no change.

**Comment by nathanlesage** [comment]
> Hibernation is disabled by default, so I do not understand why javascript ever would need to write anything to hiberfil.sys.

Neither do I; I still assume this is some form of misconfiguration, but I am at a complete loss as to why this happens. Zettlr's code itself never even attempts to read anything like that to begin with, so it might be an error with the Electron binary itself. Especially given that it's the three system-files that Windows makes use of for certain features, and not different files.

**Comment by ZeroBomb** [comment]
From my searching on the duplicate thread:

> 
> Suspiciously similar error, indicates possible problem with imports if using VScode? Or if Zettlr uses chokidar, problem may come from there?
> 
> https://stackoverflow.com/questions/61936085/error-from-chokidar-c-error-ebusy-resource-busy-or-locked-lstat-c-dump
> https://stackoverflow.com/questions/61988518/error-ebusy-resource-busy-or-locked-lstat-c-hiberfil-sys-c-pagefile-sy
> 
> Obsolete Autocomplete-Paths may trigger this?
> atom-community/autocomplete-paths#29

I suspect that something Zettlr depends on is trying to get metadata from files in the wrong place (perhaps it defaults to "root" which gets interpreted as C:\ on windows), and gets denied by the file permissions on those particular system files.

@canpolat seemed to think Zettlr uses chokidar, so take a look at the first stackoverflow link.

**Comment by nathanlesage** [comment]
I will have a look, but this would be bad if *some* Dependency does this, because these error messages contain no clue at all

**Comment by nathanlesage** [comment]
Is this still happening on the latest 1.8.0-alpha?

**Comment by MatthiasMerk** [comment]
> 
> 
> Is this still happening on the latest 1.8.0-alpha?
@nathanlesage been running the  latest 1.8.0-alpha for a few hours now and no error messages have appeared. On previous versions they would appear almost immediately after startup.

**Comment by nathanlesage** [comment]
Perfect! If anything changes, just comment! In the meantime I'll consider this solved :)
