### ISSUE TITLE
ID and tag recognition gone at every start of the app

### ISSUE THREAD

**Issue by IulekShi** [Zettlr/Zettlr#824]
At every start of the app, no ID nor tag of the notes are recognized. 
As soon as the notes is edited, even if slightly, ID and tags are correctly recognized after a few seconds.
Meanwhile, if a note hasn't been edited since the last start of the app, creating a new internal link to that note in another note will correctly preview the notes, but the [[filename]] will be inserted, not the [[ID]].
On the contrary, if that note has been edited since the last start of Zettlr, and so its ID and tags have been correctly recognized again, everything works fine.

What still always works: manually copying and pasting the ID of the note, previous internal links with [[ID]], and alt-clicking. 

**Screenshots**
<img width="364" alt="image" src="https://user-images.githubusercontent.com/55080372/82347253-b02e0800-99f7-11ea-8cdf-4c1f6adf85cc.png">

In the image, some notes have been edited and are showing ID and tag number in the file details (deleting and rewriting a character anywhere in the text is enough).
Besides: if you edit a note while something is in the search field (cmd+shift+F), ID and tags will not show in the file details until you erase the search field and start another search.

## Platform
 - OS and version: macOS Catalina 10.15.4
 - Zettlr Version: 1.7 beta5
 - Screen Resolution: 2560 x 1600

**Comment by nathanlesage** [comment]
> As soon as the notes is edited, even if slightly, ID and tags are correctly recognized after a few seconds.

I have experienced the same, and in the current develop build (plus, importantly, as I found out, clearing the cache) solves the problem for me, so let's wait for the next beta to appear, and then please clear the cache (in the user data folder simply remove the whole `fsal` subdirectory) and check again if the problem persists. I'm not sure when the next beta will come but I think at least Friday!

**Comment by IulekShi** [comment]
thanks!
deleting the `\"user"\Library\Application Support\zettlr\fsal` folder solves the problem for me too.

I'll wait for the next beta when it's ready, thanks again!

**Comment by nathanlesage** [comment]
Simple solution: Zettlr simply didn't cache anything when changes were made, so no wonder all this stuff was gone when the files were read from the (outdated) cache 🙄
