### ISSUE TITLE
[BUG] Table Rendering - Escaped Pipe Character

### ISSUE THREAD

**Issue by 0x01BM** [Zettlr/Zettlr#825]
## Description
Any table with an escaped pipe character `\|` will not display. It will remain in markdown format and the table editor will not recognise it.

### Broken Table
```markdown
| Text            | Problem? |
| --------------- | -------- |
| test *&@?/12314* | no       |
| escaped pipe \| | yes      |
```
 ### Working Table
```markdown
| Text            | Problem? |
| --------------- | -------- |
| test *&@?/12314* | no       |
| blank    | no     |
```

## Expected Behaviour
The table editor should be able to recognise and handle an escaped pipe character.

## Platform
 - OS and version: Win10
 - Zettlr Version: 1.6
 - Screen Resolution: Irrelevant for the issue, however it is present on the following: 2560x1080 (landscape), 3840x2160 (landscape) and 1920x1080 (portrait).

Thank you very much for all your hard work with this fantastic tool and engagement on various platforms, very much appreciated 👍 😄

**Comment by nathanlesage** [comment]
> Screen Resolution: Irrelevant for the issue, however it is present on the following: 2560x1080 (landscape), 3840x2160 (landscape) and 1920x1080 (portrait).

Yes, indeed, the placeholder is only there for quick insertion in case it's relevant … but let's be honest 99% of the issues don't require it 😄 

This sounds pretty much like a fix is needed in the table rendering CodeMirror plugin! I'll have a look
