### ISSUE TITLE
Render markup into TABLES

### ISSUE THREAD

**Issue by sjewson** [Zettlr/Zettlr#826]
## Description
I used a text template pre BETA 1.7.0-beta.5 that looks like this - 
http://prntscr.com/skyrl9

I updated to beta 1.7.0-beta.5 and now in the header region my markup has been replaced by a TABLE that looks like this ..
http://prntscr.com/skzkue

So the new beta update has replaced the header markup (between the 2 rows of ***) into a table format that I dont want

## Reproducing
I updated from previous Zettlr to version 1.7.0.-beta.5

## Expected behaviour
nothing....should NOT change my template which is below

# ID

***
ID:
Tags: # # #
Date: 21.05.2020  (21 May 2020)
***

**Screenshots**
![beta foramt](https://user-images.githubusercontent.com/2188641/82546605-a53eb900-9b58-11ea-9ca2-17a5e4e708cc.jpg)
![pre beta](https://user-images.githubusercontent.com/2188641/82546606-a5d74f80-9b58-11ea-8e52-9c5ce32e608b.jpg)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.0 beta.5
 - Screen Resolution: 1920 x 1080

**Comment by nathanlesage** [comment]
I just tried this out but unfortunately I cannot reproduce this behaviour locally :/

Would you mind copying and pasting the exact Markdown that makes it look like this within a Markdown code-block here in the issue so that I have the code?

**Comment by sjewson** [comment]
Forgive me if this is not a code block as Im unsure how to do that :/

`# Tiny Assets Engine

***
ID:[[20200522140943]]
Tags: #avatar #questions #client
Date: 22.05.2020  (22 May 2020)

***`

This would then render into the below i.e. cut ALL ending characters off past first 3 characters and add table borders

# Tiny Assets Engine

ID:
Tag
Dat

![image](https://user-images.githubusercontent.com/2188641/82724565-42276080-9cd7-11ea-8c93-94be872b024d.png)

**Comment by sjewson** [comment]
Hi Ive added a link to a ZIP which contains one Zettel. This is the exact markup that will reproduce the error in latest version of Zettlr.

[https://drive.google.com/file/d/1dBVUrq6cOEZ_Q1h6aP7R8X3lKoA3xLSH/view?usp=sharing](url)
