### ISSUE TITLE
"&" not allowed in the authors of a project

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#828]
Zettlr 1.6 on MacOS:

1. In the parameters of a project, add multiple authors with "&"  (like "Alice & Bob")
2. Try to expot that project to PDF
3. Latex fails…

Error producing PDF.
! Extra alignment tab has been changed to \cr.
<recently read> \endtemplate 
                             
l.165 \pagebreak

**Comment by nathanlesage** [comment]
Oh boy, you hit the 20: Two bugs in one!

1. the cool `sanitizeTexValues` did not, in fact, sanitize values for the TeX document
2. Even if it did, the current beta would have not altered any PDF property except the title

**Comment by ploum** [comment]
Fastest non-trivial fix ever!
