### ISSUE TITLE
[BUG] Zettlr v1.7.0-beta.6 doesn't open well - just a white screen

### ISSUE THREAD

**Issue by elkrause** [Zettlr/Zettlr#829]
## Description

I have installed Zettlr v1.7.0-beta.6 and it does not open. Only a white windows appears.

## Reproducing

I had all previous betas installed and deinstalled Zettlr completely again and restartet Windows. Even after a fresh installation the problem is still there.

## Expected behaviour

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53222869/82729069-c805d480-9cf4-11ea-8570-4bac02bb7a07.png)

## Platform
 - OS and version: Windwos 10
 - Zettlr Version: Zettlr v1.7.0-beta.6
 - Screen Resolution: 1920x1200

**Comment by vtcarlino** [comment]
Same problem here on macOS Mojave 10.14.6. Restarted my computer didn't solve anything either.

**Comment by nathanlesage** [comment]
Just a second; I'm on it …

**Comment by danieltomasz** [comment]
I am confirming this on my Mac 10.15.4

**Comment by nathanlesage** [comment]
Okay, I have no idea what is happening, the renderer is spitting out an error in a `node_modules` dependency that is not even existing in the codebase o_O

![image](https://user-images.githubusercontent.com/17251683/82729237-28494600-9cf6-11ea-92f3-8d348058e036.png)

I'll keep on going, but I'm a little bit confused as to what is happening, as the build logs look perfectly fine

**Comment by danieltomasz** [comment]
maybe this is a node style component error? https://github.com/styled-components/styled-components/issues/2907

**Comment by nathanlesage** [comment]
Hm, I have no idea … but I found that the Workflow action for build actually had an older command running, I'm going to try it this time and download the binary to test it now, maybe that was the cause … please feel free to continue googling during this! :D

**Comment by lemonballoons** [comment]
Also confirmed on my Mac 10.15.4, still present after a reinstall and restart.

**Comment by nathanlesage** [comment]
@lemonballoons Don't worry, we don't need new confirmations, it's pretty clear the whole build malfunctions :(

**Comment by nathanlesage** [comment]
Quick update: Building a full release locally doesn't exhibit that bug, so I hope that the recent change to the workflow will fix it for the CI as well … I currently assume it has to do something with how `npm` differs in building from `yarn` …

**Comment by nathanlesage** [comment]
Build run complete, just quickly checking this locally …

**Comment by nathanlesage** [comment]
Alright, apparently it was the `npm install` in the workflow file — releasing the `beta.7` right away!

**Comment by elkrause** [comment]
Works now with Beta 7 - thanks for fixing it so fast!
