### ISSUE TITLE
[BUG] File name is not added when autocompleting links

### ISSUE THREAD

**Issue by wgslr** [Zettlr/Zettlr#831]
## Description

The setting "When linking files, add the filename... always" has no effect.

## Reproducing

1. Start creating a link with open brackets `[[`.
2. Select one of the suggested notes
3. Confirm the selection with TAB
4. The note ID is inserted, but the cursor remains just after the ID, before the closing `]]` bracket and target file name is not inserted.

## Expected behaviour
Add the title of linked note after the link.

## Screenshots
![image](https://user-images.githubusercontent.com/6932414/82730310-f5f01680-9cfe-11ea-87c8-676e2372610a.png)

![image](https://user-images.githubusercontent.com/6932414/82730314-f7b9da00-9cfe-11ea-89d8-f0746ece7611.png)

## Platform
- OS and version: Arch Linux 5.6.11-arch1-1 x86_64 GNU/Linux
- Zettlr Version: 1.7.0-beta.7
- Screen Resolution: 2560x1440

## Additional information

- My ID regex: `(\d{4}-\d{2}-\d{2}N\d{6})`
- My ID generation pattern: `%Y-%M-%DN%h%m%s`

**Comment by shotazi** [comment]
I have the same problem in Mac OS.

**Comment by nathanlesage** [comment]
Please check the relation of this bug with #819 and close this issue if it's a duplicate, because I strongly think so.

**Comment by wgslr** [comment]
Perhaps it's related, but I don't think it is the same bug. In #819, the autocomplete suggestions don't appear at all. I have experienced this as well. But when the autocomplete does appear, only note ID is filled in and note the name of the target note, and that's the subject of this issue.

**Comment by Raphapere** [comment]
I am having exactly this same problem.

![Peek 27-05-2020 21-28](https://user-images.githubusercontent.com/20495934/83085122-5ebdf280-a061-11ea-9c37-b2872177a9ad.gif)

Zettler 1.7.0-beta.7
