### ISSUE TITLE
[BUG] Cannot close  external file when it is opened in editor tab 

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#832]
## Description

Closing the external file in the sidebar is not possible when this file is opened in the editor  (even if not currently active & only opened as a tab)

## Expected behaviour
Choosing right-click menu sidebar action "Close file" should remove the file from the sidebar (under files) and close file in the editor

**Screenshots**

## Platform
 - OS and version: MacOS
 - Zettlr Version: 1.7beta7
 - Screen Resolution:

**Comment by danieltomasz** [comment]
Also, I have problem with closing the directories, when I have added directory and subdirectory (as different items), I cannot close subdirectory until I close another directory (but this is not consistent behaviour, most times it works)

**Comment by nathanlesage** [comment]
All hail the bughunt! 🙌🏼

> I cannot close subdirectory until I close another directory (but this is not consistent behaviour, most times it works)

Please monitor this, because this doesn't look *that* cool! :)
