### ISSUE TITLE
Windows Defender detects trojan in installer

### ISSUE THREAD

**Issue by kjaquier** [Zettlr/Zettlr#836]
## Description

Windows Defender detects trojan `Win32/Fuery.C!cl` in installer executable and blocks the execution.

Would be good to know if I'm the only one to get this :)

## Reproducing

Install fails on Windows 10 using either the installer or Chocolatey. Apparently blocked by Windows Defender. 

Scanning the file (or looking at Protection Log) reveals the following threat detected in the installer .exe file: `Trojan:Win32/Fuery.C!cl`

## Expected behaviour

Install should succeed. No malware should be detected (better if because there is none).

## Platform
 - OS and version: Windows 10 Pro 1909
 - Zettlr Version: 1.6.0

## Additional information

N/A

**Comment by nathanlesage** [comment]
There were problems with a Latvian (?) antivir-company, whose (AI) model is still under development, but Microsoft apparently decided to integrate its results anyway. Obviously, as long as the installer comes from here (or the official site, which also only downloads from the repository) there is no trojan or something else in there. We've already gotten in touch with the company that promised to update its models; but there is nothing more we can do at this point. Please use the search function to search for the older issue where all of this has been discussed in length!

**Comment by kjaquier** [comment]
Alright thanks!
