### ISSUE TITLE
[BUG] Sidebar does not display any attachments

### ISSUE THREAD

**Issue by henrique9i** [Zettlr/Zettlr#837]
## Description
You asked me to let you know if it wasn't fixed in a later version, I'm here!
![Zettlr_20-05-24-17_371x228](https://user-images.githubusercontent.com/62220974/82765332-42fde680-9dec-11ea-83f1-7fd3cef45810.png)

**Comment by nathanlesage** [comment]
Huh …? Please be so kind and provide some context, I am afraid I don't recall what issue you are referring to!

**Comment by henrique9i** [comment]
The attachment sidebar is not showing any file, just that

**Comment by henrique9i** [comment]
I found the old issue link https://github.com/Zettlr/Zettlr/issues/794

**Comment by nathanlesage** [comment]
@Wieke Were you able so far to have another look at the loader …? Or is this issue unrelated to this? If the latter, I'll try to get to it at the end of the week!

**Comment by Wieke** [comment]
I think so, it's the whole withFileType issue. I just pushed the fix to my [clarity-icons](https://github.com/Wieke/Zettlr/tree/clarity-icons) branch. Do you want me to open a new pull request?

**Comment by danieltomasz** [comment]
1.7.BWT doesn't display citation  items mentioned in the text of the note

**Comment by nathanlesage** [comment]
@Wieke Yeah, sure, if it fixes this this'll certainly help!

@danieltomasz I factored out that whole bibiography stuff from the editor file, so bugs are expected. One I already know of is that it does not include simply citekeys without a "well-formed" citation, plus I'm still unsure whether the performance is good …

**Comment by danieltomasz** [comment]
I don't have a problem with including cite keys...
Before there was also a possibility to open pdf linked to the citation...
Now, because the bibliography disappears from the sidebar, this is gone too...

**Comment by nathanlesage** [comment]
> Before there was also a possibility to open pdf linked to the citation...
> Now, because the bibliography disappears from the sidebar, this is gone too...

What. That shouldn't even be linked o_O

**Comment by danieltomasz** [comment]
![image](https://user-images.githubusercontent.com/7980381/83202067-1416a600-a147-11ea-8b2f-e0c4015b56fa.png)
Open attachment actually still working  - it will open pdf from Zotero library ...
What is gone is possibility to ctrl + click to open (or other combination of keys), but maybe this was newer there, but I remember that I often opened the pdf by clicking on the link...

@nathanlesage, This was (and still is) the killer feature to me! :P

**Comment by nathanlesage** [comment]
> What is gone is the possibility to ctrl + click to open (or other combination of keys, I don't remember exactly), but maybe this was never there, but I remember that I often opened the pdf by somehow clicking on the link...

I don't remember this being a feature … shall we add that to the keyboard shortcuts (as it basically is one, iirc)? 🧐

**Comment by danieltomasz** [comment]
It's weird.... I tried 1.6 and combination of clicking + any key doesn't work...
Its should be not in the priority list (only if this will be useful for you too )

**Comment by manisabri** [comment]
If I run zettlr with `yarn start` I can see the files in attachments but if I build it ( yarn build:this or ...) and install it or run the unpacked release it wont show the files. Any ideas? (on ubuntu 20.04)

**Comment by danieltomasz** [comment]
In Zettlr 1.7.beta10 Zettlr still doesn't display added references

**Comment by nathanlesage** [comment]
The reference thing is a problem that they're not always updated, I'll have a look at the weekend or so!

**Comment by IpeTek** [comment]
> 
> 
> In Zettlr 1.7.beta10 Zettlr still doesn't display added references

In my case attachment bar shows some previously added citations, but none of the most recently added ones. beta11.

**Comment by nathanlesage** [comment]
> In my case attachment bar shows some previously added citations, but none of the most recently added ones. beta11 on Win10.

I just fixed that yesterday evening
