### ISSUE TITLE
[ENHANCEMENT] Drag & drop notes from search result panel to directory folders

### ISSUE THREAD

**Issue by b4nn** [Zettlr/Zettlr#838]
## Description
I would love to be able to easily move the notes with drag & drop from the search results file list into one of my existing subdirectories displayed in the file tree. Not being able to do it negates an important use case of using search.

Currently to be able to move the notes I searched for is a very cumbersome process. I need to locate the notes manually, which can be too hard to do when dealing with many notes. My current workaround is to right-click on the note in the search results panel, click 'show file' and then outside of Zettlr in the system file explorer I can move the note to a new subdirectory.

## Additional Information
 This functionality actually already exists when viewing all your notes without activating search.

**Comment by nathanlesage** [comment]
Basically this should be one single switch. I may be wrong here, but it sounds both reasonable and easy to implement
