### ISSUE TITLE
[BUG] The new shortcuts don't work

### ISSUE THREAD

**Issue by b4nn** [Zettlr/Zettlr#841]
## Description
The following shortcuts don't work:
"- Changed Cmd/Ctrl+W: Now closes open tabs first, before closing the main window
New shortcuts: Switch tabs (Ctrl+Tab and Ctrl+Shift+Tab)"

## Reproducing
1. Open multiple tabs
2. Try switching or closing the tabs with the new shortcuts

## Platform
- Zettlr Version: v1.7.0-beta.7
- System: win32 10.0.18362 (architecture: x64)

**Comment by nathanlesage** [comment]
… what do they do instead?

(btw, Cmd/Ctrl+W currently ALWAYS attempts to close tabs first even if there's other windows in focus as I found out, so it requires some more work)

**Comment by b4nn** [comment]
Sorry Hendrik, I should have said they don't work at all, so nothing happens.

**Comment by anoel-hub** [comment]
Hello b4nn, i work half Mac,, half windows and with Windows 10 ver1809 x64 i have the same problem. 

I have another problem but I don't know if it's my laptop or zettlr. If I type a word, autosave is activated and the character cursor goes back to the beginning of the document. Have you observed this type of behavior? Thx

**Comment by b4nn** [comment]
hi @anoel-hub, I haven't got that particular issue but it sure sounds strange. You can consider adding it as a separate issue to help Hendrik keep an eye on it and see if anyone else have got it.

**Comment by nathanlesage** [comment]
> If I type a word, autosave is activated and the character cursor goes back to the beginning of the document

See for that this issue: #822

**Comment by BellLongworth** [comment]
Windows 10 here, CTRL W/tan/alt-tab shortcuts not working at all as well.

**Comment by nathanlesage** [comment]
There'll be a new beta today, please feel free to check them! I'll have a final look at the shortcuts today but I'm not sure whether or not I'll find something …

**Comment by wgslr** [comment]
I have the same issue, now in beta.8 and in earlier betas as well: ctrl+w, ctrl+shift+w, ctrl+tab, ctrl+shift+tab have absolutely no effect.

Zettlr Version: v1.7.0-beta.8
System: linux 5.6.14-arch1-1 (architecture: x64)

**Comment by nathanlesage** [comment]
This almost sounds as if there's an error in the Electron configuration o_O Damnit, I need a test system here, I'm basically flying blind when it comes to non-macOS platforms …

**Comment by nathanlesage** [comment]
… how about the new beta?

**Comment by nabusch** [comment]
I am using the most recent 1.7.0-beta.9 on a windows 10 PC. I still have the same issue: CTRL+W, CTRL+tab, CTRL+Shift+tab have no effect.

However, CTRL+click on an internal link correctly opens the linked note in a new tab, so it is not that the app generally disregards CTRL.

**Comment by nathanlesage** [comment]
… I do begin to think that what we may face here is simply a conflict of several keyboard shortcuts with builtin codemirror ones.

Just as a test: Would you mind **de-focusing** the CodeMirror instance, that is, e.g., clicking on the title bar until the cursor is gone, and then attempt to use one of these shortcuts? Does it work then?

**Comment by nabusch** [comment]
OK, just tried: clicked on the tab title and cursor disappears. But CTRL+W, CTRL+tab, CTRL+Shift+tab still have no effect.

**Comment by wgslr** [comment]
Same here, still no effect for the shortcuts.

**Comment by nathanlesage** [comment]
Hmm … and the logs remain quiet? What does the menu btw say when it comes to the accelerators? Do the accelerators show up next to the corresponding menu items?

**Comment by b4nn** [comment]
Doesn't work for me as well. Not sure if this is of any use, but here are my logs when I've used ctrl+1, ctrl+2 and ctrl+3 shortcuts which currently open in tabs what seems like random notes.

![image](https://user-images.githubusercontent.com/65569952/83817097-d6bc9600-a6bb-11ea-9e51-a47735537027.png)

**Comment by nathanlesage** [comment]
> which currently open in tabs what seems like random notes.

Yeah, I know … but at least this means Ctrl+[0-9] works! What I was aiming at was a screenshot of the menu of Windows, because at least on macOS (and I think on Windows too) the registered shortcuts are displayed next to the menu item labels, and this would be a first indicator of what goes wrong.

**Comment by vijoc** [comment]
The menu in Windows shows the registered shortcuts next to the menu item labels, too. I was unable to find tab-related menu items, but here's a screenshot of some others. This is in version 1.7.0-beta.9.

![image](https://user-images.githubusercontent.com/1031232/84022575-2c7c9100-a98f-11ea-806d-bff5e0e9c8e3.png)

Digging into this, it seems to me that the `window` menu under which the actions are defined in the template is not even built on platforms other than macOS:

https://github.com/Zettlr/Zettlr/blob/fc4e802db5064a729837836bc425fb75683d8772/source/main/zettlr-menu.js#L187

I'm not familiar with the codebase or electron in general, but maybe that could have something to do with the issue?

**Comment by nathanlesage** [comment]
AHAHAHAHAHAHAHA okay I'm an idiot 😂

I was thinking of whatnotelse going wrong, but it's just me forgetting that I have to explicitly offer them for Windows! Oh God, I'm sorry for letting you down on this one!

**Comment by vijoc** [comment]
Heh, I'm glad that it was helpful. And don't be too hard on yourself, I'm sure we all have moments like that! Your amazing work on Zettlr is greatly appreciated. :)

**Comment by nathanlesage** [comment]
Hey yall, I just enabled the "Window" submenu on ALL platforms, not just macOS. However, there is one macOS-only-item in the menu ("Bring all to front"), and I am not quite sure whether Electron will simply not render that one (which would be great) or cause bugs (which would be bad) — so I would really appreciate it if any one of you might want to try the whole submenu on Windows and/or Linux and get back with info on whether everything works as expected, so that I can push a new beta this week based on that information (and, potentially, tweaks!)

**Comment by nabusch** [comment]
Sure, I can test it on Windows 10. How do I get the most recent build?

And to clarify: when you say "Window submenu", are you referring to the "View" menu?

![zettlr](https://user-images.githubusercontent.com/6177572/84044057-58a40c00-a9a7-11ea-8685-bea6a6243bb3.jpg)

**Comment by nabusch** [comment]
Ah, I can see your commit about "enabling window submenu on all platforms". So I guess you are referring to a submenu that does not yet exist at all for windows users, right?

And sorry for the dumb question: can I just clone the repo and install it on my machine? Can I somehow turn the code into an .exe or installer?

**Comment by nathanlesage** [comment]
Yes, I'm talking about a Window submenu — I do not know why I disabled it on all platforms except macOS, but it's different from "View"! I assume this is because on macOS there's a lot of additional stuff going on in the Window menu that's not available on Windows:

![image](https://user-images.githubusercontent.com/17251683/84046604-9ce4db80-a9aa-11ea-860e-13398cc5c2b5.png)

(For instance the tiling or automatic transfer to different displays, etc.)

> And sorry for the dumb question: can I just clone the repo and install it on my machine? Can I somehow turn the code into an .exe or installer?

Yes, it should be fairly straightforward! Here's how you do it:

1. Download & install [nodeJS](https://nodejs.org/en/download/), [Yarn](https://yarnpkg.com/getting-started/install), and [git](https://git-scm.com/)
2. `git clone https://github.com/Zettlr/Zettlr.git`
3. Wait until everything has finished
4. Then run `git checkout develop` (I'm not sure if its already on develop, but it can't hurt to run this)
4. Run `yarn start`

And then it should start the app with the correct stuff, and you can check the menu!

**Comment by vijoc** [comment]
Running the latest development version on Windows 10 shows me this:

![image](https://user-images.githubusercontent.com/1031232/84115441-c21f2b80-aa36-11ea-8591-9e7e3cd2e4c4.png)

Clicking on the menu items does what you would expect, except the "Bring All to Front" which does not appear to do anything. I'm not sure what it should do on macOS, but on Windows it appears to be harmless. I tried having the quicklook window open and covered by another window, but clicking "Bring All to Front" did not seem to do anything with that.

The shortcuts (Ctrl+M, Ctrl+Shift+W, Ctrl+W, Ctrl+Tab, Ctrl+Shift+Tab) appear to work as well.

**Comment by nabusch** [comment]
Thanks @vijoc ! I was just in the process of building the app from the latest development version, but yarn keeps throwing me an error "Cannot find module 'bcp-47'". But to be honest, I am new to the world of building Javascript apps, so I hardly understand what I am doing. 

Glad you figured this out for us!

**Comment by nathanlesage** [comment]
Perfect! Just was at the office to test it myself as well, beta comes in a few minutes!
