### ISSUE TITLE
RTF export is only exporting the first line

### ISSUE THREAD

**Issue by gcman105** [Zettlr/Zettlr#843]
## Description
I wanted to export to RTF format. All other formats seem to work as expected but RTF seems to just export the first line of the file.

## Reproducing
Content below:
This is an RTF test file

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras placerat lectus vitae massa. Morbi justo. Suspendisse eu sem sed lorem faucibus sodales.

Vestibulum tristique lobortis lorem. Suspendisse potenti. Donec blandit purus in urna. Vestibulum egestas mi a felis. Praesent quis purus eget purus imperdiet placerat. Donec consequat consequat lacus. In viverra neque.

## Expected behaviour
Should export the whole file to RTF.

**Screenshots**
![2020-05-26_10-17-51](https://user-images.githubusercontent.com/460778/82877223-34254a00-9f3a-11ea-8190-3fcc70878b16.png)

Produces:
![2020-05-26_10-19-02](https://user-images.githubusercontent.com/460778/82877339-54550900-9f3a-11ea-9899-60265b84e78b.png)

## Platform
 - OS and version: macOS Catalina Version 10.15.4
 - Zettlr Version: Version 1.6.0 (1.6.0)
 - Screen Resolution: 27-inch (2560 x 1440)

**Comment by nathanlesage** [comment]
Apparently this has something to do with the Pandoc RTF writer, as I can reproduce this issue even by bypassing Zettlr's internals. So the command `pandoc -f markdown -t rtf -o "Test.rtf" "Test.md"` as well yields the results you described.

Interestingly, the file itself does contain all contents, but something is confusing the reader application … please try to reproduce this locally by running a pandoc-command by yourself and, if you can reproduce it, this is an error in Pandoc!

**Comment by nathanlesage** [comment]
This has already been solved, so here we go!
