### ISSUE TITLE
Julia code highlighting support

### ISSUE THREAD

**Issue by dunefox** [Zettlr/Zettlr#847]
Is it possible to add syntax highlighting in code blocks for [Julia](https://julialang.org/)?

**Comment by nathanlesage** [comment]
Do you mean [this Julia](https://codemirror.net/mode/julia/index.html) or [that Julia](https://en.wikipedia.org/wiki/Romeo_and_Juliet)?

**Comment by dunefox** [comment]
Sorry, I meant [this Julia](https://en.wikipedia.org/wiki/Julia_Roberts).

**Comment by nathanlesage** [comment]
Ah damn it, I'm not sure it's in the source code; can I help you out with [that guy](https://nodesource.com/blog/is-guy-fieri-in-your-node-js-packages/) instead?

**Comment by nathanlesage** [comment]
jk here you go 😄
