### ISSUE TITLE
[ENHANCEMENT] Add option to highlight tags when searching for them

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#848]
## Description
Right now, when you CTRL+click on a tag to show all files with the same tag*, the found tags are not highlighted inside the files. However, as I often use a tag multiple times inside a larger document (for bookmarking purposes) it would be nice if tags were highlighted when searching for them.

(*or, equivalently, search explicitly via the global search bar)

## Proposed Changes
Add option to enable highlighting tags when searching for them.

## Caveats
Probably none (?)

## Additional Information
- Version: 1.6.0

**Comment by nathanlesage** [comment]
> the found tags a not highlighted inside the files.

That preeeeeeeetty much sounds like some form of bug, I'll investigate (or someone else, if you stumble upon this and have some time!)
