### ISSUE TITLE
[BUG] Highlighting mode breaks with RTL scripts

### ISSUE THREAD

**Issue by amirography** [Zettlr/Zettlr#849]
When there is a comment or code, the highlighting feature highlights the wrong portion of the line, when in RTL.

## Reproducing
Just start typing in any RTL language, and use the comment or code clauses. most of the time it will highlight the wrong portion but it changes, each letter you add. 

## Expected behaviour
highlight the right portion!

**Screenshots**
![2020-05-30-082653-](https://user-images.githubusercontent.com/28535608/83319019-b3bf5b80-a24f-11ea-8732-74d34dc86e6d.PNG)

## Platform
 - OS and version: windows 10 build 18363
 - Zettlr Version:1.7 beta 7
 - Screen Resolution: 1600*900

**Comment by nathanlesage** [comment]
Can you reproduce this in one of the [CodeMirror demos](https://codemirror.net/index.html)?

**Comment by amirography** [comment]
> Can you reproduce this in one of the [CodeMirror demos](https://codemirror.net/index.html)?

It looks fine in CodeMirror demos. 
![2020-05-31-102652-](https://user-images.githubusercontent.com/28535608/83345536-716a4d00-a329-11ea-8f7d-549aa0431d47.PNG)

**Comment by nathanlesage** [comment]
Perfect, thanks for double checking!

**Comment by nathanlesage** [comment]
Fixed in the current develop branch.
