### ISSUE TITLE
RTL settings are not correct when zettlr starts

### ISSUE THREAD

**Issue by amirography** [Zettlr/Zettlr#850]
## Description
When Zettlr starts, it reverts back to LTR, while in the settings it says it's RTL. You will have to change the settings to LTR and then RTL again to revert back to RTL mode. 

## Reproducing

1. type this in a file in Zettlr:
این یک متن آزمایشی در زتلر است. 

2. Make sure you have changed your settings in the editor to RTL.
3. Close zettlr.
4. Open it again
5. Voila! :D 

## Expected behaviour
The settings should be consistent with the preferences defined by the user.

**Screenshots**
![2020-05-30-083918-](https://user-images.githubusercontent.com/28535608/83319158-2846ca00-a251-11ea-958d-dea087150f06.PNG)

## Platform
 - OS and version: windows 10 build 18363
 - Zettlr Version: 1.7 beta 7
 - Screen Resolution: 1600*900

**Comment by nathanlesage** [comment]
Just double-checked, and I'm at a loss, because I can't find the problem why it won't update. It won't even use the RTL mode if I pre-set the editor with it …

**Comment by hrmon** [comment]
I have to say the issue is still present. I see in the commit you have tried to resolve it by a timeout. Maybe the amount of timeout will not work in all situations?

**Comment by nathanlesage** [comment]
As I said, I am not really sure what is happening :/ If you find something, let me know!
