### ISSUE TITLE
Zero-Width Non-Joiner character is rendered as a red dot

### ISSUE THREAD

**Issue by amirography** [Zettlr/Zettlr#851]
## Description
ZWNJ character which is used in connected complex scripts is rendered as a red dot instead. 

## Reproducing
copy and paste the quote: "‌" which should be rendered as you see here. instead, there will be a red dot in Zettlr.

## Expected behaviour
It should be rendered without the red dot.

**Screenshots**
![2020-05-30-084122-](https://user-images.githubusercontent.com/28535608/83319263-216c8700-a252-11ea-8de9-d1dadd6ebbde.PNG)

## Platform
 - OS and version: Windows 10 build 18363
 - Zettlr Version: 1.7 beta 7
 - Screen Resolution: 1600*900

**Comment by nathanlesage** [comment]
Is this part of the following setting regex: https://codemirror.net/doc/manual.html#option_specialChars ? Can you identify this?

**Comment by amirography** [comment]
Not as far as I can tell. But I could reproduce this in CodeMirror demos. 
![2020-05-31-103355-](https://user-images.githubusercontent.com/28535608/83345599-4e8c6880-a32a-11ea-9a68-6045af042080.PNG)

**Comment by nathanlesage** [comment]
Then this looks like it's for CodeMirror to have a look … would you mind searching their issue tracker if they had this discussion (so as to determine _why_ the ZWNJ has been determined "unrenderable")?

**Comment by amirography** [comment]
I have opened an issue today there, and it seems that it has been fixed and will be on the next release of code mirror:
https://github.com/codemirror/CodeMirror/issues/6303

**Comment by nathanlesage** [comment]
Perfect, I'll be updating the CodeMirror dependency before 1.7, so the fix will ship with the next release of Zettlr! Thank you very much for helping out! It's well received! :)

**Comment by amirography** [comment]
BTW, as of now, this problem still persists.

**Comment by nathanlesage** [comment]
Thanks for reminding me, totally forgot to pull that patch. But did it now!
