### ISSUE TITLE
[FEATURE] Sort selected lines with shortcut

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#852]
# Description

Would be great to be able to sort selected rows alphabetically and numerically by pressing some key combination. I have all kind of lists in Zettlr which I like to keep in order. I also like to keep my tag lists in order.

# Implementation in Sublime Text

Sublime Text has this. You press F9 and selected rows are sorted. If no rows are selected, the whole text is sorted. I guess whole file sort would not be good in Zettrl. Rarely one wants to sort the whole zettel.

# Additional feature 1

**Additionally, would be nice if sorting would cycle when pressed the key combination. Example:**
1. Select rows to be sorted
2. Press key combination
3. Zettlr sorts the selected rows alphabetically, ascending
4. Press key combination
5. Zettlr sees the rows are already sorted
6. Zettlr sorts the selected rows alphabetically, descending

# Additional feature 2

We have rows like this:

[[20200530110055]] Title 3
[[20200530110107]] Title 1
[[20200530110122]] Title 2

Those rows are sorted alphabetically and numerically. Sublime sorts them with date stamp right now because the time stamp is before the title text.
Zettlr could in this case recognize that the row is [[ID]] title and sort the rows by title.

In that case, the sorting would become this:

[[20200530110107]] Title 1
[[20200530110122]] Title 2
[[20200530110055]] Title 3

**This feature could use the keyboard shortcut cycling feature:** 
First keyboard combination press: sort rows alphabetically (by zettel ID)
Second keyboard combination press: sort rows aphabetically reversed (by zettel ID)
Third keyboard combination press: sort rows by title alphabetically
Fourth keyboard combination press: sort rows by title alphabetically reversed

PS. I think this kind of neat and useful features are great. They save time and help the user mould the text efficiently.

**Comment by nathanlesage** [comment]
So basically a contextual-aware sorting mechanism — I just recently needed that functionality in Word, so sounds good to me! Short little algorithm that should be implementable rather easily. Concerning the shortcut: We already have `F9` as a candidate, but in case you wanna double-check that this is indeed a good choice and it doesn't conflict with other shortcuts!

**Comment by ME7DYCgw8M** [comment]
Key was not used in this site:
[https://www.zettlr.com/shortcuts](https://www.zettlr.com/shortcuts)

In this site, different programs seem to have different uses for F9:
[https://defkey.com/what-means/f9](https://defkey.com/what-means/f9)
