### ISSUE TITLE
Mermaid code does not be rendered into graphics in exports.

### ISSUE THREAD

**Issue by mevernom** [Zettlr/Zettlr#854]
## Description
Mermaid code can be rendered during editing, but in all exported results, including HTML, the code remains as code, not the desired rendered graphics.

## Reproducing
1. open a file, write in any correct mermaid code block.
2. hit export.

## Expected behaviour
The mermaid code block should be exported as rendered graphics.

**Screenshots**
![截圖 2020-05-30 23 41 25](https://user-images.githubusercontent.com/3414482/83332686-228fc980-a2cf-11ea-8c66-498e98c0d1d2.png)
![截圖 2020-05-30 23 41 30](https://user-images.githubusercontent.com/3414482/83332688-27547d80-a2cf-11ea-8422-8c785582cf53.png)
![截圖 2020-05-30 23 41 40](https://user-images.githubusercontent.com/3414482/83332691-2a4f6e00-a2cf-11ea-9aa1-723c3d563d18.png)

## Platform
 - OS and version: macOS Catalina 10.15.4
 - Zettlr Version: 1.6.0
 - Screen Resolution:

**Comment by nathanlesage** [comment]
To have mermaid being parsed on export, currently what you'd need to do is install a special **filter** for pandoc. Zettlr as of now does not compile Mermaid code, because this is currently not implemented.
