### ISSUE TITLE
[ENHANCEMENT] Do not lowercase tags

### ISSUE THREAD

**Issue by mdinic** [Zettlr/Zettlr#855]
All tags are lowercased by default during the auto-complete process: both in the auto-complete drop-down and on page. This makes them hard to read when they contain multiple words. It would be better to keep the original case of the tags everywhere.

**Comment by An-png** [comment]
don't you use underscores to seperate multiple words in tags?

**Comment by mdinic** [comment]
I could, and that's a OK alternative. It's slower to type and again, when
tagging things like author names, book names, stock symbols, financial
formulas and much more you don't want to lowercase. You want to preserve
case and during auto-complete it would be correct.

**Comment by nathanlesage** [comment]
The reason why the tag matching is done case-insensitive is that this will yield more results (as it accounts for accidental typos, and my broken SHIFT-key on my keyboard can certainly tell you why this is a good idea 😄 ). But what would be possible is an _insensitive_ search, and a _sensitive_ display, that is: Searching is done case-insensitive but displaying is done case-sensitive. Should be possible using a few internal changes to the engine …
