### ISSUE TITLE
Error dialog when creating a file or directory inside a "virtual directory"

### ISSUE THREAD

**Issue by userfav** [Zettlr/Zettlr#86]
## Description

Zettlr shows a error dialog box when I try to create a file or folder inside a previously created virtual directory.

## Reproducing

1) Create a directory 2) Create a "Virtual Directory" inside the directory 3) Try to create a new file or directory when you have the virtual directory selected. 

## Expected behaviour

If that action is not possible, show a message warning that.

**Screenshots**

![imagen](https://user-images.githubusercontent.com/46328784/51147988-225a6f80-183b-11e9-8b9d-0754ced2a2b4.png)

## Platform
 - OS: Linux Mint 19.1
 - Zettlr Version 1.0.0

**Comment by nathanlesage** [comment]
And here you go! Will be completely fixed in the next version :)
