### ISSUE TITLE
[FEATURE] Recognize that the selected text is within special characters before re-entering those characters.

### ISSUE THREAD

**Issue by henrique9i** [Zettlr/Zettlr#860]
## Description
When I select a word that is in bold and press CTRL + B, it inserts the asterisks again, for example:
`**text**`
`CTRL+B`
`****text****`

The program should recognize that the text is already in bold and instead of inserting it again, delete them.
I can easily select a word with a double click, but selecting the code also gives 3 times more work.

### More complex example and logic

`***some big text in bold and italic***`
Supose a select only the word "**text**"
`CTRL+B`: 
- First search the selected text for this ` **any text** `
 (space + ** + any characters + ** + space). You need to consider the beginning and end of the paragraph (space or not).

If not found:
- Search for 2x asterisc on the right and left, if find > erase, elseif > add
    - Search the entire paragraph.
    -   Need to stop at the first match found (for each side).
    -   Need to find the code on both sides, otherwise go to the "elseif" and insert the codes
    -   Asterisks on the left should only have space on the left (Same logic for the right side):
        -   `** text` = wrong
        -   `**text` = wrong (if it's at the beginning of the paragraph, that's right)
        -   ` ** text` = wrong
        -   ` **text` = right
        -   ` ***text` = right

After applying the change, keep the word selected, I may want to remove the bold from a sentence and apply only to that word, in that case I just press again CTRL + B.

You can use the same logic for all other Markdown codes.

> I used Google Translate because I don't speak english very well, any questions ask that I try to explain better.

**Comment by nathanlesage** [comment]
You are right, the algorithm currently is not very sophisticated and does not check the adjacent characters. Furthermore, what would be cool is if it would "unionize" selections, so if you select `**bold** and non-bold text` that it would either completely make it bold or un-bolden it first before toggling through bold/non-bold!

**Comment by nathanlesage** [comment]
Works in the 1.8 alpha already, so will ship with the regular 1.8
