### ISSUE TITLE
Clicking internal link does not open target

### ISSUE THREAD

**Issue by adamfeuer** [Zettlr/Zettlr#861]
## Description

Clicking an internal link does not open the target note file.

## Reproducing

1. Cmd-N to make a new note.
1. Cmd-L to place an ID, for instance `20200601204942`
1. Type `#foo` to title the note on a new line
1. Copy the ID
1. Cmd-N to make a new note
1. Cmd-L to place an ID
1. Type `#bar`to title the note on a new line
1. Type `[[20200601204942]] foo` (or paste whatever ID you used from step 2.
1. Cmd-Click on the internal link.
1. Nothing happens.

## Expected behaviour

1. You should be taken to the note with `#foo`

**Screenshots**
<img width="1440" alt="Screen Shot 2020-06-01 at 9 46 20 PM" src="https://user-images.githubusercontent.com/324915/83480916-614d8d00-a451-11ea-9d78-2ca1d36249e9.png">
<img width="1440" alt="Screen Shot 2020-06-01 at 9 46 11 PM" src="https://user-images.githubusercontent.com/324915/83480926-64487d80-a451-11ea-9b68-6dd55f402860.png">

## Platform
 - OS and version: macOS 10.16.4
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1440x900

## Additional information

I'm a new Zettlr user. This seems like basic functionality, so I might be doing something wrong.

**Comment by nathanlesage** [comment]
Hey, thanks for noticing!

Actually, `Cmd-Click on the internal link.` — currently you have to hold down `option`. I'm more and more stumbling upon this myself, which means I'm likely going to enable Cmd/Ctrl instead of Alt, as the former is much more common.

And one note to your titles: What you're doing is a tag, not a title (to avoid confusion, titles need a space between the character and the title itself, e.g.: `# foo`)

**Comment by adamfeuer** [comment]
@nathanlesage Thanks– I tried `Option-Click`... it brings me to a screen where there are two files shown. I have to click one of them to get to the file with `# foo`. So for me the `Option-Click` still doesn't go directly to the file with the ID in the link– it's more like search results, where I have to find the file myself. 

Is there a way to get Zettlr to go directly to the linked file in one click of an internal link? Or am I still doing something wrong?

Thanks for the tip about the titles, I didn't know that.

Here's a few screen shots:

The updated foo file with a title (`# foo`) and a link to the `# bar` file:
<img width="801" alt="Screen Shot 2020-06-02 at 10 11 05 AM" src="https://user-images.githubusercontent.com/324915/83549278-ea98aa00-a4b9-11ea-9274-8982e1f10fc9.png">
After Command-Clicking the link:
<img width="997" alt="Screen Shot 2020-06-02 at 10 11 14 AM" src="https://user-images.githubusercontent.com/324915/83549287-eec4c780-a4b9-11ea-8075-9b4a715ec588.png">
I have to click the card in the left pane to get to the card with `# bar` in it:
<img width="817" alt="Screen Shot 2020-06-02 at 10 11 27 AM" src="https://user-images.githubusercontent.com/324915/83549296-f2584e80-a4b9-11ea-85d3-3ae96ab7b4ab.png">

**Comment by nathanlesage** [comment]
> Is there a way to get Zettlr to go directly to the linked file in one click of an internal link?

Yeah, actually this should work, I'm curious why it's not … wait a moment! The ID in the link doesn't correspond to the ID of the files! :D Here, see what I mean:

![image](https://user-images.githubusercontent.com/17251683/83555543-b7ccd100-a50e-11ea-860d-5d99abc84097.png)

To make sure that the correct ID is taken, right-click the file and say "Copy ID"! This way you can paste the real ID, and not generate a new one!

**P.S.: A keyboard shortcut for that functionality is already requested and will come in 1.7!**

**Comment by adamfeuer** [comment]
@nathanlesage Ok, it works if I use the file's name as the link. Thanks.

But doesn't the Zettlr docs say that the link can be the first ID in the file, and not the file name? I can't link directly to it, but see the Internal Links section of this page:

https://docs.zettlr.com/en/reference/settings/

It says, 

> The internal links are used for two things: First, if they either contain an existing file name or an existing ID, clicking them will directly open the respective file (identified either by its name without the extension, or by its ID). 

That seems like the point of having IDs... you can drop them in a file and use that as the link target instead of the file's name. Or am I getting that wrong? If so, what do you use the IDs for?

**Comment by nathanlesage** [comment]
You are completely right, it works like this:

1. Zettlr searches first the filename, then the filecontents, top to bottom, for anything that matches the ID pattern
2. If it found one such thing, the first it found will be assumed the ID of the file
3. To link to that file, you can subsequently use this ID, and wrap it in your link-characters (default: `[[` and `]]`) within the other files!
