### ISSUE TITLE
[FEATURE] Implement VIM mode for editor

### ISSUE THREAD

**Issue by tobiaslocker** [Zettlr/Zettlr#862]
## Description

I would like to use Zettlr but without VIM Mode this would mean a huge lack of productivity compared to, well... VIM

## Example Workflow
Settings -> Editor -> Enable VIM Mode (as in several IDEs)

## Caveats
Nope

## Additional Information
Nope

**Comment by nathanlesage** [comment]
Hey, we are actually in the process of implementing it, have a look at this issue: https://github.com/Zettlr/Zettlr/pull/683

This will ship in 1.7, and you'll be able to choose the default keymap (basic editor + sublime text addons), emacs, and vim (albeit vim seems to have a few minor shortcut collisions we'll have to work out) — just look at the above mentioned PR: Once it's merged, the next release afterwards will contain that! :)
