### ISSUE TITLE
[MIGRATION] devToolsExtensions deprecation warning in Electron 9

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#863]
Just for information: I just read the following migration warning, and I'll put up this issue just not to forget this:

```
(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.
(electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.
```

Seems easy enough to migrate.

Further info: https://www.electronjs.org/docs/api/session#sesloadextensionpath

@tobiasdiez I'll assign you real quick, as you introduced the vueDevtools, and hence I think you're the right person for this job — feel free to protest if you think otherwise! :)

**Comment by tobiasdiez** [comment]
Loading the extension is done using `electron-devtools-installer` and they are currently in the progress to fix this. https://github.com/MarshallOfSound/electron-devtools-installer/issues/130

**Comment by nathanlesage** [comment]
Thanks for the heads up!

**Comment by nathanlesage** [comment]
Sometimes it helps to scroll through old issues: Has been solved in the meantime!
