### ISSUE TITLE
[ENHANCEMENT] Insert current (not new) id

### ISSUE THREAD

**Issue by indeyets** [Zettlr/Zettlr#865]
## Description

Zettlr has command (triggered by Cmd-L) which inserts new ID into document. I wish there was an option to quickly insert current ID instead.

## Proposed Changes

It would be nice if there was additional shortcut which would take current document-id known to zettlr and insert it into document. Cmd-Shift-L could be used for this, for example.

My usecase is: document id is populated from filename, by default and I want to move it inside of document and rename the file. Currently, I have to do it via right-click→copy-id→paste, but it's possible to make it simpler.

## Additional Information

My usecase is: document id is populated from filename, by default and I want to move it inside of document and rename the file. Currently, I have to do it via right-click→copy-id→paste, but it's possible to make it simpler.

**Comment by nathanlesage** [comment]
This is already covered by #783
