### ISSUE TITLE
[BUG] After update electron to 9 error with image and app doesn't launch

### ISSUE THREAD

**Issue by rbereziuk** [Zettlr/Zettlr#867]
## Description
After last update on Manjaro Linux app doesn't launch and alerts error

## Reproducing
1. Update manjaro and electron to 9 version
2. Install Zettlr with AUR 
3. Try to launch

## Expected behaviour
1. App should starts

**Screenshots**
![Screenshot from 2020-06-02 18-04-57](https://user-images.githubusercontent.com/22666814/83536860-7d5a3880-a4fc-11ea-9c21-56f6e840399e.png)

## Platform
 - OS and version: Manjaro Linux 20.0.2 (Lysia)
 - Zettlr Version: 1.6.0-2 (from AUR)
 - Screen Resolution: 1366x768

**Comment by nathanlesage** [comment]
Interesting — but it very much seems like a problem with the AUR dependency; the version `1.6.0` has not yet switched to Electron 9, and the bug appeared only on Electron 9. I have fixed it in the most recent beta, but I'm not sure as to the cycle the maintainers of the AUR repository have, so I don't know if or when that beta will be in the AUR … please get in touch with them in that case! :)

In any case please either use Electron 8 with versions prior to the most recent beta release, or upgrade to the most recent beta release to have this bug gone!
