### ISSUE TITLE
Attachments "Open Directory" button open multiple instances of the file manager.

### ISSUE THREAD

**Issue by userfav** [Zettlr/Zettlr#87]
## Description

When "Open Directory" icon is clicked (Attachments panel), open multiple instances (then or more) of the file manager at same directory.

## Reproducing

Click on "view attachments" icon, and then in "Open Directory"

![imagen](https://user-images.githubusercontent.com/46328784/51148532-5cc50c00-183d-11e9-86d0-db7b67266a32.png)

## Expected behaviour

Open just one instance of the file manager.

**Screenshots**

Example: (panel view) 

![imagen](https://user-images.githubusercontent.com/46328784/51148589-9564e580-183d-11e9-8466-979e25b96bb3.png)

## Platform
 - OS: Linux Mint 19.1  Cinnamon
 - Zettlr Version 1.0.0

**Comment by nathanlesage** [comment]
Thanks for bringing this up! I would strongly suggest that this might be an error with the native electron binding for opening up the shell on your distribution, as I'm pretty sure there's nothing wrong with my own code.

For reference, this function is triggered when you click on the button:

https://github.com/Zettlr/Zettlr/blob/bc8d2de917f10088e109e0efb37b5778ea862909/source/renderer/zettlr-attachments.js#L103-L107

I think what's going wrong is the call to `shell.openItem` there. But I don't havy any influene on how `openItem` works internally …

**Comment by userfav** [comment]
Thanks Nathan. I don't know if this can help or not, but I try dig a little more in the situation and come to this:

Starting the program with a root directory containing a bunch of files and an empty directory folder like this...

![imagen](https://user-images.githubusercontent.com/46328784/51193918-bd4d5b00-18c8-11e9-91d6-09359f7e9337.png)

... if I click here the "Open directory" button, works as expected (open just one instance of the selected folder)

But if I navigate and select the empty directory in the tree...

![imagen](https://user-images.githubusercontent.com/46328784/51194114-2b921d80-18c9-11e9-8727-178df264d8f3.png)

...and try to open the directory, now two instances of the file manager are opened (if I keep clicking always open two instances each time).

Now, if I navigate and come back to the root directory and try to open the folder now three instances are opened. 

So, I can switch between the two directories and each time one instance will be added when I try to open the directory.

**Comment by nathanlesage** [comment]
Oh, ah. I think this indeed helps a lot because now I think it‘s because - somehow - the app always attaches a new listener, and all of them are fired when you click the button, i.e. whenever you change the directory, you get yourself an additional handler

**Comment by nathanlesage** [comment]
Found the error! Will be closed with the next version :)
