### ISSUE TITLE
[Issue] Exporting to a pdf document (shell.openItem is not a function)

### ISSUE THREAD

**Issue by jofimendes** [Zettlr/Zettlr#870]
## Description

I update Zettlr to v.1.7 beta 8. I'm using Pandoc v.2.9.1 and MiKTeX v2.9.

When i try to export to PDF the i receive a notification "TypeError: shell.openItem is not a function".

Maybe i'm doing something wrong or i need to install some dependencies. Or it is just some advanced settings i need to check, i' don't know. 

When i did use Zettlr to test it all was working fine until i update it.

## Reproducing

Try to install the last beta version of Zettlr (v.1.7 beta 8.exe) on Windows 10 x64 with the same Pandoc and  MikTeX versions. 

## Expected behaviour

It should export a markdown document to PDF.

## Platform

 - OS and version: Windows 10 x64 Build 1909
 - Zettlr Version: v1.7-beta8.exe
 - Screen Resolution: 1366 x 768

## Additional information

I'm gonna attach the last log file. If anyone can help or need more information just tell me.

Thanks.

[2020-06-02.log](https://github.com/Zettlr/Zettlr/files/4719538/2020-06-02.log)

**EDIT:** The export to PDF works now I didnt checked the file directory for the PDF :) 
(Usually it opens from the the default pdf reader. The issue still appears when i export the document, so this request remains valid, i guess)

**Comment by nathanlesage** [comment]
Hey, thanks for noticing!

> It should export a markdown document to PDF.

This is still true, the only thing that is broken in 1.7.0-beta.8 is that I accidentally forgot to migrate that line of code which simply opens the file, but it's already fixed, so auto-opening exported files will work again in the next beta, which'll come during this week!

**Comment by cippaciong** [comment]
Hello, I'm having the same problem with Zettlr `1.6.0` and Electron `9.0.3`. I think that `shell.openItem` has been replaced by `shell.openPath` in Electron 9 ([reference](https://www.electronjs.org/docs/breaking-changes#api-changed-shellopenitem-is-now-shellopenpath))

**Comment by nathanlesage** [comment]
It's all good in the current betas!
