### ISSUE TITLE
Need to Ctrl + Alt + click to open links. 

### ISSUE THREAD

**Issue by TheWizzard666** [Zettlr/Zettlr#875]
> Great! That works with the name in the link. Although on my (unusual) keyboard I need to Ctrl-Alt click.
> I think I was mistaking the timestamp below the filename for the ID (which needs to be generated manually). Link with ID: 20181015022308 also works. Am I correct in assuming that the ID can be placed anywhere in the file?
> Thank you for your help - and thank you for developing this lovely app. I am hoping to use it to organize my notes, Zettelkasten-style.

_Originally posted by @cjpoor in https://github.com/Zettlr/Zettlr/issues/41#issuecomment-429626504_

I had a similar issue and I couldn't open links. It took me quite some time struggling before I found this post. Links in Zettlr only open when I use Ctrl + Alt + click. No other combination works. 
I'm on MacOS with ctrl and cmd switched around, so I actually use cmd+alt+click to open links. I would be delighted if I could use a simpler key combination for this.

**Comment by nathanlesage** [comment]
The key combination should be `Option+Click`, but I know that we should alter this to `Cmd+Click`, because that's what makes most sense. Have to do so at some point, yes!

**Comment by nathanlesage** [comment]
I just took the liberty of changing the key combination and it SHOULD now work in the new beta I'll be releasing in a few minutes — please either close the issue, if it works, or respond if it doesn't! :)

**Comment by TheWizzard666** [comment]
> The key combination should be `Option+Click`, but I know that we should alter this to `Cmd+Click`, because that's what makes most sense. Have to do so at some point, yes!

Option+Click doesn't work on my MacBook. Alter this to Cmd+Click might do the trick.

**Comment by TheWizzard666** [comment]
> I just took the liberty of changing the key combination and it SHOULD now work in the new beta I'll be releasing in a few minutes — please either close the issue, if it works, or respond if it doesn't! :)

The Zettlr I'm using is the pre-compiled 1.6 for OSX. I'm sorry, but I don't know how to test the new beta version. Do you want me to close this wan and see how it goes when 1.7 is released?

**Comment by danieltomasz** [comment]
Hi,the development releases are published on github https://github.com/Zettlr/Zettlr/releases/tag/v1.7.0-beta.9

**Comment by nathanlesage** [comment]
@danieltomasz Thanks a lot for helping out! :)

> Do you want me to close this wan and see how it goes when 1.7 is released?

As soon as it works, feel free to close this! Either in the beta or when 1.7 is out, depending on what you'll try out! :) (The emptier this list is, the less pressure there is comimg from daunting bugs!)

**Comment by TheWizzard666** [comment]
> @danieltomasz Thanks a lot for helping out! :)
> 
> > Do you want me to close this wan and see how it goes when 1.7 is released?
> 
> As soon as it works, feel free to close this! Either in the beta or when 1.7 is out, depending on what you'll try out! :) (The emptier this list is, the less pressure there is comimg from daunting bugs!)

It works. Thank you so much! It looks like a small thing, but Zettlr works a lot more convenient for me now. I'll close this issue now. Cheers.

**Comment by nathanlesage** [comment]
Perfect, I'm glad it works now! :)
