### ISSUE TITLE
[ENHANCEMENT] Open in new Tab with a shortcut, not default behavior

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#878]
## Description
I find the behavior of current beta versions of Zettlr odd, that as soon as I open a new file, it will open in a new tab. I can see that this is the behavior that one would expect from an editor that is made for programming, first an foremost. For writing and reading however, I find it really annoying and liked it better the way it was before. Currently, when I am reading a lot of different notes, I will have to close them all every so often. This distracts very much from the actual reading and writing. When I have 20 open notes, I can't find anything through the tab overview.

## Proposed Changes
I would either propose to change the default behavior to the way it was before, with the option to open new notes in new tabs, similar to how it works in web browsers, or in the least to give the option to change it between "browser mode" and "editor mode", for those people who'd possibly like the new behavior.

**Comment by nathanlesage** [comment]
Closing in favor of #879
