### ISSUE TITLE
[DISCUSSION] Tab Behaviour (transient/browser)

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#879]
So folks,

as everyone seems to have a different idea of how the tabs should **really** work, let's make this a quick process. Here's so far the different positions I've registered so far:

1. Whenever you click a file (or file link), open that one in the currently active tab, effectively switching out the document within that. Open a new tab, if none is open. Use `Ctrl/Cmd+Click` to open the file in a new tab instead.
2. Whenever you click a file, check if the current tab is transient (i.e. unmodified), and open it in that one. Otherwise, automatically open a new tab.

[The Twitter poll](https://twitter.com/zettlr/status/1264861826543738880) indicated people favour the first behaviour, with a huge margin wanting the second one.

As of now, I'm inclined to try and implement both of them with a switch, but that would really depend on how difficult this would be to implement. Right now I can think of the following (pseudo-code):

```javascript
if (global.config.get('editor.tabMode') === 'transient' &&
    this._activeDoc.isTransient) {
  this.openSameTab(file, transient = true)
} else if (global.config.get('editor.tabMode') === 'permanent' &&
           !(event.metaKey || event.ctrlKey)) {
  this.openSameTab(file, transient = false)
} else {
  let shouldBeTransient = global.config.get('editor.tabMode') === 'transient'
  this.openNewTab(file, shouldBeTransient) 
}
```

So I think this should be possible … feel free to check that I didn't miss something, and please don't open any more issues regarding this, just comment here 😄

**Comment by Zverik** [comment]
I'm for making the "transient" state invisible to user, with automatic saving on any action, including tab/app closure and switching out. That way this would be a no-choice.

For me, I'm getting used to all these tabs, but for now it adds more hassle then help. Maybe there could be pinned tabs that won't be closed or replaced automatically, and unpinned tabs would be replaced by new notes...

**Comment by nathanlesage** [comment]
> aybe there could be pinned tabs that won't be closed or replaced automatically

Yeah, but PLEASE later :D Not another feature for 1.7! But yeah, the always-save-thingy is already more or less implemented, I'd more or less only need to implement this also on every … tab-action, basically... should be a no-brainer. And then use a "transient"-flag, aka close if unmodified, keep if modified?

**Comment by Zverik** [comment]
Of course, pinning tabs is a bit too much for 1.7 :)

After you do autosaving, it would not be possible to have an unmodified note on opening another file — so the current tab would always be reused (or not, depending on settings or #817). So it would be the first option.

**Comment by nathanlesage** [comment]
Mhmh … I'm currently inclined to just ship 1.7 with a transient behaviour and then maybe add more options later. I'm currently very much in favor of just having the 1.7 get stable so that I can have some vacation hehehe

**Comment by nathanlesage** [comment]
Alright, here's the current state: I've now simply decided to implement transience for tabs pretty much the way VSCode does this. Let's see what the next beta yields from a UX perspective.

**Comment by jchalifour** [comment]
Hello, I've been following the discussions on the transient tabs and I think I understand from the beta 13 changelog that transient tabs are the expected behaviour? If I understand that correctly, then I believe they might not be functioning that way on the Linux AppImage. I've been looking during the last couple betas but so far, every time I click a file it opens in a new tab regardless of whether I've modified anything in it.

**Comment by nathanlesage** [comment]
> I've been looking during the last couple betas but so far, every time I click a file it opens in a new tab regardless of whether I've modified anything in it.

The behaviour needs to be described in the docs as well, but unfortunately my days also only have 24 hours …

But you are right, I forgot to make a certain way of opening files transitive — namely folloiwing links within documents. The file list tabs are transient.

**Comment by jchalifour** [comment]
Oh sorry, I guess I didn't explain well. I was clicking on a file, in the file list and then that opens in a new tab each time. I guess I wasn't sure if it was useful to report this or not because I'm not entirely certain if that is supposed to happen.

**Comment by nathanlesage** [comment]
Ah, well transiency is handled rather conservative, that is: A tab is only replaced with a new file, if it is transient and also the currently active tab!

**Comment by jchalifour** [comment]
I think I understand that and am pretty sure then that it's behaving differently. Here are the steps I took. 1. Opened Zettlr 1.7.0-beta.13
2. clicked a file from the list on the right-side.
3. clicked a different file from the list on the right-side (Zettlr opened it in a new tab).
4. tried putting the cursor in the opened file tab but not changing anything
5. clicked a different file from the list on the right-side (Zettlr opened it in a new tab).

But! It just occurred to me to try something. I have my sidebar mode set as "Combined". I just tried changing it to "Expanded" or "Thin" and in those two cases, the transient tabs do work. It's only when it's in the Combined form that it always opens a new tab.

**Comment by nathanlesage** [comment]
> But! It just occurred to me to try something. I have my sidebar mode set as "Combined". I just tried changing it to "Expanded" or "Thin" and in those two cases, the transient tabs do work. It's only when it's in the Combined form that it always opens a new tab.

Aaaaaaah, okay, I withdraw my previous statement: I forgot it TWO ways of making them transient =D

**Comment by nathanlesage** [comment]
Fixed now in upstream
