### ISSUE TITLE
diable markdown or use restructerd tex 

### ISSUE THREAD

**Issue by manisabri** [Zettlr/Zettlr#881]
Markdown is a pain I like to use rst or completely disable it  and just have simple text with ID and etc

**Comment by nathanlesage** [comment]
If you do not like Markdown, and like to use rST or plain text, I'd like to kindly point you to Google, where I am sure you will find many editors that support rST or don't include syntax highlighting at all! Zettlr is a Markdown editor.

**Comment by manisabri** [comment]
yeah, I liked the ID link stuff but I guess ctag and vim will do.

**Comment by manisabri** [comment]
"kindly" checkout sphinx-reload and a text editor
