### ISSUE TITLE
Strange Formatttng for Code Block after Dash

### ISSUE THREAD

**Issue by dcfrankel** [Zettlr/Zettlr#882]
## Description
If you enter a dash `-` directly after a Github Markdown style code block it temporarily makes the code blocks formatting get messed up (increases the font size drastically). Attached is a gif showing the behavior. Thanks again for all your hard work on Zettlr!

## Reproducing
Create a code block with some text in it and then leave the block and enter the dash character.

## Expected behaviour
Retain correct code block formatting.

**Screenshots**
![2020-06-05 16 24 04](https://user-images.githubusercontent.com/57853028/83919924-a6233d80-a749-11ea-9eba-4a96f8a178ef.gif)

## Platform
 - OS and version: MacOS Catalina 10.15.4
 - Zettlr Version: 1.6.0
 - Screen Resolution: 2560 x 1600

**Comment by nathanlesage** [comment]
Aaaaaaaah, it's an error in the Setex header class detection! Thanks for finding out, I'll have a look!

**Comment by nathanlesage** [comment]
And here we go!

**Comment by dcfrankel** [comment]
Awesome, thanks for looking!
