### ISSUE TITLE
[ENHANCEMENT] render divider as line

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#883]
## Description
Render `***` as a straight line. 

Other markdown editors, including GitHub do this and it really helps for having a visual distinction between sections. With so much other stuff being rendered, I can't imagine that this would lead to problems, wouldn't it?

It could potentially also be included to the `Display` options.

**Comment by nathanlesage** [comment]
Hmhmhm … I'd have to think about it. The more Zettlr grows, the more I'm convinced of the WYSIWYM-semi-rendered preview it does, so adding new elements to be pre-rendered needs to be considered. Do you feel like the divider is too less visible? If so, do you have screenshots indiciating situations where it would indeed be better to have a dividing *line* instead of the three asterisks?

**Comment by PhilHem** [comment]
![image](https://user-images.githubusercontent.com/34508934/83941880-23ed5480-a7ef-11ea-82c2-e68c426e28e8.png)

In this case, I use asterisks as bullet points for an unnumbered list, as well as a divider for different literature sources. When both these things come together, a visual distinction is not very visible. It could also be argued, that the bullet points could actually be rendered as such, but I'd think of the divider as more important.

**Comment by nathanlesage** [comment]
I see what you mean!

Concerning rendering bullet points: This'll probably wreck CodeMirror (or my sanity), so a horizontal rule would be more appropriate :D

**Comment by PhilHem** [comment]
Cool! As far as the pre-rendering goes, a horizontal rule would also be closer to the rendered output in HTML and LaTeX.
All in all, I really like the pre-rendering! This would just make it a tiny bit better :)

**Comment by nathanlesage** [comment]
Hey, I just realized that there is no need in visually rendering this element: You can just repeat the dividers for as long as you wish. This aligns much better with the philosophy of Zettlr to retain as much formatting as possible, and henceforth the effect of having a visual divider for the whole line is easily achievable without the need for a specific rendering element. Hence, I'd like to leave it just as it were! I hope that's okay for you! :)

**Comment by PhilHem** [comment]
Hah, this makes absolute sense :)
