### ISSUE TITLE
[ENHANCEMENT] Vim custom keymap

### ISSUE THREAD

**Issue by AlexandreDubray** [Zettlr/Zettlr#884]
## Description
At the moment we can select vim as editor thanks to #683 but it doesn't seems that there is a "out-of-the-box" way to add custom mapping.
Being able to import our customs key mapping would be a huge plus when writting (with time, you get a lot of muscle memories).

## Proposed Changes

It looks like codemirror does not handle the import of `vimrc` files, but as pointed out here https://github.com/codemirror/CodeMirror/issues/2840 it should be possible to define such keymap via some js.

If the input mode is selected as vim, then it would be nice to have some places where we can either
1) Define some keymap that would then be translated into js
2) Link our vimrc configuration file that would be parsed and translate the keymap in js (I don't know how hard it would be though)

## Caveats

I guess that we would need to check that the bindings do not interfer with the initial bindings it Zettlr.

## Additional Information

I'm willing to put the efforts to add this but I want to first discuss if it is possible, and in which way to do it:-)

**Comment by nathanlesage** [comment]
This goes some way of what others have pointed out who wanted to override keymappings with their own keys, sooooo … while I can certainly see that introducing the vim mode will in fact awaken this desire, a first step would be to see through the issue list where other people want some custom keymappings in some way. Then we'd have a basis to begin thinking about how to satisfy this with the least effort and more centralised way. While I can see the reason of importing `.vimrc`-files, I personally would rather opt for a one-size-fits-all-solution (that is: Override them within the settings) instead of adding another way to import key bindings (which of course means duplicate work for vim-users, but I would assume that this is only a one-time-effort, as those keybindings are not necessarily going to change often, would they?)

**Comment by AlexandreDubray** [comment]
Ok I see the idea. So basically it need to be done in two steps:
1) General custom bindings
2) Integrate vim bindings in it

I looked over the opened issues and it doesn't (or I did not see it) looks like someone is working on that or have proposed some kind of design for it? Do you have already think of how you would want it?
I guess that the most straightforward way would be a new tab in the parameters

(PS: I think that you are right for the `vimrc` files. The bindings should not changed that much over time :-) )

**Comment by nathanlesage** [comment]
> I guess that the most straightforward way would be a new tab in the parameters

Hmmmm … or a completely new dialog (like with the tag manager)? I'm always a little bit unsure about whether to stuff something into the general preferences or create their own dialog for that … (after all, the source file for the preferences is already at an insane length … \*looks it up\* over 900 lines :D)

In general, I think it should only be one step, basically a two-column-table with "funtion" on the left and an input for the key binding on the right. The highly problematic aspect I fear will occur is how to actually customize the vim keybindings in CodeMirror. As I don't use them myself, I haven't yet gotten the time to look over how its actually implemented …

**Comment by AlexandreDubray** [comment]
> after all, the source file for the preferences is already at an insane length … *looks it up* over 900 lines :D
Well it certainly start to become a big file ^^.

I see what you have in mind. I'll try to dig into the code and see how it goes.
As for the vim keybindings I should say for references (first I will concentrate on the normal bindings) that they seem to be implemented there https://codemirror.net/keymap/vim.js

**Comment by nathanlesage** [comment]
> that they seem to be implemented there https://codemirror.net/keymap/vim.js

Yeah, this is what Zettlr includes in order to enable the vim mode! But … I've just had a look at that file, and holy hell — over 5,000 lines 😨  This is going to be quite some work I guess …

P.S.: Something I also just remembered: The sublime-keymap also defines some cool functions that Zettlr currently not implements, we could _also_ think about adding them to such a custom keyboard manager itself so that users can activate them as they need them … so many possibilities (and so much work :D)

**Comment by ianhi** [comment]
Hiya, Just discovered zettlr and love it already (vim mode was one of the requirements for me)!

@nathanlesage vim mode in codemirror is indeed huge! But fortunately they expose an api for things like key remappings. I actually I recently made a jupyterlab (also uses codemirror) extension that enables a basic vimrc for vim mode: https://github.com/ianhi/jupyterlab-vimrc that should hopefully be helpful for implementing this here. For example these lines handle the codemirror equivalent of `imap`  https://github.com/ianhi/jupyterlab-vimrc/blob/caa2bad1fa36bce044d59dda2bd7e6507b1d92be/src/index.ts#L35-L40

There are some restrictions with `noremap` commands I detail in the readme but it works pretty well for some basic keyremappings. I took the approach mentioned here of having a settings file and then parsing it and using the appropriate codemirror commands. So for me a settings file would like this:
```json
{
"inoremap": 
    [
        ["ii", "<Esc>"],
    ],
}
```
@AlexandreDubray If you work on this I'd be happy to try to help with understanding the codemirror vim api.

**Comment by ianhi** [comment]
Also the relevant documentation is here: https://codemirror.net/doc/manual.html#vimapi

**Comment by AlexandreDubray** [comment]
@ianhi Thanks for the tips, will definitely check-out this API:-).

I am indeed working on this right now, a WIP PR is open. First I'm adding a way to modify the general keybindings of Zettlr, and then I'll worry about the Vim bindings ;-) (so that we have a unified way to handle the mappings).

**Comment by nathanlesage** [comment]
Hui, didn't know about that `map`-command as well. But that could help explain the 10.000+ lines of code in that monstrosity of a plugin :D 

I'm looking forward to seeing the PR, however!

**Comment by faviobecker** [comment]
- I know it's 2023, but how is this one progressing?
- Has there been any solutions to customising the vim keymap?
- If not, is there anything I can help with? _(famous last words)_

**Comment by nathanlesage** [comment]
> * I know it's 2023, but how is this one progressing?

Not at all, because it's closed? Also, GitHub should've told you to "consider opening a new issue instead of leaving a comment here"; which might've brought you to issue https://github.com/Zettlr/Zettlr/issues/4643.

>     * Has there been any solutions to customising the vim keymap?

No

>     * If not, is there anything I can help with? _(famous last words)_

Look at issue https://github.com/Zettlr/Zettlr/issues/4643.

**Comment by faviobecker** [comment]
Thank you very much for educating a complete Github and Open Source newbie who was a Zettlr enthusiast in an efficient and German manner.

Danke

**Comment by nathanlesage** [comment]
I'm not sure if you read my response in an insulting manner, I hope not so, but in any case: gern geschehen 😅
