### ISSUE TITLE
[BUG] editor Vim mode with display night mode: Cursor not visible

### ISSUE THREAD

**Issue by BeatHubmann** [Zettlr/Zettlr#885]
## Description
While the functionality is there, the navigation cursor is not visible when using the Vim editor mode while in dark mode. Cursor visibility is fine when using Vim mode and not in night mode.

## Reproducing
Activate both night mode and Vim editor mode and try to navigate in Vim normal mode.

## Expected behaviour
Have a (grey) block cursor show your navigation position when not in Vim insert mode.

**Screenshots**

## Platform
 - OS and version: Mac OS 10.15.5
 - Zettlr Version: 1.7.0-beta.9 
 - Screen Resolution: 5120 x 2160

**Comment by nathanlesage** [comment]
Looks pretty much as if all that's needed is an additional CSS directive. Give me a second …
