### ISSUE TITLE
[Bug] Table of contents not working in v1.7.0-beta.9

### ISSUE THREAD

**Issue by PedroLima92** [Zettlr/Zettlr#886]
## Description
Table of contents button shows an exclamation point and is not working.
I've just updated from version 1.6. I didn't uninstall previous version... just ran the .deb on top of it.

**Screenshots**
A print of the icon
![image](https://user-images.githubusercontent.com/44039025/83955038-32566300-a825-11ea-80fc-e06511bbbcb3.png)

## Platform
 - Ubuntu 18

## Additional information
Here's a code snipet for the button I took from devtools. Hopefully it can help somehow.
```html
<div class="button show-toc" data-command="toc" data-content="{}" data-tippy-content="Show the table of contents"><clr-icon shape="indented-view-list" role="none"><svg version="1.1" class="has-solid " viewBox="0 0 36 36" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" focusable="false" role="img"><path class="clr-i-outline clr-i-outline-path-1" d="M18,6A12,12,0,1,0,30,18,12,12,0,0,0,18,6Zm0,22A10,10,0,1,1,28,18,10,10,0,0,1,18,28Z"></path>
                <path class="clr-i-outline clr-i-outline-path-2" d="M18,20.07a1.3,1.3,0,0,1-1.3-1.3v-6a1.3,1.3,0,1,1,2.6,0v6A1.3,1.3,0,0,1,18,20.07Z"></path>
                <circle class="clr-i-outline clr-i-outline-path-3" cx="17.95" cy="23.02" r="1.5"></circle>
                <path class="clr-i-solid clr-i-solid-path-1" d="M18,6A12,12,0,1,0,30,18,12,12,0,0,0,18,6Zm-1.49,6a1.49,1.49,0,0,1,3,0v6.89a1.49,1.49,0,1,1-3,0ZM18,25.5a1.72,1.72,0,1,1,1.72-1.72A1.72,1.72,0,0,1,18,25.5Z"></path></svg></clr-icon></div>
```

**Comment by PedroLima92** [comment]
Maybe I should've added

**Comment by PedroLima92** [comment]
Accidentally clicked the close button... sorry

**Comment by nathanlesage** [comment]
Thanks for reporting; I noticed this myself and wanted to fix this next week; but now I can't forget it! :)

**Comment by nathanlesage** [comment]
Whoops, already fixed that in some commit, just forgot to close this issue — will work again in beta 10!
