### ISSUE TITLE
[BUG] Creating new note fails when there are unsaved notes.

### ISSUE THREAD

**Issue by jadcx** [Zettlr/Zettlr#887]
Version 1.7.0-beta.9
MacOS 10.15.5

When creating a new note (Command+N) the note is not created if there are any unsaved notes open at the time.  The new note appears to be opened, the ID is auto-filled etc. But on pressing Enter nothing happens, and the new note is not listed in the directory.
Saving any unsaved open notes (or waiting for them to be auto-saved) resolves the problem.

**Comment by PhilHem** [comment]
Got the same Issue on OS X 14.4.0.

Doesn't seem to be new though. I think there were issues before regarding this with the 1.7.x betas.

**Comment by nathanlesage** [comment]
This should have been fixed by commit https://github.com/Zettlr/Zettlr/commit/15c2d92f4a275ff60123ab77d70d5ab645a54618

If the issue persists in the next beta, feel free to reopen this!
