### ISSUE TITLE
Table editor buggy on Mac

### ISSUE THREAD

**Issue by mtharrison** [Zettlr/Zettlr#891]
Just checking out Zettlr as an alternative to Evernote and just learning about Zettelkasten approach, however I've ran into a few issues creating my first note.

The table editor seems unusable in the version I have. Rows seems to randomly disappear meaning you lose the content, also the table controls render in odd place in editor window, appearing in top left. Also controls appear for rows which no longer exist.

This happened whilst trying to create my very first note, I didn't do anything special to trigger the behaviour (see gif)

![Jun-07-2020 23-33-33](https://user-images.githubusercontent.com/916064/83981643-9c4f3500-a917-11ea-95a2-7cccd1d302ea.gif)

## Platform
 - OS and version: MacOS Catalina 10.15.4
 - Zettlr Version: Version 1.6.0 (1.6.0)
 - Screen Resolution: 15.4-inch (2880 x 1800)

**Comment by nathanlesage** [comment]
I'll have a look!

**Comment by nathanlesage** [comment]
Fixed in the current develop branch
