### ISSUE TITLE
[BUG] Search functionality stops working after a while

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#895]
## Description

After using the search functionality for a few entries, it stops working. The loading circle gets stuck at a certain point. `F5` does not work. Only a restart of the software will.

What does work however is that when I enter a specific note name, it will open that note. Also the Wikilink suggestions work. 

## Reproducing

Honstely, I don't really know if it is reproducible on other systems, as there is not yet an entry for this issue, which is quite surprising to me. Might be interesting though if others chime in who got the same problem, but have not yet submitted the issue.

## Platform
 - OS and version: OS X Mojave 10.14.4
 - Zettlr Version: 1.7.9 Beta

## Additional information

There are no error messages in the DevTools console regarding this.

**Comment by nathanlesage** [comment]
Curious. I'll have a lookout for what this does …

**Comment by KarlClinckspoor** [comment]
Indeed, I have gotten the same bug a few times, but I do not know what caused it. It was always after working for some time though, like a few hours.

**Comment by nathanlesage** [comment]
Did it completely went dark after that with only a restart helping? And, does the console spit out some error or something …?

**Comment by KarlClinckspoor** [comment]
The circle search stopped at some random point. I think an F5 did solve it, but I'm not sure. I will be sure to keep a look out when this happens next time and look for anything weird in the console, and tell you if F5 worked or not. Also, this was on Win 8.1, but was on a previous beta. Sorry if I can't give you more info, I will in the future.

**Comment by nathanlesage** [comment]
Thank you very much! :) And don't rush, just keep an eye out for anything helpful, it's greatly appreciated!

**Comment by PhilHem** [comment]
Just tested this in 1.7.10, and the problem still persists. Not that I expected a fix, just for completeness :)

**Comment by nathanlesage** [comment]
Yeah, I need the time to test this myself, unfortunately my next weeks look like a nightmare :(

**Comment by KarlClinckspoor** [comment]
I had this problem right now, in the latest beta (13). I don't know what triggered exactly, but my system was under relatively high load from something. What I did was Ctrl-click a tag, when it started searching, and stopped. The progress pizza stopped almost at the end. The logs start with

```[13:58:41]	>>> IPC IN: force-open-if-exists
#NMR
[13:58:41]	Trying to run command through Application: force-open-if-exists
[13:58:41]	>>> IPC IN: file-search
hash: 2015271330
terms: [{"word":"#NMR","operator":"AND"}]```

And this continues on for a very long while (392 lines). From what I could tell, it's repeats of  

```[13:58:41]	>>> IPC IN: file-search
[13:58:41]	Trying to run command through Application: file-search
[13:58:41]	<<< IPC OUT: file-search-result
hash: -1447128194
result: []```

However, it ends with

```[13:58:41]	>>> IPC IN: file-search
[13:58:41]	Trying to run command through Application: file-search
[13:58:41]	Unknown command received: file-search```

Additional file searches result in

```[14:05:32]	>>> IPC IN: force-open-if-exists
test
[14:05:32]	Trying to run command through Application: force-open-if-exists
[14:05:32]	>>> IPC IN: file-search
hash: 2015271330
terms: [{"word":"test","operator":"AND"}]
[14:05:32]	Trying to run command through Application: file-search
[14:05:32]	<<< IPC OUT: file-search-result
hash: 2015271330
result: []```

And no actual results, just the entire list of files, no highlights.

Pressing F5 made it possible to search again, provided some color coded results, but the progress pizza got stuck again, in roughly the same spot. Logs end with `Unknown command received: file-search`. Closing and reopening fixed the problem.

OS: Windows 8
Zettlr 1.7.0-beta.13

**Comment by nathanlesage** [comment]
> The progress pizza

I'm going to remember that name for sure! :D

But sounds like an error in the corresponding command … I'll have a look!
