### ISSUE TITLE
[ENHANCEMENT] Fold top bar functions to drop down menu on small screens (1.7.x)

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#896]
## Description

**Fold the top UI bar options into a drop down menu, when screen width small.**

I often use Zettlr on a 13,3" Macbook and split the screen to use it in parallel to a pdf-reader or something. Currently, when the width of the programm is very small, the search bar gets compressed to an unusable size, while the buttons for functions remain the same, or in the extreme case, get pushed out of the window. 

## Proposed Changes

Ideally, I think the search bar should have a limit to which width it can be compressed, while the other functions should be put into a drop down menu, similar to the drop down menu that exists in the windows version of Zettlr. 

Should there be difficulty in implementing this responsiveness, I'd suggest always having the drop down menu present, as well as the buttons and simply deactivate them when the width constraints for the search bar are reached. This could pose an intermediary solution. 

Alternatively, instead of having a dropdown menu in the UI, the options could also be present in the regular OS X top menu.

**Comment by ploum** [comment]
Don't know if it's covered by this bug but, on my small screen, the "file menu bar" (which was not there in 1.6) is quite ugly (because the color is not related to Zettlr as it use system theme) and taking precious vertical space. Fullscreen is not even hiding the bar.

**Comment by nathanlesage** [comment]
@ploum are you on Linux?

There was somewhere this request to restore the previous appearance. I originally removed the Linux window decorations for a more consistent feeling, as many different implementations exist, but I figured that some GUIs look quite good with Zettlr. Now I just have to enable this via setting … so it's coming!

**Comment by ploum** [comment]
I forgot to mention that I'm indeed reporting this on Linux.

Thanks a lot for your time :-)

**Comment by nathanlesage** [comment]
Since I have now severely stripped down the toolbar, there is so much space that even on small displays the toolbar will use. (On a 13 inch MBP you can resize Zettlr to about a third of the screen width with no problems)
