### ISSUE TITLE
Inconveniency when saving new file without a folder

### ISSUE THREAD

**Issue by treborxy** [Zettlr/Zettlr#898]
## Description
When trying to save a new file without previously having selected a folder, zettler asks for selecting a folder - but does not offer a function to do so. So you have to get back to main menue, open a folder and so on. If you know how to use the workarround no problem, but a bit irritating...

## Expected behaviour
offer a file/folder dialog

## Platform
 - OS and version: Linux and Windows
 - Zettlr Version: 1.6
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
In almost any circumstance, a folder is selected, because the app doesn't support "de-selecting" folders, only selecting. So this is just in rare edge cases, and it's not that much of an inconvenience I'd presume. Considering the cost/benefit-ratio of implementing that I personally favour leaving it this way, because the instructions are clear!

**Comment by treborxy** [comment]
I agree, it might not be worth the effort, there are fields more interesting...
Anyway, to be complete: There are two cases. First start (immediately editing a new file) and after closing the last selected folder. For a experienced user almost never will happen, but for first time users its not unlikely.
And: the dialogue is a bit confusing: you are right, there is a message pointing out there has to be an open folder. But: simultaniously might reopen the dialogue "Save / Abort" whitch tends to lead you to an "Ostfriesen"- loop ;-)

**Comment by nathanlesage** [comment]
> but for first time users its not unlikely.

Absolutely, but there's a "first start guide" in the making that'll hopefully capture a lot of these edge cases …

> But: simultaniously might reopen the dialogue "Save / Abort" whitch tends to lead you to an "Ostfriesen"- loop ;-)

Yeah, I see what you mean! Honestly, to make the app completely "user-safe" would require an insane amount of work :D But if you wanna help out, good PRs are always welcome!
