### ISSUE TITLE
Brazilian Portuguese

### ISSUE THREAD

**Issue by OrionRandD** [Zettlr/Zettlr#899]
Could you add Brazilian Portuguese spellchecker?
And, perhaps, vim key-bindings?
Thx

**Comment by nathanlesage** [comment]
Hey,

thanks for opening up the issue! Vim keybindings will ship with 1.7; as for portuguese dictionaries: They won't work with the spellchecker we're currently employing (but you are able to [load smaller partial dictionaries](https://docs.zettlr.com/en/core/localisation/#install-new-dictionaries) just fine)
