### ISSUE TITLE
Add a way to create snippets

### ISSUE THREAD

**Issue by Ara0n** [Zettlr/Zettlr#90]
It would be nice to have a way to create snippets like in Sublime Text 3. You create them and once loaded they write your text and can be filled in some places that were specified in the snippet file.

**Comment by nathanlesage** [comment]
This sounds like a nice addition, I'll see to it!

**Comment by nathanlesage** [comment]
Now that the stale bot discovered this very old issue which has received literally no interaction in about one and a half years, I think I'm finally closing this for good. Most people seem to use stuff like TextExpander to insert snippets, and as the focus of this is more on the social scientist side of life, I feel like this can free me from a huge mental burden!
