### ISSUE TITLE
[FEATURE] Default Folders

### ISSUE THREAD

**Issue by ditServices** [Zettlr/Zettlr#900]
## Description

It would be nice to have the option to specify a default folder for new notes. 
I cannot seem to find a setting that allows this at present.

## Example Workflow

__Menu Setting__
Folder Path new default folder, For example /Inbox
Right Click desired folder and set as default.

**Comment by nathanlesage** [comment]
Zettlr by default (using `Cmd/Ctrl+N`-shortcut) stores new notes in the currently selected directory.
