### ISSUE TITLE
[ENHANCEMENT] Custom formatting for [[links]] upon linking

### ISSUE THREAD

**Issue by MushroomHunting** [Zettlr/Zettlr#902]
Hi there, I'm new to zettlr and and thoroughly enjoying the experience so would like to first say my thanks for this great project! I am not sure if this feature/enhancement has already been proposed or possible already so apologies if it has been addressed.

## Description
I would like to be able to customize the formatting of linked files when zettlr autocompletes a link.

For example, when i type [[]] and it brings up the dropdown list: [my_zettel1, my_zettel2, ..., my_zettelN] and then I select and press Enter on _my_zettel2_ . The current behaviour is that zettlr autocompletes the text as: **[[20200608143735]] my_zettel2**. I would like the ability to customize the formatting. For example, I could add custom code format: `<link_id> ($\color{blue}\text{<link_name>})$` where <link_id> corresponds to _[[20200608143735]]_ and <link_name> corresponds to _my_zettel2_. Thus, the resulting autocomplete by zettlr after pressing Enter looks like: **[[20200608143735]] ($\color{blue}\text{my_zettel2})$** and consequently would be rendered by the latex engine.

## Proposed Changes
It seems there is already a menu in Settings->Zettelkasten->"When linking files, add the filename..." in which such an option would be suitably placed. I would propose that there is a "custom format" option in which one would place their formatted text. At a bare minimum I think the placeholders for <link_id> and _<link_name>_ are required.

**Comment by nathanlesage** [comment]
Hey, thank you very much! :)

Unfortunately, while your idea is certainly interesting, it would be out of scope for the application, as this overly complicates the idea of linking. Wikilinks really are meant for internal usage, not necessarily for export, so I think we need to focus on other issues first!
