### ISSUE TITLE
Images with titles don't show

### ISSUE THREAD

**Issue by darahak** [Zettlr/Zettlr#903]
## Description
A placeholder is displayed instead of the actual image when a title has been added.

## Reproducing
Use the following syntax to add a title to an image: `![Alt text](/path/to/img.jpg "Optional title")`. The image appears when the title is removed.

## Expected behaviour
The editor should show the image and the title should show in the tooltip when the mouse is hovering on the image.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920 x 1080

Just started using Zettlr as my main Markdown editor and it's great, so thank you!

**Comment by nathanlesage** [comment]
Has already been raised on the forum and should only be a matter of adapting the image regex.

**Comment by nathanlesage** [comment]
Now they do!

**Comment by darahak** [comment]
@nathanlesage Awesome!
