### ISSUE TITLE
Feature: Styled Header Hashes

### ISSUE THREAD

**Issue by jcuenod** [Zettlr/Zettlr#91]
In Bear, the `md` hashes marking heading levels are hidden the moment the hashes clearly mark the line as a heading. In their place a discreet "H1" (or equivalent) mark appears. I think indentation is slightly affected by this. The moment the user deletes/backspaces the space between the hashes and the header text the hashes reappear to be edited.

I really like the way that Bear uses styles to hide the markdown wherever it's natural. I also really like that it's not an effort to "undo" this styling: that is, in some WYSIWYG editors, a hash turns into an `<h1>` but if you backspace at that point, the whole node disappears.

It would be great to implement something similar in Zettler.

**Comment by nathanlesage** [comment]
As already discussed in the CSS issue, it'll come with the next version! :)
