### ISSUE TITLE
[BUG] Zotero reference attachment will not open (1.7.10 Beta)

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#910]
## Description

Opening the referenced Zotero entries pdf does currently give the error message:

`Could not open Attachment. Is Zotero running?`

Zotero is running and the actual link is being rendered, so I suppose the `citeproc` does its job as far as pulling the bibliographic data. 

## Reproducing

Try opening an attachment. 

## Platform
 - OS and version: 10.14.4
 - Zettlr Version: 1.7.10 beta

**Comment by PhilHem** [comment]
Oh, in fact, the reference and attachment window does not list the rendered references as actual citations. They simply don't show up.

**Comment by nathanlesage** [comment]
> the reference and attachment window does not list the rendered references as actual citations

Different error, will have a look at that as well!

**Comment by PhilHem** [comment]
Wouldn't it make sense to keep this one open and rather add another issue for that?

**Comment by nathanlesage** [comment]
What do you mean? "Zotero reference attachment will not open" is exactly fixed right now. The bibliography in the sidebar needs fixing, there's no need for another issue for that because it affects me as well, so I can't forget it!

**Comment by PhilHem** [comment]
Ahh, I got it now. Didn't realize you actually fixed it that quickly :D

**Comment by nathanlesage** [comment]
Ehe, well it was some stupid mistake of mine, so easy to fix :D Whenever I close something with a commit message (as you can see in this issue) this means the issue is fixed. If an issue is only partially fixed, what I'll do is something like "cf. issue #xxx" or something to not close it ;D
