### ISSUE TITLE
[BUG] Zettlr will create duplicate files without notification (1.7.10 Beta)

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#911]
## Description

Previously, Zettlr posted a warning when one was to create a duplicate note. Right now, it will simply create it without a warning, causing some other issues down the line, regarding internal links. 

## Reproducing

Create a `.md` file with the same name as another one.

## Platform
 - OS and version: OS X 10.14.4
 - Zettlr Version: 1.7.10 beta

## Additional information

I think this is acutally a pretty critical issue, because I have lost some files because of it. Zettlr will do all kinds of weird stuff when editing one of the two notes.

**Comment by nathanlesage** [comment]
> Previously, Zettlr posted a warning when one was to create a duplicate note.

Ah, I remember that I removed some translated strings for that, but apparently I forgot to re-add them. I'll have a look later on

**Comment by nathanlesage** [comment]
Fixed in https://github.com/Zettlr/Zettlr/commit/392049dbea0d078db7c55e86ae0e4407bb97ca49

**Comment by PhilHem** [comment]
@nathanlesage Thanks so much. This is driving me crazy every day a few time 😄

**Comment by nathanlesage** [comment]
*has been 😄
