### ISSUE TITLE
[Bug] Preferences dialog missing text resource (v1.7.0-beta.10)

### ISSUE THREAD

**Issue by derwok** [Zettlr/Zettlr#914]
v1.7.0-beta.10, Windows 10

The preferences dialog has a missing text resource.
Checked in English and German - both affected.
So it seems not to be a translation issue?

![image](https://user-images.githubusercontent.com/4393698/84298227-0ef62580-ab4f-11ea-9210-ed54c14c80d3.png)

**Comment by nathanlesage** [comment]
Can't recreate — did you happen to deny network access to Zettlr? If so, this might explain it. Another solution would be to remove the translation data updates from the application data (`C:\Users\name\AppData\Local\Zettlr` if I'm not mistaken) and try restarting twice

**Comment by derwok** [comment]
Oh! OK. You're right.
Just checked on Linux v1.7.0-beta.10 - it looks good there.

Yes, my Windows version gives me a strange error on every start that I got used to ignore. Something like "bla bla certificate not available... cant connect to network". 
I was not aware, that even if I use one of the four "main languages" (German / English), that there needs to be resources downloaded? And in my case only this one string seems broken. All other Ui looks good.

I can dig out the proper error message above once I'm back on Windows.

So, if its this rare edge case, you may close this issue.
I thought its a general thing.

**Comment by nathanlesage** [comment]
> I was not aware, that even if I use one of the four "main languages" (German / English), that there needs to be resources downloaded?

Yeah, these are basically the updates the app needs to pull from Zettlr Translate. My plan is to migrate this stuff in the future that all languages are always shipped with the app!

> And in my case only this one string seems broken

Because there was only one added in the meantime!

> I can dig out the proper error message above once I'm back on Windows.

Alright, if it looks like it might have something to do with Zettlr itself, feel free to get back to me!

**Comment by derwok** [comment]
The error message on launch looks like this:
![image](https://user-images.githubusercontent.com/4393698/84384192-e5400b80-abed-11ea-9474-fa738bdb5029.png)

Can't think of a reason why this shows up.
My machine is connected to the internet properly...

**Comment by nathanlesage** [comment]
According to [this thread](https://community.letsencrypt.org/t/how-fix-unable-to-get-local-issuer-certificate/56700/11), there might be an issue with using certain proxy servers to connect to the internet, so maybe that's the cause!
