### ISSUE TITLE
[BUG] PDF export fails when image scaling parameter is provided

### ISSUE THREAD

**Issue by obehrto** [Zettlr/Zettlr#915]
## Description
PDF export fails when an image scaling parameter such as width=25% is provided. Other exports such as docx and HTML work and produce the expected image output. The error message is:

`Error producing PDF.
! Argument of \Gin@iii has an extra }.
<inserted text> 
                \par 
l.299 }`

## Reproducing
Include an image as, for example, `![](image.png){width=25%}` and generate PDF.

## Expected behaviour
Generate PDF with expected image scaling.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.70-beta.9

**Comment by nathanlesage** [comment]
Would you mind testing this out with the [default Pandoc template](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex)?

**Comment by obehrto** [comment]
Yes, when using the default.tex template it works perfectly and the scaling is correct. I am also using `--filter pandoc-xnos` if that is of interest.

**Comment by nathanlesage** [comment]
> es, when using the default.tex template it works perfectly and the scaling is correct.

That's good; means I have to update Zettlr's default template. If anybody wants this to be quicker, feel free to research which changes need to be done and feel free to submit a PR!

**Comment by nathanlesage** [comment]
Fixed in PR #928
