### ISSUE TITLE
[BUG] Freezing when trying to open an .md file with Zettlr

### ISSUE THREAD

**Issue by henrique9i** [Zettlr/Zettlr#916]
## Description
When trying to open a file outside of Zettlr, it froze completely, no buttons work.
Closing and reopening the program didn't solve it either.

## Reproducing
Windows Explorer > Righ click on .md file > Open whit Zettlr
![Steps](https://user-images.githubusercontent.com/62220974/84311762-3f7f9480-ab3a-11ea-8e0c-fae54388b48e.png)

## Expected behaviour
Show the file content!

**Screenshots**
![Frozen](https://user-images.githubusercontent.com/62220974/84311837-5faf5380-ab3a-11ea-8663-dd4b3042b7ab.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.0 beta 10
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
This should have also been closed by the last commit https://github.com/Zettlr/Zettlr/commit/488ea601eb7c56fa50c624cfe8be49ae65ac3f8b

If it's not fixed in the next beta, please feel free to reopen it.
