### ISSUE TITLE
[BUG] Copy via context menu not working

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#919]
## Description
When right-clicking a word, and then selecting "Copy" in the context menu, the word is not copied.

When selecting "Cut" instead, the word is removed, but not copied either.

## Reproducing
1. Right-click a word
2. Select "Copy" in the context menu
3. Try pasting (either with `CTRL-V` or via context menu)
4. Only white space gets pasted

## Expected behaviour
The selected word should be copied to the clipboard.

## Platform
 - OS and version: Linux Mint 19.2
 - Zettlr Version: 1.6, 1.7.0-beta.10
 - Screen Resolution: 1920x1080

## Additional information
When first selecting the word manually by double-clicking it, and _then_ copying it via the context menu, the copying works.

Also, when right-clicking the word, then clicking somewhere else (the word is still highlighted), then `right-click --> Copy` works.

**Comment by nathanlesage** [comment]
This sounds a little bit like an Electron problem — it works sometimes, but not always, interestingly

**Comment by nathanlesage** [comment]
This almost seems like race condition, because the "select word under cursor"-command apparently takes longer (?) than for the popup menu to appear, hence there's nothing selected while the menu is open, it only displays as if. But other than that, no idea. What works is as you explained, you need to manually select or click twice. However, the shortcuts work …

**Comment by PhilHem** [comment]
I tried this and can't confirm the Issue on OS X 10.14.4.

**Comment by nathanlesage** [comment]
Can't confirm the reproducibility, or the issue at all?

**Comment by PhilHem** [comment]
Isn't this one and the same? Using the context menu for copy and pasting worked in multiple instances and never didn't work for me.

**Comment by nathanlesage** [comment]
Mh, the thing is that what I realized is that the "select word under cursor"-command that selects a word on right-clicking doesn't work on the first instance, whereas selecting stuff first and THEN right-clicking works always like a charm.

**Comment by PhilHem** [comment]
Well this I can confirm. Never crossed my mind to do it like that, but I guess it's a thing.

**Comment by nathanlesage** [comment]
I have already run extensive tests, and this is an issue with CodeMirror itself, which is unable to process a copy event in this case. We'll have to abandon this until CodeMirror.Next is being implemented for Zettlr.

Mitigation until then: copy the word by selecting it with a double-click prior.
