### ISSUE TITLE
Clicking the link does not open nonexisting target

### ISSUE THREAD

**Issue by a-gerescher** [Zettlr/Zettlr#92]
## Description

Nonexisting links to another local note do not open a new note with editor opened.

## Reproducing

`[Note about javascript](./Javascript.md)` or `[[Javascript]]` do only work if i have the corresponding file already on my disc.

## Expected behaviour

Linkhandler can handle the creation of notes.

**Screenshots**

## Platform
ALL

## Additional information

Is it possible to change this? Zettlr would be the only software i know on Windows where it is possible to do this.

**Comment by a-gerescher** [comment]
Sure. Opt in would be better. My own workflow is at the moment -> 

* Open Text editor 
* Create new file 
* write something 
* write a link to a new note
* save
* Create file with the filename corresponding to the link
* Write the `# Header` with the text corresponding to the link
* Repeat above steps every 30 Seconds.

😳

Maybe the steps help you to make a solid / mostly working implementation of this feature if you code it.

**Comment by nathanlesage** [comment]
Oh boy, this definitely sounds like a hassle.

I'll see to it. Additionally, I sense there could be potentially a need for "New File"-Templates that newly created files are pre-set with some information?

**Comment by a-gerescher** [comment]
It definetly is a hassle. But nothing you can't handle with a few commands.

Sure, a template would be nice, if it doesn't make it more complicated.
Potentially users with your ID-Feature would like a header with the ID, some a dateheader like `%y-%m-%d` some the link they used in the file where you clicked on the link.
Depends on personal taste.
