### ISSUE TITLE
Tabs with names in italic cannot be chosen

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#933]
Sometimes I wake up to tab names being in italic font, like this:

<img width="664" alt="Screenshot 2020-06-16 at 11 17 03" src="https://user-images.githubusercontent.com/766031/84752228-25283980-afc6-11ea-8afd-2a45909439f3.png">

The style restores to normal after modifying and saving a note. But before that I cannot switch to such tab by clicking on it from another note. I can open it by clicking on a note name in the sidebar though. If I close the tab and then open the file, its name is still in italic.

1. Please fix the tab switching.
2. What does this style even mean? It's not described in any popups.

_Zettlr 1.7.0-beta.11, macOS 10.14.5_

**Comment by nathanlesage** [comment]
You just found transient tabs! Each tab is now transient by default if you open a new note, and becomes "fixed" if you modify it.

However:

> But before that I cannot switch to such tab by clicking on it from another note.

This is not good (I've never attempted that)
