### ISSUE TITLE
[ENHANCEMENT] Center Align $$$$ environments

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#936]
## Description

When using the `$$$$` environment, other markdown editors, as well as LaTeX itself align the contents center. I would love this in the Zettlr render as well, as it helps readability and comes a little closer to final LaTeX export.

I have tried modifying the css a little bit to get what I want and stumbled upon the fact that the LaTeX math mode is in the same codemirror div as the paragraphs, and is therefore tied to the alignment of that. 
Would it be possible to have `$$$$` create a div around itself that has the screen width  and aligns its contents center?

I wouldn't know how to do it myself, but maybe thats a piece of cake for somebody else :)

**Comment by nathanlesage** [comment]
Please see #648 for progress on this.
