### ISSUE TITLE
[ENHANCEMENT] Hidding toolbar and document tab while in distraction free mode

### ISSUE THREAD

**Issue by Amar0ks** [Zettlr/Zettlr#939]
## Description & Proposed Changes
While you are in the distraction free mode the toolbar and the document tab should be hidden.

## Caveats
Possibly the visibility of the time could still be needed.

**Comment by nathanlesage** [comment]
Implemented! The toolbar is a bigger issue that needs more addressing, but better not for 1.7!

**Comment by Ellipsine** [comment]
I would like to have an option to hide the top bar while I am in distraction free mode (Cntr + J). In addition with the middle page cursor, the software would become perfect.

**Comment by nathanlesage** [comment]
As indicated, here we go again!

**Comment by Ellipsine** [comment]
It would be great ! With typewriting and hiding interface, I could stay on Zettlr from the beginning to the end without leaving, switching, loosing work. The way Zettlr allows me to organise my work is helpfull, so thank you for the work you already made.
