### ISSUE TITLE
Alphabetical sorting of note titles separate for filename and YAML titles

### ISSUE THREAD

**Issue by nabusch** [Zettlr/Zettlr#941]
## Description
Zettlr shows a list of all notes in a folder in the left side pane. When sorting this list of notes alphabetically, the sorting is done separately for:
- Notes whose title is defined in the file name (i.e. whose ID appears in the file content);
- Notes whose title is defined in the YAML header (i.e. whose ID is the file name).

## Reproducing
Put three notes in a folder:
1. a note with filename "a note.md" and some ID in the note text.
2. a note with filename "z note.md" and some ID in the note text.
3. a note with ID as filename a "title: b note" inside a YAML header in the note text.

Note 3 should be sorted in between 1. and 2. but will be sorted separately.

## Expected behaviour
All notes should be sorted alphabetically, irrespective of how their titles are defined.

**Screenshots**
![sorttitles](https://user-images.githubusercontent.com/6177572/85010088-b8e13d80-b15f-11ea-8e0a-d6942df13a46.jpg)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.0-beta.11
 - Screen Resolution: 2560 x 1440

**Comment by nathanlesage** [comment]
Reason: the sorter ignores YAML headers (and H1) as of now. Will have to amend the corresponding function.

**Comment by nathanlesage** [comment]
Fixed!

**Comment by nabusch** [comment]
Awesome! This may look like just a small thing (from a user perspective, I honestly don't know how hard it was for you to fix it) but this really helps with my workflow! Thank you Hendrik!

**Comment by nathanlesage** [comment]
Thankfully, it was rather easy, and I was able to fix a few other things as well …
