### ISSUE TITLE
Opening links with Ctrl+Click multiplies cursors

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#942]
0. Use Linux or Windows.
1. Open a note with links to other notes.
2. Ctrl+Click on a link to open another note in a new tab.
3. Switch back to the first note and Ctrl+Click something else.

Expected: nothing, a cursor on the last clicked link.

Got: multiple cursors, including one for each link.

After #875 and 71d1ab972f0783fb5dd8e6645fa2374a1e06afdd, we open links not by Alt+Click (which indeed was not intuitive), but with Ctrl+Click or Cmd+Click. While the latter works fine on macOS, Ctrl+Click is for adding more cursors — see #471. That issue confirms that this behaviour is often unexpected.

This wasn't an issue before fixing #741, since all cursors were reset after switching tabs then.

I propose to disable multiple cursors functionality. I don't see how it helps with keeping notes.

_Zettlr 1.7.0-beta.12 from this hour's develop branch, Fedora Linux 32_

**Comment by nathanlesage** [comment]
Sometimes it indeed comes in handy, but you are right that we should prevent this from happening when using `Ctrl` to open a link!
