### ISSUE TITLE
[ENHANCEMENT] Forward wikilinks to "main zettels"

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#944]
Oftentimes, I find myself making Zettels that simply refer to another "main Zettel", because they are one and the same thing. 

Say I have a Zettel `Hamburger` and it links to the Zettel `Bun` which in essence is a `Roll`, I might state `See [[Roll]]` within `Bun`. 
I still think it is important to have `Bun` as a linkable object though. 
I think Wikis can do a similar thing. 

Also: Might there be a possible workaround for this already? Maybe via the IDs?

**Comment by nathanlesage** [comment]
I'm not sure I follow you …?

**Comment by PhilHem** [comment]
I'll use an example from the German Wikipedia: 

Enter `Reduktions-Oxidations-Reaktion`in the search bar. You will be forwarded to `Redoxreaktion` automatically, because it's considered an alias.

**Comment by nathanlesage** [comment]
Ah … but how would you implement this? I mean this clearly isn't an enhancement, it's quite big enough to be a standalone feature, and probably a difficult one as such

**Comment by PhilHem** [comment]
Hmm, as it currently stands, Zettls have the ID adresses. Usually, when I first create a Zettel, the first line consists of the ID. Just from a user perspective, there could possibly be a syntax like `20200623091809->20200623091911`

Let's take the example in my last previous comment:



1. Within `Reduktions-Oxidations-Reaktion`, I have specified `20200623091809->20200623091911`. 

The left ID is the ID of `Reduktions-Oxidations-Reaktion`, the right ID is the ID of the alias `Redoxreaktion`.

2. What comes now would be probably a matter of taste, so I'll just write one solution:

Say, I create the note `Oxditation`.

Because now the word `Reduktions-Oxidations-Reaktion` is the first word that comes to my mind, I will want to link to it via Wikilink to it. 

When I call the drop-down menu via `[[]]`, I will find `Reduktions-Oxidations-Reaktion`.

If I select this now, instead of replacing my entry within the square brackets with
`[[20200623091809]] Reduktions-Oxidation-Reaktion`, it will replace it with:
`[[20200623091911]] Redoxreaktion`, and therefore link to the previously specified alias.

***

While there are different ways to implement the last step, I think the beauty of this solution is that in the end, the syntax within the Zettels will stay pretty much the same, except for the alias specifier. 
I wouldn't think of it as a distinct feature of its own, and rather an extension of the already implemented linking system.
