### ISSUE TITLE
[Enhancement] The possibility to select Doc Templates for pandoc

### ISSUE THREAD

**Issue by Amar0ks** [Zettlr/Zettlr#945]
## Description

With `$ pandoc test.md --reference-doc=Template-Basic.docx -o OUTPUT.docx` it is possible to style your doc output. It is way more easyer to style a doc than creating a latex template.

## Proposed Changes
The possibility to choose a Doc template beside a TEX template.

**Comment by nathanlesage** [comment]
With a few addendums to the settings this should be not at all problematic!

**Comment by nathanlesage** [comment]
For 2.0 we have switched to defaults files which allow you to select reference docs comfortably.
