### ISSUE TITLE
Alt+Click not opening internal linking target files.

### ISSUE THREAD

**Issue by lenciel** [Zettlr/Zettlr#946]
## Description
I created a folder and generated files as suggested but Alt+Click cannot open internal linking target files.

I also tried Ctrl+Click or linking with file name (no extension) after reading the docs once again but it is not working.

## Reproducing

1. Create a testing folder.

2. Create two files with generated IDs.

3. Type '[[' in one file will suggest the other file ID (which is what I expected)

![image](https://user-images.githubusercontent.com/390648/85249059-55b81980-b485-11ea-96d6-52dabff85192.png)

4. Alt click on the internal link, nothing happened.

![image](https://user-images.githubusercontent.com/390648/85249212-b0ea0c00-b485-11ea-96e5-d7f43e875fa7.png)

## Platform
 - OS and version: MacOS 10.15.5
 - Zettlr Version: 1.6.0
 - Screen Resolution:3840 x 2160

## Additional information
Where can I see the log?

**Comment by nathanlesage** [comment]
This is curious. Would you mind trying out the latest beta? We've switched to Cmd/Ctrl+Clicking all targets within Markdown files, and it works for me (on macOS) — would you mind verifying that?

**Comment by lenciel** [comment]
I can confirm the latest beta version works (Version 1.7.0-beta.13).
