### ISSUE TITLE
Adding tabs can add invisible zero-width characters

### ISSUE THREAD

**Issue by sebastienvercammen** [Zettlr/Zettlr#948]
## Description
Rather than adding a tab character, occasionally the editor seems to register the tab keypress but adds a zero-width (invisible) character where the tab was supposed to be. It doesn't take up any width but in order to remove the text before it (or navigate to the text before it) you need to press the backspace/arrow key once for each invisible tab character.

## Reproducing
1. Make a list anywhere, of at least one entry
2. If you position your cursor before the first text character (not the star for Markdown list syntax, the actual text) of any entry in the list, and press tab, it will add one extra indentation to the entry, making it an indented ("second-level") list

This is regular behavior. In order to break it:

1. Make a list anywhere, again with two entries
2. Position your cursor before **the star** (denoting the list syntax) of any entry
3. Press tab

The tab character will be added invisibly. There'll be a zero-width character, but no tab indentation will be visible.

Keep pressing tab to add more invisible characters, breaking it even more. Two invisible tabs seems to turn it into code formatting.

Copy/pasting this snippet into Zettlr also works:
```
* No tabs
	* One tab
			* Three tabs

			* Three tabs, separate list
```
![image](https://user-images.githubusercontent.com/4874269/85333313-a8232580-b4d9-11ea-86af-d12eec53c0eb.png)

And the following snippet renders two flat one-level lists, but still has the invisible characters when you try to navigate past them:

```
* No tabs
	* One tab
		* Two
			* Three tabs

			* Three tabs, separate list
```
![image](https://user-images.githubusercontent.com/4874269/85333285-9e012700-b4d9-11ea-99f4-7529b3b90e75.png)

This has affected other things as well, but this is the only way I know of to break it consistently.

## Expected behaviour
Press tab = add a visible tab character for indentation.

## Screenshots
See samples above.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Wanna know an even better thing? Just try to add more and more list tokens in front of it and watch the magic happen, e.g.: `- - - - - list item`

It's something we need to do additional work on (the list indentation where we perform some magic to get correct line indentation with wrapped list items), I'll leave it to @tobiasdiez once he returns from his holidays!

**Comment by tobiasdiez** [comment]
I had a look at the code, but had trouble locating the problematic piece. @nathanlesage can you point me to the code that handles the tab insertion?

**Comment by nathanlesage** [comment]
> can you point me to the code that handles the tab insertion?

https://github.com/Zettlr/Zettlr/blob/1ea99c386fcf0c47fd993f6f7f6d447380a79cc1/source/renderer/zettlr-editor.js#L325-L360

Somewhere here it's adding more and more indent on the wrapper instead of just one, to me it looks like a small logical error

**Comment by sebastienvercammen** [comment]
Found one more thing related to lists. There's a way to make the list character appear left of the indentation for regular text:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/4874269/88166050-f2054580-cc16-11ea-8f19-b2739febc9cb.png">

And even move it into or past the renderer's limits:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/4874269/88165889-b10d3100-cc16-11ea-8c49-7f19b4b44fbc.png">

<img width="159" alt="image" src="https://user-images.githubusercontent.com/4874269/88166003-d601a400-cc16-11ea-8960-581848e7457e.png">

Copy/paste this:
```
Legend
* ^ Major
* = Medium
*  Minor
text
```

The issue is caused by the extra space before "Minor". Instead of moving "Minor" to the right, it moves the list character to the left.

Add more spaces = byebye list character as it flies off the screen.

**Comment by canpolat** [comment]
This may be related to #1097 in that fixing one may fix the other too.
