### ISSUE TITLE
[FEATURE] SVG support and Git Support and so much more?

### ISSUE THREAD

**Issue by AndreasS2501** [Zettlr/Zettlr#949]
Hi my name is Andreas, I'm from Germany and also a Software Developer. I want to use zettlr to write/continue my zettelkasten. Up until now I simply have a git repo with markdown files, where each commit roughly corresponds to a Zettel. 

Now I have also some SVG files in my repo how do I embedded them or display them in markdown with zettlr best or at all?

Also it would be nice to do create a git commit after I finish editing a single markdown file - a kind of incremental backup.

I also have various display/visualization demands which can not be meet by the given configuration options and I can't imagine I'm the only one.

## Description

So while the questions for SVG and Git are relatively straight forward I can imagine that the sheer endless customization demands put a heavy burden on the developers. 
So instead of simply begging for features what do you think about giving more control to the user so that he can actually do many things on his own.

I came across two projects that point towards an interesting direction regarding that :

1. lively kernel

https://lively-kernel.org/
https://github.com/LivelyKernel/lively4-core

2. cloxp (which uses lively kernel)

https://github.com/cloxp
https://cloxp.github.io/

## Example Workflow

If you are interested in the SVG/ Git features are can add a more detailed description of the imagined workflow later.

## Caveats

Changes in Culture do not easy fit in templates but are worth discussing IMHO 

## Additional Information

So what are your thoughts on that? I hope the issues is not a place to strange for such kind of discussion. If you have another "official" place for that. I'd be happy to take it furthere there.

**Comment by nathanlesage** [comment]
Hey Andreas!

> Now I have also some SVG files in my repo how do I embedded them or display them in markdown with zettlr best or at all?

Simply embed them as images, works the same as for PNG or JPEG.

> Also it would be nice to do create a git commit after I finish editing a single markdown file - a kind of incremental backup.

There are ideas floating around. Nothing concrete yet, but it'll come someday.

> I also have various display/visualization demands which can not be meet by the given configuration options and I can't imagine I'm the only one.

Zettlr is first and foremost a text editor, not so much a visualization tool, so it is to be expected that the chances of that will remain limited!

> So instead of simply begging for features what do you think about giving more control to the user so that he can actually do many things on his own.

So basically an API — while certainly an interesting idea I would want to further, there are good and valid reasons for opting against this, the most of it is to prevent a feature flood that'll make the app unusable. It's similar to the complexity issues arising when using VSCode or Atom, albeit the users of such IDEs are to be expected to cope with that easier. The target audience of Zettlr, however, is one that does not program or code, and that also is pretty silent here on GitHub, so the false illusion might appear that Zettlr is aimed at programmers/software developers!

> So what are your thoughts on that? I hope the issues is not a place to strange for such kind of discussion. If you have another "official" place for that. I'd be happy to take it furthere there.

Mh, basically what I just wrote: Zettlr is first and foremost aimed at people with less technical knowledge, and while I'm always open to add functionality that software developers might deem useful, this function will always face the limitation that it may not interfere with normal operation of the application in a way that confuses people with less understanding of these concepts. Usability and a good UX are paramount to Zettlr. That being said, I'm always open for new ideas, but such meta discussions are best held on the [forum](https://forum.zettlr.com/)!
