### ISSUE TITLE
Right to left (rtl) languages support

### ISSUE THREAD

**Issue by gotoayman** [Zettlr/Zettlr#950]
Please consider giving support to rtl languages like Arabic and Hebrew in the program

**Comment by nathanlesage** [comment]
Already implemented, coming in 1.7 in two weeks!

**Comment by gotoayman** [comment]
great
Thank you a lot.

**Comment by sajjad-shirazy** [comment]
Thanks, @nathanlesage for the great work. it's awesome.

**Comment by gotoayman** [comment]
RtL in 1.7.1 is not working at all, text always aligned to the left side of the screen!

**Comment by nathanlesage** [comment]
@gotoayman Please update your application to 1.7.5.

**Comment by gotoayman** [comment]
> @gotoayman Please update your application to 1.7.5.

Updated and the problem is the same.
![image](https://user-images.githubusercontent.com/34642444/91888133-72967780-ec94-11ea-90a5-498e2f70bde4.png)

**Comment by sajjad-shirazy** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/8807409/91932281-f5521d80-ecfa-11ea-8fc7-c9418c17da1f.png)

It's 1.7.5

**Comment by gotoayman** [comment]
not working with me. i wonder why!

**Comment by nathanlesage** [comment]
@gotoayman Would you mind checking the Berlin theme? It looks as if you're using the Frankfurt theme; if it works using the Berlin theme, this might indicate a problem with the theme itself.

**Comment by gotoayman** [comment]
i tested all the themes and there is no change. i even uninstalled and installed the program and there is no change. right to left option has no effect on the display screen.
i have the windows 10  with the latest updates. display language is English but Arabic is enabled. 
I wonder if any other user have the same problem.

**Comment by gotoayman** [comment]
just now i changed the editor option to LtR direction and then returned it to LtR and it surprisingly works?!!!!
![image](https://user-images.githubusercontent.com/34642444/92102260-0c6e3980-ede7-11ea-8bd4-09a0b6203ddd.png)

**Comment by gotoayman** [comment]
when exporting RtL pages to any format it switches to LtR. I hope that the program will support the Rtl in exporting as well, not only in the display.

**Comment by nathanlesage** [comment]
> I hope that the program will support the Rtl in exporting as well, not only in the display.

Mh, please feel free to open up issues with regard to this.
