### ISSUE TITLE
List indentations produces large negative indents

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#951]
1. Type "-"
2. Then add "1."
3. Add "2."
4. Keep adding numbers to have "- 1. 2. 3. 4. 5. 6"
5. Observe how the line moves to the left further and further, hiding first characters.

I believe this is caused by #628 — while a useful PR, negative indentation for numbered lists feels weird. I experience this on the Bielefeld theme with "Liberation Sans" font.

_Zettlr 1.7.0 beta 13, Fedora Linux 32_

**Comment by Zverik** [comment]
This is even worse: in numbered lists, you cannot see the second digit.

![numbered_list_indent](https://user-images.githubusercontent.com/766031/85468583-52bc4680-b5b5-11ea-9b25-5a8c8e6c7d25.png)

**Comment by nathanlesage** [comment]
Isn't it magical? You can hide whole texts in the gutter!

(Yes, it's a bug, but I'm fascinated by it to the same degree)

**Comment by nathanlesage** [comment]
So, I _finally_ managed to have a look and the code, and I'm so far pretty satisfied – the code is much shorter now, and as far as I can see it it works pretty well both with monospaced font and variable-width:

![image](https://user-images.githubusercontent.com/17251683/89732315-36ce1080-da4e-11ea-9958-da992d259f6f.png)

Amazingly, it also works with variable-width fonts just as well:

![image](https://user-images.githubusercontent.com/17251683/89732352-7e549c80-da4e-11ea-86f9-2e7b8ee348fc.png)

**Comment by tobiasdiez** [comment]
Nice!

**Comment by Zverik** [comment]
Looks great!
