### ISSUE TITLE
Setting a relative path to CSL-Style file?

### ISSUE THREAD

**Issue by Krande** [Zettlr/Zettlr#952]
Hi,

Is it possible to set the CSL Style filepath relatively in Zettlr (for project level and\or globally)?
I have tried pointing to the path to my CSL file relative to project folder, main work directory or bibtex file, but without luck.  

Unfortunately I was unable to find my question specifically answered in the [documentation](https://docs.zettlr.com/en/academic/citations/#step-3-open-your-library-in-zettlr) nor in any issue raised.

FYI I am using Zettlr v1.6.0.

If it is possible, perhaps a small clarification in the documentation could be useful (especially for those of us new to using Markdown\pandoc for creating technical documentation)? If not, perhaps this is a "low hanging fruit" feature that more people could appreciate? 

In addition to relative local path, maybe supporting url link to CSL files would make sense? (for example: "https://www.zotero.org/styles/ieee")?

The reason for wanting to set a relative path is that I regularly switch between workstations and would love to have a fully "portable" writing setup.

PS! I just recently came across Zettlr and I have to say it is a pure delight to work with! Keep up the great work!

Let me know if you need more info,

Best Regards
Kristoffer

**Comment by Krande** [comment]
Thanks for the quick reply!

I completely agree, it makes only sense for projects.

I think url links are supported based on what I read [here](https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md): 

_"csl or citation-style : Path or URL of a CSL style file."_

No rush, this is not a big issue:)

Best Regards
Kristoffer

**Comment by nathanlesage** [comment]
Looks good!

**Comment by Krande** [comment]
I hope it is okay that I'm giving this a small bump as I think having the option to set a relative path to CSL style (and optionally as a url for that matter) hopefully is a "low hanging fruit" that would provide a significant improvement for us jumping between work stations or sharing technical documentation between colleagues using GIT.

As a side note, I've been using Zettlr for some time now, and the more I use it, the more I enjoy using it. Keep up the good work on this beautifully crafted piece of software!

Best Regards 
Kristoffer

**Comment by nathanlesage** [comment]
> As a side note, I've been using Zettlr for some time now, and the more I use it, the more I enjoy using it. Keep up the good work on this beautifully crafted piece of software!

Thanks!

Concerning relative CSL-files: We could do it relative to the project root, but not globally (because what baseline should we use for it? There's nothing to infer from), but then please open a new issue "Add project-specific CSL-files", as this would then align with the possible custom template on projects!
