### ISSUE TITLE
[BUG] Global search: Multiple occurrences in same line not highlighted

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#955]
## Description
When the global search term appears multiple times inside a line, only the first occurrence is highlighted. (see screenshot below)

## Reproducing
1. Use sample sentence (in one line): _"An apple is an apple."_
2. Global search for _"apple"_
3. Only the first _"apple"_ (of the line) will be highlighted

## Expected behaviour
Highlight all occurrences found inside a line.
In file _local_ search, every occurrence is highlighted as expected.

**Screenshots**
![Bildschirmfoto vom 2020-06-26 22-13-06](https://user-images.githubusercontent.com/18646029/85897255-437a0a80-b7fa-11ea-8e7b-5b5f87901a9e.png)

## Platform
 - OS and version: Linux Mint 19.2
 - Zettlr Version: 1.6, 1.7.0-beta.13
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Requires changes to the search engine

**Comment by nathanlesage** [comment]
This specific issue is no longer relevant to the upcoming 2.0 line.
