### ISSUE TITLE
[ENHANCEMENT] Save File position on closing

### ISSUE THREAD

**Issue by ziegelstein** [Zettlr/Zettlr#957]
## Description
It would be nice for zettlr to save the line position of an file when closed and automatically jump back to the position after reopening zettlr and the file. Especially on large files it can become cumbersome to find the last edited position.

## Proposed Changes
Probably easiest implementation would be some small csv file storing the filename and the line number, updating it on saving a file and loading it on startup to displaying the saved line number.

**Comment by nathanlesage** [comment]
> Probably easiest implementation would be some small ~~csv~~ [JSON] file
