### ISSUE TITLE
Unhandled JavaScript exception EBUSY

### ISSUE THREAD

**Issue by MyGGaN** [Zettlr/Zettlr#960]
## Description
With a few minutes interval, usually when Zettlr is not in focus, this error popup occur:

> **A JavaScript error occurred in the mail process**
> Uncaught Exception:
> Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

The program seem to work even if this error popps up several times a day. It even survives hibernation without loosing data.

## Reproducing
Open Zettlr with a file or directory. Unfocus the app and wait.
I used the installer, have had this issue form start. Though I believe it complained about a *hiber* file at first.
The file from the error message is not present on C:/, nor is it a file I've opened to edit and nor can I find it in the source code.
I've installed all recommended tools to generate a pdf file. But it's the Zettlr app that is associated with the error popup.

## Expected behaviour
I don't understand the root cause, but this exception should be handled in a better way. 

**Screenshots**
![ebusy](https://user-images.githubusercontent.com/420726/86087968-ebab0000-ba94-11ea-881f-672174561081.jpg)

## Platform
 - OS and version: Windows 10 Enterprise
 - Zettlr Version: 1.6.0
 - Screen Resolution: 2x 3840x2160

**Comment by nathanlesage** [comment]
Had a similar bug report earlier this year, but personally, I have no idea why this happens, as Zettlr never accesses any file on `C:\` unless you load your C-drive into the app, which you normally don't do either way. A quick googling showed that apparently it's safe to deactivate the creation of this file, which may mitigate this error message.

I just did a check and I could indeed not find any `lstat` within the codebase that would either query an unknown file or not capture the exception. So, honestly? I have no idea why this is happening. So without any more info on the context of this bug I have nothing to begin searching for this behaviour.

**Comment by MyGGaN** [comment]
I'll reinstall and hope it resolves this issue. If not I'll reopen and hopefully have some more info.
Thanks

**Comment by ZeroBomb** [comment]
I am experiencing the same issue after updating from Zettlr 1.6.0 to 1.7.1 on Windows Education 2H20.  The errors complain about hiberfile.sys, pagefile.sys, and swapfile.sys in that order.

**Comment by ZeroBomb** [comment]
Suspiciously similar error, indicates possible problem with imports if using VScode?

https://stackoverflow.com/questions/61936085/error-from-chokidar-c-error-ebusy-resource-busy-or-locked-lstat-c-dump

**Comment by canpolat** [comment]
As far as I know Zettlr uses chokidar. This issue seems related to or is a duplicate of #823

**Comment by nathanlesage** [comment]
Yes, it's a duplicate so please let's head over there!
