### ISSUE TITLE
Open file with an external editor

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#962]
My usecase is prettystraightforward : I use a French spellcheck called "Antidote" which opens its own editor.

I would like to be able to open the current md or txt file with an external editor (in my case Antidote).

**Comment by nathanlesage** [comment]
Does dragging the file out of the app work (albeit I still have to find a way that you don't have to press `Option` while beginning the drag of the file) in this case? I'm hesitant adding "Open with …" as this might open the door for "Can you make it work with app XYZ???"-requests, which might result in bloat :/

**Comment by ploum** [comment]
I 100% agree with the bloat problem. I was hoping there was a kind of "open with" system command on most OS that would ask the OS to handle the call and basically pass the $path to the OS.

Alternatively, a "show file in file explorer" might do the trick.

If the solution is not trivial (like I thought it was), then it worths investigating if other users share my need.

**Comment by nathanlesage** [comment]
> I 100% agree with the bloat problem. I was hoping there was a kind of "open with" system command on most OS that would ask the OS to handle the call and basically pass the $path to the OS.

Hmm … depending on how that works, what might be possible is to just let the users' decide up to, e.g., 4 spaces to define "Open with …"-commands. I haven't yet had the chance to look into that, feel free to remind me in case I forget

> Alternatively, a "show file in file explorer" might do the trick.

This would be the alternative I see myself, yes!

Let's await Friday, then some days of rest and then I'm sure I'll also be much more open to just pondering such ideas! :)

**Comment by ploum** [comment]
Of course, this was never intended to be urgent ;-)
