### ISSUE TITLE
[ENHANCEMENT / DISCUSSION] Clicking an internal link should perform exact search in search field

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#963]
## Description
As we know, when an internal link is clicked, Zettlr will try to open a file whose name matches exactly the links content, and at the same time also trigger a global search for the link content.

The idea of this search is, as the [docs](https://docs.zettlr.com/en/academic/zkn-method/#internal-linking) say, to find all _backlinks_. Currently, this search is not performed with exact matching, i.e. no quotation marks ("") around the search term. 

This is fine for searching Zettelkasten IDs (e.g. `[[20200630214258]]`) or single word links (e.g. `[[physics]]`). However, when a link contains multiple words, such as `[[This is]]` _(I know, not the most realistic example, but bear with me)_, the search will match any files that contain _all_ search terms. The problem here - in my eyes - is that the search will also include any files that contain the search terms, but not necessarily in the order as given by the link.

However, when I click a link, I expect to find all files which match the link _exactly_. With the example given above, any file containing "this" and "is" would be found, and if you have a lot of files, it is very likely that many of the files will have "this" and "is" spread all over their contents. Yet the point of finding backlinks is to find only those files which have the _exact_ content as the clicked link (either also a link with the same content --> existing _backlink_, or same content but no link --> _unlinked reference_) (in the example above: "This is" or "this is").

## Proposed Changes
When an internal link is clicked, add quotation marks around search terms in the search field.

## Additional Information
I don't know if I'm the only one who prefers it the way I proposed. I recently found myself adding the double-bracket `[[ ]]` links not only to link to specific files, but also to link files through common terms. You can consider these as "more specific" hashtags. Zettlr makes it very convenient to browse these links, simply by clicking them and then going through the search results. Therefore it would be nice if the search was _exact_, so that only files with the _exact_ terms _in-order_ would get found and listed.

I added the DISCUSSION tag as well, since there might be others who view this differently!

**Comment by nathanlesage** [comment]
I'll keep this open; this certainly also feeds into the more general discussion on another rework of the search!
