### ISSUE TITLE
Escaping parentheses in URLs doesn't work

### ISSUE THREAD

**Issue by AlvaroDeMenard** [Zettlr/Zettlr#964]
## Description

When a url contains a closing parenthesis, rendering of the links is screwed up even when the parenthesis is escaped.

## Reproducing

The following should show up as a link with the text "foo" (note escaped closing parenthesis in the url):

`[foo](https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(20\)30082-1/fulltext)`

It actually shows "foo30082-1/fulltext)".

## Expected behaviour

Respect escaped closing parentheses.

**Screenshots**

## Platform
 - OS and version: win10
 - Zettlr Version: 1.6.0
 - Screen Resolution:1080p

**Comment by nathanlesage** [comment]
Fixed in 1.7
