### ISSUE TITLE
HTML export throws TypeError: shell.openItem is not a function

### ISSUE THREAD

**Issue by ohthehugemanatee** [Zettlr/Zettlr#968]
## Description
When I try to export as HTML (and several other "share" menu items), it fails with a status notification `TypeError: shell.openItem is not a function`.

## Reproducing
Create a document, click the share icon and select HTML.

## Expected behaviour
Should export the document as HTML. 

## Platform
 - OS and version: Manjaro latest
 - Zettlr Version: 1.6.0
 - Screen Resolution: 3840x2400 @ 59.993999 Hz

## Additional information
Installed from http://aur.archlinux.org/packages/zettlr

**Comment by nathanlesage** [comment]
Please download 1.7, which'll be released tomorrow, and if the bug persists there, please let me know, or close the issue if it works then! :)
