### ISSUE TITLE
Website contact page has dead link to forum

### ISSUE THREAD

**Issue by foss-** [Zettlr/Zettlr#97]
First: Loving this app, thanks for investing your time and creating it.

https://www.zettlr.com/contact has a link in "please use the discussion board!" which gives a 404.

Would be great to remove the link or correct it so it goes to the actual forum.

**Comment by nathanlesage** [comment]
Oh yes, it's a reminiscence from my first failed attempt at opening up a discussion forum (I think for the time being I'll stick with GitHub and Reddit)

Thanks for reporting it! :)

**Comment by foss-** [comment]
Maybe add links to GitHub issues and the Zettler Reddit page?
