### ISSUE TITLE
[ENHANCMENT] Option to disable 'file matching'?

### ISSUE THREAD

**Issue by Jos512** [Zettlr/Zettlr#971]
## Description
Release 1.7.0-beta added a 'file matching' feature:

> Feature: File matching — when linking files (e.g. [[filename]]) those with a higher match based on used tags appear to the top of the list.

The way matches are ordered, however, doesn't work well for my Zettelkasten. As a result I get irrelevant file names there, which makes adding a link between files more time consuming. (I nearly have to type out the full file name now simply to 'work past' the suggested files.)

## Proposed Changes
If there's a setting to disable 'file matching', people can choose if they want to use this new feature or not.

## Caveats
There are no caveats. File matching can be something that's enabled by default, but possible to turn off. That way people whose Zettelkasten doesn't work well with the matching algorithm can choose. :slightly_smiling_face: 

## Additional information
- I think 1.7 is a big improvement and really appreciate the work put into it. :slightly_smiling_face:

**Comment by nathanlesage** [comment]
I see where you're going to — this is for now merely a concept study, because I already have a much better idea to make this list of "suggested" files more accessible, stay tuned (and remind me in case I forget this :D)

**Comment by Jos512** [comment]
> this is for now merely a concept study, because I already have a much better idea to make this list of "suggested" files more accessible, stay tuned

That's sounds good, thanks! :slightly_smiling_face: 

I also thought after opening the issue that customisation might be better than a turn off option. It seems like the current algorithm uses the intersection of one tag together with file modification times. 

An option that would allow how many tags are compared might be better. People that have a Zettelkasten around one main topic probably can do with one related tag. Others that have Zettelkasten about wildly different topics probably need more tags for useful relatedness.

**Comment by nathanlesage** [comment]
:D Let's see to get some of the new bugs sorted out first! :)
