### ISSUE TITLE
Application does not start

### ISSUE THREAD

**Issue by agscala** [Zettlr/Zettlr#972]
## Description

Running zettlr after installing or launching from the start menu fails.

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: Win 10 Home, 10.0.19640 Build 19640 (Insider Fast Ring)
 - Zettlr Version: 1.7.0
 - Screen Resolution: 1920x1200

## Additional information

If there's a way to supply debug logs, let me know and I'll do my best.

**Comment by nathanlesage** [comment]
Hey!

> If there's a way to supply debug logs, let me know and I'll do my best.

Logs are located in the Local-folder, but if the app fails to start, I doubt there are logs to show — does nothing work at all? Even multiple attempts at starting?

**Comment by agscala** [comment]
I was able to launch the application with the suggestion mentioned in #984 (running in win8 compatibility mode)
