### ISSUE TITLE
[ENHANCEMENT] Open note in new tab

### ISSUE THREAD

**Issue by nistude** [Zettlr/Zettlr#973]
## Description
I want to be able to open a bunch of notes in their own tab, regardless of transiency.

## Proposed Changes
I propose to use `middle button click` for that, similar to how it's handled in web browsers. To stay consistent, it could also be `CTRL + middle button click`.

## Caveats
None that I am aware of.

**Comment by nathanlesage** [comment]
Has already been asked on the forum (?), and is an important addition!
