### ISSUE TITLE
[ENHANCEMENT] Tabbing behavior consistency with other apps

### ISSUE THREAD

**Issue by nistude** [Zettlr/Zettlr#974]
## Description
I would love to see Zettlr tabbing behavior be consistent with other tab-aware apps like web browsers.

## Proposed Changes
Change or implement the following keyboard shortcuts:
- replace `CTRL + Tab / CTRL + Shift + Tab` with `CTRL + PageUp / PageDown`
- add `CTRL + Shift + PageUp / PageDown` to move the active tab around

## Caveats
This would break current shortcuts for navigating tabs and people would have to change their behavior. However, as the suggested behavior is what is implemented in mainstream applications anyways, I believe migration would be pretty smooth.

**Comment by nathanlesage** [comment]
> replace CTRL + Tab / CTRL + Shift + Tab with CTRL + PageUp / PageDown

Is this REALLY a thing? Because it makes so much no sense for me (and I have a keyboard that features PageUp/PageDown). If so, probably on Windows only, and then we'd need to wait for the keyboard shortcut customizer, I suppose …

**Comment by nistude** [comment]
@nathanlesage I am on Linux and just reviewed the official keyboard shortcuts of [Chrome](https://support.google.com/chrome/answer/157179?hl=en), [Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) and [VS Code](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference). All three applications implement **both** kinds of shortcuts (which I wasn't aware of and which are not documented in all cases). While VS Code implements them slightly differently, the browsers seem to behave identical in both cases.

After these findings I would change the request to copying those applications and **adding** `CTRL + PgUp / PgDn` as additional shortcuts for tab switching.

My personal motivation is the placement of keys on the keyboard. I have only used ThinkPads in the last couple of years, where the `PgUp / PgDn` keys are placed together with arrow keys in the lower right hand corner:
```
PgUp |  Up  | PgDn
Left | Down | Right
```
With this layout my fingers can easily find the keys and it's a two-hand gesture. I am not sure if it's my being not used to finding `CTRL + Tab` but it feels much less fluent for heavy use.

**Comment by nathanlesage** [comment]
Puuuuuh … both types of shortcuts. Hmm … Let's say the following: There's currently a PR in the making (#927) that aims to make all shortcuts customizable, including the tabbing behavior, so while `Ctrl+Tab` is more "sensible" (if you can even say that in this context), because normally `PgUp` and `PgDn` are not located in the way ThinkPads handle them, and I now can clearly see why you like this approach.

Therefore, I'd like to propose the following:

1. Close this issue
2. Wait for the PR to be merged
3. Customize the shortcuts to your liking!
