### ISSUE TITLE
Zettlr hangs with one electron thread consuming 100% CPU

### ISSUE THREAD

**Issue by akstrfn** [Zettlr/Zettlr#975]
## Description

After an upgrade to 1.7 zettlr would lock entirely after trying to open one of my files. Whats even worse it would block completely (except the top bar) after restarting so I needed to clean the `./config/zettlr/` to start it again. I've traced the problem and it seems to be related to parsing. When blocked one thread is 100% used by electron but do note that top bar works which could indicate which thread gets crazy.

## Reproducing

Have a file that contains something like: `[[link](https://url.com)` (adding a bracket at the end should also break zettlr)

Another way reproduce the the bug live is to have `[link](https://url.com)` and try to add `[` in front i.e.  `[[link](https://url.com)`

## Expected behaviour

Zettlr should continue to work.

## Platform
 - OS and version: ArchLinux
 - Zettlr Version: 1.7 but git version (commit https://github.com/Zettlr/Zettlr/commit/e4ccee45dec452643c1614e681301a02f333dfdf)

## Additional information
This version of zettrl is compiled on the machine but I've tested AppImage as well and the bug is there. Btw AppImage download from the zettlr.com does not work.

**Comment by Jos512** [comment]
Since this issue happens when working with links, it looks to me that it's related to [[BUG] Zettlr freezes with 100% CPU when adding a [[link]]](https://github.com/Zettlr/Zettlr/issues/967). Can you take a look at that issue to see what you experience is the same?

**Comment by akstrfn** [comment]
Seems to be the same issue (should have read issues before posting this...) it also blocks on '[[' for me and interestingly I also use English/German as #956 but changing locale does not seem to have any effect.

**Comment by nathanlesage** [comment]
Alright, so this might have to do with the parser, as it expects a link to end on the same line. I might have an idea of where to look!

**Comment by nathanlesage** [comment]
So, y'all, we found the bug, please head over to #967 until it's resolved!
