### ISSUE TITLE
[ENHANCEMENT] copy (yank) to system clipboard in vim mode

### ISSUE THREAD

**Issue by ianhi** [Zettlr/Zettlr#977]
## Description
I'd like to be able to yank to the system clipboard in vim mode. Currently `"+y` will not populate the system clipboard. Ideally I'd also be able to do the equivalent of `:set unnamedplus` to have yanking to the system clipboard be the default. Settings for this could be included in the same place as the settings in https://github.com/Zettlr/Zettlr/issues/884.

## Proposed Changes
I implemented this for the codemirror in jupyterlab https://github.com/ianhi/jupyterlab_vim-system-clipboard-support. The basic approach is to copy the `yank` function from codemirror add in lines to fill the system clipboard: https://github.com/ianhi/jupyterlab_vim-system-clipboard-support/blob/78f0dba8f447e092e9cf97016e96eadc92e50e63/src/yank.ts#L33-L39 and then replace the default yank function like so: https://github.com/ianhi/jupyterlab_vim-system-clipboard-support/blob/78f0dba8f447e092e9cf97016e96eadc92e50e63/src/index.ts#L20

## Caveats

I didn't implement paste from system clipboard in jupyterlab as firefox does not allow the `readText` method, so to support paste there would need to be some work also reimplementing paste (some info about this here https://github.com/ianhi/jupyterlab_vim-system-clipboard-support/issues/2). I also am not sure if it would be easy to paste images using this.

## Additional Information
Happy to help with codemirror stuff if anyone wants to do this.

**Comment by nathanlesage** [comment]
… what does yanking stand for, in this context?

**Comment by ianhi** [comment]
Ah yes I can see that being unclear in retrospect, sorry about that. Yank is the terminology vim uses for copy 

from https://vim.fandom.com/wiki/Copy,_cut_and_paste
>y stands for yank in Vim, which in other editors is usually called copy 


the `"` followed by a character specifies the [register](https://www.brianstorti.com/vim-registers/) and the `+` and `*` are the registers representing the system clipboard. So you can understand the command `"+y` to mean: copy the current selection to the system clipboard while also filling the vim `+` register. (I think in proper vim there is not a distinction but in codemirror vim these really are two separate acts). Currently codemirror vim mode only does the latter step, filling the internal register, but does not populate the system clipboard.

Should I change the title? perhaps to `Copy to system clipboard in vim mode`?

**Comment by ianhi** [comment]
Notably unless you override the `ctrl-C` in the codemirror `extra-keys` then you also cannot copy to system clipboard with ctrl-C as this is a command that is approximately equivalent to escape ([ref](https://stackoverflow.com/questions/5030164/whats-the-difference-between-ctrlc-and-ctrl)). I wrote about this a bit here: https://github.com/jupyterlab/jupyterlab/issues/7388#issuecomment-609546197 but the upshot is that unless using the proposed fixes for yank or disabling the `crtl-C` behavior of vim then there is no way to copy text outside of Zettlr using the only the keyboard.

**disabling crtl-C**
You can do this by setting:     `extraKeys['Ctrl-C'] = false;` followed by `editor.setOption('extraKeys', extraKeys);` (see https://github.com/jwkvam/jupyterlab-vim/blob/d3ef1ed7aaebfda8cb7582cbd54ef730c4815640/src/index.ts#L68-L70).

Happily ctrl-V still works.

**Comment by nathanlesage** [comment]
> You can do this by setting: extraKeys['Ctrl-C'] = false; followed by editor.setOption('extraKeys', extraKeys);

I think this is highly specific, isn't it? Plus, Zettlr doesn't set this extrakey in the keymap generator 🧐

**Comment by ianhi** [comment]
How do you mean by "highly specific"? 

> Zettlr doesn't set this extrakey in the keymap generator

I believe that this extraKey is set to be a vim command - thus disabling the standard copy behavior - when you do `_cm.setOption('keymap', 'vim')`.  So what I was suggesting with the extrakeys is basically to undo the setting being done by `vim.js` disable this. 
FWIW this is solution to this issue taken by jupyterlab_vim and the vscode vim extension https://github.com/VSCodeVim/Vim/issues/1437
My guess is that many vim keybindings users are more likely to want ctrl-C to be paste rather than another version of escape (though I have no real evidence for that claim). Also in normal vim mode ctrl-C is a stronger version of escape but in codemirror vim I believe it interpreted as an alias to escape and so no longer provides the extra functionality. 

Although enabling the vim copying with `y` to also fill the clipboard is probably a more "correct" solution - if you would be open to PR with the modifications to yank I can do that.

(Thanks for thinking about vim keybinds even if you don't use them)

**Comment by nathanlesage** [comment]
Aaaah, okay, I see what you mean. What I meant with "highly specific" was that the plugin of yours was made for jupyter, and hence I thought that this might have specific key bindings, but yeah, the whole GUI in the local web server is implemented in JavaScript — haven't fully thought this through!

Concerning this, however, I'd suggest closely tying efforts to implement this with the #927 PR, as I am sure there'd be an option for this as well!
