### ISSUE TITLE
Tutorial French translation

### ISSUE THREAD

**Issue by framatophe** [Zettlr/Zettlr#978]
Hi !

Here is a proposal for a translation of the small tutorial in french. It corresponds to the folder here : https://github.com/Zettlr/Zettlr/tree/develop/source/main/assets/tutorial/en

I know how to use git but only on a basic level. I'm not  able to propose requests correctly. So I propose you to download the zip file below.  Hoping it will be useful for you.

The file will be available only 45 days : https://covid19.framadrop.org/lufi/r/_EK94rxS5D#OoEkaEReBqhTZdFEYzkrmF+bSUnJXOQgZ6/ntMKhnqI=

**Comment by nathanlesage** [comment]
Hey, thank you very much for the translation!

Albeit, to get it right, you'd need to open a PR. I know that GitHub can be daunting sometime! Here's what I would like to suggest:

1. Install `git` on your computer
2. Fork this repository
2. `Clone` your fork of this repository
3. Make your changes (i.e. copying the `en`-folder to `fr`) and translate everything
4. Commit the changes
5. Start a PR on this repository

If you made any mistakes, don't worry, we will get them sorted out! :) 

Here's a tutorial I just found on that: https://gist.github.com/Chaser324/ce0505fbed06b947d962

If you have any questions, please comment here on this issue! I will see these comments and reply!
