### ISSUE TITLE
Undo breaks checkbox rendering

### ISSUE THREAD

**Issue by tanepiper** [Zettlr/Zettlr#979]
When trying out the interactive demo, I used Cmd + Z to undo something I had tried, and going further back it shows the following behaviour:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/376930/86488477-61e38700-bd61-11ea-91e3-a44758b94dd9.gif)

1. Check the boxes and then uncheck then - work fine
2. Check the boxes, click off and then undo - the boxes disappear - they reappear on redo.

## Platform
 - OS and version: OSX 10.15.5, Macbook Pro 15" 2019
 - Zettlr Version: 1.7 
 - Screen Resolution: 2880 x 1880

**Comment by nathanlesage** [comment]
That is interesting — I'll have a look over the weekend!
