### ISSUE TITLE
[BUG] Process hangs when trying to nest hyperlinks

### ISSUE THREAD

**Issue by seanchristians** [Zettlr/Zettlr#980]
## Description
Zettlr process becomes unresponsive when attempting to create a nested markdown hyperlink.

## Reproducing
1. Open Zettlr
1. Make a markdown hyperlink: `[Hello, world!](./hello.txt)`
1. Attempt to add a `[` before the above text

## Expected behaviour
Escape all data in hyperlink title text. A link inside of a link is not necessary to parse.

**Screenshots**

## Platform
 - OS and version: Ubuntu 20.04 LTS 64 bit
 - Zettlr Version: Zettlr-1.7.0-x86_64.AppImage
 - Screen Resolution: 1920x1080
 - Graphics: Mesa Intel® UHD Graphics (CML GT2)
 - Desktop: GNOME 3.36.2
 - Windowing System: X11

## Additional information
The zettlr process hangs and must be killed, however only a SIGTERM is required. When the process recieves the signal, it opens an alert asking the user if they would like to save their changes. This alert does accept user input. The program succesfully exists.

While the program is unresponsive, the cursor does continue to blink. The mouse cursor switches to text-input style everywhere in the window.

By unresponsive, I mean: the program stops accepting input from anywhere. Arrows keys do not work, clicking the mouse in a different location does not move the cursor, input from the keyboard does not write any text to the screen, and scrolling the mouse wheel and the trackpad do nothing. The navigation bar: `File Edit View Window Help` does work.

Opening a document with nested hyperlinks does not kill the program. That document can still be edited, until a user decides to touch one of those links.

**Comment by kyaso** [comment]
Related: #956, #967, #975

**Comment by nathanlesage** [comment]
Alright, a lot of issues, please all of you, head over to #967; going to close the rest so that we can focus the discussion!
