### ISSUE TITLE
[ENHANCEMENT] Hyperlinked images do not render as images

### ISSUE THREAD

**Issue by seanchristians** [Zettlr/Zettlr#981]
## Description
Markdown images in `![]()` format do not render when wrapped in another hyperlink

## Proposed Changes
Badges, like from [shields.io](https://shields.io/), with links to external resources would render properly.

`[![License](https://img.shields.io/github/license/zettlr/zettlr)](https://github.com/zettlr/zettlr/blob/master/LICENSE)`

currently renders in Zettlr as: `![License](https://github.com/zettlr/zettlr/blob/master/LICENSE)`
It should render as  [![License](https://img.shields.io/github/license/zettlr/zettlr)](https://github.com/zettlr/zettlr/blob/master/LICENSE)
Notice that this badge is hyperlinked to Zettlr's license and clicking it will bring you there.

## Caveats
This will affect issue #980: All title text should be escaped **unless it is an image**. All alt-text in images should probably be escaped, I don't know how much functionality other markdown renderers such as GitHub give to image alt-text. 

## Additional Information

**Comment by nathanlesage** [comment]
Known & I was too lazy+busy to implement it to 1.7, you're right!

**Comment by elkrause** [comment]
It would be nice if you could implement it since it seems to be part of the markdown standard. My Notebooks App on iOS also uses this syntax, e.g.

[![](NBImages/20200726-191712.jpeg)](NBImages/20200726-191712.jpeg)

It is not shown within Zettlr.

**Comment by nathanlesage** [comment]
Found the error, but it requires a little bit more work, as the current RegEx doesn't work in this case …

**Comment by nathanlesage** [comment]
I got it working somehow, but I think I created a monster along the way …
