### ISSUE TITLE
Windows OS warns 1.7.0 installer is harmful

### ISSUE THREAD

**Issue by SunnyRaj** [Zettlr/Zettlr#983]
## Description
Microsoft Defender SmartScreen is tagging the `Zettlr-1.7.0.exe` installer as potentially harmful.

## Reproducing
Download Zettlr-1.7.0.exe from https://www.zettlr.com/download/win32

## Expected behaviour
Windows should not tag this as harmful as the release notes indicate `Windows-installers are finally code-signed, so no more warnings from your operating system`

**Screenshots**

![image](https://user-images.githubusercontent.com/1192484/86490746-4f475e80-bd1d-11ea-956b-ed53fffb719c.png)

![image](https://user-images.githubusercontent.com/1192484/86490863-c7ae1f80-bd1d-11ea-96b3-8768e995493b.png)

## Platform
 - OS and version: Windows 10 Enterprise build 18362.900
 - Zettlr Version: 1.7.0
 - Screen Resolution: 3840 x 2160

**Comment by djsavvy** [comment]
I can confirm that this issue is reproducible.

**Comment by nathanlesage** [comment]
This'll apparently go away after some installations. Because even though Windows installers are now signed by me, it apparently needs some installations to build up "trust"

**Comment by ajm896** [comment]
I second what Nathan says, once his "signature" has been seen enough by Microsoft and is seen not to be an issue. The warnings should go away in the future.

**Comment by nathanlesage** [comment]
> I second what Nathan says, once his "signature" has been seen enough by Microsoft and is seen not to be an issue. The warnings should go away in the future.

Let's hope Microsoft didn't lie to us with this …!

**Comment by krsche** [comment]
Hey, I'm a first time user of Zettlr. Looks very promising, but the Windows Defender notice is a bummer... What about offering a (portable) .zip file with all the depencies included, in addition to the installer?
The Defender notice I got:
![image](https://user-images.githubusercontent.com/5144985/99024877-d5936d00-2567-11eb-8913-eb48229312d0.png)

**Comment by nathanlesage** [comment]
> What about offering a (portable) .zip

That would require a few amendments to the code base, but I'm pondering the thought. But at least I'm happy to see that by now it automatically gives you the "Run anyway" option without users having to click on "More information" first – this means that the binary is slowly gaining trust within the Windows eco system. I'm sure a few more releases will do it until this works without a warning!

**Comment by krsche** [comment]
@nathanlesage Sorry to tell you, but it only gave me the option to run anyway *after* clicking on more info. I just happened to take the screenshot then, since I was curious 😬 sorry
