### ISSUE TITLE
[BUG] Zettlr 1.7.0 needs to be run in Windows 8 compatibility mode

### ISSUE THREAD

**Issue by djsavvy** [Zettlr/Zettlr#984]
I can't run Zettlr 1.7.0 on Windows 10 Build 20161 --- the process just exits immediately. If I run the executable from Powershell, there's no output. 

## Reproducing
I installed Zettlr 1.7.0 from the website and tried to open it. 

## Expected behaviour
It should run without needing to tweak compatibility settings. 

**Screenshots**

## Platform
 - OS and version: Windows 10 Build 20161
 - Zettlr Version: 1.7.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
This almost sounds like a bug in Electron — can anyone confirm?

**Comment by StoltHD** [comment]
Its the same problem here, on windows 10 Enterprise N build 19645 (insider version), 

Its the same problem that has been reported before with distributed com.

My Windows version is Norwegian, so the error message are of no use, but maybe someone with an English Windows 10 with the problem could provide the Event Log Error message ( Windows Logs - System)

**Comment by nathanlesage** [comment]
> Fixed: On some Windows machines, especially Windows Insider builds, Electron would crash silently during startup

Found this in the Electron changelog for the `9.0.4` release. Going to bump that version now and release a patch, so if I read this correctly, the problem has been fixed by Electron already. Coming in a few hours.

**Comment by StoltHD** [comment]
Just want to cenfirm that Zettlr 1.7.1 runs without setting compatibility mode on Windows 10 Enterprise N 19645 (Insider) ...
