### ISSUE TITLE
Idle performance

### ISSUE THREAD

**Issue by onemenzel** [Zettlr/Zettlr#986]
## Description

Zettlr and its helper processes consistantly take around 11-15% CPU when being idle.

## Reproducing

Just start Zettlr.

## Expected behaviour

Being idle, Zettlr should optimally use 0-1% CPU.

## Platform
 - OS and version: macOS 10.14 Mojave
 - Zettlr Version: 1.7.0
 - Screen Resolution: 2304 x 1440

**Comment by nathanlesage** [comment]
Relevant meme:

![image](https://user-images.githubusercontent.com/17251683/86519856-320ab100-be3f-11ea-8f77-a0f1ada4592f.png)

Also an [interesting read on that thing](https://www.wired.com/2014/10/google-chrome-helper/)

However, I fear this is nothing that can be solved by one issue/PR, but needs to be addressed over time. In the last year, Zettlr has grown considerably, and while it has been praised as an extremely lightweight Electron app in the past, tons of features have made this false by now. We need to take a look at all the features, identify bottlenecks and gradually improve the app again. This will always be on my mind and will guide my endeavours, but this as an issue is unfortunately not helpful — however, if you happen to have some spare time, I warmly welcome any PRs that increase performance!

**Comment by onemenzel** [comment]
The interesting thing is though that, when I pulled the repo and started Zettlr from there, this problem wasn't present. The Main process needed 0.1% CPU, Renderer and Helper together still took 4% but that's better than the 11 % of the official 1.7.0 build. I tried this with 1.7.0 and the deleop branch and both revealed the same results.

I initially did that because I wanted to run a profiler on Zettlr while being idle.

I have to wait a litte until I can try out the official 1.7.1 build because it is not yet on homebrew Cask.

**Comment by nathanlesage** [comment]
Hmm, maybe this has to do something with the currently somewhat shaky integration with the build process — Zettlr's codebase is almost three years old by now, and some things have just stayed since the beginning (such as the two-package-structure). Nevertheless, someone already tries to tackle the installer being too big and generally some stuff:

See this PR: #938
