### ISSUE TITLE
Tab key should increase indentation level regardless of cursor position within line

### ISSUE THREAD

**Issue by digitalsignalperson** [Zettlr/Zettlr#987]
## Description
Currently shift+tab decreases indentation level regardless of cursor position within a line belonging to a list.
The opposite is not true. Pressing tab at the end or the middle of a line results in insertion of whitespace. This seems to be editor dependent. E.g. MS Word is like the current Zettlr behaviour, versus Evernote is like the requested behaviour.

It would be nice if there was an option to choose the behaviour. When working a lot with outlining and bullet lists, making it easier to indent/dedent with tab/shift-tab is nice.

## Proposed Changes
Option to choose how list indentation functions with the "Tab" key.
Alternative could be other keybindings like Alt+Left-arrow / Alt+Right-arrow

## Caveats
If there is an option, no caveat. Versus adopting the behaviour for all times, caveat if people use tab characters as whitespace within list item lines. I'm not sure if anyone does and I don't have enough info to be sure.

## Additional Information
Tested with Zettlr 1.7.0

**Comment by nathanlesage** [comment]
I'm pretty sure this issue is already somewhere in the issue tracker — in case you find it, make sure to notify us!

**Comment by digitalsignalperson** [comment]
I searched around and couldn't find this specifcially (keywords: tab, indentation). Found this, which is the opposite (dealing with shift+tab behaiour): https://github.com/Zettlr/Zettlr/issues/278

**Comment by nathanlesage** [comment]
Oh, yes! I might have mentioned this in a comment, and the GitHub search is not really good at this. But however, this is already on the bucket list, because I don't like that myself!
