### ISSUE TITLE
Unable to start Zettlr after upgraded to version 1.1.0

### ISSUE THREAD

**Issue by ArthurZ** [Zettlr/Zettlr#99]
## Reproducing
Start the program

## Expected behaviour
Program starts

**Screenshots**
![image](https://user-images.githubusercontent.com/701808/52544891-b0197400-2d81-11e9-9c47-eead3b4f7d6e.png)

## Platform
 - OS: [e.g. iOS] Win 10
 - OS Version [e.g. 11] Home
 - Zettlr Version [e.g. 0.15] 1.1.0
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information
The older version worked, tried to un-install and re-install with no effect

**Comment by nathanlesage** [comment]
There was indeed a bug in the first installer that I've uploaded, but thanks to the quick people here on GitHub, it has been fixed within two hours. It will work if you re-download the installer from the GitHub releases page (I just replaced the binaries)!

**Comment by ArthurZ** [comment]
Hmm, IDK what gives, I installed the new binary, but then no error and the UI does not come up.
Yet I get three (1) Zettler processes running in one hop:
![image](https://user-images.githubusercontent.com/701808/52603629-a6e9df00-2e35-11e9-9dc5-d7fbea19790e.png)

**Comment by nathanlesage** [comment]
Huh, that is strange! Let’s give it a last try: maybe Electron produced a hiccup during the usage of my malicious installer. Would you mind uninstalling the app once more and then removing the complete zettlr data directory at `C:\Users\<your-user-name>\AppData\Zettlr`? (Make sure to backup the `stats.json` and the `tags.json` files to not lose that data!)

Then uninstall and do a clean install. If the error persists even this method, then there’s sometging more severe happening

**Comment by ArthurZ** [comment]
Thank you for not giving up. I hope the installer is **not** malicious :-)
There was no such directory you indicated, but these files were found in `C:\Users\<me>\AppData\Roaming\Zettlr` which I deleted. 
Long story short, that helped 👍

**Comment by nathanlesage** [comment]
No no, just "malicious" in the sense that it did not what it should :D (which was proven by the fact that it worked after you deleted these files)

Additionally, thank you for the information, I'll update the docs to indicate that `Roaming` is now the directory where the stuff resides!
