### ISSUE TITLE
[FEATURE] Have a "copy to clipboard" link next to code blocks

### ISSUE THREAD

**Issue by smetj** [Zettlr/Zettlr#995]
## Description
Next to a rendered code block it would be nice to have a "copy-to-clipboard" link which copies the content of the code-block to the clipboard.

## Proposed Changes
Add functionality to the markdown renderer to detect a code-block and automatically display a copy-to-clipboard icon in the top right corner of the rendered code block. 

## Caveats
Make sure to (optionally) strip off the last new-line of the code-block. If not it's automatically executed when pasting on a terminal or something like a repl, which might not be desired. 

## Additional Information
https://squidfunk.github.io/mkdocs-material/getting-started/ has an example of this. If  you hoover over the rendered code-block a 'copy-to-clipboard' icon appears in its right upper corner.  It does however the mistake of adding a newline at the end which executes it when pasting in a terminal which is not desired I'd say.

**Comment by nathanlesage** [comment]
That's a cool idea!

**Comment by nathanlesage** [comment]
Closing in favor of https://github.com/Zettlr/Zettlr/issues/2375, will be implemented by a currently opened PR
