### ISSUE TITLE
Hide the tab bar when only one tab is used

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#998]
When only one tab is used, the tab bar feels like wasted space (on my small screen) and quite distracting (perhaps is because of the grey from the Berlin inverted theme).

I was wondering if it would make sense to simply hide the tab bar when only one tab is opened. I remember it was the case for browsers and lot of tabbed interfaces.

**Comment by nathanlesage** [comment]
> (on my small screen)

So, [the solution you need is this](https://d13ezvd6yrslxm.cloudfront.net/wp/wp-content/images/Biggest-IMAX-Screen-700x321.jpg). Hah!

Just kidding, it's a good idea, yes.

**Comment by ploum** [comment]
By the way, you learned the hard way one big open source lesson: never plan holidays after a release ;-)

**Comment by nathanlesage** [comment]
Yeah, you're right, BUT: I knew that this avalanche of issues would come, and holidays is the only time where I can fully focus on this, because it's really hard switching from research to Open Source development during my day-to-day-work!
