### ISSUE TITLE
[BUG] Toggling "Night mode" breaks "Distraction free mode" status

### ISSUE THREAD

**Issue by nvalis** [Zettlr/Zettlr#999]
## Description

When toggling "Night mode" (NM) while "Distraction free mode" (DFM) is enabled the status of DFM is unlinked/inverted to the mode the editor view is actually in.

## Reproducing

1. enable DFM
2. toggle NM

&rarr; DFM is disabled in the menu while being enabled in the editor view

## Expected behaviour

Toggling NM should not affect the state of the menu DFM status, just enable or disable NM.

## Platform
 - OS and version: Manjaro Linux
 - Zettlr Version: 1.7.0
 - Screen Resolution: independent

**Comment by nathanlesage** [comment]
Is this an issue in the 1.8 alphas?

**Comment by nathanlesage** [comment]
Reason: The distraction free mode (as well as typewriter mode) are not bount to configuration parameters; the app will always start with them being off, but the menu rebuilds itself every time some configuration changes, and then presets the checked status with "not checked". There's currently no mechanism to prevent this, but as it's purely cosmetic, we'll leave it like that for now.
